### ISSUE TITLE
WARNING: Chromosome 17 not found in annotation sources or synonyms on line 167982

### ISSUE THREAD

**Issue by yongfeng-zhou** [Ensembl/ensembl-vep#10]
Hello,

I followed the manual and did the following steps:

grep -v "#" data.gff | sort -k1,1 -k4,4n -k5,5n | bgzip -c > data.gff.gz
tabix -p gff data.gff.gz
perl vep.pl -i input.vcf -gff data.gff.gz -fasta genome.fa.gz

I got a long list of warnings like the following:

WARNING: Chromosome 11 not found in annotation sources or synonyms on line 591383

WARNING: Chromosome 11 not found in annotation sources or synonyms on line 591384

WARNING: Chromosome 11 not found in annotation sources or synonyms on line 591385

WARNING: Chromosome 11 not found in annotation sources or synonyms on line 591386

WARNING: Chromosome 11 not found in annotation sources or synonyms on line 591387

WARNING: Chromosome 11 not found in annotation sources or synonyms on line 591388

WARNING: Chromosome 11 not found in annotation sources or synonyms on line 591389

WARNING: Chromosome 11 not found in annotation sources or synonyms on line 591390

Did I do something wrong? I used a gff3 annotation file. 

Thanking you!

**Comment by willmclaren** [comment]
My guess is that the chromosome names are not the same between your GFF, VCF and possibly FASTA.

The code should be able to cope if the chromosome names differ by the prefix "chr" (e.g. chr8 or 8). If, however, your GFF perhaps uses accessions for chromosome names (e.g. NC_000008.11 for human chromosome 8) and the VCF uses e.g. chr8, then you would need to supply a synonyms file mapping these with `--synonyms [file]`.

Synonym files for each species are available in the relevant cache file; if you have the human 87 GRCh38 cache file, for example, the synonym file can be found as `~/.vep/homo_sapiens/87_GRCh38/chr_synonyms.txt`

**Comment by willmclaren** [comment]
No further comment so closing...

**Comment by zillurbmb51** [comment]
Hello; I am having the same problem here. I did not use fast or gff, rather than,  I ran the vep as follows:
`./vep -i /Volumes/Macintosh\ HD2/data/UPR_CANCER_2/snpcall/combined.n2.vcf.Q40d20.vcf -o /Volumes/Macintosh\ HD2/data/UPR_CANCER_2/snpcall/combined.n2.vcf.Q40d20.vcf.vep.txt -offline --assembly GRCh38`
And getting the following error.
```
WARNING: Chromosome chr1 not found in annotation sources or synonyms on line 1
WARNING: Chromosome chr10 not found in annotation sources or synonyms on line 63
WARNING: Chromosome chr11 not found in annotation sources or synonyms on line 81
WARNING: Chromosome chr12 not found in annotation sources or synonyms on line 113
WARNING: Chromosome chr13 not found in annotation sources or synonyms on line 124
WARNING: Chromosome chr14 not found in annotation sources or synonyms on line 138
WARNING: Chromosome chr15 not found in annotation sources or synonyms on line 155
WARNING: Chromosome chr16 not found in annotation sources or synonyms on line 175
WARNING: Chromosome chr17 not found in annotation sources or synonyms on line 195
WARNING: Chromosome chr18 not found in annotation sources or synonyms on line 216
WARNING: Chromosome chr19 not found in annotation sources or synonyms on line 240
WARNING: Chromosome chr2 not found in annotation sources or synonyms on line 266
WARNING: Chromosome chr20 not found in annotation sources or synonyms on line 322
WARNING: Chromosome chr21 not found in annotation sources or synonyms on line 330
WARNING: Chromosome chr22 not found in annotation sources or synonyms on line 338
WARNING: Chromosome chr3 not found in annotation sources or synonyms on line 359
WARNING: Chromosome chr4 not found in annotation sources or synonyms on line 381
WARNING: Chromosome chr5 not found in annotation sources or synonyms on line 420
WARNING: Chromosome chr6 not found in annotation sources or synonyms on line 460
WARNING: Chromosome chr7 not found in annotation sources or synonyms on line 478
WARNING: Chromosome chr8 not found in annotation sources or synonyms on line 507
WARNING: Chromosome chr9 not found in annotation sources or synonyms on line 523
WARNING: Chromosome chrX not found in annotation sources or synonyms on line 545
```
And finally got no result. Any help? Best, Zillur

**Comment by at7** [comment]
Hi @zillurbmb51,
could you please share one of your input lines? Which cache files did you install?
Thanks,
Anja

**Comment by zillurbmb51** [comment]
Thank you Anja. I do not remember which cache files I installed. Is there any way to find it out? Also what did you mean by input lines? Best, Zillur

**Comment by at7** [comment]
I just noticed that you have to specify that you want to use the cache files with --cache. The cache files are installed by default under $ENV{HOME}.'/.vep. By input lines I mean some of your input variants which you want to annotate with VEP from  /Volumes/Macintosh\ HD2/data/UPR_CANCER_2/snpcall/combined.n2.vcf.Q40d20.vcf.

**Comment by zillurbmb51** [comment]
Thank you Anja, Here is the ./vep directory in my home. Among these which one is the cache file?

> (base) rcmi-29:snpcall mzillur$ ls /Users/mzillur/.vep/
> Plugins			homo_sapiens		homo_sapiens_refseq
> (base) rcmi-29:snpcall mzillur$ ls /Users/mzillur/.vep/homo_sapiens/
> 97_GRCh37	97_GRCh38
> (base) rcmi-29:snpcall mzillur$ ls /Users/mzillur/.vep/homo_sapiens_refseq/
> 97_GRCh37
> (base) rcmi-29:snpcall mzillur$ ls /Users/mzillur/.vep/Plugins/
> AncestralAllele.pm	CSN.pm			Conservation.pm		ExAC.pm			G2P.pm			Gwava.pm		LoF.pm			MPC.pm			NearestGene.pm		REVEL.pm		TSSDistance.pm		miRNA.pm
> Blosum62.pm		Carol.pm		Downstream.pm		ExACpLI.pm		GO.pm			LD.pm			LoFtool.pm		MTR.pm			Phenotypes.pm		SameCodon.pm		dbNSFP.pm		plugin_config.txt
> CADD.pm			Condel.pm		Draw.pm			FATHMM_MKL.pm		GeneSplicer.pm		LOVD.pm			LocalID.pm		MaxEntScan.pm		ProteinSeqs.pm		SpliceRegion.pm		dbscSNV.pm
> (base) rcmi-29:snpcall mzillur$ ls /Users/mzillur/.vep/homo_sapiens/97_GRCh38/
> Homo_sapiens.GRCh38.dna.toplevel.fa.gz
Attached is my vcf file I want to annotate. Best, Zillur
[combined.n2.vcf.Q30d15.vcf.txt](https://github.com/Ensembl/ensembl-vep/files/3457251/combined.n2.vcf.Q30d15.vcf.txt)

**Comment by at7** [comment]
Hi @zillurbmb51,
thank you for sending me your input file. The cache files which you need for annotating your input file are stored under /Users/mzillur/.vep/homo_sapiens/97_GRCh38. I didn't have any problems annotating your input file with the 97_GRCh38 cache files. Could you please check if you have any files in the  /Users/mzillur/.vep/homo_sapiens/97_GRCh38/ directory? Could you also please check your output file's header? There should be a line near the top starting with: ## Using cache in. Can you please let me know what it says in your output file (/Volumes/Macintosh\ HD2/data/UPR_CANCER_2/snpcall/combined.n2.vcf.Q40d20.vcf.vep.txt)?

Thank you,
Anja

**Comment by zillurbmb51** [comment]
Thank you very much. In  /Users/mzillur/.vep/homo_sapiens/97_GRCh38/ I have only one file and it is: Homo_sapiens.GRCh38.dna.toplevel.fa.gz
I have tried:
`./vep -i /Volumes/Macintosh\ HD2/data/UPR_CANCER_2/snpcall/combined.n2.vcf.Q40d20.vcf -o /Volumes/Macintosh\ HD2/data/UPR_CANCER_2/snpcall/combined.n2.vcf.Q40d20.vcf.vep.2.txt -offline --assembly GRCh38 --cache /Users/mzillur/.vep/homo_sapiens/97_GRCh38
`and 
`./vep -i /Volumes/Macintosh\ HD2/data/UPR_CANCER_2/snpcall/combined.n2.vcf.Q40d20.vcf -o /Volumes/Macintosh\ HD2/data/UPR_CANCER_2/snpcall/combined.n2.vcf.Q40d20.vcf.vep.2.txt -offline --assembly GRCh38 --cache /Users/mzillur/.vep/homo_sapiens/97_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz 
`
Attached are the output files. Best, Zillur
[combined.n2.vcf.Q40d20.vcf.vep.3.txt](https://github.com/Ensembl/ensembl-vep/files/3457819/combined.n2.vcf.Q40d20.vcf.vep.3.txt)
[combined.n2.vcf.Q40d20.vcf.vep.2.txt](https://github.com/Ensembl/ensembl-vep/files/3457823/combined.n2.vcf.Q40d20.vcf.vep.2.txt)
[combined.n2.vcf.Q40d20.vcf.vep.2.txt_warnings.txt](https://github.com/Ensembl/ensembl-vep/files/3457824/combined.n2.vcf.Q40d20.vcf.vep.2.txt_warnings.txt)
[combined.n2.vcf.Q40d20.vcf.vep.3.txt_warnings.txt](https://github.com/Ensembl/ensembl-vep/files/3457825/combined.n2.vcf.Q40d20.vcf.vep.3.txt_warnings.txt)

**Comment by helensch** [comment]
Hi

Thank you for looking for files in  /Users/mzillur/.vep/homo_sapiens/97_GRCh38/. 

As you only have a FASTA file, it looks like you do not have cache files installed. In the directory 97_GRCh38 there should be files (info.txt and chr_synonyms.txt) and directories (e.g. directories called "1", "2" etc) that contain files.

The caches for VEP can be installed using the installer INSTALL.pl or manually downloaded. For information on downloading the cache see:
https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache 

Helen
