### ISSUE TITLE
VEP missing dbSNP annotations or 1KG frequencies ?

### ISSUE THREAD

**Issue by af8** [Ensembl/ensembl-vep#100]
Hello,

Don't know whether it is the right place to ask this question.
I have this position in a VCF file (Here on GRCh37):

> 10 88635779 rs11528010  C  A  BMPR1A ...

This is a **very common** SNP with a rs_id. The dbSNP page indicates that it has been genotyped by the 1KG, ExAC, ESP projects and reports high frequencies for both alleles. 

But annotating with VEP (90.8) will fail to report any frequency data and even "Existing_Variation" field remains blank.

There are very few positions like this one out of 3.5 millions records in my germline VCF, but can not figure out why VEP would fail to report at least the rs_id. For 1KG allelic frequencies (AF), I have a guess, they have applied some accessibility masks (two stringency: pilot & strict). If the position does not fall into the accessibility mask used, one may not be able to report the AF. In particular, `10:88635779` does not belong to a region of the strict mask.

But at least the rs_id should exist in dbSNP.

Any idea of why such behaviour can be observed ?

Many thanks,
Best,
Anthony

**Comment by willmclaren** [comment]
This SNP has failed one of our QC checks; in this case the QC check is actually one carried out by dbSNP, you can see here: http://grch37.ensembl.org/Homo_sapiens/Variation/Population?v=rs11528010

You may force VEP to report these failed variants with `--failed 1`.
