### ISSUE TITLE
Distribution plots: position sorting

### ISSUE THREAD

**Issue by jd3234** [Ensembl/ensembl-vep#1001]
## Describe the issue
We have noticed a strange ordering of positions in the distribution along the chr plots. We noticed it because of the sharp decline of variants. Upon closer inspection we noticed that sharp down is actually the end of the chromosome. But you can see that numbering goes on. It looks like an alphabetical sorting instead of a natural .. Older pictures of these plots we found online seem ok.

![grafik](https://user-images.githubusercontent.com/32764481/120639988-4487d300-c472-11eb-8d71-12b1b75a9a61.png)

## Additional information
We are using custom and in house data (vcf, fasta, gff3).

### System

    VEP version: 104.3 (official docker)
    VEP Cache version: custom
    Perl version:
    OS: Ubuntu
    tabix installed ? yes

### Full error message
There are no error/warning messages.

**Comment by dglemos** [comment]
Hi @jd3234,
Can you send an example of an input variants and what you would expect to see in the output?

**Comment by jd3234** [comment]
Hi @dglemos,

unfortunately it would not be complient for me to share the data. I will try to find a vcf that was created internally but with public data that I can share with you. The data in the VCF is sorted by bcftools sort. I checked position sorting again and it looks fine.

I would expect that in the plot that is called "Distribution" and that has positions on the X axis that the x axis does represent the positions in the chromosome - in a natural order: 1,2,3,4,5,6,7,8,9,10,11. But what I get is 1,10,11,2,3,4,5,6,7,8. (Sorry my picture is not very pretty but I hope you understand what I mean.)

![grafik](https://user-images.githubusercontent.com/32764481/121152487-8a171800-c845-11eb-82fb-c59176422a85.png)

Here is an example that we found on google (and how I have seen it in the past)
![grafik](https://user-images.githubusercontent.com/32764481/121152781-cc405980-c845-11eb-8197-c92119b306ab.png)

**Comment by worker000000** [comment]
I am also suffering from this bug

**Comment by dglemos** [comment]
How do you generate these "Distribution" plots? 
About the position sorting, VEP doesn't do any sorting. If your input file has the correct position sorting then the VCF output should be the same.

**Comment by jd3234** [comment]
The plots are part of the html output from VEP... In my case I did check the sorting in my input VCF and it is sorted in the correct way.

**Comment by dglemos** [comment]
You are correct, the position within the chromosome is not a natural sorting. The issue seems to be only in the plots, not in the output file. We will try to add a fix.
Thanks
Diana

**Comment by michaeljon** [comment]
Opened a PR (https://github.com/Ensembl/ensembl-vep/pull/1169) to address this. We were starting to rely on the statistics display and this was causing concern.

**Comment by diegomscoelho** [comment]
Closing this issue now since it was fixed in PR (https://github.com/Ensembl/ensembl-vep/pull/1170).

Thanks @michaeljon for your help in this issue.

Best, @diegomscoelho
