### ISSUE TITLE
gzip: stdout: Broken pipe 

### ISSUE THREAD

**Issue by Kaskere** [Ensembl/ensembl-vep#1005]
Hello,
I try to run VEP tool on three file types: vcf, txt and gz. In first two cases I get only empty outputs, and in third case `gzip: stdout: Broken pipe ` occurs. I downloaded VEP as Singularity image. 
my code looks like this:
I saw several issues about the same topic, but no one seemed to be answered. Is this bug corrected?

```
#!/bin/bash -x


module load bio/vep/101-sg

export inpath=/dir
export outpath=/dir
mkdir -p $outpath
chmod u+rwx $outpath
export reference=/mnt/home/references/hg38.fasta

for file in $inpath/*.txt ;
do
        sample=$(basename $file ".txt")
        outfile=$outpath/$sample".vep.vcf"
        #module load bio/vep/101-sg
        singularity exec $vep \
        vep --database \
        vep --force_overwrite -i $file -o $outfile
done
```

**Comment by aparton** [comment]
Hi @Kaskere,

Thank you for your query. Could you please try and run a simple query to see if you get the same issue? If you replace `-i $file` in your input command with `--id rs699`, does VEP correctly produce an output file?

If the simple query is successful, could you please send me on a copy of your VCF and I can attempt to reproduce the issue? You can either attach it to this ticket, or email it to helpdesk@ensembl.org

Kind Regards,
Andrew

**Comment by Kaskere** [comment]
Hello,
I ran
```
for file in $inpath/*.txt ;
do
        sample=$(basename $file ".txt")
        outfile=$outpath/$sample".vep.vcf"
        #module load bio/vep/101-sg
        singularity exec $vep \
        vep --database \
        vep --force_overwrite -id rs699  -o $outfile
done
```

It made output from first file in directory with the named rs.

**Comment by at7** [comment]
Hi @Kaskere,
thank you for running the suggested test. We will look into the problem and get back to you as soon as we know more.

Best wishes,
Anja

**Comment by aparton** [comment]
Hi @Kaskere,

Thanks for running the test query. If the test query was successful, that suggests that there's something within your VCF file that VEP doesn't like.

If you're unable to send your file on, could you please run it through VCF validator and verify that the content of your VCF file is valid? You can find it as part of the VCFtools package - https://vcftools.github.io/

Alternatively, could you try running VEP with a subset of the variants included within your VCF file? If you run your command on a sample VCF file containing your header lines and the first variant included within your file, do you see the same issue?

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew
