### ISSUE TITLE
Substr outside of string 

### ISSUE THREAD

**Issue by Anahit19** [Ensembl/ensembl-vep#1006]
## Describe the issue
Hi, I am running vcf2maf with the following command 

perl vcf2maf.pl --input-vcf BY01.vcf --output-maf BYZ01.vcf.maf --tumor-id BY01 --ref-fasta resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta --vep-path /gpfs/software/soft/manual/any/ensembl-vep/102/ --vep-data all_samples/ --ncbi-build GRCh38 --vep-overwrite

All my samples passed the analysis except one. I am getting the following error for that particular sample:

### Full error message

STATUS: Running VEP and writing to: ./BY01.vep.vcf
substr outside of string at /gpfs/software/soft/manual/any/ensembl-vep/102/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 906.
Died in forked process 16552

ERROR: Failed to run the VEP annotator! 
 
Could you please help with this issue. Thanks!

**Comment by at7** [comment]
Hi,
the script vcf2maf is not developed by us and you might need to contact the developers of the vcf2maf script. However, I'm happy to debug the error if you could isolate the VEP call and input line which leads to the error.

Thank you,
Anja

**Comment by Anahit19** [comment]
Separately VEP is working :) Thank you!

**Comment by at7** [comment]
That is good to know. Thank you for letting us know.
