### ISSUE TITLE
Missing COSMIC ids

### ISSUE THREAD

**Issue by sean-ocall** [Ensembl/ensembl-vep#1008]
## Describe the issue
Following from my closed issue: https://github.com/Ensembl/ensembl-vep/issues/1007

I've now been able to achieve annotation of all of the columns I require, but there is still information missing from one column. My `Existing_variation` column is not reporting cosmic ids. Is there a flag I have missed? or some incompatible flags?

### System
- VEP version: 104
- VEP Cache version: 104
- tabix installed 1.3.1

### Full VEP command line
```
vep -i $TSV_NAME -v --dir_cache $PWD --cache --offline --format ensembl --fasta $PWD/Homo_sapiens.GRCh37.dna.primary_assembly.fa --variant_class --sift b --polyphen b --regulatory --total_length --numbers --no_escape --hgvs --hgvsg --shift_hgvs 0 --symbol --ccds --uniprot --protein --canonical --biotype --domains --xref_refseq --check_existing --exclude_null_alleles --af --af_1kg --af_gnomad --tab -o vep_output.tsv
```

### Full error message
No error, but reported annotation is missing cosmic IDs. 

### Data files (if applicable)
Input: 
`1 1722003 1722003 G/A + 1_1722003_G_A`

output file attached

In addition, a straight call to tabix: `tabix $PWD/homo_sapiens/104_GRCh37/1/all_vars.gz 1:1722003-1722003` returns the following: 
```
1	COSV101060785	.	1	1722003	.	COSMIC_MUTATION	.	.	.	.	1	.	.	COSMIC::COSM8502737	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.
1	rs200569590	.	.	1722003	.	G/A	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	A:1.592e-05	A:0	A:0	A:0.000298	A:0	A:0	A:8.806e-06	A:0	A:0
```
so the cache seems to contain the data, but I'm not getting it in the output

[vep_output_18062021.txt](https://github.com/Ensembl/ensembl-vep/files/6676024/vep_output_18062021.txt)

Many thanks,
Sean

**Comment by at7** [comment]
Hi Sean,
you need to remove --exclude_null_alleles from your options. Alleles are not publicly available for variants from HGMD and COSMIC; by default these are included when using --check_existing. And using --exclude_null_alleles will exclude them.

Best wishes,
Anja

**Comment by sean-ocall** [comment]
Thank you!
