### ISSUE TITLE
Output is written to stdout if stdout is found in output file name

### ISSUE THREAD

**Issue by lacek** [Ensembl/ensembl-vep#101]
On the line https://github.com/Ensembl/ensembl-vep/blob/3c71cb4f0438d5d7d2f420b551cf68113192e3a7/modules/Bio/EnsEMBL/VEP/Config.pm#L632, `stdout` is matched if it appears in any location of the output file name. If an output file name like `sample.stdout.vcf`, output is written to stdout.

I would suggest using `/^stdout$/i` to match the file name more strictly.

> Note: I was using VEP 80, I am not sure if the same behaviour applies to new versions.

**Comment by willmclaren** [comment]
This is fixed in newer versions; version 80 of VEP formed part of the ensembl-tools repository and is no longer supported. If possible, please move to using ensembl-vep.
