### ISSUE TITLE
Missing AF data

### ISSUE THREAD

**Issue by marc-sturm** [Ensembl/ensembl-vep#1010]
## Describe the issue
I just tested VEP 104.3 on GRCh38 and found some missing data for the variant chr1:876499 A>G.
There is no1000 Genomes and gnomAD allele frequency data annotated when using VEP locally in offline-mode.
The data is also missing in the VEP web interface:
![grafik](https://user-images.githubusercontent.com/5638144/122779681-61b00480-d2ae-11eb-9ed8-257dc0813ac0.png)

It might be normal that the gnomAD AF is missing because there is not exomes for GRCh38.
However the 1000 Genomes AF should be there, since it was also annotated for GRCh37 (AF=0.9131).
1000 Genomes AF is also listed on several webpages for the variant:
http://www.ensembl.org/Homo_sapiens/Variation/Population?db=core;r=1:940619-941619;v=rs4372192;vdb=variation;vf=2638644#1000genomesprojectphase3_anchor
https://gnomad.broadinstitute.org/variant/1-941119-A-G?dataset=gnomad_r3

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 104.3
- VEP Cache version:104
- Perl version: 5.26.1
- OS: Ubuntu 18.04
- tabix installed: yes

**Comment by helensch** [comment]
Hi @marc-sturm 

There are no co-located variants for the input variant chr1:876499 A>G on GRCh38. Therefore no frequencies are reported. From your VEP Web output the co-located (existing variant) column is empty.

https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#existing 

The VCF for rs4372192 on GRCh38
1  941119  rs4372192  A  C,G,T

For this variant, VEP returns:
1000 Genomes continental allele frequencies
gnomAD (exomes) allele frequencies

It does not return 1000 Genomes global minor allele frequency. This is an known issue that is being looked at. See related issue #957

Please let me know if you have any further queries.

Regards
Helen

**Comment by marc-sturm** [comment]
Hi Helen,

thanks for the quick answer.
Since my main concern is the missing 1000G AF, you can mark this issue a duplicate of #957 and close it.

Best,
  Marc

**Comment by helensch** [comment]
Hi @marc-sturm 

Thanks for the reply. As you noted this is a duplicate issue to #957. I will close this issue and record this variant for testing.

Regards
Helen
