### ISSUE TITLE
"--sift" tag returns no results when running ensembl vep in the command line

### ISSUE THREAD

**Issue by BeeSam-code** [Ensembl/ensembl-vep#1012]
Hi,

When I try to run a list of (human)SNPs through the ensembl vep in the command line, I get the standard results but there are no added results column when I add the "--sift b" and the "--polyphen b" tags as in the code below:

./vep -i input_rsID_vep.txt -o rsID_output062021.txt --assembly GRCh37 --sift b --polyphen b  --database --sf stats_rsID_output062021.txt 

Any advice on what may be going wrong? 

When I run the above code or the version with the "--sift b" and the "--polyphen b" tags, I get an output file with the headers:

## PolyPhen : PolyPhen prediction and/or score
#Uploaded_variation     Location        Allele  Gene    Feature Feature_type    Consequence     cDNA_position   CDS_position                                                                Protein_position Amino_acids     Codons  Existing_variation      Extra

**Comment by helensch** [comment]
Hi @BeeSam-code 

Thank you for query and example command line.

When available, SIFT and PolyPhen values are reported for missense variants.
https://www.ensembl.org/info/genome/variation/prediction/protein_function.html

What are the consequence types of the variants you are using?

To test that SIFT and PolyPhen scores are being extracted, please could you try using the following example variant:  rs1600654359

`./vep  -id rs1600654359 --assembly GRCh37 --database --sift b --polyphen b -o rs1600654359_vep_output.tab --tab`

The output should include the following 
| #Uploaded_variation |	Feature	| Consequence | SIFT	| PolyPhen|
|--------------------- |-----------| ---------------|--------|----------|
| rs1600654359	| ENST00000313949 | missense_variant | deleterious_low_confidence(0.01) | possibly_damaging(0.798)| 
|rs1600654359	| ENST00000371075 | missense_variant | deleterious_low_confidence(0.01) |	possibly_damaging(0.798)|
|rs1600654359    | ENST00000371098 | missense_variant | deleterious_low_confidence(0.01) |	possibly_damaging(0.798)|
| rs1600654359	|ENST00000419558	| upstream_gene_variant	|-	|-|

Note only the first non missense_variant has been reported. The SIFT and PolyPhen results for the variant  rs1600654359 are also reported on the "Genes and Regulation" page for the variant  rs1600654359 on https://grch37.ensembl.org/ 

Please let me know if you have any further queries.

Regards
Helen

**Comment by BeeSam-code** [comment]
Hi Helen,

Thank you for your insight. Your test command line worked for me as well. My list of test SNPs (a few out of the ~50k I am investigating) did not happen to have any missense variants. Running the entire list of SNPs overnight and it seems like it should work fine. 

Again, thank you, closing the issue for now. 

Sam
