### ISSUE TITLE
Uninitialized value warning - indel annotation

### ISSUE THREAD

**Issue by davidfstein** [Ensembl/ensembl-vep#1017]
## Describe the issue
When running vep on a set of indels, I repeatedly receive the warning ```WARNING: Use of uninitialized value in pattern match (m//) at /vep/100/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/InputBuffer.pm line 596, <__ANONIO__> line 4957.```
This warning is not produced for snps run with the same parameters.
Is this warning something I need to worry about, i.e. will it affect the quality of my indel annotations?

### System
- VEP version: 100
- VEP Cache version: 100
- Perl version: 5.16.3
- OS: CentOS Linux 7 (Core)
- tabix installed ? yes

### Full VEP command line
```
vep -i $myinput -o $WRKDIR/$myoutput --vcf --dir_cache $cachedir --assembly GRCh38 --cache --sift b --polyphen b --ccds --hgvs --symbol --numbers --domains --regulatory --canonical --protein --biotype --uniprot --tsl --appris --gene_phenotype --pubmed --variant_class --mane --total_length --pick_allele --offline --fasta $ref_fasta --dir_plugins $pathToPlugins --plugin CADD,$cadddir/whole_genome_SNVs.tsv.gz,$cadddir/gnomad.genomes.r3.0.indel.tsv.gz --force_overwrite --fork 48 --buffer_size 10000 --minimal --allele_number --plugin Blosum62 --plugin Condel,$plugdir/Condel/config,b --plugin Conservation,$plugdir/Conservation/gerp_conservation_scores.homo_sapiens.GRCh38.bw --plugin ExACpLI,$plugdir/ExACpLI/ExACpLI_values.txt --plugin LoFtool,$plugdir/LoFtool/LoFtool_scores.txt --plugin REVEL,$plugdir/REVEL/new_tabbed_revel_grch38.tsv.gz --plugin StructuralVariantOverlap,file=$plugdir/StructuralVariantOverlap/gnomad_v2.1_sv.sites.vcf.gz --plugin NearestExonJB --plugin Carol --plugin Downstream --plugin GeneSplicer,$plugdir/GS/GeneSplicer/bin/linux/genesplicer,$plugdir/GS/GeneSplicer/human,context=200,tmpdir=/tmp --plugin MaxEntScan,$plugdir/maxentscan/ --plugin Mastermind,$plugdir/mastermind/mastermind_cited_variants_reference-2021.04.02-grch38.vcf.gz --plugin PON_P2,$plugdir/ponp2/ponp2.py --plugin ReferenceQuality,$plugdir/refquality/sorted_GRCh38_quality_mergedfile.gff3.gz --plugin satMutMPRA,file=$plugdir/satmutmpra/satMutMPRA_GRCh38_ALL.gz --plugin TSSDistance --plugin DisGeNET,file=$plugdir/disgenet/all_variant_disease_pmid_associations_final.tsv.gz --plugin dbscSNV,$plugdir/dbscsnv/dbscSNV1.1_GRCh38.txt.gz
```

**Comment by aparton** [comment]
Hi @davidfstein,

Thank you for your query. I suspect this warning is something to be concerned about, could you please send me an example variant/input file where you see this issue happening?

Kind Regards,
Andrew

**Comment by davidfstein** [comment]
Hi Andrew, 

Thanks for your reply. I can't share all of the data because of licencing issues. I'm trying to pin down a few indels that cause the issue so I can share an example with you. Is there a way to trace a warning back to a specific line in the vcf file?

**Comment by davidfstein** [comment]
In tracking down the offending variants, I think I discovered the issue. The warning appears to be triggered by the <del> identifier in the alt column. I suppose an error or warning is the expected behavior in this case?

**Comment by aparton** [comment]
Hi @davidfstein,

Yes, in this case than the warning you receive is expected behaviour. You can find more details regarding VEP's VCF input expectations for variants of this type here: https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#sv

Please let me know if there's anything else we can do to help.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew
