### ISSUE TITLE
gnomAD/1000G frequencies for multiallelic variants

### ISSUE THREAD

**Issue by sigven** [Ensembl/ensembl-vep#102]
Hi,
I am running v90 locally with annotations against 1000Genomes and gnomAD (exomes) turned on, i.e.: '--af --af_1kg --af_gnomad'. I came across a variant that is found at considerable frequency, and apparently [part of both the 'genome' and 'exome' set of gnomAD](http://gnomad.broadinstitute.org/variant/1-161514542-A-C). However, when I query this variant against my local cache, I do not see any germline frequencies in my CSQ tag output by VEP, although I can see the frequencies for this multiallelic site listed in the cache file (161000001-162000000_var.gz). Is there any reason for this, or are there options that I need to turn on to have these frequencies reported?

regards,
Sigve

**Comment by willmclaren** [comment]
It's possible the variant is being excluded as it has failed a QC check; you can force include these with `--failed 1`.

If this still doesn't work, let us know what your input is and we can take a look.

**Comment by sigven** [comment]
Thanks, including `--failed 1`  gave me proper frequencies (although i am not sure why this variant is failing).
