### ISSUE TITLE
Segmentation fault when using custom dataset (ex. Clinvar)

### ISSUE THREAD

**Issue by kvn95ss** [Ensembl/ensembl-vep#1020]
## Describe the issue
When using a custom dataset for annotation of Genome data (Even Clinvar), vep throws segmentation fault error. Annotation works if I use data from cache, i.e. when using ```--everything```. The vcf file has around 3.8 million variants

### System
- VEP version: 103.1
- VEP Cache version: 103
- Perl version: v5.26.2
- OS: RHEL
- tabix installed Yes

### Full VEP command line
Command which works - 
```
vep --tab --fork 30 --assembly GRCh38 --cache --offline --dir "$vep-cache" --fasta "$ref_hg38" -i test.vcf.gz -o test --everything --per_gene
```
Command which fails - 
```
vep --tab --fork 30 --assembly GRCh38 --cache --offline --dir "$vep-cache" --fasta "$ref_hg38" -i test.vcf.gz -o test --everything --per_gene --custom "$vep-cache"/clinvar.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNREVSTAT,CLNDN
```
### Full error message
> Segmentation fault (core dumped)

UPDATE - 

I tried the docker version of 103, still getting the same error. Will try with the latest version (104) and update if it resolves anything.

**Comment by at7** [comment]
Hello,
I ran your VEP command using custom annotations from the [ClinVar file](https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar.vcf.gz) for the input variant `--id "1  230710048 230710048 A/G 1"`. But I'm not able to reproduce your error message. I also ran the command with docker `docker run -t -i -v $HOME/vep_data:/opt/vep/.vep ensemblorg/ensembl-vep ./vep --id "1  230710048 230710048 A/G 1" --database  --output_file /opt/vep/.vep/output/my_output.vcf --custom /opt/vep/.vep/clinvar.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNREVSTAT,CLNDN` and also could not reproduce the error. 

We had similar issues in the past with the same error message. But those also had an extra warning about problems reading or indexing files.
Did you get any other error messages or did you only get Segmentation fault (core dumped)?

Best wishes,
Anja

**Comment by kvn95ss** [comment]
Hello Anja,

Thanks for the response, however my problem was something else. There was issue when downloading the clinvar file and for some reason ```curl``` had saved a webpage as vcf.gz file, hence leading to the issue. Once I downloaded vcf .gz and tbi using ```wget``` it all worked well, even in docker. 

So considering this solved. If someone else is facing the same issue, ensure the files are downloaded correctly.
