### ISSUE TITLE
first vep command. get error

### ISSUE THREAD

**Issue by junhuixiao** [Ensembl/ensembl-vep#1022]
## Describe the issue
MSG: ERROR: Cache directory /home/junhuixiao/.vep/homo_sapiens not found

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: [104.3] 
- VEP Cache version: [e.g. 98]
- Perl version: [v5.30.0]
- OS: [Ubuntu]
- tabix installed no

### Full VEP command line
./vep -i examples/homo_sapiens_GRCh38.vcf --cache

### Full error message
-------------------- EXCEPTION --------------------
MSG: ERROR: Cache directory /home/junhuixiao/.vep/homo_sapiens not found

STACK Bio::EnsEMBL::VEP::CacheDir::dir /home/junhuixiao/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:311
STACK Bio::EnsEMBL::VEP::CacheDir::init /home/junhuixiao/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:227
STACK Bio::EnsEMBL::VEP::CacheDir::new /home/junhuixiao/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /home/junhuixiao/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:115
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/junhuixiao/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/junhuixiao/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /home/junhuixiao/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::run /home/junhuixiao/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel ./vep:232
Date (localtime)    = Fri Jul  9 15:33:14 2021
Ensembl API version = 104

### Data files (if applicable)
none

**Comment by NavenM** [comment]
Hi @junhuixiao

Were the cache files installed during VEP installation (i.e. when running `perl INSTALL.pl`)? The default location is your home directory ($HOME/.vep), but if you installed them elsewhere you can point to them using the `--dir` option when running VEP. 

If the cache isn't installed then installing it will hopefully resolve the issue; If the cache is installed and you're seeing the error, leave a comment and I can have a closer look.

Thanks

**Comment by junhuixiao** [comment]
Thank you for your reply. I didn't install cache. I am installing now. 

I have several questions:
1.  i uploaded a file from the web interface http://grch37.ensembl.org/Homo_sapiens/Tools/VEP and get the result back. I went to the job details and see the command line equivalent.

My Command line equivalent:
./vep --af_gnomad --appris --biotype --buffer_size 500 --canonical --check_existing --distance 5000 --gencode_basic --mane --plugin CADD,[path_to]/CADD_GRCh37_1.6_whole_genome_SNVs.tsv.gz,[path_to]/CADD_GRCh37_1.6_InDels.tsv.gz --pubmed --regulatory --species homo_sapiens --symbol --transcript_version --tsl --cache --input_file [input_data] --output_file [output_file] --port 3337

I am familiar with rest api. can you give me the tips which rest API I can use to get the same result back as my above command line? to query with a big file, It seems command line is the best way to do it.


2. During the installation, I got the below message. How to install  Bio::Root::Version in my windows usbsysem in linux?
Checking prerequisites...
  requires:
    !  Bio::Root::Version is not installed

Thanks,

**Comment by NavenM** [comment]
No problem, glad I could help. I've left a response to your other questions below:

1. If you haven't already, I'd suggest looking at getting started withe the [Ensembl REST API](https://github.com/Ensembl/ensembl-rest/wiki/Getting-Started#introduction), and then at the [VEP endpoint](https://rest.ensembl.org/#VEP) for lists of parameters and examples. 

I've used the command line to run VEP when I've had large/multiple files, but everyone has a personal preference.

2. I think Bio::Root::Version is included with BioPerl, which is installed when running INSTALL.pl. You may want to check that BioPerl has been installed, and it's included in your $PERL5LIB variable. If both of those conditions are met, then try installing Bio::Root:Version on its own:
    `$ sudo apt-get install cpanminus`
    `$ cpanm Bio::Root::Version`

I hope the above helps, but if not, let me know.
Thanks

**Comment by junhuixiao** [comment]
Thank you for your reply. 
I am trying rest api:

POST vep/:species/region


Here is the parameter I passed:
 String postBody = "{ \"variants\" : [\"21  26960070  rs116645811 G A . . .\", \"21  26965148  rs1135638 G A . . .\" ], \"CADD\" : \"1\" }";

I want CADD return, so I passed CADD = 1, but I didn't get any CADD data back. can rest api POST vep/:species/region return CADD data ?

thanks!

**Comment by junhuixiao** [comment]
This is the sample code I copied from the rest api POST vep/:species/region

String postBody = "{ \"variants\" : [\"21  26960070  rs116645811 G A . . .\", \"21  26965148  rs1135638 G A . . .\" ] }";
Is my postBody the correct format?
String postBody = "{ "variants" : ["21 26960070 rs116645811 G A . . .", "21 26965148 rs1135638 G A . . ." ], "CADD" : "1" }";

Thanks,
junhui

**Comment by NavenM** [comment]
Hi @junhuixiao,

it looks like you need to remove the CADD option from your postBody string and place it after your endpoint. For example, the corresponding lines in the java example on the POST vep/:species/region page would look something like this:

`String ext = "/vep/homo_sapiens/region?CADD=1";`

`String postBody = "{ \"variants\" : [\"21  26960070  rs116645811 G A . . .\", \"21  26965148  rs1135638 G A . . .\" ] }";`

That should hopefully return CADD data.

Thanks

**Comment by junhuixiao** [comment]
Thank you so much! I got CADD return after following your instructions.

**Comment by junhuixiao** [comment]
Thank you for your previous help!

Is it possible I pass the variants like that "{ \"variants\" : [\"21 26960070 rs116645811 G A . . .\", \"21 26965148 rs1135638 G A . . .\" ] }" and get gnomAD_freq	and gnomAD_binary data using a rest API? I believe there is one as we can use web interface to get gnomAD_freq	and gnomAD_binary back. I read through the rest API and cannot locate one. can you point me to the correct rest API?

Thanks!

**Comment by junhuixiao** [comment]
Please ignore my last question about gnomAD_binary . Our group define it by ourselves.

We need to get gnomAD frequency. Is it possible we call the rest api **POST vep/:species/region**  to get the gnomAD frequency back? 
Below are the code I used. I didn't see gnomAD frequency data in the returned string. Do you have an optional parameter I can do in this api to get gnomAD frequency back? 
 ext = "/vep/human/region?CADD=1";
  string postBody = "{ \"variants\" : [\"1  865519  . C T . . .\", \"1  865545  . G A . . .\" ] }";


I saw rest api **POST vep/:species/id** can return  gnomAD frequency. I can do the rest api **POST vep/:species/region** first, then call **POST vep/:species/id** to get the gnomAD frequency. in that way, I need to call rest api two times. i hope one time rest api **POST vep/:species/region** call can get gnomAD frequency.

Thanks!



POST vep/:species/region

**Comment by NavenM** [comment]
Hi,

It looks like the only way to get gnomAD frequencies via the rest API is by using POST vep/:species/region and then vep/:species/id as you described.

You might find it more convenient to use the command line if you need frequencies for a lot of variants, and there's a brief discussion on gnomAD frequency data here that you might find informative (https://m.ensembl.org/info/docs/tools/vep/script/vep_other.html).

I hope that helps - please let me know if not!
Thanks

**Comment by junhuixiao** [comment]
Thanks! 

  use the api GET vep/:species/hgvs/:hgvs_notation and pass the below sample string:
   String server = "https://rest.ensembl.org";
    String ext = "/vep/human/hgvs/ENST00000366667:c.803C%3ET?";
I got the Gnomad freq info.

But when I use the api POST vep/:species/hgvs and pass the below sample strings:

 String server = "https://rest.ensembl.org";
    String ext = "/vep/human/hgvs";
    String postBody = "{ \"hgvs_notations\" : [\"ENST00000366667:c.803C>T\", \"9:g.22125504G>C\" ] }";

I didn't get any gnomad freq info. You can tell in the 2nd api POST vep/:species/hgvs, I pass the same parameter NST00000366667:c.803C>T as the first one. I suppose got the Gnomad freq the same as the first api call.

can you help what I am missing?

Thanks!

**Comment by NavenM** [comment]
Hi, 

Did you use the ?CADD=1 option in your ext string?  It's not shown in the example code but is still required to get CADD output. Was there any output at all with POST vep/:species/hgvs? Your postBody string has multiple pairs of quotation marks (""), and I'm not sure how they'll be handled. They're preceded by backslashes in the example and they might be necessary. Trying with the following couple of lines below might be the solution: 

     `String ext = "/vep/human/hgvs?CADD=1";`
     `String postBody = "{ \"hgvs_notations\" : [\"ENST00000366667:c.803C>T\", \"9:g.22125504G>C\" ] }";`

If the above suggestions work, then great! But if not, we'll have a look for another solution.
Thanks

**Comment by junhuixiao** [comment]
Hi there,
I think you misunderstand my questions. My question is I didn't get gnomad freq using API POST vep/:species/hgvs.
Below are my steps.

1. first I use the api  POST vep/:species/region and set
ext = "/vep/human/region?CADD=1&hgvs=1" and get the CADD and hgvs back.

2. Then I use the api POST vep/:species/hgvs and pass below parameters and try to get  gnomad freq data:
 `String ext = "/vep/human/hgvs";`
 `String postBody = "{ \"hgvs_notations\" : [\"ENST00000366667:c.803C>T\", \"9:g.22125504G>C\" ] }";`

But the 2nd api POST vep/:species/hgvs doesn't return gnomad freq.

Do you have a better way to get CADD and gnomad freq back using VEP rest API?

Thanks,

**Comment by junhuixiao** [comment]
Hi there,
we manipulated our raw data and created the HGVS notation and call rest API GET vep/:species/hgvs/:hgvs_notation and we can get CADD and Gnomad requency in one rest API call.

But we have another problem. You rest API only returns "assembly_name":"GRCh38". But our  raw data are using assembly_name GRCh37. Do you have the rest API I can call to return assembly  GRCh37 data?

Thanks,
Junhui

**Comment by NavenM** [comment]
Hi,

sorry, yes - I got mixed up with your earlier question about returning CADD. 

I've just checked GET vep/:species/hgvs/:hgvs_notation using 
    `String ext = "/vep/human/hgvs/ENST00000366667:c.803C%3ET?";`

and POST vep/:species/hgvs using 
    `String postBody = "{ \"hgvs_notations\" : [\"ENST00000366667:c.803C>T\", \"9:g.22125504G>C\" ] }";`.

ENST00000366667:c.803C>T returns gnomAD data for both endpoints, but 9:g.22125504G>C doesn't. Are you not seeing frequencies for ENST00000366667:c.803C>T, or just 9:g.22125504G>C?

The VEP endpoints return frequency data as it is stored in the VEP cache files. The caches themselves only contain gnomad exome frequencies as imported from dbSNP - so until gnomAD is fully submitted to dbSNP and it's incorporated into Ensembl, some alleles might have missing frequency data (as is the case for 9:g.22125504G>C).


Converting your raw data as you have done should allow you get data back from a single API call. If you need to get GRCh37 specific data back, you can try the [GRCh37 REST api here](https://grch37.rest.ensembl.org/).

I hope that's all makes sense - if not, just let me know.
Thanks

**Comment by junhuixiao** [comment]
Thank you so much for your reply. The GRCH37 rest API link really helps.

**Comment by junhuixiao** [comment]
Hi there,
 I am trying to use https://grch37.rest.ensembl.org/ Rest API POST vep/:species/id to get CADD and Gnomad_freq.  

If I pass less than 500 IDs, the rest api works well, I can get the data return. But If I passed more than 500 IDs, it gives error. Do you have the ID amount limitation to call this API?

Thanks,

**Comment by NavenM** [comment]
HI, 

I'm having trouble replicating the issue with your sample variants. Did you run one of the example requests or was it a custom one you wrote yourself? I ran using the example java request at the bottom of [this page](https://grch37.rest.ensembl.org/documentation/info/vep_region_post), that uses your sample variants and got gnomAD frequencies back. When I added "?CADD=1" to the ext string, I also got CADD data returned. Could you try one of the examples (if you haven't already) and let me know if you get gnomAD and CADD data returned?

As for the POST limits, I believe there's a limit of 200 (for GRCh38) or 300 (for GRCh37) variants per request. The whole REST API is limited to 55,000 requests per hour, so downloading and installing VEP may be more convenient for >1 million variants.

Thanks

**Comment by junhuixiao** [comment]
Thank you for your reply. 
I used C# code not Java code. I think for REST API calling, the language difference doesn't matter.

I pasted my code below. Does my ext string look good?

 string server = "https://grch37.rest.ensembl.org";
 string ext = "/vep/homo_sapiens/region?CADD=1&canonical=1";


I do got CADD back after I passed CADD=1,  but no GnomadAD data returns at all.

Below are my variances. 
{ "variants" : ["7 4787729 rs397704709 GCTGCTGGACCTGCC G . . .", "15 84799209 rs150829393 G A . . .", "11 126275389 rs267606829 C T . . .", "11 126277517 rs267606830 A G . . .", "14 31562125 rs200401432 G A . . .", "6 26092913 rs1800562 G A . . .", "6 26090951 rs1799945 C G . . .", "6 26090957 rs1800730 A T . . .", "6 26091078 rs28934596 T C . . .", "6 26091041 rs28934597 G C . . .", "6 26093008 rs1800758 G A . . .", "6 26090921 rs28934889 G A . . .", "6 26090939 rs111033557 G A . . .", "6 26091354 rs28934595 A C . . .", "6 26093215 rs111033558 G T . . .", "6 26092916 rs111033563 A C . . .", "2 19989284 rs397515534 T C . . .", "2 19945787 rs267607174 T C . . .", "2 19931374 rs397515334 AG A . . .", "2 19933469 rs267607175 C T . . .", "20 25323409 rs1555813914 TC AAA . . .", "20 25307980 rs397704714 G GGCTCTTA . . .", "20 25302322 rs267606624 G A . . .", "2 27378156 rs267607182 A G . . .", "10 97611611 rs397509360 TGAG T . . .", "10 97611535 rs138207257 G T . . .", "10 97598852 rs267606762 C T . . .", "10 97600167 . G T . . ." ]}

Thanks!

**Comment by junhuixiao** [comment]
sorry, I pasted wrong the variances above. below are correct.

{ "variants" : ["7 4827360 rs397704709 GCTGCTGGACCTGCC G . . .", "15 85342440 rs150829393 G A . . .", "11 126145284 rs267606829 C T . . .", "11 126147412 rs267606830 A G . . .", "14 32031331 rs200401432 G A . . .", "6 26093141 rs1800562 G A . . .", "6 26091179 rs1799945 C G . . .", "6 26091185 rs1800730 A T . . .", "6 26091306 rs28934596 T C . . .", "6 26091269 rs28934597 G C . . .", "6 26093236 rs1800758 G A . . .", "6 26091149 rs28934889 G A . . .", "6 26091167 rs111033557 G A . . .", "6 26091582 rs28934595 A C . . .", "6 26093443 rs111033558 G T . . .", "6 26093144 rs111033563 A C . . .", "2 20189045 rs397515534 T C . . .", "2 20145548 rs267607174 T C . . .", "2 20131135 rs397515334 AG A . . .", "2 20133230 rs267607175 C T . . .", "20 25304045 rs1555813914 TC AAA . . .", "20 25288616 rs397704714 G GGCTCTTA . . .", "20 25282958 rs267606624 G A . . .", "2 27601023 rs267607182 A G . . .", "10 99371368 rs397509360 TGAG T . . .", "10 99371292 rs138207257 G T . . .", "10 99358609 rs267606762 C T . . .", "10 99359924 . G T . . ." ]}

**Comment by junhuixiao** [comment]
After I passed the correct variants, I do get the CADD and GnomadAD back. Thanks!

we may have to install VEP in local for our big variants data.

Thank you for your help.

**Comment by junhuixiao** [comment]
Hi there,
We have VeP installed in HPC. This is The command I issued:
this is the command I issused:

vep --af_gnomad --appris --biotype --buffer_size 500 --canonical --check_existing --distance 5000 --gencode_basic --mane --plugin CADD,CADD_GRCh37_1.6_whole_genome_SNVs.tsv.gz,CADD_GRCh37_1.6_InDels.tsv.gz --pubmed --regulatory --species homo_sapiens --symbol --transcript_version --tsl --cache --input_file mytext.txt --output_file test.txt --force_overwrite --port 3337

 I got below error msg:
WARNING: Plugin 'CADD' went wrong: ERROR: Data file CADD_GRCh37_1.6_whole_genome_SNVs.tsv.gz not found

it seems I missed CADD_GRCh37_1.6_whole_genome_SNVs.tsv.gz. where can I download CADD_GRCh37_1.6_whole_genome_SNVs.tsv.gz? 
Thanks!

**Comment by NavenM** [comment]
Hi,

CADD files can be downloaded from here: [http://cadd.gs.washington.edu/download](http://cadd.gs.washington.edu/download). You'll also need to download the tabix index files from the same site, unless you plan on creating your own.

Hope that helps!
Marc

**Comment by junhuixiao** [comment]
Hi there,
we have  VEP installed in local. I ran below VEP command. I passed vep.input as input file and get the output file  test.txt.

vep \
--af_gnomad \
--appris \
--biotype \
--buffer_size 500 \
--canonical \
--check_existing \
--distance 5000 \
--gencode_basic \
--mane \
--plugin \
CADD,whole_genome_SNVs.tsv.gz,InDels.tsv.gz \
--pubmed \
--regulatory \
--species homo_sapiens \
--symbol \
--transcript_version \
--tsl \
--cache \
--input_file \
vep.input \
--output_file test.txt \
--force_overwrite \
--port 3337


The weird thing is i didn't get the gnomAD_AF and CADD_RAW data back for the below seven variances:
17;26732935;26732935;GC;TT
X;48652323;48652323;G;T
14;67787791;67787791;C;T
3;189526254;189526254;G;A
3;189612207;189612207;AC;A
17;26733109;26733109;C;CG
17;26732938;26732938;G;GC


But we can get the gnomAD_AF and CADD_RAW back from web interface. can you help check why that happens?
Thanks!

**Comment by NavenM** [comment]
Hi,

There may be differences between your command line and web interface parameters used. Are you able to post a link to your job results page? If not, could your post the command line equivalent from that page (you can find this by expanding the job details section)? It might be worth checking that the genome assembly (e.g. GRCh37) you're using is consistent between your web jobs, command line and downloaded cache files.

I'm not sure why VEP doesn't annotate those variants specifically, so it might be useful to have some more info on them. Could you also post their corresponding lines from your input and output files? Do you see the annotations for other variants?

If you want gnomAD data beyond allele frequencies, then the [gnomADc plugin](https://github.com/Ensembl/VEP_plugins/blob/release/104/gnomADc.pm) may be of interest to you, as well as looking at the [custom annotations flag](http://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html).

Thanks,
Marc

**Comment by junhuixiao** [comment]
Hi there,
I downloaded gnomADc plugin from gnomADc plugin link you provided and ran below VEP command:

vep \
--af_gnomad \
--appris \
--buffer_size 500 \
--canonical \
--check_existing \
--distance 5000 \
--gencode_basic \
--mane \
--plugin gnomADc,gnomADg.gz \
--plugin gnomADc,gnomADe.gz \
--regulatory \
--species homo_sapiens \
--transcript_version \
--cache \
--input_file \
vep.input \
--output_file Moregnomad.txt \
--force_overwrite \
--port 3337

But I got no gnomad data returned at all.
Here is a sample  input :
1 865519 1_865519_C/T . . .

below is my output:
## ENSEMBL VARIANT EFFECT PREDICTOR v104.3
## Output produced at 2021-09-02 13:17:45
## Connected to homo_sapiens_core_104_37 on ensembldb.ensembl.org
## Using cache in /home/xiaoj2/.vep/homo_sapiens/104_GRCh37
## Using API version 104, DB version 104
## ensembl version 104.1af1dce
## ensembl-funcgen version 104.59ae779
## ensembl-io version 104.1d3bb6e
## ensembl-variation version 104.6154f8b
## Column descriptions:
## Uploaded_variation : Identifier of uploaded variant
## Location : Location of variant in standard coordinate format (chr:start or chr:start-end)
## Allele : The variant allele used to calculate the consequence
## Gene : Stable ID of affected gene
## Feature : Stable ID of feature
## Feature_type : Type of feature - Transcript, RegulatoryFeature or MotifFeature
## Consequence : Consequence type
## cDNA_position : Relative position of base pair in cDNA sequence
## CDS_position : Relative position of base pair in coding sequence
## Protein_position : Relative position of amino acid in protein
## Amino_acids : Reference and variant amino acids
## Codons : Reference and variant codon sequence
## Existing_variation : Identifier(s) of co-located known variants
## Extra column keys:
## IMPACT : Subjective impact classification of consequence type
## DISTANCE : Shortest distance from variant to transcript
## STRAND : Strand of the feature (1/-1)
## FLAGS : Transcript quality flags
## CANONICAL : Indicates if transcript is canonical for this gene
## MANE_SELECT : MANE Select (Matched Annotation from NCBI and EMBL-EBI) Transcript
## MANE_PLUS_CLINICAL : MANE Plus Clinical (Matched Annotation from NCBI and EMBL-EBI) Transcript
## APPRIS : Annotates alternatively spliced transcripts as primary or alternate based on a range of computational methods
## CLIN_SIG : ClinVar clinical significance of the dbSNP variant
## SOMATIC : Somatic status of existing variant
## PHENO : Indicates if existing variant(s) is associated with a phenotype, disease or trait; multiple values correspond to multiple variants
## BIOTYPE : Biotype of transcript or regulatory feature
## MOTIF_NAME : The stable identifier of a transcription factor binding profile (TFBP) aligned at this position
## MOTIF_POS : The relative position of the variation in the aligned TFBP
## HIGH_INF_POS : A flag indicating if the variant falls in a high information position of the TFBP
## MOTIF_SCORE_CHANGE : The difference in motif score of the reference and variant sequences for the TFBP
## TRANSCRIPTION_FACTORS : List of transcription factors which bind to the transcription factor binding profile
#Uploaded_variation	Location	Allele	Gene	Feature	Feature_type	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	Extra
1_865519_C/T	1:865519	T	ENSG00000187634	ENST00000342066.3	Transcript	intron_variant	-	-	-	-	-	-	IMPACT=MODIFIER;STRAND=1;CANONICAL=YES

Do I miss something?

Thanks!

**Comment by junhuixiao** [comment]
Here is my error msg:

 ERROR: gnomAD directory not found

**Comment by nuno-agostinho** [comment]
Hey @junhuixiao,

Have you been able to run the gnomAD plugin? Do you need help?

Best regards,
Nuno
