### ISSUE TITLE
Feature Request: Summary statistics option for custom annotations (bed/bigwig) as CNVs annotation can be enormous

### ISSUE THREAD

**Issue by davmlaw** [Ensembl/ensembl-vep#1023]
For example, a <1k CNV VCF (from Dragen) using custom annotations with VEP can produce a 1GB gzipped annotated VCF

This is because CNVs span long distances, and custom bed/bigwig annotations work by packing the values together in the fields, eg:

```
0.0570000000298023&0.372000008821487&0.638999998569489&0.579999983310699
```

Eg a single VCF record with REFLEN=15015  had per-base annotation from phastCons100way_vertebrate - so a single field was 257,903 characters long.

```
csq = v.INFO.get("CSQ")
td = dict(zip(vep_columns, transcript_csq.split("|")))
cons_data = td["phastCons100way_vertebrate"]
In [62]: len(cons_data)                                                                                                                      
Out[62]: 257903
```

**Suggested solution:** 

Have an option for custom annotations (bed/bigwig) to produce summary statistics, eg something like this:

```
In [65]: pd.Series(cons_data.split("&"), dtype='f').describe()                                                                                          
Out[65]: 
count    15015.000000
mean         0.066185
std          0.141911
min          0.000000
25%          0.002000
50%          0.013000
75%          0.058000
max          0.997000
dtype: float64
```

**Comment by NavenM** [comment]
Hi @davmlaw ,

that sounds like a sensible solution, that we could potentially implement. I've added it to our backlog, but it might be a few months before we get to develop this.

Thanks

**Comment by davmlaw** [comment]
Hi, in VEP10 it looks like you added new ```--custom``` named arguments, ie ```format```, ```fields``` etc.

For conservation - I only really need the max, so perhaps this could be implemented as adding a new field:

summary_stat=max

Where if you have >1 result (ie variant spans multiple bases) you apply that summary statistic on the data before returning it

summary_stat options could be eg one of "max", "mean", "median", "min"

If anyone wants multiple summary stats, they could just run custom multiple times with different values for summary_stat

**Comment by davmlaw** [comment]
It's possible to calculate summary stats as you go (without keeping all of them in memory) - eg min/max is trivial, can do a rolling/moving mean - (though median is difficult)

If you did this rolling calculation, you would also likely solve #1414

**Comment by nuno-agostinho** [comment]
Hi @davmlaw,

Thanks for your suggestions!

I _really_ like your idea of expanding the new `--custom` features to include summary statistics. To extend on your suggestion, users could be able to select multiple statistics by using a delimiter such as `%` (for consistency with other `--custom` fields): `summary_stat=min%mean%max`.

I was also looking for an efficient median algorithm and found one that calculates the median using bins with `O(n)` of average running time complexity, thus avoiding to store all individual values: https://www.stat.cmu.edu/~ryantibs/median/

I will let you know when I have more updates on this.

Kind regards,
Nuno

**Comment by nuno-agostinho** [comment]
Hey @davmlaw, thanks again for the feature request!

This option was now merged to our codebase and will be available in the next release (e111).

If you have any other suggestions, feel free to open a new ticket.

Thanks and have a great day!

Best regards,
Nuno

**Comment by davmlaw** [comment]
Awesome, can't wait to try it out
