### ISSUE TITLE
VEP 104 Installation Test Fail

### ISSUE THREAD

**Issue by Jay-Leung** [Ensembl/ensembl-vep#1027]
## Describe the issue
Hi, I am very new to Ubuntu Linux and I tried installing VEP following the instructions on https://asia.ensembl.org/info/docs/tools/vep/script/vep_download.html#installer but it seems to fail at the test stage. I can't figure out what is wrong, could you take a look at the code?

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 104
- VEP Cache version: -
- Perl version: 5.30
- OS: Ubuntu
- tabix installed ? Yes

### Full VEP command line
```
git clone https://github.com/Ensembl/ensembl-vep.git
cd ensembl-vep
perl INSTALL.pl
```

### Full error message

Hello! This installer is configured to install v104 of the Ensembl API for use by the VEP.
It will not affect any existing installations of the Ensembl API that you may have.

It will also download and install cache files from Ensembl's FTP server.

Checking for installed versions of the Ensembl API...done

Setting up directories
Destination directory ./Bio already exists.
Do you want to overwrite it (if updating VEP this is probably OK) (y/n)? y
 - fetching BioPerl
 - unpacking ./Bio/tmp/release-1-6-924.zip
 - moving files
Attempting to install Bio::DB::HTS and htslib.

>>> If this fails, try re-running with --NO_HTSLIB

 - checking out HTSLib
fatal: destination path 'htslib' already exists and is not an empty directory.
 - building HTSLIB in ./htslib
In /home/jy96/Software/ensembl-vep/htslib
make: Nothing to be done for 'all'.
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.11 - moving files to ./biodbhts
 - making Bio::DB:HTS
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.11'
Building Bio-DB-HTS
x86_64-linux-gnu-gcc -I/home/jy96/Software/ensembl-vep/htslib -I/usr/lib/x86_64-linux-gnu/perl/5.30/CORE -DVERSION="2.11" -DXS_VERSION="2.11" -fPIC -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wno-unused-result -c -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -o lib/Bio/DB/HTS.o lib/Bio/DB/HTS.c
lib/Bio/DB/HTS.xs: In function ‘XS_Bio__DB__HTS__VCF__Header_fmt_text’:
lib/Bio/DB/HTS.xs:1770:5: warning: ‘bcf_hdr_fmt_text’ is deprecated: use bcf_hdr_format() instead [-Wdeprecated-declarations]
 1770 |     RETVAL = newSVpv(bcf_hdr_fmt_text(header, is_bcf, &len), 0);
      |     ^~~~~~
In file included from lib/Bio/DB/HTS.xs:59:
/home/jy96/Software/ensembl-vep/htslib/htslib/vcf.h:439:11: note: declared here
  439 |     char *bcf_hdr_fmt_text(const bcf_hdr_t *hdr, int is_bcf, int *len)
      |           ^~~~~~~~~~~~~~~~
ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Bio/DB/HTS/HTS.bs')
x86_64-linux-gnu-gcc -shared -L/usr/local/lib -fstack-protector-strong -o blib/arch/auto/Bio/DB/HTS/HTS.so lib/Bio/DB/HTS.o -L/home/jy96/Software/ensembl-vep/htslib -Wl,-rpath,/home/jy96/Software/ensembl-vep/htslib -lhts -lpthread -lz
x86_64-linux-gnu-gcc -I/home/jy96/Software/ensembl-vep/htslib -I/usr/lib/x86_64-linux-gnu/perl/5.30/CORE -DVERSION="2.11" -DXS_VERSION="2.11" -fPIC -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wno-unused-result -c -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -o lib/Bio/DB/HTS/Faidx.o lib/Bio/DB/HTS/Faidx.c
ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Bio/DB/HTS/Faidx/Faidx.bs')
x86_64-linux-gnu-gcc -shared -L/usr/local/lib -fstack-protector-strong -o blib/arch/auto/Bio/DB/HTS/Faidx/Faidx.so lib/Bio/DB/HTS/Faidx.o -L/home/jy96/Software/ensembl-vep/htslib -Wl,-rpath,/home/jy96/Software/ensembl-vep/htslib -lhts -lpthread -lz

Downloading required Ensembl API files
 - fetching ensembl
 - unpacking ./Bio/tmp/ensembl.zip
 - moving files
 - getting version information
 - fetching ensembl-variation
 - unpacking ./Bio/tmp/ensembl-variation.zip
 - moving files
 - getting version information
 - fetching ensembl-funcgen
 - unpacking ./Bio/tmp/ensembl-funcgen.zip
 - moving files
 - getting version information
 - fetching ensembl-io
 - unpacking ./Bio/tmp/ensembl-io.zip
 - moving files
 - getting version information

Testing VEP installation
./t/AnnotationSource_Database_Transcript.t ........... ok    
./t/Parser_Region.t .................................. ok    
./t/OutputFactory_JSON.t ............................. ok    
./t/Config.t ......................................... ok    
./t/VariantRecoder.t ................................. "my" variable $sth masks earlier declaration in same scope at Bio/EnsEMBL/DBSQL/TranslationAdaptor.pm line 607.
./t/VariantRecoder.t ................................. ok    
./t/bam_edit.t ....................................... 1/? /usr/bin/perl: symbol lookup error: ./HTS.so: undefined symbol: bam_hdr_destroy
./t/bam_edit.t ....................................... Dubious, test returned 127 (wstat 32512, 0x7f00)
All 9 subtests passed 
./t/AnnotationSource_File_BigWig.t ................... ok    
./t/AnnotationSource_File_GTF.t ...................... ok    
./t/AnnotationSource.t ............................... ok    
./t/Runner.t ......................................... 50/? /usr/bin/perl: symbol lookup error: ./HTS.so: undefined symbol: bam_name2id
./t/Runner.t ......................................... Dubious, test returned 127 (wstat 32512, 0x7f00)
All 73 subtests passed 
./t/Parser_SPDI.t .................................... ok   
./t/Parser_VCF.t ..................................... ok    
./t/Parser_HGVS.t .................................... ok    
./t/AnnotationSource_File.t .......................... ok    
./t/OutputFactory_Tab.t .............................. ok    
./t/InputBuffer.t .................................... ok    
./t/Utils.t .......................................... ok    
./t/AnnotationSource_Cache_RegFeat.t ................. ok    
./t/AnnotationSourceAdaptor.t ........................ ok    
./t/BaseVEP.t ........................................ ok    
./t/AnnotationSource_Database_RegFeat.t .............. ok    
./t/AnnotationSource_File_BED.t ...................... ok    
./t/AnnotationSource_Cache_Transcript.t .............. ok    
./t/AnnotationSource_Cache_Variation.t ............... ok    
./t/Parser_VEP_input.t ............................... ok    
./t/TranscriptTree.t ................................. ok    
./t/AnnotationSource_File_VCF.t ...................... ok    
./t/AnnotationSource_Database_Variation.t ............ ok    
./t/version.t ........................................ ok   
./t/Parser_ID.t ...................................... ok   
./t/Parser.t ......................................... ok     
./t/CacheDir.t ....................................... ok    
./t/AnnotationSource_File_GFF.t ...................... ok    
./t/AnnotationSource_Cache_VariationTabix.t .......... ok    
./t/OutputFactory.t .................................. ok     
./t/OutputFactory_VEP_output.t ....................... ok    
./t/OutputFactory_VCF.t .............................. Possible attempt to separate words with commas at ./t/OutputFactory_VCF.t line 580.
./t/OutputFactory_VCF.t .............................. ok    
./t/AnnotationSource_Cache.t ......................... ok   
./t/Stats.t .......................................... ok    
./t/FilterSet.t ...................................... ok     
./t/AnnotationSource_Database_StructuralVariation.t .. ok    

Test Summary Report
-------------------
./t/bam_edit.t                                     (Wstat: 32512 Tests: 9 Failed: 0)
  Non-zero exit status: 127
  Parse errors: No plan found in TAP output
./t/Runner.t                                       (Wstat: 32512 Tests: 73 Failed: 0)
  Non-zero exit status: 127
  Parse errors: No plan found in TAP output
Files=41, Tests=1691, 75 wallclock secs ( 0.08 usr  0.20 sys + 67.54 cusr  6.37 csys = 74.19 CPU)
Result: FAIL
Failed 2/41 test programs. 0/1691 subtests failed.

**Comment by helensch** [comment]
Hi @Jay-Leung 

The test failures appear to be related to HTSLib.

You noted that you had tabix installed. Was this installed separately from the VEP installation?

Please could you run the following 2 commands in the same environment you are running the VEP installer:

```perl -MBio::DB::HTS -e 'print "$Bio::DB::HTS::VERSION\n"'```

```perldoc -l Bio::DB::HTS```

Regards
Helen

**Comment by helensch** [comment]
Hi @Jay-Leung 

I am going to close this issue now.

If you have any further questions, please feel free to reopen it or create a new issue.

Regards
Helen
