### ISSUE TITLE
VEP is working slow

### ISSUE THREAD

**Issue by Kaskere** [Ensembl/ensembl-vep#1028]
Hello,
i try to run VEP on HPC with Singularity container system. My vcf files are around 11 Mb in size.
Annotation process is going extremely slow;  input file is not finished even after 4 days.

In the moment, my script looks like this:

```
#!/bin/bash -x

#PBS -N vep
#PBS -q batch
#PBS -l walltime=72:00:00
#PBS -l nodes=1:ppn=8


module load vep/101-sg

export inpath=/dir/
export outpath=/dir/
mkdir -p $outpath
chmod u+rwx $outpath
export reference=/mnt/home/references/hg38.fasta

for file in $inpath/*.vcf ;
do
        sample=$(basename $file ".vcf")
        echo $sample
        outfile=$outpath/$sample"_vep.vcf"
        singularity exec $vep \
        vep --database \
        vep --force_overwrite -i $file -o $outfile
done

```

Is there any additional option should be added to VEP script to make process faster?

Thank you!

**Comment by dglemos** [comment]
Hi @Kaskere,
There could be something wrong with your input files. Can you verify that your VCF file is valid? You can run it through VCF validator which is part of the VCFtools package - https://vcftools.github.io/
This issue could be related to https://github.com/Ensembl/ensembl-vep/issues/1005 
You could try running VEP with a subset of the variants included within one of your VCF file to see how much time the job takes to run and if the output is valid.

**Comment by Kaskere** [comment]
Hello,
problem was with--database fag, it is supposed for small vcfs

**Comment by dglemos** [comment]
Hello @Kaskere,
Connecting to the public database is slower than using the cache in offline mode. 
I'm glad the issue has been sorted. I'm going to close the ticket for now.

Best wishes,
Diana
