### ISSUE TITLE
Feature Request: Adding INFO details along with tab delimited annotations 

### ISSUE THREAD

**Issue by nkausthu** [Ensembl/ensembl-vep#1029]
This is an amazing framework which is really helpful for variant prioritization. However,  I couldn't figure out whether any feature is existing for adding the zygosity along with the tab format output file. I think it will be more useful for the users if you can provide the INFO details such as  zygosity, read numbers and read frequencies as a separate column  along with other annotations. awk can be used to parse this information but still if it comes along with the tool then this can be skipped. Looking forward to hearing from you.

**Comment by aparton** [comment]
Hi @nkausthu,

Thank you for your query. You can use our custom annotation feature to add additional information from VCF files to your VEP output. You can read more about how to do this here: http://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html

If there's anything else we can do to help, please don't hesitate to ask.

Kind Regards,
Andrew

**Comment by kvn95ss** [comment]
Hello,

If I'm not mistaken, I think @nkausthu is actually referring to data from Individual identifier part of vcf file.

Ex. if the vcf file is - 
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample_1	sample_2
11	5244444	rsxxx	T	A	99	PASS	AC=1,AF=0.00038,...	GT;DP	0/1;90	1/1;94
```

We want to get the info about ```0/1;90``` and ```1/1;94``` from the vcf file, which are on the sample field. Information from INFO can easily be used, however I could not see any way to get information from sample field. The layout of sample field is specified by FORMAT.

**Comment by jamie-m-a** [comment]
Hi @nkausthu,

We will investigate whether to implement the genotype info per sample in tab format, but as this information is currently provided through the VCF output option, this would be a low priority change and not likely to occur in the near future.

So, with that being the case, I will close off this ticket, but we will contact you if we do make this change.

Please feel free to reopen the ticket or open a new one if you have further questions.

Cheers,
Jamie.
