### ISSUE TITLE
Annotations missing in the VCF file

### ISSUE THREAD

**Issue by segoerge** [Ensembl/ensembl-vep#103]
Hi,

i'm working with VEP 90.6 and in some cases a few number of my variants are not annotated (they are getting no ANN field). 

I used the following command:

/tools/vep/vep -i input.vcf -o test.vcf --offline --vcf --merged --hgvs --fasta vep/homo_sapiens/90_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz --force_overwrite --fork 2 --variant_class --vcf_info_field ANN --numbers --total_length --canonical --exclude_predicted --allele_number --dir vep/

Two example variants, where the problem occurs:
4	190599092	rs62331402	G	A	175.77	.	AC=1;AF=0.5;AN=2;BaseQRankSum=-0.524;ClippingRankSum=0.0;DB;DP=10;ExcessHet=3.0103;FS=3.31;MLEAC=1;MLEAF=0.5;MQ=60.0;MQRankSum=0.0;QD=17.58;ReadPosRankSum=-2.287;SOR=0.105	GT:AD:DP:GQ:PL	0/1:2,8:10:38:204,0,38
4	190599152	rs62331403	G	T	81.77	.	AC=1;AF=0.5;AN=2;BaseQRankSum=-2.1;ClippingRankSum=0.0;DB;DP=8;ExcessHet=3.0103;FS=3.332;MLEAC=1;MLEAF=0.5;MQ=60.0;MQRankSum=0.0;QD=10.22;ReadPosRankSum=1.242;SOR=0.105	GT:AD:DP:GQ:PL	0/1:2,6:8:62:110,0,62

Surrounding variants are correctly annotated with "LOC105379514", but not these two. I looks like it is working for the intronic variants, but not for the exonic hits.

One that is correct:
4	190600672	rs72718638	C	T	131.9	.	AC=2;AF=1.0;AN=2;DB;DP=5;ExcessHet=3.0103;FS=0.0;MLEAC=2;MLEAF=1.0;MQ=60.0;QD=26.38;SOR=1.022;ANN=T|intron_variant&non_coding_transcript_variant|MODIFIER|LOC105379514|105379514|Transcript|NR_135513.1|lncRNA||2/2|NR_135513.1%3An.335-465C>T||||||||1||1||SNV|EntrezGene||YES|rseq_mrna_nonmatch&rseq_nctran_mismatch|RefSeq|C|C|	GT:AD:DP:GQ:PL	1/1:0,5:5:15:160,15,0

Best regards,
Sebastian

**Comment by willmclaren** [comment]
Thanks for the report. This was occurring because your input variant has an ALT allele that matches the reference base in the RefSeq transcript; VEP was then dismissing this as non-variant so not producing any output.

I've patched a fix to the ensembl-variation repo which contains the code for handling this; if you re-run INSTALL.pl you should be able to pick up the fix.
