### ISSUE TITLE
fail plugin with singularity 

### ISSUE THREAD

**Issue by quentin67100** [Ensembl/ensembl-vep#1032]
## Describe the issue
I try to use vep within a containers with singularity. I used the version 104.3. 
I download the cache file (human grch38 ensembl indexed version 104) and all the plugin but when i run vep i get this error: 
 Failed to compile plugin Carol: Can't locate Math/CDF.pm in @INC. 

It's not install in the container ? How could i solve this ? 

The exact command : 

```
module load singularity

singularity exec /shared/_NGS/Ressources/VEP/vep_104.3_docker/vep.sif \
vep \
--everything \
--fork ${SLURM_CPUS_PER_TASK} \
--input_file ${VCF_input_DIR}/${VCF_input} \
--output_file ${VCF_output_DIR}/${VCF_annotated} \
--stats_file ${VCF_output_DIR}/${stat_file} \
--cache --dir_cache ${cache_DIR} \
--dir_plugins ${plugin_DIR} \
--fasta ${Ref_genome} \
--merged \
--vcf \
--buffer_size 250000 \
--total_length \
--hgvsg \
--appris \
--check_existing \
--clin_sig_allele 0 \
--exclude_null_alleles \
--plugin AncestralAllele,${plugin_data_DIR}/homo_sapiens_ancestor_GRCh38.fa.gz \
--plugin Carol \
--plugin Condel,${plugin_data_DIR}/Condel/config,b \
--plugin Conservation,${plugin_data_DIR}/hg38.phastCons100way.bw \
--plugin ExACpLI \
--plugin GO \
--plugin LoFtool \
--plugin Mastermind,${plugin_data_DIR}/mastermind_cited_variants_reference-2021.04.02-grch38.vcf.gz \
--plugin DisGeNET,file=${plugin_data_DIR}/all_variant_disease_pmid_associations_final.tsv.gz,disease=1 \
--plugin NearestExonJB \
--plugin MaxEntScan,${plugin_data_DIR}/MaxEntScan,SWA,NCSS \
--plugin NearestGene \
--plugin Phenotypes,dir=${plugin_data_DIR} 
```

Thanks in advance

**Comment by dglemos** [comment]
Hi @quentin67100,
We don't include the dependencies of all plugins into the docker image to reduce the size of the image. 
You could try to install it with command:
`singularity exec /shared/_NGS/Ressources/VEP/vep_104.3_docker/vep.sif cpanm Math::CDF`

Best wishes,
Diana

**Comment by quentin67100** [comment]
Hi @dglemos 
I tried to install it, it seemed that it worked I got this message:
```
`--> Working on Math::CDF
Fetching http://www.cpan.org/authors/id/C/CA/CALLAHAN/Math-CDF-0.1.tar.gz ... OK
Configuring Math-CDF-0.1 ... OK
Building and testing Math-CDF-0.1 ... OK
Successfully installed Math-CDF-0.1
1 distribution `installed`
```
But if I re-run the vep command I still get an error: 
`WARNING: Failed to compile plugin Carol: Can't locate Math/CDF.pm in @INC (you may need to install the Math::CDF module)`

So i don't know how to solve the problem.

Thanks in advance, 

Quentin

**Comment by dglemos** [comment]
You probably need to install it on your machine. If you run the command:
`cpanm Math::CDF`

**Comment by quentin67100** [comment]
> You probably need to install it on your machine. If you run the command:
> `cpanm Math::CDF`

I also test this solution but without results. I don't know how to solve the problem. 
Maybe create a new image with the library directly installed ? But i don't know how to do that. 
Maybe Ensembl team could manage to docker image ? One "minimal" and one with all things needed to all plugins ?

**Comment by dglemos** [comment]
Do you still get the warning message?
`WARNING: Failed to compile plugin Carol: Can't locate Math/CDF.pm in @INC (you may need to install the Math::CDF module)`

**Comment by quentin67100** [comment]
> Do you still get the warning message?
> `WARNING: Failed to compile plugin Carol: Can't locate Math/CDF.pm in @INC (you may need to install the Math::CDF module)`

Yes

**Comment by quentin67100** [comment]
I finally found the solution. Add `export PERL5LIB=$PERL5LIB:$HOME/perl5` in my bashrc

**Comment by dglemos** [comment]
I'm glad you found a solution! 
I'm going to close the ticket but feel free to open a new issue if you have more questions. 

Best wishes,
Diana
