### ISSUE TITLE
perl INSTALL.pl

### ISSUE THREAD

**Issue by Nagasundaram620** [Ensembl/ensembl-vep#1035]
Hi, 
I tried to use this command line perl INSTALL.pl, however its show the following error, kindly suggest me to solve the error
C:\Users\ADMIN\ensembl-vep>perl INSTALL.pl
'which' is not recognized as an internal or external command,
operable program or batch file.
'which' is not recognized as an internal or external command,
operable program or batch file.
'which' is not recognized as an internal or external command,
operable program or batch file.
'which' is not recognized as an internal or external command,
operable program or batch file.
LWP::Simple failed (500), trying to fetch using HTTP::Tiny
ERROR: Failed last resort of using HTTP::Tiny to download https://api.github.com/repos/Ensembl/ensembl-vep

**Comment by aparton** [comment]
Hi @Nagasundaram620,

It looks like you're trying to install VEP on Windows, is that correct? VEP has been developed for UNIX-like environments, and while installation on Windows is possible then it's a more involved process.

Can you please tell me which OS version you're using? If you're using Windows 10, then it is possible to use Ubuntu with the Windows Subsystem for Linux, which is the easiest way to install VEP on Windows (https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6). Alternatively, we have a Docker image available that can be used - you can read more about running VEP with Docker here: https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker

Kind Regards,
Andrew

**Comment by jamie-m-a** [comment]
Hi @Nagasundaram620,

I'm going to close this issue now. If you need any furtehr information or help please reopen it, or raise a new issue.

Thanks,
Jamie.
