### ISSUE TITLE
Missing the checkout Funcgen

### ISSUE THREAD

**Issue by yueli8** [Ensembl/ensembl-vep#1038]
Hello,

Thank you for developing so nice software.

I followed the Perl API Installation video: <http://asia.ensembl.org/info/docs/api/api_installation.html>.

When I want to `poing_ensembl.pl`, it comes out `Missing the checkout Funcgen`. What can I do in this step?

Thank you in advance for great help!

Best regards,

Yue
```
export PERL5LIB=$HOME/src/ensembl/modules:$PERL5LIB
export PERL5LIB=$HOME/src/ensembl-variation/modules:$PERL5LIB
export PERL5LIB=$HOME/src/ensembl-compara/modules:$PERL5LIB
export PERL5LIB=$HOME/src/ensembl-funcgen/modules:$PERL5LIB
export PERL5LIB=$HOME/src/ensembl-tools/modules:$PERL5LIB
export PERL5LIB=$HOME/src/bioperl-1.6.924/:$PERL5LIB
```

```
Inspiron-3670:~$ . ~/.profile
jing@jing-Inspiron-3670:~$ echo $PERL5LIB
/home/jing/src/bioperl-1.6.924/:/home/jing/src/ensembl-tools/modules:/home/jing/src/ensembl-funcgen/modules:/home/jing/src/ensembl-compara/modules:/home/jing/src/ensembl-variation/modules:/home/jing/src/ensembl/modules:/home/jing/src/bioperl-1.6.924/:/home/jing/src/ensembl-tools/modules:/home/jing/src/ensembl-funcgen/modules:/home/jing/src/ensembl-compara/modules:/home/jing/src/ensembl-variation/modules:/home/jing/src/ensembl/modules:
```

```
Inspiron-3670:~/src/ensembl/misc-scripts$ ./ping_ensembl.pl
Installation is good. Connection to Ensembl works and you can query the human core database
ERROR: Error detected when connecting to Ensembl!
	Your core installation was good but supplementary modules cannot be found. If you wish to access these other Ensembl resources add the libraries to your PERL5LIB:
	Missing the checkout Funcgen
```

**Comment by NavenM** [comment]
Hi Yue,

does ensembl-funcgen exist at $HOME/src/ensembl-funcgen? If not, you can check it out from github using:

`cd $HOME/src/`
`git clone https://github.com/ensembl/ensembl-funcgen`

That should resolve the issue, but please let me know if it doesn't.

Thanks,
Marc

**Comment by yueli8** [comment]
Hello Marc,

Thank you so much for your response!

The folder of ensembl-funcgen already in my $Home/src folder.

Thank you again and really appreciated!

Best Regards,

Yue

```
Inspiron-3670:~/src$ git clone https://github.com/ensembl/ensembl-funcgen
fatal: destination path 'ensembl-funcgen' already exists and is not an empty directory.
```

**Comment by NavenM** [comment]
Hi Yue,

it's odd that you're getting the ping_ensembl.pl error message if ensembl-funcgen has already exists. Does ~/src/ensembl-funcgen/modules also exist? 

You could try running `git diff` from inside ~/src/ensembl-funcgen to see if there are differences in your cloned repository. If there are differences, could you post them here so I can help diagnose the issue?

Thanks,
Marc

**Comment by yueli8** [comment]
Hello Marc,

Thank you so much for your response!

The output as follows:

Thank you again and really appreciated!

Best Regards,

Yue

```
Inspiron-3670:~/src/ensembl-funcgen$ git diff
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
```

**Comment by NavenM** [comment]
Hi Yue,

it looks like there could have been problems during your initial cloning of the repository - git diff should have recognised it otherwise. The message you see after running git init is also indicative of this, as you should see something like `Reinitialized existing Git repository in /home/jing/src/ensembl-funcgen/.git/`.

I think your best option here is to remove your /home/jing/src/ensembl-funcgen directory and run the git clone command again. If successful, you should see no differences with `git diff`, and the following message when running `git status`:

```
$ git status
On branch release/105
Your branch is up to date with 'origin/release/105'.

nothing to commit, working tree clean
```

Providing you clone it into ~/src, then your PERL5LIB should be fine as it is.

That should work, but let me know if you have trouble.
Thanks
Marc

**Comment by yueli8** [comment]
Hello Marc,

Thank you so much for your great help! It works！

Really appreciated!

With all the best,

Yue

```
Inspiron-3670:~$ cd src/ensembl-funcgen/
Inspiron-3670:~/src/ensembl-funcgen$ git diff
Inspiron-3670:~/src/ensembl-funcgen$ git status
On branch release/104
Your branch is up to date with 'origin/release/104'.

nothing to commit, working tree clean
```
```
Inspiron-3670:~/src/ensembl/misc-scripts$ ./ping_ensembl.pl 
Installation is good. Connection to Ensembl works and you can query the human core database

```
