### ISSUE TITLE
VEP with singularity and --dir_cache

### ISSUE THREAD

**Issue by Kaskere** [Ensembl/ensembl-vep#1039]
Hello,
I try to run VEP using Singularity on Linux system. I downloaded cache file, extracted it in scratch folder, and tried to use it with --dir_cache option, but with error (message below).  How should I include downloaded VEP reference file in a containerized vep script?

thank you!

Error:

> __IMPORTANT INFORMATION:
> 
> If you have already set up a cache, use "--cache" or "--offline" to use it.
> 
> It is possible to use the public databases hosted at ensembldb.ensembl.org, but
> this is slower than using the cache and concurrent and/or long running VEP jobs
> can put strain on the Ensembl servers, limiting availability to other users._
> 

Here is my code:
```

#!/bin/bash -x


module load bio/vep/101-sg

export inpath=/dir
export outpath=/dir
mkdir -p $outpath
chmod u+rwx $outpath
export SINGULARITY_BINDPATH=$SINGULARITY_BINDPATH:/mnt/beegfs2/beegfs_scratch/usr/cache
export cache=/mnt/beegfs2/scratch/cache/homo_sapiens
for file in $inpath/*.vcf ;
do
        sample=$(basename $file ".vcf")
        echo $sample
        outfile=$outpath/$sample"_vep.vcf"
        singularity exec $vep \
        vep --fasta $reference \
        vep --dir_cache $cache -i $file -o $outfile
done
```

**Comment by dglemos** [comment]
Hi @Kaskere,
To be able to use the cache you need to use option `--cache` or `--offline`.
The flag `--dir_cache` specifies the directory where the cache is stored but doesn't switch on the cache. 

Best wishes,
Diana

**Comment by Kaskere** [comment]
> Hi @Kaskere,
> To be able to use the cache you need to use option `--cache` or `--offline`.
> The flag `--dir_cache` specifies the directory where the cache is stored but doesn't switch on the cache.
> 
> Best wishes,
> Diana

cache=/mnt/beegfs2/scratch/cache/homo_sapiens

ok, but I stored unarchived cache file from VEP in here: `cache=/mnt/beegfs2/scratch/cache/homo_sapiens`
and runned it with `vep --dir_cache $cache`

**Comment by dglemos** [comment]
Does the following command work for you?

`#!/bin/bash -x


module load bio/vep/101-sg

export inpath=/dir
export outpath=/dir
mkdir -p $outpath
chmod u+rwx $outpath
export SINGULARITY_BINDPATH=$SINGULARITY_BINDPATH:/mnt/beegfs2/beegfs_scratch/usr/cache
export cache=/mnt/beegfs2/scratch/cache/homo_sapiens
for file in $inpath/*.vcf ;
do
        sample=$(basename $file ".vcf")
        echo $sample
        outfile=$outpath/$sample"_vep.vcf"
        singularity exec $vep \
        vep --fasta $reference \
        vep --cache --dir_cache $cache -i $file -o $outfile
done`

**Comment by Kaskere** [comment]
> #!/bin/bash -x
> 
> 
> module load bio/vep/101-sg
> 
> export inpath=/dir
> export outpath=/dir
> mkdir -p $outpath
> chmod u+rwx $outpath
> export SINGULARITY_BINDPATH=$SINGULARITY_BINDPATH:/mnt/beegfs2/beegfs_scratch/usr/cache
> export cache=/mnt/beegfs2/scratch/cache/homo_sapiens
> for file in $inpath/*.vcf ;
> do
>         sample=$(basename $file ".vcf")
>         echo $sample
>         outfile=$outpath/$sample"_vep.vcf"
>         singularity exec $vep \
>         vep --fasta $reference \
>         vep --cache --dir_cache $cache -i $file -o $outfile
> done

Hello,
now I got error that cache dir is not found. But it IS there

```

MSG: ERROR: Cache directory /mnt/beegfs2/beegfs_scratch/user/homo_sapiens not found

STACK Bio::EnsEMBL::VEP::CacheDir::dir /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:311
STACK Bio::EnsEMBL::VEP::CacheDir::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:227
STACK Bio::EnsEMBL::VEP::CacheDir::new /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:115
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:132
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:203
STACK toplevel /opt/vep/src/ensembl-vep/vep:228
Date (localtime)    = Thu Aug 19 08:58:36 2021
Ensembl API version = 101
```

this is how downloaded cache looks
(base) [user@ui-1 user]$ ls /mnt/beegfs2/beegfs_scratch/user/homo_sapiens
104_GRCh38

**Comment by dglemos** [comment]
Your VEP version is 101, by default VEP is going to use the same version of the cache. However, the cache under `/mnt/beegfs2/beegfs_scratch/user/homo_sapiens` is version from release 104. 
You have two options:
- download cache version 101. Can be found here: http://ftp.ensembl.org/pub/release-101/variation/vep/ 
- update singularity to version 104 (the latest version)

**Comment by Kaskere** [comment]
> Your VEP version is 101, by default VEP is going to use the same version of the cache. However, the cache under `/mnt/beegfs2/beegfs_scratch/user/homo_sapiens` is version from release 104.
> You have two options:
> 
> * download cache version 101. Can be found here: http://ftp.ensembl.org/pub/release-101/variation/vep/
> * update singularity to version 104 (the latest version)

thank you
but which one is indexed from them

**Comment by dglemos** [comment]
The indexed caches can be found here: http://ftp.ensembl.org/pub/release-101/variation/indexed_vep_cache/

**Comment by dglemos** [comment]
I'm going to close the ticket but feel free to open a new issue if you have more questions.

Best wishes,
Diana
