### ISSUE TITLE
variant_recoder endpoint returns different hgvsg than original input

### ISSUE THREAD

**Issue by leexgh** [Ensembl/ensembl-vep#1040]
Hi Ensembl team,

I have a question about variant_recoder endpoint. Not sure if this is a good place to ask, please let me know if I should move this question to other places. Thank you!

## Describe the issue
https://grch37.rest.ensembl.org/variant_recoder/human/17:g.41276045_41276046del?content-type=application/json
If query `17:g.41276045_41276046del` in grch37 variant_recoder endpoint, it returns `NC_000017.10:g.41276047_41276048del` in hgvsg, which would be `17:g.41276047_41276048del`. Could you tell me why it's mapping to a different variant in response?

**Comment by at7** [comment]
Hi @leexgh,
this is expected behaviour and follows the 3' rule to shift insertions and deletions in repetitive regions to their most 3’ position of the reference sequence. You can find more information about the rule [here](http://varnomen.hgvs.org/recommendations/general/).

Best regards,
Anja
