### ISSUE TITLE
RFE: add ALFA variant frequencies to VEP caches

### ISSUE THREAD

**Issue by ntm** [Ensembl/ensembl-vep#1043]
Hi VEP devs,
I saw in the release notes of Ensembl 102 that it featured the "Addition of population frequency data from the NCBI Allele Frequency Aggregator (ALFA)".
It would be very useful if you could add these ALFA frequencies in the VEP caches, and something like --af_alfa to generate ALFA_AF* fields.
This is probably already on a TODO-list, I'm just opening this RFE so users like myself can track when it's implemented. Thanks!

**Comment by helensch** [comment]
Hi @ntm 

Thank you for your request to have ALFA frequencies include in the cache. We will take this into account when we review the cache contents - however this will be in the longer term and on the use cases.

In the shorter/medium term we will look at writing a  VEP Plugin to include the ALFA frequencies. I have created a ticket for this and will update this issue.

Regards
Helen

**Comment by jamie-m-a** [comment]
I'm closing this down as we consider implementing the alfa plugin as low priority, considering the current availability of extensive AF data from gnomAD 4.1
