### ISSUE TITLE
Docker curl command failing

### ISSUE THREAD

**Issue by idinsmore1** [Ensembl/ensembl-vep#1045]
## Describe the issue
I am attempting to install a cache and plugins into for the docker image on a linux server, but the curl command in perl INSTALL.pl is failing 

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

I run the docker container with 
```
docker run -t -i -v $HOME/vep_data:/opt/vep/.vep:Z -u $(id -u):$(id -g) ensemblorg/ensembl-vep:latest perl INSTALL.pl -a cfp -s homo_sapiens -y GRCh38 -g all
```
the :Z and -u commands are since I am on a redhat server running Centos 8
The output error is 
```
curl failed (000), trying to fetch using LWP::Simple
LWP::Simple failed (501), trying to fetch using HTTP::Tiny
ERROR: Failed last resort of using HTTP::Tiny to download https://api.github.com/repos/Ensembl/ensembl-vep
```
I'm not sure why this is happening as this is the docker image so everything should be good to go out of the box. Thanks for any help!

**Comment by helensch** [comment]
Hi @idinsmore1 

You may have a connectivity issue. See related ticked #1037

I have given some commands to try. Please modify them for the volume set up you are using.

Please could you try installing a single plugin e.g.  

```docker run -t -i -v $HOME/vep_data:/opt/vep/.vep ensemblorg/ensembl-vep perl INSTALL.pl -a cfp -s homo_sapiens -y GRCh38 -g CADD```

If this fails, please could you try downloading the file using ```curl``` to check connectivity e.g.
```docker run -t -i -v $HOME/vep_data:/opt/vep/.vep ensemblorg/ensembl-vep curl https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/104/CADD.pm```

Please could you also try running ```vep``` with a single variant without a cache e.g.
```docker run -t -i -v $HOME/vep_data:/opt/vep/.vep ensemblorg/ensembl-vep ./vep -id rs699 --database -o STDOUT```

Regards
Helen

**Comment by idinsmore1** [comment]
Hi Helen, 

Thanks for your response. The curl command works, however the single variant test fails. Looking at the linked issue that you sent, I believe my issue is coming from a firewall on the server. Thanks for your help!

Best,
Ian

**Comment by helensch** [comment]
Hi @idinsmore1 

I am going to close this issue now.

If you have any further questions, please feel free to reopen it or create a new issue.

Regards
Helen
