### ISSUE TITLE
Incorrect protein_start value?

### ISSUE THREAD

**Issue by onursumer** [Ensembl/ensembl-vep#105]
http://grch37.rest.ensembl.org/vep/human/hgvs/17%3Ag.37687472Gdel?content-type=application/json&xref_refseq=1&ccds=1&canonical=1&domains=1&hgvs=1&numbers=1&protein=1

For the given query, `protein_start` and `protein_end` values are reported as `1459` for the transcript `ENST00000447079`. Shouldn't it be `1461` instead?

```JavaScript
{
        "hgvsp": "ENSP00000398880.3:p.Gly1461AlafsTer38",
        "variant_allele": "-",
        "cdna_end": 4409,
        "refseq_transcript_ids": [
          "NM_015083.1",
          "NM_016507.2"
        ],
        "codons": "tGg/tg",
        "hgvsc": "ENST00000447079.4:c.4382del",
        "protein_end": 1459,
        "amino_acids": "W/X",
        "hgnc_id": 24224,
        "strand": 1,
        "gene_symbol": "CDK12",
        "exon": "14/14",
        "transcript_id": "ENST00000447079",
        "cdna_start": 4409,
        "gene_id": "ENSG00000167258",
        "hgvs_offset": 6,
        "cds_start": 4376,
        "canonical": 1,
        "protein_id": "ENSP00000398880",
        "protein_start": 1459,
        "biotype": "protein_coding",
        "gene_symbol_source": "HGNC",
        "cds_end": 4376,
        "consequence_terms": [
          "frameshift_variant"
        ],
        "ccds": "CCDS11337.1",
        "impact": "HIGH"
}
```

**Comment by jjgao** [comment]
... and for an insertion at the same genomic location, the protein location of `hgvsp` is differerent from the deletion above.

http://grch37.rest.ensembl.org/vep/human/hgvs/17%3Ag.37687471_37687472insG?content-type=application/json&xref_refseq=1&ccds=1&canonical=1&domains=1&hgvs=1&numbers=1&protein=1


```json
{
"hgvsp": "ENSP00000398880.3:p.Thr1463AsnfsTer50",
"variant_allele": "G",
"cdna_end": 4409,
"refseq_transcript_ids": [
"NM_015083.1",
"NM_016507.2"
],
"codons": "tgg/tGgg",
"hgvsc": "ENST00000447079.4:c.4382dup",
"protein_end": 1459,
"amino_acids": "W/WX",
"hgnc_id": 24224,
"strand": 1,
"gene_symbol": "CDK12",
"exon": "14/14",
"transcript_id": "ENST00000447079",
"cdna_start": 4408,
"gene_id": "ENSG00000167258",
"hgvs_offset": 7,
"cds_start": 4375,
"canonical": 1,
"protein_id": "ENSP00000398880",
"protein_start": 1459,
"biotype": "protein_coding",
"gene_symbol_source": "HGNC",
"cds_end": 4376,
"consequence_terms": [
"frameshift_variant"
],
"ccds": "CCDS11337.1",
"impact": "HIGH"
}
```

**Comment by sarahhunt** [comment]
Hi @onursumer, @jjgao 

The input position, 37687472 on chr17, is the first in a run of G's:
  
http://grch37.ensembl.org/Homo_sapiens/Location/View?r=17:37687471-37687485

Looking at the CDS and protein sequence in this area:
                                                                      
TGG GGG GGC CCA ACT CAG  
 Trp - Gly - Gly - Pro - Thr - Gln  
1459   ------------------  1464

VEP consequences, protein positions etc are based on the input positions and amino acid changes considered quite basically. The deletion is assigned a codon change of TGG-> TG and amino acid change of  Trp -> incomplete at position 1459. 

As you will know, HGVS rules require a change to be described at the 3' most position, so the following bases are checked. The deleted G is taken to be the last in the run, so the HGVS annotation uses the shifted protein position of 1461 giving GGC => GCC and  Gly->Ala

The insertion of the G means the new amino acid sequence diverges from the reference later. The additional G is added to the end of the run of G's, so the second Gly is still a Gly: 

Insertion: GGC => GGG,    Gly => Gly

Next codon CCA => CCC,  Pro => Pro

Next codon: ACT => AAC,     Thr =>Asn

so the position of the first changed aa at protein level is further along than for the insertion than for the deletion at 1463.

We realise this approach of potentially different coordinates for insertion and deletions is not ideal and plan to bring the positions assigned into line with the HGVS positions in the new year.

**Comment by jjgao** [comment]
@sarahhunt Thanks for looking into this and the detailed explanation. This makes sense.
