### ISSUE TITLE
VEP issue: ERROR: Cache assembly version (GRCh37) and database or selected assembly version (GRCh38) do not match

### ISSUE THREAD

**Issue by krunal2406** [Ensembl/ensembl-vep#1052]
## Describe the issue
VEP give errors even my query and reference has same assembly version

Command :$: ./vep -i examples/homo_sapiens_GRCh37.vcf --cache --refseq

**cache reference details while running install.pl**
? 458
NB: Remember to use --refseq when running the VEP with this cache!
 - downloading ftp://ftp.ensembl.org/pub/release-104/variation/indexed_vep_cache/homo_sapiens_refseq_vep_104_GRCh37.tar.gz
 - unpacking homo_sapiens_refseq_vep_104_GRCh37.tar.gz
 - converting cache, this may take some time but will allow VEP to look up variants and frequency data much faster
 - use CTRL-C to cancel if you do not wish to convert this cache now (you may run convert_cache.pl later)
2021-09-15 18:17:16 - Processing homo_sapiens_refseq
2021-09-15 18:17:16 - Processing version 104_GRCh37
2021-09-15 18:17:16 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this
2021-09-15 18:17:16 - No unprocessed types remaining, skipping
2021-09-15 18:17:16 - All done!
## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
-Ensemble version: 104
- Perl version:  5.26
- OS: Ubuntu
- tabix installed yes Version: 1.13

### Full VEP command line
```
./vep -i examples/homo_sapiens_GRCh37.vcf --cache --refseq

### Full error message
-------------------- EXCEPTION --------------------
MSG: ERROR: Cache assembly version (GRCh37) and database or selected assembly version (GRCh38) do not match

 You can use --offline to avoid a database connection entirely

STACK Bio::EnsEMBL::VEP::CacheDir::dir /home/krunal/Krunal/Software/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:340
STACK Bio::EnsEMBL::VEP::CacheDir::init /home/krunal/Krunal/Software/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:227
STACK Bio::EnsEMBL::VEP::CacheDir::new /home/krunal/Krunal/Software/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /home/krunal/Krunal/Software/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:115
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/krunal/Krunal/Software/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/krunal/Krunal/Software/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /home/krunal/Krunal/Software/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::run /home/krunal/Krunal/Software/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel ./vep:232
Date (localtime)    = Wed Sep 15 21:34:51 2021
Ensembl API version = 104
---------------------------------------------------


### Data files (if applicable)
i used default example file
examples/homo_sapiens_GRCh37.vcf

**Comment by helensch** [comment]
Hi @krunal2406 

As you are using human GRCh37 and cache,  you will need to  add ```--port 3337``` to use the GRCh37 database, or ```--offline``` to avoid database connection entirely.

Further information can be found at:
https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#assembly

Please let me know if you have any futher queries on this.

Regards
Helen

**Comment by krunal2406** [comment]
Thanks Helen,

It works :)

**Comment by helensch** [comment]
Hi @krunal2406 

I am going to close this issue now.

If you have any further questions, please feel free to reopen it or create a new issue.

Regards
Helen
