### ISSUE TITLE
Annotation very slow for certain genes

### ISSUE THREAD

**Issue by emkoch** [Ensembl/ensembl-vep#1054]
## Describe the issue
Annotation is much faster in some regions of the genome than in others.
For instance, all variants in the giant protein TTN annotate much much faster than those in the smaller GRIN2B. This doesn't seem to be related to any of the plugins I am using. 

### System
- VEP version: 104
- VEP Cache version: 104
- Perl version: 5.26.2
- OS: CentOS
- tabix installed yes

### Full VEP command line
```
{vep_exec} --cache --dir_cache {vep_cache} --dir_plugins {vep_plugins} --plugin AncestralAllele,{ancestral} --everything --force_overwrite --buffer_size 10000 --fork 8 --no_stats --verbose -i {params.fname} -o STDOUT

**Comment by helensch** [comment]
Hi @emkoch 

Thank you for your query.

Information on "Getting VEP to run faster"  described  at 
https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#faster

If you run without the --everything flag do you still see the difference?

Are the number of variants, type of variants and consequence of variants being run for TTN and GRIN2B similar?

Regards
Helen
