### ISSUE TITLE
Somatic variant annotation strategy

### ISSUE THREAD

**Issue by gudeqing** [Ensembl/ensembl-vep#1055]
Hi, 
From my point of view, somatic and germline mutation should be taken together to infer changes in every transcript, and I do think this should be the best way to annotate somatic variants.  However, I do not see any variant annotation tool that provide such a function.  Haplosaurus is the most closely tool I am looking for, it annotates variant by examining the whole transcript, however, it  still ignores the germline variants that may contribute to the final changes of a transcript. So, I want to know if the VEP group will move on to this related issue. Thanks.

Best wishes!

**Comment by dglemos** [comment]
Hi @gudeqing,
I'm not sure I understand what you mean. VEP does not take into account if a variant is somatic or germline. It annotates variants (germline and/or somatic) separately, not taking into account other variants in the same transcript. Do you mean VEP ignores some variants? Or you mean VEP should behave more like Haplosaurus and take other variants into account? 
Could you provide an example of a use case?

**Comment by gudeqing** [comment]
Yes, I think VEP should behave more like Haplosaurus and take other variants into account.  In most cases, in a tumor-normal paired analysis, we get somatic variants and germline variants separately, And, when comes to variant annotation, currently, most researchers will annotate somatic variants one by one with tools like vep, annovar and snpeff.  However, a long transcript may contains multiple mutations that contribute to the final impact together but not alone.  I think Haplosaurus is the tool(maybe the only known tool) that tries to fill the gap. And, I hope Haplosaurus could go further, such as takes both somatic variant vcf and germline variant vcf  as inputs and infers mutation impact of each transcript.

**Comment by dglemos** [comment]
I will close off this ticket, but we will contact you when the change is made.
Please feel free to reopen the ticket or open a new one if you have further questions.

Best wishes,
Diana
