### ISSUE TITLE
Can't use an undefined value as an ARRAY reference

### ISSUE THREAD

**Issue by Hardlearn** [Ensembl/ensembl-vep#1057]
## Describe the issue
Hi,

I am trying to use haplo to construct the protein sequence from the vcf file of sars-cov-2 S protein, and hit a bug I couldn't solve. Or Is there any other way to turn my VCF provide here into a protein sequence?
 

## Additional information
But there is no problem when I deal with human vcf file, so could be something wrong with the original vcf?

### System
- VEP version: 104
- VEP Cache version: 104: homo_sapiens/101: sars_cov_2 
- Perl version: 5.26
- OS: Ubuntu
- tabix installed: yes

### Full VEP command line
sars_cov_2:
```
 haplo -i nCoV_S.vcf -o S_protein.json --cache --dir_cache /data/user/huanghr/database/vep_sars/ --json -offline --cache_version 101 --species sars_cov_2 
```
human:
```
haplo -i /data/user/huanghr/project/ACE2_COV19/X.15494566-15607236.ALL.chrX_GRCh38.genotypes.20170504.vcf -o /data/user/huanghr/project/ACE2_COV19/ACE2_protein.json --cache --dir_cache
/data/user/huanghr/database/vep_GRCh38/ --json --offline --cache_version 104
```
### Full error message
> Possible precedence issue with control flow operator at /home/huanghr/miniconda3/envs/Python3.6/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
Can't use an undefined value as an ARRAY reference at /home/huanghr/miniconda3/envs/Python3.6/share/ensembl-vep-104.3-0/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 782, <__ANONIO__> line 2.
(Python3.6) huanghr@mu01:/data/user/huanghr/project/ACE2_COV19/nCoV$ Can't use an undefined value as an ARRAY reference at /home/huanghr/miniconda3/envs/Python3.6/share/ensembl-vep-104.3-0/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 782, <__ANONIO__> line 2.

### Data files (if applicable)
They include:
- The input file: (https://download.cncb.ac.cn/GVM/Coronavirus/vcf/) and cut the specific region using tabix
- The cache file: http://ftp.ensemblgenomes.org/pub/viruses/variation/indexed_vep_cache/sars_cov_2_vep_101_ASM985889v3.tar.gz 

Thanks a lot

**Comment by dglemos** [comment]
Hi @Hardlearn,
Thank you for all the details, however I cannot download the input file. Could you send a sample of the input with only the variants of interest?

**Comment by Hardlearn** [comment]
Thank you for your reply, and the file in attachment is the compressed VCF file.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ensembl/ensembl-vep"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月23日(星期四) 晚上10:34
***@***.***&gt;;
抄送:&nbsp;"Haoran ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ensembl/ensembl-vep] Can't use an undefined value as an ARRAY reference (#1057)





 
Hi @Hardlearn,
 Thank you for all the details, however I cannot download the input file. Could you send a sample of the input with only the variants of interest?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


从QQ邮箱发来的超大附件

nCoV_S.vcf.gz (38.01M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7638396525bea9cc3085172a1561041e02595b500a560e09190b5c03524c02020d5914045051021c510b01500b005755575e5852336c365f77576f3a604f405252165e1f335c&t=exs_ftn_download&code=489e3a61

**Comment by Hardlearn** [comment]
Hi, have you found where the problem is? Looking forward to your reply.

**Comment by dglemos** [comment]
Hi, 
Thank you for sending the input file again. 
The issue is in your input VCF which is missing the header. You can check if the VCF is valid with vcf-validator https://vcftools.github.io/perl_module.html#vcf-validator 
Also, the genotype data doesn't look correct. In the VCF file:
`GT      0       0 ...`
Haplosaurus uses phased genotypes which should be something like:
`GT      0|0       0|0 ...`

**Comment by Hardlearn** [comment]
> Did you have an opportunity to modify your file and try running Haplosaurus again?

Unfortunately, I still failed to do so even though I added the header for my input VCF.

**Comment by dglemos** [comment]
Could you send the first lines of the new input file?
