### ISSUE TITLE
EGFR select NM_005228.5 but not NM_005228.3

### ISSUE THREAD

**Issue by asmlgkj** [Ensembl/ensembl-vep#1061]
## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 104
- VEP Cache version:104
- Perl version: 5.26
- OS: CentOS
- tabix installed yes

in LRG, egfr select 	NM_005228.3, but vep is NM_005228.5, annovar is NM_005228.4, is there any select standards,
<>
it seems that  .5 is the most updated in NCBI, how can I get all the newest NM minor version
thanks a lot

**Comment by dglemos** [comment]
Hi @asmlgkj,
The RefSeq transcripts available in VEP are imported from NCBI. We try to keep the data updated. 
To download the latest transcript IDs, you can use the file GFF or GTF file available here: https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/annotation_releases/109.20210514/GCF_000001405.39_GRCh38.p13/

**Comment by asmlgkj** [comment]
thanks  a lot
@dglemos
