### ISSUE TITLE
VEP cache error

### ISSUE THREAD

**Issue by quentin67100** [Ensembl/ensembl-vep#1062]
Hello,

When i try to use vep 104.3 with the option --cache i get this error 
MSG: ERROR: No cache found for homo_sapiens, version 103

Even if i add the option --dir_cache to point to the directory with cache. 
The cache is here : $HOME/.vep/homo_sapiens/104_GRCh38

What could be the issue and how to solve it ?

**Comment by quentin67100** [comment]
Hi @helensch 

ensembl-vep          : 104.3

Command example: 
```
vep \
--everything \
--fork ${SLURM_CPUS_PER_TASK} \
--input_file ${VCF_input} \
--output_file ${VCF_output_DIR}/${vcf_output} \
--stats_file ${VCF_output_DIR}/${stat_file} \
-v \
--format vcf \
--cache \
--offline \
--buffer_size 20000 \
--fasta ${REF_Genome} \
--vcf \
--compress_output gzip \
--nearest symbol \
--total_length \
--no_escape 
```

I precise that it's a conda based module from an hpc environnement. I also add a singularity image from the docker image and with this and the same cache it's work... So i don't understand

**Comment by helensch** [comment]
Hi @quentin67100 

Thank you for the information. As it works with a docker image, it is probably related to how vep was installed for the command line version.  

If as you suggest it is  Bioconda installation, we don't officially support installation through Bioconda. While an ensembl-vep Bioconda recipe exists, it wasn't set up by us so you may need to ask them for assistance.

Having said that if  ./vep only reports version information from ensembl-vep and does not report versions for ensembl, ensembl-funcgen, ensembl-io, ensembl-variation, it  suggests that there is an installation of the Ensembl API that is being used. Please can you check whether  the ensembl modules are in your PERL5LIB.

Please can you also check if there are multiple perl versions in your $PATH with ```which -a perl```

Regards
Helen

**Comment by helensch** [comment]
Hi @quentin67100 

I am going to close this issue now.

If you have any further questions, please feel free to reopen it or create a new issue.

Regards
Helen
