### ISSUE TITLE
Cache Size Not Shown Before Download Starts

### ISSUE THREAD

**Issue by DarioS** [Ensembl/ensembl-vep#1067]
INSTALL.pl should show the size of cache files in brackets before the user starts a download. Only filename shown.

```
455 : zosterops_lateralis_melanops_vep_104_ASM128173v1.tar.gz
456 : homo_sapiens_merged_vep_104_GRCh37.tar.gz
457 : homo_sapiens_merged_vep_104_GRCh38.tar.gz
458 : homo_sapiens_refseq_vep_104_GRCh37.tar.gz
459 : homo_sapiens_refseq_vep_104_GRCh38.tar.gz
460 : homo_sapiens_vep_104_GRCh37.tar.gz
461 : homo_sapiens_vep_104_GRCh38.tar.gz
```

I wasn't expecting it to bomb my home directory (12 GB hard limit).

```
Cannot write to Local file /users/stgrad/dario/.vep/tmp/homo_sapiens_vep_104_GRCh38.tar.gz: Input/output error
 at INSTALL.pl line 1240.
 
 ~$ quota -v
Disk quotas for user dario (uid 3509):
Filesystem       blocks   quota   limit   grace   files   quota   limit   grace
dora:/users     11341044* 6000000 12000000   7days   93735  500000 1000000
```

The download is automatically deleted when it hits the limit and I am under the limit automatically. The quota output above is from a few seconds before that happened.

**Comment by nuno-agostinho** [comment]
Hello @DarioS,

Thanks for your suggestion! We will show the file size of cache files when running `INSTALL.pl` in release 107.

Please feel free to open a new issue if you have further suggestions or issues.

Kind regards,
Nuno
