### ISSUE TITLE
adding individuals to VEP output

### ISSUE THREAD

**Issue by rsalz** [Ensembl/ensembl-vep#1069]
I'm annotating a file that contains a large amount of individuals. I would like to see back in my VEP output _which_ individuals had the variant (annotation) in question. I know that there is an option `--individual all`, which I use, but due to the large number of individuals, I have a huge output file where there are lots of lines that are completely the same except for the 'IND' field. 

Wouldn't it make sense to just list the individuals in the Extra section instead of put out a separate line for each individual? Or is there a reason you guys don't do this?

**Comment by rsalz** [comment]
In each line of the output, there is something along the lines of:

IND=PERSON1;ZYG=HOM;IMPACT=MODIFIER;STRAND=-1; ...

I would prefer if you had an option where you could have more than 1 individual in the line, such as:

IND=PERSON1;ZYG=HOM;IND=PERSON2;ZYG=HOM;IND=PERSON3;ZYG=HOM;IMPACT=MODIFIER;STRAND=-1; ...

Since everything after the 'IND/ZYG' part is the same for a given variant!

I am annotating with a combined VCF of 150 people. Not only is my output file huge but the run time is much longer. There has to be a way to get information about which individuals have a particular variant in the VEP run without outputting 1 line per individual (considering all other information is identical)...

**Comment by dglemos** [comment]
Thank you for your example. 
It makes sense to optionally return all individuals in the same line without duplication of variants in the output. We will create a plan to add an option in the future to report individuals in the same output line. 

Best wishes,
Diana

**Comment by ntm** [comment]
Hi,
alternately you could ask VEP to output VCF, you'll get the annotations in the CSQ= INFO field and keep the genotypes of all your individuals in the data columns following FORMAT .
Having multiple instances of IND= and ZYG= tags with different values doesn't seem right.

**Comment by dglemos** [comment]
In the VCF output we get the genotypes in the column FORMAT however when using the option `--individuals` variants are being reported multiple times which we want to avoid.  

> Having multiple instances of IND= and ZYG= tags with different values doesn't seem right.

That is correct, we should avoid duplication of keys (IND or ZYG). All the individuals could be reported as a list in the same tag/key.

**Comment by dglemos** [comment]
We plan on changing the behaviour of the option `--individuals` in the next release at the end of the year. The option will return all individuals in the same line to avoid duplication in the output. 

I'm going to close this issue but feel free to re-open it if you find more issues.

Best wishes,
Diana

**Comment by dglemos** [comment]
Hi @ntm,
Just to let you know we have decided to include this functionality in a new option called `--individual_zyg`.
The new option will return all individuals' zygosity in the same line, for example: `ZYG=ind1:HOM,ind2:HET`.
The behaviour of option `--individuals` will stay the same.

Best wishes,
Diana
