### ISSUE TITLE
The results are inconsistent

### ISSUE THREAD

**Issue by zambofd** [Ensembl/ensembl-vep#107]
I run the vep with all my sites and only one site. But feature is different between the two results. May I have the reason?
1_89946888_A/G  1:89946888      G       ENSSSCG00000004432      ENSSSCT00000004897      Transcript      synonymous_variant 
1_89946888_A/G  1:89946888      G       ENSSSCG00000004432      ENSSSCT00000004897      Transcript      stop_retained_variant

**Comment by willmclaren** [comment]
Can you please provide two sets of input, each of which generates the different outputs? Also the command you are running would be helpful.

**Comment by zambofd** [comment]
My apologies for the delay in responding. 
The two sets: 
[test1.txt](https://github.com/Ensembl/ensembl-vep/files/1524631/test1.txt)
[test2.txt](https://github.com/Ensembl/ensembl-vep/files/1524632/test2.txt)
The command:
~/biosoft/ensembl-vep/vep --species sus_scrofa --assembly Sscrofa10.2 --format ensembl --input_file input.txt --output_file output.vep.txt --cache --dir $HOME/.vep/ --fasta /home/zyb/.vep/sus_scrofa/87_Sscrofa10.2/Sus_scrofa.Sscrofa10.2.dna.toplevel.fa.gz --cache_version 87 --sift b  --distance 5000 --gene_phenotype --regulatory --total_length --numbers --domains --symbol --appris --biotype --ccds --tsl --tab --pick --offline --hgvs
Thank you first.

**Comment by willmclaren** [comment]
The input at the quoted position is different in each file:

```
$ grep 89946888 test1.txt
1       89946888        89946888        A/G     -1
$ grep 89946888 test2.txt
1       89946888        89946888        A/G     +
```

The input in `test1.txt` is on the reverse strand as denoted by `-1`; in `test2.txt` it is on the forward strand as denoted by `+`.

This explains the difference in the called consequence types.

**Comment by zambofd** [comment]
The first line was extracted from  my result. The second line was what I input. Why a site on  the forward strand  is annotated on the reverse strand? Can VEP only use the input strand infomation intead of the strand info in annotated file?
Thank you!

**Comment by sarahhunt** [comment]
Hi @zambofd - are the two files you provided (test1.txt and test2.txt) the inputs you used in the different VEP analyses? If so, as Will says, they specify different strands for the variant so will be interpreted differently. 

The strand is provided as '-1' in test1.txt, so the alternate allele is complimented - 'C' will be considered.
The strand is provided as '+' in test1.txt, so the alternate allele 'G' is considered.
