### ISSUE TITLE
No canonical flags 

### ISSUE THREAD

**Issue by Madelinehazel** [Ensembl/ensembl-vep#1071]
## Describe the issue
I have specified the --canonical flag, but the flag is not present anywhere in the output vcf.

## Additional information
Is this because I am annotating against both RefSeq and Ensembl transcripts (i.e. --merged)?

### System
- VEP version: [104] 
- VEP Cache version: [104]
- OS: [linux]
- tabix installed ? yes

### Full VEP command line
```
vep --vcf -o stdout -i {incalls} {threadsprefix} --species homo_sapiens --no_stats --cache --offline {dirprefix} {dircacheprefix} --symbol --numbers --biotype --total_length --canonical --gene_phenotype --ccds --uniprot --domains --regulatory --protein --tsl --appris --af --max_af --af_1kg --af_esp --af_gnomad --pubmed --variant_class --allele_number {fastaprefix} {humanancestorfastaprefix} {maxentscanprefix} --plugin SpliceRegion --sift b --polyphen b --hgvs --shift_hgvs 1 --merged  | sed '/^#/! s/;;/;/g' {outprefix} > {outcalls}"
```

**Comment by helensch** [comment]
Hi @Madelinehazel 

Please could you provide an example of a variant where the canonical flag is not being returned in the output VCF.

The canonical flag will be returned when using the ```--merged ``` option.

For example the variant ```1  230710048  rs699  A  G``` will flag transcripts as CANONICAL. Example given below is from tab-output for easier viewing
```
## Uploaded_variation : Identifier of uploaded variant
## CANONICAL : Indicates if transcript is canonical for this gene
#Uploaded_variation	Location	Allele	Gene	Feature	CANONICAL
rs699	1:230710048	G	ENSG00000135744	ENST00000366667	YES
rs699	1:230710048	G	ENSG00000244137	ENST00000412344	YES
rs699	1:230710048	G	183	NM_001382817.3	YES
```

The header information in the VCF file will describe the format of the CSQ info field, and the position of the CANONICAL flag.
https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#vcfout

During testing, the fields output in the CSQ can be specified using the ```--fields``` option
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_fields e.g.

For example using:
``` --fields "Allele,Gene,Feature_type,Feature,CANONICAL"```

The VCF header will include
```##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Gene|Feature_type|Feature|CANONICAL">```

and CANONICAL flag can be seen for example in
```CSQ=G|ENSG00000135744|Transcript|ENST00000366667|YES```


Regards
Helen

**Comment by Madelinehazel** [comment]
Hi Helen, 
Thank you for the detailed response! I had thought that that flag itself was CANONICAL, and when grepping for this did not return any variants, thought that it was not annotated- I see now that the flag is YES, and is indeed incorporated into the annotations. 
Thanks
Madeline
