### ISSUE TITLE
filter_vep --only_matched doesn´t work as I expected

### ISSUE THREAD

**Issue by MGCarta** [Ensembl/ensembl-vep#1076]
Hello! I encounter this warning when I try to filter with filter_vep a vcf file already annotated by vep:
**MSG: The script 'filter_vep' couldn't find the VEP annotations INFO field CSQ in 28 lines of the input file**.

In addition the option --only_matched doesn´t work as I expected and I don´t know if is related to the problem above. 
I would like to filter only the consequences reported below and keep the blocks that are not included in the filter. 

### System
- VEP version: 104.3
- Perl version: perl 5, version 26
- OS: Ubuntu

### Full VEP command line
```
filter_vep -i $1 \
	--force_overwrite \
	--filter "(Consequence is transcript_ablation or Consequence is splice_acceptor_variant or Consequence is splice_donor_variant or Consequence is stop_gained or Consequence is frameshift_variant or Consequence is stop_lost or Consequence is start_lost or Consequence is inframe_insertion or Consequence is inframe_deletion or Consequence is missense_variant or Consequence is protein_altering_variant or Consequence is splice_region_variant or Consequence is incomplete_terminal_codon_variant or Consequence is start_retained_variant or Consequence is stop_retained_variant or Consequence is coding_sequence_variant or Consequence is NMD_transcript_variant or COnsequence is TFBS_ablation or Consequence is TFBS_amplification or Consequence is TF_binding_site_variant or Consequence is feature_elongation or Consequence is feature_truncation or Consequence is intergenic_variant or Consequence is regulatory_region_ablation or Consequence is regulatory_region_amplification or Consequence is regulatory_region_variant) and FILTER is PASS" \
	--only_matched  \
	-o /research/storage-normal/vep/.vep/output/filter_vep_lost/filter_${2}
```

### Full error message
> -------------------- EXCEPTION --------------------
MSG: ERROR: Could not write to output file /research/storage-normal/vep/.vep/

STACK Bio::EnsEMBL::VEP::BaseRunner::get_output_file_handle /research/storage-normal/bioinfo/miniconda3/envs/vep104/share/ensembl-vep-104.3-1/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:221
STACK Bio::EnsEMBL::VEP::Runner::run /research/storage-normal/bioinfo/miniconda3/envs/vep104/share/ensembl-vep-104.3-1/modules/Bio/EnsEMBL/VEP/Runner.pm:201
STACK toplevel /research/storage-normal/bioinfo/miniconda3/envs/vep104/bin/vep:232
Date (localtime)    = Thu Nov 11 14:31:35 2021
Ensembl API version = 104
---------------------------------------------------

### Data files (if applicable)
They include:
You can find attached the vcf file already processed with vep and that I want to filter with filter_vep with the command that I wrote.

Thank you very much!

**Comment by MGCarta** [comment]
[output_vep.txt](https://github.com/Ensembl/ensembl-vep/files/7521115/output_vep.txt)

**Comment by dglemos** [comment]
Hi @MGCarta,
In your input file you have 28 variants without VEP annotation that is why the command throws the warning. 
For example, these variants are not annotated by VEP:
```
chrY	7929812	.	C	CT	47	LowDP;LowVarSupport	DP=2	GT:GQ:AD:DP:VF:NL:SB:NC:AQ:GQX	./.:0:0,2:2:1.000:25:-25.0205:0.0000:14.938:0
chrY	17951649	.	T	A	39	LowDP;LowVarSupport	DP=5	GT:GQ:AD:DP:VF:NL:SB:NC:AQ:GQX	./.:0:3,2:5:0.400:25:-20.2763:0.1667:16.036:0
chrY	18560721	.	T	C	41	LowDP;LowVarSupport	DP=4	GT:GQ:AD:DP:VF:NL:SB:NC:AQ:GQX	./.:0:2,2:4:0.500:25:-22.0305:0.0000:17.391:0
chrY	21082230	.	A	T	35	LowDP;LowVarSupport	DP=8;ANT=ENST00000454875.1|intron_variant&non_coding_transcript_variant|YES|ENST00000454875.1:n.75-43139T>
```
Which VEP command did you run?

**Comment by dglemos** [comment]
I noticed you are filtering only variants that pass the filter `FILTER is PASS`. In your file only two variants match this filter and none of these variants match the consequences you want to filter. 

If you want to keep the blocks that are not included in the filter, you shouldn't use flag `--only_matched`. This option will remove blocks that do not pass the filters.

**Comment by MGCarta** [comment]
Hi @dglemos , thank you for your clarification about the use of --only_matched! 
The vep command that I used is the following:
vep --offline \
	--cache \
	--assembly GRCh37 \
	--refseq \
	--force_overwrite \
	--hgvs \
	--numbers \
	--pubmed \
	--no_intergenic \
	--clin_sig_allele 1 \
	--af \
	--af_1kg \
	--af_gnomad \
	--vcf --filter_common \
	--freq_freq 0.025 \
	--dir /vep/.vep \
	--fasta /homo_sapiens_refseq/104_GRCh37/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz \
	--input_file $1 \
	--output_file /path/to/vep_output/vep_output_ref_${2}

**Comment by dglemos** [comment]
The command looks alright. The error message you posted above is thrown when you run the VEP command?
```
-------------------- EXCEPTION --------------------
MSG: ERROR: Could not write to output file /research/storage-normal/vep/.vep/
```

**Comment by MGCarta** [comment]
No, this error message only occurred because I gave the wrong path to the output folder, never mind. 
Instead the message that appears when i run vep is this one:

**2021-11-12 08:48:11 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this**

 and it seems correct to me.

**Comment by dglemos** [comment]
The message is related to the RefSeq cache, nothing wrong with that. 

Some variants are not being annotated by VEP because of this option `--no_intergenic` - the intergenic variants are the ones without annotation. For the filter_vep to work you can do one of the following:
- remove `--no_intergenic` from the VEP command and filter these variants with filter_vep 
- include `--no_intergenic` in the command and delete these lines from the VCF file before running the filter_vep

**Comment by MGCarta** [comment]
@dglemos  thank you for the explanation, now it´s clearer!

**Comment by dglemos** [comment]
I'm glad it's clearer now. 
I'm going to close this issue but feel free to open a new one if you have more questions.

Best wishes,
Diana
