### ISSUE TITLE
Issue when running VEP using custom annotation

### ISSUE THREAD

**Issue by AnneBoshove** [Ensembl/ensembl-vep#1079]
When trying to run VEP with a custom gff file, it prints lots of lines including:
"Use of uninitialized value $phase in numeric eq (==) at /home/WUR/bosho009/miniconda3/envs/vep/share/ensembl-vep-104.3-1/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm line 784, <__ANONIO__> line 90033." 
Sometimes instead of $phase it's $exon_phase or $start_phase.

And finally ends after about a minute with:
"Can't call method "seq" on an undefined value at /home/WUR/bosho009/miniconda3/envs/vep/share/ensembl-vep-104.3-1/Bio/EnsEMBL/Transcript.pm line 827, <__ANONIO__> line 90033."

Some output is produced which seems to be correct, but the vcf file already ends somewhere in chromosome 1. I checked the sv it should be predicting next, but this was not anything different from the ones it did succesfully predict beforehand. 
When running vep normally without a custom annotation it works perfectly fine. 

VEP version: 104.3
Perl version: 5.26.2

Command: perl /home/WUR/bosho009/miniconda3/envs/vep/bin/vep -i ../syri/LWvsTemposyri.vcf --gff ../LargeWhite.gff.gz --fasta ../minimap/LWqry2.fa.gz --vcf --symbol --force_overwrite -o LWvsTempo.vep.vcf

Can anyone help?

**Comment by helensch** [comment]
Hi @AnneBoshove

Are the warning messages regarding "uninitialised values"  getting printed for all variants being run?

The messages suggest there may be problems parsing the exons in the GFF file.

Does the format of your gff follow the "GFF format expectations" on
https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff 

Please could you try 
- running for a variant that was successful and has expected output
- running with just  a couple of variants before it stopped and the sv it should be predicting next and see if it stops  in same place

Are you able to provide an example  VCF and example of your  GFF format so that I can investigate further?

Regards
Helen

**Comment by AnneBoshove** [comment]
Hi @helensch , 
Thanks for your reply!

The warning messages do not seem to occur for every single variant. I got around ~10k warning lines for the ~80k variants it managed to run.

As far as I can tell the GFF file has the proper format, sometimes it has additional info in the 9th column, could that be an issue?

I tried to run it on the couple of variants before and after the one it stopped on only, and surprisingly finished the entire thing, so it's not the specific variant causing the issue. Re-ran the original file and it still stopped at the same one though. 

I've added a sample VCF and GFF file (of course the gff file I use when running is bgzipped and indexed).
It stops running at Chr1 pos 14463954  SNP92572 for mewhen running the full thing.

[samplegff.txt](https://github.com/Ensembl/ensembl-vep/files/7558125/samplegff.txt)
[samplevcf.syri.txt](https://github.com/Ensembl/ensembl-vep/files/7558139/samplevcf.syri.txt)

Thanks in advance!
Anne

**Comment by AnneBoshove** [comment]
I eventually managed to solve the problem by using a gtf file instead of a gff file for annotation, so i'll close this issue now.

**Comment by helensch** [comment]
Hi @AnneBoshove 

Thank you for sending your example files and letting us know you managed to solve the problem using a gtf file instead.

Initial investigation showed that that VEP reported an error for a few exons in the GFF and stopped running.

We will add this issue onto our task list to investigate further.

Thank you for raising this issue.

Regards
Helen
