### ISSUE TITLE
filter_vep ignores VEP annotations when SnpEff annotations are available as well

### ISSUE THREAD

**Issue by Oodnadatta** [Ensembl/ensembl-vep#108]
Hello VEP team and thank you for this tool!

I have a vcf with SnpEff and VEP annotations.

    ##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|VARIANT_CLASS|SYMBOL_SOURCE|HGNC_ID|GIVEN_REF|USED_REF|SIFT|PolyPhen|AF|AFR_AF|AMR_AF|EAS_AF|EUR_AF|SAS_AF|AA_AF|EA_AF|gnomAD_AF|gnomAD_AFR_AF|gnomAD_AMR_AF|gnomAD_ASJ_AF|gnomAD_EAS_AF|gnomAD_FIN_AF|gnomAD_NFE_AF|gnomAD_OTH_AF|gnomAD_SAS_AF|CLIN_SIG|SOMATIC|PHENO">

    chr1    18807897        .       C       G       60.31   .       AB=0;ABP=0;AC=2;AF=1;AN=2;ANN=G|missense_variant|MODERATE|KLHDC7A|ENSG00000179023|transcript|ENST00000400664|protein_coding|1/1|c.422C>G|p.Pro141Arg|474/5055|422/2334|141/777||;AO=5;BVAR;CIGAR=1X;CSQ=G|missense_variant|MODERATE||CCDS185.2|Transcript|CCDS185.2|protein_coding|1/1||||422|422|141|L/R|cTc/cGc|rs2992755||1||SNV|||C|T|tolerated(0.65)|benign(0)||0.5688|0.7147|0.8958|0.6113|0.4847|0.5957|0.6338|0.6583|0.581|0.804|0.6972|0.8954|0.6454|0.629|0.6618|0.5068|||,G|missense_variant|MODERATE|KLHDC7A|ENSG00000179023|Transcript|ENST00000400664|protein_coding|1/1||||474|422|141|L/R|cTc/cGc|rs2992755||1||SNV|HGNC|26791|C|T|tolerated(0.65)|benign(0)||0.5688|0.7147|0.8958|0.6113|0.4847|0.5957|0.6338|0.6583|0.581|0.804|0.6972|0.8954|0.6454|0.629|0.6618|0.5068|||,G|missense_variant|MODERATE|KLHDC7A|127707|Transcript|NM_152375.2|protein_coding|1/1||||474|422|141|L/R|cTc/cGc|rs2992755||1||SNV|EntrezGene|26791|C|T|tolerated(0.65)|benign(0)||0.5688|0.7147|0.8958|0.6113|0.4847|0.5957|0.6338|0.6583|0.581|0.804|0.6972|0.8954|0.6454|0.629|0.6618|0.5068|||,G|missense_variant|MODERATE|KLHDC7A|127707|Transcript|NM_152375.2|protein_coding|1/1||||474|422|141|L/R|cTc/cGc|rs2992755||1||SNV|EntrezGene|26791|C|T|tolerated(0.65)|benign(0)||0.5688|0.7147|0.8958|0.6113|0.4847|0.5957|0.6338|0.6583|0.581|0.804|0.6972|0.8954|0.6454|0.629|0.6618|0.5068|||,G|missense_variant|MODERATE|KLHDC7A|127707|Transcript|XM_005245739.1|protein_coding|1/2||||429|422|141|L/R|cTc/cGc|rs2992755||1||SNV|EntrezGene|26791|C|T||||0.5688|0.7147|0.8958|0.6113|0.4847|0.5957|0.6338|0.6583|0.581|0.804|0.6972|0.8954|0.6454|0.629|0.6618|0.5068|||,G|intron_variant|MODIFIER|KLHDC7A|127707|Transcript|XM_005245740.1|protein_coding||1/1||||||||rs2992755||1||SNV|EntrezGene|26791|C|C||||0.5688|0.7147|0.8958|0.6113|0.4847|0.5957|0.6338|0.6583|0.581|0.804|0.6972|0.8954|0.6454|0.629|0.6618|0.5068|||;DP=6;DPB=6;DPRA=0;EPP=13.8677;EPPR=5.18177;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=4.04584;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=133;QR=26;RO=1;RPP=13.8677;RPPR=5.18177;RUN=1;SAF=5;SAP=13.8677;SAR=0;SRF=0;SRP=5.18177;SRR=1;TYPE=snp  GT:AO:DP:PL:QA:QR:RO    1/1:5:6:50,0,16:133:26:1

I would like to filter this vcf using
`filter_vep -i "$input" -o "$output" --filter "gnomAD_AF > 0.01"`
but it gives no output variant even though gnomAD_AF is 0.6583.

In the code, there are two lines which mention both "CSQ" and "ANN"
https://github.com/Ensembl/ensembl-vep/blob/ac1ac350957a0ed946aaed33207c89bf546d42f4/filter_vep#L237
https://github.com/Ensembl/ensembl-vep/blob/ac1ac350957a0ed946aaed33207c89bf546d42f4/filter_vep#L295

When I remove "ANN" from these two lines, filtering works as expected.

Thanks.

**Comment by willmclaren** [comment]
`filter_vep` will currently be unable to (reliably) filter files like this with both CSQ and ANN fields populated; it expects to find only one.

I can see a few ways to address this:

1. Allow the user to specify which INFO field to parse (something like `--vcf_info_field ANN`)
2. Direct `filter_vep` to only read from VEP-annotated fields, as indicated in the header metadata
3. Allow `filter_vep` to filter on both ANN and CSQ together, though this could get complicated!!!

Would you have a preference for your particular use case?

**Comment by willmclaren** [comment]
I've gone with option 1 from above; this will be available in release/91, due in a few weeks.

I have specifically tested with your input file and it works OK.

**Comment by Oodnadatta** [comment]
Thank you for your reply! The first option seems to be the most flexible.
I will test it in the next release.
