### ISSUE TITLE
vep 1 HGVS notation to genomic coordinate - not find 

### ISSUE THREAD

**Issue by jeongmeani** [Ensembl/ensembl-vep#1082]
## Describe the issue
Hi, 
using VEP web api, i'm about to find some specific genomic coordinate from HGVS.
but some of them, vep could not find these.
for example, Gen1:p.K707N was not found on BALB_cJ_v1 data.
i check this gene on BALB_cJ_v1. 

is there chance to fix it?

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 98
- VEP Cache version: 98
- Perl version: 5.26
- OS: Centos7
- tabix installed ? Yes

### Full VEP command line
```
./vep -i input.txt -o output.txt ...
```

### Full error message
> Including the warnings, if available

### Data files (if applicable)
They include:
- The input file
- The output file
- The custom file(s)
You can provide a sample of them

**Comment by dglemos** [comment]
Hi @jeongmeani,
Could you please send the VEP command?
Is Gen1:p.K707N the input format?

**Comment by jeongmeani** [comment]
Hi, 

i ran this task on VEP web interface like below image
![image](https://user-images.githubusercontent.com/26432983/145120013-695c8d20-b2d0-4e92-9624-1101c4bef031.png)

yes the input is **Gen1:p.K707N**

Best regards.

Jeongmin

**Comment by dglemos** [comment]
Hi @jeongmeani,
Sorry for taking so long to reply.
The reason VEP is not annotating the variant `Gen1:p.K707N` is because for the gene Gen1 the aminoacid `K` is not in the protein position `707`.

**Comment by dglemos** [comment]
I'm going to close this issue but if you have more questions feel free to open a new one.

Best wishes,
Diana
