### ISSUE TITLE
Combine the same variants between the samples in the same line (question)

### ISSUE THREAD

**Issue by Danisov** [Ensembl/ensembl-vep#1083]
Dear colleagues

I used VEP to annotate a multisamples vcf file, but I get separate lines of the same variant, which corresponds to each sample.

here is an example of output

```
Location         Allele       IND     ZYG
chr1:27868305-27868306  A        sample1   HET
chr1:27868305-27868306  A        sample2   HOM
chr1:27868305-27868306  A        sample3   HET
```
I would like to get a single row for each variant, like this:

```
Location         Allele               IND               ZYG
chr1:27868305-27868306  A        sample1,sample2,sample3   HET,HOM,HET
```

Or

```
Location          Allele      sample1  sample2   sample3
chr1:27868305-27868306  A         HET        HOM        HET
```

Do you have an idea ?

**Comment by dglemos** [comment]
Hi @Danisov,
At the moment, VEP reports separate output lines for each sample. 
As described in this ticket: https://github.com/Ensembl/ensembl-vep/issues/1069 we have a plan to add an option in the future to report samples in the same output line.

Best wishes,
Diana

**Comment by Danisov** [comment]
Thank you for your feedback !
I opened another issue about --custom with the bed file of OMIM would it be possible to see it?

**Comment by dglemos** [comment]
I will close off this ticket, but we will contact you when the change is made.
Please feel free to reopen the ticket or open a new one if you have further questions.

Best wishes,
Diana

**Comment by dglemos** [comment]
Hi @Danisov,
Regarding your first question, we have decided to include a new option called --individual_zyg which will return all individuals' zygosity in the same line to avoid duplicated data in the output. For example: ZYG=ind1:HOM,ind2:HET.
The behaviour of option --individuals will stay the same.

Best wishes,
Diana
