### ISSUE TITLE
installation error, Do I need some perl libs?

### ISSUE THREAD

**Issue by 11Dmitriy11** [Ensembl/ensembl-vep#1084]
## Describe the issue
Hello! This installer is configured to install v104 of the Ensembl API for use by the VEP.
It will not affect any existing installations of the Ensembl API that you may have.

It will also download and install cache files from Ensembl's FTP server.

Checking for installed versions of the Ensembl API...done
It looks like you already have the following API modules installed:

ensembl-variation
ensembl
ensembl-io

The VEP requires the ensembl, ensembl-io, ensembl-variation and ensembl-funcgen modules

Skip to the next step (n) to install cache files

Do you want to continue installing the API (y/n)? y

Setting up directories
Destination directory ./Bio already exists.
Do you want to overwrite it (if updating VEP this is probably OK) (y/n)? y
 - fetching BioPerl
 - unpacking ./Bio/tmp/release-1-6-924.zip
 - moving files

Downloading required Ensembl API files
 - fetching ensembl
 - unpacking ./Bio/tmp/ensembl.zip
 - moving files
 - getting version information
 - fetching ensembl-variation
 - unpacking ./Bio/tmp/ensembl-variation.zip
 - moving files
 - getting version information
 - fetching ensembl-funcgen
 - unpacking ./Bio/tmp/ensembl-funcgen.zip
 - moving files
 - getting version information
 - fetching ensembl-io
 - unpacking ./Bio/tmp/ensembl-io.zip
 - moving files
 - getting version information

Testing VEP installation
ERROR: Testing VEP script failed with the following error
Search pattern not terminated at /humgen/atgu1/methods/dusoltsev/programms/ensembl-vep/Bio/EnsEMBL/Slice.pm line 3056.
Compilation failed in require at /humgen/atgu1/methods/dusoltsev/programms/ensembl-vep/Bio/EnsEMBL/Feature.pm line 84.
BEGIN failed--compilation aborted at /humgen/atgu1/methods/dusoltsev/programms/ensembl-vep/Bio/EnsEMBL/Feature.pm line 84.
Compilation failed in require at /humgen/atgu1/methods/dusoltsev/programms/ensembl-vep/Bio/EnsEMBL/Variation/BaseVariationFeature.pm line 58.
BEGIN failed--compilation aborted at /humgen/atgu1/methods/dusoltsev/programms/ensembl-vep/Bio/EnsEMBL/Variation/BaseVariationFeature.pm line 58.
Compilation failed in require at /humgen/atgu1/methods/dusoltsev/programms/ensembl-vep/Bio/EnsEMBL/Variation/VariationFeature.pm line 97.
BEGIN failed--compilation aborted at /humgen/atgu1/methods/dusoltsev/programms/ensembl-vep/Bio/EnsEMBL/Variation/VariationFeature.pm line 97.
Compilation failed in require at /humgen/atgu1/methods/dusoltsev/programms/ensembl-vep/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm line 89.
BEGIN failed--compilation aborted at /humgen/atgu1/methods/dusoltsev/programms/ensembl-vep/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm line 89.
Compilation failed in require at /humgen/atgu1/methods/dusoltsev/programms/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 59.
BEGIN failed--compilation aborted at /humgen/atgu1/methods/dusoltsev/programms/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 59.
Compilation failed in require at (eval 6) line 3.
        ...propagated at /broad/software/free/Linux/redhat_7_x86_64/pkgs/perl_5.8.9/lib/5.8.9/base.pm line 93.
BEGIN failed--compilation aborted at /humgen/atgu1/methods/dusoltsev/programms/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm line 56.
Compilation failed in require at (eval 5) line 3.
        ...propagated at /broad/software/free/Linux/redhat_7_x86_64/pkgs/perl_5.8.9/lib/5.8.9/base.pm line 93.
BEGIN failed--compilation aborted at /humgen/atgu1/methods/dusoltsev/programms/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 71.
Compilation failed in require at ./vep line 20.
BEGIN failed--compilation aborted at ./vep line 20.

### System
- VEP version: [104] 
- Perl version: [e.g. 5.8]
- OS: Red Hat Enterprise Linux
- tabix: yes

### Full VEP command line
```
perl INSTALL.pl --NO_HTSLIB
```
### Data files (if applicable)
They include:
- The input file
- The output file
- The custom file(s)
You can provide a sample of them

**Comment by noranekonobokkusu** [comment]
Hi,

I have the same error when I try to install VEP, and I have all the dependencies installed. Did you manage to fix that?
