### ISSUE TITLE
Annotation bed file with --custom 

### ISSUE THREAD

**Issue by Danisov** [Ensembl/ensembl-vep#1085]
I would like to use OMIM with --custom,

I have a txt file and I wanted to use it in --custom. This file contains the following headings

` # Chromosome Genomic Position Start Genomic Position End Cyto Location Computed Cyto Location MIM Number Gene Symbols Gene Name Approved Gene Symbol Enter Gene ID Ensembl Gene ID Comments Phenotypes Mouse Gene Symbol / ID`
 
 I followed the steps mentioned here https://m.ensembl.org/info/docs/tools/vep/script/vep_custom.html
 
 1- I prepared the file
 grep -v "#" genemap2.txt | sort -k1,1 -k2,2n -k3,3n -t $ '\ t' | bgzip -c> genmap2.bed.gz
 
 2- I indexed it
 tabix -p bed genmap2.bed.gz
 
 3-Then I integrated it into the pipeline with this option:
 --custom ${OMIM}/genemap2.bed.gz,OMIM,bed,exact,1
 
For the results, I didn't get the columns that match the headers (above), I got a single empty column.

Do you have any idea so that I can correctly annotate my vcf file with OMIM?

Thanks in advance,
Danisov

**Comment by helensch** [comment]
Hi @Danisov

From https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html
"BED : a simple tab-delimited format containing 3-12 columns of data. The first 3 columns contain the coordinates of the feature. If available, VEP will use the 4th column of the file as the identifier of the feature. "

The options of the custom annotation are given in
https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html#custom_options

The 4th column of the BED file is being used for the annotation and the "OMIM" in your custom command line is the name for the annotation in the results.

A small example of using a VCF with a BED file is given in similar issue https://github.com/Ensembl/ensembl-vep/issues/598#issuecomment-530827622. This may help you get started with annotating your VCF file with OMIM.

Please let me know if you have any additional queries.

Regards
Helen

**Comment by helensch** [comment]
Hi 

I am going to close this issue now.

If you have any further questions, please feel free to reopen it or create a new issue.

Regards
Helen
