### ISSUE TITLE
ERROR: Could not eval VEP plugin config file (VEP 105)

### ISSUE THREAD

**Issue by Z-Zen** [Ensembl/ensembl-vep#1090]
## Describe the issue
When trying to build VEP version 105, I get an error for installing all the plugins by giving the parameter `./INSTALL.pl -a p --PLUGINS all`.

### System
- VEP version: 105
- Perl version: 5.24
- OS: Debian 9
- tabix installed ? Yes

### Full VEP command line
```
./INSTALL.pl -a p --PLUGINS all
```

### Full error message
```
ERROR: Could not eval VEP plugin config file: Can't modify constant item in scalar assignment at (eval 54) line 920, near ""PrimateAI","
```

**Comment by helensch** [comment]
Hi @Z-Zen 

Thank you for reporting this installation error. A fix has been made to correct the VEP plugin config.

Please could you try re-running the INSTALL.pl

Regards
Helen

**Comment by Z-Zen** [comment]
@helensch Thank you for the quick fix! Now, I am getting a warning:

```
WARNING: The following plugins have not been found: all
Available plugins: AncestralAllele,Blosum62,CADD,CSN,Carol,ClinPred,Condel,Conservation,DisGeNET,Downstream,Draw,ExAC,ExACpLI,FATHMM,FATHMM_MKL,FlagLRG,FunMotifs,G2P,GO,GeneSplicer,Gwava,HGVSIntronOffset,LD,LOVD,LoF,LoFtool,LocalID,MPC,MTR,Mastermind,MaxEntScan,NMD,NearestExonJB,NearestGene,PON_P2,Phenotypes,PostGAP,PrimateAI,ProteinSeqs,REVEL,ReferenceQuality,SameCodon,SingleLetterAA,SpliceAI,SpliceRegion,StructuralVariantOverlap,SubsetVCF,TSSDistance,dbNSFP,dbscSNV,gnomADc,miRNA,neXtProt,satMutMPRA
```

But the installation proceeds with installing the plugins.

**Comment by helensch** [comment]
Hi @Z-Zen 

Thank you for flagging the WARNING message when using ```---PLUGINS all```.

All plugins are looked up and installed when ```---PLUGINS all```  is used.
https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#opt_plugins 

I have put in a ticket to remove the WARNING when "all " is used.

I am going to close this issue but feel free to create a new issue if you have more questions.

Regards
Helen
