### ISSUE TITLE
can ensemble-vep 104.0.0 annotate a mutation file that was mapped to GRCH37(hg19)?

### ISSUE THREAD

**Issue by stroke1989** [Ensembl/ensembl-vep#1091]
Excuse me:
I'm a new to use vep, I try to use vep to annotate my mutation file. My mutation files were mapping to hg19. The version of ensemble-vep I installed is 104.0.0, VEP Cache version is 104_GRCh37, I don't know whether I could use vep 104.0.0 to annotate my mutation file(mapped to hg19). I saw that GRCH37 stop at ensemble version 75. Hope your response. Appreciate!

**Comment by dglemos** [comment]
Hi @stroke1989,
You can annotate your file with VEP cache 104_GRCh37. Ensembl stopped to update the geneset on GRCh37 at release 75. However, the variation and regulation data were updated more recently (dbSNP 154, ClinVar 2020-12, COSMIC 92, HGMD, etc).

Best wishes,
Diana

**Comment by dglemos** [comment]
I'm going to close the issue for now but feel free to open a new one if you have more questions.

Best wishes,
Diana
