### ISSUE TITLE
vep 100.0 skips VCF record with reason "incomplete" even though it is a valid record

### ISSUE THREAD

**Issue by tedil** [Ensembl/ensembl-vep#1092]
## Describe the issue
For certain VCF records, ensembl-vep 100.0 reports `WARNING: VCF line on line [n] looks incomplete, skipping:`, even though these records are valid (i.e. not incomplete) VCF records.

Example record that is skipped by vep:
```
16	88643570	DEL00000869	G	<DEL>	.	.	SVLEN=-2544;SVTYPE=DEL;PROB_ARTIFACT=121.637;PROB_GERMLINE_HET=inf;PROB_SOMATIC_TUMOR_MEDIUM=0.750273;PROB_SOMATIC_NORMAL=16.0045;PROB_SOMATIC_TUMOR_LOW=26.5453;PROB_GERMLINE_HOM=inf;PROB_SOMATIC_TUMOR_HIGH=8.81574;PROB_ABSENT=548.064;END=88643570	DP:AF:SOBS:OBS:SB:ROB:RPB:SCB:HE:AFD	34:0:34N:15Np+>*..15Np+<*..2Np-**..1Np->*..1Np+<*$.:.:.:.:.:.:0.00=-11.36	71:0.227113:12V59N:5Vp+>*$.4Vp+**$.3Vp->*$.28Np+<*..20Np+>*..8Np+**..1Np-**..1Np*<*..1Np+**$.:.:.:.:.:.:0.00=545.05,0.01=88.62,0.04=45.00,0.06=24.69,0.06=20.01,0.07=14.38,0.08=12.35,0.08=9.75,0.09=7.84,0.09=5.89,0.10=5.28,0.10=4.69,0.10=4.11,0.11=0.08,0.16=-7.94,0.19=-10.54,0.20=-10.95,0.20=-11.04,0.21=-11.21,0.22=-11.28,0.22=-11.34,0.23=-11.36,0.23=-11.34,0.24=-11.22,0.25=-11.03,0.25=-10.99,0.30=-8.79,0.31=-7.73,0.31=-7.59,0.31=-7.44,0.32=-7.29,0.32=-6.82,0.33=-6.40,0.33=-5.81,0.34=-5.44,0.35=-4.40,0.35=-3.56,0.40=1.90,0.48=16.22,0.65=57.94,0.83=120.32,1.00=3306.03
```

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 100.0
- VEP Cache version: 100
- Perl version: v5.26.2
- OS: Ubuntu 18.04.6
- tabix installed: yes, `tabix (htslib) 1.12`

(vep has been installed using conda via `conda install "ensembl-vep==100.0"`)

### Full VEP command line
```
vep --cache --dir resources/vep/cache --everything -i vep_annotation_missing_input.vcf --format vcf --vcf --output_file vep_annotation_missing_output.vcf --stats_file vep_annotation_missing.txt
```

### Full error message
> WARNING: VCF line on line 1 looks incomplete, skipping:
> [.. record from above ...]

### Data files (if applicable)
They include:
- The input file: 
[vep_annotation_missing_input.vcf.txt](https://github.com/Ensembl/ensembl-vep/files/7839058/vep_annotation_missing_input.vcf.txt)

**Comment by dglemos** [comment]
Hi @tedil,
If END is defined in INFO, VEP is going to use it to determine the end coordinate. In your example the end coordinate is the same as the start `END=88643570` which means VEP cannot determine where the deletion ends. Another way to know the end coordinate is to use SVLEN, however VEP only uses SVLEN if END is not defined which is not the case for your variant. 
If you remove the tag END from INFO, VEP is able to complete the annotation.

**Comment by tedil** [comment]
Thanks for the reply!
Indeed, removing `END` resolves the issue (I'll have to find out why `END` is wrong).

Perhaps the warning could be a bit more specific, if possible. E.g. explains why the record is deemed "incomplete", or have a check that POS and SVLEN agree with END, at least for insertions and deletions.

Closing since the issue itself has been solved. Thanks again ;)
