### ISSUE TITLE
VEP  returns empty columns

### ISSUE THREAD

**Issue by hamidghaedi** [Ensembl/ensembl-vep#1103]
I am facing an issue regarding running VEP:
Using a vcf file and online version of VEP , the returned result got columns filled with "_" and the only annotations that I got are  "Uploaded variant",  "location" and "consequence". 
When I tried VEP in docker, it is working and returning information but it's super slow. 

I have posted this issue on [Biostar ](https://www.biostars.org/p/9507416/)as well, so I thought to post here in hope of getting your input on this.  Why is the online version doing so and returning no information?

**Comment by hamidghaedi** [comment]
@jamie-m-a 
If you want to look at the file that I used and got the above error, please find that [here](https://raw.githubusercontent.com/hamidghaedi/file_sharing/main/review_by_expert_panel.vcf).

**Comment by jamie-m-a** [comment]
Hi @hamidghaedi 

Similar to the result my colleague Ben has reported in your Biostars thread, I have been unable to replicate the issue, the results for web VEP appear normally for me.

In terms of resolving the issue with web VEP, perhaps try again using another browser. Or maybe restart your machine and try again in case there is some corrupted data held in your browser's cache.

For running using the command line interface from the docker package, yes, using the --cache option is optimal and a vcf of this size should run quickly with a local cache file.

**Comment by hamidghaedi** [comment]
Thanks @jamie-m-a ,
Just to keep this thread informative, using the " Show most severe consequence per variant" from the "Restrict results" section caused that kind of result.
