### ISSUE TITLE
Adding G2P annotation using vep

### ISSUE THREAD

**Issue by ajaarma** [Ensembl/ensembl-vep#1104]
## Describe the issue
I tried annotating list of variants from chromosome 1 for a subset of cohort. After running the Vep command there was no variants annotated with G2P gene lists.

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
Versions:
  
  ensembl              : 104.1af1dce
  ensembl-funcgen      : 104.59ae779
  ensembl-io           : 104.1d3bb6e
  ensembl-variation    : 104.6154f8b
  ensembl-vep          : 104.3
  Perl                         : 5.26
  Tabix                       : Installed

### Full VEP command line
```
bcftools view tmpFile_chr1.AC0.norm.noGT.vcf.gz | /resources/softwares/ensembl-vep/vep --vcf -o STDOUT --format vcf --offline --cache --merged --dir_cache /resources/softwares/vep/grch38 --force_overwrite --species homo_sapiens --assembly GRCh38 --fasta /resources/gatk_bundle/Homo_sapiens_assembly38.fasta --vcf_info_field ANN --plugin G2P,file=/resources/ddg2p/DDG2
P_17_11_2021.csv --stats_text --stats_file chr1_vep_stats.txt | bgzip -c > chr1.new.vep.vcf.gz

```

### Full error message
> Including the warnings, if available
Output Error: The input vcf file was not annotated with any of the DDG2P overlapping genes. Hence the output vcf file there were no variants.

### Data files (if applicable)
They include:
- The input file : tmpFile_chr1.AC0.norm.noGT.vcf.gz (list of variants to be annotated from chromosome 1)
- The output file: chr1.new.vep.vcf.gz (no variants), chr1_vep_stats.txt: 
[VEP run statistics]
VEP version (API)	 104 (104)
Annotation sources	Cache: /resources/softwares/vep/grch38/homo_sapiens_merged/104_GRCh38
Species	homo_sapiens
Command line options	--assembly GRCh38 --cache --dir_cache /resources/softwares/vep/grch38 --fasta /resources/gatk_bundle/Homo_sapiens_assembly38.fasta --force_overwrite --format vcf --merged --offline --output_file STDOUT --plugin G2P,file=/resources/ddg2p/DDG2P_17_11_2021.csv --species homo_sapiens --stats_file chr1_vep_stats.txt --stats_text --vcf --vcf_info_field ANN
Start time	2022-01-26 01:14:57
End time	2022-01-26 01:15:53
Run time	56 seconds
Input file	STDIN
Output file	STDOUT

[General statistics]
Lines of input read
Variants processed
Variants filtered out	0
Novel / existing variants	-
Overlapped genes	0
Overlapped transcripts	0
Overlapped regulatory features	-

[Variant classes]

[Consequences (most severe)]

[Consequences (all)]

[Coding consequences]

[SIFT summary]

[PolyPhen summary
- The custom file(s)
You can provide a sample of them

**Comment by olaaustine** [comment]
Hi ajaarma,

Thank you for reporting this issue.

Is it possible for you to share your input vcf file to see if we can recreate the issue? 

Thank you 
Ola.

**Comment by ajaarma** [comment]
Hi Ola,

I am attaching test_chr1.tar.gz file with all input file (subset of original chr1 variants) and corresponding output generated. 

Hope this helps.

Regards
Ajay
[test_chr1.tar.gz](https://github.com/Ensembl/ensembl-vep/files/7942938/test_chr1.tar.gz)

**Comment by olaaustine** [comment]
Hi ajaarma, 
Just to confirm, you are using the G2P panel file from 17_11_2021? 
Thank you 
Ola.

**Comment by ajaarma** [comment]
Ya, I downloaded the corresponding version on 17th Nov 2021 hence named DDG2P_17_11_2021.csv. I also issued the same command with 1_12_2021.csv version file downloaded from here: http://ftp.ebi.ac.uk/pub/databases/gene2phenotype/DD/DDG2P_1_12_2021.csv.gz 

The result was same.

**Comment by olaaustine** [comment]
Hi ajaarma,

Thank you for the information provided.

The genotype field is missing in the input VCF.  https://samtools.github.io/hts-specs/VCFv4.3.pdf

G2P works with the genotype field  .i.e. zygosity reference is defined.

We are taking a look at why VEP returns an empty output when the plugin does not work.

Please let us know if you have any other questions.

Thank you

Ola.

**Comment by olaaustine** [comment]
Hi ajaarma,
I'm going to close this issue now.
If you have any further questions, please feel free to reopen it or create a new issue.
Thank you
Ola.
