### ISSUE TITLE
More "Variants processed" than "Lines of input read"

### ISSUE THREAD

**Issue by frahimov** [Ensembl/ensembl-vep#1106]
I ran VEP (v104) on 9213 variants, however the html output shows

Lines of input read | 9213
Variants processed | 9365

Lines of input read is correct.
I am curious where the extra variants indicated in the Variants processed came from.
My script looks like this:
vep
--gencode_basic
--input_file inputfile
--format id
--cache
--dir_cache ../cache_dir/
--everything
--output_file outputfile
--tab

Many thanks!

**Comment by jamie-m-a** [comment]
Hi @frahimov 

Thanks for getting in touch! Would it be possible to share your input data so we can can try and replicate the issue?

**Comment by frahimov** [comment]
Certainly. Could you please provide an email address that I could send you the list of SNPs?

**Comment by jamie-m-a** [comment]
You can use our heldpesk contact (https://www.ensembl.org/info/about/contact/index.html), if you specify in your message that you have been in touch with Jamie from variation about your issue already, they can forward it on to me.
