### ISSUE TITLE
filter_vep with on-the-fly calculation?

### ISSUE THREAD

**Issue by MikeHala** [Ensembl/ensembl-vep#1107]
Dear VEP Team,

Following https://m.ensembl.org/info/docs/tools/vep/script/vep_filter.html 
it is possible to select entries where AFR_AF is greater than EUR_AF by
`--filter "AFR_AF > #EUR_AF"`

Is it possible to select entries where AFR_AF is e.g. at least twice EUR_AF?
I have tried (with no success)
``--filter "AFR_AF > 2 * #EUR_AF"``

Thanks!

**Comment by dglemos** [comment]
Hi @MikeHala,
It is not possible to do calculations as you mentioned. The script filter_vep will only use the input value or the value of another field.

**Comment by dglemos** [comment]
I'm going to close the issue for now but feel free to open a new one if you have more questions.

Best wishes,
Diana
