### ISSUE TITLE
Unable to install Command Line VEP (Non-zero exit status: 255   Parse errors: No plan found in TAP output) 

### ISSUE THREAD

**Issue by eibol1** [Ensembl/ensembl-vep#1113]
I am trying to install VEP, but I have the next error that makes fail the installation:
 ` Non-zero exit status: `
 ` Parse errors: No plan found in TAP output`

Also tried with sudo and got the same fail.

Here is all I got: 

ensembl-vep git:(release/105) ✗ perl INSTALL.pl 
WARNING: DBD::mysql module not found. VEP can only run in offline (--offline) mode without DBD::mysql installed

http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#requirements
Installation on OSX requires that you set up some paths before running this installer.
Have you 
1. added /Users/abelgd/Bioinfo/ensembl-vep/htslib to your DYLD_LIBRARY_PATH environment variable?
(y/n): y

Hello! This installer is configured to install v105 of the Ensembl API for use by the VEP.
It will not affect any existing installations of the Ensembl API that you may have.

It will also download and install cache files from Ensembl's FTP server.

Checking for installed versions of the Ensembl API...done

Setting up directories
Destination directory ./Bio already exists.
Do you want to overwrite it (if updating VEP this is probably OK) (y/n)? y
 - fetching BioPerl
 - unpacking ./Bio/tmp/release-1-6-924.zip
 - moving files
Attempting to install Bio::DB::HTS and htslib.

>>> If this fails, try re-running with --NO_HTSLIB

 - checking out HTSLib
fatal: destination path 'htslib' already exists and is not an empty directory.
 - building HTSLIB in ./htslib
In /Users/abelgd/Bioinfo/ensembl-vep/htslib
make: Nothing to be done for `all'.
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.11 - moving files to ./biodbhts
 - making Bio::DB:HTS
Checking prerequisites...
  requires:
    !  Bio::Root::Version is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Run 'Build installdeps' to install missing prerequisites.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.11'
Building Bio-DB-HTS
cc -iwithsysroot /Users/abelgd/Bioinfo/ensembl-vep/htslib -iwithsysroot /System/Library/Perl/5.30/darwin-thread-multi-2level/CORE -DVERSION="2.11" -DXS_VERSION="2.11" -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wno-unused-result -c -g -pipe -fno-strict-aliasing -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -Os -o lib/Bio/DB/HTS.o lib/Bio/DB/HTS.c
lib/Bio/DB/HTS.xs:1770:22: warning: 'bcf_hdr_fmt_text' is deprecated: use bcf_hdr_format() instead [-Wdeprecated-declarations]
    RETVAL = newSVpv(bcf_hdr_fmt_text(header, is_bcf, &len), 0);
                     ^
/usr/local/include/htslib/vcf.h:572:9: note: 'bcf_hdr_fmt_text' has been explicitly marked deprecated here
        HTS_DEPRECATED("use bcf_hdr_format() instead");
        ^
/usr/local/include/htslib/hts_defs.h:75:49: note: expanded from macro 'HTS_DEPRECATED'
#define HTS_DEPRECATED(message) __attribute__ ((__deprecated__ (message)))
                                                ^
lib/Bio/DB/HTS.xs:1786:30: warning: format specifies type 'int' but the argument has type 'long long' [-Wformat]
     printf("position:%d\t", (row->pos+1));
                      ~~     ^~~~~~~~~~~~
                      %lld
2 warnings generated.
ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Bio/DB/HTS/HTS.bs')
env LD_RUN_PATH=/System/Library/Perl/5.30/darwin-thread-multi-2level/CORE cc -bundle -undefined dynamic_lookup -fstack-protector-strong -o blib/arch/auto/Bio/DB/HTS/HTS.bundle lib/Bio/DB/HTS.o -L/Users/abelgd/Bioinfo/ensembl-vep/htslib -Wl,-rpath,/Users/abelgd/Bioinfo/ensembl-vep/htslib -lhts -lpthread -lz
cc -iwithsysroot /Users/abelgd/Bioinfo/ensembl-vep/htslib -iwithsysroot /System/Library/Perl/5.30/darwin-thread-multi-2level/CORE -DVERSION="2.11" -DXS_VERSION="2.11" -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wno-unused-result -c -g -pipe -fno-strict-aliasing -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -Os -o lib/Bio/DB/HTS/Faidx.o lib/Bio/DB/HTS/Faidx.c
ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Bio/DB/HTS/Faidx/Faidx.bs')
env LD_RUN_PATH=/System/Library/Perl/5.30/darwin-thread-multi-2level/CORE cc -bundle -undefined dynamic_lookup -fstack-protector-strong -o blib/arch/auto/Bio/DB/HTS/Faidx/Faidx.bundle lib/Bio/DB/HTS/Faidx.o -L/Users/abelgd/Bioinfo/ensembl-vep/htslib -Wl,-rpath,/Users/abelgd/Bioinfo/ensembl-vep/htslib -lhts -lpthread -lz

Downloading required Ensembl API files
 - fetching ensembl
 - unpacking ./Bio/tmp/ensembl.zip
 - moving files
 - getting version information
 - fetching ensembl-variation
 - unpacking ./Bio/tmp/ensembl-variation.zip
 - moving files
 - getting version information
 - fetching ensembl-funcgen
 - unpacking ./Bio/tmp/ensembl-funcgen.zip
 - moving files
 - getting version information
 - fetching ensembl-io
 - unpacking ./Bio/tmp/ensembl-io.zip
 - moving files
 - getting version information

Testing VEP installation
./t/Utils.t .......................................... ok    
./t/Parser_Region.t .................................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser_Region.t .................................. ok    
./t/FilterSet.t ...................................... ok     
./t/AnnotationSource_Cache.t ......................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache.t ......................... ok   
./t/AnnotationSource_Database_Variation.t ............ Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_Variation.t ............ ok    
./t/AnnotationSource_Database_RegFeat.t .............. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_RegFeat.t .............. ok    
./t/OutputFactory_Tab.t .............................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_Tab.t .............................. ok    
./t/version.t ........................................ ok   
./t/AnnotationSource_File_BigWig.t ................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_BigWig.t ................... ok    
./t/AnnotationSource_Cache_VariationTabix.t .......... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_VariationTabix.t .......... ok    
./t/OutputFactory_VEP_output.t ....................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_VEP_output.t ....................... ok    
./t/Config.t ......................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Config.t ......................................... ok    
./t/TranscriptTree.t ................................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/TranscriptTree.t ................................. ok    
./t/InputBuffer.t .................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/InputBuffer.t .................................... ok    
./t/OutputFactory_JSON.t ............................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_JSON.t ............................. ok    
./t/Parser.t ......................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser.t ......................................... ok     
./t/VariantRecoder.t ................................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
"my" variable $sth masks earlier declaration in same scope at Bio/EnsEMBL/DBSQL/TranslationAdaptor.pm line 607.
./t/VariantRecoder.t ................................. ok    
./t/AnnotationSource_File.t .......................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File.t .......................... ok    
./t/Parser_ID.t ...................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser_ID.t ...................................... ok   
./t/OutputFactory.t .................................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory.t .................................. ok     
./t/Parser_VEP_input.t ............................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser_VEP_input.t ............................... ok    
./t/Parser_SPDI.t .................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser_SPDI.t .................................... ok   
./t/CacheDir.t ....................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/CacheDir.t ....................................... ok    
./t/AnnotationSource_Database_Transcript.t ........... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_Transcript.t ........... ok    
./t/Runner.t ......................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Runner.t ......................................... 50/? 
-------------------- EXCEPTION --------------------
MSG: ERROR: Cannot use format gff without Bio::DB::HTS::Tabix module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:162
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:228
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:93
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:361
STACK toplevel ./t/Runner.t:755
Date (localtime)    = Wed Feb 16 13:10:33 2022
Ensembl API version = 105
---------------------------------------------------
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 73.
./t/Runner.t ......................................... Dubious, test returned 255 (wstat 65280, 0xff00)
All 73 subtests passed 
./t/AnnotationSource_Database_StructuralVariation.t .. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_StructuralVariation.t .. ok    
./t/AnnotationSource_Cache_RegFeat.t ................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_RegFeat.t ................. ok    
./t/AnnotationSource_File_GFF.t ...................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_GFF.t ...................... ok    
./t/Parser_HGVS.t .................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser_HGVS.t .................................... ok    
./t/AnnotationSource_File_VCF.t ...................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_VCF.t ...................... ok    
./t/bam_edit.t ....................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/bam_edit.t ....................................... ok    
./t/OutputFactory_VCF.t .............................. Possible attempt to separate words with commas at ./t/OutputFactory_VCF.t line 580.
Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_VCF.t .............................. ok    
./t/AnnotationSourceAdaptor.t ........................ Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSourceAdaptor.t ........................ ok    
./t/Stats.t .......................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Stats.t .......................................... ok    
./t/AnnotationSource_Cache_Transcript.t .............. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_Transcript.t .............. ok    
./t/AnnotationSource_File_BED.t ...................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_BED.t ...................... ok    
./t/AnnotationSource.t ............................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource.t ............................... ok    
./t/AnnotationSource_Cache_Variation.t ............... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_Variation.t ............... ok    
./t/Parser_VCF.t ..................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser_VCF.t ..................................... ok    
./t/Parser_CAID.t .................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser_CAID.t .................................... ok    
./t/BaseVEP.t ........................................ Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/BaseVEP.t ........................................ ok    
./t/AnnotationSource_File_GTF.t ...................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_GTF.t ...................... ok    

Test Summary Report
-------------------
./t/Runner.t                                       (Wstat: 65280 Tests: 73 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=42, Tests=1716, 88 wallclock secs ( 0.20 usr  0.13 sys + 83.64 cusr  2.68 csys = 86.65 CPU)
Result: FAIL
Failed 1/42 test programs. 0/1716 subtests failed.

### System
- VEP version: 105 release
- VEP Cache version: [e.g. 98]
- Perl version: Perl 5, Version 
- OS: MacOS

Let me know if you need some more info about my situation pls !

**Comment by nakib103** [comment]
Hello @eibol1 ,

Looks like the actual reason for installation failure is - 
`MSG: ERROR: Cannot use format gff without Bio::DB::HTS::Tabix module installed`

Could you please:
1. Check that the Bio::DB::HTS::Tabix module is located in the ensembl-vep directory at: /ensembl-vep/Bio/DB/HTS/Tabix.pm
2. Check that your ensembl-vep folder is included within your PERL5LIB. If not, you can add it with:
   `export PERL5LIB=${PERL5LIB}:<ENSEMBL-VEP_PATH>`
3. Rerun your initial command, and send me the output if it's still not working correctly?

Best regards,
Nakib

**Comment by eibol1** [comment]
Hi @nakib103, 

Thanks for the quick reply. 

I followed you steps:

1. I checked that Tabix.pm file is in that directory. 👍
2. I exported PERL5LIB like this: 

ensembl-vep git:(release/105) ✗ `export PERL5LIB=${PERL5LIB}:/Users/abelgd/Bioinfo/ensembl-vep`

3. I rerun the code without and with **sudo** and I still have the same error, but without **sudo** it couldn't unlink and restore a large list of files and permissions. So then I tried it with **sudo** and that's what I had:

ensembl-vep git:(release/105) ✗ sudo perl INSTALL.pl
Password:
WARNING: DBD::mysql module not found. VEP can only run in offline (--offline) mode without DBD::mysql installed

http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#requirements
Installation on OSX requires that you set up some paths before running this installer.
Have you 
1. added /Users/abelgd/Bioinfo/ensembl-vep/htslib to your DYLD_LIBRARY_PATH environment variable?
(y/n): y

Hello! This installer is configured to install v105 of the Ensembl API for use by the VEP.
It will not affect any existing installations of the Ensembl API that you may have.

It will also download and install cache files from Ensembl's FTP server.

Checking for installed versions of the Ensembl API...done

Setting up directories
Destination directory ./Bio already exists.
Do you want to overwrite it (if updating VEP this is probably OK) (y/n)? y
 - fetching BioPerl
 - unpacking ./Bio/tmp/release-1-6-924.zip
 - moving files
Attempting to install Bio::DB::HTS and htslib.

>>> If this fails, try re-running with --NO_HTSLIB

 - checking out HTSLib
fatal: destination path 'htslib' already exists and is not an empty directory.
 - building HTSLIB in ./htslib
In /Users/abelgd/Bioinfo/ensembl-vep/htslib
make: Nothing to be done for `all'.
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.11 - moving files to ./biodbhts
 - making Bio::DB:HTS
Checking prerequisites...
  requires:
    !  Bio::Root::Version is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Run 'Build installdeps' to install missing prerequisites.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.11'
Building Bio-DB-HTS
cc -iwithsysroot /Users/abelgd/Bioinfo/ensembl-vep/htslib -iwithsysroot /System/Library/Perl/5.30/darwin-thread-multi-2level/CORE -DVERSION="2.11" -DXS_VERSION="2.11" -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wno-unused-result -c -g -pipe -fno-strict-aliasing -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -Os -o lib/Bio/DB/HTS.o lib/Bio/DB/HTS.c
lib/Bio/DB/HTS.xs:1770:22: warning: 'bcf_hdr_fmt_text' is deprecated: use bcf_hdr_format() instead [-Wdeprecated-declarations]
    RETVAL = newSVpv(bcf_hdr_fmt_text(header, is_bcf, &len), 0);
                     ^
/usr/local/include/htslib/vcf.h:572:9: note: 'bcf_hdr_fmt_text' has been explicitly marked deprecated here
        HTS_DEPRECATED("use bcf_hdr_format() instead");
        ^
/usr/local/include/htslib/hts_defs.h:75:49: note: expanded from macro 'HTS_DEPRECATED'
#define HTS_DEPRECATED(message) __attribute__ ((__deprecated__ (message)))
                                                ^
lib/Bio/DB/HTS.xs:1786:30: warning: format specifies type 'int' but the argument has type 'long long' [-Wformat]
     printf("position:%d\t", (row->pos+1));
                      ~~     ^~~~~~~~~~~~
                      %lld
2 warnings generated.
ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Bio/DB/HTS/HTS.bs')
env LD_RUN_PATH=/System/Library/Perl/5.30/darwin-thread-multi-2level/CORE cc -bundle -undefined dynamic_lookup -fstack-protector-strong -o blib/arch/auto/Bio/DB/HTS/HTS.bundle lib/Bio/DB/HTS.o -L/Users/abelgd/Bioinfo/ensembl-vep/htslib -Wl,-rpath,/Users/abelgd/Bioinfo/ensembl-vep/htslib -lhts -lpthread -lz
cc -iwithsysroot /Users/abelgd/Bioinfo/ensembl-vep/htslib -iwithsysroot /System/Library/Perl/5.30/darwin-thread-multi-2level/CORE -DVERSION="2.11" -DXS_VERSION="2.11" -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wno-unused-result -c -g -pipe -fno-strict-aliasing -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -Os -o lib/Bio/DB/HTS/Faidx.o lib/Bio/DB/HTS/Faidx.c
ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Bio/DB/HTS/Faidx/Faidx.bs')
env LD_RUN_PATH=/System/Library/Perl/5.30/darwin-thread-multi-2level/CORE cc -bundle -undefined dynamic_lookup -fstack-protector-strong -o blib/arch/auto/Bio/DB/HTS/Faidx/Faidx.bundle lib/Bio/DB/HTS/Faidx.o -L/Users/abelgd/Bioinfo/ensembl-vep/htslib -Wl,-rpath,/Users/abelgd/Bioinfo/ensembl-vep/htslib -lhts -lpthread -lz

Downloading required Ensembl API files
 - fetching ensembl
 - unpacking ./Bio/tmp/ensembl.zip
 - moving files
 - getting version information
 - fetching ensembl-variation
 - unpacking ./Bio/tmp/ensembl-variation.zip
 - moving files
 - getting version information
 - fetching ensembl-funcgen
 - unpacking ./Bio/tmp/ensembl-funcgen.zip
 - moving files
 - getting version information
 - fetching ensembl-io
 - unpacking ./Bio/tmp/ensembl-io.zip
 - moving files
 - getting version information

Testing VEP installation
./t/Utils.t .......................................... ok    
./t/Parser_Region.t .................................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser_Region.t .................................. ok    
./t/FilterSet.t ...................................... ok     
./t/AnnotationSource_Cache.t ......................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache.t ......................... ok   
./t/AnnotationSource_Database_Variation.t ............ Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_Variation.t ............ ok    
./t/AnnotationSource_Database_RegFeat.t .............. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_RegFeat.t .............. ok    
./t/OutputFactory_Tab.t .............................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_Tab.t .............................. ok    
./t/version.t ........................................ ok   
./t/AnnotationSource_File_BigWig.t ................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_BigWig.t ................... ok    
./t/AnnotationSource_Cache_VariationTabix.t .......... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_VariationTabix.t .......... ok    
./t/OutputFactory_VEP_output.t ....................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_VEP_output.t ....................... ok    
./t/Config.t ......................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Config.t ......................................... ok    
./t/TranscriptTree.t ................................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/TranscriptTree.t ................................. ok    
./t/InputBuffer.t .................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/InputBuffer.t .................................... ok    
./t/OutputFactory_JSON.t ............................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_JSON.t ............................. ok    
./t/Parser.t ......................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser.t ......................................... ok     
./t/VariantRecoder.t ................................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
"my" variable $sth masks earlier declaration in same scope at Bio/EnsEMBL/DBSQL/TranslationAdaptor.pm line 607.
./t/VariantRecoder.t ................................. ok    
./t/AnnotationSource_File.t .......................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File.t .......................... ok    
./t/Parser_ID.t ...................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser_ID.t ...................................... ok   
./t/OutputFactory.t .................................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory.t .................................. ok     
./t/Parser_VEP_input.t ............................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser_VEP_input.t ............................... ok    
./t/Parser_SPDI.t .................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser_SPDI.t .................................... ok   
./t/CacheDir.t ....................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/CacheDir.t ....................................... ok    
./t/AnnotationSource_Database_Transcript.t ........... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_Transcript.t ........... ok    
./t/Runner.t ......................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Runner.t ......................................... 50/? 
-------------------- EXCEPTION --------------------
MSG: ERROR: Cannot use format gff without Bio::DB::HTS::Tabix module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:162
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:228
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:93
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:361
STACK toplevel ./t/Runner.t:755
Date (localtime)    = Thu Feb 17 09:19:07 2022
Ensembl API version = 105
---------------------------------------------------
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 73.
./t/Runner.t ......................................... Dubious, test returned 255 (wstat 65280, 0xff00)
All 73 subtests passed 
./t/AnnotationSource_Database_StructuralVariation.t .. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_StructuralVariation.t .. ok    
./t/AnnotationSource_Cache_RegFeat.t ................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_RegFeat.t ................. ok    
./t/AnnotationSource_File_GFF.t ...................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_GFF.t ...................... ok    
./t/Parser_HGVS.t .................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser_HGVS.t .................................... ok    
./t/AnnotationSource_File_VCF.t ...................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_VCF.t ...................... ok    
./t/bam_edit.t ....................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/bam_edit.t ....................................... ok    
./t/OutputFactory_VCF.t .............................. Possible attempt to separate words with commas at ./t/OutputFactory_VCF.t line 580.
Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_VCF.t .............................. ok    
./t/AnnotationSourceAdaptor.t ........................ Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSourceAdaptor.t ........................ ok    
./t/Stats.t .......................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Stats.t .......................................... ok    
./t/AnnotationSource_Cache_Transcript.t .............. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_Transcript.t .............. ok    
./t/AnnotationSource_File_BED.t ...................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_BED.t ...................... ok    
./t/AnnotationSource.t ............................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource.t ............................... ok    
./t/AnnotationSource_Cache_Variation.t ............... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_Variation.t ............... ok    
./t/Parser_VCF.t ..................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser_VCF.t ..................................... ok    
./t/Parser_CAID.t .................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser_CAID.t .................................... ok    
./t/BaseVEP.t ........................................ Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/BaseVEP.t ........................................ ok    
./t/AnnotationSource_File_GTF.t ...................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_GTF.t ...................... ok    

Test Summary Report
-------------------
./t/Runner.t                                       (Wstat: 65280 Tests: 73 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=42, Tests=1716, 88 wallclock secs ( 0.19 usr  0.12 sys + 84.55 cusr  2.55 csys = 87.41 CPU)
Result: FAIL
Failed 1/42 test programs. 0/1716 subtests failed.

**Comment by eibol1** [comment]
Maybe I have to rerun the installation with --NO_HTSLIB or maybe I have to install before Bio::Root::Version module?

**Comment by nakib103** [comment]
There can be an issue with `BioPerl` downloaded by VEP. It can happen if there is a clash between version of `BioPerl` downloaded using VEP and if there is another one downloaded by cpanm ( #345 ). 

Can you confirm if any other version is installed by cpanm? You can follow this step to resolve the issue - 

1) Uninstall the cpanm module Bio::Root::Version (should be as simple as `cpanm —uninstall Bio::Root::Version`)
2) Download BioPerl manually and add it to your $PERL5LIB variable:
3) Just in case, update your Module::Build package.

E.g.
```
cpanm —uninstall Bio::Root::Version
wget https://cpan.metacpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.6.924.tar.gz 
tar -zxvf BioPerl-1.6.924.tar.gz
PERL5LIB=${PERL5LIB}:${HOME}/src/bioperl-1.6.924
cpanm Module::Build
```

**Comment by eibol1** [comment]
Hi Nakib,

I followed the instructions here: [http://m.ensembl.org/info/docs/tools/vep/script/vep_download.html](url) "Using VEP in Mac OS". 

I did the steps: **Perlbrew, xz, MySqL, BioPerl, Final Dependancies and Installing VEP.**

In the step **Installing VEP**, I type `sudo perl INSTALL.pl --NO_TEST ` and overwrited existing files, but i didn't install cache files because this step gave me some problems and now it is supposed to work. 

How can I download manually cache files, specifically 105_GRCh38.tar.gz? where I have to locate this file? in home/.vep? How can I check that vep runs correctly? 

thank you so much,

**Comment by nakib103** [comment]
Hello @eibol1 ,

It's great to hear that you have resolved the issue!

To manually setup cache you can refer to this page - 
https://github.com/Ensembl/ensembl-vep/issues/url 

And, you can also find details how to run VEP with cache here - 
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html 

In general you will see errors go to `STDERR` when running VEP in command line in case something is not right and you can also get this on a file by passing it to `--warning_file` argument (see above page). A good idea would be to go through the VEP tutorials page - https://www.ensembl.org/info/docs/tools/vep/script/vep_tutorial.html  first.

Let me know if I you face any further problems.

Best regards,
Nakib

**Comment by eibol1** [comment]
Thank you so much @nakib103 , I close this issue! Have a nice day
