### ISSUE TITLE
How Can I install Cache directory and Cache Files manually?

### ISSUE THREAD

**Issue by eibol1** [Ensembl/ensembl-vep#1114]
Hi, 

I thought that I installed well but then I try: `./vep --help` and I got:

Can't locate Try/Tiny.pm in @INC (you may need to install the Try::Tiny module) (@INC contains: /Users/abelgd/Bioinfo/ensembl-vep/modules /Users/abelgd/Bioinfo/ensembl-vep /Users/abelgd/src/bioperl-1.6.924 /Users/abelgd/Bioinfo/ensembl-vep/BioPerl-1.6.924 /Users/abelgd/perl5/perlbrew/perls/5.26.2/lib/site_perl/5.26.2/darwin-thread-multi-2level /Users/abelgd/perl5/perlbrew/perls/5.26.2/lib/site_perl/5.26.2 /Users/abelgd/perl5/perlbrew/perls/5.26.2/lib/5.26.2/darwin-thread-multi-2level /Users/abelgd/perl5/perlbrew/perls/5.26.2/lib/5.26.2) at /Users/abelgd/Bioinfo/ensembl-vep/Bio/EnsEMBL/IO/Parser.pm line 44.
BEGIN failed--compilation aborted at /Users/abelgd/Bioinfo/ensembl-vep/Bio/EnsEMBL/IO/Parser.pm line 44.
Compilation failed in require at /Users/abelgd/perl5/perlbrew/perls/5.26.2/lib/5.26.2/parent.pm line 16.
BEGIN failed--compilation aborted at /Users/abelgd/Bioinfo/ensembl-vep/Bio/EnsEMBL/IO/TextParser.pm line 45.
Compilation failed in require at /Users/abelgd/perl5/perlbrew/perls/5.26.2/lib/5.26.2/parent.pm line 16.
BEGIN failed--compilation aborted at /Users/abelgd/Bioinfo/ensembl-vep/Bio/EnsEMBL/IO/ColumnBasedParser.pm line 36.
Compilation failed in require at /Users/abelgd/perl5/perlbrew/perls/5.26.2/lib/5.26.2/parent.pm line 16.
BEGIN failed--compilation aborted at /Users/abelgd/Bioinfo/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 45.
Compilation failed in require at /Users/abelgd/perl5/perlbrew/perls/5.26.2/lib/5.26.2/parent.pm line 16.
BEGIN failed--compilation aborted at /Users/abelgd/Bioinfo/ensembl-vep/Bio/EnsEMBL/IO/Parser/VCF4.pm line 41.
Compilation failed in require at /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 79.
BEGIN failed--compilation aborted at /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 79.
Compilation failed in require at /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 71.
BEGIN failed--compilation aborted at /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 71.
Compilation failed in require at /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 83.
BEGIN failed--compilation aborted at /Users/abelgd/Bioinfo/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 83.
Compilation failed in require at ./vep line 20.
BEGIN failed--compilation aborted at ./vep line 20.

Can anyone help me? 

### System
- VEP version: 105
- Perl version: 5.26.2
- OS: MacOS

**Comment by eibol1** [comment]
Here I put all the lines of the installation: 

ensembl-vep git:(release/105) ✗ sudo perl INSTALL.pl --NO_TEST
Password:
WARNING: DBD::mysql module not found. VEP can only run in offline (--offline) mode without DBD::mysql installed

http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#requirements
Installation on OSX requires that you set up some paths before running this installer.
Have you 
1. added /Users/abelgd/Bioinfo/ensembl-vep/htslib to your DYLD_LIBRARY_PATH environment variable?
(y/n): y

Hello! This installer is configured to install v105 of the Ensembl API for use by the VEP.
It will not affect any existing installations of the Ensembl API that you may have.

It will also download and install cache files from Ensembl's FTP server.

Checking for installed versions of the Ensembl API...done

Setting up directories
Destination directory ./Bio already exists.
Do you want to overwrite it (if updating VEP this is probably OK) (y/n)? y
 - fetching BioPerl
 - unpacking ./Bio/tmp/release-1-6-924.zip
 - moving files
Attempting to install Bio::DB::HTS and htslib.

>>> If this fails, try re-running with --NO_HTSLIB

 - checking out HTSLib
fatal: destination path 'htslib' already exists and is not an empty directory.
 - building HTSLIB in ./htslib
In /Users/abelgd/Bioinfo/ensembl-vep/htslib
make: Nothing to be done for `all'.
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.11 - moving files to ./biodbhts
 - making Bio::DB:HTS
Checking prerequisites...
  requires:
    !  Bio::Root::Version is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Run 'Build installdeps' to install missing prerequisites.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.11'
Building Bio-DB-HTS
cc -I/Users/abelgd/Bioinfo/ensembl-vep/htslib -I/Users/abelgd/perl5/perlbrew/perls/5.26.2/lib/5.26.2/darwin-thread-multi-2level/CORE -DVERSION="2.11" -DXS_VERSION="2.11" -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wno-unused-result -c -fno-common -DPERL_DARWIN -mmacosx-version-min=12.2 -arch x86_64 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV -O3 -o lib/Bio/DB/HTS.o lib/Bio/DB/HTS.c
lib/Bio/DB/HTS.xs:1770:22: warning: 'bcf_hdr_fmt_text' is deprecated: use bcf_hdr_format() instead [-Wdeprecated-declarations]
    RETVAL = newSVpv(bcf_hdr_fmt_text(header, is_bcf, &len), 0);
                     ^
/Users/abelgd/Bioinfo/ensembl-vep/htslib/htslib/vcf.h:440:9: note: 'bcf_hdr_fmt_text' has been explicitly marked deprecated here
        HTS_DEPRECATED("use bcf_hdr_format() instead");
        ^
/Users/abelgd/Bioinfo/ensembl-vep/htslib/htslib/hts_defs.h:65:49: note: expanded from macro 'HTS_DEPRECATED'
#define HTS_DEPRECATED(message) __attribute__ ((__deprecated__ (message)))
                                                ^
1 warning generated.
ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Bio/DB/HTS/HTS.bs')
env LD_RUN_PATH=/Users/abelgd/perl5/perlbrew/perls/5.26.2/lib/5.26.2/darwin-thread-multi-2level/CORE cc -arch x86_64 -mmacosx-version-min=12.2 -bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector-strong -o blib/arch/auto/Bio/DB/HTS/HTS.bundle lib/Bio/DB/HTS.o -L/Users/abelgd/Bioinfo/ensembl-vep/htslib -Wl,-rpath,/Users/abelgd/Bioinfo/ensembl-vep/htslib -lhts -lpthread -lz
cc -I/Users/abelgd/Bioinfo/ensembl-vep/htslib -I/Users/abelgd/perl5/perlbrew/perls/5.26.2/lib/5.26.2/darwin-thread-multi-2level/CORE -DVERSION="2.11" -DXS_VERSION="2.11" -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wno-unused-result -c -fno-common -DPERL_DARWIN -mmacosx-version-min=12.2 -arch x86_64 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV -O3 -o lib/Bio/DB/HTS/Faidx.o lib/Bio/DB/HTS/Faidx.c
ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Bio/DB/HTS/Faidx/Faidx.bs')
env LD_RUN_PATH=/Users/abelgd/perl5/perlbrew/perls/5.26.2/lib/5.26.2/darwin-thread-multi-2level/CORE cc -arch x86_64 -mmacosx-version-min=12.2 -bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector-strong -o blib/arch/auto/Bio/DB/HTS/Faidx/Faidx.bundle lib/Bio/DB/HTS/Faidx.o -L/Users/abelgd/Bioinfo/ensembl-vep/htslib -Wl,-rpath,/Users/abelgd/Bioinfo/ensembl-vep/htslib -lhts -lpthread -lz

Downloading required Ensembl API files
 - fetching ensembl
 - unpacking ./Bio/tmp/ensembl.zip
 - moving files
 - getting version information
 - fetching ensembl-variation
 - unpacking ./Bio/tmp/ensembl-variation.zip
 - moving files
 - getting version information
 - fetching ensembl-funcgen
 - unpacking ./Bio/tmp/ensembl-funcgen.zip
 - moving files
 - getting version information
 - fetching ensembl-io
 - unpacking ./Bio/tmp/ensembl-io.zip
 - moving files
 - getting version information

The VEP can either connect to remote or local databases, or use local cache files.
Using local cache files is the fastest and most efficient way to run the VEP
Cache files will be stored in /Users/abelgd/.vep
Do you want to install any cache files (y/n)? n
Skipping cache installation

The VEP can use FASTA files to retrieve sequence data for HGVS notations and reference sequence checks.
FASTA files will be stored in /Users/abelgd/.vep
Do you want to install any FASTA files (y/n)? n
Skipping FASTA installation - Exiting

The VEP can use plugins to add functionality and data.
Plugins will be installed in /Users/abelgd/.vep/Plugins
Do you want to install any plugins (y/n)? y
Plugins directory /Users/abelgd/.vep/Plugins does not exists - do you want to create it (y/n)? y

The following plugins are available; which do you want (can specify multiple separated by spaces or 0 for all): 
# Pathogenicity predictions
   1: dbNSFP                   - dbNSFP provides pathogenicity predictions for missense variants from various algorithms
   2: CADD                     - Combined Annotation Dependent Depletion (CADD) is a tool for scoring the deleteriousness of single nucleotide variants and insertion/deletion variants in the human genome. CADD integrates multiple annotations into one metric by contrasting variants that survived natural selection with simulated mutations.
   3: FATHMM                   - 
   4: FATHMM_MKL               - FATHMM-MKL predicts functional consequences of variants, both coding and non-coding.
   5: Gwava                    - Retrieves precomputed Genome Wide Annotation of VAriants (GWAVA) scores for any  variant that overlaps a known variant from the Ensembl variation database
   6: Carol                    - Calculates the Combined Annotation scoRing toOL (CAROL) score for a missense mutation based on the pre-calculated SIFT and PolyPhen scores
   7: Condel                   - Calculates the Consensus Deleteriousness (Condel) score for a missense mutation based on the pre-calculated SIFT and PolyPhen scores
   8: LoF                      - LOFTEE identifies LoF (loss-of-function) variation
   9: LoFtool                  - Provides a per-gene rank of genic intolerance and consequent susceptibility to disease based on the ratio of Loss-of-function (LoF) to synonymous mutations in ExAC data
  10: ExACpLI                  - Provides a per-gene probability of being loss-of-function intolerant (pLI) from ExAC data
  11: MPC                      - MPC is a missense deleteriousness metric based on the analysis of genic regions depleted of missense mutations in ExAC
  12: MTR                      - MTR scores quantify the amount of purifying selection acting specifically on missense variants in a given window of protein-coding sequence
  13: PrimateAI                - PrimateAI scores can be used to assess pathogenicity of variants in humans
  14: REVEL                    - An ensemble method for predicting the pathogenicity of rare missense variants
  15: PON_P2                   - 
  16: ClinPred                 - A prediction tool for the identification of disease-relevant nonsynonymous single nucleotide variants
# Splicing predictions
  17: dbscSNV                  - Retrieves data for splicing variants from a tabix-indexed dbscSNV file
  18: GeneSplicer              - Detects splice sites in genomic DNA
  19: MaxEntScan               - Sequence motif and maximum entropy based splice site consensus predictions
  20: SpliceRegion             - More granular predictions of splicing effects
  21: SpliceAI                 - Pre-calculated annotations from SpliceAI a deep neural network, developed by Illumina, Inc that predicts splice junctions from an arbitrary pre-mRNA transcript sequence. Used for non-commercial purposes (https://github.com/Illumina/SpliceAI)
# Conservation
  22: Blosum62                 - BLOSUM62 amino acid conservation score
  23: Conservation             - Retrieves a conservation score from the Ensembl Compara databases for variant positions
  24: AncestralAllele          - Retrieves the ancestral allele for variants inferred from the Ensembl Compara Enredo-Pecan-Ortheus (EPO) pipeline
# Frequency data
  25: ExAC                     - Reports allele frequencies from the Exome Aggregation Consortium
  26: gnomADc                  - 
# Phenotype data and citations
  27: Phenotypes               - Retrieves overlapping phenotype annotations
  28: GO                       - Retrieves Gene Ontology terms associated with transcripts/translations via the Ensembl API
  29: G2P                      - Assesses variants using G2P allelic requirements for potential phenotype involvement.
  30: PostGAP                  - 
  31: satMutMPRA               - Reports saturation mutagenesis MPRA measures of variant effects on gene RNA expression for 21 enhancers/promoters
  32: DisGeNET                 - Variant-Disease-PMID associations from the DisGeNET database (https://www.disgenet.org/)
  33: Mastermind               - Variants with clinical evidence cited in the medical literature reported by Mastermind Genomic Search Engine (https://www.genomenon.com/mastermind)
# Variant data
  34: LD                       - Finds variants in linkage disequilibrium with any overlapping existing variants from the Ensembl variation databases
  35: SameCodon                - Reports existing variants that fall in the same codon
  36: LOVD                     - Retrieves LOVD variation data
  37: SubsetVCF                - 
# Nearby features
  38: NearestGene              - Finds the nearest gene to non-genic variants
  39: NearestExonJB            - 
  40: Downstream               - Predicts the downstream effects of a frameshift variant on the protein sequence of a transcript
  41: TSSDistance              - Calculates the distance from the transcription start site for upstream variants   
# Sequence
  42: ProteinSeqs              - Prints out the reference and mutated protein sequences of any proteins found with non-synonymous mutations
  43: ReferenceQuality         - 
# Visualisation
  44: Draw                     - Creates images of the transcript model showing variant location
# Look up
  45: LocalID                  - Allows you to use variant IDs as VEP input without making a database connection.
# External ID
  46: FlagLRG                  - 
# Motif
  47: FunMotifs                - 
# HGVS
  48: HGVSIntronOffset         - 
  49: SingleLetterAA           - 
# Structural variant data
  50: StructuralVariantOverlap - 
# Nonsense-mediated predictions
  51: NMD                      - Nonsense-mediated mRNA decay escaping variants prediction
# Protein data
  52: neXtProt                 - Retrieves protein-related data from neXtProt
# Other plugins
  53: CSN                      - Reports Clinical Sequencing Nomenclature (CSN) for variants
  54: miRNA                    - Determines where in the secondary structure of a miRNA a variant falls

? 1 2 16 26

 - installing "dbNSFP"
 - This plugin requires installation
 - This plugin requires data
 - See /Users/abelgd/.vep/Plugins/dbNSFP.pm for details
 - OK

 - installing "CADD"
 - This plugin requires data
 - See /Users/abelgd/.vep/Plugins/CADD.pm for details
 - OK

 - installing "ClinPred"
 - This plugin requires data
 - See /Users/abelgd/.vep/Plugins/ClinPred.pm for details
 - OK

 - installing "gnomADc"
 - add "--plugin gnomADc" to your VEP command to use this plugin
 - OK

NB: One or more plugins that you have installed will not work without installation or downloading data; see logs above

All done

**Comment by nakib103** [comment]
Hello @eibol1,

It seems you have some missing Perl libraries. Can you try installing them with - 
`sudo cpanm install Try::Tiny`

and try running VEP again. Let me know if this fixes your error.

Best regards
Nakib

**Comment by eibol1** [comment]
Hi @nakib103, 

Done what you said and it looks like it works: 

➜  ensembl-vep git:(release/105) ✗ `./vep --help `
#----------------------------------#
# ENSEMBL VARIANT EFFECT PREDICTOR #
#----------------------------------#

Versions:
  ensembl              : 105.525fbcb
  ensembl-funcgen      : 105.660df8f
  ensembl-io           : 105.2a0a40c
  ensembl-variation    : 105.ac8178e
  ensembl-vep          : 105.0

Help: dev@ensembl.org , helpdesk@ensembl.org
Twitter: @ensembl

http://www.ensembl.org/info/docs/tools/vep/script/index.html

Usage:
./vep [--cache|--offline|--database] [arguments]

Basic options
=============

--help                 Display this message and quit

-i | --input_file      Input file
-o | --output_file     Output file
--force_overwrite      Force overwriting of output file
--species [species]    Species to use [default: "human"]
                       
--everything           Shortcut switch to turn on commonly used options. See web
                       documentation for details [default: off]                       
--fork [num_forks]     Use forking to improve script runtime

For full option documentation see:
http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html

I did not install cache files, how can I do that now that I have VEP installed?

kind regards,

Abel

**Comment by eibol1** [comment]
Ok Nakib, 

I've found how to in this URL https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#pre

Can you tell me if with the message I put in the comment above VEP is well installed?

**Comment by nakib103** [comment]
Hello @eibol1 ,

It greats it has solved your issue. The output of `./vep --help` shows your installation is successful.

Great you found the page - https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#pre that is the correct place to go to when you want to download vep cache.

Let me know if you face any other issues.

Best regards,
Nakib

**Comment by nakib103** [comment]
I'm going to close the issue for now but feel free to open a new one if you have more questions.

Best regards,
Nakib
