### ISSUE TITLE
Can't locate Bio/EnsEMBL/IO/Parser/VCF4.pm in @INC

### ISSUE THREAD

**Issue by JiguuP** [Ensembl/ensembl-vep#1117]
Hello, I tried to figure out this error, but cannot sovled it.

my code is
`/home/jisoojihyun/ensembl-vep/vep --no_stats -vcf --force --symbol --terms SO --tsl --hgvs --fasta /home/sysbioinfo1/.vep/homo_sapiens/Homo_sapiens.GRCh38.dna.primary_assembly.fa --offline --pick --transcript_version --cache --plugin Downstream --plugin Wildtype --no_check_variants_order --buffer_size 20000 --dir_cache /home/sysbioinfo1/.vep/ --assembly GRCh38 -i /home/jisoojihyun/NeoAntigen/Somatic_SAAV-SJNa/vcf/Output_RE-P007_20220221.vcf -o /home/jisoojihyun/output.vep.vcf
`
and the error is
`Can't locate Bio/EnsEMBL/IO/Parser/VCF4.pm in @INC (you may need to install the Bio::EnsEMBL::IO::Parser::VCF4 module) (@INC contains: /home/jisoojihyun/ensembl-vep/modules /home/jisoojihyun/ensembl-vep /home/jisoojihyun/src/bioperl-1.6.924 /home/jisoojihyun/src/ensembl/modules /home/jisoojihyun/src/ensembl-compara/modules /home/jisoojihyun/src/ensembl-variation/modules /home/jisoojihyun/src/ensembl-funcgen/modules /home/jisoojihyun/anaconda3/envs/NA/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi /home/jisoojihyun/anaconda3/envs/NA/lib/perl5/site_perl/5.22.0 /home/jisoojihyun/anaconda3/envs/NA/lib/perl5/5.22.0/x86_64-linux-thread-multi /home/jisoojihyun/anaconda3/envs/NA/lib/perl5/5.22.0 .) at /home/jisoojihyun/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 79.
BEGIN failed--compilation aborted at /home/jisoojihyun/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 79.
Compilation failed in require at /home/jisoojihyun/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 71.
BEGIN failed--compilation aborted at /home/jisoojihyun/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 71.
Compilation failed in require at /home/jisoojihyun/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 83.
BEGIN failed--compilation aborted at /home/jisoojihyun/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 83.
Compilation failed in require at /home/jisoojihyun/ensembl-vep/vep line 20.
BEGIN failed--compilation aborted at /home/jisoojihyun/ensembl-vep/vep line 20.
`
I checked 'Bio/EnsEMBL/IO', but it is not exsited. So I downloaded agin by git clone, it was still same.
Also I put 'perl INSTALL.pl', 'perl INSTALL.pl --AUTO a', it didn't work.

"perl -MModule::Build -le 'print $Module::Build::VERSION'" said 0.4231.

Additionally, I tried to install Bio::DB:HTS with  the code 'cpan Bio::DB:HTS', I got a error again.

`**Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/home/jisoojihyun/.cpan/Metadata'
  Database was generated on Tue, 22 Feb 2022 08:55:45 GMT
Running install for module 'Bio::DB::HTS'
Checksum for /home/jisoojihyun/.cpan/sources/authors/id/A/AV/AVULLO/Bio-DB-HTS-3.01.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring A/AV/AVULLO/Bio-DB-HTS-3.01.tar.gz with Build.PL

This module requires HTSlib (http://htslib.org/)
Install it if you have not done so already.

This script will attempt to locate HTSlib by looking for htslib/hts.h
and libhts.a / libhts.so in:

  1. --htslib command line argument
  2. HTSLIB_DIR environment variable
  3. --prefix command line argument (which also sets installation location)
  4. Alien::HTSlib dependency resolver
  5. pkg-config (extra directories can be set in PKG_CONFIG_PATH environment variable)
  6. common library locations: /usr /usr/local, /usr/share, /opt/local

Warning: No success on command[/home/jisoojihyun/anaconda3/envs/NA/bin/perl Build.PL]
  AVULLO/Bio-DB-HTS-3.01.tar.gz
  /home/jisoojihyun/anaconda3/envs/NA/bin/perl Build.PL -- NOT OK
But I have htslib directory under 'ensembl-vep'.**`

How can I fix it?
Thank you.

**Comment by diegomscoelho** [comment]
Hi @JiguuP,

I am going to close this issue now.

If you have any further questions, please feel free to reopen it or create a new issue.

Regards
@diegomscoelho
