### ISSUE TITLE
Cryptic warnings when installing VEP

### ISSUE THREAD

**Issue by Filago4** [Ensembl/ensembl-vep#1118]
## Describe the issue
Hello,
I installed VEP (V105) and received no error during installation, but a lot of **warnings** when building the HTS-Lib. What to do?

### System
- VEP version: 105 (hg37)
- Perl version: e.g. 5.32
- OS: Linux/Fedora

### Full error message
building HTSLIB in ./htslib
In /home/myname/ensembl-vep/htslib
echo '/* Default config.h generated by Makefile */' > config.h
echo '#define HAVE_LIBBZ2 1' >> config.h
echo '#define HAVE_LIBLZMA 1' >> config.h
echo '#define HAVE_LZMA_H 1' >> config.h
echo '#define HAVE_FSEEKO 1' >> config.h
echo '#define HAVE_DRAND48 1' >> config.h
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o kfunc.o kfunc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o knetfile.o knetfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o kstring.o kstring.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o bcf_sr_sort.o bcf_sr_sort.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o bgzf.o bgzf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o errmod.o errmod.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o faidx.o faidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hfile.o hfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.9-dirty"' > version.h
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hts.o hts.c
hts.c: In function ‘hts_idx_init’:
hts.c:1386:59: **warning**: overflow in conversion from ‘uint32_t’ {aka ‘unsigned int’} to ‘int’ changes value from ‘idx->z.last_bin = 4294967295’ to ‘-1’ [-Woverflow]
 1386 |     idx->z.save_bin = idx->z.save_tid = idx->z.last_tid = idx->z.last_bin = 0xffffffffu;
      |                                                           ^~~
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hts_os.o hts_os.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o md5.o md5.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o multipart.o multipart.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o probaln.o probaln.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o realn.o realn.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o regidx.o regidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o sam.o sam.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o synced_bcf_reader.o synced_bcf_reader.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcf_sweep.o vcf_sweep.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o tbx.o tbx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o textutils.o textutils.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o thread_pool.o thread_pool.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcf.o vcf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcfutils.o vcfutils.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_decode.o cram/cram_decode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_encode.o cram/cram_encode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_external.o cram/cram_external.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_index.o cram/cram_index.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c: In function ‘cram_populate_ref’:
cram/cram_io.c:2095:9: **warning**: ‘strncpy’ specified bound 4096 equals destination size [-Wstringop-truncation]
 2095 |         strncpy(path, path2, PATH_MAX);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘full_path’,
    inlined from ‘cram_write_SAM_hdr’ at cram/cram_io.c:3823:17:
cram/cram_io.c:3748:13: **warning**: ‘strncpy’ specified bound 4096 equals destination size [-Wstringop-truncation]
 3748 |             strncpy(out, in, PATH_MAX);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
cram/cram_io.c: In function ‘cram_dopen’:
cram/cram_io.c:4126:9: **warning**: ‘strncpy’ specified bound 20 equals destination size [-Wstringop-truncation]
 4126 |         strncpy(def->file_id, filename, 20);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_samtools.o cram/cram_samtools.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_stats.o cram/cram_stats.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/files.o cram/files.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/mFILE.o cram/mFILE.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/open_trace_file.o cram/open_trace_file.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/pooled_alloc.o cram/pooled_alloc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/rANS_static.o cram/rANS_static.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/sam_header.o cram/sam_header.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/string_alloc.o cram/string_alloc.c
ar -rc libhts.a kfunc.o knetfile.o kstring.o bcf_sr_sort.o bgzf.o errmod.o faidx.o hfile.o hfile_net.o hts.o hts_os.o md5.o multipart.o probaln.o realn.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o textutils.o thread_pool.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o
ranlib libhts.a
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o kfunc.pico kfunc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o knetfile.pico knetfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o kstring.pico kstring.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o bcf_sr_sort.pico bcf_sr_sort.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o bgzf.pico bgzf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o errmod.pico errmod.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o faidx.pico faidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o hfile.pico hfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o hfile_net.pico hfile_net.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o hts.pico hts.c
hts.c: In function ‘hts_idx_init’:
hts.c:1386:59: **warning**: overflow in conversion from ‘uint32_t’ {aka ‘unsigned int’} to ‘int’ changes value from ‘idx->z.last_bin = 4294967295’ to ‘-1’ [-Woverflow]
 1386 |     idx->z.save_bin = idx->z.save_tid = idx->z.last_tid = idx->z.last_bin = 0xffffffffu;
      |                                                           ^~~
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o hts_os.pico hts_os.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o md5.pico md5.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o multipart.pico multipart.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o probaln.pico probaln.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o realn.pico realn.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o regidx.pico regidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o sam.pico sam.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o synced_bcf_reader.pico synced_bcf_reader.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o vcf_sweep.pico vcf_sweep.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o tbx.pico tbx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o textutils.pico textutils.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o thread_pool.pico thread_pool.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o vcf.pico vcf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o vcfutils.pico vcfutils.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_codecs.pico cram/cram_codecs.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_decode.pico cram/cram_decode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_encode.pico cram/cram_encode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_external.pico cram/cram_external.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_index.pico cram/cram_index.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_io.pico cram/cram_io.c
cram/cram_io.c: In function ‘cram_populate_ref’:
cram/cram_io.c:2095:9: **warning**: ‘strncpy’ specified bound 4096 equals destination size [-Wstringop-truncation]
 2095 |         strncpy(path, path2, PATH_MAX);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘full_path’,
    inlined from ‘cram_write_SAM_hdr’ at cram/cram_io.c:3823:17:
cram/cram_io.c:3748:13: **warning**: ‘strncpy’ specified bound 4096 equals destination size [-Wstringop-truncation]
 3748 |             strncpy(out, in, PATH_MAX);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
cram/cram_io.c: In function ‘cram_dopen’:
cram/cram_io.c:4126:9: **warning**: ‘strncpy’ specified bound 20 equals destination size [-Wstringop-truncation]
 4126 |         strncpy(def->file_id, filename, 20);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_samtools.pico cram/cram_samtools.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_stats.pico cram/cram_stats.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/files.pico cram/files.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/mFILE.pico cram/mFILE.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/open_trace_file.pico cram/open_trace_file.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/pooled_alloc.pico cram/pooled_alloc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/rANS_static.pico cram/rANS_static.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/sam_header.pico cram/sam_header.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/string_alloc.pico cram/string_alloc.c
gcc -shared -Wl,-soname,libhts.so.2  -o libhts.so kfunc.pico knetfile.pico kstring.pico bcf_sr_sort.pico bgzf.pico errmod.pico faidx.pico hfile.pico hfile_net.pico hts.pico hts_os.pico md5.pico multipart.pico probaln.pico realn.pico regidx.pico sam.pico synced_bcf_reader.pico vcf_sweep.pico tbx.pico textutils.pico thread_pool.pico vcf.pico vcfutils.pico cram/cram_codecs.pico cram/cram_decode.pico cram/cram_encode.pico cram/cram_external.pico cram/cram_index.pico cram/cram_io.pico cram/cram_samtools.pico cram/cram_stats.pico cram/files.pico cram/mFILE.pico cram/open_trace_file.pico cram/pooled_alloc.pico cram/rANS_static.pico cram/sam_header.pico cram/string_alloc.pico -lz -lm -lbz2 -llzma -lpthread
ln -sf libhts.so libhts.so.2
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o bgzip.o bgzip.c
gcc  -o bgzip bgzip.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o htsfile.o htsfile.c
gcc  -o htsfile htsfile.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o tabix.o tabix.c
gcc  -o tabix tabix.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/hts_endian.o test/hts_endian.c
gcc  -o test/hts_endian test/hts_endian.o -lz -lm -lbz2 -llzma
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/fieldarith.o test/fieldarith.c
gcc  -o test/fieldarith test/fieldarith.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/hfile.o test/hfile.c
gcc  -o test/hfile test/hfile.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/sam.o test/sam.c
gcc  -o test/sam test/sam.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test_bgzf.o test/test_bgzf.c
gcc  -o test/test_bgzf test/test_bgzf.o libhts.a -lz -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test_realn.o test/test_realn.c
gcc  -o test/test_realn test/test_realn.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-regidx.o test/test-regidx.c
gcc  -o test/test-regidx test/test-regidx.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test_view.o test/test_view.c
gcc  -o test/test_view test/test_view.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-vcf-api.o test/test-vcf-api.c
gcc  -o test/test-vcf-api test/test-vcf-api.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-vcf-sweep.o test/test-vcf-sweep.c
gcc  -o test/test-vcf-sweep test/test-vcf-sweep.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-bcf-sr.o test/test-bcf-sr.c
gcc  -o test/test-bcf-sr test/test-bcf-sr.o libhts.a -lz -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-bcf-translate.o test/test-bcf-translate.c
gcc  -o test/test-bcf-translate test/test-bcf-translate.o libhts.a -lz -lz -lm -lbz2 -llzma -lpthread
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.11 - moving files to ./biodbhts
 - making Bio::DB:HTS
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.11'
Building Bio-DB-HTS
gcc -I/home/myname/ensembl-vep/htslib -I/usr/lib64/perl5/CORE -DVERSION="2.11" -DXS_VERSION="2.11" -fPIC -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wno-unused-result -c -D_REENTRANT -D_GNU_SOURCE -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fwrapv -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g -o lib/Bio/DB/HTS.o lib/Bio/DB/HTS.c
lib/Bio/DB/HTS.xs: In function ‘hts_fetch_fun’:
lib/Bio/DB/HTS.xs:147:7: **warning**: variable ‘count’ set but not used [-Wunused-but-set-variable]
  147 |   int count;
      |       ^~~~~
lib/Bio/DB/HTS.xs: In function ‘invoke_pileup_callback_fun’:
lib/Bio/DB/HTS.xs:193:7: **warning**: variable ‘count’ set but not used [-Wunused-but-set-variable]
  193 |   int count,i;
      |       ^~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTS_htslib_version’:
lib/Bio/DB/HTS.c:565:17: **warning**: variable ‘packname’ set but not used [-Wunused-but-set-variable]
  565 |         char *  packname;
      |                 ^~~~~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTS__Fai_load’:
lib/Bio/DB/HTS.c:591:17: **warning**: variable ‘packname’ set but not used [-Wunused-but-set-variable]
  591 |         char *  packname;
      |                 ^~~~~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTSfile_is_remote’:
lib/Bio/DB/HTS.c:708:17: **warning**: unused variable ‘packname’ [-Wunused-variable]
  708 |         char *  packname = (char *)SvPV_nolen(ST(0))
      |                 ^~~~~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTSfile_open’:
lib/Bio/DB/HTS.c:730:17: **warning**: unused variable ‘packname’ [-Wunused-variable]
  730 |         char *  packname = (char *)SvPV_nolen(ST(0))
      |                 ^~~~~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTSfile_index_build’:
lib/Bio/DB/HTS.c:790:17: **warning**: unused variable ‘packname’ [-Wunused-variable]
  790 |         char *  packname = (char *)SvPV_nolen(ST(0))
      |                 ^~~~~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTSfile_index_load’:
lib/Bio/DB/HTS.c:812:17: **warning**: unused variable ‘packname’ [-Wunused-variable]
  812 |         char *  packname = (char *)SvPV_nolen(ST(0))
      |                 ^~~~~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTSfile_header_read’:
lib/Bio/DB/HTS.xs:531:15: **warning**: variable ‘result’ set but not used [-Wunused-but-set-variable]
  531 |       int64_t result ;
      |               ^~~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTS__Alignment_new’:
lib/Bio/DB/HTS.c:1079:17: **warning**: variable ‘package’ set but not used [-Wunused-but-set-variable]
 1079 |         char *  package;
      |                 ^~~~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTS__VCFfile_open’:
lib/Bio/DB/HTS.c:3276:17: **warning**: unused variable ‘packname’ [-Wunused-variable]
 3276 |         char*   packname = (char *)SvPV_nolen(ST(0))
      |                 ^~~~~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTS__VCFfile_tbx_index_load’:
lib/Bio/DB/HTS.c:3310:17: **warning**: unused variable ‘packname’ [-Wunused-variable]
 3310 |         char*   packname = (char *)SvPV_nolen(ST(0))
      |                 ^~~~~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTS__VCFfile_bcf_index_load’:
lib/Bio/DB/HTS.c:3343:17: **warning**: unused variable ‘packname’ [-Wunused-variable]
 3343 |         char*   packname = (char *)SvPV_nolen(ST(0))
      |                 ^~~~~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTS__VCFfile_bcf_index_close’:
lib/Bio/DB/HTS.c:3377:17: **warning**: unused variable ‘packname’ [-Wunused-variable]
 3377 |         char*   packname = (char *)SvPV_nolen(ST(0))
      |                 ^~~~~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTS__VCFfile_num_variants’:
lib/Bio/DB/HTS.c:3498:17: **warning**: unused variable ‘packname’ [-Wunused-variable]
 3498 |         char*   packname = (char *)SvPV_nolen(ST(0))
      |                 ^~~~~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTS__VCFfile_query’:
lib/Bio/DB/HTS.c:3538:17: **warning**: unused variable ‘packname’ [-Wunused-variable]
 3538 |         char*   packname = (char *)SvPV_nolen(ST(0))
      |                 ^~~~~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTS__VCF__Iterator_iter_next’:
lib/Bio/DB/HTS.xs:1633:9: **warning**: unused variable ‘ret’ [-Wunused-variable]
 1633 |     int ret;
      |         ^~~
lib/Bio/DB/HTS.xs: In function ‘XS_Bio__DB__HTS__VCF__Header_fmt_text’:
lib/Bio/DB/HTS.xs:1770:5: **warning**: ‘bcf_hdr_fmt_text’ is deprecated: use bcf_hdr_format() instead [-Wdeprecated-declarations]
 1770 |     RETVAL = newSVpv(bcf_hdr_fmt_text(header, is_bcf, &len), 0);
      |     ^~~~~~
In file included from lib/Bio/DB/HTS.xs:59:
/home/myname/ensembl-vep/htslib/htslib/vcf.h:439:11: note: declared here
  439 |     char *bcf_hdr_fmt_text(const bcf_hdr_t *hdr, int is_bcf, int *len)
      |           ^~~~~~~~~~~~~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTS__VCF__Row_get_format’:
lib/Bio/DB/HTS.xs:2110:11: **warning**: unused variable ‘row_ids’ [-Wunused-variable]
 2110 |       AV* row_ids;
      |           ^~~~~~~
lib/Bio/DB/HTS.xs:2102:14: **warning**: unused variable ‘avi’ [-Wunused-variable]
 2102 |       int i, avi;
      |              ^~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTS__VCF__Row_get_genotypes’:
lib/Bio/DB/HTS.xs:2222:11: **warning**: variable ‘ngt’ set but not used [-Wunused-but-set-variable]
 2222 |       int ngt ;
      |           ^~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTS__Kseq_new’:
lib/Bio/DB/HTS.c:5081:17: **warning**: unused variable ‘package’ [-Wunused-variable]
 5081 |         char *  package = (char *)SvPV_nolen(ST(0))
      |                 ^~~~~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTS__Kseq_newfh’:
lib/Bio/DB/HTS.c:5115:17: **warning**: unused variable ‘pack’ [-Wunused-variable]
 5115 |         char *  pack = (char *)SvPV_nolen(ST(0))
      |                 ^~~~
lib/Bio/DB/HTS.c: In function ‘XS_Bio__DB__HTS__Kseq__Kstream_new’:
lib/Bio/DB/HTS.c:5208:17: **warning**: unused variable ‘package’ [-Wunused-variable]
 5208 |         char *  package = (char *)SvPV_nolen(ST(0))
      |                 ^~~~~~~

**Comment by diegomscoelho** [comment]
Hi @Filago4,

It's normal to have some **warnings** during installation. Did you test `vep` after that to see if it's working?

Regards, @diegomscoelho

**Comment by diegomscoelho** [comment]
Hi @Filago4,

I am going to close this issue now.

If you have any further questions, please feel free to reopen it or create a new issue.

Regards
@diegomscoelho
