### ISSUE TITLE
VEP does not annotate HGVSg for some variants

### ISSUE THREAD

**Issue by FelixMoelder** [Ensembl/ensembl-vep#1119]
## Description
When annotating variants using VEP in some cases no HGVSg value is annotated while I would expect that that value should always be annotated.
The cache has been downloaded first by `vep install`, while version `105` of the plugins was downloaded from the github repo.
An example variant and the annotated output is attached. 

### System
- VEP version: 105
- VEP Cache version: 105
- Perl version: 5.26
- OS: Ubuntu
- tabix is installed

### Full VEP command line
```
 bcftools view <input.bcf> | vep --everything --vcf_info_field ANN --hgvsg --fork 2 --format vcf --vcf --offline --cache --dir_cache resources/vep/cache --cache_version 105 --species homo_sapiens --assembly GRCh38   --dir_plugins resources/vep/plugins --plugin LoFtool,resources/vep/plugins/LoFtool_scores.txt --plugin REVEL,resources/revel_scores.tsv.gz --output_file STDOUT --stats_file results/calls/Sample.stats.html
```

### Data files (if applicable)
They include:
- The input file: variant.bcf
- The output file: variant.annotated.bcf

[vep_testcase.zip](https://github.com/Ensembl/ensembl-vep/files/8130994/vep_testcase.zip)

**Comment by diegomscoelho** [comment]
Hi @FelixMoelder,

I was able to reproduce your problem. We are looking this issue and I will send an update here.

Thank you for reporting us.

Regards, @diegomscoelho

**Comment by diegomscoelho** [comment]
Hi @FelixMoelder,

Looking again at your input, we don't actually support `--hgvsg` flag usage for SV. We are going to discuss this new feature in our team, any news I will post it an answer here.

Thank you again.

Regards, @diegomscoelho

**Comment by likhitha-surapaneni** [comment]
Hi @FelixMoelder ,

Unfortunately we do not have immediate plans to support HGVSg for structural variants . I am closing this ticket for now, please feel free to open a new issue if you have any other questions.

Kind regards,
Likhitha
