### ISSUE TITLE
Documentation on building packages of vep

### ISSUE THREAD

**Issue by cking-ha** [Ensembl/ensembl-vep#112]
Hello,

I've been trying for the last few release to build an RPM of vep, but I was wondering if you had any documentation or suggestions for building vep as a package.

Thanks,

--Chris

**Comment by willmclaren** [comment]
Hi Chris,

We don't have any documentation for this unfortunately, nor do I have any direct experience building packages that could guide you.

VEP is available as a docker image and also as a bioconda recipe/package; you might find some helpful pointers by looking through the build processes for these.

[Dockerfile](https://github.com/Ensembl/ensembl-vep/blob/release/90/docker/Dockerfile)
[Bioconda VEP page](https://bioconda.github.io/recipes/ensembl-vep/README.html)
[Bioconda VEP recipe](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/ensembl-vep)
