### ISSUE TITLE
Reinstall VEP

### ISSUE THREAD

**Issue by Filago4** [Ensembl/ensembl-vep#1122]
Hello,
is there any option to remove vep from my system (Linux) and reinstall it completely from zero?
Is it an option to just delete all files in the ensembl-vep and ./vep folders, created during installation (are there any other files/folders created by vep)?

Many thanks for your help :)

**Comment by diegomscoelho** [comment]
Hi @Filago4,

If you delete your cloned repo `ensembl-vep` and your `.vep`, your probably good to go. Also check if BioPerl repo was installed with `ensembl-vep`, you can delete this also if you find it.

Hope this helped you, any other questions about this issue you can comment here.

Regards, @diegomscoelho

**Comment by Filago4** [comment]
Many thanks for your answer!

Do you know, how to locate BioPerl on linux/Fedora?

Many thanks in advance!

**Comment by diegomscoelho** [comment]
Hi @Filago4,

If you have installed BioPerl or other ensembl repos separately, you should delete them. If you just used, ensembl-vep installation, you just need to delete `ensembl-vep`.

Hope this helped you.

Regards, @diegomscoelho

**Comment by diegomscoelho** [comment]
Hi @Filago4,

I am going to close this issue now.

If you have any further questions, please feel free to reopen it or create a new issue.

Regards
@diegomscoelho
