### ISSUE TITLE
VEP filter

### ISSUE THREAD

**Issue by Danisov** [Ensembl/ensembl-vep#1123]
HI
I have a csv file (I also have the vcf) containing the annotation results of the varians from VEP of several samples. To facilitate prioritization I would like to add a column summarizing in which the variant was identified as homozygous and another column for the heterozygous variants. VEP can add this option? if not, do you have any suggestions?

**Comment by dglemos** [comment]
Hi @Danisov,
VEP does not have the functionality you are asking for. There is one option `--individual all` which only works with VCF files containing individual genotype data. This option returns the zygosity of the variant however not in the format you requested.

**Comment by dglemos** [comment]
I'm going to close this issue but feel free to re-open it in case you have more questions.

Best wishes,
Diana
