### ISSUE TITLE
Can I use dbNSFP v4.3 with VEP v105 ?

### ISSUE THREAD

**Issue by Z-Zen** [Ensembl/ensembl-vep#1124]
## Describe the issue
Like the title says, it is possible to use the current version of VEP (v105) and the [dbNSFP plugin of VEP](https://github.com/Ensembl/VEP_plugins/blob/release/105/dbNSFP.pm) with the latest data of dbNSFP (v4.3)?

## Additional information
[dbNSFP v4.3](https://sites.google.com/site/jpopgen/dbNSFP) have updated the versions of dbSNP and ClinVar. REVEL is now transcript-specific. Finally, a new column of genotypes for `Chagyrskaya  Neandertals` has been added. 

Will it be possible to run VEP with this new version of dbNSFP?

**Comment by dglemos** [comment]
Hi @Z-Zen,
The current dbNSFP plugin works with version 4.3 however, the results will not be transcript-specific. 

Best wishes,
Diana

**Comment by ntm** [comment]
Hi,
check out this PR, is this what you want? 
https://github.com/Ensembl/VEP_plugins/pull/461

**Comment by Z-Zen** [comment]
@ntm Hello!
Yes, this is exactly what I am looking for. Will it be available on vep release 106 ?
Thanks

**Comment by dglemos** [comment]
Hi @Z-Zen,
The updates will be available at the earliest on release 107.

**Comment by dglemos** [comment]
I'm going to close this issue but feel free to re-open it in case you have issues with the update in release 107. 

Best wishes,
Diana
