### ISSUE TITLE
documentation: new splice_polypyrimidine_tract_variant consequence

### ISSUE THREAD

**Issue by ntm** [Ensembl/ensembl-vep#1128]
Hi,
VEP produces a new Consequence: "splice_polypyrimidine_tract_variant" (LOW impact AFAICT). This consequence is currently missing from the (very useful) "Calculated consequences" documentation page:
https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html
Updating this webpage with the new consequence would be nice.

**Comment by dglemos** [comment]
Hi @ntm,
Thank you for pointing it out. We will update the documentation for release 107.

Best wishes,
Diana
