### ISSUE TITLE
Understanding and parsing multisample VEP output in vcf format

### ISSUE THREAD

**Issue by dana-obk** [Ensembl/ensembl-vep#1129]
Hello,

I've annotated multisample (200/300) vcf file with VEP, and got an output in vcf format, e.i. like below. The format is very complicated to understand, like **why do I have several annotations for the same variant (starts with` A|` ?)** etc.
I was wondering it there a way to get a human readable format easy to analyse? I do I have to write a script? I already tried `vep-annotation-reporter`, but this is not exactly useful fto understandthe annotation in multisample vcf.

`chr1	3338	.	G	A	5133.45	PASS	AC=2;AF=0.014;AN=142;set=variant2;CSQ=A|missense_variant|MODERATE|MT-ND1|ENSG00000198888|Transcript|ENST00000361390|protein_coding|1/1||ENST00000361390.2:c.32T>A|ENSP00000354687.2:p.Gly11Glu|32/956|32/956|11/318|G/E|gGa/gAa|||1||SNV|HGNC|7455|YES||||||ENSP00000354687|NU1M_HUMAN|Q85KV6_HUMAN&Q8WCX9_HUMAN&Q5Q757_HUMAN&Q14WI3_HUMAN&G3EBI1_HUMAN&D2Y6X8_HUMAN&D2Y6X6_HUMAN&A6ZHG8_HUMAN|UPI0000000AA1||1|deleterious_low_confidence(0)|benign(0.239)|Transmembrane_helices:TMhelix&Cleavage_site_(Signalp):SignalP-TM&HAMAP:MF_01350&PANTHER:PTHR11432:SF3&PANTHER:PTHR11432&Pfam:PF00146||||||||||||||||||||||||||||||,A|upstream_gene_variant|MODIFIER|MT-ND2|ENSG00000198763|Transcript|ENST00000361453|protein_coding|||||||||||1132|1||SNV|HGNC|7456|YES||||||ENSP00000355046|NU2M_HUMAN|Q7GXY9_HUMAN&Q5Q3P5_HUMAN&Q14X33_HUMAN&Q14WT3_HUMAN&A6ZH82_HUMAN&A6ZGN8_HUMAN&A6ZGG3_HUMAN|UPI0000000AA2||1|||||||||||||||||||||||||||||||||,A|upstream_gene_variant|MODIFIER|MT-CO1|ENSG00000198804|Transcript|ENST00000361624|protein_coding|||||||||||2566|1||SNV|HGNC|7419|YES||||||ENSP00000354499|COX1_HUMAN|Q957U9_HUMAN&Q7GXY8_HUMAN&M9Z2G2_HUMAN&Q8HBX8_HUMAN&Q5Q1W2_HUMAN&Q4R1L4_HUMAN&Q14XD3_HUMAN&Q14X83_HUMAN&F8U4W0_HUMAN&D3WYY6_HUMAN&D3WYY5_HUMAN&D3WYY4_HUMAN&D2Y6W4_HUMAN&C8YAE4_HUMAN&C3UPN2_HUMAN&B7TCT8_HUMAN&B2Y9D8_HUMAN&A5YMT3_HUMAN&A1XP63_HUMAN&A0S1I7_HUMAN|UPI0000000AA3||1|||||||||||||||||||||||||||||||||,A|upstream_gene_variant|MODIFIER|MT-CO2|ENSG00000198712|Transcript|ENST00000361739|protein_coding|||||||||||4248|1||SNV|HGNC|7421|YES||||||ENSP00000354876|COX2_HUMAN|Q7GXZ8_HUMAN&Q4R1L5_HUMAN&Q4R1L3_HUMAN&Q14XT3_HUMAN&K7WVJ5_HUMAN&H9E7W2_HUMAN&H9E7T7_HUMAN&H9E7P8_HUMAN&H9E7F7_HUMAN&E2DTL8_HUMAN&D3WYY9_HUMAN&D2Y6Y2_HUMAN&D2Y6Y1_HUMAN&B2YKU2_HUMAN|UPI0000000AA4||1|||||||||||||||||||||||||||||||||,A|downstream_gene_variant|MODIFIER|MT-TL1|ENSG00000209082|Transcript|ENST00000386347|Mt_tRNA|||||||||||34|1||SNV|HGNC|7490|YES|||||||||||1|||||||||||||||||||||||||||||||||,A|downstream_gene_variant|MODIFIER|MT-TF|ENSG00000210049|Transcript|ENST00000387314|Mt_tRNA|||||||||||2691|1||SNV|HGNC|7481|YES|||||||||||1|||||||||||||||||||||||||||||||||,A|downstream_gene_variant|MODIFIER|MT-TV|ENSG00000210077|Transcript|ENST00000387342|Mt_tRNA|||||||||||1668|1||SNV|HGNC|7500|YES|||||||||||1|||||||||||||||||||||||||||||||||,A|downstream_gene_variant|MODIFIER|MT-RNR2|ENSG00000210082|Transcript|ENST00000387347|Mt_rRNA|||||||||||109|1||SNV|HGNC|7471|YES|||||||||||1|||||||||||||||||||||||||||||||||,A|upstream_gene_variant|MODIFIER|MT-TI|ENSG00000210100|Transcript|ENST00000387365|Mt_tRNA|||||||||||925|1||SNV|HGNC|7488|YES|||||||||||1|||||||||||||||||||||||||||||||||,A|downstream_gene_variant|MODIFIER|MT-TQ|ENSG00000210107|Transcript|ENST00000387372|Mt_tRNA|||||||||||991|-1||SNV|HGNC|7495|YES|||||||||||1|||||||||||||||||||||||||||||||||,A|upstream_gene_variant|MODIFIER|MT-TM|ENSG00000210112|Transcript|ENST00000387377|Mt_tRNA|||||||||||1064|1||SNV|HGNC|7492|YES||||||||||||||||||||||||||||||||||||||||||||,A|upstream_gene_variant|MODIFIER|MT-TW|ENSG00000210117|Transcript|ENST00000387382|Mt_tRNA|||||||||||2174|1||SNV|HGNC|7501|YES|||||||||||1|||||||||||||||||||||||||||||||||,A|downstream_gene_variant|MODIFIER|MT-TA|ENSG00000210127|Transcript|ENST00000387392|Mt_tRNA|||||||||||2249|-1||SNV|HGNC|7475|YES||||||||||||||||||||||||||||||||||||||||||||,A|downstream_gene_variant|MODIFIER|MT-TN|ENSG00000210135|Transcript|ENST00000387400|Mt_tRNA|||||||||||2319|-1||SNV|HGNC|7493|YES|||||||||||1|||||||||||||||||||||||||||||||||,A|downstream_gene_variant|MODIFIER|MT-TC|ENSG00000210140|Transcript|ENST00000387405|Mt_tRNA|||||||||||2423|-1||SNV|HGNC|7477|YES||||||||||||||||||||||||||||||||||||||||||||,A|downstream_gene_variant|MODIFIER|MT-TY|ENSG00000210144|Transcript|ENST00000387409|Mt_tRNA|||||||||||2488|-1||SNV|HGNC|7502|YES||||||||||||||||||||||||||||||||||||||||||||,A|downstream_gene_variant|MODIFIER|MT-TS1|ENSG00000210151|Transcript|ENST00000387416|Mt_tRNA|||||||||||4108|-1||SNV|HGNC|7497|YES|||||||||||1|||||||||||||||||||||||||||||||||,A|upstream_gene_variant|MODIFIER|MT-TD|ENSG00000210154|Transcript|ENST00000387419|Mt_tRNA|||||||||||4180|1||SNV|HGNC|7478|YES||||||||||||||||||||||||||||||||||||||||||||,A|upstream_gene_variant|MODIFIER|MT-TK|ENSG00000210156|Transcript|ENST00000387421|Mt_tRNA|||||||||||4957|1||SNV|HGNC|7489|YES|||||||||||1|||||||||||||||||||||||||||||||||,A|downstream_gene_variant|MODIFIER|MT-RNR1|ENSG00000211459|Transcript|ENST00000389680|Mt_rRNA|||||||||||1737|1||SNV|HGNC|7470|YES|||||||||||1|||||||||||||||||||||||||||||||||	GT:AD:DP:GQ:PL	0/0:180,0:180:99:0,120,1800	0/0:83,0:83:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:52,0:52:99:0,107,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:50,0:50:99:0,116,1550	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:67,0:67:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:96,0:96:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:139,0:139:99:0,112,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:122,0:122:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:46,0:46:99:0,104,1187	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:39,0:39:99:0,101,1144	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:125,0:125:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:74,0:74:99:0,120,1800	0/0:165,0:165:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:132,0:132:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:121,0:121:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:275,0:275:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:196,0:196:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:233,0:233:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:217,0:217:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:140,0:140:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:41,0:41:99:0,103,1190	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:39,0:39:99:0,100,1178	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:51,0:51:99:0,102,1507	0/0:29,0:29:72:0,72,1080	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:153,0:153:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:92,0:92:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:73,0:73:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:83,0:83:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:73,0:73:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:59,0:59:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:50,0:50:99:0,116,1601	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:100,0:100:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:39,0:39:99:0,101,1112	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:74,0:74:99:0,120,1800	0/0:54,0:54:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:68,0:68:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:30,0:30:81:0,81,1215	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	1/1:1,157:158:99:5196,436,0	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:56,0:56:99:0,115,1569	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:38,0:38:99:0,99,1139	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:52,0:52:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:59,0:59:99:0,120,1800	0/0:79,0:79:99:0,120,1800	0/0:28,0:28:81:0,81,732	0/0:62,0:62:99:0,120,1800	0/0:46,0:46:99:0,120,1118	0/0:84,0:84:99:0,120,1800	0/0:51,0:51:99:0,120,1800	0/0:73,0:73:99:0,120,1800	0/0:77,0:77:99:0,120,1800	0/0:46,0:46:99:0,120,1800	0/0:54,0:54:99:0,120,1800	0/0:60,0:60:99:0,120,1800	0/0:52,0:52:99:0,120,1800	0/0:67,0:67:99:0,120,1800	0/0:66,0:66:99:0,120,1800	0/0:51,0:51:99:0,120,1800	0/0:38,0:38:99:0,106,918	0/0:78,0:78:99:0,120,1800	0/0:104,0:104:99:0,120,1800	0/0:74,0:74:99:0,120,1800	0/0:50,0:50:99:0,120,1800	0/0:63,0:63:99:0,120,1800	0/0:82,0:82:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:157,0:157:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:64,0:64:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:63,0:63:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:.:.:.:.	0/0:748,0:748:99:0,120,1800	0/0:727,0:727:99:0,120,1800	0/0:696,0:696:99:0,120,1800	0/0:.:.:.:.	0/0:.:.:.:.	0/0:774,0:774:99:0,120,1800	0/0:.:.:.:.`

**Comment by dglemos** [comment]
Hi @dana-obk,
VCF is one of the supported output formats, if you prefer a format that is simple to read maybe tab-delimited output would be a better choice. You can read more about the different types of output formats here: http://www.ensembl.org/info/docs/tools/vep/vep_formats.html#output 
Here you can read more about the VCF format: https://samtools.github.io/hts-specs/VCFv4.2.pdf

>  why do I have several annotations for the same variant

VEP reports multiple consequence annotations for the same variant. The consequence is calculated per overlapping transcript and if a variant overlaps several transcripts you can end up with different consequence annotations for each variant transcript pair.

**Comment by dana-obk** [comment]
thanks for your answer @dglemos , however according to documentation, a multisample vcf annotation is supported only by vcf format, and not tab, so I cannot use a tab delimited format as far as I understood. I find out how to filter overlapping transcripts with `--distance 0` and` --pick` options, then I guess a custom script is needed to parse. Could you pelase confirm?

**Comment by dglemos** [comment]
That is correct, the sample annotations are only supported in VCF format.
The `--pick` option will pick one line or block of consequence data per variant according to the criteria described here: https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick 
You can customise the order the criteria are applied with `--pick_order` described here: https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_pick_order 

The option `--distance` modifies the distance up and/or downstream between a variant and a transcript for which VEP will assign the upstream_gene_variant or downstream_gene_variant consequences. This option will not help to filter the transcripts.

**Comment by dglemos** [comment]
I'm going to close the issue but feel free to re-open it in case you have more questions.

Best wishes,
Diana
