### ISSUE TITLE
MSG: ERROR: Cannot use format vcf without Bio::DB::HTS::Tabix module installed

### ISSUE THREAD

**Issue by Filago4** [Ensembl/ensembl-vep#1130]
Hello,
I installed VEP V. 105 without any error and can use it without any problems.
However, when I include a custom annotation of gnomad the following error occurs:

`MSG: ERROR: Cannot use format vcf without Bio::DB::HTS::Tabix module installed`

The tabix.pm file is at its right location (ensembl-vep/Bio/DB/HTS/)

```
perldoc -l Bio::DB::HTS::Tabix
/home/user/ensembl-vep/Bio/DB/HTS/Tabix.pm
```

Many thanks for your help in advance!

**Comment by dglemos** [comment]
Hi @Filago4,
Could you please check that your ensembl-vep folder is included within your PERL5LIB. If not, you can add it with:
`export PERL5LIB=${PERL5LIB}:/home/user/ensembl-vep/`

**Comment by LightSun** [comment]
I had met the same issue.  and 'export PERL5LIB' have nothing effect

**Comment by olaaustine** [comment]
Hi Lightsun, 
Apologies for the late response. 
Can you check if you have `Bio::DB::HTS::Tabix` installed? 
Thank you, 
Ola

**Comment by LightSun** [comment]
@olaaustine I  installed vep by conda.  and export the bin dir to path. As you say, Is tabix to be installed separately?

**Comment by olaaustine** [comment]
Hi Lightsun, 
Thanks for your response.
This issue occurs mostly when there is a multiple version of Bio::DB::HTS installed usually one is installed as part of the VEP installation process.
Can you check if Bio::DB::HTS is already installed on your machine?
I believe this might be causing a conflict if the machine being used already has BIO::DB::HTS installed.
Thanks,
Ola

**Comment by LightSun** [comment]
@olaaustine  sorry now I can't . I had use a script to install vep successed which is like your docker file some days ago. Now it works.

**Comment by olaaustine** [comment]
Hi @LightSun,
Just to confirm, is the issue now resolved? 
If no, can you try to check all the versions of vep you have installed? 
Thank you 
Ola.

**Comment by LightSun** [comment]
@olaaustine I resolve it by reinstall vep with flow the docker file of this project.

**Comment by olaaustine** [comment]
Hi @LightSun,
Thank you for letting us know. 
I will close this ticket now, please feel free to open another ticket if you have any issue. 
Thank you, 
Ola.
