### ISSUE TITLE
Can't have both GRCh38 and 37 at the same time? How do I work around this?

### ISSUE THREAD

**Issue by Jolleboll** [Ensembl/ensembl-vep#1131]
## Describe the issue

Hello. I'm installing VEP and am excited to use it, I'll be working with human data some of which is older so I need both h37 and h38 "installed". h38 installs fine but then after downloading h37 the INSTALL.pl script throws an error.

### System
- VEP version: 105
- VEP Cache version: 105
- Perl version: 5.26
- OS: OpenSuse
- tabix installed Yes

### Full VEP command line
```
perl INSTALL.pl
```

### Full error message
```
ERROR: For technical reasons this installer is unable to install GRCh37 caches alongside others; please install them separately
```

What should I do? Thanks in advance!

**Comment by nuno-agostinho** [comment]
Hello @Jolleboll!

When you use `INSTALL.pl` to install both GRCh38 and GRCh37 caches, only GRCh38 is installed. However, you can follow [our instructions to manually install GRCh37](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#manual_cache) to VEP cache as well.

Having both caches allows you to run VEP with either GRCh38 or GRCh37 by setting the [`--assembly`](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_assembly) flag, for instance:

```
./vep --cache --assembly GRCh37 -i input.txt -o output.txt
```

Let me know if you have any further issues.

Cheers,
Nuno
