### ISSUE TITLE
Please consider supporting byte range requests from your HTTP server

### ISSUE THREAD

**Issue by anderspitman** [Ensembl/ensembl-vep#1138]
When downloading the VEP cache files as described here:

https://uswest.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache

If the download fails there's no way to resume it (ie with `curl -C`) because the server does not support [HTTP range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests). This is a huge problem, especially since the files are relatively large and the download speeds are slow.

It would be awesome if you could enable range requests on nginx, which is the reported server and already supports this functionality.

This would be helpful for you as well as it would reduce traffic from people not needing to restart failed requests from the beginning of the file.

**Comment by anderspitman** [comment]
For context I've had 3 download attempts fail in the last 30 minutes. I'm currently unable to download the cache for release 105. Are there mirrors anywhere by chance?

**Comment by anderspitman** [comment]
Using FTP is much faster. Not sure what's going on with your nginx webserver. Here's an example command:

`curl -O -C - ftp://ftp.ensembl.org/pub/release-105/variation/indexed_vep_cache/homo_sapiens_merged_vep_105_GRCh37.tar.gz`

It would still be great if you're able to enable range requests.

**Comment by nakib103** [comment]
Hello @anderspitman 

Thanks for your query. Unfortunately I am unable to re-produce your issue.

The server do seems to support range request showing `Accept-Ranges` as `bytes` - 
```
>curl -I http://ftp.ensembl.org/pub/release-105/variation/indexed_vep_cache/homo_sapiens_merged_vep_105_GRCh37.tar.gz
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 16166665466
Content-Type: application/x-gzip
Date: Fri, 25 Mar 2022 11:08:09 GMT
Etag: "61541c8c-3c39bbcfa"
Last-Modified: Wed, 29 Sep 2021 07:58:04 GMT
Server: nginx
```

Also, in my case curl resumes download - 
```
C:\Users\Asus\Desktop>curl -O http://ftp.ensembl.org/pub/release-105/variation/indexed_vep_cache/homo_sapiens_merged_vep_105_GRCh37.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1 15.0G    1  171M    0     0   238k      0 18:24:31  0:12:19 18:12:12  232k^C

C:\Users\Asus\Desktop>curl -O -C - http://ftp.ensembl.org/pub/release-105/variation/indexed_vep_cache/homo_sapiens_merged_vep_105_GRCh37.tar.gz
** Resuming transfer from byte position 180361808
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 14.8G    0 2512k    0     0   157k      0 27:36:48  0:00:16 27:36:32  146k
```

See that `Total` has reduced from 15.0G to 14.8G in second call.

What is the error you are getting when you are trying to resume download?  

Best regards,
Nakib

**Comment by nakib103** [comment]
I'm going to close the issue for now but feel free to open a new one if you have more questions.

Best regards,
Nakib
