### ISSUE TITLE
Error: Use of uninitialized value $aa_string in pattern match (m//) at .vep/Plugins/Mastermind.pm line 280

### ISSUE THREAD

**Issue by dana-obk** [Ensembl/ensembl-vep#1139]
Hello,

I am running vep version 105 with this command line:
```
perl ./vep -i prova.chr2.vcf \
    --format vcf \
    --offline \
    --assembly GRCh37 \
    -o out.chr2.vcf \
    --distance 0 \
    --vcf \
    --pick \
    --fork 12 \
    --no_stats \
    --check_existing \
    --fields Allele,Consequence,IMPACT,SYMBOL,Gene,Existing_variation,SIFT,PolyPhen,ZYG \
    --plugin Mastermind,/path/to/mastermind_cited_variants_reference-2022.01.06-grch37.vcf.gz,0,0,1
```
But it gives me the following warning. How to solve this? Also is it fine to increase fork to 25 on a server? is it analogous to cpu?

`WARNING: 45629 : Use of uninitialized value $aa_string in pattern match (m//) at .vep/Plugins/Mastermind.pm line 280.`

**Comment by dglemos** [comment]
Hi @dana-obk,
The plugin doesn't parse correctly nonsense variants - we have a plan to review how the Mastermind plugin parses the frameshifts and nonsense variants. I'll let you know when we make the changes.

**Comment by dana-obk** [comment]
Ok, thanks a lot! Please, let me know as we are interested in using this plugin.

**Comment by dglemos** [comment]
Hi @dana-obk,
The plugin has been reviewed and we have fixed the parsing of frameshifts/nonsense variants. The updates will be available in the next release which is scheduled for mid-September.
I'm going to close this issue for now but feel free to re-open it if you have more questions.

Best wishes,
Diana
