### ISSUE TITLE
Checksum for homo_sapiens_vep_105_GRCh38.tar.gz is incorrect

### ISSUE THREAD

**Issue by rastogiruchir** [Ensembl/ensembl-vep#1140]
## Describe the issue
During VEP installation, the checksum for homo_sapiens_vep_105_GRCh38.tar.gz does not match the checksum on the FTP site. I've repeated the installation process three times, and I get the same error every time.

### System
- VEP version: 105
- VEP Cache version: 105
- Perl version: v5.16.3
- OS: Scientific Linux 7.9
- tabix installed ? yes

### Full VEP command line
```
perl INSTALL.pl --AUTO cf --CACHEDIR cache --NO_HTSLIB --ASSEMBLY GRCh38 --SPECIES homo_sapiens
```

### Full error message
```
WARNING: DBD::mysql module not found. VEP can only run in offline (--offline) mode without DBD::mysql installed

http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#requirements
 - getting list of available cache files
 - downloading ftp://ftp.ensembl.org/pub/release-105/variation/indexed_vep_cache/homo_sapiens_vep_105_GRCh38.tar.gz
ERROR: checksum for cache/tmp/homo_sapiens_vep_105_GRCh38.tar.gz doesn't match checksum in CHECKSUMS file on FTP site
```

**Comment by olaaustine** [comment]
Hi rastogiruchir,
You can try installing the module DBD::mysql.
We have tried to recreate the cache file issue but we could not.
Can you try to check the checksum for the file you have.
Also you can manually install the cache by 
`curl -O http://ftp.ensembl.org/pub/release-105/variation/vep/homo_sapiens_vep_105_GRCh38.tar.gz`
The documentation can be found [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#:~:text=curl%20%2DO%20http%3A//ftp.ensembl.org/pub/release%2D105/variation/vep/homo_sapiens_vep_105_GRCh38.tar.gz%0Atar%20xzf%20homo_sapiens_vep_105_GRCh38.tar.gz).

Thank you, 
Ola

**Comment by rastogiruchir** [comment]
I believe the issue is that the INSTALL.pl script assumes that the user has the UNIX ``sum`` utility installed on their machine. ``sum`` is a legacy utility, so I'm not sure why this is assumed (might be worth using a more modern checksum utility that is built into Perl?). For now, I've found that commenting out lines 1252-1254 is sufficient to avoid the issue.

**Comment by olaaustine** [comment]
Hi, 
Thank you very much. 
We would take a look at this as we believe this might be a backward compatibility issue. 
Thanks,
Ola
