### ISSUE TITLE
VEP Cache Licensing Inquiry

### ISSUE THREAD

**Issue by fahadkh** [Ensembl/ensembl-vep#1143]
## Describe the issue
Not necessarily a technical issue, but wanted to clarify licensing requirements around the inclusion of COSMIC and HGMD data within the cache files. Please let me know if there's a better forum for these types of questions.

## Additional information
Looking at the [following documentation about the cache files](https://useast.ensembl.org/info/docs/tools/vep/script/vep_other.html#:~:text=For%20some%20data,only%2C%20use%20%2D%2Dno_check_alleles.), it appears that ensembl-vep does **not** redistribute COSMIC and HGMD data within the cache files available for public download:

> For some data sources (COSMIC, HGMD), Ensembl is not licensed to redistribute allele-specific data, so VEP will report the existence of co-located variants with unknown alleles without carrying out allele matching. To disable this behaviour and exclude these variants, use the [--exclude_null_alleles](https://m.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_exclude_null_alleles) flag.

> To disable allele matching completely and compare variant locations only, use [--no_check_alleles](https://m.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_no_check_alleles).

I just wanted to confirm that this is actually the case and the cache files are useable without acquiring a license from COSMIC.

### System
- VEP version: 87 and 102
- VEP Cache version: 87 and 102
- Perl version: 5.26
- OS: Debian (docker)
- tabix installed ? Yes

### Full VEP command line
```
./vep
```

**Comment by olaaustine** [comment]
Hi fahadkh, 
Thank you for your enquiry.
Yes, the cache files are useable without acquiring a license.
Do let us know if you have any other questions. 
Thank you,
Ola.

**Comment by olaaustine** [comment]
Hi @fahadkh,
I will be closing this issue now. 
Please feel free to open another ticket or reopen if you have any other issue.
Thank you, 
Ola.

**Comment by fahadkh** [comment]
Thank you!

**Comment by migrau** [comment]
A question related: Can the VEP cache files be redistributed?
