### ISSUE TITLE
perl INSTALL.pl gets stuck during cache download

### ISSUE THREAD

**Issue by paulrdelg** [Ensembl/ensembl-vep#1145]
## Describe the issue
The `perl INSTALL.pl` process gets stuck when I attempt to download cache.

### System
- VEP version: 105
- VEP Cache version: 105 ?
- Perl version: 5.30
- OS: Windows 11 with Ubuntu 20.04 through WSL, Ubuntu 20.04 on a laptop, Ubuntu 20.04 virtual machine
- tabix installed ?

### Full VEP command line
* `perl INSTALL.pl` (the first instruction in README for installation)
* `y` when prompted to overwrite `./Bio`
* `y` when prompted to install any cache files
* `466` when prompted with list of cache (466 being `homo_sapiens_vep_105_GRCH38.tar.gz`
* `./vep -i input.vcf -o out.txt -offline` (the second instruction in the README)

### Full error message
No error message. It simply is always stuck at:
`- downloading ftp://ftp.ensembl.org/pub/release-105/variation/indexed_vep_cache/homo_sapiens_vep_105_GRCh38.tar.gz`

If I do not attempt to download the cache files and simply run the second instruction, the error message would be: 
`MSG:  ERROR: Cache directory /home/<me>/.vep/homo_sapiens not found`.

### Data files (if applicable)
They include:
- The input file
- The output file
- The custom file(s)
You can provide a sample of them

**Comment by diegomscoelho** [comment]
Hi @paulrdelg,

About first error message, downloading cache can take a little bit long, it's a `14Gb` compressed folder. Can you provide me what is inside your `/home/$USER/.vep/` folder? It looks like `vep` command is not finding `homo_sapiens` folder with cache files.

If you have not found cache folder inside `/home/$USER/.vep/` and have not downloaded `homo_sapiens_vep_105_GRCh38.tar.gz`, you can try:

1) Using `wget ftp://ftp.ensembl.org/pub/release-105/variation/indexed_vep_cache/homo_sapiens_vep_105_GRCh38.tar.gz`
2) Decompress this `tar.gz` inside `/home/$USER/.vep/`, command `tar -xvzf homo_sapiens_vep_105_GRCh38.tar.gz`

If you have already downloaded cache files and decompressed in another path, you can use:

1) Flag `--dir_cache` to have `vep` using your personal folder, i.e
`./vep -i input.vcf -o out.txt -ofline -dir_cache <path-to-homo_sapiens-folder>/`

If you have any other question, please just let me know here.

Regards, @diegomscoelho

**Comment by diegomscoelho** [comment]
Hi @paulrdelg,

I am going to close this issue now.

If you have any further questions, please feel free to reopen it or create a new issue.

Regards,
@diegomscoelho
