### ISSUE TITLE
filter_vep with match contents of a file

### ISSUE THREAD

**Issue by Addy81** [Ensembl/ensembl-vep#1146]
Hello, 

I was wondering if theres a way to do something similar to this from your docs:

filter using a file of MotifFeatures
--filter "Feature in /data/files/motifs_list.txt"

But instead of match exactly it does a regex match with the contents of the file? Looking into filtering for a chosen transcript without spcifying a version and without writing a really big string to use the Feature match filter.

Many thanks,

Adriana

**Comment by diegomscoelho** [comment]
Hi @Addy81,

Unfortunately `filter_vep` does not support `matches` while using `Feature in /data/to/motif_list.txt`.
But you can try a bash script like this, i.e

```
## Gets header
grep "^#" output.txt > filtered_output.txt

## Regex matches all lines from a file
cat pattern.txt | while read line; do filter_vep -i output.txt --force_overwrite -filter "Feature matches ${line}" | grep -v "^#"; done >> filtered_output.txt
```

`pattern.txt` can be a file where you store all your patterns on separate lines (as in /data/files/motifs_list.txt"

Thanks for your question. If you still need some help, please, post here in this issue.

Regards, @diegomscoelho

**Comment by Addy81** [comment]
Thank you @diegomscoelho for the response.  Thought I'd check in case it was missing from the docs. I anticipate it might be useful feature in the future for other people as well.
