### ISSUE TITLE
plugin MaxEntScan, GeneSplicer,SpliceAI do not work

### ISSUE THREAD

**Issue by zyh4482** [Ensembl/ensembl-vep#1149]
## Describe the issue
plugin MaxEntScan, GeneSplicer,SpliceAI do not work

## Additional information
All the plugins have been installed in ~/.vep/Plugins

### System
- VEP version: [104] 
- VEP Cache version: [104]
- Perl version: [5.22]
- OS: [Ubuntu]

### Full VEP command line
#MaxEntScan#
```
 vep -i sort.vcf.gz -o ../splice_prediction/out.txt --cache --plugin MaxEntScan,/home/tomas/.vep/Plugins
```
#GeneSplicer#
```
vep -i sort.vcf.gz -o ../splice_prediction/out.txt --cache --plugin GeneSplicer,/home/tomas/GeneSplicer/sources/genesplicer,/home/tomas/GeneSplicer/human,context=50
```
#SpliceAI#
```
vep -i sort.vcf.gz -o ../splice_prediction/out.txt --cache --plugin SpliceAI,~/.vep/Plugins
```

### Full error message
#MaxEntScan#
> WARNING: Failed to instantiate plugin MaxEntScan: Can't open /home/tomas/.vep/Plugins/me2x5!

#GeneSplicer#
For this plugin, a warning log is provided below.
[out.txt_warnings.txt](https://github.com/Ensembl/ensembl-vep/files/8438758/out.txt_warnings.txt)

#SpliceAI#
WARNING: Failed to instantiate plugin SpliceAI: ERROR: SpliceAI files not provided or not found!

**Comment by diegomscoelho** [comment]
Hi @zyh4482,

I have posted an answer on your last VEP_Plugins issue https://github.com/Ensembl/VEP_plugins/issues/486.

You need to download data from each Plugin and follow a few steps in some cases, i.e,

`SpliceAI`
https://github.com/diegomscoelho/VEP_plugins/blob/b062a0a1ecec2f0f6f25c236153cf08cddccf1c7/SpliceAI.pm#L84-L103

`GeneSplicer`
https://github.com/diegomscoelho/VEP_plugins/blob/b062a0a1ecec2f0f6f25c236153cf08cddccf1c7/GeneSplicer.pm#L35-L84

`MaxEntScan` -> follow my answer in your original VEP_Plugin issue.

Hope this helped you, any other question about VEP_Plugins you can comment in your first issue.

Regards, @diegomscoelho

**Comment by zyh4482** [comment]
@diegomscoelho Thank you so much! The documents are very useful. MaxEntScan could work normally. 
I'm testing SpliceAI now with following command:

`vep -i test.vcf.gz -o ../splice_prediction/spliceai.txt --cache --plugin SpliceAI,snv=/home/tomas/SpliceAI/annotation/spliceai_scores.raw.snv.hg38.vcf.gz,indel=/home/tomas/SpliceAI/annotation/spliceai_scores.raw.indel.hg38.vcf.gz`

But it comes with another error. 

```
-------------------- EXCEPTION --------------------
MSG: ERROR: Could not write to stats file ../splice_prediction/spliceai.txt_summary.html

STACK Bio::EnsEMBL::VEP::BaseRunner::get_stats_file_handle /home/tomas/anaconda3/share/ensembl-vep-104.3-0/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:275
STACK Bio::EnsEMBL::VEP::Runner::init /home/tomas/anaconda3/share/ensembl-vep-104.3-0/modules/Bio/EnsEMBL/VEP/Runner.pm:147
STACK Bio::EnsEMBL::VEP::Runner::run /home/tomas/anaconda3/share/ensembl-vep-104.3-0/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel /home/tomas/anaconda3/bin/vep:232
Date (localtime)    = Fri Apr  8 10:49:02 2022
Ensembl API version = 104
---------------------------------------------------
```

Do you have any idea how to deal with it?

**Comment by diegomscoelho** [comment]
Hi @zyh4482,

Can you try to include `--force_overwrite` to your command? - i.e,

```sh
vep -i test.vcf.gz -o ../splice_prediction/spliceai.txt --cache --force_overwrite --plugin SpliceAI,snv=/home/tomas/SpliceAI/annotation/spliceai_scores.raw.snv.hg38.vcf.gz,indel=/home/tomas/SpliceAI/annotation/spliceai_scores.raw.indel.hg38.vcf.gz
```

I think you are getting this message because you already have a file `../splice_prediction/spliceai.txt_summary.html` and vep will not overwrite by default.

Regards, @diegomscoelho

**Comment by diegomscoelho** [comment]
Hi @zyh4482,

I was only able to reproduce your error when I tried to write a file in a directory that I do not have permission to write or create a file. 

Can you put your output: `-o ../splice_prediction/spliceai.txt` in a different directory? - To ensure you have access to this, you can try `touch ../splice_prediction/file.txt`. If this solution does not work, could you please post your full command for both cases?

Best, @diegomscoelho

**Comment by zyh4482** [comment]
@diegomscoelho Thank you very much. I corrected the directory and the error message didn't show again.
