### ISSUE TITLE
Missing GRCh37 106 Indexed Cache files

### ISSUE THREAD

**Issue by davmlaw** [Ensembl/ensembl-vep#1152]
The [web site](https://asia.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache) lists the latest version of Cache (106) as being supported by both GRCh37 and GRCh38

However the [FTP site](http://ftp.ensembl.org/pub/release-106/variation/indexed_vep_cache/) contains only GRCh38 cache files:

```
homo_sapiens_merged_vep_106_GRCh38.tar.gz
homo_sapiens_refseq_vep_106_GRCh38.tar.gz
homo_sapiens_vep_106_GRCh38.tar.gz  
```

The equivalent GRCh37 files are missing

**Comment by dglemos** [comment]
Hi @davmlaw,
You can find the GRCh37 cache files here: http://ftp.ensembl.org/pub/grch37/release-106/variation/vep/ 

Best wishes,
Diana

**Comment by Stikus** [comment]
Hello, According to previous releases, not only GRCh37 files were present in release folder:
![image](https://user-images.githubusercontent.com/41360525/163538340-e4e0cb65-abfc-4bf3-858c-4bc93f848e17.png)
But release folder for GRCh37 should have `indexed_vep_cache` subfolder - now it is missing:

- Release 105:
![image](https://user-images.githubusercontent.com/41360525/163538716-a83eef70-dc14-49a2-9493-6759e4d75f82.png)
![image](https://user-images.githubusercontent.com/41360525/163538772-2b108d65-4afe-4cd3-9fd2-8c4738ac738a.png)

- Release 106:
![image](https://user-images.githubusercontent.com/41360525/163538839-b09eca7e-89e6-4146-b196-15f91929eeed.png)


Where to find indexed VEP 106 cache for GRCh37?

**Comment by davmlaw** [comment]
Stikus is right, to clarify it's the indexed cache files that are missing - I updated the issue title to reflect that

**Comment by serge2016** [comment]
Hello! I hope this would be fixed very soon!

**Comment by dglemos** [comment]
You are correct, the indexed cache files are missing. We are working on a fix.

**Comment by Stikus** [comment]
Hello again @dglemos, can you give us any ETA for fix? We cannot use latest VEP due to this.

**Comment by dglemos** [comment]
Hi @Stikus,
The cache files are available now. Let me know if you have any problem downloading them.

Best wishes,
Diana

**Comment by Stikus** [comment]
Thanks for fast answer.
I've found files here:
![image](https://user-images.githubusercontent.com/41360525/164440133-d9f33327-070a-4409-a6be-0bea11a1c54f.png)

But they are still missing here:
![image](https://user-images.githubusercontent.com/41360525/164440506-7acc5512-c5e4-466a-a113-4b4c2b52cd05.png)
![image](https://user-images.githubusercontent.com/41360525/164441245-a891db35-2328-4ec6-9e57-2e49b7d2f24f.png)

And VEP is looking for them in this place:
https://github.com/Ensembl/ensembl-vep/blob/release/106/INSTALL.pl#L217
```
$CACHE_URL_INDEXED  ||= "ftp://ftp.ensembl.org/pub/release-$DATA_VERSION/variation/indexed_vep_cache";
```

Error persists:
![image](https://user-images.githubusercontent.com/41360525/164441347-8ca67fa7-6d02-4982-8037-9251c3582598.png)


Looks like you should add links for these files to release folder (or files itself if you prefer this).

**Comment by dglemos** [comment]
Could you send the command you're running?

The grch37 cache files are kept in a [separate folder](http://ftp.ensembl.org/pub/grch37/release-106/variation/indexed_vep_cache/). The directory http://ftp.ensembl.org/pub/release-106/variation/indexed_vep_cache/ only contains human assembly GRCh38 which is the one being used by the installer. I would recommend you download the GRCh37 cache files manually after the installation.

**Comment by dglemos** [comment]
We have added the missing homo_sapiens grch37 cache files to that directory. 
Could you please rerun the installation?

**Comment by davidhoover** [comment]
Thank you!

**Comment by Stikus** [comment]
Finally:
```
 - getting list of available cache files                                                                             
 - downloading ftp://ftp.ensembl.org/pub/release-106/variation/indexed_vep_cache/homo_sapiens_vep_106_GRCh37.tar.gz  
```
Looks like issue can be closed. Thanks.

**Comment by Stikus** [comment]
Not closed, sorry. Download failing due to CHECKSUMS missing:
```
 - getting list of available cache files                                                                                                
 - downloading ftp://ftp.ensembl.org/pub/release-106/variation/indexed_vep_cache/homo_sapiens_vep_106_GRCh37.tar.gz                     
curl failed (550), trying to fetch using LWP::Simple                                                                                    
LWP::Simple failed (404), trying to fetch using HTTP::Tiny                                                                              
Use of uninitialized value in numeric eq (==) at /usr/share/perl/5.26/HTTP/Tiny.pm line 606.                                            
Use of uninitialized value in numeric eq (==) at /usr/share/perl/5.26/HTTP/Tiny.pm line 606.                                            
ERROR: Failed last resort of using HTTP::Tiny to download ftp://ftp.ensembl.org:21/pub/release-106/variation/indexed_vep_cache/CHECKSUMS

```

Release 105:
![image](https://user-images.githubusercontent.com/41360525/164646352-795e706e-38f0-4e7f-a633-4460bc0f7ad9.png)
Release 106:
![image](https://user-images.githubusercontent.com/41360525/164646416-e80a4b64-9e02-4e80-916b-6a521ad2a264.png)

**Comment by dglemos** [comment]
We added the missing checksums. Could you please check if it's working now?

**Comment by kibalee** [comment]
Checksums of 105 and 106 version are same.

![image](https://user-images.githubusercontent.com/93112769/165004053-fb7e70b8-6454-4717-9208-3b02d00c4313.png)

**Comment by kibalee** [comment]
Checksum of 105 and 106 are same. Please check the file.

![image](https://user-images.githubusercontent.com/93112769/165004177-8420cfa2-a403-4bef-926f-df6953af6de7.png)

**Comment by Stikus** [comment]
I have some problems too:
```
 - getting list of available cache files                                                                            
 - downloading ftp://ftp.ensembl.org/pub/release-106/variation/indexed_vep_cache/homo_sapiens_vep_106_GRCh37.tar.gz 
 - unpacking homo_sapiens_vep_106_GRCh37.tar.gz                                                                     
 - converting cache, this may take some time but will allow VEP to look up variants and frequency data much faster  
 - use CTRL-C to cancel if you do not wish to convert this cache now (you may run convert_cache.pl later)           
ERROR: Version 106_GRCh37 not found                                                                                 
WARNING: Failed to run convert script                                                                               
                                                                                                                    
WARNING: Changing FTP URL for GRCh37                                                                                
 - downloading Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz                                                    
 - converting sequence data to bgzip format, this may take some time...                                             
 - conversion successful                                                                                            
 - indexing FASTA file                                                                                              
 - indexing OK                                                                                                      
                                                                                                                    
The FASTA file should be automatically detected by the VEP when using --cache or --offline.                         
If it is not, use "--fasta /ref/.vep/homo_sapiens/106_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz"     
                                                                                                                    
                                                                                                                    
All done                                                                                                            
```

```
WARNING: Chromosome 2 not found in annotation sources or synonyms on line 1     
WARNING: Chromosome 4 not found in annotation sources or synonyms on line 2     
WARNING: Chromosome 6 not found in annotation sources or synonyms on line 3     
WARNING: Chromosome 22 not found in annotation sources or synonyms on line 5    
```

And here is my cache folder:
![image](https://user-images.githubusercontent.com/41360525/165045230-a932aa10-3d43-44c3-82d4-3f560d2239a3.png)

Release 105 for the reference:
![image](https://user-images.githubusercontent.com/41360525/165045298-2ec2726d-b70d-4fbf-bad4-93248a75ff3c.png)

**Comment by Stikus** [comment]
@kibalee nonindexed files are same too:
![image](https://user-images.githubusercontent.com/41360525/165046654-0358ee7d-601d-4d16-948a-14cd16d2cdde.png)
![image](https://user-images.githubusercontent.com/41360525/165046677-13abe847-f5cb-4113-a5b2-173644ad79e3.png)

**Comment by dglemos** [comment]
Hi @kibalee, @Stikus,
There are no updates for the cache files GRCh37, the data is the same between releases 105 and 106.

**Comment by Stikus** [comment]
But this is the problem:
![image](https://user-images.githubusercontent.com/41360525/165054160-924c38f5-ffd0-4209-aeaa-96e78b8b8a01.png)

106 archive contains 105 folder and VEP cannot recognize it.

**Comment by kibalee** [comment]
> Hi @kibalee, @Stikus, There are no updates for the cache files GRCh37, the data is the same between releases 105 and 106.

Thank you.

**Comment by dglemos** [comment]
I'm really sorry for the inconvenience. We are having problems with the public FTP which is causing issues with the human GRCh37 cache files for release 106. In the meantime, you could use the 105 cache files as they are the same as release 106. 
I'll let you know when the problem is resolved.

**Comment by pdl** [comment]
Per @Stikus it does look to me like the problem is now that the 105 cache files are the same but should not be (the folder name in the cache file should reference 106), and this causes an error when running `INSTALL.pl` which is a) not fatal and b) prevents the convert script step from running.

In case it is useful, here's my output (I have substituted `[...]` for my current dir),

```
$ perl /opt/vep/src/ensembl-vep/INSTALL.pl -a cf  -s homo_sapiens -y GRCh37 && echo ok
WARNING: Unable to carry out version check for 'ensembl-vep'
 - getting list of available cache files
 - downloading ftp://ftp.ensembl.org/pub/release-106/variation/indexed_vep_cache/homo_sapiens_vep_106_GRCh37.tar.gz
 - unpacking homo_sapiens_vep_106_GRCh37.tar.gz
 - converting cache, this may take some time but will allow VEP to look up variants and frequency data much faster
 - use CTRL-C to cancel if you do not wish to convert this cache now (you may run convert_cache.pl later)
ERROR: Version 106_GRCh37 not found
WARNING: Failed to run convert script

WARNING: Changing FTP URL for GRCh37
 - downloading Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz
 - converting sequence data to bgzip format, this may take some time...
 - conversion successful
 - indexing FASTA file
 - indexing OK

The FASTA file should be automatically detected by the VEP when using --cache or --offline.
If it is not, use "--fasta [...]/.vep/homo_sapiens/106_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz"


All done
ok
```

I note that despite:

```
ERROR: Version 106_GRCh37 not found
WARNING: Failed to run convert script
```

the script exits with a successful (0) status.

Running the `INSTALL.pl` script has created **two** folders, `105_GRCh37` and `106_GRCh37` in the `./.vep/homo_sapiens/` folder. `105_GRCh37` contains `chr_synonyms.txt` and folders for the contigs. `106_GRCh37` contains `Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz{,.fai,.gzi}`. I've tried to `mv ./.vep/homo_sapiens/105_GRCh37/* ./.vep/homo_sapiens/106_GRCh37/` and remove the 105_GRCh37 folder however, the convert script then claims it has nothing to do (despite the earlier warning):

```
perl /opt/vep/src/ensembl-vep/convert_cache.pl -s homo_sapiens --version 106_GRCh37
2022-04-25 15:57:25 - Processing homo_sapiens
2022-04-25 15:57:25 - Processing version 106_GRCh37
2022-04-25 15:57:25 - No unprocessed types remaining, skipping
2022-04-25 15:57:25 - All done!
```

(it's possible it would have done this anyway, I'm not sure)

**Comment by Stikus** [comment]
Hello, any news?
Looks like now 106 GRCh37 cache files are deleted from all locations on FTP.
![image](https://user-images.githubusercontent.com/41360525/166704911-2492dbd7-3eac-4b28-8f29-0d0a815923b5.png)

**Comment by davmlaw** [comment]
@Stikus - I can see them, http://ftp.ensembl.org/pub/release-106/variation/indexed_vep_cache/

```
homo_sapiens_merged_vep_106_GRCh38.tar.gz          28-Feb-2022 12:32         21986957811
homo_sapiens_refseq_vep_106_GRCh38.tar.gz          28-Feb-2022 12:26         18716668833
homo_sapiens_vep_106_GRCh38.tar.gz                 28-Feb-2022 12:38         19350569358
```

**Comment by serge2016** [comment]
@davmlaw sorry, there are **GRCh38** files in your place:
![image](https://user-images.githubusercontent.com/18323865/166868887-1c5f289a-e352-41bb-a360-035504cfc39a.png)

And @Stikus asks about **GRCh37** here: http://ftp.ensembl.org/pub/grch37/release-106/variation/indexed_vep_cache/
![image](https://user-images.githubusercontent.com/18323865/166869038-13b37587-c7e5-48c4-a0cc-a2bae0b147ea.png)

For example, previous one exists:
![image](https://user-images.githubusercontent.com/18323865/166869104-f9a0c1d1-be4d-46e1-ba08-d3e63c0ca9d0.png)

**Comment by tahi87** [comment]
@dglemos, 

> I'll let you know when the problem is resolved.

Please let us know how long should we expect? 
tnx
