### ISSUE TITLE
Different Effects of  The Same SNP

### ISSUE THREAD

**Issue by liangdy678** [Ensembl/ensembl-vep#1155]
## Describe the issue
Sir，

We plan to predict the effect of the SNP( GRCh37: chrX-100085855-A-AG) via VEP Web interface, encountered some problems.

![图片1](https://user-images.githubusercontent.com/103975033/163904736-50128cb4-3a75-4c89-9721-cad7456babcc.png)

As we can see，insert the base [G] at any position (arrow) , results in a consistent effect .
So the SNP can be represented as [chrX-100085856-G-GG] or [chrX-100085857-G-GG] , Despite the vcf requires left alignment and normalization.
when we predict these snps above, some of the results are as follows：

![image](https://user-images.githubusercontent.com/103975033/163912229-3b327d4a-52a8-4cf9-8841-e65cbd8dd0ab.png)

Would you mind telling me  why conseqs of the first two are frameshit, I think that  None of transcripts seem to have frameshift mutations. And the HGVSc [NM_001306206.2:c.949+1dup] also suggests this variation  occurs  within an intron.

Thanks

**Comment by nakib103** [comment]
Hello @liangdy678 ,

Thanks for the query and bringing this issue to our notice. Currently VEP is not considering the most 3' representation of the variant to be after the exon/intron boundary when calculating consequence. We need to look into this issue in more depth.

Best regards,
Nakib

**Comment by nakib103** [comment]
Hello @liangdy678,

We reviewed the code and it would be complicated to properly model and give correct HGVS for variants that are in the exon-intron boundaries. We are looking to improve these cases in our future implementation of VEP.

Best regards,
Nakib
