### ISSUE TITLE
Getting Ensembl and RefSeq ID from VEP

### ISSUE THREAD

**Issue by dana-obk** [Ensembl/ensembl-vep#1158]
Dear all,

I am suing` VEP v.105` and human genome` GRCh37`. I am using the default Ensembl cache. But I would also like to find the aligned RefSeq ID. I am using using this option` --xref_refseq`, but in the documentation is says: `The RefSeq and Ensembl transcripts aligned in this way MAY NOT, AND FREQUENTLY WILL NOT, match exactly in sequence, exon structure and protein product`. How to correctly assign the RefSeq ID to the vep output keeping also Ensembl ID?

```
perl ./vep -i infile.vcf \
    --format vcf \
    --offline \
    --assembly GRCh37 \
    -o outfile.vcf \
    --distance 0 \
    --sift b \
    --polyphen b \
    --vcf \
    --pick \
    --fork 12 \
    --no_stats \
    --check_existing \
    --everything \
    --xref_refseq
```

**Comment by nakib103** [comment]
Hello @dana-obk,

Thanks for your query.

Actually `--xref_refseq` would be the best way to get both refseq and Ensembl ID both at the same time from VEP. The refseq and Ensembl transcripts would not always exactly match as the warning says. 

You can also use `--merged` flag with merged refseq and Ensembl cache but that will give you the results for each transcript in different lines of output.

Best regards,
Nakib

**Comment by nakib103** [comment]
Hello,

I am closing this issue. If you face any other issue  in future you can re-open it or create another one.

Best regards,
Nakib
