### ISSUE TITLE
vep 91 release

### ISSUE THREAD

**Issue by matthdsm** [Ensembl/ensembl-vep#116]
Hi Will,

Do you have a timeline on a github release for vep 91? I'd like to update the bioconda installer so people (me) can easily install the latest version.

Thanks!
Cheers
M

**Comment by willmclaren** [comment]
Hi, release/91 was released last Monday.

If you'd like to stay up to date with Ensembl release dates (which coincide with VEP releases), you can subscribe to the [Ensembl announce mailing list](https://www.ensembl.org/info/about/contact/mailing.html).

**Comment by matthdsm** [comment]
Hi Will, 

Thanks for the answer. I actually meant a VEP code release as listed under https://github.com/Ensembl/ensembl-vep/releases. That's the URL used by conda to retrieve to code for the recipe.

Cheers
M

**Comment by willmclaren** [comment]
Ah my mistake, you should find it there now.

**Comment by matthdsm** [comment]
Thanks!

Cheers
M
