### ISSUE TITLE
HGVS nomenclature upstream variants

### ISSUE THREAD

**Issue by andreupaytuvi** [Ensembl/ensembl-vep#1160]
Hello Ensembl-VEP authors,

I have a question regarding the HGVS nomenclature. Ensembl-VEP provides it as long as the variant is within an exon or an intron. My question is about upstream variants. Is it possible to obtain the HGVS nomenclature for upstream variants, something like the variant rs1246774295, upstream variant reported in dbSNP as NM_001368143.1:c.-537G>A.

Thanks in advance.

**Comment by nakib103** [comment]
Hello @andreupaytuvi ,

At the moment HGVS is not reported for upstream variants. I have added this as feature request to our backlog - we will look into it for possible implementation. 

Best regards,
Nakib

**Comment by andreupaytuvi** [comment]
Good afternoon,

Is it in the backlog yet? Do you have plans to implementing it?

Thank you in advance,

**Comment by nakib103** [comment]
Hello @andreupaytuvi,

We are not prioritising to add any new features to the current implementation of HGVS. Instead, we are looking to improve these cases in our future implementation of VEP.

Best regards,
Nakib
