### ISSUE TITLE
Error: no compiler detected to compile 'lib/Bio/DB/HTS.c'.  

### ISSUE THREAD

**Issue by hfl112** [Ensembl/ensembl-vep#1175]
## Describe the issue
I am actually following https://useast.ensembl.org/info/docs/api/api_installation.html to install VEP, 
but encountered an error when trying to install BIO-DB-HTS

### System
- Perl version: 5.26.2
- OS: ubuntu
- tabix installed: yes

### Full error message
```
$ perl Build.PL
WARNING: the following files are missing in your kit:
        DISCLAIMER
Please inform the author.

/Tools/miniconda3/bin/x86_64-conda-linux-gnu-ld: unrecognized option '-Wl,-O2'
/Tools/miniconda3/bin/x86_64-conda-linux-gnu-ld: use the --help option for usage information
Warning: ExtUtils::CBuilder not installed or no compiler detected
Proceeding with configuration, but compilation may fail during Build

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '3.01'

$ ./Build
Building Bio-DB-HTS
Error: no compiler detected to compile 'lib/Bio/DB/HTS.c'.  Aborting
```

## Additional information
1. $ which gcc
~/Tools/miniconda3/bin/gcc

2. perviously I installed VEP88 through conda, it works. But if I want to use custom databases like COSMIC, it went wrong:`MSG: ERROR: Cannot use format vcf without Bio::DB::HTS::Tabix module installed`

**Comment by likhitha-surapaneni** [comment]
Hi @hfl112,

Thank you for your query!

From the details provided, it seems like a problem related to C compiler not being available to the setup. VEP requires gcc, g++ and make to install correctly. Could you please check if g++ and make are available as well?

The error message `MSG: ERROR: Cannot use format vcf without Bio::DB::HTS::Tabix module installed` generally may  occur when either ensembl-vep folder is not included within your PERL5LIB or when there are multiple installations of `Bio::DB::HTS` on your machine. Could you please let us know if any of these is true?

If there's anything else we can do to help, please don't hesitate to ask.

Thanks,
Likhitha

**Comment by hfl112** [comment]
I think I have somehow solved this problem by update my conda and then updated my old perl lib using App::migrate
