### ISSUE TITLE
Argument "ensembl ID" isn't numeric in numeric BaseGXF.pm

### ISSUE THREAD

**Issue by GACGAMA** [Ensembl/ensembl-vep#1176]
## Describe the issue
I'm trying to run VEP on VCF anottated from RNA-seq experiments with GATK program and Mutect2.
Running VEP online with my VCF runs fine without errors.

### System
Versions:
  ensembl              : 106
  ensembl-funcgen      : 106
  ensembl-io           : 106
  ensembl-variation    : 106
  ensembl-vep          : 106.1

- OS: Ubuntu 22.04 LTS
- tabix installed: Yes

### Full VEP command line
When I run:

`./vep --verbose --cache --refseq --input_file /home/Desktop/VCF\ gabriel/1.vcf --fasta /home/Desktop/references/Homo_sapiens.GRCh38.dna.primary_assembly.fa.bgz --gtf /home/Desktop/references/gtf/Homo_sapiens.GRCh38.103.chr_patch_hapl_scaff.bed.gtf.gz --vcf --variant_class --sift b --polyphen b --gene_phenotype --regulatory --numbers --hgvs --transcript_version --symbol --biotype --clin_sig_allele 0 --max_af --af_gnomad --filter_common --freq_pop 1KG_ALL --freq_pop gnomAD --output_file /home/Desktop/vcf_vep/1.vep.vcf	
`
I get:

Argument "ENSG00000253971" isn't numeric in numeric le (<=) at /home/programs/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm line 240, <__ANONIO__> line 4751

Which goes continuously until the program finishes.

### Data files (if applicable)
Fasta file and GTF from ENSEMBL 103 (the version I used to align the samples)

To generate GTF file and index it:

```
gunzip -c /home/Desktop/references/gtf/Homo_sapiens.GRCh38.103.chr_patch_hapl_scaff.gtf.gz | gtf2bed - | bgzip -c > /home/Desktop/references/gtf/Homo_sapiens.GRCh38.103.chr_patch_hapl_scaff.bed.gtf.gz

tabix -p bed /home/Desktop/references/gtf/Homo_sapiens.GRCh38.103.chr_patch_hapl_scaff.bed.gtf.gz

```
And to convert ENSEMBL downloaded reference to bgzip:

`zcat /home/Desktop/references/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz | bgzip -c > /home/Desktop/references/Homo_sapiens.GRCh38.dna.primary_assembly.fa.bgz`

Output file exists, and the HTML reports shows:

```
<h3 id="run_stats" style="color: rgb(102, 102, 102); font-family: arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">EP run statistics</h3>

VEP version (API) | 106 (106)
-- | --
Annotation sources | Cache: /home/.vep/homo_sapiens_refseq/106_GRCh38; homo_sapiens_core_106_38 on ensembldb.ensembl.org; Custom: /home/Desktop/references/gtf/Homo_sapiens.GRCh38.103.chr_patch_hapl_scaff.bed.gtf.gz (overlap)
Species | homo_sapiens
Command line options | --af_gnomad --biotype --cache --custom /home/Desktop/references/gtf/Homo_sapiens.GRCh38.103.chr_patch_hapl_scaff.bed.gtf.gz,,gtf --fasta /home/Desktop/references/Homo_sapiens.GRCh38.dna.primary_assembly.fa.bgz --filter_common --freq_pop gnomAD --gene_phenotype --gtf /home/Desktop/references/gtf/Homo_sapiens.GRCh38.103.chr_patch_hapl_scaff.bed.gtf.gz --hgvs --input_file /home/Desktop/VCF gabriel/1.vcf --max_af --numbers --output_file /home/Desktop/vcf_vep/1.vep.vcf --polyphen b --refseq --regulatory --sift b --symbol --transcript_version --variant_class --vcf --verbose
Start time | 2022-05-11 20:13:36
End time | 2022-05-11 20:23:30
Run time | 594 seconds
Input file | /home/Desktop/VCF gabriel/1.vcf
Output file | /home/Desktop/vcf_vep/1.vep.vcf

<br class="Apple-interchange-newline">

```

I'm not sure if the output file is OK because of the errors it gave.

**Comment by olaaustine** [comment]
Hi @GACGAMA 
Thank you for your query.
Is it possible for you to share your input file to check if I can recreate the warning? 
Thank you 
Ola.

**Comment by GACGAMA** [comment]
[1.vcf.txt](https://github.com/Ensembl/ensembl-vep/files/8680661/1.vcf.txt)
This is the vcf (just remove the txt extension)

**Comment by olaaustine** [comment]
Hi @GACGAMA,
Thank you for sharing your VCF file.
I have been unable to recreate this issue.
 I suggest you use our latest FASTA file `http://ftp.ensembl.org/pub/release-106/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz` and our latest GTF file `http://ftp.ensembl.org/pub/release-106/gtf/homo_sapiens/Homo_sapiens.GRCh38.106.chr_patch_hapl_scaff.gtf.gz` as your VEP version is 106.  
 Thank you, 
 Ola.
