### ISSUE TITLE
Filter_vep for multiple conditions in one command line

### ISSUE THREAD

**Issue by dana-obk** [Ensembl/ensembl-vep#1177]
Dear all,

I would like to filter out variants > than MAX_AF 0.05 and all synonymous_variants (but not in case synonymous_variants&intron ecc ecc).
How is it possible to do in one command line using filter_vep?

`perl filter_vep --format vcf --filter "MAX_AF < 0.05" --filter  "Consequence not synonymous_variant"-i {input} -o {output}`

**Comment by olaaustine** [comment]
Hi @dana-obk 
Thank you for your query. You can use 
`perl filter_vep --format vcf --filter "(MAX_AF < 0.05) AND (Consequence != synonymous_variant)" -i {input} -o {output} `
Thank you 
Ola.

**Comment by dana-obk** [comment]
So If I want to filter out also MODIFIER etc etc, I do like this?
`perl filter_vep --format vcf --filter "(MAX_AF < 0.05) AND (Consequence != synonymous_variant)" AND (IMPACT != MODIFIER)" -i {input} -o {output}`

Thanks a lot! Unfortunately there is no example in vep documentation, so this is very helpful to know.

**Comment by olaaustine** [comment]
Hi @dana-obk,
You can also use : 
`perl filter_vep --format vcf --filter "(MAX_AF < 0.05) AND (Consequence != synonymous_variant) AND (IMPACT != MODIFIER)" -i {input} -o {output`
The filter_vep documentation is [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html)
You can also check for what can be filtered on using:
`perl filter_vep --list --format vcf -i {input}`
The [--list](https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html#:~:text=%2D%2D-,list,-%2Dl) would list allowed field allowed fields from the input file.
Please let us know if you have any other query.
Thank you. 
Ola.
