### ISSUE TITLE
combination of --check_ref --dont_skip fails to catch problematic lines

### ISSUE THREAD

**Issue by ghost** [Ensembl/ensembl-vep#1178]
## Describe the issue
With the file below, --check_ref and --dont_skip fail to produce expected string "failed" in the "CHECK_REF" column. Variant where REF is AAT does not match the reference, or does it?

### System
- VEP version: 105
- VEP Cache version: 105
- Perl version: 5.32.1
- OS: Debian
- tabix installed: yes

### Full VEP command line
```
./vep  -input_file /opt/vep/.vep/input/test.vcf --offline --cache --cache_version 105 --dir_cache /opt/vep/.vep/reference --refseq --hgvs --hgvsg --fasta /opt/vep/.vep/reference/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz --format vcf --vcf --check_ref --dont_skip --force_overwrite --no_stats -o stdout > /opt/vep/.vep/output/test_VEP_RefSeq.vcf
```

### Input
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	S21
chr13	32900399	.	AAT	A	.	PASS		GT:DP:AF	0/1::0.0138313
chr13	32900399	.	TAT	A	.	PASS		GT:DP:AF	0/1::0.0138313
chr13	32900399	.	GAT	A	.	PASS		GT:DP:AF	0/1::0.0138313
chr13	32900399	.	CAT	A	.	PASS		GT:DP:AF	0/1::0.0138313

### Output
##fileformat=VCFv4.1
##VEP="v105" time="2022-05-12 14:56:46" cache="/opt/vep/.vep/reference/homo_sapiens_refseq/105_GRCh37" ensembl-variation=105.ac8178e ensembl-io=105.2a0a40c ensembl=105.525fbcb ensembl-funcgen=105.660df8f 1000genomes="phase3" COSMIC="92" ClinVar="202012" HGMD-PUBLIC="20204" assembly="GRCh37.p13" dbSNP="154" gencode="GENCODE 19" genebuild="2011-04" gnomAD="r2.1" polyphen="2.2.2" refseq="2020-10-26 17:03:42 - GCF_000001405.25_GRCh37.p13_genomic.gff" regbuild="1.0" sift="sift5.2.2"
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|REFSEQ_MATCH|REFSEQ_OFFSET|GIVEN_REF|USED_REF|BAM_EDIT|HGVS_OFFSET|HGVSg|CHECK_REF">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	S21
chr13	32900399	.	AAT	A	.	PASS	CSQ=-|frameshift_variant|HIGH|BRCA2|675|Transcript|NM_000059.4|protein_coding|6/27||NM_000059.4:c.498_499del|NP_000050.3:p.Pro168LysfsTer14|696-697|497-498|166|H/X|cAT/c|||1||EntrezGene||||AT|TA||1|chr13:g.32900401_32900402del|	GT:DP:AF	0/1::0.0138313
chr13	32900399	.	TAT	A	.	PASS	CSQ=A|frameshift_variant|HIGH|BRCA2|675|Transcript|NM_000059.4|protein_coding|6/27||NM_000059.4:c.496_498delinsA|NP_000050.3:p.His166AsnfsTer16|695-697|496-498|166|H/X|CAT/A|||1||EntrezGene||||TAT|CAT|||chr13:g.32900399_32900401delinsA|**failed**	GT:DP:AF	0/1::0.0138313
chr13	32900399	.	GAT	A	.	PASS	CSQ=A|frameshift_variant|HIGH|BRCA2|675|Transcript|NM_000059.4|protein_coding|6/27||NM_000059.4:c.496_498delinsA|NP_000050.3:p.His166AsnfsTer16|695-697|496-498|166|H/X|CAT/A|||1||EntrezGene||||GAT|CAT|||chr13:g.32900399_32900401delinsA|**failed**	GT:DP:AF	0/1::0.0138313
chr13	32900399	.	CAT	A	.	PASS	CSQ=A|frameshift_variant|HIGH|BRCA2|675|Transcript|NM_000059.4|protein_coding|6/27||NM_000059.4:c.496_498delinsA|NP_000050.3:p.His166AsnfsTer16|695-697|496-498|166|H/X|CAT/A|||1||EntrezGene||||CAT|CAT|||chr13:g.32900399_32900401delinsA|	GT:DP:AF	0/1::0.0138313

**Comment by znestor** [comment]
Hi,
how about using the following as an input file? In my setup, failed reference check does not trigger, while AFAIK position 32900399 in chromosome 13 of build 37 is a C, not an A:
https://grch37.ensembl.org/Homo_sapiens/Location/View?r=13%3A32900399-32900399

#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT S21
chr13 32900399 . AAT A . PASS GT:DP:AF 0/1::0.0138313

This is how originally found out about the issue, then i created a 4-line test file that you see in my opening post.

**Comment by olaaustine** [comment]
Hi @znestor,
I have been able to recreate this issue with only this REF and ALT allele example. 
This is an issue, we are looking into, thanks for bringing this to our notice. 
Ola.
