### ISSUE TITLE
Issue running VEP with GTF due to Bio::DB::HTS::Tabix

### ISSUE THREAD

**Issue by Jensen416** [Ensembl/ensembl-vep#1185]
## Describe the issue
I am using VEP version 102 to annotate my vcf files. 
Prior to running VEP, I index my GTF file using tabix as such: 

`grep -v "#" mm10.gtf | sort -k1,1 -k4,4n -k5,5n -t$'\t' | bgzip -c > mm10.gtf.gz
tabix -p gff mm10.gtf.gz`

Then I call VEP:

`./vep --input_file input.vcf --output_file output.vep.vcf --format vcf --vcf --symbol --terms SO --tsl --fasta mm10.fa --gtf mm10.gtf.gz.tbi --offline --cache --species mus_musculus --merged --dir_plugins ~/VEP_plugins --plugin Wildtype --plugin Frameshift --pick --transcript_version`

The system returns the error:

-------------------- EXCEPTION --------------------
MSG: ERROR: Cannot use format gtf without Bio::DB::HTS::Tabix module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /home/user/ensembl-vep-release-102.0/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:162
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /home/user/ensembl-vep-release-102.0/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:228
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/user/ensembl-vep-release-102.0/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:93
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/user/ensembl-vep-release-102.0/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /home/user/ensembl-vep-release-102.0/modules/Bio/EnsEMBL/VEP/Runner.pm:132
STACK Bio::EnsEMBL::VEP::Runner::run /home/user/ensembl-vep-release-102.0/modules/Bio/EnsEMBL/VEP/Runner.pm:203
STACK toplevel ./vep:229
Date (localtime)    = Thu May 19 09:46:02 2022
Ensembl API version = 102

When checking `perldoc -l Bio::DB::HTS::Tabix` the system returned a path in the root. However, I understand that VEP comes with its own Bio::DB::HTS::Tabix package upon install. I have tried updating the PERL5LIB to direct to the root Tabix or the VEP Tabix, separately. I have also tried removing the VEP Tabix or the root Tabix, separately. Each time I am still met with the same error.

### System
- VEP version: 102
- VEP Cache version: 102
- Perl version: 5.30.0
- OS: Linux
- tabix installed: Yes

**Comment by olaaustine** [comment]
Hi @Jensen416,
Thank you for your query.
Yes, VEP comes with its own tabix installed and this can cause a conflict which is most likely causing this error as you already have Tabix installed separately. 
I suggest that you get a clean checkout of ensembl-vep and install it with the option[ --NO_HTSLIB](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#:~:text=dir%5D%20vep-,%2D%2DNO_HTSLIB,-%2Dl)
Please let us know if you have any more query or if this does not solve the problem.
Thank you. 
Ola.

**Comment by Jensen416** [comment]
That worked! Thank you!
