### ISSUE TITLE
Filter_vep keep variants with empty MAX_AF

### ISSUE THREAD

**Issue by dana-obk** [Ensembl/ensembl-vep#1188]
Dear all,

I am filtering out the variants from vep output (`VEP v.105 with hg19`) that have `MAX_AF` higher than `0.05` like following:

`perl ./filter_vep --format vcf --filter "(MAX_AF < 0.05) AND (Consequence != synonymous_variant)" -i {input} -o {output}`

But this filters out also the empty `MAX_AF` fields, while I would like to keep the fields with empty MAX_AF. How to do that?

**Comment by dana-obk** [comment]
This could be a solution, I think. Please, if someone could confirm.

`perl ./filter_vep --format vcf --filter "(MAX_AF < 0.05 or not MAX_AF) AND (Consequence != synonymous_variant)" -i {input} -o {output}`

**Comment by olaaustine** [comment]
Hi @dana-obk ,
I am going to close this issue now. 
Please feel free to open it if you have a query regarding filter-vep tool.
Thank you, 
Ola.
