### ISSUE TITLE
Invalid tag name with custom GFF

### ISSUE THREAD

**Issue by dariober** [Ensembl/ensembl-vep#1189]
I'm annotating using a custom GFF file named `PlasmoDB-52_PbergheiANKA.gff.gz`. VEP (version 105) adds to the vcf output a tag named after the gff file. In this case, the tag named `PlasmoDB-52_PbergheiANKA.gff.gz` results in bcftools (version 1.15) to issue a warning about an invalid tag name. I guess because of the hyphen in the GFF filename. It's not a big deal but it would be nice to fix it.

## Steps to reproduce

Rename one of the test input files and run VEP:

```
cp t/testdata/custom/test.gff.gz PlasmoDB-52_PbergheiANKA.gff.gz
cp t/testdata/custom/test.gff.gz.tbi PlasmoDB-52_PbergheiANKA.gff.gz.tbi

vep -i t/testdata/input/test.vcf.gz --vcf --gff PlasmoDB-52_PbergheiANKA.gff.gz --format vcf --compress_output bgzip \
    --fasta t/testdata/fasta/Homo_sapiens.GRCh38.toplevel.test.fa --force_overwrite -o tmp.vcf.gz
tabix -f tmp.vcf.gz
```

Runnig bcftools returns a warning:

```
bcftools view tmp.vcf.gz > /dev/null
[W::bcf_hrec_check] Invalid tag name: "PlasmoDB-52_PbergheiANKA.gff.gz" 
```

Here's the vcf header:

```
##fileformat=VCFv4.1
##VEP="v105" time="2022-05-23 14:53:27" ensembl-funcgen=105.660df8f ensembl=105.525fbcb ensembl-io=105.2a0a40c ensembl-variation=105.ac8178e
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|SOURCE|PlasmoDB-52_PbergheiANKA.gff.gz">
##INFO=<ID=PlasmoDB-52_PbergheiANKA.gff.gz,Number=.,Type=String,Description="PlasmoDB-52_PbergheiANKA.gff.gz (overlap)">
```

### System
- VEP version: 105.0 installed via bioconda
- VEP Cache version: N/A
- Perl version: 5.32.1
- OS: CentOS
- tabix installed ? Yes v 1.15.1

**Comment by dglemos** [comment]
Hi @dariober,
Which version of bcftools you're using? 
I tried to replicate the issue with `bcftools view` but I'm not getting any warning.

**Comment by dglemos** [comment]
I could replicate the issue using version 1.15 - currently, we don't have a fix.
Before you run VEP, I recommend removing the unsupported character from `PlasmoDB-52_PbergheiANKA`.

Let me know if you have more questions.

Best wishes,
Diana

**Comment by dglemos** [comment]
I'm closing this issue but if you have more questions feel free to open a new one.

Best wishes,
Diana

**Comment by dariober** [comment]
@dglemos Thanks for looking into this.

> Before you run VEP, I recommend removing the unsupported character from PlasmoDB-52_PbergheiANKA.

Or maybe pass the output VCF to `sed` or similar to fix the invalid tag?

Anyway, if you want to close the issue, that's ok by me. However, I would still consider this a bug since effectively VEP is producing an invalid VCF file from a valid input. 

I'm probably making things too easy here... Shouldn't it be easy to sanitize the name of the input file before creating the INFO tag? It should be just a matter of running a regex to replace invalid characters...?

**Comment by dglemos** [comment]
I'm sorry my message wasn't clear, we closed the issue but the update is in our backlog. 
We will add it sometime in the future.
