### ISSUE TITLE
Can vep give only one canonical transcript result?

### ISSUE THREAD

**Issue by xiucz** [Ensembl/ensembl-vep#1195]
## Describe the issue
I find there are many transcripts in CQS field, it there a parameter to give only one canonical transcript result? 
Thank you.
## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 105
- VEP Cache version: 105

Best, 
xiucz

**Comment by dglemos** [comment]
Hi @xiucz,
There is one option `--canonical` which adds a flag indicating if the transcript is the canonical transcript for the gene. However, the output still includes all the transcripts. To filter the VEP output file you can use the tool `filter_vep` to only include the transcripts that have flag canonical. You can find more info here: https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html 

Another option is to run VEP with the option `--pick` which picks one line or block of consequence data per variant. The consequences are chosen according to the criteria described [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick) and you can customise the order of the criteria with `--pick_order` https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_pick_order

Let me know if you have more questions.

**Comment by xiucz** [comment]
@dglemos 
Thank you! I will feedback later if I meet other questions.
