### ISSUE TITLE
Gene Symbol output issue

### ISSUE THREAD

**Issue by Mahmoudbassuoni** [Ensembl/ensembl-vep#1197]
## Describe the issue
I have an issue regarding the output of the vep offline as it's not getting me the Gene Symbol as I used to have on the online platform. Although I changed the output format using the flag --fields but still getting me blank column for the Gene Symbol.
## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: [105.0] 
- VEP Cache version: [homo_sapiens_vep_105_GRCh38]
- Perl version: [5.32]
- OS: [Ubuntu]
- tabix installed ? yes

### Full VEP command line
`./vep -i /home/bassyouni/Documents/VC/Freebayes/new.vcf -o /home/bassyouni/Documents/Venn_compare/Cancer_Analysis/freebayes_vep_new2.txt --fork 16 --dir_cache /home/bassyouni/.vep/     --cache'`

### Full error message
NA

### Data files (if applicable)
They include:
- The input file VCF
- The output file txt
- The custom file(s) NA

**Comment by nakib103** [comment]
Hi @Mahmoudbassuoni ,

Thanks for your query. Can you provide me with the input you are using so that I can replicate the issue.

Best regards,
Nakib

**Comment by nakib103** [comment]
Hi, I can see only the `intergenic_variants` that do not have Gene Symbols in the output as it should be. To potentially have them as downstream or upstream gene variant with Gene Symbols you can increase the value for `--distance` argument - 

https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_distance 

By default it is 5000bp.

As it says in the doc `--fields` option is used with `tab` or `vcf` output (can be enabled by using `--tab` and `--vcf` respectively) and only filters output and do not modify the result - 
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_fields 

You can send me the examples where you are finding mismatch between online and offline output along with commands you are using. I can have a look.

Best regards,
Nakib

**Comment by Mahmoudbassuoni** [comment]
Hi @nakib103 
Thanks for the reply, the thing is I am comparing the output of different variant calling tools so I am using the output of Vep to compare the genes results but with the other tools I didn't have to play with that distance so I am afraid not to be consistent regarding the procedure itself. My question now would be, do you have any idea what should be the distance ? and also the other files from the other tools came to be holding intergenic variants also but while ran on the online platform it gave normal resutls. This file only came to be bigger than 50M so I couldn't run it on the online platform!

**Comment by nakib103** [comment]
Hi,

> do you have any idea what should be the distance ?

It can vary depending on the work is being done. As, you are comparing different tools it makes sense to keep this parameter same for all of them. So, you should find out what is the distance the other tools are using when annotating a variants against a gene.

> also the other files from the other tools came to be holding intergenic variants also but while ran on the online platform it gave normal resutls.

I do not understand the question properly. What is the online platform you are talking about - is it related to vep? It would be helpful if you can share the results from this two sources so that we can compare.

**Comment by Mahmoudbassuoni** [comment]
yeah I mean the VEP online tool, I used it with the other vcf files resulted from the other tools. All of them came to be consistent with slight differences as for the variant calling results of each tool but this one result was really questionable so I believe it's because of the VEP offline resutls!

**Comment by nakib103** [comment]
I can see you are using **105 version** for offline, currently Ensembl e106 has been released and the VEP online tool uses the new version. Can you try using the 106 version?

**Comment by Mahmoudbassuoni** [comment]
maybe I would try that yes. Thanks @nakib103

**Comment by Mahmoudbassuoni** [comment]
Hi @nakib103 I have tried the newer version 106 but still the same. Look at the picture, that's part of the resulted file, what I mean is you can see here the ENSG ID of the Gene but the SYMBOL column always comes to be blank. I am not sure if I am missing a flag to add or what should I do for it to appear? 

![Screenshot from 2022-05-31 11-42-43](https://user-images.githubusercontent.com/16631169/171144948-7ed323b2-d4a2-430d-a474-9cd06570eee1.png)
)

**Comment by nakib103** [comment]
Thanks for checking. 
Can you provide me the full command you used to get this result?

**Comment by Mahmoudbassuoni** [comment]
`./vep -i /home/bassyouni/Documents/VC/Freebayes/new.vcf -o /home/bassyouni/Documents/Venn_compare/Cancer_Analysis/freebayes_vep_new3.txt --tab  --fields "Uploaded_variation,Location,Allele,Gene,SYMBOL,Existing_variation" --cache`

**Comment by Mahmoudbassuoni** [comment]
Hei @nakib103, Thanks Man, it's all working now!!! I have just used the same command above but added `--symbol ` and it came to be added to the output the same like the VEP online platform. 
`./vep -i /home/bassyouni/Documents/VC/Freebayes/new.vcf -o /home/bassyouni/Documents/Venn_compare/Cancer_Analysis/freebayes_vep_new3.txt --tab --cache --fork 16 --check_existing --symbol --force_overwrite `

**Comment by nakib103** [comment]
Great that it works! I was just testing the same thing for you.

The `--field` option can only filter out the output (if it is present). It does not actually generate the output for you. `--symbol` actually produce the Gene Symbols as says here - 
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_symbol
