### ISSUE TITLE
 --domain option not working

### ISSUE THREAD

**Issue by JIBINJOHNV** [Ensembl/ensembl-vep#1201]
## Describe the issue

During the VEP annotation, I used "--domains," but no domain information was incorporated into the DOMAINS column. Could you please check this?

Furthermore, I would like to know whether the domain information are gene/transcript specifics or variant position-specifics

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version:106
- VEP Cache version: 106
- OS: , Ubuntu
- tabix installed ? Yes

### Full VEP command line
```
docker run -it \
-v /home/:/home/ \
-v $HOME/vep_data:/opt/vep/.vep ensemblorg/ensembl-vep vep \
--refseq  \
--CACHE_VERSION 106 \
--dir_plugins /opt/vep/.vep/Plugins \
--no_stats \
-i /home/clinvar_20220528.vcf.gz \
 -o /home/clinvar_20220528_vep.tab \
--symbol --hgvs --variant_class --gene_phenotype \
--flag_pick_allele_gene --canonical --appris --ccds --numbers --total_length --mane \
--sift p --polyphen p \
--fasta  /opt/vep/.vep/homo_sapiens_refseq/106_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz \
--species homo_sapiens --assembly GRCh37 \
--max_af --domains \
--custom /opt/vep/.vep/clinvar.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNREVSTAT,CLNDN, \
--custom /opt/vep/.vep/hg19_rmsk.bed.gz,repeats,bed \
--custom /opt/vep/.vep/hg19_genomicSuperDups.bed.gz,genomicSuperDups,bed \
--plugin CADD,/opt/vep/.vep/whole_genome_SNVs.tsv.gz,/opt/vep/.vep/InDels.tsv.gz, \
--plugin dbscSNV,/opt/vep/.vep/dbscSNV1.1_GRCh37.txt.gz \
--plugin NMD \
--plugin ExACpLI,/opt/vep/.vep/ACMG_Lof_Genes.tsv \
--plugin dbNSFP,/opt/vep/.vep/dbNSFP4.3c_grch37.gz,PROVEAN_pred,LRT_pred,MutationTaster_pred,\
MutationAssessor_pred,FATHMM_pred,fathmm-MKL_coding_pred,M-CAP_pred,fathmm-XF_coding_pred,\
DANN_score,MutPred_score,PrimateAI_pred,Aloft_pred,BayesDel_addAF_pred,GERP++_RS,\
MVP_score,Eigen-phred_coding,SiPhy_29way_logOdds,bStatistic,Interpro_domain,MetaLR_pred,\
GTEx_V8_gene,GTEx_V8_tissue --offline --tab --fork 10


### Full error message
No error and vep run was completed successfully. But the Domain column was empty

**Comment by nakib103** [comment]
Hello @JIBINJOHNV ,

Thanks foe your query!

So the first thing is the refseq support is somewhat limited and it does not provide domain information. As you can see here - https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#refseq
As you are using refseq cache you are not getting any domain results.

As, for your second question - it is more of a variant-position specific as variant position in the peptide co-ordinates are taken into account when getting the overlapped domain.

Hope that answers your question.

Best regards,
Nakib

**Comment by nakib103** [comment]
Hi,

I am closing this issue. If you have further issue regarding this - please feel free to create another ticket.
