### ISSUE TITLE
Where to find the cache data details for different VEP versions

### ISSUE THREAD

**Issue by SimonLi5601** [Ensembl/ensembl-vep#1202]
I can only find the cache data for latest version, but I can't find the older version of all default human cache files
https://useast.ensembl.org/info/docs/tools/vep/script/vep_cache.html

Do you have the detailed release notes? Thanks!

**Comment by jamie-m-a** [comment]
Hi @SimonLi5601 

To download previous versions of the VEP cache you can access them directly via:

http://ftp.ensembl.org/pub/release-106/variation/indexed_vep_cache/

Just amend the release-XXX to the release you're looking for.

General Ensembl release notes are available through the Ensembl blog here: https://www.ensembl.info/2022/04/12/ensembl-106-has-been-released/

And VEP specific new features are here: https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#new 

Let me know if there's anything else I can help with.

**Comment by SimonLi5601** [comment]
@jamie-m-a Thanks for your reply. Let's say,  I would like to know what's the exact version of Gencode and Clinvar used for VEP99, I can't seem to find a place for it like the table in the latest version which has all the details. If those information could be placed in the FTP or the history website, that would be very helpful.

**Comment by jamie-m-a** [comment]
Hi Simon,

When you extract the cache file, there should be a file called info.txt in the directory it extracts to. This file contains details of the versions of Gencode, Clinvar etc... that were used for the creation of that specific cache file.

For example, for VEP 99:

source_gencode	GENCODE 33
source_ClinVar	201909

We currently don't collate all this information but we will review and discuss internally whether doing so might be a useful resource for VEP users.

**Comment by jamie-m-a** [comment]
Closing this one down - we'll look to add this info to the release documentation going forward.
