### ISSUE TITLE
filter vep does not work

### ISSUE THREAD

**Issue by raynogu** [Ensembl/ensembl-vep#1203]
I used filter vep to extract protein coding SNV from vcf file.

 /bin/bash
#$ -cwd
eval "$(~/miniconda3/bin/conda shell.bash hook)"
conda activate env-vep
filter_vep -i /home/renoguch/input_noguchi/out4.vcf -o out5f.vcf --vcf --filter "Consequence is protein_coding"
conda deactivate

Then, I got error message as below.

-------------------- EXCEPTION --------------------
MSG: ERROR: No valid filters given

STACK main::configure /home/renoguch/miniconda3/envs/env-vep/bin/filter_vep:110
STACK toplevel /home/renoguch/miniconda3/envs/env-vep/bin/filter_vep:52
Date (localtime)    = Wed Jun 15 02:18:46 2022
Ensembl API version = 106
---------------------------------------------------

What should I do ?

**Comment by raynogu** [comment]
Thanks! Ola.
I already performed vep exchange against my vcf file.
Then, I performed vep filter. Is it right ? Please tell me to confirm that you have protein_coding as a consequnece.

Ray

**Comment by olaaustine** [comment]
Hi @raynogu,
Our list of calculated variant consequences can be found [here](https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html).
Thanks,
Ola.

**Comment by olaaustine** [comment]
Hi @raynogu,
I am going to close this ticket now.
Please feel free to open another or reopen this if you have any other query.
Thank you, 
Ola.
