### ISSUE TITLE
Downstream plugin: `Use of uninitialized value $pep_end in numeric lt (<)`

### ISSUE THREAD

**Issue by Z-Zen** [Ensembl/ensembl-vep#1204]
## Describe the issue
The [Downstream](https://github.com/Ensembl/VEP_plugins/blob/release/106/Downstream.pm) plugin gives a warning when annotating a VCF file. Is this warning supposed to be normal ?

## Additional information
Regular exome file of a human patient annotating with hg38.

### System
- VEP version: `106`
- VEP Cache version: `106`
- Perl version: `v5.26.1`
- OS: `Ubuntu 18.04.6 LTS`
- tabix installed ? `Yes`

### Full VEP command line
```
vep --cache \
  --dir /dev/shm/ \
  --dir_plugins /opt/vep/.vep/Plugins/ \
  -i 23016_INDEL_polyx.chr3.vcf \
  -o 23016_INDEL_annotated_picked_chr3.vcf \
  --refseq --everything --humdiv --no_escape --no_stats \
  --buffer_size 50 --pick_allele \
  --exclude_predicted --fork 1 \
  --force --cache --offline \
  --assembly GRCh38 \
  --fasta /Isiprod1/data/reference/hg38/tmp/bwa2/GCF_000001405.40_GRCh38.p14_genomic_primary_assembly.fa \
  --plugin dbNSFP,/dev/shm/dbNSFP/dbNSFP4.3a/dbNSFP4.3a_grch38.gz,Polyphen2_HDIV_rankscore,Polyphen2_HVAR_rankscore,SIFT_converted_rankscore,SIFT4G_converted_rankscore,LRT_converted_rankscore,MutationTaster_converted_rankscore,MutationTaster_score,MutationAssessor_rankscore,FATHMM_converted_rankscore,PROVEAN_converted_rankscore,VEST4_rankscore,MetaSVM_score,phyloP17way_primate,ESP6500_AA_AF,ESP6500_EA_AF,ExAC_AC,ExAC_AFR_AF,ExAC_NFE_AF,ExAC_AMR_AF,ExAC_EAS_AF,ExAC_SAS_AF,Ancestral_allele,gnomAD_exomes_AC,gnomAD_exomes_AN,gnomAD_exomes_AF \
  --plugin dbscSNV,/dev/shm/dbscSNV/dbscSNV1.1/dbscSNV1.1_GRCh38.txt.gz \
  --plugin GeneSplicer,/dev/shm/genesplicer/sources/genesplicer,/dev/shm/genesplicer/human,tmpdir=/dev/shm/ \
  --plugin MaxEntScan,/dev/shm/MaxEntScan \
  --plugin SpliceRegion \
  --plugin CADD,/dev/shm/CADD/GRCh38_v1.6/whole_genome_SNVs.tsv.gz,/dev/shm/CADD/GRCh38_v1.6/gnomad.genomes.r3.0.indel.tsv.gz \
  --plugin REVEL,/dev/shm/REVEL/new_tabbed_revel.tsv.gz \
  --plugin Blosum62 \
  --plugin Conservation,/dev/shm/Conservation/gerp_conservation_scores.homo_sapiens.GRCh38.bw \
  --plugin Downstream \
  --vcf --use_given_ref
```

### Full error message
> Including the warnings, if available
```
WARNING: 1080 : Use of uninitialized value $pep_end in numeric lt (<) at /opt/vep/.vep/Plugins/Downstream.pm line 142, <__ANONIO__> line 162.
  Use of uninitialized value $pep_start in numeric lt (<) at /opt/vep/.vep/Plugins/Downstream.pm line 142, <__ANONIO__> line 162.
  Use of uninitialized value $pep_end in addition (+) at /opt/vep/.vep/Plugins/Downstream.pm line 142, <__ANONIO__> line 162.
```
### Data files (if applicable)
[VCFs.zip](https://github.com/Ensembl/ensembl-vep/files/8907305/VCFs.zip)

**Comment by jamie-m-a** [comment]
Hi @Z-Zen 

Thanks for providing the data I'll take a look into this and get back to you if I need any more information.

**Comment by jamie-m-a** [comment]
Hi @Z-Zen 

Firstly my apologies for not getting back to you sooner, this one fell through the cracks! 

In short, no, it's not a big problem, it looks like we couldn't calculate new peptide start and end positions for one of the variants, so at the worst you may have been missing some data. I will continue to look at the plugin to see exactly what happened, but I'm going to close this ticket now as I suspect the outcome is no longer relevant for you. 

Please do reach out if you have any other questions though.
