### ISSUE TITLE
get hgvs genomic position

### ISSUE THREAD

**Issue by asmlgkj** [Ensembl/ensembl-vep#1208]
thanks a lot for this powerful tool.
I input a variant  chr7	55248980	.	C	CTCCAGGAAGCCT  into vep online of grch37.

I get the HGVSc   NM_005228.5:c.2284-5_2290dup
I also want to get the hgvs.g，can you have a look

**Comment by likhitha-surapaneni** [comment]
Hi @asmlgkj ,

Thank you for reaching out to us.

HGVSg can be obtained by running VEP using the command-line with the option --hgvsg . You can check the other options available in https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html 

You can also obtain HGVSg by using Variant Recoder tool. Please check https://www.ensembl.org/info/docs/tools/vep/recoder/index.html for further details.

Kindly reach out to us if you have any further questions.

Thanks and regards,
Likhitha

**Comment by asmlgkj** [comment]
Thanks  a lot.
I tried the variant recorder. the result is the following picture, in fact it was an insertion in chr7:55248992 due to the insertion was dupliction of genome sequence between 55248980-55248992, variant recorder seems does not fullfil this job
![image](https://user-images.githubusercontent.com/50854682/175553094-8ca3fc67-ab7f-45cd-a3ea-8610567d02ac.png)

**Comment by likhitha-surapaneni** [comment]
Hi @asmlgkj ,

I am sorry to hear that you are facing an issue with Variant Recoder.

Could you please confirm if you are using the the Variant Recoder corresponding to GRCh37: https://grch37.ensembl.org/Homo_sapiens/Tools/VR

**Comment by asmlgkj** [comment]
@likhitha-surapaneni  yes, I am using grch37

**Comment by likhitha-surapaneni** [comment]
Hi @asmlgkj ,

Thank you for your patience.

According to HGVS recommendations for sequence variants (https://varnomen.hgvs.org/recommendations/general/), duplication takes precedence over insertion. In this case, 55248981_55248990dup takes precedence over 55248992 insertion. 

Please let us know if you have any other questions!

Kind regards,
Likhitha

**Comment by likhitha-surapaneni** [comment]
Hi @asmlgkj ,

I am going to close this issue for now. Please feel free to open a new issue if you have any other questions.

Kind regards,
Likhitha
