### ISSUE TITLE
Error while installing new releases of vep!!

### ISSUE THREAD

**Issue by Navin-techi** [Ensembl/ensembl-vep#1210]
Would like to know how to bypass the 

**_The VEP can either connect to remote or local databases, or use local cache files.
Using local cache files is the fastest and most efficient way to run the VEP
Cache files will be stored in /root/.vep
Do you want to install any cache files (y/n)? y
Cache directory /root/.vep does not exists - do you want to create it (y/n)? y
 - getting list of available cache files
ERROR: Could not login as anonymous_**

![Screenshot at 2022-06-24 12-30-42](https://user-images.githubusercontent.com/73836925/175482232-c50d4965-3c3e-4c7e-9381-ef7fda38228f.png)

Trying to install it in ubuntu 18.04 .

**Comment by olaaustine** [comment]
Hi @Navin-techi,
Thank you for query.
Can you please start a fresh install of VEP?
Please let us know if there are any more issues.
Thank you,
Ola.

**Comment by Navin-techi** [comment]
Hi @olaaustine,
Did try installing with the new version from your git repo. I am still finding the following error.

![Screenshot at 2022-06-25 18-46-10](https://user-images.githubusercontent.com/73836925/175775157-57e500bc-252a-40b8-a321-50627446be04.png)

Would be best if there is a way around it. 

These are the following packages requested for this Build.

cpan install Bio::DB::HTS::Tabix
cpan install DBI 
cpan install Module::Build
cpan install Archieve::Zip
cpan install Bio::EnsEMBL
cpan install Bio::Perl.

Even tried fulfilling the deps packages in biodbhts directory. Yet the results seem the same as mentioned in the snapshot.

**Comment by olaaustine** [comment]
Hi @Navin-techi,
As a workaround, Can you say "n" instead and then manually install cache files?
```
curl -O http://ftp.ensembl.org/pub/release-106/variation/vep/homo_sapiens_vep_106_GRCh38.tar.gz
tar xzf homo_sapiens_vep_106_GRCh38.tar.gz
```
Thank you, 
Ola

**Comment by olaaustine** [comment]
Hi @Navin-techi,
I am going to close this ticket now. 
Please feel free to open another ticket if you have any query.
Thank you.
Ola
