### ISSUE TITLE
--total_length option in JSON mode removes position values instead of adding length

### ISSUE THREAD

**Issue by fedkon** [Ensembl/ensembl-vep#1211]
### The issue

In JSON output mode, --total_length option removes position values from results instead of presenting them in pos/length form as it should.

In standard VEP output mode, --total_length option works fine.

### Likely cause

I guess the position parsing code in JSON output factory does not (yet) take into account a postfix starting with "/" and deletes the non-conforming value whatsoever.

### System
- VEP version: 106.1
- VEP Cache version: 106
- Perl version: 5.32.1
- OS: Debian 11
- tabix installed? yes

### Test VEP command line with JSON output
```
vep -i test_length_json.vcf --cache --dir_cache ~/VEP_CACHE/ --offline --canonical --symbol --hgvs --refseq --numbers --shift_3prime 1 --flag_pick_allele --pick_order rank,canonical,mane,appris,tsl,biotype,ccds,length --regulatory --mirna --canonical --tsl --mane --biotype --total_length --json -o test-output_length.json
```
### Control VEP command line with JSON output (no --total_length option)
```
vep -i test_length_json.vcf --cache --dir_cache ~/VEP_CACHE/ --offline --canonical --symbol --hgvs --refseq --numbers --shift_3prime 1 --flag_pick_allele --pick_order rank,canonical,mane,appris,tsl,biotype,ccds,length --regulatory --mirna --canonical --tsl --mane --biotype --json -o test-output_nolength.json
```

### Prettifying
```
cat test-output_nolength.json | jq -S > test-output_nolength_pretty.txt
cat test-output_length.json | jq -S > test-output_length_pretty.txt
```

### Diff results: position values just disappear with --total_length on
```
diff test-output_nolength_pretty.txt test-output_length_pretty.txt

16,19d15
<       "cdna_end": 6206,
<       "cdna_start": 6206,
<       "cds_end": 6134,
<       "cds_start": 6134,

34,35d29
<       "protein_end": 2045,
<       "protein_start": 2045,
```

### Data files
ZIP archive: [test_length.zip](https://github.com/Ensembl/ensembl-vep/files/8976193/test_length.zip)

- input VCF (GRCh38): test_length_json.vcf
```
##fileformat=VCFv4.0
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr1	152308752	.	C	G	.	.	.
```
- test-output_length.json
- test-output_length_pretty.txt
- test-output_nolength.json
- test-output_nolength_pretty.txt

**Comment by likhitha-surapaneni** [comment]
Hi @fedkon , 

Thank you for the detailed report.

I can confirm that I see the same results. We will try to add a fix for parsing the pos/length correctly. 

Kind regards,
Likhitha

**Comment by likhitha-surapaneni** [comment]
Hi @fedkon ,

Thank you for your patience. We resolved this bug in release 108. 

I am closing this issue for now. Please feel free to open a new issue if you have any other queries.

Kind regards,
Likhitha
