### ISSUE TITLE
lmza.h not found on VEP install

### ISSUE THREAD

**Issue by scthree** [Ensembl/ensembl-vep#1212]
Dear Ensembl, thank you greatly in advance for your help. I know you're busy and appreciate your time!

## Describe the issue
I'm trying to install VEP without using the --NO_HTSLIB option (because I'd like to use ClinVar and manually download caches downstream). The lzma.h header can't be found in /usr/include but I can't access this folder (I'm on a cluster and don't have root access). Is there still anyway to complete the download?
(Sorry for my stupid question, I'm a complete newbie at coding)

### System
- VEP version: 106
- Perl version: 5.26
- OS: CentOS 7.9
- tabix installed: no

### Full VEP command line
perl INSTALL.pl

### Full error message
WARNING: DBD::mysql module not found. VEP can only run in offline (--offline) mode without DBD::mysql installed

http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#requirements

Hello! This installer is configured to install v106 of the Ensembl API for use by the VEP.
It will not affect any existing installations of the Ensembl API that you may have.

It will also download and install cache files from Ensembl's FTP server.

Checking for installed versions of the Ensembl API...done

Setting up directories
 - fetching BioPerl
 - unpacking ./Bio/tmp/release-1-6-924.zip
 - moving files
Attempting to install Bio::DB::HTS and htslib.

>>> If this fails, try re-running with --NO_HTSLIB

lzma.h library header(s) not found in /usr/include. Please install it and try again.
(or to skip Bio::DB::HTS/htslib install re-run with --NO_HTSLIB)

On Debian/Ubuntu systems you can do this with the command:

apt-get install liblzma-dev

**Comment by olaaustine** [comment]
Hi @scthree,
Thank you for your query.
As this is a cluster, can you confirm that tabix(HTSLIB) is not already installed on the cluster?
Thank you, 
Ola.

**Comment by olaaustine** [comment]
Hi @scthree,
I am going to close this ticket now.
Please feel free to open another if you have another query.
Thank you
Ola
