### ISSUE TITLE
Make VEP understand sequence ontology features (e.g. gene -> protein_coding_gene)

### ISSUE THREAD

**Issue by dariober** [Ensembl/ensembl-vep#1217]
I'm working with [GFF annotations](https://plasmodb.org/common/downloads/release-58/PbergheiANKA/gff/data) from VEuPathDB where the "gene" feature (3rd column) is marked as "protein_coding_gene" and VEP doesn't recognize "protein_coding_gene" as a valid feature type.

Since "protein_coding_gene" is a valid [sequence ontology](http://www.sequenceontology.org/browser/current_release/term/SO:0001217) term it would be great if VEP could work with it.

## Additional information

These steps should reproduce the limitation using the test data:

* Prepare a gff file with "protein_coding_gene" replacing "gene" (also replace chromosome name NC_000021.9 with 21):

```
zcat t/testdata/custom/refseq.gff.gz \
| sed 's/\tgene\t/\tprotein_coding_gene\t/; s/NC_000021.9/21/' \
| bgzip > ../refseq2.gff.gz

tabix ../refseq2.gff.gz
```

* Running VEP issues warnings about invalid types:

```
vep --force_overwrite -i t/testdata/input/test.vcf --gff ../refseq2.gff.gz --fasta t/testdata/fasta/Homo_sapiens.GRCh38.toplevel.test.fa 

WARNING: Parent entries with the following IDs were not found or skipped due to invalid types: gene49534, gene49532, gene49521, gene49527, gene49525, gene49522, gene49524, gene49518, gene49523, gene49537, gene49535, gene49531, gene49516, gene49536, gene49519, gene49514, gene49528, gene49513, gene49526
```

### System

```
vep 
#----------------------------------#
# ENSEMBL VARIANT EFFECT PREDICTOR #
#----------------------------------#

Versions:
  ensembl              : 106.f4b50c6
  ensembl-funcgen      : 106.027e023
  ensembl-io           : 106.6eafdaa
  ensembl-variation    : 106.2aa7a5d
  ensembl-vep          : 106.1
```

**Comment by likhitha-surapaneni** [comment]
Hi @dariober ,

Thank you for reaching out to us. I am going to discuss with my team regarding supporting "protein_coding_gene" sequence ontology and will keep you updated on the same.

Kind regards,
Likhitha

**Comment by likhitha-surapaneni** [comment]
Hi @dariober ,

Hope you are doing well!

Support for "protein_coding_gene" will be available in release 108. I hope this resolves the issue. Please feel free to open a new ticket if you have any other questions.

Kind regards,
Likhitha

**Comment by dariober** [comment]
@likhitha-surapaneni thanks for taking care of this! 

Will release 108 only add "protein_coding_gene" or will it include other sequence ontology terms? Ideally, it would be good to support the official sequence ontology tree, including for example the children of "protein_coding_gene", "ncRNA", etc. although I guess that would be quite a feat.

For example, these are the types from one of the GFF from plasmodb, I think they are all SO terms:

```
curl  -s https://plasmodb.org/common/downloads/release-58/PbergheiANKA/gff/data/PlasmoDB-58_PbergheiANKA.gff | grep -v '^#' | cut -f 3 | sort | uniq
CDS
exon
mRNA
ncRNA
ncRNA_gene
protein_coding_gene
pseudogene
pseudogenic_transcript
rRNA
snoRNA
snRNA
three_prime_UTR
tRNA
```

Also (this may be a separate issue), if the input GTF/GFF includes unsupported types, it would be useful to issue warnings to notify the user that some records have been ignored.

**Comment by likhitha-surapaneni** [comment]
Hi @dariober ,

We have plans of supporting the other ontology terms from the official sequence ontology tree in the future releases.

Issuing warnings to notify the user about the ignored records during handling of unsupported types is definitely a useful feature. We will let you know once we have an update on that.

Thank you for your time and patience.

Kind regards,
Likhitha
