### ISSUE TITLE
VCF only have intergenic variants

### ISSUE THREAD

**Issue by SowmyaPulapet** [Ensembl/ensembl-vep#1218]
## Describe the issue
I am using ensembl VEP to annotate my VCF files, but the resultant annotated VCF only have intergenic variants  ! I am using the GFF file and Fasta file from Phytozome. Earlier I had an issue as chromosome names of VCF and GFF were not matching, then I created chr_synonyms.txt. It did work but the result is not desirable. Would you please help me?
## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 106
- Perl version : v5.22
- OS: Ubuntu
- tabix installed = Yes

### Full VEP command line
```
./vep -i var.vcf --gff Osativa_323_v7.0.gene.gff3.gz --fasta Osativa_323_v7.0.transcript.fa.gz --output_file var_anno.txt --stats_file var_anno_summary.html --synonyms chr_synonyms.txt
```

### Full error message
>WARNING: No exons found for protein_coding transcript LOC_Os12g01020.1.MSUv7.0

### Data files (if applicable)
They include:
- Input VCF
  `LOC_Os11g48100.1	252	.	C	G,T	730.311	.	AB=0.387097,0.612903;ABP=6.44263,6.44263;AC=1,1;AF=0.5,0.5;AN=2;AO=12,19;CIGAR=1X,1X;DP=31;DPB=31;DPRA=0,0;EPP=3.73412,3.12459;EPPR=0;GTI=0;LEN=1,1;MEANALT=2,2;MQM=58.3333,54.8947;MQMR=0;NS=1;NUMALT=2;ODDS=45.3181;PAIRED=0.583333,0.789474;PAIREDR=0;PAO=0,0;PQA=0,0;PQR=0;PRO=0;QA=394,639;QR=0;RO=0;RPL=11,8;RPP=21.1059,4.03889;RPPR=0;RPR=1,11;RUN=1,1;SAF=6,8;SAP=3.0103,4.03889;SAR=6,11;SRF=0;SRP=0;SRR=0;TYPE=snp,snp	GT:DP:RO:QR:AO:QA:GL	1/2:31:0:0:12,19:394,639:-82.0662,-50.393,-46.7806,-31.9997,0,-26.2801`

- The output file
  `LOC_Os11g48100.1_252_C/G/T	LOC_Os11g48100.1:252	T	-	-	-	intergenic_variant	-	-	-	-	--	IMPACT=MODIFIER`

- The custom file(s)
GFF file:
 `Chr1    phytozomev11    mRNA    2903    10817   .       +       .       ID=LOC_Os01g01010.1.MSUv7.0;Name=LOC_Os01g01010.1;pacid=33123311;longest=1;Parent=LOC_Os01g01010.MSUv7.0
`
- chr_synonyms.txt (in tab limited format, not like how it is displayed here)
`LOC_Os01g01010  Chr1
LOC_Os01g01010.1        Chr1
LOC_Os01g01010.1        Chr1
LOC_Os01g01010.1        Chr1
LOC_Os01g01010.1        Chr1
LOC_Os01g01010.1        Chr1`

**Comment by olaaustine** [comment]
Hi @SowmyaPulapet,
Thank you for your query. 
Is it possible for you to share the GFF and FASTA file being used so we can recreate the issue. 
Thank you, 
Ola.

**Comment by SowmyaPulapet** [comment]
Hi @olaaustine 
 Thank you for your response. Here I am attaching zip file with the data. Please tell me if you are not able to use it. 
link : 
[download.20220713.160644.zip](https://github.com/Ensembl/ensembl-vep/files/9101291/download.20220713.160644.zip)

**Comment by olaaustine** [comment]
Hi @SowmyaPulapet,
Thank you for the folder shared, I can find the FASTA file used Osativa_323_v7.0.transcript.fa.gz.
Please can you share the gff file again?
Thank you
Ola.

**Comment by SowmyaPulapet** [comment]
Hi @olaaustine 
  Sorry, I uploaded the wrong zip. This one contains the GFF file. 
[download.20220713.180118.zip](https://github.com/Ensembl/ensembl-vep/files/9102141/download.20220713.180118.zip)

**Comment by olaaustine** [comment]
Hi @SowmyaPulapet,
Thank you for sharing!
Please can you share the chr_synonyms.txt file created?
Thank you.
Ola.

**Comment by SowmyaPulapet** [comment]
Hi @olaaustine 
I am attaching the chr_synonyms.txt as well. 
Thank you. 
Sowmya.
[chr_synonyms.txt](https://github.com/Ensembl/ensembl-vep/files/9108363/chr_synonyms.txt)

**Comment by SowmyaPulapet** [comment]
Hi @olaaustine 
Yes, As I had mentioned earlier in the issue I got the following warning: 

`WARNING: No exons found for protein_coding transcript LOC_Os12g01020.1.MSUv7.0`

The warnings.txt had a couple of warnings similar to this and a vcf file with only intergenic variants. The INFO field was empty. I am also sharing my results here. Hope you would be able to find me a solution.

[RS_3360_anno.zip](https://github.com/Ensembl/ensembl-vep/files/9117716/RS_3360_anno.zip)

**Comment by olaaustine** [comment]
Hi @SowmyaPulapet,
Thank you!
The gff file does not contain any exon information, thats why VEP annotates all the variants as intergenic_variant.
I suggest that you use another gff file as your annotation source. 
Thank you
Ola.

**Comment by SowmyaPulapet** [comment]
Hi @olaaustine 
Thank you for the suggestion. I tried with a gff3 containing exon information. I got the result but the .html file is about 16 mb and I am unable to open it. I assume something is not right ! Would you be able to look into this? I will share the vcf and html files here.

[RS_3360.zip](https://github.com/Ensembl/ensembl-vep/files/9121348/RS_3360.zip)

**Comment by SowmyaPulapet** [comment]
The gff3 file I used: 

[Osativa_323_v7.0.gene_exons.gff3.gz](https://github.com/Ensembl/ensembl-vep/files/9121354/Osativa_323_v7.0.gene_exons.gff3.gz)

**Comment by olaaustine** [comment]
Hi @SowmyaPulapet,
Thank you for sharing the files, I am unable to see any results in the HTML file as you stated. There is no VCF file attached, please can you send that and the command used to see if I can recreate the issue.
Also using the input VCF example you shared earlier and the new gff file and the FASTA file, i tried to recreate the issue and I can not as I can see my output in the html file. 
Thank you, 
Ola

**Comment by SowmyaPulapet** [comment]
Hi @olaaustine 
   Thank you for your follow up!  I am sharing the command and some lines of the vcf file here. 

`./vep -i ../variant_calling/var.vcf --gff Osativa_323_v7.0.gene_exons.gff3.gz --fasta Osativa_323_v7.0.transcript.fa.gz --output_file var_anno.txt --stats_file var_summary.html --synonyms chr_synonyms.txt`

```
LOC_Os10g35390.1	800	.	C	G	523.805	.	AB=0.6;ABP=6.05036;AC=1;AF=0.5;AN=2;AO=21;CIGAR=1X;DP=35;DPB=35;DPRA=0;EPP=3.1137;EPPR=3.63072;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=62.5604;PAIRED=0.571429;PAIREDR=0.571429;PAO=0;PQA=0;PQR=0;PRO=0;QA=753;QR=482;RO=14;RPL=12;RPP=3.94093;RPPR=5.49198;RPR=9;RUN=1;SAF=12;SAP=3.94093;SAR=9;SRF=11;SRP=12.937;SRR=3;TYPE=snp	GT:DP:RO:QR:AO:QA:GL	0/1:35:14:482:21:753:-57.555,0,-33.1662
LOC_Os10g35390.1	808	.	G	T	574.192	.	AB=0.628571;ABP=8.03571;AC=1;AF=0.5;AN=2;AO=22;CIGAR=1X;DP=35;DPB=35;DPRA=0;EPP=3.40511;EPPR=3.17734;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=63.0766;PAIRED=0.590909;PAIREDR=0.538462;PAO=0;PQA=0;PQR=0;PRO=0;QA=814;QR=481;RO=13;RPL=14;RPP=6.56362;RPPR=3.17734;RPR=8;RUN=1;SAF=12;SAP=3.40511;SAR=10;SRF=10;SRP=11.1951;SRR=3;TYPE=snp	GT:DP:RO:QR:AO:QA:GL	0/1:35:13:481:22:814:-63.0508,0,-33.0983
LOC_Os10g35390.1	1290	.	A	G	940.239	.	AB=0.625;ABP=11.6962;AC=1;AF=0.5;AN=2;AO=40;CIGAR=1X;DP=64;DPB=64;DPRA=0;EPP=6.48466;EPPR=5.3706;GTI=0;LEN=1;MEANALT=2;MQM=59.975;MQMR=60;NS=1;NUMALT=1;ODDS=107.936;PAIRED=0.6;PAIREDR=0.391304;PAO=0;PQA=0;PQR=0;PRO=0;QA=1454;QR=851;RO=23;RPL=0;RPP=89.8692;RPPR=44.6459;RPR=40;RUN=1;SAF=24;SAP=6.48466;SAR=16;SRF=10;SRP=3.86001;SRR=13;TYPE=snp	GT:DP:RO:QR:AO:QA:GL	0/1:64:23:851:40:1454:-112.066,0,-57.8291
LOC_Os10g35390.1	1300	.	A	G	470.631	.	AB=0.367647;ABP=13.3567;AC=1;AF=0.5;AN=2;AO=25;CIGAR=1X;DP=68;DPB=68;DPRA=0;EPP=5.18177;EPPR=4.27278;GTI=0;LEN=1;MEANALT=1;MQM=59.96;MQMR=60;NS=1;NUMALT=1;ODDS=108.367;PAIRED=0.52;PAIREDR=0.465116;PAO=0;PQA=0;PQR=0;PRO=0;QA=863;QR=1541;RO=43;RPL=2;RPP=41.3151;RPPR=72.1439;RPR=23;RUN=1;SAF=12;SAP=3.09716;SAR=13;SRF=25;SRP=5.48477;SRR=18;TYPE=snp	GT:DP:RO:QR:AO:QA:GL	0/1:68:43:1541:25:863:-57.5031,0,-118.5
LOC_Os10g35390.1	1309	.	A	G	1240.6	.	AB=0.676056;ABP=22.1254;AC=1;AF=0.5;AN=2;AO=48;CIGAR=1X;DP=71;DPB=71;DPRA=0;EPP=3.19126;EPPR=6.56362;GTI=0;LEN=1;MEANALT=2;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=90.3317;PAIRED=0.541667;PAIREDR=0.318182;PAO=0;PQA=0;PQR=0;PRO=0;QA=1764;QR=764;RO=22;RPL=7;RPP=55.3066;RPPR=12.8806;RPR=41;RUN=1;SAF=30;SAP=9.52472;SAR=18;SRF=8;SRP=6.56362;SRR=14;TYPE=snp	GT:DP:RO:QR:AO:QA:GL	0/1:71:22:764:48:1764:-137.848,0,-47.8773
LOC_Os10g35390.1	1337	.	T	A	605.941	.	AB=0.363636;ABP=15.4469;AC=1;AF=0.5;AN=2;AO=28;CIGAR=1X;DP=77;DPB=77;DPRA=0;EPP=4.25114;EPPR=3.05462;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=139.523;PAIRED=0.464286;PAIREDR=0.408163;PAO=0;PQA=0;PQR=0;PRO=0;QA=1024;QR=1801;RO=49;RPL=9;RPP=10.7656;RPPR=4.11819;RPR=19;RUN=1;SAF=21;SAP=18.2106;SAR=7;SRF=20;SRP=6.59988;SRR=29;TYPE=snp	GT:DP:RO:QR:AO:QA:GL	0/1:77:49:1801:28:1024:-69.2933,0,-139.184
LOC_Os10g35390.1	1351	.	CTTTT	TTTTT	772.816	.	AB=0.395062;ABP=10.7579;AC=1;AF=0.5;AN=2;AO=32;CIGAR=1X4M;DP=81;DPB=81.6;DPRA=0;EPP=3.28173;EPPR=5.18177;GTI=0;LEN=1;MEANALT=2;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=4.27815;PAIRED=0.5;PAIREDR=0.32;PAO=0.5;PQA=18.5;PQR=0;PRO=0;QA=1134;QR=863;RO=25;RPL=11;RPP=9.79615;RPPR=3.79203;RPR=21;RUN=1;SAF=22;SAP=12.7819;SAR=10;SRF=9;SRP=7.26639;SRR=16;TYPE=snp	GT:DP:RO:QR:AO:QA:GL	0/1:81:25:863:32:1134:-84.1862,0,-59.8709
LOC_Os10g35390.1	1369	.	T	A	1677.09	.	AB=0.709302;ABP=35.7339;AC=1;AF=0.5;AN=2;AO=61;CIGAR=1X;DP=86;DPB=86;DPRA=0;EPP=5.89373;EPPR=3.09716;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=94.8262;PAIRED=0.459016;PAIREDR=0.36;PAO=0;PQA=0;PQR=0;PRO=0;QA=2257;QR=837;RO=25;RPL=27;RPP=4.7546;RPPR=3.09716;RPR=34;RUN=1;SAF=36;SAP=7.31765;SAR=25;SRF=10;SRP=5.18177;SRR=15;TYPE=snp	GT:DP:RO:QR:AO:QA:GL	0/1:86:25:837:61:2257:-177.492,0,-49.7366
LOC_Os10g35390.1	1392	.	AG	GT	1560.76	.	AB=0.728395;ABP=39.7109;AC=1;AF=0.5;AN=2;AO=59;CIGAR=2X;DP=81;DPB=81;DPRA=0;EPP=3.93042;EPPR=4.58955;GTI=0;LEN=2;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=84.3182;PAIRED=0.440678;PAIREDR=0.363636;PAO=0;PQA=0;PQR=0;PRO=0;QA=2119;QR=776;RO=22;RPL=25;RPP=5.99147;RPPR=3.0103;RPR=34;RUN=1;SAF=37;SAP=11.2913;SAR=22;SRF=8;SRP=6.56362;SRR=14;TYPE=mnp	GT:DP:RO:QR:AO:QA:GL	0/1:81:22:776:59:2119:-166.576,0,-45.7728
```

**Comment by olaaustine** [comment]
Hi @SowmyaPulapet,
Thank you for sharing the data. I was not able to recreate the issue but i suggest that you run without the --stats_file option. VEP by default writes [statistics information](https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#output:~:text=polyphen_prediction%2C%20polyphen_score-,Statistics,-VEP%20writes%20an) to an output.
Let us know if that resolves the issue.
Thank you. 
Ola.

**Comment by SowmyaPulapet** [comment]
Hi @olaaustine 
I  had used the --stats_file option before and I have got the results perfectly. I just wanted to name the statistics file corresponding to the sample.
However, if you are not facing any error could you please share the commands used? 

Thanks in advance!

**Comment by olaaustine** [comment]
Hi @SowmyaPulapet,
This was the command used 
`./vep --input_file x.vcf --fasta Osativa_323_v7.0.transcript.fa.gz --gff Osativa_323_v7.0.gene_exons.gff3.gz --output_file var_anno.vep --synonyms chr_synonyms.txt --force_overwrite`
Thank you
Ola.

**Comment by olaaustine** [comment]
Hi @SowmyaPulapet, 
I am going to close this issue now. 
Please feel free to open another if you have a query. 
Thank you.
Ola.
