### ISSUE TITLE
vep online does not support normalized variants

### ISSUE THREAD

**Issue by asmlgkj** [Ensembl/ensembl-vep#1219]
Dear professor
I used the vep online tool to annotate variants,
when I input the normalized (chr3	37059092	37059092	-	C), it does not have a result.

but when I input the unnormalized variant (chr3	37059092	37059092	T	TC), it works,
is there any option to make it supp oert for normalized variant

**Comment by olaaustine** [comment]
Hi @asmlgkj,
Thank you for your query.
This is because the variant `-/C` does not follow the [VCF specification](https://samtools.github.io/hts-specs/VCFv4.1.pdf).

> REF - reference base(s): Each base must be one of A,C,G,T,N (case insensitive). Multiple bases are permitted.
> The value in the POS field refers to the position of the first base in the String. For simple insertions and
> deletions in which either the REF or one of the ALT alleles would otherwise be null/empty, the REF and ALT
> Strings must include the base before the event (which must be reflected in the POS field)

Please let us know if you have any other questions. 
Thank you

**Comment by asmlgkj** [comment]
thanks a lot @olaaustine 
so there has to be the vcf format?

**Comment by olaaustine** [comment]
Yes, the REF should be `.` not `-` as above.
Let us know if this fixes the problem.
Thank you, 
Ola

**Comment by asmlgkj** [comment]
thanks  a lot

**Comment by olaaustine** [comment]
I am going to close this issue, please feel free to open this if you have more questions about this or reopen another if you have another query. 
Thank you
Ola
