### ISSUE TITLE
No HGVS for Structural Variants

### ISSUE THREAD

**Issue by Addy81** [Ensembl/ensembl-vep#1222]
Hello,

I was running VEP (v105) on some CNV data and was wondering if it is meant to output HGVS notation for the CNVs or  not?

The fields are empty so making sure I haven't run it wrongly or missing anything.

My command:
```
docker run -v /home/dnanexus:/opt/vep/.vep b478f679ac19 ./vep -i /opt/vep/.vep/CEN35CNV2-CEN-F-EGG5_segments_temp.vcf -o /opt/vep/.vep/CEN35CNV2-CEN-F-EGG5_segments_temp_annotated.vcf.gz --vcf --cache --refseq --exclude_predicted --symbol --hgvs --hgvsg --check_existing --variant_class --numbers --format vcf --offline --exclude_null_alleles --assembly GRCh37 --fields Allele,SYMBOL,HGNC_ID,VARIANT_CLASS,Consequence,IMPACT,EXON,INTRON,Feature,HGVSc,HGVSp,HGVS_OFFSET,Existing_variation,STRAND,HGVSg --buffer_size 100 --fork 16 --no_stats --compress_output bgzip --shift_3prime 1

```
Example output I get:

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	CEN35CNV2-CEN-F-EGG5
X	32827580	CNV_X_32827580_32841534	N	<DUP>	452.63	.	END=32841534;CSQ=duplication|DMD||duplication|splice_polypyrimidine_tract_variant&coding_sequence_variant&intron_variant&feature_elongation|LOW|5-7/79|4-7/78|NM_000109.4|||||-1|,duplication|DMD||duplication|splice_polypyrimidine_tract_variant&coding_sequence_variant&intron_variant&feature_elongation|LOW|5-7/79|4-7/78|NM_004006.3|||||-1|,duplication|DMD||duplication|splice_polypyrimidine_tract_variant&coding_sequence_variant&intron_variant&feature_elongation|LOW|5-7/79|4-7/78|NM_004009.3|||||-1|,duplication|DMD||duplication|splice_polypyrimidine_tract_variant&coding_sequence_variant&5_prime_UTR_variant&intron_variant&feature_elongation|LOW|5-7/79|4-7/78|NM_004010.3|||||-1|	GT:CN:NP:QA:QS:QSE:QSS	./.:3:3:183:453:188:253

```

Any input would be greatly appreciated.

Many thanks,

Adriana :)

**Comment by nakib103** [comment]
Hello @Addy81 ,

Thank you for your query. There should be support for CNVs albeit limited. 

Can you share me your input file so that I can check further.

Best regards,
Nakib

**Comment by nakib103** [comment]
Hi @Addy81 

Thank you for your query. We don't actually support HGVS for SV currently. 

Hope that answers your query.

Best regards,
Nakib

**Comment by Addy81** [comment]
Thanks for the response @nakib103 !

Is it in your roadmap to support them in the future?

Many thanks,
Adriana :)

**Comment by nakib103** [comment]
Yes, we do have plan to support them in the future. I cannot comment on the exact timeline right now, but we will let you know once the feature is available.

Best regards,
Nakib

**Comment by davmlaw** [comment]
Hi, could I suggest renaming this issue to something like "No HGVS for symbolic alts" (or Structural Variants) etc?

Was trying to find it, and it wasn't obvious this was the issue. Thanks

**Comment by nakib103** [comment]
Hello,

We are not prioritising to add any new features to the current implementation of HGVS. Instead, we are looking to improve these cases in our future implementation of VEP.

Best regards,
Nakib
