### ISSUE TITLE
conda installation - install older version and not the current

### ISSUE THREAD

**Issue by unitsmanolis** [Ensembl/ensembl-vep#1223]
## Describe the issue
Hi, when I try to install VEP using conda 

conda install -c bioconda ensembl-vep

it came out 

Versions:
  ensembl              : 105.f357e33
  ensembl-funcgen      : 105.660df8f
  ensembl-io           : 105.2a0a40c
  ensembl-variation    : 105.ac8178e
  ensembl-vep          : 105.0

How can I install VEP with conda?

**Comment by nakib103** [comment]
Hello @unitsmanolis ,

Unfortunately, I could not understand the query properly. 

Did your conda installation failed? What is the exact error message that you received?

Please provide me with some more details.

Best regards,
Nakib

**Comment by unitsmanolis** [comment]
Hi @nakib103 

everything fixed. In the conda site says that with the command

`conda install -c bioconda ensembl-vep`

should install vep-107 but it was installing the v105 ... I tried to specify the version like

`conda install -c bioconda ensembl-vep=107`

but it gives me dependencies problems.

I solved it adding in the code also the build version.

Thanks for you time.
"unitsmanolis"
