### ISSUE TITLE
a plugin for cosmic

### ISSUE THREAD

**Issue by asmlgkj** [Ensembl/ensembl-vep#1224]
cosmic has a file called CosmicMutantExport.tsv.  it has many columns that not exists in the vcf supplied by cosmic

Gene name       Accession Number        Gene CDS length HGNC ID Sample name     ID_sample       ID_tumour       Primary site    Site subtype 1  Site subtype 2  Site subtype 3  Primary histology
       Histology subtype 1     Histology subtype 2     Histology subtype 3     Genome-wide screen      GENOMIC_MUTATION_ID     LEGACY_MUTATION_ID      MUTATION_ID     Mutation CDS    Mutation AA
     Mutation Description    Mutation zygosity       LOH     GRCh    Mutation genome position        Mutation strand SNP     Resistance Mutation     FATHMM prediction       FATHMM score    Mutation somatic status Pubmed_PMID     ID_STUDY        Sample Type     Tumour origin   Age     HGVSP   HGVSC   HGVSG
UNC79_ENST00000555664   ENST00000555664.1       7791    19966   GCTK_532_T      2747556 2606259 stomach NS      NS      NS      carcinoma       NS      NS      NS      y       COSV56381555    COSN13602101    86251835        c.3032+118G>A   p.?     Unknown                 37      14:94053372-94053372    +       n       -       NEUTRAL .00125  Confirmed somatic variant               683     NS      primary                 ENST00000555664.1:c.3032+118G>A 14:g.94053372G>A
PRMT3_ENST00000437750   ENST00000437750.2       1410    30163   GCTK_532_T      2747556 2606259 stomach NS      NS      NS      carcinoma       NS      NS      NS      y       COSV100423976   COSN30620201    55859481        c.586-130G>A    p.?     Unknown                 37      11:20429327-20429327    +       n       -       NEUTRAL .00128  Confirmed somatic variant               683     NS      primary                 ENST00000437750.2:c.586-130G>A  11:g.20429327G>A
ANO7_ENST00000402430    ENST00000402430.3       2652    31677   GCTK_532_T      2747556 2606259 stomach NS      NS      NS      carcinoma       NS      NS      NS      y       COSV51480223    COSM4766778     46195809        c.388C>T        p.R130W Substitution - Missense                 37      2:242135180-242135180   +       n       -       NEUTRAL .04035  Confirmed somatic variant  

will you plan to write such a plguin that can extract specific column with the result of vep anno

thanks a lot

**Comment by asmlgkj** [comment]
thanks a lot, because the information of cosmic vcf is too brief, most information recorded in the tsv file

**Comment by nakib103** [comment]
Hello @asmlgkj,

Thanks for your query and bringing our attention to this. We are looking into this and plan to talk to COSMIC team about possible implementation. 

We will let you know if there is any updates.

Best regards,
Nakib

**Comment by asmlgkj** [comment]
@nakib103   thanks  a lot

**Comment by nakib103** [comment]
Hello @asmlgkj,

This issue has been quite old. The priority of creating a COSMIC plugin has been quite low partially and we do not have any plan in near future to add it.

If you have COSMIC data available you can still try to do annotation with VEP using [custom annotation](https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html).

I will be going to close this ticket. If you have any further queries feel free to open a new one.

Best regards,
Nakib
