### ISSUE TITLE
Releases 53 and 54 of Ensembl Genomes Bacterial Cache Files Giving Error 403

### ISSUE THREAD

**Issue by chrisAta** [Ensembl/ensembl-vep#1226]
Hello,

I am trying to run the VEP on a set of bacterial VCF files. I attempted to manually download the cache for my species of interest (_Bacillus subtilis 168_ ) using the instructions found [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache).  However, when clicking on the FTP directory for [Bacteria](http://ftp.ebi.ac.uk/ensemblgenomes/pub/bacteria/current/variation/vep/), I get "Error 403: Forbidden". 

I did a bit of digging, and it seems to be a problem for both releases 53 and 54 (which is the current release as of today). The link to release 52 works fine for example: http://ftp.ebi.ac.uk/ensemblgenomes/pub/bacteria/release-52/variation/vep/

I don't know if it's because the cache files have not been produced for releases 53 and 54 or if they're missing, but thought I'd report it as I will need to use release 52 instead for now.

Thanks!

**Comment by nakib103** [comment]
Hi @chrisAta,

There was an issue with the download links which is fixed now. Can you try and see if the download works now.

Best regards,
Nakib

**Comment by chrisAta** [comment]
Hello @nakib103! I've just tried it and it's sorted now, thanks for the quick fix!
