### ISSUE TITLE
MSG: Can not find internal name for species 'homo_sapiens'

### ISSUE THREAD

**Issue by marianakhoul** [Ensembl/ensembl-vep#1227]
## Describe the issue
Hello! I installed a local instance of the VEP database on my server. I am passing secure data which is why I can't use the public Ensembl API. I want to pass the hgvs annotation and return a VCF File for the data with the reference and alternate alleles, chromosome and position. I want to pass the RefSeq transcript ID and the CDS Change to get this information as the public API is able to do. I get the following error: MSG: Can not find internal name for species 'homo_sapiens'. 
I followed the steps here to install and load the data: https://useast.ensembl.org/info/docs/webcode/mirror/install/ensembl-data.html
I am using homo_sapiens_core_99_37 DB locally.

### System
- VEP version: [e.g. 99] 
- VEP Cache version: [e.g. 99]
- Perl version: [e.g. 5.26.2]
- OS: [CentOS 7]
- tabix installed? Yes

### Full VEP command line
```
./vep -i input.txt -o output.txt  --database  --host XXX.XX.XXX.XXX  --port 3306 -u root --password XXXX --hgvs
```

### Full error message

-------------------- WARNING ----------------------
MSG: homo_sapiens is not a valid species name (check DB and API version)
FILE: Bio/EnsEMBL/Registry.pm LINE: 1334
CALLED BY: Bio/EnsEMBL/Registry.pm  LINE: 1109
Date (localtime)    = Thu Jul 28 13:57:40 2022
Ensembl API version = 99
---------------------------------------------------

-------------------- EXCEPTION --------------------
MSG: Can not find internal name for species 'homo_sapiens'
STACK Bio::EnsEMBL::Registry::get_adaptor /apps/ensembl-vep/Bio/EnsEMBL/Registry.pm:1111
STACK Bio::EnsEMBL::VEP::BaseVEP::get_adaptor /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:307
STACK Bio::EnsEMBL::VEP::BaseVEP::get_database_assembly /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:419
STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::init /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:118
STACK Bio::EnsEMBL::VEP::Runner::run /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel ./vep:224
Date (localtime)    = Thu Jul 28 13:57:40 2022
Ensembl API version = 99

### Data files (if applicable)
input.txt has 1 line which is: NM_080794.3:c.1001C>T

**Comment by nuno-agostinho** [comment]
Hey @marianakhoul, thanks for opening this issue.

Reading the documentation on that page, it seems that it doesn't mention the variation database. Have you installed `homo_sapiens_variation_99_37`? This database is required for VEP to run.

Kind regards,
Nuno

**Comment by nuno-agostinho** [comment]
Hey @marianakhoul,

I just want to add that you can also run VEP in offline mode with cache. You can read instructions at https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache.

This solution should be easier to use, but tell me if it's not appropriate.

Best,
Nuno

**Comment by marianakhoul** [comment]
HI @nuno-agostinho,

I am having some issues loading the homo_sapiens_variantion_99_37 db. Working with our DevOps team to resolve the space issue and hopefully get back to you about if loading it worked.

As for the cache files, I tried that previously before setting up a local instance of the DB. When the input file is in hgvs format, we can't use cache files or run ver in offline mode. Is there a recent fix to this?

thank you,
Maria Nakhoul

**Comment by nuno-agostinho** [comment]
Hey @marianakhoul,

> I am having some issues loading the homo_sapiens_variantion_99_37 db. Working with our DevOps team to resolve the space issue and hopefully get back to you about if loading it worked.

All right, I hope that you can make it work soon!

> As for the cache files, I tried that previously before setting up a local instance of the DB. When the input file is in hgvs format, we can't use cache files or run ver in offline mode. Is there a recent fix to this?

No, VEP 107 and earlier still cannot accept HGVS in offline mode (we do have plans to change this in the future, but we didn't start working on this yet). In the meantime, you can convert the HGVS symbols using [the online version of Variant Recoder](https://www.ensembl.org/Homo_sapiens/Tools/VR) and output a VCF that you can then use as input for VEP in offline mode with cache.

Hope this can help.

Cheers,
Nuno

**Comment by nuno-agostinho** [comment]
Hey @marianakhoul,

Just to rectify something I said before, you **do not** need to locally install the variation database just to get VEP to use HGVS annotation (as it is a really big database, this may be impractical).

You can instead locally install the `core` and `otherfeatures` databases (`otherfeatures` contains RefSeq information required for your specific case) and VEP can convert HGVS on-demand.

If you have access to rsIDs, you can also locally convert them using the VEP plugin https://github.com/Ensembl/VEP_plugins/blob/release/107/LocalID.pm.

Sorry for the confusion.

Best,
Nuno

**Comment by marianakhoul** [comment]
Hi @nuno-agostinho,

thanks for letting me know! I downloaded other features and loaded the DB. I am still getting the same error. This is the command I am using:

./vep -i input.txt -o output.txt  --database  --host XXX.XX.XXX.XXX  --port 3306 -u root --password XXXX --hgvs --fasta /apps/Homo_sapiens_assembly19.fasta --dir /apps/vep --dir_cache /apps/vep --force_overwrite --refseq

thank you,
Maria Nakhoul

**Comment by marianakhoul** [comment]
hi @nuno-agostinho ,

any updates?

**Comment by nuno-agostinho** [comment]
Hi @marianakhoul, sorry for the delay in replying back. Have you had any progress with this? Are you still getting the same error?

**Comment by nuno-agostinho** [comment]
Hey @marianakhoul,

Given that I didn't get a reply so far, I will close this issue for now.

Feel free to reopen it if you would like to discuss this issue further.

Best regards,
Nuno
