### ISSUE TITLE
UTRannotator Plugin Issue

### ISSUE THREAD

**Issue by mmccorkindale** [Ensembl/ensembl-vep#1229]
### Describe the issue
Hi,

I've recently updated to release 107 in an attempt to fix an issue I was having with the UTRannotator plugin. It might be fairly basic, but I have double checked and I'm still getting the same warning. 

Basically, it's telling me there is "No such file or directory" for the UTRannotator.pm Plugin, but I have listed the contents of the Plugins directory immediately prior to the VEP command line in my script to check this, and it is present in the required folder. Additionally, my other two plugins (dbNSFP and CADD) both run successfully from the same folder, so I'm not sure what the issue is.

VEP still runs successfully, but without the UTRannotator fields included in the output. I didn't know if this would be a VEP or a UTRannotator issue, but I figured I would post it here first, since I'm guessing the warning message is VEP's.

### System
- VEP version: 107
- VEP Cache version: 107
- Perl version: 5.26
- OS: CentOS 7
- tabix installed ?

### Full VEP command line
```
${PATHF_VEP}/vep -v \
 --cache \
 --tab \
 --fork 4 \
 --offline \
 --merged \
 --dir_plugins ${tmpdir}/cache/Plugins/ \
 --dir_cache ${tmpdir}/cache/ \
 --plugin dbNSFP,${tmpdir}/${DBNSFP_PLUGIN},Polyphen2_HVAR_pred,CADD_raw,CADD_raw_rankscore,CADD_phred,SIFT_pred,FATHMM_pred,MutationTaster_pred,MetaSVM_pred,GERP++_NR,GERP++_RS,GERP++_RS_rankscore,phyloP100way_vertebrate,phastCons100way_vertebrate,SiPhy_29way_pi,SiPhy_29way_logOdds \
 --plugin CADD,${tmpdir}/${CADD_PLUGIN},${tmpdir}/${CADD_INDEL_PLUGIN} \
 --plugin UTRannotator,${tmpdir}/${ORF_FILE} \
 --fasta ${FASTA} \
 --assembly ${REF_BUILD} \
 --everything \
 --force_overwrite \
 --individual all --format vcf --use_transcript_ref --keep_csq \
 -i ${tmpdir}/input.vcf \
 -o ${tmpdir}/${D_PROJECT}_hiConf_annotated_variants.txt
```

### Full error message
WARNING: Failed to instantiate plugin UTRannotator: No such file or directory at /scratch/nmm213/26977720/cache/Plugins/UTRannotator.pm line 54.

This is the result of `ls /scratch/nmm213/26977720/cache/Plugins/`:
CADD.pm
_config.yml
dbNSFP.pm
ExACpLI.pm
ExAC.pm
GO.pm
LICENSE
LoF.pm
plugin_config.txt
README.md
src
Supplementary_Information.pdf
test
uORF_5UTR_GRCh37_PUBLIC.txt
uORF_5UTR_GRCh38_PUBLIC.txt
UTRannotator
UTRannotator.pm

**Comment by diegomscoelho** [comment]
Glad to hear @mmccorkindale, 

Anything else related to `UTRannotator` feel free to reopen this issue or open a new one.

Best, @diegomscoelho
