### ISSUE TITLE
gene annotation discrepancy between two annotators with same in variant position

### ISSUE THREAD

**Issue by cmccabe0728** [Ensembl/ensembl-vep#1233]
In the below the same variant is annotated by vep (line 1) and another (line2) and the results are different. The same gene and transcript is being  used in both, but protein, c., and consequence seem to be different. Thank you :).

    vep --cache --dir_cache path/to/ --cache_version 106 --refseq --offline --fasta path/to --hgvs --symbol -i ${vcf_file} --vcf -o vep.vcf --force_overwrite --exclude_predicted --distance 1000 -plugin path/to/UTRannotator

    chr1	1013466	.	T	TA	 
    upstream_gene_variant|MODIFIER|ISG15|9636|Transcript|NM_005101.4|protein_coding|||||||||||30|1||EntrezGene|||||||

    1	1013466	T	TA	ISG15 ubiquitin-like modifier	NM_005101.3	1	667	498	NP_005092.1	P05161	duplication	 
    c.-107dup	5'UTR

**Comment by diegomscoelho** [comment]
Hi @cmccabe0728,

I didn't understand what you mean by "another (line 2)" (is this a totally different annotator?) and what is your question?
Can you post here:
1) VEP version are you using;
2) If you used VEP in both cases, vep command-line in both cases;
3) Your input example;

Best, Diego

**Comment by cmccabe0728** [comment]
Hi @diegomscoelho,

I am using vep106 to with the command above annotate (vcf) and the second line in the above post is from a different annotator.

[vcf.txt](https://github.com/Ensembl/ensembl-vep/files/9293404/vcf.txt)

Thanks.

**Comment by diegomscoelho** [comment]
Hi @cmccabe0728,

Although annotators agree in most variants results, it's normal to have different results sometimes due to each software logic.

If you have any other question or a more specific about your results, please feel free to post here.

Best, @diegomscoelho

**Comment by cmccabe0728** [comment]
Below is the vep output for that variant position. T have added numerous plugins to the command above (--plugin Downstream,UTRannotator,NearestExonJB,NearestGene,TSSDistance).... the distance is -109 accordioning to the other annotator, but vep doesn't seem to calculate this with the --distance option and the plugins. Is there something else needed? Thank you.


**vep output**
    |upstream_gene_variant|MODIFIER|ISG15|9636|Transcript|NM_005101.4|protein_coding|||||||||||30|1||EntrezGene|||||||

**Comment by diegomscoelho** [comment]
Hi there,

I will close this issue since same question was answered in another issue (https://github.com/Ensembl/ensembl-vep/issues/1242). I will update new one with some information.

Regards, @diegomscoelho
