### ISSUE TITLE
filter_vep compare custom annotation

### ISSUE THREAD

**Issue by rsalz** [Ensembl/ensembl-vep#1240]
I have a vcf annotated with both cache (reference) and custom annotation sources. For variants that are missense in both the cache and the custom annotation source, I would like to see which ones have a different amino acid substitution when using the custom annotation versus those when using the cache. Is there a clean way to do this with filter_vep?

Additional information: I have a string identifier that can separate the custom sequences from those of the cache.

**Comment by likhitha-surapaneni** [comment]
Hi @rsalz , thank you for reaching out.

The documentation for filter_vep is available [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html). 

Could you please share an example VCF file and the filter output that you would expect?

Kind regards,
Likhitha

**Comment by rsalz** [comment]
The documentation does not cover situations where you want to compare within annotation of a variant.

Here is a toy example with 2 variants including their annotations:

`
1       1787378 224718  C       T       .       .ALLELEID=904889;CLNDISDB=Human_Phenotyp
e_Ontology:HP:0002575,MONDO:MONDO:0008586,MedGen:C0040588,OMIM:189960,Orphanet:ORPHA1199;CLNDN=
Tracheoesophageal_fistula;CLNHGVS=NC_000001.11:g.964512C>A;CLNREVSTAT=no_assertion_criteria_pro
vided;CLNSIG=Likely_pathogenic;CLNVC=single_nucleotide_variant;CLNVCSO=SO:0001483;GENEINFO=KLHL
17:339451;MC=SO:0001583|missense_variant;ORIGIN=32;RS=756054473;CSQ=T
|missense_variant|MODERATE|GNB1|ENSG00000078369.17|Transcript|NOVELT000256040_ORF_1|protein_coding|4/5||||546|415|139|A/T|Gct/Act|rs869312826||-1|||||novel_complete.gff.gz||C|C||||||likely_pathogenic&pathogenic||1|,T|missense_variant|MODERATE|GNB1|ENSG00000078369.17|Transcript|NOVELT000256047_ORF_1|protein_coding|9/10||||1077|976|326|A/T|Gct/Act|rs869312826||-1|||||novel_complete.gff.gz||C|C||||||likely_pathogenic&pathogenic||1|,T|missense_variant|MODERATE|GNB1|ENSG00000078369.17|Transcript|NOVELT000256054_ORF_1|protein_coding|7/8||||880|844|282|A/R|gCt/gAt|rs869312826||-1|||||novel_complete.gff.gz||C|C||||||likely_pathogenic&pathogenic||1|

1       1789242 995963  T       C       .       .       ALLELEID=983663;CLNDISDB=MONDO:MONDO:0014855,MedGen:C4310774,OMIM:616973;CLNDN=Intellectual_disability,_autosomal_dominant_42;CLNHGVS=NC_000001.11:g.1789242T>C;CLNREVSTAT=no_assertion_criteria_provided;CLNSIG=Pathogenic;CLNVC=single_nucleotide_variant;CLNVCSO=SO:0001483;GENEINFO=GNB1:2782;MC=SO:0001583|missense_variant;ORIGIN=1;RS=1394767075;CSQ=C|missense_variant|MODERATE|GNB1|ENSG00000078369|Transcript|ENST00000615252|protein_coding|8/10||||974|427|143|T/A|Act/Gct|rs1394767075||-1||HGNC|HGNC:4396||Ensembl||T|T||deleterious(0)|possibly_damaging(0.788)|3.525e-05|gnomAD_NFE||||,C|missense_variant|MODERATE|GNB1|2782|Transcript|NM_001282538.2|protein_coding|8/10||||944|427|143|T/A|Act/Gct|rs1394767075||-1||EntrezGene|HGNC:4396||RefSeq||T|T||deleterious(0)|possibly_damaging(0.788)|3.525e-05|gnomAD_NFE||||,C|missense_variant|MODERATE|GNB1|ENSG00000078369.17|Transcript|NOVELT000256054_ORF_1|protein_coding|6/8||||631|595|199|T/A|Act/Gct|rs1394767075||-1|||||novel_complete.gff.gz||T|T||||3.525e-05|gnomAD_NFE||||`

I would like a simple filter that removes the second variant, since the amino acid substitution is the same in all cases (T/A). In the first variant, there is 1 different amino acid substitution in my custom annotation (A/R instead of A/T in the reference annotation).

**Comment by likhitha-surapaneni** [comment]
Hi @rsalz , unfortunately this is not in our immediate priorities. I am closing this ticket for now. Please feel free to open a new issue in case you have any other questions.

Thanks and regards,
Likhitha
