### ISSUE TITLE
GeneSplicer Warning

### ISSUE THREAD

**Issue by Z-Zen** [Ensembl/ensembl-vep#1241]
## Describe the issue
Sometimes, running VEP with the plugin [GeneSplicer](https://github.com/Ensembl/VEP_plugins/blob/release/106/GeneSplicer.pm) will generate the following warning:

```
WARNING: 74 : readline() on closed filehandle RES at /opt/vep/.vep/Plugins/GeneSplicer.pm line 287.
```

### System
- VEP version: 106
- VEP Cache version: 106
- Perl version: v5.26.1
- OS:  Ubuntu
- tabix installed ? Yes

### Full VEP command line
```bash
vep --dir /dev/shm/ \
  --dir_plugins /opt/vep/.vep/Plugins/ \
  -i "ERR194147_SNP_polyx.chr9.vcf" \
  -o "ERR194147_SNP_annotated_chr9.vcf" \
  --refseq --everything --humdiv --no_escape --no_stats \
  --buffer_size 50 \
  --exclude_predicted \
  --fork 5 \
  --force --cache \
  --offline --assembly GRCh38 \
  --fasta /dev/shm/reference/bwa2/GCF_000001405.40_GRCh38.p14_genomic_primary_assembly.fa \
  --plugin dbNSFP,/dev/shm/dbNSFP/dbNSFP4.3a/dbNSFP4.3a_grch38.gz,Polyphen2_HDIV_rankscore,Polyphen2_HVAR_rankscore,SIFT_converted_rankscore,SIFT4G_converted_rankscore,LRT_converted_rankscore,MutationTaster_converted_rankscore,MutationTaster_score,MutationAssessor_rankscore,FATHMM_converted_rankscore,PROVEAN_converted_rankscore,VEST4_rankscore,MetaSVM_score,phyloP17way_primate,ESP6500_AA_AF,ESP6500_EA_AF,ExAC_AC,ExAC_AFR_AF,ExAC_NFE_AF,ExAC_AMR_AF,ExAC_EAS_AF,ExAC_SAS_AF,Ancestral_allele,gnomAD_exomes_AC,gnomAD_exomes_AN,gnomAD_exomes_AF \
  --plugin dbscSNV,/dev/shm/dbscSNV/dbscSNV1.1/dbscSNV1.1_GRCh38.txt.gz \
  --plugin GeneSplicer,/dev/shm/genesplicer/sources/genesplicer,/dev/shm/genesplicer/human,tmpdir=/dev/shm/ \
  --plugin MaxEntScan,/dev/shm/MaxEntScan \
  --plugin SpliceRegion \
  --plugin CADD,/dev/shm/CADD/GRCh38_v1.6/whole_genome_SNVs.tsv.gz,/dev/shm/CADD/GRCh38_v1.6/gnomad.genomes.r3.0.indel.tsv.gz \
  --plugin REVEL,/dev/shm/REVEL/new_tabbed_revel.tsv.gz \
  --plugin Blosum62 \
  --plugin Conservation,/dev/shm/Conservation/gerp_conservation_scores.homo_sapiens.GRCh38.bw \
  --plugin Downstream \
  --vcf --use_given_ref
```

### Data files

[ERR194147_SNP_polyx.chr9.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/9308930/ERR194147_SNP_polyx.chr9.vcf.gz)

**Comment by likhitha-surapaneni** [comment]
Hi @Z-Zen ,

Unfortunately, we are not able to replicate this issue on our end. Could you provide us with any other details regarding when this warning occurs, does it occur every time you try to run GeneSplicer plugin with the input file provided?

Thanks and regards,
Likhitha

**Comment by Z-Zen** [comment]
Hi @likhitha-surapaneni

Thank you for trying to replicate the issue.

In our case, we launch vep to annotate multiple samples on our Slurm cluster with 7 slaves. Each sample has its mutations divided by the number of chromosomes. And for GeneSplicer, we have defined `tmpdir` to `/dev/shm` in the RAM to speed up the annotation.

Could it be because different samples are being annotated on the same slave and all are writing the GeneSplicer temporary files to `/dev/shm`?

**Comment by likhitha-surapaneni** [comment]
Hi @Z-Zen , I hope the issue got resolved. Please feel free to open a new ticket if you have any further queries.

Thanks and regards,
Likhitha
