### ISSUE TITLE
vep plugin syntax error

### ISSUE THREAD

**Issue by cmccabe0728** [Ensembl/ensembl-vep#1242]
I am running vep 106 in docker on aws. In the below the --plugin seems to produce an error, but the ec2-user is the default location and cannot be changed. It seems like the - is causing an issue but /-/ doesn't seem to be the escape sequence. Thank you.

    --plugin /home/ec2-user/vep-plugin/UTRannotator
 
     WARNING: Failed to compile plugin /home/ec2-user/vep-plugin/UTRannotator: Unknown regexp modifier "/e" at (eval 40) line 
      2, at end of line
      Unknown regexp modifier "/2" at (eval 40) line 2, at end of line
       syntax error at (eval 40) line 2, near "use /home/ec2"

**Comment by olaaustine** [comment]
Hi @cmccabe0728,
Thank you for your query. 
Please can you share your full CLI command?
Thank you 
Ola

**Comment by cmccabe0728** [comment]
vep does run and annotate the vcf, however the --plugin does not compile because of the error above.

     ./vep --cache --dir_cache /home/ec2-user/vep-resources/ --cache_version 106 --refseq --offline --fasta /home/ec2- 
     user/vep-resources/fastq/106_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz \
     --hgvs --symbol -i ${vcf_file} --vcf -o ${sample}_vep_output.vcf --force_overwrite --exclude_predicted --distance 5000,5000 \
     --plugin /home/ec2-user/vep-plugin/UTRannotator,/home/ec2-user/vep-plugin/Downstream,/home/ec2-user/vep- 
      plugin/NearestExonJB,/home/ec2-user/vep-plugin/NearestGene,/home/ec2-user/vep-plugin/TSSDistance

**Comment by olaaustine** [comment]
Hi @cmccabe0728,
To use multiple plugins, you have to call the --[plugin](http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#:~:text=Output%20fields-,%2D%2Dplugin,-%5Bplugin%20name%5D) option multiple times.
Let us know if this solves the issue.
Thank you 
Ola.

**Comment by cmccabe0728** [comment]
I modified the command and all the plugins execute, however the distance is not shown for the upstream and downstream variants. The --distance is set for both as well. Is there something else needed? Below is a specific example that is -107bp:

Thank you.

     chr1	1013466	.	T	TA	9571.03	PASS,PASS	|upstream_gene_variant|MODIFIER|ISG15|9636|Transcript|NM_005101.4|protein_coding|||||||||||30|1||EntrezGene|||||||||||31

**Comment by olaaustine** [comment]
Hi @cmccabe0728,
The  --distance option see [VEP Output options](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#output) is used to modify how VEP annotates the genes within a 5000bp upstream and downstream of the variant, the distance by default is 5000.
And according to the example just shared, it shows distance as 30 which [is the shortest distance from the variant to the transcript](https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#output:~:text=DISTANCE%20%2D%20Shortest%20distance%20from%20variant%20to%20transcript)
Is there a different output you expect ?
Thank you 
Ola

**Comment by cmccabe0728** [comment]
I expected the distance to be -107 so was looking for that.... the transcripts do match, but the distance is different. Thank you.

    chr1:1013466     rs3841266    | T → TAc.-107dup

**Comment by olaaustine** [comment]
Hi @cmccabe0728,
Considering you are comparing the results between two annotators, can you confirm the distance used in the other annotator ? 
Also from your previous message here in #1233, it shows that two different version of the  NCBI reference sequence was used by VEP and the other  (NM_005101.4 and NM_005101.3).
Thank you 
Ola.

**Comment by cmccabe0728** [comment]
-107 is the distance of the other annotator, but it may be the version of the transcript as you mentioned. Thank you.

**Comment by olaaustine** [comment]
Hi @cmccabe0728,
I will close this now, feel free to open another or reopen this if you have any more queries.
Thank you 
Ola
