### ISSUE TITLE
--check_ref sometimes reports failed ref in 107

### ISSUE THREAD

**Issue by jvolanen** [Ensembl/ensembl-vep#1243]
VEP version 107 complains about failed ref for some variants ( < 4%) although the variants are OK. VEP version 106 does not have this problem. Normally we do not use `--dont_skip` parameter, so the effect in our pipeline is that some variants do not get any annotations.

INPUT
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT
11      108366029       91860879        CAA     C       .       PASS            .
```

VEP 107
command line:
`docker run -v /tmp:/tmp  --rm ensemblorg/ensembl-vep:release_107.0 vep  --assembly GRCh38 --input_file /tmp/failed_ref.vcf --format vcf --database  --output_file stdout --no_stats --check_ref --dont_skip`

Result
```
#Uploaded_variation     Location        Allele  Gene    Feature Feature_type    Consequence     cDNA_position   CDS_position    Protein_position        Amino_acids     Codons  Existing_variation      Extra
91860879        11:108366030-108366031  -       ENSG00000149311 ENST00000278616 Transcript      3_prime_UTR_variant,NMD_transcript_variant      9999-10000      -       -       -       -       -       IMPACT=MODIFIER;STRAND=1;CHECK_REF=failed
...
```

VEP 106
command line:
`docker run -v /tmp:/tmp  --rm ensemblorg/ensembl-vep:release_106.0 vep  --assembly GRCh38 --input_file /tmp/failed_ref.vcf --format vcf --database  --output_file stdout --no_stats --check_ref --dont_skip
`
Result:
```
#Uploaded_variation     Location        Allele  Gene    Feature Feature_type    Consequence     cDNA_position   CDS_position    Protein_position        Amino_acids     Codons  Existing_variation      Extra
91860879        11:108366030-108366031  -       ENSG00000149311 ENST00000278616 Transcript      3_prime_UTR_variant,NMD_transcript_variant      9999-10000      -       -       -       -       -       IMPACT=MODIFIER;STRAND=1

```

**Comment by olaaustine** [comment]
Hi @jvolanen,
Thank you for bringing this to our notice. 
We have fixed this issue. You can pull from our release 107 for the fix applied.
I will close this now, please feel free to reopen or open another ticket it if you have another query.
Thank you.
Ola.
