### ISSUE TITLE
SIFT not available

### ISSUE THREAD

**Issue by madhuripulijala** [Ensembl/ensembl-vep#1247]
Hello,
I recently installed vep and no errors while installation. However, I am facing an error message when I test the vep installation (https://asia.ensembl.org/info/docs/tools/vep/script/vep_tutorial.html). 
Please find below the error message:

./vep -i examples/homo_sapiens_GRCh38.vcf --cache --force_overwrite --sift b

-------------------- EXCEPTION --------------------
MSG: ERROR: SIFT not available

STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::check_sift_polyphen /home/madhu/ensembl/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:168
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::new /home/madhu/ensembl/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:121
STACK Bio::EnsEMBL::VEP::CacheDir::get_all_AnnotationSources /home/madhu/ensembl/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:150
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /home/madhu/ensembl/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:122
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/madhu/ensembl/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:92
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/madhu/ensembl/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /home/madhu/ensembl/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::run /home/madhu/ensembl/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel ./vep:238
Date (localtime)    = Mon Aug 29 19:04:09 2022
Ensembl API version = 107
---------------------------------------------------

**Comment by likhitha-surapaneni** [comment]
Hi @madhuripulijala ,

Sorry to hear that you're facing an issue while running VEP. Could you please look into `info.txt` file in the installed cache directory and check if you have sift related information in the file?

Kind regards,
Likhitha

**Comment by madhuripulijala** [comment]
Hi @likhitha-surapaneni ,
Thank you for your reply. I did look into the "info.txt" file in the cache directory. It does seem to have sift information. Please find below the info

assembly        GRCh38
bam     GCF_000001405.39_GRCh38.p13_knownrefseq_alns.bam
polyphen        b
sift    b
source_assembly GRCh38.p13
source_gencode  GENCODE 41
source_genebuild        2014-07
source_polyphen 2.2.2
source_refseq   109.20211119 - GCF_000001405.39_GRCh38.p13_genomic.gff
source_sift     sift5.2.2
species homo_sapiens
variation_cols  chr,variation_name,failed,somatic,start,end,allele_string,strand,clin_sig,phenotype_or_disease,clin_sig_allele,pubmed,var_synonyms,AF,AFR,AMR,EAS,EUR,SAS,gnomADe,gnomADe_AFR,gnomADe_AMR,gnomADe_ASJ,gnomADe_EAS,gnomADe_FIN,gnomADe_NFE,gnomADe_OTH,gnomADe_SAS,gnomADg,gnomADg_AFR,gnomADg_AMI,gnomADg_AMR,gnomADg_ASJ,gnomADg_EAS,gnomADg_FIN,gnomADg_MID,gnomADg_NFE,gnomADg_OTH,gnomADg_SAS
source_COSMIC   95
source_HGMD-PUBLIC      20204
source_ClinVar  202201
source_dbSNP    154
source_1000genomes      phase3
source_gnomADe  r2.1.1
source_gnomADg  v3.1.2
var_type        tabix
regulatory      1
cell_types      A549,A673,B,B_(PB),CD14+_monocyte_(PB),CD14+_monocyte_1,CD4+_CD25+_ab_Treg_(PB),CD4+_ab_T,CD4+_ab_T_(PB)_1,CD4+_ab_T_(PB)_2,CD4+_ab_T_(Th),CD4+_ab_T_(VB),CD8+_ab_T_(CB),CD8+_ab_T_(PB),CMP_CD4+_1,CMP_CD4+_2,CMP_CD4+_3,CM_CD4+_ab_T_(VB),DND-41,EB_(CB),EM_CD4+_ab_T_(PB),EM_CD8+_ab_T_(VB),EPC_(VB),GM12878,H1-hESC_2,H1-hESC_3,H9_1,HCT116,HSMM,HUES48,HUES6,HUES64,HUVEC,HUVEC-prol_(CB),HeLa-S3,HepG2,K562,M0_(CB),M0_(VB),M1_(CB),M1_(VB),M2_(CB),M2_(VB),MCF-7,MM.1S,MSC,MSC_(VB),NHLF,NK_(PB),NPC_1,NPC_2,NPC_3,PC-3,PC-9,SK-N.,T_(PB),Th17,UCSF-4,adrenal_gland,aorta,astrocyte,bipolar_neuron,brain_1,cardiac_muscle,dermal_fibroblast,endodermal,eosinophil_(VB),esophagus,foreskin_fibroblast_2,foreskin_keratinocyte_1,foreskin_keratinocyte_2,foreskin_melanocyte_1,foreskin_melanocyte_2,germinal_matrix,heart,hepatocyte,iPS-15b,iPS-20b,iPS_DF_19.11,iPS_DF_6.9,keratinocyte,kidney,large_intestine,left_ventricle,leg_muscle,lung_1,lung_2,mammary_epithelial_1,mammary_epithelial_2,mammary_myoepithelial,monocyte_(CB),monocyte_(VB),mononuclear_(PB),myotube,naive_B_(VB),neuron,neurosphere_(C),neurosphere_(GE),neutro_myelocyte,neutrophil_(CB),neutrophil_(VB),osteoblast,ovary,pancreas,placenta,psoas_muscle,right_atrium,right_ventricle,sigmoid_colon,small_intestine_1,small_intestine_2,spleen,stomach_1,stomach_2,thymus_1,thymus_2,trophoblast,trunk_muscle
source_regbuild 1.0

**Comment by likhitha-surapaneni** [comment]
Hi @madhuripulijala , thank you for the details provided.

Could you please check if you are able to run using  `--database` option  instead of `--cache`? If it is working as expected, there may be an issue with the downloaded cache and you may want to re-download it following the docs: https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#pre
