### ISSUE TITLE
Reannotation can lead to an  inconsistent INFO block

### ISSUE THREAD

**Issue by segoerge** [Ensembl/ensembl-vep#125]
Hi again,

I have the following situation. If I annotate an ANN field with VEP, followed by another tool that does some further INFO field annotations and then reannotate with, for example, a newer version of VEP, the old ANN field is erased, what is in principle a good thing.

The problem is that the old ANN field is not deleted correctly, if it occurs somewhere in the middle of the INFO block. Both the semicolon before ANN (that belongs to the previous field) and the one closing the ANN field are deleted, leading to an inconsistent INFO block.

Best regards,
Sebastian

**Comment by at7** [comment]
Could you please provide a few lines of input and any script parameters? It will be easier for us to reproduce the problem.

**Comment by segoerge** [comment]
Sure...

I'm using VEP with the following way:
./vep -i in.vcf -o out.vcf --vcf --hgvs --fasta hg19.fa --force_overwrite --fork 2 --variant_class --vcf_info_field ANN --numbers --total_length --canonical --exclude_predicted --allele_number --custom interim_GRCh37.p13_top_level_2017-01-13.gff3.gz,RefSeq,gff --custom Homo_sapiens.GRCh37.87.chromosome.MT.gff3.gz,Ensembl,gff --synonyms chr_synonyms.txt --transcript_filter "stable_id match N[MR]_ or stable_id match ENST"

As input I'm using an already vep-annotated VCF file that was further processed. Here one example variant (with ANN field and a "TEST" info-field from a further step positioned at the end):

16	2138218	.	A	C	0	.	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=39;CIGAR=1X;DP=573;DPB=573;DPRA=0;EPP=3.51141;EPPR=8.01982;GTI=0;LEN=1;MEANALT=2;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=358.969;PAIRED=1;PAIREDR=0.996234;PAO=0;PQA=0;PQR=0;PRO=0;QA=1470;QR=20310;RO=531;RPL=26;RPP=12.42;RPPR=5.99147;RPR=13;RUN=1;SAF=18;SAP=3.51141;SAR=21;SRF=246;SRP=9.23028;SRR=285;TYPE=snp;technology.Illumina=1;ANN=C|downstream_gene_variant|MODIFIER|PKD1|5310|Transcript|NM_000296.3|protein_coding|||||||||||1|493|-1||SNV||||RefSeq|||,C|intron_variant|MODIFIER|TSC2|7249|Transcript|NM_000548.4|protein_coding||40/41|NM_000548.4:c.5161-10A>C||||||||1||1||SNV||||RefSeq|||,C|downstream_gene_variant|MODIFIER|PKD1|5310|Transcript|NM_001009944.2|protein_coding|||||||||||1|493|-1||SNV||||RefSeq|||,C|intron_variant|MODIFIER|TSC2|7249|Transcript|NM_001077183.2|protein_coding||38/39|NM_001077183.2:c.4960-10A>C||||||||1||1||SNV||||RefSeq|||,C|intron_variant|MODIFIER|TSC2|7249|Transcript|NM_001114382.2|protein_coding||39/40|NM_001114382.2:c.5092-10A>C||||||||1||1||SNV||||RefSeq|||,C|intron_variant|MODIFIER|TSC2|7249|Transcript|NM_001318827.1|protein_coding||37/38|NM_001318827.1:c.4852-10A>C||||||||1||1||SNV||||RefSeq|||,C|intron_variant|MODIFIER|TSC2|7249|Transcript|NM_001318829.1|protein_coding||37/38|NM_001318829.1:c.4816-10A>C||||||||1||1||SNV||||RefSeq|||,C|intron_variant|MODIFIER|TSC2|7249|Transcript|NM_001318831.1|protein_coding||36/37|NM_001318831.1:c.4429-10A>C||||||||1||1||SNV||||RefSeq|||,C|intron_variant|MODIFIER|TSC2|7249|Transcript|NM_001318832.1|protein_coding||38/39|NM_001318832.1:c.4993-10A>C||||||||1||1||SNV||||RefSeq|||,C|downstream_gene_variant|MODIFIER|MIR1225|100188847|Transcript|NR_030646.1|miRNA|||||||||||1|1978|-1||SNV||||RefSeq|||,C|upstream_gene_variant|MODIFIER|LOC105371049|105371049|Transcript|NR_135175.1|ncRNA|||||||||||1|3219|1||SNV||||RefSeq|||;TEST=1	GT:DP:AD:RO:QR:AO:QA:GL	0/0:573:531,39:531:20310:39:1470:0,-39.182,-1694.1

A re-annotation with VEP is then producing the following line:

16	2138218	.	A	C	0	.	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=39;CIGAR=1X;DP=573;DPB=573;DPRA=0;EPP=3.51141;EPPR=8.01982;GTI=0;LEN=1;MEANALT=2;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=358.969;PAIRED=1;PAIREDR=0.996234;PAO=0;PQA=0;PQR=0;PRO=0;QA=1470;QR=20310;RO=531;RPL=26;RPP=12.42;RPPR=5.99147;RPR=13;RUN=1;SAF=18;SAP=3.51141;SAR=21;SRF=246;SRP=9.23028;SRR=285;TYPE=snp;technology.Illumina=1TEST=1;ANN=C|downstream_gene_variant|MODIFIER|PKD1|5310|Transcript|NM_000296.3|protein_coding|||||||||||1|493|-1||SNV||||RefSeq|||,C|intron_variant|MODIFIER|TSC2|7249|Transcript|NM_000548.4|protein_coding||40/41|NM_000548.4:c.5161-10A>C||||||||1||1||SNV||||RefSeq|||,C|downstream_gene_variant|MODIFIER|PKD1|5310|Transcript|NM_001009944.2|protein_coding|||||||||||1|493|-1||SNV||||RefSeq|||,C|intron_variant|MODIFIER|TSC2|7249|Transcript|NM_001077183.2|protein_coding||38/39|NM_001077183.2:c.4960-10A>C||||||||1||1||SNV||||RefSeq|||,C|intron_variant|MODIFIER|TSC2|7249|Transcript|NM_001114382.2|protein_coding||39/40|NM_001114382.2:c.5092-10A>C||||||||1||1||SNV||||RefSeq|||,C|intron_variant|MODIFIER|TSC2|7249|Transcript|NM_001318827.1|protein_coding||37/38|NM_001318827.1:c.4852-10A>C||||||||1||1||SNV||||RefSeq|||,C|intron_variant|MODIFIER|TSC2|7249|Transcript|NM_001318829.1|protein_coding||37/38|NM_001318829.1:c.4816-10A>C||||||||1||1||SNV||||RefSeq|||,C|intron_variant|MODIFIER|TSC2|7249|Transcript|NM_001318831.1|protein_coding||36/37|NM_001318831.1:c.4429-10A>C||||||||1||1||SNV||||RefSeq|||,C|intron_variant|MODIFIER|TSC2|7249|Transcript|NM_001318832.1|protein_coding||38/39|NM_001318832.1:c.4993-10A>C||||||||1||1||SNV||||RefSeq|||,C|downstream_gene_variant|MODIFIER|MIR1225|100188847|Transcript|NR_030646.1|miRNA|||||||||||1|1978|-1||SNV||||RefSeq|||,C|upstream_gene_variant|MODIFIER|LOC105371049|105371049|Transcript|NR_135175.1|ncRNA|||||||||||1|3219|1||SNV||||RefSeq|||	GT:DP:AD:RO:QR:AO:QA:GL	0/0:573:531,39:531:20310:39:1470:0,-39.182,-1694.1

The new ANN field moves to the end of the INFO block, leaving the previous location incorrect:

...technology.Illumina=1TEST=1;ANN=.... (a ";" is missing)

I hope this helps.

**Comment by ens-lgil** [comment]
Dear Sebastian,

Thank you very much for the command/input/output example. This was very useful!
I think I found where the issue lay in the code. I am going to work on a fix and I will be back to you once it's done.

Best regards,
Laurent

**Comment by ens-lgil** [comment]
Dear @segoerge,

We just added a fix on the branch **release/91**.
You can update your local copy of the Git repository or download the new zip package (release/91.2 - https://github.com/Ensembl/ensembl-vep/releases).

Best regards,
Laurent
