### ISSUE TITLE
Specific transcripts not in output

### ISSUE THREAD

**Issue by JakeHagen** [Ensembl/ensembl-vep#1250]
## the issue
When annotating with VEP, it seems that certain classes of transcripts get filtered and the consequences are not considered. For example the variant `chr1 95244265 95244265 T/C` falls in the 3` utr of ENST00000604534 but this consequence is not output.
I have looked at several of these "missing" transcript variants and while it makes sense to exclude them for various reasons, I can't figure out the exact logic of why they are excluded. Does this logic exist in the codebase somewhere or is something else going on entirely? Thank you for any help.

### System
- VEP version: [107] 
- VEP Cache version: [107]
- WEB

### Full VEP command line
```
./vep --af --appris --biotype --buffer_size 500 --check_existing --distance 5000 --mane --polyphen b --pubmed --regulatory --sift b --species homo_sapiens --symbol --transcript_version --tsl --cache --input_file [input_data] --output_file [output_file]
```

**Comment by diegomscoelho** [comment]
Hi @JakeHagen,

I was able to reproduce your issue. I will post what I found after investigating a little bit more.

Regards, @diegomscoelho

**Comment by diegomscoelho** [comment]
Hi @JakeHagen,

We decided to filter out from cache and database `readthrough` transcripts and `biotype artifacts` transcripts. You can check on our "What's new?" session - https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#new

Code part:
https://github.com/Ensembl/ensembl-vep/blob/release/107/modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/Transcript.pm#L264-L268

Any other question, please feel free to ask here again.

Regards, @diegomscoelho
