### ISSUE TITLE
VEP missing annotation of gnomAD for some variants

### ISSUE THREAD

**Issue by Z-Zen** [Ensembl/ensembl-vep#1254]
## Describe the issue
When annotating variants, it seems that VEP is missing some variants annotation with gnomAD.

As stated in the [data cache](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html), the gnomAD version used is `v2.1.1` for `GRCh38`.

I used the plugin for [dbNSFP v4.3a](https://github.com/Ensembl/VEP_plugins/blob/release/107/dbNSFP.pm) which also uses `v2.1.1`. The readme of the latest version of dbNSFP can be found [here](https://usf.app.box.com/s/vjigc1jponlbdpkp8ifsxl0zmumm61sh).

One expects that the annotation gives a similar allele frequency since they are using the same database of gnomAD but it isn't the case.

The columns that are impacted (found in the attached data) are `gnomADe_AF` included in VEP cache and `gnomAD_exomes_AF` for `dbNSFP`. As per the readme of dbNSFP:

> 225	gnomAD_exomes_AF: Alternative allele frequency in the whole gnomAD exome samples v2.1.1

The variants are not annotated for gnomAD from the cache but will return values when using dbNSFP plugin (see example below)

```
CHROM    POS         REF    ALT    gnomADe_AF(VEP)    gnomAD_exomes_AF(dbNSFP)
chr14    19747830    A      G      -                  1.34E-01
chr14    19748139    T      C      -                  7.29E-01
chr7     95316772    A      T      -                  2.89E-01
```

## Additional information
You can also check one of the existing variants from the above example (`chr14-19747830-A-G`) in the [online browser](https://gnomad.broadinstitute.org/variant/14-20215989-A-G?dataset=gnomad_r2_1) of gnomAD.

### System
- VEP version: 107
- VEP Cache version: 107
- Perl version: 5.26
- OS: Ubuntu
- tabix installed ? Yes

### Full VEP command line
```bash
vep --dir /dev/shm/ \
--dir_plugins /opt/vep/.vep/Plugins/ \
-i "example.vcf" \
-o "example_annotated.vcf" \
--refseq --everything --humdiv --no_escape --no_stats \
--buffer_size 50 \
--exclude_predicted \
--fork 5 \
--force --cache \
--offline --assembly GRCh38 \
--fasta /dev/shm/reference/bwa2/GCF_000001405.40_GRCh38.p14_genomic_primary_assembly.fa \
--plugin dbNSFP,/dev/shm/dbNSFP/dbNSFP4.3a/dbNSFP4.3a_grch38.gz,Polyphen2_HDIV_rankscore,Polyphen2_HVAR_rankscore,SIFT_converted_rankscore,SIFT4G_converted_rankscore,LRT_converted_rankscore,MutationTaster_converted_rankscore,MutationTaster_score,MutationAssessor_rankscore,FATHMM_converted_rankscore,PROVEAN_converted_rankscore,VEST4_rankscore,MetaSVM_score,phyloP17way_primate,ESP6500_AA_AF,ESP6500_EA_AF,ExAC_AC,ExAC_AF,ExAC_Adj_AC,ExAC_Adj_AF,ExAC_AFR_AF,ExAC_NFE_AF,ExAC_AMR_AF,ExAC_EAS_AF,ExAC_SAS_AF,1000Gp3_AF,1000Gp3_AC,Ancestral_allele,gnomAD_exomes_AN,gnomAD_exomes_AC,gnomAD_exomes_AF,gnomAD_genomes_AC,gnomAD_genomes_AF,gnomAD_genomes_AN \
--plugin dbscSNV,/dev/shm/dbscSNV/dbscSNV1.1/dbscSNV1.1_GRCh38.txt.gz \
--plugin GeneSplicer,/dev/shm/genesplicer/sources/genesplicer,/dev/shm/genesplicer/human,tmpdir=./ \
--plugin MaxEntScan,/dev/shm/MaxEntScan \
--plugin SpliceRegion \
--plugin SpliceAI,snv=spliceai_scores.raw.snv.hg38.vcf.gz,indel=spliceai_scores.raw.indel.hg38.vcf.gz,cutoff=0.5 \
--plugin CADD,/dev/shm/CADD/GRCh38_v1.6/whole_genome_SNVs.tsv.gz,/dev/shm/CADD/GRCh38_v1.6/gnomad.genomes.r3.0.indel.tsv.gz \
--plugin REVEL,/dev/shm/REVEL/new_tabbed_revel.tsv.gz \
--plugin Blosum62 \
--plugin Conservation,/dev/shm/Conservation/gerp_conservation_scores.homo_sapiens.GRCh38.bw \
--plugin Downstream \
--vcf --use_given_ref
```

### Data files (if applicable)
They include:
- The input file: [example.vcf.txt](https://github.com/Ensembl/ensembl-vep/files/9501461/example.vcf.txt)
- The output file: [example_annotated.vcf.txt](https://github.com/Ensembl/ensembl-vep/files/9501462/example_annotated.vcf.txt)

**Comment by diegomscoelho** [comment]
Hi @Z-Zen,

VEP release 107 will only annotate dbSNP (v154) variants, it seems that two variants that you mentioned are not covered in dbSNP and the third one started being covered in dbSNP (v155 - https://www.ncbi.nlm.nih.gov/snp/rs854560). For annotating those variants with gnomAD information, you can use `--custom` flag with gnomAD original VCFs (https://gnomad.broadinstitute.org/downloads).

Any other question, feel free to post a comment here again.

Regards, @diegomscoelho

**Comment by diegomscoelho** [comment]
Hi @Z-Zen.

I mean `dbSNP` is our main variant source, I didn't mean `dbNSFP`. Our cache is limited to some sources, most variants comes from dbSNP. You can check on our cache webpage (https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache) - See `Data in the cache` subsection.
Then, if your variant are not in our cache, it will not be annotated by VEP. As mentioned before, depending on what you need to annotate, you can use `--custom` flag to add some extra information (some examples - https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html).

**Comment by diegomscoelho** [comment]
Hi again,

```
I suppose when annotating the variants, VEP checks if the variant is also available in gnomAD cache and not only dbSNP, isn't this right?
```

Unfortunately, no.

gnomAD exomes / genomes reported values are limited to intersection with dbSNP v154 variants. So, if your variant exists in gnomAD exomes / genomes but does not exist in dbSNP v154, gnomAD value will not be reported, because this variant will not exist in VEP cache at all. We don't create a `gnomAD cache`, we simply add gnomAD information to our cache, but this information is limited to variants that we report, in this case, dbSNP variants mostly.
