### ISSUE TITLE
ERROR: Could not write to warnings file

### ISSUE THREAD

**Issue by NuoXu0621** [Ensembl/ensembl-vep#1258]
**System**
Docker version 18.03.1-ce
VEP version: 107
OS: 18.04.1-Ubuntu

Here is my command,
`sudo docker run -t -i -v $HOME/vep_data:/opt/vep/.vep:Z ensemblorg/ensembl-vep ./vep -i $InputDir/$inVCF -o $outVCF \
    --plugin dbNSFP,$VEPDATA/extdata/dbNSFP4.3a_grch38.gz,Ensembl_transcriptid,Uniprot_acc,VEP_canonical,LRT_pred,SIFT_pred,MutationTaster_pred,Polyphen2_HDIV_pred,Polyphen2_HVAR_pred \
    --plugin LoFtool,scores_file.txt \
    --dir_plugins $VEPDATA/Plugins/ --dir_cache $VEPDATA --cache \
    --everything --offline --buffer_size 2000 --compress_output bgzip --vcf`

I've changed the rw access of $HOME/vep_data but still get this error,
`-------------------- EXCEPTION --------------------
MSG: ERROR: Could not write to warnings file /home/dnanexus/vep_data/output/ukb23157_c1_b0_v1_annotated.vcf.gz_warnings.txt

STACK Bio::EnsEMBL::VEP::BaseVEP::warning_fh /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:760
STACK Bio::EnsEMBL::VEP::BaseVEP::warning_msg /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:724
STACK Bio::EnsEMBL::VEP::Runner::get_all_Plugins /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:899
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:125
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel ./vep:238
Date (localtime)    = Wed Sep 14 12:31:16 2022
Ensembl API version = 107
---------------------------------------------------`

**Comment by diegomscoelho** [comment]
Hi @NuoXu0621,

Can you try to use `--force_overwrite` flag? - It can also be that VEP is not able to overwrite a file.

Regards, @diegomscoelho

**Comment by NuoXu0621** [comment]
Sorry for replying so late, I found the solution by modifying the $VEPDATA from $HOME/vep_data to /opt/vep/.vep, which is the default path of vep docker image, I think. Then it ran successfully.
But I found another question: my input data is a population VCF file of about 30G, and it took 5 hours to complete the annotation. Is there any advice for optimizing runtime? By the way, I set buffer size and fork option to `--buffer_size 100 --fork 8`
Thanks!

**Comment by diegomscoelho** [comment]
Hi @NuoXu0621,

Try setting buffer_size * fork til max out your RAM. For example, if you have 32GB of RAM, you can use --buffer_size 5000 (already default) + fork 6 = 30 GB of RAM are going to be used. I would always left some space to not ran out of memory, last example was 2GB.

If you have any other question, please feel free to comment here again or close this issue.

Regards, @diegomscoelho
