### ISSUE TITLE
"Failed to fork" for any fork value

### ISSUE THREAD

**Issue by sharra44** [Ensembl/ensembl-vep#1265]
Getting the error below for any value of --fork(tried 1, 2, 4, 8, and 20). Input file is from 1000genomes, normalized through bftools and with tabix run on it. Program has been running with no forks for about 3 days now without stopping, so I definitely need the ability to speed up the process. \
-------------------- EXCEPTION --------------------
MSG: ERROR: Failed to fork

STACK Bio::EnsEMBL::VEP::Runner::_forked_buffer_to_output /home/centos/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:495
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /home/centos/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:365
STACK Bio::EnsEMBL::VEP::Runner::run /home/centos/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:207
STACK toplevel ./vep:238
Date (localtime)    = Fri Sep 23 16:11:56 2022
Ensembl API version = 107

### System
System is centos linux ec2 of type m5.4xlarge. Running all latest updates of perl/vep/dependencies.

### Full VEP command line
```
nohup ./vep \
--cache \
--merged \
--fork 4 \
--dir_cache /root/.vep \
--species homo_sapiens \
--compress_output bgzip \
--input_file sampleChrm11.normalized.vcf \
--format vcf \
--output_file sampleChrm11.annotated.vcf \
--no_stats \
--force_overwrite \
--assembly GRCh38 \
--fields "Allele,Consequence,IMPACT,SYMBOL,Feature_type,Feature,gnomAD_AF,CLIN_SIG,PHENO,ENSP" \
--fasta /root/.vep/homo_sapiens/107_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz \
--check_ref \
--flag_pick \
--vcf &

**Comment by olaaustine** [comment]
Hi @sharra44,
Thank you for your query. 
I have not been able to recreate this issue but can you use the [option ](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_merged:~:text=%2Dbuffer_size%20%5Bnumber%5D) --buffer_size. The default is 5000 so reducing the buffer size will allow VEP to fork correctly. 
Please let us know if this solves this problem.
Thanks 
Ola.

**Comment by sharra44** [comment]
My current buffer size is set to the default - should i be using a lower value?

**Comment by olaaustine** [comment]
Hi @sharra44,
Can you try with either --buffer_size 5000 or  --buffer_size 50?
Let us know if this error still occurs
Thank you 
Ola.

**Comment by sharra44** [comment]
Both 5000 and 50 still failed to fork. I have attempted to reinstall on a new ec2 thats larger (m5.12xlarge) and am now getting the following error when attempting to fetch the cache ERROR: Could not connect to FTP host ftp.ensembl.org
Net::FTP: connect: timeout

**Comment by sharra44** [comment]
Both 5000 and 50 failed to fork as well

**Comment by olaaustine** [comment]
Hi @sharra44,
Can you share your input VCF file so I can use it to try to recreate the issue. 
Thank you 
Ola

**Comment by olaaustine** [comment]
Hi, 
I am still unable to recreate this issue using the VCF and following your pre-processing steps
Do you have tabix installed? If you already have tabix installed on the cluster, this might be causing a clash with tabix installed in VEP
Thank you 
Ola.

**Comment by sharra44** [comment]
Hello -
I have managed to successfully run the program by increasing the size of my ec2 to a 12xlarge. Thank you for your assistance.

**Comment by olaaustine** [comment]
Hi @sharra44,
Thank you very much for letting us know. 
I will close this ticket now. Please feel free to reopen or open another if you have another query. 
Thank you,
Ola
