### ISSUE TITLE
VEP running in slurm HPC failing for some users but not others

### ISSUE THREAD

**Issue by Krutik6** [Ensembl/ensembl-vep#1269]
## Describe the issue
Dear VEP engineers, I work in a team of informaticians and we have been having a recurring issue with VEP 107 for the past month. Simply put our vep installations work fine for myself and I get the expected output, however vep does not work for any colleagues. Our vep is installed in a slurm based HPC, and we believe this issue comes from our HPC rather than from vep. We were wondering if others have found these issues before. 

### System
- VEP version: [107] 
- VEP Cache version: [107]
- Perl version: [e.g. 5.34]
- OS: [CentOS Linux 7 (Core)]
- tabix installed: [yes - tabix/0.2.6-GCCcore-10.2.0 (L,D)]

### Full VEP command line
```
${vep_path}/vep --cache --dir ${dir}  --dir_cache ${dir_cache}  --offline 
--fasta $fasta  --species homo_sapiens  --input_file ${Job}_filtered_cohort.vcf.gz  
--output_file ${Job}_VEP_annotated.vcf  --format vcf --force_overwrite  --vcf --no_check_variants_order --check_existing --freq_pop gnomAD --assembly GRCh38 --stats_file ${Job}_vep_stat.html --warning_file ${Job}_vep_warning.txt --hgvs --variant_class --keep_csq --af_gnomad --polyphen p --sift p --symbol --total_length --max_af --plugin LoFtool --plugin REVEL,/pathto/new_tabbed_revel_grch38.tsv.gz \
--plugin Mastermind,/pathto/mastermind_cited_variants_reference-2022.07.22-grch38.vcf.gz,0,0,1 --plugin LoFtool --plugin CADD,/pathto/whole_genome_SNVs.tsv.gz,/pathto/gnomad.genomes.r3.0.indel.tsv.gz 
--fields 
"Uploaded_variation,Location,Allele,Gene,Feature,SYMBOL,Existing_variation,VARIANT_CLASS,Consequence,cDNA_position,CDS_position,Protein_position,Amino_acids,HGVSc,HGVSp,BIOTYPE,IMPACT,CLIN_SIG,PolyPhen,SIFT,MAX_AF,gnomAD_AF,AF,CADD_PHRED,CADD_RAW,LoFtool,REVEL,Mastermind_URL" 
--pick --pick_order rank,canonical,tsl --buffer_size 20000 --fork 4 
```

### Full error message
For myself I find no errors - only some warnings, and for other users who have tried the same code - they find a recurring error.

### Data files (if applicable)
My error output (vep works) 
[slurm-mine.txt](https://github.com/Ensembl/ensembl-vep/files/9696988/slurm-mine.txt)
colleague 1's output files
[slurm-colleague1_1.txt](https://github.com/Ensembl/ensembl-vep/files/9696990/slurm-colleague1_1.txt)
[slurm-colleague1_2.txt](https://github.com/Ensembl/ensembl-vep/files/9696991/slurm-colleague1_2.txt)
colleague 2's output file 
[slurm-colleague2.txt](https://github.com/Ensembl/ensembl-vep/files/9696995/slurm-colleague2.txt)

As you can see, both of my colleagues are getting a similar error, even though we are running the same scripts - sometimes on the same files, and using the same HPC. Any ideas would be great.

Best Wishes,
Krutik

**Comment by likhitha-surapaneni** [comment]
Hi @Krutik6 , I am sorry to hear that you are facing an issue with VEP installation. I am trying to understand what might be different for different users. Can you please confirm if the slurm nodes used by different users have the same configuration? 

In order to understand what might be going wrong with running VEP by other users, can you and your colleagues try the following and see if the error still exists:
1. Setting `buffer_size` to 500 instead of 20000. 
2. Running without `forks` or at least reducing ` forks` to 2  

Thanks and regards,
Likhitha

**Comment by Krutik6** [comment]
Hi @likhitha-surapaneni,

Apologies for the delay in messaging - we have heard back from our slurm HPC maintainer and all accounts at our University have the same privileges and access to memory. 

I have attached files which were run when `buffer_size` was set to `500` for: 
myself 
[slurm-27722165_buffer500_mine.txt](https://github.com/Ensembl/ensembl-vep/files/9734723/slurm-27722165_buffer500_mine.txt)
colleague1 
[slurm-27722168_buffer500_colleage1.txt](https://github.com/Ensembl/ensembl-vep/files/9734725/slurm-27722168_buffer500_colleage1.txt)

and when `forks` were reduced to `2` for:
myself
[slurm-27711010_fork2_mine.txt](https://github.com/Ensembl/ensembl-vep/files/9734729/slurm-27711010_fork2_mine.txt)
colleage1
[slurm-27722168_buffer500_colleage1.txt](https://github.com/Ensembl/ensembl-vep/files/9734731/slurm-27722168_buffer500_colleage1.txt)

**Comment by likhitha-surapaneni** [comment]
Hi @Krutik6 , thank you for the reports. It still does not seem to be clear why the output is different. In order to get some additional details, 
Could you and your colleague try the following and let me know what happens:
1. Run VEP command with minimal options and with a smaller test dataset (with no forks or plugins) to rule out if it is setup/file permission issues
2. Run `perl -e "use Bio::DB::HTS::Tabix"` in the environment where you are running VEP

**Comment by vkorak** [comment]
Hi @likhitha-surapaneni, 

I apologise for the delay and thank you for your response. I am working in the same team as @Krutik6, and I am "colleague 1".

Please see attached the file I run with minimal options (no plugins or forks) for only chr1 (_VEP worked_): 
[slurm-27771411_Chr1_no_plugins_colleague1.txt](https://github.com/Ensembl/ensembl-vep/files/9766272/slurm-27771411_Chr1_no_plugins_colleague1.txt)

Next, the file I run with forks and plugins for only chr1 (_VEP worked_): 
[slurm-27772706_Chr1_plugins_colleague1.txt](https://github.com/Ensembl/ensembl-vep/files/9766933/slurm-27772706_Chr1_plugins_colleague1.txt)

and the file I run `perl -e "use Bio::DB::HTS::Tabix"`  in the environment where I run VEP (_VEP did not work_): 
[slurm-27771399_perl_Bio_DB_colleague1.txt](https://github.com/Ensembl/ensembl-vep/files/9766355/slurm-27771399_perl_Bio_DB_colleague1.txt)

**Comment by likhitha-surapaneni** [comment]
Hi @vkorak , apologies for the delay in responding. 
Since the error happens when locating tabix, it might be worth installing htslib and Bio::DB::HTS manually following the steps in https://www.ensembl.org/info/docs/api/api_installation.html#variation. Please let me know if that solves the issue.

**Comment by likhitha-surapaneni** [comment]
Hi @vkorak and @Krutik6  , 

I hope the above steps were useful in solving the issue. Please feel free to open a new ticket if there are any further queries.

Kind regards,
Likhitha
