### ISSUE TITLE
VEP does not work properly using dbNSFP plugin neither custom gnomAD  (running from Docker)

### ISSUE THREAD

**Issue by mshumilova** [Ensembl/ensembl-vep#1270]
## Describe the issue

I did not get the statistics after VEP annotation using dbNSFP plugin. I thought maybe I did something wrong during my preparation of the database and decided to use another metric using custom gnomAD plugin. Unfortanutely I had got the same result without any statistics. 

### System
- VEP version: 107.0
- VEP Cache version: I do not know how to check it
- Perl version: (v5.26.1) built for x86_64-linux-gnu-thread-multi
- OS: MacOS M1
- tabix installed: yes

### Full VEP command line

1)  running VEP from Docker container: 

sudo docker run --platform=linux/amd64 -t -I -v /{path_to_my_folder}:/opt/vep/.vep:Z ensemblorg/ensembl-vep

2) downloading and preparation the databases: 

a) for plugin dbNSFP I used the manual from the site (https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html#dbnsfp):

> wget ftp://dbnsfp:dbnsfp@dbnsfp.softgenetics.com/dbNSFP4.1a.zip
> unzip dbNSFP4.1a.zip
> zcat dbNSFP4.1a_variant.chr1.gz | head -n1 > h
> zgrep -h -v ^#chr dbNSFP4.1a_variant.chr* | awk '$8 != "." ' | sort -T /path/to/tmp_folder -k8,8 -k9,9n - | cat h - | bgzip -c > dbNSFP4.1a_grch37.gz
> tabix -s 8 -b 9 -e 9 dbNSFP4.1a_grch37.gz

b) for custom gnomAD I also used manual from the site(https://www.ensembl.org/info/docs/tools/vep/script/vep_example.html):

GRCh37
gnomAD genomes (r2.1): [[VCF and tabix indexes]](http://ftp.ensembl.org/pub/data_files/homo_sapiens/GRCh37/variation_genotype/)
gnomAD exomes (r2.1): [[VCF and tabix indexes]](http://ftp.ensembl.org/pub/data_files/homo_sapiens/GRCh37/variation_genotype/)

3) My code is: 

a) for plugin dbNSFP: 

./vep --cache --offline --format vcf --vcf --database \
--dir_cache /opt/vep/.vep/ \
--input_file /opt/vep/.vep/2_rsid/test.vcf \
--fasta /opt/vep/.vep/Plugins/ref_fasta/human_g1k_v37.fasta \
--output_file /opt/vep/.vep/3_annotated/test_annotated.vcf \
--hgvs \
--symbol \
--polyphen b \
--gene_phenotype \
--pubmed \
--assembly GRCh37 \
--plugin dbNSFP,/opt/vep/.vep/Plugins/dbNSFP/dbNSFP4.1a_grch37.gz,LRT_score,LRT_pred,GERP++_RS

b) for custom gnomAD:

./vep --cache --offline --format vcf --vcf --database \
--dir_cache /opt/vep/.vep/ \
--input_file /opt/vep/.vep/2_rsid/test.vcf \
--fasta /opt/vep/.vep/Plugins/ref_fasta/human_g1k_v37.fasta \
--output_file /opt/vep/.vep/3_annotated/test_annotated.vcf \
--hgvs \
--symbol \
--polyphen b \
--gene_phenotype \
--pubmed \
--assembly GRCh37 \
--custom /opt/vep/.vep/Plugins/gnomAD/gnomad.exomes.r2.0.1.sites.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF_NFE

```
### Full error message
a) for dbNSFP plugin:
>Use of uninitialized value $readme_file in concatenation (.) or string at /opt/vep/.vep/Plugins/dbNSFP.pm line 344.

b) for gnomAD:
> [W::hts_idx_load2] The index file is older than the data file: {path_to_tbi_file}

### Data files (if applicable)
The output annotation (the results are the same in both cases):

a) 1	8021812	rs527992433	G	T,A	444.41	.	AC=2,0;AF=1.101e-03,0.00;AN=1816;BaseQRankSum=-1.110e-01;ClippingRankSum=-1.110e-01;DB;DP=52996;ExcessHet=3.0131;FS=0.000;InbreedingCoeff=0.0048;MQ=90.66;MQRankSum=0.479;QD=2.10;ReadPosRankSum=0.262;SOR=0.687;CSQ=T|5_prime_UTR_variant|MODIFIER|PARK7|ENSG00000116288|Transcript|ENST00000338639|protein_coding|1/7||ENST00000338639.5:c.-65G>T||90|||||||1||HGNC|16369|1|||||||||,A|5_prime_UTR_variant|MODIFIER|PARK7|ENSG00000116288|Transcript|ENST00000338639|protein_coding|1/7||ENST00000338639.5:c.-65G>A||90|||||rs527992433||1||HGNC|16369|1|||||||||
b) 1	8021812	rs527992433	G	T,A	444.41	.	AC=2,0;AF=1.101e-03,0.00;AN=1816;BaseQRankSum=-1.110e-01;ClippingRankSum=-1.110e-01;DB;DP=52996;ExcessHet=3.0131;FS=0.000;InbreedingCoeff=0.0048;MQ=90.66;MQRankSum=0.479;QD=2.10;ReadPosRankSum=0.262;SOR=0.687;CSQ=T|5_prime_UTR_variant|MODIFIER|PARK7|ENSG00000116288|Transcript|ENST00000338639|protein_coding|1/7||ENST00000338639.5:c.-65G>T||90|||||||1||HGNC|16369||1||||||||,A|5_prime_UTR_variant|MODIFIER|PARK7|ENSG00000116288|Transcript|ENST00000338639|protein_coding|1/7||ENST00000338639.5:c.-65G>A||90|||||rs527992433||1||HGNC|16369||1||||||||

**Comment by gerasimov-studio** [comment]
I had the same problem, after two days of torture I changed the tool

**Comment by mshumilova** [comment]
Dear developers, I would be grateful if you give me some hint what could be wrong from my side. I am really sorry for disturbing you, I just have some time limits and I really do not want to change the tool as mentioned above by @gerasimov-studio, because I spent more than two days on it) Thank you in advance! Sincerely, Maria.

**Comment by likhitha-surapaneni** [comment]
Hi @mshumilova , thank you for your patience and sorry for the delay. I am testing this out to see what might be going wrong in this case.

**Comment by likhitha-surapaneni** [comment]
Hi @mshumilova ,

The dbNSFP plugin writes results to your output but only for variants of type: missense_variant, stop_lost, stop_gained or start_lost. Could you please try running them for another  example variant which satisfies the above condition?

**Comment by likhitha-surapaneni** [comment]
Hi @mshumilova ,
Regarding  the example with custom annotation, when using "exact" only, annotations whose coordinates match "exactly" those of the variant will be reported. You could check further documentation for custom annotation here: https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html. This might be the problem why custom annotation may return empty annotation

Thank for your patience and hope this helps!

**Comment by mshumilova** [comment]
Dear @likhitha-surapaneni,

I've concentrated on gnomAD annotation. For some reason I get annotation from gnomADg (even with "exact" parameter), but not from gnomADe (tried both parameters). 

I've checked all fields of my output test dataset and they are empty for gnomADe.
Example of my output of the fields: 

|gnomADe|gnomADe_AF_NFE|gnomADg|gnomADg_AF_NFE
|||rs11121064|3.33511e-04

My current code: 

./vep --cache --offline --format vcf --vcf --database \
--dir_cache /opt/vep/.vep/ \
--input_file /opt/vep/.vep/2_rsid/test.vcf \
--fasta /opt/vep/.vep/Plugins/ref_fasta/human_g1k_v37.fasta \
--output_file /opt/vep/.vep/3_annotated/test_annotated.vcf \
--hgvs \
--symbol \
--polyphen b \
--gene_phenotype \
--pubmed \
--assembly GRCh37 \
--custom /opt/vep/.vep/Plugins/gnomAD/gnomad.exomes.r2.0.1.sites.noVEP.vcf.gz,gnomADe,vcf,overlap,0,AF_NFE \
--custom /opt/vep/.vep/Plugins/gnomAD/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF_NFE

**Comment by likhitha-surapaneni** [comment]
Hi @mshumilova ,

I am closing this issue for now since there are no outstanding problems. Please feel free to open a new issue for any further queries.

Thanks and regards,
Likhitha
