### ISSUE TITLE
HGVS formatted input reduces speed immensely

### ISSUE THREAD

**Issue by davidfstein** [Ensembl/ensembl-vep#1277]
## Describe the issue
I am attempting to annotate ~100 million SNVs in HGVS format to determine all possible missense variants in canonical ensembl transcripts. With a VCF formatted input, VEP annotates several 100,000 variants an hour. However, with the HGVS input, which precludes the usage of offline mode, VEP slows to a crawl and no longer leverages all the cores available. I have followed all the steps in the running VEP faster guide, I even copy the cache and fasta reference to shared memory for fast reading. 

My command is as follows, I really only need the variant consequence and the canonical status of the impacted transcript, so this should be a very minimal job.

/tools/ensembl-vep-106/ensembl-vep/vep  -i $WRKDIR/$myinput -o $WRKDIR/$myoutput --format hgvs --dir_cache $cachedir --vcf --no_stats --assembly GRCh38 --canonical --cache --total_length --fasta $ref_fasta --force_overwrite --fork 40 --buffer_size 10000

Is there anything I can do to speed this up at all? Or if there is a better way to identify missense variants in the canonical transcripts please let me know. I formatted my input as HGVS because it was the easiest option, but perhaps I will have to convert transcript coordinates to genomic coordinates on my own so that I can use VCF input. 

## Additional information
Machine has 80 cores and around 512 gb RAM

### System
- VEP version: 106
- VEP Cache version: 106
- Perl version: 5.26.1
- OS: Ubuntu 18.04
- tabix installed yes

### Full VEP command line
```
/tools/ensembl-vep-106/ensembl-vep/vep  -i $WRKDIR/$myinput -o $WRKDIR/$myoutput --format hgvs --dir_cache $cachedir --vcf --no_stats --assembly GRCh38 --canonical --cache --total_length --fasta $ref_fasta --force_overwrite --fork 40 --buffer_size 10000
```

### Data files (if applicable)
- The input file
ENST00000631435.1:c.1G>T
ENST00000631435.1:c.1G>A
ENST00000631435.1:c.1G>C
ENST00000631435.1:c.2G>T
ENST00000631435.1:c.2G>A
ENST00000631435.1:c.2G>C
ENST00000631435.1:c.3G>T
...
...
...

**Comment by nuno-agostinho** [comment]
Hey @davidfstein, hope you are having a wonderful day!

As you noted, VEP currently requires a database connection to convert from the HGVS format, making this option slow when running for a large number of variants. We are looking into making this work offline in a future release.

Meanwhile, the fastest way to run VEP would be to convert from HGVS to VCF so you can run VEP with the `--offline` flag. To convert the HGVS identifiers to VCF, you can input your variants into the web version of [Variant Recoder](https://www.ensembl.org/Multi/Tools/VR) and export as VCF. Note that VR may return more than one variant per HGVS identifier (if ambiguous).

For tips on optimising VEP,  take a look at our [documentation](https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#faster). Hopefully this helps you, but please feel free to discuss this further if needed.

Thanks,
Nuno

**Comment by nuno-agostinho** [comment]
Hi @davidfstein,

Variant Recoder also requires an online connection (even the command-line version) as they are based on the same code as VEP. I was just suggesting it as it may be easier to convert your HGVS variants to VCF before running VEP.

The max file upload size for our tools is 50MB and they accept zip archives.

Cheers,
Nuno

**Comment by davidfstein** [comment]
Ok thanks Nuno. I think HGVS format offline would be nice, so I'm looking forward to future releases where that is supported
