### ISSUE TITLE
Unable to parse HGVS notation. Frameshifts are not supported for HGVS protein input.

### ISSUE THREAD

**Issue by migrau** [Ensembl/ensembl-vep#1283]
## Description
Trying to annotate (using the [online vep version](https://asia.ensembl.org/Homo_sapiens/Tools/VEP?db=core)) some HGVS protein frameshift mutations, e.g:
ENST00000257430.16:p.Ile1557fs*30
APC:p.I1557fs*30

But I got an error:
![image](https://user-images.githubusercontent.com/6456499/197130635-892d0c87-d79f-4019-8ecc-358ff24c9edb.png)

What is the correct syntax to insert frameshift mutations?

Thanks,

**Comment by dglemos** [comment]
Hi @migrau,
VEP does not support frameshifts as HGVS protein input e.g. `p.Ile1557fs30`. To annotate frameshift variants you should input their HGVS genomic or coding format. 

Let me know if you have more questions.

Best wishes,
Diana

**Comment by dglemos** [comment]
I'm going to close the issue but feel free to open a new one if you have more questions.

Best wishes,
Diana
