### ISSUE TITLE
INSTALL.pl can no longer install caches

### ISSUE THREAD

**Issue by ntm** [Ensembl/ensembl-vep#1284]
Hi,
a recent commit replaced ftp with https everywhere:
https://github.com/Ensembl/ensembl-vep/commit/6185f08
This includes changing $CACHE_URL , $CACHE_URL_INDEXED and $FASTA_URL from ftp:// to https:// in INSTALL.pl, and this breaks INSTALL.pl: caches and FASTA files can no longer be installed.
Indeed, INSTALL.pl expects the URLs to begin with ftp, eg:
https://github.com/Ensembl/ensembl-vep/blob/0cc6b7c3471fc8e9ce9fd574156410e96475f141/INSTALL.pl#L1109

Simply reverting the INSTALL.pl part of commit 6185f08 solves the issue.

**Comment by nuno-agostinho** [comment]
Hi @ntm, thanks for notifying us of this issue! We just released VEP 108.1 to patch this problem.

Cheers,
Nuno
