### ISSUE TITLE
GRCh37 assembly is not available in 108 release

### ISSUE THREAD

**Issue by aschluter** [Ensembl/ensembl-vep#1288]
Hi,
Cache files for homo_sapiens in GRCh37 assembly are not available in 108 release.

https://ftp.ensembl.org/pub/release-108/variation/indexed_vep_cache/

### System
- VEP version: 108 
- VEP Cache version: 108

Thank you,

Agatha

**Comment by nuno-agostinho** [comment]
Hi @aschluter,

Thanks for mentioning this issue and I'm sorry for the inconvenience. We will make the GRCh38 VEP cache available as soon as possible.

Kind regards,
Nuno

**Comment by nuno-agostinho** [comment]
Hi @aschluter, hope you are having a nice day!

You can now find the GRCh37 cache for release 108 in https://ftp.ensembl.org/pub/release-108/variation/indexed_vep_cache/

Please let me know if you find any other issues.

Best regards,
Nuno

**Comment by aschluter** [comment]
Thanks for fixing it so quickly!

Best regards,

Agatha
