### ISSUE TITLE
gnomad v3 in code, but only v2 in docs. which is default?

### ISSUE THREAD

**Issue by layne-sadler** [Ensembl/ensembl-vep#1293]
Thank you for your important work. We are going to publish some of our top variants so I am doing a bit of diligence on the hg38 allele frequencies that were annotated using VEP.

---

## Describe the issue

Which gnomAD version is used by default? both?

- [In the documentation about the gnomad plugin, it mentions gnomad v2, but does not mention gnomad v3](https://useast.ensembl.org/info/docs/tools/vep/script/vep_example.html)

- [However, I see v3 in the code](https://github.com/Ensembl/ensembl-vep/blob/0cc6b7c3471fc8e9ce9fd574156410e96475f141/modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/DumpVEP_conf.pm#L154)

- [v3 also appears in the cache docs](https://useast.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache)

---

### System
- VEP version: v107
- VEP Cache version: homo_sapiens/107_GRCh38 (23.94GB)
- Perl version: 5.26.1
- OS: MacOS
- tabix: 1.9

---

### Full VEP command line
```
./vep -i in.vcf -o out.vcf --cache --af_gnomad --tab --symbol --pick
```

**Comment by layne-sadler** [comment]
Within `home_sapiens/107_GRCh38/info.txt` I see 

```
source_gnomADe: r2.1.1
source_gnomADg: v3.1.2
```

since my column is `gnomADe_AF` it must be referring to the exomes aka v2

**Comment by layne-sadler** [comment]
What's weird is that my column says `gnomADe_AF`, which leads me to think that it is from gnomad v2, but it only shows up in v3

![image](https://user-images.githubusercontent.com/76759666/198841884-c96e2bc2-00c4-43fc-9362-ff08bf406aeb.png)

![image](https://user-images.githubusercontent.com/76759666/198842030-754b6f4d-5b48-4726-ac3c-662e53bb22d5.png)

![image](https://user-images.githubusercontent.com/76759666/198842138-22f8d752-6eae-4cda-835c-128694fd805f.png)


which leads me to believe that genomes is being used even though it says exomes

**Comment by diegomscoelho** [comment]
Hi @layne-sadler,

Both versions are supported v2 for exomes (gnomAD exomes) and v3 for genomes (gnomAD genomes). You can find this info in [cache](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache).

![image](https://user-images.githubusercontent.com/10541523/198976197-d68dbd02-6b78-4c0d-85d0-d2537d1f4bef.png)

You can also find a brief explanation about difference between `--af_gnomade` (exomes) and `--af_gnomadg` (genomes) in [vep_options](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html).

`--af_gnomad` flag is equal to `--af_gnomade` flag, so you are only having exomes results. If you want genomes also, you should use `--af_gnomadg` too.

Can you provide your `in.vcf` line? - Not sure if your query is 20:33289907-33289907 in GRCh37 (as you provide in gnomAD v2) or GRCh38 (as you provide in gnomAD v3).

Regards, @diegomscoelho

**Comment by layne-sadler** [comment]
> Can you provide your in.vcf line?

Is that not what this is?

![image](https://user-images.githubusercontent.com/76759666/199012390-323d79ca-0cca-46f6-a46a-ca8981e84b57.png)

**Comment by layne-sadler** [comment]
>  Not sure if your query is 20:33289907-33289907 in GRCh37 (as you provide in gnomAD v2) or GRCh38 (as you provide in gnomAD v3).

I am using GRCh38 whole exome vcfs

**Comment by layne-sadler** [comment]
> --af_gnomad flag is equal to --af_gnomade flag

Is it though? If that is the case then why I am seeing `-af_gnomadg` looking results?

thanks for the info!

**Comment by layne-sadler** [comment]
Thank you @diegomscoelho I never would have figured out that the gnomad v2 hg37 values were being lifted over! now I see in the gnomad portal v2 shows "Genome buildGRCh37 / hg19." So that is where I was getting stuck   

It would be nice if the gnomad section on this page was updated w more info about the different AF commands:
https://useast.ensembl.org/info/docs/tools/vep/script/vep_example.html

thank you! 🙏

**Comment by diegomscoelho** [comment]
Hi @layne-sadler,

VEP is not lifting over gnomAD v2, we use already provided liftover from them. You can find more information about `--af_gnomad`, `--af_gnomade` and `--af_gnomadg` on vep options [webpage](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html).

I also can see now that vep_examples are a little bit misleading of how you can get VEP cache gnomAD data. Just to confirm, from version 107, VEP cache already have gnomAD information for exomes + genomes, if you have downloaded VEP cache files you don't need to download gnomAD VCF files and use `--custom` to get gnomAD frequencies (only if you want to annotate variants that are not present on cache).

I will make sure that we update again docs to reflect these new alterations on VEP.

Thanks for letting us know, @diegomscoelho

**Comment by diegomscoelho** [comment]
Hi @layne-sadler,

Closing this issue now! If you have any other question feel free to comment here.

Regards, @diegomscoelho
