### ISSUE TITLE
HGVS.p not annotated

### ISSUE THREAD

**Issue by xiucz** [Ensembl/ensembl-vep#1295]
## Describe the issue
Hi,  when I use vep to annotate "chr19 42384927 ATCCCAGGGCCTGAACCTGGACGACTGCTCCATGTATGAGGACATC  A", it cannot return the p point,  can you help me to check it ?

Thank you.
xiucz 

### System
- VEP version: [105] 
- VEP Cache version: [105]

### Full VEP command line
```
vep -cache --refseq --force_overwrite --fork 8 --offline --no_escape --format vcf --vcf  --canonical --pubmed --use_given_ref --hgvs --transcript_version --dir_cache ~/hg19/vep105db/ --dir_plugins ~/vep/ensembl-vep_105/ensembl-vep/Plugins --species homo_sapiens --assembly=GRCh37 --fasta /hg19/gatk_bundle/ucsc.hg19.fasta -o  xx.vcf
```

**Comment by nakib103** [comment]
Hello @xiucz,

We reviewed the code and it would be complicated to properly model and give correct HGVS for variants that are in the exon-intron boundaries. We are looking to improve these cases in our future implementation of VEP.

Best regards,
Nakib
