### ISSUE TITLE
SIFT/PolyPhen getting disabled at GRCh37

### ISSUE THREAD

**Issue by barslmn** [Ensembl/ensembl-vep#1296]
Hi Ensembl Team,
## Describe the issue
SIFT and PolyPhen gets disabled when used with GRCh37. I can see polyphen and sift with GRCh38. Is this related to 107 known bug: https://www.ensembl.info/known-bugs/ensembl-107/

Best,
B

### System
- VEP version: 108.1
- VEP Cache version: 108.1
- Perl version: 5.30
- OS: Ubunru
- tabix installed yes

### Test Cases

ASSEMBLY="GRCh37"
echo "##fileformat=VCFv4.2
##genome-build=GRCh37
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       45796269        .       G       C       10000        .       .
10      43581968        .       C       A       10000        .       ." > dummy$ASSEMBLY.vcf
/home/admin/ensembl-vep/vep \
	--input_file "dummy$ASSEMBLY.vcf" \
	--output_file "dummy$ASSEMBLY.tsv" \
	--assembly "$ASSEMBLY" \
	--species homo_sapiens \
	--merged --use_given_ref \
	--everything \
	--cache \
	--nearest transcript

# Warning messages
2022-10-31 17:15:56 - INFO: disabling SIFT
2022-10-31 17:15:56 - INFO: disabling PolyPhen

ASSEMBLY="GRCh38"
echo "##fileformat=VCFv4.2
##genome-build=GRCh38
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       91297378        .       G       C       10000.00        .       ." > dummy$ASSEMBLY.vcf
/home/admin/ensembl-vep/vep \
	--input_file "dummy$ASSEMBLY.vcf" \
	--output_file "dummy$ASSEMBLY.tsv" \
	--assembly "$ASSEMBLY" \
	--species homo_sapiens \
	--merged --use_given_ref \
	--fa .vep/homo_sapiens_merged/105_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz \
	--everything \
	--cache \
	--nearest transcript

# Output files

![image](https://user-images.githubusercontent.com/43095157/199184644-f06b2dc1-3b8f-4341-b46f-41c9ce0bcd00.png)

![image](https://user-images.githubusercontent.com/43095157/199184663-a6cd7a0a-10ba-4d47-bd81-a3b8c5899df8.png)

**Comment by dglemos** [comment]
Hi @barslmn,
Unfortunately, I cannot reproduce the issue. 
Are you using the cache from this directory http://ftp.ensembl.org/pub/release-108/variation/indexed_vep_cache/?
I tested VEP with cache homo_sapiens_merged_vep_108_GRCh37.tar.gz

**Comment by barslmn** [comment]
Yes, I am installing cache with 
perl INSTALL.pl -a acf -s homo_sapiens_merged -y GRCh37
but checking after installation is done there is only the fastq file in the ~/.vep/homo_sapiens_merged/108_GRCh37 folder. However vep seems to work fine :? 
I will try to manually download the cache.

**Comment by dglemos** [comment]
You should have a folder for each chromosome inside 108_GRCh37. 
Let me know how it goes after you download the cache manually.

**Comment by barslmn** [comment]
Manual download fixed the issue. Thanks a lot.
