### ISSUE TITLE
Using --minimal flag changes the annotation results for some variants

### ISSUE THREAD

**Issue by jvolanen** [Ensembl/ensembl-vep#1297]
## Describe the issue
Using --minimal flag changes the annotation results for some variants: rsid, gnomad population frequencies and custom annotations are missing. We rely on the --minimal flag and cannot remove it from the VEP command line.

### System
- VEP version: docker.io/ensemblorg/ensembl-vep:release_107.0
- VEP Cache version: 107

### Full VEP command line

The example VCF contains one variant (X:g.78011960dup) using two different forms

```
cat /tmp/ngs-6011.vcf | sudo docker run -i --rm \
-v /opt/vep_cache/:/opt/vep/.vep \
docker.io/ensemblorg/ensembl-vep:release_107.0 \
vep \
--cache \
--merged \
--species homo_sapiens \
--assembly GRCh38 \
--format vcf \
--output_file STDOUT \
--hgvsg \
--pick \
--check_existing \
--minimal \
--af_gnomadg \
--tab \
--fields Uploaded_variation,Location,Allele,Existing_variation,GIVEN_REF,USED_REF,HGVSg,gnomADg_AF
```
Results:

```
## VEP command-line: vep --cache --merged --species homo_sapiens --assembly GRCh38 --format vcf --output_file STDOUT --hgvsg --pick --check_existing --minimal --af_gnomadg --tab --fields Uploaded_variation,Location,Allele,Existing_variation,GIVEN_REF,USED_REF,HGVSg,gnomADg_AF
#Uploaded_variation     Location        Allele  Existing_variation      GIVEN_REF       USED_REF        HGVSg   gnomADg_AF
correct X:78011947-78011948     T       rs373689911     -       -       X:g.78011960dup 0.003265
incorrect       X:78011948-78011949     T       -       -       -       X:g.78011960dup -
```

When the --minimal flag is removed the result is correct:
```
## VEP command-line: vep --cache --merged --species homo_sapiens --assembly GRCh38 --format vcf --output_file STDOUT --hgvsg --pick --check_existing --af_gnomadg --tab --fields Uploaded_variation,Location,Allele,Existing_variation,GIVEN_REF,USED_REF,HGVSg,gnomADg_AF
#Uploaded_variation     Location        Allele  Existing_variation      GIVEN_REF       USED_REF        HGVSg   gnomADg_AF
correct X:78011947-78011948     T       rs373689911     -       -       X:g.78011960dup 0.003265
incorrect       X:78011948      TT      rs373689911     T       T       X:g.78011948dup 0.003265
```

### Data files (if applicable)
Input file
```
##fileformat=VCFv4.2
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT
X       78011947        correct A       AT      .       .       .       .
X       78011947        incorrect       AT      ATT     .       .       .       .
```

**Comment by dglemos** [comment]
Hi @jvolanen,
For VCF input VEP assumes the variants are represented at their most 5' representation. 
The first variant `A/AT` is represented like that, however the second variant `AT/ATT` is not. When VEP applies the minimal flag  `A/AT` is converted to `-/T` with start = 78011947 and end = 78011948; while `AT/ATT` is converted to `T/TT` start = 78011948 and end = 78011949.

We will investigate further but for now you should normalize the variants before running a VEP annotation. You can use bcftools to normalize a VCF file with the following command:
`cat input.vcf | vcf-annotate -n > output.vcf`

**Comment by dglemos** [comment]
Could you please let us know how did you get these variants? The second variant is the same as the first variant just with a different representation. Is there a reason for you having the same variant twice?

According to the VCF format specification, an insertion should include the preceding allele as you have in the first variant **A**/**A**T but in your case the second variant includes two alleles **AT**/**AT**T.

**Comment by jvolanen** [comment]
Hi @dglemos 

The variants are from a BWA-Mutect2 pipeline. We don't know why we sometimes get different representations for a variant. 
At the moment we are investigating to add `vcf-annotate -n` to the pipeline.

**Comment by dglemos** [comment]
Hi @jvolanen,
We recommend a normalisation before running VEP. For a correct annotation, it's very important the VCF follows the specification for variant representation. 
I'm going to close the issue for now but feel free to open a new issue if you have more questions.

Best wishes,
Diana
