### ISSUE TITLE
Feature request: most severe in filter script

### ISSUE THREAD

**Issue by martiliasf** [Ensembl/ensembl-vep#13]
I know the ```--most-severe``` flag exists during the primary VEP run, but it would nice if something similar existed for the filter script. 

I.e., for a given "uploaded variation", if there are multiple entries, which of these is most severe.

**Comment by willmclaren** [comment]
Currently the filter script considers one variant at a time, so it would require a fair amount of coding (or hacking) to do as you suggest.

I'd also point out the perils of using something like `--most_severe` - it is not uncommon for the transcript that produces the most severe consequence to be one that is not well supported, with the most severe consequence amongst other well supported transcripts being one of a much lower rank.

I'd recommend instead using `--flag_pick` (or one of the related flags, `--flag_pick_allele` or `--flag_pick_allele_gene`). This instead tags one of the entries with a `PICK=1` flag that accounts for how well transcripts are supported.

http://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick

**Comment by jamie-m-a** [comment]
Hi @martiliasf I'm closing this issue as I believe Will provided a solution and there has been no follow up in several years.
