### ISSUE TITLE
Support multi-platform docker images

### ISSUE THREAD

**Issue by zhx828** [Ensembl/ensembl-vep#1304]
## Describe the issue
This is not an issue but a feature request. Our team at MSK that builds cBioPortal, OncoKB, Genome-Nexus etc. is interested to deploy our apps on AWS graviton processors. In order to do that, we need to build all docker images based on at least linux/amd64, linux/arm64. Our app Genome-Nexus is built on top of VEP, therefore I'm reaching out to see whether multi-platform images can be supported here.

We have made some progress by using a github action combining docker buildx/QEMU for the purpose. I'm wondering whether the group is interested. I don't think github action is used to build docker image? I'm happy to help if you can give me few pointers on how the group builds the docker image. Thank you for your time.

- https://github.com/genome-nexus/genome-nexus/pull/641
- https://github.com/cBioPortal/cbioportal/pull/9890

**Comment by nuno-agostinho** [comment]
Hey @zhx828,

Let me start by thanking you for your interest in VEP Docker for ARM platforms!

We are currently using DockerHub's Automated Builds to build the image based on our GitHub repo's [Dockerfile](https://github.com/Ensembl/ensembl-vep/blob/release/108/docker/Dockerfile). Unfortunately, DockerHub doesn't allow to build for multiple platforms, despite [feature requests from multiple users](https://github.com/docker/roadmap/issues/109).

Given the inertia on part of DockerHub's team to support that feature, we have looked into using GitHub Actions to build multi-platform Docker images. The links you sent seem great examples that we may look into for inspiration if we decide to go this route.

Even so, be mindful that we do not consider this feature a priority as the `linux/amd64` VEP Docker image still works in other platforms. I also think we have a bug when building the Docker image for ARM given that a Perl dependency ([`Bio::DB::BigFile`](https://metacpan.org/pod/Bio::DB::BigFile)) silently fails to install. We will have to fix this to offer proper support to ARM platforms.

I will write here if we have any news on this matter. Have a great day!

Kind regards,
Nuno

**Comment by relyativus** [comment]
Hey @nuno-agostinho,
We're also interested in this feature request. Do you have more information regards why the BigFile fails to install on arm platform? 
After trying to build the image on Mac M1, I getting the following error from vep command:
`Can't locate Bio/EnsEMBL/Registry.pm in @INC (you may need to install the Bio::EnsEMBL::Registry module) (@INC contains: /opt/vep/src/ensembl-vep/modules /opt/vep/src/ensembl-vep /etc/perl /usr/local/lib/aarch64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/aarch64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/aarch64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/aarch64-linux-gnu/perl-base) at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 58.
BEGIN failed--compilation aborted at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 58.
Compilation failed in require at /usr/share/perl/5.26/base.pm line 136.
        ...propagated at /usr/share/perl/5.26/base.pm line 158.
BEGIN failed--compilation aborted at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm line 56.
Compilation failed in require at /usr/share/perl/5.26/base.pm line 136.
        ...propagated at /usr/share/perl/5.26/base.pm line 158.
BEGIN failed--compilation aborted at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 71.
Compilation failed in require at /opt/vep/src/ensembl-vep/vep line 20.
BEGIN failed--compilation aborted at /opt/vep/src/ensembl-vep/vep line 20.
`
I did the build with a quite standard command:
`docker build -t vep_arm_experimental -f Docker/Docker-vep .`

Also, I saw MACHTYPE env var, but it doesn't seem to be used in the Dockerfile(maybe it's consumed by the tool internally)

Note: we're still on 97 https://github.com/Ensembl/ensembl-vep/blob/release/97/docker/Dockerfile
Appreciate any help

**Comment by relyativus** [comment]
Hi @nuno-agostinho 
Thanks for the quick reply.
I've noticed the MACHTYPE env var and tried to set it to arm64 manually, but the approach to determine it dynamically via $(uname -m) is much better!

But it seems like an issue with the missing dependencies I shared was due to an old version of vep we're using. In the INSTALL.pl, there's a check for updates. It is interactive, meaning it expects an input (yes/no) from the console if you're trying to build an older version and that seems to break the last RUN command from the Dockerfile. So I had to add **-n** to INSTALL.pl to skip the updates check and now it correctly installs all the dependencies and works! 
Thanks a lot for the help!

**Comment by nuno-agostinho** [comment]
Hi @relyativus, I am glad you made it work!

If you find any issues using VEP Docker on M1 Macs, please report them so we can help with any issues. We would like to make sure it is working fine so we can publish a Docker image for ARM platform soon. :)

Have a wonderful day!

Cheers,
Nuno

**Comment by zhx828** [comment]
> Hi @zhx828 and @relyativus,
> 
> We have merged a GitHub Action script to build a Docker image on `linux/amd64` and `linux/arm64` platforms for VEP 110 (to be released soon).
> 
> We changed our Docker image building process to use GitHub Actions and upload the resulting multi-platform image as [ensembl-vep](https://hub.docker.com/r/ensemblorg/ensembl-vep) in our Docker Hub.
> 
> I am going to close this now, but please feel free to open a new thread if you find any issues using the new Docker image.
> 
> Have a great day!
> 
> Cheers, Nuno

Thank you!
