### ISSUE TITLE
SIFT not available on GRCh38

### ISSUE THREAD

**Issue by pdl** [Ensembl/ensembl-vep#1307]
## Describe the issue

After installing 108.2, on GRCh38 (not 37) I have the error `SIFT not available` when attempting to annotate variants. It looks like there is a file on the FTP server for sift/polyphen for 107 which is not available from the equivalent 108 location:

https://ftp.ensembl.org/pub/release-107/variation/sift_polyphen/
https://ftp.ensembl.org/pub/release-108/variation/sift_polyphen/

### System
- VEP version: 108.2
- VEP Cache version: 108
- Perl version: As per image
- OS: Singularity, built from Docker image running on 18.04
- tabix installed Yes, in Docker image

### Full VEP command line
```
--offline --cache --format ensembl --no_escape --json -o STDOUT --no_stats --warning_file STDERR
--transcript_version --sift b --polyphen b --hgvs
--assembly GRCh38
--plugin dbNSFP,/opt/vep/.vep/PluginData/dbNSFP4.2a_grch38.gz,REVEL_score
--plugin CADD,/opt/vep/.vep/PluginData/whole_genome_SNVs.tsv.gz,/opt/vep/.vep/PluginData/gnomad.genomes.r3.0.indel.tsv.gz
--plugin SpliceAI,snv=/opt/vep/.vep/PluginData/spliceai_scores.raw.snv.hg38.vcf.gz,indel=/opt/vep/.vep/PluginData/spliceai_scores.raw.indel.hg38.vcf.gz
```

### Full error message
> Including the warnings, if available

Please excuse the surrounding JSON.

```
{
  time: 2022-11-21T08:13:51.136Z,
  error: '\n' +
    '-------------------- EXCEPTION --------------------\n' +
    'MSG: ERROR: SIFT not available\n' +
    '\n' +
    'STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::check_sift_polyphen /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:168\n' +
    'STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::new /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:121\n' +
    'STACK Bio::EnsEMBL::VEP::CacheDir::get_all_AnnotationSources /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:150\n' +
    'STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:122\n' +
    'STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:92\n' +
    'STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170\n' +
    'STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128\n' +
    'STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:199\n' +
    'STACK toplevel /opt/vep/src/ensembl-vep/vep:240\n' +
    'Date (localtime)    = Mon Nov 21 08:13:51 2022\n' +
    'Ensembl API version = 108\n' +
    '---------------------------------------------------\n',
  variants: [
    {
      release: '108',
      assembly: 'GRCh38',
      chr: '1',
      start: '12345',
      end: '12345',
      ref: 'C',
      alt: 'T'
    }
  ]
}
```

**Comment by pdl** [comment]
Two thoughts:

- the file should be present on the FTP and it would be good if there were a post-release check on Ensembl's side to make sure that the files on the FTP are the ones expected, as it seems to be a recurring issue that not everything is there: #932 #1152 #1220 #1285 #1288
- It also feels odd that INSTALL.pl succeeds when the file is not present

**Comment by nakib103** [comment]
Hi @pdl,

Thanks for your query!

First of all, the FTP file you are looking at is only published for e107. In e107 SIFT and Polyphen-2 scroes for new transcripts were missing. That's why we published a separate db with those predictions which could be used with `PolyPhen_SIFT` VEP plugin. In e108 this has been fixed.

The issue you are facing seems to stem from the cache. Could you please look into `info.txt` file in the installed cache directory and check if you can see SIFT related information there?

Best regards,
Nakib

**Comment by pdl** [comment]
Ah, apologies, and thanks for that prompt @nakib103: it looks like the install failed silently: info.txt is missing; looking a bit deeper, not all the chromosomes are there either. I've added some code on my end to check whether the info.txt file exists rather than assuming the return value of INSTALL.pl is sufficient. I'll dig into why it's not working and perhaps open a separate issue if required.
