### ISSUE TITLE
What is the difference between cache files for homo_sapiens?

### ISSUE THREAD

**Issue by QANGFQ** [Ensembl/ensembl-vep#1309]
Hello,
I have a question about cache files for species/files.

There are three types of cache files for homo sapiens GRCh37 :
1. homo_sapiens_merged_vep_105_GRCh37.tar.gz
2. homo_sapiens_refseq_vep_105_GRCh37.tar.gz
3. homo_sapiens_vep_105_GRCh37.tar.gz

What is the difference between them?
Is this difference a variant notation(nomenclature)?

Does "_refsetq_vep" file notate it like NM_number?
Does "_vep" file notate it like ENSTnumber?
Does "_merged_vep" file notate it as both NM_number and ENSTnumber?

Yours sincerely,
QANGFQ

### System
- VEP version: 105 
- Perl version: 5.26.2
- OS: CentOS
- tabix installed ? Y

**Comment by diegomscoelho** [comment]
Hi @QANGFQ,

Refseq cache will use RefSeq transcripts nomenclature, VEP will use Ensembl transcripts nomenclature and merged will use both. Refseq cache has not all information from VEP only cache. And "Yes" for last three questions.
You may check more information on:
https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache
https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#refseq

I would also advise you to use VEP api + cache last version (108).

Regards, @diegomscoelho

**Comment by QANGFQ** [comment]
Thanks for the quick and detailed reply and your advice!

Regards, 
QANGFQ

**Comment by diegomscoelho** [comment]
Hi @QANGFQ,

If you have any other question, please feel free to comment here. I'm closing this issue now.

Regards, @diegomscoelho
