### ISSUE TITLE
more of a question about install vep without internet access.

### ISSUE THREAD

**Issue by kemin711** [Ensembl/ensembl-vep#1320]
In my case, I have download the zip file from the github, unzip, then perl INSTALL.pl -a a -n 

.... many routine normal output omitted ....

Downloading required Ensembl API files
 - fetching ensembl
 curl failed (000), trying to fetch using LWP::Simple
ERROR: Failed last resort of using HTTP::Tiny to download https://github.com/Ensembl/ensembl/archive/release/108.zip

When I download vep, tried to install on a China server, it blocked the access. Is it possible that I can download 108.zip manually,
and somehow provide to the INSTALL.pl script?

**Comment by kemin711** [comment]
673     my $module = $module_hash->{name};
 674 
 675     # do we need to update this?
 676     my $have_sub = $CURRENT_VERSION_DATA->{$module} ? ($CURRENT_VERSION_DATA->{$module}->{sub} || '') : '';
 677 
 678     my $url = $ENS_GIT_ROOT.$module.$ensembl_url_tail.$release_url_string.$archive_type;
 679 
 680     print " - fetching $module\n" unless $QUIET;
 681     my $target_file = $DEST_DIR.'/tmp/'.$module.$archive_type;
 682     mkdir($DEST_DIR.'/tmp/') unless -d $DEST_DIR.'/tmp/';
 683     print"target_file=$target_file from url=$url\n";
 684     eval {
 685       download_to_file($url, $target_file) unless -e $target_file;
 686       #my $tmpbasename=basename($target_file);
 687       #copy($target_file, "./archive/$tmpbasename");
 688    };
 689    if ($@) {
 690       my $tmpbasename=basename($target_file);
 691       copy("./archive/$tmpbasename", $target_file);
 692    }
 693     print " - unpacking $target_file\n" unless $QUIET;
 694     unpack_arch("$DEST_DIR/tmp/$module$archive_type", "$DEST_DIR/tmp/");
I made little modifications to the code. In this way, the required zip files are in archive.  If download fails, then it can use the file from the archive directory. Not sure this solution is acceptable or not.

**Comment by diegomscoelho** [comment]
Hi @kemin711,

Can you try first using zip from last release version (https://github.com/Ensembl/ensembl-vep/archive/refs/tags/release/108.2.zip). A few alterations in `INSTALL.pl` were introduced in release 108 tag versions.

Regards, @diegomscoelho

**Comment by diegomscoelho** [comment]
Hi @kemin711,

Closing this issue now! If you still have a problem, please feel free to comment here or open a new issue.

Best, Diego
