### ISSUE TITLE
Installing ensembl VEP on MacOS Monterrey

### ISSUE THREAD

**Issue by akr55** [Ensembl/ensembl-vep#1326]
## Describe the issue
Won't install. seems to get stuck with clang-4.0, but I've installed updated clang using brew and when I ask clang or gcc --version, I have a far updated version. Below is error message I get when trying to install software with "perl INSTALL.pl"

 - checking out HTSLib
fatal: destination path 'htslib' already exists and is not an empty directory.
 - building HTSLIB in ./htslib
In /Users/andrewressler/ensembl-vep/htslib
make: Nothing to be done for `all'.
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.11 - moving files to ./biodbhts
 - making Bio::DB:HTS
clang-4.0: error: invalid version number in '-mmacosx-version-min=12.4'
Warning: ExtUtils::CBuilder not installed or no compiler detected
Proceeding with configuration, but compilation may fail during Build

Checking prerequisites...
  requires:
    !  Bio::Root::Version is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Run 'Build installdeps' to install missing prerequisites.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.11'
Building Bio-DB-HTS
Error: no compiler detected to compile 'lib/Bio/DB/HTS.c'.  Aborting

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: [] 
- VEP Cache version: [e.g. 98]
- Perl v 5.32.0
- OS: Monterrey

**Comment by diegomscoelho** [comment]
Hi @akr55,

Not sure which version are you using, can you try to use last version (https://github.com/Ensembl/ensembl-vep/archive/refs/tags/release/108.2.tar.gz)?

Regards, @diegomscoelho

**Comment by akr55** [comment]
Also, to add onto that, when I check clang --version I get the below.

[image: image.png]

gcc --version I get the below.

[image: image.png]

**Comment by diegomscoelho** [comment]
Hi @akr55,

I can't see the images you tried to post images here on github. It only appears:
[image: image.png].

![image](https://user-images.githubusercontent.com/10541523/208398213-5f929aef-8e51-4d23-b188-1c54e66b8c2b.png)


Anyway, it looks like your BioPerl (https://github.com/bioperl/bioperl-live) wasn't installed properly at some point. Can you try to follow this API installation: https://www.ensembl.org/info/docs/api/api_installation.html

Besides that we have also a docker image to avoid this dependencies problems:
https://hub.docker.com/r/ensemblorg/ensembl-vep

Best, @diegomscoelho

**Comment by akr55** [comment]
I followed api installation exactly 3X and tried a few different ways.
Still stopping on compiling and saying i don't have proper compiler with
clang version too low.

I'll try with the docker.

**Comment by diegomscoelho** [comment]
Hi @akr55,

Can you also try to follow these steps (https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#macos) before installing VEP?

Best, @diegomscoelho

**Comment by diegomscoelho** [comment]
Hi @akr55,

Closing this issue now! If you are still not able to install VEP on MacOS Monterrey, please feel free to comment here or open a new issue!

Regards, @diegomscoelho
