### ISSUE TITLE
Cache directory not found despite --dir_cache used

### ISSUE THREAD

**Issue by robertw-hihm** [Ensembl/ensembl-vep#1327]
## Describe the issue
Installed ensembl-vep 108 via perlbrew using perl 5.26.2 on RHEL8

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 108
- VEP Cache version:108
- Perl version: 5.26.2 (via perlbrew, newly installed this week)
- OS: RHEL8
- tabix installed ? YES

### Full VEP command line
```
./vep -i /datastore/Rob/ENSEMBL_VEP/KLOEPPER/AANNORM041241201279.X1.g.bcft_view_convert_annot.vcf -o /datastore/Rob/ENSEMBL_VEP/KLOEPPER/VEPoutputAANNORM041241201279.X1.g.bcft_view_convert_annot.vcf --offline --symbol --protein --gene_phenotype --regulatory --af --max_AF --species Bos_taurus --dir_cache /home/robert/.vep --cache --vcf --fork 16

```

### Full error message
-------------------- EXCEPTION --------------------
MSG: ERROR: Cache directory /home/robert/.vep/Bos_taurus not found

STACK Bio::EnsEMBL::VEP::CacheDir::dir /home/robert/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:305
STACK Bio::EnsEMBL::VEP::CacheDir::init /home/robert/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:219
STACK Bio::EnsEMBL::VEP::CacheDir::new /home/robert/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /home/robert/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:116
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/robert/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:92
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/robert/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /home/robert/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::run /home/robert/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel ./vep:240
Date (localtime)    = Fri Dec 16 09:08:21 2022
Ensembl API version = 108

### Data files (if applicable)
They include:
- The input file
- The output file
- The custom file(s)
You can provide a sample of them

**Comment by diegomscoelho** [comment]
Hi @robertw-hihm,

I think you might have used wrong species name, instead of:
`--species Bos_taurus`
try:
`--species bos_taurus`

Did you have downloaded cache files? - You can find those files here.
https://ftp.ensembl.org/pub/release-108/variation/indexed_vep_cache/

For Bos Taurus:
https://ftp.ensembl.org/pub/release-108/variation/indexed_vep_cache/bos_taurus_vep_108_ARS-UCD1.2.tar.gz

Regards, @diegomscoelho

**Comment by robertw-hihm** [comment]
Hi again,

I guess I wasn’t tired or stupid, just used to running this on my Mac where the species name Bos_taurus works just fine!

But again, thanks for your help!

Best,
Rob

Fra: Rob Wilson ***@***.***>
Dato: fredag, 16. desember 2022 kl. 11:01
Til: Ensembl/ensembl-vep ***@***.***>
Emne: Svar: [Ensembl/ensembl-vep] Cache directory not found despite --dir_cache used (Issue #1327)
Hi Diego,

Sorry for being stupid and thanks for your help! I must have been tired last night; everything is working fine now…

Best,
Rob

Fra: Diego Coelho ***@***.***>
Dato: fredag, 16. desember 2022 kl. 10:51
Til: Ensembl/ensembl-vep ***@***.***>
Kopi: Rob Wilson ***@***.***>, Mention ***@***.***>
Emne: Re: [Ensembl/ensembl-vep] Cache directory not found despite --dir_cache used (Issue #1327)

Hi @robertw-hihm<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frobertw-hihm&data=05%7C01%7Crobert.wilson%40inn.no%7C789e43984b5948e6b56908dadf4ab689%7Cd45cfa45904a497297413335dc0372b4%7C0%7C0%7C638067810605591588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mQqq%2Fc27jBkFc2LSUu2Nmx%2FDmVM6i2EW9VdrRPN9fP0%3D&reserved=0>,

I think you might have used wrong species name, instead of:
--species Bos_taurus
try:
--species bos_taurus

Did you have downloaded cache files? - You can find those files here.
https://ftp.ensembl.org/pub/release-108/variation/indexed_vep_cache/<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fftp.ensembl.org%2Fpub%2Frelease-108%2Fvariation%2Findexed_vep_cache%2F&data=05%7C01%7Crobert.wilson%40inn.no%7C789e43984b5948e6b56908dadf4ab689%7Cd45cfa45904a497297413335dc0372b4%7C0%7C0%7C638067810605591588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IoqeI16rEx4IccvuRE0TeIaM7205eMVVcRfpCYZe3pc%3D&reserved=0>

For Bos Taurus:
https://ftp.ensembl.org/pub/release-108/variation/indexed_vep_cache/bos_taurus_vep_108_ARS-UCD1.2.tar.gz<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fftp.ensembl.org%2Fpub%2Frelease-108%2Fvariation%2Findexed_vep_cache%2Fbos_taurus_vep_108_ARS-UCD1.2.tar.gz&data=05%7C01%7Crobert.wilson%40inn.no%7C789e43984b5948e6b56908dadf4ab689%7Cd45cfa45904a497297413335dc0372b4%7C0%7C0%7C638067810605591588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=L4pIFHRDPfYQZthKTzuthksMI%2BR6H%2F%2BejrSN2%2BLtGG0%3D&reserved=0>

Regards, @diegomscoelho<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdiegomscoelho&data=05%7C01%7Crobert.wilson%40inn.no%7C789e43984b5948e6b56908dadf4ab689%7Cd45cfa45904a497297413335dc0372b4%7C0%7C0%7C638067810605591588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8P9%2B0dHSbXndK4z1cqmqxtrhU2kubDpd%2Buio%2BWgrLxA%3D&reserved=0>

**Comment by diegomscoelho** [comment]
Hi @robertw-hihm,

Great to hear it's working now. Closing this issue, if you have another question about this issue feel free to comment here.

Best, @diegomscoelho
