### ISSUE TITLE
Error when installing plugins

### ISSUE THREAD

**Issue by henrikstranneheim** [Ensembl/ensembl-vep#133]
When executing:
```
perl INSTALL.pl --AUTO p --PLUGINS UpDownDistance,LoFtool,MaxEntScan
WARNING: Unable to carry out version check for ensembl-vep
Can't use an undefined value as an ARRAY reference at INSTALL.pl line 1504.
```
It seems like the installation is trying to download this file:
https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/90

which does not exist.

If I comment this line out in INSTALL.pl:
download_to_file($plugin_url_root.'/plugin_config.txt', $plugin_config_file);

and supply an old plugin_config.txt in .vep/Plugins/ dir. The plugins seems to work fine.

Is there another syntax to install plugins that I should be using instead this?

**Comment by aparton** [comment]
Hi Henrik,

Thank you for the issue report. It looks like the installation is having trouble constructing the URL to obtain the plugin config file.

Can you please update your copy of VEP to the latest release (91) and let me know if you still see the same issue? 

Kind Regards,
Andrew

**Comment by henrikstranneheim** [comment]
I reinstalled everything using:
Versions:
  ensembl              : 91.18ee742
  ensembl-funcgen      : 91.4681d69
  ensembl-io           : 91.923d668
  ensembl-variation    : 91.c78d8b4
  ensembl-vep          : 91.2

And the issue is gone. I will switch to 91.2 and hope that the actual analyses goes fine as well. Thanks!

**Comment by aparton** [comment]
Hi Henrik,

Excellent, glad that solved the problem.

Kind Regards,
Andrew
