### ISSUE TITLE
Slow FTP download

### ISSUE THREAD

**Issue by umasstr** [Ensembl/ensembl-vep#1332]
I've attempted to download the newest VEP annotation on my local machine, my university's server, and a cloud bucket. Strangely, all seem to be capped at <700kbps.

```
curl -O https://ftp.ensembl.org/pub/release-108/variation/indexed_vep_cache/homo_sapiens_vep_108_GRCh38.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 21.2G    0 7171k    0     0   641k      0  9:39:32  0:00:11  9:39:21  668k
```

As a reference, I tested a dropbox link for a large file. This was orders of magnitude faster on all machines:

```
test.bam               24%[===========>                                      ]   1.58G  94.3MB/s    eta 82s
```

I also tried downloading from a USA public repository. This also allowed for much, much faster downloads:

```
time fasterq-dump -p -e 15 SRR000001
join   :|-------------------------------------------------- 100%
concat :|-------------------------------------------------- 100%
spots read      : 470,985
reads read      : 1,883,940
reads written   : 707,026
reads 0-length  : 468,635
technical reads : 708,279
real    0m 26.26s
user    0m 4.82s
sys     0m 4.15s

 du -sh SRR000001_*.fastq
82.7M   SRR000001_1.fastq
92.0M   SRR000001_2.fastq
```

If there's another way to download these files—or if anyone is aware of another host—I'd be very appreciative for any tips. I'd like to use the most up-to-date annotations but spending >9hrs per download is just too burdensome. Thank you in-advance for your time and help!

**Comment by olaaustine** [comment]
Hi @umasstr,
Thank you for your query. 
Ensembl FTP site does not have mirrors.
I suggest you check with your local networking folks to see if they can shed some light.
Let us know if you have any other queries or issues.
Thank you,
Ola

**Comment by alicedb2** [comment]
I have the exact same issue. I've tried downloading it from 3 different networks: my home internet, a US R1 university network, and the Digital Research Alliance of Canada network. The download speed capped around 700kB/sec on all 3.

**Comment by nakib103** [comment]
Hi @alicedb2 ,

Are you facing this often times or is it always the same speed? 
It could be a network issue - can you check with your network team.

Best regards,
Nakib

**Comment by alicedb2** [comment]
Speed is always ~600 kB/s or less on every network. @umasstr and I have tried on a total of 7 different networks with the same outcome each time, so I'm absolutely sure it's not an issue with us. Moreover I was able to increase the download speed using segmented download, meaning I was able to open 10 connections, each going at ~600 kB/s, so it seems it's a per-connection issue or there's throttling on the side of the ensembl ftp server.

**Comment by nakib103** [comment]
Hello @alicedb2 ,

We have contacted our internal network team and they are going to check about this issue. I will get back to you once I hear back from them.

**Comment by Hoeze** [comment]
@nakib103 Are there any news? We have the same issue.

**Comment by nakib103** [comment]
Hello, 

I now have some update that I can share with you. Our network team have confirmed identifying sub-performance on FTP download on network outside of EBI. Identifying and resolving the issue may not happen very soon. But there is an alternative to this for now.

You can use the Globus platform. Our Ensembl public FTP data is also hosted there and you can have faster download speed (I achieved 4MB/s on my network). 
- First login here - https://www.globus.org/ 
- Go to 'EMBL-EBI Public Data' collection
- Go to ensemblorg/pub and directory will match http://ftp.ensembl.org/pub/ FTP link

Best regards,
Nakib

**Comment by nakib103** [comment]
I will close this issue for now. Please re-open or create a new ticket if you face any further problem.
