### ISSUE TITLE
VEP install error

### ISSUE THREAD

**Issue by CaptainLabMan** [Ensembl/ensembl-vep#1333]
## Describe the issue
when trying to run the:
perl INSTALL.pl 
command, the error:
cram/cram_io.c:61:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
          ^~~~~~~~
1 error generated.
make: *** [cram/cram_io.o] Error 1
Compile didn't complete. No libhts.a library file found at INSTALL.pl line 881.

### System
- OS: MacOS 13, MacBook M1

### Full error message
 - building HTSLIB in ./htslib
In /Users/andrejnekrasov/pro/csp/modules/ensembl-vep/htslib
echo '/* Default config.h generated by Makefile */' > config.h
echo '#define HAVE_LIBBZ2 1' >> config.h
echo '#define HAVE_LIBLZMA 1' >> config.h
echo '#define HAVE_LZMA_H 1' >> config.h
echo '#define HAVE_FSEEKO 1' >> config.h
echo '#define HAVE_DRAND48 1' >> config.h
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o kfunc.o kfunc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o knetfile.o knetfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o kstring.o kstring.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o bcf_sr_sort.o bcf_sr_sort.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o bgzf.o bgzf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o errmod.o errmod.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o faidx.o faidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hfile.o hfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.9-dirty"' > version.h
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hts.o hts.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hts_os.o hts_os.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o md5.o md5.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o multipart.o multipart.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o probaln.o probaln.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o realn.o realn.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o regidx.o regidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o sam.o sam.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o synced_bcf_reader.o synced_bcf_reader.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcf_sweep.o vcf_sweep.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o tbx.o tbx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o textutils.o textutils.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o thread_pool.o thread_pool.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcf.o vcf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcfutils.o vcfutils.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_decode.o cram/cram_decode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_encode.o cram/cram_encode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_external.o cram/cram_external.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_index.o cram/cram_index.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c:61:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
         ^~~~~~~~
1 error generated.
make: *** [cram/cram_io.o] Error 1
Compile didn't complete. No libhts.a library file found at INSTALL.pl line 881.

**Comment by olaaustine** [comment]
Hi @CaptainLabMan ,
I'm sorry to hear you are having problems installing VEP.
It looks like something when wrong during the automated installation of htslib through the VEP installation script.
Could you please make sure you installed the prerequisites required by macOS? You can find the instructions on this page: https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#macos
Thank you,
Ola.

**Comment by CaptainLabMan** [comment]
Yes, I did everything according to the instructions, still the same error, even did it all over again, the same thing.
Maybe I'm somehow not exporting the path to htslib?
For this I do:
export DYLD_LIBRARY_PATH=/Users/andrejnekrasov/pro/csp/tools/vep/ensembl-vep
When I call the echo $DYLD_LIBRARY_PATH command, I see:
/Users/andrejnekrasov/pro/csp/tools/vep/ensembl-vep
But after the shell is reloaded (if it is reloaded), this line disappears when the same echo $DYLD_LIBRARY_PATH command is called, is this normal? Could this be a problem?
I don't understand what could be the problem

**Comment by CaptainLabMan** [comment]
Maybe I can somehow use htslib installed in a different way, if this is the problem, the htslib installation is successful through brew

**Comment by CaptainLabMan** [comment]
Oh my god, I managed to install vep, I downloaded htslib from here https://github.com/samtools/htslib and installed it according to the instructions (well, almost), before that I deleted the folder with this library from the vep folder, replacing it with the folder given repository - https://github.com/samtools/htslib/blob/develop/INSTALL
Three points are described in the Basic Installation section, but their use does not give positive results, I did this:
make
sudo make install
Then added again (because it was already empty) the path to DYLD_LIBRARY_PATH (export DYLD_LIBRARY_PATH=path to the htslib)
And I started the installation of vep with the perl INSTALL.pl --NO_TEST command

**Comment by CaptainLabMan** [comment]
Oh my god, I managed to install vep, I downloaded htslib from here https://github.com/samtools/htslib and installed according to the instructions (well, almost) - https://github.com/samtools/htslib/blob/develop/ INSTALL, before deleting the folder with this library from the vep folder, replacing it with the folder of this repository.
Three points are described in the Basic Installation section, but their use does not give positive results, I did this:
make
sudo make install
Then added again (because it was already empty) the path to DYLD_LIBRARY_PATH (export DYLD_LIBRARY_PATH=path to the htslib)
And I started the installation of vep with the perl INSTALL.pl --NO_TEST command

**Comment by olaaustine** [comment]
Hi @CaptainLabMan,
We are glad you were able to install VEP.
I will close this ticket now. 
Please reopen this or open another ticket if you have any more queries or issues.
Thank you
Ola.
