### ISSUE TITLE
Splice_region_variant annotation not added with splice_donor_5th_base_variant annotation

### ISSUE THREAD

**Issue by oleraj** [Ensembl/ensembl-vep#1345]
## Describe the issue
Since vep105 added new splice region variant annotations (i.e., splice_donor_region_variant, splice_donor_5th_base_variant, splice_polypyrimidine_tract_variant), variants that were previously annotated as splice_region_variant no longer have this annotation.  (Note that the title just refers to splice_donor_5th_base_variant annotation since that is the example I have in the attached file, but I've also noticed this issue with splice_donor_region variants; I haven't tested thoroughly with splice_polypyrimidine_tract_variants to see if that applies to this issue.) The variants do match the definition of [splice_region_variant](http://www.sequenceontology.org/browser/current_release/term/SO:0001630), so they should still have the splice_region_variant annotation (with the exception of some polypyrimidine tract variants that extend beyond 8bp of the intron).  Adding this back as appropriate will provide backwards compatibility.  Possibly an independent check for whether a variant meets the definition of splice_region_variant could be added.

## Additional information
In addition, I noticed that splice_region_variant is ranked as higher consequence than these new splice region variant annotations.  https://useast.ensembl.org/info/genome/variation/prediction/predicted_data.html#consequences
Since these regions are (mostly) more specific than splice_region, I would suggest this order instead:

splice_donor_5th_base_variant
splice_donor_region_variant
**splice_region_variant**
splice_polypyrimidine_tract_variant

OR

splice_donor_5th_base_variant
splice_donor_region_variant
splice_polypyrimidine_tract_variant
**splice_region_variant**

### System
- VEP version: 108
- VEP Cache version: 108
- Perl version: 5.26
- OS: RHEL 7.9
- tabix installed ? Yes, v1.13

### Full VEP command line
```
in=test.GRCh38.vcf.gz; \
  out=${in/.vcf.gz/}.vep.vcf.gz; \
  $EBROOTVEP/ensembl-vep/vep --fork 8 --cache --compress_output bgzip --dir $EBROOTVEP/.vep  --assembly GRCh38 --offline --vcf  --fasta $EBROOTVEP/.vep/homo_sapiens/108_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz -i $in -o $out 
```

### Full error message
No error message, but sample output annotation looks like this (reformatted below for readability).  Specifically, these variants have splice_donor_5th_base_variant and intron_variant annotations, but no splice_region_variant annotation.

```
chr16	31487764	rs200228142	G	A	505.3	PASS ...	
,A|splice_donor_5th_base_variant&intron_variant|LOW|SLC5A2|ENSG00000140675|Transcript|ENST00000330498|protein_coding||7/13||||||||||1||HGNC|HGNC:11037
,A|splice_donor_5th_base_variant&intron_variant&NMD_transcript_variant|LOW|SLC5A2|ENSG00000140675|Transcript|ENST00000419665|nonsense_mediated_decay||7/11||||||||||1||HGNC|HGNC:11037
```

### Data files (if applicable)
- The input file
[test.GRCh38.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/10559399/test.GRCh38.vcf.gz)

- The output file
[test.GRCh38.vep.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/10559403/test.GRCh38.vep.vcf.gz)

**Comment by nuno-agostinho** [comment]
Hello @oleraj,

We avoid annotating variants based on generic terms as much as possible. In this case, VEP avoids annotating a `splice_region_variant` if a more specific term (such as `splice_donor_region_variant`) is available: https://github.com/Ensembl/ensembl-variation/blob/release/108/modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm#L540-L544

Moreover, the `splice_region_variant` is independent from `splice_polypyrimidine_tract_variant`, so you should come across both annotations in case of a variant that affects them both.

The change in ranking that you mentioned makes sense and we agree we need to review them. We currently have plans to assess the relevance of the ranks across all consequences in the near future.

Please tell me if you need further clarification. Thanks!

Kind regards,
Nuno

**Comment by oleraj** [comment]
Hi @nuno-agostinho,

Thanks for the reply and I'm glad to hear my suggestions of consequence ranking were helpful and that you plan to revisit that soon.

I think what you're saying about avoiding more generic terms makes sense in theory.  However I don't completely understand.  The way it's implemented seems a bit arbitrary since `splice_donor_region` and `splice_donor_5th_base_variant` variants also have the generic `intron_variant` term since it's also in the intron. Consistency might argue that `splice_donor_5th_base_variant` variants should also get `splice_donor_region` and `splice_region_variant` terms since it meets the definition of all three.  Or, alternatively, that the `intron_variant` term shouldn't be present because it's more generic?

Also, I wouldn't say that `splice_region_variant` is _independent_ from `splice_polypyrimidine_tract_variant` since they are overlapping in the -3 to -8 bases upstream of the acceptor (unless I'm missing something?).  To me this is analogous to `splice_donor_region` and `splice_region` where `splice_donor_region` is overlapping with `splice_region` in the +3 to +6 position downstream of the splice donor site.  I admit they are different since in the case of `splice_donor_region`, this is completely contained within what is defined as `splice_region`.  Perhaps you're saying that if a term is completely contained within another term then in that case you would use the more specific term?  (Again, if that is the rule, it doesn't seem to apply to the `intron_variant` term.) 

Interested to hear your thoughts.

Thanks!

Andrew

**Comment by nuno-agostinho** [comment]
Hi @oleraj!

> Consistency might argue that splice_donor_5th_base_variant variants should also get splice_donor_region and splice_region_variant terms since it meets the definition of all three. Or, alternatively, that the `intron_variant` term shouldn't be present because it's more generic?

We prefer the second option: we shouldn't show `intron_variant` in those cases. Looking at our [code](https://github.com/Ensembl/ensembl-variation/blob/release/108/modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm#L549-L554), it seems that we are currently returning `intron_variant` simply if a variant falls within an intron without considering other terms.

> Also, I wouldn't say that `splice_region_variant` is independent from `splice_polypyrimidine_tract_variant`.

Sorry for the lack of clarity: I meant that the way they are assigned they are "independent" in our code, as in: we report them both independently so a variant can be annotated with both simultaneously.

> Perhaps you're saying that if a term is completely contained within another term then in that case you would use the more specific term? (Again, if that is the rule, it doesn't seem to apply to the `intron_variant` term.)

Our intention is to follow the hierarchy of [Sequence Ontology](http://www.sequenceontology.org): if a child node is reported, we would not report their parent. In some cases, we also only report the term that is contained within another (even if they are not in a parent-child relationship; we may consider asking for revisions to the SO term hierarchy for theses cases).

Regardless, we are aware that we are not following this logic for some terms (such as `intron_variant`) given that this is a manual process on our side and we aim to review how we assign consequences to improve this.

Thanks for mentioning this and we hope to fix the issues you presented in a future release.

Hope this was clearer, but feel free to reply if you want to discuss further!

Best,
Nuno

**Comment by oleraj** [comment]
Hi @nuno-agostinho,

Thanks for the additional explanation, that does help to clarify.  I think a systematic approach as you mention respecting the hierarchy of SO sounds great, and glad to know you would also try to work with them to make revisions in the ontology as needed to keep things logical.

As a side note, I want to just says thanks for your team's work/maintenance on this tool, it's very valuable for us and critical for our workflow.

Best,
Andrew

**Comment by jamie-m-a** [comment]
I'm going to close this ticket now - we have plans to make appropriate revisions to the splicing consequences in upcoming releases. Thanks for you comments and feedback!
