### ISSUE TITLE
Plugins and forks: situations where data is lost

### ISSUE THREAD

**Issue by dennishendriksen** [Ensembl/ensembl-vep#1346]
In the [VEP documentation](https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html) it is stated in step 5 that:
```
When writing plugins be aware that while the VEP code attempts to preserve the state of any plugin-specific cached data between separate forks, there may be situations where data is lost. If you find this is the case, you should disable forking in the new() method of your plugin by deleting the "fork" key from the $config hash. 
```
What are these 'situations where data is lost'? In case data loss occurs, will VEP exit with an error?
Otherwise data loss events could easily go unnoticed. In that case: should disabled forking be the default in plugins?

**Comment by diegomscoelho** [comment]
Hi @dennishendriksen,

This was a comment related to ProteinSeqs output (https://github.com/Ensembl/VEP_plugins/issues/30), it's related to cache overwrite partially an output.

Most of plugins will not face an issue with fork usage and if it does have it will have an error message. If your new plugin is not writing something to a cache and it's just adding values to annotation, hardly it will have a problem with `--fork`. Therefore, remove fork from our plugins should not be default config.

Regards, @diegomscoelho
