### ISSUE TITLE
Missing homo_sapiens CHECKSUMs for vep/ release 107

### ISSUE THREAD

**Issue by bryce-turner** [Ensembl/ensembl-vep#1347]
## Describe the issue
Looks like similar issues were reported in #1285 #1220 #1163 though these specifically focused on indexed_vep_cache/. A similar issue exists in [release-107/variation/vep/](https://ftp.ensembl.org/pub/release-107/variation/vep/) however specifically all homo_sapiens_* files do not have checksums. It looks like this was partially resolved in release-108 (Missing GRCh37 though - see example image below)

## Additional information
Example (Missing all entries for homo_sapiens):
![image](https://user-images.githubusercontent.com/40504111/216802665-c5b7b6b9-54ba-4d4e-8f4b-30eea68e9c20.png)

Expectation (based on release-108):
![image](https://user-images.githubusercontent.com/40504111/216802696-a7d5ff19-dfc6-4fa7-b5ec-cd19d7d7bcdc.png)

### System
- VEP version: 107
- VEP Cache version: 107
- Perl version: NA
- OS: NA

**Comment by dglemos** [comment]
Hi @bryce-turner,
Thank you for letting us know. 
We are working on adding the missing checksums, I'll keep you updated.

**Comment by bryce-turner** [comment]
I see these were updated!
![image](https://user-images.githubusercontent.com/40504111/217091770-5a0d4f72-92b8-49f7-aae7-9a46ebdae682.png)


Thanks!
