### ISSUE TITLE
GRCh37 assembly is not available in 109 release

### ISSUE THREAD

**Issue by davmlaw** [Ensembl/ensembl-vep#1356]
https://ftp.ensembl.org/pub/release-109/variation/indexed_vep_cache/

This was reported for v108 in issue #1288 - however it appears it broke again for v109

**Comment by nakib103** [comment]
Hi @davmlaw,

Thanks for reporting, we will publish it shortly.

Best regards,
Nakib

**Comment by serge2016** [comment]
The same problem was with v106 also: https://github.com/Ensembl/ensembl-vep/issues/1152

**Comment by Stikus** [comment]
Looks like fixed?
![image](https://user-images.githubusercontent.com/41360525/218968641-590b5f22-b121-4d90-87a4-4fd2fbb87d14.png)

**Comment by nakib103** [comment]
Hi, 
Yes the v109 caches are already available. We are working on v106 caches.

**Comment by Stikus** [comment]
But they are in place, aren't they?
![image](https://user-images.githubusercontent.com/41360525/218993121-3aa886a6-ba6b-4a3e-b732-a7f613407f86.png)

**Comment by nakib103** [comment]
I think @serge2016 was talking about non-indexed cache - 
http://ftp.ensembl.org/pub/release-106/variation/vep/

**Comment by Stikus** [comment]
This folder has errors, you are right:
![image](https://user-images.githubusercontent.com/41360525/218994638-bdad55c6-544c-487f-86c2-fc89d5c1c0d2.png)

Old issue was mainly about indexed cache - and indexed was fixed, that's why I'm mistaken.

**Comment by alejandrogzi** [comment]
Hi guys,

I having a similar issue with the dog files (109 release):

`sudo docker run -t -i -v $HOME/Gits/vep_data:/data:Z ensemblorg/ensembl-vep INSTALL.pl -a cf -s canis_lupus_familiaris -y ROS_Cfam_1.0`

outputs: 

getting list of available cache files
downloading https://ftp.ensembl.org/pub/release-109/variation/indexed_vep_cache/canis_lupus_familiaris_vep_109_ROS_Cfam_1.0.tar.gz
Cannot open Local file /opt/vep/.vep/tmp/canis_lupus_familiaris_vep_109_ROS_Cfam_1.0.tar.gz: No such file or directory
 at /opt/vep/src/ensembl-vep/INSTALL.pl line 1315.
curl failed (000), trying to fetch using LWP::Simple
LWP::Simple failed (501), trying to fetch using HTTP::Tiny
ERROR: Failed last resort of using HTTP::Tiny to download https://ftp.ensembl.org:21/pub/release-109/variation/indexed_vep_cache/canis_lupus_familiaris_vep_109_ROS_Cfam_1.0.tar.gz

I have followed part of the solution described in #297 by just manually downloading files. Actually all dog files are indeed within the FTP: 

![Screenshot from 2023-02-17 13-21-15](https://user-images.githubusercontent.com/78838419/219748961-85806069-1d9c-499b-aa82-583a412e14d9.png)

Any thoughts on that?

Thanks in advance,
Alejandro

**Comment by nakib103** [comment]
Hi @alejandrogzi ,

Thanks for your query.

The first of your problem, VEP docker install we will soon be releasing a fix for that. 
You should still be able to manually download cache and run VEP with it. The error you are getting is because of default species in VEP - by default VEP have `homo_sapiens` for species. You should change the species and assembly using the `--species` and `--assembly` options respectively.

Best regards,
Nakib

**Comment by nakib103** [comment]
Hi @alejandrogzi, there is a new docker image available that should have fix for the issue you were having.
@serge2016, the human GRCh37 non-indexed cache files for e106 are generated and available in the FTP.

Let me know if you have any further issues.

**Comment by davmlaw** [comment]
Confirm that original issue is fixed - GRCh37 files located in https://ftp.ensembl.org/pub/release-109/variation/indexed_vep_cache/

If other problems still occur please raise in another issue
