### ISSUE TITLE
HGVS_OFFSET not given for intronic variants?

### ISSUE THREAD

**Issue by suzyhh** [Ensembl/ensembl-vep#1371]
## Describe the issue
I'm looking at how VEP is annotating INDELs in repetitive regions. I noticed a particular intronic variant on a + strand gene that was shifted 15bp in the HGVSc nomenclature, however the HGVS_OFFSET column was empty. I went back through my dataset and found that none of the intronic variants that had been 3' shifted in the HGVS had a value in the HGVS_OFFSET column.

I also tried running the first variant through web VEP and again didn't get a value in HGVS_OFFSET

Is this by design, or a bug? 

### System
- VEP version: Docker v108.2 running through a WDL task
- VEP Cache version: 108_GRCh38
- Perl version: [e.g. 5.26]
- OS: Ubuntu
- tabix installed ?

### Full VEP command line

```
vep --cache --offline \
-i ~{VCF} \
--dir_cache /opt/vep/.vep \
--dir_plugins /opt/vep/.vep/Plugins/ \
--vcf --merged --fasta $refFasta \
--assembly GRCh38 \
--no_stats \
--fork 16 \
--buffer_size 5000 \
-check_existing --hgvs --hgvsg --af --af_gnomadg --protein --uniprot --symbol --numbers \
--sift b --polyphen b --pubmed --show_ref_allele --variant_class --mane_select --transcript_version \
--plugin MaxEntScan,/opt/vep/.vep/fordownload,NCSS,SWA \
--plugin SpliceAI,snv=/opt/vep/.vep/mnt/data1/resources/spliceai/hg38/spliceai_scores.raw.snv.hg38.vcf.gz,indel=/opt/vep/.vep/mnt/data1/resources/spliceai/hg38/spliceai_scores.raw.indel.hg38.vcf.gz \
--plugin SpliceRegion \
--plugin NearestExonJB,max_range=100 \
--plugin REVEL,/opt/vep/.vep/new_tabbed_revel.tsv.gz \
--plugin SpliceDistance \
--custom /opt/vep/.vep/HGMD_Pro_2022.4_hg38.vcf.gz,HGMD,vcf,exact,0,CLASS,PHEN \
--force_overwrite \
-o ~{sampleId}_snvs.vep.vcf
```

### Data files (if applicable)
This is the variant I noticed first in the VCF with the 5' position, it's part of a 15bp tract of 'A's. 
```
14      56634842        rs10601913      CA      C       209.73  PASS
```
VEP gives this variant an HGVSc of NM_017799.4:c.1725-42del and an HGVSg of 14:g.56634857del which are both correctly 3' shifted, but no value is given in HGVS_OFFSET.

Many thanks for your help

**Comment by dglemos** [comment]
Hi @suzyhh,
This is not the intended behaviour. There is an issue reporting the HGVS offset for some hgvsc such as your example `NM_017799.4:c.1725-42del`.
We are going to work on a fix, I'll let you know when we have more details.

Best wishes,
Diana

**Comment by dglemos** [comment]
We have fixed the HGVS offset for the HGVSc. 
The fix will be available next release scheduled for summer. 

Best wishes,
Diana

**Comment by suzyhh** [comment]
Amazing, thank you so much for fixing it so promptly! :)
