### ISSUE TITLE
Problems installing VEP databases for local use (MySQL).

### ISSUE THREAD

**Issue by Marius101** [Ensembl/ensembl-vep#1372]
## Describe the issue
When following the instructions to install and set up the MySQL databases to run VEP on a local server/machine (https://www.ensembl.org/info/docs/webcode/mirror/install/ensembl-data.html) there are a few problems that came up:
1. Two of the directories/folders on Ensemble's FTP repository which are required to set up databases (As per the VEP installation instructions) for use locally are missing; Namely the 'ensemble_ontology_109' and 'ensembl_website_109' folders. I have searched multiple times through most of the Ensemble FTP site, but could not find these folders. According to the instructions, these folders are necessary databases to set up any VEP MySQL database. 
2. When attempting to initialize the 'ensembl_accounts' database or any other database (such as homo_sapiens_core_109_37) as per the instructions using the command: 
`mysql -u root ensembl_accounts < ensembl_accounts.sql`
the following error output is given:
ERROR 1109 (42S02) at line 17: Unknown table 'SESSION_VARIABLES' in information_schema

## Additional information
This issue was encountered when following the instructions listed here: https://www.ensembl.org/info/docs/webcode/mirror/install/ensembl-data.html

### System
- VEP version: 109 
- VEP Cache version: N/A
- Perl version: v5.34.0
- OS: Ubuntu
- tabix installed: YES

### Full error message
ERROR 1109 (42S02) at line 17: Unknown table 'SESSION_VARIABLES' in information_schema

**Comment by dglemos** [comment]
Hi @Marius101,
We would encourage you to use a cache wherever possible, using a cache is the most efficient way to use VEP. Caches are easier to download and set up ([documentation link](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache)).
Is there a particular reason you need to install the databases to run VEP?

**Comment by Marius101** [comment]
Hi @dglemos, 
Apologies for the delayed response, I will be using VEP using caches moving forward. 
Thank you for your reply and the recommendation
Kind regards.

**Comment by dglemos** [comment]
I'm glad that works for you. 
I'm going to close this issue but if you find any problem while setting up VEP please feel free to open a new ticket.

Best wishes,
Diana
