### ISSUE TITLE
enhancement: allow html AND text summary output?

### ISSUE THREAD

**Issue by jayoung** [Ensembl/ensembl-vep#1374]
hi there,

I have an enhancement suggestion - probably an easy one to implement.  

I like the _summary.html file that's produced - helps troubleshooting.  For other uses (constructing downstream reports containing other analyses summaries as well), I ALSO like the _summary.txt file we can get using the `--stats_text` option.

But it seems like there's no option to produce both _summary.txt  and _summary.html in a single VEP run - we have to choose one or the other (is that right?).  I'd love to be able to save both outputs.

thanks!

Janet

**Comment by dglemos** [comment]
Hi @jayoung,
The html stats is generated by default, but it is replaced by the text stats when using --stats_text. 
However, there is a way to produce the two types using both options:
```
--stats_text
--stats_html
```
I noticed this option is not documented - I'm going to look into how we can improve the documentation in the future.

Best wishes,
Diana

**Comment by jayoung** [comment]
Thanks, Diana - I should have tried that!    Yes, the documentation is a bit misleading: how about just deleting " in place of the HTML." in the `--stats_text` line of the doc?

Janet

**Comment by dglemos** [comment]
Yes, if you run with only `--stats_text` then it will replace the HTML, you'll also need to use `--stats_html` which is missing from the docs.

I'm glad it worked - I'm going to close the ticket but feel free to re-open it if you have more questions.

Best wishes,
Diana
