### ISSUE TITLE
Is gnomad_v3 an option now?

### ISSUE THREAD

**Issue by fyfreya** [Ensembl/ensembl-vep#1375]
I saw there is some work done last to have gnomad_v3 as an option. Is it part of the release now? If not, could you consider adding it? Thank you!

**Comment by likhitha-surapaneni** [comment]
Hi @fyfreya , 
Since `release/107` , the `af_gnomadg` option uses gnomAD genome v3.1.2 and `af_gnomade` uses gnomAD exome v2.1.  Hope this answers your question.

Kind regards,
Likhitha
