### ISSUE TITLE
Error when using vep with ClinVar database

### ISSUE THREAD

**Issue by bioinfo2016** [Ensembl/ensembl-vep#1380]
Hi ,

I used vep to annotate vcf sample using Clinvar and I got the following error:

MSG: ERROR: No format specified for custom annotation source /home/u1/.vep/clinvar.vcf.gz

System:
OS: Ubuntu
tabix: installed

### Full VEP command line
```
./vep -i ./inputPath/Input.vcf -o ./OutputPath/output.vcf --canonical  --offline --use_given_ref --force_overwrite   --check_existing  --custom  /home/u1/.vep/clinvar.vcf.gz,ClinVar,0,CLNSIG,CLNREVSTAT,CLNDN  --cache --everything --dir_cache /home/u1/.vep
```

### Full error message
MSG: ERROR: No format specified for custom annotation source /home/u1/.vep/clinvar.vcf.gz

STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /home/storage01/bin/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:209
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/storage01/bin/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:94
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/storage01/bin/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /home/storage01/bin/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::run /home/storage01/bin/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel ./vep:240
Date (localtime)    = Mon Mar 20 11:30:27 2023
Ensembl API version = 108

Thank you

**Comment by bioinfo2016** [comment]
Thanks for your reply,

I add all parameter including vcf and then I got the error below:
MSG: ERROR: New type "vcf" is not valid

Thanks

**Comment by jamie-m-a** [comment]
Hi @bioinfo2016 

I can't replicate your error using a copy of the ClinVar VCF we have locally, I'm wondering whether your ClinVar file might be corrupted? Can you try downloading it again and retrying perhaps?

Also, can I check which version of VEP you are using?

**Comment by bioinfo2016** [comment]
Hi @jamie-m-a 

I reinstalled ClinVar again and got the following error:
MSG: ERROR: Cannot use format vcf without Bio::DB::HTS::Tabix module installed

vep vesion: 108.2

Thanks

**Comment by jamie-m-a** [comment]
Hi @bioinfo2016 

So this is sort of progress! It looks like there was an issue with your previous ClinVar vcf. Regarding your new Tabix issue - have you added it to your PERL5LIB?

Something like: `export PERL5LIB=${PERL5LIB}:/location/of/HTSLIB`

**Comment by bioinfo2016** [comment]
You are right,

Regarrdsing Tabix , I add it , running echo $PERL5LIB I got :
:/home/storage01/bin/ensembl-vep:/home/storage01/bin/ensembl-vep:/home/storage01/bin/ensembl-vep/htslib:/home/storage01/bin/ensembl-vep/htslib/

**Comment by jamie-m-a** [comment]
If you're still getting the issue, it could be the case that you have multiple versions of HTSLib installed. When you installed VEP it should have installed HTSLib, unless you used the --NO_HTSLIB option.

If you installed VEP without that flag you could try removing your ensembl-vep directory, re-cloning it and then installing again, this time with the --NO_HTSLIB flag (so that in theory the only HTSLib is the separate one you installed).

Alternatively we have a docker version of VEP which bypasses these configuration issues, you can get the details here: https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker

**Comment by bioinfo2016** [comment]
Thank you 

It works, I reinstalled VEP with --NO_HTSLIB.

**Comment by jamie-m-a** [comment]
That's great to hear! I'll go ahead and close this ticket now. Please feel free to reach out to us if you have any further issues.
