### ISSUE TITLE
Adding fixed string flag as custom annotation instead of selecting field from VCF

### ISSUE THREAD

**Issue by jethror1** [Ensembl/ensembl-vep#1382]
Hi, I was wondering when using a vcf for custom annotation if it is possible to add a fixed string instead of selecting the field from the annotation vcf.

The use case for this is having a vcf to use for custom annotation and wanting to annotate on the presence of a variant in that vcf, but not select any of the INFO/FORMAT fields as these aren't consistent in the annotation vcf. For these I would just like to add an INFO field to identify presence as a FLAG type if possible?

Thanks

**Comment by olaaustine** [comment]
Hi @jethror1, 
I will be closing this issue now. 
Feel free to reopen this or open another ticket if you have another query. 
Thank you 
Ola.
