### ISSUE TITLE
Plugins installation and DBs

### ISSUE THREAD

**Issue by manolis2023** [Ensembl/ensembl-vep#1392]
Good morning,

I installed locally Ensemble VEP 109.3. I used to use conda but with that version there is something wrong with the installation. Testing the docker, require to download the dbs using FTP, something that is not allowed in my institution. In some steps during local installation also require FTP and as above I can not use it.

Installing the plugins, for some cases require to install the tools, for example dbNSFP and to download the db. Seems that this step is not automatic. How can I install dbNSFP and where can I find the db?

Thank you very much.

### System
- VEP version: 109.3
- OS: Ubuntu server 22.04

### Installation code
perl INSTALL.pl --CACHEDIR /mypath/ --SPECIES homo_sapiens_refseq --NO_TEST

**Comment by nakib103** [comment]
Hello @manolis2023 ,

Thank you for your query.

`VEP` can be run in two ways - using database and cache. Using cache is faster but requires you to download the cache files from the FTP. So, if you are unable to download files from FTP you can just use the database while running VEP. You would not need to download anything in this case - VEP will use the public database we host.
e.g. - `./vep --database -i input.txt -o output.txt`
More details can be found here - https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html 

Using plugin with VEP on the other hand will, most often than not, require you to download files and often do some processing on it. This steps are manual and the plugins comes with instruction (on the description header). For dbNSFP, for example, the [instruction](https://github.com/Ensembl/VEP_plugins/blob/release/109/dbNSFP.pm) include this -
```
 For release 4.3a:
 > version=4.3a
 > wget ftp://dbnsfp:dbnsfp@dbnsfp.softgenetics.com/dbNSFP${version}.zip
 > unzip dbNSFP${version}.zip
 > zcat dbNSFP${version}_variant.chr1.gz | head -n1 > h
 # GRCh38/hg38 data
 > zgrep -h -v ^#chr dbNSFP${version}_variant.chr* | sort -k1,1 -k2,2n - | cat h - | bgzip -c > dbNSFP${version}_grch38.gz
 > tabix -s 1 -b 2 -e 2 dbNSFP${version}_grch38.gz
``` 

You have to follow this instruction to prepare the data file. 

The docker should have plugins already installed but you can also install it via command -
```
perl INSTALL.pl -a p -g dbNSFP
```

Best regards,
Nakib

**Comment by BioinfoRDX** [comment]
Thank you very much!

**Comment by nakib103** [comment]
I will close this issue. If you face any further problem please re-open or create another issue.
