### ISSUE TITLE
SwissVar And Vep

### ISSUE THREAD

**Issue by bioinfo2016** [Ensembl/ensembl-vep#1393]
Hi

Is anyone know to annotate the variants from SwissVar using Vep. I need to report significance of the variants (disease or not) from
SwissVar.

Thanks in advance .

**Comment by nakib103** [comment]
Hello @bioinfo2016 ,

Thank you for your query!

VEP has a option called `--gene_phenotype` which can give associated disease/phenotype with the gene the variants overlaps. See more [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_gene_phenotype).

We also have a plugin called [Phenotype](https://github.com/Ensembl/VEP_plugins/blob/release/109/Phenotypes.pm) which maybe more useful in this case.  For example you can run -
```
./vep --i <input SwissVar variant file> --plugin Phenotypes,dir=${HOME},include_types=Variation --database
```
For details check the description in the header of the plugin. Also let me know if I can be of further help.

Best regards,
Nakib

**Comment by bioinfo2016** [comment]
Thanks @nakib103 for your answer .

I added the option --gene_phenotype to my vep command. It added the column GENE_PHENO to my output file. The output contain numbers in GENE_PHENO column  , whai do these number mean?.

Regards

**Comment by nakib103** [comment]
I will close this issue. If you face any further problem please re-open or create another issue.
