### ISSUE TITLE
Chromosome 1 does not overlap any features

### ISSUE THREAD

**Issue by mariaelf97** [Ensembl/ensembl-vep#1395]
Hello,
I am trying to use VEP with my custom annotation files (both gff and gtf) but when I run it it produces an empty file with warnings as below 
Chromosome 1 does not overlap any features
WARNING: Chromosome 1 not found in annotation sources or synonyms on line N.  (for all lines)

### System
- VEP version: 96.0
- Perl version:  5.32.1
- OS: Ubuntu
- tabix installed ? yes, in VEP's bin 

### Full VEP command line
```
gffread 1-0039.gff -T -o 1-0039.gtf
grep -v "#" 1-0039.gtf | sort -k1,1 -k4,4n -k5,5n -t$'\t' | bgzip -c > 1-0039_sorted.gtf.gz
tabix -p gff 1-0039_sorted.gtf.gz
bgzip 1-0039.fasta
vep -i 1-0039_hsdM.vcf --gtf 1-0039_sorted.gtf.gz --fasta 1-0039.fasta.gz
```

### Full error message
> Including the warnings, if available
WARNING: Chromosome 1 not found in annotation sources or synonyms on line 32431. 
Chromosome 1 does not overlap any features
(for all lines in the VCF file)
### Data files (if applicable)
1-0039.fasta.gz
```
>1 4411261
TTGACCGATGACCCCGGTTCAGGCTTCACCACAGTGTGGAACGCGGTCGTCTCCGAACTT
AACGGCGACCCTAAGGTTGACGACGGACCCAGCAGTGATGCTAATCTCAGCGCTCCGCTG
ACCCCTCAGCAAAGGGCTTGGCTCAATCTCGTCCAGCCATTGACCATCGTCGAGGGGTTT
GCTCTGTTATCCGTGCCGAGCAGCTTTGTCCAAAACGAAATCGAGCGCCATCTGCGGGCC
CCGATTACCGACGCTCTCAGCCGCCGACTCGGACATCAGATCCAACTCGGGGTCCGCATC
GCTCCGCCGGCGACCGACGAAGCCGACGACACTACCGTGCCGCCTTCCGAAAATCCTGCT
ACCACATCGCCAGACACCACAACCGACAACGACGAGATTGATGACAGCGCTGCGGCACGG
GGCGATAACCAGCACAGTTGGCCAAGTTACTTCACCGAGCGCCCGCACAATACCGATTCC
GCTACCGCTGGCGTAACCAGCCTTAACCGTCGCTACACCTTTGATACGTTCGTTATCGGC
GCCTCCAACCGGTTCGCGCACGCCGCCGC

```
1-0039_hsdM.vcf
```
##fileformat=VCFv4.0
##source=pbhooverV1.1.0
##INFO=<ID=RSR,Number=1,Type=Integer,Description="Reference-supporting reads">
##INFO=<ID=VSR,Number=1,Type=Integer,Description="Variant-supporting reads">
##INFO=<ID=VF,Number=1,Type=Float,Description="Variant frequency">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FILTER=<ID=LOW,Description="Position with too low of depth">
##FILTER=<ID=NO,Description="Does not meet criteria to call variant">
##FILTER=<ID=HETERO,Description="Enough support to call reference and variant (mixed population)">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       3040622 .       C       G       10      LOW     RSR=0;VSR=1;VF=1.0;DP=1
1       3040630 .       C       CG      12      LOW     RSR=0;VSR=1;VF=1.0;DP=1
1       3040639 .       G       GT      1       LOW     RSR=0;VSR=1;VF=1.0;DP=1
1       3040640 .       C       G       8       LOW     RSR=0;VSR=1;VF=1.0;DP=1
1       3040643 .       T       TA      7       LOW     RSR=0;VSR=1;VF=1.0;DP=1
1       3040652 .       C       CA      14      LOW     RSR=0;VSR=1;VF=1.0;DP=1
1       3040657 .       AG      A       17      LOW     RSR=0;VSR=1;VF=1.0;DP=1
1       3040657 .       AG      A       17      LOW     RSR=0;VSR=1;VF=1.0;DP=1
1       3040664 .       A       AT      13      LOW     RSR=0;VSR=1;VF=1.0;DP=1
1       3040670 .       C       CA      12      LOW     RSR=0;VSR=1;VF=1.0;DP=1
1       3040672 .       G       GGA     4       LOW     RSR=0;VSR=1;VF=1.0;DP=1
1       3040676 .       C       T       13      LOW     RSR=0;VSR=1;VF=1.0;DP=1


```
1-0039_sorted.gtf.gz
```
1-0039.1        EMBL    CDS     1       1524    .       +       0       transcript_id "1-0039.1.2"; gene_name "dnaA";
1-0039.1        EMBL    transcript      1       1524    .       +       .       transcript_id "1-0039.1.2"; gene_id "1-0039.1.2"; gene_name "dnaA"
1-0039.1        EMBL    CDS     1646    1972    .       +       0       transcript_id "1-0039.1.5"; gene_name "ORF0009";
1-0039.1        EMBL    transcript      1646    1972    .       +       .       transcript_id "1-0039.1.5"; gene_id "1-0039.1.5"; gene_name "ORF0009"
1-0039.1        EMBL    CDS     2023    2940    .       +       0       transcript_id "1-0039.1.7"; gene_name "ORF0586";
1-0039.1        EMBL    transcript      2023    2940    .       +       .       transcript_id "1-0039.1.7"; gene_id "1-0039.1.7"; gene_name "ORF0586"
1-0039.1        EMBL    CDS     2897    3223    .       +       0       transcript_id "1-0039.1.9"; gene_name "ORF0009";
1-0039.1        EMBL    transcript      2897    3223    .       +       .       transcript_id "1-0039.1.9"; gene_id "1-0039.1.9"; gene_name "ORF0009"
1-0039.1        EMBL    CDS     3274    4158    .       +       0       transcript_id "1-0039.1.11"; gene_name "ORF0004";
1-0039.1        EMBL    transcript      3274    4158    .       +       .       transcript_id "1-0039.1.11"; gene_id "1-0039.1.11"; gene_name "ORF0004"
1-0039.1        EMBL    CDS     4768    5976    .       +       0       transcript_id "1-0039.1.13"; gene_name "dnaN";
1-0039.1        EMBL    transcript      4768    5976    .       +       .       transcript_id "1-0039.1.13"; gene_id "1-0039.1.13"; gene_name "dnaN"
1-0039.1        EMBL    CDS     5996    7153    .       +       0       transcript_id "1-0039.1.15"; gene_name "recF";
1-0039.1        EMBL    transcript      5996    7153    .       +       .       transcript_id "1-0039.1.15"; gene_id "1-0039.1.15"; gene_name "recF"
1-0039.1        EMBL    CDS     7150    7713    .       +       0       transcript_id "1-0039.1.17"; gene_name "Rv0004";
1-0039.1        EMBL    transcript      7150    7713    .       +       .       transcript_id "1-0039.1.17"; gene_id "1-0039.1.17"; gene_name "Rv0004"
1-0039.1        EMBL    CDS     7956    9983    .       +       0       transcript_id "1-0039.1.19"; gene_name "gyrB";
1-0039.1        EMBL    transcript      7956    9983    .       +       .       transcript_id "1-0039.1.19"; gene_id "1-0039.1.19"; gene_name "gyrB"
1-0039.1        EMBL    CDS     10018   12534   .       +       0       transcript_id "1-0039.1.21"; gene_name "gyrA";
1-0039.1        EMBL    transcript      10018   12534   .       +       .       transcript_id "1-0039.1.21"; gene_id "1-0039.1.21"; gene_name "gyrA"
1-0039.1        EMBL    CDS     12630   13544   .       +       0       transcript_id "1-0039.1.23"; gene_name "Rv0007";
1-0039.1        EMBL    transcript      12630   13544   .       +       .       transcript_id "1-0039.1.23"; gene_id "1-0039.1.23"; gene_name "Rv0007"
1-0039.1        EMBL    CDS     12679   12876   .       +       0       transcript_id "1-0039.1.25"; gene_name "ORF0348";
1-0039.1        EMBL    transcript      12679   12876   .       +       .       transcript_id "1-0039.1.25"; gene_id "1-0039.1.25"; gene

```

**Comment by dglemos** [comment]
Hi @mariaelf97,
The problem is probably in your gtf file, in this file the chromosome name is `1-0039.1` however in the VCF and fasta the chromosome is `1`. 
If they are the same chromosome you could either:
- update your gtf file to include `1`.
- use the vep options `--synonyms [file]` where [file] contains the chromosome synonyms. This file should be tab-delimited with the primary identifier in column 1 and the synonym in column 2. You can find this option listed [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#ident).

Let me know if it works.

Best wishes,
Diana

**Comment by mariaelf97** [comment]
@dglemos Hi , Thank you so much for your response! I actually tried changing the chromosome but it failed and the reason was because awk somehow changed all tabs to space for some reason, once I changed the chromosome name it worked! I get these warnings though 
`Use of uninitialized value in split at /jet/home/ahmadije/miniconda3/envs/vep/share/ensembl-vep-109.3-0/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/GTF.pm line 137, <__ANONIO__> line 5011.`

Is this something I should be concerned about?

**Comment by mariaelf97** [comment]
@dglemos it seems that the output is not correct, it is showing all variants as modifier, intergenic. For some reason it seems that it does not recognize genes in the annotation file.
The modified gtf file looks like this :
```
1       EMBL    transcript      1       1524    .       +       .       transcript_id   "1-0039.1.2";   gene_id "1-0039.1.2";   gene_name       "dnaA"
1       EMBL    CDS     1       1524    .       +       0       transcript_id   "1-0039.1.2";   gene_name       "dnaA";
1       EMBL    transcript      1646    1972    .       +       .       transcript_id   "1-0039.1.5";   gene_id "1-0039.1.5";   gene_name       "ORF0009"
1       EMBL    CDS     1646    1972    .       +       0       transcript_id   "1-0039.1.5";   gene_name       "ORF0009";
1       EMBL    transcript      2023    2940    .       +       .       transcript_id   "1-0039.1.7";   gene_id "1-0039.1.7";   gene_name       "ORF0586"
1       EMBL    CDS     2023    2940    .       +       0       transcript_id   "1-0039.1.7";   gene_name       "ORF0586";
1       EMBL    transcript      2897    3223    .       +       .       transcript_id   "1-0039.1.9";   gene_id "1-0039.1.9";   gene_name       "ORF0009"
1       EMBL    CDS     2897    3223    .       +       0       transcript_id   "1-0039.1.9";   gene_name       "ORF0009";
1       EMBL    transcript      3274    4158    .       +       .       transcript_id   "1-0039.1.11";  gene_id "1-0039.1.11";  gene_name       "ORF0004"
1       EMBL    CDS     3274    4158    .       +       0       transcript_id   "1-0039.1.11";  gene_name       "ORF0004";
1       EMBL    transcript      4768    5976    .       +       .       transcript_id   "1-0039.1.13";  gene_id "1-0039.1.13";  gene_name       "dnaN"
1       EMBL    CDS     4768    5976    .       +       0       transcript_id   "1-0039.1.13";  gene_name       "dnaN";
1       EMBL    transcript      5996    7153    .       +       .       transcript_id   "1-0039.1.15";  gene_id "1-0039.1.15";  gene_name       "recF"
1       EMBL    CDS     5996    7153    .       +       0       transcript_id   "1-0039.1.15";  gene_name       "recF";
1       EMBL    transcript      7150    7713    .       +       .       transcript_id   "1-0039.1.17";  gene_id "1-0039.1.17";  gene_name       "Rv0004"
1       EMBL    CDS     7150    7713    .       +       0       transcript_id   "1-0039.1.17";  gene_name       "Rv0004";
1       EMBL    transcript      7956    9983    .       +       .       transcript_id   "1-0039.1.19";  gene_id "1-0039.1.19";  gene_name       "gyrB"
1       EMBL    CDS     7956    9983    .       +       0       transcript_id   "1-0039.1.19";  gene_name       "gyrB";
1       EMBL    transcript      10018   12534   .       +       .       transcript_id   "1-0039.1.21";  gene_id "1-0039.1.21";  gene_name       "gyrA"
1       EMBL    CDS     10018   12534   .       +       0       transcript_id   "1-0039.1.21";  gene_name       "gyrA";
1       EMBL    transcript      12630   13544   .       +       .       transcript_id   "1-0039.1.23";  gene_id "1-0039.1.23";  gene_name       "Rv0007"
1       EMBL    CDS     12630   13544   .       +       0       transcript_id   "1-0039.1.23";  gene_name       "Rv0007";
1       EMBL    transcript      12679   12876   .       +       .       transcript_id   "1-0039.1.25";  gene_id "1-0039.1.25";  gene_name       "ORF0348"
1       EMBL    CDS     12679   12876   .       +       0       transcript_id   "1-0039.1.25";  gene_name       "ORF0348";
1       EMBL    transcript      13239   13544   .       +       .       transcript_id   "1-0039.1.27";  gene_id "1-0039.1.27";  gene_name       "Rv0007"
```
The output looks like this ;
`## VEP command-line: vep --database 0 --fasta 1-0039.fasta.gz --gtf 1-0039_modified_sorted.gtf.gz --input_file 1-0039_hsdM.vcf
#Uploaded_variation     Location        Allele  Gene    Feature Feature_type    Consequence     cDNA_position   CDS_position    Protein_position        Amino_acids     Codons  Existing_variation      Extra
1_3040622_C/G   1:3040622       G       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040631_-/G   1:3040630-3040631       G       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040640_-/T   1:3040639-3040640       T       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040640_C/G   1:3040640       G       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040644_-/A   1:3040643-3040644       A       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040653_-/A   1:3040652-3040653       A       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040658_G/-   1:3040658       -       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040658_G/-   1:3040658       -       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040665_-/T   1:3040664-3040665       T       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040671_-/A   1:3040670-3040671       A       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040673_-/GA  1:3040672-3040673       GA      -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040676_C/T   1:3040676       T       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040686_-/AGA 1:3040685-3040686       AGA     -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040691_C/G   1:3040691       G       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040692_G/T   1:3040692       T       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040697_-/G   1:3040696-3040697       G       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040701_-/A   1:3040700-3040701       A       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040708_-/ACGCCGGT    1:3040707-3040708       ACGCCGGT        -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040710_-/G   1:3040709-3040710       G       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040714_C/A   1:3040714       A       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040716_-/C   1:3040715-3040716       C       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040720_T/A   1:3040720       A       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040722_-/GA  1:3040721-3040722       GA      -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040726_-/TGCA        1:3040725-3040726       TGCA    -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040733_-/AGCG        1:3040732-3040733       AGCG    -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040740_-/AG  1:3040739-3040740       AG      -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040746_-/G   1:3040745-3040746       G       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040748_C/G   1:3040748       G       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040750_-/AGA 1:3040749-3040750       AGA     -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
1_3040754_T/C   1:3040754       C       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
`

I also tried another gff to gtf tool called AGAT but it did not resolve the issue.

**Comment by mariaelf97** [comment]
Update on this issue, at first I thought the space changed to tab e.g.  `transcript_id   "1-0039.1.2";   gene_id "1-0039.1.2";   gene_name       "dnaA"` caused the issue, so I fixed it, the `Use of uninitialized value in split at /jet/home/ahmadije/miniconda3/envs/vep/share/ensembl-vep-109.3-0/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/GTF.pm line 137, <__ANONIO__> line 5011.` warning was gone but the output file is still wrong, it calls all variants as intergenic with IMPACT=MODIFER.

**Comment by dglemos** [comment]
In your example, the variants overlap the region 1:3040622-3040754 but the GTF file only covers until 1:13544.
Can you share the complete VCF and GTF files?

**Comment by mariaelf97** [comment]
@dglemos Dear Diana, Thank you for your response. It seems that the issue is with gffread package. The gtf format that it produces is wrong. I used agat package to change my gff to gtf and it worked!
