### ISSUE TITLE
how to obtain the correspondence between all genes  and  transcripts 

### ISSUE THREAD

**Issue by user-tq** [Ensembl/ensembl-vep#1402]
I am using the GRCH37 104 version of vep and refseq_ Cache```homo_sapiens_refseq_vep_104_GRCh37.tar.gz```, I want to obtain all genes, transcripts, and transcript versions from cache. For the convenience of using custom scripts to select transcripts in the future.

Currently, I have extracted some transcripts from MANE, but MANE is based on GRCH 38. I am not sure if these transcripts are present in the VEP cache or if their versions are consistent. So I need complete gene and transcript information in the cache.And based on this information, manually select suitable transcripts by myself.

Perhaps the problem I described is not accurate, my problem is similar to a problem in Snpeff.(https://github.com/pcingola/SnpEff/issues/39)
Thanks in advance

**Comment by olaaustine** [comment]
Hi @user-tq,
Thank you for your query.
Our [cache](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache:~:text=Data%20in%20the,using%20%2D%2Dhgvs) data contains all transcript models, regulatory features and variant data for a species.
MANE only exists for GRCh38. Results for only canonical transcript can be gotten using the options [--pick](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_pick_order:~:text=%2D%2Dsummary-,%2D%2Dpick,-Pick%20one%20line), and customise using the [--pick_order](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_pick_order:~:text=PICK-,%2D%2Dpick_order,-%5Bc1%2Cc2%2C...%2CcN). 
Please let me know if this solves the issue or if you have any more question. 
Thank you, 
Ola.

**Comment by user-tq** [comment]
> Hi @user-tq, Thank you for your query. Our [cache](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache:~:text=Data%20in%20the,using%20%2D%2Dhgvs) data contains all transcript models, regulatory features and variant data for a species. MANE only exists for GRCh38. Results for only canonical transcript can be gotten using the options [--pick](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_pick_order:~:text=%2D%2Dsummary-,%2D%2Dpick,-Pick%20one%20line), and customise using the [--pick_order](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_pick_order:~:text=PICK-,%2D%2Dpick_order,-%5Bc1%2Cc2%2C...%2CcN). Please let me know if this solves the issue or if you have any more question. Thank you, Ola.

Thank you for your reply, but this does not completely solve my problem. It should be said that my problem is to use mane to select transcripts in grch37, and if not, choose according to other rules.For example, I am annotating ERBB2, even if I use  ```--pick_order  canonical,tsl,biotype,rank,ccds,length```,I get

```
17	37880997	.	G	GTTT	.	PASS	AS_FilterStatus=SITE;AS_SB_TABLE=47,38|14,8;DP=116;ECNT=2;GERMQ=93;MBQ=35,38;MFRL=194,183;MMQ=60,60;MPOS=24;NALOD=1.66;NLOD=12.96;POPAF=6.00;ROQ=93;TLOD=81.11;CSQ=TTT|protein_altering_variant|MODERATE|ERBB2|2064|Transcript|NM_001382784.1|protein_coding|21/28||NM_001382784.1:c.2443_2444insTTT|NP_001369713.1:p.Gly815delinsValCys|2618-2619/4674|2443-2444/3885|815/1294|G/VC|ggt/gTTTgt|rs397516979&COSV54064203&COSV54064477&COSV54066307&COSV54066802&COSV54077015&COSV99507093|1||1||insertion|EntrezGene||YES|||NP_001369713.1||||||||||||||||||||||||||||||likely_pathogenic|0&1&1&1&1&1&1|1&1&1&1&1&1&1|24033266&25157968&16863509&15753357|||||
```
but  MANE  chose is NM_004448 which I need.
I guess I can't just get the results I want through VEP.
Therefore, I need to customize a transcript whitelist to select the transcript I want.
But obviously, the prerequisite for customizing the whitelist is to obtain all transcripts (including versions) used by VEP.

**Comment by olaaustine** [comment]
Hi @user-tq,
Thank you.
If you want all the transcripts used by VEP, you can download our GTF file from any release, for release-104, this can be gotten from https://ftp.ensembl.org/pub/release-104/gtf/homo_sapiens/ and then filter to show only transcript rows and then parse the gene, transcript and version attributes anyway preferred.
Please let me know if this resolves the issue. 
Thank you
Ola.

**Comment by user-tq** [comment]
> Hi @user-tq, Thank you. If you want all the transcripts used by VEP, you can download our GTF file from any release, for release-104, this can be gotten from https://ftp.ensembl.org/pub/release-104/gtf/homo_sapiens/ and then filter to show only transcript rows and then parse the gene, transcript and version attributes anyway preferred. Please let me know if this resolves the issue. Thank you Ola.

Sorry for my late reply. and thank you very much, this solved my problem.
