### ISSUE TITLE
--custom gnomAD genomes annotation does not return variant in overlap mode

### ISSUE THREAD

**Issue by FlorianErger** [Ensembl/ensembl-vep#1405]
Dear VEP team,

running vep with the --custom flag pointing to the gnomAD genomes data in overlap mode does not return the allele frequency of a variant at that exact position. It does return the variant in exact mode. I have a local setup of VEP (local cache, local database). I have downloaded gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz for custom annotation as described in the VEP documentation. I slightly modified this file to have an info field with the reference sequence, variant sequence and position for easier downstream data management, but do not believe this has any bearing on my issue, because 99.9% of variants are annotated normally using these files.

A variant where my issue occurs is "3:g186302392G>T" [hg19]. If I

`zcat gnomad.exomes.r2.0.1.sites.noVEP.vcf.gz | grep 186302392`

I thus get
> 3       186302392       rs3222398       G       **T**,GTGTGTGTGTGTGTGTGTGTA 39498.2 LCR;RF  AC=32,1;AF=2.10526e-01,6.57895e-03;AN=152;AC_AFR=6,1;AC_AMR=1,0;AC_ASJ=1,0;AC_EAS=1,0;AC_FIN=3,0;AC_NFE=19,0;AC_OTH=1,0;AC_Male=22,1;AC_Female=10,0;AN_AFR=28;AN_AMR=2;AN_ASJ=4;AN_EAS=4;AN_FIN=20;AN_NFE=92;AN_OTH=2;AN_Male=90;AN_Female=62;AF_AFR=2.14286e-01,3.57143e-02;AF_AMR=5.00000e-01,0.00000e+00;AF_ASJ=2.50000e-01,0.00000e+00;AF_EAS=2.50000e-01,0.00000e+00;AF_FIN=1.50000e-01,0.00000e+00;AF_NFE=2.06522e-01,0.00000e+00;AF_OTH=5.00000e-01,0.00000e+00;AF_Male=2.44444e-01,1.11111e-02;AF_Female=1.61290e-01,0.00000e+00;GC_AFR=7,6,0,1,0,0;GC_AMR=0,1,0,0,0,0;GC_ASJ=1,1,0,0,0,0;GC_EAS=1,1,0,0,0,0;GC_FIN=7,3,0,0,0,0;GC_NFE=27,19,0,0,0,0;GC_OTH=0,1,0,0,0,0;GC_Male=22,22,0,1,0,0;GC_Female=21,10,0,0,0,0;AC_raw=105,1;AN_raw=1778;AF_raw=5.90551e-02,5.62430e-04;GC_raw=795,62,14,1,0,0;GC=43,32,0,1,0,0;AC_POPMAX=1,1;AN_POPMAX=2,28;AF_POPMAX=5.00000e-01,3.57143e-02;REF=G;ALT=T,GTGTGTGTGTGTGTGTGTGTA;POS=186302392

As can be seen by the output, it is a multiallelic site, but G>T is present in the source data at the queried position.

However, if I 
`/opt/Ensembl/ensembl-vep/vep --cache --dir /opt/Ensembl/ensembl-vep/cache --refseq --fasta /opt/Ensembl/ensembl-vep/fasta/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz --force --host localhost --user ens_DBuser --pass XXXX --custom /opt/Ensembl/ensembl-vep/cache/Plugins/gnomADg/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz,gnomADg,vcf,overlap,0,AF_AFR,AF_AMR,AF_ASJ,AF_EAS,AF_FIN,AF_NFE,AF_OTH,ALT,REF,POS -id '3:g186302392G>T'`

my output file is (**correct variant missing**):
> _... header and identical annotation entries for other transcripts omitted, can be provided if necessary_
> 3:g186302392G>T 3:186302392     T       51726   NR_165643.1     Transcript      intron_variant,non_coding_transcript_variant -       -       -       -       -       -       IMPACT=MODIFIER;STRAND=1;GIVEN_REF=G;USED_REF=G;gnomADg=3:186302390-186302392;gnomADg_AF_AFR=0.00000e+00;gnomADg_AF_AMR=0.00000e+00;gnomADg_AF_ASJ=0.00000e+00;gnomADg_AF_EAS=0.00000e+00;gnomADg_AF_FIN=0.00000e+00;gnomADg_AF_NFE=7.23589e-05;gnomADg_AF_OTH=0.00000e+00;gnomADg_ALT=T;gnomADg_FILTER=LCR;gnomADg_POS=186302389;gnomADg_REF=TTA

The variant in the gnomAD genomes vcf is not reported. The variant has a filter info of "LCR;RF", however other variants with this filter info are successfully annotated, so that's not it.

If I change the command line to exact mode:
`/opt/Ensembl/ensembl-vep/vep --cache --dir /opt/Ensembl/ensembl-vep/cache --refseq --fasta /opt/Ensembl/ensembl-vep/fasta/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz --force --host localhost --user ens_DBuser --pass XXXX --custom /opt/Ensembl/ensembl-vep/cache/Plugins/gnomADg/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF_AFR,AF_AMR,AF_ASJ,AF_EAS,AF_FIN,AF_NFE,AF_OTH,ALT,REF,POS -id '3:g186302392G>T'`

my output file is (**correct variant**)
> _... header and identical annotation entries for other transcripts omitted, can be provided if necessary_
> 3:g186302392G>T 3:186302392     T       51726   NR_165643.1     Transcript      intron_variant,non_coding_transcript_variant -       -       -       -       -       -       IMPACT=MODIFIER;STRAND=1;GIVEN_REF=G;USED_REF=G;gnomADg=rs3222398;gnomADg_AF_AFR=2.14286e-01;gnomADg_AF_AMR=5.00000e-01;gnomADg_AF_ASJ=2.50000e-01;gnomADg_AF_EAS=2.50000e-01;gnomADg_AF_FIN=1.50000e-01;gnomADg_AF_NFE=2.06522e-01;gnomADg_AF_OTH=5.00000e-01;gnomADg_ALT=T;gnomADg_FILTER=LCR,RF;gnomADg_POS=186302392;gnomADg_REF=G

What could be the reason the variant is not found by VEP in overlap mode, but is found in exact mode?

Thanks and best wishes,
Florian

### System
- VEP version: [109.3] 
- VEP Cache version: [109]
- Perl version: [5.26]
- OS: [SLES]
- tabix installed yes

**Comment by nakib103** [comment]
Hi @FlorianErger ,

This issue will have a fix in Ensembl VEP e110 version coming out soon. I am closing this issue but if you face any further problem please let us know.

Best regards,
Nakib

**Comment by FlorianErger** [comment]
Great, thanks very much!

Best,
Florian
