### ISSUE TITLE
empty consequence 

### ISSUE THREAD

**Issue by hujingchu** [Ensembl/ensembl-vep#141]
we use VEP(version 91, use only refseq database) to annotate sites, but we found one sites were missing consequence value, however, this site were successfully got consequence using version 88.
![image](https://user-images.githubusercontent.com/14899280/35797518-ee56be86-0a9a-11e8-8309-f61d1fe47c13.png)

**Comment by aparton** [comment]
Hiya,

Thank you for bringing this to our attention. This definitely looks like a caching issue - I'll investigate further and get back to you.

Kind Regards,
Andrew

**Comment by kvshams** [comment]
We also got into the same issue.. almost 1/3 of the sites have `-` for dbNSFP annotations. The wb API is running fine with input vcf file. I am using VEP 91

**Comment by aparton** [comment]
Hi,

This issue should now be resolved. I'm going to close this issue now, if you have any other problems please open another issue.

Kind Regards,
Andrew
