### ISSUE TITLE
Genomic g. HGVS represents DUP as INS

### ISSUE THREAD

**Issue by davmlaw** [Ensembl/ensembl-vep#1417]
## Describe the issue

When using the ```--hgvsg``` to add g. HGVS the c.HGVS is correctly formatted as a DUP, ie:

NM_001079515.3:c.1411_1501dup

While the g.HGVS field is:

1:g.235611723_235611724insCAGACCTTCTGTTGTCCTATGAAAGTCCCAAAGTAAGTTGCCCAGCAAAATACAAAGTCAAAGTCAAGCTTAGTCCTCGTATTATGACATTAAACTGTCTCTAGATAGCAACAGTTTGATTCTAAATGGAGACCATGGGTCTGTTTGTTTGATTTTAAGGGTAAGCTACTGCCTGGGGACGGGGTGGGGGAAGAGTATGTGTAGCATGCTTTATCGGATCTGTCTTAATCACATCCTTCCCCACCTTCGTTCTAATTTTAGAAGCCGGGCAATTCAAAAGGTGAAGGGATTGCTGTCACGTCTTCTCAAAGTTCCTGTGT

Expected output:

1:g.235611675_235611994dup 

### System

- VEP version: 107
- VEP Cache version: 107
- Perl version: 5.30.2
- OS: Ubuntu 22
- tabix installed: yes

### Example Input VCF

Has been renamed to .txt to attach

[dup_g_hgvs.txt](https://github.com/Ensembl/ensembl-vep/files/11504395/dup_g_hgvs.txt)

### Command Line

```
/home/dlawrence/localwork/variantgrid/scripts/perlbrew_runner.sh /data/annotation/VEP/ensembl-vep/vep -i /home/dlawrence/localwork/variantgrid/data/annotation_dump/dump_373_standard.vcf -o /home/dlawrence/localwork/variantgrid/data/annotation_dump/dump_373_standard.vep_annotated_GRCh37_v2.vcf.gz --cache --dir /data/annotation/VEP/vep_cache --fasta /data/annotation/fasta/GCF_000001405.25_GRCh37.p13_genomic.fna.gz --assembly GRCh37 --offline --use_given_ref --vcf --compress_output gzip --force_overwrite --flag_pick --exclude_predicted --no_stats --check_existing --no_escape --sift b --hgvs --hgvsg --symbol --numbers --domains --canonical --protein --biotype --transcript_version --af --pubmed --variant_class --distance 5000 --refseq
```

**Comment by likhitha-surapaneni** [comment]
Hi @davmlaw, thank you for reporting to us and providing the details. We are working towards a fix for this problem which will be made available in the coming release. 

Kind regards,
Likhitha

**Comment by likhitha-surapaneni** [comment]
Hi @davmlaw , a fix for this will be available in the upcoming release. Thank you and please let us know if there are any further issues
