### ISSUE TITLE
Genomic g. HGVS should use reference contig rather than VCF chromosome

### ISSUE THREAD

**Issue by davmlaw** [Ensembl/ensembl-vep#1418]
## Describe the issue

When using ```--hgvsg``` to add g. HGVS, VEP produces a genomic HGVS using chromsome name (ie what was provided in the VCF), while the [HGVS specification](https://varnomen.hgvs.org/bg-material/refseq/) says:

> the recommended reference is a genomic reference sequence based on a recent genome build, e.g. NC_000023.11 (for Homo sapiens chromosome X, build GRCh38/hg38)

Eg for attached VCF

Actual output:

11:g.103048382T>A

Expected output:

NC_000011.9:g.103048382T>A

**NOTE:** 

The g.HGVS appears to use whatever is supplied in the VCF, ie if CHROM (1st column) contained "NC_000011.9" instead of "11" it would have produced it correctly. I just think it's best to always use the versioned contig name.

If you want to keep backwards compatibility, perhaps you could introduce a new command line option: ```--hgvsg-use-contig``` 

### System

- VEP version: 107
- VEP Cache version: 107
- Perl version: 5.30.2
- OS: Ubuntu 22
- tabix installed: yes

### Example Input VCF

Has been renamed to .txt to attach

[g_hgvs_grch37.txt](https://github.com/Ensembl/ensembl-vep/files/11504469/g_hgvs_grch37.txt)

**Comment by likhitha-surapaneni** [comment]
Hi @davmlaw, thank you for the suggestion. I will discuss this with our team and get back to you. 

Kind regards,
Likhitha

**Comment by likhitha-surapaneni** [comment]
Hi @davmlaw , thank you for your patience. I have talked to the team and keeping the versioned config name irrespective of the input data seems correct. This enhancement is currently not in the priority list and we will work towards making it available in the coming releases. 

Kind regards,
Likhitha

**Comment by davmlaw** [comment]
Hi, it looks like there is already a command line option for this: ```--hgvsg_use_accession``` - I will just use that, thanks!
