### ISSUE TITLE
 phaseolus vulgaris is not a valid species name

### ISSUE THREAD

**Issue by vishalsnegi** [Ensembl/ensembl-vep#1419]
## Describe the issue
 phaseolus vulgaris is not a valid species name (check DB and API version)

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 101
- VEP Cache version: Not sure
- Perl version: Not sure
- OS: linux
- tabix installed ? Yes

### Full VEP command line
```
vep --i "$c_vcf_file" -o "$output_directory/vc_bcf_annotated.vcf.gz" --vcf --compress_output bgzip --force_overwrite \
  --gtf "$gtf_file" --fasta "$ref" --cache --dir_cache /home/vn81649/.vep --species  "Phaseolus vulgaris" -a "GCA_000499845.1"
```

### Full error message
-------------------- WARNING ----------------------
MSG: phaseolus vulgaris is not a valid species name (check DB and API version)
FILE: Bio/EnsEMBL/Registry.pm LINE: 1334
CALLED BY: Bio/EnsEMBL/Registry.pm  LINE: 1109
Date (localtime)    = Mon May 22 14:47:48 2023
Ensembl API version = 101
---------------------------------------------------

-------------------- EXCEPTION --------------------
MSG: Can not find internal name for species 'phaseolus vulgaris'
STACK Bio::EnsEMBL::Registry::get_adaptor /apps/eb/VEP/101.0-foss-2019b-Perl-5.30.0/modules/api/Bio/EnsEMBL/Registry.pm:1111
STACK Bio::EnsEMBL::VEP::BaseVEP::get_adaptor /apps/eb/VEP/101.0-foss-2019b-Perl-5.30.0/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:308
STACK Bio::EnsEMBL::VEP::BaseVEP::get_database_assembly /apps/eb/VEP/101.0-foss-2019b-Perl-5.30.0/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:419
STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /apps/eb/VEP/101.0-foss-2019b-Perl-5.30.0/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::init /apps/eb/VEP/101.0-foss-2019b-Perl-5.30.0/modules/Bio/EnsEMBL/VEP/Runner.pm:127
STACK Bio::EnsEMBL::VEP::Runner::run /apps/eb/VEP/101.0-foss-2019b-Perl-5.30.0/modules/Bio/EnsEMBL/VEP/Runner.pm:203
STACK toplevel /apps/eb/VEP/101.0-foss-2019b-Perl-5.30.0/vep:228
Date (localtime)    = Mon May 22 14:47:48 2023
Ensembl API version = 101
---------------------------------------------------

### Data files (if applicable)
They include:
#Inpu files
c_vcf_file="/path to my file/vc_bcf_filtered.vcf.gz"
gtf_file="/path to my file/Phaseolus_vulgaris.PhaVulg1_0.42.chr.gtf"
index_file="/path to my file/vc_bcf_filtered.vcf.gz.csi"
ref="/path to my file/Ref/ref.fa"
#Output
output_directory="/path to my file/ann_vc_bcf"

**Comment by dglemos** [comment]
Hi @vishalsnegi,
Which cache did you download to `/home/vn81649/.vep`? Could you please list what is in this directory?

**Comment by vishalsnegi** [comment]
> For your example, VEP does not need to use the species name. Please try to run the same command without the species `--species "Phaseolus vulgaris"`.

I ran the script without using --species
`mkdir -p /home/vn81649/.vep

# Set input and output file paths
c_vcf_file="/scratch/vn81649/snapbean/snapbean/merged_vc_bcf/vc_bcf_filtered.vcf.gz"
gtf_file="/scratch/vn81649/snapbean/snapbean/Ref_gtf/Phaseolus_vulgaris.PhaVulg1_0.42.chr.gtf"
#index_file="/scratch/vn81649/snapbean/snapbean/merged_vc_bcf/vc_bcf_filtered.vcf.gz.csi"
ref="/scratch/vn81649/snapbean/snapbean/Ref/ref.fa"
output_directory="/scratch/vn81649/snapbean/snapbean/ann_vc_bcf"

# Annotate the VCF file
vep -i "$c_vcf_file" -o "$output_directory/vc_bcf_annotated.vcf.gz" --vcf --compress_output bgzip --force_overwrite \
  --gtf "$gtf_file" --fasta "$ref" --cache --dir_cache /home/vn81649/.vep
`
However, it resulted in the error:
`vn81649@ss-sub3 snapbean$ cat test_vep-22995221.err

-------------------- EXCEPTION --------------------
MSG: ERROR: Cache directory /home/vn81649/.vep/homo_sapiens not found

STACK Bio::EnsEMBL::VEP::CacheDir::dir /apps/eb/VEP/101.0-foss-2019b-Perl-5.30.0/modules/Bio/EnsEMBL/VEP/CacheDir.pm:311
STACK Bio::EnsEMBL::VEP::CacheDir::init /apps/eb/VEP/101.0-foss-2019b-Perl-5.30.0/modules/Bio/EnsEMBL/VEP/CacheDir.pm:227
STACK Bio::EnsEMBL::VEP::CacheDir::new /apps/eb/VEP/101.0-foss-2019b-Perl-5.30.0/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /apps/eb/VEP/101.0-foss-2019b-Perl-5.30.0/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:115
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /apps/eb/VEP/101.0-foss-2019b-Perl-5.30.0/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /apps/eb/VEP/101.0-foss-2019b-Perl-5.30.0/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /apps/eb/VEP/101.0-foss-2019b-Perl-5.30.0/modules/Bio/EnsEMBL/VEP/Runner.pm:132
STACK Bio::EnsEMBL::VEP::Runner::run /apps/eb/VEP/101.0-foss-2019b-Perl-5.30.0/modules/Bio/EnsEMBL/VEP/Runner.pm:203
STACK toplevel /apps/eb/VEP/101.0-foss-2019b-Perl-5.30.0/vep:228
Date (localtime)    = Wed May 24 08:20:45 2023
Ensembl API version = 101
---------------------------------------------------
`

**Comment by vishalsnegi** [comment]
Thanks for the help.
I excluded the cache altogether and used the bgzipped and indexed gtf file for annotations. It now worked for me.
 `vep -i "$c_vcf_file" --gtf "$data_gtf" --fasta "$fasta"`

Thanks again.
