### ISSUE TITLE
Cache version error

### ISSUE THREAD

**Issue by Jinjie-Duan** [Ensembl/ensembl-vep#142]
Hello,

I have installed VEP v85 and downloaded corresponding cache files as well to incorporate with Hail (https://hail.is/). However, when I launched VEP with default cache_version value, I got an error - ERROR: No cache found for homo_sapiens, version 84. It seems the default cache_version is 84, not 85. It can be fixed with adding --cache_version 85. But the problem is there is no chance to add cache_version parameter in Hail when call vep function. So I am wondering how to set the default cache_version back to right number, here is 85. Thanks a lot for any comments.

cheers,
Jinjie

**Comment by aparton** [comment]
Hi,

Thank you for your query. Can you please check the version number of your core ensembl API? The default cache_version value should be taken from there.

Alternatively, the current version of VEP (v91) contains new features and faster analysis than v85, so if it were possible for you to upgrade, it would be recommended. This would also resolve your issue of differing version between your API, VEP and cache files.

If there's anything else I can do to help, let me know.

Kind Regards,
Andrew

**Comment by Jinjie-Duan** [comment]
@aparton thanks a lot for the prompt reply. It's solved now. 👍 

Since right now the Hail can only integrate with VEP version 81/85, I have to stick with v85 so far. Hopefully, hail can work with v91 shortly.
