### ISSUE TITLE
Is zygosity (het/hom) factored into impact?

### ISSUE THREAD

**Issue by aiqc** [Ensembl/ensembl-vep#1422]
Is allele zygosity (heterozygous/ homozygous) ever taken into account when determining `IMPACT`?

For example:
- Is there ever a situation where a homozygous MODERATE is treated as a HIGH?
- If both alleles are mutated differently (e.g. alt and del), is only the highest IMPACT kept?

---

This is what I found about zygosity in the documentation:

```
ZYG - zygosity of individual genotype at this locus
> http://useast.ensembl.org/info/docs/tools/vep/vep_formats.html#defaultout
```

Flag | Description | Output Fields |
-- | -- | --
--individual [all\|ind list] | Consider only alternate alleles present in the genotypes of the specified individual(s). May be a single individual, a comma-separated list or "all" to assess all individuals separately. Individual variant combinations homozygous for the given reference allele will not be reported. **Each individual and variant combination is given on a separate line of output.** Only works with VCF files containing individual genotype data; individual IDs are taken from column headers. Not used by default | IND, ZYG
> https://useast.ensembl.org/info/docs/tools/vep/script/vep_options.html

**Comment by aiqc** [comment]
Hi @dglemos – The root of the question is how zygosity is handled if at all

**Comment by dglemos** [comment]
Default VEP does not handle zygosity, the only option is `--individual ` which considers only alternate alleles present in the genotypes of the specified individual(s). It only works with VCF files and it outputs two new fields `IND` and `ZYG` but the other VEP fields are not affected.

**Comment by aiqc** [comment]
![image](https://github.com/Ensembl/ensembl-vep/assets/74990642/e8a3a08a-10b1-4f3d-97b1-582a8d197031)

Wow, I was not expecting to find so many impactful homozygous variants. 

This is off-topic, but has it been considered to include zygosity by default when running VEP on an individual sample? Even when running on multiple samples you could have a homozygous frequency (ranging 0 to 1).

**Comment by dglemos** [comment]
We don't plan to include zygosity by default as it depends on the type of input given to VEP however, we plan to improve the option --individual to output a simpler and more intuitive output.

**Comment by dglemos** [comment]
I'm going to close this issue but feel free to open a new one if you have more questions.

Best wishes,
Diana
