### ISSUE TITLE
Wrong HGVSp

### ISSUE THREAD

**Issue by G2GreenTea** [Ensembl/ensembl-vep#1424]
## Describe the issue
An output for the HGVSp notation  was wrong.

## Additional information
The variant is GRCh37 19_13135450_G/-. When I annotated the variant, I got the HGVSp NP_001257972.1:p.Glu2?. But it was wrong and the correct output should be NP_001257972.1:p.Glu2ArgfsTer63. The deletion of base G would result out a frameshift that the second amino acid Glu changes to Arg.

chr19: 13,135,448-13,135,462
ATGGAGATGTCATGG   Met-Glu-Met-Ser-Trp
AT   GAGATGTCATGG   Met-Arg-Cys-His

### System
- VEP version: 107.0
- VEP Cache version: 
- Perl version: 5.26.1
- OS: Ubuntu
- tabix installed Yes

### Full VEP command line
/opt/vep/src/ensembl-vep/vep vep -species homo_sapiens --offline --no_progress --no_stats --buffer_size 5000 --fork 4 --af --af_1kg --af_gnomad --hgvs --symbol --canonical --max_af --pubmed --shift_hgvs 1 --pick_order canonical,tsl,biotype,ccds,rank,length --cache --xref_refseq --refseq --tab --numbers --force_overwrite --format vcf --dir_plugins /project/Database/human/database/vep/Plugin  --assembly GRCh37 --input_file test.vcf -o test.vep.txt

### Data files (if applicable)
They include:
- The input file
[test.vcf.txt](https://github.com/Ensembl/ensembl-vep/files/11573202/test.vcf.txt)
- The output file
[test.vep.txt](https://github.com/Ensembl/ensembl-vep/files/11573208/test.vep.txt)
- The custom file(s)
You can provide a sample of them

**Comment by dglemos** [comment]
Hi @G2GreenTea,
Thank you for reporting this issue. 
We are investigating why the VEP HGVS cannot determine the amino acid Arg at position 2.
I'll let you know when we have updates.

**Comment by dglemos** [comment]
This bug is happening only for deletions in the ATG. When the allele G is deleted VEP assumes the start is gone even though it is followed by another G.
We are still working on a fix. We'll let you know when we have any updates.

**Comment by nakib103** [comment]
Hello @G2GreenTea,

We have added a fix for this issue which will be available in the next Ensembl release (e113).
I will close this ticket, if you need any further help please feel free to open a new ticket.

Best regards,
Nakib
