### ISSUE TITLE
Mitochondrial variants not annotated when using the RefSeq cache

### ISSUE THREAD

**Issue by gabrielhim** [Ensembl/ensembl-vep#1425]
Hello!
I need to annotate mitochondrial variants to extract all the HGVS (c., p. and m.) and their gene symbol using RefSeq as reference. However, VEP reports all variants in chrM as intergenic and returns no information about HGVSc, HGVSp and gene symbol.

- VEP version: 109.3
- Cache: `homo_sapiens_refseq_vep_109_GRCh38.tar.gz`

**Command line:**
```
docker run --rm -v $PWD:/data ensemblorg/ensembl-vep:release_109.3 vep \
    --input_file /data/samples/mitochondrial.vcf \
    --dir_cache /data/vep \
    --fasta /data/references/hg38/Homo_sapiens_assembly38.fasta \
    --force_overwrite \
    --hgvs \
    --hgvsg \
    --offline \
    --no_escape \
    --protein \
    --refseq \
    --symbol \
    --tab \
    --use_transcript_ref \
    --output_file /data/vep/outputs/mitochondrial.refseq.txt
```

**Input:**
```
chrM    4745    .       A       G       294.06  .       AC=2;AF=1.00;AN=2;DP=10;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=42.65;QD=29.41;SOR=1.085        GT:AD:DP:GQ:PL:SB       1/1:0,10:10:30:308,30,0:0,0,6,4
chrM    4769    .       A       G       194.97  .       AC=2;AF=1.00;AN=2;DP=6;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=42.33;QD=32.50;SOR=0.693 GT:AD:DP:GQ:PL:SB       1/1:0,6:6:18:209,18,0:0,0,3,3
chrM    7337    .       G       A       239.05  .       AC=2;AF=1.00;AN=2;DP=9;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=57.63;QD=26.56;SOR=0.892 GT:AD:DP:GQ:PL:SB       1/1:0,9:9:27:253,27,0:0,0,4,5
```
These variants have been reported as exonic by other annotators.

**Output:**
```
## VEP command-line: vep --database 0 --dir_cache [PATH]/vep --dir_plugins /plugins --fasta [PATH]/Homo_sapiens_assembly38.fasta --force_overwrite --hgvs --hgvsg --input_file [PATH]/mitochondrial_subset.vcf --no_escape --offline --output_file [PATH]/mitochondrial_subset.refseq.txt --protein --refseq --symbol --tab --use_transcript_ref
#Uploaded_variation	Location	Allele	Gene	Feature	Feature_type	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	IMPACT	DISTANCE	STRAND	FLAGS	SYMBOL	SYMBOL_SOURCE	HGNC_ID	ENSP	REFSEQ_MATCH	REFSEQ_OFFSET	GIVEN_REF	USED_REF	BAM_EDIT	HGVSc	HGVSp	HGVS_OFFSET	HGVSg
chrM_4745_A/G	chrM:4745	G	-	-	-	intergenic_variant	-	-	-	-	-	-	MODIFIER	-	-	-	-	-	-	-	-	-	chrM:g.4745A>G
chrM_4769_A/G	chrM:4769	G	-	-	-	intergenic_variant	-	-	-	-	-	-	MODIFIER	-	-	-	-	-	-	-	-	-	chrM:g.4769A>G
chrM_7337_G/A	chrM:7337	A	-	-	-	intergenic_variant	-	-	-	-	-	-	MODIFIER	-	-	-	-	-	-	-	-	-	chrM:g.7337G>A
```

Could you help me with this?
Thank you!

**Comment by olaaustine** [comment]
Hi @gabrielhim, 
Thank you for your query. 
We have been able to replicate this issue. 
We are investigating the issue and will come back to you with more information. 
Thank you.
Ola.

**Comment by gabrielhim** [comment]
Hello, @olaaustine. Could you give us an update about this issue? There's a PR opened by @nakib103 that seems to solve the problem, is there any plan to incorporate it in the coming versions of VEP?
Thank you!

**Comment by olaaustine** [comment]
Hi @gabrielhim,
Hope this meets you well 😄 
We are working hard to fix this reported issue and the fix will be applied for the next VEP release 
This ticket will be updated once the fix has been merged.
Thank you very much 
Ola

**Comment by gabrielhim** [comment]
Sounds great, thank you!

**Comment by olaaustine** [comment]
Hi @gabrielhim, 
Hope this meets you well 😄
The fix for this issue has been applied and will be available in our next release. 
I will close this ticket now. 
Feel free to open another ticket if you have another issue. 
Thank you 
Ola.

**Comment by gabrielhim** [comment]
Hello, @olaaustine!
Thank you very much for the update! Looking forward to the next release.

**Comment by ying-sheng** [comment]
Hello, Could you tell in which version of VEP this was solved? I tried VEP v110, it seems it still has the problem.

**Comment by nakib103** [comment]
Hello @ying-sheng, 
This should be fixed in the next version of Ensembl (**113**) which is scheduled to be released in the next month.

Best regards,
Nakib

**Comment by ying-sheng** [comment]
Thanks for the information!
