### ISSUE TITLE
Can't locate Bio/PrimarySeqI.pm in @INC

### ISSUE THREAD

**Issue by lqr131115** [Ensembl/ensembl-vep#1426]
## Describe the issue
I am running vep by using `conda`. 
I download `ensembl-vep-107.0-pl5321h4a94de4_0.tar.bz2` from [anaconda.org](https://anaconda.org/) and run:
```shell
conda install --use-local ensembl-vep-107.0-pl5321h4a94de4_0.tar.bz2
```
 I tried `vep -v` and got the following error:
![image](https://github.com/Ensembl/ensembl-vep/assets/68832962/2a06073b-0c1e-4127-8528-e09e80da0640)

I tried `sudo cpanm Bio::PrimarySeqI ` and tried `sudo find /home -name '*BioPerl*'` ,and  find something  like
```
/home/echo/.cpanm/work/1685536384.7215/BioPerl-1.7.8
/home/echo/.cpanm/work/1685536384.7215/BioPerl-1.7.8/lib/BioPerl.pm
/home/echo/.cpanm/work/1685536384.7215/BioPerl-1.7.8.tar.gz
```
I  tried  `export PERL5LIB=/home/echo/.cpanm/work/1685536384.7215 ` and  `vep -v` agian, I still get the same error message.

It may be an issue of the module not being installed in the proper location,  because the module seems should be appear in the location like  `/home/echo/perl5`. or `/home/echo/perl5/lib/perl5/`.

Also,  I tried  `export PERL5LIB=/home/echo/perl5/lib/perl5/ ` and  `vep -v` ,  I get the same error again.

And files in `/home/echo/perl5/lib/perl5/` were
![image](https://github.com/Ensembl/ensembl-vep/assets/68832962/44e3b7ad-a7db-4842-8b2c-a81408d36cec)

What should I do？

Thanks.

### System
- VEP version: 107 
- VEP Cache version: -
- Perl version: 5.26
- OS: Windows subsystem for Linux (ubuntu-18.04)
- tabix installed ?

**Comment by nuno-agostinho** [comment]
Hi @lqr131115, hope you are having a nice day!

We do not support VEP installation from `conda` given that we did not create that package. I would direct you to seek support for the package with the developers of the `conda` package.

I would advise to try instead our Docker image, [as documented here](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker). This would avoid the need to install Perl and other VEP dependencies.

Kind regards,
Nuno

**Comment by lqr131115** [comment]
Thanks @nuno-agostinho,  I am trying Docker image as your advice. I have tried 
```shell
mkdir /mnt/g/vep-docker/vep_data
sudo docker run -t -i -v /mnt/g/vep-docker/vep_data:/data ensemblorg/ensembl-vep
```
After that ,  i tired `sudo docker run -t -i -v /mnt/g/vep-docker/vep_data:/data ensemblorg/ensembl-vep INSTALL.pl`  and type  `0` to choose all cache fiels , i get a  error:
![image](https://github.com/Ensembl/ensembl-vep/assets/68832962/c93e6eb5-0ee1-458e-a5c9-b7c526b3e28c)

shat should i do? 
the all cahce files are to large and which  cache files should i  choose if i want to run other tools ,  like [capice](https://github.com/molgenis/capice) 

Yours
Lqr

**Comment by nuno-agostinho** [comment]
Hey @lqr131115,

That error is not expected, maybe you had some connection issues. I just tried your steps and VEP successfully downloads the cache.

Anyway, I do not recommend downloading cache files for all species, unless you really need them. If you are only interested in analysing human variants, only download human cache. Pre-computed CAPICE scores are currently only available for GRCh37, so you should download [`homo_sapiens_vep_109_GRCh37.tar.gz`](https://ftp.ensembl.org/pub/release-109/variation/indexed_vep_cache/homo_sapiens_vep_109_GRCh37.tar.gz).

Best,
Nuno

**Comment by nuno-agostinho** [comment]
Hi @lqr131115,

That error doesn't seem related with network, weird.

Yes, simply download the cache file to `/mnt/g/vep-docker/vep_data` and gunzip it, it is the same.

Best,
Nuno

**Comment by nuno-agostinho** [comment]
Hi @lqr131115,

Hope you were able to successfully fix this issue. Given that I didn't hear from you yet, I will now close this ticket.

Feel free to re-open it in case you want to discuss it further. Thanks!

Best regards,
Nuno
