### ISSUE TITLE
Error: no compiler detected to compile 'lib/Bio/DB/BigFile.c'.

### ISSUE THREAD

**Issue by lqr131115** [Ensembl/ensembl-vep#1428]
Now , I have run vep successfully ! 

So I try to use the command provide by [capcie](https://github.com/molgenis/capice),  and I get an error:

![image](https://github.com/Ensembl/ensembl-vep/assets/68832962/da8a2543-4202-48f6-a8a3-d137ab13c759)

I  try to solve the problem according to this [guidance](https://useast.ensembl.org/info/docs/tools/vep/script/vep_download.html#bigfile),  
When I type `cpanm -l $HOME/cpanm Bio::DB::BigFile`, another error appear

![image](https://github.com/Ensembl/ensembl-vep/assets/68832962/2012b796-40d2-4be1-a87e-32508c230ebb)

## Additional info
After read  #1175 , I check my `gcc` | `g++` | `make`, and here are their  info :

-  $ which gcc | g++ | make
~/anaconda3/envs/vep/bin/gcc  | g++ | make

-  Pervious location for `gcc` and `g++` is `/usr/bin/`, and I do a modification like:
```shell
ln -s  ~/anaconda3/envs/vep/bin/gcc  gcc
```
The error occur both before and after modification

Best, 
Lqr

**Comment by nuno-agostinho** [comment]
Hey @lqr131115, I am glad to made VEP work.

Are you using Docker or command-line VEP?

You will need to check how to use a custom compiler location to `cpanm`. Maybe the solutions provided here are helpful: https://stackoverflow.com/questions/8734980/how-to-tell-cpan-about-path-to-make-and-cc. Does the `build.log` file provide the expected compiler location?

Best,
Nuno

**Comment by lqr131115** [comment]
Hi @nuno-agostinho 

I am using command-line VEP.  

I add  something like this
 
![image](https://github.com/Ensembl/ensembl-vep/assets/68832962/18585f56-3a3b-4436-9e22-4f121e2fa45c)

and try again, the error still exist. Here my `build.log` 

![image](https://github.com/Ensembl/ensembl-vep/assets/68832962/bd4152a3-c570-47fc-9877-70ad06152940)


Wishes,
Lqr

**Comment by nuno-agostinho** [comment]
Hey @lqr131115,

Based on this line from your `build.log`:
  > `/home/liujie/anaconda3/envs/vep/bin/×86_64-conda-linux-gnu-ld: unrecognized option '-Wl, -02'`

It seems that you are setting your compiler correctly, but something about your compiler is off. I would try to see if you can update the compiler or using gcc installed from somewhere else other than `conda` if possible.

Cheers,
Nuno

**Comment by nuno-agostinho** [comment]
Hi @lqr131115,

You can also try leaving the original path and creating a symbolic link in the path where it is looking for `gcc`.

Best,
Nuno

**Comment by lqr131115** [comment]
Hi @nuno-agostinho 

I am glad to tell your  that I have solved this error, and install `Bio-BigFile` successfully! 

![7DK}C3D2F7YM2C)P69R{_(I](https://github.com/Ensembl/ensembl-vep/assets/68832962/d5cc3f0c-1a70-4587-be78-52ec224351f6)

I give up the `conda`  environment, and  do some `unlink` to make  my `gcc | g++ | make` in `/usr/bin`. Then I try again, and everything is ok. 

Now,  I use the command provide by [capcie](https://github.com/molgenis/capice), and I get a `messy code ` result.

![image](https://github.com/Ensembl/ensembl-vep/assets/68832962/c114e2bc-4800-4b25-a8ba-664324cbe5bd)

Do I need to enter any specific  options or  parameters ? 



Cheers,
Lqr

**Comment by nuno-agostinho** [comment]
Hey @lqr131115, I am glad to know that it is working for you!

I will now close this issue, but feel free to open a new one if you are having issues. Happy VEPing! 😁

Cheers,
Nuno
