### ISSUE TITLE
Multiple AFs for some variants

### ISSUE THREAD

**Issue by bjhall** [Ensembl/ensembl-vep#143]
For a small number of variants (approx 1 in 1000 in an exome VCF) the AF-field (representing 1000G MAF) will consist of two &-separated frequencies, like this:

`0.1506&0.1510`

They are almost always close to identical, but in a small number of cases they differ significantly. 

What does this mean? Is it intended behaviour or a bug? I cannot find anything about it in the documenation. Is it safe to just use the first value?

I've replicated this in VEP90 and 91, both from the command line tool and the web tool. As an example, try pasting the variant below into the web tool, **for GRCh37**:

`1       1564952 .       TG      T       644.09  PASS`

**Comment by ima23** [comment]
Hi bjhall, thanks for your message. I'm looking into it. Thanks, Irina

**Comment by ima23** [comment]
Hi @bjhall, this is an interesting case. The same allele happens to be represented by two variant ids rs112177324 and TMP_ESP_1_1564953_1564953. The rsID has an AF in 1000G (0.151) stored in the cache and the TMP_ESP variant does not, in which case the code checks the 1000G vcf for the AF and finds the non-rounded one 0.1506.  Therefore, it is safe to ignore the 0.1506 one. 
The next release 92, should report only one AF. Thanks again for reporting this case!
