### ISSUE TITLE
Deadsnakes no longer supports Ubuntu 18.04

### ISSUE THREAD

**Issue by muppetjones** [Ensembl/ensembl-vep#1433]
### Context

- Extending the base docker image with newer versions of python (specifically 3.9)
- Compiling python from source results in very slow execution at runtime (presumably due to compiler flags, etc)
- Using deadsnakes PPA significantly improves speed and stability

### Issues 

- [Deadsnakes no longes supports python 3.9](https://github.com/deadsnakes/issues/issues/251)

### System

> NOTE: This same issue affects all released docker images

- VEP version: `ensemblorg/ensembl-vep:release_108.2`
- VEP Cache version: n/a
- Perl version: n/z
- OS: Ubuntu

### Full VEP command line

```dockerfile
ARG PYTHON_VERSION=3.9

RUN echo "=== Installing python ${PYTHON_VERSION}" \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update && apt-get -yqq install \
    python${PYTHON_VERSION}-dev \
    python${PYTHON_VERSION}-venv \
    && echo "=== Installing pip for python version" \
    && curl -sS https://bootstrap.pypa.io/get-pip.py | python${PYTHON_VERSION} \
    && echo "=== Setting up v${PYTHON_VERSION} as the default python" \
    && ln -s /usr/bin/python${PYTHON_VERSION} /usr/local/bin/python3 \
    && ln -s /usr/local/bin/python3 /usr/local/bin/python \
    && echo "=== Cleanup apt-get" \
    && apt-get clean autoclean \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*
```

### Full error message

```
#10 10.93 E: Unable to locate package python3.9-dev
#10 10.93 E: Couldn't find any package by glob 'python3.9-dev'
#10 10.93 E: Couldn't find any package by regex 'python3.9-dev'
#10 10.93 E: Unable to locate package python3.9-venv
#10 10.93 E: Couldn't find any package by glob 'python3.9-venv'
#10 10.93 E: Couldn't find any package by regex 'python3.9-venv'
```

### Data files (if applicable)
n/a

**Comment by nakib103** [comment]
Hello @muppetjones ,

Thanks for flagging this to us. We will see the feasibility of updating Ubuntu to next LTS.

Best regards,
Nakib

**Comment by nakib103** [comment]
Hello @muppetjones ,

The base image for Ensembl VEP docker will have a update from 18.04 to 22.04 (latest LTS) in the next release. Hopefully that will resolve your issue. If you face any further problem please feel free to open another ticket.

Best regards,
Nakib

**Comment by muppetjones** [comment]
Is there a timeline for the next release?

**Comment by nakib103** [comment]
Hello @muppetjones,

The new version is estimated to be out before the new year. 

Best regards,
Nakib

**Comment by nakib103** [comment]
Hello @muppetjones,

Coincidentally, Ensembl e111 has just been released today -
https://www.ensembl.info/2024/01/11/ensembl-111-has-been-released/

Best regards,
Nakib
