### ISSUE TITLE
MSG: ERROR: Cannot use format gff without Bio::DB::HTS::Tabix module installed

### ISSUE THREAD

**Issue by PierreLaplante** [Ensembl/ensembl-vep#1438]
## Describe the issue

I had to reinstall VEP after succesfully installing and using the tool once about a week ago.
I can't seem to be able to reinstall it, getting the following error:

MSG: ERROR: Cannot use format gff without Bio::DB::HTS::Tabix module installed

I am running the installation with the following options :

perl -I /home/home_dir/perl5/lib/perl5/ INSTALL.pl --NO_HTSLIB

I am running the --NO_HTSLIB option because I am not able to install it without. This is how I succeeded the first time.
I have tabix installed from bioconda, which doesn't seem to be a problem for the other .t files.

I have tried directly installing it through cpanm Bio::DB::HTS::Tabix which failed.

I didn't run into this problem last time, because, as I understood, VEP should be trying to install Bio::DB::Fasta module with --NO_HTSLIB.

Thank you for your help.

### System
- VEP version: 109.3
- Perl version: 5.30
- OS: CentOS 7
- tabix installed : yes, through conda

### Full VEP command line
```
perl -I /home/home_dir/perl5/lib/perl5/ INSTALL.pl --NO_HTSLIB
```

### Full error message
-------------------- EXCEPTION --------------------
MSG: ERROR: Cannot use format gff without Bio::DB::HTS::Tabix module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /mnt/nfs01/home/p_laplante@intra.igr.fr/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:162
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /mnt/nfs01/home/p_laplante@intra.igr.fr/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:247
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /mnt/nfs01/home/p_laplante@intra.igr.fr/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:94
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /mnt/nfs01/home/p_laplante@intra.igr.fr/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /mnt/nfs01/home/p_laplante@intra.igr.fr/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /mnt/nfs01/home/p_laplante@intra.igr.fr/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:361
STACK toplevel ./t/Runner.t:756
Date (localtime)    = Wed Jun 21 12:19:19 2023
Ensembl API version = 109
---------------------------------------------------

Test Summary Report
-------------------
./t/Runner.t                                       (Wstat: 65280 Tests: 73 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=49, Tests=1845, 285 wallclock secs ( 0.68 usr  0.33 sys + 206.39 cusr 22.52 csys = 229.92 CPU)
Result: FAIL
Failed 1/49 test programs. 0/1845 subtests failed.

**Comment by dglemos** [comment]
Hi @PierreLaplante,
That is correct, VEP shouldn't try to look for HTS tabix.
Can you check what is returned when you run `perl -e "use Bio::DB::HTS::Tabix"`?

An option is to uninstall the tabix (installed by conda), download the ensembl-vep and run an installation from scratch with --NO_HTSLIB

**Comment by PierreLaplante** [comment]
Hello @dglemos,

Thank you for your prompt response.
Actually, since this was the only test that failed, and as you said it shouldn't happen during a run with the --offline --cache options, I ran the the installation with --NO_TEST, which succeeded.
I then successfully annotated my VCFs with the following command :

./vep \
--input_file $f --output_file path/to/output/*.VEP_anno.vcf.gz \
--format vcf --vcf --everything --terms SO \
--species mus_musculus \
--symbol \
--offline --fasta $HOME/.vep/mus_musculus/109_GRCm39/Mus_musculus.GRCm39.dna.toplevel.fa --cache --merged --dir_cache $HOME/.vep/ \
--plugin Frameshift --plugin Wildtype \
--dir_plugins $HOME/.vep/Plugins/VEP_plugins/ \
--verbose \

For the sake of it here is what is returned from   perl -e "use Bio::DB::HTS::Tabix"  :

Can't locate Bio/DB/HTS/Tabix.pm in @INC (you may need to install the Bio::DB::HTS::Tabix module) (@INC contains: $HOME/perl5/lib/perl5/5.30.0/x86_64-linux-thread-multi /home/p_laplante@intra.igr.fr/perl5/lib/perl5/5.30.0 $HOME/perl5/lib/perl5/x86_64-linux-thread-multi /home/p_laplante@intra.igr.fr/perl5/lib/perl5 /mnt/beegfs/software/perl/5.30.0/lib/site_perl/5.30.0/x86_64-linux-thread-multi /mnt/beegfs/software/perl/5.30.0/lib/site_perl/5.30.0 /mnt/beegfs/software/perl/5.30.0/lib/5.30.0/x86_64-linux-thread-multi /mnt/beegfs/software/perl/5.30.0/lib/5.30.0) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.


On another note, I encountered a warning message that I'm not sure what to do with, regarding the Frameshift plugin : 

Use of uninitialized value in numeric lt (<) at $HOME/.vep/Plugins/VEP_plugins/Frameshift.pm line 129.
Use of uninitialized value in addition (+) at $HOME/.vep/Plugins/VEP_plugins/Frameshift.pm line 129.

Either of those, several time, but only for some VCFs.

I'm not sure if the Frameshift.pm plugin is your responsability, but if you have any idea what could be the cause (and especially the consequence) of this message?

**Comment by dglemos** [comment]
I'm glad you found a way to skip that failure especially when you don't need that type of annotation.

The Frameshift plugin is not part of our plugin inventory but looking at the code one of these values is undef:
`($tv->translation_start < $tv->translation_end ? $tv->translation_start : $tv->translation_end) + length($new_pep)`

Can you please send which variants are affected by this warning? The VCF could be missing some info or VEP is unable to calculate all the translation data.

**Comment by PierreLaplante** [comment]
How can I found out which variants are affected ? The error message doesn't specify at which positions I get the error.

**Comment by dglemos** [comment]
If you don't know which ones are affected you can send your input file to [helpdesk@ebi.ac.uk](mailto:helpdesk@ebi.ac.uk)

**Comment by dglemos** [comment]
Hi @PierreLaplante, 
Did you send your input file to helpdesk?
I didn't see any email from you just checking if you sent it.

**Comment by dglemos** [comment]
I'm going to close this issue but feel free to re-open it if you have any updates.

Best wishes,
Diana
