### ISSUE TITLE
lzma.h: No such file or directory with install v91 of the Ensembl API

### ISSUE THREAD

**Issue by BenoitFiset** [Ensembl/ensembl-vep#144]
Hi

the lzma.h dependancy seems to still be there....

Hello! This installer is configured to install v91 of the Ensembl API
[.. snip ..]
remote: Counting objects: 9627, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9627 (delta 3), reused 3 (delta 1), pack-reused 9619
Receiving objects: 100% (9627/9627), 6.98 MiB | 2.28 MiB/s, done.
Resolving deltas: 100% (6689/6689), done.
warning: Remote branch 1.3.2 not found in upstream origin, using HEAD instead
 - building HTSLIB in ./htslib
[.. snip ..]
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c:61:18: fatal error: lzma.h: No such file or directory
 #include <lzma.h>

Tips ?

Thanks,

B.

**Comment by ens-lgil** [comment]
Dear Benoît,

It looks like your machine is missing the xz package.
I found the following discussion solving the missing xz package, for the htslib installation: https://discussions.apple.com/thread/7895857

Best regards,
Laurent

**Comment by ens-lgil** [comment]
Please feel free to reopen if the issue persists.

**Comment by heihaheihaha** [comment]
The above link does not solve my problem, I slove the problem by a crude means.
I copy _lzma.h_ and _lzma/_ fileflod from my _minconda/pkgs/xz-version/_ to _ensembl-vep/htslib/_ 
then `perl INSTALL.pl`
unbelieveable, it seem that works very well, I have wasted 2 days on it.
