### ISSUE TITLE
How to prioritize MANE PLUS CLINICAL isoforms?

### ISSUE THREAD

**Issue by Heredia-Maria** [Ensembl/ensembl-vep#1443]
Dear Ensembl team:
I came across with an issue during the analysis of my otput. I would like to prioritize variants in MANE PLUS CLINICAL transcrips when available, in front of MANE isoforms. I have seen the flag pick_order in your vep documentation. However, I can not see any specific way to prioritize this PLUS CLINICAL field. Valid criteria are: [ canonical appris tsl biotype ccds rank length mane ]. e.g.:

I would like to know if is there any way, please 

Thanks in advance.
Kind regards,

María.

**Comment by Heredia-Maria** [comment]
Hi @olaaustine. 

I'm using release 109 and GRCh38. 
Thanks for your quick response.

María.

**Comment by Heredia-Maria** [comment]
Hi Ola. I will try as soon as possible and give you feedback.

Thank you
María.

**Comment by Heredia-Maria** [comment]
Hi Ola. The prioritization is now working properly! 

Thank you very much
María.

**Comment by Heredia-Maria** [comment]
Hi Ola. 

The prioritization is now working for most genes! However, I still have some issues. For example, in the case of NOX1 "ENSG000007952", which have two gold isoforms in Ensembl, the one prioritized is not the gold MANE isoform, but the other one. Why is this happening? Finally, my main objective would be to annotate the variants on the same sequences that are collected in UniProt, but I am not succeeding.

Thank you very much
María.

**Comment by olaaustine** [comment]
Hi @Heredia-Maria,

Thank you very much for letting us know. 

To better investigate the issue, what transcripts are the two gold isoforms in Ensembl?

The [gene NOX1](https://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000007952;r=X:100843324-100874359) in the example has the transcript [ENST00000372966](https://www.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000007952;r=X:100843324-100874359;t=ENST00000372966). 

Thank you very much
Ola.

**Comment by Heredia-Maria** [comment]
Hi @olaaustine,

The two gold isoforms in Ensemble are: ENST00000372966.8 (MANE) and ENST00000217885.5. 
The isoforms on which my variants have been annotated are: ENST00000217885 (16 variants) and ENST00000372960 (2 variants). Not the MANE Select here...

Thank you very much.
María.

**Comment by Heredia-Maria** [comment]
Hi @olaaustine 

The command used is the following:
./vep --offline --cache --fa Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz --format vcf --tab -i ./../Escritorio/DataBasesData/clinvar_20230213.vcf --show_ref_allele --total_length --mane --verbose --variant_class --force_overwrite --hgvs --symbol --uniprot --gencode_basic --canonical --biotype --exclude_predicted --no_intergenic --protein --shift_3prime 1 --pick_order biotype,ccds,rank --pick --custom clinvar.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNDN -o NMD_20230213_output.txt -plugin Downstream -plugin ProteinSeqs,references.fa,mutated.fa -plugin NMD

The input file is the whole bunch of variants downloaded from ClinVar. I attach here an vcf with the variants just for NOX1. 
[NOX1.txt](https://github.com/Ensembl/ensembl-vep/files/11906113/NOX1.txt)

Thank you very much,
María.

**Comment by olaaustine** [comment]
Hi @Heredia-Maria, 

Looking at your command, the --pick_order should be  `--pick_order mane_plus_clinical,mane_select,canonical,appris,tsl,biotype,ccds,rank,length ` which priorities mane. 
 
More about the gold isoforms in Ensembl can be seen [here](https://www.ensembl.org/Help/View?id=151#:~:text=A%20gold%2C%20or,beginning%20with%200.)
Please let us know if this helps. 
Thank you 
Ola

**Comment by Heredia-Maria** [comment]
Hi @olaaustine 
 
I was also working with the old output!!  It is everything working properly, even without the biotype flag. Anyways I will try to use it and compare both outputs. 

Thank you so much for your help and your patience.
Kind regards,
María.

**Comment by olaaustine** [comment]
Hi @Heredia-Maria, 

Thank you very much for letting us know. 

I will close this ticket now. Please feel free to open another ticket or reopen this if you have another query. 

Thank you. 
Ola.
