### ISSUE TITLE
Inframe variants do not produce mutated protein sequences.

### ISSUE THREAD

**Issue by zincuum** [Ensembl/ensembl-vep#1445]
## Additional information
I wanted to know the mutated protein sequence of indels, so I tried to annotate frameshift indels and inframe indels using vep. 
As shown below, I ran --wildtype --frameshift as an option, and frameshift indels showed both wildtype protein sequences and mutant protein sequences, but inframe indels only came out wildtype protein sequences (splice or stop gains and those tied together with '&' excluded). Is inframe not supported yet?

### Full VEP command line
vep \
-i ${VCFPATH}${VCF} \
-o ${VCFPATH}${OUTPUT} \
--verbose \
--everything \
--assembly GRCh38 \
--pick \
--stats_file ${VCFPATH}${ID}_vep_summary.html \
--fork 4 \
--cache --dir_cache /data/public/VEP/108 \
--check_frequency --freq_pop gnomADe_EAS --freq_freq 0.01 --freq_filter exclude \
--cache_version 108 \
--offline --format vcf --vcf --symbol --terms SO --tsl --biotype \
--fasta $REF --hgvs \
--force_overwrite \
--dir_plugins /data/public/VEP/108/Plugins \
--plugin Downstream \
--plugin Frameshift --plugin Wildtype

### Full error message
> Including the warnings, if available

**Comment by likhitha-surapaneni** [comment]
Hi @zincuum , thank you for reaching out.

Downstream plugin currently supports only frameshift variants.

WildType and Frameshift plugins are a part of the pVACtools immunotherapy tools suite:
https://github.com/griffithlab/pVACtools/tree/master/pvactools/tools/pvacseq/VEP_plugins
We would recommend contacting them regarding the plugins.

Kind regards,
Likhitha

**Comment by likhitha-surapaneni** [comment]
Hi @zincuum , I am closing the ticket for now. Please feel free to open a new ticket if you face any other issues
