### ISSUE TITLE
RefSeq Mitochondria transcript annotations missing 

### ISSUE THREAD

**Issue by davmlaw** [Ensembl/ensembl-vep#1447]
Hi, RefSeq annotations do not appear to be working for mitochondria

This was [reported against a closed issue](https://github.com/Ensembl/ensembl-vep/issues/464#issuecomment-1423159351), so you may have missed it 

It doesn't work for 107 GRCh37 or GRCh38 and the @gabrielhim reports it doesn't work on 108.2

**Comment by likhitha-surapaneni** [comment]
Hi @davmlaw , thank you for flagging this. We are currently investigating this in https://github.com/Ensembl/ensembl-vep/issues/1425. Please feel free to add comments if you have any related issues or suggestions!

Kind regards,
Likhitha
