### ISSUE TITLE
DBD::mysql::st execute failed

### ISSUE THREAD

**Issue by Avinash-git-py** [Ensembl/ensembl-vep#1452]
I have installed the needed plugins and I executed those plugins it works well, but today I tried to run the command it shows error "DBD::mysql::st execute failed:". I tried to resolve the issue but I'm not able resolve this error.

The error that I have faced:
DBD::mysql::st execute failed: Table 'seq_region' is marked as crashed and should be repaired at /path/to/CoordSystemAdaptor.pm line 261.

The command that I have used to run:
./vep --cache -i input.vcf -o output.txt --plugin Blosum62 --plugin G2P,"file=/media/ngslinux/External Disk/ensembl-vep/merged_file.csv" --plugin Downstream --plugin HGVSIntronOffset --plugin NearestExonJB --plugin LoFtool --plugin LOVD --tab

**Comment by alicia-hgim** [comment]
Hi
I got the same error today. This is my output:
DBD::mysql::st execute failed: Table 'seq_region' is marked as crashed and should be repaired at /ensembl-vep/Bio/EnsEMBL/DBSQL/CoordSystemAdaptor.pm line 261
Did you manage to fix it?
Thanks!

**Comment by nakib103** [comment]
Hello @Avinash-git-py @alicia-hgim ,

Thanks for reporting it to us, we are already looking into it. We will let you once we have a update.

Best regards,
Nakib

**Comment by soumyarao86** [comment]
Hello,

I got the exact same issue.
I am not sure of it's an the installation issue, as I reinstalled the ensembl-vep package and its dependencies under the base environment, and it no longer throws errors when I run 'vep' as a test command or vep --help (the 'perl-compress-raw-zlib' package from the bioconda catalog was too old, so I had to use the one from the conda-forge catalog instead).
But when I give an input it shows the same error as stated above.
```
DBD::mysql::st execute failed: Table 'seq_region' is marked as crashed and should be repaired at /home/srng3/anaconda3/share/ensembl-vep-109.3-1/Bio/EnsEMBL/DBSQL/CoordSystemAdaptor.pm line 261.
```

**Comment by anaduba** [comment]
Hello!
I have exactly the same error. VEP was working locally on Friday but yesterday started crashing. I've tried to reinstall VEP and the databases but still not working.
Thanks!

**Comment by alicia-hgim** [comment]
Hi
For me its working now. Didnt throw any error. I didnt change nothing

**Comment by nakib103** [comment]
Hello, 

Thanks for checking. I can confirm that the issue has been fixed.
I am going to close this issue but if you face any further problem please feel free to reach back to us.

Best regards,
Nakib

**Comment by alicia-hgim** [comment]
Hi
I am getting this error now: 
DBD::mysql::st execute failed: Table 'meta' is marked as crashed and should be repaired at /ensembl-vep/Bio/EnsEMBL/DBSQL/BaseMetaContainer.pm line 140.
Thanks in advance!

**Comment by nakib103** [comment]
@alicia-hgim ,
Thanks for reporting! It has been fixed - can you check again? Thanks!

**Comment by alicia-hgim** [comment]
now it works :)
Thanks!

**Comment by soumyarao86** [comment]
Hi, it didn't repeat but vep now throws a new error.
Do I need to reinstall VEP or a way around?

$ vep -i paxgene1_L003_L004_raw_sorted.g.vcf.gz --cache

-------------------- EXCEPTION --------------------
MSG: ERROR: Cache directory /home/srng3/.vep/homo_sapiens not found

STACK Bio::EnsEMBL::VEP::CacheDir::dir /home/srng3/anaconda3/share/ensembl-vep-109.3-1/modules/Bio/EnsEMBL/VEP/CacheDir.pm:305
STACK Bio::EnsEMBL::VEP::CacheDir::init /home/srng3/anaconda3/share/ensembl-vep-109.3-1/modules/Bio/EnsEMBL/VEP/CacheDir.pm:219
STACK Bio::EnsEMBL::VEP::CacheDir::new /home/srng3/anaconda3/share/ensembl-vep-109.3-1/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /home/srng3/anaconda3/share/ensembl-vep-109.3-1/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:116
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/srng3/anaconda3/share/ensembl-vep-109.3-1/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:92
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/srng3/anaconda3/share/ensembl-vep-109.3-1/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /home/srng3/anaconda3/share/ensembl-vep-109.3-1/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::run /home/srng3/anaconda3/share/ensembl-vep-109.3-1/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel /home/srng3/anaconda3/bin/vep:46
Date (localtime)    = Thu Jul 20 11:40:19 2023
Ensembl API version = 109
---------------------------------------------------

**Comment by nakib103** [comment]
Hello @soumyarao86,

Great to know that the error is not showing for you anymore! 

Could it be that while re-installing VEP you deleted the cache files? Can you try re-installing the cache files again and see if it fixes your issue. To install cache for human for example you can run - 
```
perl INSTALL.pl --AUTO c --species homo_sapiens
```

Best regards,
Nakib

**Comment by soumyarao86** [comment]
Thanks Nakib.
I couldn't find INSTALL.pl in VEP env.
Any idea on where to locate it?

**Comment by nakib103** [comment]
It resides in the base dir of the `ensembl-vep` repository. So it will be in the same directory as `vep` executable. See - 
https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html

And in case you are using docker you can also just call - 
`INSTALL.pl --AUTO c --species homo_sapiens`

Best regards,
Nakib

**Comment by miamihailovic1** [comment]
To whom it may concern, 
I am getting the error above today. DBD::mysql::st execute failed: Table 'seq_region' is marked as crashed and should be repaired at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/DBSQL/CoordSystemAdaptor.pm line 261.

The command I was running: 
vep -i <input_file> --cache --dir data/vep_data --mane --pick --pick_order mane_select --total_length --vcf --output_file <output_file>

**Comment by nakib103** [comment]
Hello @miamihailovic1,

Thanks for notifying! We are checking the issue and will update here once we have more information.

Best regards,
Nakib

**Comment by Rmulet** [comment]
I also get the same error. I reinstalled VEP several times, to no avail.

**Comment by nakib103** [comment]
Thanks @Rmulet!
@miamihailovic1 , the issue has been fixed. Can you confirm it is working for you?
