### ISSUE TITLE
Usage of custom annotations per release 110 documentation produces error on VEP 109

### ISSUE THREAD

**Issue by lacek** [Ensembl/ensembl-vep#1453]
## Describe the issue
In the [documentation](https://asia.ensembl.org/info/docs/tools/vep/script/vep_custom.html), it is described that the syntax for `--custom` options is

```sh
./vep [...] --custom file=Filename,short_name=Short_name,format=File_type,type=Annotation_type,coords=Force_report_coordinates,fields=VCF_fields
```

and that an example for ClinVar VCF is

```sh
./vep [...] --custom file=clinvar.vcf.gz,short_name=ClinVar,format=vcf,type=exact,coords=0,fields=CLNSIG%CLNREVSTAT%CLNDN
```

However, I get error `New type "type=exact" is not valid` when using such syntax.

In the older version of [doc](http://feb2023.archive.ensembl.org/info/docs/tools/vep/script/vep_custom.html) I found the syntax without "keys" working, e.g.

```sh
docker run -it --rm \
    -v ~/.vep:/opt/vep/.vep \
    ensemblorg/ensembl-vep:release_109.3 vep \
    --custom clinvar.vcf.gz,ClinVar,vcf,exact,0,CLNSIG \
    -i test.vcf --o result.vcf
```

I think it would be better the describe both syntax along with the new one in the documentation for a while as not every body will be using the latest version of VEP.

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 109.3
- VEP Cache version: 109
- Perl version: 5.26.1
- OS: Ubuntu (Docker)
- tabix installed: yes

### Full VEP command line
```
docker run -it --rm \
    -v ~/.vep:/opt/vep/.vep \
    ensemblorg/ensembl-vep:release_109.3 vep \
    --custom file=clinvar.vcf.gz,short_name=ClinVar,format=vcf,type=exact,coords=0,fields=CLNSIG \
    -i test.vcf --o result.vcf
```

### Full error message
```
MSG: ERROR: New type "type=exact" is not valid

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::type /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:233
STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:146
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:247
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:94
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel /opt/vep/src/ensembl-vep/vep:46
Date (localtime)    = Tue Jul 18 09:58:11 2023
Ensembl API version = 109
```

**Comment by nuno-agostinho** [comment]
Hi @lacek, thanks for your feedback.

Our intention was to highlight the new `--custom` usage in VEP 110, making it easier to use and supporting new features. As you mentioned, the old usage (which is still compatible with VEP 110) is documented in archive versions of the Ensembl website and can still be accessed.

Anyway, I will talk with the team about whether to document the old usage. Thanks again for your suggestion!

Kind regards,
Nuno

**Comment by nuno-agostinho** [comment]
Hey @lacek,

We updated our documentation for custom usage in VEP 109 and earlier. This is will be visible in our website in our next release.

Thanks for reporting this issue!

Best,
Nuno
