### ISSUE TITLE
VEP can't find mysql in @INC

### ISSUE THREAD

**Issue by cgy0627** [Ensembl/ensembl-vep#1458]
## Describe the issue
I installed all the prerequisites as outlined in the installations guideline. However, for DBD::mysql, due to system-related problems (error : /lib64/libc.so.6: version GLIBC_2.35' not found (required by /home/linuxbrew/.linuxbrew/opt/gcc/lib/gcc/current/libgcc_s.so.1)), I installed DBD::mysql using `sudo cpanm DBD::mysql` (everything else was installed through `cpanm` without the sudo).

I finished installing by `perl INSTALL.pl --NO_TEST`, but somehow when I run ./vep it can't find mysql in @INC.

Checking whether DBD::mysql gives me this:
`sudo cpanm DBD::mysql`
>DBD::mysql is up to date. (4.050)

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 110
- VEP Cache version: 110
- Perl version: 5.26 (when I use sudo it's 5.32)
- OS: 6.1.38-59.109.amzn2023.x86_64

### Full VEP command line
```
./vep -i examples/homo_sapiens_GRCh38.vcf --cache
```

### Full error message
> Smartmatch is experimental at /home/ec2-user/programs/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 472.
> install_driver(mysql) failed: Can't locate DBD/mysql.pm in @INC (you may need to install the DBD::mysql module) (@INC contains: /home/ec2-user/programs/ensembl-vep/modules /home/ec2-user/programs/ensembl-vep /home/ec2-user/programs/BioPerl-1.6.924 /home/ec2-user/perl5/perlbrew/perls/5.26.2/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/ec2-user/perl5/perlbrew/perls/5.26.2/lib/site_perl/5.26.2 /home/ec2-user/perl5/perlbrew/perls/5.26.2/lib/5.26.2/x86_64-linux-thread-multi /home/ec2-user/perl5/perlbrew/perls/5.26.2/lib/5.26.2) at (eval 77) line 3.
> Perhaps the DBD::mysql perl module hasn't been fully installed,
> or perhaps the capitalisation of 'mysql' isn't right.
> Available drivers: DBM, ExampleP, File, Gofer, Mem, Proxy, Sponge.
>  at /home/ec2-user/programs/ensembl-vep/Bio/EnsEMBL/Registry.pm line 1771.

**Comment by dglemos** [comment]
Hi @cgy0627,
You probably have more than one installation of Perl. When you installed MySQL with sudo it got installed in a different version than the one used by VEP.
In your first error `(error : /lib64/libc.so.6: version GLIBC_2.35' not found (required by /home/linuxbrew/.linuxbrew/opt/gcc/lib/gcc/current/libgcc_s.so.1))` you probably need to upgrade your libc6 package. After that, you could try to install MySQL again without sudo.

**Comment by cgy0627** [comment]
Thanks for the reply.
I'm not too familiar with the system packages like the libc6, but I found out that it's ok to have multiple glibc packages as long as they are in non-standard paths. So I now have the glibc-2.35 in the /opt path, but I don't know how to use this to run `cpanm DBD::mysql` only.
I tried `export LD_LIBRARY_PATH=/opt/glibc-2.35/lib` but that caused Segmentation fault for everything in the system.

How can I go about this without breaking the whole system?

**Comment by cgy0627** [comment]
I actually did try that, but got stuck on what to put for "myapp" in the command line since I'm trying to use the new glibc for `cpanm DBD::mysql`. I left a question for patchelf but still waiting for their reply.

**Comment by dglemos** [comment]
Hi @cgy0627,
Do you have any news?

**Comment by dglemos** [comment]
I'm going to close this issue but feel free to open a new one if you have more questions.

Best wishes,
Diana
