### ISSUE TITLE
VEP Docker base image uplift

### ISSUE THREAD

**Issue by mvforster** [Ensembl/ensembl-vep#1467]
## Describe the issue
I am unable to use an updated base image for building VEP containers due to a requirement by some modules to use Python 2.7's pip, which reached End Of Life at the end of 2019. The current base image is Ubuntu 18.04 which reached End Of Life at the end of May this year. 

The issue appears to be around the dependencies for Pon_P2 and FATHMM which require the following libraries which are no longer provided or supported:
python
python-pip
python-setuptools
python-dev

I have attempted to circumvent these by trying to use the `universe` repo but this is not an ideal solution.

As both of these plugins are official plugins would it be possible to liaise with the developers of these up update their code to make it compatible with Python 3.10+ ?

**Comment by mvforster** [comment]
Dear @dglemos,

Many thanks for your reply.

Let me know if I can be of any help in porting code to Python3 😄 

Best wishes,

Matthieu

**Comment by mvforster** [comment]
Dear @dglemos 
Update:
I have been able to successfully complete a build of the VEP110 container with a modern version of Ubuntu.

I have opened the following pull request (https://github.com/Ensembl/ensembl-vep/pull/1546) with the changes that I needed to make to get the container to build. I hope that this will help the team in their efforts.

**Comment by nakib103** [comment]
Hello @mvforster,

It is nice hearing you that you have been able to resolve the issue. Thanks for your PR, we are reviewing it currently and get back to you shortly.

Best regards,
Nakib

**Comment by nakib103** [comment]
@mvforster 

The ensembl-vep Dockerfile has been updated to use a more recent version of Ubuntu. I am closing this issue as the progress of the PR you mentioned is stale. Anything related to the changes in the PR can be discussed there.

Best regards,
Nakib
