### ISSUE TITLE
not able to download vep  image

### ISSUE THREAD

**Issue by anuj348** [Ensembl/ensembl-vep#1469]
## Describe the issue
I am trying to download the latest image but getting errors

### System
- VEP version: [e.g. 98 or 98.1] 
- VEP Cache version: [e.g. 98]
- Perl version: [e.g. 5.26]
- OS: [e.g. MacOS, Ubuntu, CentOS]
- tabix installed ?

### Full VEP command line
```
singularity pull docker://ensemblorg/ensembl-vep:latest
```

### Full error message
WARN[0000] "/run/user/5239" directory set by $XDG_RUNTIME_DIR does not exist. Either create the directory or unset $XDG_RUNTIME_DIR.: stat /run/user/5239: no such file or directory: Trying to pull image in the event that it is a public image.
FATAL:   While making image from oci registry: failed to get checksum for docker://ensemblorg/ensembl-vep:latest: Error reading manifest latest in docker.io/ensemblorg/ensembl-vep: manifest unknown: OCI index found, but accept header does not support OCI indexes

**Comment by nuno-agostinho** [comment]
Hello @anuj348,

I just tried to pull the latest VEP container using that exact command and it worked for me.

Can you try to see if you are able to download other containers?

Thanks,
Nuno

**Comment by MikeWLloyd** [comment]
We can pull 109.3, and earlier (note that I have removed HPC specific WARN statements): 

```
$ singularity pull docker://ensemblorg/ensembl-vep:release_109.3

INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:0c5227665c11379f79e9da3d3e4f1724f9316b87d259ac0131628ca1b923a392
Copying blob sha256:fd763e33f9c71ec3ae9876d6873e5c6eefda66bb23224c05c290bd052c86c9ec

... <TRUNCATED STDOUT> ...

2023/07/31 10:01:25  info unpack layer: sha256:f75685bf48060a33ec752d2c6309767689c56da723c3369fa879677497168f1a
2023/07/31 10:01:25  info unpack layer: sha256:da7895fae97fc5181aaf02d89c76d4153c9e76e99883930dd60096b7e5083bf3
INFO:    Creating SIF file...
```

But can not pull 110.0 or 110.1. We see the following fatal errors (note that I removed HPC specific WARN statements): 

```
$ singularity pull docker://ensemblorg/ensembl-vep:release_110.1
FATAL:   While making image from oci registry: failed to get checksum for docker://ensemblorg/ensembl-vep:release_110.1: Error reading manifest release_110.1 in docker.io/ensemblorg/ensembl-vep: manifest unknown: OCI index found, but accept header does not support OCI indexes
```

```
$ singularity pull docker://ensemblorg/ensembl-vep:release_110.0
FATAL:   While making image from oci registry: failed to get checksum for docker://ensemblorg/ensembl-vep:release_110.0: Error reading manifest release_110.0 in docker.io/ensemblorg/ensembl-vep: manifest unknown: OCI index found, but accept header does not support OCI indexes
```

We are limited to the following Singularity version on our HPC:

```
singularity --version
singularity version 3.4.1
```

**Comment by nuno-agostinho** [comment]
Hi @MikeWLloyd,

We updated the Docker image build process for VEP 110 to allow us to build multi-platform images with some modern settings. Singularity 3.6.4 seems the earliest version working with our new build process.

[Singularity 3.4.1](https://github.com/apptainer/singularity/releases?page=3) is almost 4 years old and doesn't comply with modern multi-platform Docker images. Singularity v3.5.3 (and earlier) do not support VEP 110 and even other official Docker images, such as ubuntu:
```
singularity pull docker://ubuntu
```

Would it be possible to update Singularity? 

Thanks,
Nuno

**Comment by MikeWLloyd** [comment]
Our default supported version in our HPC is 3.4.1, we have access to an updated version (though not officially supported by our IT group). I can confirm the update to Singluarity resolved our issue. Thank you for your input.
