### ISSUE TITLE
"File does not exist" error when running ensembl-vep with docker

### ISSUE THREAD

**Issue by zivlang** [Ensembl/ensembl-vep#1471]
## Describe the issue
I installed ensembl-vep with Docker as instructed in the documentation, and when I tied running the program the error message was printed,

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

The following information, except for the ensembl-vep version, is of the Linux system, not of the Docker container.
### System
- VEP version: 110
- VEP Cache version: Couldn't find the cache version
- Perl version: v5.30.0
- OS: Linux
- tabix installed ? No

## vep installation:

```
docker run -t -i -v $HOME/vep_data:/data ensemblorg/ensembl-vep INSTALL.pl -a cf -s homo_sapiens -y GRCh38
 - getting list of available cache files
```

>WARNING: It looks like you already have the cache for homo_sapiens GRCh38 (v110) installed.
>
>Delete the folder /opt/vep/.vep/homo_sapiens/110_GRCh38 and re-run INSTALL.pl if you want to re-install
> - skipping homo_sapiens
> - downloading Homo_sapiens.GRCh38.dna.toplevel.fa.gz
> - downloading Homo_sapiens.GRCh38.dna.toplevel.fa.gz.fai
> - downloading Homo_sapiens.GRCh38.dna.toplevel.fa.gz.gzi
>
>The FASTA file should be automatically detected by the VEP when using --cache or --offline.
>If it is not, use "--fasta /opt/vep/.vep/homo_sapiens/110_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz"
>
>
>All done

### Full VEP command line
```
docker run -v $HOME/vep_data:/data ensemblorg/ensembl-vep \
  vep --cache --offline --format vcf --vcf --force_overwrite --everything\
      --input_file input/1000123_23191_0_0.g.vcf \
      --output_file output/my_output.vcf
```

### Full error message
> Smartmatch is experimental at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 472.
>
>-------------------- EXCEPTION --------------------
>MSG: ERROR: File "input/1000123_23191_0_0.g.vcf" does not exist
>
>STACK Bio::EnsEMBL::VEP::Parser::file /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm:237
>STACK Bio::EnsEMBL::VEP::Parser::new /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm:131
>STACK Bio::EnsEMBL::VEP::Runner::get_Parser /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:802
>STACK Bio::EnsEMBL::VEP::Runner::get_InputBuffer /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:829
>STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:136
>STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:200
>STACK toplevel /opt/vep/src/ensembl-vep/vep:46
>Date (localtime)    = Sun Aug  6 18:49:23 2023
>Ensembl API version = 110
>---------------------------------------------------

**Comment by nuno-agostinho** [comment]
Hi @zivlang,

By using `-v $HOME/vep_data:/data`, the VEP Docker container has access to the data in your `$HOME/vep_data` folder and you should give the path exactly as the data is organised in that folder. If your VCF file is located in `$HOME/vep_data/1000123_23191_0_0.g.vcf`, could try simply using `--input 1000123_23191_0_0.g.vcf`?

If this doesn't work, please tell me how your folder is organised. Thanks!

Kind regards,
Nuno

**Comment by zivlang** [comment]
Thank you for replying.
I tried your suggestion and got the same error message.

Here is the basic directories' structure:

├── input
│   └── 1000123_23191_0_0.g.vcf
├── output
└── vep_data

(vep_data includes many directories so I didn't include them).
Is that what you asked for?

‫בתאריך יום ב׳, 7 באוג׳ 2023 ב-13:13 מאת ‪Nuno Agostinho‬‏ <‪
***@***.***‬‏>:‬

**Comment by nuno-agostinho** [comment]
Hi @zivlang,

Is the path to that folder `$HOME/vep_data`? If so, your first command should have worked.

Let's try something different: entering the VEP image in interactive mode and looking for the file. Please run this command to start bash inside the VEP image and check for the files inside your working directory:

```
docker run -ti -v $HOME/vep_data:/data ensemblorg/ensembl-vep bash
ls
```

What is the result of these commands?

Thanks,
Nuno

**Comment by zivlang** [comment]
***@***.***:~/.vep$ ls
homo_sapiens  homo_sapiens_vep_110_GRCh38.tar.gz

‫בתאריך יום ג׳, 8 באוג׳ 2023 ב-11:23 מאת ‪Nuno Agostinho‬‏ <‪
***@***.***‬‏>:‬

**Comment by zivlang** [comment]
Is there an alternative way to use ensembl-vep?

בתאריך יום ג׳, 8 באוג׳ 2023, 13:02, מאת Ziv Lang ***@***.***>:

**Comment by zivlang** [comment]
By installing with the perl script without the docker container?

בתאריך יום ד׳, 9 באוג׳ 2023, 19:44, מאת Ziv Lang ***@***.***>:

**Comment by zivlang** [comment]
You mean changing the path in the file provided in the --path parameter?
for instance

      --input_file home/user/input/1000123_23191_0_0.g.vcf \

instead of

      --input_file input/1000123_23191_0_0.g.vcf \
?


‫בתאריך יום ב׳, 7 באוג׳ 2023 ב-13:13 מאת ‪Nuno Agostinho‬‏ <‪
***@***.***‬‏>:‬

**Comment by nuno-agostinho** [comment]
Hi @zivlang,

No, I mean changing the source folder used in the mounting parameter `-v $HOME/vep_data:/data`. Currently, `$HOME/vep_data` only contains the cache data, so instead of using `$HOME/vep_data`, you should use the folder path containing your input variant data.

Best,
Nuno

**Comment by zivlang** [comment]
Thanks, I'll try.

‫בתאריך יום ב׳, 14 באוג׳ 2023 ב-12:35 מאת ‪Nuno Agostinho‬‏ <‪
***@***.***‬‏>:‬

**Comment by zivlang** [comment]
Is this what you meant?
docker run -v /home/dnanexus/input:/data ensemblorg/ensembl-vep   vep
--cache --offline --format vcf --vcf --force_overwrite --everything
 --input_file input/1000123_23191_0_0.g.vcf       --output_file
output/my_output.vcf

That resulted in

-------------------- EXCEPTION --------------------
MSG: ERROR: Cache directory /opt/vep/.vep/homo_sapiens not found

STACK Bio::EnsEMBL::VEP::CacheDir::dir
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:305
STACK Bio::EnsEMBL::VEP::CacheDir::init
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:219
STACK Bio::EnsEMBL::VEP::CacheDir::new
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:116
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:92
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::run
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:200
STACK toplevel /opt/vep/src/ensembl-vep/vep:46
Date (localtime)    = Mon Aug 14 09:59:47 2023
Ensembl API version = 110

‫בתאריך יום ב׳, 14 באוג׳ 2023 ב-12:43 מאת ‪Ziv Lang‬‏ ***@***.***
‬‏>:‬

**Comment by zivlang** [comment]
Why not use the path $HOME/vep_data ? because it doesn't work for some
unknown reason?

‫בתאריך יום ב׳, 14 באוג׳ 2023 ב-13:12 מאת ‪Nuno Agostinho‬‏ <‪
***@***.***‬‏>:‬

**Comment by nuno-agostinho** [comment]
You can use `$HOME/vep_data` if you prefer, it's all the same as long the data is all in the folder you use.

**Comment by zivlang** [comment]
The data was in $HOME/vep_data , right? So how come the previous command
didn't work?
I tried the command
docker run -v /home/dnanexus/input:/data ensemblorg/ensembl-vep   vep
--cache --offline --format vcf --vcf --force_overwrite --e
verything      --input_file input/1000123_23191_0_0.g.vcf
--output_file output/my_output.vcf
after moving the data at $HOME/vep_data, as suggested, and got the
following error message

MSG: ERROR: File "input/1000123_23191_0_0.g.vcf" does not exist

STACK Bio::EnsEMBL::VEP::Parser::file
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm:237
STACK Bio::EnsEMBL::VEP::Parser::new
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm:131
STACK Bio::EnsEMBL::VEP::Runner::get_Parser
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:802
STACK Bio::EnsEMBL::VEP::Runner::get_InputBuffer
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:829
STACK Bio::EnsEMBL::VEP::Runner::init
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:136
STACK Bio::EnsEMBL::VEP::Runner::run
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:200
STACK toplevel /opt/vep/src/ensembl-vep/vep:46
Date (localtime)    = Mon Aug 14 10:47:42 2023
Ensembl API version = 110

Maybe it would be easier to use ensembl-vep without a Docker container?

‫בתאריך יום ב׳, 14 באוג׳ 2023 ב-13:46 מאת ‪Nuno Agostinho‬‏ <‪
***@***.***‬‏>:‬

**Comment by nuno-agostinho** [comment]
Hi @zivlang,

You need to directly mount the folder as you want to use it in Docker. If you want to use the input as `input/1000123_23191_0_0.g.vcf`, you have to mount the folder with `-v /home/dnanexus:/data`.

Also, more information on mounting Docker volumes can be found in https://docs.docker.com/storage/volumes/.

Best,
Nuno

**Comment by zivlang** [comment]
I moved the directory's content  and run the following command and got the
error message that follows. I don't know what to do, What more can be done?
$ sudo mv vep_data/* input/
$ docker run -v /home/dnanexus:/data ensemblorg/ensembl-vep   vep --cache
--offline --format vcf --vcf --force_overwrite --everyth
ing      --input_file input/1000123_23191_0_0.g.vcf       --output_file
output/my_output.vcf
Smartmatch is experimental at
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm
line 472.

-------------------- EXCEPTION --------------------
MSG: ERROR: Cache directory /opt/vep/.vep/homo_sapiens not found

STACK Bio::EnsEMBL::VEP::CacheDir::dir
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:305
STACK Bio::EnsEMBL::VEP::CacheDir::init
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:219
STACK Bio::EnsEMBL::VEP::CacheDir::new
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:116
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:92
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::run
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:200
STACK toplevel /opt/vep/src/ensembl-vep/vep:46
Date (localtime)    = Mon Aug 14 14:16:59 2023
Ensembl API version = 110

‫בתאריך יום ב׳, 14 באוג׳ 2023 ב-14:18 מאת ‪Nuno Agostinho‬‏ <‪
***@***.***‬‏>:‬

**Comment by nuno-agostinho** [comment]
Hi @zivlang,

When you mount `/home/dnanexus` as `/data`, this means that VEP Docker container will use your `/home/dnanexus` folder as its working directory, as written in our [public documentation](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker).

By default, VEP will look for the cache in `/home/dnanexus`. If you are moving the cache data to `/home/dnanexus/input`, you will have to indicate that to VEP by using the option `--dir_cache input`.

Please can you either move the cache data to `/home/dnanexus` or run VEP with option `--dir_cache input`? Hopefully it will work now. Thanks!

Cheers,
Nuno

**Comment by zivlang** [comment]
I tried moving the files out of the directories to home/dnanexus:

$ ls
1000123_23191_0_0.g.vcf   dx_stderr    homo_sapiens
 job-GYJ4xBQJ79XJxX166b11GJj9          job_input.json  vep_data
dnanexus-executable.json  dx_stdout    homo_sapiens_vep_110_GRCh38.tar.gz
job-GYJ4xBQJ79XJxX166b11GJj9.code.py  nohup.out
dnanexus-job.json         environment  input
job_error_reserved_space              output

and run the command
$ sudo docker run -v /home/dnanexus:/data ensemblorg/ensembl-vep   vep
--cache --offline --format vcf --vcf --force_overwrite
--everything      --input_file 1000123_23191_0_0.g.vcf       --output_file
output/my_output.vcf

which led to the following error message

-------------------- EXCEPTION --------------------
MSG: ERROR: Could not write to stats file output/my_output.vcf_summary.html

STACK Bio::EnsEMBL::VEP::BaseRunner::get_stats_file_handle
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:275
STACK Bio::EnsEMBL::VEP::Runner::init
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:147
STACK Bio::EnsEMBL::VEP::Runner::run
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:200
STACK toplevel /opt/vep/src/ensembl-vep/vep:46
Date (localtime)    = Mon Aug 14 16:36:19 2023
Ensembl API version = 110
---------------------------------------------------
2023-08-14 16:36:19 - INFO: Disabling --hgvs; using --offline and no FASTA
file found

‫בתאריך יום ב׳, 14 באוג׳ 2023 ב-17:42 מאת ‪Nuno Agostinho‬‏ <‪
***@***.***‬‏>:‬

**Comment by nuno-agostinho** [comment]
Hi @zivlang,

If you are having permission issues, you can follow the instructions in https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker:

1. Use option `:Z` within the Docker `-v` option (requires Docker 1.7.0+):
```
sudo docker run -t -i -v /home/dnanexus:/data:Z ensemblorg/ensembl-vep
```

2. Change the read/write access of the mounted volume
```
chmod -R a+rwx /home/dnanexus
```

Tell me if this works for you.

Thanks,
Nuno

**Comment by zivlang** [comment]
Ok. Thanks.
I returned to the using directories as I did before and added the z option
as suggested:

$ sudo docker run -v $HOME/vep_data:/data:z ensemblorg/ensembl-vep
vep --cache --offline --format vcf --vcf --force_overwrite --
everything   --input_file input/1000123_23191_0_0.g.vcf
--output_file output/my_output.vcf
Smartmatch is experimental at
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm
line 472.

-------------------- EXCEPTION --------------------
MSG: ERROR: File "input/1000123_23191_0_0.g.vcf" does not exist

I then used the second command you suggested and run the first command
again:

$ sudo chmod -R a+rwx $HOME/vep_data

$ sudo docker run -v $HOME/vep_data:/data:z ensemblorg/ensembl-vep
vep --cache --offline --format vcf --vcf --force_overwrit
e --everything   --input_file input/1000123_23191_0_0.g.vcf
--output_file output/my_output.vcf
Smartmatch is experimental at
/opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm
line 472.

-------------------- EXCEPTION --------------------
MSG: ERROR: File "input/1000123_23191_0_0.g.vcf" does not exist


‫בתאריך יום ג׳, 15 באוג׳ 2023 ב-11:40 מאת ‪Nuno Agostinho‬‏ <‪
***@***.***‬‏>:‬

**Comment by nuno-agostinho** [comment]
Hi @zivlang,

Your data is not in `$HOME/vep_data`, it's in `/home/dnanexus`. As such, you have to point it to that folder when trying the proposed solutions:

- Try using option `:Z`: `sudo docker run -t -i -v /home/dnanexus:/data:Z ensemblorg/ensembl-vep`
- If that doesn't work, try changing the folder permissions: `chmod -R a+rwx /home/dnanexus`

Hope that makes it clear.

Thanks,
Nuno

**Comment by nuno-agostinho** [comment]
Hi @zivlang,

Hope the instructions here were clear and helped you fixing the issue.

I will now close this ticket, but feel free to reopen it in case you are still facing issues. Thanks!

Best regards,
Nuno

**Comment by ajtock** [comment]
Hi @zivlang

Just in case you're still having trouble, I encountered the same error message

> MSG: ERROR: File "input/sample.vcf" does not exist

when I was using symbolic links to the VCF input files - the problem was that I was mounting a directory containing symlinks to file paths that aren't resolvable from within the container. Replacing the symlinks with the actual files solved this for me.

Andy

**Comment by zivlang** [comment]
Thanks. I can't remember how the issue was resolved.

בתאריך יום ג׳, 21 בנוב׳ 2023, 19:01, מאת ajtock ***@***.***>:

**Comment by zyh4482** [comment]
This issue is about Docker usage not about VEP. I would like to make a comment if any new user start with ensembl-vep and Docker. 

People usually follow the instruction provided by vep team. Hence, the installation of cache is most likely to be somewhere like `/home/zyh/vep_data`. But in some case, their data may store in a different directory, like `/home/zyh/data`. In this case, if you still use the command from the vep website, you will get this caveat. 

To solve it, you need to volume or mount multiple folders into your container like below: 

```
docker_workdir="/home/zyh/data"
cache_dir="/home/zyh/vep_data"
other_folders_you_want_to_add_in="/..../..../...."

docker run -t -i \
-v ${docker_workdir}:/data \
-v ${other_folders_you_want_to_add_in}:/another_name_in_Docker \
-v ${cache_dir}:/cache ensemblorg/ensembl-vep \
vep --cache --offline --dir_cache /cache \
--input_file /data/example.vcf
[other arguments]
``` 
After that, you can use `sudo chown` to get permission back for your output files. 

Perhaps this will solve your question.
