### ISSUE TITLE
hgvsp incorrect ,  a case when it is necessary to use  shift_hgvs

### ISSUE THREAD

**Issue by ArsFc** [Ensembl/ensembl-vep#1475]
## Describe the issue
when i use vep annot a insertion ,  vep  result  is 'NP_005219.2:p.Val769_Asp770insValAlaSer' , but i think the 
 result 'NP_005219.2:p.Ala767_Val769dup' more reasonable 。。

### System
- VEP version: 109
- VEP Cache version: 109
- Perl version: v5.30.0
- OS: Ubuntu 20.04 lts
- tabix installed ?

### Full VEP command line
vep --offline  --cache --refseq --species homo_sapiens --assembly GRCh37  --dir_cache ~/ensembl-vep/cache/ --dir_plugins ~/cache/Plugins/ -id '7 55248998 . A ATGGCCAGCG'  --variant_class --symbol --canonical --hgvs --shift_hgvs 1 --shift_3prime 1 --shift_length   --biotype --allele_number --numbers  --check_existing --exclude_null_alleles --no_stats --fasta  ~/cache/homo_sapiens_merged/109_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz  --tab --output_file  b1_m.tsv  --force_overwrite 
```

**Comment by nakib103** [comment]
Hello @ArsFc,

Thanks for your query!

I tried with your command but cannot seem to reproduce the issue. I am getting `NP_005219.2:p.Ala767_Val769dup` in the output - 
```
7_55248999_-/TGGCCAGCG	7:55248998-55248999	CCAGCGTGG	1956	NM_005228.5	Transcript	inframe_insertion	2569-2570	2308-2309	770	D/ASVD	gac/gCCAGCGTGGac	-	1	MODERATE	-	1	-	insertionEGFR	EntrezGene	-	protein_coding	YES	-	-	-	-	-	20/28	-	NM_005228.5:c.2300_2308dup	NP_005219.2:p.Ala767_Val769dup	12	-	-	-	12
```

I am curious about the FASTA file you are using - can you provide me the link from where you downloaded?

Best regards,
Nakib

**Comment by ArsFc** [comment]
thanks a lot ， thr FFASTA file download for the link : 'https://ftp.ensembl.org/pub/grch37/release-109/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz' ,  its may be simultaneous use  'shift_hgvs' and 'shift_3prime'

**Comment by nakib103** [comment]
Sorry, instead of Ensembl VEP e109 version I was using the latest e110. That is why I was unable to re-produce the issue.

In the **latest version of VEP which is e110** this issue has been fixed  - 
https://github.com/Ensembl/ensembl-variation/pull/812

Can you try using that version and see if you still encounter the problem.

Best regards,
Nakib

**Comment by nakib103** [comment]
Hello @ArsFc,

I am closing this issue. If you face any further problems please feel free to open another one.

Best regards,
Nakib
