### ISSUE TITLE
Breakend variant annotation differs for web-vep and command line

### ISSUE THREAD

**Issue by janrehker** [Ensembl/ensembl-vep#1479]
Hi,

Using most recent version of vep (110.1) both on web interface and command line (installed via conda), I am getting different results.

While the web version will yield 'feature_truncation' annotations, the command line will only give me an 'intron_variant' for the same variant and the same transcript.

My command:
vep --offline --cache --dir_cache /mnt/NFS/pathonas01/pathodata/miniconda3_ballm/envs/vep110/.vep --use_given_ref --distance 5000 --force_overwrite --input_file test2.vcf --max_sv_size 280000000 --output_file test.vcf --hgvs --fasta /mnt/NFS/pathonas01/pathodata/miniconda3_ballm/envs/vep110/.vep/Homo_sapiens.GRCh38.dna_sm.toplevel.fa.gz

Is there any commandline parameter I am missing?

Best regards,
Jan Rehker

[test2.zip](https://github.com/Ensembl/ensembl-vep/files/12371417/test2.zip)

**Comment by nuno-agostinho** [comment]
Hi @janrehker,

Thanks for reporting this issue, I will take a look into your command as soon as possible.

In the meantime, please note that web VEP shows a `Command line equivalent` command in the `Job details`:

<img width="927" alt="Screenshot 2023-08-17 at 17 08 57" src="https://github.com/Ensembl/ensembl-vep/assets/3199157/7e525572-eaf5-4dd3-b188-4625b2fbc2c6">

You can use this to check if you are using the same parameters between web VEP and command-line interface.

Thanks,
Nuno

**Comment by janrehker** [comment]
Hi @nuno-agostinho,

Thanks for looking into this. The command line in the web version was: 
`vep --af --appris --biotype --buffer_size 500 --check_existing --distance 5000 --hgvs --mane --polyphen b --pubmed --refseq --regulatory --sift b --species homo_sapiens --symbol --transcript_version --tsl --cache --input_file [input_data] --output_file [output_file]`

I should have mentioned that I tested the equivalent in the command line version, without the expected result.

This behaviour affects bnd variants derived from Manta. So far, large deletions get annotated as truncating.


Best regards,
Jan

**Comment by nuno-agostinho** [comment]
Hi @janrehker,

This seems to be related with a bug when checking the chromosome from VCF input (specific to breakend code only). For now, please avoid using the prefix `chr` in your input data.

I will create a fix for this issue for future VEP releases. Sorry for this issue and thanks for reporting it.

Kind regards,
Nuno

**Comment by janrehker** [comment]
Parsing the vcf files for the time in between is no big deal. Just tried it with a Manta vcf file and it could be processed in the way you described with the expected outcome of 'feature_truncation&intron_variant' to be reported for the variants.


Thanks for this workaround!


Best regards,
Jan

**Comment by nuno-agostinho** [comment]
Hey @janrehker,

This issue has now been fixed. The fix will be available in the next Ensembl release.

Thanks for your report! :)

Best,
Nuno
