### ISSUE TITLE
Non-standard (?) cHGVS calculation

### ISSUE THREAD

**Issue by kkchau** [Ensembl/ensembl-vep#1485]
## Describe the issue
Calculating cHGVS for a minus-strand transcript yields a non-standard(?), although technically correct nomenclature. This appears in release 110; running on 109 yields the expected nomenclature.

## Additional information

Input (VCF):
```
##fileformat=VCFv4.2
##contig=<ID=11>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
11	64577375	.	G	GGGGGC	.	.	.
```

Output:
|VEP Version|cHGVS|
|-|-|
|v110|NM_130799.2:c.206_207insGCCCC|
|v109|NM_130799.2:c.202_206dup|

Mutalyzer maps NM_130799.2:c.206_207insGCCCC to NM_130799.2:c.202_206dup https://mutalyzer.nl/normalizer/NM_130799.2:c.206_207insGCCCC

The dup representation seems to be the generally accepted representation (MANE): https://www.ncbi.nlm.nih.gov/clinvar/variation/183079/

### System
- VEP version: 110
- VEP Cache version: 110
- Perl version: v5.30.0
- OS: Ubuntu 22.04
- tabix installed: Yes

### Full VEP command line
```
# Same command used with v110 and v109, with respective cache versions used
 ./vep --verbose --cache --offline --vcf --allele_number --symbol --hgvs --hgvsg --variant_class --numbers --af_gnomad --no_escape --merged --use_given_ref -a GRCh37 --fasta /opt/vep/.vep/homo_sapiens_merged/109_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa --dir /opt/vep/.vep --format vcf -i input.vcf -o vep.vcf
```

### Full error message
N/A

**Comment by nakib103** [comment]
Hello @kkchau ,

Thanks for your query!

I can re-produce the issue. I am looking into it more and once I have more information I will update you.

Best regards,
Nakib

**Comment by senanu** [comment]
I can confirm that this is a problem. For another example:

Input (minimal.vcf)
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
14	21391016	c.7112dup	A	AT	.	.	.
```

Command line (with varying docker installations to match v110 or v109.3, accordingly):
```
vep --input_file minimal.vcf --database --species homo_sapiens --output_file STDOUT -v --format vcf --variant_class --hgvs --shift_hgvs 1 --canonical --mane_select --mane --db_version 110 --symbol --pick
```

Output (v109) -- this is **correct**
```HGVSc=ENST00000646647.2:c.7112dup```

Output (v110): -- this is **non-standard**
```HGVSc=ENST00000646647.2:c.7112_7113insA```

### More info from REST API

The sequence in question here is 

```
      ATT
2139106 8
```

followed by additional `T`'s, with the insertion/duplication being between the `A` and `T`. Looking this up by HGVS using the REST API produces different VCF strings (both valid, but shifted):

```
https://rest.ensembl.org/vep/human/hgvs/ENST00000646647.2:c.7112_7113insA?content-type=application/json;vcf_string=1;hgvs=1
```
produces 
```
"vcf_string": "14-21391016-A-AT"
```
whereas
```
https://rest.ensembl.org/vep/human/hgvs/ENST00000646647.2:c.7112dup?content-type=application/json;vcf_string=1;hgvs=1
```
produces
```
"vcf_string": "14-21391017-T-TT"
```

Lastly, `shift_3prime=1` doesn't seem to make any difference with this.

**Comment by nakib103** [comment]
Hello @kkchau @senanu,

The fix for this issue will be available in next release (e112). I am closing this issue but if you face any further issue please feel free to open another one.

Best regards,
Nakib
