### ISSUE TITLE
Incorrect HGVSp nomenclature

### ISSUE THREAD

**Issue by suzyhh** [Ensembl/ensembl-vep#1488]
## Describe the issue
Incorrect HGVSp description for a frameshift duplication:
- VCF description: 2 1477447 . A ACGGC
- HGVSc: NM_001206744.2:c.1184_1187dup 

VEP is giving me an HGVSp of `NP_001193673.1:p.Ala397GlyfsTer76` which is incorrect, the HGVSp should be `NP_001193673.1:p.Ala397ProfsTer76`. I have confirmed this in ClinVar/VariantValidator. I'm guessing it's an issue with the shifting of the variant, however I'm struggling to work out where exactly VEP has put the duplication in order to get a Gly at position 397.

### System
- VEP version: 109
- VEP Cache version: 109
- Using VEP docker image

### Full VEP command line
```
docker run --network host -t -i -v "$PWD":/opt/vep/.vep swg/ensembl-vep:2.0 vep --cache --offline \
    -id '2 1477447 . A ACGGC' \
    --dir_cache /opt/vep/.vep \
    --tab --merged --fasta $refFasta \
    --assembly GRCh38 \
    --no_stats \
    --no_escape \
    -check_existing --hgvs --hgvsg --af --af_gnomadg --protein --uniprot --symbol --numbers \
    --pubmed --show_ref_allele --variant_class --mane_select --transcript_version \
    -o /opt/vep/.vep/sample1.tsv \
    --force_overwrite
```

I've run the variant through the web interface and this gives the correct HGVSp, so I'm assuming it's an issue with v109. It would be good to know exactly what has caused it though as I need to go back and look at all the other variants we have that might also be impacted.

Thanks!

**Comment by dglemos** [comment]
Hi @suzyhh,
In release 110 a few fixes and improvements were made to VEP when annotating duplications. 
I recommend you review the annotation for all duplication variants.
Let me know if you find more of these cases.

Best wishes,
Diana

**Comment by suzyhh** [comment]
Hiya, thanks for the information - does this problem extend to insertions and deletions as well? Should we also be reviewing these?

**Comment by dglemos** [comment]
You should also include the deletions and insertions in your review. The fixes impacted HGVSp directly but they also can impact some of the HGVSc and HGVSg so reviewing those is a good idea too.

**Comment by suzyhh** [comment]
Hi @dglemos,

I'm not sure if this is a related problem or not as it is another issue with duplications and HGVS nomenclature although slightly different to the previous variant - let me know if you would like me to open a new issue.

While testing VEP v110.1 (using the docker image) I noticed another issue with a 1bp duplication. Here is my command:

```
docker run --network host -t -i -v /mnt/data1/working_directory/suzy/alamut_replacement/vep/vep_data:/opt/vep/.vep ensemblorg/ensembl-vep:release_110.1 vep --cache --offline \
    -id '2 169140514 . T TG' \
    --dir_cache /opt/vep/.vep \
    --tab \
    --merged \
    --fasta /opt/vep/.vep/homo_sapiens_merged/110_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz \
    --assembly GRCh38 \
    --hgvs --hgvsg \
    -o /opt/vep/.vep/rs80338754.vep.tsv \
    --force_overwrite 
```

The correct HGVSc nomenclature for this variant is `NM_004525.3:c.13139dup`, however VEP is returning an HGVSc of `NM_004525.3:c.13139_13140insC`. This variant is in LRP2, which is a gene on the reverse strand and the variant is a G duplication within a string of 8 Gs. The HGVSg is given correctly as `2:g.169140522dup`

Web VEP also gives the incorrect nomenclature.

Many thanks for your help.

**Comment by nakib103** [comment]
Hi @suzyhh,

This seems to like the same issue reported in - https://github.com/Ensembl/ensembl-vep/issues/1485.
We are looking into it and hopefully will have a fix.

Best regards,
Nakib

**Comment by suzyhh** [comment]
Hiya @nakib103 

Thanks for looking into this - do you think this fix will be a minor release relatively soon? or will it be part of the next version of VEP? We're trying to decide whether to temporarily revert back to v109.

Thanks!

**Comment by nakib103** [comment]
Hi @suzyhh, The fix is supposed to be part of next versions of VEP.

Best regards,
Nakib

**Comment by suzyhh** [comment]
Hi @nakib103, I just updated to v111 of VEP and unfortunately the issue with duplications being described as insertions in the HGVSc remains. I have confirmed this on the command line with the new docker image and cache and on web VEP, e.g.

VCF description: `2 169140514 T TG`
HGVSg (correct): `2:g.169140522dup`
HGVSc (v111): `NM_004525.3:c.13139_13140insC`

and on the web:
![image](https://github.com/Ensembl/ensembl-vep/assets/36733421/22b5f4fd-656e-4ba1-97f5-fd378695db18)

This is the same, incorrect HGVSc that v110 gives me for this variant.

**Comment by nakib103** [comment]
Hello @suzyhh,

Unfortunately this issue has not been resolved in e111. 

Our HGVS code is quite complex and there are several others issues we are solving at the moment and assessing the impact one solution to other. 
There is a pull request though that addresses this issue - https://github.com/Ensembl/ensembl-variation/pull/1042. You can pull this pull request for now to temporarily solve the issue you are having.

Best regards,
Nakib

**Comment by suzyhh** [comment]
Great, thank you for the quick response!

**Comment by nakib103** [comment]
Hello @suzyhh,

The pull request has been merge and the fix will be available in next release (e112). I am closing this issue but if you face any further issue please feel free to open another one.

Best regards,
Nakib
