### ISSUE TITLE
A confuse about dividing lines by ALT field

### ISSUE THREAD

**Issue by boyanboyue** [Ensembl/ensembl-vep#1489]
HI,I have a problem.
There are more than one allele gene in ALT field but I want to divide every one allele into one line,which options can I use?

For example:
Now the result looks like this:
chr3	113376110	rs10606566	TTGCTGCTGC	TTGCTGC,T	22665.86	.	AC=5,1;AF=0.833,0.167;AN=6;DB;DP=715;ExcessHet=3.0103;FS=0.000;MLEAC=5,1;MLEAF=0.833,0.167;MQ=60.00;QD=42.13;SOR=0.976;CSQ=TGCTGC|inframe_deletion|MODERATE|KIAA2018|ENSG00000176542|Transcript|ENST00000316407|protein_coding|7/7||ENST00000316407.4:c.4416_4418del|ENSP00000320794.4:p.Gln1478del|4821-4829|

but I want to get the result like below:
chr3	113376110	rs10606566	TTGCTGCTGC	TTGCTGC	22665.86	.	AC=5,1;AF=0.833,0.167;AN=6;DB;DP=715;ExcessHet=3.0103;FS=0.000;MLEAC=5,1;MLEAF=0.833,0.167;MQ=60.00;QD=42.13;SOR=0.976;CSQ=TGCTGC|inframe_deletion|MODERATE|KIAA2018|ENSG00000176542|Transcript|ENST00000316407|protein_coding|7/7||ENST00000316407.4:c.4416_4418del|ENSP00000320794.4:p.Gln1478del|4821-4829|
chr3	113376110	rs10606566	TTGCTGCTGC	T	22665.86	.	AC=5,1;AF=0.833,0.167;AN=6;DB;DP=715;ExcessHet=3.0103;FS=0.000;MLEAC=5,1;MLEAF=0.833,0.167;MQ=60.00;QD=42.13;SOR=0.976;CSQ=TGCTGC|inframe_deletion|MODERATE|KIAA2018|ENSG00000176542|Transcript|ENST00000316407|protein_coding|7/7||ENST00000316407.4:c.4416_4418del|ENSP00000320794.4:p.Gln1478del|4821-4829|

**Comment by dglemos** [comment]
Hi @boyanboyue,
VEP does not support splitting the alleles but you could do that before running the VEP annotation.

You could split the alt alleles with `bcftools norm [OPTIONS] file.vcf.gz`:
```
-m, --multiallelics -|+[snps|indels|both|any]
  split multiallelic sites into biallelic records (-) or join biallelic sites into multiallelic records (+). An optional type string can  follow which controls variant types which should be split or merged together: If only SNP records should be split or merged, specify snps; if both SNPs and indels should be merged separately into two records, specify both; if SNPs and indels should be merged into a single record, specify any.
```

**Comment by boyanboyue** [comment]
I have done it with your suggested command,thank you so much!

**Comment by dglemos** [comment]
I'm glad it works!
I'm going to close this issue.

Best wishes,
Diana
