### ISSUE TITLE
Install location of new Perl modules

### ISSUE THREAD

**Issue by kjohnsen** [Ensembl/ensembl-vep#149]
When I run the install script, it seems to install `htslib` and `Bio` modules right in the ensembl-vep folder, which naturally isn't already in my `@INC` path. So, later on in the `INSTALL.pl` script, I fail a lot of tests with errors like these:
```
Error:  Can't locate Bio/EnsEMBL/Registry.pm in @INC (you may need to install the Bio::EnsEMBL::Registry module) (@INC contains...)
```
I don't understand why the INSTALL script doesn't install the Perl modules where it can access them.

**Comment by ima23** [comment]
Hi @kjohnsen, could you let me know what installation command and what code version you used? Thanks.

**Comment by kjohnsen** [comment]
@ima23 I get this from the vep script:
```
Versions:
  ensembl              : 91.18ee742
  ensembl-funcgen      : 91.4681d69
  ensembl-io           : 91.923d668
  ensembl-variation    : 91.c78d8b4
  ensembl-vep          : 91.3
```
I cloned the repository just last week. To install, all I did was `./INSTALL.pl`

**Comment by ima23** [comment]
@kjohnsen Thanks for the code versions, they are the correct ones. I'm looking into replicating the behavior.
The INSTALL.pl script installs the API code in the current directory as a default setting and also runs a VEP installation test set. Did the installation step tests run ok or were there any errors?

**Comment by genomics-geek** [comment]
I have the same behavior

**Comment by kjohnsen** [comment]
They seem to have run okay. I don't remember from when I originally installed it, but after moving the modules I needed to my Perl library folder, vep seemed to work. Now when I run the install script about every other test fails with the message `Possible precedence issue with control flow operator...`. One popular place for these errors is Bio/DB/IndexedBase.pm at line 845.

**Comment by ima23** [comment]
Hi @kjohnsen, if the tests run finished with `All tests successful.` then all is fine. The message about Bio/DB/IndexedBase.pm is a known warning only message, see https://github.com/Ensembl/ensembl-vep/issues/75.

**Comment by kjohnsen** [comment]
@ima23 The tests do not all pass. It says 
```
./t/Runner.t ..
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=40...
Result: FAIL
Failed 1/40 test programs. 0/1641 subprograms failed
```

**Comment by ima23** [comment]
Hi @kjohnsen, this parse error usually appears when there are different versions of the code installed than the ones required by the calling test. May I recommend a clean install and running only the commands below:
git clone https://github.com/Ensembl/ensembl-vep.git
cd ensembl-vep perl INSTALL.pl` in the

**Comment by ima23** [comment]
Hi @kjohnsen, this parse error usually appears when there are different versions of the code installed than the ones required by the calling test. May I recommend a clean install and running only the commands below. Could you letting me know if there are any test failing after these commands, thanks.
`git clone https://github.com/Ensembl/ensembl-vep.git`
`cd ensembl-vep `
 `perl INSTALL.pl.`

**Comment by ima23** [comment]
Please feel free to reopen if the issue persists.

**Comment by kjohnsen** [comment]
I'm sorry I've been so slow with this...so I tried deleting, recloning, and installing again, and I run into the same problem. 

This is a typical error:
```
# BEGIN failed--compilation aborted at ./t/AnnotationSource_Cache_RegFeat.t line 35.
Can't locate object method "new" via package "Bio::EnsEMBL::VEP::Config" at ./t/AnnotationSource_Cache_RegFeat.t line 37.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 2.
./t/AnnotationSource_Cache_RegFeat.t ................. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 2/2 subtests
./t/Parser_VCF.t ..................................... 1/?
#   Failed test 'use Bio::EnsEMBL::VEP::Parser::VCF;'
#   at ./t/Parser_VCF.t line 33.
#     Tried to use 'Bio::EnsEMBL::VEP::Parser::VCF'.
#     Error:  Can't locate Bio/EnsEMBL/Registry.pm in @INC (you may need to install the Bio::EnsEMBL::Registry module) (@INC contains: /home/<username>/ensembl-vep/t /home/<username>/ensembl-vep/modules /home/<username>/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/<username>/perl5/lib/perl5 ./Bio /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/<username>/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 58.
```

You would understand better what's going on than I do, but it seems the script is installing the perl libraries in the wrong place. This error, for example, says it can't find `Bio/EnsEMBL/Registry.pm`, but the script actually does install the module. I find it under `~/ensembl-vep/Bio/EnsEMBL/Registry.pm`. So the script installed it (along with many other `Bio`, `biodbhts`, and `htslib` modules) directly in the `ensembl-vep` folder, which isn't in `@INC`, rather than someplace like `ensembl-vep/modules`, which _is_ included in `@INC`.

**Comment by ima23** [comment]
Thanks for the log @kjohnsen! 
It's been very useful in ruling out a few cases and finding out that my colleague @aparton has come across something like this before. The previous case was due to an old version of `Module::Build` library. 
Could you please check and update the installed library? If you are using `cpan` or `cpanm` to manage your perl libraries, then `cpanm Module::Build` should do the trick.

**Comment by kjohnsen** [comment]
Sorry again for the delay...

I ran `cpan module::Build` and got the following result:
`Module::Build is up to date (0.4224).`

I then recloned the repository and reinstalled, with the same result as before ("Failed 38/40 test programs").

**Comment by aparton** [comment]
Hi,

Something seems to have gone wrong with the version of BioPerl that the VEP installer has downloaded, manually installing BioPerl and pointing VEP towards it should fix the issue. Could you please:

1) Download BioPerl at https://cpan.metacpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.6.924.tar.gz and unzip with tar zxvf BioPerl-1.6.924.tar.gz
2) Add the path to your manually downloaded BioPerl to your PERL5LIB variable
3) Delete the ensembl-vep directory
4) Reclone VEP with ‘git clone https://github.com/ensembl/ensembl-vep <https://github.com/ensembl/ensembl-vep> (or however you accessed VEP the first time)
5) Rerun the installer

This should resolve your issue - we are aware of an issue with the VEP installer where BioPerl has installation issues on particular systems and a fix will be available in a future release, but in the short-term this should solve your issue.

Any other issues or questions, please let me know.

Kind Regards,
Andrew

**Comment by jzluo** [comment]
Hi, 
I think the installer still isn't fixed. 
[vep_install.log](https://github.com/Ensembl/ensembl-vep/files/2989667/vep_install.log)

```
<username>@x24382:~/ensembl-vep$ cpanm Module::Build
Module::Build is up to date. (0.4224)
<username>@x24382:~/ensembl-vep$ perl --version

This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux-gnu-thread-multi
(with 85 registered patches, see perl -V for more detail)
```
This workaround fixes it for me since ``Bio`` was installed directly in ``ensembl-vep``, which isn't in ``@INC``:
```
<username>@x24382:~/ensembl-vep$ git diff INSTALL.pl
diff --git a/INSTALL.pl b/INSTALL.pl
index 4a3005d..337bff4 100755
--- a/INSTALL.pl
+++ b/INSTALL.pl
@@ -38,6 +38,7 @@ INSTALL.pl - a script to install required code and data for VEP
 use strict;
 use FindBin qw($RealBin);
 use lib $RealBin.'/modules';
+use lib $RealBin;
 use Getopt::Long;
 use File::Path qw(mkpath rmtree);
 use File::Copy;
```

**Comment by aparton** [comment]
Hi @jzluo,

Thank you for your feedback. We're making some changes to our VEP installer in the coming months, that will include a fix for this issue.

In the meantime, workarounds include your fix, or adding the ensembl-vep directory to your PERL5LIB.

Kind Regards,
Andrew

**Comment by NLSVTN** [comment]
I installed Bioperl, set PERL5LIB and it did not help. I am still struggling with just basic 'perl INSTALL.pl' script. Asked it on biostars:

https://www.biostars.org/p/422309/

**Comment by NLSVTN** [comment]
The solution to the issue that I was facing was the following:

1. Run `cpanm Module::Build`
2. Set `PERL5LIB=/opt/gris/perl5/lib/perl5/`
3. Run as a root: `yum install enablerepo=rpmforge perl-Try-Tiny`
4. Run `cpanm autodie`

**Comment by aparton** [comment]
Hi @NLSVTN,

Thank you for this report. I'm glad you were able to resolve your issue.

If you have any other questions, please don't hesitate to open a new ticket.

Kind Regards,
Andrew

**Comment by dvg-p4** [comment]
This still appears to be an issue:
```
Can't locate Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm in @INC (you may need to install the Bio::EnsEMBL::Variation::DBSQL::VariationFeatureAdaptor module)
```

**Comment by GiovannaPrezia** [comment]
Still having the same problem

**Comment by dvg-p4** [comment]
...why was this issue just closed, is this fixed in dev?

**Comment by dvg-p4** [comment]
Oh never mind github just changed their UI. This was (incorrectly?) closed in 2018.
