### ISSUE TITLE
BND sv types transcript consequences keys suggestion

### ISSUE THREAD

**Issue by themkdemiiir** [Ensembl/ensembl-vep#1492]
## Describe the issue
I received the JSON file, but I cannot determine which BND end corresponds to each transcript consequence in BND types.

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

I used docker tag ensemblorg/ensembl-vep:release_110.1

### System
- VEP version: 110
- VEP Cache version: 110
- Perl version: I used docket
- OS: Ubuntu
- tabix installed?

### Full VEP command line
vep --cache --dir /data --merged --fasta /data/Homo_sapiens.GRCh38.dna.primary_assembly.fa -i /sv_vcfs/wes_hg38.vcf -o /sv_vcfs/vep_110_tiddit.json --use_given_ref --json --canonical --offline --max_sv_size 200000000 --symbol --overlap --force_overwrite --numbers --offline

### Full error message
> Including the warnings, if available

### Data files (if applicable)
They include:
- The input file vcf
- The output file JSON
- The custom file(s) no custom files
You can provide a sample of them

I received the JSON file, but I cannot determine which chromosome corresponds to each consequence in BND types. 
```
{
  "strand": 1,
  "id": "SV_5_1",
  "start": 7936272,
  "input": "1\t7936271\tSV_5_1\tN\tN[12:58877476[\t80\tUnexpectedCoverage\tSVTYPE=BND;REGIONA=7936125,7936271;REGIONB=58877476,58877627;LFA=3,0;LFB=3,0;LTE=3,0;CTG=.\tGT:CN:COV:DV:RV:LQ:RR:DR\t1/1:.:3,0,248:3:0:0.0,0.0:2,194:0,138",
  "allele_string": "N[12:58877476[",
  "end": 7936272,
  "assembly_name": "GRCh38",
  "transcript_consequences": [
    {
      "hgnc_id": "HGNC:30991",
      "gene_symbol": "LRIG3",
      "impact": "HIGH",
      "consequence_terms": [
        "feature_truncation"
      ],
      "source": "Ensembl",
      "transcript_id": "ENST00000320743",
      "variant_allele": "N[12:58877476[",
      "strand": -1,
      "gene_symbol_source": "HGNC",
      "gene_id": "ENSG00000139263",
      "canonical": 1
    }],
   "most_severe_consequence": "feature_truncation",
   "seq_region_name": "1",
```

Each transcript consequence should be annotated with the chromosome location of the affected region, or specify which BND end is involved in the consequence.

**Comment by nuno-agostinho** [comment]
Hi @themkdemiiir, thanks for your suggestion!

Our team has previously discussed adding which breakends are involved in each consequence (particularly in the case of breakpoints with multiple mates, such as `N[12:58877476[,N[8:1434846[`). We will look into this again.

Best regards,
Nuno

**Comment by themkdemiiir** [comment]
Thanks for the reply!

Could you please let me know when the update is expected to be released?

Best regards,
Kaan

**Comment by nuno-agostinho** [comment]
Hey @themkdemiiir,

I already opened two PRs to make the output easily display the consequences involved in each breakend. We are still testing if everything is fine with the changes, which means they will be probably be available in release 112 (estimated to be released early next year).

Thanks for opening this issue and for your understanding.

Please tell me if you encounter any further issue.

Thanks,
Nuno

**Comment by nuno-agostinho** [comment]
Hey @themkdemiiir, just to let you know that the code has been merged and will be available in release 112 (to be released early next year).

Thanks for your suggestion!

I will now close this issue, but feel free to open a new one if you face any problems with VEP.

Cheers,
Nuno
