### ISSUE TITLE
Running INSTALL.pl stuck while downloading homo_sapiens_vep_110_GRCh38.tar.gz

### ISSUE THREAD

**Issue by sylee20** [Ensembl/ensembl-vep#1494]
## Describe the issue
I am running INSTALL.pl and I think it is stuck somewhere. 
I tried to install Ensembl VEP using the following code:
```
git clone https://github.com/Ensembl/ensembl-vep.git
cd ensembl-vep
perl INSTALL.pl -a cfp -s homo_sapiens -y GRCh38 -g all
```
I got the following results but there has been no progress for more than a day: 
```
 - getting list of available cache files
 - downloading https://ftp.ensembl.org/pub/release-110/variation/indexed_vep_cache/homo_sapiens_vep_110_GRCh38.tar.gz
```
When I type https://ftp.ensembl.org/pub/release-110/variation/indexed_vep_cache/homo_sapiens_vep_110_GRCh38.tar.gz
in the browser I get 404 not found error. 

I have checked that I have gcc, g++, make, and Perl packages (Archive::Zip, DBD::mysql, DBI) installed.

### System
- Perl version: v5.26.1
- OS: Ubuntu
- tabix installed ? Yes.

**Comment by nuno-agostinho** [comment]
Hi @sylee20, thanks for creating this issue!

It's weird it's giving 404, the URL is correct and is downloading the file for me. Could you check if you can access https://ftp.ensembl.org/pub/ at all? If not, this may be related with network/firewall permissions.

Thanks,
Nuno

**Comment by nuno-agostinho** [comment]
Hi @sylee20, do you have any updates on this issue?

**Comment by nuno-agostinho** [comment]
Hi @sylee20,

Given that I didn't hear from you yet and everything seems to be running as expected on our side, I will now close this ticket.

Feel free to re-open it in case you want to discuss it further. Thanks!

Best regards,
Nuno
