### ISSUE TITLE
"--check_existing" outputs empty vcf file

### ISSUE THREAD

**Issue by nyoonhee** [Ensembl/ensembl-vep#1495]
## Describe the issue
I am running VEP from docker. The vcf file gets annotated when --check_existing option is not used. However it outputs empty vcf file (only the header with no variants) when --check_existing option is used. The output message is the same with or without the --check_existing option.

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: ensemblorg/ensembl-vep:release_109.3
- Perl version: v5.16.3
- OS: Amazon linux 2
- tabix installed  : yes

### Full VEP command line
```
      docker run -v /home/ec2-user/ref/vep109_for_docker:/data \
                -v ${out_dir}:/vcf_path \
                -v /home/ec2-user/ref:/fasta_path \
                ensemblorg/ensembl-vep:release_109.3 \
                vep --cache --offline --format vcf --vcf --force_overwrite \
                --assembly GRCh38 \
                --check_existing \
                --symbol --terms SO --tsl --hgvs --fasta /fasta_path/hg38.fa \
                --input_file /vcf_path/test.vcf \
                --output_file /vcf_path/test.vep.vcf \
                
```

### Full error message

Unknown option: pluginsdir
Ignoring unsupported option 'pluginsdir' found via ENV variable or INI file
Unknown option: no_update
Ignoring unsupported option 'no_update' found via ENV variable or INI file
Unknown option: no_htslib
Ignoring unsupported option 'no_htslib' found via ENV variable or INI file
Unknown option: no_plugins
Ignoring unsupported option 'no_plugins' found via ENV variable or INI file

**Comment by olaaustine** [comment]
Hi @nyoonhee,
Thank you very much for your query.
Please you can ignore the warnings, this has been fixed in our release version 110. 
Please can you give an example of some of the variants in your input VCF file if possible so we can recreate this issue. 
Thank you very much 
Ola

**Comment by olaaustine** [comment]
Hi @nyoonhee, 
Hope this meets you well? 
I am going to close this ticket now. 
Please feel free to open another ticket if you have another issue. 
Thank you, 
Ola.
