### ISSUE TITLE
How to retain some input fields in the output file?

### ISSUE THREAD

**Issue by sruthisrini** [Ensembl/ensembl-vep#1499]
## Describe the issue
I would like to generate spliceAI predictions using VEP plugin and that's working fine. However, I would like to retain few columns from my input file so that in future, I could able to compare them.

### System
- VEP version: v109.3
- API version 109, DB version 109
- MacOS

### Full VEP command line
```
/vep -i input.vcf -o output.vcf --cache --pick_allele --force_overwrite --tab --no_check_variants_order --force --plugin SpliceAI,snv=/Downloads/spliceai_scores.raw.snv.hg38.vcf.gz,indel=/Downloads/spliceai_scores.raw.indel.hg38.vcf.gz,cutoff=0.5 --sift b --polyphen p

```

I added --list to the above command
```
/vep -i input.vcf -o output.vcf --cache --pick_allele --force_overwrite --tab --list --no_check_variants_order --force --plugin SpliceAI,snv=/Downloads/spliceai_scores.raw.snv.hg38.vcf.gz,indel=/Downloads/spliceai_scores.raw.indel.hg38.vcf.gz,cutoff=0.5 --sift b --polyphen p

```
### Full error message
Unknown option: list
ERROR: Failed to parse command-line flags

### Input file
```
Chr	Start	End	Ref	Alt	ExonicFunc.refGene_x	Genes	CADD_phred	SIFT_score	phastCons20way_mammalian	Polyphen2_HDIV_score	gnomAD_exome_ALL	LOEUF	LOEUF score	pLI	pLI score	ExonicFunc.refGene_y	ScoreCategory
chr1	100140182	100140182	G	C	nonsynonymous SNV	TRMT13	20.2	0.026	1.000	0.1	0.0	LOEUF:	0.93	pLI:	0.0	Synonymous	>0.35
chr1	100140450	100140450	C	T	nonsynonymous SNV	TRMT13	12.72	0.202	0.969	0.108	4.064e-06	LOEUF:	0.93	pLI:	0.0	Synonymous	>0.35

```
This is how my input file looks like and I would like to retain the column "ScoreCategory" in the output file for all the rows. Could you help to solve this?

Thanks in advance.

**Comment by olaaustine** [comment]
Hi @sruthisrini, 
Thank you for your query. 
I presume the option you wanted to use was [--fields ](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_fields:~:text=used%20by%20default-,%2D%2Dfields%20%5Blist%5D,-Configure%20the%20output)
If you want to keep your information from your input.vcf, I suggest you use the option [--vcf ](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_fields:~:text=Incompatible%20with-,%2D%2Dvcf,-Writes%20output%20in) to retain the information in your input vcf 
Please let us know if you have any other query. 
Thank you 
Ola.
