### ISSUE TITLE
Unable to parse HGVS notation

### ISSUE THREAD

**Issue by sandertan** [Ensembl/ensembl-vep#15]
Hi,

Congratulations on the new VEP project on GitHub. I'm having some trouble running it though. I'd like to run a file in HGVS notation as input, but the parser is giving me an error:

```
$ perl /usr/local/ensembl-vep/vep.pl -i test_HGVS-annotation.txt

WARNING: Unable to parse HGVS notation 'AGT:c.803T>C'
Can't call method "dnadb" on an undefined value at /usr/local/ensembl-vep/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm line 1790, <__ANONIO__> line 2.
```

This input file contains the example from the online VEP tool:
```
AGT:c.803T>C
9:g.22125504G>C
ENST00000003084:c.1431_1433delTTC
19:g.110747_110748insT
LRG_101t1:c.1019T>C
```

Before the run, I installed VEP by following the instructions on VEP project page. My perl version is 5.18.2, OS is Ubuntu 14.04 and I installed the DBI package with:
```
sudo cpan
install DBI
```

I tested the installation with an example input by running it both online (get an error) and offline (runs good):
```
perl /usr/local/ensembl-vep/vep.pl -i /usr/local/ensembl-vep/examples/homo_sapiens_GRCh37.vcf -o ~/test2

WARNING: Chromosome 21 not found in annotation sources or synonyms on line 1

WARNING: Chromosome 21 not found in annotation sources or synonyms on line 2

WARNING: Chromosome 21 not found in annotation sources or synonyms on line 3
```
This error goes on until `WARNING: Chromosome 22 not found in annotation sources or synonyms on line 173`

When I run it offline, it seems to run successfully (I installed hg19 in the cache):
```
perl /usr/local/ensembl-vep/vep.pl -i /usr/local/ensembl-vep/examples/homo_sapiens_GRCh37.vcf -o ~/test4 --offline -dir /usr/local/vep-cache
```

**Comment by willmclaren** [comment]
You must specify either `--database` (to use the database only), `--cache` (to primarily use the cache but allow database connections) or `--offline` (use the cache only, forbid database connections). VEP should warn you of this before it attempts to parse the HGVS input, so I'm surprised you got the error you saw.

So your first command should be:

`perl /usr/local/ensembl-vep/vep.pl -i test_HGVS-annotation.txt --database`

OR

`perl /usr/local/ensembl-vep/vep.pl -i test_HGVS-annotation.txt --cache`

And your second example should be:

`perl /usr/local/ensembl-vep/vep.pl -i /usr/local/ensembl-vep/examples/homo_sapiens_GRCh37.vcf -o ~/test2 --cache`

NB `--offline` will not work with HGVS input.

**Comment by sandertan** [comment]
Wow I'm sorry I missed the --database argument. Thank's for the fast response, it's working smoothly now.
