### ISSUE TITLE
VEP v91: ERROR: Forked process(es) died

### ISSUE THREAD

**Issue by NandiniBN** [Ensembl/ensembl-vep#150]
Hello,
I'm running VEP on a single sample vcf with approx 5000 variants generated using GATK v3.7 with the following command
`./vep --cache --dir_cache /Software/ensembl-vep/.vep  --stats_text S3.html --refseq --everything --individual all --transcript_filter "stable_id match N[M]_" --fork 4 -tab --custom /Software/ensembl-vep/.vep/score.bed.gz,score,bed,exact,0 --custom Software/ensembl-vep/.vep/HEX.bed.gz,HEX,bed,exact,0  --port 3337 -i S3.recode.vcf -o S3.txt`

and run into the following error

```
-------------------- EXCEPTION --------------------
MSG: 
ERROR: Forked process(es) died: read-through of cross-process communication detected

STACK Bio::EnsEMBL::VEP::Runner::_forked_buffer_to_output /Software/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:554
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /Software/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:361
STACK Bio::EnsEMBL::VEP::Runner::run /Software/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:202
STACK toplevel ./vep:222
Date (localtime)    = Wed Mar  7 10:27:19 2018
Ensembl API version = 91

```
Any idea what might be going wrong ?

Thanks

**Comment by at7** [comment]
I cannot see anything obviously wrong. Can you run the analysis successfully without using fork mode and have you been able run similar pipelines in fork mode before?

**Comment by NandiniBN** [comment]
I tried running it without the fork, the job is killed. I've tried this command only on 3 samples (all variants generated with the same script), 2 of which have been successful. 
```
2018-03-07 11:14:36 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this
2018-03-07 11:14:36 - INFO: Database will be accessed when using --hgvs
2018-03-07 11:14:36 - INFO: Database will be accessed when using --hgvsc
2018-03-07 11:14:36 - INFO: Database will be accessed when using --hgvsp
2018-03-07 11:14:36 - INFO: Database will be accessed when using --use_transcript_ref
Killed
```

**Comment by at7** [comment]
Could you please clarify for me if you can run the analysis successfully without using forks? I suspect that the problem is caused by some of the input data.

**Comment by NandiniBN** [comment]
The analysis for this particular input file was not successful either ways. What should I be looking in the input data that could be causing this problem ?

**Comment by at7** [comment]
Can you see any error messages? Does the run stop with 'Killed'? Can you see a S3.txt_warnings.txt file? 
It would also be helpful to know your ensembl-vep version. Thank you.

**Comment by at7** [comment]
Sorry. I just noted that your are using version 91.

**Comment by NandiniBN** [comment]
There are no error messages produced. It stops with 'killed'. The vep version as you can see from the first error post is 91. No output files are generated including  "S3.txt_warnings.txt"

**Comment by NandiniBN** [comment]
Thank you. Yes, that's correct. I'm using homo_sapiens_refseq_vep_91_GRCh37 as my cache file

**Comment by willmclaren** [comment]
In the past I've seen `Killed` messages when memory is exhausted.

It may be worth trying a smaller default buffer size value e.g. `--buffer_size 50`

**Comment by willmclaren** [comment]
It may also be worth trying using a FASTA file for sequence lookup, see http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#fasta

**Comment by NandiniBN** [comment]
Dear Both,
Thank you so much for your help. Using `--buffer_size 50` has worked for me. 
Regarding the FASTA file for sequence lookup, can we use our own reference or does it need to be downloaded from VEP ?

Thanks

**Comment by at7** [comment]
I'm glad it is working now. You can use your own FASTA file.

**Comment by willmclaren** [comment]
You can use your own as long as it matches the assembly version of the transcript set (VEP cache) and your input variants.

In some cases you may find that chromosome names in your FASTA don't match up to either your input or the cache; the cache contains a synonyms file that is automatically loaded and should take care of this in most instances, but you may also manually specify a synonyms file with `[--synonyms](http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_synonyms)`

**Comment by NandiniBN** [comment]
Okay. I'll try and work this out. Thanks, guys!
