### ISSUE TITLE
gnomADg population not found when filtering common variants

### ISSUE THREAD

**Issue by GACGAMA** [Ensembl/ensembl-vep#1504]
## Describe the issue
Hello everyone
I'm trying to annotate a vcf file on HG38 with many  annotations
I'm using

`singularity exec -H /scratch4/references/vep_cache_singularity /scratch4/singularities/vep.sif vep --cache -i vcf --species homo_sapiens --assembly GRCh38  --buffer_size 10000 --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --format vcf --input_file /scratch4/test_small_vcf/511912-0424960726.Consensus.sSNV.vcf.pass.vcf.gz  --vcf --output_file /scratch4/test_small_vcf/511912-0424960726.Consensus.sSNV.vcf.pass.VEP.vcf.gz --force_overwrite --pubmed --fork 1 --regulatory --gene_phenotype --polyphen b --af --max_af --af_1kg --af_gnomade --af_gnomadg  --filter_common --check_frequency --freq_pop gnomADg --plugin CADD,"\$CADD" --plugin dbNSFP,"\$dbNSFP",SIFT_pred,SIFT4G_pred,Polyphen2_HDIV_pred,MetaRNN_score,MetaRNN_pred,REVEL_score,BayesDel_noAF_score,BayesDel_noAF_pred,ClinPred_score,ClinPred_pred,clinvar_id,clinvar_clnsig,clinvar_trait,clinvar_review,clinvar_var_source,clinvar_OMIM_id,ALFA_Total_AF,ALFA_Total_AN,1000Gp3_AF,1000Gp3_AC,ExAC_AC,ExAC_AF,gnomAD_exomes_AF,gnomAD_exomes_AN,gnomAD_exomes_AC,gnomAD_genomes_AC,gnomAD_genomes_AF,gnomAD_genomes_AN,gnomAD_genomes_AC
`
But then VEP throws:
```
-------------------- EXCEPTION --------------------
MSG: ERROR: Invalid population gnomADg specified
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::BaseCacheVariation::check_frequency_filter /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseCacheVariation.pm:288
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::BaseCacheVariation::new /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseCacheVariation.pm:93
STACK Bio::EnsEMBL::VEP::CacheDir::get_all_AnnotationSources /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:194
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:122
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:92
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:200
STACK toplevel /opt/vep/src/ensembl-vep/vep:46
Date (localtime)    = Sun Sep 24 12:30:41 2023
Ensembl API version = 110
```

If I use --freq-pop gnomADe, it works. I also tried "gnomADg", gnomADg_AF and some other variation.

Also, if I don't filter, gnomADg frequencies are outputted.

In addition, some tags, which are reported in the VEP 110 manual, are not working, like:

`--af_exac
`
Which outputs that --af-exac does not exist.

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
Singularity running docker image on HPC cluster
```
#----------------------------------#
# ENSEMBL VARIANT EFFECT PREDICTOR #
#----------------------------------#

Versions:
  ensembl              : 110.584a8f3
  ensembl-funcgen      : 110.24e6da6
  ensembl-io           : 110.b1a0d57
  ensembl-variation    : 110.d34d25e
  ensembl-vep          : 110.1
```

**Comment by nakib103** [comment]
Hello @GACGAMA ,

Thanks for your query!

This is a known issue and have been reported before ([here](https://github.com/Ensembl/ensembl-vep/issues/1404)). The workaround currently is to use `filter_vep` to perform the filtering (like - `filter_vep --format vcf -i  out.vcf  --filter "gnomADg_AF < 0.01" -o filtered.vcf`)

About the `--af_exac` flag, as mentioned [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_af_exac) in the doc, it has been deprecated (since release 90 as per [release note](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#history)) and replaced by `gnomAD`. It can be used only with VEP version 88 or older.

Best regards,
Nakib

**Comment by GACGAMA** [comment]
I see!
I'm trying to pipe my input to not generate very large files because the annotated multiVCF (non-filtered) is aprox 2TB in size.
When doing:

 
`singularity exec -H /scratch4/vep_cache_singularity /scratch4/singularities/vep.sif vep --cache -i vcf --species homo_sapiens --assembly GRCh38  --buffer_size 10000 --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --format vcf --input_file /scratch4/nsobrei2/ggama1/wgs_vcf_vep/test_small_vcf/511912-0424960726.Consensus.sSNV.vcf.pass.vcf.gz  --vcf  --force_overwrite --pubmed --fork 4 --regulatory --polyphen b --af --max_af --af_1kg --af_gnomade --af_gnomadg --plugin CADD,"$CADD_SNV" --plugin CADD,"$CADD_INDEL" --plugin dbNSFP,"$dbNSFP",SIFT_pred,SIFT4G_pred,Polyphen2_HDIV_pred,MetaRNN_score,MetaRNN_pred,REVEL_score,BayesDel_noAF_score,BayesDel_noAF_pred,ClinPred_score,ClinPred_pred,clinvar_id,clinvar_clnsig,clinvar_trait,clinvar_review,clinvar_var_source,clinvar_OMIM_id,ALFA_Total_AF,ALFA_Total_AN,1000Gp3_AF,1000Gp3_AC,ExAC_AC,ExAC_AF,gnomAD_exomes_AF,gnomAD_exomes_AN,gnomAD_exomes_AC,gnomAD_genomes_AC,gnomAD_genomes_AF,gnomAD_genomes_AN,gnomAD_genomes_AC -o STDOUT | singularity exec -H /scratch4/vep_cache_singularity /scratch4/nsobrei2/singularities/vep.sif filter_vep --force_overwrite --only_matched  --output_file /scratch4/test_small_vcf/511912-0424960726.Consensus.sSNV.vcf.pass.VEP.gnomadg.vcf --filter "gnomADg_AF < 0.01 or not gnomADg_AF" `

The first command is always generating an intermediate file. I tried following the VEP tutorial using:
`-o STDOUT`

I tried without specifying output file without any success.
Is there anyway of not generating intermediate files?

**Comment by nakib103** [comment]
Hi @GACGAMA,
I am closing this issue. If you face further problem feel free to open a new one.

Best regards,
Nakib
