### ISSUE TITLE
Warning when using chm13

### ISSUE THREAD

**Issue by dingyaozhang** [Ensembl/ensembl-vep#1506]
## Describe the issue
When I ran 
`vep --dir_cache data/vepcache/ --cache --offline --fasta data/T2T_CHM13/chm13v2.0.fa --gff data/vepcache/chm13v2.0_GENCODEv35_CAT_Liftoff.vep.gff3.gz --symbol -i somaticSNV.vcf -o out1.txt --force_overwrite`

I got those warning:
`WARNING: The feature_type intron is being skipped
WARNING: The feature_type stop_codon is being skipped
WARNING: The feature_type start_codon is being skipped
WARNING: The feature_type three_prime_UTR is being skipped
WARNING: The feature_type five_prime_UTR is being skipped`

Do you know whether it happens and how to deal with it? Thank you so much!

**Comment by dingyaozhang** [comment]
Hi Nuno, thank you very much for your help!  Actually, I did not notice significant errors, but I am just afraid to miss something. The annotation file I used is T2T annotation, which is in https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/annotation/chm13v2.0_GENCODEv35_CAT_Liftoff.vep.gff3.gz  . Actually, I still could see intron features in the output, so I am really confused.

**Comment by nuno-agostinho** [comment]
Hey @dingyaozhang,

VEP parses the following features from GTF files to construct a custom gene/transcript annotation: https://github.com/Ensembl/ensembl-vep/blob/e1229f49b74995e89081f5b48d137fa6ea295654/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/GFF.pm#L72-L115

Any other features (including `intron`, `start_codon`, `stop_codon`, `five_prime_UTR`, `three_prime_UTR`) are not currently used to build the custom annotation.

> Actually, I still could see intron features in the output, so I am really confused.

VEP infers introns and start/stop codons from CDS and exons. These features are not usually available in GTF/GFF files, so this is a standard way to parse these formats.

Regarding 3'- and 5'-prime UTRs, we currently ignore those. I will put in our backlog to check if we can support these features and improve the warnings to be more clear about the process.

Let me know if you have any further questions! :)

Best,
Nuno

**Comment by dingyaozhang** [comment]
Hi Nuno,

Thank you so much for your help!!!! You are really helpful!!!!
I think then it should be ok to just ignore the warnings~

Best,
Dingyao
