### ISSUE TITLE
Error installing vep110 with --SPECIES all

### ISSUE THREAD

**Issue by garadar** [Ensembl/ensembl-vep#1514]
## Description
Trying to install VEP-110 though easybuild here the build cmd:

```
== 2023-10-09 12:14:17,953 easyblock.py:4277 WARNING build failed (first 300 chars): cmd " perl INSTALL.pl --NO_BIOPERL --NO_HTSLIB --AUTO af --SPECIES all --NO_UPDATE --DESTDIR /opt/ebsofts/VEP/110-GCC-11.3.0/modules/api " exited with exit code 255 and output:
```
And the error output:
```
ERROR: Unable to parse assembly name from 
Cyprinus_carpio_german_mirror.German_Mirror_carp_1.0.dna.toplevel.fa.gz
```

So it's installing all the species but the`Cyprinus_carpio_german_mirror.German_Mirror_carp_1.0.dna.toplevel.fa.gz` seems to be not available.

By looking a little more further:

https://www.ensembl.org/Cyprinus_carpio_german_mirror/Info/Index

https://ftp.ensembl.org/pub/release-110/fasta/cyprinus_carpio_germanmirror/dna/

It seems there is a typo in the name file:
https://ftp.ensembl.org/pub/release-110/fasta/cyprinus_carpio_germanmirror/dna/Cyprinus_carpio_germanmirror.German_Mirror_carp_1.0.dna.toplevel.fa.gz

It missing the '-' beetween german and mirror

### system
OS: rocky 8.8
VEP version: 110

Some datacenter are using easybuild to install software for large community, do you think you could provide a new version of the easybuild  recipe ?
https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/v/VEP

**Comment by likhitha-surapaneni** [comment]
Hi @garadar, thank you for reporting this. The issue indeed seems to be due to the "_" in the filename. We will get back to you once we have an update on the fix.

Best regards,
Likhitha

**Comment by likhitha-surapaneni** [comment]
Hi @garadar, the filename has been fixed and the issue should be resolved now. Please let us know if you are still facing problems.

Regarding the easy build recipes, unfortunately we do not support them. We recommend contacting the developers of Easybuild. 

Best regards,
Likhitha

**Comment by garadar** [comment]
Thank you very much
