### ISSUE TITLE
How to install the full VEP suit on HPC cluster ?

### ISSUE THREAD

**Issue by garadar** [Ensembl/ensembl-vep#1515]
## Describe the issue
Dear maintainer,

I am a sys-admin on HPC (High-Performance Computing) cluster and I am trying to build the VEP 110 suite as a simple user (not root) in  shared FS available for all users. To avoid installing it in each user's home directory, I would like to know the appropriate installation commands to use for this kind of infrastructure. I am not familiar with this software, so I'm unsure how it works internally.

By default, SPECIES and plugins are installed in `$HOME/.vep`. Is there a way to install them in a shared directory (e.g., the VEP installation directory), or should these files be stored in the user's home directory because they will be edited later?

Additionally, when I attempted to install other SPECIES as another user, I encountered permission errors:

```
cannot unlink file for /srv/export/opt/ebsofts-dev/VEP/110-GCC-11.3.0/modules/api/Bio/EnsEMBL/Funcgen/SegmentationStateEmission.pm: Permission denied at /srv/export/opt/ebsofts-dev/VEP/110-GCC-11.3.0/INSTALL.pl line 698.
cannot restore permissions to 0100666 for /srv/export/opt/ebsofts-dev/VEP/110-GCC-11.3.0/modules/api/Bio/EnsEMBL/Funcgen/SegmentationStateEmission.pm: Permission denied at /srv/export/opt/ebsofts-dev/VEP/110-GCC-11.3.0/INSTALL.pl line 698.
cannot remove directory for /srv/export/opt/ebsofts-dev/VEP/110-GCC-11.3.0/modules/api/Bio/EnsEMBL/Funcgen: Permission denied at /srv/export/opt/ebsofts-dev/VEP/110-GCC-11.3.0/INSTALL.pl line 698.
cannot unlink file for /srv/export/opt/ebsofts-dev/VEP/110-GCC-11.3.0/modules/api/Bio/EnsEMBL/RepeatMaskedSlice.pm: Permission denied at /srv/export/opt/ebsofts-dev/VEP/110-GCC-11.3.0/INSTALL.pl line 698.
cannot restore permissions to 0100666 for /srv/export/opt/ebsofts-dev/VEP/110-GCC-11.3.0/modules/api/Bio/EnsEMBL/RepeatMaskedSlice.pm: Permission denied at /srv/export/opt/ebsofts-dev/VEP/110-GCC-11.3.0/INSTALL.pl line 698.
cannot remove directory for /srv/export/opt/ebsofts-dev/VEP/110-GCC-11.3.0/modules/api/Bio/EnsEMBL: Permission denied at /srv/export/opt/ebsofts-dev/VEP/110-GCC-11.3.0/INSTALL.pl line 698.
cannot remove directory for /srv/export/opt/ebsofts-dev/VEP/110-GCC-11.3.0/modules/api/Bio/tmp: Permission denied at /srv/export/opt/ebsofts-dev/VEP/110-GCC-11.3.0/INSTALL.pl line 698.
cannot chdir to /root from /srv/export/opt/ebsofts-dev/VEP/110-GCC-11.3.0/modules/api/Bio: Permission denied, aborting. at /srv/export/opt/ebsofts-dev/VEP/110-GCC-11.3.0/INSTALL.pl line 698.
```
Could you please provide guidance on how to resolve these permission issues and properly configure VEP for a shared HPC environment?

Best Regards

**Comment by likhitha-surapaneni** [comment]
Hi @garadar,

It is recommended to have separate installations per user to avoid file permission and access issues while running VEP. If you wish to download species-related files to a custom directory, the option `--CACHEDIR <custom_directory_path>` must be passed during [installation](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#installer).

For installing VEP on HPC environments, we suggest you to take a look at setting up VEP using [docker](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker) or [singularity](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#singularity).

Hope this is helpful!

Best regards,
Likhitha

**Comment by likhitha-surapaneni** [comment]
Hi @garadar, I am closing this for now. Kindly open a new issue if there are any other problems.
