### ISSUE TITLE
Annotate variants withing +/- 15bp of target 

### ISSUE THREAD

**Issue by NandiniBN** [Ensembl/ensembl-vep#152]
Hello,

I'm looking to annotate my variants with HGVS that lie within +/- 15bp of my target/exon interval with the following command (vep v 91)
```

./vep --cache --dir_cache $cache --warning_file $i_warning.txt \
--fasta $fasta --no_stats \
--refseq --transcript_version --hgvs --symbol --sift p --polyphen p \
--af_gnomad --individual all --distance 15 \
--transcript_filter "stable_id match N[MR]_" \
--custom $cache/score.bed.gz,score,bed,exact,0 \
--custom $cache/HEX.bed.gz,HEX,bed,exact,0 \
--fork 4 --port 3337 --buffer_size 50 \
-i ${i}.recode.vcf -tab -o ${i}.txt
```
I also tried using the plugin `-plugin UpDownDistance,15 ` but that did not work either for me. My output file I think includes HGVS annotations that are beyond +/- 15 bp. 

```
#Uploaded_variation	Location	Allele	Gene	Feature	Feature_type	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	INDZYG	IMPACT	DISTANCE	STRAND	FLAGS	SYMBOL	SYMBOL_SOURCE	HGNC_ID	REFSEQ_MATCH	GIVEN_REF	USED_REF	BAM_EDIT	SOURCE	SIFT	PolyPhen	HGVSc	HGVSp	HGVS_OFFSETgnomAD_AF	gnomAD_AFR_AF	gnomAD_AMR_AF	gnomAD_ASJ_AF	gnomAD_EAS_AF	gnomAD_FIN_AF	gnomAD_NFE_AF	gnomAD_OTH_AF	gnomAD_SAS_AF	CLIN_SIG	SOMATIC	PHENO	score	HEX
rs11582684	1:15490962	G	55092	NM_001136216.1	Transcript	intron_variant	-	-	-	-	-	rs11582684	WES	HET	MODIFIER	-	1	-	TMEM51	EntrezGene	-	-	A	A	OK	-	-	-	NM_001136216.1:c.-267+11682A>G	-	-	0.2151	0.2637	0.2225	0.1693	0.3079	0.216	0.1805	0.2056	0.2407	-	-	-	-	-
rs11582684	1:15490962	G	55092	NM_001136217.1	Transcript	intron_variant	-	-	-	-	-	rs11582684	WES	HET	MODIFIER	-	1	-	TMEM51	EntrezGene	-	-	A	A	OK	-	-	-	NM_001136217.1:c.-194+11682A>G	-	-	0.2151	0.2637	0.2225	0.1693	0.3079	0.216	0.1805	0.2056	0.2407	-	-	-	-	-
rs11582684	1:15490962	G	55092	NM_001136218.1	Transcript	intron_variant	-	-	-	-	-	rs11582684	WES	HET	MODIFIER	-	1	-	TMEM51	EntrezGene	-	-	A	A	OK	-	-	-	NM_001136218.1:c.-267+10512A>G	-	-	0.2151	0.2637	0.2225	0.1693	0.3079	0.216	0.1805	0.2056	0.2407	-	-	-	-	-


```
Is there a way to limit this ? 

thanks

**Comment by sarahhunt** [comment]
Hi @NandiniBN ,

The options you mention configure how far upstream and downstream from the transcript variants are listed. We don't have an option to configure how far into the intron variants are reported.

The SpliceRegion.pm plugin flags variants within certain distances from the exon/intron boundary - can you modify this to flag variant within the regions you require?

**Comment by willmclaren** [comment]
If you are trying to find overlaps within 15bp +/- of the features in your BED file(s), you could use [BEDTOOLS](http://bedtools.readthedocs.io/en/latest/)

**Comment by NandiniBN** [comment]
Hi Both,
SpliceRegion.pm does not work either. So the HGVS annotation for `rs11582684` get is as follows
 
```
NM_001136216.1:c.-267+11682A>G
NM_001136217.1:c.-194+11682A>G
NM_001136218.1:c.-267+10512A>G	
```
Which is way beyond +/- 15bp of the target.

**Comment by ima23** [comment]
Hope bedtools is working for you. If you need more help, please get in touch.
