### ISSUE TITLE
Option `--hgvsg_use_accession` breaks execution when using RefSeq and merged caches

### ISSUE THREAD

**Issue by gabrielhim** [Ensembl/ensembl-vep#1520]
Hello, everyone.
I need to annotate the HGVSg of my variants using the RefSeq chromosome notation, so that variants such as `chr1:g.17407G>A` are reported as `NC_000001.11:g.17407G>A`. The option `--hgvsg_use_accession` seems to have that purpose, but adding it to the command breaks the execution. That was observed for both RefSeq and merged caches.

### System
- VEP version: 110.1
- VEP Cache version: 110

### Command line
```
docker run --rm -v $PWD:/data ensemblorg/ensembl-vep:release_110.1 vep \
    --input_file /data/samples/sample.vcf \
    --assembly GRCh38 \
    --dir_cache /data \
    --fasta /data/fasta/Homo_sapiens_assembly38.fasta \
    --force_overwrite \
    --hgvs \
    --hgvsg \
    --hgvsg_use_accession \
    --no_stats \
    --offline \
    --refseq \
    --tab \
    --output_file /data/outputs/sample.txt
```
This command was tried with `--refseq` and `--merged`.

### Error message
```
Smartmatch is experimental at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 472.
Can't call method "db" on an undefined value at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Slice.pm line 2984, <__ANONIO__> line 5409.
2023-10-12 23:53:39 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this
```

I would appreciate if you could look into this.
Thank you!!

**Comment by dglemos** [comment]
Hi @gabrielhim,
Thank you for reporting this issue.
There is a problem with the option `--hgvsg_use_accession` when run in offline mode`--offline`. We are trying to find a solution, in the meantime, you could run vep connecting to the database (option --database). I understand this is not optimal as connecting to the database increases the running time.
I'll let you know once we find a fix for this issue.

Best wishes,
Diana

**Comment by gabrielhim** [comment]
Hi, @dglemos.
Glad you identified the cause. Looking forward to the solution. We'll see if we can use the `--database` option for now.
Thank you very much!

**Comment by dglemos** [comment]
A fix has been applied to the code which will be available in the next release. 

Best wishes,
Diana

**Comment by gabrielhim** [comment]
Thank you, Diana!!
Best regards!
