### ISSUE TITLE
Failed to instantiate plugin AlphaMissense: ERROR: Tabix index file not found

### ISSUE THREAD

**Issue by jukerbox** [Ensembl/ensembl-vep#1526]
Hello!

I tried to use AlphaMissense module using the following command:

`./vep --plugin AlphaMissense,file=/home/ensembl/VEP/AlphaMissense_hg38.tsv.gz --species homo_sapiens --database -i /home/ensembl/VEP/5233.txt -o /home/ensembl/VEP/5233_out.txt`

but it ends with error:

`WARNING: Failed to instantiate plugin AlphaMissense: ERROR: Tabix index file /home/ensembl/VEP/AlphaMissense_hg38.tsv.gz.tbi not found - perhaps you need to create it first?`

So I tried to fix it using the command i found in the AlphaMissense.pm [line 85] file:

`tabix -s 1 -b 2 -e 2 -f -S 1 AlphaMissense_hg38.tsv.gz`

but it ends with error:

`[tabix] the compression of 'AlphaMissense_hg38.tsv.gz' is not BGZF`
 
How can I fix this problem?

### System
- VEP version: 110 
- VEP Cache version: not used due to lack of space
- Perl version:  5.34.0
- OS: Ubuntu
- tabix installed ? yes

**Comment by olaaustine** [comment]
Hi @jukerbox 
Hope this meets you well? 
Did you download the file using this url https://storage.googleapis.com/dm_alphamissense/AlphaMissense_hg38.tsv.gz
If no, Please can you redownload the file using that url and try to tabix it again. 
Let us know if this helps.
Thank you very much 
Ola

**Comment by jukerbox** [comment]
Thanks, @olaaustine, now it works!

**Comment by jukerbox** [comment]
Thanks, @olaaustine, now it works!
