### ISSUE TITLE
Wildtype, Downstream plugin in annotating indels

### ISSUE THREAD

**Issue by venkataddala** [Ensembl/ensembl-vep#153]
Hi guys,

I am not able to fetch wildtype and mutant aa sequence to Indels using Wildtype, Downstream plugin. I am using GATK indel vcf file as input. Used following command.

vep/86
variant_effect_predictor.pl --fork 24 -i "$donor"_indel_tumor_VEP.vcf  --output_file "$donor"_indel_VEP_Formated.vcf --vcf --format vcf --terms SO --dir /reference/software/vep  --symbol --dir_plugins /mnt/lustre/reference/software/vep/Plugins/ --plugin Downstream --plugin Wildtype --offline --coding_only --assembly GRCh37 --pick --buffer_size=50000 --minimal

**Comment by aparton** [comment]
Hi,

I've had a quick look at this issue and the Downstream plugin is working as expected for v86. However, I do not recognise the plugin 'Wildtype', is this a plugin that you have developed yourself? Can you try running the command without the Wildtype plugin and see if it works?

Additionally, we would recommend that you update to v91 if you can, there are multiple improvements and efficiencies included within VEP that are not available in v86.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

Please feel free to reopen the issue if you are still having problems.

Kind Regards,
Andrew

**Comment by sarahhunt** [comment]
Hi @venkataddala ,

If you have set up VEP88 to use  Bio::DB::Fasta, you will need to gzip rather than bgzip the fasta file.

Best wishes,
Sarah
