### ISSUE TITLE
Can VEP get the protein sequences created from mutation

### ISSUE THREAD

**Issue by LindseyOlsen** [Ensembl/ensembl-vep#1532]
Hello,

It wasn't clear to me from the documentation. Can VEP report the full protein sequence or transcript sequence predicted from a mutation (ex a splice site mutation)? If so, how?

Thanks,
Lindsey

**Comment by dglemos** [comment]
Hi @LindseyOlsen,
VEP has a plugin [ProteinSeqs](https://github.com/Ensembl/VEP_plugins/blob/release/110/ProteinSeqs.pm) that prints out the reference and mutated protein sequences of any proteins found with non-synonymous mutations in the input file.
Would this work for your use case?

**Comment by dglemos** [comment]
I'm going to close this issue but feel free to re-open it if you have more questions.

Best wishes,
Diana
