### ISSUE TITLE
AlphaMissense WARNING: Could not fetch slice for chromosome

### ISSUE THREAD

**Issue by jukerbox** [Ensembl/ensembl-vep#1533]
Hello!
I am using module AlphaMissense with the following command:

```
./vep --plugin AlphaMissense,file=/home/ensembl/VEP/AlphaMissense_hg38.tsv.gz --species homo_sapiens --database -i /home/ensembl/VEP/5233.vcf.gz -o /home/ensembl/VEP/5233_out.txt
```

But the work ends with the error message:
```
WARNING: Could not fetch slice for chromosome ﻿15 on line 
```
How can I fix it? Could there be problems in the input file?

### Data files
- The input file: [5233.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/13049877/5233.vcf.gz)
- The output file: [5233_out.txt_warnings.txt](https://github.com/Ensembl/ensembl-vep/files/13050647/5233_out.txt_warnings.txt)

### System
- VEP version: 110 
- VEP Cache version: not used due to lack of space
- Perl version: 5.34.0
- OS: Ubuntu

**Comment by jamie-m-a** [comment]
Hi @jukerbox 

Sorry to hear you're having trouble annotating your variants, as you have guessed already there is a problem with the input. In this case the reason you're seeing that error message is because the reference in GRCh38 at 15:48483839 is a C, not a T as you have in the example VCF.

As for resolving the issue, I can't really say without knowing more about how your input was generated. Do you have other variants in this set that worked correctly?

**Comment by jukerbox** [comment]
But I am sure the reference in our file is correct as it matches the sequences in: 

- IGV, 
![image](https://github.com/Ensembl/ensembl-vep/assets/79960394/bd610903-2bc0-450e-8d32-149a87b2ba78)
- NCBI, 
![image](https://github.com/Ensembl/ensembl-vep/assets/79960394/af6adf8b-ff7d-4184-9cba-b19009a96fbe)
- Encembl. 
![image](https://github.com/Ensembl/ensembl-vep/assets/79960394/fcdd718d-5d62-4ccb-a177-0f079465a016)

The input data are part of the WES data that we analyzed in our lab. Other variants were not tested. Should we do this?

**Comment by jukerbox** [comment]
Thanks for the tip! We rechecked the coordinates and found an error in them. Now the input file looks like this:
- [5322.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/13224087/5322.vcf.gz)

The data in it is part of WES that we ran in our lab. We would like to test this particular variant with AlphaMissense.

Since we changed the input, we also changed the command:
`./vep --plugin AlphaMissense,file=/home/ensembl/VEP/AlphaMissense_hg38.tsv.gz --species homo_sapiens --database --format vcf -i /home/ensembl/VEP/5322.vcf -o /home/ensembl/VEP/5322_out.txt`

But now another error has been added and the console message looks like this:

Argument "POS" isn't numeric in addition (+) at /home/ensembl/ensembl-api-folder/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 252.
WARNING: Start POS or end 2 coordinate invalid on line 1
WARNING: Could not fetch slice for chromosome ﻿15 on line 2

**Comment by nakib103** [comment]
Hello @jukerbox,

It seems your file still has some issue. If I paste it to a text file using vim editor - 
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT
<feff>15        48483889        .       T       C       998.64  .       .       .
```

The extra `<feff>` character suggests it is a UTF-16 encoded. Can you update the file to have ASCII/utf-8 encoding and see if it fixes your issue.

Best regards,
Nakib

**Comment by jukerbox** [comment]
Thank you @nakib103, it works now!
