### ISSUE TITLE
Mane transcript not showing in BioMart and vep 110 

### ISSUE THREAD

**Issue by FedericaBrando** [Ensembl/ensembl-vep#1539]
## Describe the issue
While annotating a dataset with vep, I was expecting PBRM1 gene to be annotated in MANE Select as it is in the MANE datasets v1.1 which is based on ensembl release 110, as written in the [README](https://ftp.ncbi.nlm.nih.gov/refseq/MANE/MANE_human/release_1.1/README_versions.txt). 

```
~$ cat  MANE.GRCh38.v1.1.summary.txt | grep PBRM1
GeneID:55193	ENSG00000163939.19	HGNC:30064	PBRM1	polybromo 1	NM_001405607.1	NP_001392536.1	ENST00000707071.1	ENSP00000516722.1	MANE Select	NC_000003.12	52545367	52685913	-
```

Although, when running vep it dows not get annotated as expected:

```
#Uploaded_variation	Location	Allele	Gene	Feature	Feature_type	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	IMPACT	DISTANCE	STRAND	FLAGS	SYMBOL	SYMBOL_SOURCE	HGNC_ID	CANONICAL	MANE_SELECT	MANE_PLUS_CLINICAL	ENSP
IXXXXXXXXXXXX	-ENSG00000163939	ENST00000707071	Transcript	frameshift_variant,stop_lost	5293	5113	1705	*/X	Taa/aa	-	HIGH	-	-1	-	PBRM1	HGNC	HGNC:30064	YES	-	-	ENSP00000516722
```

same on biomart:
![image](https://github.com/Ensembl/ensembl-vep/assets/52486325/6be4c56f-c0bc-4bbc-bf8c-c00c79b33f63)

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 110
- VEP Cache version: 110
- Perl version: v5.26.1
- OS: CentOS 
- tabix installed yes

### Full VEP command line
```
vep -i ${input} -o STDOUT --assembly GRCh38 \
			--no_stats --cache --offline --symbol \
			--protein --tab --canonical --mane \
			--dir vep \
```

**Comment by nuno-agostinho** [comment]
Hi @FedericaBrando,

Our current Ensembl release (e110) is using MANE Select v1.0, for which there is no PBRM1 transcript. We intend to update the MANE version in the next Ensembl release (e111).

In the meantime, you can run VEP with one of the annotation files from https://ftp.ncbi.nlm.nih.gov/refseq/MANE/MANE_human/release_1.1 as a custom annotation ([more instructions here](https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html)).

Sorry for the inconvenience. Let me know if this works for you.

Kind regards,
Nuno

**Comment by nuno-agostinho** [comment]
Hi @FedericaBrando, do you have any update on this issue? Was my previous comment helpful or would you like to discuss this further?

Looking forward for your reply.

Best regards,
Nuno

**Comment by nuno-agostinho** [comment]
Hi @FedericaBrando, I will be closing this ticket for now, but please feel free to discuss here if you have any updates on this issue. Thanks!
