### ISSUE TITLE
non-deterministic ##VEP line in header of VCF output

### ISSUE THREAD

**Issue by ntm** [Ensembl/ensembl-vep#1540]
Hi devs,

I'm using the latest VEP 110.1 release on an ALMA9 (~RHEL9) server, Perl v5.32.1.
When VEP outputs VCF it writes header lines including one that looks like this:
##VEP="v110" time="2023-10-27 18:47:28" cache="/data/.vep/homo_sapiens/110_GRCh38" ensembl=110.584a8f3 ensembl-funcgen=110.24e6da6 ensembl-io=110.b1a0d57 ensembl-variation=110.d34d25e 1000genomes="phase3" COSMIC="97" ClinVar="202301" HGMD-PUBLIC="20204" assembly="GRCh38.p14" dbSNP="154" gencode="GENCODE 44" genebuild="2014-07" gnomADe="r2.1.1" gnomADg="v3.1.2" polyphen="2.2.3" regbuild="1.0" sift="6.2.1"

In this line the fields ensembl, ensembl_funcgen, ensembl-io and ensembl-variation appear in a random order, and this order can change from run to run.
Example with a one-liner input VCF containing a single SNP:
$ cat in.vcf
chr12   11200   .       G       T       .       .       .
$ cat in.vcf | vep --offline --format vcf --vcf --stats_file vepStats.html --force_overwrite -o STDOUT > out1.vcf
$ cat in.vcf | vep --offline --format vcf --vcf --stats_file vepStats.html --force_overwrite -o STDOUT > out2.vcf
$ diff out1.vcf out2.vcf
-> different order of ensembl API modules in the ##VEP line

This non-deterministic behavior makes comparing results between runs a bit more complicated, and could be fixed easily here:
https://github.com/Ensembl/ensembl-vep/blob/1066f6836fd10163f995424728a92dc899711de6/modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm#L225
add "sort" just before "keys". This patch solves ths issue in my tests.
Note that a few lines below, the "misc version" info IS sorted, with "sort keys" line 233. It's only the API module versions that are not sorted.

Also note that I used to get deterministic order when running under CentOS 7 (much older Perl version), so I guess this issue may depend on your perl version. But it CAN happen, as Perl doesn't provide any guarantees on the order of hash keys returned by keys().

Would you consider patching this?
I can fork and make a PR if needed, although for a 5-char diff it seems overkill.

Regards,
Nicolas

**Comment by likhitha-surapaneni** [comment]
Hi Nicolas,

Thank you for notifying us. We will provide a fix to sort the keys as suggested.

Kind regards,
Likhitha

**Comment by ntm** [comment]
Hi devs,
I see the patch is in the latest released VEP 112, closing this issue!
Regards,
Nicolas
