### ISSUE TITLE
LoFtool_scores.txt is not in your docker image "ensemblorg/ensembl-vep"

### ISSUE THREAD

**Issue by qisun2** [Ensembl/ensembl-vep#1541]
Thanks for including vep plugins in the docker image "ensemblorg/ensembl-vep". Three text files are missing from the /plugins directory of the image: LoFtool_scores.txt  neXtProt_headers.txt  pLI_values.txt  
When running vep LoFtools plugin in the docker container, I get this warning message:
WARNING: Failed to instantiate plugin LoFtool: ERROR: LoFtool scores file /plugins//LoFtool_scores.txt not found

**Comment by nakib103** [comment]
Hi @qisun2,

Thanks for your query!

The Ensembl docker image only include plugin and their dependency. If plugin does not require data or automatically downloads it, you can run them off simply by calling them.

But if plugin requires external data you have to download them manually and point to them as shown in the plugin description. `LoFtool` plugin requires external data which you can download from [here](https://github.com/Ensembl/VEP_plugins/blob/release/110/LoFtool_scores.txt) (or, you can also download from different source if you have any).

In future we can add logic to automatically download the datafile for LoFtool but this is not a priority right now.

Best regards,
Nakib

**Comment by nakib103** [comment]
Hi @qisun2, I am closing this ticket. Feel free to open another one if you face further issues.

Best regards,
Nakib

**Comment by Sreelekshmi-291** [comment]
Hi Team,
I am facing the same issue in Docker. Could you please guide me through the usage of plugins that require additional files? For example, in this case, where do you install this file, LoFtool_scores.txt? How do you point it to Docker?

**Comment by nakib103** [comment]
Hello @Sreelekshmi-291 ,

You do not need to install the file. You can put it the file in any location in your computer and point to that location when using the plugin. For example, say, you place the file in `/Users/abcd/vep_data/plugin/LoFtool_scores.txt` then you can run -
```
vep -i variants.vcf --plugin LoFtool,/Users/abcd/vep_data/plugin/LoFtool_scores.txt
```

If you are using docker you need to make this file available to your docker container and you have to mount that directory -
```
docker run -t -i -v $Users/abcd/vep_data:/data ensemblorg/ensembl-vep vep -i variants.vcf --plugin LoFtool,plugin/LoFtool_scores.txt
```

See more at - https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker
also docker reference - https://docs.docker.com/reference/cli/docker/container/run/#volume

Best regards,
Nakib
