### ISSUE TITLE
Docker build from scratch fails

### ISSUE THREAD

**Issue by vpoten** [Ensembl/ensembl-vep#1543]
## Describe the issue
When trying to build the docker image from scratch, using the official dockerfile, an error is got.

## Additional information
The error seems to be related to the `DBD::mysql` dependency: 
> Configuring DBD-mysql-5.002 ... ! Configure failed for DBD-mysql-5.002. See /root/.cpanm/work/1698671110.1188/build.log for details.

### System
- VEP version: 110

### Full error message
> #0 42.55 ==> Found dependencies: DBI, Test::Differences, Error, Test::Pod::Coverage, Perl::Critic::Utils, PadWalker, Test::Deep, IO::String, Test::Warnings, Gzip::Faster, Devel::Cycle, Test::MockObject, Test::Exception, DBD::mysql, Test::Perl::Critic, Config::IniFiles
#0 42.85 --> Working on DBI
#0 42.85 Fetching http://www.cpan.org/authors/id/T/TI/TIMB/DBI-1.643.tar.gz ... OK
#0 43.30 Configuring DBI-1.643 ... OK
#0 43.64 Building DBI-1.643 ... OK
#0 49.31 Successfully installed DBI-1.643
#0 49.41 --> Working on Test::Differences
#0 49.41 Fetching http://www.cpan.org/authors/id/D/DC/DCANTRELL/Test-Differences-0.71.tar.gz ... OK
#0 49.50 Configuring Test-Differences-0.71 ... OK
#0 49.67 ==> Found dependencies: Text::Diff, Capture::Tiny
#0 49.71 --> Working on Text::Diff
#0 49.71 Fetching http://www.cpan.org/authors/id/N/NE/NEILB/Text-Diff-1.45.tar.gz ... OK
#0 49.82 Configuring Text-Diff-1.45 ... OK
#0 50.00 Building Text-Diff-1.45 ... OK
#0 50.46 Successfully installed Text-Diff-1.45
#0 50.56 --> Working on Capture::Tiny
#0 50.56 Fetching http://www.cpan.org/authors/id/D/DA/DAGOLDEN/Capture-Tiny-0.48.tar.gz ... OK
#0 50.69 Configuring Capture-Tiny-0.48 ... OK
#0 50.88 Building Capture-Tiny-0.48 ... OK
#0 51.38 Successfully installed Capture-Tiny-0.48
#0 51.45 Building Test-Differences-0.71 ... OK
#0 51.95 Successfully installed Test-Differences-0.71
#0 52.05 --> Working on Error
#0 52.05 Fetching http://www.cpan.org/authors/id/S/SH/SHLOMIF/Error-0.17029.tar.gz ... OK
#0 52.19 Configuring Error-0.17029 ... OK
#0 52.36 Building Error-0.17029 ... OK
#0 52.75 Successfully installed Error-0.17029
#0 52.87 --> Working on Test::Pod::Coverage
#0 52.87 Fetching http://www.cpan.org/authors/id/N/NE/NEILB/Test-Pod-Coverage-1.10.tar.gz ... OK
#0 52.96 Configuring Test-Pod-Coverage-1.10 ... OK
#0 53.13 ==> Found dependencies: Pod::Coverage
#0 53.18 --> Working on Pod::Coverage
#0 53.18 Fetching http://www.cpan.org/authors/id/R/RC/RCLAMP/Pod-Coverage-0.23.tar.gz ... OK
#0 53.29 Configuring Pod-Coverage-0.23 ... OK
#0 53.46 ==> Found dependencies: Devel::Symdump
#0 53.51 --> Working on Devel::Symdump
#0 53.51 Fetching http://www.cpan.org/authors/id/A/AN/ANDK/Devel-Symdump-2.18.tar.gz ... OK
#0 53.63 Configuring Devel-Symdump-2.18 ... OK
#0 53.85 Building Devel-Symdump-2.18 ... OK
#0 54.33 Successfully installed Devel-Symdump-2.18
#0 54.39 Building Pod-Coverage-0.23 ... OK
#0 54.97 Successfully installed Pod-Coverage-0.23
#0 55.03 Building Test-Pod-Coverage-1.10 ... OK
#0 55.49 Successfully installed Test-Pod-Coverage-1.10
#0 55.59 --> Working on Perl::Critic::Utils
#0 55.59 Fetching http://www.cpan.org/authors/id/P/PE/PETDANCE/Perl-Critic-1.152.tar.gz ... OK
#0 56.29 ==> Found dependencies: List::SomeUtils, B::Keywords
#0 56.33 --> Working on List::SomeUtils
#0 56.33 Fetching http://www.cpan.org/authors/id/D/DR/DROLSKY/List-SomeUtils-0.59.tar.gz ... OK
#0 56.48 Configuring List-SomeUtils-0.59 ... OK
#0 56.92 ==> Found dependencies: List::SomeUtils::XS
#0 56.97 --> Working on List::SomeUtils::XS
#0 56.97 Fetching http://www.cpan.org/authors/id/D/DR/DROLSKY/List-SomeUtils-XS-0.58.tar.gz ... OK
#0 57.14 Configuring List-SomeUtils-XS-0.58 ... OK
#0 57.38 Building List-SomeUtils-XS-0.58 ... OK
#0 60.10 Successfully installed List-SomeUtils-XS-0.58
#0 60.17 Building List-SomeUtils-0.59 ... OK
#0 60.67 Successfully installed List-SomeUtils-0.59
#0 60.77 --> Working on B::Keywords
#0 60.77 Fetching http://www.cpan.org/authors/id/R/RU/RURBAN/B-Keywords-1.26.tar.gz ... OK
#0 60.89 Configuring B-Keywords-1.26 ... OK
#0 61.06 Building B-Keywords-1.26 ... OK
#0 61.56 Successfully installed B-Keywords-1.26
#0 61.63 Configuring Perl-Critic-1.152 ... OK
#0 61.93 ==> Found dependencies: PPI::Document, Module::Pluggable, Exception::Class, PPIx::Regexp, Config::Tiny, Pod::Spell, String::Format, PPI::Token::Whitespace, PPI::Document::File, PPI::Token::Quote::Single, File::Which, PPIx::Regexp::Util, PPIx::Utils::Traversal, PPIx::QuoteLike, Perl::Tidy, PPI::Node, PPI
#0 61.98 --> Working on PPI::Document
#0 61.98 Fetching http://www.cpan.org/authors/id/M/MI/MITHALDU/PPI-1.277.tar.gz ... OK
#0 62.39 Configuring PPI-1.277 ... OK
#0 62.67 ==> Found dependencies: Task::Weaken, Clone
#0 62.72 --> Working on Task::Weaken
#0 62.72 Fetching http://www.cpan.org/authors/id/E/ET/ETHER/Task-Weaken-1.06.tar.gz ... OK
#0 62.85 Configuring Task-Weaken-1.06 ... OK
#0 63.10 Building Task-Weaken-1.06 ... OK
#0 63.58 Successfully installed Task-Weaken-1.06
#0 63.67 --> Working on Clone
#0 63.67 Fetching http://www.cpan.org/authors/id/G/GA/GARU/Clone-0.46.tar.gz ... OK
#0 63.80 Configuring Clone-0.46 ... OK
#0 63.97 Building Clone-0.46 ... OK
#0 65.05 Successfully installed Clone-0.46
#0 65.13 Building PPI-1.277 ... OK
#0 66.63 Successfully installed PPI-1.277
#0 66.73 --> Working on Module::Pluggable
#0 66.73 Fetching http://www.cpan.org/authors/id/S/SI/SIMONW/Module-Pluggable-5.2.tar.gz ... OK
#0 66.87 Configuring Module-Pluggable-5.2 ... OK
#0 67.06 Building Module-Pluggable-5.2 ... OK
#0 67.58 Successfully installed Module-Pluggable-5.2
#0 67.69 --> Working on Exception::Class
#0 67.69 Fetching http://www.cpan.org/authors/id/D/DR/DROLSKY/Exception-Class-1.45.tar.gz ... OK
#0 67.84 Configuring Exception-Class-1.45 ... OK
#0 68.08 ==> Found dependencies: Devel::StackTrace, Class::Data::Inheritable
#0 68.12 --> Working on Devel::StackTrace
#0 68.12 Fetching http://www.cpan.org/authors/id/D/DR/DROLSKY/Devel-StackTrace-2.04.tar.gz ... OK
#0 68.26 Configuring Devel-StackTrace-2.04 ... OK
#0 68.49 Building Devel-StackTrace-2.04 ... OK
#0 69.02 Successfully installed Devel-StackTrace-2.04
#0 69.15 --> Working on Class::Data::Inheritable
#0 69.15 Fetching http://www.cpan.org/authors/id/R/RS/RSHERER/Class-Data-Inheritable-0.09.tar.gz ... OK
#0 69.24 Configuring Class-Data-Inheritable-0.09 ... OK
#0 69.41 Building Class-Data-Inheritable-0.09 ... OK
#0 69.88 Successfully installed Class-Data-Inheritable-0.09
#0 69.94 Building Exception-Class-1.45 ... OK
#0 70.45 Successfully installed Exception-Class-1.45
#0 70.56 --> Working on PPIx::Regexp
#0 70.56 Fetching http://www.cpan.org/authors/id/W/WY/WYANT/PPIx-Regexp-0.088.tar.gz ... OK
#0 70.90 Configuring PPIx-Regexp-0.088 ... OK
#0 71.15 Building PPIx-Regexp-0.088 ... OK
#0 72.10 Successfully installed PPIx-Regexp-0.088
#0 72.19 --> Working on Config::Tiny
#0 72.19 Fetching http://www.cpan.org/authors/id/R/RS/RSAVAGE/Config-Tiny-2.30.tgz ... OK
#0 72.31 Configuring Config-Tiny-2.30 ... OK
#0 72.50 Building Config-Tiny-2.30 ... OK
#0 72.99 Successfully installed Config-Tiny-2.30
#0 73.09 --> Working on Pod::Spell
#0 73.09 Fetching http://www.cpan.org/authors/id/H/HA/HAARG/Pod-Spell-1.26.tar.gz ... OK
#0 73.20 ==> Found dependencies: File::ShareDir::Install
#0 73.24 --> Working on File::ShareDir::Install
#0 73.24 Fetching http://www.cpan.org/authors/id/E/ET/ETHER/File-ShareDir-Install-0.14.tar.gz ... OK
#0 73.40 Configuring File-ShareDir-Install-0.14 ... OK
#0 73.64 Building File-ShareDir-Install-0.14 ... OK
#0 74.12 Successfully installed File-ShareDir-Install-0.14
#0 74.18 Configuring Pod-Spell-1.26 ... OK
#0 74.38 ==> Found dependencies: Class::Tiny, Lingua::EN::Inflect, File::ShareDir
#0 74.45 --> Working on Class::Tiny
#0 74.45 Fetching http://www.cpan.org/authors/id/D/DA/DAGOLDEN/Class-Tiny-1.008.tar.gz ... OK
#0 74.57 Configuring Class-Tiny-1.008 ... OK
#0 74.77 Building Class-Tiny-1.008 ... OK
#0 75.21 Successfully installed Class-Tiny-1.008
#0 75.31 --> Working on Lingua::EN::Inflect
#0 75.31 Fetching http://www.cpan.org/authors/id/D/DC/DCONWAY/Lingua-EN-Inflect-1.905.tar.gz ... OK
#0 75.43 Configuring Lingua-EN-Inflect-1.905 ... OK
#0 75.64 Building Lingua-EN-Inflect-1.905 ... OK
#0 76.17 Successfully installed Lingua-EN-Inflect-1.905
#0 76.27 --> Working on File::ShareDir
#0 76.27 Fetching http://www.cpan.org/authors/id/R/RE/REHSACK/File-ShareDir-1.118.tar.gz ... OK
#0 76.39 ==> Found dependencies: inc::latest
#0 76.44 --> Working on inc::latest
#0 76.44 Fetching http://www.cpan.org/authors/id/D/DA/DAGOLDEN/inc-latest-0.500.tar.gz ... OK
#0 76.54 Configuring inc-latest-0.500 ... OK
#0 76.72 Building inc-latest-0.500 ... OK
#0 77.22 Successfully installed inc-latest-0.500
#0 77.28 Configuring File-ShareDir-1.118 ... OK
#0 77.49 ==> Found dependencies: Class::Inspector, List::MoreUtils
#0 77.54 --> Working on Class::Inspector
#0 77.54 Fetching http://www.cpan.org/authors/id/P/PL/PLICEASE/Class-Inspector-1.36.tar.gz ... OK
#0 77.65 Configuring Class-Inspector-1.36 ... OK
#0 77.82 Building Class-Inspector-1.36 ... OK
#0 78.34 Successfully installed Class-Inspector-1.36
#0 78.45 --> Working on List::MoreUtils
#0 78.45 Fetching http://www.cpan.org/authors/id/R/RE/REHSACK/List-MoreUtils-0.430.tar.gz ... OK
#0 78.73 ==> Found dependencies: Config::AutoConf
#0 78.78 --> Working on Config::AutoConf
#0 78.78 Fetching http://www.cpan.org/authors/id/A/AM/AMBS/Config-AutoConf-0.320.tar.gz ... OK
#0 78.88 Configuring Config-AutoConf-0.320 ... OK
#0 79.08 ==> Found dependencies: File::Slurper
#0 79.14 --> Working on File::Slurper
#0 79.14 Fetching http://www.cpan.org/authors/id/L/LE/LEONT/File-Slurper-0.014.tar.gz ... OK
#0 79.23 Configuring File-Slurper-0.014 ... OK
#0 79.40 ==> Found dependencies: PerlIO::utf8_strict
#0 79.45 --> Working on PerlIO::utf8_strict
#0 79.45 Fetching http://www.cpan.org/authors/id/L/LE/LEONT/PerlIO-utf8_strict-0.010.tar.gz ... OK
#0 79.60 Configuring PerlIO-utf8_strict-0.010 ... OK
#0 79.77 Building PerlIO-utf8_strict-0.010 ... OK
#0 80.74 Successfully installed PerlIO-utf8_strict-0.010
#0 80.80 Building File-Slurper-0.014 ... OK
#0 81.30 Successfully installed File-Slurper-0.014
#0 81.37 Building Config-AutoConf-0.320 ... OK
#0 81.92 Successfully installed Config-AutoConf-0.320
#0 81.98 Configuring List-MoreUtils-0.430 ... OK
#0 82.43 ==> Found dependencies: List::MoreUtils::XS
#0 82.48 --> Working on List::MoreUtils::XS
#0 82.48 Fetching http://www.cpan.org/authors/id/R/RE/REHSACK/List-MoreUtils-XS-0.430.tar.gz ... OK
#0 82.74 Configuring List-MoreUtils-XS-0.430 ... OK
#0 84.14 Building List-MoreUtils-XS-0.430 ... OK
#0 87.89 Successfully installed List-MoreUtils-XS-0.430 (upgraded from 0.416)
#0 87.95 Building List-MoreUtils-0.430 ... OK
#0 88.50 Successfully installed List-MoreUtils-0.430 (upgraded from 0.416)
#0 88.58 Building File-ShareDir-1.118 ... OK
#0 89.22 Successfully installed File-ShareDir-1.118
#0 89.29 Building Pod-Spell-1.26 ... OK
#0 90.10 Successfully installed Pod-Spell-1.26
#0 90.20 --> Working on String::Format
#0 90.20 Fetching http://www.cpan.org/authors/id/S/SR/SREZIC/String-Format-1.18.tar.gz ... OK
#0 90.29 Configuring String-Format-1.18 ... OK
#0 90.46 Building String-Format-1.18 ... OK
#0 90.96 Successfully installed String-Format-1.18
#0 91.22 --> Working on File::Which
#0 91.22 Fetching http://www.cpan.org/authors/id/P/PL/PLICEASE/File-Which-1.27.tar.gz ... OK
#0 91.32 Configuring File-Which-1.27 ... OK
#0 91.50 Building File-Which-1.27 ... OK
#0 91.95 Successfully installed File-Which-1.27
#0 92.11 --> Working on PPIx::Utils::Traversal
#0 92.11 Fetching http://www.cpan.org/authors/id/D/DB/DBOOK/PPIx-Utils-0.003.tar.gz ... OK
#0 92.25 Configuring PPIx-Utils-0.003 ... OK
#0 92.46 Building PPIx-Utils-0.003 ... OK
#0 93.02 Successfully installed PPIx-Utils-0.003
#0 93.12 --> Working on PPIx::QuoteLike
#0 93.12 Fetching http://www.cpan.org/authors/id/W/WY/WYANT/PPIx-QuoteLike-0.023.tar.gz ... OK
#0 93.28 Configuring PPIx-QuoteLike-0.023 ... OK
#0 93.58 Building PPIx-QuoteLike-0.023 ... OK
#0 94.08 Successfully installed PPIx-QuoteLike-0.023
#0 94.17 --> Working on Perl::Tidy
#0 94.17 Fetching http://www.cpan.org/authors/id/S/SH/SHANCOCK/Perl-Tidy-20230912.tar.gz ... OK
#0 94.70 Configuring Perl-Tidy-20230912 ... OK
#0 94.92 Building Perl-Tidy-20230912 ... OK
#0 95.96 Successfully installed Perl-Tidy-20230912
#0 96.16 Building Perl-Critic-1.152 ... OK
#0 98.45 Successfully installed Perl-Critic-1.152
#0 98.56 --> Working on PadWalker
#0 98.56 Fetching http://www.cpan.org/authors/id/R/RO/ROBIN/PadWalker-2.5.tar.gz ... OK
#0 98.69 Configuring PadWalker-2.5 ... OK
#0 98.85 Building PadWalker-2.5 ... OK
#0 99.84 Successfully installed PadWalker-2.5
#0 99.95 --> Working on Test::Deep
#0 99.95 Fetching http://www.cpan.org/authors/id/R/RJ/RJBS/Test-Deep-1.204.tar.gz ... OK
#0 100.2 Configuring Test-Deep-1.204 ... OK
#0 100.4 Building Test-Deep-1.204 ... OK
#0 101.4 Successfully installed Test-Deep-1.204
#0 101.5 --> Working on IO::String
#0 101.5 Fetching http://www.cpan.org/authors/id/G/GA/GAAS/IO-String-1.08.tar.gz ... OK
#0 101.6 Configuring IO-String-1.08 ... OK
#0 101.7 Building IO-String-1.08 ... OK
#0 102.2 Successfully installed IO-String-1.08
#0 102.3 --> Working on Test::Warnings
#0 102.3 Fetching http://www.cpan.org/authors/id/E/ET/ETHER/Test-Warnings-0.032.tar.gz ... OK
#0 102.5 Configuring Test-Warnings-0.032 ... OK
#0 102.7 Building Test-Warnings-0.032 ... OK
#0 103.2 Successfully installed Test-Warnings-0.032
#0 103.3 --> Working on Gzip::Faster
#0 103.3 Fetching http://www.cpan.org/authors/id/B/BK/BKB/Gzip-Faster-0.21.tar.gz ... OK
#0 103.4 Configuring Gzip-Faster-0.21 ... OK
#0 103.7 Building Gzip-Faster-0.21 ... OK
#0 104.8 Successfully installed Gzip-Faster-0.21
#0 104.9 --> Working on Devel::Cycle
#0 104.9 Fetching http://www.cpan.org/authors/id/L/LD/LDS/Devel-Cycle-1.12.tar.gz ... OK
#0 105.0 Configuring Devel-Cycle-1.12 ... OK
#0 105.1 Building Devel-Cycle-1.12 ... OK
#0 105.6 Successfully installed Devel-Cycle-1.12
#0 105.8 --> Working on Test::MockObject
#0 105.8 Fetching http://www.cpan.org/authors/id/C/CH/CHROMATIC/Test-MockObject-1.20200122.tar.gz ... OK
#0 105.9 Configuring Test-MockObject-1.20200122 ... OK
#0 106.0 ==> Found dependencies: UNIVERSAL::isa, UNIVERSAL::can
#0 106.1 --> Working on UNIVERSAL::isa
#0 106.1 Fetching http://www.cpan.org/authors/id/E/ET/ETHER/UNIVERSAL-isa-1.20171012.tar.gz ... OK
#0 106.2 Configuring UNIVERSAL-isa-1.20171012 ... OK
#0 106.5 Building UNIVERSAL-isa-1.20171012 ... OK
#0 106.9 Successfully installed UNIVERSAL-isa-1.20171012
#0 107.0 --> Working on UNIVERSAL::can
#0 107.0 Fetching http://www.cpan.org/authors/id/C/CH/CHROMATIC/UNIVERSAL-can-1.20140328.tar.gz ... OK
#0 107.1 Configuring UNIVERSAL-can-1.20140328 ... OK
#0 107.3 Building UNIVERSAL-can-1.20140328 ... OK
#0 107.7 Successfully installed UNIVERSAL-can-1.20140328
#0 107.8 Building Test-MockObject-1.20200122 ... OK
#0 108.3 Successfully installed Test-MockObject-1.20200122
#0 108.4 --> Working on Test::Exception
#0 108.4 Fetching http://www.cpan.org/authors/id/E/EX/EXODIST/Test-Exception-0.43.tar.gz ... OK
#0 108.5 Configuring Test-Exception-0.43 ... OK
#0 108.7 ==> Found dependencies: Sub::Uplevel
#0 108.7 --> Working on Sub::Uplevel
#0 108.7 Fetching http://www.cpan.org/authors/id/D/DA/DAGOLDEN/Sub-Uplevel-0.2800.tar.gz ... OK
#0 108.8 Configuring Sub-Uplevel-0.2800 ... OK
#0 109.0 Building Sub-Uplevel-0.2800 ... OK
#0 109.5 Successfully installed Sub-Uplevel-0.2800
#0 109.6 Building Test-Exception-0.43 ... OK
#0 110.0 Successfully installed Test-Exception-0.43
#0 110.1 --> Working on DBD::mysql
#0 110.1 Fetching http://www.cpan.org/authors/id/D/DV/DVEEDEN/DBD-mysql-5.002.tar.gz ... OK
#0 110.4 ==> Found dependencies: Devel::CheckLib
#0 110.4 --> Working on Devel::CheckLib
#0 110.4 Fetching http://www.cpan.org/authors/id/M/MA/MATTN/Devel-CheckLib-1.16.tar.gz ... OK
#0 110.5 Configuring Devel-CheckLib-1.16 ... OK
#0 110.7 Building Devel-CheckLib-1.16 ... OK
#0 111.4 Successfully installed Devel-CheckLib-1.16
#0 111.4 Configuring DBD-mysql-5.002 ... ! Configure failed for DBD-mysql-5.002. See /root/.cpanm/work/1698671110.1188/build.log for details.
#0 111.6 N/A
#0 111.7 --> Working on Test::Perl::Critic
#0 111.7 Fetching http://www.cpan.org/authors/id/P/PE/PETDANCE/Test-Perl-Critic-1.04.tar.gz ... OK
#0 111.8 Configuring Test-Perl-Critic-1.04 ... OK
#0 111.9 ==> Found dependencies: MCE
#0 112.0 --> Working on MCE
#0 112.0 Fetching http://www.cpan.org/authors/id/M/MA/MARIOROY/MCE-1.889.tar.gz ... OK
#0 112.2 Configuring MCE-1.889 ... OK
#0 112.4 ==> Found dependencies: Sereal::Decoder, Sereal::Encoder
#0 112.5 --> Working on Sereal::Decoder
#0 112.5 Fetching http://www.cpan.org/authors/id/Y/YV/YVES/Sereal-Decoder-5.004.tar.gz ... OK
#0 112.9 Configuring Sereal-Decoder-5.004 ... OK
#0 113.2 ==> Found dependencies: Test::LongString, Test::Warn
#0 113.2 --> Working on Test::LongString
#0 113.2 Fetching http://www.cpan.org/authors/id/R/RG/RGARCIA/Test-LongString-0.17.tar.gz ... OK
#0 113.3 Configuring Test-LongString-0.17 ... OK
#0 113.5 Building Test-LongString-0.17 ... OK
#0 114.0 Successfully installed Test-LongString-0.17
#0 114.1 --> Working on Test::Warn
#0 114.1 Fetching http://www.cpan.org/authors/id/B/BI/BIGJ/Test-Warn-0.37.tar.gz ... OK
#0 114.2 Configuring Test-Warn-0.37 ... OK
#0 114.4 Building Test-Warn-0.37 ... OK
#0 114.8 Successfully installed Test-Warn-0.37
#0 114.9 Building Sereal-Decoder-5.004 ... OK
#0 140.8 Successfully installed Sereal-Decoder-5.004
#0 140.9 --> Working on Sereal::Encoder
#0 140.9 Fetching http://www.cpan.org/authors/id/Y/YV/YVES/Sereal-Encoder-5.004.tar.gz ... OK
#0 141.3 Configuring Sereal-Encoder-5.004 ... OK
#0 141.7 Building Sereal-Encoder-5.004 ... OK
#0 167.7 Successfully installed Sereal-Encoder-5.004
#0 167.8 Building MCE-1.889 ... OK
#0 168.7 Successfully installed MCE-1.889
#0 168.8 Building Test-Perl-Critic-1.04 ... OK
#0 169.1 Successfully installed Test-Perl-Critic-1.04
#0 169.2 --> Working on Config::IniFiles
#0 169.2 Fetching http://www.cpan.org/authors/id/S/SH/SHLOMIF/Config-IniFiles-3.000003.tar.gz ... OK
#0 169.4 Configuring Config-IniFiles-3.000003 ... OK
#0 169.6 Building Config-IniFiles-3.000003 ... OK
#0 170.0 Successfully installed Config-IniFiles-3.000003
#0 170.1 ! Installing the dependencies failed: Module 'DBD::mysql' is not installed
#0 170.1 ! Bailing out the installation for ..
#0 170.1 57 distributions installed

dockerfile_vep:142

 141 |     # Install/compile more libraries
 142 | >>> RUN export MACHTYPE=$(uname -m) &&\
 143 | >>>     ensembl-vep/travisci/build_c.sh && \
 144 | >>>     # Remove unused Bio-DB-HTS files
 145 | >>>     rm -rf Bio-HTS/cpanfile Bio-HTS/Build.PL Bio-HTS/Build Bio-HTS/_build Bio-HTS/INSTALL.pl && \
 146 | >>>     # Install ensembl perl dependencies (cpanm)
 147 | >>>     cpanm --installdeps --with-recommends --notest --cpanfile ensembl_cpanfile . && \
 148 | >>>     cpanm --installdeps --with-recommends --notest --cpanfile ensembl-vep/cpanfile . && \
 149 | >>>     # Delete bioperl and cpanfiles after the cpanm installs as bioperl will be reinstalled by the INSTALL.pl script
 150 | >>>     rm -rf bioperl-live ensembl_cpanfile ensembl-vep/cpanfile && \
 151 | >>>     # Configure "locale", see https://github.com/rocker-org/rocker/issues/19
 152 | >>>     echo "$LANG_VAR UTF-8" >> /etc/locale.gen && locale-gen en_US.utf8 && \
 153 | >>>     /usr/sbin/update-locale LANG=$LANG_VAR && \
 154 | >>>     # Copy htslib executables. It also requires the packages 'zlib1g-dev', 'libbz2-dev' and 'liblzma-dev'
 155 | >>>     cp $HTSLIB_DIR/bgzip $HTSLIB_DIR/tabix $HTSLIB_DIR/htsfile /usr/local/bin/ && \
 156 | >>>     # Remove CPAN cache
 157 | >>>     rm -rf /root/.cpanm
 158 |     
 
ERROR: failed to solve: process "/bin/sh -c export MACHTYPE=$(uname -m) &&    ensembl-vep/travisci/build_c.sh &&     rm -rf Bio-HTS/cpanfile Bio-HTS/Build.PL Bio-HTS/Build Bio-HTS/_build Bio-HTS/INSTALL.pl &&     cpanm --installdeps --with-recommends --notest --cpanfile ensembl_cpanfile . &&     cpanm --installdeps --with-recommends --notest --cpanfile ensembl-vep/cpanfile . &&     rm -rf bioperl-live ensembl_cpanfile ensembl-vep/cpanfile &&     echo \"$LANG_VAR UTF-8\" >> /etc/locale.gen && locale-gen en_US.utf8 &&     /usr/sbin/update-locale LANG=$LANG_VAR &&     cp $HTSLIB_DIR/bgzip $HTSLIB_DIR/tabix $HTSLIB_DIR/htsfile /usr/local/bin/ &&     rm -rf /root/.cpanm" did not complete successfully: exit code: 1

**Comment by vpoten** [comment]
The content of /root/.cpanm/work/1698671110.1188/build.log is here:
[build.log](https://github.com/Ensembl/ensembl-vep/files/13215997/build.log)

As you can see MySql 8 is required by DBD::mysql

**Comment by nakib103** [comment]
Hello @vpoten,

Thanks for your query!

The error is coming from a perl library called DBD::mysql. The dockerfile is trying to install the latest version (5.002) which has beed released recently and failing. I was trying to re-produce the issue but for my case it always tries to install the older version (4.050) which does not have the problem.

Can you share me the command you use to build the docker image?

Best regards,
Nakib

**Comment by vpoten** [comment]
Hi @nakib103,

The command I run was:

`docker build . -f dockerfile_vep --no-cache -t registry.mydomain.local:5000/ensembl/ensembl-vep:latest`

the `dockerfile_vep` is a copy of `docker/Dockerfile`

**Comment by vpoten** [comment]
Hi @nakib103 

Seems they did something related to the error in the parent project (ensembl):
https://github.com/Ensembl/ensembl/pull/669

**Comment by nakib103** [comment]
Hi @vpoten ,

Thanks for pointing that out. This is probably why I am unable to re-generate the issue. This PR should also fix the issue you were having. Can you verify that and see if your docker build is working now?

Best regards,
Nakib

**Comment by nakib103** [comment]
Thanks for confirming!
I will close this issue, but you face any further problem please feel free to open a new one.
