### ISSUE TITLE
Annotation Failed due to lack of device space - any way to restart from where it left off?

### ISSUE THREAD

**Issue by sharra44** [Ensembl/ensembl-vep#1547]
I am running a vep command for a very large vcf(around 12.5gb compressed) with the following options:
```
vep \
--cache \
--merged \
--fork 4 \
--dir_cache /root/.vep \
--species homo_sapiens \
--input_file {file} \
--format vcf \
--output_file {file} \
--no_stats \
--force_overwrite \
--assembly GRCh38 \
--af_gnomadg \
--symbol \
--variant_class \
--fasta /home/centos/fasta/Homo_sapiens_assembly38.fasta \
--check_ref \
--buffer_size 5000 \
--flag_pick \
--check_ref \
--offline \
--vcf &
```
The annotation failed about 30 days in due to the ec2 it was running on running out of space, which has since been remedied.
Is there a way to start the annotation again from where it left off or do I need to run the entire process again?

**Comment by nakib103** [comment]
Hello @sharra44 ,

Thanks for your query and sorry to hear that happened!

Unfortunately there is no direct way of resuming the run from VEP itself. 

But you can try checking how much the run have progressed through from the last lines of your output file and start another run with only the input variants that have not been processed. Later you can merge the two output VCF files with any standard text file editing tools.

I would also like to bring your attention to `nextflow-vep` - https://github.com/Ensembl/ensembl-vep/tree/release/110/nextflow, which uses [Nextflow](https://www.nextflow.io/) to run VEP. It divides the input file into smaller chunks and run each of them in parallel. It should be faster and Nextflow have default capability to resume a run (see - [here](https://www.nextflow.io/docs/latest/cache-and-resume.html)).

Hope that helps!

Best regards,
Nakib

**Comment by nakib103** [comment]
Hello @sharra44 , I am closing this ticket. Feel free to open another one if you face further issues.

Best regards,
Nakib
