### ISSUE TITLE
filter_vep can not filter HGVSc or HGVSp

### ISSUE THREAD

**Issue by conanyangqun** [Ensembl/ensembl-vep#155]
Hi, vep team.
I am using vep to annotate VCF file and filter_vep to filter. When I use vep in cache mode to annotate , everything is ok. But when I use filter_vep to filter hgvsc, it gives no result. The command is `filter_vep -i 1_anno.tsv -o test_FilteredAnno.tsv --filter 'HGVSc in test_hgvsc.txt'`. test_hgvsc.txt file contains HGVSc info from 1_anno.tsv.
The vep verison in 1_anno.tsv is `ENSEMBL VARIANT EFFECT PREDICTOR v90.9`.
Hope your reply.

**Comment by sarahhunt** [comment]
Hi @conanyangqun, 

The syntax you need is:
filter_vep -i 1_anno.tsv -o test_FilteredAnno.tsv --filter "exists(HGVSc)"

There is full documentation here:
http://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html#filter_write

**Comment by conanyangqun** [comment]
Hi, @sarahhunt 
Thanks for reply.
I did not make myself clear. I have a target file named target_hgvsc.txt, containing a set of hgvsc mutations. I use vep to annotate sample 1 and get the anno in 1_anno.tsv. I want to find whether the mutations in 1_anno.tsv  are in target_hgvsc.txt file. So, I think the syntax is `filter_vep -i 1_anno.tsv -o test_FilteredAnno.tsv --filter 'HGVSc in target_hgvsc.txt'`. But it seems that no mutations pass, even if I extract some HGVSc from 1_anno.tsv to make target_hgvsc.txt file.

**Comment by sarahhunt** [comment]
Hi @conanyangqun,

Thanks for the additional detail and apologies for the missunderstanding. This is now fixed in the e!92 branch which will be live in the first week in April. The cache files are not yet available for e!92, so you cannot simply switch releases, but if you would like to apply the fix to your local checkout it is here:  

https://github.com/Ensembl/ensembl-vep/pull/157/files

**Comment by conanyangqun** [comment]
Hi, @sarahhunt 
OK. Thanks for all your work. I am waiting for the new cache files and the new release.
