### ISSUE TITLE
Duplicated lines in output VCF with plugin dbNSFP

### ISSUE THREAD

**Issue by leedchou** [Ensembl/ensembl-vep#1550]
## Describe the issue
I found duplicated annotations for each of the variants in output, and some of the `Consequence` are not the same for each variant.

![image](https://github.com/Ensembl/ensembl-vep/assets/44693576/735a2bb9-6748-4124-b5dd-68528edc8991)

### System
- VEP version: 110
- VEP Cache version: 110
- OS: CentOS

### Full VEP command line
```
vep \
        --offline --cache \
        --format vcf --fork 8 \
        --compress_output bgzip \
        --force_overwrite \
        --dir_cache $vep_data_dir \
        -i $input \
        -o $output \
        --plugin dbNSFP,$plu_data_dir/dbNSFP4.4a_grch37.gz,$dbnsfp_str \
        --fasta $reference --assembly GRCh37 \
        --shift_3prime 1 --no_escape --show_ref_allele --check_existing \
        --exclude_predicted --canonical --tab --fields $fields_str
```

**Comment by dglemos** [comment]
Hi @leedchou,
VEP predicts a consequence for each feature (transcript). 
I can't see the column 'Feature' in your output, did you remove it after the annotation or is it missing from the VEP output?

From your example, the variant rs142558220 is predicted to be:
- downstream_gene_variant for transcript ENST00000327044 (gene ENSG00000188976)
- synonymous_variant for transcript ENST00000341065 (gene ENSG00000187634)
- non_coding_transcript_exon_variant for transcript ENST00000474461 (gene ENSG00000187634)
- etc.

**Comment by leedchou** [comment]
Thank you @dglemos 

I didn't add 'Feature' in output. Now I can see it, but I don't know the difference between column "Gene" and column "Feature".

**Comment by dglemos** [comment]
On this page you can find a list of output columns and their description: https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#defaultout
'Gene': Ensembl stable ID of the affected gene
'Feature': Ensembl stable ID of the feature
The Feature can be Transcript, RegulatoryFeature or MotifFeature. There is another column 'Feature type' that says which type it is.

**Comment by leedchou** [comment]
Thank you @dglemos, I really appreciate it.

**Comment by dglemos** [comment]
Glad I could help.
I'm going to close this issue but if you have more questions please feel free to re-open it.

Best wishes,
Diana
