### ISSUE TITLE
HGVSp URI Encoding for synonymous mutations 

### ISSUE THREAD

**Issue by kokul-atx** [Ensembl/ensembl-vep#1552]
This URI encode seems unnecessary and creates issues with the VEP output in both vcf and tab delimited format.

Is there a specific reason why this encoding is necessary.

```
# URI encode "="
$hgvs_p =~ s/\=/\%3D/g if $hgvs_p && !$self->{no_escape};
```

https://github.com/Ensembl/ensembl-vep/blob/1066f6836fd10163f995424728a92dc899711de6/modules/Bio/EnsEMBL/VEP/OutputFactory.pm#L1632

**Comment by dglemos** [comment]
According to the [VCF specifications](https://samtools.github.io/hts-specs/VCFv4.2.pdf)
> INFO - additional information: (String, no whitespace, semicolons, or equals-signs permitted; commas are
> permitted only as delimiters for lists of values)

Equals signs are not permitted in the INFO field this is why by default, VEP URI escapes HGVS strings but you can change this behaviour with the option [--no_escape](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_no_escape)

Let me know if you have more questions.

Best wishes,
Diana

**Comment by dglemos** [comment]
I'm going to close this issue but feel free to open a new one if you have more questions.

Best wishes,
Diana
