### ISSUE TITLE
Issues with perlbrew, mysql during installation

### ISSUE THREAD

**Issue by Acetyl-ZHOU** [Ensembl/ensembl-vep#1553]
Hello,

I am facing a list issues while running VEP installations. Below are the installations I made and I have also mentioned the errors followed by that.

```
gcc -v

#Perlbrew
curl -L http://install.perlbrew.pl | bash
echo 'source $HOME/perl5/perlbrew/etc/bashrc' >> ~/.bash_profile
source ~/perl5/perlbrew/etc/bashrc
cd '/Users/huizhou/perl5' 
perlbrew install -j 5 --as 5.26.2 --thread --64all -Duseshrplib perl-5.26.2 --notest
perlbrew switch 5.26.2
perlbrew install-cpanm

#Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/huizhou/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"
brew

#xz
brew install xz

#MySQL
brew install mysql
cpanm DBI
cpanm DBD::mysql
echo 'export PATH="/usr/local/opt/mysql@8.0/bin:$PATH"' >> /Users/huizhou/.zprofile
echo 'export PATH="/usr/local/opt/mysql@8.1.0/bin:$PATH"' >> /Users/huizhou/.zprofile
echo 'export PATH="/Users/huizhou/perl5/perlbrew/perls/5.26.2/lib/site_perl/5.26.2/darwin-thread-multi-2level/DBD/mysql.pm:$PATH"' >> /Users/huizhou/.zprofile


#Installing BioPerl
curl -O https://cpan.metacpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.6.924.tar.gz
tar zxvf BioPerl-1.6.924.tar.gz
echo 'export PERL5LIB=${PERL5LIB}:##PATH_TO##/bioperl-1.6.924' >> ~/.bash_profile

#Final Dependancies
cpanm Test::Differences Test::Exception Test::Perl::Critic Archive::Zip PadWalker Error Devel::Cycle Role::Tiny::With Module::Build
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib/:$DYLD_LIBRARY_PATH
export PERL5LIB=$PERL5LIB:$HOME/perl5

Perform annotations in perl5/ensembl-vep/
nano ~/.bash_profile
source ~/.bash_profile

```

1.  When running `perlbrew switch 5.26.2`, it says `ERROR: The installation "5.26.2" is unknown.`. Please help with that.
2. While installing `cpanm DBD::mysql` , I get `Building and testing DBD-mysql-5.002 ... FAIL` . I am not sure if there is any problem with the version and how to solve it.
3. Due to these above errors, when running VEP, I get 
```
Can't locate Bio/EnsEMBL/Registry.pm in @INC (you may need to install the Bio::EnsEMBL::Registry module) (@INC contains: /Users/huizhou/ensembl-vep/modules /Users/huizhou/ensembl-vep /Users/huizhou/perl5 ##PATH_TO##/bioperl-1.6.924 /Library/Perl/5.30/darwin-thread-multi-2level /Library/Perl/5.30 /Network/Library/Perl/5.30/darwin-thread-multi-2level /Network/Library/Perl/5.30 /Library/Perl/Updates/5.30.3 /System/Library/Perl/5.30/darwin-thread-multi-2level /System/Library/Perl/5.30 /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level /System/Library/Perl/Extras/5.30) at /Users/huizhou/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 58.
BEGIN failed--compilation aborted at /Users/huizhou/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 58.
Compilation failed in require at /System/Library/Perl/5.30/base.pm line 137.
	...propagated at /System/Library/Perl/5.30/base.pm line 159.
BEGIN failed--compilation aborted at /Users/huizhou/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm line 56.
Compilation failed in require at /System/Library/Perl/5.30/base.pm line 137.
	...propagated at /System/Library/Perl/5.30/base.pm line 159.
BEGIN failed--compilation aborted at /Users/huizhou/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 71.
Compilation failed in require at ./vep line 20.
BEGIN failed--compilation aborted at ./vep line 20.
```

Could you please help out with these errors?

Thanks in advance

Best,
Hui

**Comment by olaaustine** [comment]
Hi @Acetyl-ZHOU 
Hope this meets you well? 
Please can you let us know what macOS version you are using and also what mysql version you have? 
Thank you 
Ola.

**Comment by Acetyl-ZHOU** [comment]
Thanks for your response @olaaustine . 

macOS version: 13.5
mysql  Ver: 8.0.34

**Comment by Acetyl-ZHOU** [comment]
Also when I give cpanm DBD::mysql                                                                       

I get the below error
--> Working on DBD::mysql
Fetching http://www.cpan.org/authors/id/D/DV/DVEEDEN/DBD-mysql-5.002.tar.gz ... OK
Configuring DBD-mysql-5.002 ... OK
Building and testing DBD-mysql-5.002 ... FAIL
! Installing DBD::mysql failed. See /Users/huizhou/.cpanm/work/1699879284.96936/build.log for details. Retry with --force to force install it.

**Comment by olaaustine** [comment]
Hi @Acetyl-ZHOU, 
Thank you for your response. 
Can you try installing the version  DBD::mysql 4.050
The latest version has some issues installing.
Thank you 
Ola.

**Comment by olaaustine** [comment]
You can try a manual installation as stated in this [docs ](https://metacpan.org/pod/DBD::mysql::INSTALL#Manual-installation). 
or ` cpanm https://cpan.metacpan.org/authors/id/D/DV/DVEEDEN/DBD-mysql-4.050.tar.gz`
Let us know if this works. 
Thank you
Ola.

**Comment by Acetyl-ZHOU** [comment]
I tried this command:
cpanm https://cpan.metacpan.org/authors/id/D/DV/DVEEDEN/DBD-mysql-4.050.tar.gz

the output:

**Comment by Acetyl-ZHOU** [comment]
Sorry, closed by mistake. The issue is still open

**Comment by olaaustine** [comment]
Hi @Acetyl-ZHOU, 
Can you try the manual installation 
`wget http://www.cpan.org/modules/by-module/DBD/DBD-mysql-4.050.tar.gz`
and please follow the instructions as stated [here](https://metacpan.org/pod/DBD::mysql::INSTALL#Manual-installation).
Thank you
Ola.

**Comment by Acetyl-ZHOU** [comment]
I used the following commands:
wget http://www.cpan.org/modules/by-module/DBD/DBD-mysql-4.050.tar.gz
tar -xf DBD-mysql-4.050.tar.gz 
perl Makefile.PL
make

When using make command, I get this output. Not sure if its an error
Skip blib/lib/DBD/mysql.pm (unchanged)
Skip blib/lib/DBD/mysql/GetInfo.pm (unchanged)
Skip blib/lib/DBD/mysql/INSTALL.pod (unchanged)
Skip blib/lib/Bundle/DBD/mysql.pm (unchanged)
Running Mkbootstrap for mysql ()
chmod 644 "mysql.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- mysql.bs blib/arch/auto/DBD/mysql/mysql.bs 644
cc -c  -I/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/DBI -I/opt/homebrew/Cellar/mysql/8.1.0/include/mysql -DDBD_MYSQL_WITH_SSL -g  -g -pipe -DPERL_USE_SAFE_PUTENV -Os   -DVERSION=\"4.050\" -DXS_VERSION=\"4.050\"  -iwithsysroot "/System/Library/Perl/5.30/darwin-thread-multi-2level/CORE"   dbdimp.c
In file included from dbdimp.c:15:
./dbdimp.h:20:10: fatal error: 'DBIXS.h' file not found
#include <DBIXS.h>  /* installed by the DBI module                        */
         ^~~~~~~~~
1 error generated.
make: *** [dbdimp.o] Error 1

**Comment by olaaustine** [comment]
Hi, 
What perl version are you using please? 
`perl -v`

**Comment by Acetyl-ZHOU** [comment]
This is perl 5, version 30, subversion 3 (v5.30.3) built for darwin-thread-multi-2level

**Comment by olaaustine** [comment]
Hi, 
Can you check this 
`find /Library/Developer/CommandLineTools -name DBIXS.h`

**Comment by Acetyl-ZHOU** [comment]
```
/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/DBI/DBIXS.h
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/DBI/DBIXS.h
/Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/DBI/DBIXS.h
/Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/System/Library/Perl/Extras/5.34/darwin-thread-multi-2level/auto/DBI/DBIXS.h
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/DBI/DBIXS.h
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Perl/Extras/5.18/darwin-thread-multi-2level/auto/DBI/DBIXS.h
```

**Comment by olaaustine** [comment]
Can you try this when you do 
`perl Makefile.PL -I /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk//System/Library/Perl/5.30/darwin-thread-multi-2level/auto`
Let us know if this helps

**Comment by olaaustine** [comment]
Should be.
perl Makefile.PL --cflags='-I /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk//System/Library/Perl/5.30/darwin-thread-multi-2level/auto'

**Comment by Acetyl-ZHOU** [comment]
```
I will use the following settings for compiling and testing:

  cflags        (User's choice) = -I /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk//System/Library/Perl/5.30/darwin-thread-multi-2level/auto
  embedded      (guessed      ) = 
  ldflags       (guessed      ) = 
  libs          (mysql_config ) = -L/opt/homebrew/Cellar/mysql/8.1.0/lib -lmysqlclient -lz -lzstd -L/opt/homebrew/lib -lssl -lcrypto -lresolv
  mysql_config  (Users choice ) = mysql_config
  nocatchstderr (default      ) = 0
  nofoundrows   (default      ) = 0
  nossl         (default      ) = 0
  testdb        (User's choice) = test
  testhost      (default      ) = 
  testpassword  (default      ) = 
  testport      (default      ) = 
  testsocket    (default      ) = 
  testuser      (User's choice) = huizhou

To change these settings, see 'perl Makefile.PL --help' and
'perldoc DBD::mysql::INSTALL'.

Checking if libs are available for compiling...
Looks good.

Warning (mostly harmless): No library found for -lz
Warning (mostly harmless): No library found for -lzstd
Warning (mostly harmless): No library found for -lresolv
Using DBI 1.643 (for perl 5.030003 on darwin-thread-multi-2level) installed in /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/DBI/
Generating a Unix-style Makefile
Writing Makefile for DBD::mysql
Writing MYMETA.yml and MYMETA.json

```

**Comment by Acetyl-ZHOU** [comment]
Thanks. I think it worked. So, what should be done next?

**Comment by olaaustine** [comment]
You need to finish the manual installation steps.

**Comment by Acetyl-ZHOU** [comment]
After this, when I code make

"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- mysql.bs blib/arch/auto/DBD/mysql/mysql.bs 644
cc -c  -I/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/DBI -I /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk//System/Library/Perl/5.30/darwin-thread-multi-2level/auto -DDBD_MYSQL_WITH_SSL -g  -g -pipe -DPERL_USE_SAFE_PUTENV -Os   -DVERSION=\"4.050\" -DXS_VERSION=\"4.050\"  -iwithsysroot "/System/Library/Perl/5.30/darwin-thread-multi-2level/CORE"   dbdimp.c
In file included from dbdimp.c:15:
./dbdimp.h:20:10: fatal error: 'DBIXS.h' file not found
#include <DBIXS.h>  /* installed by the DBI module                        */
         ^~~~~~~~~
1 error generated.
make: *** [dbdimp.o] Error 1


I get this error.

**Comment by Acetyl-ZHOU** [comment]
Hi, could you please give a solution for this?

**Comment by olaaustine** [comment]
Hi @Acetyl-ZHOU,

We have documentation for installing VEP dependencies on Mac [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#macos). Pleas follow the steps if you want a local installation. 
We also have a docker image and documentation on how to run VEP in docker [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker). We also have a singularity image, a blogpost on how to this is [here](https://www.ensembl.info/2021/05/24/cool-stuff-the-vep-can-do-singularity/)

Let us know if this helps. 
Thank you 
Ola.
