### ISSUE TITLE
Option --no-escape doesn't work for custom annotation

### ISSUE THREAD

**Issue by KevinMer** [Ensembl/ensembl-vep#1555]
## Describe the issue
Hello, 

I'm currently using custom annotation to retrieve upstream variant annotation.
My custom annotation is a clinvar vcf that I processed to add p. informations from NCBI database.

I saw in options that --no-escape allows to deal with some annotations character (such as equal sign).
However, I can see in my output vcf that equal sign is escaped for the custom annotation but not for the annotations retrieved from the cache.

I am using a singularity image with vep installed.

Do --no-escape option only work for cache annotation ?
Is there a way to prevent escape for custom annotation ?

You can find in attachment a short example of my custom annotation and the corresponding input vcf.

Thanks for your help.

Kevin

### System
- VEP version: 110
- VEP Cache version: 110
- Perl version: 5.26.1
- OS: CentOS
- tabix installed ? : yes

### Full VEP command line
```
vep 
--dir_cache /cache/dir 
--cache_version 110 
--format vcf 
--cache 
--refseq 
--offline 
--fasta /path/to/hg19_base.fa 
--hgvs 
--hgvsp_use_prediction 
--no_escape 
--custom file=custom.vcf.gz,short_name=ClinVar,format=vcf,type=exact,coords=0,fields=CLNHGVS%CLNHGVS_P 
-i input.vcf
-o output.vcf
```

### Data files (if applicable)
They include:
- The input file : yes
- The output file : yes
- The custom file(s) : yes
[issueNoEscape.tar.gz](https://github.com/Ensembl/ensembl-vep/files/13347206/issueNoEscape.tar.gz)

**Comment by likhitha-surapaneni** [comment]
Hi @KevinMer,

Currently,` --no_escape` is possible for HGVSp output field but not custom fields. Please let us know if this answers your question.

Kind regards,
Likhitha

**Comment by KevinMer** [comment]
Hi @likhitha-surapaneni,

thanks for your answer.

Is there a trick I could use to keep the string integrity of the custom annotation ? 
I tried to replace all "=" by "\=" in order to avoid string escaping but it didn't work.

Would you have an idea to bypass this issue ?

Best regards,
Kevin

**Comment by likhitha-surapaneni** [comment]
Hi @KevinMer ,

I am afraid it may not be possible to keep the string integrity for custom annotation fields. We have plans of extending `--no-_escape` for HGVS strings in custom annotation fields in our coming releases. 

Kind regards,
Likhitha

**Comment by likhitha-surapaneni** [comment]
Hi @KevinMer , this is not in our immediate plans and hence I am closing this ticket for now. Please feel free to open a new issue if you have any further questions.
