### ISSUE TITLE
Cannot use format bigwig without Bio::DB::BigFile module installed

### ISSUE THREAD

**Issue by lqr131115** [Ensembl/ensembl-vep#1556]
## Describe the issue
I install vep108 from [Ensembl Vep :: Anaconda.org](https://anaconda.org/bioconda/ensembl-vep)， and install `Bio::DB::BigFile` successfully, 
![image](https://github.com/Ensembl/ensembl-vep/assets/68832962/51e8f47d-facd-4986-817d-302f3185ff5c)
When I do vep , I get an error:
![image](https://github.com/Ensembl/ensembl-vep/assets/68832962/852657a3-34dc-4a01-ad52-ac729d43320d)

I wonder what are the possible reasons for this phenomenon

Thanks for your help
Lqr

### System
- VEP version: 108 
- VEP Cache version: 108
- Perl version: 5.32.1
- OS: WSL ( Ubuntu )

**Comment by likhitha-surapaneni** [comment]
Hi @lqr131115 ,

From the error message, it seems like the perl environment used by VEP is different from the one where the module is installed. That being said, we do not support conda installs of VEP as they are not packages created by us. It is recommended to reach out to the creator of the package for any issues related to the conda package.

Alternatively, we provide containerised options to run VEP using [docker](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker) and [singularity](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#singularity).

Kind regards,
Likhitha

**Comment by likhitha-surapaneni** [comment]
Hi @lqr131115 , I want to add that you may also want to check the following [instructions](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#bigfile) to install `Bio::DB::BigFile`.

**Comment by lqr131115** [comment]
Hi @likhitha-surapaneni ，

Thank for your reply. I tried to do vep by  `singularity`, and another error appear:
![image](https://github.com/Ensembl/ensembl-vep/assets/68832962/c4fa9c88-6e06-4434-b412-5bfe57b3291d)

I am the dir `/homo_sapiens_refseq` is exist ,  so what should I do?

And here my vep command:
```
singularity exec vep.sif vep --input_file positive.sample.ipt.test.vcf --format vcf --output_file positive.sample.opt.test.vcf --vcf --sift s --polyphen s --numbers --symbol --shift_3prime 1 --allele_number --refseq --total_length --no_stats --offline --cache --dir_cache /mnt/g/vep108_dependency/cache_data/GRCh38 --species "homo_sapiens" --assembly GRCh38 --fork 4 --dont_skip --allow_non_variant --use_given_ref --exclude_predicted --flag_pick_allele --plugin Grantham --plugin SpliceAI,snv=/mnt/g/capice_dependency/capice/require_data/spliceai_scores.masked.snv.hg38.vcf.gz,indel=/mnt/g/capice_dependency/capice/require_data/spliceai_scores.masked.indel.hg38.vcf.gz --custom "/mnt/g/capice_dependency/capice/require_data/gnomad.genomes.v3.1.2.sites.stripped.vcf.gz,gnomAD,vcf,exact,0,AF,HN" --custom "/mnt/g/capice_dependency/capice/require_data/hg38.phyloP100way.bw,phyloP,bigwig,exact,0" --dir_plugins /mnt/g/capice_dependency/capice/vep_plugins --force_overwrite 

```
Best wishes,
Lqr

**Comment by likhitha-surapaneni** [comment]
Hi @lqr131115,

Glad that the issue got resolved. I am closing this ticket for now. Please feel free to open a new ticket if you have any further issues.

Kind regards,
Likhitha
