### ISSUE TITLE
Multiple Output Formats

### ISSUE THREAD

**Issue by Maryam-May** [Ensembl/ensembl-vep#1558]
Running command line VEP in a pipeline only allows a single output format to be specified (`tsv`, `json`, `vcf`, and the default). However, some downstream tools require the VEP file to be in one particular format or another. It would be convenient to allow the VEP program to produce multiple output files in different formats if requested, rather than other solutions such as rerunning VEP or attempting to convert one format to another (which can be error-prone).

**Comment by likhitha-surapaneni** [comment]
Hi @Maryam-May,

If you are looking to convert one format to the other, please also take a look at https://github.com/Ensembl/ensembl-vep/issues/346. If you are looking for a way to generate output in multiple formats at the same time, I can discuss with the team and get back to you.
 
Thanks,
Likhitha

**Comment by Maryam-May** [comment]
Hello, thank you for your response.

I believe that allowing VEP to produce multiple output formats at once would still be useful as the solutions in #346 rely on scripts that may break on VEP adjusting its output formats.

There are also small differences between output formats, for example I've run VEP 109 on the same file twice, once with `-tab` enabled and once with `-vcf` enabled, and the `gnomad3` field between them has differences such as `chr1:12345678-12345678,12345677` (tab) vs `chr1:12345678-12345678&12345677` (vcf). Additionally, the position of indels in the tab format tends to be 1 higher than the position reported in the vcf format.

These are minor differences of course but these small details, which may need to be accounted for when converting between formats, are easy to miss. Format conversion tools may fail silently if they expect certain characters or positions.

Enabling VEP to produce multiple formats at once would avoid this issue in pipelines when downstream tools require different formats.

**Comment by likhitha-surapaneni** [comment]
Hi @Maryam-May,
Thank you for the details. Unfortunately, this is not in our immediate priorities but we will try to include this in the future implementations of VEP. I am closing this ticket for now. Please feel free to open a new issue in case of any other questions
