### ISSUE TITLE
All my variants annotated as intergenic_variant

### ISSUE THREAD

**Issue by xiucz** [Ensembl/ensembl-vep#1559]
## Describe the issue
After updating to VEP110 from VEP105, All my variants were annotated as intergenic_variant type.
C
```
#INSTALL STEP
1. download github vep release and unzip ,
mkdir ensembl-vep-release-110/src/ && cd ensembl-vep-release-110/src/
2. and then download perl  module from github to `ensembl-vep-release-110/src/`. I dont install or update the perl module via  INSTALL.pl
```
![image](https://github.com/Ensembl/ensembl-vep/assets/12706146/658a71f2-7908-4ea4-b025-caf2016424e7)

![image](https://github.com/Ensembl/ensembl-vep/assets/12706146/717d7d25-d5d2-4e1c-a703-eb9445ecd878)

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 110
- VEP Cache version: [110]
- Perl version: perl-5.32.1
- OS: Centos
- tabix installed ? YES

### Full VEP command line
```
~/ensembl-vep-release-110/vep -cache --refseq \
--force_overwrite --fork 8 --offline --tab  --canonical \
--pubmed --use_given_ref --hgvs --transcript_version --no_escape  \
--dir_cache ~/database/hg38/vep110db --dir_plugins \
~/vep/ensembl-vep_105/ensembl-vep/Plugins --species homo_sapiens --assembly=GRCh38 --fasta ~/hg38/gatk_bundle/Homo_sapiens_assembly38.fasta --format vcf -input_file hg38_multianno.vcf -o hg38_multianno.vep.txt

**Smartmatch is experimental at ~/ensembl-vep-release-110/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 472.**

```
Best,
xiucz

**Comment by olaaustine** [comment]
Hi @xiucz, 
Hope you are well? 
It looks like there might be some issues with the installation. Can you please ensure that the required packages and dependencies mentioned in the [docs](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#installer) are installed as well?
We also have a docker image and documentation on how to run VEP in docker [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker). We also have a singularity image, a blogpost on how to this is [here](https://www.ensembl.info/2021/05/24/cool-stuff-the-vep-can-do-singularity/)
Please let us lknow if this helps. 
Thank you 
Ola

**Comment by olaaustine** [comment]
Hi @xiucz, 
Hope you are well? 
I will close this issue now.
Please feel free to reopen another ticket if you have another issue.
Thank you
Ola.
