### ISSUE TITLE
POST query fails even if there is a single invalid input

### ISSUE THREAD

**Issue by onursumer** [Ensembl/ensembl-vep#156]
When querying http://grch37.rest.ensembl.org/vep/human/hgvs API with multiple values, the query results with an error even if there is just one invalid input. For example this input fails even if there are 2 valid notations there: 
```JavaScript
{ "hgvs_notations" : ["AGT:c.803T>C", "9:g.22125503G>C" , "invalid_hgvs_notation"] }
```

Instead of failing the whole request, it would be more useful to return the annotations for the valid ones, and maybe return individual error messages for each failing input.

**Comment by aparton** [comment]
Hi Onur,

Thank you for your enquiry. This behaviour should currently be within the HGVS POST endpoint for REST VEP, can you please provide me with the error message that you are receiving when you try to do this?

Kind Regards,
Andrew

**Comment by onursumer** [comment]
Hi Andrew,

Seems like I only get the error message when the first notation is invalid.

So, actually `{ "hgvs_notations" : ["AGT:c.803T>C", "9:g.22125503G>C" , "invalid_hgvs_notation"] }` works fine, but `{ "hgvs_notations" : ["invalid_hgvs_notation", "AGT:c.803T>C", "9:g.22125503G>C"] }` returns this error message:

```JavaScript
{
    "error": "No variant found with ID 'invalid_hgvs_notation'"
}
```

Thanks,
Onur

**Comment by aparton** [comment]
Hi Onur,

Thanks for this, I'll take a look and be back in touch shortly.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi Onur, 

We’re looking into this issue and we are aiming to have a fix in for the release of Ensembl v92, currently scheduled for early April. However, in the meantime, as a workaround if you provide a correctly formatted HGVS string as the first value in your input array, then everything should work as normal from there.

Kind Regards,
Andrew
