### ISSUE TITLE
Compress::Raw::Zlib version 2.201 required--this is only version 2.105

### ISSUE THREAD

**Issue by Acetyl-ZHOU** [Ensembl/ensembl-vep#1568]
I have a problem in running.
`Compress::Raw::Zlib version 2.201 required--this is only version 2.105 at /Users/huizhou/anaconda3/envs/allelic/lib/perl5/site_perl/Compress/Zlib.pm line 11.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/lib/perl5/site_perl/Compress/Zlib.pm line 11.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/ProteinFunctionPredictionMatrix.pm line 83.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/ProteinFunctionPredictionMatrix.pm line 83.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 74.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 74.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/TranscriptVariation.pm line 68.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/TranscriptVariation.pm line 68.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/DBSQL/TranscriptVariationAdaptor.pm line 89.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/DBSQL/TranscriptVariationAdaptor.pm line 89.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/VariationFeature.pm line 112.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/VariationFeature.pm line 112.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm line 89.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm line 89.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 59.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 59.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/lib/perl5/site_perl/base.pm line 100.
	...propagated at /Users/huizhou/anaconda3/envs/allelic/lib/perl5/site_perl/base.pm line 109.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/modules/Bio/EnsEMBL/VEP/BaseRunner.pm line 56.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/lib/perl5/site_perl/base.pm line 100.
	...propagated at /Users/huizhou/anaconda3/envs/allelic/lib/perl5/site_perl/base.pm line 109.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/modules/Bio/EnsEMBL/VEP/Runner.pm line 71.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/bin/vep line 20.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/bin/vep line 20.`

**Comment by nuno-agostinho** [comment]
Hi @Acetyl-ZHOU,

Are you having some issue when running VEP in the command line? Based on the error message, you need to update your [Compress::Raw::Zlib](https://metacpan.org/pod/Compress::Raw::Zlib). Please tell me if you find any other issues.

Thanks,
Nuno

**Comment by Acetyl-ZHOU** [comment]
Hi, could you please tell how to update to version 2.201?

**Comment by nuno-agostinho** [comment]
Hey @Acetyl-ZHOU,

You may find installation instructions in the CPAN page for the package: https://metacpan.org/pod/Compress::Raw::Zlib

If you are having issues installing VEP dependencies, you may also want to consider using our [official Docker image](https://hub.docker.com/r/ensemblorg/ensembl-vep) instead.

Thanks,
Nuno

**Comment by Acetyl-ZHOU** [comment]
yes,#1569also is my issue. This is VEP 110. and I have issue of #1568.When I change VEP105, I have issue of #1569 . And with your help, I can use VEP 105 finish my work.

**Comment by Acetyl-ZHOU** [comment]
yes ,still have issue with VEP110.such as :`vep -i /Users/huizhou/Documents/allelic/RNA-allele-expression/DKR2_RNA.filter.vcf -o /Users/huizhou/Documents/allelic/RNA-allele-expression/DKR2_vep.vcf --vcf --dir_cache /Users/huizhou/Documents/allelic/110 --force_overwrite --no_check_variants_order --cache  `

and it will have issue
`Compress::Raw::Zlib version 2.201 required--this is only version 2.105 at /Users/huizhou/anaconda3/envs/allelic/lib/perl5/site_perl/Compress/Zlib.pm line 11.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/lib/perl5/site_perl/Compress/Zlib.pm line 11.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/ProteinFunctionPredictionMatrix.pm line 83.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/ProteinFunctionPredictionMatrix.pm line 83.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 74.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 74.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/TranscriptVariation.pm line 68.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/TranscriptVariation.pm line 68.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/DBSQL/TranscriptVariationAdaptor.pm line 89.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/DBSQL/TranscriptVariationAdaptor.pm line 89.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/VariationFeature.pm line 112.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/VariationFeature.pm line 112.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm line 89.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm line 89.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 59.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 59.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/lib/perl5/site_perl/base.pm line 100.
	...propagated at /Users/huizhou/anaconda3/envs/allelic/lib/perl5/site_perl/base.pm line 109.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/modules/Bio/EnsEMBL/VEP/BaseRunner.pm line 56.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/lib/perl5/site_perl/base.pm line 100.
	...propagated at /Users/huizhou/anaconda3/envs/allelic/lib/perl5/site_perl/base.pm line 109.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/share/ensembl-vep-110.1-0/modules/Bio/EnsEMBL/VEP/Runner.pm line 71.
Compilation failed in require at /Users/huizhou/anaconda3/envs/allelic/bin/vep line 20.
BEGIN failed--compilation aborted at /Users/huizhou/anaconda3/envs/allelic/bin/vep line 20`

and I try to update zlip but I failed. And I send message to zlib github. They did not answer question.

**Comment by pdiakumis** [comment]
Thought I'll comment since we also stumbled on this with the ensembl-vep v110.1 that comes via bioconda. There are two conda packages for `Compress::Raw::Zlib`, one on bioconda and one on conda-forge:

- https://anaconda.org/bioconda/perl-compress-raw-zlib (most current version: 2.105)
- https://anaconda.org/conda-forge/perl-compress-raw-zlib (most current version: 2.202)

The ensembl-vep package pulls in the one from bioconda for whatever reason (probably gives priority to bioconda packages). So if you want to use the one from conda-forge, you'll have to do:

```
conda install -c conda-forge perl-compress-raw-zlib
```

At least that worked for us. Hope that helps @Acetyl-ZHOU

**Comment by Acetyl-ZHOU** [comment]
Thank you. Can I find SNPID in vep? My data have CHR and position ,and I want to get SNP ID such as :rs75377686. I can find "## dbSNP version 147" in VEP. But I don`t know how to work with it. Can you help me!

**Comment by nakib103** [comment]
Hello @Acetyl-ZHOU,

You can use the option `--check_existing` in VEP which will give you RefSNP ID of known variants in the output. You can find more in the documentation - 
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_check_existing

Best regards,
Nakib

**Comment by nakib103** [comment]
Hello @Acetyl-ZHOU 

I am closing this issue, if you face further problems please feel free to open another one.

Best regards,
Nakib
