### ISSUE TITLE
No cache found for homo_sapiens, version 105

### ISSUE THREAD

**Issue by Acetyl-ZHOU** [Ensembl/ensembl-vep#1569]
I have a problem
`MSG: ERROR: No cache found for homo_sapiens, version 105

STACK Bio::EnsEMBL::VEP::CacheDir::dir /Users/huizhou/anaconda3/envs/a11/share/ensembl-vep-105.0-0/modules/Bio/EnsEMBL/VEP/CacheDir.pm:328
STACK Bio::EnsEMBL::VEP::CacheDir::init /Users/huizhou/anaconda3/envs/a11/share/ensembl-vep-105.0-0/modules/Bio/EnsEMBL/VEP/CacheDir.pm:227
STACK Bio::EnsEMBL::VEP::CacheDir::new /Users/huizhou/anaconda3/envs/a11/share/ensembl-vep-105.0-0/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /Users/huizhou/anaconda3/envs/a11/share/ensembl-vep-105.0-0/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:115
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /Users/huizhou/anaconda3/envs/a11/share/ensembl-vep-105.0-0/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /Users/huizhou/anaconda3/envs/a11/share/ensembl-vep-105.0-0/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /Users/huizhou/anaconda3/envs/a11/share/ensembl-vep-105.0-0/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::run /Users/huizhou/anaconda3/envs/a11/share/ensembl-vep-105.0-0/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel /Users/huizhou/anaconda3/envs/a11/bin/vep:232
Date (localtime)    = Fri Dec  1 11:45:47 2023
Ensembl API version = 105`
but I have download
`homo_sapiens				homo_sapiens_vep_105_GRCh37.tar.gz
`
why it not work?

**Comment by nuno-agostinho** [comment]
Hi @Acetyl-ZHOU,

Can you show me what command you are using to run VEP? If you are using GRCh37 data, don't forget that you need to run VEP with the flag `--assembly GRCh37`.

Best regards,
Nuno

**Comment by Acetyl-ZHOU** [comment]
`vep -i /Users/huizhou/Documents/allelic/RNA-allele-expression/DKR1_RNA.filter.vcf -o /Users/huizhou/Documents/allelic/RNA-allele-expression/DKR1_vep.vcf --vcf --cache --force_overwrite --no_check_variants_order --assembly GRCh37`

I run with '--assembly GRCh37'.but it still have problem the same as last one.
`MSG: ERROR: No cache found for homo_sapiens, version 105

STACK Bio::EnsEMBL::VEP::CacheDir::dir /Users/huizhou/anaconda3/envs/a11/share/ensembl-vep-105.0-0/modules/Bio/EnsEMBL/VEP/CacheDir.pm:328
STACK Bio::EnsEMBL::VEP::CacheDir::init /Users/huizhou/anaconda3/envs/a11/share/ensembl-vep-105.0-0/modules/Bio/EnsEMBL/VEP/CacheDir.pm:227
STACK Bio::EnsEMBL::VEP::CacheDir::new /Users/huizhou/anaconda3/envs/a11/share/ensembl-vep-105.0-0/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /Users/huizhou/anaconda3/envs/a11/share/ensembl-vep-105.0-0/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:115
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /Users/huizhou/anaconda3/envs/a11/share/ensembl-vep-105.0-0/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /Users/huizhou/anaconda3/envs/a11/share/ensembl-vep-105.0-0/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /Users/huizhou/anaconda3/envs/a11/share/ensembl-vep-105.0-0/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::run /Users/huizhou/anaconda3/envs/a11/share/ensembl-vep-105.0-0/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel /Users/huizhou/anaconda3/envs/a11/bin/vep:232
Date (localtime)    = Fri Dec  1 11:54:43 2023
Ensembl API version = 105`

**Comment by nuno-agostinho** [comment]
Hi @Acetyl-ZHOU,

Is your GRCh37 data located in the default cache directory `$HOME/.vep/`? If not, you have to specify the cache directory with argument [`--dir_cache`](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_dir_cache). 

More information about VEP cache can be found in https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache

Best regards,
Nuno

**Comment by nuno-agostinho** [comment]
Hi @Acetyl-ZHOU,

I'm glad it is working for you! I am going to close this issue now.

Have a great day!

Cheers,
Nuno
