### ISSUE TITLE
Why SWISSPROT field contain a number after an accession number in ensembl-vep v 109.3?

### ISSUE THREAD

**Issue by dana00000** [Ensembl/ensembl-vep#1572]
Hello

I am using ensembl-vep version 109.3
The SWISSPROT accession contains `Q9NZK5.167` some numbers after a dot, why is that? If I put this accession number in the UniProtKB database it does not find me, but If I put without it does fint it. This is creating some problems while parsing the output.

**Comment by nakib103** [comment]
Hello @dana00000, 
I am closing this ticket. If you have further problem feel free to open another ticket.

Best regards,
Nakib
