### ISSUE TITLE
VEP in containers. "Chromosome 1 not found in annotation sources..." error

### ISSUE THREAD

**Issue by migrau** [Ensembl/ensembl-vep#1573]
## Describe the issue
If I run this command with the 109 version:
```
singularity exec ensembl-vep_109.sif  vep --dir /workspace/datasets/vep/ -i mini_example.tsv --offline --cache -o miniout2.vcf --species homo_sapiens --assembly GRCh38 --fork 8
```
Runs without errors. 
If I run the same with 110 version: 
```
singularity exec ensembl-vep_110.0.sif vep --dir /workspace/datasets/vep/ -i mini_example.tsv --offline --cache -o miniout2.vcf --species homo_sapiens --assembly GRCh38 --fork 8
```
or 
```
singularity exec ensembl-vep_110.0.sif vep --dir /workspace/datasets/vep/ -i mini_example.tsv --offline --cache -o miniout2.vcf --species homo_sapiens --assembly GRCh38 --fork 8 --fasta 110.0_GRCh38//homo_sapiens/110_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz
```
The output is empty after this terminal message:
```
Smartmatch is experimental at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 472.
WARNING: Line 1 skipped (1   881907    881906    -/C   +): Chromosome 1 not found in annotation sources or synonyms; chromosome 1 does not overlap any features
WARNING: Line 2 skipped (2   946507    946507    G/C   +): Chromosome 2 not found in annotation sources or synonyms; chromosome 2 does not overlap any features
WARNING: Line 3 skipped (5   140532    140532    T/C   +): Chromosome 5 not found in annotation sources or synonyms; chromosome 5 does not overlap any features
WARNING: Line 4 skipped (8   150029    150029    A/T   +    var2): Chromosome 8 not found in annotation sources or synonyms; chromosome 8 does not overlap any features
WARNING: Line 5 skipped (12  1017956   1017956   T/A   +): Chromosome 12 not found in annotation sources or synonyms; chromosome 12 does not overlap any features
WARNING: Line 6 skipped (14  19584687  19584687  C/T   -): Chromosome 14 not found in annotation sources or synonyms; chromosome 14 does not overlap any features
WARNING: Line 7 skipped (19  66520     66520     G/A   +    var1): Chromosome 19 not found in annotation sources or synonyms; chromosome 19 does not overlap any features
```
I downloaded the cache as always:
```
singularity exec ensembl-vep_110.0.sif INSTALL.pl -c 110.0_GRCh38/ -a cf -s homo_sapiens --ASSEMBLY GRCh38
```
I tried with 110.0 and 110.1 with the same results

### System
- VEP version: 109 (OK) , 110.1 (KO), 110.0 (KO)
- VEP Cache version: 109_GRCh38  (OK)  , 110.1 (KO), 110.0 (KO)
- Perl version: v5.26.2
- OS:  Ubuntu 
- tabix installed yes

### Data files (if applicable)
- The input file
$ cat mini_example.tsv 
1   881907    881906    -/C   +
2   946507    946507    G/C   +
5   140532    140532    T/C   +
8   150029    150029    A/T   +    var2
12  1017956   1017956   T/A   +
14  19584687  19584687  C/T   -
19  66520     66520     G/A   +    var1

**Comment by nakib103** [comment]
Hi @migrau,

Thanks for your query!

I tried to re-produce the issue with input that you provided but failed. The issue seems to be with cache - can you try deleting the cache dir and re-downloading it again.

Best regards,
Nakib

**Comment by migrau** [comment]
Hi nakib103, 
I realised it was a problem with the folders hierarchy, maybe something changed in the last versions. In v109, specifying `--dir /workspace/datasets/vep/` works (the v109 cache is in `/workspace/datasets/vep/homo_sapiens/109_GRCh38`). But when downloading the v110,  the folder created `/workspace/datasets/vep/homo_sapiens/110.0_GRCh38` contains two sublevels more: `/workspace/datasets/vep/homo_sapiens/110.0_GRCh38/homo_sapiens/110_GRCh38/`. If I specified this one, vep works correctly.

**Comment by nakib103** [comment]
Hi @migrau,

The cache directory structure is same between 109 and 110 - 
```
$ tar -tf homo_sapiens_vep_109_GRCh38.tar.gz | head -n 4
homo_sapiens/109_GRCh38/
homo_sapiens/109_GRCh38/1/
homo_sapiens/109_GRCh38/1/1-1000000.gz
homo_sapiens/109_GRCh38/1/1-1000000_reg.gz

$ tar -tf homo_sapiens_vep_110_GRCh38.tar.gz | head -n 4
homo_sapiens/110_GRCh38/
homo_sapiens/110_GRCh38/1/
homo_sapiens/110_GRCh38/1/1-1000000.gz
homo_sapiens/110_GRCh38/1/1-1000000_reg.gz
```

And as you can see it has structure such as - `<species>/<version>_<assembly>/<chromosome>/<cache_files>`. So when you gave the `-c 110.0_GRCh38/` in your download command it extracted the cache files with the above folder structure under `/workspace/datasets/vep/homo_sapiens/110.0_GRCh38`.

If you had given `-c /workspace/datasets/vep` than you would expect the cache files under `/workspace/datasets/vep/` same as 109.

Hope that answers your question.

Best regards,
Nakib

**Comment by migrau** [comment]
Thanks, nakin103. I didn't download the tar.gz directly but using the `singularity exec ensembl-vep_110.0.sif INSTALL.pl -c 110.0_GRCh38/ -a cf -s homo_sapiens --ASSEMBLY GRCh38` command, and for some reason, the directory structure inside the downloaded folder is different, as I said. 
`109_GRCh38` contains all the files and folders (e.g. LRG_*, Homo_sapiens.GRCh38.dna.toplevel.fa.gz*) but `110.0_GRCh38` contains two subfolders more `homo_sapiens/110_GRCh38`, before all the files and folders (e.g. LRG_*, Homo_sapiens.GRCh38.dna.toplevel.fa.gz*) 
Anyway, it is solved now, thanks!
