### ISSUE TITLE
gnomad v4 in VEP

### ISSUE THREAD

**Issue by ntm** [Ensembl/ensembl-vep#1574]
Hello devs,

gnomAD v4 was [released ](https://gnomad.broadinstitute.org/news/2023-11-gnomad-v4-0/) in November. I'ld love to get those AFs via VEP! It contains data from both exomes and genomes, so I guess --af_gnomade and --af_gnomadg would become simply --af_gnomad.
You're probably aware of this and maybe already working on it, I'm opening this issue so users like me can track the progress. Thanks!
Regards,
Nicolas

**Comment by davmlaw** [comment]
In the meantime, you can download the gnomAD4 VCFs and use ```--custom```

gnomADv4.0 has both Exome and Genomes, and AFAIK there is no combined score available, so you need to sum the counts and re-calculate the AF if you want them merged

I have some scripts to do this (and cut down the INFO fields to the dozen or so I want) if you want to take a look:

https://github.com/SACGF/variantgrid/blob/master/annotation/annotation_data/generate_annotation/gnomad4.0_download.sh
https://github.com/SACGF/variantgrid/blob/master/annotation/annotation_data/generate_annotation/gnomad_data.py

**Comment by trust-odia** [comment]
Hi @davmlaw 
thank you for this help. I appreciate it.
I tried to run the gnomad_data.py script, I already downloaded the gnomad4 data with the gnomad4.0_download.sh script; but I get syntax error on line 131 in the gnomad_data.py script

"with (open(chrom_script, "w") as cs):
                                              ^
SyntaxError: invalid syntax

I'll appreciate your help

**Comment by jamie-m-a** [comment]
Hi @ntm (and others interested).

We are currently not certain in which version of Ensembl we will update to the latest gnomAD, but it's likely to be 113. We tend not to rush to incorporate the initial major release version (4.0 in this case) because gnomAD typically provide an updated minor version not that long after each major release.

If you want to start using the data before we incorporate it to the cache, you can, as described in this thread, use the `--custom` option to use the latest data (with a bit of pre-parsing to get it in the right shape).

**Comment by ntm** [comment]
Thanks for the info @jamie-m-a , very helpful for planning ahead and deciding our course of action.
While we're talking variant frequencies, any progress on the integration of [ALFA](https://github.com/Ensembl/ensembl-vep/issues/1043), maybe via a plugin as mentioned by @helensch ?
Thanks!

**Comment by trust-odia** [comment]
hi @ntm, were you able to run @davmlaw scripts? I am having issues running them. I'll appreciate you help. Please see my comment above. Thank you.

**Comment by davmlaw** [comment]
Hi @trust-odia - I've removed the outer brackets, which may fix the script (hard to know as it works on my machine)

You may also want to just download them from here:

https://variantgrid.com/download/annotation/VEP/annotation_data/GRCh38/gnomad4.0_GRCh38_combined_af.vcf.bgz
https://variantgrid.com/download/annotation/VEP/annotation_data/GRCh38/gnomad4.0_GRCh38_combined_af.vcf.bgz.tbi

**Comment by mrymkdnz** [comment]
Hello @davmlaw ,
My computer's processor power is not enough to process Gnomad v4 data. If so, can you post links to separate vcfs for exomes and genomes? If you don't have it, that's okay. Thanks for information.

**Comment by davmlaw** [comment]
You don't need to process the data if you just download the already processed/combined VCF in the comment above yours.

VEP should randomly seek inside the VCF so I don't think it should matter much how big the VCF is

If you want to make separate combined VCF files from exomes/genomes, download the individual per-chromosome files from the gnomAD site, then concatenate them, that shouldn't take much processing power either (leaving an old laptop on overnight)

**Comment by trust-odia** [comment]
Hi Dave,

Thank you so much.

From: Dave Lawrence ***@***.***>
Date: Monday, January 1, 2024 at 8:15 PM
To: Ensembl/ensembl-vep ***@***.***>
Cc: Odia, Trust ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [Ensembl/ensembl-vep] gnomad v4 in VEP (Issue #1574)

Hi @trust-odia<https://github.com/trust-odia> - I've removed the outer brackets, which may fix the script (hard to know as it works on my machine)

You may also want to just download them from here:

https://variantgrid.com/download/annotation/VEP/annotation_data/GRCh38/gnomad4.0_GRCh38_combined_af.vcf.bgz
https://variantgrid.com/download/annotation/VEP/annotation_data/GRCh38/gnomad4.0_GRCh38_combined_af.vcf.bgz.tbi

**Comment by trust-odia** [comment]
Hi Dave,

I use the combined gnomad4 data that you sent me (Thank you for this), to run VEP, just only for the AF freq, but the gnomADg_AF column does not have new values.

Please see my command:

vep -i /project/dshared/projects/VEP/chr20_NF.vcf.split.gz --tab -everything --buffer_size 1000 --offline --fork 4 --dir_plugins /project/shared/projects/PMBB_VEP_Annotations --dir_cache /home/todia  --custom file=/project/shared/projects/gnomad4/gnomad4.0_GRCh38_combined_af.vcf.bgz,short_name=gnomad4,format=vcf -o /project/shared/projects/VEP/vep_out/testAnnot.chr20.txt

I will appreciate your response.

Thank you


From: Odia, Trust ***@***.***>
Date: Monday, January 8, 2024 at 11:23 AM
To: Ensembl/ensembl-vep ***@***.***>, Ensembl/ensembl-vep ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [External] Re: [Ensembl/ensembl-vep] gnomad v4 in VEP (Issue #1574)
Hi Dave,

Thank you so much.

From: Dave Lawrence ***@***.***>
Date: Monday, January 1, 2024 at 8:15 PM
To: Ensembl/ensembl-vep ***@***.***>
Cc: Odia, Trust ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [Ensembl/ensembl-vep] gnomad v4 in VEP (Issue #1574)

Hi @trust-odia<https://github.com/trust-odia> - I've removed the outer brackets, which may fix the script (hard to know as it works on my machine)

You may also want to just download them from here:

https://variantgrid.com/download/annotation/VEP/annotation_data/GRCh38/gnomad4.0_GRCh38_combined_af.vcf.bgz
https://variantgrid.com/download/annotation/VEP/annotation_data/GRCh38/gnomad4.0_GRCh38_combined_af.vcf.bgz.tbi

**Comment by trust-odia** [comment]
@davmlaw 

Hi Dave,
 
I use the combined gnomad4 data that you sent me (Thank you for this), to run VEP, just only for the AF freq, but the gnomADg_AF column does not have new values.
 
Please see my command:
 
vep -i /project/dshared/projects/VEP/chr20_NF.vcf.split.gz --tab -everything --buffer_size 1000 --offline --fork 4 --dir_plugins /project/shared/projects/PMBB_VEP_Annotations --dir_cache /home/todia  --custom file=/project/shared/projects/gnomad4/gnomad4.0_GRCh38_combined_af.vcf.bgz,short_name=gnomad4,format=vcf -o /project/shared/projects/VEP/vep_out/testAnnot.chr20.txt
 
I will appreciate your response.
 
Thank you

**Comment by davmlaw** [comment]
Hi, 

I think you need to add ```fields=AF```as an argument to custom - then it will add a column called ```gnomad4_AF``` (ie custom short_name + field)

See [VEP Custom documentation](http://asia.ensembl.org/info/docs/tools/vep/script/vep_custom.html)

**Comment by trust-odia** [comment]
@davmlaw Thank you.

**Comment by trust-odia** [comment]
Hi Dave,

Is my command correct this way? Because in previous try, VEP is not producing the frequencies.

nohup vep -i /project/shared/projects/VEP/genetic_exome_chr21_NF.vcf.split.gz --tab --offline --dir_cache /home/todia  --custom file=/project/shared/projects/gnomad4/gnomad4.0_GRCh38_combined_af.vcf.bgz,short_name=gnomad4g,format=vcf,type=exact,fields=AF -o /project/shared/projects/VEP/vep_out/testAnnot_0207.chr21.txt

Thank you for your response.

From: Dave Lawrence ***@***.***>
Date: Wednesday, February 7, 2024 at 7:23 PM
To: Ensembl/ensembl-vep ***@***.***>
Cc: Odia, Trust ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [Ensembl/ensembl-vep] gnomad v4 in VEP (Issue #1574)

Hi,

I think you need to add fields=AFas an argument to custom - then it will add a column called gnomad4_AF (ie custom short_name + field)

See VEP Custom documentation<http://asia.ensembl.org/info/docs/tools/vep/script/vep_custom.html>

**Comment by davmlaw** [comment]
Hi, it's hard to know without looking at your files, but it could be due to chromosome mappings. I use the full contig names in the VCF, you may need to use ```--synonyms``` [VEP Option](https://asia.ensembl.org/info/docs/tools/vep/script/vep_options.html)

**Comment by nakib103** [comment]
Hello,

I am delighted to announce that gnomAD v4.1 would be available from Ensembl next release (113) with approximate release date in the next month. It will be available in the Ensembl website Variation views, Ensembl REST, and also in VEP.

I will close this ticket. But if you face any issue using gnomAD v4.1 once it released or have any other queries feel free to re-open it or create a new one.

Best regards,
Nakib
