### ISSUE TITLE
Adding data in ".txt" or "tsv" format to annotations

### ISSUE THREAD

**Issue by Alex2006gene** [Ensembl/ensembl-vep#1581]
Hello,
I want to add data like inheritance pattern from databases like OMIM to my annotations with VEP but they provide us their data in the ".txt" or ".tsv" formmats. How can i convert them to suitable formats or use them in anywhay with VEP?
I use vep version 110.1

**Comment by nakib103** [comment]
Hello @Alex2006gene,

Thanks for you r query!

A good way to add additional annotation to VEP result is using the `--custom` option. There are several type of file format supported but you might find `bed` to be useful for your purpose. The files need to have genomic co-ordinates and be tabix indexed for VEP to calculate variant overlaps. You can find a detailed description in the doc -
https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html

Best regards,
Nakib

**Comment by Alex2006gene** [comment]
Thank you Nakib for your kind response

**Comment by sounkou-bioinfo** [comment]
> Hello @Alex2006gene,
> 
> Thanks for you r query!
> 
> A good way to add additional annotation to VEP result is using the `--custom` option. There are several type of file format supported but you might find `bed` to be useful for your purpose. The files need to have genomic co-ordinates and be tabix indexed for VEP to calculate variant overlaps. You can find a detailed description in the doc - https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html
> 
> Best regards, Nakib
Hi @nakib103 , i have a question with regard to the bed annotation output.  i used a bed 12 file and output vep in json format, the custom annotation is including only name:chr:start-end. Is there a way to specify which annotations are transfered in the case of a bed file. Thanks in advance
