### ISSUE TITLE
Usage of my own fasta and gff

### ISSUE THREAD

**Issue by AsmaaSamyMohamedMahmoud** [Ensembl/ensembl-vep#1591]
Hi, 
1) Can I run the VEP with --fasta and --gff and without using --cache, --offline, or --database parameters?
2) A lot of features from gff file are not supported and are reported in the warning output file, do you know how to fix this ? (warning.txt is attached) 
[tumor.annotation.tsv_warnings.txt](https://github.com/Ensembl/ensembl-vep/files/14046293/tumor.annotation.tsv_warnings.txt)

Thank you

**Comment by nuno-agostinho** [comment]
Hi @AsmaaSamyMohamedMahmoud,

Thanks for your question.

You don't need to use `--cache`, `--offline`, or `--database` parameters if you use the `--custom` annotation flag (`--gff`, `--gtf` and `--bigwig` are a shortcut for `--custom`). Are you having any issue with this command as such?

About the warnings, let's look into each type that you got:

### Variant size
```
WARNING: line 181 skipped (NC_060925.1 16396440 nv_SV56259-DC6AF N <INV> ...): variant size (128772784) is bigger than --max_sv_size (10000000)
WARNING: line 5723 skipped (NC_060929.1 81137247 nv_SV16301-AB94D N <INV> ...): variant size (13917690) is bigger than --max_sv_size (10000000)
```

The length of this structural variant is too big to be processed. You would have to use `--max_sv_size` bigger than the variant size to process them (such as `--max_sv_size 14000000`).

### Non-supported `feature_type`

```
WARNING: Ignoring non-supported 'region' feature_type from /home/asmaa/Desktop/MUN_PhD/PhD_research/Ref_genome/genomic.sorted.gff.gz
WARNING: Ignoring non-supported 'cDNA_match' feature_type from /home/asmaa/Desktop/MUN_PhD/PhD_research/Ref_genome/genomic.sorted.gff.gz
WARNING: Ignoring non-supported 'match' feature_type from /home/asmaa/Desktop/MUN_PhD/PhD_research/Ref_genome/genomic.sorted.gff.gz
WARNING: Ignoring non-supported 'biological_region' feature_type from /home/asmaa/Desktop/MUN_PhD/PhD_research/Ref_genome/genomic.sorted.gff.gz
WARNING: Ignoring non-supported 'enhancer' feature_type from /home/asmaa/Desktop/MUN_PhD/PhD_research/Ref_genome/genomic.sorted.gff.gz
WARNING: Ignoring non-supported 'silencer' feature_type from /home/asmaa/Desktop/MUN_PhD/PhD_research/Ref_genome/genomic.sorted.gff.gz
(...)
```

The GFF annotation is used by VEP to build a transcript set based on specific `feature_type` values: https://github.com/Ensembl/ensembl-vep/blob/a9c9ffde86368006d348ec1b31163cc54b17e187/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/GFF.pm#L72-L115

Unless those `feature_type`s describe transcripts, it should not be a problem.

### Parent entries not found or skipped

```
WARNING: Parent entries with the following IDs were not found or skipped due to invalid types: rna-NR_037806.1
WARNING: Parent entries with the following IDs were not found or skipped due to invalid types: rna-NR_170323.1
WARNING: Parent entries with the following IDs were not found or skipped due to invalid types: rna-NR_046507.1
WARNING: Parent entries with the following IDs were not found or skipped due to invalid types: rna-NR_148359.1
WARNING: Parent entries with the following IDs were not found or skipped due to invalid types: rna-NR_001566.1
WARNING: Parent entries with the following IDs were not found or skipped due to invalid types: rna-NR_185915.1, rna-NR_185914.1, rna-NR_045414.2, rna-NR_185916.1
```

Look for those IDs to see if the entries exist. If so, they may simply be invalid and could not be processed by VEP. If there is something that you think should be improved here, please do tell us.

### Unable to determine biotype

```
WARNING: Unable to determine biotype of XR_007071467.1
WARNING: Unable to determine biotype of XR_007071455.1
WARNING: Unable to determine biotype of NR_002997.1
WARNING: Unable to determine biotype of XR_007071464.1
WARNING: Unable to determine biotype of XR_007071466.1
WARNING: Unable to determine biotype of NR_003023.1
WARNING: Unable to determine biotype of NR_003139.1
WARNING: Unable to determine biotype of XR_007082513.1
WARNING: Unable to determine biotype of XR_007086035.1
WARNING: Unable to determine biotype of NR_003003.2
```

The biotype for those transcripts was not found in the GFF annotation. You can compare with other transcripts to check what are they missing. Here's the logic we use to determine the biotype: https://github.com/Ensembl/ensembl-vep/blob/a9c9ffde86368006d348ec1b31163cc54b17e187/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/GFF.pm#L231-L258

Hope this was clear enough, but feel free to reply to me so we can discuss this more.

Best regards,
Nuno

**Comment by AsmaaSamyMohamedMahmoud** [comment]
Hi @[nuno-agostinho](https://github.com/nuno-agostinho), 

Thank you so much for your quick and detailed response. 
1) For the custom annotation: I had no issue running it, I just wanted to make sure I am using it correctly. 
2) For the warnings: your explanation was clear for all. I will look more into it. Just a quick note, I am using GFF of T2T assembly. 

Sincerely, 
Asmaa

**Comment by nuno-agostinho** [comment]
Hey @AsmaaSamyMohamedMahmoud,

I am glad that the answer was helpful and I'll be here in case you have any more questions and comments.

Just for curiosity, what is the source of your T2T GFF file?

Cheers,
Nuno

**Comment by AsmaaSamyMohamedMahmoud** [comment]
Hi @nuno-agostinho, 

Thank you so much. I'm using NCBI RefSeq assembly GCF_009914755.1

Sincerely, 
Asmaa

**Comment by nuno-agostinho** [comment]
Hi @AsmaaSamyMohamedMahmoud,

I will close this issue now. Feel free to open a new one in case you have further questions.

Have a lovely day!

Kind regards,
Nuno
