### ISSUE TITLE
Error with dbNSFP plugin

### ISSUE THREAD

**Issue by kathleenvarty** [Ensembl/ensembl-vep#1597]
## Issue

I am trying to use the dbNSFP plugin with VEP. The following is the steps I took for installation:

1. Download from the google link. 
2. unzip dbNSFP4.5a.zip
3. gzcat dbNSFP4.5a_variant.chr1.gz | head -n1 > h
4. zgrep -h -v ^#chr dbNSFP4.5a_variant.chr* | sort -k1,1 -k2,2n - | cat h - | bgzip -c > dbNSFP4.5a_grch38.gz 
5. tabix -s 1 -b 2 -e 2 dbNSFP4.5a_grch38.gz

I then run vep using the docker image with the following command:

    command = [
        'docker', 'run',
        '-v', f'{vep_data_dir}:/data',
        'ensemblorg/ensembl-vep',
        'vep', '--cache', '--offline', '--format', 'ensembl',
        '--input_file', f'/data/{vcf_file}',  # Use the full path to the input file within the Docker container
        '--output_file', f'/data/{output_file}',  # Use the full path to the output file within the Docker container
        '--everything',
        '--merged',
        '--mane',
        '--mane_select',
        '--plugin', 'dbNSFP,/data/dbNSFP4.5a_grch38.gz,ALL',
    ]

## Error Message

Use of uninitialized value $allele_string in pattern match (m//) at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VEP_input.pm line 136, <__ANONIO__> line 2.
Can't locate object method "get_alternatives" via package "Bio::EnsEMBL::VEP::Parser::VEP_input" at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 662, <__ANONIO__> line 2.
2024-01-31 13:52:49 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this

## System
- VEP version: 111
- VEP Cache version: 111
- Perl version: v5.30.3
- OS: MacOS
- tabix installed ? Yes

Any help is appreciated, thank you!

**Comment by likhitha-surapaneni** [comment]
Hi @kathleenvarty , sorry to hear that you are facing issues. Can you please provide us with the input file you have been using?

**Comment by kathleenvarty** [comment]
[git_example.txt](https://github.com/Ensembl/ensembl-vep/files/14129134/git_example.txt)
Here is an example of a file. The file is a vcf but git does not support that so here is a .txt version

**Comment by likhitha-surapaneni** [comment]
Hi @kathleenvarty , thank you for providing the input file.

The error is likely due to the option format with `--format ensembl`  With this option, the parser tries to separate by tab and not space. However, if you don't specify the format with `--format ensembl` VEP will identify the format and the delimiter automatically and the error messages should go away. 
I am attaching the output file generated without the option. Hope this helps.
[vep_output_without_format.txt](https://github.com/Ensembl/ensembl-vep/files/14137643/vep_output_without_format.txt)


Kind regards,
Likhitha

**Comment by gilmorera** [comment]
@kathleenvarty I think the real issue might be that you need to use 4.5c instead of 4.5a: 
https://github.com/Ensembl/VEP_plugins/pull/688/files#diff-9237fcc30039979b3f1b5b8d088a2c333cec425f7fee4a7119fcc93962260e12R59-R60

**Comment by likhitha-surapaneni** [comment]
Hi @gilmorera and @kathleenvarty ,

It should be fine to use either of the files. The plugin description is being updated in the upcoming release, suggesting to select the version that is the most appropriate (academic or commercial licence). The example is being updated to use the commercial version as it applicable to wider audience.

**Comment by kathleenvarty** [comment]
Hi @likhitha-surapaneni  and @gilmorera,

Thank you both for your help! Likhitha's solution did work and because I am using this for academic purposes I believe I should stick to 4.5a. Thank you!
