### ISSUE TITLE
Inconsistent consequence annotation

### ISSUE THREAD

**Issue by woook** [Ensembl/ensembl-vep#1598]
## Describe the issue
- Annotating certain variants produces inconsistent consequence annotation. This issue occurs with web VEP 110, and previous versions (v105, v107 dockers tested).

- Example affected variant (VCF format):
``` 
4	55140744	.	GGTGATT	G
```

- ~85% of the time, the correct consequence is calculated; however ~15% of time, an incorrect `stop_lost` consequence is added. This non-deterministic behaviour is particularly problematic.

- Example of correct annotation (https://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Ticket?tl=gwjgHeeQJwncUTUn):
![image](https://github.com/Ensembl/ensembl-vep/assets/5719650/ecc8ab89-f202-4a5f-a673-898626c42520)

- Example of incorrect annotation (https://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Ticket?tl=5CFEdoHgE61Os404)
![image](https://github.com/Ensembl/ensembl-vep/assets/5719650/113a97c5-ddb1-4a5c-83de-568a8f0af870)

## Additional information
- Removing `--shift_3prime 1` appears to prevent the issue from occuring but that causes other issues (which is why it's enabled)
- The issue occurs with GRCh38 too
- It's always the addition of a `stop_lost` consequence

Other example affected variants (VCF format):
``` 
5	176562202	.	GTAA	G
5	176562232	.	TTAA	T
10	43615567	.	AGCT	A
12	56477627	.	GTGA	G
15	66729133	.	AGCT	A
```

### System
- VEP version: 110
- VEP Cache version: 110
- Web-VEP

### Full VEP command line
```
./vep --appris --biotype --buffer_size 5000 --distance 5000 --mane --refseq --shift_3prime 1 --show_ref_allele --species homo_sapiens --symbol --transcript_version --tsl --uploaded_allele --cache --input_file [input_data] --output_file [output_file] --port 3337
```

### Full error message
> None

**Comment by olaaustine** [comment]
Hi @woook, 
Hope you are well ? 
Thank you for reporting this issue. 
We can see how this is an issue. 
We are looking into it and will update this ticket when we have a solution. 
Thank you very much again. 
Ola.

**Comment by dennishendriksen** [comment]
Hello @olaaustine,

We are also running into this issue. The non-deterministic behaviour is particularly problematic for us as well.
Any updates on this @olaaustine?

Greetings,
@dennishendriksen

**Comment by olaaustine** [comment]
Hi @woook, 
Hope this meets you well and thank you very much for your patience. 
This issue has been resolved in more recent versions of VEP. 
Please try to use a more recent version of VEP and let us know if this issue still persists. 
I am going to close this ticket now. Please do not hesitate to reopen this ticket or open another ticket if you have any other issues. 
Thank you so much 
Ola
