### ISSUE TITLE
Input lines skipped when input is a pipe

### ISSUE THREAD

**Issue by joaoe** [Ensembl/ensembl-vep#16]
If I run VEP with a pipe as input, like for instance:
```
perl vep.pl --format vcf -i <(generate_some_vcf_content) -o /dev/stdout
```
a bunch of the first lines from that pipe will be skipped.
The culprit is in [this line](https://github.com/Ensembl/ensembl-vep/blob/release/87/modules/Bio/EnsEMBL/VEP/Parser.pm#L149).
The `-B` operator reads a chunk of data from the file to detect if it's binary data.
I'd suggest changing it to `-f $file && -B $file`.

Thanks.

**Comment by joaoe** [comment]
Btw, the download link at https://github.com/Ensembl/ensembl-tools/archive/release/87.zip instead includes this script https://github.com/Ensembl/ensembl-tools/blob/release/87/scripts/variant_effect_predictor/variant_effect_predictor.pl

Why the difference ? Anyway, that file also has [the same bug](https://github.com/Ensembl/ensembl-tools/blob/release/87/scripts/variant_effect_predictor/variant_effect_predictor.pl#L1810), although I can't create an issue in that project.

**Comment by willmclaren** [comment]
You should be able to bypass this with

`(generate_some_vcf_content) | perl vep.pl --format vcf -o stdout`

See the [README](https://github.com/Ensembl/ensembl-vep#vepdiffs) and the [docs](http://www.ensembl.org/info/docs/tools/vep/script/index.html) for details of how/why VEP is changing.

**Comment by joaoe** [comment]
I know, thanks. I'm not relying on this feature though but making a bug report.

**Comment by willmclaren** [comment]
Fixed by https://github.com/Ensembl/ensembl-vep/commit/038bfd95b7d4bae5f9134b4f7f8d5d63711aaad8
