### ISSUE TITLE
--tab and --vcf give different results

### ISSUE THREAD

**Issue by conanyangqun** [Ensembl/ensembl-vep#160]
Hi, vep team:
    I have a vcf file and want to annotate it using a custom vcf file **hg19_BRCA_1MF_gnomad_exomes_r2.0.2.vcf.gz**. When I run this cmd `/datapool/user/yangq/src/ensembl-vep/vep -i test.vcf -o test_anno.tsv --force --no_stats --cache --dir_cache=/datapool/user/yangq/databases/vep_cache/ --refseq --offline --fasta=/datapool/share/Database/hg19/hg19_mask/hg19.order.fasta --custom hg19_BRCA_1MF_gnomad_exomes_r2.0.2.vcf.gz,BRCAgnomAD,vcf,exact,0,AF,AN --tab`, everything works fine. I can find some mutations has the correct value in BRCAgnomAD_AF and BRCAgnomAD_AN column.

When I change `--tab` to `--vcf `, the result file contains headers like '##INFO=<ID=BRCAgnomAD_AF,' but no mutations has **BRCAgnomAD_AD** in its INFO column. I think the result is different from `--tab`. Any good suggestions? Is this a bug?

Waiting for your reply.
Thanks.

**Comment by at7** [comment]
Could you please check your CSQ string in the header starting with ##INFO=<ID=CSQ... Your custom annotation string BRCAgnomAD_AD should be listed at the end. Let me know if that is not the case. Could you then please share the complete CSQ Info line? Thank you.

**Comment by conanyangqun** [comment]
Hi, @at7 
Thanks for reply.
I am sorry that I made a mistake. I thought the custom anno would add to an independent key in info column. Now, I find it, just inside CSQ key. I will close this issue.
