### ISSUE TITLE
Empty fields HGVSc and HGVSp of INFO - CSQ after VCF annotation via GTF and Fasta

### ISSUE THREAD

**Issue by CaptainLabMan** [Ensembl/ensembl-vep#1602]
###System

VEP version: 111
VEP Cache: NO CACHE
OS: MacOS
tabix installed ? yes
###Full VEP command line

vep -vcf --force_overwrite -i ex3950-barcode63_filtered.vcf -o ex3950-barcode63_filtered.vep_ann.vcf --gtf Homo_sapiens.GRCh38.111.gtf.bgzip.gz --fasta Homo_sapiens.GRCh38.dna.toplevel.fa.gz

###Data files (if applicable)

They include:

The input file
The output file
Annotation via GTF and Fasta
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|SOURCE|Homo_sapiens.GRCh38.111.gtf.bgzip.gz">

chr3	15635512	chr3:15635512:G:A	G	A	6912	PASS	CSQ=A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000303498|protein_coding|3/5||||524|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000417015|protein_coding|2/3||||239|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000427382|protein_coding|2/4||||396|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000436193|protein_coding|2/4||||431|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000437172|protein_coding|4/6||||371|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000449107|protein_coding|2/4||||490|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|non_coding_transcript_exon_variant|MODIFIER|BTD|ENSG00000169814|Transcript|ENST00000467027|retained_intron|3/4||||912|||||||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|downstream_gene_variant|MODIFIER|BTD|ENSG00000169814|Transcript|ENST00000471964|protein_coding_CDS_not_defined|||||||||||83|1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000482824|protein_coding|2/3||||208|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000643237|protein_coding|2/4||||239|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000646371|protein_coding|3/5||||384|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000671928|protein_coding|2/4||||239|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000672141|protein_coding|2/4||||239|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000672336|protein_coding|3/4||||912|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000672427|protein_coding|2/5||||225|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000672760|protein_coding|2/4||||203|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000672892|protein_coding|2/5||||239|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|downstream_gene_variant|MODIFIER|BTD|ENSG00000169814|Transcript|ENST00000672968|protein_coding_CDS_not_defined|||||||||||2668|1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000673467|protein_coding|2/4||||206|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|,A|missense_variant|MODERATE|BTD|ENSG00000169814|Transcript|ENST00000673620|protein_coding|2/4||||134|73|25|G/R|Ggg/Agg|||1||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz|	GT:AF:AD	0/1:0.507018:289

These fields are empty for all variants. Why? What am I doing wrong?

**Comment by CaptainLabMan** [comment]
Got it. I had to add --hgvs flag.

**Comment by nakib103** [comment]
Hello @CaptainLabMan,

Yes, as you figured out you need to use the `--hgvs` flag here to get HGVS outputs. More details here -
https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#vcfout

I will close this issue as fixed. But feel free to open a new one if you face further issues.

Best regards,
Nakib
