### ISSUE TITLE
Absence MANE and canonical annotation tags in output VCF.

### ISSUE THREAD

**Issue by CaptainLabMan** [Ensembl/ensembl-vep#1604]
###System

VEP version: 111
VEP Cache: NO CACHE
OS: MacOS
tabix installed ? yes
###Full VEP command line

vep -vcf --hgvs --canonical --mane --flag_pick --force_overwrite --vcf_info_field ANN -i NBS-13981_filtered.vcf -o NBS-13981_filtered.vep_ann.vcf --gtf /Volumes/clm_data/dbs/refs/Homo_sapiens.GRCh38.111.gtf.bgzip.gz --fasta /Volumes/clm_data/dbs/refs/Homo_sapiens.GRCh38.dna.toplevel.fa.bgzip.gz

###Data files (if applicable)

They include:

The input file
The output file
Annotation via GTF and Fasta

I annotate my VCF files via GTF and Fasta with --canonical --mane options, but these fields is empty in output VCF for all variants (~1500000 variants). Also I use --flag_pick flag in order to select main transcripts. As said here, https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#assembly first of all transcripts should be MANE, then MANE Clinical and then Canonical, but it's not. Obviously because VEP can't get MANE and Canonical data from GTF. Why?

**Comment by CaptainLabMan** [comment]
GFF3 didn't work for me too. I prepared it as recommended here https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff 

gunzip -c Homo_sapiens.GRCh38.111.gff3.gz | grep -v "#" | sort -k1,1 -k4,4n -k5,5n -t$'\t' | bgzip > Homo_sapiens.GRCh38.111.gff3.bgzip.gz

tabix -p gff Homo_sapiens.GRCh38.111.gff3.bgzip.gz

And MANE and canonical fields are still empty.
##INFO=<ID=ANN,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|PICK|SYMBOL_SOURCE|HGNC_ID|CANONICAL|MANE_SELECT|MANE_PLUS_CLINICAL|RefSeq|SOURCE|HGVS_OFFSET|Homo_sapiens.GRCh38.111.gtf.bgzip.gz">

chr1    21570206        chr1:21570206:A:G       A       G       45      LowGQX;LowDepth;NoPassedVariantGTs      ANN=G|upstream_gene_variant|MODIFIER|ALPL|ENSG00000162551|Transcript|ENST00000374829|protein_coding_CDS_not_defined|||||||||||4272|1|||||||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz||,G|upstream_gene_variant|MODIFIER|ALPL|ENSG00000162551|Transcript|ENST00000374830|protein_coding|||||||||||97|1|||||||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz||,G|intron_variant|MODIFIER|ALPL|ENSG00000162551|Transcript|ENST00000374832|protein_coding||7/11|ENST00000374832.1:c.793-99A>G|||||||||1|||||||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz||,G|intron_variant|MODIFIER|ALPL|ENSG00000162551|Transcript|ENST00000374840|protein_coding||7/11|ENST00000374840.1:c.793-99A>G|||||||||1||1|||||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz||,G|intron_variant|MODIFIER|ALPL|ENSG00000162551|Transcript|ENST00000539907|protein_coding||5/9|ENST00000539907.1:c.562-99A>G|||||||||1|||||||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz||,G|intron_variant|MODIFIER|ALPL|ENSG00000162551|Transcript|ENST00000540617|protein_coding||6/10|ENST00000540617.1:c.628-99A>G|||||||||1|||||||||Homo_sapiens.GRCh38.111.gtf.bgzip.gz||     GT:AF:AD        1/1:1:2

ENST00000374840 transcript is MANE and canonical for ALPL gene, but i can't see it in my annotation.

**Comment by nakib103** [comment]
Hello @CaptainLabMan,

With current VEP release, we do not annotate MANE sets or canonical transcript from the GFF/GTF file. That is why you are not getting the transcripts flagged. You can use cache or database instead. For example, for the variant you flagged - 

```
$ vep --force -i ../input_files/issue_1604 --mane --canonical --hgvs --fasta path/to/fasta/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --database --tab

#Uploaded_variation	Location	Allele	Gene	Feature	Feature_type	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	IMPACT	DISTANCE	STRANDFLAGS	CANONICAL	MANE	MANE_SELECT	MANE_PLUS_CLINICAL	HGVSc	HGVSp	HGVS_OFFSET
chr1:21570206:A:G	chr1:21570206	G	ENSG00000162551	ENST00000374829	Transcript	upstream_gene_variant	-	-	-	-	-	-	MODIFIER	4272	1	-	-	-	-	-
chr1:21570206:A:G	chr1:21570206	G	ENSG00000162551	ENST00000374830	Transcript	upstream_gene_variant	-	-	-	-	-	-	MODIFIER	97	1	cds_start_NF	-	-	-
chr1:21570206:A:G	chr1:21570206	G	ENSG00000162551	ENST00000374832	Transcript	intron_variant	-	-	-	-	-	-	MODIFIER	-	1	-	-	-	-	-	ENST00000374832.5:c.793-99A>G	-	-
chr1:21570206:A:G	chr1:21570206	G	ENSG00000162551	ENST00000374840	Transcript	intron_variant	-	-	-	-	-	-	MODIFIER	-	1	-	YES	MANE_Select	NM_000478.6	-	ENST00000374840.8:c.793-99A>G	-	-
chr1:21570206:A:G	chr1:21570206	G	ENSG00000162551	ENST00000539907	Transcript	intron_variant	-	-	-	-	-	-	MODIFIER	-	1	-	-	-	-	-	ENST00000539907.5:c.562-99A>G	-	-
chr1:21570206:A:G	chr1:21570206	G	ENSG00000162551	ENST00000540617	Transcript	intron_variant	-	-	-	-	-	-	MODIFIER	-	1	-	-	-	-	-	ENST00000540617.5:c.628-99A>G	-	-
```

Best regards,
Nakib

**Comment by nakib103** [comment]
Hello @CaptainLabMan,

We have added feature to get MANE and Canonical tags using GFF/GTF files. In such scenario, for MANE annotation, whether a transcript is a MANE_Select of MANE_Plus_Clinical would be added to a new field called `MANE` in the output file. For Canonical transcript the behavior would be same as before.

This feature would be available in the next Ensembl release (e113). 

I will close this issue for now, if you face further problems please feel free to open a new one.
