### ISSUE TITLE
Annotating with GNOMAD custom vcf makes frequencies become STRING and unable to filter

### ISSUE THREAD

**Issue by GACGAMA** [Ensembl/ensembl-vep#1608]
## Describe the issue
VCF format is unparsable after annotating with GNOMAD custom VCF.

I'm using GNOMAD 4.0 VCF with some columns filtered off. When annotating using this custom VCF, the annotated output VCF file is unparsable by vcf filter because it annotates frequencies as strings.

The header of GNOMAD 4.0 is

```
 ##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##hailversion=0.2.120-f00f916faf78
##FILTER=<ID=AC0,Description="Allele count is zero after filtering out low-confidence genotypes (GQ < 20; DP < 10; and AB < 0.2 for het calls)">
##FILTER=<ID=AS_VQSR,Description="Failed VQSR filtering thresholds of -1.4526 for SNPs and 0.0717 for indels">
##FILTER=<ID=InbreedingCoeff,Description="Inbreeding coefficient < -0.3">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Alternate allele count">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles">
##INFO=<ID=AF,Number=A,Type=Float,Description="Alternate allele frequency">
##INFO=<ID=nhomalt,Number=A,Type=Integer,Description="Count of homozygous individuals">

```

So VEP should annotate with ##INFO=<ID=AF,Number=A,Type=Float,Description="Alternate allele frequency">, but it outputs ##INFO=<ID=gnomad40_exomes_AF,Number=.,Type=String,Description="AF field from [PATH]/gnomad_40_genomes.vcf.gz">

### System
 DOCKER ensembl              : 110.584a8f3

### Full VEP command line

`singularity exec -H /scratch4/nsobrei2/references/vep_cache_singularity /scratch4/nsobrei2/singularities/vep.sif vep --fork 4 --cache -i vcf --species homo_sapiens --assembly GRCh38  --buffer_size 10000  --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --format vcf --input_file $1 --vcf --output_file $vep_path/output_vcf_unfiltered_AI/minimum_example_annotated_V2.vcf --force_overwrite --pubmed  --regulatory --polyphen b --af --max_af --af_1kg --af_gnomade --af_gnomadg --plugin CADD,"$CADD_SNV" --plugin CADD,"$CADD_INDEL" --plugin dbNSFP,"$dbNSFP",SIFT_pred,SIFT4G_pred,Polyphen2_HDIV_pred,MetaRNN_score,MetaRNN_pred,REVEL_score,BayesDel_noAF_score,BayesDel_noAF_pred,ClinPred_score,ClinPred_pred,clinvar_id,clinvar_clnsig,clinvar_trait,clinvar_review,clinvar_var_source,clinvar_OMIM_id --custom file=$vep_path/output_vcf_unfiltered_AI/gnomad_exomes_minimal.vcf.gz,short_name=gnomad40_exomes,fields=AC%AN%AF%nhomalt,format=vcf,type=exact
`

Then to filter:
`
singularity exec -H /scratch4/nsobrei2/references/vep_cache_singularity /scratch4/nsobrei2/singularities/vep.sif filter_vep --force_overwrite --only_matched --input_file  $vep_path/output_vcf_unfiltered_AI/minimum_example_annotated_V2.vcf.gz --output_file  $vep_path/output_vcf_unfiltered_AI/minimum_example_annotated_filtered.vcf  --filter "gnomad40_genomes_AF<0.01 or not gnomad40_genomes_AF" `

### Data files (if applicable)
[gnomad_exomes_minimal.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/14225471/gnomad_exomes_minimal.vcf.gz)

[minimum_example_annotated_V2.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/14225463/minimum_example_annotated_V2.vcf.gz)

**Comment by nakib103** [comment]
Hello @GACGAMA,

Thanks for your query!

I think there is a typo in your `filter_vep` command. Instead of `gnomad40_genomes_AF<0.01` it should be `gnomad40_exomes_AF<0.01` ("exomes" instead of "genomes").

Can you try with the update and let me know you get filtered result.

Best regards,
Nakib

**Comment by GACGAMA** [comment]
Hello @nakib103 

I mispeled the command in my example, but i've run the filtering step with multiple configurations, all with the same effect: VEP is removing some columns on CSQ when I filter numeric in a column defined in the header as string, even tough the original annotation was a number (float, AF)
I'm not sure why, but VEP is annotating the GNOMAD vcf (for example the one I provided), specifically and more importantly, the AF, as a string instead of a number. 
I also tried to normalize the GNOMAD file to remove multiallelica annotation, but the file is already biallelic. I`m not sure what is happening

**Comment by nakib103** [comment]
Hello @GACGAMA,

I can reproduce the issue. The filters works if we use string like comparison but that should not be the case. Thanks for reporting - I will add a bug fix. I will let you know updates here once we have a fix in place.

Best regards,
Nakib

**Comment by nakib103** [comment]
Hello @GACGAMA,

I have more insight into this issue. 
I missed the fact that you were not giving any spaces between the components (`field`, `operator`, and `values` - see [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html#filter_write)) of the filter. So, if you run with `--filter "gnomad40_genomes_AF < 0.01 or not gnomad40_genomes_AF"` it will work fine.

Best regards,
Nakib

**Comment by GACGAMA** [comment]
Hi @nakib103 

I tried with --filter "not gnomad40_exomes_AF", but it is not working as intended.
When I use `bcftools +split-vep -f "%gnomad40_exomes_AF/n" $i"  | sed -e "s/\/n/,/g" | sed 's/. $//' | tr "," "\n" | sort -u  | tr "\n" "," | fmt -w 1 ` to find which unique values are present in my tag after filtering with "not gnomad40_exomes_AF", I still get all the values as in the unfiltered file.

**Comment by nakib103** [comment]
Hello @GACGAMA,

If I run the following command -
```
filter_vep --i minimum_example_annotated_V2.vcf.gz --o filtered.vcf --filter "not gnomad40_exomes_AF" --force
```
I see only null values for `gnomad40_exomes_AF` in the output - [filtered.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/14403443/filtered.vcf.gz)

That is the expected result. Using `not` removes any lines where that specific field is not null. It does not remove the INFO header line as in the output the null subfield in the CSQ still exists.

Best regards,
Nakib

**Comment by nakib103** [comment]
Hello @GACGAMA,

I will close this issue for now. If you face any further problems feel free to open a new one.

Best regards,
Nakib
