### ISSUE TITLE
can not call method "seq"

### ISSUE THREAD

**Issue by Marije179** [Ensembl/ensembl-vep#1615]
Hi, I am trying to run VEP, but I keep getting this issue (and output file is empty): 

Can't call method "seq" on an undefined value at /home/WUR/steen179/miniforge3/share/ensembl-vep-111.0-0/Bio/EnsEMBL/Transcript.pm line 828, <__ANONIO__> line 379.

Someone knows what this issue means and how to solve it?

**Comment by nuno-agostinho** [comment]
Hi @Marije179,

Thank you for reporting this issue.

Could you please tell me what command are you using to run VEP? If possible, also send a sample of the input variants that reproduce the error. Thanks!

Best regards,
Nuno

**Comment by Marije179** [comment]
Hi Nuno, 

Thankyou for your fast response.

I am using this command to run VEP: 
 vep -i syri.vcf --gff <FILENAME>.gff3.gz --fasta <FILENAME>.fasta -o syri_VEP.vcf 

I use a vcf file generated with syri. 

the gff3 file is sorted and indexed with these commands (as provided on ensembl-vep):
grep -v "#" data.gff | sort -k1,1 -k4,4n -k5,5n -t$'\t' | bgzip -c > data.gff.gz
tabix -p gff data.gff.gz

the gff3 file is a pseudo-annotation of a animal breed assembly fasta I generated (specificied in --fasta). 

It is not possible to send the input variants. 

Thankyou in advance!

**Comment by nuno-agostinho** [comment]
Hey @Marije179,

Your command seems fine. Is the error message complete? Does it only show that?

From what I can understand, while running VEP with your files, there may be a transcript whose sequence cannot be retrieved. Please do the following:
1. Check if the FASTA file is as expected for the coordinates of some transcripts specified in the GFF annotation.
2. Check if the chromosome names are the same between the GFF and FASTA files.

Please report me your findings and if there is anything else to add. Thanks!

Cheers,
Nuno

**Comment by Marije179** [comment]
Hi Nuno, 

It also gives me these warning messages (a few more warning messages for some types that are not supported, but just to show you the short version): 

WARNING: line 309 skipped (Chr location type N <type> . PASS END=...): HDR type is not supported
WARNING: line 310 skipped (Chr location type N <type> . PASS END=...): SYNAL type is not supported
WARNING: line 311 skipped (Chr location type N <type> . PASS END=...): NOTAL type is not supported
WARNING: Ignoring non-supported 'three_prime_UTR' feature_type from NAMEFILE.gff3.gz
WARNING: Ignoring non-supported 'five_prime_UTR' feature_type from NAMEFILE.gff3.gz
Can't call method "seq" on an undefined value at /home/WUR/steen179/miniforge3/share/ensembl-vep-111.0-0/Bio/EnsEMBL/Transcript.pm line 828, <__ANONIO__> line 379.

I checked the things you suggested, but the sequences in the reference fasta and the GFF3 file are the same and also the chromosome names between the fasta and gff3 are the same.

**Comment by nuno-agostinho** [comment]
Hi @Marije179,

I suppose you are running a list of variants as input (at least 311 from what I can see in your warnings).

Could you try creating small files and running VEP with them? This would allow you to narrow down which variant is the problematic. You can split your input file using `split -l 50 syri.vcf syri.vcf_`, which will split your input into small files with 50 variants each.

Unfortunately, I cannot do much more without knowing more information on what is wrong, so do tell me if find something interesting.

Cheers,
Nuno

**Comment by Marije179** [comment]
Thankyou. 

I see that this variant is causing problem: 
Chr1	location	INV338	N	<INV>	.	PASS	END=location;ChrB=Chr1;StartB=location;EndB=location;Parent=.;VarType=SR;DupType=-

When I then remove that variant from the vcf file, it runs fine, but when I add more variants to the VCF file, another variant is causing problems: 

Chr1	location	DUP696	N	<DUP>	.	PASS	END=location;ChrB=Chr1;StartB=location;EndB=location;Parent=.;VarType=SR;DupType=copygain

and same here, when removing this variant and perform VEP with the same VCF file it runs fine, but with adding more variants to it, leads again somewhere that another variant is disrupting the annotation...

**Comment by nakib103** [comment]
Hello @Marije179,

I have went though the discussion in this issue. It is not possible to pinpoint the issue without the input variants, FASTA and the GFF file you are using.

But my guess is that it is the GFF file that is causing the issue. I can provide some pointers to debug this issue - 
- The variant that are causing problem can you find the transcripts they are overlapping. You can do that by querying the GFF using `tabix` in the same region that the variant lies. Once you find the overlapping transcripts can you check if the transcript description is correct and complete - i.e. - it has child exon/introns with proper details.

Sorry that I cannot provide exact solution to the problem due to lack of information. 

Best regards,
Nakib

**Comment by Marije179** [comment]
Thankyou for your reply.

I was using a pseudo annotation of GFF file. Now I received final GFF annotations of Ensembl and it is working now.

Regards,

Marije
________________________________
Van: Syed Nakib Hossain ***@***.***>
Verzonden: woensdag 25 september 2024 17:35
Aan: Ensembl/ensembl-vep ***@***.***>
CC: Steensma, Marije ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Ensembl/ensembl-vep] can not call method "seq" (Issue #1615)


Hello @Marije179<https://github.com/Marije179>,

I have went though the discussion in this issue. It is not possible to pinpoint the issue without the input variants, FASTA and the GFF file you are using.

But my guess is that it is the GFF file that is causing the issue. I can provide some pointers to debug this issue -

  *   The variant that are causing problem can you find the transcripts they are overlapping. You can do that by querying the GFF using tabix in the same region that the variant lies. Once you find the overlapping transcripts can you check if the transcript description is correct and complete - i.e. - it has child exon/introns with proper details.

Sorry that I cannot provide exact solution to the problem due to lack of information.

Best regards,
Nakib
