### ISSUE TITLE
Normalisation-based allele matching algorithm and custom file

### ISSUE THREAD

**Issue by KevinMer** [Ensembl/ensembl-vep#1616]
## Describe the issue
Hi,

I am currently using a vcf custom file with cosmic references.
Based on the section "Existing or colocated variants" (from this web page : (https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html), it seems that normalisation-based allele matching algorithm is always used.
However, I do not clearly understand how it works. 

In the vcf input file I included, you can see the variant chr7:55248998:A:ATGGCCAGCG which I except to match with the corresponding line in the custom vcf file : chr7:55248998:-:TGGCCAGCG. But it's not the case. 
Since vep applies a normalisation before searching for matches I added the key chr7:55248999:-:TGGCCAGCG in the custom file but once again I get no match and I do not understand why.

In fact, if i add specifically the line chr7:55248998:A:ATGGCCAGCG in the custom file, I obtain the corresponding match. But this line do not exist in the file from which I extracted the cosmic references so I can't consider this as a way to solve this issue.  

Could you explain me what should be the corresponding line in the custom vcf file in order to match the vcf one ?

Thanks a lot for you help.

Have a nice day,

Kevin 
[KevMerIssue.zip](https://github.com/Ensembl/ensembl-vep/files/14344415/KevMerIssue.zip)

### System
- VEP version: 110 
- VEP Cache version: 110
- Perl version: 5.26.1
- OS: Ubuntu
- tabix installed ? yes

### Full VEP command line
```
vep \
--fork 8 \
--offline \
--refseq \
--cache \
--dir_cache /path/to/dir/cache/ \
--dir_plugins /plugins/ \
--cache_version 110 \
--fasta hg19.fa \
--format vcf \
--vcf \
-i input.vcf \
-o output.vcf \
--custom file=cosmic86.vcf.gz,short_name=CUSTOM,format=vcf,type=exact,coords=0,fields=cosmic86 \
--hgvsp_use_prediction \
--hgvs \
--force_overwrite
```

### Data files (if applicable)
They include:
- The input file
- The output file
- The custom file(s)
You can provide a sample of them

**Comment by nuno-agostinho** [comment]
Hey @KevinMer,

Hope you are having a nice day.

The documentation section **[Existing or colocated variants](https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#colocated)** is only regarding the use of the option [`--check_existing`](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_check_existing) to report variants in the Ensembl database that match your input. As you are not using that flag in your command, that section doesn't apply in this case.

I took a look into the VCF file `cosmic86.vcf`. The `REF` is incorrect according to the [VCF specifications (section 1.6.1)](https://samtools.github.io/hts-specs/VCFv4.4.pdf):

> REF — reference base(s): Each base must be one of A,C,G,T,N (case insensitive). Multiple bases are permitted. The value in the POS field refers to the position of the first base in the String.

A dash (`-`) is not a valid character for the `REF` column in a VCF. The correct line should indeed start with `7       55248998        7_55244898_-_TGGCCAGCG  A       ATGGCCAGCG`.

Did you download the VCF file from the [COSMIC website](https://cancer.sanger.ac.uk/cosmic/download/cosmic)?

Best regards,
Nuno

**Comment by KevinMer** [comment]
Hi @nuno-agostinho,

thanks for your answer !

I didn't download it from the COSMIC website. It's an old release (v86). I transformed an annovar file to vcf in order to use it as a custom file for vep.
We're using annovar and would like to switch to vep so I was trying to obtain exactly the same results from extern databases as validation.

Seems that annovar do some tricky things that I need to catch.

Thanks for your help. I close the issue

Have a nice day,

Kevin
