### ISSUE TITLE
filter_vep output file larger than input file

### ISSUE THREAD

**Issue by sdhutchins** [Ensembl/ensembl-vep#1621]
## Describe the issue
I am using the `filter_vep` script to filter my vcf file after annotating.

Per the documentation on VEP's website, using the `--gz` should allow for compressed vcfs to be read.

When i use `filter_vep` on my vcf files, the output vcf file is larger in size.

On inspection, the file is not compressed.

**_Should I be compressing this with bcftools or using the vep script to do this? Is this expected behavior?_**

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 111 
- VEP Cache version: 111
- Perl version: [e.g. 5.26]
- OS: CentOS
- tabix installed ? Yes

### Full VEP command line
```
filter_vep -i {input.calls} --format vcf -o {output.filtered_calls} --filter "gnomADv3_AF < {params.af_cutoff}" --gz
```

### Full error message

```console
[shutchin@login004 LW001394]$ file LW001394_vep_annotated_filtered_by_gnomad_af.vcf.gz
LW001394_vep_annotated_filtered_by_gnomad_af.vcf.gz: ASCII text, with very long lines
```

### Data files (if applicable)
They include:
- The input file
- The output file
- The custom file(s)
You can provide a sample of them

**Comment by nuno-agostinho** [comment]
Hey @sdhutchins,

Hope you are having a great day!

`filter_vep` does not output compressed data. You will need to use `bgzip` or `gzip` on its plain text output after running the command.

I added this as a feature request to our backlog, so we can have a flag in `filter_vep` to allow outputting results in a compressed format.

Let me know if this helps.

Best regards,
Nuno

**Comment by sdhutchins** [comment]
Thank you so much! This explains everything.
