### ISSUE TITLE
WARNING: Chromosome 22 not found in annotation sources or synonyms on line 1

### ISSUE THREAD

**Issue by MaayanYoles** [Ensembl/ensembl-vep#1622]
## Describe the issue
Hi,
I am trying to use VEP for the first time and after successfully installing. I downloaded an older version (105). when running the tool i get an error about the chromosome in my vcf file.

The tool does make the .txt file and the txt_summary.html file, but they are empty and there is an additional file of txt_warnings.txt that has one line:
WARNING: Chromosome 22 not found in annotation sources or synonyms on line 1

I will say the vcf file being used was make using bcftools and PLINK.

the vcf's header looks like this, and has the chromosome number in it:
##fileformat=VCFv4.2
##fileDate=20240222
##source=PLINKv1.90
##contig=<ID=22,length=51244565>
##INFO=<ID=PR,Number=0,Type=Flag,Description="Provisional reference allele, may not be based on real reference genome">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT 

thank you so much
Maayan
---------------------------------------------------

### System
- VEP version: [105] 
- VEP Cache version: [105]
- Perl version: [v5.16.3]
- OS: [lynux]
- tabix installed yes

### Full VEP command line
```
vep --format vcf -i .vep/DATA_all_00_hg19_chr_22_16000000_17000000.vcf -o .vep/vep_DATA_all_00_hg19_chr_22_16000000_17000000.txt --offline --force_overwrite
```

**Comment by olaaustine** [comment]
Hi @MaayanYoles, 
Hope you are well? 
Thank you for your query. 
To use offline mode, an additional source of annotation is required. See [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#basic:~:text=Default%20%3D%20%22%24HOME/.vep/%22-,%2D%2Doffline,-Enable%20offline%20mode). 
If you have the cache files already downloaded, please point to the directory using [--dir_cache](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#basic:~:text=Default%20%3D%20%22%24HOME/.vep/%22-,%2D%2Ddir_cache,-%5Bdirectory%5D).  If the cache files have not been downloaded yet, please see [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#:~:text=Manually%20downloading%20caches) to manually download our cache files. 
Let us know if this helps. 
Thank you very much 
Ola.

**Comment by olaaustine** [comment]
Hi @MaayanYoles, 
Thank you for your response. 
Please follow the instructions here 
```
cd  .vep/homo_sapiens/
tar -xvf 105_GRCh37.tar
```
Your cache directory should be  `<homo_sapiens>/<105_GRCh37> `not `.tar`
Please let us know if this helps. 
Thank you so much 
Ola.

**Comment by olaaustine** [comment]
Hi @MaayanYoles, 
Just a follow up about this issue. 
Thank you 
Ola.

**Comment by olaaustine** [comment]
Hi @MaayanYoles, 
Hope you are well? 
To debug this issue, can you confirm that you have tabix installed in your path?
 If you do, can you go into this directory .vep/homo_sapiens/105_GRCh37` and confirm that you have `chr_synonyms.txt` and you should have the directory structure`homo_sapiens/105_GRCh37/chromosome_number`
Thank you 
Ola.

**Comment by MaayanYoles** [comment]
Hi @olaaustine 
I am well, hope you are too.

I followed your instructions and it worked!! The results look great and the tool runs.
Thank you so much for the patience.

Have a great day :)
Maayan

**Comment by olaaustine** [comment]
Hi @MaayanYoles, 
I am well, thank you 😁
Thank you for letting us know and thank you for using VEP.
I will close this ticket now, please feel free to reopen this or open another ticket if you have any issues. 
Do have a lovely day. 
Thank you, 
Ola
