### ISSUE TITLE
trouble finding cache file "MSG: ERROR: Cache directory /..."

### ISSUE THREAD

**Issue by waaaliceee** [Ensembl/ensembl-vep#1624]
## Describe the issue
I'm currently having issue running vep using docker. 
The error seems to be caused by the directory issues but I cannot find the problem. 
Is there any solutions that might help me throughout?

## Additional information
cache files for 111_GRCh38 is in 
"vep_data/cache/homo_sapiens/111_GRCh38/"
reference genome file is in 
"vep_data/cache/homo_sapiens_refseq/"

### System
- VEP version: [e.g. 98 or 98.1] 
- VEP Cache version: [e.g. 98]
- Perl version: 5.32
- OS: [MacOS]
- tabix installed : O

### Full VEP command line
```
(base) hyunjeong@ohyeonjeongs-MacBook-Air ~ % docker run -t -i -v /Users/hyunjeong/vep_data/cache:/data ensemblorg/ensembl-vep

vep@ede0800fcfca:~/.vep$ vep --cache --offline --format vcf --tab --force_overwrite --hgvs --check_ref --stats_Text --transcript_version --numbers --canonical --show_ref_allele --assembly GRCh38 --fasta /Users/hyunjeong/vep_data/cache/homo_sapiens_refseq/Homo_sapiens.GRCh38.dna.primary_assembly.fa --dir_cache /Users/hyunjeong/vep_data/cache --input_file input/test.vcf.gz --output_file output/output.txt

```

### Full error message

-------------------- EXCEPTION --------------------
MSG: ERROR: Cache directory /Users/hyunjeong/vep_data/cache/homo_sapiens not found

STACK Bio::EnsEMBL::VEP::CacheDir::dir /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:305
STACK Bio::EnsEMBL::VEP::CacheDir::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:219
STACK Bio::EnsEMBL::VEP::CacheDir::new /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:116
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:92
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:200
STACK toplevel /opt/vep/src/ensembl-vep/vep:46
Date (localtime)    = Wed Feb 28 04:43:14 2024
Ensembl API version = 111

### Data files (if applicable)
They include: 
- The input file
- The output file
- The custom file(s)
You can provide a sample of them

## Issue 2
I've also tried other code 
```
(base) hyunjeong@ohyeonjeongs-MacBook-Air ~ % docker run -t -i -v /Users/hyunjeong/vep_data:/opt/vep/.vep:Z ensemblorg/ensembl-vep

vep@867be8fcfdb4:~/.vep$ vep --cache --offline --format vcf --tab --force_overwrite --hgvs --check_ref --stats_Text --transcript_version --numbers --canonical --show_ref_allele --assembly GRCh38 \
--fasta /opt/vep/.vep/cache/homo_sapiens_refseq/Homo_sapiens.GRCh38.dna.primary_assembly.fa \
--dir_cache /opt/vep/.vep/cache/homo_sapiens \
--input_file /opt/vep/.vep/input/test.vcf.gz \
--output_file /opt/vep/.vep/output/output.txt
```

##Full Error Message 
ERROR: Unexpected extra command-line parameter(s): --fasta /opt/vep/.vep/cache/homo_sapiens_refseq/Homo_sapiens.GRCh38.dna.primary_assembly.fa, --dir_cache /opt/vep/.vep/cache/homo_sapiens, --input_file /opt/vep/.vep/input/test.vcf.gz, --output_file /opt/vep/.vep/output/output.txt at /opt/vep/src/ensembl-vep/vep line 30.

**Comment by waaaliceee** [comment]
I've also tried other code 
'''
(base) hyunjeong@ohyeonjeongs-MacBook-Air ~ % docker run -t -i -v /Users/hyunjeong/vep_data:/opt/vep/.vep:Z ensemblorg/ensembl-vep

vep@867be8fcfdb4:~/.vep$ vep --cache --offline --format vcf --tab --force_overwrite --hgvs --check_ref --stats_Text --transcript_version --numbers --canonical --show_ref_allele --assembly GRCh38 \
--fasta /opt/vep/.vep/cache/homo_sapiens_refseq/Homo_sapiens.GRCh38.dna.primary_assembly.fa \
--dir_cache /opt/vep/.vep/cache/homo_sapiens \
--input_file /opt/vep/.vep/input/test.vcf.gz \
--output_file /opt/vep/.vep/output/output.txt
'''


###Full Error Message 
ERROR: Unexpected extra command-line parameter(s): --fasta /opt/vep/.vep/cache/homo_sapiens_refseq/Homo_sapiens.GRCh38.dna.primary_assembly.fa, --dir_cache /opt/vep/.vep/cache/homo_sapiens, --input_file /opt/vep/.vep/input/test.vcf.gz, --output_file /opt/vep/.vep/output/output.txt at /opt/vep/src/ensembl-vep/vep line 30.

**Comment by olaaustine** [comment]
Hi @waaaliceee, 

Hope you are well ? 

Thank you for your query. 

For the first issue, i see you are using VEP CLI, to debug this, can you confirm that tabix is on your path? 
If it is can you confirm the directory structure you have for the cache ` /Users/hyunjeong/vep_data/cache`, your structure should be something like ` /Users/hyunjeong/vep_data/cache/homo_sapiens/111_GRCh38/chromosome_name/number` can you also confirm that `chr_synonyms.txt` in this directory `/Users/hyunjeong/vep_data/cache/homo_sapiens/111_GRCh38/`

For the second issue, I see you are using VEP Docker image and you are trying to mounting the VEP Cache data, however can you change the way you are doing it following the instructions [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker:~:text=vep%20%2Di%20examples/homo_sapiens_GRCh38.vcf%20%2D%2Dcache-,Running%20VEP%20with%20data%20from%20local%20folder,-Here%20is%20an%20example%20on%20running%20VEP%20with%20data%20from). 

Please let us know if these steps help resolve this issue. 
Thank you very much 
Ola.

**Comment by olaaustine** [comment]
Hi @waaaliceee, 
Just a follow up about this to see if you have been able to resolve this issue.
Thank you 
Ola.

**Comment by waaaliceee** [comment]
Thank you for your reply and reminder Ola, 

1) tabix was installed, and on my path
(base) hyunjeong@ohyeonjeongs-MacBook-Air ~ % which tabix
/opt/homebrew/bin/tabix

2) I'm not sure but I guess I can show the image file to answer the directory structure for "/Users/hyunjeong/vep_data/cache/homo_sapiens/111_GRCh38/<chromosome_name/number>"
<img width="808" alt="스크린샷 2024-02-29 오전 10 09 28" src="https://github.com/Ensembl/ensembl-vep/assets/121419360/613edd9d-3379-497f-a962-339ca64c0c0c">


3) chr_synonyms.txt was in the "/Users/hyunjeong/vep_data/cache/homo_sapiens/111_GRCh38/" directory.
(base) hyunjeong@ohyeonjeongs-MacBook-Air homo_sapiens % cd 111_GRCh38
(base) hyunjeong@ohyeonjeongs-MacBook-Air 111_GRCh38 % find chr_synonyms.txt
chr_synonyms.txt


For the second issue, I will try to follow the instruction you gave me.

**Comment by waaaliceee** [comment]
Hi Ola, 
currently, I can run the docker and ensembl-vep, thanks to your help.

I'm having another issue with dbNSFP plugin. 

This is the code that I used and the output.txt showed no pathogenic prediction scores from dbNSFP.  
:
vep --cache --offline --format vcf --vcf --force_overwrite --dir_cache /opt/vep/.vep --appris --buffer_size 500 --distance 25 --hgvs --mane --plugin dbNSFP,dbNSFP4.4a_grch38.gz,VEST4_score,REVEL_score,BayesDel_noAF_score,CADD_phred,clinvar_hgvs --regulatory --show_ref_allele --species homo_sapiens --symbol --transcript_version --tsl --uploaded_allele --assembly GRCh38 --fasta /opt/vep/.vep/homo_sapiens_refseq/Homo_sapiens.GRCh38.dna.primary_assembly.fa  --input_file input/test.vcf --output_file output/output.txt 

Here is the format of output.txt
:
#CHROM        POS        ID        REF        ALT        QUAL        FILTER        INFO        FORMAT     

chr13        32890572        .        G        A        35554.2        PASS        AF=0.998047;AO=3574;DP=3586;FAO=3578;FDP=3585;FDVR=10;FR=.;FRO=7;FSAF=2039;FSAR=1539;FSRF=4;FSRR=3;FWDB=0.0429046;FXX=0.00167084;HRUN=1;HS_ONLY=0;LEN=1;MLLD=254.786;OALT=A;OID=.;OMAPALT=A;OPOS=32890572;OREF=G;PB=0.5;PBP=1;QD=39.67;RBI=0.0429257;REFB=-0.0114366;REVB=-0.00134575;RO=7;SAF=2036;SAR=1538;SRF=4;SRR=3;SSEN=0;SSEP=0;SSSB=-6.73711e-06;STB=0.500003;STBP=0.999;TYPE=snp;VARB=1.92054e-05;CSQ=A|intron_variant&non_coding_transcript_variant|MODIFIER|LINC00423|ENSG00000226968|Transcript|ENST00000421002.1|lncRNA||3/3|||||||||G|G/A||-1||HGNC|HGNC:42758|||5||||||||||||        GT:GQ:DP:FDP:RO:FRO:AO:FAO:AF:SAR:SAF:SRF:SRR:FSAR:FSAF:FSRF:FSRR        1/1:1495:3586:3585:7:7:3574:3578:0.998047:1538:2036:4:3:1539:2039:4:3

**Comment by olaaustine** [comment]
Hi @waaaliceee, 
Hope this meets you well? 
Can you use the option [--dir_plugins](https://grch37.ensembl.org/info/docs/tools/vep/script/vep_options.html#basic:~:text=Default%20%3D%20%22%24HOME/.vep/%22-,%2D%2Ddir_plugins,-%5Bdirectory%5D) to specify what plugin dir to use and see if the issue still exists. 
Thank you 
Ola.

**Comment by olaaustine** [comment]
Hi @waaaliceee,
Hope this meets you well?
I will close this issue now.
Please feel free to reopen another ticket if you have another issue.
Thank you
Ola
