### ISSUE TITLE
Mismatch between cache and assembly for T2T

### ISSUE THREAD

**Issue by Heather1999** [Ensembl/ensembl-vep#1628]
## Describe the issue
I used the t2t cache file provided in "https://ftp.ensembl.org/pub/rapid-release/species/Homo_sapiens/GCA_009914755.4/ensembl/variation/2022_08/indexed_vep_cache/"; However, there seems to be a mismatch between cache and assembly.

### System
 ensembl              : 111.a6cc543
  ensembl-funcgen      : 111.5327cdd
  ensembl-io           : 111.dbba8d6
  ensembl-variation    : 111.d616b1e
  ensembl-vep          : 111.0
- Perl version: [e.g. 5.32.1]
- OS: Ubuntu

### Full VEP command line
```
./vep -i /home/sealight1999/ASC_T2T/rmzero/AS_02_filtered.vcf -o /home/sealight1999/ASC_T2T/rmzero/AS_02_veped_mutect.vcf --offline --cache_version 111 --force --assembly T2TCHM13v2.0 --dir_cache /home/sealight1999/references/CHM13/vep/ > vep_AS_02_Mutect2.log 2>&1
```

### Full error message
> WARNING: line 1 skipped (chr1 381371 . C T . haplotype;normal_artifact;...): Chromosome chr1 not found in annotation sources or synonyms; chromosome chr1 does not overlap any features
WARNING: line 2 skipped (chr1 381377 . G A . haplotype;normal_artifact;...): Chromosome chr1 not found in annotation sources or synonyms; chromosome chr1 does not overlap any features
WARNING: line 3 skipped (chr1 409792 . C T . orientation;weak_evidence ...): Chromosome chr1 not found in annotation sources or synonyms; chromosome chr1 does not overlap any features
WARNING: line 4 skipped (chr1 475470 . C T . normal_artifact;orientatio...): Chromosome chr1 not found in annotation sources or synonyms; chromosome chr1 does not overlap any features
WARNING: line 5 skipped...
it went on to Chrom Y.

**Comment by nakib103** [comment]
Hello @Heather1999,

Thanks for your query!

I cannot reproduce the same error message you are getting, is it the full error message?

But I can see several issues with the vep command you provided not related to those error messages -
- Firstly, you need to give `--species homo_sapiens_gca009914755v4` as by default vep assumes `species=homo_sapiens`
- the assembly name have a typo, it would be `--assembly T2T-CHM13v2.0` and the cache version needs to be `106` based on the cache file you have downloaded. You can check this in the cache - there will be folder under `/home/sealight1999/references/CHM13/vep/<species>/<version>_<assembly>`

Can you try running the command with these updates.

Best regards,
Nakib

**Comment by Heather1999** [comment]
Hello @nakib103 
Thank you so much for your swift response!!
I made the changes you mentioned (thanks a lot for that), However the full messages remained:
`./vep -i /home/sealight1999/ASC_T2T/rmzero/AS_02_filtered.vcf -o /home/sealight1999/ASC_T2T/rmzero/AS_02_veped_mutect.vcf --offline --species homo_sapiens_gca009914755v4 --cache_version 106 --force --assembly T2T-CHM13v2.0 --dir_cache /home/sealight1999/references/CHM13/vep/`

WARNING: Chromosome chr1 not found in annotation sources or synonyms on line 1
WARNING: Chromosome chr2 not found in annotation sources or synonyms on line 378
WARNING: Chromosome chr3 not found in annotation sources or synonyms on line 622
WARNING: Chromosome chr4 not found in annotation sources or synonyms on line 793
WARNING: Chromosome chr5 not found in annotation sources or synonyms on line 941
WARNING: Chromosome chr6 not found in annotation sources or synonyms on line 1088
WARNING: Chromosome chr7 not found in annotation sources or synonyms on line 1279
WARNING: Chromosome chr8 not found in annotation sources or synonyms on line 1514
WARNING: Chromosome chr9 not found in annotation sources or synonyms on line 1601
WARNING: Chromosome chr10 not found in annotation sources or synonyms on line 1739
WARNING: Chromosome chr11 not found in annotation sources or synonyms on line 1882
WARNING: Chromosome chr12 not found in annotation sources or synonyms on line 2095
WARNING: Chromosome chr13 not found in annotation sources or synonyms on line 2325
WARNING: Chromosome chr14 not found in annotation sources or synonyms on line 2385
WARNING: Chromosome chr15 not found in annotation sources or synonyms on line 2476
WARNING: Chromosome chr16 not found in annotation sources or synonyms on line 2598
WARNING: Chromosome chr17 not found in annotation sources or synonyms on line 2721
WARNING: Chromosome chr18 not found in annotation sources or synonyms on line 2888
WARNING: Chromosome chr19 not found in annotation sources or synonyms on line 2942
WARNING: Chromosome chr20 not found in annotation sources or synonyms on line 3331
WARNING: Chromosome chr21 not found in annotation sources or synonyms on line 3393
WARNING: Chromosome chr22 not found in annotation sources or synonyms on line 3436
WARNING: Chromosome chrX not found in annotation sources or synonyms on line 3524
WARNING: Chromosome chrY not found in annotation sources or synonyms on line 3662
Could the issue stem from the upstream processing?
Thank you!

**Comment by nakib103** [comment]
Hi @Heather1999,
Can you share the input file you are using if possible, so that I can try reproducing the issue?

Thanks

**Comment by Heather1999** [comment]
Sure ! I've sent out invitation to you, please check.
Thank you.

**Comment by nakib103** [comment]
Hello @Heather1999,

Can you kindly attach the input file in this ticket if possible? Or, you can send the files to this address helpdesk@ensembl.org and refer to vep-issue 1628? Our outreach team will forward the files to me.

Best regards,
Nakib

**Comment by Heather1999** [comment]
Hello @nakib103 ,
Since the last post, I've decided to try another route.
But ran into another issue today:
-------------------- EXCEPTION --------------------
MSG: ERROR: SIFT not available

STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::check_sift_polyphen /home/sealight1999/miniconda3/envs/vep_t2t/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:168
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::new /home/sealight1999/miniconda3/envs/vep_t2t/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:121
STACK Bio::EnsEMBL::VEP::CacheDir::get_all_AnnotationSources /home/sealight1999/miniconda3/envs/vep_t2t/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:150
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /home/sealight1999/miniconda3/envs/vep_t2t/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:121
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/sealight1999/miniconda3/envs/vep_t2t/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/sealight1999/miniconda3/envs/vep_t2t/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /home/sealight1999/miniconda3/envs/vep_t2t/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::run /home/sealight1999/miniconda3/envs/vep_t2t/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel /home/sealight1999/miniconda3/envs/vep_t2t/ensembl-vep/vep:233
Date (localtime)    = Wed Jun 19 21:45:53 2024
Ensembl API version = 106

While the SIFT is indeed inside the vep data file (iinfo.txt), the followings ar its content:
species	homo_sapiens_gca009914755v4
assembly	T2T-CHM13v2.0
sift	
polyphen	
source_genebuild	2022-06
source_assembly	T2T-CHM13v2.0
variation_cols	chr,variation_name,failed,somatic,start,end,allele_string,strand,minor_allele,minor_allele_freq,clin_sig,phenotype_or_disease,clin_sig_allele,pubmed,var_synonyms
var_type	tabix

could you look into this please? Thank you!!

**Comment by nakib103** [comment]
Hello @Heather1999,

You are seeing this error because we do not have SIFT scores for T2T assembly in the vep cache. The info.txt shows that there is no SIFT (otherewise it would have s/p/b value similar to [--sift](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_sift) command) data in the cache.

We will soon publish a blog about how to use SIFT with T2T assembly in VEP along with required files. Keep an eye on this [page](https://www.ensembl.info/) for update. Until then please avoid using `--sift` for now.

Best regards,
Nakib

**Comment by Heather1999** [comment]
Hello @nakib103  ,
Thank you for your swift response!!
I did not use --sift as my command is as following:
perl /home/user/app/vcf2maf/vcf2maf.pl --input-vcf input.varscan.indel.Somatic.hc.vcf \
--output-maf output.varscan.indel.Somatic.hc.maf \
--tumor-id T --normal-id N --vcf-tumor-id TUMOR --vcf-normal-id NORMAL \
--ref-fasta "${T2T}" -vep-data /home/user/ref/CHM13/vep \
--species homo_sapiens_gca009914755v4 \
--vep-path /home/user/miniconda3/envs/vep_t2t/ensembl-vep \
--ncbi-build T2T-CHM13v2.0

Does that mean I can't work with T2T version of somatic variant vcf at the moment? Thank you!

**Comment by nakib103** [comment]
Hello @Heather1999,

This is command for `vcf2maf` tool. This is an external tool and is not maintained by us. 
I believe the tool uses the `--sift` option when running VEP. If this is not required, can you get into contact with team that maintains `vcf2maf` about how you can avoid running `--sift`?

**Comment by nakib103** [comment]
You have space after the `,` in the `--custom` argument. It should be something like this - 
```
--custom /home/user/references/CHM13/chm13v2.0_GENCODEv35_CAT_Liftoff.vep.sorted.gtf,t2t,gtf,exact
```

**Comment by Heather1999** [comment]
Thank you so much for all your help!!!
