### ISSUE TITLE
Docker 112 release doesn't build

### ISSUE THREAD

**Issue by Artemlin6231** [Ensembl/ensembl-vep#1629]
Docker 112 release doesn't build
I am trying to build a Docker image using the Dockefile specified in the release/112 branch (replacing the branch in the Dockerfile description with release/112). However, during the build process, one of your tests fails, causing the Docker image not to be built.
Command:
docker build -t my_docker_image .

**Comment by nakib103** [comment]
Hello @Artemlin6231,

Thanks for your query!
Latest Ensembl VEP release is e111 corresponding to git branch release/111. Can you try using that branch?

Best regards,
Nakib

**Comment by nakib103** [comment]
Hello @Artemlin6231,
I will close this issue, if you face further problems please feel free to open a new one.
