### ISSUE TITLE
Can't locate DBI.pm in @INC

### ISSUE THREAD

**Issue by sagitaninta** [Ensembl/ensembl-vep#1630]
## Describe the issue
I have installed vep version 110 using `conda install -c bioconda ensembl-vep=110` but when I ran vep I only got error message.

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 110
- VEP Cache version: 110
- Perl version: 5.38 (it was whatever in the conda)
- OS: Red Hat Enterprise Linux release 8.9 (Ootpa)
- tabix installed yes

### Full VEP command line
(Have not even gone here)

### Full error message

```
Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC entries checked: /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0/modules /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0 /opt/software/perl/5.38.0/lib/site_perl/5.38.0/x86_64-linux /opt/software/perl/5.38.0/lib/site_perl/5.38.0 /opt/software/perl/5.38.0/lib/5.38.0/x86_64-linux /opt/software/perl/5.38.0/lib/5.38.0) at /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.
BEGIN failed--compilation aborted at /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.
Compilation failed in require at /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 69.
BEGIN failed--compilation aborted at /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 69.
Compilation failed in require at /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Registry.pm line 137.
BEGIN failed--compilation aborted at /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Registry.pm line 137.
Compilation failed in require at /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 58.
BEGIN failed--compilation aborted at /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 58.
Compilation failed in require at /opt/software/perl/5.38.0/lib/5.38.0/base.pm line 137.
        ...propagated at /opt/software/perl/5.38.0/lib/5.38.0/base.pm line 159.
BEGIN failed--compilation aborted at /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0/modules/Bio/EnsEMBL/VEP/BaseRunner.pm line 56.
Compilation failed in require at /opt/software/perl/5.38.0/lib/5.38.0/base.pm line 137.
        ...propagated at /opt/software/perl/5.38.0/lib/5.38.0/base.pm line 159.
BEGIN failed--compilation aborted at /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0/modules/Bio/EnsEMBL/VEP/Runner.pm line 71.
Compilation failed in require at /home/mdn487/.conda/envs/ensembl-vep/bin/vep line 20.
BEGIN failed--compilation aborted at /home/mdn487/.conda/envs/ensembl-vep/bin/vep line 20.
```

### Data files (if applicable)
NA

**Comment by nakib103** [comment]
Hi @sagitaninta 

Thanks for your query!
It seems your `DBI` module might not have installed properly - can you make sure the module have been installed properly and available to the environment.

Notice that, we don't actively support VEP in conda as it's not an installation we have created (and so there could be any number of potential issues specific to a users system and environment that would be very hard for us to debug).

We would instead recommend using the containerised version of VEP we do support - full details here: https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker

Best regards,
Nakib

**Comment by sagitaninta** [comment]
Hi Nakib,

Thanks for your fast response. 

I ended up making a conda environment that has all the dependencies installed including DBI as I cannot sudo install perl modules in my server. The VEP 110 that I installed from the source code can be activated as long as I ran it within that conda environment.

Best,
Sabhrina
