### ISSUE TITLE
Problem of: Use of uninitialized value

### ISSUE THREAD

**Issue by celine-weng** [Ensembl/ensembl-vep#1632]
## Describe the issue
3 warning that I got:

STATUS: Running VEP and writing to: HI.snv.vep.vcf

WARNING: 96322 : Use of uninitialized value in string eq at /home/anaconda3/envs/idat2maf/share/ensembl-vep-102.0-0/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 2145, <__ANONIO__> line 13000.

Use of uninitialized value $check_alt in numeric ge (>=) at /home/anaconda3/envs/idat2maf/share/ensembl-vep-102.0-0/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 2148, <__ANONIO__> line 13000.

Use of uninitialized value in uc at /home/anaconda3/envs/idat2maf/lib/site_perl/5.26.2/Bio/SeqUtils.pm line 290, <__ANONIO__> line 13000.

WARNING: No genotype column for NORMAL in VCF!

## Additional information
Previously, I run the same command with same file, but on different computer and different reference. Previously I used GRCh37 and it work well without any warning. But when I tried to run it with GRCh38, it output those three warnings. I don't know if this is related to the problem or not. I could get the output, but I'm not sure if this warning will affect my output. I used the vcf file generated from SnpEff as input file.

### System
- VEP version: 102 
- VEP Cache version: 102
- Perl version: 5.26.2
- OS: Ubuntu
- tabix installed: yes

### Full VEP command line
```
vep --species homo_sapiens --assembly GRCh38 --no_progress --no_stats --buffer_size 5000 --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --vcf --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --dir /.vep --fasta /.vep/homo_sapiens/102_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --format vcf --input_file HI.snv.vcf --output_file HI.snv.vep.vcf --offline --pubmed --fork 4 --polyphen b --af --af_1kg --af_esp --af_gnomad --regulatory
```

**Comment by likhitha-surapaneni** [comment]
Hi @celine-weng ,
Thank you for reaching out. Can you please provide an input file?

**Comment by celine-weng** [comment]
Due to privacy reason, I can provide you with some sample, will this be enough?

`##fileformat=VCFv4.1									
##source=array-analysis-cli 2.1.0									
##genomeBuild=38									
##reference=file://GRCh38_latest_genomic.fa									
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">									
##FORMAT=<ID=GS,Number=1,Type=Float,Description="GenCall score. For merged multi-assay or multi-allelic record, min GenCall score is reported.">									
##FORMAT=<ID=BAF,Number=1,Type=Float,Description="B Allele Frequency">									
##FORMAT=<ID=LRR,Number=1,Type=Float,Description="Log R Ratio">									
##contig=<ID=1,length=248956422>									
##contig=<ID=2,length=242193529>									
##contig=<ID=3,length=198295559>									
##contig=<ID=4,length=190214555>									
##contig=<ID=5,length=181538259>									
##contig=<ID=6,length=170805979>									
##contig=<ID=7,length=159345973>									
##contig=<ID=8,length=145138636>									
##contig=<ID=9,length=138394717>									
##contig=<ID=10,length=133797422>									
##contig=<ID=11,length=135086622>									
##contig=<ID=12,length=133275309>									
##contig=<ID=13,length=114364328>									
##contig=<ID=14,length=107043718>									
##contig=<ID=15,length=101991189>									
##contig=<ID=16,length=90338345>									
##contig=<ID=17,length=83257441>									
##contig=<ID=18,length=80373285>									
##contig=<ID=19,length=58617616>									
##contig=<ID=20,length=64444167>									
##contig=<ID=21,length=46709983>									
##contig=<ID=22,length=50818468>									
##contig=<ID=X,length=156040895>									
##contig=<ID=Y,length=57227415>									
##contig=<ID=MT,length=16569>									
##SnpEffVersion="5.2a (build 2023-10-24 14:24), by Pablo Cingolani"									
##SnpEffCmd="SnpEff  GRCh38.105 /home/mca-vm/idat2maf/idat_sample/vcf/202485320131_R01C01.snv.vcf "									
##INFO=<ID=ANN,Number=.,Type=String,Description="Functional annotations: 'Allele | Annotation | Annotation_Impact | Gene_Name | Gene_ID | Feature_Type | Feature_ID | Transcript_BioType | Rank | HGVS.c | HGVS.p | cDNA.pos / cDNA.length | CDS.pos / CDS.length | AA.pos / AA.length | Distance | ERRORS / WARNINGS / INFO' ">									
##INFO=<ID=LOF,Number=.,Type=String,Description="Predicted loss of function effects for this variant. Format: 'Gene_Name | Gene_ID | Number_of_transcripts_in_gene | Percent_of_transcripts_affected'">									
##INFO=<ID=NMD,Number=.,Type=String,Description="Predicted nonsense mediated decay effects for this variant. Format: 'Gene_Name | Gene_ID | Number_of_transcripts_in_gene | Percent_of_transcripts_affected'">									
##SnpSiftVersion="SnpSift 5.2 (build 2023-10-24 14:25), by Pablo Cingolani"									
##SnpSiftCmd="SnpSift Filter 'ANN[*].IMPACT has 'HIGH'' /home/mca-vm/idat2maf/idat_sample/vcf/snpEff_annotated_vcf/202485320131_R01C01.snpEff.ann.snv.vcf"									
##FILTER=<ID=SnpSift,Description="SnpSift 5.2 (build 2023-10-24 14:25), by Pablo Cingolani, Expression used: ANN[*].IMPACT has 'HIGH'">									
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	202485320131_R01C01
1	980192	1:915572	CTG	C	.	PASS	ANN=C|frameshift_variant|HIGH|PERM1|ENSG00000187642|transcript|ENST00000341290.6|protein_coding|3/5|c.494_495delCA|p.Thr165fs|531/3035|494/2031|165/676||,C|frameshift_variant|HIGH|PERM1|ENSG00000187642|transcript|ENST00000433179.3|protein_coding|1/3|c.836_837delCA|p.Thr279fs|837/3340|836/2373|279/790||,C|upstream_gene_variant|MODIFIER|PERM1|ENSG00000187642|transcript|ENST00000479361.1|retained_intron||n.-3553_-3552delCA|||||3552|,C|downstream_gene_variant|MODIFIER|PLEKHN1|ENSG00000187583|transcript|ENST00000379410.8|protein_coding||c.*5618_*5619delTG|||||4328|,C|downstream_gene_variant|MODIFIER|PLEKHN1|ENSG00000187583|transcript|ENST00000491024.1|protein_coding||c.*4495_*4496delTG|||||4328|WARNING_TRANSCRIPT_NO_START_CODON;LOF=(PERM1|ENSG00000187642|3|0.67)	GT:GS:BAF:LRR	0/0:0.7599:0:-0.10469136
1	1286108	rs555847974	CAA	C	.	PASS	ANN=C|frameshift_variant|HIGH|SCNN1D|ENSG00000162572|transcript|ENST00000325425.12|protein_coding|4/15|c.448_449delAA|p.Lys150fs|598/2679|448/2115|150/704||,C|frameshift_variant|HIGH|SCNN1D|ENSG00000162572|transcript|ENST00000338555.6|protein_coding|4/15|c.250_251delAA|p.Lys84fs|1394/3475|250/1917|84/638||,C|frameshift_variant|HIGH|SCNN1D|ENSG00000162572|transcript|ENST00000470022.1|protein_coding|4/4|c.358_359delAA|p.Lys120fs|586/645|358/417|120/138||WARNING_TRANSCRIPT_NO_STOP_CODON,C|frameshift_variant|HIGH|SCNN1D|ENSG00000162572|transcript|ENST00000379116.10|protein_coding|7/18|c.742_743delAA|p.Lys248fs|968/3050|742/2409|248/802||,C|frameshift_variant|HIGH|SCNN1D|ENSG00000162572|transcript|ENST00000400928.7|protein_coding|5/16|c.250_251delAA|p.Lys84fs|645/2731|250/1917|84/638||,C|upstream_gene_variant|MODIFIER|SCNN1D|ENSG00000162572|transcript|ENST00000379099.3|protein_coding||c.-1001_-1000delAA|||||1000|WARNING_TRANSCRIPT_INCOMPLETE,C|downstream_gene_variant|MODIFIER|SCNN1D|ENSG00000162572|transcript|ENST00000467651.2|processed_transcript||n.*512_*513delAA|||||512|,C|non_coding_transcript_exon_variant|MODIFIER|SCNN1D|ENSG00000162572|transcript|ENST00000379101.8|nonsense_mediated_decay|6/17|n.648_649delAA||||||;LOF=(SCNN1D|ENSG00000162572|8|0.63)	GT:GS:BAF:LRR	0/0:0.4226:0:0.05689301
1	1287831	rs749990768	C	T	.	PASS	ANN=T|stop_gained|HIGH|SCNN1D|ENSG00000162572|transcript|ENST00000325425.12|protein_coding|8/15|c.1264C>T|p.Arg422*|1414/2679|1264/2115|422/704||,T|stop_gained|HIGH|SCNN1D|ENSG00000162572|transcript|ENST00000338555.6|protein_coding|8/15|c.1066C>T|p.Arg356*|2210/3475|1066/1917|356/638||,T|stop_gained|HIGH|SCNN1D|ENSG00000162572|transcript|ENST00000379116.10|protein_coding|11/18|c.1558C>T|p.Arg520*|1784/3050|1558/2409|520/802||,T|stop_gained|HIGH|SCNN1D|ENSG00000162572|transcript|ENST00000400928.7|protein_coding|9/16|c.1066C>T|p.Arg356*|1461/2731|1066/1917|356/638||,T|stop_gained|HIGH|SCNN1D|ENSG00000162572|transcript|ENST00000379099.3|protein_coding|2/7|c.514C>T|p.Arg172*|515/923|514/922|172/306||WARNING_TRANSCRIPT_INCOMPLETE,T|3_prime_UTR_variant|MODIFIER|SCNN1D|ENSG00000162572|transcript|ENST00000379101.8|nonsense_mediated_decay|10/17|n.*477C>T|||||894|,T|downstream_gene_variant|MODIFIER|ACAP3|ENSG00000131584|transcript|ENST00000354700.10|protein_coding||c.*5733G>A|||||4560|,T|downstream_gene_variant|MODIFIER|ACAP3|ENSG00000131584|transcript|ENST00000492936.5|retained_intron||n.*4559G>A|||||4559|,T|downstream_gene_variant|MODIFIER|SCNN1D|ENSG00000162572|transcript|ENST00000470022.1|protein_coding||c.*1663C>T|||||1663|WARNING_TRANSCRIPT_NO_STOP_CODON,T|downstream_gene_variant|MODIFIER|SCNN1D|ENSG00000162572|transcript|ENST00000467651.2|processed_transcript||n.*2234C>T|||||2234|,T|non_coding_transcript_exon_variant|MODIFIER|SCNN1D|ENSG00000162572|transcript|ENST00000379101.8|nonsense_mediated_decay|10/17|n.*477C>T||||||;LOF=(SCNN1D|ENSG00000162572|8|0.63);NMD=(SCNN1D|ENSG00000162572|8|0.63)	GT:GS:BAF:LRR	0/0:0.4606:0:0.051256247
1	1318875	rs62623580	G	A	.	PASS	ANN=A|stop_gained|HIGH|INTS11|ENSG00000127054|transcript|ENST00000429572.5|protein_coding|4/4|c.850C>T|p.Gln284*|908/1104|850/870|284/289||,A|upstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000462432.5|processed_transcript||n.-1425C>T|||||1425|,A|upstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000478641.5|retained_intron||n.-3705C>T|||||3705|,A|upstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000531292.5|retained_intron||n.-4211C>T|||||4211|,A|upstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000467408.6|retained_intron||n.-3274C>T|||||3274|,A|upstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000533916.5|retained_intron||n.-3178C>T|||||3178|,A|upstream_gene_variant|MODIFIER|ENSG00000240731|ENSG00000240731|transcript|ENST00000444968.1|pseudogene||n.-186C>T|||||186|,A|upstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000527383.5|nonsense_mediated_decay||n.-3269C>T|||||3267|,A|upstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000531020.1|retained_intron||n.-3734C>T|||||3734|,A|upstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000470030.6|retained_intron||n.-3442C>T|||||3442|,A|downstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000493534.6|processed_transcript||n.*185C>T|||||185|,A|downstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000532952.5|processed_transcript||n.*472C>T|||||472|,A|downstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000490853.5|processed_transcript||n.*506C>T|||||506|,A|downstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000534345.5|protein_coding||c.*431C>T|||||431|WARNING_TRANSCRIPT_INCOMPLETE,A|downstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000531019.5|nonsense_mediated_decay||n.*832C>T|||||506|,A|downstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000498476.6|protein_coding||c.*528C>T|||||528|WARNING_TRANSCRIPT_INCOMPLETE,A|downstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000525285.1|nonsense_mediated_decay||n.*1988C>T|||||1603|,A|downstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000530233.1|retained_intron||n.*3896C>T|||||3896|,A|downstream_gene_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000470679.3|nonsense_mediated_decay||n.*1013C>T|||||595|,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000323275.10|retained_intron|3/15|n.817+421C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000435064.6|protein_coding|4/16|c.429+421C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000540437.5|protein_coding|6/18|c.447+421C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000545578.5|protein_coding|5/17|c.342+421C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000620829.4|protein_coding|2/14|c.140-3261C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000421495.6|protein_coding|1/13|c.-529-3257C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000458452.7|nonsense_mediated_decay|6/18|n.*713+421C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000419704.5|protein_coding|2/14|c.126+2121C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000527098.5|nonsense_mediated_decay|5/17|n.*257+421C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000488042.6|retained_intron|4/6|n.450+421C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000525603.1|retained_intron|2/2|n.679+421C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000526797.5|nonsense_mediated_decay|4/6|n.*92+421C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000526332.5|protein_coding|2/4|c.57+421C>T||||||WARNING_TRANSCRIPT_NO_STOP_CODON,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000526904.5|retained_intron|1/1|n.79-3257C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000411962.5|protein_coding|2/14|c.136-3257C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000532772.5|nonsense_mediated_decay|2/12|n.126+2121C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000450926.6|protein_coding|4/16|c.429+421C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000528879.5|nonsense_mediated_decay|4/13|n.429+421C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000531377.5|nonsense_mediated_decay|1/6|n.51+421C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000434694.6|protein_coding|4/6|c.653+197C>T||||||WARNING_TRANSCRIPT_INCOMPLETE,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000430786.5|nonsense_mediated_decay|6/8|n.*307+421C>T||||||,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000527719.5|protein_coding|5/7|c.447+421C>T||||||WARNING_TRANSCRIPT_INCOMPLETE,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000530031.5|protein_coding|5/7|c.570+421C>T||||||WARNING_TRANSCRIPT_INCOMPLETE,A|intron_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000526113.1|retained_intron|1/2|n.58-3257C>T||||||,A|non_coding_transcript_exon_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000498173.2|retained_intron|3/3|n.1395C>T||||||,A|non_coding_transcript_exon_variant|MODIFIER|INTS11|ENSG00000127054|transcript|ENST00000496353.1|retained_intron|2/2|n.2250C>T||||||	GT:GS:BAF:LRR	0/0:0.7443:0.0017591715:0.08530161
1	1338000	rs797044837	CT	C	.	PASS	ANN=C|frameshift_variant|HIGH|DVL1|ENSG00000107404|transcript|ENST00000378891.9|protein_coding|14/15|c.1615delA|p.Ser539fs|1662/2926|1615/2013|539/670||,C|frameshift_variant|HIGH|DVL1|ENSG00000107404|transcript|ENST00000378888.10|protein_coding|14/15|c.1690delA|p.Ser564fs|2043/3305|1690/2088|564/695||,C|frameshift_variant|HIGH|DVL1|ENSG00000107404|transcript|ENST00000632445.1|protein_coding|4/6|c.619delA|p.Ser207fs|619/785|619/654|207/217||WARNING_TRANSCRIPT_NO_START_CODON,C|frameshift_variant|HIGH|DVL1|ENSG00000107404|transcript|ENST00000631679.1|protein_coding|7/8|c.721delA|p.Ser241fs|721/778|721/756|241/251||WARNING_TRANSCRIPT_NO_START_CODON,C|downstream_gene_variant|MODIFIER|TAS1R3|ENSG00000169962|transcript|ENST00000339381.6|protein_coding||c.*3537delT|||||2687|,C|downstream_gene_variant|MODIFIER|DVL1|ENSG00000107404|transcript|ENST00000472445.1|retained_intron||n.*3769delA|||||3769|,C|downstream_gene_variant|MODIFIER|DVL1|ENSG00000107404|transcript|ENST00000633096.1|retained_intron||n.*1491delA|||||1491|,C|downstream_gene_variant|MODIFIER|DVL1|ENSG00000107404|transcript|ENST00000634054.1|retained_intron||n.*333delA|||||333|,C|downstream_gene_variant|MODIFIER|MIR6808|ENSG00000284372|transcript|ENST00000616525.1|miRNA||n.*1649delA|||||1649|;LOF=(DVL1|ENSG00000107404|7|0.43)	GT:GS:BAF:LRR	0/0:0.3010:0.0060598357:-0.04165465
1	1338086	rs797044838	AC	A	.	PASS	ANN=A|frameshift_variant|HIGH|DVL1|ENSG00000107404|transcript|ENST00000378891.9|protein_coding|14/15|c.1529delG|p.Gly510fs|1576/2926|1529/2013|510/670||,A|frameshift_variant|HIGH|DVL1|ENSG00000107404|transcript|ENST00000378888.10|protein_coding|14/15|c.1604delG|p.Gly535fs|1957/3305|1604/2088|535/695||,A|frameshift_variant|HIGH|DVL1|ENSG00000107404|transcript|ENST00000632445.1|protein_coding|4/6|c.533delG|p.Gly178fs|533/785|533/654|178/217||WARNING_TRANSCRIPT_NO_START_CODON,A|frameshift_variant|HIGH|DVL1|ENSG00000107404|transcript|ENST00000631679.1|protein_coding|7/8|c.635delG|p.Gly212fs|635/778|635/756|212/251||WARNING_TRANSCRIPT_NO_START_CODON,A|downstream_gene_variant|MODIFIER|TAS1R3|ENSG00000169962|transcript|ENST00000339381.6|protein_coding||c.*3623delC|||||2773|,A|downstream_gene_variant|MODIFIER|DVL1|ENSG00000107404|transcript|ENST00000472445.1|retained_intron||n.*3683delG|||||3683|,A|downstream_gene_variant|MODIFIER|DVL1|ENSG00000107404|transcript|ENST00000633096.1|retained_intron||n.*1405delG|||||1405|,A|downstream_gene_variant|MODIFIER|DVL1|ENSG00000107404|transcript|ENST00000634054.1|retained_intron||n.*247delG|||||247|,A|downstream_gene_variant|MODIFIER|MIR6808|ENSG00000284372|transcript|ENST00000616525.1|miRNA||n.*1563delG|||||1563|;LOF=(DVL1|ENSG00000107404|7|0.57)	GT:GS:BAF:LRR	0/0:0.5086:0:-0.14043668
1	1338096	rs797044835	CA	C	.	PASS	ANN=C|frameshift_variant|HIGH|DVL1|ENSG00000107404|transcript|ENST00000378891.9|protein_coding|14/15|c.1519delT|p.Trp507fs|1566/2926|1519/2013|507/670||,C|frameshift_variant|HIGH|DVL1|ENSG00000107404|transcript|ENST00000378888.10|protein_coding|14/15|c.1594delT|p.Trp532fs|1947/3305|1594/2088|532/695||,C|frameshift_variant|HIGH|DVL1|ENSG00000107404|transcript|ENST00000632445.1|protein_coding|4/6|c.523delT|p.Trp175fs|523/785|523/654|175/217||WARNING_TRANSCRIPT_NO_START_CODON,C|frameshift_variant|HIGH|DVL1|ENSG00000107404|transcript|ENST00000631679.1|protein_coding|7/8|c.625delT|p.Trp209fs|625/778|625/756|209/251||WARNING_TRANSCRIPT_NO_START_CODON,C|downstream_gene_variant|MODIFIER|TAS1R3|ENSG00000169962|transcript|ENST00000339381.6|protein_coding||c.*3633delA|||||2783|,C|downstream_gene_variant|MODIFIER|DVL1|ENSG00000107404|transcript|ENST00000472445.1|retained_intron||n.*3673delT|||||3673|,C|downstream_gene_variant|MODIFIER|DVL1|ENSG00000107404|transcript|ENST00000633096.1|retained_intron||n.*1395delT|||||1395|,C|downstream_gene_variant|MODIFIER|DVL1|ENSG00000107404|transcript|ENST00000634054.1|retained_intron||n.*237delT|||||237|,C|downstream_gene_variant|MODIFIER|MIR6808|ENSG00000284372|transcript|ENST00000616525.1|miRNA||n.*1553delT|||||1553|;LOF=(DVL1|ENSG00000107404|7|0.57)	GT:GS:BAF:LRR	0/0:0.4713:0:0.2488735
1	1338098	rs797044834	GGGGGCAGCCGGGT	G	.	PASS	ANN=G|frameshift_variant|HIGH|DVL1|ENSG00000107404|transcript|ENST00000378891.9|protein_coding|14/15|c.1505_1517delACCCGGCTGCCCC|p.His502fs|1564/2926|1505/2013|502/670||,G|frameshift_variant|HIGH|DVL1|ENSG00000107404|transcript|ENST00000378888.10|protein_coding|14/15|c.1580_1592delACCCGGCTGCCCC|p.His527fs|1945/3305|1580/2088|527/695||,G|frameshift_variant|HIGH|DVL1|ENSG00000107404|transcript|ENST00000632445.1|protein_coding|4/6|c.509_521delACCCGGCTGCCCC|p.His170fs|521/785|509/654|170/217||WARNING_TRANSCRIPT_NO_START_CODON,G|frameshift_variant|HIGH|DVL1|ENSG00000107404|transcript|ENST00000631679.1|protein_coding|7/8|c.611_623delACCCGGCTGCCCC|p.His204fs|623/778|611/756|204/251||WARNING_TRANSCRIPT_NO_START_CODON,G|downstream_gene_variant|MODIFIER|TAS1R3|ENSG00000169962|transcript|ENST00000339381.6|protein_coding||c.*3635_*3647delGGGGCAGCCGGGT|||||2785|,G|downstream_gene_variant|MODIFIER|DVL1|ENSG00000107404|transcript|ENST00000472445.1|retained_intron||n.*3659_*3671delACCCGGCTGCCCC|||||3671|,G|downstream_gene_variant|MODIFIER|DVL1|ENSG00000107404|transcript|ENST00000633096.1|retained_intron||n.*1381_*1393delACCCGGCTGCCCC|||||1393|,G|downstream_gene_variant|MODIFIER|DVL1|ENSG00000107404|transcript|ENST00000634054.1|retained_intron||n.*223_*235delACCCGGCTGCCCC|||||235|,G|downstream_gene_variant|MODIFIER|MIR6808|ENSG00000284372|transcript|ENST00000616525.1|miRNA||n.*1539_*1551delACCCGGCTGCCCC|||||1551|;LOF=(DVL1|ENSG00000107404|7|0.57)	GT:GS:BAF:LRR	0/0:0.3364:0:0.02459389
`

**Comment by celine-weng** [comment]
I realized that after I further filter my vcf file, I got no WARNING when I run the vep. Is this the problem with certain line in my vcf files?

**Comment by celine-weng** [comment]
After further trials, I found out that only this line showing warning:

> <!DOCTYPE html>

<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 7.3.7.2 (Linux)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Liberation Sans"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>

#CHROM | POS | ID | REF | ALT | FORMAT | 202485320131_R03C01
-- | -- | -- | -- | -- | -- | --
17 | 59169809 | 17:57247170 | C | CA | GT:GS:BAF:LRR | 0/0:0.3868:0.00657749:-0.0648169


</body>

</html>

**Comment by celine-weng** [comment]
I have found the problem is within our vcf file, not in the vep program, thank you!

**Comment by celine-weng** [comment]
I have found the problem is within our vcf file, not with the vep program, thank you!
