### ISSUE TITLE
SIFT score source

### ISSUE THREAD

**Issue by jonahcullen** [Ensembl/ensembl-vep#1634]
## Describe the issue
Hello, I have been looking at available SIFT scores and was unable to track down from where exactly they came.

## Additional information
For example, dog (CanFam3.1) has a SIFT score of 0.05 for Chr1:928646 T/C (rs850738376) based on the variant table of gene CTDP1 (image below).

![Screenshot 2024-03-12 at 9 42 58 AM](https://github.com/Ensembl/ensembl-vep/assets/38636272/1f4a7200-04d2-4fab-bbd3-21535e7651b5)

When I pull down the most recent SIFT archive for [CanFam3](https://sift.bii.a-star.edu.sg/sift4g/public//Canis_familiaris/), that position and T/C has a score of 0.296.

```
928646  T       A       ENSCAFT00000000012      ENSCAFG00000000010      CTDP1   CDS     K       M       262     0.009   2.52    35      novel
928646  T       C       ENSCAFT00000000012      ENSCAFG00000000010      CTDP1   CDS     K       R       262     0.296   2.52    35      novel
928646  T       G       ENSCAFT00000000012      ENSCAFG00000000010      CTDP1   CDS     K       T       262     0.029   2.52    35      novel
928646  T       T       ENSCAFT00000000012      ENSCAFG00000000010      CTDP1   CDS     K       K       262     1.000   2.52    35      ref
```

Are these scores further processed from the SIFT server or is there additional information needed to get from a 0.296 to a 0.05?

**Comment by olaaustine** [comment]
Hi @jonahcullen, 
Hope this meets you well? 
We run our version of the SIFT software to generate our scores also the version of the software being used by us and the score archives mentioned is different as we use [SIFT](https://www.ensembl.org/info/genome/variation/prediction/protein_function.html#:~:text=and%20filtering%20options.-,SIFT,-SIFT%20predicts%20whether) and [ SIFT4G](https://github.com/rvaser/sift4g) was used by the score archives, which may account for the differences in the scores. 
Please let us know if this helps. 
Thank you very much. 
Ola.

**Comment by jonahcullen** [comment]
Hello, I think I am still confused as to where the scores originate. Is there not a more raw input somewhere for any of the species listed? For example, from the link you provided above
```
We ran SIFT version 6.2.1 following the instructions from the authors and used SIFT to choose homologous proteins rather than supplying them ourselves.
```
From where does data come?

Thanks again,
Jonah.

**Comment by olaaustine** [comment]
Hi @jonahcullen, 
We use the software SIFT version  6.2.1, we use the algorithm created by the SIFT authors to generate the data. 
The software version we use can be gotten [here](https://s3.amazonaws.com/sift-public/nsSNV/sift6.2.1.tar.gz).
The protein sequences used was the  UniRef90 (release 2014_11). 
Please let us know if this answers all your questions or if you have more questions. 
Thank you 
Ola.

**Comment by jonahcullen** [comment]
Okay. Are the scores VEP creates available outside the downloadable cache's for example in bed format somewhere?

**Comment by olaaustine** [comment]
Hi @jonahcullen, 
No, the scores are only available from the downloadable cache and on the website. 
They are also available when you run VEP. 
Let us know if you have any other questions. 
Thank you 
Ola.

**Comment by jonahcullen** [comment]
The scores would be great to get. Where are the scores available on the website?

**Comment by olaaustine** [comment]
Hi @jonahcullen, 
We do not publish the SIFT scores in any other format, like above (screenshot) you can search for a particular variants and check if it has SIFT scores associated with it. 
Thank you so much. 
Ola.

**Comment by olaaustine** [comment]
Hi @jonahcullen, 
Hope this meets you well? 
I am going to close this ticket now. Please do open another ticket or you can reopen this ticket if you have any other queries.
Thank you so much 
Ola.
