### ISSUE TITLE
`--mirna` not providing results for RefSeq transcript source

### ISSUE THREAD

**Issue by dennishendriksen** [Ensembl/ensembl-vep#1644]
I've been trying to get VEP v111 to output miRNA results when using the RefSeq cache without success. Using the VEP web interface with `rs569478349` and `--mirna` shows that the Ensembl transcript source does provide results:

![image](https://github.com/Ensembl/ensembl-vep/assets/2477186/9258216e-043e-49d8-abbb-09d9b78f2815)

Should the `--mirna` work for RefSeq transcript source?

**Comment by jamie-m-a** [comment]
Hi @dennishendriksen 

I'm sorry for the slow response, I'm catching up on some tickets that I missed.

In short, we think this should be working as you imagine. We have the relevant refseq transcript in our database and it is assigned the miRNA biotype. We will investigate why it isn't picking up the miRNA attribute from the VEP cache and get back to you.

**Comment by jamie-m-a** [comment]
Hi @dennishendriksen 

Following up on this - I was incorrect, we don't store the secondary structure information for the refseq miRNA transcripts, so this is why you are not finding it for this case. I will add a ticket to update our documentation of the --mirna option to make that explicit.
