### ISSUE TITLE
Custom VCF w/overlap joins multiple FILTER values for a record with same delimiter ("&") as other records

### ISSUE THREAD

**Issue by davmlaw** [Ensembl/ensembl-vep#1646]
## Describe the issue

When ```--custom``` is used with overlap, it can return multiple records. INFO values from the multiple records are joined with "&"

Multiple FILTER values for the *SAME VCF record* are also converted to using the same delimiter ("&") which means you lose track of what record it came from. 

For instance if you annotate the test VCF provided against an annotation file:

```
chr1	13203398	gnomAD-SV_v3_DEL_chr1_cf5f2df8	N	<DEL:ME:LINE1>	348	HIGH_NCR;UNRESOLVED
chr1	13203534	gnomAD-SV_v3_DEL_chr1_52ee315d	N	<DEL:ME:LINE1>	175	UNRESOLVED
```

It outputs the equivalent of:

```
gnomAD_SV=gnomAD-SV_v3_DEL_chr1_cf5f2df8&gnomAD-SV_v3_DEL_chr1_52ee315d
gnomAD_SV_FILTER=HIGH_NCR&UNRESOLVED&UNRESOLVED
```

There should be 2 values for every field, but in gnomAD_SV_FILTER there are 3

This means that you can't match FILTER records to other records as the array sizes are different.

### System
- VEP version: 110

### Full VEP command line
```
vep -i input_sv.vcf -o vep_out.vcf --cache --dir /data/annotation/VEP/vep_cache --fasta /data/annotation/fasta/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --assembly GRCh38 --offline --use_given_ref --vcf --force_overwrite --flag_pick --exclude_predicted --no_stats --check_existing --no_escape --sift b --hgvs --symbol --numbers --domains --canonical --protein --biotype --transcript_version --af --pubmed --variant_class --distance 5000 --refseq --custom file=gnomad_sv_grch38_example.vcf.gz,short_name=gnomAD_SV,format=vcf,type=overlap,overlap_cutoff=80,same_type=1,fields=AC%AF%FILTER
```

Attached ZIP containing input VCF, output VCF and 2 record custom annotation VCF w/multiple filters for 1 recrd

[custom_vcf_join.zip](https://github.com/Ensembl/ensembl-vep/files/14766251/custom_vcf_join.zip)

**Comment by nakib103** [comment]
Hello @davmlaw,

Thanks for your query and I can re-produce the issue. I think it is coming from some conversion logic in our VCF output representation. Any `,` in CSQ INFO field is converted to `&` as `,` is used to separates each consequence results. This issue persist in other output formats too.

We will have to look into it if there is any better separator to represent this case. 

Best regards,
Nakib

**Comment by nakib103** [comment]
Hello @davmlaw,

We have added a fix for this issue and will be available on next release (e113). 
So, instead of getting `HIGH_NCR&UNRESOLVED&UNRESOLVED` you will get `HIGH_NCR%3BUNRESOLVED&UNRESOLVED` (we cannot use `;` as it has meaning in the VCF and would disrupt the parsing, so we are using the ACII value instead).

I will close this issue but feel free to open a new one if needed.
