### ISSUE TITLE
Normalization of VCF file

### ISSUE THREAD

**Issue by celine-weng** [Ensembl/ensembl-vep#1647]
Hi,

Since my vcf file is left-normalized, do I need to conduct normalization before I process my file?

Thank you

**Comment by nakib103** [comment]
Hi @celine-weng,

Thanks for your query!

If your variant is already left-normalized you might also look at minimising the alleles. This article is very helpful to understand this -
https://genome.sph.umich.edu/wiki/Variant_Normalization

VEP does not minimise alleles by default but you can provide `--minimise` option to let VEP know to do this task for you (see [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_minimal)). 

Hope that answers your query.

Best regards,
Nakib
