### ISSUE TITLE
VEP version 111 outputs HGVSp duplications not following the 3' rule in regions of repeated aminoacids

### ISSUE THREAD

**Issue by jperales** [Ensembl/ensembl-vep#1654]
The positions of HGVSp duplications in regions with repeats of the same aminoacid are shift 1 position towards the N-terminal in VEP version 111. As far as I understand from the HGVS documentation, this does not follow the 3' rule:

> for all descriptions, the most C-terminal position possible of the reference sequence is arbitrarily assigned to have been changed (3'rule). Source: https://hgvs-nomenclature.org/stable/recommendations/protein/duplication/, Notes section.

Moreover, I noticed that VEP version 104 was correctly annotating these cases. The potential bug was introduced at some point later. See an example below:

## Input (VCF format)
```
chr16 12009530 . C CCCG . . .
```

### VEP version 104
```
❯ vep --no_stats --fasta [PATH]/GRCh37.p5_all.fa -id "chr16 12009530 . C CCCG . . ." -o "STDOUT" --tab --force_overwrite --assembly GRCh37 --symbol --numbers --hgvs --hgvsg --offline | grep -v '##' | cut -f 1,2,3,24 | sort | uniq
#Uploaded_variation     Location        Allele  HGVSp
chr16_12009531_-/CCG    chr16:12009530-12009531 CCG     -
chr16_12009531_-/CCG    chr16:12009530-12009531 CCG     ENSP00000398131.2:p.Gly16dup
chr16_12009531_-/CCG    chr16:12009530-12009531 CCG     ENSP00000408399.2:p.Gly16dup
```

### VEP version 111
```
❯ vep --no_stats --fasta [PATH]/GRCh37.p5_all.fa -id "chr16 12009530 . C CCCG . . ." -o "STDOUT" --tab --force_overwrite --assembly GRCh37 --symbol --numbers --hgvs --hgvsg --offline | grep -v '##' | cut -f 1,2,3,24 | sort | uniq
#Uploaded_variation     Location        Allele  HGVSp
chr16_12009531_-/CCG    chr16:12009530-12009531 CCG     -
chr16_12009531_-/CCG    chr16:12009530-12009531 CCG     ENSP00000398131.2:p.Gly15dup
chr16_12009531_-/CCG    chr16:12009530-12009531 CCG     ENSP00000408399.2:p.Gly15dup
```

Please note the difference ENSP00000398131.2:p.Gly16dup Vs.  ENSP00000398131.2:p.Gly15dup (VEP 104 & VEP 111 respectively).

The [ENSP00000398131.2](https://www.ensembl.org/Homo_sapiens/Transcript/ProteinSummary?db=core;g=ENSG00000103342;r=16:11868128-11916082;t=ENST00000434724) protein matches [P15170-3](http://www.uniprot.org/uniprot/P15170-3)) with the following aminoacid sequence (see the mark at position 16 which is the most C-terminal):

```
           Gly16
               |
MDPGSGGGGGGGGGGGSSSGSSSSDSAPDCWDQADMEAPGPGPCGGGGSLAAAAEAQRENLSAAFSRQLNVNAKPFVPNVHAAEFVPSFLRGPAAPPPPVGGAANNHGAGSGAGGRAAPVESSQEEQSLCEGSNSAVSMELSEPIVENGETEMSPEESWEHKEEISEAEPGGGSLGDGRPPEESAHEMMEEEEEIPKPKSVVAPPGAPKKEHVNVVFIGHVDAGKSTIGGQIMYLTGMVDKRTLEKYEREAKEKNRETWYLSWALDTNQEERDKGKTVEVGRAYFETEKKHFTILDAPGHKSFVPNMIGGASQADLAVLVISARKGEFETGFEKGGQTREHAMLAKTAGVKHLIVLINKMDDPTVNWSNERYEECKEKLVPFLKKVGFNPKKDIHFMPCSGLTGANLKEQSDFCPWYIGLPFIPYLDNLPNFNRSVDGPIRLPIVDKYKDMGTVVLGKLESGSICKGQQLVMMPNKHNVEVLGILSDDVETDTVAPGENLKIRLKGIEEEEILPGFILCDPNNLCHSGRTFDAQIVIIEHKSIICPGYNAVLHIHTCIEEVEITALICLVDKKSGEKSKTRPRFVKQDQVCIARLRTAGTICLETFKDFPQMGRFTLRDEGKTIAIGKVLKLVPEKD
```

Thus it seems that the 3' rule was correctly applied in VEP version 104 but a potential bug has been introduced later and detected in VEP version 111.

### System
- VEP version: 111 ; as compared to 104
- VEP Cache version: none
- Perl version: 5.22
- OS:  CentOS
- tabix installed

### Full VEP command line
```
vep --no_stats --fasta [PATH]/GRCh37.p5_all.fa -id "chr16 12009530 . C CCCG . . ." -o "STDOUT" --tab --force_overwrite --assembly GRCh37 --symbol --numbers --hgvs --hgvsg --offline
```

### Full error message
None

### Data files
Inline examples are provided and VEP run in offline mode with assembly cache.

**Comment by nuno-agostinho** [comment]
Hi @jperales,

Thanks for pointing out this issue. I can confirm that, while this is a problem in VEP 110 and 111, it has already been fixed for VEP 112 with PR https://github.com/Ensembl/ensembl-variation/pull/1061.

The result is as shown:
```
## HGVSp : HGVS protein sequence name
chr16_12009531_-/CCG	chr16:12009530-12009531	CCG	ENSG00000103342	ENST00000434724	Transcript	inframe_insertion	247-248	47-48	16	G/Gggg/ggCGGg	-	IMPACT=MODERATE;STRAND=-1;HGVSc=ENST00000434724.2:c.47_48insCGG;HGVSp=ENSP00000398131.2:p.Gly16dup
chr16_12009531_-/CCG	chr16:12009530-12009531	CCG	ENSG00000103342	ENST00000439887	Transcript	inframe_insertion	205-206	47-48	16	G/Gggg/ggCGGg	-	IMPACT=MODERATE;STRAND=-1;HGVSc=ENST00000439887.2:c.47_48insCGG;HGVSp=ENSP00000408399.2:p.Gly16dup
```

This fix will be available in the next VEP release (112). Thank you for your report!

Best regards,
Nuno
