### ISSUE TITLE
Use of uninitialized value at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/IO/Parser/GTF.pm

### ISSUE THREAD

**Issue by RanWei1987** [Ensembl/ensembl-vep#1656]
Hello,

When running the VEP docker for VCF annotation using customized ref genome and annotation GTF file, I keep receiving this kind of warning:

```
Use of uninitialized value $key in substitution (s///) at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/IO/Parser/GTF.pm line 122, <__ANONIO__> line 381.
Use of uninitialized value $key in substitution (s///) at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/IO/Parser/GTF.pm line 123, <__ANONIO__> line 381.
Use of uninitialized value $key in hash element at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/IO/Parser/GTF.pm line 124, <__ANONIO__> line 381.

```
The command I used is:
`docker run ensemblorg/ensembl-vep vep --input_file test.vcf.gz --output_file test.vep.vcf --fasta ref_genome.fa --gtf ref_annot.sorted_clean.gtf.gz --pick`

The content of test.vcf.gz is:
```
chr1    2488153 .       A       G       .       .       AS_SB_TABLE=0,0|233,204;DP=445;ECNT=1;MBQ=0,20;MFRL=0,171;MMQ=60,60;MPOS=34;POPAF=7.3;TLOD=1279.02      GT:AD:AF:DP:F1R2:F2R1:SB        0/1:0,437:0.997:437:0,220:0,215:0,0,233,204
chr1    9784337 .       T       G       .       .       AS_SB_TABLE=220,204|2,33;DP=464;ECNT=1;MBQ=20,11;MFRL=252,203;MMQ=60,60;MPOS=31;POPAF=7.3;TLOD=4.87     GT:AD:AF:DP:F1R2:F2R1:SB        0/1:424,35:0.022:459:116,4:166,2:220,204,2,33
chr1    11205058        .       C       T       .       .       AS_SB_TABLE=82,89|63,70;DP=317;ECNT=1;MBQ=20,20;MFRL=189,189;MMQ=60,60;MPOS=34;POPAF=7.3;TLOD=340.27    GT:AD:AF:DP:F1R2:F2R1:SB        0/1:171,133:0.445:304:100,59:70,71:82,89,63,70
```

Head of the gtf as an example is:

```
chr1    BestRefSeq      exon    11874   12227   .       +       .       gene_id "DDX11L1"; transcript_id "NR_046018.2"; db_xref "GeneID:100287102"; gene "DDX11L1"; product "DEAD/H-box helicase 11 like 1 (pseudogene)"; pseudo "true"; transcript_biotype "transcript"; exon_number "1"; 
chr1    BestRefSeq      gene    11874   14409   .       +       .       gene_id "DDX11L1"; transcript_id ""; db_xref "GeneID:100287102"; db_xref "HGNC:HGNC:37102"; description "DEAD/H-box helicase 11 like 1 (pseudogene)"; gbkey "Gene"; gene "DDX11L1"; gene_biotype "transcribed_pseudogene"; pseudo "true"; 
```

The 3 lines of VCF results in ~9000 lines of warnings that simply repeat the 3 lines of "Use of uninitialized value" information above. But, I can still get the VCP annotated VCF (test.vep.vcf):

```
#Uploaded_variation     Location        Allele  Gene    Feature Feature_type    Consequence     cDNA_position   CDS_position    Protein_position        Amino_acids     Codons  Existing_variation      Extra
chr1_2488153_A/G        chr1:2488153    G       TNFRSF14        NM_003820.4     Transcript      missense_variant        344     50      17      K/R     aAa/aGa -       IMPACT=MODERATE;STRAND=1;SOURCE=ref_annot.sorted.gtf.gz
chr1_9784337_T/G        chr1:9784337    G       PIK3CD  NM_005026.5     Transcript      missense_variant        2931    2722    908     F/V     Ttc/Gtc -       IMPACT=MODERATE;STRAND=1;SOURCE=ref_annot.sorted.gtf.gz
chr1_11205058_C/T       chr1:11205058   T       MTOR    NM_001386500.1  Transcript      synonymous_variant      4879    4731    1577    A       gcG/gcA -       IMPACT=LOW;STRAND=-1;SOURCE=ref_annot.sorted.gtf.gz
```

I used the most recent version of VEP docker from https://hub.docker.com/r/ensemblorg/ensembl-vep. Please let me know if these warnings are ignorable. Thanks a lot!

**Comment by nuno-agostinho** [comment]
Hey @RanWei1987,

I am sorry for the inconvenience.

The issue seems related with the GTF annotation. Could you tell me where did you get the GTF from so I can try running VEP with that file? Thank you.

Best regards,
Nuno

**Comment by RanWei1987** [comment]
Hi Nuno,

The GTF is a revised version of GCF_000001405.25_GRCh37.p13_genomic.gtf from NCBI. The way to represent chromosomes are changed from "NC_" to chr1-22, and removed transcripts initiated with "XM_" and "XR_". Please find the zipped folder attached. It includes a vcf file with 3 variants from chr22 and the GTF with only chr22 information, together with their indices. Running 
`docker run ensemblorg/ensembl-vep vep --input_file test.vcf.gz --output_file test.vep.vcf --fasta ref_genome.fa --gtf chr22.sorted.gtf.gz --pick` would produce the error information listed in the beginning of this thread.
[vep_problem.zip](https://github.com/Ensembl/ensembl-vep/files/14962435/vep_problem.zip)

**Comment by nuno-agostinho** [comment]
Hi @RanWei1987,

This is a bug because your GTF attributes end with a space after the last delimeter (`; `) and the parser incorrectly tries to get more information, resulting in those warnings.

Fortunately, you can safely ignore the warnings for now, all the GTF attributes are retrieved as expected and the output also includes all the information.

I am already working on a fix to avoid this warning in future versions of VEP: https://github.com/Ensembl/ensembl-io/pull/161. Thanks for pointing it out!

Best regards,
Nuno

**Comment by RanWei1987** [comment]
Thank you so much Nuno!
