### ISSUE TITLE
Can't locate Bio/EnsEMBL/Utils/Exception.pm in @INC 

### ISSUE THREAD

**Issue by jooY-Jeong** [Ensembl/ensembl-vep#1657]
## Describe the issue
Hello, i got a problem.

until now, i input the following commands for installing VEP.

git clone https://github.com/Ensembl/ensembl-vep.git
cd ensembl-vep

And when i input "perl INSTALL.pl" command, the following error occurred.
__________________________________________________________________________________________________________________

Can't locate Bio/EnsEMBL/Utils/Exception.pm in @INC (you may need to install the Bio::EnsEMBL::Utils::Exception module) (@INC contains: /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl /home/ext/Extended_02/JJY/ensembl-vep/ensembl-variation/modules /home/ext/Extended_02/JJY/ensembl/modules /home/ext/Extended_02/JJY/ensembl-vep/modules /home/ext/Extended_02/JJY/ensembl-vep/modules /home/ext/Extended_02/JJY/ensembl-vep/modules/Bio/EnsEMBL/VEP /path/to/ensembl-vep/modules /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl /home/share/miniconda3/envs/vetbio/lib/perl5/site_perl /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/vendor_perl /home/share/miniconda3/envs/vetbio/lib/perl5/vendor_perl /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/core_perl /home/share/miniconda3/envs/vetbio/lib/perl5/core_perl .) at /home/ext/Extended_02/JJY/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 64.
BEGIN failed--compilation aborted at /home/ext/Extended_02/JJY/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 64.
Compilation failed in require at /home/share/miniconda3/envs/vetbio/lib/perl5/vendor_perl/lib.pm line 6.
BEGIN failed--compilation aborted at /home/share/miniconda3/envs/vetbio/lib/perl5/vendor_perl/lib.pm line 6.
Compilation failed in require at INSTALL.pl line 40.
BEGIN failed--compilation aborted at INSTALL.pl line 40.

__________________________________________________________________________________________________________________

To solve this problem, I tried the following methods that I thought, but it was not solved.
__________________________________________________________________________________________________________________

export LD_LIBRARY_PATH=/home/share/miniconda3/envs/vetbio/lib:$LD_LIBRARY_PATH
export PERL5LIB=/home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl:$PERL5LIB
cpan install DBD::mysql
cpan install DBI
conda install -c bioconda perl-dbd-mysql
sudo apt-get update
sudo apt-get install --reinstall curl
sudo apt-get install --reinstall ca-certificates
cpan install LWP::Simple HTTP::Tiny
git config --global --add safe.directory /home/ext/Extended_02/JJY/ensembl-vep
export PERL5LIB=/home/ext/Extended_02/JJY/ensembl-vep/modules/Bio/EnsEMBL/VEP:$PERL5LIB
__________________________________________________________________________________________________________________

When i enter the "cpan" and "cpanm" commands simply, i got the similar error as the one above.

I use VScode, and i share space with coworker.

I have plan to solve this problem and install VEP to finally use the VCF2MAF tool.

I'm a beginner in bioinformatics, so there are a lot of things I'm not familiar with. sorry to poor skilled..

I would be very grateful if help me.

### Full error message
> /home/ext/Extended_02/JJY/ensembl-vep$ perl INSTALL.pl
Can't locate Bio/EnsEMBL/Utils/Exception.pm in @INC (you may need to install the Bio::EnsEMBL::Utils::Exception module) (@INC contains: /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl /home/ext/Extended_02/JJY/ensembl-vep/ensembl-variation/modules /home/ext/Extended_02/JJY/ensembl/modules /home/ext/Extended_02/JJY/ensembl-vep/modules /home/ext/Extended_02/JJY/ensembl-vep/modules /home/ext/Extended_02/JJY/ensembl-vep/modules/Bio/EnsEMBL/VEP /path/to/ensembl-vep/modules /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl /home/share/miniconda3/envs/vetbio/lib/perl5/site_perl /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/vendor_perl /home/share/miniconda3/envs/vetbio/lib/perl5/vendor_perl /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/core_perl /home/share/miniconda3/envs/vetbio/lib/perl5/core_perl .) at /home/ext/Extended_02/JJY/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 64.
BEGIN failed--compilation aborted at /home/ext/Extended_02/JJY/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 64.
Compilation failed in require at /home/share/miniconda3/envs/vetbio/lib/perl5/vendor_perl/lib.pm line 6.
BEGIN failed--compilation aborted at /home/share/miniconda3/envs/vetbio/lib/perl5/vendor_perl/lib.pm line 6.
Compilation failed in require at INSTALL.pl line 40.
BEGIN failed--compilation aborted at INSTALL.pl line 40.

> /home/ext/Extended_02/JJY/ensembl-vep$ cpan
Can't locate Bio/EnsEMBL/Utils/Exception.pm in @INC (you may need to install the Bio::EnsEMBL::Utils::Exception module) (@INC contains: /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl /home/ext/Extended_02/JJY/ensembl-vep/ensembl-variation/modules /home/ext/Extended_02/JJY/ensembl/modules /home/ext/Extended_02/JJY/ensembl-vep/modules /home/ext/Extended_02/JJY/ensembl-vep/modules /home/ext/Extended_02/JJY/ensembl-vep/modules/Bio/EnsEMBL/VEP /path/to/ensembl-vep/modules /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl /home/share/miniconda3/envs/vetbio/lib/perl5/site_perl /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/vendor_perl /home/share/miniconda3/envs/vetbio/lib/perl5/vendor_perl /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/core_perl /home/share/miniconda3/envs/vetbio/lib/perl5/core_perl) at /home/ext/Extended_02/JJY/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 64.
BEGIN failed--compilation aborted at /home/ext/Extended_02/JJY/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 64.
Compilation failed in require at /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/core_perl/Errno.pm line 11.
BEGIN failed--compilation aborted at /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/core_perl/Errno.pm line 11.
Compilation failed in require at /home/share/miniconda3/envs/vetbio/lib/perl5/core_perl/CPAN/FTP.pm line 6.
BEGIN failed--compilation aborted at /home/share/miniconda3/envs/vetbio/lib/perl5/core_perl/CPAN/FTP.pm line 6.
Compilation failed in require at /home/share/miniconda3/envs/vetbio/lib/perl5/core_perl/CPAN.pm line 28.
BEGIN failed--compilation aborted at /home/share/miniconda3/envs/vetbio/lib/perl5/core_perl/CPAN.pm line 28.
Compilation failed in require at /home/share/miniconda3/envs/vetbio/lib/perl5/core_perl/App/Cpan.pm line 290.
BEGIN failed--compilation aborted at /home/share/miniconda3/envs/vetbio/lib/perl5/core_perl/App/Cpan.pm line 290.
Compilation failed in require at /home/share/miniconda3/envs/vetbio/bin/cpan line 10.
BEGIN failed--compilation aborted at /home/share/miniconda3/envs/vetbio/bin/cpan line 10.

> /home/ext/Extended_02/JJY/ensembl-vep$ cpanm
Can't locate Bio/EnsEMBL/Utils/Exception.pm in @INC (you may need to install the Bio::EnsEMBL::Utils::Exception module) (@INC contains: FatPacked::94295533817656=HASH(0x55c2e3cc0f38) /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl /home/ext/Extended_02/JJY/ensembl-vep/ensembl-variation/modules /home/ext/Extended_02/JJY/ensembl/modules /home/ext/Extended_02/JJY/ensembl-vep/modules /home/ext/Extended_02/JJY/ensembl-vep/modules /home/ext/Extended_02/JJY/ensembl-vep/modules/Bio/EnsEMBL/VEP /path/to/ensembl-vep/modules /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/site_perl /home/share/miniconda3/envs/vetbio/lib/perl5/site_perl /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/vendor_perl /home/share/miniconda3/envs/vetbio/lib/perl5/vendor_perl /home/share/miniconda3/envs/vetbio/lib/perl5/5.32/core_perl /home/share/miniconda3/envs/vetbio/lib/perl5/core_perl .) at /home/ext/Extended_02/JJY/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 64.
BEGIN failed--compilation aborted at /home/ext/Extended_02/JJY/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 64.
Compilation failed in require at /home/share/miniconda3/envs/vetbio/bin/cpanm line 32.
BEGIN failed--compilation aborted at /home/share/miniconda3/envs/vetbio/bin/cpanm line 32.
Compilation failed in require at /home/share/miniconda3/envs/vetbio/bin/cpanm line 499.
BEGIN failed--compilation aborted at /home/share/miniconda3/envs/vetbio/bin/cpanm line 499.

**Comment by olaaustine** [comment]
Hi @jooY-Jeong, 

Thank you for your query.

We don't actively support VEP in conda as it's not an installation we have created (and so there could be any number of potential issues specific to a users system and environment that would be very hard for us to debug).

We would instead recommend using the containerised version of VEP we do support - full details here: https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker

Please let us know if this helps.

Thank you
Ola.

**Comment by jooY-Jeong** [comment]
i thought it works!
thank you to help!
