### ISSUE TITLE
Homo Sapiens GRCH38 Merged Cache Installation Failing on CHECKSUMS

### ISSUE THREAD

**Issue by sharra44** [Ensembl/ensembl-vep#1658]
I am doing a fresh installation of VEP on AlmaLinux 8 and while trying to install the cache am getting the following error:
NB: Remember to use --merged when running the VEP with this cache!
 - downloading https://ftp.ensembl.org/pub/release-111/variation/indexed_vep_cache/homo_sapiens_merged_vep_111_GRCh38.tar.gz
ERROR: checksum for /root/.vep/tmp/homo_sapiens_merged_vep_111_GRCh38.tar.gz doesn't match checksum in CHECKSUMS file on FTP site

### System
- VEP version: 111
- VEP Cache version: 111
- Perl version: 5.26.3
- OS: AlmaLinux 8
- tabix installed yes

### Full VEP command line
```
perl INSTALL.pl
```

**Comment by olaaustine** [comment]
Hi @sharra44, 

Hope you are well? 

Thank you for this query. 

Can you confirm what checksum utility is available on AlmaLinux 8 ? 
Also as a workaround can you manually download the cache.
` curl -O https://ftp.ensembl.org/pub/release-111/variation/vep/homo_sapiens_merged_vep_111_GRCh38.tar.gz`
 Documentation about this can be seen [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#:~:text=/vep_data-,curl%20%2DO%20https%3A//ftp.ensembl.org/pub/release%2D111/variation/vep/homo_sapiens_vep_111_GRCh38.tar.gz%0Atar%20xzf%20homo_sapiens_vep_111_GRCh38.tar.gz,-Ensembl%20release%20111)

Please let us know if this helps. 
Thank you, 
Ola.

**Comment by maxulysse** [comment]
Doing a fresh install as well, but on Linux Mint.
Tried to install `GRCh38`, and it failed with the `ERROR: checksum for 111_GRCh38/tmp/homo_sapiens_vep_111_GRCh38.tar.gz doesn't match checksum in CHECKSUMS file on FTP site` error as well.
No issue with `GRCh37` or `WBCel235`.

**Comment by olaaustine** [comment]
Hi @maxulysse, 

Thank you bringing this to our notice. 
We have fixed the issue in our CHECKSUMS file. 
Please redownload GRCh38 and let us know if this issue persists. 

Thank you so much, 
Ola.

**Comment by sharra44** [comment]
Hi,
I tried again, and had the same issue 
```
NB: Remember to use --merged when running the VEP with this cache!
 - downloading https://ftp.ensembl.org/pub/release-111/variation/indexed_vep_cache/homo_sapiens_merged_vep_111_GRCh38.tar.gz
ERROR: checksum for /root/.vep/tmp/homo_sapiens_merged_vep_111_GRCh38.tar.gz doesn't match checksum in CHECKSUMS file on FTP site
```
Additionally, similar to maxulysse, I am able to download GRCh37 with no problem, it is only GRCh38 merged which has the issue

**Comment by maxulysse** [comment]
@olaaustine I tried again, and same issue

**Comment by mvheetve** [comment]
Hi there, 

we are experiencing this issue as well.

**Comment by olaaustine** [comment]
Hi @maxulysse , @mvheetve, 
Thank you for your patience with this. 
Please can you try again and tell us if this issue still persists. 
Thank you so much 
Ola.

**Comment by mvheetve** [comment]
Hej Ola,

thanks for addressing this so quickly. Here's my output, I think this solves the issue. 

```
$ export VEP_DIR=${VSC_SCRATCH_VO_USER}/ensembl-vep
$ mkdir -p ${VEP_DIR}
$ cd ${VEP_DIR}
$ singularity exec -B ${VEP_DIR} ensembl-vep.sif INSTALL.pl -s homo_sapiens -y GRCh38 --CACHEDIR ${VEP_DIR} --CACHE_VERSION 111 --AUTO c --CONVERT --NO_BIOPERL --NO_TEST --NO_UPDATE
 - getting list of available cache files
 - downloading https://ftp.ensembl.org/pub/release-111/variation/indexed_vep_cache/homo_sapiens_vep_111_GRCh38.tar.gz
 - unpacking homo_sapiens_vep_111_GRCh38.tar.gz
 - converting cache, this may take some time but will allow VEP to look up variants and frequency data much faster
 - use CTRL-C to cancel if you do not wish to convert this cache now (you may run convert_cache.pl later)
2024-04-17 12:23:06 - Processing homo_sapiens
2024-04-17 12:23:06 - Processing version 111_GRCh38
2024-04-17 12:23:06 - No unprocessed types remaining, skipping
2024-04-17 12:23:06 - All done!

All done
```

Regards
Mattias

**Comment by maxulysse** [comment]
I think I'm good too.
