### ISSUE TITLE
docker file rest service

### ISSUE THREAD

**Issue by inodb** [Ensembl/ensembl-vep#166]
For cBioPortal (http://www.cbioportal.org/) we are using Genome Nexus (http://genomenexus.org/#/home) to annotate our date before importing, which talks to the Ensembl REST endpoint (http://grch37.rest.ensembl.org/). In order to not overload the Ensembl service it would be nice if there was a docker file for the rest service, so we can run our own. I'm happy to make this and send a PR to ensembl-rest repo - just wondering if there are any reasons other than time constraints why there isn't one already. Thank you!

**Comment by ens-lgil** [comment]
Dear @inodb,

I would suggest that you create an "Issue" to the https://github.com/Ensembl/ensembl-rest git repository as the Ensembl REST API is developped and maintained by an other team in the Ensembl Project.

Best regards,
Laurent

**Comment by ens-lgil** [comment]
Dear @inodb,

Sorry, I didn't see that the "Issues" tab wasn't visible on https://github.com/Ensembl/ensembl-rest.
It is now available on https://github.com/Ensembl/ensembl-rest.
Please, could you create an issue there ?

Thanks,
Laurent

**Comment by inodb** [comment]
Sure!
