### ISSUE TITLE
docker run issue and pm module missing

### ISSUE THREAD

**Issue by vyomesh4bcOnco** [Ensembl/ensembl-vep#1666]
## Describe the issue
The issue here seems to be that the VEP (Variant Effect Predictor) tool is unable to locate and load the required plugin, specifically dbNSFP4.1. The error message indicates that it failed to compile the plugin because it couldn't find the necessary Perl module (dbNSFP4.pm) in its expected location.

The plugin dbNSFP4.1 likely relies on the dbNSFP4.pm Perl module, which appears to be missing or not installed in the expected directory. The VEP tool expects to find this module in one of the directories listed in the @INC Perl array, which includes directories like /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 and /usr/share/perl/5.34.

To resolve this issue, you'll need to ensure that the dbNSFP4.pm module is correctly installed and accessible by the VEP tool. This may involve installing the missing Perl module or ensuring that it's available in one of the directories listed in the @INC array.

## Additional information
time sudo docker run -v $HOME/vep_data:/data ensemblorg/ensembl-vep vep --cache --offline --format vcf --vcf --force_overwrite --input_file test_samples.vcf --output_file test_samples_annot.txt  --plugin dbNSFP4.1,dbNSFP4.1a.txt.gz --pick
WARNING: Failed to compile plugin dbNSFP4.1: Can't locate [dbNSFP4.pm](http://dbnsfp4.pm/) in @INC (you may need to install the dbNSFP4 module) (@INC contains: /plugins /opt/vep/src/ensembl-vep/modules /opt/vep/src/ensembl-vep /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at (eval 42) line 2.

#Attempts to resolve:
We have kept dbNSFP4.pm module in the cache folder, its now working. Also,  /plugins /opt/vep/src/ensembl-vep/modules /opt/vep/src/ensembl-vep /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) this path are not found when the docker image is considered

**Comment by likhitha-surapaneni** [comment]
Hi @vyomesh4bcOnco,

The plugin name does not have versioning in it. The data can be downloaded according to the preferred version by following the docs [here](https://github.com/Ensembl/VEP_plugins/blob/release/111/dbNSFP.pm)
You may need to download the data to a mounted directory in order to use it with docker by following the docs [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker)

Kind regards,
Likhitha

**Comment by vyomesh4bcOnco** [comment]
Hi @likhitha-surapaneni ,

Tried it without the version to it does not run and show pm module error.. 
All the details are kept inside the mounted folder. however the path shown in error are not traceable while in docker

**Comment by likhitha-surapaneni** [comment]
Hi @vyomesh4bcOnco,

Can you please let us know the error encountered when the plugin name has no version?
Can you please check if the dbNSFP data has been downloaded properly? The usual link to download the file seems to be down, the file can also be downloaded from https://dbnsfp.s3.amazonaws.com/dbNSFP4.4a.zip. 

Thanks and regards, 
Likhitha

**Comment by vyomesh4bcOnco** [comment]
Hi @likhitha-surapaneni ,

Can you please let us know the error encountered when the plugin name has no version?
-->
time sudo docker run -v $HOME/vep_data:/data ensemblorg/ensembl-vep vep --cache --offline --format vcf --vcf --force_overwrite --input_file test_samples.vcf --output_file test_samples_annot.txt  --plugin dbNSFP,dbNSFP4.4a.txt.gz 
[sudo] password for bioinfo-b: 
WARNING: Failed to instantiate plugin dbNSFP: ERROR: No headers found before data

Can you please check if the dbNSFP data has been downloaded properly?
Yes, no truncation and unexpected error -->  tried with both versions 4.1 and 4.4

Attaching the Docker shell command used up until  now to set up the annotation pipeline for your reference.
[vep_cmd_vyomesh.txt](https://github.com/Ensembl/ensembl-vep/files/15137152/vep_cmd_vyomesh.txt)

**Comment by likhitha-surapaneni** [comment]
Hi @vyomesh4bcOnco ,

Thank you for providing the details, It seems like the header of dbNSFP file is not as expected. Can you please try these [preprocessing steps](https://github.com/Ensembl/VEP_plugins/blob/7df2b1c422f69d00c8c77276a2af54758ab959ce/dbNSFP.pm#L54-L66) instead and let us know if it fixes the issue?

**Comment by vyomesh4bcOnco** [comment]
Hi @likhitha-surapaneni,

Attempted to follow the preprocessing step, However it still shows the header issue.

Step performed are highlighted below:
Step 1: 
zgrep -h -v ^#chr dbNSFP4.4a_variant.chr* | awk '$8 != "." ' | sort -k8,8 -k9,9n - | cat - | bgzip -c > dbNSFP4.4a_grch37.gz
tabix -s 8 -b 9 -e 9 dbNSFP4.4a_grch37.gz

Step 2:
time sudo docker run -v $HOME/vep_data:/data ensemblorg/ensembl-vep vep --cache --offline --format vcf --vcf --force_overwrite --input_file homo_sapiens_GRCh37.vcf --output_file homosapiens37_annot.txt  --plugin dbNSFP,dbNSFP4.4a_grch37.gz,ALL
WARNING: Failed to instantiate plugin dbNSFP: ERROR: No headers found before data

Alternative with "ALL"
time sudo docker run -v $HOME/vep_data:/data ensemblorg/ensembl-vep vep --cache --offline --format vcf --vcf --force_overwrite --input_file homo_sapiens_GRCh37.vcf --output_file homosapiens37_annot.txt  --plugin dbNSFP,dbNSFP4.4a_grch37.gz
WARNING: Failed to instantiate plugin dbNSFP: ERROR: No headers found before data.

**Comment by likhitha-surapaneni** [comment]
Hi @vyomesh4bcOnco ,

Thank you for your patience. 

You can optionally use `fields [list]`([link](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#format)) to configure the output format using a comma separated list of fields. 
For example, `--vcf --fields "Allele,Consequence,Feature_type,Feature"` 

Kind regards,
Likhitha

**Comment by vyomesh4bcOnco** [comment]
> Hi @vyomesh4bcOnco ,
> 
> Thank you for your patience.
> 
> You can optionally use `fields [list]`([link](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#format)) to configure the output format using a comma separated list of fields. For example, `--vcf --fields "Allele,Consequence,Feature_type,Feature"`
> 
> Kind regards, Likhitha

Hi @likhitha-surapaneni,
Appreciated your help in de-coding VEP process.

I have one more query:
CLIN_SIG and Clinvar_clnSig they have different value for example
A missense variant for ALK chr2 29416572 T>C c.4381A>G  p.ile1461Val is highlighted likely_pathogenics&benign under CLIN_SIG &  benign under Clinvar_clnSig.

it would be helpful if you could provide some clarification on the above challenge.

Regards,
Vyomesh

**Comment by dglemos** [comment]
Hi @vyomesh4bcOnco,
`CLIN_SIG` is the ClinVar clinical significance annotated by VEP, however `Clinvar_clnSig` is not provided by VEP. Did you run other annotation with a different tool?

The VEP clinical significance `likely_pathogenic&benign` matches the following submissions:
[RCV000119976.11](https://www.ncbi.nlm.nih.gov/clinvar/RCV000119976.11/?redir=rcv): benign
[RCV000590065.1](https://www.ncbi.nlm.nih.gov/clinvar/RCV000590065.1/?redir=rcv): benign
[RCV000573143.2](https://www.ncbi.nlm.nih.gov/clinvar/RCV000573143.2/?redir=rcv): benign
[RCV000608829.21](https://www.ncbi.nlm.nih.gov/clinvar/RCV000608829.21/?redir=rcv): benign
[RCV001250949.1](https://www.ncbi.nlm.nih.gov/clinvar/RCV001250949.1/?redir=rcv): likely pathogenic -> this submission has no criteria provided

You can check the phenotype data in this table: https://www.ensembl.org/Homo_sapiens/Variation/Phenotype?db=core;r=2:29193206-29194206;v=rs1670283;vdb=variation;vf=89497988

**Comment by vyomesh4bcOnco** [comment]
Hi Team,

Noted with thanks.

Regards,
Vyomesh Javle

Vyomesh Javle

Team Lead - Clinical Bioinformatics
<https://www.linkedin.com/company/4basecare/>
<https://twitter.com/4baseCare>  <https://www.facebook.com/4basecare>
<https://www.instagram.com/4basecare_onco_solutions/>
<https://www.youtube.com/channel/UCTxWrSDbho9zHxBxPZ7KK0A>
+91 9022695551
***@***.***
www.4basecare.com <https://4basecare.com/>
India, Singapore
