### ISSUE TITLE
--safe option seems broken

### ISSUE THREAD

**Issue by bartcharbon** [Ensembl/ensembl-vep#1674]
When using VEP we always provide the "--safe" option, to ensure that an error is reported if a plugin fails.
However this seems to have stopped working, VEP reports a succesful run while a plugin (a new one I'm currently writing) crashes.
The error is written to the VEP logging.

We currently use VEP 111.0

**Comment by dglemos** [comment]
Hi @bartcharbon,
I'm glad you are working on a new plugin!
Did you try running the option `--safe` with another plugin ([one of these](https://github.com/Ensembl/VEP_plugins)) to check it fails when it's supposed to?
The option should have the same behaviour as previous releases.

**Comment by bartcharbon** [comment]
Hi @dglemos
Since I need te plugin to fail I find it hard to reproduce with exisiting plugins.

I created a minimalistic one instead:

```
package error;

use strict;
use warnings;

use Bio::EnsEMBL::Variation::Utils::BaseVepTabixPlugin;
use base qw(Bio::EnsEMBL::Variation::Utils::BaseVepTabixPlugin);

my $self;

sub new {
    if (!(defined $self)) {
        my $class = shift;
        $self = $class->SUPER::new(@_);
    }
  return $self;
}

sub feature_types {
  return ['Transcript'];
}

sub get_header_info {
    return {
      Test => "test"
    }
}

sub run {
  die "this should terminate the VEP run with --safe.";
  
  return {};
  };
1;
```

I would expect this to fail the VEP run, but it doesn't

The error does show up the logging:
WARNING: Plugin 'error' went wrong: this should terminate the VEP run with --safe. at /groups/umcg-gcc/tmp02/users/umcg-bcharbon/vip/resources/vep/plugins/error.pm line 30, <$fh> line 11.

**Comment by dglemos** [comment]
The option --safe stops the vep run if the plugin cannot be instantiated:
`$instance = $module->new($self->config->{_params}, @params);`

You can find the code here: https://github.com/Ensembl/ensembl-vep/blob/release/112/modules/Bio/EnsEMBL/VEP/Runner.pm#L908-L914

For your example, the plugin was instantiated successfully. 

If you add the `die()` command to the method `new()` then vep run is killed:
```
sub new {
    if (!(defined $self)) {
        my $class = shift;
        $self = $class->SUPER::new(@_);
    }
  die "this should terminate the VEP run with --safe.";
  return $self;
}
```

**Comment by dglemos** [comment]
I'm going to close this issue. If you have more questions please open a new issue.

Best wishes,
Diana
