### ISSUE TITLE
Clarification Needed on dbNSFP Plugin Annotation for Variants with Multiple Values

### ISSUE THREAD

**Issue by sibylZHAI** [Ensembl/ensembl-vep#1676]
Dear Developer,

I hope this message finds you well. I am currently using the VEP Plugin dbNSFP to annotate my VCF file. However, I have encountered a peculiar situation where annotations for some variants display multiple values separated by an "&" symbol. These values are sometimes equal and sometimes not, and they also include the "." character.

For your reference, I have attached a table illustrating the issue. Could you please explain why this discrepancy occurs and how it can be resolved?

I would greatly appreciate any guidance or insights you could provide on this matter.

Thank you for your time and assistance.

Best regards,

Zhai

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

</head>
<body>

AlphaMissense_pred | CADD_phred | Polyphen2_HDIV_pred
-- | -- | --
B&B | 2.209 | .&B
B | 14.21 | B
A | 24.7 | D
B | 6.599 | B
B | 9.609 | null
P&.&A&P&P&A&P | 27.3 | D&.&.&D&.&.&.
B&B&B | 23 | .&B&.
B | 13.08 | P
B | 0.926 | B
B | 13.64 | D
B&B | 0.017 | .&.
B&B | 4.449 | .&.
B | 12.7 | B
B | 10.58 | B

</body>

</html>

**Comment by dglemos** [comment]
Hi @sibylZHAI,
Most of the dbNSFP scores are transcript-specific. 

**Example**
For variant: `1 999169 A/C`

dbNSFP 4.7c
```
Ensembl_transcriptid    ENST00000428771;ENST00000304952;ENST00000484667
AlphaMissense_score    0.1133;0.113;0.1316
```
(`;` [separates different values](https://github.com/Ensembl/VEP_plugins/blob/release/112/dbNSFP.pm#L88-L94))

For this example there are 3 Alpha Missense scores, one for each transcript:
ENST00000428771 -> 0.1133
ENST00000304952 -> 0.113
ENST00000484667 -> 0.1316

In your example, `B&B` is a score for each transcript. If you check the column `Ensembl_transcriptid` you should have two transcript IDs.


Here you can find more information about dbNSFP:
- dbNSFP website: https://sites.google.com/site/jpopgen/dbNSFP
- dbNSFP publication: [dbNSFP v4: a comprehensive database of transcript-specific functional predictions and annotations for human nonsynonymous and splice-site SNVs](https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-020-00803-9)

Let me know if you have more questions.

Best wishes,
Diana

**Comment by sibylZHAI** [comment]
Hi Diana,

Thank you for the detailed explanation and resources. This helps a lot!

Wishing you the best,
Zhai
