### ISSUE TITLE
--exclude_predicted

### ISSUE THREAD

**Issue by jammywwh** [Ensembl/ensembl-vep#1686]
When I tested vep annotations, I found that with or without the --exclude_predicted option, the results came out without predicted transcripts.
**This problem exists with the hg19 genome, but not with the hg38 genome.**

### System
- VEP version: 111.0
- VEP Cache version: 111.0
- Perl version: 5.34.0
- OS: CentOS
- tabix installed

### Full VEP command line
```
vep \
  -i case.vcf \
  --dir_cache /datapool/db/vep/cache/ --offline --cache \
  --species homo_sapiens \
  --assembly GRCh37 \
  --fasta ucsc.hg19.opn1masked.fasta \
  --refseq \
  --fork 4 \
  --plugin UTRannotator,/datapool/db/vep/uORF/uORF_5UTR_GRCh37_PUBLIC.txt \
  --tab --force_overwrite \
  -o utrAnno.txt
```

**Comment by olaaustine** [comment]
Hi @jammywwh, 
Hope this meets you well?
If possible can you share your input VCF file or example of variants with this issue. 
Thank you very much 
Ola.

**Comment by jammywwh** [comment]
Hi, @olaaustine 
Thanks for your reply.
input.vcf is input vcf file, output.txt is annotated output file.
[files.zip](https://github.com/user-attachments/files/15527910/files.zip)

Thank you.
Jammy.

**Comment by jammywwh** [comment]
Hi, @olaaustine 
Thanks for your reply.
I got it.
Best wishes,
Jammy
