### ISSUE TITLE
Cannot run haplo -- `Attempt to reload Bio/EnsEMBL/VEP/TranscriptTree.pm aborted`

### ISSUE THREAD

**Issue by ifiddes-10x** [Ensembl/ensembl-vep#169]
I am unable to run `haplo` after installation:

```
bespin1 Wed Mar 21 10:33 ensembl-vep $./haplo
Attempt to reload Bio/EnsEMBL/VEP/TranscriptTree.pm aborted.
Compilation failed in require at /mnt/home/ian/ensembl-vep/modules/Bio/EnsEMBL/VEP/Haplo/Runner.pm line 68.
BEGIN failed--compilation aborted at /mnt/home/ian/ensembl-vep/modules/Bio/EnsEMBL/VEP/Haplo/Runner.pm line 68.
Compilation failed in require at ./haplo line 20.
BEGIN failed--compilation aborted at ./haplo line 20.
```

However `vep` is fine:

```
bespin1 Wed Mar 21 10:33 ensembl-vep $./vep
#----------------------------------#
# ENSEMBL VARIANT EFFECT PREDICTOR #
#----------------------------------#

Versions:
  ensembl              : 91.18ee742
  ensembl-funcgen      : 91.4681d69
  ensembl-io           : 91.923d668
  ensembl-variation    : 91.c78d8b4
  ensembl-vep          : 91.3

Help: dev@ensembl.org , helpdesk@ensembl.org
Twitter: @ensembl , @EnsemblWill

http://www.ensembl.org/info/docs/tools/vep/script/index.html

Usage:
./vep [--cache|--offline|--database] [arguments]

Basic options
=============

--help                 Display this message and quit

-i | --input_file      Input file
-o | --output_file     Output file
--force_overwrite      Force overwriting of output file
--species [species]    Species to use [default: "human"]

--everything           Shortcut switch to turn on commonly used options. See web
                       documentation for details [default: off]
--fork [num_forks]     Use forking to improve script runtime

For full option documentation see:
http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html
```

The file (and folder) in question, `Bio/EnsEMBL/VEP/TranscriptTree.pm`, doesn't exist:

```
bespin1 Wed Mar 21 10:35 EnsEMBL $ls Bio/EnsEMBL/VEP
ls: cannot access Bio/EnsEMBL/VEP: No such file or directory
```

**Comment by vivekruhela** [comment]
Hi,

I am facing the same issue. I have checked the `modules` folder. The file `TranscriptTree.pm` is available in `VEP` directory. But still this error is coming. Any suggestions.....

**Comment by vivekruhela** [comment]
@ima23 : Let me know if I am wrong. I type `perldoc -l Set::IntervalTree` to check if this package is installed in the system or not. And the output is `No documentation found for "Set::IntervalTree".` i.e. this package is not installed in system. Then I go to the link to download this package mentioned by you in previous comment. After giving the command `perl Makefile.PL`, I am getting the following error:
 `Can't locate ExtUtils/CppGuess.pm in @INC (you may need to install the ExtUtils::CppGuess module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at Makefile.PL line 11.
BEGIN failed--compilation aborted at Makefile.PL line 11.`

Can you help me with this issue. Thanks.

**Comment by vivekruhela** [comment]
@ima23 :  Problem Solved. `./haplo` is working well. Thanks. But I want to know, does ensemble-vep and haplo program support parallel computation. If yes, then how to enable it or how to assign number of threads ( I asked this because haplo program is taking much time (& still running from last 5 hours)).

**Comment by vivekruhela** [comment]
Hi: @ima23 : Script is still running. It is taking time more than expected. But I think is it due to more than 2 million variants in vcf file. What about my last question: where is the protein sequence in the line I types in the previous comment. I am not able to understand or get protein sequence from the output file.Thanks.

**Comment by ima23** [comment]
Hi @vivekruhela, the protein sequence is not exported. The variation consequence at the protein level is represented by the Ensembl identifier and HVGS nomenclature: `ENSP00000342313:343W>R`, this is a missense in the ENSP00000342313 protein, where the 343th amino acid is changed from a Tryptophan (W) to Arginine (R). Hope this helps.

**Comment by ima23** [comment]
Hi @vivekruhela, I got to have another look at Haplosaurus and the sequences are exported but only if you switch to the JSON output format using `--json`.  By default the CDS haplotypes and protein haplotypes sequences are displayed. Each evaluated transcript will be represented in a JSON object written on one line.
The JSON format is the same as the output json of the REST API https://rest.ensembl.org/documentation/info/transcript_haplotypes_get. 
I have added an update to the documentation and it should be out latest with next release.

**Comment by iranmdl** [comment]
Hello!
I'm trying to run `haplosaurus` using `--json` option to retrieve the full protein sequence but I'm having the following error:
`ERROR: JSON module not installed`
Any help would be appreciated :)

Another question, I'm trying to predict the mutated protein sequences based on the combined consequences of multiple variants in the same phase, such as in the case of having a transcript affected by a frame shift indel and downstream in the sequence another variant (such as SNP).
If a protein coding transcript is affected by a frame shift variant, then all variants further downstream, in this case a SNP, should be shifted accordingly. Is this possible using `haplosaurus`? Is it possible to retrieve as well the transcript sequence with the variations embedded?

Thank you in advance :)

**Comment by ima23** [comment]
I assume the issue has been resolved. Please feel free to re-open this issue if it persists.

Thanks,
Irina
