### ISSUE TITLE
VEP installer not downloading cache files when specified

### ISSUE THREAD

**Issue by ethankreuzer** [Ensembl/ensembl-vep#1690]
## Describe the issue
I am trying to download the cache file for humans on build hg38 with theinstaller, but it is not doing it and I do not know why

## Additional information

I ran the following line:

$ perl INSTALL.pl --AUTO ac --species homo_sapiens --assembly GRCh38 --NO_HTSLIB

Also I did not load the DBD:mysql Perl module becasue I was having issues 
### System
Versions:
  ensembl              : 112.3add379
  ensembl-funcgen      : 112.be19ffa
  ensembl-io           : 112.2851b6f
  ensembl-variation    : 112.4113356
  ensembl-vep          : 112.0

- Perl version: 5.30.2
- OS: 
NAME="Rocky Linux"
VERSION="8.7 (Green Obsidian)"
- tabix installed ? YES

### Last part of terminal output

-------------------- EXCEPTION --------------------
MSG: ERROR: Cannot use format gff without Bio::DB::HTS::Tabix module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /project/richards/ethan.kreuzer/EXWAS/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:178
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /project/richards/ethan.kreuzer/EXWAS/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:328
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /project/richards/ethan.kreuzer/EXWAS/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:94
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /project/richards/ethan.kreuzer/EXWAS/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /project/richards/ethan.kreuzer/EXWAS/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /project/richards/ethan.kreuzer/EXWAS/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:362
STACK toplevel ./t/Runner.t:833
Date (localtime)    = Mon Jun  3 12:25:06 2024
Ensembl API version = 112
---------------------------------------------------
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 81.
./t/Runner.t ......................................... Dubious, test returned 255 (wstat 65280, 0xff00)
All 81 subtests passed 
./t/Stats.t .......................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Stats.t .......................................... ok    
./t/TranscriptTree.t ................................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/TranscriptTree.t ................................. ok    
./t/Utils.t .......................................... ok    
./t/VariantRecoder.t ................................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/VariantRecoder.t ................................. ok    
./t/bam_edit.t ....................................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/bam_edit.t ....................................... ok    
./t/version.t ........................................ ok   

Test Summary Report
-------------------
./t/Runner.t                                       (Wstat: 65280 Tests: 81 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=49, Tests=1927, 109 wallclock secs ( 0.45 usr  0.21 sys + 95.95 cusr  9.95 csys = 106.56 CPU)
Result: FAIL
Failed 1/49 test programs. 0/1927 subtests failed.

### Proof no cache files (if applicable)
"
[-----.-------@---- ensembl-vep]$ ls ~/.vep
Plugins  tmp
"

The cache files are not here

**Comment by likhitha-surapaneni** [comment]
Hi @ethankreuzer ,

Sorry to hear that you are facing issues.

Can you please let us what is returned when you run `perl -e "use Bio::DB::HTS::Tabix"`?

An option is to uninstall the tabix, download the ensembl-vep and run an installation from scratch with `--NO_HTSLIB`

**Comment by likhitha-surapaneni** [comment]
Hi @ethankreuzer , I hope the issue got solved. I am closing this ticket due to inactivity but please feel free to open a new ticket in case the issue persists
