### ISSUE TITLE
Docker v111.0 and. v112.0 got error bgzip not found in path

### ISSUE THREAD

**Issue by barbarian1803** [Ensembl/ensembl-vep#1693]
## Describe the issue
Error when running VEP docker version 111.0 and 112.0: MSG: ERROR: bgzip not found in path
The same script works when running docker version v110.1.
It works when compress_output parameter is not specified.
The docker for v110 use ubuntu 18 but for 111 and 112 use ubuntu:22.04. 
I suspect this is the cause.

## Parameters
compress_output bgzip

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: docker 111.0 or 112.0
- VEP Cache version: 111 or 112
- Docker runtime: podman version 1.6.4

### Full error message
```
-------------------- EXCEPTION --------------------
MSG: ERROR: bgzip not found in path

STACK Bio::EnsEMBL::VEP::BaseRunner::get_output_file_handle /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:206
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:202
STACK toplevel /opt/vep/src/ensembl-vep/vep:46
Date (localtime)    = Thu Jun  6 03:20:29 2024
Ensembl API version = 111
---------------------------------------------------
```

**Comment by barbarian1803** [comment]
Hi,

That is the weird part. I have tried your command and it shows the bgzip command is there.
I have also run it on other linux machine and it works fine.
The environment that shows error is using podman so I am not sure that is the cause although the old version v110 works just fine.

**Comment by nuno-agostinho** [comment]
Hi @barbarian1803,

In that case, the issue appears to be related to using the Docker image in Podman. Unfortunately, we do not provide support for Podman.

As a workaround, you can manually bgzip the resulting file from VEP.

Don’t hesitate to ask if you have more questions or want to chat about this further.

Cheers,
Nuno
