### ISSUE TITLE
Cant Install plugins

### ISSUE THREAD

**Issue by GianlucaMattei** [Ensembl/ensembl-vep#1708]
Hello, I can not install vep plugins. 
I am using anaconda to launch "vep_install" with the following command. 
Anyone know how to fix this ?
Thanks

```vep_install AlphaMissense```

```

Hello! This installer will help you set up VEP v112, including:
 - Install v112 of the Ensembl API for use by the VEP. It will not affect any existing installations of the Ensembl API that you may have.
 - Download and install cache files from Ensembl's FTP server.
 - Download FASTA files from Ensembl's FTP server.
 - Download VEP plugins.

Checking for installed versions of the Ensembl API...done

Setting up directories
Destination directory ./Bio already exists.
Do you want to overwrite it (if updating VEP this is probably OK) (y/n)? Can't open AlphaMissense: No such file or directory at /data2/user1/.conda/envs/vep/bin/vep_install line 678.
Exiting

```

### System
- VEP version: v112
- VEP Cache version: v112
- Perl version: v5.32.1
- OS: RHEL 8
- tabix installed

**Comment by GianlucaMattei** [comment]
Ok. I have the same issue using the "normal" vep installed with

```
git clone https://github.com/Ensembl/ensembl-vep.git
cd ensembl-vep
perl INSTALL.pl

```

I just edited the title of the issue....

Anyway, when I run the command

`./INSTALL.pl AlphaMissense`

I get

```
WARNING: DBD::mysql module not found. VEP can only run in offline (--offline) mode without DBD::mysql installed

http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#requirements

Version check reports a newer release of 'ensembl-vep' is available (installed: 109, available: 112)

We recommend using git to update 'ensembl-vep', by exiting this installer and running:

        git pull
        git checkout release/112

Do you wish to exit so you can get updates (y) or continue (n): Can't open AlphaMissense: No such file or directory at ./INSTALL.pl line 425.
OK, bye!

NB: Remember to re-run INSTALL.pl after updating to check for API updates

```

### System
- VEP version: v109
- VEP Cache version: v109
- Perl version: v5.32.1
- OS: RHEL 8
- tabix installed

**Comment by nuno-agostinho** [comment]
Hey @GianlucaMattei,

To install AlphaMissense, you will need to run the command `./INSTALL -a p -g AlphaMissense`. Otherwise, you can also interactively follow the instructions when running the command `./INSTALL.pl`.

After installing AlphaMissense and any other plugins of interest, you can look into our documentation on how to use each plugin: https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html

Hope this helps.

Best regards,
Nuno

**Comment by GianlucaMattei** [comment]
Thanks

**Comment by GianlucaMattei** [comment]
It works, Thanks
