### ISSUE TITLE
Q: How to filter variants by a specific feature before --pick_order is applied?

### ISSUE THREAD

**Issue by asalimih** [Ensembl/ensembl-vep#1711]
Hi,
I'm using the --pick and --pick_order to customize the priority of transcript selection. Now for each variant I want to only consider transcripts which have a TSL number and then pick the one based on the priority I have specified in pick_order. I know there is a `tsl` option in pick_order but I guess it chooses the transcript with the lowest TSL number. my questions are:

- Is there any built-in solution for this?
- if not how should I approach it?
- Is there any other feature/option which is equivalent to having a TSL number? 

Thanks in Advance

**Comment by nuno-agostinho** [comment]
Hi @asalimih,

Hope you are having a great day!

Just to make sure that I understand, you want to pick a specific transcript with a `tsl` other than the best available? So, for example, you want to pick a transcript of `tsl=3` even if a `tsl=1` exists?

> Is there any other feature/option which is equivalent to having a TSL number?

We intend to provide an improved categorisation for transcript support that will supersede TSL in the future, but it's still in discussion.

You can look at other criteria used to prioritise transcripts, although they are not directly related with TSL, such as those described [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick_options).

Looking forward to your reply.

Cheers,
Nuno

**Comment by asalimih** [comment]
> Just to make sure that I understand, you want to pick a specific transcript with a `tsl` other than the best available? So, for example, you want to pick a transcript of `tsl=3` even if a `tsl=1` exists?
> 
Hi @nuno-agostinho , 
Yes, and I want to choose the transcript with the highest impact (based on consequence) among those which have a tsl number (are not NA).

**Comment by nuno-agostinho** [comment]
Hi @asalimih,

I don't think there is a way to do that in VEP, but I think you can manually do something like:

* Do not use `--pick`, as it will return only one consequence per variant.
* Use `--tsl` to return the TSL number for each transcript.
* Use `filter_vep` to filter out consequences with no TSL number.
* From that result, you could create a custom script to go through each variant and select the consequence with highest impact based on your criteria.

Hope this helps.

Best,
Nuno

**Comment by asalimih** [comment]
Thank you @nuno-agostinho, now I'm confident there isn't a simple built-in solution inside vep.
It may be a useful feature if there was an option like `--pre_filter` with the filter_vep notation to filter variants before other options like `--pick` are applied.

**Comment by nuno-agostinho** [comment]
Hey @asalimih,

> It may be a useful feature if there was an option like --pre_filter with the filter_vep notation to filter transcripts before other options like --pick are applied.

I will suggest a `--pre_filter` feature to our team for us to discuss it. Thank you!

I will now close this issue, but please feel free to open a new one if you encounter issues or have more suggestions on VEP.

Cheers,
Nuno
