### ISSUE TITLE
`0` does not work as a variant identifier

### ISSUE THREAD

**Issue by dvg-p4** [Ensembl/ensembl-vep#1714]
## Describe the issue
If a provided variant identifier is `0`, it will be ignored and the default identifier will be used instead.

### System
- VEP version: 112
- VEP Cache version: 112
- Perl version: 5.26.3
- OS: Rocky 8
- tabix installed: Yes

### Full VEP command line
```
~/ensembl-vep/vep --input_file repro_input.tsv --format ensembl --cache --offline --dir ~/.vep --assembly GRCh38 --output_file repro_output.vcf --vcf
```

### Data files
`repro_input.tsv`:
```
1	1220794	1220794	G/T	+	-2
1	1220795	1220795	C/T	+	-1
1	1220796	1220796	G/A	+	0
1	1220796	1220796	G/C	+	1
1	1220797	1220797	G/A	+	2
1	1220801	1220801	C/G	+	3
```

`$ grep -v "^##" repro_output.vcf | cut -f 1-5 | column -t`:
```
#CHROM  POS      ID             REF  ALT
1       1220794  -2             G    T
1       1220795  -1             C    T
1       1220796  1_1220796_G/A  G    A
1       1220796  1              G    C
1       1220797  2              G    A
1       1220801  3              C    G
```

**Comment by olaaustine** [comment]
Hi @dvg-p4, 
Hope this meets you well? 
Thank you for your query. 
To better understand your issue, do you want to use 0 as a variant identifier ? 
Thank you
Ola.

**Comment by dvg-p4** [comment]
Yes, I'd like for "0" to be usable as a variant identifier.

**Comment by olaaustine** [comment]
Hi @dvg-p4.
Thank you for your response.
At this time, we do not support this feature. However, I will discuss the possibility of adding this functionality with our team for future updates. 
I will close this ticket now, please feel free to open another ticket or reopen this ticket if you have any issues. 
Thank you 
Ola

**Comment by dvg-p4** [comment]
I think the fix might actually be simple -- pretty sure the bug is here:

https://github.com/Ensembl/ensembl-vep/blob/ecf716fcce17d57765a0cc8c2578631331c71da7/modules/Bio/EnsEMBL/VEP/Parser.pm#L462

since "0" is falsy, it treats it as if it were undefined. But as of perl 5.10 you can explicitly test for definedness with `//=` instead.

**Comment by ainefairbrother** [comment]
Hi @dvg-p4, 

Thank you for looking into this. If you would like to, you can submit a PR for review. There's some general guidance for contributing to Ensembl repos [here](https://github.com/Ensembl/ensembl/blob/main/CONTRIBUTING.md). 

If not, I'm happy to do this. 

Best, 

Aine
