### ISSUE TITLE
StructuralVariantOverlap Hanging Indefinitely

### ISSUE THREAD

**Issue by Lukecassar21** [Ensembl/ensembl-vep#1715]
The issue I'm encountering is that when running the following vep command line:

`vep --cache 112 --dir_cache /media/user/Maxtor/SV_Analysis/outputs/vep_output/vep_caches/homo_sapiens/homo_sapiens_merged_vep_112_GRCh37 -i /media/user/Maxtor/SV_Analysis/outputs/manta_output/NA24385_manta_did.vcf -o /media/user/Maxtor/SV_Analysis/outputs/vep_output/NA24385_manta_did_vep_gnomad_test.vcf --offline --fasta /media/user/Maxtor/SV_Analysis/inputs/reference_fasta/genome.fa --max_sv_size 2800000000 --force_overwrite --vcf --assembly GRCh37 --plugin StructuralVariantOverlap,file=/media/user/Maxtor/SV_Analysis/outputs/vep_output/gnomad_v2.1_sv.sites.vcf.gz -v`

I get the following output:
2024-07-03 13:30:27 - Read configuration from environment variables
2024-07-03 13:30:27 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this
2024-07-03 13:30:27 - No input file format specified - detected vcf format

The file output being a VCF file that only has the header printed. It remains this way for upwards of 24 hours with seemingly no progress whatsoever, but the moment I remove the StructuralVariantOverlap plugin, the run finishes and produces a full 40mb output in less than 5 minutes.

I've also attempted this using the gnomad v4.1 database with no luck.

### System
- VEP version: 112
- VEP Cache version: 112
- Perl version: 5.32
- OS: Ubuntu
- tabix installed: 1.20

### Data files (if applicable)
Input File:[NA24385_manta_did.vcf.txt](https://github.com/user-attachments/files/16084782/NA24385_manta_did.vcf.txt)

Output File: [NA24385_manta_did_vep_gnomad_test.vcf.txt](https://github.com/user-attachments/files/16084791/NA24385_manta_did_vep_gnomad_test.vcf.txt)

**Comment by davmlaw** [comment]
Hi, as a work around, you can try using ```--custom```. If you want both the overlap and the ID, you can call ```--custom``` twice and do a bit of post-processing

**Comment by jamie-m-a** [comment]
I think this has been addressed under the other issue you had open @Lukecassar21, essentially we will probably deprecate the SV overlap plugin as the functionality is now available in the core VEP code. 

I'll close this ticket now, but do shout out in the other ticket (still open) if you have any further questions.
