### ISSUE TITLE
Request for Documentation and Containerization of Bio::EnsEMBL::XS Module for VEP to run faster.

### ISSUE THREAD

**Issue by JoshuaSWIBI** [Ensembl/ensembl-vep#1722]
Hi,

I am working on annotating large datasets, specifically WGS VCF files, using VEP. I came across the Bio::EnsEMBL::XS module mentioned in the VEP documentation and decided to install it as per the instructions. However, there are no clear guidelines on how to effectively use this module to improve VEP performance.

Details:

Environment:

Azure VM with 32 vCPUs and 64GB RAM
VEP installed and running in a Docker container
Issues:

Lack of Documentation:

There are no detailed instructions on how to use the Bio::EnsEMBL::XS module with VEP.
It is unclear how this module optimizes VEP and what specific steps need to be taken to leverage its capabilities.
Containerization:

I would like to know if it is possible to containerize the Bio::EnsEMBL::XS module and use it within the VEP Docker container.
If yes, I need guidance on the steps to achieve this.
Request:

Documentation:

Please provide detailed documentation on how to use the Bio::EnsEMBL::XS module with VEP, including examples and best practices.
Information on how this module improves VEP performance would be highly appreciated.
Containerization:

If possible, provide instructions or a Dockerfile example on how to integrate the Bio::EnsEMBL::XS module into the VEP Docker container.
Any additional configurations or dependencies required for the module to function optimally within the container.
Thank you for your support. Any help or pointers to relevant documentation would be a great favor.

Best regards,
Joshua Ravi

**Comment by likhitha-surapaneni** [comment]
Hi @JoshuaSWIBI ,

Thank you for reaching out and providing us feedback. 

`ensembl-xs` should be included in the official docker image of VEP by default. Further documentation about the module can be found [here](https://github.com/Ensembl/ensembl-xs). Within the docker container, the following command can be run `perldoc Bio::EnsEMBL::XS` for documentation on the module. 

While this may not be in our immediate priority list, we will certainly try to work towards improving documentation on how to use the `ensembl-xs`module with VEP along with examples and best practices in the coming releases.

Kind regards,
Likhitha

**Comment by JoshuaSWIBI** [comment]
Thanks @likhitha-surapaneni

**Comment by likhitha-surapaneni** [comment]
Hi @JoshuaSWIBI ,
I am closing this for now. Please feel free to open a new issue in case there are any other problems.
