### ISSUE TITLE
filter_vep on HGNC_ID

### ISSUE THREAD

**Issue by fellen31** [Ensembl/ensembl-vep#1723]
## Describe the issue

Hi, I can't figure out how to use `--filter "HGNC_ID in /test/hgnc.txt"` when HGNC_ID is annotated as `HGNC:12345` and not just `12345`. I get no matching variants. 

Thanks! 

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 110 
- VEP Cache version: 110 (GRCh38)
- Perl version: [e.g. 5.26]
- OS: [e.g. MacOS, Ubuntu, CentOS]
- tabix installed ?

### Full VEP command line
```
 singularity exec --bind $(pwd):/test https://depot.galaxyproject.org/singularity/ensembl-vep:110.0--pl5321h2a3209d_0 filter_vep --input_file /test/multisample_2.vcf.gz --filter "HGNC_ID in /test/hgnc.txt" --only_matched
```

### Full error message
> Including the warnings, if available

### Data files (if applicable)
They include:
- The input file
- The output file
- The custom file(s)
You can provide a sample of them

**Comment by likhitha-surapaneni** [comment]
Hi @fellen31,
Sorry to hear that you are facing issues with filtering. Can you please provide an input file you are using?

Thank you

**Comment by fellen31** [comment]
Sure, here's the file: [multisample.vcf.gz](https://github.com/user-attachments/files/16263910/multisample.vcf.gz)

**Comment by likhitha-surapaneni** [comment]
Hi @fellen31, thank you for providing the input file. I am able to replicate the issue on my end.

We will try to provide a fix for this and keep you updated.

Kind regards,
Likhitha

**Comment by likhitha-surapaneni** [comment]
Hi @fellen31, 

The fix will be made available in the coming release (release/113). I am closing this ticket for now. Please feel free to open a new issue if you are facing any other problems.

Thanks and regards,
Likhitha

**Comment by fellen31** [comment]
Thanks a lot @likhitha-surapaneni!
