### ISSUE TITLE
VEP installation can not install Bio::DB:HTS module

### ISSUE THREAD

**Issue by xiyasong** [Ensembl/ensembl-vep#1728]
## Describe the issue
Hi My VEP installaztion work fine with the --NO_HTSLIB, but when I try to use it for my real sample it gives error:
-------------------- EXCEPTION --------------------
MSG: ERROR: Cannot use format vcf without Bio::DB::HTS::Tabix module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /sza_data/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:178
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /sza_data/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:328
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /sza_data/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:94
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /sza_data/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /sza_data/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::run /sza_data/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:200
STACK toplevel ./vep:46
Date (localtime)    = Thu Jul 25 17:49:56 2024
Ensembl API version = 112

So, I tried to install Bio::DB::HTS module, by running perl INSTALL.pl, then it gives error: 
....
gcc  -o test/test-bcf-translate test/test-bcf-translate.o libhts.a -lz -lz -lm -lbz2 -llzma -lpthread
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.11 - moving files to ./biodbhts
 - making Bio::DB:HTS
/usr/bin/ld: unrecognized option '-Wl,-O2'
/usr/bin/ld: use the --help option for usage information
Warning: ExtUtils::CBuilder not installed or no compiler detected
Proceeding with configuration, but compilation may fail during Build

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.11'
Building Bio-DB-HTS
Error: no compiler detected to compile 'lib/Bio/DB/HTS.c'.  Aborting
ERROR: Shared Bio::DB:HTS library not found

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 112
- VEP Cache version: 112
- Perl version: v5.32.1
- OS: Ubuntu
- tabix installed ? Yes

### Full VEP command line
```
perl INSTALL.pl
```

### Full error message
> Including the warnings, if available
Hello! This installer will help you set up VEP v112, including:
 - Install v112 of the Ensembl API for use by the VEP. It will not affect any existing installations of the Ensembl API that you may have.
 - Download and install cache files from Ensembl's FTP server.
 - Download FASTA files from Ensembl's FTP server.
 - Download VEP plugins.

Checking for installed versions of the Ensembl API...done

Setting up directories
 - fetching BioPerl
 - unpacking ./Bio/tmp/release-1-6-924.zip
 - moving files
Attempting to install Bio::DB::HTS and htslib.

>>> If this fails, try re-running with --NO_HTSLIB

 - checking out HTSLib
Cloning into 'htslib'...
remote: Enumerating objects: 17111, done.
remote: Counting objects: 100% (1388/1388), done.
remote: Compressing objects: 100% (668/668), done.
remote: Total 17111 (delta 883), reused 916 (delta 687), pack-reused 15723
Receiving objects: 100% (17111/17111), 12.76 MiB | 10.46 MiB/s, done.
Resolving deltas: 100% (12292/12292), done.
Note: switching to '1832d3a1b75133e55fb6abffc3f50f8a6ed5ceae'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

 - building HTSLIB in ./htslib
In /sza_data/ensembl-vep/htslib
echo '/* Default config.h generated by Makefile */' > config.h
echo '#define HAVE_LIBBZ2 1' >> config.h
echo '#define HAVE_LIBLZMA 1' >> config.h
echo '#define HAVE_LZMA_H 1' >> config.h
echo '#define HAVE_FSEEKO 1' >> config.h
echo '#define HAVE_DRAND48 1' >> config.h
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o kfunc.o kfunc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o knetfile.o knetfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o kstring.o kstring.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o bcf_sr_sort.o bcf_sr_sort.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o bgzf.o bgzf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o errmod.o errmod.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o faidx.o faidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hfile.o hfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.9-dirty"' > version.h
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hts.o hts.c
hts.c: In function ‘hts_idx_init’:
hts.c:1386:59: warning: overflow in conversion from ‘uint32_t’ {aka ‘unsigned int’} to ‘int’ changes value from ‘idx->z.last_bin = 4294967295’ to ‘-1’ [-Woverflow]
 1386 |     idx->z.save_bin = idx->z.save_tid = idx->z.last_tid = idx->z.last_bin = 0xffffffffu;
      |                                                           ^~~
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hts_os.o hts_os.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o md5.o md5.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o multipart.o multipart.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o probaln.o probaln.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o realn.o realn.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o regidx.o regidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o sam.o sam.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o synced_bcf_reader.o synced_bcf_reader.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcf_sweep.o vcf_sweep.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o tbx.o tbx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o textutils.o textutils.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o thread_pool.o thread_pool.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcf.o vcf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcfutils.o vcfutils.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_decode.o cram/cram_decode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_encode.o cram/cram_encode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_external.o cram/cram_external.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_index.o cram/cram_index.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_io.o cram/cram_io.c
In file included from /usr/include/string.h:535,
                 from cram/cram_io.c:53:
In function ‘strncpy’,
    inlined from ‘cram_populate_ref’ at cram/cram_io.c:2095:9:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:10: warning: ‘__builtin_strncpy’ specified bound 4096 equals destination size [-Wstringop-truncation]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘full_path’ at cram/cram_io.c:3748:13,
    inlined from ‘cram_write_SAM_hdr’ at cram/cram_io.c:3823:17:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:10: warning: ‘__builtin_strncpy’ specified bound 4096 equals destination size [-Wstringop-truncation]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘cram_dopen’ at cram/cram_io.c:4126:9:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:10: warning: ‘__builtin_strncpy’ specified bound 20 equals destination size [-Wstringop-truncation]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_samtools.o cram/cram_samtools.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_stats.o cram/cram_stats.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/files.o cram/files.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/mFILE.o cram/mFILE.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/open_trace_file.o cram/open_trace_file.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/pooled_alloc.o cram/pooled_alloc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/rANS_static.o cram/rANS_static.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/sam_header.o cram/sam_header.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/string_alloc.o cram/string_alloc.c
ar -rc libhts.a kfunc.o knetfile.o kstring.o bcf_sr_sort.o bgzf.o errmod.o faidx.o hfile.o hfile_net.o hts.o hts_os.o md5.o multipart.o probaln.o realn.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o textutils.o thread_pool.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o
ranlib libhts.a
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o kfunc.pico kfunc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o knetfile.pico knetfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o kstring.pico kstring.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o bcf_sr_sort.pico bcf_sr_sort.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o bgzf.pico bgzf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o errmod.pico errmod.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o faidx.pico faidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o hfile.pico hfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o hfile_net.pico hfile_net.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o hts.pico hts.c
hts.c: In function ‘hts_idx_init’:
hts.c:1386:59: warning: overflow in conversion from ‘uint32_t’ {aka ‘unsigned int’} to ‘int’ changes value from ‘idx->z.last_bin = 4294967295’ to ‘-1’ [-Woverflow]
 1386 |     idx->z.save_bin = idx->z.save_tid = idx->z.last_tid = idx->z.last_bin = 0xffffffffu;
      |                                                           ^~~
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o hts_os.pico hts_os.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o md5.pico md5.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o multipart.pico multipart.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o probaln.pico probaln.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o realn.pico realn.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o regidx.pico regidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o sam.pico sam.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o synced_bcf_reader.pico synced_bcf_reader.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o vcf_sweep.pico vcf_sweep.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o tbx.pico tbx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o textutils.pico textutils.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o thread_pool.pico thread_pool.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o vcf.pico vcf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o vcfutils.pico vcfutils.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_codecs.pico cram/cram_codecs.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_decode.pico cram/cram_decode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_encode.pico cram/cram_encode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_external.pico cram/cram_external.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_index.pico cram/cram_index.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_io.pico cram/cram_io.c
In file included from /usr/include/string.h:535,
                 from cram/cram_io.c:53:
In function ‘strncpy’,
    inlined from ‘cram_populate_ref’ at cram/cram_io.c:2095:9:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:10: warning: ‘__builtin_strncpy’ specified bound 4096 equals destination size [-Wstringop-truncation]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘full_path’ at cram/cram_io.c:3748:13,
    inlined from ‘cram_write_SAM_hdr’ at cram/cram_io.c:3823:17:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:10: warning: ‘__builtin_strncpy’ specified bound 4096 equals destination size [-Wstringop-truncation]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘cram_dopen’ at cram/cram_io.c:4126:9:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:10: warning: ‘__builtin_strncpy’ specified bound 20 equals destination size [-Wstringop-truncation]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_samtools.pico cram/cram_samtools.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_stats.pico cram/cram_stats.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/files.pico cram/files.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/mFILE.pico cram/mFILE.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/open_trace_file.pico cram/open_trace_file.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/pooled_alloc.pico cram/pooled_alloc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/rANS_static.pico cram/rANS_static.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/sam_header.pico cram/sam_header.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/string_alloc.pico cram/string_alloc.c
gcc -shared -Wl,-soname,libhts.so.2  -o libhts.so kfunc.pico knetfile.pico kstring.pico bcf_sr_sort.pico bgzf.pico errmod.pico faidx.pico hfile.pico hfile_net.pico hts.pico hts_os.pico md5.pico multipart.pico probaln.pico realn.pico regidx.pico sam.pico synced_bcf_reader.pico vcf_sweep.pico tbx.pico textutils.pico thread_pool.pico vcf.pico vcfutils.pico cram/cram_codecs.pico cram/cram_decode.pico cram/cram_encode.pico cram/cram_external.pico cram/cram_index.pico cram/cram_io.pico cram/cram_samtools.pico cram/cram_stats.pico cram/files.pico cram/mFILE.pico cram/open_trace_file.pico cram/pooled_alloc.pico cram/rANS_static.pico cram/sam_header.pico cram/string_alloc.pico -lz -lm -lbz2 -llzma -lpthread
ln -sf libhts.so libhts.so.2
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o bgzip.o bgzip.c
gcc  -o bgzip bgzip.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o htsfile.o htsfile.c
gcc  -o htsfile htsfile.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o tabix.o tabix.c
gcc  -o tabix tabix.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/hts_endian.o test/hts_endian.c
gcc  -o test/hts_endian test/hts_endian.o -lz -lm -lbz2 -llzma
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/fieldarith.o test/fieldarith.c
gcc  -o test/fieldarith test/fieldarith.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/hfile.o test/hfile.c
gcc  -o test/hfile test/hfile.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/sam.o test/sam.c
gcc  -o test/sam test/sam.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test_bgzf.o test/test_bgzf.c
gcc  -o test/test_bgzf test/test_bgzf.o libhts.a -lz -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test_realn.o test/test_realn.c
gcc  -o test/test_realn test/test_realn.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-regidx.o test/test-regidx.c
gcc  -o test/test-regidx test/test-regidx.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test_view.o test/test_view.c
gcc  -o test/test_view test/test_view.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-vcf-api.o test/test-vcf-api.c
gcc  -o test/test-vcf-api test/test-vcf-api.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-vcf-sweep.o test/test-vcf-sweep.c
gcc  -o test/test-vcf-sweep test/test-vcf-sweep.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-bcf-sr.o test/test-bcf-sr.c
gcc  -o test/test-bcf-sr test/test-bcf-sr.o libhts.a -lz -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-bcf-translate.o test/test-bcf-translate.c
gcc  -o test/test-bcf-translate test/test-bcf-translate.o libhts.a -lz -lz -lm -lbz2 -llzma -lpthread
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.11 - moving files to ./biodbhts
 - making Bio::DB:HTS
/usr/bin/ld: unrecognized option '-Wl,-O2'
/usr/bin/ld: use the --help option for usage information
Warning: ExtUtils::CBuilder not installed or no compiler detected
Proceeding with configuration, but compilation may fail during Build

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.11'
Building Bio-DB-HTS
Error: no compiler detected to compile 'lib/Bio/DB/HTS.c'.  Aborting
ERROR: Shared Bio::DB:HTS library not found

### Data files (if applicable)
They include:
- The input file
- The output file
- The custom file(s)
You can provide a sample of them

**Comment by jamie-m-a** [comment]
HI @xiyasong 

Sorry to hear you've been having trouble with the install. It can be tricky to debug these issues, but there are possibly a couple of simple workarounds.

1) If you run in offline mode, using a cache and fasta file, VEP shouldn't try to use that module, so you can bypass the issue that way. So use `--offline`, `--cache`, `--dir_cache` and `--fasta` (see [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html) for more details).

2) Failing that, you can try using the containerised docker image of Ensembl VEP - available [here](https://hub.docker.com/r/ensemblorg/ensembl-vep), with instructions [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker). It comes with all dependencies and plugins packaged already.

Do let me know how you get on!

**Comment by xiyasong** [comment]
Hi, thanks for your kind reply and suggestions, I tried --offline --cache --dir_cache seems still not solved, but **luckily: I solved the problem by creating a brand new conda environment and redo everything and it magically works**. :)).
