### ISSUE TITLE
UpDownDistance.pm broken

### ISSUE THREAD

**Issue by gherasima** [Ensembl/ensembl-vep#173]
After running 'perl INSTALL.pl' the UpDownDistance.pm contains only one row with:
"404: Not Found"

Versions:
  ensembl              : 91.18ee742
  ensembl-funcgen      : 91.4681d69
  ensembl-io           : 91.923d668
  ensembl-variation    : 91.c78d8b4
  ensembl-vep          : 91.3

**Comment by aparton** [comment]
Hi Adrian,

Thank you for letting us know about this. This is a bug, and the dead link will be removed in release 92.

The functionality of this plugin has been added into the main VEP code, not requiring the use of the plugin. This can be used by setting the —distance flag as detailed here: https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html <https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html>

Kind Regards,
Andrew

**Comment by gherasima** [comment]
Thanks very much.
From what version the distance flag is supported?

**Comment by aparton** [comment]
Hi Adrian,

No problem. The —distance flag was added for release 90, released in August 2017.

Kind Regards,
Andrew
