### ISSUE TITLE
ERROR: Can't detect input format

### ISSUE THREAD

**Issue by Zhang-Rui-2018** [Ensembl/ensembl-vep#1730]
## Describe the issue
Hi! I was trying to run VEP to annotate several regions separately (with average length 1Mb-2Mb) with the same scripts (from generating the input file to run VEP). For most regions, VEP works, but for a few regions, I got the error message: Can't detect input format.

### System
- VEP version: 112.0
- VEP Cache version: 112
- Perl version: 5.26
- OS: Ubuntu
- tabix installed: Yes

### Full VEP command line
```
vep --cache \
    --dir_cache /stanley/huang_lab/home/rzhang/00_Software/ensembl-vep/ \
    --everything \
    --force_overwrite \
    --tab \
    --pick \
    -i ${WORK_DIR}/input_region/${Type}_${chr}_${start_pos}_${end_pos}_input.tsv \
    -o ${WORK_DIR}/VEP_result/${Type}_${chr}_${start_pos}_${end_pos}_VEP.tsv
```

### Full error message
ERROR: Can't detect input format

### Data files (if applicable)
The input format is (I got the error message on this region)
```
chr10    98768564        98768564       T/A     +       chr10:98768564:T:A
chr10    98768640        98768640       A/G     +       chr10:98768640:A:G
chr10    98768760        98768760       T/C     +       chr10:98768760:T:C
chr10    98768843        98768843       G/A     +       chr10:98768843:G:A
chr10    98768870        98768870       G/A     +       chr10:98768870:G:A
chr10    98768911        98768911       C/T     +       chr10:98768911:C:T
chr10    98768947        98768947       C/G     +       chr10:98768947:C:G
chr10    98768969        98768969       C/A     +       chr10:98768969:C:A
......
```
For region I can get the final annotation result, the input format is
```
chr16   49599279        49599279        A/G     +       chr16:49599279:A:G
chr16   49599406        49599406        C/T     +       chr16:49599406:C:T
chr16   49599468        49599481        TAAGGAACCTGCAG/T        +       chr16:49599468:TAAGGAAC
chr16   49599647        49599647        C/T     +       chr16:49599647:C:T
chr16   49599821        49599821        G/A     +       chr16:49599821:G:A
chr16   49599960        49599960        G/A     +       chr16:49599960:G:A
chr16   49600042        49600042        C/A     +       chr16:49600042:C:A
```

**Comment by nakib103** [comment]
Hello @Zhang-Rui-2018,

Thanks for your query! Unfortunately, I cannot reproduce the issue with the example variants you have provided. 

The input format is detected using the first variant line of the input. In the example you have provided, are they the first few variant? If not, can you share the first few variants from the input file that encountered the error. Or, alternatively, if possible you can share the full input file.

Best regards,
Nakib

**Comment by Zhang-Rui-2018** [comment]
Hi @nakib103, 

They are the first few variants of my input. But it's OK, I found adding a parameter `--format ensembl` can solve my problem. Thank you for your response!

Best,
Rui
