### ISSUE TITLE
Document --max_sv_size command line default

### ISSUE THREAD

**Issue by davmlaw** [Ensembl/ensembl-vep#1731]
https://asia.ensembl.org/info/docs/tools/vep/script/vep_options.html

From looking at the code I think this defaults to 10000000

I had a quick skim over all the other options and couldn't see any other missing defaults

**Comment by nakib103** [comment]
Hi @davmlaw,

Yes, that would be the default for `--max_sv_size` option. Thanks for pointing that out, I will add it to the docs.

Best regards,
Nakib

**Comment by nakib103** [comment]
Hi @davmlaw, 

The doc update will be available in the next release (113). I will close this ticket for now but feel free to open a new one if you find any other issues.

Best regards,
Nakib
