### ISSUE TITLE
HGVS C dot not using right most aligned option

### ISSUE THREAD

**Issue by namiller2015** [Ensembl/ensembl-vep#1741]
Hello,

For the following variant in VCF format
`chr19   1219320 .   CACGTATATG  CCCG`

This represents a variant that looks like this
`CACGTATATGGTG     REF
 CCCG--------GTG     ALT`

We have a SNP A->C at the 2nd nucleotide and a deletion of TATAT and a deletion of a G.
VCF formatting would have the left most G deleted. HGVS standards would have the right most G deleted

Online web VEP using refseq transcripts gives the following C Dot
c.375-2_380delinsCC 
for transcript  NM_000455.5

but HGVS should be right most aligned giving a cdot of
c.375-2_381delinsCCG

I'm having difficulty understanding the correct way to resolve the inherit discrepancy between VCF standards and HGVS standards.
Is this an issue with the VCF representation, the way VEP's HGVS annotation is working, or something else?

Thanks!

**Comment by namiller2015** [comment]
Some additional detail.

Using online web VEP I entered 2 HGVS entries for just the deletion.
NM_000455.5:c.375-380del
AND
NM_000455.5:c.376-381del

both had the HGVS C dot output as NM_000455.5:c.375-380del.
but according to HGVS standards this should be 3 prime shifted and result in 376-381.

I don't understand why the 376-381del is getting reworked to 375-380.

VEP output results
https://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Results?tl=0I7ML6omyVC7jwHN-10322036

**Comment by namiller2015** [comment]
I put this deletion into LUMC Mutalyzer 3's normalizer and got the expected 3 prime shifted C dot.

input: (NM_000455.5):c.375_380del
https://mutalyzer.nl/


![image](https://github.com/user-attachments/assets/c2d8a283-ea84-42db-a297-13f6814acb6d)

**Comment by dglemos** [comment]
Hi @namiller2015,
Thank you for reporting this issue. 
We are still investigating the output, I'll let you know when we have any updates.

Best wishes,
Diana

**Comment by namiller2015** [comment]
Thanks!

Just adding some more details. Maybe this is a order of operations issue?

If you assess if the change is one indel or two different alterations AND THEN AFTER THAT three-prime you get delinsCC, because they are 2 (not less than 2) bp apart  (Order operations A) 

BUT 

If you assess 3’ needs first AND THEN AFTER THAT assess if the alterations are three or more nucleotides apart you get SNV change at -2 and a 6 basepair del (376_381) (Order operations B) 

This could explain why when I just put in the 6 base pair del into mutalyzer it 3-primes correctly, but when I put in the sequence it does order of operations A


The HGVS standards are also in the process of changing so it depends on which set of standards are currently being used.

![HGVS_standards (1)](https://github.com/user-attachments/assets/cf9f6c6d-9f01-49e3-ade2-e01c96c9c8b7)

**Comment by namiller2015** [comment]
any updates on this? Thanks

**Comment by dglemos** [comment]
> This represents a variant that looks like this
> CACGTATATGGTG     REF CCCG--------GTG     ALT

The 3' representation is the following:
CACGTATATGGTG     REF CCC---------GGTG     ALT

Which looks like this:
![var1](https://github.com/user-attachments/assets/cc900b10-f583-4ab0-892c-ec23131e499f)

The order is:
1) deletion of ACGTATAT
`CCC--------GGTG`

2) insertion of CC
`CCC**CC**GGTG`

If you input `ENST00000326873.7:c.375-2_381delinsCCG` in mutalyzer, it corrects the representation to `ENST00000326873.7:c.375-2_380delinsCC` ([link](https://mutalyzer.nl/normalizer/ENST00000326873.7:c.375-2_381delinsCCG)).

**Comment by dglemos** [comment]
I'm going to close this issue but feel free to re-open it if you have more questions.

Best wishes,
Diana
