### ISSUE TITLE
Calculate distance from nearest exon boundary

### ISSUE THREAD

**Issue by jasiozaucha** [Ensembl/ensembl-vep#175]
Is it possible to use VEP to calculate the distance from the nearest exon boundary? I had a brief look at SpliceRegion.pm but I do not understand the variables well enough to modify it for my need.

**Comment by aparton** [comment]
Hi,

Currently VEP does not have this functionality. SpliceRegion.pm looks at exon boundaries, but will not report the distance to the nearest one. It would be possible for you to develop a plugin to pull out this information, but as you have identified then that's not necessarily trivial.

Sorry that I couldn't be of more help.

Kind Regards,
Andrew
