### ISSUE TITLE
Can not find .index file for FASTA file

### ISSUE THREAD

**Issue by kuaileshizuihao** [Ensembl/ensembl-vep#1755]
## Describe the issue
I encountered the same problem as shown in the figure when using the DownStream plugin (there is no such problem when using --hgvs). Following these three instructions, I updated BioPerl and re-downloaded the FASTA file, but it still did not solve the problem. I suspect that my vep did not index the FASTA file correctly, because I did not find the .index file, but I found the .fai file. I wonder if this is the reason why the error still occurs. It seems that I can use vep normally without dealing with this error. What impact will it have? Thank you for your help, thanks a lot.

### System
- VEP version: 112
- VEP Cache version: 111
- Perl version: 5.32.1
- OS: CentOS

### Full VEP command line
```
export PERL5LIB=/ehpcdata/home/qiu/software/applications/micromamba/pkgs/perl-bioperl-core-1.7.8-pl5321hdfd78af_1/lib/perl5/site_perl/Bio/:$PERL5LIB
export PATH=/ehpcdata/analysis/liuhankui/bin/software/htslib:$PATH

/ehpcdata/home/qiu/software/applications/micromamba/envs/vepano/bin/perl /ehpcdata/home/qiu/software/applications/micromamba/envs/vepano/bin/vep \
-i WesDemo.vcf \
-o Result.vcf \
--assembly GRCh38 --no_stats --fork 4 --force \
--cache --merged --offline --use_given_ref \
--fasta /ehpcdata/analysis/chen/Tools/FASTA/Homo_sapiens.GRCh38.dna.primary_assembly.fa \
--dir_cache /ehpcdata/analysis/qiu/Public/VEPdatabase/VEP_cache \
--dir_plugins /ehpcdata/analysis/qiu/Public/VEPdatabase/VEP_plugins \
--vcf  \
--sift s --polyphen s --total_length --numbers \
--hgvs --protein --symbol --ccds --tsl --canonical  --mane --biotype \
--check_existing --exclude_null_alleles \
--cache_version 111 \
--plugin Downstream \
```

### Full error message
> Including the warnings, if available
WARNING: 30804 : Use of uninitialized value $pep_end in numeric lt (<) at /ehpcdata/analysis/qiu/Public/VEPdatabase/VEP_plugins/Downstream.pm line 142, <__ANONIO__> line 1000.
Use of uninitialized value $pep_start in numeric lt (<) at /ehpcdata/analysis/qiu/Public/VEPdatabase/VEP_plugins/Downstream.pm line 142, <__ANONIO__> line 1000.
Use of uninitialized value $pep_end in addition (+) at /ehpcdata/analysis/qiu/Public/VEPdatabase/VEP_plugins/Downstream.pm line 142, <__ANONIO__> line 1000.

![figure1](https://github.com/user-attachments/assets/85115260-bff4-4c02-93cc-d8345f36d494)

**Comment by likhitha-surapaneni** [comment]
Hi @kuaileshizuihao ,

Sorry to hear that you are facing issues.
Can you please let us know if you are seeing these warnings even when you run VEP using the fasta file without the plugin? This may rule out the possibility of fasta index file being corrupted. Can you kindly provide us the input file (or test input from the file) in order to see if we can replicate the issue on our end?

**Comment by kuaileshizuihao** [comment]
> Hi @kuaileshizuihao ,
> 
> Sorry to hear that you are facing issues. Can you please let us know if you are seeing these warnings even when you run VEP using the fasta file without the plugin? This may rule out the possibility of fasta index file being corrupted. Can you kindly provide us the input file (or test input from the file) in order to see if we can replicate the issue on our end?

Thank you for kindly offering help. This issue did not occur when I was not using the Downstream plugin. Here is the input I used for testing. Thanks!
[WesDemo.zip](https://github.com/user-attachments/files/17042598/WesDemo.zip)

**Comment by likhitha-surapaneni** [comment]
Hi @kuaileshizuihao ,
Thank you for providing the file. We are able to replicate the issue on our end and are looking into it.

**Comment by kuaileshizuihao** [comment]
> Hi @kuaileshizuihao , Thank you for providing the file. We are able to replicate the issue on our end and are looking into it.

Thank you very much！

**Comment by likhitha-surapaneni** [comment]
Hi @kuaileshizuihao, we provided a [fix](https://github.com/Ensembl/VEP_plugins/pull/746) for this and will be available in the upcoming release (114). I am closing this issue for now. 

Thanks and regards,
Likhitha
