### ISSUE TITLE
INSTALL.pl download_to_file check curl exit code

### ISSUE THREAD

**Issue by aheinzel** [Ensembl/ensembl-vep#176]
I would like to suggest an enhancement for _download_to_file_ in the INSTALL.pl script. In case curl is available it is the preferred way in _download_to_file_ to retrieve data.  However, it is executed in silent mode and it is just assumed that it successfully completes it's task. I would suggest to check the exit code and in case of error either try to fail over to LWP or HTTP::Tiny or just terminate the installer so that the user knows that something went wrong while retrieving data from the web.

This is actually the case for the other options (LWP, HTTP::Tiny) that would be used when curl is not available. The response code is checked and it is even tried to automatically fall back to another option in case of an error. Contrary to the behaviour when curl is used the installer would also be terminated in case both LWP and HTTP:Tiny fail to complete the download.

**Comment by ima23** [comment]
Hi @aheinzel, thanks for the suggestion. I've added the exit code check when using curl. If it fails it will try the next option in line, LWP or HTTP::Tiny. The code should be there starting with release e!93. If you would like to update your code before that, see below the changes. Thanks again!
https://github.com/Ensembl/ensembl-vep/pull/178/files

**Comment by aheinzel** [comment]
Hi @ima23, thanks for incorporating the check. May I (as you are currently on it) also suggest to protect the url with double quotes. It's quite likely that an ampersand has a special meaning in the shell used for evaluating the backticks expression. Thus in case of an url with multiple get parameters only the part of the url till the first ampersand would be passed to curl and the remaining part would be interpreted by the shell (potentially causing side effects unless we have always nice key value pairs).
example w/o quotes:
``echo '$url = "http://httpbin.org/get?a=b&c=d"; print `curl -s --location $url`' | perl``
>  {
  "args": {
    "a": "b"
  }, 
  "headers": {
    "Accept": "*/*", 
    "Connection": "close", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.55.1"
  }, 
  "origin": "149.148.93.45", 
  "url": "http://httpbin.org/get?a=b"
}

example with quotes:
``echo '$url = "http://httpbin.org/get?a=b&c=d"; print `curl -s --location "$url"`' | perl``
>{
  "args": {
    "a": "b", 
    "c": "d"
  }, 
  "headers": {
    "Accept": "*/*", 
    "Connection": "close", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.55.1"
  }, 
  "origin": "149.148.93.45", 
  "url": "http://httpbin.org/get?a=b&c=d"
}

Not sure if this ever happens in the installer, but on the other hand being defensive shouldn't hurt. May also be worth to protect the file name.

**Comment by ima23** [comment]
Hi @aheinzel thanks for your check! I've added the suggested quotes and they should be in at the same time with the other update.

**Comment by aheinzel** [comment]
Hi @ima23 thanks for your efforts!
