### ISSUE TITLE
VEP REST API - Variation allele parameter

### ISSUE THREAD

**Issue by vappiah** [Ensembl/ensembl-vep#1763]
Dear Developers,
I am trying to use the REST API for annotating variants  by specifying the species and region. I would like to understand the meaning of C and DUP in the variant allele parameters.

Thanks

**Comment by dglemos** [comment]
Hi @vappiah,
Can you please send an example?
Here you can find the documentation about the output formats https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#output 
As per the docs, `variant allele` is the allele used to calculate the consequence.

**Comment by vappiah** [comment]
Hi @dglemos . Thanks for the documentation. 
I understand now. And have performed the annotation.

**Comment by dglemos** [comment]
I'm glad it helped.

Best wishes,
Diana
