### ISSUE TITLE
Question: Is it normal to get multiple values in the output from the FORMAT for GT:GQ:AD:DP:VF etc?

### ISSUE THREAD

**Issue by schreyers** [Ensembl/ensembl-vep#1766]
Heya :) So I'm running version 112. I go through a few steps with the data so apologies for the long question :)

The original data is:

``#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	case.bam
chr1	115251293	rs764373235	GA	G	100	R3x6;LowVariantFreq	DP=9008;cosmic=1|COSN26986980,1|COSN27008417,1|COSN27008716;CSQT=1|NRAS|NM_002524.4|intron_variant	GT:GQ:AD:DP:VF:NL:SB:NC	0/1:100:8850,158:9008:0.018:20:-53.1286:0.0000``

I then run a script to merge the FORMAT values into the INFO column. That data looks like this:

``#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	case.bam
chr1	115251293	rs764373235	GA	G	100	R3x6;LowVariantFreq	DP=9008;cosmic=1|COSN26986980,1|COSN27008417,1|COSN27008716;CSQT=1|NRAS|NM_002524.4|intron_variant;FORMAT=GT:GQ:AD:DP:VF:NL:SB:NC|0/1:100:8850#158:9008:0.018:20:-53.1286:0.0000	GT:GQ:AD:DP:VF:NL:SB:NC	0/1:100:8850,158:9008:0.018:20:-53.1286:0.0000``

(I add the # instead off the , in the values as leaving it caused issues before and data would get missed)

I then run the annotation which works, but on the output, the extra_format column that I use a --custom script to add, shows multiple GT:GQ:AD:DP:VF etc values. For example the lines above would show the out values of:

``GT:GQ:AD:DP:VF:NL:SB:NC|0/1:100:8850#158:9008:0.018:20:-53.1286:0.0000,GT:GQ:AD:DP:VF:NL:SB:NC|0/0:98:8836:9008:0.019:20:-100.0000:0.0017``

Also, the FILTER column would change from: R3x6;LowVariantFreq to: R3x6;LowVariantFreq,PASS

Just want to know if this is normal behaviour? and why it would add multiples of the GT:GQ etc values? Some of these values are a mix of incorrect and correct, so we're trying to filter out the incorrect values.

This is my VEP command:

``./vep --cache --dir_cache /opt/.vep/ --format vcf --no_stats --check_existing --sift b --polyphen b --symbol --numbers --keep_csq --canonical --use_transcript_ref --exclude_predicted --transcript_version --protein --pubmed --variant_class --gene_phenotype --allele_number --show_ref_allele --uploaded_allele --use_given_ref --hgvsg_use_accession --hgvs --fasta /opt/ensembl-vep/FASTA/Homo_sapiens.GRCh37.dna.primary_assembly.fa --force_overwrite --species homo_sapiens --merged --assembly GRCh37 --tab -i /home/tmp_annotation/CASE_NUMBER.genome_sorted.vcf -o /home/tmp_annotation/CASE_NUMBER.genome.txt --custom file=/home/tmp_annotation/CASE_NUMBER.genome.vcf.gz,format=vcf,short_name=EXTRA,fields=FILTER%FORMAT%DP%ANT%CSQT%cosmic%GMAF%AA%AF1000G%phyloP 2>&1``

Thanks for any help!

**Comment by olaaustine** [comment]
Hi @schreyers, 
Hope this meets you well? 
Can you try to run VEP without merging the FORMAT values into the INFO column. 
When you run the script to merge the FORMAT values into the INFO column and add the # character, that no longer follows the VCF input file format VEP is expecting
Secondly if possible can you share the custom VCF file you used for annotation so I can try to recreate the issue. 
Thank you 
Ola.

**Comment by schreyers** [comment]
Hey Ola :) Thanks for getting back. 

I tried doing it without the merge and I basically lose all the FORMAT data that I need (sort of)

I'll attach all the files that get produced in each step so that you can see what is happening, but the --custom file line that is used is this:

``chr1	115251293	rs764373235	GA	G	100	R3x6;LowVariantFreq	DP=9008;cosmic=1|COSN26986980,1|COSN27008417,1|COSN27008716;CSQT=1|NRAS|NM_002524.4|intron_variant;ORIGFORMAT=GT:GQ:AD:DP:VF:NL:SB:NC|0/1:100:8850,158:9008:0.018:20:-53.1286:0.0000;	GT:GQ:AD:DP:VF:NL:SB:NC	0/1:100:8850,158:9008:0.018:20:-53.1286:0.0000``

I have stopped replacing the # to see if that worked, but same issue. I also changed the label to be ORIGFORMAT but same issue. 

The final output lines on the column EXTRA_ORIGFORMAT is:

``158:9008:0.018:20:-53.1286:0.0000``

So, it's replacing (sometimes / not consistent) the ORIGFORMAT vales from the merged and replacing them. These values could be the correct ones, but they don't match the  GT:GQ:AD:DP:VF:NL:SB:NC array keys so how do we know what values correlate to what?

So I'm confused where they are coming from? Does Vep generate the GT, GQ, AD, VF data some other way that I have missed?

**Comment by schreyers** [comment]
I think I've over complicated the questions, sorry, so:

1: Why are extra values being added to the EXTRA_ORIGFORMAT column, when they are being fetched from the custom file?
2: Why are there extra filters being added to the FILTERS column?
3: Are there alternative ways to get the values added instead to make things clearer / easier?

Thanks for the help :)

**Comment by schreyers** [comment]
Heya :) So I have come closer to figuring out what is happening. 

I amended the custom file to split and merge the GT:GQ values into the INFO column, so that they become (I add JV to the start to try to keep them unique):

``JVGT=(0/0);JVGQ=(100);JVAD=(8379);JVDP=(8530);JVVF=(0.018);JVNL=(20);JVSB=(-100.0000);JVNC=(0.0119);``

Then, when I run a single line test, the output is correct:

``#Uploaded_variation	Location	Allele	Gene	Feature	Feature_type	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	ALLELE_NUM	REF_ALLELE	UPLOADED_ALLELE	IMPACT	DISTANCE	STRAND	FLAGS	VARIANT_CLASS	SYMBOL	SYMBOL_SOURCE	HGNC_ID	CANONICAL	ENSP	REFSEQ_MATCH	SOURCE	REFSEQ_OFFSET	GENE_PHENO	SIFT	PolyPhen	EXON	INTRON	HGVSc	HGVSp	HGVS_OFFSET	CLIN_SIG	SOMATIC	PHENO	PUBMED	EXTRA	EXTRA_FILTER	EXTRA_DP	EXTRA_ANT	EXTRA_CSQT	EXTRA_cosmic	EXTRA_GMAF	EXTRA_AA	EXTRA_AF1000G	EXTRA_phyloP	EXTRA_JVGT	EXTRA_JVGQ	EXTRA_JVAD	EXTRA_JVDP	EXTRA_JVVF	EXTRA_JVNL	EXTRA_JVSB	EXTRA_JVNC
rs267608087	chr2:48030639-48030640	C	2956	NM_000179.3	Transcript	frameshift_variant	3342-3343	3253-3254	1085	T/TX	acc/aCcc	rs267608078	1	-	-/C	HIGH	-	1	-	insertion	MSH6	EntrezGene	7329	YES	NP_000170.1	-	RefSeq	-	-	-	-	5/10	-	NM_000179.3:c.3261dup	NP_000170.1:p.Phe1088LeufsTer5	8	likely_pathogenic,pathogenic	-	1	25741868,25980754,26845104,24689082,18269114,18301448,10508506,17117178,16807412,20587412,24362816,15483016,20028993,20487569,12658575,15365995,21642682,17453009,15837969,24100870,18809606,25117503,26681312,20301390,27064304,20007843,19526325,17557300,25194673,26787237,28481244,33087929,32832836,35372080,36140642,29371908,31447099,32449172,30322717,20591884,28466842,30730459,31921681,32008151,25110875,32060697,28502729,36988593,32141610,20045164,30147880,30093976,22734033,27854360,9929971,31845022,30387329,21674763,22480969,31783044,28195393,30787465,17082796,9307272,34425783,32660107,32719484,28523262,32042422,26318770	rs267608087	PASS	8500	-	1|FBXO11|NM_001190274.1|downstream_gene_variant	1|COSM308681	-	-	-	-	(0/1)	(100)	(6663~1837)	(8500)	(0.216)	(20)	(-100.0000)	(0.0000)``

If i run 3 test lines, the results in the custom fields get added to, so for example the EXTRA_JVGT value would become (0/1),(0/1),(0/1),(0/0)

I don't know how or why they are being added to with extra values, even when I've made the custom file very custom with brackets etc wrapping the values. 

Any ideas?

**Comment by schreyers** [comment]
Ola, can close this now, sorry for the wasted time. I needed to add flags to the --custom  command.

For anyone else getting this issue - It's because I hadn't set the type to exact!

So my --custom command needed type=exact at the end. 

Hope this helps!
