### ISSUE TITLE
VCF OUTPUT NOT VALID

### ISSUE THREAD

**Issue by vappiah** [Ensembl/ensembl-vep#1772]
Dear Developers,
I annotated a vcf file with VEP and what I got appears not be be the standard VCF format. I would be happy to get advice on what can be done to get a proper vcf output.

Below is the command I used. I have also attached the output file
singularity exec ./vep.sif vep --cache ./vep_cache -i vcf.gz --assembly GRCh38 --species homo_sapiens --af_gnomadg --hgvsg --output_file out.anno.vcf --format vcf Dear Developers,
I annotated a vcf file with VEP and what I got appears not be be the standard VCF format. I would be happy to get advice on what can be done to get a proper vcf output.

Below is the command I used. I have also attached the output file
singularity exec ./vep.sif vep --cache ./vep_cache -i vcf.gz --assembly GRCh38 --species homo_sapiens --af_gnomadg --hgvsg --output_file out.anno.vcf --format vcf 

Output file
[Output.anno.zip](https://github.com/user-attachments/files/17452653/Output.anno.zip)

**Comment by jamie-m-a** [comment]
Hi @vappiah 

The `--format` option is for the input format, natively Ensembl VEP will attempt to autodetect the input format, but you can override this by using `--format`. In the example you show you've told it that the input is VCF.

By default, the output of VEP is the VEP format (the output you have in your file currently). To specify VCF, use `--vcf` in your command (see [here for output format options](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#format))

**Comment by vappiah** [comment]
Thanks very much.
I have been able to generate the vcf.
