### ISSUE TITLE
VEP progress bar

### ISSUE THREAD

**Issue by nihalraman** [Ensembl/ensembl-vep#1777]
Hi VEP team,
I see reference to a 'no_progress' option within the VEP source code that seems to refer to a VEP progress bar. I wasn't able to find anything in the docs about this. How can I get a progress bar to display as VEP is running?

I'm using VEP v112 (singularity)

**Comment by likhitha-surapaneni** [comment]
Hi @nihalraman ,
Thank you for reaching out to us. The `no_progress` option is only relevant for the script converting cache to use tabix. Hope this answers your question.

**Comment by nihalraman** [comment]
Gotcha. Thanks!
