### ISSUE TITLE
VEP can't handle gzipped vcf as input

### ISSUE THREAD

**Issue by Lloyd-LiuSiyi** [Ensembl/ensembl-vep#1781]
## Describe the issue
VEP cannot read compressed (gzipped) vcf file as input.

## Additional information
I first tested annotating a test `vcf` which contains only two SNPs with success. Then I gzipped the same `vcf` into a `.vcf.gz` file, applied the same command line and encountered the error saying `gzip: stdout: Broken pipe`. Despite the error message, VEP was able to produce an annotation output. Finally I tried annotating the original large `.vcf.gz` (28.9GB). In addition to gzip error, the process was also killed, leaving an empty output file.

### System
- VEP version: 113.0
- VEP Cache version: 113
- Perl version: 5.30.0
- OS: 5.10.102.1-Microsoft-standard-WSL2, Ubuntu 20.04.3 LTS
- tabix installation: Not installed

### Full VEP command line
```
vep --cache -i chr12_test_snp.vcf -o chr12_test_vcf_output.txt
vep --cache -i chr12_test_snp.vcf.gz -o chr12_test_vcf_gz_output.txt
vep --cache -i chr12_split_snp_rename.vcf.gz -o chr12_split_snp_rename_annotation.txt
```

### Full error message
For the test `.vcf.gz` I get:
> gzip: stdout: Broken pipe

For the original `.vcf.gz` I get:
> gzip: stdout: Broken pipe
gzip: stdout: Broken pipe
[1]    337 killed     vep --cache -i chr12_split_snp_rename.vcf.gz -o

### Data files (if applicable)
I have attached:
the test `.vcf.gz` file and its corresponding annotation output
[chr12_test_snp.vcf.gz](https://github.com/user-attachments/files/17573773/chr12_test_snp.vcf.gz)
[chr12_test_vcf_gz_output.txt](https://github.com/user-attachments/files/17573775/chr12_test_vcf_gz_output.txt)
and also the empty output of the original large `.vcf.gz`
[chr12_split_snp_rename_annotation.txt](https://github.com/user-attachments/files/17573783/chr12_split_snp_rename_annotation.txt)

Thanks for your help!

**Comment by dglemos** [comment]
Hi @Lloyd-LiuSiyi,
Can you please post the command you run the compress the input files?

**Comment by dglemos** [comment]
I've tested VEP with your input file `chr12_test_snp.vcf.gz` and it completed successfully without any errors or warnings.

**Comment by Lloyd-LiuSiyi** [comment]
Thanks for your time @dglemos! The command I used was `vep --cache -i chr12_test_snp.vcf.gz -o chr12_test_vcf_gz_outp
ut.txt`. I re-ran the script and the error persisted. I've attatched the screenshot here:
![image](https://github.com/user-attachments/assets/803a9dcb-2509-404e-9d7c-16d6a1789f25)
Was this likely because part of my VEP was corrupted since you were able to run VEP without any problem? I'm a bit confused.

**Comment by dglemos** [comment]
How did you compress the input file?
Did you run `bgzip chr12_test_snp.vcf`?

**Comment by Lloyd-LiuSiyi** [comment]
Hi @dglemos, I used the simple `gzip` to compress `chr12_test_snp.vcf`. After reading your comment I tried unzipping `chr12_test_snp.vcf.gz` and re-compressing it with `bgzip`, but the problem remains:
![image](https://github.com/user-attachments/assets/eb274f43-28fd-48de-b8d5-ec07235f513c)
The original large `.vcf.gz` was an output of `bcftools` with the command `-o ${name}.vcf.gz`.

**Comment by Lloyd-LiuSiyi** [comment]
Thanks for your time and patience @dglemos! I'll try Docker and other approaches as well.

**Comment by dglemos** [comment]
I'm going to close this issue, if you keep having issues please open a new ticket.

Best wishes,
Diana
