### ISSUE TITLE
Unable to Locate PolyPhen and SIFT SQLite Files for CHM13 Genome

### ISSUE THREAD

**Issue by LuyaoRen** [Ensembl/ensembl-vep#1783]
Hi,

I am trying to use VEP to annotate variants called against T2T-CHM13, and trying to predict missense variants deleteriousness, but the link to download [homo_sapiens_pangenome_PolyPhen_SIFT_20240502.db](http://ftp.ensembl.org/pub/current_variation/pangenomes/Human/homo_sapiens_pangenome_PolyPhen_SIFT_20240502.db) is not working. Could you please update the link in the tutorial at https://www.ensembl.info/2024/08/09/cool-stuff-ensembl-vep-can-do-supporting-alternative-human-assemblies/ and https://useast.ensembl.org/info/docs/tools/vep/vep_faq.html

Thank you very much!

**Comment by nakib103** [comment]
Hi @LuyaoRen,

Thanks for flagging this to us!
The link in the tutorial is fixed. We are also fixing the one in the faq page.

**Comment by nakib103** [comment]
Hi @LuyaoRen,

The links now all has been updated.
I will close this issue, but feel free to open a new one if you face any further problems.
