### ISSUE TITLE
No protein version from overlap/id/:id end point results

### ISSUE THREAD

**Issue by XLIU-hub** [Ensembl/ensembl-vep#1786]
## Describe the issue
Hi, I am using the rest api end point `overlap/id/:id` to retrieve features (gene -> transcript -> exon -> cds) that overlap with a transcript region. I cannot find version numbers to all the protein identifiers, for example [(https://rest.ensembl.org/overlap/id/ENST00000396373?feature=gene;feature=transcript;feature=exon;feature=cds;content-type=text/x-gff3)](https://rest.ensembl.org/overlap/id/ENST00000396373?feature=gene;feature=transcript;feature=exon;feature=cds;content-type=text/x-gff3) 

Do you think maybe I can get this features info and the protein version info in one go? @pemtaschner Or I can get this protein version from other api endpoints?

Many thnaks!

**Comment by nakib103** [comment]
Hello @XLIU-hub ,

Thanks for your query!

You can get the protein version using the `lookup/id/:id` endpoint, for example - 
```
https://rest.ensembl.org/lookup/id/ENSP00000441463?content-type=application/json
{
  "Parent": "ENST00000545027",
  "length": 88,
  "end": 11840483,
  "version": 1,
  "object_type": "Translation",
  "id": "ENSP00000441463",
  "db_type": "core",
  "start": 11752501,
  "species": "homo_sapiens"
}
```

Best regards,
Nakib

**Comment by nakib103** [comment]
Hi @XLIU-hub,
I will close this issue, but feel free to open a new one if you face any further problems.

**Comment by XLIU-hub** [comment]
Thanks @nakib103 ! 
Yes, I get the version number for protein using `lookup/id/:id`. Do you have plans for adding this in `overlap/id/:id` to make them consistent? And may I ask why the version info for protein is missing in the overlap results,  while genes and transcripts do have this info?

Best,
Liu

**Comment by nakib103** [comment]
Hi @XLIU-hub,

Great that you were able to get the version from `lookup/id/:id` endpoint as suggested.

The `overlap/id/:id` endpoint uses the CDS instead of Translation object because of performance reason, which does not currently expose the version for the related protein. There is no immediate plan to try add protein version to this endpoint.

Best regards,
Nakib
