### ISSUE TITLE
Annotation Discrepancy for Variant 1:98348885_G>A in VEP 113

### ISSUE THREAD

**Issue by GSYongWu** [Ensembl/ensembl-vep#1793]
Hi,
I observed that for the variant **1:98348885_G>A**, the HGVSp annotation returned by VEP is **p.C29=**. However, the expected annotation should be **p.R29C**.
This discrepancy might lead to confusion regarding the effect of this variant, as the amino acid change is significant. 
Could you please investigate this issue? It may help ensure the accuracy of the annotations provided by VEP for users relying on correct variant classifications.
Thank you for your attention to this matter.

Best regards,

**Comment by dglemos** [comment]
Hi @GSYongWu,
To further understand the issue, can you please send the full command you run to annotate the variant?

**Comment by GSYongWu** [comment]
Hi,
My command is:
 "/usr/bin/perl ensembl-vep-release-113.0/vep --offline --no_stats --buffer_size 10000 --fork 4 --ccds --uniprot --hgvs --symbol --shift_3prime 1 --numbers --canonical --protein --biotype --hgvsg --variant_class --total_length --force_overwrite --allele_number --no_escape --vcf --dir  vepdb --fasta genome/hs37d5.fa --format vcf --input_file clincal.merge.vcf --output_file clincal.merge.out.vep.vcf --refseq --use_given_ref --no_check_variants_order"
I tested several hundred mutations and did not encounter this issue with the other mutations

**Comment by GSYongWu** [comment]
11:108183167_AT>GC has the same issue. the HGVSp annotation returned by VEP is p.S1983=. The expected annotation should be p.N1983S.
Additionally, I found that the 10:89624327_C>T variant should be in the intron of PTEN, but the result is annotated upstream of KLLN.

**Comment by dglemos** [comment]
We have released a new VEP version where we fixed this issue.
Can you please update VEP to the latest release https://github.com/Ensembl/ensembl-vep/releases/tag/release%2F113.3 and let me know if you keep having discrepancies in the output?

Thanks

**Comment by dglemos** [comment]
I'm going to close this issue. If you come accross more issue please create a new one.

Best wishes,
Diana
