### ISSUE TITLE
language suffix: vep.pl vs vep

### ISSUE THREAD

**Issue by afif-elghraoui** [Ensembl/ensembl-vep#18]
From https://wiki.debian.org/UpstreamGuide#Language_extensions_in_scripts :
> Debian policy says in section 10.4 Scripts
>
> When scripts are installed into a directory in the system PATH, the script name should not include an extension such as .sh or .pl that denotes the scripting language currently used to implement it. 
>
> Here you can find good reasons for this:
>
>   Wikipedia about command names
>     The use of a filename extension in a command name appears occasionally, usually as a side effect of the command having been implemented as a script (in Bourne shell, Python, etc.) and the interpreter name being suffixed to the command name, a practice common on systems like Windows and Mac OS X, which rely on globally set associations between filename extension and interpreter, but sharply deprecated in UNIX-derived systems like Linux and Apple's Mac OS X, where the interpreter is normally specified as a header in the script. ... 
>
>  Commandname extensions considered harmful
>      Commands should never have filename extensions. Rely on interpreter directives instead or some other paradigm that prevent the implementation from being exposed, or worse yet, lied about, within the very name of the command. 
>
>  one out of several good mails on Debian policy list

Since you're coming out with this new independent version with a different executable name, now might be a good time to address this.

I'm proposing that `vep.pl` be renamed to just `vep` and marked executable. It looks like you have the proper shebang line already (`#!/usr/bin/env perl`). The same would apply to the other scripts.

Execution in the current directory would then be `./vep [...]` rather than `perl vep.pl [...]`. Or, when we have it installed on our systems, we can simply execute it as `vep`.

**Comment by willmclaren** [comment]
> When scripts are installed into a directory in the system PATH, the script name should not include an extension such as .sh or .pl that denotes the scripting language currently used to implement it.

We don't suggest users install VEP into system PATH, though there's nothing to stop you doing so if it better suits your pattern of usage.

It's also straightforward to use alias to get the same effect.

**Comment by afif-elghraoui** [comment]
> We don't suggest users install VEP into system PATH, though there's nothing to stop you doing so if it better suits your pattern of usage.

Even if not installing system-wide, using it with environment modules or otherwise setting PATH presents the same situation-- it's a user-facing program that exposes implementation details. Running pipelines out of a set of extracted download archives gets messy quickly.

> It's also straightforward to use alias to get the same effect.

That's true, but I'd like for us to agree on this-- using the name that you decide improves portability of scripts and workflows based on VEP.

**Comment by willmclaren** [comment]
OK, agreed, see https://github.com/Ensembl/ensembl-vep/commit/3e5ae983ed24d5b56d7fb0f943a800db7b69b319

This will appear in release/88 when available, for now only on master.
