### ISSUE TITLE
ClinVar Pathogenic Variant Not Annotated as Pathogenic in VEP

### ISSUE THREAD

**Issue by xsvato01** [Ensembl/ensembl-vep#1808]
## Describe the issue
Hi,
I noticed a discrepancy in variant annotation between VEP and the official ClinVar website. Specifically, this variant:
https://www.ncbi.nlm.nih.gov/clinvar/variation/839733/ is reported as Pathogenic on the ClinVar website; however, VEP outputs no CLIN_SIG tag.

_596577	11:108272552-108272553	AT	ENSG00000149311	-	ENST00000675843	Transcript	frameshift_variant	3248-3249	3098-3099	1033	K/KX	aaa/aaATa	rs2081640268	HIGH	1	ATM	HGNC	HGNC:795	CCDS31669.1	-	P1	NM_000051.4	ENST00000675843.1:c.3105_3106dup	ENSP00000501606.1:p.Phe1036TyrfsTer4	YES	-	-	-	25614872,23807571	-	-	-	-	-	-	-	-	PDB-ENSP_mappings:5np0.A,PDB-ENSP_mappings:5np0.B,PDB-ENSP_mappings:5np1.A,PDB-ENSP_mappings:6k9k.A,PDB-ENSP_mappings:6k9l.A,PDB-ENSP_mappings:6k9l.B,PDB-ENSP_mappings:7ni4.A,PDB-ENSP_mappings:7ni4.B,PDB-ENSP_mappings:7ni5.A,PDB-ENSP_mappings:7ni5.B,PDB-ENSP_mappings:7ni6.A,PDB-ENSP_mappings:7ni6.B,PDB-ENSP_mappings:7sic.A,PDB-ENSP_mappings:7sic.B,PDB-ENSP_mappings:7sid.A,PDB-ENSP_mappings:7sid.C	1	1	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-_

Online annotator:
[https://www.ensembl.org/Multi/Tools/VEP/Ticket?tl=TFVpu1tVJEcr1UXF](https://www.ensembl.org/Multi/Tools/VEP/Ticket?tl=TFVpu1tVJEcr1UXF)

## Additional information
Does Ensembl filter CLIN_SIG annotations based on the number of publications associated with a given variant? This specific variant has only one supportive publication...

**Comment by likhitha-surapaneni** [comment]
Hi @xsvato01 ,
Thank you for reporting this.
This is happening because the stored allele representation is slightly different and does not match with the provided input allele, we have plans to improve this. You can try giving the rsid (rs2081640268) as an input and check if the clinical significance is returned as expected.

**Comment by xsvato01** [comment]
Hi @likhitha-surapaneni thank you for getting to me so quickly!
I tried the rsid you mentioned as an input, clinical significance is indeed there: https://www.ensembl.org/Homo_sapiens/Tools/VEP/Results?tl=AELKSKURrzrFgf24-10681495

The allele representation does not seem to be normalized, though: https://genebe.net/variant/hg38/rs2081640268

**Comment by likhitha-surapaneni** [comment]
Hi @xsvato01 , good to hear that the clinical significance is as expected with rsid as input. 

The allele representation matched for clinical significance is not normalised, this means that currently, "pathogenic" is returned only when uploaded variant matches against `ATATATAT/ATATAT/ATATATATAT` and subsequently VEP returns the same allele. On the other hand, if the input provided is normalised, the match might not work as expected. We have plans to improve this.

Hope this is helpful!

**Comment by xsvato01** [comment]
Perfect, thank you for clarification!
