### ISSUE TITLE
Issue installing VEP

### ISSUE THREAD

**Issue by cvalenci** [Ensembl/ensembl-vep#181]
HI, I've been trying to install VEP in a linux environment.
 git clone https://github.com/Ensembl/ensembl-vep.git
cd ensembl-vep/
perl INSTALL.pl

# but I always get the same error message about 'Archive::Zip'. I am attaching the entire output below.
Any help will be really appreciate.
Thank you!

Cristian

[VEP.Error.txt](https://github.com/Ensembl/ensembl-vep/files/1877789/VEP.Error.txt)

**Comment by ima23** [comment]
Hi @cvalenci, thanks for the log. The code expects the `Archive::Zip` perl library to be installed. 
I would recommend installing manually the `Archive::Zip` library and rerunning the perl INSTALL.pl script. 
If you use `cpan` or `cpanm` to manage your perl packages, the following command should do the trick `cpan Archive::Zip` or `cpanm Archive::Zip`. You can test and double check that the perl module is installed where you expect it using `perldoc -l Archive::Zip`.

**Comment by ima23** [comment]
Please feel free to reopen the issue if it persists. I will close the ticket for now.
