### ISSUE TITLE
Docker, vep/release92 

### ISSUE THREAD

**Issue by thedam** [Ensembl/ensembl-vep#183]
Hi,
There's some problem in using/updating Docker and VEP92.

```
damian@host:/path/VEP$ docker pull ensemblorg/ensembl-vep
Using default tag: latest
latest: Pulling from ensemblorg/ensembl-vep
Digest: sha256:99d9e1c18b6942ed9eb7f316eb6b477e1838c9f0e26aa19f00d755
```
then:
```
damian@host:/path/VEP$ docker run -t -i -v /path/VEP/vepCache:/home/vep/.vep ensemblorg/ensembl-vep perl INSTALL.pl

Version check reports a newer release of ensembl-vep is available (installed: 91, available: 92)

You may use git to update ensembl-vep by exiting this installer and running:

git pull
git checkout release/92

Do you wish to exit so you can get updates (y) or continue (n): 

```
so I click "no", and I go into a docker session:
`docker run -t -i -v /path/VEP/vepCache:/home/vep/.vep ensemblorg/ensembl-vep /bin/bash`
I do:
```
vep@69dbccf818ab:~/src/ensembl-vep$ git pull
From https://github.com/Ensembl/ensembl-vep
 * [new tag]         release/92.0 -> release/92.0
Already up-to-date.
vep@69dbccf818ab:~/src/ensembl-vep$ git  checkout release/92
Branch release/92 set up to track remote branch release/92 from origin.
Switched to a new branch 'release/92'
vep@69dbccf818ab:~/src/ensembl-vep$ 
```
then from the same session:
```
vep@69dbccf818ab:~/src/ensembl-vep$ perl INSTALL.pl 

Hello! This installer is configured to install v92 of the Ensembl API for use by the VEP.
It will not affect any existing installations of the Ensembl API that you may have.

It will also download and install cache files from Ensembl's FTP server.

Checking for installed versions of the Ensembl API...done
It looks like you have an older version (91) of the API installed.
This installer will install a limited set of the API v92 for use by the VEP only

Skip to the next step (n) to install cache files

Do you want to continue installing the API (y/n)? 
```
It's keeping reminding me that I have an old Ensembl API. It shouldn't be like that, no?

Ps. just to be sure nothing is confused, firstly I've removed all v91 images and caches, and installed v92 from scratch

**Comment by ens-lgil** [comment]
Dear @thedam,

Unfortunately the Docker image you downloaded was still on the version 91 (built before we switched to the version 92 of Ensembl).
We have setup the Docker automated build which create a new image when we push new code on GitHub (which was done before the version 92 was released).
We will need to check from now on that the Docker image match the new release when we switch to a new version. I apologize for this issue.

Docker just rebuilt a new image so you should be able to download the image for the version 92.

Please, let us know if you have any issue with the new image.

Best regards,
Laurent

**Comment by thedam** [comment]
Thanks for quick reaction, it's a pleasure to work with you.
Now I was able to install it without any problems, thanks!

**Comment by ens-lgil** [comment]
Dear @thedam,

I am glad that it works fine now!

Best regards,
Laurent
