### ISSUE TITLE
How to install and use GRCh37 cache for VEP92

### ISSUE THREAD

**Issue by Ural-Yunusbaev** [Ensembl/ensembl-vep#184]
Hi,
There is no homo_sapiens_vep_92_GRCh37.tar.gz file in the folder ftp://ftp.ensembl.org/pub/release-92/variation/VEP/

Can I use homo_sapiens_vep_91_GRCh37.tar.gz for VEP92
?

If not, how to find and use GRCh37 cache for VEP92

Thank you!

**Comment by at7** [comment]
Hi,
the cache files will be copied to the FTP site today. I let you know when they are available. For now you can still use the cache files from 91. Just add --cache_version 91 to your command line arguments.

**Comment by at7** [comment]
The cache files are now on the ftp site. Please repeat the installation command to help you with the download of the GRCh37 cache files.

**Comment by Ural-Yunusbaev** [comment]
It works! Thank you!
