### ISSUE TITLE
installation of older vep versions

### ISSUE THREAD

**Issue by jemten** [Ensembl/ensembl-vep#189]
Hi 
I'm trying to install version 91 of VEP. I'm using the AUTO flags to skip user prompts but the installer still asks me if I want to exit to install version 92. Is there an option to skip the version check when installing VEP or force install an old version without user prompts? 
Cheers,
Anders

This is my install command:
```
git clone https://github.com/Ensembl/ensembl-vep.git
cd ensembl-vep
git checkout release/91
perl INSTALL.pl --AUTO apcf --VERSION 91 --PLUGINS LoFtool,MaxEntScan --SPECIES homo_sapiens --ASSEMBLY GRCh37
```

**Comment by aparton** [comment]
Hi Anders,

You can add the --NO_UPDATE flag to prevent the installation script from looking for an updated version of VEP.

If there’s anything else we can do to help, please let us know.

Kind Regards,
Andrew

**Comment by jemten** [comment]
Thanks!
