### ISSUE TITLE
VEP terminates after  7-10 warnings

### ISSUE THREAD

**Issue by sandertan** [Ensembl/ensembl-vep#19]
Hi,

Thanks again for coming back on my previous issues. Currently I'm running VEP with HGVS notations. For about 5% of my data, I receive the warning message `WARNING: Unable to parse HGVS notation`. The problem is that after 7-10 warnings, VEP terminates. Only after manually removing the incorrect lines the program continues. Is exiting the program intended? Is there a possibility to finish a run with more than a couple warnings, so I can inspect them all at once?

**Comment by willmclaren** [comment]
Should be fixed by https://github.com/Ensembl/ensembl-vep/commit/ff754c1b4b3a0eef9cd7793b742e53717aa63f87, but please let me know if not.
