### ISSUE TITLE
Order of annotation

### ISSUE THREAD

**Issue by dariober** [Ensembl/ensembl-vep#193]
Hello- When a variant affects multiple transcripts, the default annotation is a list of consequences. Does this list have any particular order? 

I'm using the `--flag_pick` option followed by a custom script that puts the picked consequence first on the list. I'm wondering whether in doing so I'm losing some information if the list of consequences has some meaningful order.

(Apologies if this is not really an issue. If you prefer this sort of questions posted elsewhere please let me know.)

**Comment by ens-lgil** [comment]
Dear Dario,

VEP lists the consequences by order of severity (from the most severe to the least severe).
You can see the list of consequences ordered by severity in the following Ensembl documentation page:
http://www.ensembl.org/info/genome/variation/predicted_data.html#consequence_type_table

Best regards,
Laurent

**Comment by dariober** [comment]
Thanks Laurent for the speedy reply. I'm a bit confused though. It seems to me that the picked consequences should be first listed then? However, this doesn't seem to be the case. For example, the record below lists these consequences, where the picked one is the second:

```
A|downstream_gene_variant                     |MODIFIER|AP005530.1|ENSG00000263305|Transcript|ENST00000572062|lincRNA||   |||||||||2170|-1|| |Clone_based_ensembl_gene|,
A|intron_variant&non_coding_transcript_variant|MODIFIER|LINC02564 |ENSG00000262352|Transcript|ENST00000572573|lincRNA||1/2|||||||||    |1 ||1|HGNC                    |HGNC:53604,
A|downstream_gene_variant                     |MODIFIER|AP005530.1|ENSG00000263305|Transcript|ENST00000572608|lincRNA||   |||||||||1875|-1|| |Clone_based_ensembl_gene|,
A|intron_variant&non_coding_transcript_variant|MODIFIER|LINC02564 |ENSG00000262352|Transcript|ENST00000575820|lincRNA||1/1|||||||||    |1 || |HGNC                    |HGNC:53604
```

This is the actual VFC record:

```
chr18   12320   .       T       A       .       .       DP=36;ECNT=1;NLOD=5.42;N_ART_LOD=-1.298e+00;POP_AF=5.000e-08;P_CONTAM=0.00;P_GERMLINE=-9.612e+00;TLOD=64.72;CSQ=A|downstream_gene_variant|MODIFIER|AP005530.1|ENSG00000263305|Transcript|ENST00000572062|lincRNA|||||||||||2170|-1|||Clone_based_ensembl_gene|,A|intron_variant&non_coding_transcript_variant|MODIFIER|LINC02564|ENSG00000262352|Transcript|ENST00000572573|lincRNA||1/2||||||||||1||1|HGNC|HGNC:53604,A|downstream_gene_variant|MODIFIER|AP005530.1|ENSG00000263305|Transcript|ENST00000572608|lincRNA|||||||||||1875|-1|||Clone_based_ensembl_gene|,A|intron_variant&non_coding_transcript_variant|MODIFIER|LINC02564|ENSG00000262352|Transcript|ENST00000575820|lincRNA||1/1||||||||||1|||HGNC|HGNC:53604    GT:AD:AF:F1R2:F2R1:MBQ:MFRL:MMQ:MPOS:SA_MAP_AF:SA_POST_PROB     0/0:18,0:0.050:11,0:7,0:0:302,0:0:0     0/1:1,15:0.937:0,9:1,6:40:294,310:60:20:0.929,0.929,0.938:0.024,0.030,0.946
```

This is with vep 92.1 and the following command:

```
vep --flag_pick --offline --cache --dir_cache {params.dir_cache} --fork 4 --vcf --force_overwrite -i {input.vcf} -o STDOUT --stats_file {output.stats} \\
| bgzip > {output.vcf}
```

**Comment by ens-lgil** [comment]
I think I see what you means:
The `--pick` (and `--flag_pick`) option choose the most relevant line for a variant, using the criteria listed in this documentation page:
http://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick
However you can change the ordering of the criteria, using the option [`--pick_order`](http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_pick_order).

Within a line, the consequences are ordered by severity: in your data example you can see lines with the consequences `intron_variant&non_coding_transcript_variant`.
We rank `intron_variant` more severe than `non_coding_transcript_variant`. That's why `intron_variant` is displayed first within the line.

I hope this makes sense.
Best regards,
Laurent

**Comment by dariober** [comment]
Hi again Laurent. Thank you that makes sense and I'm happy with the default criteria vep uses to pick the most relevant consequence/line. 

What I'm still wondering is whether there is a particular reason why the order of the consequences is this:

```
A|downstream_gene_variant                     |MODIFIER|AP005530.1|ENSG00000263305|Transcript|ENST00000572062|lincRNA||   |||||||||2170|-1|| |Clone_based_ensembl_gene|,
A|intron_variant&non_coding_transcript_variant|MODIFIER|LINC02564 |ENSG00000262352|Transcript|ENST00000572573|lincRNA||1/2|||||||||    |1 ||1|HGNC                    |HGNC:53604,
A|downstream_gene_variant                     |MODIFIER|AP005530.1|ENSG00000263305|Transcript|ENST00000572608|lincRNA||   |||||||||1875|-1|| |Clone_based_ensembl_gene|,
A|intron_variant&non_coding_transcript_variant|MODIFIER|LINC02564 |ENSG00000262352|Transcript|ENST00000575820|lincRNA||1/1|||||||||    |1 || |HGNC                    |HGNC:53604
```

rather than, for example, this one:

```
A|intron_variant&non_coding_transcript_variant|MODIFIER|LINC02564 |ENSG00000262352|Transcript|ENST00000572573|lincRNA||1/2|||||||||    |1 ||1|HGNC                    |HGNC:53604,
A|intron_variant&non_coding_transcript_variant|MODIFIER|LINC02564 |ENSG00000262352|Transcript|ENST00000575820|lincRNA||1/1|||||||||    |1 || |HGNC                    |HGNC:53604
A|downstream_gene_variant                     |MODIFIER|AP005530.1|ENSG00000263305|Transcript|ENST00000572062|lincRNA||   |||||||||2170|-1|| |Clone_based_ensembl_gene|,
A|downstream_gene_variant                     |MODIFIER|AP005530.1|ENSG00000263305|Transcript|ENST00000572608|lincRNA||   |||||||||1875|-1|| |Clone_based_ensembl_gene|,
```

**Comment by ens-lgil** [comment]
Dear Dario,

The ordering of the results per line is simply using the ENST IDs:
- ENST0000057*2062*
- ENST0000057*2573*
- ENST0000057*2608*
- ENST0000057*5820*
This is a default sorting behaviour from the Ensembl Variation API:
https://github.com/Ensembl/ensembl-variation/blob/release/92/modules/Bio/EnsEMBL/Variation/VariationFeature.pm#L592

Best regards,
Laurent
