### ISSUE TITLE
ERROR: Failed to fork for high values of --fork 

### ISSUE THREAD

**Issue by rbatorsky-claritas** [Ensembl/ensembl-vep#194]
Hi, 
I am running on a machine with 36 CPU and tried values of --fork 25 and --fork 30 and got the error "Failed to fork". The same command seems (for now) to be running with --fork 10. Below is the command and error. I am running in docker, ensembl 91. 

```
+ /home/vep/src/ensembl-vep/vep -i test.recal.vcf.gz \
-cache --offline --dir_cache vep_data/ \
--sift b --polyphen b --symbol --af_1kg --af_gnomad --af_esp --max_af --flag_pick \
--fork 30 --buffer_size 50000 --compress_output bgzip --vcf -o test.vep.vcf.gz \
--custom vep_data/gwas_hg19_pmid.bed.gz,NHGRI_EBI_GWAS_PMID,bed,exact,0 --custom vep_data/gwas_hg19_disease_trait.bed.gz,NHGRI_EBI_GWAS_disease_trait,bed,exact,0 --custom vep_data/gwas_hg19_risk_allele.bed.gz,NHGRI_EBI_GWAS_strongest_snp_risk_allele,bed,exact,0 --custom vep_data/gwas_hg19_pvalue.bed.gz,NHGRI_EBI_GWAS_pvalue,bed,exact,0

-------------------- EXCEPTION --------------------
MSG: ERROR: Failed to fork

STACK Bio::EnsEMBL::VEP::Runner::_forked_buffer_to_output /home/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:488
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /home/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:361
STACK Bio::EnsEMBL::VEP::Runner::run /home/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:202
STACK toplevel /home/vep/src/ensembl-vep/vep:222
Date (localtime)    = Sun Apr 22 12:38:59 2018
Ensembl API version = 91 
```

I see the documentation suggests that --fork 4 is appropriate for most users. Is this because most users have 4 cores available or is there another reason that the number of forks is limited to 4? 

I'm running VEP on a large ~25 G multi-sample vcfs so I'm trying to speed things up.

Thank you,
Rebecca

**Comment by helensch** [comment]
Hi

The number of forks will depend on system setup. When using fork, users usually use 4-8 forks. 
You may be having memory issues with higher forks.

Regards
Heen

**Comment by rbatorsky-claritas** [comment]
With 4 forks I get a similar message:
```
WARNING: Chromosome GL000207.1 not found in annotation sources or synonyms on line 23272422
WARNING: Chromosome GL000239.1 not found in annotation sources or synonyms on line 23275098
WARNING: Chromosome GL000245.1 not found in annotation sources or synonyms on line 23276875
WARNING: Chromosome GL000203.1 not found in annotation sources or synonyms on line 23276962
WARNING: Chromosome GL000246.1 not found in annotation sources or synonyms on line 23277076
WARNING: Chromosome GL000238.1 not found in annotation sources or synonyms on line 23277350
WARNING: Chromosome NC_007605 not found in annotation sources or synonyms on line 23392957
WARNING: Chromosome hs37d5 not found in annotation sources or synonyms on line 23392970

-------------------- EXCEPTION --------------------
MSG: ERROR: Failed to fork

STACK Bio::EnsEMBL::VEP::Runner::_forked_buffer_to_output /home/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:488
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /home/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:361
STACK Bio::EnsEMBL::VEP::Runner::run /home/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:202
STACK toplevel /home/vep/src/ensembl-vep/vep:222
Date (localtime)    = Tue Apr 24 23:08:22 2018
Ensembl API version = 91
---------------------------------------------------
```
With --fork 4 I got a large ~25G output vcf with appears to have all variants in it. 
I would like to understand if the error means information was lost. 
I am now running single threaded, but I would like to run multi thread.
Any hints would be appreciated.
Thanks again,
Rebecca

**Comment by rbatorsky-claritas** [comment]
I am  running on a machine with 35 CPU and 58.6 G Memory.

**Comment by aparton** [comment]
Hi Rebecca,

Thank you for the details. I’ve had a look at this issue and have only been able to reproduce it when I tell VEP that more forks exist than are available on the machine. I have a couple of thoughts:

1) Can I ask, what operating system are you running this setup on? Also, has it ran successfully on a single threaded system? Do you receive the same error when you don’t use the custom annotation flags?

2) Unfortunately, the ‘Failed to fork’ error message does mean that whatever output you have received from this run will be incomplete. 

3) Reducing your buffer size from 50000 to approximately 5000 should allow us to rule out a memory issue.

If there’s anything else we can do to help, please let us know.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now - if you would like more support with this problem then please open a new ticket.

Kind Regards,
Andrew
