### ISSUE TITLE
VEP92.1 LoF plugin found 0 "frameshift" PTVs (--assembly GRCh37 --cache_version 92) but other PTVs  types were ok.

### ISSUE THREAD

**Issue by Ural-Yunusbaev** [Ensembl/ensembl-vep#195]
Hi all!
We have obtained VEP LOFTEE (92.1) output quite close to results in Lek et al., 2016.
In our dataset the number of LoF=HC PTVs per chromosome (table 1) and per individual (table 2) were appeared to be close to ExAC's. 
But it looks like we have a problem with "frameshift" LoF=HC PTVs resulted in 0 (table 3). Here we have two questions:
1. How can we fix the bug with 0 frameshift PTV?
2. Which version of VEP and cache were used to prepare the data for the paper Lek et al., 2016?
Thank you!

Used command:
./vep --offline --assembly GRCh37 --force_overwrite --cache --dir_cache ~/.vep --no_stats --plugin LoF,human_ancestor_fa:${INPUT_DIR}/ensembl-vep/ANC_SEQ/human_ancestor.fa.gz,loftee_path:~/.vep/Plugins/loftee --cache_version 92 -i ${INPUT_DIR}/VCF_by_inds_chrom_${i}/${sample} -o ${INPUT_DIR}/ensembl-vep/VEP_OUT92_1/LOFTEE_chrom_${i}_ind_${sample}.txt --dir_plugins ~/.vep/Plugins/loftee

Output:

Table 1
-------------------------------
CHR	LoF=HC*	LoF=LC**
-------------------------------
1	4495	4526
2	2337	4439
3	1144	3575
4	2222	1751
5	1771	2873
6	4486	2010
7	2167	2681
8	1843	4810
9	1085	2593
10	767	520
11	10783	10041
12	3215	2851
13	962	298
14	1062	3186
15	1323	1875
16	3123	2621
17	5830	4493
18	432	3032
19	6107	7033
20	547	150
21	433	125
22	2147	2375
Total	58281	67858
-------------------------------
*  for i in {1..22}; do echo $i; grep "stop_gained\|frameshift\|splice_donor\|splice_acceptor" LOFTEE_chrom_${i}_ind_*.vcf.gz.txt | grep LoF=HC | wc -l; done
** for i in {1..22}; do echo $i; grep "stop_gained\|frameshift\|splice_donor\|splice_acceptor" LOFTEE_chrom_${i}_ind_*.vcf.gz.txt | grep LoF=LC | wc -l; done

Table 2
-------------------------------
N	INDIVID_ID	LoF=HC*
-------------------------------
1	S000014405	148
2	S000014412	129
3	S000014411	146
4	S000014410	151
5	S000014408	148
...
401	S000035685	119

Total	58281
Avarage	145,3
Max	208
Min	97
-------------------------------
* for sample in $(bcftools query --list-samples /mmg/ural/heterosis/singleton_MAC_filtered/SINGLETONS_removed_d_22.recode.vcf); do echo $sample; grep "stop_gained\|frameshift\|splice_donor\|splice_acceptor" LOFTEE_chrom_*_ind_${sample}.vcf.gz.txt | grep LoF=HC | wc -l; done

Table 3
-------------------------------
PTV_type	LoF=HC*	LoF=LC**
-------------------------------
stop_gained	37829	11532
splice_acceptor	10479	18328
splice_donor	9973	37998
frameshift	0	0
Total	58281
-------------------------------
*
grep "stop_gained"     LOFTEE_chrom_*_ind_*.vcf.gz.txt | grep LoF=HC | wc -l
grep "splice_acceptor" LOFTEE_chrom_*_ind_*.vcf.gz.txt | grep LoF=HC | wc -l
grep "splice_donor"    LOFTEE_chrom_*_ind_*.vcf.gz.txt | grep LoF=HC | wc -l
grep "frameshift"      LOFTEE_chrom_*_ind_*.vcf.gz.txt | grep LoF=HC | wc -l

**
grep "stop_gained"     LOFTEE_chrom_*_ind_*.vcf.gz.txt | grep LoF=LC | wc -l
grep "splice_acceptor" LOFTEE_chrom_*_ind_*.vcf.gz.txt | grep LoF=LC | wc -l
grep "splice_donor"    LOFTEE_chrom_*_ind_*.vcf.gz.txt | grep LoF=LC | wc -l
grep "frameshift"      LOFTEE_chrom_*_ind_*.vcf.gz.txt | grep LoF=LC | wc -l

**Comment by aparton** [comment]
Hi,

Thank you for your query. While we include LoFtee within the VEP installer, it was developed by an out-of-house team who would be better placed to answer your question. You can find them at: https://github.com/konradjk/loftee <https://github.com/konradjk/loftee>

As far as I am aware they are very responsive to questions and should be able to help you out.

Kind Regards,
Andrew

**Comment by Ural-Yunusbaev** [comment]
Thank you.
