### ISSUE TITLE
Variation in LTBP4

### ISSUE THREAD

**Issue by shaytzur** [Ensembl/ensembl-vep#196]
Annotation using VEP for the variant chr19:41135308 C > T (hg19)  gave:
LTBP4,NM 001042544.1:c.**4727C**>T,NP 001036009.1:p.Asn1576=

However,  the correct c. position is **7428** and not 7427.
In position 4727 there is A in the reference, and not C.

Thank you!

**Comment by sarahhunt** [comment]
Hi @shaytzur ,

Thanks for this report, it is an issue we are aware of. As you probably know, not all RefSeq transcripts completely match the reference genome. In cases where they don't, we are now using alignment files provided by NCBI to create a new reference, matching the transcript, and use this for consequence calling. 

Our HGVS calculation does not currently use this reference modification, but it is something we are working on and aim to release later this year. VEP can report reference miss-matches for GRCh38, but these data are not available for GRCh37. 

Best wishes,
Sarah

**Comment by shaytzur** [comment]
Thank you for your quick response, looking forward to this update. 
Regards,
Shay

**Comment by LukiDan** [comment]
Hi Sarah,
I am probably experiencing a similar issue as @shaytzur related to not matched RefSeq transcripts. I tried to annotate chr10:87965321 C>T (hg38, rs375709098) by VEP version 94 (offline cache). I obtained three HGVS features (NM_000314.6:c.1062C>T, NM_001304717.2:c.1580C>T, NM_001304718.1:c.471C>T). However, the coding position of only the middle one is correct while the remaining ones are incremented by one (should be NM_000314.6:c.1061C>T and NM_001304718.1:c.470C>T). I am aware of RefSeq HGVS calculation issues, but I am a bit puzzled by the BAM_EDIT field. It shows OK for NM_000314.6:c.1062C>T and NM_001304718.1:c.471C>T while FAILED for NM_001304717.2:c.1580C>T. Is there any (other) option to recognize transcripts not completely matching the reference genome? 
Thank you.

Best regards,
Lukas
[BS1585-18_S1_ME_L001_hg38_so_rmdp.xlsx](https://github.com/Ensembl/ensembl-vep/files/2620396/BS1585-18_S1_ME_L001_hg38_so_rmdp.xlsx)
