### ISSUE TITLE
Strange characters in HGVSp notation

### ISSUE THREAD

**Issue by thedam** [Ensembl/ensembl-vep#199]
Hi,
I'm using VEP v92 with Docker. I've run this command:

`vep -i test.vcf --cache --refseq  -o test.tsv  --port 3337 --tab --ASSEMBLY GRCh37 --hgvs `

Example lines of output from some three transcripts:

#Uploaded_variation | Location | Allele | Gene | Feature | Feature_type | Consequence | cDNA_position | CDS_position | Protein_position | Amino_acids | Codons | Existing_variation | IMPACT | DISTANCE | STRAND | FLAGS | REFSEQ_MATCH | GIVEN_REF | USED_REF | BAM_EDIT | HGVSc | **HGVSp** | HGVS_OFFSET
chr10_101544447_A/T | chr10:101544447 | T | 1244 | NM_000392.3 | Transcript | missense_variant | 255 | 116 | 39 | Y/F | tAc/tTc | - | MODERATE | - | 1 | - | - | A | A | - | NM_000392.3:c.116A>T | **NP_000383.1:p.Tyr39Phe** | -
chr10_101544447_A/T | chr10:101544447 | T | 1244 | NM_000392.4 | Transcript | synonymous_variant | 363 | 116 | 39 | F | tTc/tTc | - | LOW | - | 1 | - | - | A | T | OK | NM_000392.4:c.116A>T | **NP_000383.1:p.Phe39%3D** | -
chr10_101544447_A/T | chr10:101544447 | T | 1244 | XM_005269536.1 | Transcript | missense_variant | 261 | 116 | 39 | Y/F | tAc/tTc | - | MODERATE | - | 1 | - | - | A | A | - | XM_005269536.1:c.116A>T | **XP_005269593.1:p.Tyr39Phe** | -

The notation like **NP_000383.1:p.Phe39%3D** is a bug, no?

Cheers

**Comment by thedam** [comment]
ah ok, thanks for info.
Would be nice to add some example here: http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html
`--no_escape         Don't URI escape HGVS strings. Default = escape`
Users may not know what it really means :)

**Comment by sarahhunt** [comment]
Good idea - we'll add an example.
