### ISSUE TITLE
failed installation

### ISSUE THREAD

**Issue by rosedu1** [Ensembl/ensembl-vep#200]
Hi,
I received the following error message when trying to do the installation with perl INSTALL.pl

Can't locate Bio/EnsEMBL/Utils/Exception.pm in @INC

I am able to install this from a source code but the Config.pm file in ~/ensembl-vep/modules/Bio/EnsEMBL/VEP has the line:

use Bio::EnsEMBL::Utils::Exception qw(throw warning);

The directory Bio]/EnsEMBL/Utils does not exist. Should I be manually creating this directory and copying Exception.pm to it?

Thanks!
Rose

**Comment by aparton** [comment]
Hi,

Thanks for your query. It looks like there has been an issue with installing the underlying ensembl API - could you please send me the full output of the install script when you try to install with ‘perl INSTALL.pl’? Additionally, what OS are you trying to install VEP onto?

Kind Regards,
Andrew

**Comment by rosedu1** [comment]
Andrew,
Thanks for getting back to me! 
I saw another post about issues with BioPerl and VEP so I went ahead and installed BioPerl manually. After I did that, the problem resolved.

Rose
