### ISSUE TITLE
--pick_order criteria

### ISSUE THREAD

**Issue by ktroule** [Ensembl/ensembl-vep#201]
I've two questions.

I've a vcf file with GRch37/hg19.

For each variant I'm trying to retain only the most important transcript. 
I know  that because I'm using GRch37/hg19 I cannot annotate the vcf file using --appris, but I'm guessing that when using `--pick_order appris` it still does the job of keeping only the principal transcript whenever this is possible, right?

The other question, if I use `--pick_order appris` , it will only use the criteria from appris right? If I want to use another criteria in case no info is found in appris I should write like  `--pick_order appris,canonical`

Thanks for your help

**Comment by ens-lgil** [comment]
Dear @ktroule,

**Comment by ens-lgil** [comment]
Dear @ktroule,

Regarding the first question, I don't think this will keep the principal transcript as we don't have APPRIS data on GRCh37.
Which leads to your second question: the `--pick_order` option change the [default list of criteria](http://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick), i.e.:
- if you use `--pick_order appris`, this will only filter on the APPRIS criteria
- if you use `--pick_order appris,canonical`, this will only filter on the APPRIS and canonical criteria.

Here is the location of the code, to give you more information:
https://github.com/Ensembl/ensembl-vep/blob/release/92/modules/Bio/EnsEMBL/VEP/OutputFactory.pm#L674

I hope this helps.
Laurent

**Comment by ktroule** [comment]
Thanks, and a very last question. Do I have to specify both flags in order to keep only the principal transcripts?  `--pick --pick_order appris,canonical,tsl` because to me, it seems to be slower when I do not specify the first one,a dn I'm not sure after reading the manual.

Thanks
