### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by adbeggs** [Ensembl/ensembl-vep#205]
Hi

I'm trying to install ensembl-vep on Ubuntu 17.10 (Artful). It keeps crashing out with the below - any suggestions? I have installed Bioperl both manually and from apt-get.

Downloading required Ensembl API files
 - fetching ensembl
 - unpacking ./Bio/tmp/ensembl.zip
 - moving files
 - getting version information
 - fetching ensembl-variation
 - unpacking ./Bio/tmp/ensembl-variation.zip
 - moving files
 - getting version information
 - fetching ensembl-funcgen
 - unpacking ./Bio/tmp/ensembl-funcgen.zip
 - moving files
 - getting version information
 - fetching ensembl-io
 - unpacking ./Bio/tmp/ensembl-io.zip
 - moving files
 - getting version information

Testing VEP installation
./t/Parser_HGVS.t .................................... Possible precedence issue with control flow operator at /home/beggsa/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 791.
./t/Parser_HGVS.t .................................... 1/?
#   Failed test 'use Bio::EnsEMBL::VEP::Parser::HGVS;'
#   at ./t/Parser_HGVS.t line 32.
#     Tried to use 'Bio::EnsEMBL::VEP::Parser::HGVS'.
#     Error:  Base class package "Bio::EnsEMBL::IO::Parser" is not empty but "Bio/EnsEMBL/IO/Parser.pm" exists in the current directory.
#     To help avoid security issues, base.pm now refuses to load optional modules
#     from the current working directory when it is the last entry in @INC.
#     If your software worked on previous versions of Perl, the best solution
#     is to use FindBin to detect the path properly and to add that path to
#     @INC.  As a last resort, you can re-enable looking in the current working
#     directory by adding "use lib '.'" to your code.
#  at Bio/EnsEMBL/IO/TextParser.pm line 45.

**Comment by ens-lgil** [comment]
Dear @adbeggs,

Can I ask you which version of Perl you are using and which version of BioPerl did you install ?
Here are the versions supported by VEP: [http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#requirements](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#requirements)
VEP requires [BioPerl version 1.6.924](wget https://github.com/bioperl/bioperl-live/archive/release-1-6-924.zip).

Best regards,
Laurent

**Comment by oranelle** [comment]
It took me hours to figure it out. Following Andrew's reply. In 3), simply delete bioperl by
https://stackoverflow.com/questions/11958614/how-to-safely-uninstall-bioperl-that-was-installed-via-cpan
rerun the installer... All credit to Andrew,thx!

**Comment by zmiimz** [comment]
```
#     Tried to use 'Bio::EnsEMBL::VEP::Runner'.
#     Error:  Base class package "Bio::EnsEMBL::IO::Parser" is not empty but "Bio/EnsEMBL/IO/Parser.pm" exists in the current directory.
 #     To help avoid security issues, base.pm now refuses to load optional modules
#     from the current working directory when it is the last entry in @INC.
#     If your software worked on previous versions of Perl, the best solution
#     is to use FindBin to detect the path properly and to add that path to
#     @INC.  As a last resort, you can re-enable looking in the current working
#     directory by adding "use lib '.'" to your code.
```
the message from base.pm is clear enough. imho, you should better fix the code

**Comment by zmiimz** [comment]
Dear Andrew,

I had the same message and failure of many tests during installation of VEP with perl v5.26.1
VEP installation with installed locally perl v5.24 goes smoothly without errors.
I suppose (didn't check it) that according to https://perl5.git.perl.org/perl.git/commitdiff/refs/heads/ap/baseincguard  
and https://en.wikipedia.org/wiki/Perl_5_version_history
(For security reasons, the current directory (".") is no longer included by default at the end of the module search path (@INC))
the code of many modules or test cases in VEP are incompatible with perl version >= 5.26

I have exactly the same issue, m.b. there is no need to open another one?
