### ISSUE TITLE
Strange Annotation using Refseq GFF

### ISSUE THREAD

**Issue by segoerge** [Ensembl/ensembl-vep#210]
Hi,

I'm using VEP v92.1 and I've found a weird annotation in the results.

Command:
./vep -i in.vcf -o out.vcf --vcf --hgvs --fasta hg19.fa --force_overwrite --fork 2 --variant_class --vcf_info_field ANN --numbers --total_length --canonical --exclude_predicted --allele_number --custom interim_GRCh37.p13_top_level_2017-01-13.gff3.gz,RefSeq,gff --custom Homo_sapiens.GRCh37.87.chromosome.MT.gff3.gz,Ensembl,gff --synonyms chr_synonyms.txt --transcript_filter "stable_id match N[MR]_ or stable_id match ENST"

Variant: 
10	23482635	.	T	C	812.79	.	AC=1;AF=0.5;AN=2;BaseQRankSum=0.122;ClippingRankSum=0.0;DP=44;ExcessHet=3.0103;FS=4.199;MLEAC=1;MLEAF=0.5;MQ=59.21;MQRankSum=-0.528;QD=18.9;ReadPosRankSum=0.724;SOR=0.886;ANN=C|start_lost&splice_region_variant|HIGH|PTF1A|256297|Transcript|NM_178161.2|protein_coding|2/2||NM_178161.2%3Ac.3T>C|NP_835455.1%3Ap.Ter1?|787/1333|3/204|1/67|X|ngT/ngC||1||1||SNV||||RefSeq|||	GT:AD:DP:GQ:PL	0/1:6,37:43:22:841,0,22

Refseq file was taken from: ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/GRCh37.p13_interim_annotation/

Somehow effect, hgvsc and hgvsp are strangely annotated. I think it should be a normal missense variant in exon 2 or am i wrong? Startlost doesn't fit to p.Ter1? and the start codon is even in the first exon. I've also tested the online version of VEP and there it's correct. Is there maybe something wrong with the gff processing?

Best regards,
Sebastian

**Comment by sarahhunt** [comment]
Hi @segoerge 

Sorry about the delay in getting back to you. Thanks for reporting this one - there was a bug in how CDS lines in the GFF files were being handled which was causing missinterpretation of some exons.  This is fixed now in VEP 92.

Best wishes,
Sarah

**Comment by segoerge** [comment]
Hi,

I've also tested this now with the most recent version of VEP. Looks good now! Thanks!
