### ISSUE TITLE
Create fasta index file for an arbitrary genome

### ISSUE THREAD

**Issue by meyermj** [Ensembl/ensembl-vep#211]
I'd like to pre-compute the index files for many fasta files (thereby enabling their use with --hgvs and --check_ref). Given an arbitrary .fasta file, is it possible to "trick" ensembl-vep to perform the indexing operation without downloading the corresponding cache data.

**Comment by ens-lgil** [comment]
Dear @meyermj,
You can specify the fasta file you want to use for VEP using the option `--fasta`
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_fasta
This will create an index of the fasta file automatically if there is none.

Best regards,
Laurent

**Comment by willmclaren** [comment]
You could also create the index with a little perl one-liner. Assuming you have VEP installed in `$HOME/src`:

```perl -I ~/src/ensembl-vep/ -MBio::DB::HTS::Faidx -e 'Bio::DB::HTS::Faidx->new(shift @ARGV)' [path_to_FASTA]```

**Comment by meyermj** [comment]
@ens-lgil, I tried using the `--fasta` option. Unfortunately, the program fails because it expects the `--species` field to be filled with a species that exists in the cache directory. I wonder if it's okay to trick ensembl-vep by providing a small dummy cache (i.e. S. cerevisiae), and indexing a fasta file that is not associated with the dummy species (i.e. homo_sapiens)? Will the cache files affect the index at all?

@willmclaren, this looks promising, but unfortunately I get the following error:
```
Can't locate Bio/DB/HTS/Faidx.pm in @INC (you may need to install the Bio::DB::HTS::Faidx module) (@INC contains: /home/ubuntu/ensembl-vep/ /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .).
```

**Comment by willmclaren** [comment]
If you don't have Bio::DB::HTS::Faidx installed, the installer (INSTALL.pl) should set it up for you. If this fails for whatever reason, VEP can fall back on an older module, Bio::DB::Fasta instead. In this scenario you can run the exact same one-liner as above, replacing Bio::DB::HTS::Faidx with Bio::DB::Fasta:

```perl -I ~/src/ensembl-vep/ -MBio::DB::Fasta -e 'Bio::DB::Fasta->new(shift @ARGV)' [path_to_FASTA]```

If you are able to install Bio::DB::HTS::Faidx then it is strongly recommended to use this instead as it offers numerous advantages over Bio::DB::Fasta.

**Comment by meyermj** [comment]
Never mind, something appears different about `samtools faidx`. `ensembl-vep` throws this error when trying to use a `samtools`-indexed genome:
```
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Could not open index file /home/ubuntu/test2/Homo_sapiens.GRCh38.dna.primary_assembly.fa.index: Inappropriate ioctl for device
STACK: Error::throw
STACK: Bio::Root::Root::throw /home/ubuntu/ensembl-vep/Bio/Root/Root.pm:449
STACK: Bio::DB::IndexedBase::_open_index /home/ubuntu/ensembl-vep/Bio/DB/IndexedBase.pm:666
STACK: Bio::DB::IndexedBase::_index_files /home/ubuntu/ensembl-vep/Bio/DB/IndexedBase.pm:643
STACK: Bio::DB::IndexedBase::index_file /home/ubuntu/ensembl-vep/Bio/DB/IndexedBase.pm:484
STACK: Bio::DB::IndexedBase::new /home/ubuntu/ensembl-vep/Bio/DB/IndexedBase.pm:364
STACK: Bio::EnsEMBL::Variation::Utils::FastaSequence::_get_fasta_db /home/ubuntu/ensembl-vep/Bio/EnsEMBL/Variation/Utils/FastaSequence.pm:341
STACK: Bio::EnsEMBL::Variation::Utils::FastaSequence::setup_fasta /home/ubuntu/ensembl-vep/Bio/EnsEMBL/Variation/Utils/FastaSequence.pm:212
STACK: Bio::EnsEMBL::VEP::BaseVEP::fasta_db /home/ubuntu/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:477
STACK: Bio::EnsEMBL::VEP::Runner::init /home/ubuntu/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:129
STACK: Bio::EnsEMBL::VEP::Runner::run /home/ubuntu/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK: /home/ubuntu/ensembl-vep/vep:224
-----------------------------------------------------------
```

**Comment by willmclaren** [comment]
I suspect an index created by Bio::DB::HTS::Faidx would be compatible with samtools and vice versa, but one generated by Bio::DB::Fasta would certainly not.

**Comment by meyermj** [comment]
@willmclaren thanks! Your first suggestion works inside the `ensembl-vep` docker container, so when the all components are present, it seems to work. I also believe that `samtools faidx` will be compatible with the docker container version of `ensembl-vep` since it is using the `Faidx` component.
