### ISSUE TITLE
Install VEP behind proxy

### ISSUE THREAD

**Issue by stefandiederich** [Ensembl/ensembl-vep#22]
Hi, 

I want to install VEP with all its dependencies by using the INSTALL.pl script. Unfortunattely we have to connect to the internet via a proxy server in our medical center.  And it seems like the script can not connect to the internet. Is there an option to tell the IP adress of our proxy server to the script? Or is there any workaround?

Thanks in advance!
Stefan

**Comment by willmclaren** [comment]
The installer should observe the values of the `http_proxy` and `ftp_proxy` environment variables:

```
$ export http_proxy=[proxy_server]:[port]
$ export ftp_proxy=[proxy_server]:[port]
$ perl INSTALL.pl
```

**Comment by stefandiederich** [comment]
Dear William,

thanks for your quick response.
I now got the installer working through our proxy server, but when I run VEP with the following parameter I get an error:

perl vep.pl --offline --dir '/media/Berechnungen/AnnotationDBs/vep' --fasta '/media/Berechnungen/Referenzgenom/HG19/HG19.karyo.fasta.VEP.fa' --everything --assembly GRCh37 -i '/media/Berechnungen/newVEP/ensembl-vep-release-87/testdata/0823-16.vcf' -o '/media/Berechnungen/newVEP/ensembl-vep-release-87/testdata/0823-16.newannot.vcf' --plugin CADD,'/media/Berechnungen/AnnotationDBs/cadd/20160314/whole_genome_SNVs.tsv.gz','/media/Berechnungen/AnnotationDBs/cadd/20160314/cadd_InDels.tsv.gz' -custom '/media/Berechnungen/AnnotationDBs/phylop/20160314/hg19.100way.phyloP100way.bw',PhyloP,bigwig,exact,0 -custom '/media/Berechnungen/AnnotationDBs/ihdb/20170208/ihdb.vcf.gz',IHDB,vcf,overlap,0 --buffer_size 10000 --vcf --pick --pick_order rank,canonical,appris,tsl,biotype,ccds,length --force_overwrite

-------------------- EXCEPTION --------------------
MSG: ERROR: Cannot use format bigwig without Bio::DB::BigFile module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /media/Berechnungen/newVEP/ensembl-vep-release-87/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /media/Berechnungen/newVEP/ensembl-vep-release-87/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:141
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /media/Berechnungen/newVEP/ensembl-vep-release-87/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:65
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /media/Berechnungen/newVEP/ensembl-vep-release-87/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:119
STACK Bio::EnsEMBL::VEP::Runner::init /media/Berechnungen/newVEP/ensembl-vep-release-87/modules/Bio/EnsEMBL/VEP/Runner.pm:77
STACK Bio::EnsEMBL::VEP::Runner::run /media/Berechnungen/newVEP/ensembl-vep-release-87/modules/Bio/EnsEMBL/VEP/Runner.pm:111
STACK toplevel vep.pl:193
Date (localtime)    = Fri Feb 17 08:45:10 2017
Ensembl API version = 87
---------------------------------------------------
administrator@k-hg-srv1:/media/Berechnungen/newVEP/ensembl-vep-release-87$+

Is this package not installed directly with the INSTALL.pl. And also, the installer does not download the cache files after installing the api.
Maybe you can tell me what I am doing wrong…

Bests
Stefan
________________________________________
Stefan Diederich
M. Sc. Bioinformatik

Universitätsmedizin
der Johannes Gutenberg-Universität Mainz
Langenbeckstraße 1, 55131 Mainz
Tel.: 06131 17-5797

Von: William McLaren [mailto:notifications@github.com]
Gesendet: Donnerstag, 16. Februar 2017 18:08
An: Ensembl/ensembl-vep
Cc: Diederich, Stefan; Author
Betreff: Re: [Ensembl/ensembl-vep] Install VEP behind proxy (#22)


The installer should observe the values of the http_proxy and ftp_proxy environment variables:

$ export http_proxy=[proxy_server]:[port]

$ export ftp_proxy=[proxy_server]:[port]

$ perl INSTALL.pl

**Comment by willmclaren** [comment]
Correct, Bio::DB::BigFile is not installed by the INSTALL.pl script, for a couple of reasons:

1) most people won't use it
2) it's a bit of a pig to install :-)

This is stated in our [README](https://github.com/Ensembl/ensembl-vep#install). Here are the [instructions for installation](http://cpansearch.perl.org/src/LDS/Bio-BigFile-1.07/README). You may find that the latest version of jksrc causes an error when installing Bio::DB::BigFile; we use v335 ([https://github.com/ucscGenomeBrowser/kent/archive/v335_base.tar.gz](https://github.com/ucscGenomeBrowser/kent/archive/v335_base.tar.gz))

Regarding the installer not downloading cache files, it should do - what is the specific problem you are seeing? If it still fails, you can [download and unpack them yourself](http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#pre).

**Comment by stefandiederich** [comment]
Yeah, we will use it for annotations of PHYLOP data…

I am trying to install the kent source tree and always get a lot of errors. I will try the version you told me. Maybe I have more luck with that.
The Installer does not jump into the cache file download because there is something going wrong at the testphase I think. But I have the cache files from the old Variant Effect Predictor version 87, will this work too?

Testing VEP installation
./t/OutputFactory.t .................................. Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/OutputFactory.t .................................. ok
./t/AnnotationSource_Cache.t ......................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource_Cache.t ......................... ok
./t/AnnotationSource_Cache_Transcript.t .............. Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource_Cache_Transcript.t .............. ok
./t/Parser_VCF.t ..................................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/Parser_VCF.t ..................................... ok
./t/AnnotationSource_File_GFF.t ...................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource_File_GFF.t ...................... ok
./t/OutputFactory_VEP_output.t ....................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/OutputFactory_VEP_output.t ....................... ok
./t/AnnotationSource.t ............................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource.t ............................... ok
./t/Parser_ID.t ...................................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/Parser_ID.t ...................................... ok
./t/AnnotationSource_File.t .......................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource_File.t .......................... ok
./t/BaseVEP.t ........................................ Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/BaseVEP.t ........................................ ok
./t/AnnotationSource_Cache_Variation.t ............... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource_Cache_Variation.t ............... ok
./t/CacheDir.t ....................................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/CacheDir.t ....................................... ok
./t/AnnotationSource_File_VCF.t ...................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource_File_VCF.t ...................... ok
./t/OutputFactory_VCF.t .............................. Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/OutputFactory_VCF.t .............................. ok
./t/AnnotationSource_BaseVariation.t ................. Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource_BaseVariation.t ................. ok
./t/Runner.t ......................................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/Runner.t ......................................... ok
./t/Stats.t .......................................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/Stats.t .......................................... ok
./t/AnnotationSource_File_BigWig.t ................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource_File_BigWig.t ................... ok
./t/AnnotationSourceAdaptor.t ........................ Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSourceAdaptor.t ........................ ok
./t/FilterSet.t ...................................... ok
./t/Config.t ......................................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/Config.t ......................................... ok
./t/AnnotationSource_Database_StructuralVariation.t .. Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource_Database_StructuralVariation.t .. ok
./t/AnnotationSource_Database_Variation.t ............ Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource_Database_Variation.t ............ ok
./t/AnnotationSource_Cache_VariationTabix.t .......... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource_Cache_VariationTabix.t .......... ok
./t/AnnotationSource_Cache_RegFeat.t ................. Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource_Cache_RegFeat.t ................. ok
./t/version.t ........................................ fatal: Not a git repository (or any parent up to mount point /media/Berechnungen)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./t/version.t ........................................ 1/?
#   Failed test 'get current git branch'
#   at ./t/version.t line 31.
# Looks like you failed 1 test of 1.
./t/version.t ........................................ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
./t/Parser.t ......................................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/Parser.t ......................................... ok
./t/Parser_HGVS.t .................................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/Parser_HGVS.t .................................... ok
./t/AnnotationSource_Database_Transcript.t ........... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource_Database_Transcript.t ........... ok
./t/OutputFactory_Tab.t .............................. Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/OutputFactory_Tab.t .............................. ok
./t/OutputFactory_JSON.t ............................. Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/OutputFactory_JSON.t ............................. ok
./t/InputBuffer.t .................................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/InputBuffer.t .................................... ok
./t/AnnotationSource_File_BED.t ...................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource_File_BED.t ...................... ok
./t/AnnotationSource_File_GTF.t ...................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource_File_GTF.t ...................... ok
./t/Parser_VEP_input.t ............................... Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/Parser_VEP_input.t ............................... ok
./t/Utils.t .......................................... ok
./t/AnnotationSource_Database_RegFeat.t .............. Possible precedence issue with control flow operator at /usr/local/share/perl/5.22.1/Bio/DB/IndexedBas                                                                                e.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 210.
./t/AnnotationSource_Database_RegFeat.t .............. ok

Test Summary Report
-------------------
./t/version.t                                      (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=37, Tests=1437, 82 wallclock secs ( 0.30 usr  0.15 sys + 78.05 cusr  5.02 csys = 83.52 CPU)
Result: FAIL
Failed 1/37 test programs. 1/1437 subtests failed.
________________________________________
Stefan Diederich
M. Sc. Bioinformatik

Universitätsmedizin
der Johannes Gutenberg-Universität Mainz
Langenbeckstraße 1, 55131 Mainz
Tel.: 06131 17-5797

Von: William McLaren [mailto:notifications@github.com]
Gesendet: Freitag, 17. Februar 2017 10:13
An: Ensembl/ensembl-vep
Cc: Diederich, Stefan; Author
Betreff: Re: [Ensembl/ensembl-vep] Install VEP behind proxy (#22)


Correct, Bio::DB::BigFile is not installed by the INSTALL.pl script, for a couple of reasons:

  1.  most people won't use it
  2.  it's a bit of a pig to install :-)

This is stated in our README<https://github.com/Ensembl/ensembl-vep#install>. Here are the instructions for installation<http://cpansearch.perl.org/src/LDS/Bio-BigFile-1.07/README>. You may find that the latest version of jksrc causes an error when installing Bio::DB::BigFile; we use v335 (https://github.com/ucscGenomeBrowser/kent/archive/v335_base.tar.gz)

Regarding the installer not downloading cache files, it should do - what is the specific problem you are seeing? If it still fails, you can download and unpack them yourself<http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#pre>.

**Comment by willmclaren** [comment]
The tests seem OK apart from one, version.t - how did you obtain the ensembl-vep repository? Did you use

`git clone https://github.com/Ensembl/ensembl-vep.git`

or similar? Or did you download the zip file?

In either case you can force the installer to skip tests with `--NO_TEST`

**Comment by stefandiederich** [comment]
I obtained it by downloading the zip file and will force the installer to skip the tests now

________________________________________
Stefan Diederich
M. Sc. Bioinformatik

Universitätsmedizin
der Johannes Gutenberg-Universität Mainz
Langenbeckstraße 1, 55131 Mainz
Tel.: 06131 17-5797

Von: William McLaren [mailto:notifications@github.com]
Gesendet: Freitag, 17. Februar 2017 10:38
An: Ensembl/ensembl-vep
Cc: Diederich, Stefan; Author
Betreff: Re: [Ensembl/ensembl-vep] Install VEP behind proxy (#22)


The tests seem OK apart from one, version.t - how did you obtain the ensembl-vep repository? Did you use

git clone https://github.com/Ensembl/ensembl-vep.git

or similar? Or did you download the zip file?

In either case you can force the installer to skip tests with --NO_TEST

**Comment by willmclaren** [comment]
OK thanks, version.t will fail to run in this case - I've added a fix for this so it doesn't catch others out in future.

**Comment by stefandiederich** [comment]
Okay but I will not need this Part of the pakage…

________________________________________
Stefan Diederich
M. Sc. Bioinformatik

Universitätsmedizin
der Johannes Gutenberg-Universität Mainz
Langenbeckstraße 1, 55131 Mainz
Tel.: 06131 17-5797

Von: William McLaren [mailto:notifications@github.com]
Gesendet: Freitag, 17. Februar 2017 10:46
An: Ensembl/ensembl-vep
Cc: Diederich, Stefan; Author
Betreff: Re: [Ensembl/ensembl-vep] Install VEP behind proxy (#22)


OK thanks, version.t will fail to run in this case - I've added a fix for this so it doesn't catch others out in future.
