### ISSUE TITLE
Synonyms only present in 2nd column of chr_synonyms.txt not recognized

### ISSUE THREAD

**Issue by ameynert** [Ensembl/ensembl-vep#224]
Release 90 VEP

77 contigs (below) are not being recognized by VEP, although they are in the chr_synonyms.txt file which is specified as a parameter. All of these contig names are present only in the 2nd column of the text file.

```
chr2_KI270715v1_random
chrUn_GL000226v1
chrUn_KI270302v1
chrUn_KI270303v1
chrUn_KI270304v1
chrUn_KI270305v1
chrUn_KI270310v1
chrUn_KI270311v1
chrUn_KI270312v1
chrUn_KI270315v1
chrUn_KI270316v1
chrUn_KI270317v1
chrUn_KI270320v1
chrUn_KI270322v1
chrUn_KI270329v1
chrUn_KI270362v1
chrUn_KI270363v1
chrUn_KI270364v1
chrUn_KI270366v1
chrUn_KI270371v1
chrUn_KI270372v1
chrUn_KI270375v1
chrUn_KI270378v1
chrUn_KI270381v1
chrUn_KI270382v1
chrUn_KI270383v1
chrUn_KI270384v1
chrUn_KI270385v1
chrUn_KI270386v1
chrUn_KI270387v1
chrUn_KI270388v1
chrUn_KI270389v1
chrUn_KI270390v1
chrUn_KI270391v1
chrUn_KI270392v1
chrUn_KI270393v1
chrUn_KI270394v1
chrUn_KI270395v1
chrUn_KI270396v1
chrUn_KI270411v1
chrUn_KI270412v1
chrUn_KI270414v1
chrUn_KI270417v1
chrUn_KI270418v1
chrUn_KI270419v1
chrUn_KI270420v1
chrUn_KI270422v1
chrUn_KI270423v1
chrUn_KI270424v1
chrUn_KI270425v1
chrUn_KI270429v1
chrUn_KI270465v1
chrUn_KI270468v1
chrUn_KI270507v1
chrUn_KI270509v1
chrUn_KI270510v1
chrUn_KI270511v1
chrUn_KI270512v1
chrUn_KI270515v1
chrUn_KI270516v1
chrUn_KI270517v1
chrUn_KI270518v1
chrUn_KI270522v1
chrUn_KI270529v1
chrUn_KI270530v1
chrUn_KI270538v1
chrUn_KI270539v1
chrUn_KI270544v1
chrUn_KI270582v1
chrUn_KI270583v1
chrUn_KI270584v1
chrUn_KI270587v1
chrUn_KI270588v1
chrUn_KI270589v1
chrUn_KI270590v1
chrUn_KI270591v1
chrUn_KI270593v1
```

**Comment by ima23** [comment]
Hi @ameynert, I am looking into this. The contig synonyms are present in the database so it should work. Could you please provide the full vep command you used and any further details that might help in tracing this? Thanks.

**Comment by ameynert** [comment]
vep --input_file $FAMILY.filtered.vcf.gz --output_file $FAMILY.annotated.vcf.gz --force_overwrite --compress_output bgzip --vcf \

--fork $NSLOTS --offline --no_stats --cache --dir_cache $VEP_CACHE_DIR --synonyms $VEP_SYNONYMS_FILE \

--fasta $REFERENCE_GENOME \

--allele_number \

--sift b \

--polyphen b \

--symbol \

--domains \

--regulatory \

--biotype \

--gene_phenotype \

--af --af_1kg --af_esp --af_gnomad --max_af \

--pubmed \

--variant_class \

--custom $GNOMAD_FILE,gnomADg,vcf,exact,0,AF_AFR,AF_AMR,AF_ASJ,AF_EAS,AF_FIN,AF_NFE,AF_OTH


I've just tested it with an altered synonyms file to include those 77 contigs in the first column and they still aren't being recognized.


Cheers,

Alison


--

Alison Meynert, IGMM Bioinformatics Analysis Core Manager



MRC Human Genetics Unit

MRC Institute of Genetics and Molecular Medicine

The University of Edinburgh

Western General Hospital

Crewe Road, Edinburgh EH4 2XU



E: alison.meynert@igmm.ed.ac.uk

T: +44 (0)131 651 8710

W: www.ed.ac.uk/mrc-human-genetics-unit

________________________________

**Comment by ens-lgil** [comment]
Dear @ameynert ,

Thank you for sending us the command line.
Just a further question: the 77 contigs are present in the input file, "custom" file or both ?

As a side note, you don't need to use the commands `--synonyms` not `--fasta` if you installed the cache throught the VEP install script and wants to use these default synonym and fasta data (VEP picks them by default from the cache directory).

About the `chr_synonyms.txt`, it is expected that these "synonym" contig names are only present in the 2nd column.

Best regards,
Laurent

**Comment by ameynert** [comment]
Hi Laurent,


Thanks, it's a custom install of VEP.


The contigs are in the original chr_synonyms.txt file downloaded with the cache and in my input VCF. In the custom file I tried swapping the columns for the pairs in which those 77 contigs appeared, but as I mentioned that did not work, so I'm really not sure what the problem is.


My output gives me warnings like this:


WARNING: Chromosome chr2_KI270715v1_random not found in annotation sources or synonyms on line 4974248

WARNING: Chromosome chrUn_KI270302v1 not found in annotation sources or synonyms on line 5009384

WARNING: Chromosome chrUn_KI270304v1 not found in annotation sources or synonyms on line 5009387

WARNING: Chromosome chrUn_KI270303v1 not found in annotation sources or synonyms on line 5009394

WARNING: Chromosome chrUn_KI270305v1 not found in annotation sources or synonyms on line 5009408



Cheers,

Alison


--

Alison Meynert, IGMM Bioinformatics Analysis Core Manager



MRC Human Genetics Unit

MRC Institute of Genetics and Molecular Medicine

The University of Edinburgh

Western General Hospital

Crewe Road, Edinburgh EH4 2XU



E: alison.meynert@igmm.ed.ac.uk

T: +44 (0)131 651 8710

W: www.ed.ac.uk/mrc-human-genetics-unit

________________________________

**Comment by ens-lgil** [comment]
Dear @ameynert,

Unfortunately VEP can't report variant consequences on a contig in the `--offline` mode as the cache doesn't contain all the required information for this.
Basically VEP will need to connect to the Ensembl databases to project the transcripts from the chromosomes to the contigs.
The script will work with the contig synonyms if you remove the `--offline` flag from your command line, however this solution is likely to slow down your script, because of the connections to the Ensembl databases.

Best regards,
Laurent

**Comment by ameynert** [comment]
Hi Laurent,


Thanks - will VEP only connect to the database when necessary and use the cache for everything else? The slowdown would be ok if it were only for the ~4K variants in these contigs.


Cheers,

Alison


--

Alison Meynert, IGMM Bioinformatics Analysis Core Manager



MRC Human Genetics Unit

MRC Institute of Genetics and Molecular Medicine

The University of Edinburgh

Western General Hospital

Crewe Road, Edinburgh EH4 2XU



E: alison.meynert@igmm.ed.ac.uk

T: +44 (0)131 651 8710

W: www.ed.ac.uk/mrc-human-genetics-unit

________________________________

**Comment by ens-lgil** [comment]
Hi Alison,

Yes, it will mainly use the data from the cache and only connect to the database when necessary.

Best regards,
Laurent

**Comment by ameynert** [comment]
Thanks, happy to close the issue now.


Cheers,

Alison


--

Alison Meynert, IGMM Bioinformatics Analysis Core Manager



MRC Human Genetics Unit

MRC Institute of Genetics and Molecular Medicine

The University of Edinburgh

Western General Hospital

Crewe Road, Edinburgh EH4 2XU



E: alison.meynert@igmm.ed.ac.uk

T: +44 (0)131 651 8710

W: www.ed.ac.uk/mrc-human-genetics-unit

________________________________
