### ISSUE TITLE
--symbol: no hgnc_id results

### ISSUE THREAD

**Issue by thedam** [Ensembl/ensembl-vep#226]
Hi,
I run VEP92 using command:
`vep -i test.vcf --cache --refseq -o test.tsv  --port 3337 --tab --exclude_predicted --ASSEMBLY GRCh37 --shift_hgvs 0 --sift b --polyphen b --humdiv --ccds --uniprot --symbol --numbers --domains --regulatory --canonical --protein --biotype --gene_phenotype --af --af_1kg --af_esp --af_gnomad --max_af --pubmed --variant_class -custom /home/vep/DATA/gnomAD/gnomad.exomes.r2.0.1.sites.noVEP.vcf.gz,gnomADe,vcf,exact,0,AF_NFE,POPMAX,AF -custom /home/vep/DATA/gnomAD/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF_NFE,POPMAX,AF --fork 50 --use_given_ref --use_transcript_ref`

However I never get any "hgnc_id". It's always "-".
SYMBOL HGNC_ID:
SYTL3 -
TAF2 -
TAF6 -
TBL1XR1 -
TCF4 -
TECR -
TGFBR1 -
TGFBR2 -
TMEM80 -
TMLHE -
TMLHE-AS1 -

Is there some error?

**Comment by ens-lgil** [comment]
Dear @thedam,

Actually for the RefSeq data we get the gene symbols from EntrezGene (which use the HGNC symbol as gene symbol when possible).
You should see it in your results, e.g.:
`SYMBOL   SYMBOL_SOURCE  HGNC_ID
SYTL3    EntrezGene    -
TAF2      EntrezGene    -
...
`
Unfortunately, we don't store the corresponding HGNC IDs for those genes in the RefSeq geneset at the moment.

Best regards,
Laurent
