### ISSUE TITLE
Error when using the --pick_allele flag

### ISSUE THREAD

**Issue by JakeHagen** [Ensembl/ensembl-vep#227]
Hello

When ever I use the --pick_allele flag I get the error below 
```
 Can't locate object method "variation_feature_seq" via package "Bio::EnsEMBL::Variation::TranscriptStructuralVariationAllele" at /home/omni/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/OutputFactory.pm line 545, <__ANONIO__> line 165.
```

I am using vep through a slightly modified docker image (just add a different user), but all of the internals should be the same. I am very unfamiliar with perl, so sorry if this is a easy fix. 

Thank you

**Comment by ens-lgil** [comment]
Dear @JakeHagen,

Please, could you send the command line you used (i.e. which species/assembly, using the database or cache) and some examples of the input file as well, in order to try to find the source of the problem.

Best regards,
Laurent

**Comment by willmclaren** [comment]
SVs are being fed into the same filtering method as sequence variants:

https://github.com/Ensembl/ensembl-vep/blob/release/92/modules/Bio/EnsEMBL/VEP/OutputFactory.pm#L512

This then trips up if e.g. `--pick_allele` is used:

https://github.com/Ensembl/ensembl-vep/blob/release/92/modules/Bio/EnsEMBL/VEP/OutputFactory.pm#L545

This either needs an extra if clause to work around it, or perhaps a separate `filter_VariationFeatureOverlapAlleles` for SVs that does not use the allele code.

**Comment by JakeHagen** [comment]
My vcf does include SVs so its looks like you found the issue, do you still need my command and files? 
Thank you for looking into it.

**Comment by ens-lgil** [comment]
Dear @JakeHagen,

Because Will spotted the source of the problem and thanks to your reply we can now try to fix this issue with SVs.

Best regards,
Laurent

**Comment by ens-lgil** [comment]
Dear @JakeHagen,

We just added a fix on this particular issue: [release/92.5](https://github.com/Ensembl/ensembl-vep/releases/tag/release%2F92.5).
You will need update your `ensembl-vep` installation to get it.

Best regards,
Laurent

**Comment by JakeHagen** [comment]
Thank you very much

**Comment by davemcg** [comment]
Hah, just ran into this exact issue. SV VCF with VEP 92. Just swapped over my version to 94 and it works again. Thanks!
