### ISSUE TITLE
Failed to compile plugin G2P: Can't locate CGI.pm in @INC

### ISSUE THREAD

**Issue by thedam** [Ensembl/ensembl-vep#228]
Hi,
I've experienced this error:

```
vep (...) --plugin G2P,/home/vep/DATA/G2P/DDG2P.csv.gz
WARNING: Failed to compile plugin G2P: Can't locate CGI.pm in @INC (you may need to install the CGI module) (@INC contains: /home/vep/.vep/Plugins /home/vep/src/ensembl-vep/modules /home/vep/src/ensembl-vep /home/vep/src/bioperl-live-release-1-6-924 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /home/vep/.vep/Plugins/G2P.pm line 104.
BEGIN failed--compilation aborted at /home/vep/.vep/Plugins/G2P.pm line 104.
Compilation failed in require at (eval 56) line 2.
BEGIN failed--compilation aborted at (eval 56) line 2.
```

I use VEP92, docker. Shouldn't CGI.pm be included in docker image?

Cheers
Damian

**Comment by at7** [comment]
Hi Damian,
I removed the CGI dependency from the G2P plugin and committed the change to the release/92 branch. Could you please pull the change from the VEP_plugins directory? Let me know if you continue seeing problems or if you have problems pulling the changes.

Thank you,
Anja

**Comment by thedam** [comment]
Hi,
and what command it should be?
I've just made:
`docker pull ensemblorg/ensembl-vep`
and it still doesn't work. Should I modify somehow the above command?
I'm not that expert in git/docker (yet) :)

**Comment by ens-lgil** [comment]
Dear @thedam,

This might be because you still have the "old" G2P plugin on your machine.

By default the VEP plugins are stored into the directory `~/.vep/Plugins/`.
If you mounted the volume like in the [VEP doc]( https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker), this means that the physical directory `~/.vep/Plugins/` is here on your machine: `$HOME/vep_data/Plugins`.

If this is the case, you need to remove the "old" `G2P.pm` plugin file in order to install the updated G2P plugin next time you will run `vep (...) --plugin G2P,/home/vep/DATA/G2P/DDG2P.csv.gz` on Docker.
For example, `rm -f $HOME/vep_data/Plugins/G2P.pm`

I hope this makes sense.

Best regards,
Laurent

**Comment by thedam** [comment]
Your right. I've updated this plugin. 
I was able to run it, however I have doubts whether it works correctly. Only with this plugin I get output like: 
```
vep (...) --plugin G2P,file=/home/vep/DATA/G2P/DDG2P.csv.gz

-------------------- WARNING ----------------------
MSG: You are using the API without caching most recent features. Performance might be affected.
FILE: EnsEMBL/DBSQL/BaseFeatureAdaptor.pm LINE: 86
CALLED BY: Bio/EnsEMBL/Registry.pm  LINE: 1189
Date (localtime)    = Tue Jul  3 16:45:14 2018
Ensembl API version = 92
---------------------------------------------------
2018-07-03 16:45:15 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this
WARNING: 4749 : Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/G2P.pm line 791.
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/G2P.pm line 791.
WARNING: 5902 : Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/G2P.pm line 791, <__ANONIO__> line 775.
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/G2P.pm line 791, <__ANONIO__> line 775.
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/G2P.pm line 791, <__ANONIO__> line 775.
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/G2P.pm line 791, <__ANONIO__> line 775.
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/G2P.pm line 791, <__ANONIO__> line 775.

```

**Comment by at7** [comment]
Hi Damian,
could you please share your full VEP command. Are you getting any results back at all? The G2P plugin creates a folder called something like: g2p_log_dir_year_month_day_time in the same directory from which you are running VEP. The file in that directory contains some intermediate results. Could you grep for G2P_flag and see if that returns anything?

**Comment by thedam** [comment]
Hi,
yes, there are some results but the point is I'm not sure they are correct (full,shifted, skipped etc), as I get these warnings.

```
 grep -v "#" test.vcf | wc -l
1452
```

firstly I do:
`docker run -t -i -v /my/vepCache:/opt/vep/.vep -v /my/DATA:/home/vep/DATA  ensemblorg/ensembl-vep /bin/bash`

then inside Docker:
```
vep@07a149612a30:/home/vep/runVEP$ vep -i test.vcf --cache --refseq -o test.tsv  --port 3337 --tab --exclude_predicted --ASSEMBLY GRCh37 --plugin G2P,file=/home/vep/DATA/G2P/DDG2P.csv.gz


-------------------- WARNING ----------------------
MSG: You are using the API without caching most recent features. Performance might be affected.
FILE: EnsEMBL/DBSQL/BaseFeatureAdaptor.pm LINE: 86
CALLED BY: Bio/EnsEMBL/Registry.pm  LINE: 1189
Date (localtime)    = Wed Jul  4 10:13:31 2018
Ensembl API version = 92



-------------------- WARNING ----------------------
MSG: You are using the API without caching most recent features. Performance might be affected.
FILE: EnsEMBL/DBSQL/BaseFeatureAdaptor.pm LINE: 86
CALLED BY: Bio/EnsEMBL/Registry.pm  LINE: 1189
Date (localtime)    = Wed Jul  4 10:13:31 2018
Ensembl API version = 92
---------------------------------------------------
2018-07-04 10:13:31 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this
2018-07-04 10:13:31 - INFO: Database will be accessed when using --use_transcript_ref
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/G2P.pm line 791, <__ANONIO__> line 111.
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/G2P.pm line 791, <__ANONIO__> line 1303.
(...)
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/G2P.pm line 791, <__ANONIO__> line 1303.
Can't call method "is_canonical" on an undefined value at /opt/vep/.vep/Plugins/G2P.pm line 1078.
```

results:
```
vep@07a149612a30:/home/vep/runVEP$ ls g2p_log_dir_2018_7_4_10_13
6238.txt
vep@07a149612a30:/home/vep/runVEP$ grep G2P_flag g2p_log_dir_2018_7_4_10_13/6238.txt | wc -l
24

```

```
grep -v "##" test.tsv | awk '{print $47,$48,$49}' | sort | uniq
- - -
1 HET 
1 HET MONO
G2P_complete G2P_flag G2P_gene_req
- HET -

```

So there is something in the results, but there are too many warnings that I'm not sure I should be worried about;)

**Comment by at7** [comment]
That is very helpful. I have to admit that the G2P plugin was tested with Ensembl transcript data. There are a few minor issues that occur when running with RefSeq data. I will fix those and let you know when the updated code is available. Would it be OK to run the same steps you have done previously to incorporate the changes once they are available?

**Comment by thedam** [comment]
yes, sure. Good luck!

**Comment by at7** [comment]
I updated the plugin. Can you please run the steps for updating again? Please let me know how it goes. Thank you!

**Comment by thedam** [comment]
ok, I've updated G2P.pm file, and re-run above commands. Now I've got only this message:

```
-------------------- WARNING ----------------------
MSG: You are using the API without caching most recent features. Performance might be affected.
FILE: EnsEMBL/DBSQL/BaseFeatureAdaptor.pm LINE: 86
CALLED BY: Bio/EnsEMBL/Registry.pm  LINE: 1189
Date (localtime)    = Wed Jul  4 14:18:49 2018
Ensembl API version = 92
---------------------------------------------------
```
the output:
```
vep@6b3fab194baf:/home/vep/runVEP$ ls g2p_log_dir_2018_7_4_14_18
19.txt
vep@6b3fab194baf:/home/vep/runVEP$ grep G2P_flag g2p_log_dir_2018_7_4_14_18/19.txt  | wc -l
24

vep@6b3fab194baf:/home/vep/runVEP$ grep -v "#" test.tsv | awk '{print $47,$48,$49}' | sort | uniq
- - -
1 HET 
1 HET MONO
- HET -


```
looks like the output is the same like previously, but no warnings this time. Hopefully it will work on bigger dataset too

Thanks!

**Comment by thedam** [comment]
ah, there are also also output files:
Log directory
```
/home/vep/runVEP/g2p_log_dir_2018_7_4_14_18
HTML report
/home/vep/runVEP/html_report_2018_7_4_14_18.html
TXT report
/home/vep/runVEP/txt_report_2018_7_4_14_18.txt
```

nice

**Comment by at7** [comment]
Great. Don't worry about the caching warning. We are working on getting rid of it. Please find more information about how the plugin works here: https://www.ebi.ac.uk/gene2phenotype/g2p_vep_plugin. Please open a new ticket if you have further questions or send an email to g2p-help@ebi.ac.uk. I close the ticket for now.
