### ISSUE TITLE
protein position and HGVSp position are different for frameshift ins/del

### ISSUE THREAD

**Issue by jjgao** [Ensembl/ensembl-vep#237]
It looks like the protein position is (HGVSp position - 1). Is there a reason for that?

https://grch37.rest.ensembl.org/vep/human/hgvs/6:g.26020799Adel?content-type=application/json&hgvs=1

![image](https://user-images.githubusercontent.com/840895/42535623-dd8933ee-845d-11e8-8bb4-004de6952a9b.png)

This happens to frameshift insertions too.

Thanks!

**Comment by ima23** [comment]
Hi @jjgao,

Thanks for this report, it is an issue we are aware of. Not all RefSeq transcripts completely match the reference genome. In cases where they don't, we are now using alignment files provided by NCBI to create a new reference, matching the transcript, and use this for consequence calling.

Our HGVS calculation does not currently use this reference modification, but it is something we are working on and aim to release later this year. VEP can report reference miss-matches for GRCh38, but these data are not available for GRCh37.

More details on the differences to the reference genome and correcting transcript models using BAM can be found here:  https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#refseq

Hope this explanation helps.
Irina

**Comment by ima23** [comment]
Hi @jjgao,

More specific to your example, for the reported 'protein_start' and 'protein_end' fields, we take the input variant location but for HGVS, we consider the new translated sequence and then find the first changed peptide. Here, one in a row of ’A’s is deleted, so if you move along looking for a change, the Lys is maintained but the next peptide changed, so HGVS reports a different location to the input position. We are working on API updates that will remove this discrepancy and report all positions in the 3' most location to match HGVS.

Best wishes,
Irina

**Comment by jjgao** [comment]
@ima23 Irina, thank you so much for the clarification. I look forward to the fix. Please feel free to close this issue if it is being tracked somewhere else.
