### ISSUE TITLE
Experimental keys on scalar is now forbidden at convert_cache.pl line 142

### ISSUE THREAD

**Issue by IsmailM** [Ensembl/ensembl-vep#24]
I'm getting the following error when running:

```bash
$ perl ~/data/.progz/ensembl-vep/convert_cache.pl -species homo_sapiens -version all

Experimental keys on scalar is now forbidden at /home/ucbtmog/data/.progz/ensembl-vep/convert_cache.pl line 142.
```

I'm using Perl (v5.24.0)

**Comment by willmclaren** [comment]
Thanks, this is fixed by https://github.com/Ensembl/ensembl-vep/commit/a2a0a51f6fea690a675c50dfa8f49dee2df4ef6f

**Comment by IsmailM** [comment]
Hey,

Thanks for the fix. I notice that you pushed this to master and release/88...

I was actually using release/87 and so was wondering how stable release/88 is and whether you think it's worth using 88 instead of 87 ?

Thanks

**Comment by sarahhunt** [comment]
Hi @IsmailM  

Release/88 is stable and will become our default version next week - it will only change if there are urgent bug fixes. Database and cache support, however, will only be available when we make the release.

**Comment by IsmailM** [comment]
Hey @sarahhunt,

Thanks for the swift reply. Can I still use the release/88 with my older cache/databases?

Also, btw, `$dirname/vep.pl ` needs to be changed to `$dirname/vep ` on
https://github.com/Ensembl/ensembl-vep/blob/release/88/INSTALL.pl#L914

and it would be nice if the binaries could be moved a separate bin directory so that I can add it to my PATH

**Comment by sarahhunt** [comment]
Hi @IsmailM . 

The update is also in release/87, if you need to stick with that version. Generally, we don't guarentee different code versions are compatible with other database or cache versions.

Thanks for pointing out the aditional '.pl' - that is updated now.
