### ISSUE TITLE
uninitialized value while using dbNSFP

### ISSUE THREAD

**Issue by thedam** [Ensembl/ensembl-vep#241]
Hi, VEP92, when using dbNSFP3.5a plugin with all columns such messages appears:

```
2018-07-16 10:10:41 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/dbNSFP.pm line 227.
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/dbNSFP.pm line 227.
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/dbNSFP.pm line 227.
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/dbNSFP.pm line 227.
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/dbNSFP.pm line 227.
```
Probably it's not a big deal, but it's hard to localize corresponding, problematic columns, to really see if this warning affects the output.
I run such command:

`vep (...) --plugin dbNSFP,/home/vep/DATA/dbNSFPv35a/hg19_dbNSFP3.5a_all_noMT.gz,ref,alt,aaref,aaalt,genename,cds_strand,refcodon,codonpos,codon_degeneracy,Ancestral_allele,AltaiNeandertal,Denisova,Ensembl_geneid,Ensembl_transcriptid,Ensembl_proteinid,aapos,SIFT_score,SIFT_converted_rankscore,SIFT_pred,Uniprot_acc_Polyphen2,Uniprot_id_Polyphen2,Uniprot_aapos_Polyphen2,Polyphen2_HDIV_score,Polyphen2_HDIV_rankscore,Polyphen2_HDIV_pred,Polyphen2_HVAR_score,Polyphen2_HVAR_rankscore,Polyphen2_HVAR_pred,LRT_score,LRT_converted_rankscore,LRT_pred,LRT_Omega,MutationTaster_score,MutationTaster_converted_rankscore,MutationTaster_pred,MutationTaster_model,MutationTaster_AAE,MutationAssessor_UniprotID,MutationAssessor_variant,MutationAssessor_score,MutationAssessor_score_rankscore,MutationAssessor_pred,FATHMM_score,FATHMM_converted_rankscore,FATHMM_pred,PROVEAN_score,PROVEAN_converted_rankscore,PROVEAN_pred,Transcript_id_VEST3,Transcript_var_VEST3,VEST3_score,VEST3_rankscore,MetaSVM_score,MetaSVM_rankscore,MetaSVM_pred,MetaLR_score,MetaLR_rankscore,MetaLR_pred,Reliability_index,M-CAP_score,M-CAP_rankscore,M-CAP_pred,REVEL_score,REVEL_rankscore,MutPred_score,MutPred_rankscore,MutPred_protID,MutPred_AAchange,MutPred_Top5features,CADD_raw,CADD_raw_rankscore,CADD_phred,DANN_score,DANN_rankscore,fathmm-MKL_coding_score,fathmm-MKL_coding_rankscore,fathmm-MKL_coding_pred,fathmm-MKL_coding_group,Eigen_coding_or_noncoding,Eigen-raw,Eigen-phred,Eigen-PC-raw,Eigen-PC-phred,Eigen-PC-raw_rankscore,GenoCanyon_score,GenoCanyon_score_rankscore,integrated_fitCons_score,integrated_fitCons_score_rankscore,integrated_confidence_value,GM12878_fitCons_score,GM12878_fitCons_score_rankscore,GM12878_confidence_value,H1-hESC_fitCons_score,H1-hESC_fitCons_score_rankscore,H1-hESC_confidence_value,HUVEC_fitCons_score,HUVEC_fitCons_score_rankscore,HUVEC_confidence_value,GERP++_NR,GERP++_RS,GERP++_RS_rankscore,phyloP100way_vertebrate,phyloP100way_vertebrate_rankscore,phyloP20way_mammalian,phyloP20way_mammalian_rankscore,phastCons100way_vertebrate,phastCons100way_vertebrate_rankscore,phastCons20way_mammalian,phastCons20way_mammalian_rankscore,SiPhy_29way_pi,SiPhy_29way_logOdds,SiPhy_29way_logOdds_rankscore,TWINSUK_AC,TWINSUK_AF,ALSPAC_AC,ALSPAC_AF,clinvar_rs,clinvar_clnsig,clinvar_trait,clinvar_golden_stars,Interpro_domain,GTEx_V6p_gene,GTEx_V6p_tissue --no_stats --fork 50 `

Cheers
DL

**Comment by aparton** [comment]
Hi Damian,

Thanks for this report, I’ll look into it. Could you please send me the full input command and a copy of your input data so that I can try to reproduce the issue?

Thanks,
Andrew

**Comment by thedam** [comment]
here it is ;)
```
##fileformat=VCFv4.2
##FILTER=<ID=medgen,Description="DP>4">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##contig=<ID=1,length=249250621>
##contig=<ID=2,length=243199373>
##contig=<ID=3,length=198022430>
##contig=<ID=4,length=191154276>
##contig=<ID=5,length=180915260>
##contig=<ID=6,length=171115067>
##contig=<ID=7,length=159138663>
##contig=<ID=8,length=146364022>
##contig=<ID=9,length=141213431>
##contig=<ID=10,length=135534747>
##contig=<ID=11,length=135006516>
##contig=<ID=12,length=133851895>
##contig=<ID=13,length=115169878>
##contig=<ID=14,length=107349540>
##contig=<ID=15,length=102531392>
##contig=<ID=16,length=90354753>
##contig=<ID=17,length=81195210>
##contig=<ID=18,length=78077248>
##contig=<ID=19,length=59128983>
##contig=<ID=20,length=63025520>
##contig=<ID=21,length=48129895>
##contig=<ID=22,length=51304566>
##contig=<ID=X,length=155270560>
##contig=<ID=Y,length=59373566>
##contig=<ID=MT,length=16569>
##contig=<ID=GL000207.1,length=4262>
##contig=<ID=GL000226.1,length=15008>
##contig=<ID=GL000229.1,length=19913>
##contig=<ID=GL000231.1,length=27386>
##contig=<ID=GL000210.1,length=27682>
##contig=<ID=GL000239.1,length=33824>
##contig=<ID=GL000235.1,length=34474>
##contig=<ID=GL000201.1,length=36148>
##contig=<ID=GL000247.1,length=36422>
##contig=<ID=GL000245.1,length=36651>
##contig=<ID=GL000197.1,length=37175>
##contig=<ID=GL000203.1,length=37498>
##contig=<ID=GL000246.1,length=38154>
##contig=<ID=GL000249.1,length=38502>
##contig=<ID=GL000196.1,length=38914>
##contig=<ID=GL000248.1,length=39786>
##contig=<ID=GL000244.1,length=39929>
##contig=<ID=GL000238.1,length=39939>
##contig=<ID=GL000202.1,length=40103>
##contig=<ID=GL000234.1,length=40531>
##contig=<ID=GL000232.1,length=40652>
##contig=<ID=GL000206.1,length=41001>
##contig=<ID=GL000240.1,length=41933>
##contig=<ID=GL000236.1,length=41934>
##contig=<ID=GL000241.1,length=42152>
##contig=<ID=GL000243.1,length=43341>
##contig=<ID=GL000242.1,length=43523>
##contig=<ID=GL000230.1,length=43691>
##contig=<ID=GL000237.1,length=45867>
##contig=<ID=GL000233.1,length=45941>
##contig=<ID=GL000204.1,length=81310>
##contig=<ID=GL000198.1,length=90085>
##contig=<ID=GL000208.1,length=92689>
##contig=<ID=GL000191.1,length=106433>
##contig=<ID=GL000227.1,length=128374>
##contig=<ID=GL000228.1,length=129120>
##contig=<ID=GL000214.1,length=137718>
##contig=<ID=GL000221.1,length=155397>
##contig=<ID=GL000209.1,length=159169>
##contig=<ID=GL000218.1,length=161147>
##contig=<ID=GL000220.1,length=161802>
##contig=<ID=GL000213.1,length=164239>
##contig=<ID=GL000211.1,length=166566>
##contig=<ID=GL000199.1,length=169874>
##contig=<ID=GL000217.1,length=172149>
##contig=<ID=GL000216.1,length=172294>
##contig=<ID=GL000215.1,length=172545>
##contig=<ID=GL000205.1,length=174588>
##contig=<ID=GL000219.1,length=179198>
##contig=<ID=GL000224.1,length=179693>
##contig=<ID=GL000223.1,length=180455>
##contig=<ID=GL000195.1,length=182896>
##contig=<ID=GL000212.1,length=186858>
##contig=<ID=GL000222.1,length=186861>
##contig=<ID=GL000200.1,length=187035>
##contig=<ID=GL000193.1,length=189789>
##contig=<ID=GL000194.1,length=191469>
##contig=<ID=GL000225.1,length=211173>
##contig=<ID=GL000192.1,length=547496>
##contig=<ID=NC_007605,length=171823>
##contig=<ID=hs37d5,length=35477943>
##reference=file:///refs/hs37d5_noHap.fa
##source=HaplotypeCaller
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	XXXX
1	3334515	1_3334515_C_A	C	A	.	.	.	GT	0/1
1	3334515	1_3334515_C_G	C	G	.	.	.	GT	0/1
1	3334515	1_3334515_C_T	C	T	.	.	.	GT	0/1
1	3334520	1_3334520_C_T	C	T	.	.	.	GT	0/1
1	3334555	1_3334555_C_T	C	T	.	.	.	GT	0/1
1	3334555	1_3334555_C_A	C	A	.	.	.	GT	0/1
1	3334556	1_3334556_G_A	G	A	.	.	.	GT	0/1
1	3334570	1_3334570_C_G	C	G	.	.	.	GT	0/1
```
command:
`vep -i input.vcf --cache --refseq -o test._out_.tsv --port 3337 --tab --exclude_predicted --ASSEMBLY GRCh37 --shift_hgvs 1 --sift b --polyphen b --humdiv --ccds --uniprot --symbol --numbers --domains --regulatory --canonical --protein --biotype --gene_phenotype --af --af_1kg --af_esp --af_gnomad --max_af --pubmed --variant_class -custom /home/vep/DATA/gnomAD/gnomad.exomes.r2.0.1.sites.noVEP.vcf.gz,gnomADe,vcf,exact,0,AF_NFE,POPMAX,AF -custom /home/vep/DATA/gnomAD/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF_NFE,POPMAX,AF --use_transcript_ref --hgvs --hgvsg --no_escape --fasta /home/vep/refs/hs37d5.fa --plugin dbscSNV,/home/vep/DATA/dbscSNP/dbscSNV1.1_GRCh37.txt.gz --plugin SpliceRegion --plugin MaxEntScan,/home/vep/DATA/MaxEntScan --plugin GeneSplicer,/home/vep/DATA/GeneSplicer/sources/genesplicer,/home/vep/DATA/GeneSplicer/human --plugin ExACpLI,/home/vep/DATA/ExACpLI/ExACpLI_values.txt --plugin REVEL,/home/vep/DATA/revel/revel_all_chromosomes.csv --plugin LoFtool,/home/vep/DATA/LoFtool/LoFtool_scores.txt --plugin Phenotypes --plugin G2P,file=/home/vep/DATA/G2P/DDG2P.csv.gz --format "vcf" --plugin dbNSFP,/home/vep/DATA/dbNSFPv35a/hg19_dbNSFP3.5a_all_noMT.gz,ref,alt,aaref,aaalt,genename,cds_strand,refcodon,codonpos,codon_degeneracy,Ancestral_allele,AltaiNeandertal,Denisova,Ensembl_geneid,Ensembl_transcriptid,Ensembl_proteinid,aapos,SIFT_score,SIFT_converted_rankscore,SIFT_pred,Uniprot_acc_Polyphen2,Uniprot_id_Polyphen2,Uniprot_aapos_Polyphen2,Polyphen2_HDIV_score,Polyphen2_HDIV_rankscore,Polyphen2_HDIV_pred,Polyphen2_HVAR_score,Polyphen2_HVAR_rankscore,Polyphen2_HVAR_pred,LRT_score,LRT_converted_rankscore,LRT_pred,LRT_Omega,MutationTaster_score,MutationTaster_converted_rankscore,MutationTaster_pred,MutationTaster_model,MutationTaster_AAE,MutationAssessor_UniprotID,MutationAssessor_variant,MutationAssessor_score,MutationAssessor_score_rankscore,MutationAssessor_pred,FATHMM_score,FATHMM_converted_rankscore,FATHMM_pred,PROVEAN_score,PROVEAN_converted_rankscore,PROVEAN_pred,Transcript_id_VEST3,Transcript_var_VEST3,VEST3_score,VEST3_rankscore,MetaSVM_score,MetaSVM_rankscore,MetaSVM_pred,MetaLR_score,MetaLR_rankscore,MetaLR_pred,Reliability_index,M-CAP_score,M-CAP_rankscore,M-CAP_pred,REVEL_score,REVEL_rankscore,MutPred_score,MutPred_rankscore,MutPred_protID,MutPred_AAchange,MutPred_Top5features,CADD_raw,CADD_raw_rankscore,CADD_phred,DANN_score,DANN_rankscore,fathmm-MKL_coding_score,fathmm-MKL_coding_rankscore,fathmm-MKL_coding_pred,fathmm-MKL_coding_group,Eigen_coding_or_noncoding,Eigen-raw,Eigen-phred,Eigen-PC-raw,Eigen-PC-phred,Eigen-PC-raw_rankscore,GenoCanyon_score,GenoCanyon_score_rankscore,integrated_fitCons_score,integrated_fitCons_score_rankscore,integrated_confidence_value,GM12878_fitCons_score,GM12878_fitCons_score_rankscore,GM12878_confidence_value,H1-hESC_fitCons_score,H1-hESC_fitCons_score_rankscore,H1-hESC_confidence_value,HUVEC_fitCons_score,HUVEC_fitCons_score_rankscore,HUVEC_confidence_value,GERP++_NR,GERP++_RS,GERP++_RS_rankscore,phyloP100way_vertebrate,phyloP100way_vertebrate_rankscore,phyloP20way_mammalian,phyloP20way_mammalian_rankscore,phastCons100way_vertebrate,phastCons100way_vertebrate_rankscore,phastCons20way_mammalian,phastCons20way_mammalian_rankscore,SiPhy_29way_pi,SiPhy_29way_logOdds,SiPhy_29way_logOdds_rankscore,TWINSUK_AC,TWINSUK_AF,ALSPAC_AC,ALSPAC_AF,clinvar_rs,clinvar_clnsig,clinvar_trait,clinvar_golden_stars,Interpro_domain,GTEx_V6p_gene,GTEx_V6p_tissue --no_stats --fork 50`

Cheers

**Comment by aparton** [comment]
Hi Damian,

Thank you for this. The plugin was having issues in finding the correct header description to use and returning those error messages when particular columns were asked for. I’m currently in the process of writing a fix, and I’ll update this issue when finished.

Fortunately, this error message is purely cosmetic and won’t change any of the output data you’re getting, so you can carry on as normal.

If there’s anything else we can do to help, please don’t hesitate to ask.

Kind Regards,
Andrew

**Comment by thedam** [comment]
Hi, still it doesn't work. Additionally again there's G2P error.

```
vep@1b790553cae7:/home/vep/runVEP$ vep -i xaf.vcf --cache --refseq -o xaf._out_.tsv --port 3337 --tab --exclude_predicted --ASSEMBLY GRCh37 --shift_hgvs 1 --sift b --polyphen b --humdiv --ccds --uniprot --symbol --numbers --domains --regulatory --canonical --protein --biotype --gene_phenotype --af --af_1kg --af_esp --af_gnomad --max_af --pubmed --variant_class -custom /home/vep/DATA/gnomAD/gnomad.exomes.r2.0.1.sites.noVEP.vcf.gz,gnomADe,vcf,exact,0,AF_NFE,POPMAX,AF -custom /home/vep/DATA/gnomAD/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF_NFE,POPMAX,AF --use_transcript_ref --hgvs --hgvsg --no_escape --fasta /home/vep/refs/hs37d5.fa --plugin dbscSNV,/home/vep/DATA/dbscSNP/dbscSNV1.1_GRCh37.txt.gz --plugin SpliceRegion --plugin MaxEntScan,/home/vep/DATA/MaxEntScan --plugin GeneSplicer,/home/vep/DATA/GeneSplicer/sources/genesplicer,/home/vep/DATA/GeneSplicer/human --plugin ExACpLI,/home/vep/DATA/ExACpLI/ExACpLI_values.txt --plugin REVEL,/home/vep/DATA/revel/revel_all_chromosomes.csv --plugin LoFtool,/home/vep/DATA/LoFtool/LoFtool_scores.txt --plugin Phenotypes --plugin G2P,file=/home/vep/DATA/G2P/DDG2P.csv.gz --format "vcf" --plugin dbNSFP,/home/vep/DATA/dbNSFPv35a/hg19_dbNSFP3.5a_all_noMT.gz,ref,alt,aaref,aaalt,genename,cds_strand,refcodon,codonpos,codon_degeneracy,Ancestral_allele,AltaiNeandertal,Denisova,Ensembl_geneid,Ensembl_transcriptid,Ensembl_proteinid,aapos,SIFT_score,SIFT_converted_rankscore,SIFT_pred,Uniprot_acc_Polyphen2,Uniprot_id_Polyphen2,Uniprot_aapos_Polyphen2,Polyphen2_HDIV_score,Polyphen2_HDIV_rankscore,Polyphen2_HDIV_pred,Polyphen2_HVAR_score,Polyphen2_HVAR_rankscore,Polyphen2_HVAR_pred,LRT_score,LRT_converted_rankscore,LRT_pred,LRT_Omega,MutationTaster_score,MutationTaster_converted_rankscore,MutationTaster_pred,MutationTaster_model,MutationTaster_AAE,MutationAssessor_UniprotID,MutationAssessor_variant,MutationAssessor_score,MutationAssessor_score_rankscore,MutationAssessor_pred,FATHMM_score,FATHMM_converted_rankscore,FATHMM_pred,PROVEAN_score,PROVEAN_converted_rankscore,PROVEAN_pred,Transcript_id_VEST3,Transcript_var_VEST3,VEST3_score,VEST3_rankscore,MetaSVM_score,MetaSVM_rankscore,MetaSVM_pred,MetaLR_score,MetaLR_rankscore,MetaLR_pred,Reliability_index,M-CAP_score,M-CAP_rankscore,M-CAP_pred,REVEL_score,REVEL_rankscore,MutPred_score,MutPred_rankscore,MutPred_protID,MutPred_AAchange,MutPred_Top5features,CADD_raw,CADD_raw_rankscore,CADD_phred,DANN_score,DANN_rankscore,fathmm-MKL_coding_score,fathmm-MKL_coding_rankscore,fathmm-MKL_coding_pred,fathmm-MKL_coding_group,Eigen_coding_or_noncoding,Eigen-raw,Eigen-phred,Eigen-PC-raw,Eigen-PC-phred,Eigen-PC-raw_rankscore,GenoCanyon_score,GenoCanyon_score_rankscore,integrated_fitCons_score,integrated_fitCons_score_rankscore,integrated_confidence_value,GM12878_fitCons_score,GM12878_fitCons_score_rankscore,GM12878_confidence_value,H1-hESC_fitCons_score,H1-hESC_fitCons_score_rankscore,H1-hESC_confidence_value,HUVEC_fitCons_score,HUVEC_fitCons_score_rankscore,HUVEC_confidence_value,GERP++_NR,GERP++_RS,GERP++_RS_rankscore,phyloP100way_vertebrate,phyloP100way_vertebrate_rankscore,phyloP20way_mammalian,phyloP20way_mammalian_rankscore,phastCons100way_vertebrate,phastCons100way_vertebrate_rankscore,phastCons20way_mammalian,phastCons20way_mammalian_rankscore,SiPhy_29way_pi,SiPhy_29way_logOdds,SiPhy_29way_logOdds_rankscore,TWINSUK_AC,TWINSUK_AF,ALSPAC_AC,ALSPAC_AF,clinvar_rs,clinvar_clnsig,clinvar_trait,clinvar_golden_stars,Interpro_domain,GTEx_V6p_gene,GTEx_V6p_tissue --no_stats --fork 50 
### Phenotypes plugin: Generating GFF file /opt/vep/.vep/Plugins/Phenotypes.pm_homo_sapiens_93_GRCh37.bed.gz from database
### Phenotypes plugin: This will take some time but it will only run once per species, assembly and release

-------------------- WARNING ----------------------
MSG: You are using the API without caching most recent features. Performance might be affected.
FILE: EnsEMBL/DBSQL/BaseFeatureAdaptor.pm LINE: 86
CALLED BY: Bio/EnsEMBL/Registry.pm  LINE: 1189
Date (localtime)    = Wed Jul 18 13:15:06 2018
Ensembl API version = 93
---------------------------------------------------
### Phenotypes plugin: Querying database
### Phenotypes plugin: Writing to file
### Phenotypes plugin: Indexing file with tabix
### Phenotypes plugin: All done!
WARNING: Failed to compile plugin G2P: Can't locate Text/CSV.pm in @INC (you may need to install the Text::CSV module) (@INC contains: /opt/vep/.vep/Plugins /opt/vep/src/ensembl-vep/modules /opt/vep/src/ensembl-vep /opt/vep/src/bioperl-live-release-1-6-924 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /opt/vep/.vep/Plugins/G2P.pm line 103.
BEGIN failed--compilation aborted at /opt/vep/.vep/Plugins/G2P.pm line 103.
Compilation failed in require at (eval 61) line 2.
BEGIN failed--compilation aborted at (eval 61) line 2.

2018-07-18 13:21:55 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/dbNSFP.pm line 230.
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/dbNSFP.pm line 230.
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/dbNSFP.pm line 230.
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/dbNSFP.pm line 230.
Use of uninitialized value in concatenation (.) or string at /opt/vep/.vep/Plugins/dbNSFP.pm line 230.
```

Cheers

**Comment by aparton** [comment]
Hiya,

A fix has now gone in for this issue, if you update the dbNSFP.pm file now then it should resolve this issue.

Kind Regards,
Andrew
