### ISSUE TITLE
filter_vep does not work on listed fields if no annotation present

### ISSUE THREAD

**Issue by vladmihaisima** [Ensembl/ensembl-vep#244]
Steps to reproduce:

1) run
`./filter_vep --filter "CHROM match 21" -i t/testdata/input/test.vcf -o output.vcf `

Expected output: file output.vcf has the same variants as t/testdata/input/test.vcf.

Version tested: latest master.

Discussion: I see two approaches/possibilities:

1) filter_vep should run exclusively on annotated files. In this case, the expected output would be an error/warning.

2) filter_vep can run on any file an filter on the fields it lists. As an argument to this is that it actually lists CHROM with the command `./filter_vep -i t/testdata/input/test.vcf --list`

I can also make a pull request with either solution, but I want to know which of the approaches is preferred by the developers.

**Comment by ens-lgil** [comment]
Dear @vladmihaisima,

Thank you for reporting this issue: the code is supposed to run filter on any VCF fields/columns.
We just added a fix on the branch `release/93` so now it should work on any VCF fields/columns, even if there is no VEP annotation.

Best regards,
Laurent
