### ISSUE TITLE
Output files from docker

### ISSUE THREAD

**Issue by thedam** [Ensembl/ensembl-vep#247]
Hi, 
When I run a VEP93 command from within the container I get several output files.
For example:
I run and enter the container:
`docker run -t -i -v /path1/vepCache:/opt/vep/.vep -v /path2/DATA:/home/vep/DATA -v /path3/runVEP:/home/vep/runVEP -v /path4/refs/:/home/vep/refs ensemblorg/ensembl-vep /bin/bash`

then inside the container I run:
`vep -i /home/vep/runVEP/test/todo_0.vcf --cache --refseq -o /home/vep/runVEP/test/todo_0_out_.tsv --port 3337 --tab --exclude_predicted --ASSEMBLY GRCh37 -custom /home/vep/DATA/gnomAD/gnomad.exomes.r2.0.1.sites.noVEP.vcf.gz,gnomADe,vcf,exact,0,AF_NFE,POPMAX,AF -custom /home/vep/DATA/gnomAD/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF_NFE,POPMAX,AF --use_transcript_ref --hgvs --hgvsg --no_escape --fasta /home/vep/refs/hs37d5.fa  --plugin G2P,file=/home/vep/DATA/G2P/DDG2P.csv --no_stats --fork 50 `

and I get files:
**g2p_log_dir_2018_7_26_15_4  
html_report_2018_7_26_15_4.html  
todo_0_out_.tsv
txt_report_2018_7_26_15_4.txt**

But when I run the command directly from terminal, like this:
`docker run -t -i -v /path1/vepCache:/opt/vep/.vep -v /path2/DATA:/home/vep/DATA -v /path3/runVEP:/home/vep/runVEP -v /path4/refs/:/home/vep/refs ensemblorg/ensembl-vep vep -i /home/vep/runVEP/test/todo_0.vcf --cache --refseq -o /home/vep/runVEP/test/todo_0_out_.tsv --port 3337 --tab --exclude_predicted --ASSEMBLY GRCh37 -custom /home/vep/DATA/gnomAD/gnomad.exomes.r2.0.1.sites.noVEP.vcf.gz,gnomADe,vcf,exact,0,AF_NFE,POPMAX,AF -custom /home/vep/DATA/gnomAD/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF_NFE,POPMAX,AF --use_transcript_ref --hgvs --hgvsg --no_escape --fasta /home/vep/refs/hs37d5.fa  --plugin G2P,file=/home/vep/DATA/G2P/DDG2P.csv --no_stats --fork 50`

or firstly running the deamon:
```
docker run -t -d -i -v /path1/vepCache:/opt/vep/.vep -v /path/DATA:/home/vep/DATA -v /path/runVEP:/home/vep/runVEP -v /path/refs/:/home/vep/refs ensemblorg/ensembl-vep /bin/bash
a5c940170803ae03f8bab63ff57dfcde3d0e6fed2a06a0d8c071ab0cdf2b0c97
```
then again from termianl:
```docker exec -it a5c940170803 vep -i /home/vep/runVEP/test/todo_0.vcf --cache --refseq -o /home/vep/runVEP/test/todo_0_out_.tsv --port 3337 --tab --exclude_predicted --ASSEMBLY GRCh37 -custom /home/vep/DATA/gnomAD/gnomad.exomes.r2.0.1.sites.noVEP.vcf.gz,gnomADe,vcf,exact,0,AF_NFE,POPMAX,AF -custom /home/vep/DATA/gnomAD/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF_NFE,POPMAX,AF --use_transcript_ref --hgvs --hgvsg --no_escape --fasta /home/vep/refs/hs37d5.fa  --plugin G2P,file=/home/vep/DATA/G2P/DDG2P.csv --no_stats --fork 50```

I get only standard output file:
**todo_0_out_.tsv**

Shouldn't I get all files like in the first example?

**Comment by at7** [comment]
The quickest solution is too specify the location with G2P,file=/home/vep/DATA/G2P/DDG2P.csv,log_dir=location,txt_report=location,html_report=location. Fields are described in the [header](https://github.com/Ensembl/VEP_plugins/blob/release/93/G2P.pm).
I look into it to see what is going on when doing it the way you have described it.

**Comment by thedam** [comment]
Indeed, with all paths set, there was no error. I've run it on 3mln variants. 
ps.
mind it, that if you have your .vcf file under some paht, lets say `/path/runVep`
and if you set 
file=/DATA/G2P/DDG2P.csv,`log_dir=/path/runVep,txt_report=/path/runVep,html_report=/path/runVep` your vcf file is removed :)

thanks for this hint,
Cheers

**Comment by at7** [comment]
Thank you for letting me know. I'll fix that asap!

**Comment by at7** [comment]
Sorry for the delay in getting back to you. The problem you pointed out is now fixed on release/93 branch. Newer branches will be fixed too. Please reopen the issue or create a new one for any further questions.
