### ISSUE TITLE
G2P random crash

### ISSUE THREAD

**Issue by thedam** [Ensembl/ensembl-vep#248]
Hi,
when I run the command:
`vep -i /home/vep/runVEP/test/todo_0.vcf --cache --refseq -o /home/vep/runVEP/test/todo_0_out_.tsv --port 3337 --tab --exclude_predicted --ASSEMBLY GRCh37 -custom /home/vep/DATA/gnomAD/gnomad.exomes.r2.0.1.sites.noVEP.vcf.gz,gnomADe,vcf,exact,0,AF_NFE,POPMAX,AF -custom /home/vep/DATA/gnomAD/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF_NFE,POPMAX,AF --use_transcript_ref --hgvs --hgvsg --no_escape --fasta /home/vep/refs/hs37d5.fa  --plugin G2P,file=/home/vep/DATA/G2P/DDG2P.csv --no_stats --fork 50 `

most of the time it works ok, but sometimes I get error like this:

> Use of uninitialized value $log_dir in concatenation (.) or string at /opt/vep/.vep/Plugins/G2P.pm line 858, <GEN5> line 2.
> WARNING: Failed to instantiate plugin G2P: Could not open file 'G2P_list /27.txt' Permission denied at /opt/vep/.vep/Plugins/G2P.pm line 859, <GEN5> line 2.

Then, when I re-run exactly the same command, everything is fine. Sometimes it happens, sometimes not. When it happens, then the main output file has different number of lines... strange...

Cheers

**Comment by at7** [comment]
Also something I need to investigate. But I would say it will be save to run if you specify the location of the log_dir.

**Comment by thedam** [comment]
yes, that was correct, example command: 
--plugin G2P,file=/home/vep/DATA/G2P/DDG2P.csv,log_dir=/home/vep/runVEP/logs/aaa/someFolderName,txt_report=/home/vep/runVEP/logs/bbb/someName,html_report=/home/vep/runVEP/logs/ccc/someName

thanks && cheers
