### ISSUE TITLE
add option to show the percentage of annotated variant 

### ISSUE THREAD

**Issue by aurelBZH** [Ensembl/ensembl-vep#252]
Hi,
Thanks for the work on variant effect predictor. 
An option to allow the user to know the percentage of annotated variant will be very usefull. I'm working to wrap vep in my software and showing the annotation percentage to the end user would be a great feature.

Thanks a lot 
Aurélien Béliard 
Bioinformatician

**Comment by aparton** [comment]
Hi Aurélien,

Thank you for your query. We’re always interested in expanding VEP functionality, so I’d be happy to take a look, however I’m not entirely sure what value you suggest, could you please clarify? 

Additionally, our plugin infrastructure makes adding of additional data into VEP relatively easy, and can be used to help customise your analysis pipelines if it’s of any interest to you: https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html <https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html>

Kind Regards,
Andrew

**Comment by aurelBZH** [comment]
Maybe i'm not clear but i'm looking for an option to show to the user the percentage of annotated variant during the annotation. Maybe a thing like that : " file: file_name 53% annotated " written in the shell  during the annotation process.

**Comment by aparton** [comment]
Hi Aurélien,

Thank you for the suggestion. While this is something that we would like to do, we've had some discussions about it and there are some technical issues preventing us from doing this easily, so it's not something that we're looking at doing in the immediate future, although we may revisit this at some point further down the road.

Kind Regards,
Andrew


Kind Regards,
Andrew
