### ISSUE TITLE
Silent exit error: '--coding_only' causes error if no 'protein_coding' variants from a chromosome

### ISSUE THREAD

**Issue by ibwoo** [Ensembl/ensembl-vep#259]
Hi,

Using VEP 92.1, I have a .vcf file with a small number of mutations for each chromosome. I have been running with the following command:

`vep --offline --species homo_sapiens --assembly GRCh38 --dir_cache /databank/ensembl-vep/cache/ -i temp_files/test_vcf_chr8_error.vcf --force_overwrite --coding_only --symbol -o temp_files/test_vcf_chr8_error.txt`

- It completes without errors but the output file stops after the last variant of chr7. 

- The stats html file suggests that three mutations from chr8 were found (but not listed in output file). It also registers mutations from chr1-7, but not from chr9 onwards. 

- If I delete all three chr8 mutations from my vcf file, the VEP run completes and the output includes mutations from all other chromosomes chr9 onwards. 

- If I remove the --coding_only tag, the output completes successfully with all chromosomes (including chr8) - and it seems that there are no protein_coding consequences of the chr8 mutations.

At a guess: It seems that if a chromosome is encountered in the vcf file but no 'protein_coding' consequences are found from mutations on that chromosome, the program will exit silently. Before exiting it must count the number of mutations on the chromosome encountered, as this count was added to the stats file that is still generated on exit. 

I will attach the vcf file subsetted to contain all mutations from chr7,8,9 so that you can reproduce this behaviour.

[test_vcf_chr8_error.zip](https://github.com/Ensembl/ensembl-vep/files/2287747/test_vcf_chr8_error.zip)

Though there are many more mutations for chr9 than chr8, in the stats html file for this test vcf you will see this count, which demonstrates the weird behaviour:

<img width="811" alt="image" src="https://user-images.githubusercontent.com/34343649/44104965-28da0cba-9fe8-11e8-989f-85360a67835b.png">

In the meantime, I can use the --biotype field to add the data to filter for 'protein_coding' afterwards.

Thanks for your ongoing support of a very useful program.

All the best

**Comment by ibwoo** [comment]
Hi @aparton, do you have any update on this? Thanks!

**Comment by aparton** [comment]
Hi @ibwoo,

Good timing! This issue has been resolved with our new release (v97).

Kind Regards,
Andrew
