### ISSUE TITLE
Combining --merged and --custom results in duplicated SOURCE column in --tab output

### ISSUE THREAD

**Issue by hmartiniano** [Ensembl/ensembl-vep#26]
When using both flags (--merged and --custom) for regular or tabbed output the header displays duplicate lines:

`## SOURCE : Source of transcript`
`## SOURCE : Source of transcript`

For regular output, there's no duplicated SOURCE key in the Extra column.
But in when the --tab flag is given the output file contains duplicated SOURCE columns.

**Comment by willmclaren** [comment]
Thanks, fixed by https://github.com/Ensembl/ensembl-vep/commit/822e51395a28f392a9bf7b56448b565f40856294

Fix will appear in upcoming release/88, available now on master.
