### ISSUE TITLE
wrong HGVS description? 

### ISSUE THREAD

**Issue by thedam** [Ensembl/ensembl-vep#265]
Hi,
I map reads on GRCh37 reference.
Annotating VCF file with such mutation:
```
chr_start_ref_alt
8_48691028_C_T
```
Gives such fields from VEP93 database:
```
location: 8:48691028
allele: T
strand: -1
rs: rs770795091
HGVSc: NM_006904.6:c.11844G>A
HGVSg: 8:g.48691028C>T
given_ref: C
used_ref: C
bam_edit: OK (what it means actually? it's not clear for me even with description from VEP tutorial:) )
```
so everything looks ok. However this RS in dbSNP has different HGVSc.
dbSNP: NM_006904.6:c.1184**5**G>A
VEP93: NM_006904.6:c.1184**4**G>A
https://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?rs=770795091

here is my command:
```
docker run -t -i -v /mnt/ssd_01/VEP/vepCache:/opt/vep/.vep -v /mnt/ssd_01/DATA:/home/vep/DATA -v /mnt/ssd_01/VEP/runVEP:/home/vep/runVEP -v /mnt/ssd_01/refs/:/home/vep/refs ensemblorg/ensembl-vep vep -i /home/vep/runVEP/$i --cache --refseq -o /home/vep/runVEP/$i.tsv --port 3337 --tab --exclude_predicted --ASSEMBLY GRCh37 --shift_hgvs 1 --sift b --polyphen b --humdiv --ccds --uniprot --symbol --numbers --domains --regulatory --canonical --protein --biotype --gene_phenotype --af --af_1kg --af_esp --af_gnomad --max_af --pubmed --variant_class -custom /home/vep/DATA/gnomAD/gnomad.exomes.r2.0.1.sites.noVEP.vcf.gz,gnomADe,vcf,exact,0,AF_NFE,POPMAX,AF -custom /home/vep/DATA/gnomAD/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF_NFE,POPMAX,AF --use_transcript_ref --hgvs --hgvsg --no_escape --fasta /home/vep/refs/hs37d5.fa --plugin dbscSNV,/home/vep/DATA/dbscSNP/dbscSNV1.1_GRCh37.txt.gz --plugin SpliceRegion --plugin MaxEntScan,/home/vep/DATA/MaxEntScan --plugin GeneSplicer,/home/vep/DATA/GeneSplicer/sources/genesplicer,/home/vep/DATA/GeneSplicer/human --plugin ExACpLI,/home/vep/DATA/ExACpLI/ExACpLI_values.txt --plugin REVEL,/home/vep/DATA/revel/revel_all_chromosomes.csv --plugin LoFtool,/home/vep/DATA/LoFtool/LoFtool_scores.txt --plugin Phenotypes  --plugin G2P,file=/home/vep/DATA/G2P/DDG2P.csv,log_dir=/home/vep/runVEP/logs/aaa/$i,txt_report=/home/vep/runVEP/logs/bbb/$i,html_report=/home/vep/runVEP/logs/ccc/$i --format "vcf" --plugin dbNSFP,/home/vep/DATA/dbNSFPv35a/hg19_dbNSFP3.5a_all_noMT.gz,ref,alt,aaref,aaalt,genename,cds_strand,refcodon,codonpos,codon_degeneracy,Ancestral_allele,AltaiNeandertal,Denisova,Ensembl_geneid,Ensembl_transcriptid,Ensembl_proteinid,aapos,SIFT_score,SIFT_converted_rankscore,SIFT_pred,Uniprot_acc_Polyphen2,Uniprot_id_Polyphen2,Uniprot_aapos_Polyphen2,Polyphen2_HDIV_score,Polyphen2_HDIV_rankscore,Polyphen2_HDIV_pred,Polyphen2_HVAR_score,Polyphen2_HVAR_rankscore,Polyphen2_HVAR_pred,LRT_score,LRT_converted_rankscore,LRT_pred,LRT_Omega,MutationTaster_score,MutationTaster_converted_rankscore,MutationTaster_pred,MutationTaster_model,MutationTaster_AAE,MutationAssessor_UniprotID,MutationAssessor_variant,MutationAssessor_score,MutationAssessor_score_rankscore,MutationAssessor_pred,FATHMM_score,FATHMM_converted_rankscore,FATHMM_pred,PROVEAN_score,PROVEAN_converted_rankscore,PROVEAN_pred,Transcript_id_VEST3,Transcript_var_VEST3,VEST3_score,VEST3_rankscore,MetaSVM_score,MetaSVM_rankscore,MetaSVM_pred,MetaLR_score,MetaLR_rankscore,MetaLR_pred,Reliability_index,M-CAP_score,M-CAP_rankscore,M-CAP_pred,REVEL_score,REVEL_rankscore,MutPred_score,MutPred_rankscore,MutPred_protID,MutPred_AAchange,MutPred_Top5features,CADD_raw,CADD_raw_rankscore,CADD_phred,DANN_score,DANN_rankscore,fathmm-MKL_coding_score,fathmm-MKL_coding_rankscore,fathmm-MKL_coding_pred,fathmm-MKL_coding_group,Eigen_coding_or_noncoding,Eigen-raw,Eigen-phred,Eigen-PC-raw,Eigen-PC-phred,Eigen-PC-raw_rankscore,GenoCanyon_score,GenoCanyon_score_rankscore,integrated_fitCons_score,integrated_fitCons_score_rankscore,integrated_confidence_value,GM12878_fitCons_score,GM12878_fitCons_score_rankscore,GM12878_confidence_value,H1-hESC_fitCons_score,H1-hESC_fitCons_score_rankscore,H1-hESC_confidence_value,HUVEC_fitCons_score,HUVEC_fitCons_score_rankscore,HUVEC_confidence_value,GERP++_NR,GERP++_RS,GERP++_RS_rankscore,phyloP100way_vertebrate,phyloP100way_vertebrate_rankscore,phyloP20way_mammalian,phyloP20way_mammalian_rankscore,phastCons100way_vertebrate,phastCons100way_vertebrate_rankscore,phastCons20way_mammalian,phastCons20way_mammalian_rankscore,SiPhy_29way_pi,SiPhy_29way_logOdds,SiPhy_29way_logOdds_rankscore,TWINSUK_AC,TWINSUK_AF,ALSPAC_AC,ALSPAC_AF,clinvar_rs,clinvar_clnsig,clinvar_trait,clinvar_golden_stars,Interpro_domain,GTEx_V6p_gene,GTEx_V6p_tissue --no_stats --fork 50
```

I wrote also to NCBI thinking they might be wrong, but apparently their description is right.

so I don't understand why there's this difference...

Cheers!
Damian

**Comment by sarahhunt** [comment]
Hi Damian,

Thanks for this report, it is an issue we are aware of. As you probably know, not all RefSeq transcripts completely match the reference genome. In cases where they don't, we are now using alignment files provided by NCBI to create a new reference, matching the transcript, and use this for consequence calling.

Our HGVS calculation does not currently use this reference modification, but it is something we are working on and aim to release later this year. 

The bam_edit flag is set if the transcript appears not to match genome. If we can successfully derive a new sequence, this is set to 'OK', if we cannot it is set to 'failed'. There are a very small number of transcripts for which alignment fails and the annotation for these should be regarded with caution. If you see  'bam_edit: OK ' the HGVS may be incorrect, but the other annotation will be fine. Incorrect HGVS will have a different HGVS transcript position to CDS position even for substitutions.

Best wishes,
Sarah

**Comment by thedam** [comment]
Ok, thanks.
I've suspected that HGVS and bam_edit may be somehow connected.
So in summary, if I see "bam_edit: OK" it means:
-the HGVS may be incorrect
-the HGVS may be correct 

Thank you for this clarification.
Hopefully you'll solve this issue :)

Cheers
Damian

**Comment by jpuntomarcos** [comment]
Hi @sarahhunt ,

Is this issue currently solved? If I use VEP online (GRCH37) to query 11:64572018_T/C variant with refseq transcripts, I get:
![image](https://user-images.githubusercontent.com/1809574/135608725-ed4c2b72-4077-4b50-ac75-9a481e59075f.png)

Consequence and codons are correct: In this position, the NM transcript contains a G and the alternate allele provided is also a G (-strand), so predicted **G**CA/**G**CA codons are right. However, the HGVSc notation seems wrong: NM_000244.3:c.1636**A**>G which is actually the one we can obtain when annotating against Ensembl transcripts or using the --use_given_ref parameter to use the ref allele provided by the user.

[Temp link](http://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Results?tl=TKwytXO1Jup97U2Y-7684324) to the VEP job.

Hope you can help! thanks in advance :)
