### ISSUE TITLE
Small GRCh37 cache/fasta for testing INSTALL.pl --AUTO acf

### ISSUE THREAD

**Issue by ckandoth** [Ensembl/ensembl-vep#266]
Hello. In our [tests for vcf2maf](https://github.com/mskcc/vcf2maf/blob/master/.travis.yml) we try to install VEP with the entire 6.5GB GRCh37 cache and reference fasta. But this takes too long for integration testing with quick turnarounds, and the downloads from the FTP server can be instable. Is there a tiny subset of the GRCh37 cache+fasta we can use, so that something like `perl INSTALL.pl --AUTO acf --SPECIES homo_sapiens --ASSEMBLY GRCh37_test` will work very quickly. Then I can test VEP with a VCF with variants only within that subset of the genome. Thanks much!

**Comment by aparton** [comment]
Hiya,

Thank you for your query. Unfortunately, we do not have readily available subsets of our cache files available for download through our installer. 

It would be possible for you to make one - each of our cache files contain subdirectories for each chromosome. It would be possible to download the full cache, remove all subdirectories other than a chromosome of interest, and point VEP towards this cache when running with the —dir_cache command. However, if you require a downloadable cache for your testing, this would not be possible.

As a potential workaround, it would also be possible to auto-install a cache for a species with a smaller genome, such as mus_musculus. Although depending on what your requirements are, this may not be beneficial.

Sorry that I couldn’t give you a more helpful response.

Kind Regards,
Andrew
