### ISSUE TITLE
Casting problem for HGVS (protein) notation having special characters like "=" 

### ISSUE THREAD

**Issue by jaudoux** [Ensembl/ensembl-vep#27]
Hi VEP developers,

For some variants having a modification on the protein level, the HGVS notation does not come-out right. 

For example, in my VCF I have got :

```
11    69462910    .    G    A    313.7    PASS    AB=0;ABP=0;AC=2;AF=1;AN=2;AO=10;CIGAR=1X;DP=10;DPB=10;DPRA=0;EPP=3.87889;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=18.4681;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=375;QR=0;RO=0;RPL=8;RPP=10.8276;RPPR=0;RPR=2;RUN=1;SAF=4;SAP=3.87889;SAR=6;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.protocol=1;DBSNP=rs9344;CLINVAR=rs9344;COSMIC=COSM1179751;CSQ=A|splice_region_variant&synonymous_variant|LOW|CCND1|595|Transcript|NM_053056.2|protein_coding|4/5||NM_053056.2:c.723G>A|NP_444284.1:p.Pro241%3D|932|723|241|P|ccG/ccA
```

The ID `NP_444284.1:p.Pro241%3D` should instead be `NP_444284.1:p.Pro241=`. Is it done on purpose, or is it a casting bug? 

I think it is the same for other special characters like "\".

Thanks in advance.

Best,
Jérôme.

**Comment by willmclaren** [comment]
The "=" character is used elsewhere in VCF encoding (the INFO field consists of KEY=VALUE pairs), so we chose URI encoding for the "=" character as seen here.

You may switch this off with `--no_escape`, but this will cause errors in parsing the VCF in any other software.

**Comment by jaudoux** [comment]
Yes, I did not thought of that, this is quite a good reason. Thanks for the fast reply!
