### ISSUE TITLE
Docker failing

### ISSUE THREAD

**Issue by sigven** [Ensembl/ensembl-vep#275]
Hi,

The latest docker build appears to be failing:
https://hub.docker.com/r/ensemblorg/ensembl-vep/builds/bgvgnpvaj7mqkwth7st8got/

Do you have any idea why DBD::mysql does not configure properly?

best,
Sigve

**Comment by ens-lgil** [comment]
Dear Sigve,

We are aware of an issue with the latest `DBD::mysql` library: it has a new dependency to the `Devel::CheckLib` library but apparently the installer within `DBD::mysql` isn't properly configured to install this new dependency.
We are waiting for a fix on the `DBD::mysql` library.

Best regards,
Laurent

**Comment by sigven** [comment]
Great, thanks for the prompt response!

best,
Sigve

**Comment by ens-lgil** [comment]
FYI: https://github.com/perl5-dbi/DBD-mysql/issues/263

**Comment by mbeijen** [comment]
I've just released a non-broken version of DBD::mysql to CPAN. Sorry for the breakage!

**Comment by ens-lgil** [comment]
Dear @sigven,

We just rebuilt the VEP Docker image with the fixed `DBD::mysql` library (thanks to @mbeijen!).

Best regards,
Laurent

**Comment by ens-lgil** [comment]
Dear @mbeijen,

Many thanks for the fix on the `DBD::mysql` library!

Best regards,
Laurent
