### ISSUE TITLE
Cannot run VEP when specifying gtf

### ISSUE THREAD

**Issue by smithmf** [Ensembl/ensembl-vep#28]
I'm attempting to run VEP, revision `6b712700089dc71996cea9a7283877406482dd87`, by specifying my own GTF annotation with the command:

`perl vep.pl -i ../alignment/R636012.vcf -gtf pao1.gtf.gz -fasta ../references/pao1.fa`

However, I am getting the following error at the command line:

`Can't locate object method "new" via package "Bio::EnsEMBL::VEP::AnnotationSource::File::GTF" at /home/<username>/git-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 119.`

For some reason it doesn't seem to be calling the `new` method in the `BaseGXF` class when trying to instantiate a `GTF` object.

**Comment by willmclaren** [comment]
Strange.

I don't find that revision string to match any commit hash, can you be more specific? What is the version given when you run:

`perl vep.pl`

?

The code should catch this, but do you have Bio::DB::HTS installed? You can test with:

`perl -MBio::DB::HTS::Tabix -e'print "OK\n"'`

**Comment by smithmf** [comment]
Hi Will,

Thanks for the quick reply! Sorry, I should have just said that I cloned the repo yesterday, so should be on the latest pushed commit.

Versions for `perl vep.pl`:
>  ensembl              : 87.f547798
>  ensembl-funcgen      : 87.0577dd0
>  ensembl-io           : 87.48cb128
>  ensembl-variation    : 87.d12da68
>  ensembl-vep          : 87.27

After running `perl -MBio::DB::HTS::Tabix -e'print "OK\n"'`, I do indeed get `OK` echo'ed. 

Also, running on perl v 5.22.3

**Comment by smithmf** [comment]
I rechecked the dependencies and it looks like I was missing `DBD::mysql`. I was previously attempting to run this in `--offline` mode so I never installed that module. 

After installing, it runs now. Perl chose to die at an odd point and with an odd message, but I think I'm good now!

Thanks

**Comment by willmclaren** [comment]
Thanks. Worth knowing as DBD::mysql shouldn't be required given your command line, will have to hunt down where it is being included.
