### ISSUE TITLE
Installing cache fails for old version (homo_sapiens 75 GRCh37)

### ISSUE THREAD

**Issue by K377U** [Ensembl/ensembl-vep#29]
Im trying to install cache for homo_sapiens 75 GRCh37 but it fails.

```
perl INSTALL.pl --AUTO c --SPECIES homo_sapiens --DESTDIR ~/vep_test/ --VERSION 75 --CACHEDIR ~/vep_test/cache/ --ASSEMBLY GRCh37
Getting list of available cache files
ERROR: No matching species found at INSTALL.pl line 1045.
```
I think that this happens because in

```
ftp://ftp.ensembl.org/pub/release-75/variation/VEP/
```
the vep file is formatted

`homo_sapiens_vep_75.tar.gz`

and not

`homo_sapiens_vep_75_GRCh37.tar.gz`

**Comment by sarahhunt** [comment]
@K377U - you would have to use the release75 version of the install script to pick up caches from release75. After this we started supporting two human assembly versions so the name format changed. We don't guarentee caches or database are compatible with different API versions.

**Comment by K377U** [comment]
Last time I tried to install release 75 it failed. If I remember correctly some of the links to files were broken, I kind of hoped that this new VEP would have solved this problem. If that old version is broken, will it be fixed at some point?

In any case I can fork this code and make changes to support 75 version. :+1:

**Comment by sarahhunt** [comment]
Hi @K377U - sorry to hear you hit problems with the release 75 code. It works for me, so maybe there was a temporary problem with the ftp site? 
I assume you are using version 75 to replicate previous analysis? It's pretty old - from Feb 2014. Newer VEP versions are faster, have more features and still support GRCh37.
