### ISSUE TITLE
keep alt and ref allele with tab option 

### ISSUE THREAD

**Issue by aurelBZH** [Ensembl/ensembl-vep#291]
Hello,
 thanks for the work on vep it's a great software.
I'm looking for a way to keep alt and ref allele with tab option and i haven't found any. is there a way to that  and if not why ? 
thanks a lot 
Aurelien Béliard 
Bioinformatician 
icm institute

**Comment by ens-lgil** [comment]
Dear Aurelien,

At the moment we only keep them when the overlapped transcripts don't match the reference (some RefSeq transcripts for instance), in the columns GIVEN_REF and USED_REF.
However I don't see why we couldn't have a ref allele column in the tab output. We will try to add it in the next Ensembl release (95).

Best regards,
Laurent

**Comment by ens-lgil** [comment]
Dear @aurelBZH,

A new flag `--show_ref_allele` will be available in our next Ensembl release (version 95, due in December), which will add an extra column "REF_ALLELE" in the tab output and will contain the reference allele.

Best regards,
Laurent
