### ISSUE TITLE
filter_vep doesn't seem to recognize any ANN subfields

### ISSUE THREAD

**Issue by PedroBarbosa** [Ensembl/ensembl-vep#294]
I'm using Ensembl VEP docker image v 93.3 to filter my VCF by MAF frequency in the 1000G and gnomAD populations. I ran VEP using docker along with my local cache.

When I list the available fields, the ANN subfields don't show up:
` filter_vep -i infile.vcf --vcf_info_field ANN --list`

And when I filter for rare variants in gnomAD no variants are reported:
`filter_vep -i infile.vcf --vcf_info_field ANN -f "gnomADg_AF < 0.01"`

However, I see that both gnomeAD fields are added in the ANN and INFO fields (for some reason that I'm not aware). Is this conflict that avoids VEP to report the passing variants ?Moreover, if I want to filter by MAF in the 1000G population, I suppose I should use the AF subfield field within the ANN field, right? How can vep_filter recognize which AF field to look (allele frequency for the ALT allele vs 1000G frequency) ?

Please find [attached](https://github.com/Ensembl/ensembl-vep/files/2461483/infile.txt) 10 variants from my VCF (including the header). Edit: Didn't check if any on these 10 variants have indeed "nomADg_AF < 0.01", but you can test with other thresholds

Thanks in advance,
PedroBarbosa

**Comment by PedroBarbosa** [comment]
As a workaround, I'm trying to filter the variants directly on the VEP run. As I see, `--filter_common` only filters based on the global 1000G frequency (AF) (that worked with me), so I use the following command instead:

`srun shifter -V=/mnt/nfs/lobo/IMM-NFS/ensembl_vep:/media --image=ensemblorg/ensembl-vep:latest vep -i $vcf_file -o $outfile --compress_output bgzip --cache --dir /media/cache --offline --vcf  -a GRCh37 --vcf_info_field ANN --freq_freq 0.0001 --freq_gt_lt lt --freq_filter include --check_frequency --freq_pop gnomAD`

However, VEP throws an invalid population error:
```-------------------- EXCEPTION --------------------
MSG: ERROR: Invalid population gnomAD specified
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::BaseCacheVariation::check_frequency_filter /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseCacheVariation.pm:273
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::BaseCacheVariation::new /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseCacheVariation.pm:93
STACK Bio::EnsEMBL::VEP::CacheDir::get_all_AnnotationSources /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:202
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:121
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /opt/vep/src/ensembl-vep/vep:224
Date (localtime)    = Wed Oct 10 00:49:09 2018
Ensembl API version = 93
```
but I know and verified that frequencies from exome gnomAD are present in the VCF as I set `--af_gnomad` in the original run.

What may be the issue here ? As a curiosity, would it be possible to set `--freq_pop` multiple times so I could filter based on more than 1 population (as filter_vep would naturally allow). What about the None values (absent variants in the databases). I want to keep them as well, but with these frequency filters seems not possible.

**Comment by ens-lgil** [comment]
Dear @PedroBarbosa,

Thank you for reporting these issues.
Fortunately they were both quick to fix and we added the updated code into the branch `release/93` (or you can use the tag `release/93.6`).

Best regards,
Laurent

**Comment by ens-lgil** [comment]
Dear @PedroBarbosa,

About your questions:
-  The `AF` field corresponds to the global 1000Genomes frequency for the alternative allele.
- The filtering options were originally created within the VEP script (`vep`) but because we wanted to provide something more powerful for our users we created the separate script `filter_vep`.
We are aiming to improve the filtering only in this script, so it is unlikely that we will develop the filtering in the `vep` script itself.

Best regards,
Laurent

**Comment by ens-lgil** [comment]
Dear @PedroBarbosa,

Sorry for the late reply.
Unfortunately, at the moment `filter_vep` only filter in or out the lines from the input file and therefore is not modifying the content of the lines.
However your suggestion to filter data within the CSQ/ANN block in VCF is an interesting feature to develop.
Furthermore the filtering on the others VEP output formats (VEP default output and tab-delimited output) works currently like this as each consequence prediction of a variant is displayed as a distinct line.

Best regards,
Laurent
