### ISSUE TITLE
Identify SNPs affecting to the same codon

### ISSUE THREAD

**Issue by iranmdl** [Ensembl/ensembl-vep#301]
Hello!
Is there any option in VEP to identify those SNPs affecting to the same codon? In case of having two homozygous variants located 0 or 1 bp apart from each other, how can I know if both are affecting to the same codon?

Thank you in advance

**Comment by aparton** [comment]
Hi,

Thank you for your query. We have a VEP plugin that will report variants that are known to affect the same codon as your given variant, this can be found here: https://github.com/Ensembl/VEP_plugins/blob/release/94/SameCodon.pm <https://github.com/Ensembl/VEP_plugins/blob/release/94/SameCodon.pm>

The SameCodon plugin can be installed using the VEP installer (found at /ensembl-vep/INSTALL.pl), and documentation on how to run a plugin can be found here: https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html <https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html>

If there’s anything else I can do to help, please let me know.

Kind Regards,
Andrew

**Comment by iranmdl** [comment]
Hello!
Thank you for the quick answer. 
Is the plugin only valid for known variants? I mean, if I have created "manually" two mutations in my VCF file affecting to the same codon (but those mutations have not be described previously, "not-known"). Can I still check if they are affecting to the same codon using the plugin?

**Comment by nuno-agostinho** [comment]
Hi @iranmdl,

I am going to close this issue as we haven't heard back from you in a while.

Hopefully everything is working as expected, but please feel free to create a new issue if you are still facing any problems with VEP.

Thanks,
Nuno
