### ISSUE TITLE
VEP fails to recognize Custom GFF file for annotation

### ISSUE THREAD

**Issue by sum732** [Ensembl/ensembl-vep#302]
Dear VEP Team,

I have built a custom GFF3 format file from StringTie. I used the online resource from "genometools" (http://genometools.org/cgi-bin/gff3validator.cgi) to validate the file. The file passes validation.

However, VEP is NOT able to use this file. I am getting "repeated" warnings of the following lines

`WARNING: 17723 : Use of uninitialized value $record_id in hash element at /software/vep/v92/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm line 385, <__ANONIO__> line 5142.
Use of uninitialized value $record_id in hash element at /software/vep/v92/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm line 392, <__ANONIO__> line 5142.
Use of uninitialized value $record_id in hash element at /software/vep/v92/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm line 392, <__ANONIO__> line 5142.`

AND

`WARNING: Unable to determine biotype of ENST00000370256.4
WARNING: Unable to determine biotype of ENST00000370256.4
WARNING: Unable to determine biotype of ENST00000441799.1
WARNING: Unable to determine biotype of ENST00000441799.1`
and more like the above. 

Exact command used in:
`vep --cache --dir_cache /modules/ogi-mbc/software/vep/v92/cache --dir_plugins /modules/ogi-mbc/software/vep/v92/plugins_dir --assembly GRCh37 --offline --vcf --fork 4 --hgvs --fasta /data/genomes/hg19_gatk_rCRS/ucsc.hg19.rCRS.fasta.gz --protein --uniprot --xref_refseq --merged --force_overwrite --canonical --regulatory --vcf_info_field ANN --input_file sample.decomp.norm.vcf --output_file sample.decomp.norm.VEP.vcf --custom /home/Human/gff_Files/HNR_StrandFixed_WithFullFeature_withCHRPrefix.sorted.gff.gz,StringTie,gff
`
I am using v92.4 of VEP 

Please suggest how to fix the issue.
Thanks.

**Comment by ens-lgil** [comment]
Dear @sum732,

VEP uses a couple of extra attributes in the 9th column (biotype and parent/Parent):
https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff
At the moment VEP needs also an ID attribute for each record, however we are working on fixing this  so it will be mandatory only for gene and transcript.

Please, could you send us a sample of your GFF, so we can help you find the issue ?

Best regards,
Laurent

**Comment by sum732** [comment]
Thank you so much Laurent for promptly responding and looking into the issue.

In the file I only have transcripts (parent) and exon(child). Each exon does have a parent ID.

Sample gff file is here 
`"https://www.dropbox.com/s/4ikthswl64tmjyh/Sample_StringTie.gff.txt?dl=0"`
About biotypes, they are not reported by StringTie, can a simple tag biotype="NULL" will work? Can this be not mandatory? 
Best,
Sudeep

**Comment by sum732** [comment]
Thanks Laurent for releasing the fix.

I can understand that biotypes should follow SO rules. I can try and add biotypes for "known" transcripts and exons. I agree with you that biotypes helps to provide accurate predictions. For VEP the cache file is there to make predictions. All I want is to add a custom annotations showing the new transcripts and exons. This new GFF is an 'add-on' to the cache file from VEP. 

In our sample set, we have identified and confirmed presence of novel exons and StringTie has used this and current gene model to make transcripts. 

So is there a work around, i dont want to add any biotype to a new transcripts when we only know its presence and NOT its actual functions.

**Comment by ens-lgil** [comment]
Dear @sum732,

I see what you mean, however the prediction will be incomplete (or inacurate) without the correct biotype. Futhermore, having a CDS entry will give you more accurate data for the protein_coding transcripts.
Here are some examples (using a CAV3 transcript):

# 1 - With a biotype "other"

Input:
`3	StringTie	transcript	8775486	8788451	1000.00	+	.	ID=ENST00000343849;biotype=other;gene_name=CAV3
3	StringTie	exon	8775486	8775676	1000.00	+	.	Parent=ENST00000343849
3	StringTie	exon	8787212	8788451	1000.00	+	.	Parent=ENST00000343849`

Output (default VEP output format):
`var1	3:8775593	A	-	ENST00000343849	Transcript	non_coding_transcript_exon_variant	108	-	-	-	-	-	IMPACT=MODIFIER;STRAND=1;SOURCE=StringTie`
Cache output:
`var1	3:8775593	A	ENSG00000182533	ENST00000343849	Transcript	missense_variant	108	31	11	A/T	Gcc/Acc	-	IMPACT=MODERATE;STRAND=1`


# 2 - With a biotype "other" and a new line for the CDS
If you add a CDS you can get a result similar to the cache:

Input:
`3	StringTie	transcript	8775486	8788451	1000.00	+	.	ID=ENST00000343849;biotype=other;gene_name=CAV3;
3	StringTie	exon	8775486	8775676	1000.00	+	.	Parent=ENST00000343849
3	StringTie	exon	8787212	8788451	1000.00	+	.	Parent=ENST00000343849
3	StringTie	CDS	8775563	8787553	.	+	.	Parent=ENST00000343849`

Output (default VEP output format):
`var1	3:8775593	A	-	ENST00000343849	Transcript	missense_variant	108	31	11	A/T	Gcc/Acc	-	IMPACT=MODERATE;STRAND=1;SOURCE=StringTie`

I hope this helps.
Best regards,
Laurent

**Comment by sum732** [comment]
Thanks so much Laurent for your patience and your continued support. 

I completely agree with you that "consequences" wont be accurate. Having CDS will help VEP to know the coding sequences and annotate better. However, I am restricted with what I am getting from StringTie and that is only "exons" and "transcripts", with gene name nothing else. 

So based on your suggestion and idea, for now, the best approach is to use the approach "1". 

Add biotype as "other". So for variants on the transcripts(novel or known) from novel exons will have inaccurate/incomplete BUT since cache file is there the ensembl/Ref annotation will still be there.

I know it does not fully resolves what we want. As we want to know impact of the new exons/transcripts and if its disease causing in our tissue. Until more analysis is done to known functionality.

So to wrap this up. I would need to get the new VEP version, and in my GFF file, for transcripts add  `biotype=other` and this should work. Am I correct or missing something.

My Best,
Sudeep

**Comment by ens-lgil** [comment]
Dear @sum732,

Yes, the annotations based on the VEP cache will give you the "correct" predictions and the annotations based on your GFF file might give you inacurate predictions (but they will be labelled with `StringTie`).
Just to let you know, I am going to push a tiny fix in the next minutes on `release/94`.

I hope you pipeline will work with the addition of the `biotype` attribute.

Best regards,
Laurent

**Comment by sum732** [comment]
Dear Laurent,

VEP was updated:
`vep -help
#----------------------------------#
# ENSEMBL VARIANT EFFECT PREDICTOR #
#----------------------------------#

Versions:
  ensembl              : 94.5c08d90
  ensembl-funcgen      : 94.08b0c13
  ensembl-io           : 94.8d53275
  ensembl-variation    : 94.066b102
  ensembl-vep          : 94.4
`
I added  `biotype=other`
Here is an example:
`chr1    StringTie       exon    11869   12227   1000.00 +       .       Parent=ENST00000456328.2
chr1    StringTie       transcript      11869   14409   1000.00 +       .       ID=ENST00000456328.2;biotype=other;geneID=HRN.129;gene_name=DDX11L1
chr1    StringTie       exon    11872   12227   1000.00 +       .       Parent=ENST00000515242.2
chr1    StringTie       transcript      11872   14412   1000.00 +       .       ID=ENST00000515242.2;biotype=other;geneID=HRN.129;gene_name=DDX11L1
chr1    StringTie       exon    11874   12227   1000.00 +       .       Parent=ENST00000518655.2
chr1    StringTie       transcript      11874   14409   1000.00 +       .       ID=ENST00000518655.2;biotype=other;geneID=HRN.129;gene_name=DDX11L1
chr1    StringTie       exon    12010   12057   1000.00 +       .       Parent=ENST00000450305.2
chr1    StringTie       transcript      12010   13670   1000.00 +       .       ID=ENST00000450305.2;biotype=other;geneID=HRN.129;gene_name=DDX11L1
chr1    StringTie       exon    12179   12227   1000.00 +       .       Parent=ENST00000450305.2
chr1    StringTie       exon    12595   12721   1000.00 +       .       Parent=ENST00000518655.2
chr1    StringTie       exon    12613   12697   1000.00 +       .       Parent=ENST00000450305.2
chr1    StringTie       exon    12613   12721   1000.00 +       .       Parent=ENST00000456328.2
chr1    StringTie       exon    12613   12721   1000.00 +       .       Parent=ENST00000515242.2
chr1    StringTie       exon    12975   13052   1000.00 +       .       Parent=ENST00000450305.2
chr1    StringTie       exon    13221   13374   1000.00 +       .       Parent=ENST00000450305.2
chr1    StringTie       exon    13221   14409   1000.00 +       .       Parent=ENST00000456328.2
chr1    StringTie       exon    13225   14412   1000.00 +       .       Parent=ENST00000515242.2
chr1    StringTie       exon    13403   13655   1000.00 +       .       Parent=ENST00000518655.2
chr1    StringTie       exon    13453   13670   1000.00 +       .       Parent=ENST00000450305.2
chr1    StringTie       exon    13661   14409   1000.00 +       .       Parent=ENST00000518655.2
chr1    StringTie       exon    14363   14829   1000.00 -       .       Parent=ENST00000423562.1
chr1    StringTie       exon    14363   14829   1000.00 -       .       Parent=ENST00000438504.2
chr1    StringTie       exon    14363   14829   1000.00 -       .       Parent=ENST00000541675.1`

Now getting a different error then before:

`WARNING: 48816 : Use of uninitialized value in hash element at /software/vep/v94/ensembl-vep/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 143.
Use of uninitialized value in hash element at /software/vep/v94/ensembl-vep/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 143.`
and more...

Could you please suggest how to go about fixing this issue.

Best,
Sudeep

**Comment by ens-lgil** [comment]
Dear Sudeep,

I am sorry, I tested your GFF file and VCF example with the flag `--no_stats`.
The warning message (only concerns the summary reports) is due to the fact that the script is expecting a Gene from your GFF.

Here is your example with the added gene:
```chr1	StringTie	gene	11869	14412	1000.00	+	.	ID=ENSG00000223972;geneID=HRN.129;gene_name=DDX11L1
chr1	StringTie	exon	11869	12227	1000.00	+	.	Parent=ENST00000456328.2
chr1	StringTie	transcript	11869	14409	1000.00	+	.	ID=ENST00000456328.2;biotype=other;geneID=HRN.129;gene_name=DDX11L1;Parent=ENSG00000223972
chr1	StringTie	exon	11872	12227	1000.00	+	.	Parent=ENST00000515242.2
chr1	StringTie	transcript	11872	14412	1000.00	+	.	ID=ENST00000515242.2;biotype=other;geneID=HRN.129;gene_name=DDX11L1;Parent=ENSG00000223972
chr1	StringTie	exon	11874	12227	1000.00	+	.	Parent=ENST00000518655.2
chr1	StringTie	transcript	11874	14409	1000.00	+	.	ID=ENST00000518655.2;biotype=other;geneID=HRN.129;gene_name=DDX11L1;Parent=ENSG00000223972
chr1	StringTie	exon	12010	12057	1000.00	+	.	Parent=ENST00000450305.2
chr1	StringTie	transcript	12010	13670	1000.00	+	.	ID=ENST00000450305.2;biotype=other;geneID=HRN.129;gene_name=DDX11L1;Parent=ENSG00000223972
chr1	StringTie	exon	12179	12227	1000.00	+	.	Parent=ENST00000450305.2
chr1	StringTie	exon	12595	12721	1000.00	+	.	Parent=ENST00000518655.2
chr1	StringTie	exon	12613	12697	1000.00	+	.	Parent=ENST00000450305.2
chr1	StringTie	exon	12613	12721	1000.00	+	.	Parent=ENST00000456328.2
chr1	StringTie	exon	12613	12721	1000.00	+	.	Parent=ENST00000515242.2
chr1	StringTie	exon	12975	13052	1000.00	+	.	Parent=ENST00000450305.2
chr1	StringTie	exon	13221	13374	1000.00	+	.	Parent=ENST00000450305.2
chr1	StringTie	exon	13221	14409	1000.00	+	.	Parent=ENST00000456328.2
chr1	StringTie	exon	13225	14412	1000.00	+	.	Parent=ENST00000515242.2
chr1	StringTie	exon	13403	13655	1000.00	+	.	Parent=ENST00000518655.2
chr1	StringTie	exon	13453	13670	1000.00	+	.	Parent=ENST00000450305.2
chr1	StringTie	exon	13661	14409	1000.00	+	.	Parent=ENST00000518655.2
```
`chr1	StringTie	gene	11869	14412	1000.00	+	.	ID=ENSG00000223972;geneID=HRN.129;gene_name=DDX11L1` as gene entry and added as parent in the transcripts.

If you are not interested in the summary reports, you can add the flag `--no_stats` to your VEP command.

Best regards,
Laurent

**Comment by sum732** [comment]
Thanks Laurent. Seems to be working now. No errors and annotation can be seen in the output file.
