### ISSUE TITLE
Docker release mixup?

### ISSUE THREAD

**Issue by glormph** [Ensembl/ensembl-vep#307]
Hi, when I do:

```
docker pull ensemblorg/ensembl-vep:release_94
docker run -ti ensemblorg/ensembl-vep:release_94 /bin/bash
vep
```

The output shows version 93:
```
vep@9262fec36719:~/src/ensembl-vep$ vep                                                                                                                                                                                  
#----------------------------------#
# ENSEMBL VARIANT EFFECT PREDICTOR #
#----------------------------------#

Versions:
  ensembl              : 93.b4d45ee
  ensembl-funcgen      : 93.0c98373
  ensembl-io           : 93.cc29a66
  ensembl-variation    : 93.c9c43a7
  ensembl-vep          : 93.3

Help: dev@ensembl.org , helpdesk@ensembl.org
```

ANd when downloading `release_94`, you get version 93. I guess there has been a mixup or I have done something very wrong here.

**Comment by ens-lgil** [comment]
Dear @glormph,

I am very sorry for the confusion: this image `release_94` shouldn't have been created.
As you can see in [Docker Hub](https://hub.docker.com/r/ensemblorg/ensembl-vep/tags/), the VEP images are in the format `release_XX.X`.
The image `release_94` was created automatically by mistake and we forgot to remove it.

Please use the image `release_94.0` instead or the image `latest` (same as `release_94.4`).

Best regards,
Laurent

**Comment by glormph** [comment]
No problem and thanks for the information! 👍
