### ISSUE TITLE
Error Faidx.so: undefined symbol: Perl_Gthr_key_ptr

### ISSUE THREAD

**Issue by marbeno** [Ensembl/ensembl-vep#311]
I recently installed seqr, which includes vep (from [here](https://github.com/macarthur-lab/seqr/blob/master/deploy/LOCAL_INSTALL.md)).  The version of perl installed with seqr is the [5.20](https://github.com/macarthur-lab/seqr/commit/527e2998dd6c8b59dedd6064842c63359936568d)

vep gives the following:
`$ perl seqr/vep/variant_effect_predictor/variant_effect_predictor.pl`
`perl: symbol lookup error: /media/DataHD/seqr/seqr/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/Faidx.so: undefined symbol: Perl_Gthr_key_ptr`

`$ perl -version`
`This is perl 5, version 20, subversion 3 (v5.20.3) built for x86_64-linux
(with 1 registered patch, see perl -V for more detail)`

I was wondering whether it might depend on perl version.

**Comment by ens-lgil** [comment]
Dear @marbeno,

This might be because you have different Perl versions installed on your machine and Perl librairies installed by VEP are installed on a different version than 5.20.
Here is what I found:
> Some research suggest this is caused by the shared library being built against a different version of perl. 

Here is the full page: http://jtes.net/2011/12/03/perl-perl_gthr_key_ptr-problems/

I hope this helps.

Best regards,
Laurent

**Comment by marbeno** [comment]
Hi,
thanks for you reply and sorry to bother again.
For what I understood, with their procedure, you download all the libraries from hail without the need for installing them (see below), am I correct?

`$ gsutil ls gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/`

```
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/Faidx.so
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/HTS.so
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/INSTALL.pl
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/PATCHED
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/README.txt
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/convert_cache.pl
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/create_new_cache.sh
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/example_GRCh37.vcf
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/example_GRCh38.vcf
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/filter_vep.pl
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/gtf2vep.pl
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/stdout_summary.html
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/stdout_warnings.txt
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/variant_effect_predictor.pl
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/Bio/
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/biodbhts/
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/htslib/
gs://hail-common/vep/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/t/
```

**Comment by ens-lgil** [comment]
Dear @marbeno,

Unfortunately we only develop and provide **VEP**, and we don't have knowledge about the way **seqr** is installing VEP.
However our own VEP installer needs to install and compile several external libraries (in Perl and C).
Furthermore **seqr** is using a quite old version of VEP (~3 years old) that we don't really support anymore: the code is stored in a different GitHub repository: [ensembl-tools](https://github.com/Ensembl/ensembl-tools/tree/release/85/scripts/variant_effect_predictor).

If you don't succeed to fix the Perl issue, I suggest that you contact the **seqr** developers about this problem.

Best regards,
Laurent

**Comment by marbeno** [comment]
Hi, 
thank you again. I'll contact them.

Best regards
