### ISSUE TITLE
No output from haplo

### ISSUE THREAD

**Issue by LeeNicha** [Ensembl/ensembl-vep#315]
Hi, I got a problem when I run haplo with case4.strelka.vcf by using this command

./haplo --json -i case4.strelka.vcf -o output_file --cahce

Output does not exist and no error. 
While I run with another file such as case4.muse.vcf, it generated the output file.

Thank you in advance.

[Archive.zip](https://github.com/Ensembl/ensembl-vep/files/2538572/Archive.zip)

**Comment by ima23** [comment]
Hi LeeNicha,

Thanks for the example files. Haplosaurus takes **phased genotyped** data as input.
 
Looking at the two files only `case4.muse.vcf` is genotyped (contains the GT field) however it's not phased. Phased genotypes have the GT field for example like this '1|0', while the file is '0/1'.
The vcf  file`case4.strelka.vcf` is not genotyped as it's missing the GT field.

An updated version of the documentation will be out in the next release and will contain additional examples on this page:
http://www.ensembl.org/info/docs/tools/vep/haplo/index.html

Best wishes,
Irina

**Comment by LeeNicha** [comment]
Thank you for your replying.

The genotyped file, case4.muse.vcf, was phased by using Beagle software.
Do you know how can I phase GT field in case4.strelka.vcf?

**Comment by ima23** [comment]
Hi LeeNicha,

The Beagle software is not developed by our team. I suggest you go through their documentation to check what options are offered to get a phased genotyped vcf and contact them if the information is unclear or missing.

Thanks,
Irina
