### ISSUE TITLE
Add information of prerequisite

### ISSUE THREAD

**Issue by hsiaoyi0504** [Ensembl/ensembl-vep#317]
At far as I know, following prerequisite needs to be fulfilled:
- gcc
- g++
- perl modules
   - Archive::Zip
   - Try::Tiny

**Comment by ens-lgil** [comment]
Dear @hsiaoyi0504,

Many thanks for your suggestions!
You are right that these requirements are currently missing from our documentation.
We will add them for the next Ensembl (and VEP) release.

Just to let you know, `Try::Tiny` is not really required as the VEP INSTALL script tries to use others libraries/tools before looking for this Perl library.

Best regards,
Laurent

**Comment by hsiaoyi0504** [comment]
Got it, thanks !

**Comment by hsiaoyi0504** [comment]
Will be fixed by #320.
