### ISSUE TITLE
htslib version

### ISSUE THREAD

**Issue by ClayBirkett** [Ensembl/ensembl-vep#318]
running vep using local file failed with error "can't identify format". I changed to
$HTSLIB_VERSION = '1.8'
and it fixed the problem. I use tabix --csi because of a large genome

**Comment by ens-lgil** [comment]
Dear @ClayBirkett,

Many thanks for your message.
We are aiming to move to a more recent version of `htslib` in the next releases.
By any chance, did you use the option `--format` to specify your input file format ?

Best regards,
Laurent

**Comment by ClayBirkett** [comment]
No, I used the default input format as listed on ensembl documentation so I didn’t need to specify format.

Clay

On Nov 6, 2018, at 4:15 AM, Laurent Gil <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear @ClayBirkett<https://github.com/ClayBirkett>,

Many thanks for your message.
We are aiming to move to a more recent version of htslib in the next releases.
By any chance, did you use the option --format to specify your input file format ?

Best regards,
Laurent
