### ISSUE TITLE
'--distance' option internal logic for MT

### ISSUE THREAD

**Issue by henrikstranneheim** [Ensembl/ensembl-vep#321]
If you do not want to split the vep processing per contigs the '--distance' option does a poor job with the MT contig as it will annotate to many genes in the upstream and downstream annotation when using the default. And if you modify it for the MT it will be a poor annotation for the nuclear genome. 

Is there any chance that VEP could change the value of the '--distance' option internally (unless set by the user) when processing the mitochondrial contig to a more sane default e.g. "10"?

**Comment by ens-lgil** [comment]
Dear @henrikstranneheim,

Thank you for reporting this use case issue.
This is default setting is definitively an issue on MT and we are looking into finding a good way to solve this problem.

Best regards,
Laurent

**Comment by henrikstranneheim** [comment]
Actually for MT one should probalvby use '--distance 0'.

**Comment by nuno-agostinho** [comment]
Hey @henrikstranneheim, thanks for this suggestion.

We are thinking about improving the implementation of `--distance` for small chromosomes and genomes in a future rewrite of VEP. We could adjust the value of base pairs to consider based on the chromosome length (or simply set it to 0, as you suggested).

For now, the workaround is to use VEP separately for small chromosomes, so you will have to analyse mitochondrial variants separately. You can do so by using the flag [`--chr`](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_chr) to subset a list of chromosomes to analyse.

As this is low priority for us, I am going to close this issue. Sorry for the inconvenience.

Best regards,
Nuno
