### ISSUE TITLE
is `--domains` no longer available with GRCh37?

### ISSUE THREAD

**Issue by genomics-geek** [Ensembl/ensembl-vep#322]
Seems like using the flag `--domains` when using a GRCh37 cache does not annotate domains with vep v93.  Is this expected behavior?

**Comment by genomics-geek** [comment]
I am also using `--refseq`, so I think it may be related to this as well.

**Comment by ens-lgil** [comment]
Dear @genomics-geek,

Unfortunately the `--domains` flag doesn't work with RefSeq data as we only have protein domain annotations associated with the Ensembl transcripts in Ensembl.

Best regards,
Laurent

**Comment by genomics-geek** [comment]
Ahh that makes sense. I used to use ‘—merged’  and used to see the annotations. 

Thanks for the information.
