### ISSUE TITLE
[feature request] Install as a perl module and run easily

### ISSUE THREAD

**Issue by hsiaoyi0504** [Ensembl/ensembl-vep#323]
Is it possible to install `ensembl-vep` through `cpanminus` and then can be directly started to use ? I mean after the installation, `vep` will be in the `$PATH` and can be run anywhere through `vep` command. Is any bottleneck there ? Although I am not an expert perl developer, I would like to help to achieve that.

**Comment by aparton** [comment]
Hi,

Thank you for your interest in VEP. Currently, with the amount of non-perl dependancies that VEP has, we are not looking into allowing vep to be installed through cpan-minus. 

We will be making alterations to our installation procedures within the coming months, so we’re hoping to be able to provide you with a smoother installation process soon. Additionally, If you are looking for an alternative way to install VEP, then we also have a Docker image (https://hub.docker.com/r/ensemblorg/ensembl-vep/) that may be useful to you.

Kind Regards,
Andrew
