### ISSUE TITLE
Include allele fraction in output?

### ISSUE THREAD

**Issue by michelled3** [Ensembl/ensembl-vep#326]
Hello, 

I am not sure if there's an existed flag for including allele fraction in the output. The ones I can find online are mostly about including the global AF from databases such as 1000Genome or gnomAD. While that's great, would it be possible to have the frequency for the specific position (so alternative allele reads/ total reads)? It seems like the information is probably there since there's a '-freq_freq' filter option. 

Thank you! 

Best,
Michelle

**Comment by helensch** [comment]
Hi

I was not clear if you were querying the availability of allele frequency or allele read counts.

When the species selected is human, VEP can report allele frequency (AF) for variants that are co-located with variants from your input data. The allele frequency is from several major projects: 1000 Genomes, gnomAD (exomes) and ESP. 

Information on the output options for co-located variants is described at
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#output

--freq_freq option is used to specify the allele frequency to use for filtering                                        

VEP can also retrieve frequency data from the gnomAD genomes set or ExAC via VEP's custom annotation functionality.
https://www.ensembl.org/info/docs/tools/vep/script/vep_example.html#gnomad

Any of the fields in the gnomAD file INFO field can be added by appending them to the list in your VEP command, this includes AC (Allele_count) fields.

Please let me know if you need any more info.

**Comment by andreabc** [comment]
We are running VEP on Mutect2 output. Mutect2 output includes allelic fraction: "AF,Number=1,Type=Float,Description="Allele fraction of the event in the tumor""

However after running VEP, we no longer find this value. Is there some way to include the FORMAT  TUMOR   NORMAL columns from the original Mutect2 output?

Thanks!

**Comment by helensch** [comment]
Hi @andreabc

Are you writing output in VCF format (--vcf option)?

If the output format is VCF,  consequences are added in the INFO field of the VCF file, using the key "CSQ".

If the input format is VCF and the output format is VCF, the input file will remain unchanged expect for the addition of the CSQ field and the header. The AF will still be in the INFO field.

https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#vcfout

Please let me know if you need  any additional info.

**Comment by andreabc** [comment]
Thank you! This solved our problem.

**Comment by michelled3** [comment]
Thank you!
