### ISSUE TITLE
Uninitialized value $record_id in hash

### ISSUE THREAD

**Issue by donthuanalyst** [Ensembl/ensembl-vep#327]
Hello,

I am trying to run VEP on a non-model organism using a fasta file of reference genome sequence and a GFF3 file of annotation.

I used the following command to run VEP and I am getting the error mentioned below. Please find attached part of a GFF file ([partial_gff3_file.zip](https://github.com/Ensembl/ensembl-vep/files/2596584/partial_gff3_file.zip)) that I am using.

COMMAND USED TO RUN VEP:

<pre>
vep -i VCFfile.vcf -gff sorted.gff3.gz -fasta genome_v6.fna.gz -o VCFfile.vcf.vepout
</pre>

ERROR MESSAGE:

<pre>

Use of uninitialized value $record_id in hash element at /home/apps/software/VEP/92.4-IGB-gcc-4.9.4-Perl-5.24.1/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm line 392, <__ANONIO__> line 241.
Use of uninitialized value $record_id in hash element at /home/apps/software/VEP/92.4-IGB-gcc-4.9.4-Perl-5.24.1/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm line 385, <__ANONIO__> line 241.
Use of uninitialized value $record_id in hash element at /home/apps/software/VEP/92.4-IGB-gcc-4.9.4-Perl-5.24.1/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm line 392, <__ANONIO__> line 241.
Use of uninitialized value $record_id in hash element at /home/apps/software/VEP/92.4-IGB-gcc-4.9.4-Perl-5.24.1/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm line 385, <__ANONIO__> line 241.
Use of uninitialized value $record_id in hash element at /home/apps/software/VEP/92.4-IGB-gcc-4.9.4-Perl-5.24.1/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm line 392, <__ANONIO__> line 241.
</pre>

Thank you,
Kiran

**Comment by ens-lgil** [comment]
Dear @donthuanalyst,

This is a know issue as VEP expects an `ID` for each line (including `exon`) in the GFF files, which is actually not mandatory in the GFF3 specifications
This is issue will be fixed in the next VEP version (95) which should be released next month.
In the mean time, one solution would be to add "fake" exon IDs in your GFF file.

Best regards,
Laurent

**Comment by donthuanalyst** [comment]
Dear Laurent,

Thank you for your answer. I see that in GFF file there are IDs for CDS lines but not for exon lines.

Can the fake ID for each exon line be anything (eg. exon1, exon2, etc) or should it follow the same pattern as CDS ID? I see that all CDS lines of a transcript (or mRNA) have same IDs. Do I need to give same ID for all exon lines that belong to the same mRNA?

Thank you,
Kiran

**Comment by ens-lgil** [comment]
Dear @donthuanalyst ,

The exon ID itself is not used in the VEP results. This only helps VEP to build the "unique" relation mRNA<->exon. However I would recommand to use unique exon IDs.
For instance you have the mRNA `mRNA1390`, you can name your exons `exon1390_1`, `exon1390_2`, ...

I hope this makes sense.
Best regards,
Laurent

**Comment by donthuanalyst** [comment]
Dear Laurent,

I added IDs to the exons lines. I noticed that IDs were missing for SOME of 3' and 5' UTR lines. I then added IDs for those UTR lines as well.

I then reran VEP and I still got the same error (Use of uninitialized value $record_id). However, this time the output file has some results (about 3190 rows). 

Later I found that there were lines in my GFF3 file with just "###". I then removed such lines from my GFF file and reran VEP. This time again I have the same error but my output file size is increased (with about 8000 rows)

It looks like VEP is not completely producing results for all the input SNPs. 

Please find below sample GFF file and output file that I used to run VEP. 

[partial.sorted.exonIDs.3P5PIDs.GFF3.zip](https://github.com/Ensembl/ensembl-vep/files/2601642/partial.sorted.exonIDs.3P5PIDs.GFF3.zip)
[partial_output.zip](https://github.com/Ensembl/ensembl-vep/files/2601705/partial_output.zip)

Thank you so much for your help.
Kiran

**Comment by ens-lgil** [comment]
Dear @donthuanalyst,

Unfortunately I can see why it failed: your GFF file looks ok to me.
Could you have a look at the failing input line(s), e.g.:
```
Use of uninitialized value $record_id in hash element at /home/apps/software/VEP/92.4-IGB-gcc-4.9.4-Perl-5.24.1/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm line 392, <__ANONIO__> line 241.
```
where **line 241** is the input line.
This might be an other missing ID.

Best regards,
Laurent

**Comment by ens-lgil** [comment]
I am closing this issue. Please reopen it if you have further questions or start a new issue thread.
