### ISSUE TITLE
Documented cache version of Gencode (28) inconsistent with info.txt (29) for release 94

### ISSUE THREAD

**Issue by mbookman** [Ensembl/ensembl-vep#329]
According to https://uswest.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache_content the version of Gencode for GRCh38 in the cache is 28:

```
Source                      Version (GRCh38)
Ensembl database version    94
...
GENCODE                     28
...
```

In the file `homo_sapiens/94_GRCh38/info.txt` found in ftp://ftp.ensembl.org/pub/release-94/variation/VEP/homo_sapiens_vep_94_GRCh38.tar.gz, it indicates:

```
species homo_sapiens
assembly    GRCh38
...
source_gencode  GENCODE 29
...
```

Gencode 29 seems like it would be the correct value as the [Ensembl94 release coincided with the GENCODE 29 release](http://www.ensembl.info/2018/10/03/ensembl-94-is-out/), and the [Ensembl92 release coincided with the GENCODE 28 release](http://www.ensembl.info/2018/04/05/ensembl-92-has-been-released/).

**Comment by ens-lgil** [comment]
Dear @mbookman,

You right: VEP is using GENCODE `29` in the Ensembl version 94.
It seems that there was an issue when we updated the online documentation.
This will be fixed in the new Ensembl 95, which should be released next month.

We apologise for the confusion.

Best regards,
Laurent
