### ISSUE TITLE
Bio::DB::BigFile module within docker image

### ISSUE THREAD

**Issue by PedroBarbosa** [Ensembl/ensembl-vep#334]
Hello,

I would like to use bigwig as a custom annotation file but I'm not sure how I should map the plugin within my docker image. I map my local cache within the image as follows:

```shifter -V=/mnt/nfs/lobo/IMM-NFS/ensembl_vep:/media --image=ensemblorg/ensembl-vep:latest```

Where /ensembl_vep folder contains the /cache and /custom_data dirs. How can I make the VEP image to recognize my installed Bio::DB::BigFile module??

Thanks,
Pedro

**Comment by PedroBarbosa** [comment]
With a previous release I do not have this issue. (Tested with release_94.3 tag)

**Comment by ens-lgil** [comment]
Dear @PedroBarbosa,

Thank you for reporting this issue. It seems that the new Docker image is not installing this Perl library.
We are investigating it and will get back to you once we found the problem.

Best regards,
Laurent

**Comment by ens-lgil** [comment]
Dear @PedroBarbosa,

We just pushed a fix so the Bio::DB::BigFile module installation doesn't fail anymore.
We built a new VEP Docker image with the fix: `ensemblorg/ensembl-vep:latest`
Please, could you pull the new Docker image ?
```
docker pull ensemblorg/ensembl-vep:latest
```
Best regards,
Laurent

**Comment by PedroBarbosa** [comment]
Thank you @ens-lgil , it's working now.

Best regards,
Pedro
