### ISSUE TITLE
VEP api have different behavior for offline and cache

### ISSUE THREAD

**Issue by MuhammedHasan** [Ensembl/ensembl-vep#337]
I am trying to write VEP plugin. I am testing my plugin with offline and cache modes. Two different modes give different results. Since I install all the necessary cache files to my local machine, I expect to get the same results. Then, I realized that MaxEntScan also have similar behavior so I am explaining the problem in there on MaxEntScan.

I install VEP, `94_GRCh37`  annotation file and homo_sapience fasta (94_GRCh38) file using `perl Install` comment.

I use [this vcf file](https://github.com/gagneurlab/MMSplice/blob/master/tests/data/test.vcf.gz) for testing.

I am running and getting results more or less I am expecting to see:
```
vep -i test.vcf --plugin MaxEntScan,/my-path/maxentscan/ --assembly GRCh37 --cache --port 3337
```

Then, I am running offline mode with:
```
vep -i test.vcf --plugin MaxEntScan,/my-path/maxentscan/ --assembly GRCh37 --offline --fasta ~/.vep/homo_sapiens/94_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz
```

The output of this two analysis totally different.

For example, if we check cache mode results at line 244,   
```
125854	17:41197836	T	ENSG00000012048	ENST00000357654	Transcript	intron_variant	-	-	-	-	-	-	IMPACT=MODIFIER;STRAND=-1;MaxEntScan_alt=8.829;MaxEntScan_diff=0.701;MaxEntScan_ref=9.529
```

but in offline mode results is different at same line 
```
125854	17:41197836	T	ENSG00000012048	ENST00000352993	Transcript	intron_variant	-	-	-	-	-	-	IMPACT=MODIFIER;STRAND=-1;MaxEntScan_alt=-18.050;MaxEntScan_diff=0.000;MaxEntScan_ref=-18.050
```

I give this example but almost all results are different. I am expecting to see non-zero diff score for this variant so cache mode is more pleasant. But score distribution (diff, alt)  mostly always negative in offline mode.

Based on my debugging efforts, I find that vep return different sequences although I try to fetch the same interval. This is how I fetch the sequence:
```
sub fetch_seq {
    my ($self, $tva, $start, $end) = @_;
    my $vf = $tva->variation_feature;
    my $tr_strand = $tva->transcript->strand;

    my $seq = $vf->{slice}->sub_Slice($start, $end, $tr_strand)->seq;
    return $seq;
}
```

Do I miss an important aspect of offline mode? If I install all the cache files, I should get the same results, right?

**Comment by aparton** [comment]
Hi Muhammed,

I’ve had a look at this issue this morning and unfortunately I’ve been unable to replicate it. I did notice a couple of things that may be relevant to your issue however:

1) You’re using a GRCh38 fasta file when using the —assembly GRCh37 setup. You can download the correct fasta file here <ftp://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz> or through the installer.

2) Using offline mode and cache mode will provide different header lines output, so comparing by line number ends up comparing the annotations for different transcripts. In your example, the cache file is looking at the transcript ENST00000357654, where  offline is looking at ENST00000352993, giving the different MaxEntScan results.

However, your issue may be entirely unrelated to this. If you’re still having an issue, could you please send me the sample output files for both —cache and —offline that have this issue?

Kind Regards,
Andrew

**Comment by MuhammedHasan** [comment]
Thank you, it seems like the problem is due to usage of wrong fasta file.
