### ISSUE TITLE
HGVS.p for synonymous variants

### ISSUE THREAD

**Issue by segoerge** [Ensembl/ensembl-vep#34]
Hi,

I'm using VEP v87 together with GRCh37.75 and the merged cache. 

Somehow there seems to be a problem with the character set or something. For all synonymous variants I   get an annotation like for example "ENSP00000369497.3:p.Lys1132%3D" where the %3D normally should be a "=". Is this a bug or do I have to configure something?

Best regards and thanks in advance,

Sebastian

**Comment by sarahhunt** [comment]
Hi @segoerge 

By default, we URI escape HGVS strings. To disable this and return '=' instead of '%3D' you can use the command line option  --no_escape.

**Comment by segoerge** [comment]
Great, thanks for the fast response!
