### ISSUE TITLE
BIOTYPE isn't included in the header

### ISSUE THREAD

**Issue by hsiaoyi0504** [Ensembl/ensembl-vep#340]
I get a result from VEP, but it seems to me that one of the attributes (BIOTYPE) in the extra column isn't included in the header section.

**Comment by ens-lgil** [comment]
Dear @hsiaoyi0504,

Please could you provide us with:
- The command line you used to run this instance of VEP
- An example of the data input
so we could test it to replicate the issue and find the source of the problem.

Best regards,
Laurent

**Comment by hsiaoyi0504** [comment]
```
##fileformat=VCFv4.2
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       155192276       .       C       A       .       .       .
```

```
vep --cache -i input.vcf -o output_with_plugin.tsv --regulatory --af --sf output_with_plugin.html --plugin Blosum62 --plugin Downstream --plugin LD,1000GENOMES:phase_3:JPT --plugin LD,1000GENOMES:phase_3:KHV --plugin LD,1000GENOMES:phase_3:CHB --plugin LD,1000GENOMES:phase_3:CHS --plugin LD,1000GENOMES:phase_3:CDX --plugin dbscSNV,./dbscSNV1.1_GRCh38.txt.gz --plugin dbNSFP,./dbNSFP.gz,ALL --plugin CADD,whole_genome_SNVs.tsv.gz,InDels.tsv.gz --plugin ExACpLI --plugin NearestGene --plugin Phenotypes --plugin TSSDistance > output_with_plugin.log
```

**Comment by ens-lgil** [comment]
Dear @hsiaoyi0504,

We found the source of the issue and we pushed a fix for the upcoming release (95) which, hopefully, should be released later this month .

Best regards,
Laurent

**Comment by ens-lgil** [comment]
This is now available in the branch `release/95`.
