### ISSUE TITLE
Missing empty HGVSp in VEP web app

### ISSUE THREAD

**Issue by sandertan** [Ensembl/ensembl-vep#347]
Hi, I was just checking out the VEP web app and it seems that the value for HGVSp is missing from the result. For example:

http://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Results?db=core;tl=USend9IQ52xvc5uF-4810274

Click "Show/Hide columns", select "HGVSp". The first result is a missense variant with T/M amino acid change and protein position 790, but the value for "HGVSp" is empty.

**Comment by aparton** [comment]
Hi,

Thank you for bringing this issue to our attention. The HGVS column shouldn't have been shown in your output table, as the HGVS option was not selected on the VEP input form. We'll update our interface to remove this when it's not applicable. 

Rerunning VEP with the HGVS option selected will provide the information you're looking for: http://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Results?db=core;tl=18jvhU27B7x4aHWS-4833143

Kind Regards,
Andrew

**Comment by sandertan** [comment]
Hi @aparton thanks for the update! I wasn't aware I should have checked this on the input form, thanks for that. It would be nice if this option was turned on by default.

**Comment by ens-lgil** [comment]
This isssue/confusion has been fixed in the version 95 of the Ensembl website.
