### ISSUE TITLE
Stable release version

### ISSUE THREAD

**Issue by matthdsm** [Ensembl/ensembl-vep#35]
Hi,

Is there a version of the new vep that can be considered as "stable"? I'm looking into creating a recipe for the bioconda repository, so it can be used/tested in production pipelines

Thanks
M

**Comment by willmclaren** [comment]
Release branches (e.g. release/88) will contain any post-release bugfixes, so will likely not remain constant. When adding post-release fixes, we create tags with a sub-version number, so you may use one of these as the tags will *not* be moved.

There are not yet any post-release patches on the recently released release/88 branch, so I'd suggest you use the tag [release/88.0](https://github.com/Ensembl/ensembl-vep/tree/release/88.0) as your "stable" release.
