### ISSUE TITLE
Performance of ensembl-vep 88

### ISSUE THREAD

**Issue by loreseeker** [Ensembl/ensembl-vep#36]
Hello.

I have a question regarding ensembl-vep performance. Would it be possible to obtain more details regarding the conditions under which the following results :
"Set up correctly, VEP is capable of processing around 3 million variants in 30 minutes." (from http://www.ensembl.org/info/docs/tools/vep/script/vep_other.html)
were obtained? (number of processors/forks, memory/buffer, command-line flags).

I am asking because both with a locally-built ensembl-vep  and with the provided Docker image, processing a VCF file with 30000 variants takes me around 2.5-3 minutes (with flags --dir --cache --offline --assembly --everything (hgsv gets disabled at runtime because I was just testing things and did not provide a fasta for it) --vcf --no_stats and --fork 8) on a Ubuntu 14.04 workstation with 8 cores and 8 GB of memory. With --fork 4, the same job takes 4 minutes. I have tabix-converted the cache files with convert_cache.pl, the VCF is sorted in chromosomal order, no plugins are used, and I followed "Getting VEP to run faster", except installing Ensembl::XS and copying fasta/cache to memory.

I don't have much experience with VEP so I could be missing something obvious.

Thank you for your time.

**Comment by loreseeker** [comment]
Thank you for the reply.

Switching the --everything flag off brings the run time down to 1.5 minutes for 30000 variants. I have Set::IntervalTree and PerlIO::gzip installed.

I will probably have to keep --everything flag for production runs, but I was hoping to squeeze a bit more performance - to process 3 million variants in 30 minutes, on 8 processors, with 8 GB RAM, vep should be processing around 100000 variants per minute - at best, it's hitting 30000 variants for me. It's a little curious... could be the hardware, I guess.

In any case, thank you for your reply. Please feel free to close this thread.

**Comment by willmclaren** [comment]
You may get additional gains by increasing the fork number higher.

Of course if you have more than one server splitting jobs by chromosome can help too.

**Comment by willmclaren** [comment]
One further thing to mention - are your 30k variants distributed across (all) chromosomes (e.g. from an exome sequencing run), or a small subset from a larger one (e.g. from a genome sequencing run)?

Due to the way VEP reads transcript data from disk (in 1MB chunks as regions are encountered), the performance of 30k variants across the genome will be slower than for 30k variants in a contiguous region.

The dataset used for benchmarking was the [Illumina Platinum Genomes](https://www.illumina.com/platinumgenomes.html) individual VCF for NA12878.

**Comment by loreseeker** [comment]
Yes, the 30k variants are distributed across all chromosomes. I ran the dataset you used for benchmarking (without --everything flag) out of curiosity and it finished in 48 mins (putting 3 million variants at around 35 mins or so), so the variants distribution is probably the reason for reduced performance I was seeing.

Thank you for your help.

**Comment by willmclaren** [comment]
Good news - glad to hear our benchmarks are not wildly out!

We're always working on ways to improve VEP runtime, and your use case is certainly not an uncommon one, so we'll look into how we might improve VEP's runtime for this type of data.

**Comment by muhammadali201** [comment]
Its been five years since this topic was discussed.
Can any one give latest performance analysis of VEP? what is the runtime on latest processors now?
Secondly,
Has there been any effort on using Heterogeneous machines like GPUs / FPGA?
