### ISSUE TITLE
Feature request: gnomAD subset allele frequencies

### ISSUE THREAD

**Issue by sigven** [Ensembl/ensembl-vep#360]
Hi,

Is there any plan to incorporate the latest gnomAD (in v2.1) subset allele frequencies during VEP annotation (i.e. "controls-only", "non-cancer samples", as explained in https://macarthurlab.org/2018/10/17/gnomad-v2-1/)?

kind regards,
Sigve

**Comment by sarahhunt** [comment]
Hi Sigve,

We are planning to incorporate to the latest gnomAD data into VEP, once we have mapped it to GRCh38. We hope to have this in place for our March release. We need to look at the sample numbers before deciding which subsets to include in the VEP caches, but will probably use the non-cancer samples.

The full range of subsets will be available via VEP's custom annotation option. If you are working with GRCh37, you can use this already:

http://www.ensembl.org/info/docs/tools/vep/script/vep_example.html#gnomad

Best wishes,

Sarah

**Comment by sigven** [comment]
Thanks a lot for the info:-) 

regards,
Sigve
