### ISSUE TITLE
Feature request: convert VCF to JSON

### ISSUE THREAD

**Issue by fgvieira** [Ensembl/ensembl-vep#363]
This issue is somewhat related to #346, but to convert VCF to JSON.
Again, `vep` can do it (`--json`), but it would be nice to avoid re-annotating files just to convert formats. Ideally, I'd say to incorporate this features on the `filter_vep` script.

best,

**Comment by olaaustine** [comment]
Hi @fgvieira ,
Hope you are well?
Following discussions with the team, we have decided this is beyond the scope of Ensembl Variant Effect Predictor as a tool.
Please let us know if you have any other issues.
Thank you.
Ola.
