### ISSUE TITLE
Polyphen & SIFT not available

### ISSUE THREAD

**Issue by cookersjs** [Ensembl/ensembl-vep#37]
Hello,

I did see the posting relating to this at: [https://github.com/Ensembl/ensembl-vep/issues/33](https://github.com/Ensembl/ensembl-vep/issues/33)
Unfortunately I wasn't able to get a solution to this problem from that issue page.

I'm working on accomodating the new vep methods into my code, but have run into the same error message for both SIFT and Polyphen: 

```
variant_effect_predictor.pl failed: exit status: 256; output: ; error: 
-------------------- EXCEPTION --------------------
MSG: ERROR: PolyPhen not available

STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::check_sift_polyphen /Users/jcook/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:110
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::new /Users/jcook/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:78
STACK Bio::EnsEMBL::VEP::CacheDir::get_all_AnnotationSources /Users/jcook/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:95
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /Users/jcook/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:81
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /Users/jcook/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:63
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /Users/jcook/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::init /Users/jcook/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:77
STACK Bio::EnsEMBL::VEP::Runner::run /Users/jcook/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:111
STACK toplevel /Users/jcook/ensembl-vep/vep:209
Date (localtime)    = Wed Apr  5 10:33:29 2017
Ensembl API version = 88
---------------------------------------------------
```

Is there a plugin or anything else needed to rectify this? 

I installed using 'perl INSTALL.pl --NO_HTSLIB'

Thanks!

-cookersjs

**Comment by willmclaren** [comment]
Couple of questions:

- why is the script you are running named `variant_effect_predictor.pl`? As of release/88 it is simply `vep`
- what is the full command line you are running?
- which cache file (species, version, assembly) did you install?

**Comment by cookersjs** [comment]
Thanks for the quick reply:

1) That was just a remnant error message from the prior version, it does execute using the 'vep' command

2) The command is input into the command line like so:

`perl "-X" "/Users/jcook/ensembl-vep/vep" "--format" "vcf" "--vcf" "--offline" "--no_progress" "--canonical" "--check_existing" "--check_ref" "--force_overwrite" "--numbers" "--domains" "--cache" "--hgvs" "--pubmed" "--sift" "b" "--polyphen" "b" "--buffer_size" "5000" "--dir_cache" "/Users/jcook/.vep" "--input_file" "common_and_clinical_20170130_UNKNOWN.vcf" "--output_file" "common_and_clinical_20170130_UNKNOWN.vcf.out.vcf" "--fork" "2"`

As well, the same error occurs when just using the sample provided in the documentation:

`./vep -i examples/homo_sapiens_GRCh38.vcf --cache --force_overwrite --sift b`

3) I used option 46: homo_sapiens_vep_88_GRCh38.tar.gz

**Comment by willmclaren** [comment]
It may be possible your cache is incomplete or did not unpack correctly, possibly due to lack of disk space.

Can you try:

`cat /Users/jcook/.vep/homo_sapiens/88_GRCh38/info.txt`

You should get the following:

```species homo_sapiens
assembly        GRCh38
sift    b
polyphen        b
source_polyphen 2.2.2
source_sift     sift5.2.2
source_genebuild        2014-07
source_gencode  GENCODE 26
source_assembly GRCh38.p10
variation_cols  variation_name,failed,somatic,start,end,allele_string,strand,minor_allele,minor_allele_freq,clin_sig,phenotype_or_disease,pubmed,AFR,AMR,EAS,EUR,SAS,AA,EA,ExAC,ExAC_AFR,ExAC_AMR,ExAC_Adj,ExAC_EAS,ExAC_FIN,ExAC_NFE,ExAC_OTH,ExAC_SAS
source_COSMIC   79
source_HGMD-PUBLIC      20164
source_ESP      20141103
source_ClinVar  201701
source_dbSNP    149
source_1000genomes      phase3
source_ESP      V2-SSA137
source_ExAC     0.3
regulatory      1
source_regbuild 16```

**Comment by cookersjs** [comment]
Haha well it seems the cache file never even downloaded now that I looked into that directory -- All that exists currently is the fasta file and its index file. I'll attempt to re-download the cache file and am sure things will cooperate once that is done.

Thanks for the help!

-cookersjs

**Comment by cookersjs** [comment]
As an aside, it seems the extraction process is the issue -- Within the tmp folder the file has been unzipped but not 'un-tarred'

**Comment by willmclaren** [comment]
This extraction process issue has been [fixed](https://github.com/Ensembl/ensembl-vep/commit/c1626aa7118bdd9c28399026e1fdf033038af39c) in release/88.4
