### ISSUE TITLE
VEP 95 installation issue

### ISSUE THREAD

**Issue by JanaKubikova** [Ensembl/ensembl-vep#374]
Hello, during VEP 95 installation I ran into following error. I tried searching for possible solution but nothing seemed to quite fit. Could someone suggest what to do? Thanks 

`Testing VEP installation`
`./t/AnnotationSource.t ............................... Replacement list is longer than search list at /usr/local/share/BioPerl/BioPerl-1.6.1/Bio/Range.pm line 251.`
`./t/AnnotationSource.t ............................... 1/? `
`#   Failed test 'use Bio::EnsEMBL::VEP::Parser::VCF;'`
`#   at ./t/AnnotationSource.t line 55.`
`#     Tried to use 'Bio::EnsEMBL::VEP::Parser::VCF'.`
`#     Error:  "trim_sequences" is not exported by the Bio::EnsEMBL::Variation::Utils::Sequence module`
`# Can't continue after import errors at /mnt/storage/users/kubikovj/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 69.`
`# BEGIN failed--compilation aborted at /mnt/storage/users/kubikovj/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 69.`
`# Compilation failed in require at (eval 93) line 2.`
`# 	...propagated at /usr/share/perl5/base.pm line 84.`

We use Scientific Linux release 7.1 (Nitrogen), perl v5.16.3
[VEP_install_error.log](https://github.com/Ensembl/ensembl-vep/files/2815784/VEP_install_error.log)

**Comment by aparton** [comment]
Hi,

It looks like you have a previously installed version of BioPerl on your machine, which is conflicting with the version VEP has downloaded.

To fix this, please:
1) Download BioPerl manually and add it to your $PERL5LIB variable:
2) Just in case, update your Module::Build package.

E.g.

wget https://cpan.metacpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.6.924.tar.gz 
tar zxvf BioPerl-1.6.924.tar.gz
PERL5LIB=${PERL5LIB}:${LOCATION}/bioperl-1.6.924
cpanm Module::Build

Kind Regards,
Andrew

**Comment by JanaKubikova** [comment]
Thank you very much for the advice. Our IT, though, still had some hard time making it work - mainly due to various Perl moduls either missing or already installed. At the end it was necessary to delete variable PERL5LIB before VEP installation.

**Comment by aparton** [comment]
Hi,

Thanks for the feedback - we'll investigate this behaviour - and I'm glad you were able to resolve this issue.

If you have any other queries, please feel free to open a new issue.

Kind Regards,
Andrew
