### ISSUE TITLE
 "ERROR: Can't use --most_severe and --symbol together"  when not using "--symbol"

### ISSUE THREAD

**Issue by MurphyDavid** [Ensembl/ensembl-vep#378]
using version 95 the program gives an  unhelpful error:

```
/ensembl_vep_95/ensembl-vep/vep  -i  chr1.norm.vcf    -o  chr1.norm.vep.vcf  --species "homo_sapiens"  --assembly  GRCh38 --compress_output gzip --vcf --most_severe

-------------------- EXCEPTION --------------------
MSG: ERROR: Can't use --most_severe and --symbol together
```

From looking at config.pm this appears to be due to the  --vcf  option setting the symbol  flag. 

```
    flags => ['vcf'],
    set   => {
      output_format => 'vcf',
      symbol => 1,
      biotype => 1,
      numbers => 1
    }
  },
```
  
It's not noted in the documentation that --vcf sets the "--symbol" flag

https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html

As such this error was not clearly understandable without reviewing the source code. 

I believe either the documentation should note that --most_severe and --vcf are incompatible, or that --vcf sets the symbol flag or the error should be changed. 

Related Query: It's not obvious to me why --most_severe must be incompatible with vcf output as my goal is to generate a VCF with a single CSQ for the most severe consequence.  VCF format doesn't seem to require the gene symbol in the CSQ as a hard requirement. Why must they be incompatible?

**Comment by aparton** [comment]
Hi David,

Thank you for bringing this issue to our attention. As you have worked out, VEP 'switches on' the symbol and numbers flags internally when creating VCF output, leading to this clash. We’ll update our documentation and the warning to improve how this incompatibility is communicated.

Regarding why this is done in the first place, our VCF creation procedures require the symbol as default to minimise confusion where multiple genes overlap in the same location.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi David,

Additionally, you should be able to produce your VCF with a single consequence using the ‘pick’ and ‘pick_order’ commands as described here: https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick_eg & https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#filt

Kind Regards,
Andrew

**Comment by MurphyDavid** [comment]
Thanks for that, pick and pick_order works for what I need.

**Comment by aparton** [comment]
Great! Glad to hear it. I'll close this issue now, please feel free to open a new one if you have any other issues.

Kind Regards,
Andrew
