### ISSUE TITLE
Problems with mitochondrial variants annotation 

### ISSUE THREAD

**Issue by xuanzhu1213** [Ensembl/ensembl-vep#38]
Hi
I use the latest version(v88) to annotate mitochondrial variants, and find a question. When I use 'chrM', it does not work, says 'WARNING: Chromosome chrM not found in annotation sources or synonyms on line 1' , then I changed to 'M', so it works. Does it is a mistake?

**Comment by willmclaren** [comment]
Which species are you using, and which cache (version, assembly, ensembl/refseq/merged)?

I don't see this issue using homo_sapiens_vep_88_GRCh38.tar.gz; VEP works OK whether I use chrM, M, chrMT or MT

**Comment by xuanzhu1213** [comment]
Yes,  it works OK when use homo_sapiens_vep_88_GRCh38.tar.gz. But when I change the cache file to GRCh37,it has the problem.

**Comment by willmclaren** [comment]
Yes, that is the solution - I will check our pipeline to understand why this line isn't there in the first place.
