### ISSUE TITLE
Docker with protists.ensembl.org

### ISSUE THREAD

**Issue by petercombs** [Ensembl/ensembl-vep#380]
I'm trying to use VEP to call variant effects in _Dictyostelium discoideum_, which is one of the organisms in protists.ensembl.org rather than the core ensembl.org. I've downloaded the VEP cache for Dicty and put it in $HOME/vep_data, but when I try to run VEP from the docker image, I get: 

    $ docker run -t -i ensemblorg/ensembl-vep ./vep -i autosome_snps_translated.vcf --species "dictyostelium_discoideum" -o vep_test --everything --cache $HOME/vep_data

    -------------------- WARNING ----------------------
    MSG: dictyostelium_discoideum is not a valid species name (check DB and API version)
    FILE: Bio/EnsEMBL/Registry.pm LINE: 1334
    CALLED BY: Bio/EnsEMBL/Registry.pm  LINE: 1109
    Date (localtime)    = Tue Feb  5 22:37:27 2019
    Ensembl API version = 95
    ---------------------------------------------------

    -------------------- EXCEPTION --------------------
    MSG: Can not find internal name for species 'dictyostelium_discoideum'
    STACK Bio::EnsEMBL::Registry::get_adaptor /opt/vep/src/ensembl- vep/Bio/EnsEMBL/Registry.pm:1111
    STACK Bio::EnsEMBL::VEP::BaseVEP::get_adaptor /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:308
    STACK Bio::EnsEMBL::VEP::BaseVEP::get_database_assembly /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:419
    STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:123
    STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:118
    STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
    STACK toplevel ./vep:225
    Date (localtime)    = Tue Feb  5 22:37:27 2019
    Ensembl API version = 95
    ---------------------------------------------------

Any advice you can give on how to get this working would be great! Thanks!

**Comment by ens-lgil** [comment]
Dear @petercombs,

As you are using a non-vertebrate species, you need to add a couple of extra flags:
[--genomes](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_genomes): to point to the protist public database server
[--cache_version](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_cache_version) 42: to poin to the protist cache: the versions differ between the vertebrate (95) and non-vertebrate (42) species.

Best regards,
Laurent
