### ISSUE TITLE
VEP - Release 95 - Installation Issues - tried on Perl versions 5.24.4, 5.26, 5.28

### ISSUE THREAD

**Issue by selvit** [Ensembl/ensembl-vep#381]
Hi,

**System Info:**

CentOS Linux release 7.5.1804 (Core)

ensembl-vep installed from git - Release 95

**VEP Installation tried on:**

Perl Versions: 5.24.4, 5.26, 5.28

BioPerl: installed manually and path added to $PERL5LIB variable in the ~/.bashrc script

HTSLIB: installed manually and path added to $PERL5LIB variable in the ~/.bashrc script

Result: FAIL

I have been trying to install ensembl-vep for the past week on CentOS Linux release 7.5.1804. Not all installation tests pass successfully on the Perl versions 5.28, 5.26 and 5.24.4. I manually installed BioPerl-1.6.924 and have set the path in the bashrc script. Also, tried installing VEP using the --NO_HTSLIB and --NO_BIOPERL options. 

Please find the output below from running the perl INSTALL.pl script with the BioPerl-1.6.924 manual installation on perl v24.4.

Thank you very much for any suggestions on how to fix this issue.

############OUTPUT############
# VEP installation perl script, INSTALL.pl, OUTPUT - perl 24.4

$ perl INSTALL.pl

Hello! This installer is configured to install v95 of the Ensembl API for use by the VEP.
It will not affect any existing installations of the Ensembl API that you may have.

It will also download and install cache files from Ensembl's FTP server.

Checking for installed versions of the Ensembl API...done

Setting up directories
 - fetching BioPerl
 - unpacking ./Bio/tmp/release-1-6-924.zip
 - moving files
Attempting to install Bio::DB::HTS and htslib.

>>> If this fails, try re-running with --NO_HTSLIB

 - checking out HTSLib
Cloning into 'htslib'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 10466 (delta 9), reused 25 (delta 9), pack-reused 10439
Receiving objects: 100% (10466/10466), 7.90 MiB | 8.07 MiB/s, done.
Resolving deltas: 100% (7297/7297), done.
Note: checking out '6bed35a3eaefa3baa2c7e0166ceba442212f166b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Checking out files: 100% (168/168), done.
 - building HTSLIB in ./htslib
In /data/programs/ensembl-vep/htslib
echo '/* Empty config.h generated by Makefile */' > config.h
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o kfunc.o kfunc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o knetfile.o knetfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o kstring.o kstring.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o bgzf.o bgzf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o faidx.o faidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hfile.o hfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.3.2-dirty"' > version.h
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hts.o hts.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o md5.o md5.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o regidx.o regidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o sam.o sam.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o synced_bcf_reader.o synced_bcf_reader.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcf_sweep.o vcf_sweep.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o tbx.o tbx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcf.o vcf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcfutils.o vcfutils.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_decode.o cram/cram_decode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_encode.o cram/cram_encode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_external.o cram/cram_external.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_index.o cram/cram_index.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_io.o cram/cram_io.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_samtools.o cram/cram_samtools.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_stats.o cram/cram_stats.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/files.o cram/files.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/mFILE.o cram/mFILE.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/open_trace_file.o cram/open_trace_file.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/pooled_alloc.o cram/pooled_alloc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/rANS_static.o cram/rANS_static.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/sam_header.o cram/sam_header.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/string_alloc.o cram/string_alloc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/thread_pool.o cram/thread_pool.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/vlen.o cram/vlen.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/zfio.o cram/zfio.c
ar -rc libhts.a kfunc.o knetfile.o kstring.o bgzf.o faidx.o hfile.o hfile_net.o hts.o md5.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o cram/thread_pool.o cram/vlen.o cram/zfio.o
ranlib libhts.a
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o kfunc.pico kfunc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o knetfile.pico knetfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o kstring.pico kstring.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o bgzf.pico bgzf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o faidx.pico faidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o hfile.pico hfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o hfile_net.pico hfile_net.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o hts.pico hts.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o md5.pico md5.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o regidx.pico regidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o sam.pico sam.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o synced_bcf_reader.pico synced_bcf_reader.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o vcf_sweep.pico vcf_sweep.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o tbx.pico tbx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o vcf.pico vcf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o vcfutils.pico vcfutils.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_codecs.pico cram/cram_codecs.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_decode.pico cram/cram_decode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_encode.pico cram/cram_encode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_external.pico cram/cram_external.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_index.pico cram/cram_index.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_io.pico cram/cram_io.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_samtools.pico cram/cram_samtools.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_stats.pico cram/cram_stats.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/files.pico cram/files.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/mFILE.pico cram/mFILE.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/open_trace_file.pico cram/open_trace_file.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/pooled_alloc.pico cram/pooled_alloc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/rANS_static.pico cram/rANS_static.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/sam_header.pico cram/sam_header.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/string_alloc.pico cram/string_alloc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/thread_pool.pico cram/thread_pool.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/vlen.pico cram/vlen.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/zfio.pico cram/zfio.c
gcc -shared -Wl,-soname,libhts.so.1 -pthread  -o libhts.so kfunc.pico knetfile.pico kstring.pico bgzf.pico faidx.pico hfile.pico hfile_net.pico hts.pico md5.pico regidx.pico sam.pico synced_bcf_reader.pico vcf_sweep.pico tbx.pico vcf.pico vcfutils.pico cram/cram_codecs.pico cram/cram_decode.pico cram/cram_encode.pico cram/cram_external.pico cram/cram_index.pico cram/cram_io.pico cram/cram_samtools.pico cram/cram_stats.pico cram/files.pico cram/mFILE.pico cram/open_trace_file.pico cram/pooled_alloc.pico cram/rANS_static.pico cram/sam_header.pico cram/string_alloc.pico cram/thread_pool.pico cram/vlen.pico cram/zfio.pico -lz -lm
ln -sf libhts.so libhts.so.1
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o bgzip.o bgzip.c
gcc -pthread  -o bgzip bgzip.o libhts.a -lz
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o htsfile.o htsfile.c
gcc -pthread  -o htsfile htsfile.o libhts.a -lz
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o tabix.o tabix.c
gcc -pthread  -o tabix tabix.o libhts.a -lz
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/fieldarith.o test/fieldarith.c
gcc -pthread  -o test/fieldarith test/fieldarith.o libhts.a -lz
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/hfile.o test/hfile.c
gcc -pthread  -o test/hfile test/hfile.o libhts.a -lz
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/sam.o test/sam.c
gcc -pthread  -o test/sam test/sam.o libhts.a -lz
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-regidx.o test/test-regidx.c
gcc -pthread  -o test/test-regidx test/test-regidx.o libhts.a -lz
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test_view.o test/test_view.c
gcc -pthread  -o test/test_view test/test_view.o libhts.a -lz
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-vcf-api.o test/test-vcf-api.c
gcc -pthread  -o test/test-vcf-api test/test-vcf-api.o libhts.a -lz
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-vcf-sweep.o test/test-vcf-sweep.c
gcc -pthread  -o test/test-vcf-sweep test/test-vcf-sweep.o libhts.a -lz
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.9 - moving files to ./biodbhts
 - making Bio::DB:HTS
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.9'
Building Bio-DB-HTS
gcc -I/data/programs/ensembl-vep/htslib/htslib -I/cm/shared/apps/perl/5.24.4/lib/5.24.4/x86_64-linux/CORE -DVERSION="2.9" -DXS_VERSION="2.9" -fPIC -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wno-unused-result -c -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -o lib/Bio/DB/HTS.o lib/Bio/DB/HTS.c
ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Bio/DB/HTS/HTS.bs')
gcc -shared -O2 -L/usr/local/lib -fstack-protector-strong -o blib/arch/auto/Bio/DB/HTS/HTS.so lib/Bio/DB/HTS.o -L/data/programs/ensembl-vep/htslib -Wl,-rpath,/data/programs/ensembl-vep/htslib -lhts -lpthread -lz
gcc -I/data/programs/ensembl-vep/htslib/htslib -I/cm/shared/apps/perl/5.24.4/lib/5.24.4/x86_64-linux/CORE -DVERSION="2.9" -DXS_VERSION="2.9" -fPIC -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wno-unused-result -c -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -o lib/Bio/DB/HTS/Faidx.o lib/Bio/DB/HTS/Faidx.c
ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Bio/DB/HTS/Faidx/Faidx.bs')
gcc -shared -O2 -L/usr/local/lib -fstack-protector-strong -o blib/arch/auto/Bio/DB/HTS/Faidx/Faidx.so lib/Bio/DB/HTS/Faidx.o -L/data/programs/ensembl-vep/htslib -Wl,-rpath,/data/programs/ensembl-vep/htslib -lhts -lpthread -lz

Downloading required Ensembl API files
 - fetching ensembl
 - unpacking ./Bio/tmp/ensembl.zip
 - moving files
 - getting version information
 - fetching ensembl-variation
 - unpacking ./Bio/tmp/ensembl-variation.zip
 - moving files
 - getting version information
 - fetching ensembl-funcgen
 - unpacking ./Bio/tmp/ensembl-funcgen.zip
 - moving files
 - getting version information
 - fetching ensembl-io
 - unpacking ./Bio/tmp/ensembl-io.zip
 - moving files
 - getting version information

Testing VEP installation
./t/AnnotationSource_File_VCF.t ...................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_VCF.t ...................... ok
./t/OutputFactory_VEP_output.t ....................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_VEP_output.t ....................... 1/? [fai_load] build FASTA index.
./t/OutputFactory_VEP_output.t ....................... ok
./t/AnnotationSource_Database_RegFeat.t .............. Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_RegFeat.t .............. ok
./t/FilterSet.t ...................................... ok
./t/Parser_VEP_input.t ............................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Parser_VEP_input.t ............................... ok
./t/AnnotationSource_Cache_VariationTabix.t .......... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_VariationTabix.t .......... ok
./t/version.t ........................................ ok
./t/Parser_ID.t ...................................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Parser_ID.t ...................................... ok
./t/AnnotationSource_Database_Variation.t ............ Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_Variation.t ............ ok
./t/Config.t ......................................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Config.t ......................................... ok
./t/Parser_HGVS.t .................................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Parser_HGVS.t .................................... ok
./t/CacheDir.t ....................................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/CacheDir.t ....................................... ok
./t/AnnotationSource_Cache_RegFeat.t ................. Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_RegFeat.t ................. ok
./t/OutputFactory.t .................................. Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory.t .................................. 61/? [fai_load] build FASTA index.
./t/OutputFactory.t .................................. ok
./t/OutputFactory_JSON.t ............................. Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_JSON.t ............................. ok
./t/bam_edit.t ....................................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/bam_edit.t ....................................... ok
./t/AnnotationSource_Cache.t ......................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache.t ......................... ok
./t/AnnotationSource.t ............................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource.t ............................... ok
./t/AnnotationSource_File_BED.t ...................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_BED.t ...................... ok
./t/VariantRecoder.t ................................. Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/VariantRecoder.t ................................. ok
./t/InputBuffer.t .................................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/InputBuffer.t .................................... ok
./t/AnnotationSource_File_GFF.t ...................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_GFF.t ...................... 1/?
#   Failed test 'use Bio::EnsEMBL::VEP::AnnotationSource::File::GFF;'
#   at ./t/AnnotationSource_File_GFF.t line 41.
#     Tried to use 'Bio::EnsEMBL::VEP::AnnotationSource::File::GFF'.
#     Error:  Attempt to reload Bio/EnsEMBL/VEP/AnnotationSource/File/GFF.pm aborted.
# Compilation failed in require at ./t/AnnotationSource_File_GFF.t line 41.
# BEGIN failed--compilation aborted at ./t/AnnotationSource_File_GFF.t line 41.
Can't locate object method "new" via package "Bio::EnsEMBL::VEP::AnnotationSource::File::GFF" at ./t/AnnotationSource_File_GFF.t line 51, <__ANONIO__> line 9.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 25 just after 4.
./t/AnnotationSource_File_GFF.t ...................... Dubious, test returned 25 (wstat 6400, 0x1900)
Failed 1/4 subtests
./t/Utils.t .......................................... ok
./t/AnnotationSourceAdaptor.t ........................ Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSourceAdaptor.t ........................ ok
./t/TranscriptTree.t ................................. Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/TranscriptTree.t ................................. ok
./t/Stats.t .......................................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Stats.t .......................................... ok
./t/AnnotationSource_Database_StructuralVariation.t .. Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_StructuralVariation.t .. ok
./t/AnnotationSource_Database_Transcript.t ........... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_Transcript.t ........... ok
./t/AnnotationSource_Cache_Transcript.t .............. Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_Transcript.t .............. ok
./t/AnnotationSource_File.t .......................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File.t .......................... 1/? Can't locate object method "new" via package "Bio::EnsEMBL::VEP::AnnotationSource::File::GFF" at /data/programs/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 167.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 17.
./t/AnnotationSource_File.t .......................... Dubious, test returned 2 (wstat 512, 0x200)
All 17 subtests passed
./t/OutputFactory_Tab.t .............................. Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_Tab.t .............................. ok
./t/Parser_VCF.t ..................................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Parser_VCF.t ..................................... ok
./t/Parser.t ......................................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Parser.t ......................................... ok
./t/OutputFactory_VCF.t .............................. Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_VCF.t .............................. ok
./t/Runner.t ......................................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Runner.t ......................................... 50/? Can't locate object method "new" via package "Bio::EnsEMBL::VEP::AnnotationSource::File::GFF" at /data/programs/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 167.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 73.
./t/Runner.t ......................................... Dubious, test returned 255 (wstat 65280, 0xff00)
All 73 subtests passed
./t/BaseVEP.t ........................................ Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/BaseVEP.t ........................................ 1/? [fai_load] build FASTA index.
./t/BaseVEP.t ........................................ ok
./t/Parser_Region.t .................................. Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Parser_Region.t .................................. ok
./t/AnnotationSource_File_GTF.t ...................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_GTF.t ...................... 1/?
#   Failed test 'use Bio::EnsEMBL::VEP::AnnotationSource::File::GTF;'
#   at ./t/AnnotationSource_File_GTF.t line 41.
#     Tried to use 'Bio::EnsEMBL::VEP::AnnotationSource::File::GTF'.
#     Error:  Attempt to reload Bio/EnsEMBL/IO/Parser/GXF.pm aborted.
# Compilation failed in require at /cm/shared/apps/perl/5.24.4/lib/5.24.4/base.pm line 138.
#     ...propagated at /cm/shared/apps/perl/5.24.4/lib/5.24.4/base.pm line 160.
# BEGIN failed--compilation aborted at /data/programs/ensembl-vep/Bio/EnsEMBL/IO/Parser/GTF.pm line 30.
# Compilation failed in require at /data/programs/ensembl-vep/Bio/EnsEMBL/IO/Parser/GTFTabix.pm line 40.
# BEGIN failed--compilation aborted at /data/programs/ensembl-vep/Bio/EnsEMBL/IO/Parser/GTFTabix.pm line 40.
# Compilation failed in require at /data/programs/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/GTF.pm line 67.
# BEGIN failed--compilation aborted at /data/programs/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/GTF.pm line 67.
# Compilation failed in require at ./t/AnnotationSource_File_GTF.t line 41.
# BEGIN failed--compilation aborted at ./t/AnnotationSource_File_GTF.t line 41.
Can't locate object method "new" via package "Bio::EnsEMBL::VEP::AnnotationSource::File::GTF" at ./t/AnnotationSource_File_GTF.t line 51, <__ANONIO__> line 9.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 25 just after 4.
./t/AnnotationSource_File_GTF.t ...................... Dubious, test returned 25 (wstat 6400, 0x1900)
Failed 1/4 subtests
./t/AnnotationSource_Cache_Variation.t ............... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_Variation.t ............... ok
./t/AnnotationSource_File_BigWig.t ................... Possible precedence issue with control flow operator at /data/programs/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_BigWig.t ................... ok

Test Summary Report
-------------------
./t/AnnotationSource_File_GFF.t                    (Wstat: 6400 Tests: 4 Failed: 1)
  Failed test:  2
  Non-zero exit status: 25
  Parse errors: No plan found in TAP output
./t/AnnotationSource_File.t                        (Wstat: 512 Tests: 17 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
./t/Runner.t                                       (Wstat: 65280 Tests: 73 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
./t/AnnotationSource_File_GTF.t                    (Wstat: 6400 Tests: 4 Failed: 1)
  Failed test:  2
  Non-zero exit status: 25
  Parse errors: No plan found in TAP output
Files=40, Tests=1601, 158 wallclock secs ( 0.33 usr  0.07 sys + 140.95 cusr  5.66 csys = 147.01 CPU)
Result: FAIL
Failed 4/40 test programs. 2/1601 subtests failed.

#########################################

**Comment by aparton** [comment]
Hi,

Thank you for your query, your tests seem to be unable to find the ‘new' method in modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm

To resolve this issue, could you please try:

Updating Module::Build using cpanm
Re-cloning the ensembl-vep directory with git to ensure that all files are correctly updated to version 95 

E.g.

cpanm Module::Build
rm -rf ensembl-vep
git clone https://github.com/ensembl/ensembl-vep
cd tnsembl-vep
perl INSTALL.PL

Kind Regards,
Andrew

**Comment by aparton** [comment]
Closing this ticket - if you have any more questions please feel free to reopen it.

Kind Regards,
Andrew
