### ISSUE TITLE
Undefined subroutine fd_retrieve

### ISSUE THREAD

**Issue by JanaKubikova** [Ensembl/ensembl-vep#383]
I am using VEP 95. When I run:
`./vep --cache --dir_cache /mnt/storage/users/kubikovj/.vep/ --input_file /home/kubikovj/mutSig/1_RawVariants.I2.vcf.gz --output_file /home/kubikovj/mutSig/1_RawVariants.I2.VEPann.vcf.gz --format vcf --vcf --symbol --terms SO --hgvs  --force_overwrite`

I get the message:
`Undefined subroutine &Bio::EnsEMBL::VEP::AnnotationSource::Cache::BaseSerialized::fd_retrieve called at /mnt/storage/users/kubikovj/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseSerialized.pm line 141, <$fh> line 3606.`

There seemed to be a problem with unpacking the .vcf.gz file. I tried unpacking the file, packing it with gzip, and bgzip with no success. Can you suggest what to do?

**Comment by helensch** [comment]
Hi

The error message is reporting that it cannot find the fd_retrieve subroutine in the Storable perl module. The Storable module is a core perl module and should be part of the standard perl installation. It is used to read the cache files.

Please could you check that Storable module can be found.

To check the installation path use
perldoc -l Storable

To check that the module can be found and the version installed use
perl -MStorable -e 'print "$Storable::VERSION\n"'

To check that it is not a problem with the compressed vcf, please could you try  running the same command with a small uncompressed VCF file

Regards
Helen

**Comment by JanaKubikova** [comment]
Hi Helen, thank you for helping me. 
I tried what you suggested:
```
[kubikovj@cheetah ~] $ perldoc -l Storable
/usr/local/share/ensembl/ensembl-funcgen/modules/Bio/EnsEMBL/Funcgen/Storable.pm
[kubikovj@cheetah ~] $ perl -MStorable -e 'print "$Storable::VERSION\n"'

[kubikovj@cheetah ~] $
```
The uncompressed .vcf reports the same error as the compressed one.
```
Undefined subroutine &Bio::EnsEMBL::VEP::AnnotationSource::Cache::BaseSerialized::fd_retrieve called at /mnt/storage/users/kubikovj/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseSerialized.pm line 141, <__ANONIO__> line 3425.
```

**Comment by helensch** [comment]
Hi
 
Thanks for the information. The core perl module Storable cannot be found (https://perldoc.perl.org/Storable.html). 

Which version of perl and operating system are you using?

Please could you check that the Storable module has been installed with your version of perl and is in your PERL5LIB path

Regards
Helen

**Comment by JanaKubikova** [comment]
**SOLVED** 
This is what IT wrote to me:
Command "perldoc -l Storable" should point to Storable.pm 
* either in "/usr/lib64/perl5/vendor_perl" 
* or updated in "/usr/local/lib64/perl5/"

Package in "/usr/local/share/ensembl/ensembl-funcgen/modules/Bio/EnsEMBL/Funcgen/Storable.pm" is wrong. I changed system variable PERL5DOC that manages order in which the packages are looked up. After new login it should begin in directory:
```
{{echo $PERL5LIB }}
/usr/local/lib64/perl5:/usr/lib64/perl5:/usr/lib64/perl5/vendor_perl .....
```
After that:
```
perldoc -l Storable
/usr/local/lib64/perl5/Storable.pm
perl -MStorable -e 'print "$Storable::VERSION\n"'
3.11
```
Best regards and thank you Helen for helping me. VEP is a great tool!

**Comment by helensch** [comment]
Hi
I am pleased that you were able to resolve this issue and access the core Storable.pm.

Thank you for your feedback and using VEP.

If you have any other queries, please feel free to open a new issue.

Regards
Helen
