### ISSUE TITLE
Commas in annotation fields (TREMBL)

### ISSUE THREAD

**Issue by loreseeker** [Ensembl/ensembl-vep#39]
Hello,

just a quick note. I was parsing a VEP annotated VCF today and ran into a comma in the TREMBL field. I saw that the VEP documentation states that commas are replaced with ampersands to preserve VCF format, so I thought I'd point this out.

For example, for this variant:
1	1139603	rs200158513	C	T	100	PASS

I have the following output for the TREMBL field: J3KT02,A8WFP4  for one of the transcripts.

Annotation was done with ensembl-vep (pre-release), here's additional info from the VCF header:
##VEP="v87" time="2017-03-10 13:08:10" cache="/opt/ensembl-vep/cache/homo_sapiens/87_GRCh37" ensembl=87.f547798 ensembl-io=87.48cb128 ensembl-funcgen=87.0577dd0 ensembl-variation=87.661e72c 1000genomes="phase3" COSMIC="78" ClinVar="201610" ESP="20141103" ExAC="0.3" HGMD-PUBLIC="20162" assembly="GRCh37.p13" dbSNP="147" gencode="GENCODE 19" genebuild="2011-04" polyphen="2.2.2" regbuild="1.0" sift="sift5.2.2"

The dbNSFP plugin also produced some whitespaces and commas, posting examples there.

I'm still rather new at working with VCFs and I saw in the VCF spec that commas are allowed in the INFO field as separators for lists (although I don't think this works for the CSQ, because transcripts entries are comma separated?), so please let me know if this is expected behaviour. Parsing this VCF with htsjdk failed. 

Thank you for your time.

**Comment by willmclaren** [comment]
Commas in the VCF output were fixed by [this commit](https://github.com/Ensembl/ensembl-vep/commit/a331fa147dcde30460dd8c73d721dc6bab5230b6)

I'll look into the issue with whitespace.

**Comment by loreseeker** [comment]
Thank you - sorry for the trouble and opening the issue unnecessarily.
