### ISSUE TITLE
Filter allele frequencies from Mouse Genome Project

### ISSUE THREAD

**Issue by PedroBarbosa** [Ensembl/ensembl-vep#395]
Hello,

Is there any way to add allele frequencies when running local VEP against the mus musculus cache?

Thanks,
Pedro Barbosa

**Comment by ima23** [comment]
Hi @PedroBarbosa,

Thanks for the question. Unfortunately the cache does not contain the allele frequencies.  You can extract the AC and AN for MGP using custom annotation, however the specific AF is not precomputed.
```gvfF=ftp://ftp.ensembl.org/pub/data_files/mus_musculus/GRCm38/variation_genotype/mgp.v3.snps.sorted.rsIDdbSNPv137.vcf.gz
vep [...] -custom $gvfF,mgp,vcf,,AC,AN```

**Comment by PedroBarbosa** [comment]
Thanks for the answer @ima23 

I'll take a look.
Best,
Pedro
