### ISSUE TITLE
Failed last resort of using HTTP::Tiny to download https://api.github.com/repos/Ensembl/ensembl-vep

### ISSUE THREAD

**Issue by 41526** [Ensembl/ensembl-vep#396]
I have a problem when I use the installer
![Uploading TIM图片20190218111734.png…]()
I don't know how to solve it.

**Comment by 41526** [comment]
[wanly2018@b2 ensembl-vep-release-95]$ perl INSTALL.pl
curl failed (000), trying to fetch using LWP::Simple
LWP::Simple failed (500), trying to fetch using HTTP::Tiny
ERROR: Failed last resort of using HTTP::Tiny to download https://api.github.com/repos/Ensembl/ensembl-vep

**Comment by aparton** [comment]
Hi Ivan,

Looks like your installer is having issues connecting to GitHub to perform a version check. 

Curl error code 000 suggests that the connection failed - is the machine you are attempting to install on connected to the internet? If so, could you please try and run the curl command manually with:
curl -0 https://api.github.com/repos/Ensembl/ensembl-vep

Also, could you please tell me what OS you're using?

Kind Regards,
Andrew

**Comment by 41526** [comment]
Hi Andrew
Thank you for trying to solve the problem I encountered.
I just try the code 
`curl -0 https://api.github.com/repos/Ensembl/ensembl-vep` and it didn't work either.
The error message is 
**curl: (6) Couldn't resolve host 'api.github.com'** 
The machine is Linux Server, and there is no doubt that this machine can connect to the Internet.
Thanks
Ivan

**Comment by 41526** [comment]
Is there any way to bypass the installer to install the required components?

**Comment by 41526** [comment]
I can get connect to the website now , however , another trouble comes to me :-( .

**Comment by 41526** [comment]
In file included from lib/Bio/DB/HTS.xs:49:
/pub5/xiaoyun/BioSoftware/ensembl-vep-release-95/htslib/htslib/khash.h:131:28: error: htslib/kstring.h: No such file or directory
cc1: warning: unrecognized command line option "-Wno-unused-result"
error building lib/Bio/DB/HTS.o from 'lib/Bio/DB/HTS.c' at /pub5/xiaoyun/BioSoftware/perl-5.22.0/lib/site_perl/5.22.0/ExtUtils/CBuilder/Base.pm line 174.
ERROR: Shared Bio::DB:HTS library not found

**Comment by aparton** [comment]
Hi Ivan,

Glad to hear we’re making progress! To attempt to solve this next problem, could you please try:

1) Downloading 1.6.924 of BioPerl, adding it to the PERL5LIB variable by doing something like:

wget https://cpan.metacpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.6.924.tar.gz 
tar zxvf BioPerl-1.6.924.tar.gz
PERL5LIB=${PERL5LIB}:${HOME}/BioPerl-1.6.924 ###Or whatever your path is

2) Updating the Module::Build library:

Cpanm Module::Build

These steps should resolve your issue. Failing that, could you please send me the full output of your VEP install, and I can take a closer look?

Kind Regards,
Andrew

**Comment by aparton** [comment]
Regarding bypassing the installer, it would be possible to download all of the ensembl-api components manually (https://www.ensembl.org/info/docs/api/api_installation.html), and then installing BioPerl, HTSLIB and Bio::DB::HTS manually as well. However, we do recommend using the installer to keep track of cache files, fasta files and plugins.

Kind Regards,
Andrew

**Comment by 41526** [comment]
Thanks a lot. I'm working on it. I'm sorry to reply you so late.

**Comment by 41526** [comment]
I have installed VEP by conda, thanks anyways.
