### ISSUE TITLE
RefSeq Cannonical Transcripts not being annotated with cache homo_sampiens_merge/95_GRCh38 cache files

### ISSUE THREAD

**Issue by thomasperson** [Ensembl/ensembl-vep#397]
Downloaded and installed latest VEP and files. Everything seems fine except  ran this command 
`vep -i toy.vcf --everything --cache --offline --vcf --fasta h38.fa.gz --merged -o toy.VEP95.vcf --use_given_ref --dir_cache ./CACHEDIR/ --force_overwrite --fork 4`
accross many genes and chromosomes.  No cannonical transcript flags seem to be set for any of the RefSeq Transcripts.  Here's example files and output.

[toy.VEP95.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/2876027/toy.VEP95.vcf.gz)
[toy.VEP95.vcf.tsv.zip](https://github.com/Ensembl/ensembl-vep/files/2876038/toy.VEP95.vcf.tsv.zip)
[toy.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/2876039/toy.vcf.gz)

Thanks!

**Comment by aparton** [comment]
Hi Thomas,

Thank you for bringing this issue to our attention. We are currently updating how we define the canonical transcript, and we expect them to return for version 96, which is currently scheduled for release at the end of March/start of April.

In the meantime, RefSeq canonical transcripts are included within our 94 cache, which you can download using the installer with the —CACHE_VERSION flag: https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html

Kind Regards,
Andrew

**Comment by thomasperson** [comment]
Thanks Andrew!  

I have everything in v92, so will just wait till v96 to update.

Cheers,

Nate
