### ISSUE TITLE
VEP - Release 95 - Installation Issues - perl (v5.22.0)

### ISSUE THREAD

**Issue by 41526** [Ensembl/ensembl-vep#398]
In file included from lib/Bio/DB/HTS.xs:49:
/pub5/xiaoyun/BioSoftware/ensembl-vep-release-95/htslib/htslib/khash.h:131:28: error: htslib/kstring.h: No such file or directory
cc1: warning: unrecognized command line option "-Wno-unused-result"
error building lib/Bio/DB/HTS.o from 'lib/Bio/DB/HTS.c' at /pub5/xiaoyun/BioSoftware/perl-5.22.0/lib/site_perl/5.22.0/ExtUtils/CBuilder/Base.pm line 174.
ERROR: Shared Bio::DB:HTS library not found

**Comment by aparton** [comment]
Closing this ticket as we're dealing with the issue in https://github.com/Ensembl/ensembl-vep/issues/396
