### ISSUE TITLE
GeneSplicer Plugin not working

### ISSUE THREAD

**Issue by stefandiederich** [Ensembl/ensembl-vep#40]
Hi, 

I tried to use the GeneSplicer plugin with VEP. First I installed GeneSplicer and did a testrun with its testdata, and it worked. 
After runing VEP with the following command I do not get any Annotaion in the GeneSplicer column.

`vep.pl --offline --dir '/media/Berechnungen/AnnotationDBs/vep' --fasta '/media/Berechnungen/Referenzgenom/HG19/HG19.karyo.fasta' --assembly GRCh37 -i '/media/Ergebnisse/xxxx-15_Exom_NB501654_0006/xxxx-15.vcf' -o '/media/Ergebnisse/xxxx-15_Exom_NB501654_0006/xxxx-15.annot_neu.vcf'  --plugin GeneSplicer,/BioinfSoftware,/media/Berechnungen/AnnotationDBs/GeneSplicer/human,context=100,tmpdir=/media/Berechnungen/Temp --vcf --force_overwrite --fork 8`

So I ook a deeper look into the GeneSplicer.pm, and with a view `print` commands I could narrow the error down to the part where the plugin tries to extact the up and downstream sequence. A `print $ref_seq."\n";` after line 170 gives me only "N" bases + "variant" + "N" bases, like this: 

NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

Can you tell what I am doing wrong?

Thanks in advance,
Stefan Diederich

**Comment by willmclaren** [comment]
The "N" sequences suggest that the correct sequence is not being retrieved from your FASTA file; this could be for a couple of reasons:

- the FASTA index is corrupt or incomplete. Remove the index with:
```rm /media/Berechnungen/Referenzgenom/HG19/HG19.karyo.fasta.*``` and re-run - VEP will take a while to regenerate the index, don't interrupt it!
- the FASTA file contains different chromosome names to your input that are not being resolved via a synonym lookup. You may add synonyms to `/media/Berechnungen/AnnotationDBs/vep/homo_sapiens/88_GRCh37/chr_synonyms.txt` as tab-separated pairs.

It also looks like your GeneSplicer plugin command is not quite correct; the first parameter after the plugin name should be the path to the genesplicer binary file, for me that is `/homes/wm2/.vep/plugin_data/genesplicer/bin/linux/genesplicer`; I'd expect yours to look similar.

**Comment by willmclaren** [comment]
Assumed resolved or no longer an issue - please reopen if this is not the case.
