### ISSUE TITLE
Warnings when running VEP

### ISSUE THREAD

**Issue by marc-sturm** [Ensembl/ensembl-vep#401]
Hi,

we just switched to the latest version of VEP (95.1) and noticed a lot of these warnings:
WARNING: 34109 : Use of uninitialized value $f1_end in numeric ge (>=) at /mnt/SRV018/share/opt/ensembl-vep-release-95.1/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm line 83, <__ANONIO__> line 4773467.

The used command was for example:
Command line call:
/mnt/share/opt/ensembl-vep-release-95.1/vep  -i /mnt/SRV018/tmp/23889.1.default_srv018/annotate_M1dWq3_unzipped.vcf --format vcf -o /mnt/SRV018/tmp/23889.1.default_srv018/annotate_xsjSLE.vcf --vcf --no_stats --force_overwrite --species homo_sapiens --assembly GRCh37 --fork 5 --offline --cache --dir_cache /tmp/local_ngs_data//ensembl-vep-95// --fasta /tmp/local_ngs_data//GRCh37.fa --numbers --hgvs --domains --regulatory --sift b --polyphen b --af --af_gnomad --af_esp --failed 1 --plugin CADD,/mnt/share/data//dbs/CADD/whole_genome_SNVs.tsv.gz,/mnt/share/data//dbs/CADD/InDels.tsv.gz --plugin REVEL,/mnt/share/data//dbs/REVEL/revel_all_chromosomes.tsv.gz --plugin FATHMM_MKL,/mnt/share/data//dbs/fathmm-MKL/fathmm-MKL_Current.tab.gz --plugin MaxEntScan,/mnt/share/opt/ensembl-vep-release-95.1/MaxEntScan/ --plugin GeneSplicer,/mnt/share/opt/ensembl-vep-release-95.1/GeneSplicer/sources/genesplicer,/mnt/share/opt/ensembl-vep-release-95.1/GeneSplicer/human,context=50 --plugin dbscSNV,/mnt/share/data//dbs/dbscSNV/dbscSNV1.1_GRCh37.txt.gz --custom /mnt/share/data//dbs/gnomAD/gnomAD_genome_r2.1.vcf.gz,gnomADg,vcf,exact,0,AF,Hom,Hemi --custom /mnt/share/data//dbs/RepeatMasker/RepeatMasker.bed.gz,REPEATMASKER,bed,overlap,0 --custom /mnt/share/data//dbs/ClinVar/clinvar_20190123_converted.vcf.gz,CLINVAR,vcf,exact,0,DETAILS --custom /mnt/share/data//dbs/phyloP/hg19.100way.phyloP100way.bw,PHYLOP,bigwig --custom /mnt/share/data//dbs/OMIM/omim.bed.gz,OMIM,bed,overlap,0 --custom /mnt/share/data//dbs/HGMD/HGMD_PRO_2018_4_fixed.vcf.gz,HGMD,vcf,exact,0,CLASS,MUT,GENE,PHEN --gencode_basic --fields Allele,Consequence,IMPACT,SYMBOL,Feature,Feature_type,EXON,INTRON,HGVSc,HGVSp,DOMAINS,SIFT,PolyPhen,Existing_variation,AF,gnomAD_AF,gnomAD_AFR_AF,gnomAD_AMR_AF,gnomAD_EAS_AF,gnomAD_NFE_AF,gnomAD_SAS_AF,EA_AF,AA_AF,BIOTYPE,CADD_PHRED,REVEL,FATHMM_MKL_C,FATHMM_MKL_NC,MaxEntScan_ref,MaxEntScan_alt,GeneSplicer,ada_score,rf_score,gnomADg_AF,gnomADg_Hom,gnomADg_Hemi,REPEATMASKER,CLINVAR,CLINVAR_DETAILS,PHYLOP,OMIM,HGMD,HGMD_CLASS,HGMD_MUT,HGMD_GENE,HGMD_PHEN

Is this known and is there a fix?

Thanks,
  Marc

**Comment by ens-lgil** [comment]
Dear @marc-sturm,

This is not a known issue so far.
Please, could you send me a sample input file that produces this warning so that I can take a look and try to reproduce it?

Best regards,
Laurent

**Comment by marc-sturm** [comment]
Hi Laurent,

I will try and create a minimal example VCF.

Best,
  Marc

**Comment by marc-sturm** [comment]
Hi Laurent,

Sorry for the delay. It took a while to figure out which variants cause the error.
It's the chrMT variants in this file:
[test2.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/2906079/test2.vcf.gz)



Best,
  Marc

**Comment by ens-lgil** [comment]
Dear @marc-sturm,

Many thanks for the test file. Unfortunately I can't reproduce the error. 
Do you see the warnings:
- Without the `--plugin` flags only ?
- Without the `--custom` flags only ?
I will try to investigate if this comes from the plugins

Best regards,
Laurent

**Comment by marc-sturm** [comment]
Hi Laurent,

sorry, I uploaded the wrong file.

Now I  identified a single variant that causes the error.
It's not on chrMT, but on chrY:
[test2.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/2908901/test2.vcf.gz)

This is the command line call i use:
/home/ahsturm1/ensembl-vep-release-95.1/vep -i test2.vcf --vcf --format vcf -o test2_anno.vcf --no_stats --force_overwrite --species homo_sapiens --assembly GRCh37 --fork 1 --offline --cache --dir_cache /tmp/local_ngs_data/ensembl-vep-95/ --fasta /tmp/local_ngs_data/GRCh37.fa --numbers --hgvs --domains --regulatory --sift p --polyphen p --af --af_gnomad --af_esp --failed 1 --gencode_basic

Best,
  Marc

**Comment by ens-lgil** [comment]
Hi @marc-sturm,

We investigated the issue and we found out that the VEP cache on the release 95 is missing some Motif feature annotations (regulatory data) on chromosome Y.
We are trying to fix this issue, but it might take some time.

Best regards,
Laurent

**Comment by at7** [comment]
Hi Marc,
the underlying problem for the warnings you get are MotifFeatures which failed to be mapped to the Y chromosome from the X chromosome in the pseudoautosomal regions. We won't be able to add those mappings back before release/98 because it requires code changes in the ensembl-funcgen API which will be scheduled by the funcgen team. However, we did push a fix to ignore those failed MotifFeatures and hence you won't get any more warnings about it. Please refresh the checkout of your ensembl-vep code and let us know if you have any questions or if you continue to see those warnings.
Thank you,
Anja

**Comment by marc-sturm** [comment]
Hi Anja and Laurent,

the warnings are gone with the master now.

Thanks,
  Marc
