### ISSUE TITLE
is every release of vep fit for GRCH37(hg19)

### ISSUE THREAD

**Issue by kobejamescurry** [Ensembl/ensembl-vep#407]
thanks a lot for making such a powerful software.
I am puzzled that vep version seems to stay the same with ensemble version.
but from http://grch37.ensembl.org/Help/ArchiveList  I can see GRCH37 stop at ensemble version 75, but there is no release of 75 in vep

and there is a argument of vep    **--grch37**: use GRCh37 assembly instead of GRCh38.

so whether it means each release of vep fit for both GRCH37 and GRCH38, and use for GRCH38 default, and when use for GRCH37 i need to set the argument  **--grch37**

![image](https://user-images.githubusercontent.com/46668881/54012284-96b4ed80-41b0-11e9-9db3-e7af01c1e684.png)

**Comment by ens-lgil** [comment]
Dear @kobejamescurry,

Ensembl stopped to update the geneset on GRCh37 at the release `75`.
However the variation and regulation data are updated once or twice a year on GRCh37.

The latest variation update was in release 95: [http://www.ensembl.info/2019/01/09/ensembl-95-is-out/](http://www.ensembl.info/2019/01/09/ensembl-95-is-out/).
So you can use VEP release 95 on GRCh37:
- You will have the same geneset as the release 75 of Ensembl.
- You will get more recent variant data mapped to GRCh37 (dbSNP 151, ClinVar, COSMIC, HGMD, phenotype association, ...).

Best regards,
Laurent

**Comment by kobejamescurry** [comment]
Thanks for your reply
so how I can know I use GRCH37 or GRCH38.

you know there is a procedure about install vep

git clone https://github.com/Ensembl/ensembl-vep.git
cd ensembl-vep
perl INSTALL.pl

will this install procedure determine GRCH37 or GRCH38 using,
or  I just need to use the argument --grch37: (use GRCh37 assembly instead of GRCh38.)
which means there is nothing with which release of git vep version I clone

![image](https://user-images.githubusercontent.com/46668881/54104335-6e283000-440a-11e9-9ef8-a007a0bc38ce.png)

thanks a lot

**Comment by ens-lgil** [comment]
Dear @kobejamescurry<

In the screenshot, you are refering to `variant_recoder`, which is one of the VEP tool.
To use VEP on GRCh37 you can do it in 2 different ways:
1. By using the Ensembl databases
For that, you need to use the [flags/options](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#dbopt) `--assembly` `--database` and `--port`:
```
 ./vep --input_file input.txt --output_file output.txt  --database --assembly GRCh37 --port 3337
```
2. By using the VEP cache files (no need for internet connection)
For that, you need to download and install the VEP cache. This can be done by the [VEP installer](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#installer).
Then you need to run VEP with some extra [flags/options](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#cacheopt): `--cache` and `--assembly`:
```
./vep --input_file input.txt --output_file output.txt  --cache --assembly GRCh37
```

I hope this helps.

Best regards,
Laurent

**Comment by kobejamescurry** [comment]
thanks a lot.
I use the second method before, so no matter release I checkout and then install, it contains bothe the GRCH37 and 38, and I just need to use the argument --assembly GRCh37 to determine which  version i need to use, am I right

git pull
**git checkout release/95**
perl INSTALL.pl

**Comment by ens-lgil** [comment]
Dear @kobejamescurry,

During the installation process, the prompt will ask you which cache(s) do you want to install:
```
...
247 : vicugna_pacos_vep_95_vicPac1.tar.gz
248 : vulpes_vulpes_vep_95_VulVul2.2.tar.gz
249 : xenopus_tropicalis_vep_95_JGI_4.2.tar.gz
250 : xiphophorus_couchianus_vep_95_Xiphophorus_couchianus-4.0.1.tar.gz
251 : xiphophorus_maculatus_merged_vep_95_X_maculatus-5.0-male.tar.gz
252 : xiphophorus_maculatus_refseq_vep_95_X_maculatus-5.0-male.tar.gz
253 : xiphophorus_maculatus_vep_95_X_maculatus-5.0-male.tar.gz
254 : homo_sapiens_merged_vep_95_GRCh37.tar.gz
255 : homo_sapiens_merged_vep_95_GRCh38.tar.gz
256 : homo_sapiens_refseq_vep_95_GRCh37.tar.gz
257 : homo_sapiens_refseq_vep_95_GRCh38.tar.gz
258 : homo_sapiens_vep_95_GRCh37.tar.gz
259 : homo_sapiens_vep_95_GRCh38.tar.gz
...  
```
If you want both `GRCh37` and `GRCh38` you need to type `258,259` on the prompt.
If you only want `GRCh37`, you simply need to type `258`. 

When the installation has finished, you can run VEP and use the flag `--assembly GRCh37`.

Best regards,
Laurent

**Comment by kobejamescurry** [comment]
thanks a lot
here is another question, the download stopped here for three hours, is there any suggestion.
thanks a lot

![image](https://user-images.githubusercontent.com/46668881/54410403-52809a80-4726-11e9-9cd0-65b76ffa04db.png)

**Comment by ens-lgil** [comment]
Dear @kobejamescurry,

The cache file is quite big (12Gb) so the download time might depend on your internet connection.
But 3 hours seems to be quite long. It used to take about half an hour for me to download it.

Best regards,
Laurent

**Comment by kobejamescurry** [comment]
so is there any suggestion to do it 
very much thanks

**Comment by wentgithub** [comment]
I also tried many times as the above person , the install timed out and the file still did not download completely. is there a another way to do. very urgent need. thanks a lot

**Comment by ens-lgil** [comment]
Hi,
This might be something to do with your location and/or the firewall settings of your company/lab.

You can install the cache manually:
```
cd $HOME/.vep
curl -O ftp://ftp.ensembl.org/pub/release-95/variation/indexed_vep_cache/homo_sapiens_vep_95_GRCh37.tar.gz
tar xzf homo_sapiens_vep_95_GRCh38.tar.gz
```
If you don't have the directory `$HOME/.vep` (or `~/.vep`), you need to create it before downloading the cache.

Best regards,
Laurent

**Comment by wentgithub** [comment]
thanks a lot.
so when the install process ask me to choose the species? how should I do

**Comment by kobejamescurry** [comment]
thanks a lot.
so when the install process ask me to choose the species? how should I do.
and I not install it in my home path, in a path set by argument  -c

I also used wget ftp://ftp.ensembl.org/pub/release-95/variation/indexed_vep_cache/homo_sapiens_vep_95_GRCh37.tar.gz

but stopped at 3.9G, I will try curl again

thanks a lot

**Comment by ens-lgil** [comment]
Dear @kobejamescurry,

In this case, you can skip the automated cache installation when the VEP installation process asks you to download the cache. 
For the manual installation, of course you can download it wherever you like (I was pointing you to `~/.vep` as it's the default location of the VEP cache).
However bare inb mind that you will need to specify the path to the cache directory when you use VEP, using the command [--dir_cache](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_dir_cache).

Best regards,
Laurent

**Comment by kobejamescurry** [comment]
Thanks a lot.
in fact, I am using another software MuPeXI, it needs vep to annotate variant.
in this case , still I need to install the reference, thanks a lot


[EnsemblVEP]
 # Please specify binary path to Ensembls Variant effect predictor (VEP), and the directory of containing the cache database. 
 VEP = your/path/to/ensembl-tools-release-85/scripts/variant_effect_predictor/variant_effect_predictor.pl
 VEPdir = your/path/to/ensembl-tools-release-85/scripts/variant_effect_predictor

[References]
 # Please specify the binary path to the references used (optional)
 cDNA = your/path/to/human_GRCh38/cDNA/Homo_sapiens.GRCh38.78.cdna.all.fa
 pep = your/path/to/human_GRCh38/pep/Homo_sapiens.GRCh38.78.pep.all.fa

**Comment by ens-lgil** [comment]
Dear @kobejamescurry,

Sorry, I forgot to say that you also need to download manually the FASTA file of the reference:
### GRCh37
```
curl -O ftp://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.75.dna_sm.primary_assembly.fa.gz
gzip -d Homo_sapiens.GRCh37.75.dna_sm.primary_assembly.fa.gz
bgzip Homo_sapiens.GRCh37.75.dna_sm.primary_assembly.fa
```
### GRCh38
```
curl -O ftp://ftp.ensembl.org/pub/release-95/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
gzip -d Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
bgzip Homo_sapiens.GRCh38.dna.primary_assembly.fa
```

The details about last message change few things:
1) VEP 85 has a quite different structure from the present VEP (95) as we rewrote it from scratch in VEP 88. Needless to say that the structure of the cache as changed quite a bit since then as well. Futhermore, some options have changed or have been removed with the new version, so I can't guarantee that the new VEP will work with MuPeXI. Which leads to the second point:
2) As you use VEP throught an other tool, we can't support the integration of VEP within MuPeXI. If you find some issues to make VEP works with MuPeXI, we encourage you to contact them.

Best regards,
Laurent

**Comment by kobejamescurry** [comment]
thanks a lot.
the author is  not a person kind like you, she just seems to disappear in the world.

thanks a lot

**Comment by jon4thin** [comment]
How do we check if GRCh37 was updated on a newer version of VEP? originally, in 2019, it was said that vep 95 was the last version with VEP updated, how can we  check if there were further developments?
