### ISSUE TITLE
Undefined error (haplo)

### ISSUE THREAD

**Issue by kmhernan** [Ensembl/ensembl-vep#41]
I had this issue in the pre-release and see it is still present in the 88 release. This is printed out and then the tool dies.

```
Can't call method "transcript" on an undefined value at ensembl-vep/modules/Bio/EnsEMBL/VEP/Haplo/Runner.pm line 131, <$fh> line 245947.
```

I get around it by wrapping the logic in an `eval` clause. But I don't know how it arises. I have had this in both Human and zebrafish samples with RefSeq cache v85.

**Comment by willmclaren** [comment]
I can't seem to replicate this issue, and looking at the code I can't see an obvious way that situation could arise.

Any chance you can provide a snippet of input and the command you used that will recreate this bug?

**Comment by kmhernan** [comment]
Hello again @willmclaren ... well the most I could winnow it down to is a single chromosome, but its the hap-dip public human sample CHM1. This is the command I used:

```
haplo -i CHM1.homozygous.2.vcf.gz --format vcf --species homo_sapiens \
--cache_version 85 --refseq --phased --output_file CHM1.homozygous.2.haplo.refseq.txt \
--cache --dir /path/to/cachedir --offline --fasta /path/to/Homo_sapiens.v84.GRCh37.dna.primary_assembly.fa.gz \
--haplotype_frequencies protein_haplotype_freqs_1KG_e85_GRCh37.txt.gz
```

Here is the bgzipped chr2 file of just homozygous vars.

[CHM1.homozygous.2.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/930281/CHM1.homozygous.2.vcf.gz)

**Comment by willmclaren** [comment]
Thanks for the report; now fixed by https://github.com/Ensembl/ensembl-vep/commit/c57d22979715aa076a56072cbf18d6a20e217a95
