### ISSUE TITLE
VEP is not dealing with recent chromosome notation change

### ISSUE THREAD

**Issue by PedroBarbosa** [Ensembl/ensembl-vep#410]
Hello,

I used to run VEP from VCFs with 'chr' string in the 1st column, let's say 'chr1'. Now, I'm using VCFs with just the number, but my custom plugins do not seem to work anymore (e.g. gwava, gnomAD, conservation scores, etc).

I reformatted and indexed all my files with scores accordingly, but now I don't see these annotations anymore in the output.
Please take a look at the command:

```
--custom /media/custom_data/gnomeAD/hg19/gnomAD_v2.1_justImportantFields.vcf.gz,gnomADg,vcf,exact,0,AF,AF_nfe,AF_nfe_nwe \
--custom /media/custom_data/gerp/All_hg19_RS.bw,Gerp,bigwig" \
--custom /media/custom_data/phastcons100/hg19.100way.phastCons.bw,phastCons,bigwig \
--custom /media/custom_data/phyloP100/hg19.100way.phyloP100way.bw,phyloP,bigwig
```
For the conservation scores I converted the original ones to bedgraph (bigWigToBedGraph), edited the first column and converted again to bigwig. Please find below an example of two variantes, where VEP correctly assigns GERP (via dbNSFP plugin) and gnomad exomes allele frequencies (via VEP directly), but fails to add annotations from my Gerp and gnomad custom files:

```
#CHROM  POS     REF     ALT     GERP++_RS       Gerp    gnomAD_NFE_AF   gnomADg_AF_nfe
1       116310967       T       C       3.44    .       0.2901  .
1       156096387       G       A       -6.65   .       0.04817 .
```

Just to be sure, the variant is in the gnomad vcf file:
```
tabix gnomAD_v2.1_justImportantFields.vcf.gz 1:116310967-116310967
1       116310967       rs4074536       T       C       5.19101e+06     PASS    AC=10286;AN=31316;AF=0.328458;AC_nfe_seu=31;AN_nfe_seu=106;AF_nfe_seu=0.292453;nhomalt_nfe_seu=3;AC_raw=10326;AN_raw=31416;AF_raw=0.328686;nhomalt_raw=1846;AC_afr=3847;AN_afr=8674;AF_afr=0.443509;nhomalt_afr=845;AC_amr=305;AN_amr=844;AF_amr=0.361374;nhomalt_amr=53;AC_eas=843;AN_eas=1544;AF_eas=0.545984;nhomalt_eas=232;nhomalt=1836;AC_nfe_nwe=2421;AN_nfe_nwe=8576;AF_nfe_nwe=0.282299;nhomalt_nfe_nwe=343;AC_nfe=3984;AN_nfe=15404;AF_nfe=0.258634;nhomalt_nfe=519
```

Any idea of what can be wrong ? I did some preliminary tests with vcfanno, and it worked, so I don't believe the problem is in the way and reformatted the files.

Thanks in advance,
Pedro Barbosa

**Comment by ens-lgil** [comment]
Dear @PedroBarbosa,

Please, could you send me the full command line you used so I can try to replicate the issue ?

Normally VEP should read both chromosome notation (i.e. `1` and `chr1`) and it should be the same for the custom annotations.

Best regards,
Laurent

**Comment by PedroBarbosa** [comment]
Dear @ens-lgil,

I'm sorry for my late response.
Ok, it's good to know about VEP dealing with both notations. 
Please find below my command:

```
srun shifter -V=/mnt/nfs/lobo/IMM-NFS/ensembl_vep:/media --image=ensemblorg/ensembl-vep:latest vep --force_overwrite --stats_text --hgvs --hgvsg --pubmed --check_existing --cache --dir /media/cache --offline --sift b --polyphen b --numbers --regulatory --variant_class --refseq --cache_version 95 -a GRCh37 --fasta /media/cache/homo_sapiens_refseq/95_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz --plugin dbscSNV,/media/custom_data/dbscSNV/hg19/dbscSNV1.1_hg19.txt.gz --plugin ExACpLI,/media/custom_data/ExACpLI/ExACpLI_values.txt --plugin GeneSplicer,/media/custom_data/genesplicer/bin/linux/genesplicer,/media/custom_data/genesplicer/human --plugin MaxEntScan,/media/custom_data/MaxEntScan --plugin SpliceRegion --plugin Condel,/media/custom_data/condel,b --plugin Carol --plugin CADD,/media/custom_data/cadd/hg19/v1.4/whole_genome_SNVs.tsv.gz,/media/custom_data/cadd/hg19/v1.4/InDels.tsv.gz --plugin dbNSFP,'consequence=ALL',/media/custom_data/dbNSFP/hg19/dbNSFP4.0b1a_hg19.txt.gz,GERP++_RS,phyloP30way_mammalian,29way_logOdds,phastCons30way_mammalian,MutationAssessor_score,SIFT4G_score,SIFT_score,Polyphen2_HDIV_score,Polyphen2_HVAR_score,MutationTaster_score,FATHMM_score,fathmm-MKL_coding_score,PROVEAN_score,CADD_phred,DANN_score,Eigen-pred_coding,Eigen-PC-phred_coding,MetaSVM_score,MetaSVM_pred,MetaLR_score,MetaLR_pred,REVEL_score,integrated_fitCons_score,LRT_score,LRT_pred,MutPred_score,VEST4_score,M-CAP_score,LINSIGHT --custom /media/custom_data/gnomAD/hg19/gnomAD_v2.1_justImportantFields.vcf.gz,gnomADg,vcf,exact,0,AF,AF_nfe,AF_nfe_nwe --plugin Gwava,region,/media/custom_data/gwava_scores/gwava_scores.bed.gz --custom /media/custom_data/gerp/All_hg19_RS.bw,Gerp,bigwig --af --af_1kg --af_esp  --max_af --af_gnomad -i /mnt/nfs/lobo/MCFONSECA-NFS/pedro.barbosa/resources/clinvar/test_dataset.txt --vcf --vcf_info_field ANN --compress_output bgzip --output_file test.vcf.bgz
```

And a small set of variants:
```
1       3321329 3321329 C/T     +       PRDM16:c.911C>T rs377547823
1       78394996        78394996        G/A     +       NEXN:c.865-5G>A rs727505353
1       78399061        78399061        A/G     +       NEXN:c.1148A>G
1       78399103        78399103        G/A     +       NEXN:c.1190G>A  rs201806320
1       116275561       116275561       G/C     +       CASQ2:c.567C>G  rs146664754
1       156108298       156108298       C/T     +       LMNA:c.1718C>T  rs60890628
1       201328373       201328373       G/A     +       TNNT2:c.832C>T  rs121964857
1       201330414       201330414       T/A     +       TNNT2:c.773A>T  rs397516482
1       201334394       201334394       C/A     +       TNNT2:c.306G>T
1       201335971       201335971       C/G     +       TNNT2:c.198G>C  rs727504869
```

Log file attached.
[1803746_runvep.log](https://github.com/Ensembl/ensembl-vep/files/2972331/1803746_runvep.log)

**Comment by ens-lgil** [comment]
Dear @PedroBarbosa,

I tried your command using both `1` and `chr1` with the Docker image on `95` and the VEP cache `refseq` on `95_GRCh37` without a problem: I got annotations.

Are you missing some of the annotations or all the annotations ?
Please, could you try to narrow down the issue, running your `plugin` and `custom` one at a time ?

Best regards,
Laurent

**Comment by PedroBarbosa** [comment]
Dear @ens-lgil ,
Came back to this issue today. I think I found what was going on.

I wasn't getting results for custom annotations because apparently VEP assigns them an unique ID within the INFO field in the header, while in fact those annotations are added into the ANN (or CSQ) field. For example, below GERP_vep field is present in the header both as an independent field with an ID as well as within the ANN field. My own script reads the header of the VCF and was expecting the values to be stored in the GERP_vep field, but the fact is that the scores from this custom annotation are stored in the ANN field. I do not know if this is the expected VEP behavior, but I already fixed my own script to deal with that.

```
##INFO=<ID=ANN,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|VARIANT_CLASS|SYMBOL_SOURCE|HGNC_ID|SOURCE|SIFT|PolyPhen|HGVS_OFFSET|HGVSg|AF|AFR_AF|AMR_AF|EAS_AF|EUR_AF|SAS_AF|AA_AF|EA_AF|gnomAD_AF|gnomAD_AFR_AF|gnomAD_AMR_AF|gnomAD_ASJ_AF|gnomAD_EAS_AF|gnomAD_FIN_AF|gnomAD_NFE_AF|gnomAD_OTH_AF|gnomAD_SAS_AF|MAX_AF|MAX_AF_POPS|CLIN_SIG|SOMATIC|PHENO|PUBMED|MOTIF_NAME|MOTIF_POS|HIGH_INF_POS|MOTIF_SCORE_CHANGE|ada_score|rf_score|ExACpLI|GeneSplicer|MaxEntScan_alt|MaxEntScan_diff|MaxEntScan_ref|SpliceRegion|Condel|CAROL|CADD_PHRED|CADD_RAW|29way_logOdds|CADD_phred|DANN_score|Eigen-PC-phred_coding|Eigen-pred_coding|FATHMM_score|GERP++_RS|LINSIGHT|LRT_pred|LRT_score|M-CAP_score|MetaLR_pred|MetaLR_score|MetaSVM_pred|MetaSVM_score|MutPred_score|MutationAssessor_score|MutationTaster_score|PROVEAN_score|Polyphen2_HDIV_score|Polyphen2_HVAR_score|REVEL_score|SIFT4G_score|SIFT_score|VEST4_score|fathmm-MKL_coding_score|integrated_fitCons_score|phastCons30way_mammalian|phyloP30way_mammalian|GERP_vep|phyloP_vep|phastCons_vep|gnomADg|gnomADg_AF|gnomADg_AF_nfe|gnomADg_AF_nfe_nwe">
##INFO=<ID=GERP_vep,Number=.,Type=String,Description="/media/custom_data/gerp/All_hg19_RS.bw (overlap)">
##INFO=<ID=gnomADg,Number=.,Type=String,Description="/media/custom_data/gnomAD/hg19/gnomAD_v2.1_justImportantFields.vcf.gz (exact)">
##INFO=<ID=gnomADg_AF,Number=.,Type=String,Description="AF field from /media/custom_data/gnomAD/hg19/gnomAD_v2.1_justImportantFields.vcf.gz">
##INFO=<ID=gnomADg_AF_nfe,Number=.,Type=String,Description="AF_nfe field from /media/custom_data/gnomAD/hg19/gnomAD_v2.1_justImportantFields.vcf.gz">
##INFO=<ID=gnomADg_AF_nfe_nwe,Number=.,Type=String,Description="AF_nfe_nwe field from /media/custom_data/gnomAD/hg19/gnomAD_v2.1_justImportantFields.vcf.gz">
```
Is it possible for custom annotations to retrieve the average value over the positions of an indel, instead of all the values (if using overlap mode), or just the position where the variant starts (if using exact mode) ? Basically I would like to know if it's possible to perform arithmetic operations as we can do with vcfanno, for example.

In what concerns to the topic of this issue, there is no problem with chromosome notation at all.

Best,
Pedro

**Comment by PedroBarbosa** [comment]
Btw, out of curiosity, how does CADD plugin deals with indels ? I see that I always get an unique value, even if my indels are not present within the InDels.tsv.gz file. Is it because by default CADD plugins runs in 'exact mode' ?

```
 --plugin CADD,/media/custom_data/cadd/hg19/v1.4/whole_genome_SNVs.tsv.gz,/media/custom_data/cadd/hg19/v1.4/InDels.tsv.gz
```

**Comment by ens-lgil** [comment]
Dear Pedro,

#### VCF headers
This is expected from VEP as it provides information about the custom annotation(s) and their selected fields.

#### Average calculation
 VEP can only use the `exact` or the `overlap`. This would be tricky to implement the average for several reasons:
- As it's external annotation provided by the VEP users, we have no control over this data and its format.
- We would need to check and make sure that the custom annotation field is numerical and always numerical (it's not the most difficult part).
- This would become trickier if the user select several fields from his custom annotation and some of them are not numeric.

#### CADD plugin
Yes, it runs by default on the `exact` mode, matching the start position.

Best regards,
Laurent

**Comment by PedroBarbosa** [comment]
Thank you @ens-lgil for the clarifications.

Best,
Pedro
