### ISSUE TITLE
Differences in "Existing_variation" field when using indexed/unindexed cache

### ISSUE THREAD

**Issue by smijalko** [Ensembl/ensembl-vep#413]
Hello,

I see a difference in some variants when I annotate the same VCF with indexed and unindexed cache with the same parameter setup. 

Here is the command line used for running VEP: 

tar xfz homo_sapiens_vep_95_GRCh38.tar.gz -C /opt/ensembl-vep/ && perl -I /root/.vep/Plugins/ /opt/ensembl-vep/vep --offline --dir /opt/ensembl-vep --buffer_size 500000 --cache --force_overwrite --fork 4 --input_file Strelka2_somatic.snvs.vcf.gz --no_progress --plugin Condel,/opt/ensembl-vep/plugin-files/Condel/config,b --output_file Strelka2_VEP.txt --species homo_sapiens  --no_stats --polyphen b --sift b --no_escape --numbers --canonical --ccds --protein --symbol --af_1kg --af_esp --af_gnomad --check_existing --vcf

Examples of a difference where one of the caches gives more/less ids:

---------------------
chr1  235112115	.	G	GA	Existing_variation = rs778909032
chr1	 235112115	.	G	GA   Existing_variation = rs778909032&TMP_ESP_1_235275431_235275431
---------------------
chr16	1065849	.	C	A      Existing_variation = rs34613944&rs80286221
chr16	1065849	.	C	A	Existing_variation = rs80286221
---------------------

Command line used for indexing VEP cache:

tar xfz homo_sapiens_vep_95_GRCh38.tar.gz -C /opt/ensembl-vep/cache &&  /opt/ensembl-vep/convert_cache.pl --species all --version all --dir /opt/ensembl-vep/cache  && tar czf homo_sapiens_vep_95_GRCh38.processed.tgz -C /opt/ensembl-vep/cache .

Can you please help me understand what causes those differences? Is this expected?

Best,
Sanja

**Comment by aparton** [comment]
Hi,

Thanks for sending this issue on. We’re currently in the process of investigating, and it looks like there is an issue in the non-indexed cache relating to multi-allelic variants.

The variants reported in the indexed cache are correct, so please continue to use that one. We don’t recommend the non-indexed cache files, particularly for human, as they can be quite slow.

I’ll let you know when we find a concrete solution to the non-indexed cache issue.

Kind Regards,
Andrew

**Comment by sigven** [comment]
Hi,

I just experienced a somewhat related issue (I believe), through the web interface. A particular variant (chr5:112841059T>A, grch38) yields both dbSNP annotation (rs459552) and gnomAD frequencies through the web interface. Submitting the same variant with grch37 coordinates (chr5:112176756T>A) yields no gnomAD frequences and no dbSNP reference. 

Performing annotation of the same variant with my local v96 installation (I use the pre-indexed cache) gives similar results for grch37, i.e. no gnomAD frequencies and no dbSNP reference. Having the `--failed 1` option turned on did not resolve the issue. 

Any clues as to why this variant do not report the same annotations for grch37 and grch38?

regards,
Sigve

**Comment by aparton** [comment]
Hi @sigven,

I've taken a look at this issue this morning and it looks like there's a bug at our end where variants on chromosome 5 are missing for GRCh37. 

Thanks for reporting this to us, and I'll let you know when there's a fix in place.

Kind Regards,
Andrew

**Comment by reWfLoiNDERnwARy** [comment]
D as acad cu

Enviado desde mi Sony Xperia™ smartphone de Telcel

---- Andrew Parton wrote ----


Hi @sigven<https://github.com/sigven>,

I've taken a look at this issue this morning and it looks like there's a bug at our end where variants on chromosome 5 are missing for GRCh37.

Thanks for reporting this to us, and I'll let you know when there's a fix in place.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

Just to provide an update to these issues, we're still investigating the initial cause of the differences between the indexed/non-indexed cache files.

The issue with missing variants on chromosome 5 on GRCh37 has now been resolved.

Kind Regards,
Andrew

**Comment by sigven** [comment]
Thanks for that. I do however notice that the pre-indexed for GRCh37 as increased significantly in size (almost 20Gb), significantly larger than GRCh38. I cannot seem to remember that it was like this in previous releases? Any comments to this?

regards,
Sigve

**Comment by aparton** [comment]
Hi,

This is due to the nature of the fix that we applied, to get a fix out sooner rather than later then we converted one of our non-indexed cache files, rather than generating an entirely new one. This has left additional non-indexed components in there, which will not have an effect on your output data.

The GRCh37 cache file will be restored to its original size with release 97, currently scheduled for release in early July.

Thanks,
Andrew

**Comment by sigven** [comment]
Thanks for the clarification. Will wait for the 97 release :-)
best,
Sigve

**Comment by at7** [comment]
Dear @sigven,
I would like to let you know that we have released Ensembl 97. Please start using the new cache files and let us in case you notice any problems.
Best wishes,
Anja

**Comment by sigven** [comment]
Dear @at7,
Thanks for the friendly reminder:-) I have already started looking at them, will let you know if I run into any issues.

best,
Sigve
