### ISSUE TITLE
gnomAD_AF missing

### ISSUE THREAD

**Issue by vyepez88** [Ensembl/ensembl-vep#414]
Hi! I'm running veptools, version 94, in order to get minor allele frequencies from gnomAD. It works for the majority, but I found around 100 of them where it doesn't give any value, although when checking manually in the gnomAD website, I do find some frequencies.
Here's the command I run:
vep --everything --af --max_af --af_gnomad -i input_vep.txt --cache --assembly GRCh37 --species homo_sapiens --merged --port 3337 --force_overwrite --dir_cache /opt/modules/i12g/ensembl-vep/94/cachedir
where input_vep.txt contains those variants.
Here are some of them:
chr2-97877292-C-A, gnomAD_AF = 0.90 in website and NA from veptools
chr17-41466096-A-G', gnomAD_AF = 0.60 in website and NA from veptools
If needed be, I can attach the file with all the variants.
Thanks!

**Comment by at7** [comment]
Hi,
could you please share the input variant list? We will take a look. Thank you.

**Comment by vyepez88** [comment]
Hi,
In attachment. Thanks a lot.
[input_vep.txt](https://github.com/Ensembl/ensembl-vep/files/2962925/input_vep.txt)

**Comment by at7** [comment]
Thank you for providing the input file. I can explain why the gnomAD frequencies are missing for some of your input variants. The frequencies are read from the VEP cache files. For gnomAD we only store the exome frequencies in our cache files. This explains why you don't get gnomAD frequencies for chr17-41466096-A-G.
When we build the cache files we only store allele frequencies in the cache files for variants that are stored in the ensembl variation database. This means that VEP only annotates input variants with frequency data that have a corresponding variant in the variation database. chr2-97877292-C-A corresponds to [rs10171441](http://grch37.ensembl.org/Homo_sapiens/Variation/Population?db=core;r=2:97876792-97877792;v=rs10171441;vdb=variation;vf=74568448). However, the variant is flagged as failed and the default is not do report failed variants as co-located and hence not to report the allele frequencies. If you want to change that you must add `--failed 1` to your command line arguments. 
That should explain why you are missing the gnomAD_AF for some variants even though there is gnomAD data available for those variants. But please let me know if you see any other cases where you expect frequencies or if you have any questions regarding my answer.

**Comment by vyepez88** [comment]
Hi,
Thanks a lot for your answer. I added the `--failed 1` and it worked.
Do you plan to store the gnomAD non exonic features in the cache files soon? It'll be great in order to analyze WGS.
Best,
Vicente

**Comment by at7** [comment]
Dear Vicente,
we are having longterm plans to include genome gnomAD data into our cache files. We haven't finalised a timeline and would like to ask you to get the latest updates from our [What's new page](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#new). Please also consider using [custom annotation ](http://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html)for adding genome gnomAD data.
Best regards,
Anja
