### ISSUE TITLE
Feature request: add auto-update option to INSTALL.pl

### ISSUE THREAD

**Issue by matthdsm** [Ensembl/ensembl-vep#42]
Hi,

Would it be possible to add an auto update flag to `INSTALL.pl` when using the `-a` flag?
This would ensure that users have the latest postfixes when using the automated installer.

Thanks
M

**Comment by willmclaren** [comment]
https://github.com/Ensembl/ensembl-vep/commit/a7445bdaa8173fedba128e95999d50477ed037f4

Will be in release/89.

**Comment by matthdsm** [comment]
Allright!
Thanks! 
M
