### ISSUE TITLE
HGVS anno for in-frame deletions off by 1 amino acid? (VEP 95.3)

### ISSUE THREAD

**Issue by danhovelson** [Ensembl/ensembl-vep#420]
- VEP version: `ensemblorg/ensembl-vep:release_95.3` image from GH

In-frame deletion annotations generated with the above version of VEP (using the Refseq cache) return HGVS protein annotations that appear to be off by 1 amino acid (bumped 1 AA in 3' direction). Am I missing something?

**Examples:**
```
Variant: chr4_55593613_TTGA/T
Refseq transcript: NM_000222.2
Expected HGVS protein anno: p.E561del
Returned HGVS protein anno: p.E562del

Variant: chr4_55593596_AGTACAGTGGAAGGTT/A
Refseq transcript: NM_000222.2
Expected anno: p.V555_V559del
Returned anno: p.Q556_V560del
```

Here's the command (run on the docker container) used to generate these annotations:

```bash
vep -i STDIN \
-o STDOUT \
--cache \
--offline \
--refseq \
--format vcf \
--fasta hg19.fasta \
--hgvs  \
--force_overwrite \
--use_given_ref \
--symbol \
--vcf \
--no_escape \
--allele_number \
 --fork 4
```

Feedback greatly appreciated!

**Comment by aparton** [comment]
Hi Dan,

I’ve has a quick look at this this morning, and it looks like the HGVS is correct. In the case of insertions and deletions within repeated sequences, HGVS variants are reported in their most 3’ position. http://varnomen.hgvs.org/recommendations/general/ <http://varnomen.hgvs.org/recommendations/general/>

So for your first example, the sequence around the variant is:

AAG GTT GTT GAG GAG ATA

Which, at protein level, corresponds to:

KVVEEI

Once the inframe deletion is performed, then we end up with the sequence:

AAG GTT GTG GAG ATA => KVVEI

So while the deletion looks like it is taking place at protein position 561, as the deleted amino acid is part of a repeated sequence, the HGVS position is shifted along one amino acid and we report the deletion at position 562.

If you have any questions, please let us know.

Kind Regards,
Andrew

**Comment by danhovelson** [comment]
Thanks very much, Andrew - very helpful explanation!
