### ISSUE TITLE
Following instructions leads to ERROR: No plugins specified

### ISSUE THREAD

**Issue by carbocation** [Ensembl/ensembl-vep#421]
The Docker instructions seem to be written for people with experience running VEP. As a VEP neophyte, I'm getting `ERROR: No plugins specified` [when following the instructions](http://useast.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker).

```sh
docker run -t -i -v $HOME/docker-vep/data:/opt/vep/.vep ensemblorg/ensembl-vep perl INSTALL.pl -a cfp -s homo_sapiens -y GRCh38
```

Result: 
```
ERROR: No plugins specified
```

Note that my path is slightly modified, but that path exists and has 777 perms:
```sh
ll $HOME/docker-vep/data
total 8
drwxrwxrwx 2 vep vep 4096 Mar 25 12:13 ./
drwxrwxr-x 3 vep vep 4096 Mar 25 12:21 ../
```

Am I supposed to modify the command to get the installer to run, or should it be working as shown in the instructions?

**Comment by ens-lgil** [comment]
Dear @carbocation,

I am sorry for the unclear documentation.

 You need to use the option `--PLUGINS` in addition to your command, e.g.:
- If you want to download/install all the plugins:
```
docker run -t -i -v $HOME/docker-vep/data:/opt/vep/.vep ensemblorg/ensembl-vep perl INSTALL.pl -a cfp -s homo_sapiens -y GRCh38  --PLUGINS all
```
- If you want to download/install specific plugins (list the plugins separated by a comma):
```
docker run -t -i -v $HOME/docker-vep/data:/opt/vep/.vep ensemblorg/ensembl-vep perl INSTALL.pl -a cfp -s homo_sapiens -y GRCh38  --PLUGINS dbNSFP,CADD
```
- If you want to list all the plugins:
```
docker run -t -i -v $HOME/docker-vep/data:/opt/vep/.vep ensemblorg/ensembl-vep perl INSTALL.pl -a p --PLUGINS list
```
We are going to improve the documentation about this.

Best regards,
Laurent

**Comment by carbocation** [comment]
Laurent - thank you, your modification to the command is working. Really appreciate it.

**Comment by ens-lgil** [comment]
Dear @carbocation,

I am glad that the command worked!

I am closing this ticket, but if you have any more questions please feel free to reopen it.

Best regards,
Laurent
