### ISSUE TITLE
VEP stalls after warning 

### ISSUE THREAD

**Issue by audyavar** [Ensembl/ensembl-vep#428]
Hi - 

I am trying to run VEP on linux in AWS. I ran the following command. It gives me the warning "no input format specified" and then fails. Any advice? I have vcf4.2 file. Is that not compatible with VEP?

./vep --cache --input_file pact1-ensemble.vcf --output_file 'pact171_VEP.txt' --force --species homo_sapiens --fork 4 --verbose --stats_file "pact171.html" --terms SO --protein  --symbol --ccds --canonical --sift b --polyphen b  --gene_phenotype --pubmed --variant_class --uniprot --regulatory  --format "vcf"
which: no tabix in (/root/perl5/bin:/root/perl5/bin:/sbin:/bin:/usr/sbin:/usr/bin)
Will only load v95 databases
Species 'homo_sapiens' loaded from database 'homo_sapiens_core_95_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_cdna_95_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_otherfeatures_95_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_rnaseq_95_38'
homo_sapiens_variation_95_38 loaded
homo_sapiens_funcgen_95_38 loaded
No ancestral database found
No ontology database found
No taxonomy database found
No ensembl_metadata database found
No production database or adaptor found
WARNING: No input file format specified - detected vcf format

**Comment by at7** [comment]
VEP parses vcf4.2 files. Could you please let me know how you installed VEP and also share some lines of your input file please?
Thank you,
Anja
