### ISSUE TITLE
Offline annotation with GFF

### ISSUE THREAD

**Issue by mcgml** [Ensembl/ensembl-vep#43]
Hi 

I wondered if it would be possible to annotate a VCF using a GFF/GTF resource without connecting to ensembl?

`[ml@cvx-gen02 ~]$ /share/apps/vep-distros/ensembl-vep/vep -i /share/apps/vep-distros/ensembl-vep/examples/homo_sapiens_GRCh37.vcf -gff /data/db/human/refseq/ref_GRCh37.p13_top_level_canonical_b37_sorted.gff3.gz -fasta /data/db/human/gatk/2.8/b37/human_g1k_v37.fasta --offline

-------------------- EXCEPTION --------------------
MSG: ERROR: Cache directory /home/ml/.vep/homo_sapiens not found

STACK Bio::EnsEMBL::VEP::CacheDir::dir /share/apps/vep-distros/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:182
STACK Bio::EnsEMBL::VEP::CacheDir::init /share/apps/vep-distros/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:139
STACK Bio::EnsEMBL::VEP::CacheDir::new /share/apps/vep-distros/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:68
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /share/apps/vep-distros/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:75
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /share/apps/vep-distros/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:65
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /share/apps/vep-distros/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::init /share/apps/vep-distros/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:77
STACK Bio::EnsEMBL::VEP::Runner::run /share/apps/vep-distros/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:111
STACK toplevel /share/apps/vep-distros/ensembl-vep/vep:209
Date (localtime)    = Mon Apr 24 14:50:27 2017
Ensembl API version = 88
---------------------------------------------------`

Thanks
Matt

**Comment by willmclaren** [comment]
Yes, just remove `--offline` from your command.

`--offline` switches on `--cache`, which then tries to look for the cache directory, hence the error.

**Comment by mcgml** [comment]
@willmclaren Thanks!
