### ISSUE TITLE
HGVSp and silent changes (there should be no "=" signs in INFO filed)

### ISSUE THREAD

**Issue by thedam** [Ensembl/ensembl-vep#430]
Hi, 
[VCF specification ](https://samtools.github.io/hts-specs/VCFv4.2.pdf)says: 

8. INFO - additional information: (String, **no** white-space, semi-colons, or **equals-signs permitted**; commas are permitted only as delimiters for lists of values), 

but [HGVSp](http://varnomen.hgvs.org/recommendations/protein/variant/substitution/) nomenclature says:

```
silent (no change)
NP_003997.1:p.Cys188=
amino acid Cys188 is not changed (DNA level change ..TGC.. to ..TGT..)
NOTE: the description p.= means the entire protein coding region was analysed and no variant was found that changes (or is predicted to change) the protein sequence.
```
so putting HGVSp notation of some silent change into `##INFO=<ID=CSQ,` makes specifications conflict:)

Take a look on my example vcf: (written as txt as git doesn't allow other formats)
[ct.txt](https://github.com/Ensembl/ensembl-vep/files/3040423/ct.txt)
there is a CSQ tag with equal-sign in INFO field:

CSQ=C|downstream_gene_variant|MODIFIER|NOC2L|26155|Transcript|NM_015658.3|protein_coding||||||||||rs6672356|1|1752|-1||EntrezGene|||T|T|OK|||1|||0.9999|0.9994|0.9999|1|1|1|0.9999|1|0.9997|||||rs6672356|9.99804e-01,C|synonymous_variant|LOW|SAMD11|148398|Transcript|NM_152486.2|protein_coding|10/14||NM_152486.2:c.1027T>C|**NP_689699.2:p.Arg343=**|1107|1027|343|R|Cgg/Cgg|rs6672356|1||1||EntrezGene|||T|C|OK|||1|||0.9999|0.9994|0.9999|1|1|1|0.9999|1|0.9997|||||rs6672356|9.99804e-01

Later this make a conflict while using VCF-specification compatible tools like [vcfR](https://knausb.github.io/vcfR_documentation/). 
Have a look on issue I've reported here:
https://github.com/knausb/vcfR/issues/130
 
to solve it, I propose change this:
`NP_689699.2:p.Arg343=`
on this:
`NP_689699.2:p.Arg343Arg`

Cheers
Damian

**Comment by at7** [comment]
Hello,
could you please let me know if you are running vep with --no_escape? The default is to URI escape HGVS strings unless you specify --no_escape.
Thanks,
Anja

**Comment by thedam** [comment]
yes, I run it with "--no_escape"

**Comment by at7** [comment]
Could you just drop the parameter or is there a reason why you need to run with --no_escape?

**Comment by thedam** [comment]
hmm long time ago I didn't like such notation: **NP_000383.1:p.Phe39%3D** and I've learned that `--no_escape` "repairs it". Ok, now I get the reason of this escape/no escape.

Thanks for clarification
