### ISSUE TITLE
Confirming VCF REF allele matches reference sequence with local RefSeq cache

### ISSUE THREAD

**Issue by danhovelson** [Ensembl/ensembl-vep#438]
I'm running VEP using a local Refseq cache (offline) [VEP Docker image v95.3], and would like to systematically confirm that the REF allele provided in my submitted VCF matches that present in my provided FASTA file for all variants submitted for annotation. 

I'm wondering why (when using `--check_ref` with `--dont_skip`) there's no indication that the REF allele in `my.vcf` **does not match** the REF allele in the provided FASTA file.

Example full VEP command:

```bash
cat my.vcf | vep \
        -o STDOUT \
        --offline \
        --refseq \
        --format vcf \
        --fasta $FASTA_FILE \  # note: here we're using hg19.fasta
        --use_given_ref \
        --check_ref \
        --dont_skip \
        --hgvs \
        --force_overwrite \
        --exclude_predicted \
        --symbol \
        --vcf \
        --flag_pick_allele \
        --no_escape \
        --canonical \
        --allele_number \
        --fork 4
```

Contents of `my.vcf` file:
```bash
##fileformat=VCFv4.1
##reference=grch37
##sampleGender=Unknown
##contig=<ID=chr1,length=249250621,assembly=hg19>
##contig=<ID=chr2,length=243199373,assembly=hg19>
##contig=<ID=chr3,length=198022430,assembly=hg19>
##contig=<ID=chr4,length=191154276,assembly=hg19>
##contig=<ID=chr5,length=180915260,assembly=hg19>
##contig=<ID=chr6,length=171115067,assembly=hg19>
##contig=<ID=chr7,length=159138663,assembly=hg19>
##contig=<ID=chr8,length=146364022,assembly=hg19>
##contig=<ID=chr9,length=141213431,assembly=hg19>
##contig=<ID=chr10,length=135534747,assembly=hg19>
##contig=<ID=chr11,length=135006516,assembly=hg19>
##contig=<ID=chr12,length=133851895,assembly=hg19>
##contig=<ID=chr13,length=115169878,assembly=hg19>
##contig=<ID=chr14,length=107349540,assembly=hg19>
##contig=<ID=chr15,length=102531392,assembly=hg19>
##contig=<ID=chr16,length=90354753,assembly=hg19>
##contig=<ID=chr17,length=81195210,assembly=hg19>
##contig=<ID=chr18,length=78077248,assembly=hg19>
##contig=<ID=chr19,length=59128983,assembly=hg19>
##contig=<ID=chr20,length=63025520,assembly=hg19>
##contig=<ID=chr21,length=48129895,assembly=hg19>
##contig=<ID=chr22,length=51304566,assembly=hg19>
##contig=<ID=chrX,length=155270560,assembly=hg19>
##contig=<ID=chrY,length=59373566,assembly=hg19>
##contig=<ID=chrM,length=16569,assembly=hg19>
#CHROM    POS    ID    REF    ALT    QUAL    FILTER    INFO
chr1    98348885    vid1   T    A    .    PASS    .
```

Here the provided reference allele (`T`) intentionally does not match the correct reference allele in the hg19.fasta:

```bash
-bash-4.2$ samtools faidx hg19.fasta chr1:98348885-98348885
>chr1:98348885-98348885
G
```

And here's the VEP output:
```bash
##VEP="v95" time="2019-04-17 15:43:09" cache="/root/.vep/homo_sapiens_refseq/95_GRCh37" ensembl-funcgen=95.94439f4 ensembl-variation=95.858de3e ensembl-io=95.78ccac5 ensembl=95.4f83453 1000genomes="phase3" COSMIC="86" ClinVar="201810" ESP="20141103" HGMD-PUBLIC="20174" assembly="GRCh37.p13" dbSNP="151" gencode="GENCODE 19" genebuild="2011-04" gnomAD="170228" polyphen="2.2.2" refseq="01_2015" regbuild="1.0" sift="sift5.2.2"
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|ALLELE_NUM|DISTANCE|STRAND|FLAGS|PICK|SYMBOL_SOURCE|HGNC_ID|CANONICAL|REFSEQ_MATCH|HGVS_OFFSET">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr1	98348885	vid1	T	A	.	PASS	CSQ=A|missense_variant|MODERATE|DPYD|1806|Transcript|NM_000110.3|protein_coding|2/23||NM_000110.3:c.85C>T|NP_000101.2:p.Ser29Cys|222|85|29|S/C|Agt/Tgt||1||-1||1|EntrezGene||YES||,A|missense_variant|MODERATE|DPYD|1806|Transcript|NM_001160301.1|protein_coding|2/6||NM_001160301.1:c.85C>T|NP_001153773.1:p.Ser29Cys|222|85|29|S/C|Agt/Tgt||1||-1|||EntrezGene||||
```

Here, there's zero indication that the supplied REF allele is wrong. The default behavior of `--check_ref` (without `--dont_skip`; i.e., omitting variants where VCF REF != FASTA REF allele) makes the workflow somewhat susceptible to errors, as it requires cross-checking of input and output variant lists to ensure we flag variants missing from annotated output as (implicitly) 'mismatched REF alleles`. 

Am I missing something? Is there no equivalent `REFSEQ_MATCH`-like indicator that could be used to indicate mismatched REF alleles?

Thanks!

**Comment by aparton** [comment]
Hi Dan,

Thanks for bringing this issue to our attention. The —check_ref flag prints a warning to STDOUT, rather than adding anything to the output file. Depending on your Docker settings, this message may well be suppressed. 

I think it would be appropriate to add an output value suggesting that this check has failed when the check_ref flag is added. I’ll start the process of making that happen, and let you know when it’s complete.

Kind Regards,
Andrew

**Comment by danhovelson** [comment]
Great - thanks very much for the prompt reply, Andrew!

**Comment by ens-lgil** [comment]
I am closing this ticket, but if you have any more questions please feel free to reopen it.

Best regards,
Laurent

**Comment by danhovelson** [comment]
Thanks Laurent - any idea whether any action has been taken, per the comment made by @aparton [above](https://github.com/Ensembl/ensembl-vep/issues/438#issuecomment-484168609)? Some indication of a mismatched reference allele in the returned VCF file would be extremely helpful to our (and I suspect others') variant processing workflows.

**Comment by aparton** [comment]
Hi Dan,

A JIRA ticket has been added, however the work has not yet been completed. We'll aim to get the change in release 97, which is due at the end of June.

Kind Regards,
Andrew
