### ISSUE TITLE
Feature request: output compressed vcf

### ISSUE THREAD

**Issue by matthdsm** [Ensembl/ensembl-vep#44]
Hi,

Would it be possible to add an option to output compressed vcf files? I realize this is allready possible by outputting to stdout and piping to gzip, but it would be handy to have a built in option.

Thanks!
M

**Comment by willmclaren** [comment]
Addressed by: https://github.com/Ensembl/ensembl-vep/commit/ce88f3b21d7411954cd195f304886849ca56aff0

Available now on master or on release/89 when released.
