### ISSUE TITLE
truncated entries after annotation by VEP when multi-threading

### ISSUE THREAD

**Issue by tdw1221** [Ensembl/ensembl-vep#440]
I recently ran VEP annotation on a batch of germline vcf files where some of the annotated files ended up with truncated lines:
1	**905020	.**	A	G	169.77	.	BaseQRankSum=2.219;ClippingRankSum=-0.361;ExcessHet=3.0103;FS=2.808;MQ=41.96;MQRankSum=-1.652;QD=18.86;ReadPosRankSum=-0.361;SOR=1.981;SF=0;DP=9;AF=0.5;MLEAC=1;MLEAF=0.5;AN=0;AC=0;CSQ=G|downstream_gene_variant|MODIFIER|KLHL17|ENSG00000187961|Transcript|ENST00000338591|protein_coding|||||||||||3925|1||HGNC|24023|||MQPRSERPAGRTQSPEHGSPGPGPEAPPPPPPQPPAPEAERTRPRQARPAAPMEGAVQLLSREGHSVAHNSKRHYHDAFVAMSRMRQRGLLCDIVLHVAAKEIRAHKVVLASCSPYFHAMFTNEMSESRQTHVTLHDIDPQALDQLVQFAYTAEIVVGEGNVQTLLPAASLLQLNGVRDACCKFLLSQLDPSNCLGIRGFADAHSCSDLLKAAHRYVLQHFVDVAKTEEFMLLPLKQVLELVSSDSLNVPSEEEVYRAVLSWVKHDVDARRQHVPRLMKCVRLPLLSRDFLLGHVDAESLVRHHPDCKDLLIEALKFHLLPEQRGVLGTSRTRPRRCEGAGPVLFAVGGGSLFAIHGDCEAYDTRTDRWHVVASMSTRRARVGVAAVGNRLYAVGGYDGTSDLATVESYDPVTNTWQPEVSMGTRRSCLGVAALHGLLYSAGGYDGASCLNSAERYDPLTGTWTSVAAMSTRRRYVRVATLDGNLYAVGGYDSSSHLATVEKYEPQVNVWSPVASMLSRRSSAGVAVLEGALYVAGGNDGTSCLNSVERYSPKAGAWESVAPMNIRRSTHDLVAMDGWLYAVGGNDGSSSLNSIEKYNPRTNKWVAASCMFTRRSSVGVAVLELLNFPPPSSPTLSVSSTSL,G|intron_variant|MODIFIER|PLEKHN1|ENSG00000187583|Transcript|ENST00000379407|protein_coding||2/14||||||||||1||HGNC|25284|||MGNSHCVPQAPRRLRASFSRKPSLKGNREDSARMSAGLPGPEAARSGDAAANKLFHYIPGTDILDLENQRENLEQPFLSVFKKGRRRVPVRNLGKVVHYAKVQL1	**905043	.**	CAT	C	377.73	.	BaseQRankSum=-0.742;ClippingRankSum=-0.742;ExcessHet=3.0103;FS=0;MQ=61.53;MQRankSum=0.742;QD=30.11;ReadPosRankSum=0.742;SOR=0.223;SF=1;DP=195;AF=1;MLEAC=2;MLEAF=1;AN=0;AC=0;CSQ=-|downstream_gene_variant|MODIFIER|KLHL17|ENSG00000187961|Transcript|ENST00000338591|protein_coding|||||||||||3949|1||HGNC|24023|||MQPRSERPAGRTQSPEHGSPGPGPEAPPPPPPQPPAPEAERTRPRQARPAAPMEGAVQLLSREGHSVAHNSKRHYHDAFVAMSRMRQRGLLCDIVLHVAAKEIRAHKVVLASCSPYFHAMFTNEMSESRQTHVTLHDIDPQALDQLVQFAYTAEIVVGEGNVQTLLPAASLLQLNGVRDACCKFLLSQLDPSNCLGIRGFADAHSCSDLLKAAHRYVLQHFVDVAKTEEFMLLPLKQVLELVSSDSLNVPSEEEVYRAVLSWVKHDVDARRQHVPRLMKCVRLPLLSRDFLLGHVDAESLVRHHPDCKDLLIEALKFHLLPEQRGVLGTSRTRPRRCEGAGPVLFAVGGGSLFAIHGDCEAYDTRTDRWHVVASMSTRRARVGVAAVGNRLYAVGGYDGTSDLATVESYDPVTNTWQPEVSMGTRRSCLGVAALHGLLYSAGGYDGASCLNSAERYDPLTGTWTSVAAMSTRRRYVRVATLDGNLYAVGGYDSSSHLATVEKYEPQVNVWSPVASMLSRRSSAGVAVLEGALYVAGGNDGTSCLNSVERYSPKAGAWESVAPMNIRRSTHDLVAMDGWLYAVGGNDGSSSLNSIEKYNPRTNKWVAASCMFTRRSSVGVAVLELLNFPPPSSPTLSVSSTSL,-|intron_variant|MODIFIER|PLEKHN1|ENSG00000187583|Transcript|ENST00000379407|protein_coding||2/14||||||||||1||HGNC|25284|||MGNSHCVPQAPRRLRASFSRKPSLKGNREDSARMSAGLPGPEAARSGDAAANKLFHYIPGTDILDLENQRENLEQPFLSVFKKGRRRVPVRNLGKVVHYAKVQLRFQHSQDVSDCYLELFPAHLYFQAHGSEGLTFQGLLPLTELSVCPLEGSREHAFQITGPLPAPLLVLCPSRAELDRWLYHLEKQTALLGGPRRCHSAPPQGSCGDELPWTLQRRLTRLRTASGHEPGGSAVCASRVKLQHLPAQEQWDRLLVLYPTSLAIFSEELDGLCFKGELPLRAVHINLEEKEKQIRSFLIEGPLINTIRVVCASYEDYGHWLLCLRAVTHREGAPPLPGAESFPGSQVMGSGRGSLSSGGQTSWDSGCLAPPSTRTSHSLPESSVPSTVGCSSQHTPLHRLSLESSPDAPDHTSETSHSPLYADPYTPPATSHRRVTDVRGLEEFLSAMQSARGPTPSSPLPSVPVSVPASDPRSCSSGPAGPYLLSKKGALQSRAAQRHRGSAKDGGPQPPDAPQLVSSAREGSPEPWLPLTDGRSPRRSRDPGYDHLWDETLSSSHQKCPQLGGPEASGGLVQWI,-|intron_variant|MODIFIER|PLEKHN1|ENSG00000187583|Transcript|ENST00000379409|protein_coding||2/14||||||||||1||HGNC|25284|||MGNSHCVPQAPRRLRASFSRKPSLKGNREDSARMSAGLPGPEAARSGDAAANKLFHYIPGTDILDLENQRENLEQPFLSVFKKGRRRVPVRNLGKVVHYAKVQLRFQHSQDVSDCYLELFPAHLYFQAHGSEGLTFQGLLPLTELSVCPLEGSREHAFQITGVWDASRAPRGTPDPGLGEGPALWLRSTCVYVCALSALPAGPLPAPLLVLCPSRAELDRWLYHLEKQTALLGGPRRCHSAPPQGSCGDELPWTLQRRLTRLRTASGHEPGGSAVCASRVKLQHLPAQEQWDRLLVLYPTSLAIFSEELDGLCFKGELPLRAVHINLEEKEKQIRSFLIEGPLINTIRVVCASYEDYGHWLLCLRAVTHREGAPPLPGAESFPGSQVMGSGRGSLSSGGQTSWDSGCLAPPSTRTSHSLPESSVPSTVGCSSQHTPDQANSDRASIGRRRTELRRSGSSRSPGSKARAEGRGPVTPLHLDLTQLHRLSLESSPDAPDHTSETSHSPLYADPYTPPATSHRRVTDVRGLEEFLSAMQSARGPTPSSPLPSVPVSVPASDPRSCSSGPAGPYLLSKKGALQSRAAQRHRGSAKDGGPQPPDAPQLVSSAREGSPEPWLPLTDGRSPRRSRDPGYDHLWDETLSSSHQKCPQLGGPEASGGLVQWI,-|intron_variant|MODIFIER|PLEKHN1|ENSG00000187583|Transcript|ENST00000379410|protein_coding||2/15||||||||||1||HGNC|25284|||MGNSHCVPQAPRRLRASFSRKPSLKGNREDSARMSAGLPGPEAARSGDAAANKLFHYIPGTDILDLENQRENLEQPFLSVFKKGRRRVPVRNLGKVVHYAKVQLRFQHSQDVSDCYLELFPAHLYFQAHGSEGLTFQGLLPLTELSVCPLEGSREHAFQITGPLPAPLLVLCPSRAELDRWLYHLEKQTALLGGPRRCHSAPPQRRLTRLRTASGHEPGGSAVCASRVKLQHLPAQEQWDRLLVLYPTSLAIFSEELDGLCFKGELPLRAVHINLEEKEKQIRSFLIEGPLINTIRVVCASYEDYGHWLLCLRAVTHREGAPPLPGAESFPGSQVMGSGRGSLSSGGQTSWDSGCLAPPSTRTSHSLPESSVPSTVGCSSQHTPDQANSDRASIGRRRTELRRSGSSRSPGSKARAEGRGPVTPLHLDLTQLHRLSLESSPDAPDHTSETSHSPLYADPYTPPATSHRRVTDVRGLEEFLSAMQSARGPTPSSPLPSVPVSVPASDPRSCSSGPAGPYLLSKKGALQSRAAQRHRGSAKDGGPQPPDAPQLVSSAREGSPEPWLPLTDGRSPRRSRDPGYDHLWDETLSSSHQKCPQLGGPEASGGLVQWI,-|upstream_gene_variant|MODIFIER|PLEKHN1|ENSG00000187583|Transcript|ENST00000480267|retained_intron|||||||||||1210|1||HGNC|25284|||,-|upstream_gene_variant|MODIFIER|PLEKHN1|ENSG00000187583|Transcript|ENST00000491024|protein_coding|||||||||||3847|1|cds_start_NF|HGNC|25284|||SLESSPDAPDHTSETSHSPLYADPYTPPATSHRRVTDVRGLEEFLSAMQSARGPTPSSPLPSVPVSVPASDPRSCSSGPAGPYLLSKKGALQSRAAQRHRGSAKDGGPQPPDAPQLVSSAREGSPEPWLPLTDGRSPRRSRDPGYDHLWDETLSSSHQKCPQLGGPEASGGLVQWI	GT:AD:DP:GQ:PL	./.:.:.:.:.

Here entry 905043 truncated into entry 905020, and all entries between them in original vcf disappear. This problem only presents and is reproducible when I set -fork larger than 1. So I believe this is likely a bug in the program, I'd be happy to report more details if needed.

My example code is below:
/ysm-gpfs/pi/zhao/dt485/immumutation/ensembl-vep/vep --input_file /ysm-gpfs/pi/zhao/dt485/immumutation/vcf/germline_vcf/skcm/example.vcf --output_file /ysm-gpfs/pi/zhao/dt485/immumutation/vcf/germline_vcf/skcm/example.vep.vcf --format vcf --vcf --symbol --terms SO -fork 4 --offline --cache --plugin Downstream --plugin Wildtype --dir_plugins /ysm-gpfs/pi/zhao/dt485/immumutation/ensembl-vep/VEP_plugins

**Comment by helensch** [comment]
Hi
 
Thank you for your reporting the truncation. I am currently looking into it.

Please could you
 - confirm that all entries are there when you run without forks and with the Plugins
 - run the command with forks but without the plugins to see if the truncation still occurs
 - let me know which assembly and cache you are using

I am not clear how many variants there were between 1:905020-905043 and that were not reported in the output file.

For the variants between 1:905020-905043 can you run
- without forks and without plugins and compare the number of input lines with the number of data lines reported in VCF.
- without forks and with plugins and compare the number of input lines with the number of data lines reported in VCF.

Thanks
Helen

**Comment by tdw1221** [comment]
Hi Helen,

      Thanks for getting back to me, sure I could run these and let you
know. It might take a while due to the large file size


Bests
Daiwei

**Comment by tdw1221** [comment]
Hi, here are my summarized results, originally there are two line of entries between the truncated entries, but truncation doesn't happen in no fork no plugin/fork no plugin/no for plugin, only when fork and plugin
[truncated_status.xlsx](https://github.com/Ensembl/ensembl-vep/files/3121359/truncated_status.xlsx)

**Comment by helensch** [comment]
Hi

Thank you for the summarized results. I am currently looking into. 

Please could you let me know  which VEP version, assembly and cache you are using.

Did you try running with only single plugin at at time to see if truncation occurred with the Downstream or the Wildtype plugin?
Helen

**Comment by aparton** [comment]
Hi,

Thanks for reporting this issue. I’ve had a look at this over the last couple of days and I’m unable to reproduce it unfortunately. I have a couple of questions:

1) Could you please provide a line count for your truncated and non-truncated output files (wc -l <FILE>), so that we can see how much is missing?

2) Wildtype is a plugin that was produced by one of our users, if the issue appears to be Wildtype specific then it will be more challenging for us to debug. Could you confirm if the issue still occurs if you run your query with only the Downstream plugin, and not the Wildtype one?

3) Which version of VEP, and which operating system are you using?

4) Would it be possible for you to provide your input data/a subset of your input data that reproduces the issue?

Kind Regards,
Andrew

**Comment by tdw1221** [comment]
Hi,

    Here is my VEP  version information:

  **Versions:
  ensembl              : 94
  ensembl-funcgen      : 94
  ensembl-io           : 94
  ensembl-variation    : 94
  ensembl-vep          : 94.5**

   And this is the cache I use: **94_GRCh37**

   The version of Wildtype is 1.0, I got to know this by looking at its Wildtype.pm file, not sure if this is the right way.

    I summarized the total lines in the attached file, I'm reproducing the error from problematic setup (fork + plugins, I accidentaly deleted it before) and will keep you posted
[truncated_status.xlsx](https://github.com/Ensembl/ensembl-vep/files/3148582/truncated_status.xlsx)

**Comment by tdw1221** [comment]
I will run another job with only downstream and get back to you

**Comment by tdw1221** [comment]
Unfortunately this time I could not reproduce the truncation issue, previously I have reproduced it multiple times but ended up with deleting all the output files. However, I still found there are minor total lines difference when running with different setup (see attached), is this expected? If not, I guess this might due to truncation else where in the file, not the specific entry I mentioned earlier.

[truncated_status.xlsx](https://github.com/Ensembl/ensembl-vep/files/3174275/truncated_status.xlsx)

**Comment by aparton** [comment]
Hi,

The difference of 1/2 lines in VEP output will be caused by the inclusion of header lines related to the plugins, this is expected behaviour.

Unfortunately, without reproduction steps then there's not a lot that we can do. I suspect that the issue is a particular variant that's causing VEP/Wildtype some problems, however that's just a hunch right now. If you're able to provide the input data and steps taken that has led to this issue, then I'm happy to take another look.

Sorry that I couldn't be of more help.

Kind Regards,
Andrew
