### ISSUE TITLE
wrong hgvsg

### ISSUE THREAD

**Issue by stellaoh** [Ensembl/ensembl-vep#442]
Hi, I am vep (vep94)user. 

In my deletion variant, there are several problems. 

This is vcf format
chr     pos                  Ref   Alt
13      20041493        TA      T 

I think hgvsg of this mutation is 13.g.20041494delA
But in my vep.vcf, 
hgvsg of this variant is "13:g.20041511del".

I don't know why my hgvsg is weird.
I want this format. 

chrNo+.+g+.+Startpos+del/ins+Alt base (like 13.g.20041494delA)

cf. in vep88, hgvsg of this variant is 13.g.20041494delN

**Comment by aparton** [comment]
Hi,

I’ve had a look at this variant this morning, the HGVS reported is correct. To minimise ambiguity, HGVS reports insertions/deletions in repeated regions at the most 3’ location possible (http://varnomen.hgvs.org/recommendations/general/ <http://varnomen.hgvs.org/recommendations/general/>). As shown here (http://grch37.ensembl.org/Homo_sapiens/Location/View?r=13:20041493-20041515;db=core <http://grch37.ensembl.org/Homo_sapiens/Location/View?r=13:20041493-20041515;db=core>), your variant is in a repeated region of As. Our HGVS code shifts this variant as 3’ as possible, and reports the deletion at the end of this repeated region. 

If you would like to suppress this behaviour, you can add ‘—shift_hgvs 0’ to your command. 

If you have any other questions, please let us know.

Kind Regards,
Andrew

**Comment by stellaoh** [comment]
Thanks a lot!

this option is very helpful for me. 

Thanks 👍 : )

**Comment by stellaoh** [comment]
I executed vep. 

hgvsg of the variant that I questioned is "13:g.20041494del".
Then, I want that the hgvsg of the variant is "13:g.20041494delA".

What can I do for that?

**Comment by aparton** [comment]
Hi,

We do not have an option to provide the deleted reference allele within HGVS I’m afraid. You can include this within the VEP output with —show_ref_allele if it helps, but this value will not be added to your HGVS.

Kind Regards,
Andrew

**Comment by stellaoh** [comment]
Hi, 

Thanks for your reply :)



> Hi, We do not have an option to provide the deleted reference allele within HGVS I’m afraid. You can include this within the VEP output with —show_ref_allele if it helps, but this value will not be added to your HGVS. Kind Regards, Andrew
> […](#)
