### ISSUE TITLE
about ExAC

### ISSUE THREAD

**Issue by stellaoh** [Ensembl/ensembl-vep#443]
Hello, I have run vep with ExAC_nonTCGA.r0.3.1.sites.vep.vcf.gz

I acquired this annotation result

ex) 

20 | 25507019 | . | T | TA | . | PASS | DP=126;GPV=1E0;SPV=3.4402E-10;SS=3;SSC=94;CSQ=A | intron_variant | MODIFIER | NINL | ENSG00000101004 | Transcript | ENST00000278886 | protein_coding | 2/ 23 | ENST00000278886.6:c.180+24dup |   |   |   |   | rs11087523 |   | -1 |   | insertion | HGNC | 29163 | YES |   |   | CCDS33452.1 | ENSP00000278886 | Q9Y2I6 |   | UPI0000206B64 |   |   |   |   |   | 20:g.25507019_25507020insA | 0.1064 | 0.2595 | 0.0648 | 0.0704 | 0.0596 | 0.0143 | 0.1996 | 0.03756 | 0.005098 | 0.05252 | 0.001052 | 0.00192 | 0.003073 | 0.00469 | 0.003301 | 0.002706 | 0.001237 | 0.2595 | AFR |   |   |   |   |   |   |   |   | **0.0459** | 0.176 | 0.0291 | 0.0485 | 0.0527 | 0.0535 | 0.0529 | 0.0446 | 0.0395 | 0.0351 | 0.016 | A | intron_variant | MODIFIER | NINL | ENSG00000101004 | Transcript | ENST00000422516 | protein_coding | 2/22 | ENST00000422516.1:c.180+24dup |   |   |   |   | rs11087523 |   | -1 |   | insertion | HGNC | 29163 |   |   |   |   | ENSP00000410431 | Q9Y2I6 |   | UPI000040F9F7 |   |   |   |   |   | 20:g.25507019_25507020insA | 0.1064 | 0.2595 | 0.0648 | 0.0704 | 0.0596 | 0.0143 | 0.1996 | 0.03756 | 0.005098 | 0.05252 | 0.001052 | 0.00192 | 0.003073 | 0.00469 | 0.003301 | 0.002706 | 0.001237 | 0.2595 | AFR |   |   |   |   |   |   |   |   | **4.71E-05** | 0.000124 | 9.05E-05 | 5.09E-05 |   | 6.97E-05 |   | 3.63E-05 | 5.78E-05 

In this results, 
ExAC values (bold) are different. 

So, I ran filter-vep with "-filter "ExAC_AF < 0.01 or not ExAC_AF"" option, 
the variants are not filtered out. 

Is it ok? 

I can't understand why these ExAC_AFs are different.

**Comment by aparton** [comment]
Hi,

I’ve taken a look at this issue this morning, and it looks like there are a couple of factors at play here. It looks like there’s a bug in the ExAC plugin.

1) We recommend to users that they use gnomAD frequency data as built into our cache files, as an alternative to ExAC as described here: https://www.ensembl.org/info/docs/tools/vep/script/vep_example.html <https://www.ensembl.org/info/docs/tools/vep/script/vep_example.html>. However, if you specifically require the older ExAC data for your analyses, this may not help you.

2) It looks like there’s a bug in the ExAC plugin that shows the frequency data for the wrong alternative allele in certain circumstances. I’ll prepare a fix for the plugin, and I’ll let you know when it’s in place.

Thanks for reporting this issue to us.

Kind Regards,
Andrew

**Comment by stellaoh** [comment]
Thanks a lot :)

I'll wait for your reply.

**Comment by aparton** [comment]
Hi @stellaoh,

We've updated the ExAC.pm plugin, for now you can find the latest version here: https://github.com/Ensembl/VEP_plugins/blob/master/ExAC.pm

Kind Regards,
Andrew
