### ISSUE TITLE
VEP output differences in txt vs vcf format, fixed columns don't show up in txt file

### ISSUE THREAD

**Issue by audyavar** [Ensembl/ensembl-vep#444]
Hello - 

I am new to VEP. I successfully ran VEP on an ensemble vcf (ensemble of 3 variant callers) with the commands below. I am a bit confused about the output. If I output the data as txt, then I get all the genes broken down by the various SNP Ids (that's my guess) whereas as VCF, I see exactly the same number of rows as input vcf. Is this assumption correct? I like the text file version as it is easy to manipulate as well as look at the individual SNPs rather than being combined at the gene level. 

Also the vcf file contains all the original information as the input vcf, while the text file does not give me the AF/DP columns anymore which I want to use to calculate allele frequency to filter my variants.  The reason I ask for this is that the fixed columns also give me the information about which variants were predicted by more than 1 caller, which I would like to take into account while prioritizing my variants. Is there a way I can get the fixed columns in the text file to enable me to compute the allele frequency?

/mnt/ensembl-vep/vep \
--cache \
--input_file $mypath/vep_snvs/mutations_ensemble.vcf.gz \
--format "vcf" \
--force_overwrite \
--output_file $mypath/vep_snvs/mutations_ensemble-vep.vcf \
--vcf \
--compress_output gzip \
--species homo_sapiens \
--fork 32 \
--verbose \
--terms SO \
--protein  \
--symbol \
--ccds \
--canonical \
--check_existing \
--sift b \
--polyphen b  \
--gene_phenotype \
--pubmed \
--variant_class \
--uniprot \
--tsl \
--appris \
--af \
--max_af \
--af_1kg \
--af_esp \
--af_gnomad \
--numbers \
--regulatory

**Comment by aparton** [comment]
Hiya,

Thank you for your interest in VEP. Default VEP output provides annotations for locations where input variants overlap with Ensembl 'features' (e.g. Transcripts or RegulatoryFeatures). Our VCF output will combine annotations for all overlapping features onto one line, matching the input VCF. You can find more information on our output formats here: https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#defaultout

Additionally, using an input VCF with the VEP --vcf flag will leave the file as unchanged as possible, other than the inclusion of the CSQ field and the addition of header lines. We do not keep annotations from other sources by default, however you could add this information into your output file by using our custom annotation functionality, that you can read more about here: https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html

Kind Regards,
Andrew
