### ISSUE TITLE
MSG: Missing reference or alternate sequence

### ISSUE THREAD

**Issue by sigven** [Ensembl/ensembl-vep#445]
Hi,

I have successfully annotated a [VCF file](https://www.dropbox.com/s/od4qpp9agt9cnie/test_civic.grch38.vcf?dl=0) through the VEP web interface (grch38). From the summary statistics obtained through the web, it seems all (809) variants were processed, i.e. no variants were filtered out. When I annotate the same VCF with my local VEP installation (v96), I do however get the following error message:

`-------------------- EXCEPTION --------------------
MSG: Missing reference or alternate sequence
STACK Bio::EnsEMBL::Variation::Utils::Sequence::trim_sequences /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Variation/Utils/Sequence.pm:943
STACK Bio::EnsEMBL::Variation::Utils::Sequence::get_matched_variant_alleles /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Variation/Utils/Sequence.pm:1125
STACK Bio::EnsEMBL::VEP::AnnotationType::Variation::compare_existing /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationType/Variation.pm:176
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::VariationTabix::_annotate_pm /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/VariationTabix.pm:239
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::VariationTabix::annotate_InputBuffer /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/VariationTabix.pm:120
STACK Bio::EnsEMBL::VEP::Runner::_buffer_to_output /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:402
STACK (eval) /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:663
STACK Bio::EnsEMBL::VEP::Runner::_forked_process /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:657
STACK Bio::EnsEMBL::VEP::Runner::_forked_buffer_to_output /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:488
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:361
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:202
STACK toplevel /opt/vep/src/ensembl-vep/vep:218
Date (localtime)    = Sun May  5 11:51:06 2019
Ensembl API version = 96
---------------------------------------------------`

These are the full set of options I am using:

`vep --input_file <input_vcf> --output_file <output_vcf> --vcf --check_ref --flag_pick_allele --pick_order canonical,appris,tsl,biotype,ccds,rank,length --force_overwrite --species homo_sapiens --assembly GRCh38 --offline --fork 4 --hgvs --verbose --dont_skip --failed 1 --af --af_1kg --af_gnomad --variant_class --domains --symbol --protein --ccds --uniprot --appris --biotype --canonical --gencode_basic --cache --numbers --total_length --allele_number --no_stats --no_escape --allow_non_variant --xref_refseq --dir <data_dir> --buffer_size 500 --check_existing --cache_version 96 --fasta <data_dir>/homo_sapiens/96_GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz`

And this is the version of VEP that I am running locally:

Versions:
ensembl              : 96.7a35428
ensembl-funcgen      : 96.9c3a0cd
ensembl-io           : 96.6e65b30
ensembl-variation    : 96.ab5ff26
ensembl-vep          : 96.0

Any ideas what is going on here?

regards,
Sigve

**Comment by ens-lgil** [comment]
Dear @sigven,

Many thanks for the detailled reports.
We are currently looking at it and we will get back to you when we will find the source of this issue.

Best regards,
Laurent

**Comment by ens-lgil** [comment]
Dear @sigven,

We found the source of the issue and we pushed a fix in one of the VEP dependency (ensembl-variation).
Please, could you reinstall VEP 96 ?

Best regards,
Laurent

**Comment by sigven** [comment]
Dear @ens-lgil,
Thanks a lot for the effort! I will re-install tonight and get back to you if the issue is not resolved. You can close the issue meanwhile.

**Comment by sigven** [comment]
Works fine, thanks for the fix @ens-lgil!
