### ISSUE TITLE
VEP96 installation/run error

### ISSUE THREAD

**Issue by sbberes** [Ensembl/ensembl-vep#446]
I am trying to use VEP on bacterial genomes, largely for its ability to predict the consequences of indels.  I have installed VEP Ensembl API version 96 on a workstation with Ubuntu 18.10 OS.  Running the "perl INSTALL.pl" install script on vep from github completes with out giving any error messages.  I have not downloaded any cache or fasta files with the install, as they primarily seem to be for eukaryotic and not bacterial organism.  I have installed a few of the plugins.  To use VEP with bacterial data, I have: 1) generated a file listing polymorphism in ensembl format called relative to a bacterial reference genome -- 2) Used the example commands supplied in the manual to sort, bgzip compress, and tabix index a gff v3 input feature annotation file -- 3) and have a corresponding genome fasta file.
  When running the command: "vep -i polys.txt --gff bac.gff.gz --fasta bac.fasta" -- I get the EXCEPTION  - MSG: ERROR: Cannot use format gff without Bio::DB::HTS::Tabix module installed.  Googling the error takes me to issue #30.  Following the suggestions on issue #30 I have checked to confirm the installations of htslib and Bio::DB::HTS v3. Using the command: perl -e "use Bio::DB::HTS::Tabix" perl finds the module.  Despite this running vep gives the same error msg.
  I am now at a loss as to how to progress further.  I do not know where vep/perl is looking that it cannot find Bio::DB::HTS::Tabix.  I have run installations using anaconda, but the version installed v87 does not seem to have the use of gff files for polymorphism annotations implemented, this appears to be a feature added in v88.  It would be nice if the vep conda package could be updated to the latest version v96.  It would be nice if you could include more information in the vep manual for the setup and use of vep for prokaryotic organisms.  The bacterial genome that I am working with is not present in Ensembl Bacteria and the Web version of VEP does not seem to have the option of providing the .vcf .gff.gz and .fasta files that the commandline version of VEP supposedly accepts.  Looking for any guidance or additional insight I can get.
Thanks in advance for any help.
Steve Beres

**Comment by aparton** [comment]
Hi Steve,

In current versions of VEP, the installer will put Bio::DB::HTS::Tabix in ensembl-vep/Bio/DB/HTS/Tabix. I’m not sure if this is the same for version 87, however we have made significant changes to the installation process since then. 

While conda/bioconda installations of VEP exist, they are not maintained by us and as such not fully supported. However, you can get an up-to-date copy of VEP through BioConda here: https://anaconda.org/bioconda/ensembl-vep/files <https://anaconda.org/bioconda/ensembl-vep/files>. You can find official instructions for download and installation here: https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html <https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html>

Updating to version 96 should resolve your issue. If not (and you’re using Perl 5.26), then adding your ensembl-vep directory to your PERL5LIB variable should help VEP find Bio::DB::HTS::Tabix.

Regarding updates to our documentation, this is something that we’re actively looking at and we’ll keep making improvements over the next few months.

Kind Regards, 
Andrew

**Comment by sbberes** [comment]
Andrew,
                Thank you for your prompt response.  I will try the things you have suggested, and get back to you with the results.
Regards,
SBB
*********************************
Stephen B. Beres Ph.D.
Professor of Pathology and Genomic Medicine,
Institute for Academic Medicine
Director of Microbial Informatics,
Center for Molecular and Translational Human Infectious Disease Research
Houston Methodist Research Institute
6670 Bertner Ave.
Houston, TX 77030
MS RIB R6-111
(713) 441-5067
sbberes@houstonmetodist.org

**Comment by sbberes** [comment]
Andrew,
                I used the link that you sent and installed VEP v96 using anaconda.  The installation seems to work, in that VEP accepts the input polys.txt (ensemble format list of variants), bac.gff.gz and bac.fasta files – and generates output files.  However the output files do not have the polymorphism annotation information that I am anticipating.  That is I am not getting any consequences for SNPs or indels located within CDSs.  That is although I have polymorphisms that are present/positioned within what is annotated as a gene/exon/CDS in the input .gff file, the VEP output identifies virtually all of the polymorphisms as being intergenic.  This is just nuts for a bacterial genome as about 85% of the genome is composed of coding sequences.  I have tried using .gff files downloaded from Genbank (gff v3), or generated from .gbk file using Artemis, or from .gbk file using bioperl script bp_genbank2gff3.pl.  No matter what .gff I provide I get no predicted consequences as they relate to CDSs.  If I use the –cds_only option then the VEP output has only header lines and no polymorphism/variants annotations.  Again looking for any help or insights that you can provide.
Regards,
SBB

**Comment by sbberes** [comment]
Andrew,
                Please ignore my most recent email.  The problem was getting the right gbk to gff conversion.  Although all of the gff files are supposed to be gff3 compliant, not all of them worked with VEP.
Regard,
Steve

**Comment by aparton** [comment]
Hi Steve, 

Excellent, I’m glad to hear that it’s now working. As I’m sure you’ve discovered, VEP requires a particular format with GFF files, as defined here: https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff_req <https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff_req>

If you have any other issues or questions, please let us know.

Kind Regards,
Andrew

**Comment by Mfpfox** [comment]
Hi, i have vep96 installed and would like to use custom annotations.  However i am getting the following errors

I am using a conda env.  I downloaded the htslib from git and trying to manually install.  I am now just trying to go through the INSTALL code and main problem is it saying it cant compile 
Building Bio-DB-HTS
Error: no compiler detected to compile 'lib/Bio/DB/HTS.c'.  Aborting

Please help :)

from ./vep : 
(perlyclone) mariapalafox@marias-mbp-2:~/Desktop/ensembl-vep$ ./vep -i data/clinvar/cv_silent_table_cleaned.txt -o data/clinvar/cv_silent_CCRvep96.txt --dir /Users/mariapalafox/.vep/ --merged --offline --custom data/CCR/ccrs.autosomes.v2.20180420.bed.gz,CCR,bed,exact,0 --gencode_basic --fields "Uploaded_variation,Location,Allele,Gene,CCR,REFSEQ_MATCH,SOURCE"
2019-05-28 20:04:30 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this

-------------------- EXCEPTION --------------------
MSG: ERROR: Cannot use format bed without Bio::DB::HTS::Tabix module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /Users/mariapalafox/Desktop/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:162
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /Users/mariapalafox/Desktop/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:228
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /Users/mariapalafox/Desktop/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:93
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /Users/mariapalafox/Desktop/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /Users/mariapalafox/Desktop/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /Users/mariapalafox/Desktop/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel ./vep:218
Date (localtime)    = Tue May 28 20:04:30 2019
Ensembl API version = 96
---------------------------------------------------
From INSTALL.pl
(perlyclone) mariapalafox@marias-mbp-2:~/Desktop/ensembl-vep$ perl INSTALL.pl --AUTO l
Installation on OSX requires that you set up some paths before running this installer.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

PLEASE REMEMBER TO 
1. add /Users/mariapalafox/Desktop/ensembl-vep/htslib to your DYLD_LIBRARY_PATH environment variable

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Attempting to install Bio::DB::HTS and htslib.

>>> If this fails, try re-running with --NO_HTSLIB

 - checking out HTSLib
fatal: destination path 'htslib' already exists and is not an empty directory.
 - building HTSLIB in ./htslib
In /Users/mariapalafox/Desktop/ensembl-vep/htslib
make: Nothing to be done for `all'.
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.9 - moving files to ./biodbhts
 - making Bio::DB:HTS
Can't exec "x86_64-apple-darwin13.4.0-clang": Not a directory at /anaconda3/envs/perlyclone/lib/5.26.2/ExtUtils/CBuilder/Base.pm line 331.
Warning: ExtUtils::CBuilder not installed or no compiler detected
Proceeding with configuration, but compilation may fail during Build

Checking prerequisites...
  requires:
    !  Bio::Root::Version is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Run 'Build installdeps' to install missing prerequisites.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.9'
Building Bio-DB-HTS
Error: no compiler detected to compile 'lib/Bio/DB/HTS.c'.  Aborting
ERROR: Shared Bio::DB:HTS library not found

**Comment by aparton** [comment]
Hi,

I believe that you are attempting to install VEP on MacOS? It looks like there is a problem with your XCode installation - installing VEP on MacOS is a little trickier and requires additional steps, as can be found here: https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#macos

If you have any other questions, please let me know.

Kind Regards,
Andrew

**Comment by Mfpfox** [comment]
Thanks Andrew for reply!

I went through that version of the install and had problems. Im on Mojave, and the issue i ran into the first time following the instructions was with DNS cache and a issue with curl.  I solved it by clearing DNS cache and deleting curl from my conda environment, which defaults to using the system version and then deleted my perlbrew installs.  Everything works in VEP except when I am trying to do the --custom flag with a bed file.  Is there a solution to my problem that involves using the conda perl environment i have created and no perlbrew, or has Mojave never been tested following those instructions?

**Comment by Mfpfox** [comment]
output of gcc -v: 
(vepHTS) mariapalafox@Marias-MacBook-Pro-2:~/Desktop/ensembl-tools-release-81/scripts/variant_effect_predictor/data/clinvar$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by aparton** [comment]
Hi,

I haven’t tested it with a Conda Perl environment, although I don’t expect any issues when using that instead of Perlbrew. Could you please provide details of the issue you’re seeing when you try the —custom flag?

Thanks,
Andrew

**Comment by Mfpfox** [comment]
So here is the command: 
./vep -i data/clinvar/cv_silent_table_cleaned.txt -o data/clinvar/cv_silent_CCRvep96.txt \
--dir /Users/mariapalafox/.vep/ --merged --offline \
--custom data/CCR/ccrs.autosomes.v2.20180420.bed.gz,CCR,bed,exact,0 --gencode_basic \
--fields "Uploaded_variation,Location,Allele,Gene,CCR,REFSEQ_MATCH,SOURCE"
 

I have a Bio/ sub directory and i have also tried to manually install HTS and htslib (no idea what i am honestly doing) and these are in my folder as biodbhts/ (where the HTS sub directory is) and htslib (not sure what this is for but i downloaded from git)
![image](https://user-images.githubusercontent.com/41930603/58584186-96a21800-820a-11e9-9ce2-79a58d1131bd.png)

the error from code that i get is : 
2019-05-29 12:06:55 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this

-------------------- EXCEPTION --------------------
MSG: ERROR: Cannot use format bed without Bio::DB::HTS::Tabix module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /Users/mariapalafox/Desktop/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:162
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /Users/mariapalafox/Desktop/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:228
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /Users/mariapalafox/Desktop/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:93
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /Users/mariapalafox/Desktop/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /Users/mariapalafox/Desktop/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /Users/mariapalafox/Desktop/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel vep:218
Date (localtime)    = Wed May 29 12:06:55 2019
Ensembl API version = 96


I went so far as putting the HTS folder where i see the Tabix/ and Tabix.pm are into teh BIo/ that VEP installed but this did not solve problem.

**Comment by Mfpfox** [comment]
https://github.com/Ensembl/Bio-DB-HTS
I also was getting errors during manual install of HTS regarding no compiler found...and tried following these instructions from link regarding CFLAGS and DFLAGS.  in my htslib/ subdirectory i looked at the makefile and that the flags were already there.  I am currently trying to get over this set:
Then do "make clean; make" in the Samtools directory to recompile the
library. After this you should be able to build this module without
errors.

here is the info from link : 


### TROUBLESHOOTING

If you encounter problems during compiling, you may need to edit
Build.PL so that extra_compiler_flags matches the CFLAGS and DFLAGS
settings in the HTSlib Makefile.  Here are some common problems:

1. When building this module, you get an error like the following:
relocation R_X86_64_32 against `a local symbol' can not be used when
making a shared object; recompile with -fPIC

To fix this, edit the Makefile in the Samtools distribution by adding
"-fPIC" to the CFLAGS line. While you're at it, you may also wish to
get rid of a bunch of unused variable warnings that appears under
recent versions of gcc. The modified CFLAGS will look like this

  CFLAGS= -g -Wall -Wno-unused -Wno-unused-result -O2 -fPIC #-m64 #-arch ppc

Then do "make clean; make" in the Samtools directory to recompile the
library. After this you should be able to build this module without
errors.

**Comment by Mfpfox** [comment]
trying to install HTS error: 

(vepHTS) mariapalafox@marias-mbp-2:~/Desktop/ensembl-vep$ perl INSTALL.pl --AUTO l
Installation on OSX requires that you set up some paths before running this installer.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

PLEASE REMEMBER TO 
1. add /Users/mariapalafox/Desktop/ensembl-vep/htslib to your DYLD_LIBRARY_PATH environment variable

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Attempting to install Bio::DB::HTS and htslib.

>>> If this fails, try re-running with --NO_HTSLIB

 - checking out HTSLib
fatal: destination path 'htslib' already exists and is not an empty directory.
 - building HTSLIB in ./htslib
In /Users/mariapalafox/Desktop/ensembl-vep/htslib
make: Nothing to be done for `all'.
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.9 - moving files to ./biodbhts
 - making Bio::DB:HTS
Can't exec "x86_64-apple-darwin13.4.0-clang": No such file or directory at /anaconda3/envs/vepHTS/lib/5.26.2/ExtUtils/CBuilder/Base.pm line 331.
Warning: ExtUtils::CBuilder not installed or no compiler detected
Proceeding with configuration, but compilation may fail during Build

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.9'
Building Bio-DB-HTS
Error: no compiler detected to compile 'lib/Bio/DB/HTS.c'.  Aborting
ERROR: Shared Bio::DB:HTS library not found

**Comment by aparton** [comment]
Hi,

Installing Bio::DB::HTS manually seems a fair strategy when seeing that error message. It looks like the issue with making Bio::DB::HTS is conda specific (it cannot find a C compiler to build Bio-DB-HTS), which is not something that we have a lot of expertise of here, and we do not officially support it.

We do however have some instructions on how to install Bio::DB::HTS manually that can be found here: https://www.ensembl.org/info/docs/api/api_installation.html - it shouldn't require additional configuration on Mojave. Additionally, we do have a docker image that may be an option for you: https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker

Kind Regards,
Andrew

**Comment by kjohnsen** [comment]
Just for the record, I've had problems with the Tabix module as well, having tried both manual installation and perlbrew installation. I've checked and seen all the files are there that should be, and my @INC seems to be pointing correctly at where I've installed. But to no avail.

**Comment by aparton** [comment]
Hi,

@Mfpfox - I'm going to close this ticket now, if there's anything else that we can do to help then please feel free to reopen it. 

@kjohnsen - Thank you for this report. If you have a specific case that you would like us to take a look at, then please feel free to open a new ticket.

Kind Regards,
Andrew
