### ISSUE TITLE
excessive memory usage during analysis

### ISSUE THREAD

**Issue by matthdsm** [Ensembl/ensembl-vep#45]
Hi,

We're trying to annotate exome vcf using the latest version of vep, but we're experiencing huge memory inefficiencies.

The following command running on a single core was using 16GB of memory before crashing.
Any idea what could be wrong? The README states the new vep should be quite memory efficient.

```
vep \
  --vcf \
  -o GiaB-vep88.vcf \
  -i Giab.vcf.gz \
  --force_overwrite \
  --species homo_sapiens \
  --fasta ./Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz \
  --cache \
  --no_stats \
  --offline \
  --dir ./vep/ \
  --hgvs \
  --shift_hgvs 1 \
  --total_length \
  --no_stats \
  --symbol --numbers --biotype --total_length --canonical --gene_phenotype --ccds --uniprot --domains --regulatory \
  --protein --tsl --appris --af --max_af --af_1kg --af_esp --af_exac --pubmed --variant_class
```

Thanks!
M

**Comment by willmclaren** [comment]
If your input is exome data, you may try modifying the buffer parameter, e.g. `--buffer 500`, or even lower. This reduces the number of variants read into memory (default is 5000) and therefore the amount of transcript and feature data read into memory.

If you're still seeing runaway memory, it may be there is a memory leak somewhere, in which case it would be useful if you could share your input file.

**Comment by matthdsm** [comment]
Hi,
Thanks for the reply, I'm testing right now with the buffer size set to 500 and I'm seeing a memory usage of about 2GB, which still seems a lot.
For example, we have several other vep processes running the "old" vep, on 7 cores, which only use about 2GB.

I've included our test input file here: [Giab.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/955036/Giab.vcf.gz). Perhaps this may help pinpoint the issue.

Thanks for the help
M

**Comment by willmclaren** [comment]
Just checking that you're using the `homo_sapiens_vep_88_GRCh38.tar.gz` cache?

**Comment by matthdsm** [comment]
yep, freshly installed this morning

**Comment by willmclaren** [comment]
Have you tabix-converted the cache?

http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache (search for "Convert with tabix")

**Comment by matthdsm** [comment]
I installed it with the --CONVERT flag on, so I do suppose the cache was converted. I can rerun the convert cache script, if you think that might be the cause.

M

**Comment by willmclaren** [comment]
It should tell you if it was converted already.

I'm running the same command as yours, with a buffer size of 500, and the memory usage is around 375kb and only creeping up small amounts occasionally.

**Comment by matthdsm** [comment]
I'm re running the cache conversion right now. I'll let you know when it's finished and I've run some more tests.

Thanks a lot for the help!
M

**Comment by matthdsm** [comment]
Hi Will

Turns out the convert step failed during installation. Reconverting the cache solved our issue!
+- 500mb/fork with the default buffer size.

Thanks a lot again!
M
