### ISSUE TITLE
Discrepancy betweent VEP SIFT and SIFT 

### ISSUE THREAD

**Issue by thedam** [Ensembl/ensembl-vep#455]
Hi,
using VEP for GRCh37 to check the variant:
`17 10543463 . TG CA . . .`
The [output](http://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Results?db=core;tl=reyxO4LhdU5f0QTb-5319445) shows the SIFT score is` 0.11` for transcript `ENST00000226209`

pasting the same coordinates 
`17,10543463,10543463,-1,TG,CA `
into proper SIFT service: 
https://sift.bii.a-star.edu.sg/www/SIFT_indels2.html
gives the different score: `0.858` for the same transcript. 

Why?

**Comment by ens-lgil** [comment]
Dear @thedam,

VEP uses SIFT version 5.2.2 (cf. [VEP doc](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache_content) or [Ensembl Variation doc](https://www.ensembl.org/info/genome/variation/prediction/protein_function.html#sift)) with UniRef90 (release 2014_11), whereas SIFT seems to use the version 6.2.1 on its website (with a different protein database I presume).

I believe this is what explains the difference in the SIFT score.

Best regards,
Laurent

**Comment by thedam** [comment]
mhm
