### ISSUE TITLE
CDF library: VEP from latest docker image does not run

### ISSUE THREAD

**Issue by PedroBarbosa** [Ensembl/ensembl-vep#457]
Hello,

I'm unable to run VEP using the latest image version. Tested with two different datasets, same error. Any help ?

`CDF.c: loadable library and perl binaries are mismatched (got handshake key 0xdb00080, needed 0xde00080)`

Vep version:
```
Versions:
  ensembl              : 96.af6c2b8
  ensembl-funcgen      : 96.9c3a0cd
  ensembl-io           : 96.6e65b30
  ensembl-variation    : 96.1f67fdd
  ensembl-vep          : 96.0
```

Command used:
`
srun shifter -V=/mnt/nfs/lobo/IMM-NFS/ensembl_vep:/media --image=ensemblorg/ensembl-vep:latest vep --force_overwrite --stats_text --hgvs --hgvsg --pubmed --check_existing --cache --dir /media/cache --offline --sift b --polyphen b --numbers --regulatory --variant_class --cache_version 96 -a GRCh37 --fasta /media/cache/homo_sapiens/96_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz --plugin dbscSNV,/media/custom_data/dbscSNV/hg19/dbscSNV1.1_hg19.txt.gz --plugin ExACpLI,/media/custom_data/ExACpLI/ExACpLI_values.txt --plugin GeneSplicer,/media/custom_data/genesplicer/bin/linux/genesplicer,/media/custom_data/genesplicer/human --plugin MaxEntScan,/media/custom_data/MaxEntScan --plugin SpliceRegion --plugin Condel,/media/custom_data/condel,b --plugin Carol --plugin CADD,/media/custom_data/cadd/hg19/v1.4/whole_genome_SNVs.tsv.gz,/media/custom_data/cadd/hg19/v1.4/InDels.tsv.gz --plugin dbNSFP,'consequence=ALL',/media/custom_data/dbNSFP/hg19/dbNSFP4.0b1a_hg19.txt.gz,GERP++_RS,phyloP30way_mammalian,29way_logOdds,phastCons30way_mammalian,MutationAssessor_score,SIFT4G_score,SIFT_score,Polyphen2_HDIV_score,Polyphen2_HVAR_score,MutationTaster_score,FATHMM_score,fathmm-MKL_coding_score,PROVEAN_score,CADD_phred,DANN_score,Eigen-pred_coding,Eigen-PC-phred_coding,MetaSVM_score,MetaSVM_pred,MetaLR_score,MetaLR_pred,REVEL_score,integrated_fitCons_score,LRT_score,LRT_pred,MutPred_score,VEST4_score,M-CAP_score,LINSIGHT --custom /media/custom_data/gerp/All_hg19_RS.bw,GERP_vep,bigwig,exact,0 --custom /media/custom_data/gerp/All_hg19_RS.bw,GERP_vep_all,bigwig,overlap,0 --custom /media/custom_data/phyloP100/hg19.100way.phyloP100way.bw,phyloP_vep,bigwig,exact,0 --custom /media/custom_data/phastcons100/hg19.100way.phastCons.bw,phastCons_vep,bigwig,exact,0 --custom /media/custom_data/gnomAD/hg19/gnomAD_v2.1_justImportantFields.vcf.gz,gnomADg,vcf,exact,0,AF,AF_nfe,AF_nfe_nwe --af --af_1kg --af_esp  --max_af --af_gnomad --pick --pick_order rank -i 
`
Best,
Pedro

**Comment by ens-lgil** [comment]
Dear @PedroBarbosa,

I can't reproduce it when I run the latest Docker VEP image.
Did it work on an older version of Docker VEP ?
Could it be something to do with `shifter` and/or the interaction between VEP docker and shifter ?
Or an update on your machine ?

Best regards,
Laurent

**Comment by PedroBarbosa** [comment]
Dear @ens-lgil ,

I am going to check that with the sysadmin team of the cluster.  
I'll write back in case of any update.
Best,
Pedro

**Comment by PedroBarbosa** [comment]
Dear @ens-lgil ,

Problem solved. As it appears this last VEP image was produced using Ubuntu 18, there were issues with the CDF perl module compiled in our cluster (older version).  

I entered within the image with shifter, compiled the CDF module with the latest perl and moved the compiled CDF to my local directory with perl libs. It's working now.

Best,
Pedro

**Comment by ens-lgil** [comment]
Dear @PedroBarbosa,

I am glad that you found the issue and solved it!

Best regards,
Laurent
