### ISSUE TITLE
VEP 96 with gnomAD genome r2.1

### ISSUE THREAD

**Issue by lyijin** [Ensembl/ensembl-vep#458]
hi there,

firstly, thanks for updating VEP 96 with gnomAD exome r2.1!

i'm interested in running VEP 96 with gnomAD **genome** r2.1, but the instructions available on the website (http://asia.ensembl.org/info/docs/tools/vep/script/vep_example.html#gnomad) seem to be outdated, and i'm not sure how to go about modifying it for the newest version.

we're asked to run 
```
./vep -i examples/homo_sapiens_GRCh38.vcf --cache \
--custom gnomad.genomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF_AFR,AF_AMR,AF_ASJ,AF_EAS,AF_FIN,AF_NFE,AF_OTH
```

note the r2.0.1 file suggested in the command. as the exome's updated to r2.1, i thought it's better to use genome r2.1 as well--unfortunately, i wasn't able to find an analogous file for r2.1, as gnomad genome r2.1 seems to have a file per chromosome:
ftp://ftp.ensembl.org/pub/data_files/homo_sapiens/GRCh38/variation_genotype/gnomad/r2.1/genomes/

should i modify the --custom flag take in multiple files? the explanation of the flag doesn't make it clear: https://asia.ensembl.org/info/docs/tools/vep/script/vep_custom.html

one hack would be to merge all *.vcf.gz files together and regenerate the index, but i'm unsure whether that'd work, as the VCF headers would end up interspersed within the concatenated compressed file.

also, i noticed that there's a huge size difference between genome r2.0.1 (26 GB, can be found at ftp://ftp.ensembl.org/pub/data_files/homo_sapiens/GRCh38/variation_genotype/) and r2.1 (351.7 GB combined). oof. if i'm only interested in the gnomAD genome MAX_AF and MAX_AF_POPS, would there be a quicker way to extract these info from... other methods?

i'm going down this rabbit hole because i'm dealing with a SNP with a massive difference between exome MAX_AF (0.02857) and genome MAX_AF (0.7830).
https://gnomad.broadinstitute.org/variant/7-143339957-G-T?dataset=gnomad_r2_1

i'm not sure what the underlying reason is, perhaps technical? i wanted to annotate all of my other variants of interest (~10k) to check whether this disparity was present in other variants as well (hopefully not!).

thanks! sorry for the wall of text.

**Comment by at7** [comment]
Hi @lyijin,

VEP's custom annotation doesn't support a wildcard style annotation for several chromosomes. This is a new feature we will definitely consider adding in a future release. For now you could create a custom annotation flag for each chromosome. Another option is to concatenate the VCF files. We recently had a request for hosting concatenated files but had to decline for reasons explained in the thread. However, they provided a recipe for concatenating gnomAD VCF files which you hopefully find helpful. Please follow the [link](https://lists.ensembl.org/pipermail/dev_ensembl.org/2019-May/013346.html) for further information. As for the increase in size the gnomAD team provided a [blog post](https://macarthurlab.org/2018/10/17/gnomad-v2-1/) which explains the increase well. I would also recommend that you contact them for further information on the frequency discrepancy you noticed for your variant of interest. Please let me know if you have any more questions related to this issue.

Thank you,
Anja

**Comment by lyijin** [comment]
thanks for the reply, and for the helpful links--looks like my google-fu is weak.

i've checked out gnomAD's download page, the slimmed down files have yet to be uploaded there (as of 25/5/19). while i could generate the slimmed files myself by following the recipe posted, i'm still a bit reluctant to download 400+ GB just to parse genome MAX_AF values.

my supervisor suggested looking at dbSNP--and it turns out that dbSNP has mean MAX_AF across all datasets, but not sub-population MAX_AF. that's good enough for my purposes atm, so i ended up downloading dbSNP 152 (14 GB) and writing a script to parse it:
```
# get the dbSNP 152 bgzipped file
wget "ftp://ftp.ncbi.nih.gov/snp/archive/b152/VCF/GCF_000001405.38.bgz"

# parse out allelic frequencies, then save them as a compressed file
zcat GCF_000001405.38.bgz | grep -v '^#' | cut -f 3,4,5,8 | grep 'FREQ=' | sed 's/RS=.*;FREQ=//' | gzip > dbsnp152.allele_freq.tsv.gz
```

and yep, i'll check with gnomAD re: huge discrepancies in exonic and genomic MAX_AFs. thanks!
