### ISSUE TITLE
cram/cram_io.c:60:18: error: lzma.h: No such file or directory

### ISSUE THREAD

**Issue by smangul1** [Ensembl/ensembl-vep#46]
Hi,

I am trying to install the tools and i am getting this error : 

cram/cram_io.c:60:18: error: lzma.h: No such file or directory

Thanks,
Serghei

**Comment by willmclaren** [comment]
This shouldn't occur if you have an up-to-date checkout of release/87 or release/88.

This error can arise during installation of newer versions of htslib, but VEP's installer has been updated to use a fixed version of htslib that does not depend on lzma.

**Comment by smangul1** [comment]
Thanks! I tried on another cluster and get another error : 


Can't locate Module/Build.pm in @INC (@INC contains: ./Bio /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at Build.PL line 20.

BEGIN failed--compilation aborted at Build.PL line 20.

ERROR: Shared Bio::DB:HTS library not found

**Comment by smangul1** [comment]
i was able to install it using 
perl INSTALL.pl --NO_HTSLIB

You might consider adding this to the manual
