### ISSUE TITLE
Problems annotating chrM

### ISSUE THREAD

**Issue by crkmary** [Ensembl/ensembl-vep#464]
Hi,
I have problems with the annotation on the mitochondrial chromosome.
In my data I have variants,for example:

> chrM	73	.	A	G	
chrM	152	.	T	C	
chrM	217	.	T	C	
chrM	263	.	A	G	
chrM	489	.	T	C	
chrM	750	.	A	G	
I use the v91 version to annotate mitochondrial variants `vep --fork 32 --refseq --force_overwrite --offline --cache --dir vep_cache_file --stats_text --stats_file stats.txt --fasta reference_sequence_file/hg19.fa --input_file input_file/mito.10478.vcf --vcf --output_file mito.10478.vcf.vep.vcf --synonyms chromosome_synonyms_file/chr_synonyms.txt --gene_phenotype --regulatory --symbol --check_existing --af --max_af --af_1kg --af_esp --af_gnomad --pubmed --shift_hgvs 1 --failed 0 --format vcf --sift b --polyphen b --terms SO --freq_pop 1KG_ALL --distance "0" --vcf_info_field "CSQ"`
But , I did not get the gene name with the parameters --symbol . How should I set the parameters to get the gene name?

**Comment by ens-lgil** [comment]
Dear @crkmary,

It seems that we don't have RefSeq data on the mitochondrial chromosome on GRCh37 and consequently, our VEP cache for GRCh37 is empty for the MT chromosome.

Unfortunately the Ensembl refseq annotations are not updated anymore on GRCh37.
If you have a BED file or a GFF file with the RefSeq data on the MT chromosome, you can use it as custom annotation ( [--custom](https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html) ).

Best regards,
Laurent

**Comment by ens-lgil** [comment]
I am closing this issue, but if you have any more questions please feel free to reopen it.

Best regards,
Laurent

**Comment by rbatorsky** [comment]
Hello,

I am seeing something similar for variants on chrM using the GRCh38 cache for version 98.

When use the --refseq flag and cache, chrM variants do not get SYMBOL or transcript annotation, they appear with Consequence "intergenic_variant".

For these same variants, when I switch to the Ensembl/GENCODE cache the chrM variants are annotated with a gene and transcript.

Can you confirm whether chrM trancripts should exist in GRCh38 cache for version 98?

Thank you,
Rebecca

**Comment by at7** [comment]
Dear Rebecca,
I can can confirm that we haven't imported mitochondrial genes from the RefSeq gene set. I'm currently investigating if we can import those genes for release 100. I will get back to you as soon as I know more.

Best wishes,
Anja

**Comment by kvn95ss** [comment]
Hello Anja, 

Has this been implemented in version 103, or it is still under investigation?

**Comment by at7** [comment]
Dear Karthik,
the RefSeq transcripts from the mitochondria are now stored in our RefSeq and merged cache files. However, we noticed a problem which prevents the annotation of those mitochondria RefSeq transcripts in VEP.
Alternatives for annotating your variants with respect to transcripts from the mitochondria are:
--using Ensembl transcripts for example by using the merged cache files
--annotate your variants against a [GFF file](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff)
I will update you here as soon as we have fixed the bug.

Best wishes,
Anja

**Comment by josephhalstead** [comment]
Any updates for this?

**Comment by likhitha-surapaneni** [comment]
Hi @josephhalstead ,

Thank you for your patience. We are currently working on it and will soon be available. We will notify you once we have it in place.

Kind regards,
Likhitha

**Comment by likhitha-surapaneni** [comment]
Hi @josephhalstead ,

Thank you for your patience. We put in a fix to handle the annotation of mitochondria RefSeq transcripts and it is available in release 108.

Please feel free to open a new issue if you have any further queries.

Kind regards,
Likhitha

**Comment by gabrielhim** [comment]
Hello!
I am experiencing the same issue with VEP 108.2. This is my command line:
```
docker run --rm -v $PWD:/data ensemblorg/ensembl-vep:release_108.2 vep \
    --input_file /data/samples/mitochondrial.vcf.gz \
    --dir_cache /data \
    --fasta /data/fasta/Homo_sapiens_assembly38.fasta \
    --force_overwrite \
    --fork 4 \
    --hgvs \
    --protein \
    --offline \
    --refseq \
    --tab \
    --use_transcript_ref \
    --output_file /data/outputs/mitochondrial_refseq.txt
```
The RefSeq cache was downloaded from `ftp://ftp.ensembl.org/pub/release-108/variation/indexed_vep_cache/homo_sapiens_refseq_vep_108_GRCh38.tar.gz`. 
The output contains no annotations for chrM and reports them as intergenic variants:
```
chrM_750_A/G	chrM:750	G	-	-	-	intergenic_variant	-	-	-	-	-	-	MODIFIER	-	-	-	-	-	-	-	-	-	-	-	-
chrM_1438_A/G	chrM:1438	G	-	-	-	intergenic_variant	-	-	-	-	-	-	MODIFIER	-	-	-	-	-	-	-	-	-	-	-	-
chrM_2259_C/T	chrM:2259	T	-	-	-	intergenic_variant	-	-	-	-	-	-	MODIFIER	-	-	-	-	-	-	-	-	-	-	-	-
```

Running the same command with the merged cache returns the desired annotations, with Ensembl transcripts. Could that be a bug with RefSeq annotations? Am I forgetting a parameter or a particular configuration?

Thank you!
