### ISSUE TITLE
Inheritance column

### ISSUE THREAD

**Issue by shigej38** [Ensembl/ensembl-vep#467]
Hello;
How to add the Inheritance column to my annotate vcf file with ensembl-vep?

**Comment by ens-lgil** [comment]
Dear @shigej38,

Please, could you be more specific about this inheritance column ?
Is this column already in your input file, in an additional file used as [custom annotation](https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html) or from a [VEP plugin](https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html) ?

Best regards,
Laurent

**Comment by shigej38** [comment]
Dear @ens-lgil 
I don't know exactly where to get it. That's exactly what I want to know.
What I mean is that I want to know the inheritance status of a disease state, that is, the inheritance of resesif homozygous or  dominant homozygous.

**Comment by ens-lgil** [comment]
We don't really have much of inheritance information in Ensembl and not directly available through VEP.

However you can get some inheritance information with the VEP plugin [G2P](https://github.com/Ensembl/VEP_plugins/blob/release/96/G2P.pm), using the column "allelic requirement" which give you the information if the disease is `monoallelic` or `biallelic`.

Best regards,
Laurent

**Comment by shigej38** [comment]
Dear @ens-lgil 
Thank you for your comment, it's nice to have time, but I'm not exactly what I'm looking for.

**Comment by ens-lgil** [comment]
I am closing this issue, but if you have any more questions please feel free to reopen it.

Best regards,
Laurent
