### ISSUE TITLE
ensembl-vep ( unexpected end of file) error

### ISSUE THREAD

**Issue by shigej38** [Ensembl/ensembl-vep#468]
Hello;
I get such an error when using ensembl-vep.
How can I get my vcf file to recognize?

my running command is:
`/home/$USER/Desktop/programlar/ensembl-vep/vep --coding_only -i /home/$USER/Desktop/pipeline/playground/FMF-288.vcf -o /home/$USER/Desktop/pipeline/playground/FMF-288.csv --cache --port 3337 --symbol --tab --polyphen p --sift p --pubmed --hgvs --fasta /home/$USER/Desktop/programlar/ensembl-data/fasta/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa --plugin LOVD --plugin Condel,/home/$USER/.vep/Plugins/config/Condel/config/condel_SP.conf,b --plugin GO --plugin dbNSFP,/home/$USER/Desktop/programlar/ensembl-data/dbNSFP3.5/dbNSFP3.5.gz,ALL --plugin dbscSNV,/home/$USER/Desktop/programlar/ensembl-data/dbscSNV/dbscSNV1.1/dbscSNV1.1_GRCh37.txt.gz --plugin G2P,/home/$USER/Desktop/programlar/ensembl-data/G2P/DDG2P_17_5_2019.csv`

this error output:
gzip: /home/$USER/Desktop/pipeline/playground/FMF-288.vcf: unexpected end of file
ERROR: Can't detect input format

**Comment by dglemos** [comment]
Hi @shigej38 
It seems it's a problem with your input file. 
Could you send me your input file to see what the problem is? 

Thanks
Diana

**Comment by shigej38** [comment]
@dglemos  You can provide your mail address. i can send the data

**Comment by dglemos** [comment]
You can send your vcf file here https://www.ensembl.org/Help/Contact

**Comment by shigej38** [comment]
it's okay .
I am waiting reply

**Comment by dglemos** [comment]
Your input file is corrupted, if you remove the line with the GATK command (##GATKCommandLine) it should work. 
Also, you use the option --coding_only which only returns consequences that fall in the coding regions of transcripts. Your variants don't fall in any coding region which means that if you try to run vep with this flag your output file is going to be empty.

**Comment by shigej38** [comment]
Thank you @dglemos
