### ISSUE TITLE
Ensembl-vep offline mode

### ISSUE THREAD

**Issue by shigej38** [Ensembl/ensembl-vep#472]
I want to use ensembl-vep in offline mode, but I get an error message that I need an internet connection to use the G2P plugin and the GO plugin. how can I use these two plugins offline?

Apart from that, the vcf file also contains only the header part where I get an empty output file which does not output any output when I added the --coding_only parameter even though I have missense and synonym mutations.

**Comment by ens-lgil** [comment]
Dear @shigej38,

Unfortunately you can't use these 2 plugins offline at the moment.

We had several requests regarding the G2P plugin not able to work offline.
We are currently working on the G2P plugin to make it usable offline and we are planning to release it with the next Ensembl release (`release/97`) at the end of June.

About the VCF output, could you send me the command line you used and a couple of lines of your input file, please ?

Best regards,
Laurent

**Comment by shigej38** [comment]
Dear @ens-lgil 
Can you give me an email address where I can send vcf files and the command I use?

**Comment by dglemos** [comment]
@shigej38 if you still have this problem, please email your input file to helpdesk https://grch37.ensembl.org/Help/Contact

**Comment by shigej38** [comment]
ı  am sended e-mail

**Comment by dglemos** [comment]
The vcf header doesn't follow vcf specification, it contains quotation marks, as example: **"**##FILTER
Regarding the variants, they are the same variants as the file from issue #468. These variants don't fall in coding region that is why the output is empty.

**Comment by shigej38** [comment]
thank you @dglemos
