### ISSUE TITLE
Ensembl-vep costum annotation

### ISSUE THREAD

**Issue by shigej38** [Ensembl/ensembl-vep#473]
I have a txt file in my hand where the diseases associated with the genes are written. 
How can I get ensembl-vep to add the information for the gene to the output file?

my text contents (head)
```
Approved Symbol	Phenotypes
CCV	Cataract 8, multiple types, Autosomal dominant
MYP14	Myopia 14
SCASI	Spinocerebellar ataxia, autosomal recessive 4, Autosomal recessive
ISG15	Immunodeficiency 38, Autosomal recessive
AGRN	Myasthenic syndrome, congenital, 8, with pre- and postsynaptic defects, Autosomal recessive
B3GALT6	Ehlers-Danlos syndrome, progeroid type, 2, Autosomal recessive;Spondyloepimetaphyseal dysplasia with joint laxity, type 1, with or without fractures, Autosomal recessive
DVL1	Robinow syndrome, autosomal dominant 2, Autosomal dominant
ATAD3A	Harel-Yoon syndrome, Autosomal recessive, Autosomal dominant
TMEM240	Spinocerebellar ataxia 21, Autosomal dominant

```

**Comment by dglemos** [comment]
As you can read in our documentation [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html), VEP can integrate custom annotation from standard format files into your results. These files must be indexed using tabix and their format can be BED, GFF, GTF, VCF.  
Your file is a tab file with only diseases and associated genes which is not suitable for vep custom annotation. Currently, we don't have any tool to perform the type of annotation you're asking. 

Thanks,
Diana

**Comment by shigej38** [comment]
I want to add the names of the disease to my output, how can I do it with ensembl-vep. @dglemos

**Comment by dglemos** [comment]
VEP doesn't perform the type of annotation you are asking.

**Comment by shigej38** [comment]
I have two more questions.
How can I add that the variant is heterozygous or homozygous?

do I have different transcripts of the same gene written on the same line?

**Comment by dglemos** [comment]
I don't understand what you mean with your first question. Could you be more specific and give an example? 
About your second question, depends on the output format you choose. It's all explained in the documentation [here](https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#defaultout). Default VEP output writes one line for each transcript/regulator region; VCF output writes all data in the same line.

**Comment by shigej38** [comment]
Dear @dglemos 
I understand what you mean, but when we take the output as vcf we combine the column that adds all the information in a single column. In this case, a very large and illegible document is obtained.
this is a situation I don't want --tab gives a very elegant and legible output.
What I want now is that both the same transcripts of the same gene should be written on a single line, and then perform the tab delimitation. Is this possible?

my first question with the "--individual all" parameter was solved. thank you for your interest.

**Comment by dglemos** [comment]
It's not possible to do that with VEP and we don't support any tool that performs the parsing of output files. However, there's a bcftools plugin `[split-vep](https://samtools.github.io/bcftools/howtos/plugin.split-vep.html)` which extracts fields from annotated files. It could be helpful for your question.

**Comment by dglemos** [comment]
I'm closing this issue. Feel free to open it if you have any more questions.
