### ISSUE TITLE
VEP not matching COSMIC alleles

### ISSUE THREAD

**Issue by kmhernan** [Ensembl/ensembl-vep#48]
I am using release 88.8 with VEP cache v84 and noticed that it is annotating COSMIC variants; however, in the cache COSMIC does not have alleles present due to licensing changes. Why would VEP annotate this?!? I am not using the `--no_check_alleles` option! 

Here is an example command.

```
/usr/bin/perl /mnt/SCRATCH/bin/ensembl_vep/ensembl-vep/vep \
--cache_version 84 --species homo_sapiens --assembly GRCh38 \
--cache --offline --no_progress --no_stats --sift b --ccds \
--uniprot --hgvs --symbol --numbers --domains --gene_phenotype \
--regulatory --canonical --protein --biotype --tsl --pubmed \
--variant_class --shift_hgvs 1 --check_existing --total_length \
--allele_number --no_escape --xref_refseq --vcf --minimal \
--failed 1 --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length \
--dir_cache /mnt/SCRATCH/vep_cache_84/cache \
--dir_plugin /home/ubuntu/NCI-GDC/vcf2maf-tool/vep-plugins \
--fasta /mnt/SCRATCH/vep_cache_84/vep_fasta/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz \
--input_file /mnt/SCRATCH/test/pyvcf2maf/new_test/new_vep/run/0577fdb0-909c-41e1-81a2-b9ab0d2b09f9.vep.vcf.gz \
--output_file /mnt/SCRATCH/test/pyvcf2maf/new_test/new_vep/run/0577fdb0-909c-41e1-81a2-b9ab0d2b09f9.vcf2maf.vcf \
--plugin GDC_entrez,/mnt/SCRATCH/vep_cache_84/custom/ensembl_entrez_names.json \
--polyphen b --af --af_1kg --af_esp --af_exac --vcf_info_field GDCCSQ --fork 4 \
--synonyms /mnt/SCRATCH/test/pyvcf2maf/new_test/new_vep/synonyms.txt
```

**Comment by willmclaren** [comment]
This is the intended behaviour. If no alleles are available for the known variant, then it passes the check.

I can understand that it does not suit your use case; however as with many things in VEP we err on the side of providing the data in questionable cases like this and allow the user to make their own judgment.

We can look into adding a filter on the known variants so you could, for example, exclude any that don't have alleles or whose IDs match a certain pattern e.g. COSM*

**Comment by kmhernan** [comment]
While I understand the choice to err on the side of providing the data in questionable cases, I just don't see how missing alleles when you want to actually match alleles would be considered questionable. In previous versions it did not include such annotations, and I would imagine that I am not alone in assuming that only variants that actually match alleles would be in `Existing_variation`. I also didn't see any documentation stating that you just stated above and that worries me that people are blindly going forward. This also assumes that users would then secondarily have to go through the annotation *and* the cache files to then see if indeed there was an allele present or not! There is nothing that I can see in the output that lets me know the COSMIC annotations are missing alleles (I just knew this from my other work). Secondarily, for the COSMIC case, it then sets the `SOMATIC` column. So you would not only have to go through the annotation *and* the cache files, but then secondarily handle `SOMATIC`, `PHENO`, etc. I feel like the *better* approach would be to have a flag for allowing null alleles to match that was not on by default. Thoughts?

**Comment by willmclaren** [comment]
That seems a reasonable approach.

While you're correct the old behaviour (using `--check_alleles`) would not include those with no allele data, in fact the default behaviour was with `--check_alleles` off, so you'd see similar results to what you see now.

I can guarantee that if I change the default again as you suggest there will be at least one person asking for the opposite to what you have requested :-)

We'll discuss it internally and hopefully make a decision in time to put any changes into release/89.

Thanks for your feedback.

**Comment by kmhernan** [comment]
@willmclaren I understand that it is impossible to make everyone happy and perhaps it is best to keep the defaults as they are but add on the option to ignore null alleles when you care about allele matching. Either way, I would definitely like to have to ability to not match null alleles in these cases. Thank you for always being so responsive :+1:

**Comment by ZhenyuZ** [comment]
@willmclaren I observed the same thing as well. I agree there will be ppl unhappy with any default implementation, but would it possible for VEP to provide another option like --check_alleles_strict to invoke another behavior of more strict checking and annotation? Thanks

**Comment by willmclaren** [comment]
Added `--exclude_null_alleles` to master https://github.com/Ensembl/ensembl-vep/commit/3c88fe79cd6ca2e4ff23ff0cf0b38e8df9fdccf9; this will appear in release/89.

You may of course use master now at your own risk.
