### ISSUE TITLE
Installation issue: API versions not recognized

### ISSUE THREAD

**Issue by marchoeppner** [Ensembl/ensembl-vep#49]
Hi,

was trying to install VEP as outlined here, but got stuck when the installation script tried to determine whether my EnsEMBL API was up-to-date:

Checking for installed versions of the Ensembl API...done
There are updates avaiable for these modules:
  ensembl-io           : installed = , available = 277fe7c
  ensembl              : installed = , available = b8ff470
  ensembl-variation    : installed = , available = ed4fefd
  ensembl-funcgen      : installed = , available = 3e63130

Both ensembl-vep as well as all other API components are at checout "release/88" and their respective most recent commits. Running on Centos6, Perl 5.18.4.

 If I skip to the next step, htslib etc is not built, so that is a problem of course. 

Any advise?

**Comment by willmclaren** [comment]
Hi Marc, if you installed the API separately (i.e. not using INSTALL.pl to set it up) then you will see this kind of message. In that case it is up to you to ensure that your checkouts of those APIs are up-to-date, which it seems they are. The script could be a bit more intelligent about this and perhaps let you know you are responsible for checking for any post-release updates.

If you allow INSTALL.pl to set up the APIs for you, then a version is recorded for each downloaded module with the idea that this check can then inform users if there are any post-release updates that they might like or need to download.

**Comment by marchoeppner** [comment]
I see! In that case this can be closed.
