### ISSUE TITLE
Possible combine outputs from multiple vcf inputs?

### ISSUE THREAD

**Issue by DaRinker** [Ensembl/ensembl-vep#490]
I am running VEP locally and would like to use multiple .vcf inputs (ie, per-chromosome vcf files) at at the very minimum generate a summary html output for all chromosomes.

I cannot find information regarding either using multiple vcfs as inputs or (perhaps more ideally) generating summary stats from multiple vep outputs.

Is there any native way to do either/both?

Thank you

**Comment by aparton** [comment]
Hi,

Unfortunately VEP does not support multiple input files - in situations like this we recommend that you combine all of your input files into one large input file. Similarly, our summary statistics are generated during the annotation process, so there is no way of generating statistics from output files. However, combining all of your single chromosome files into one input file will provide per-chromosome summary statistics.

Kind Regards,
Andrew

**Comment by DaRinker** [comment]
Ok.  Thanks for confirming this.
