### ISSUE TITLE
_check_linelength error in VEP annotation launch

### ISSUE THREAD

**Issue by Stikus** [Ensembl/ensembl-vep#493]
Hello, we are using VEP in GDC-like pipeline after VarScan step.
This is our VEP launch command:
`/soft/ensembl-vep-95/vep --fork 14 --input_file Test.all.all.hc.fp-filtered-D3.Somatic.vcf --format vcf --cache --dir_cache /ref/.vep --dir_plugins /ref/.vep/Plugins --fasta /ref/GRCh38.d1.vd1/GRCh38.d1.vd1.fa --assembly GRCh38 --offline --output_file Test.annot-vep.vcf --vcf --no_stats --symbol --force_overwrite --terms SO --plugin Downstream --plugin Wildtype --tsl --hgvs --transcript_version
`
When we used this launch-command on genome (not exome as usual) data we got following error:
```
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Each line of the qual file must be less than 65,536 characters. Line 44360861 is 235647 chars.
STACK: Error::throw
STACK: Bio::Root::Root::throw /soft/ensembl-vep-95/Bio/Root/Root.pm:449
STACK: Bio::DB::IndexedBase::_check_linelength /soft/ensembl-vep-95/Bio/DB/IndexedBase.pm:744
STACK: Bio::DB::Fasta::_calculate_offsets /soft/ensembl-vep-95/Bio/DB/Fasta.pm:175
STACK: Bio::DB::IndexedBase::_index_files /soft/ensembl-vep-95/Bio/DB/IndexedBase.pm:648
STACK: Bio::DB::IndexedBase::index_file /soft/ensembl-vep-95/Bio/DB/IndexedBase.pm:484
STACK: Bio::DB::IndexedBase::new /soft/ensembl-vep-95/Bio/DB/IndexedBase.pm:364
STACK: Bio::EnsEMBL::Variation::Utils::FastaSequence::_get_fasta_db /soft/ensembl-vep-95/Bio/EnsEMBL/Variation/Utils/FastaSequence.pm:337
STACK: Bio::EnsEMBL::Variation::Utils::FastaSequence::setup_fasta /soft/ensembl-vep-95/Bio/EnsEMBL/Variation/Utils/FastaSequence.pm:212
STACK: Bio::EnsEMBL::VEP::BaseVEP::fasta_db /soft/ensembl-vep-95/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:475
STACK: Bio::EnsEMBL::VEP::Runner::init /soft/ensembl-vep-95/modules/Bio/EnsEMBL/VEP/Runner.pm:129
STACK: Bio::EnsEMBL::VEP::Runner::run /soft/ensembl-vep-95/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK: /soft/ensembl-vep-95/vep:225
-----------------------------------------------------------
```
Can you give me any advice about what file caused this error? If I correctly understood messages - this is quality line check in reference (fasta?) file. But fasta doesn't contain quality.
I cannot attach example VCF because it is too big.

**Comment by ens-lgil** [comment]
Dear @Stikus,

Looking at the stack error messages, it seems to come from the parsing of your Fasta file by th BioPerl library.
Can you send us the first lines of your FASTA file, please ?
It might be that the header of your FASTA file is too long for BioPerl.

Best regards,
Laurent

**Comment by serge2016** [comment]
@ens-lgil,
```
$ head /ref/GRCh38.d1.vd1/GRCh38.d1.vd1.fa
>chr1  AC:CM000663.2  gi:568336023  LN:248956422  rl:Chromosome  M5:6aef897c3d6ff0c78aff06ac189178dd  AS:GRCh38
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```

**Comment by serge2016** [comment]
I used this reference fasta-file earlier in the same conditions and everything was good! Main difference is that this run is on WGS and previous runs were on WES... Maybe the input VCF is too big?

**Comment by serge2016** [comment]
Dear colleagues, any advice?

**Comment by ens-lgil** [comment]
Dear @serge2016 and @Stikus,

I checked the fasta file and the line `44360860` is actually composed of 235,647 characters. e.g.:
```
sed '44360860q;d' ref/GRCh38.d1.vd1/GRCh38.d1.vd1.fa | wc -m
``` 
This corresponds to the fasta sequence of:
```
>CMV Human_Cytomegalovirus gi:155573622 refseq:NC_006273.2 gbk:AY446894.2 ln:235646 AS:GDC.vd1
```

Would it be possible to edit the fasta file and split the sequence on several lines for `CMV Human_Cytomegalovirus` ?

Best regards,
Laurent

**Comment by Stikus** [comment]
@ens-lgil looks like that was our mistake - we used not VEP reference fasta as proposed but [GDC](https://gdc.cancer.gov/about-data/data-harmonization-and-generation/gdc-reference-files).
After removing `--fasta` flag from executive command (as proposed for automatical VEP reference detection) everything works well.
Thank you for help.
