### ISSUE TITLE
Haplosaurus can require more than 60GB memory for a single variant & transcript

### ISSUE THREAD

**Issue by LukeGoodsell** [Ensembl/ensembl-vep#497]
Hi again :-)

I have encountered a situation where a single variant and transcript combination can require more than 60 GB memory to run Haplosaurus. This seems highly excessive and indicative of a memory leak to me. Please can a member of the team check if this is expected behaviour that I should provision resource for, or something is going wrong in this instance.

Code to reproduce below. I'm using e!91.

    sed 's/ \{2,\}/\t/g' > example.vcf <<'EOF'
    ##fileformat=VCFv4.2
    ##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotypes">
    #CHROM  POS        ID  REF  ALT  QUAL  FILTER  INFO  FORMAT  sample
    chr2    179518956  .   G    GT   40    PASS    .     GT      0|1
    EOF

    haplo \
            --input_file example.vcf \
            --output_file example_haplo.json \
            --assembly GRCh37 \
            --refseq \
            --json \
            --database \
            --port 3337 \
            --transcript_filter "stable_id match NM_001267550"
    # For me this gets Killed once it uses all 62.7GB memory I have currently.

    vep \
            --input_file "example.vcf" \
            --output_file "example_vep.json" \
            --assembly "GRCh37" \
            --refseq \
            --json \
            --hgvs \
            --exclude_predicted \
            --use_transcript_ref \
            --check_existing \
            --database \
            --port 3337 \
            --transcript_filter "stable_id match NM_001267550"

    jq -rs '[.[] 
                | {chrom: .seq_region_name, pos: .start,
                    transcript_consequences: .transcript_consequences[]}
                | {chrom, pos, HGVSc: .transcript_consequences.hgvsc?,
                    HGVSp: .transcript_consequences.hgvsp?}
            ]
                | (.[0] | to_entries | map(.key)), (.[] | [.[]]) 
                | @csv
            ' \
            example_vep.json \
        | csvlook

| chrom |         pos | HGVSc                     | HGVSp                               |
| ----- | ----------- | ------------------------- | ----------------------------------- |
| chr2  | 179,518,957 | NM_001267550.1:c.38358dup | NP_001254479.1:p.Pro12787ThrfsTer10 |
| chr2  | 179,518,957 | NM_001267550.2:c.38358dup | NP_001254479.2:p.Pro12787ThrfsTer10 |

**Comment by ens-lgil** [comment]
Dear @LukeGoodsell,

Ah ... our beloved TTN gene, its more than 350 exons and its more than 100kb transcripts!

I just tried to run your command with your single input on a e96 VEP Docker image (limited by default to 2Gb of memory) and I got a result (even though it took few minutes).
e.g. default output format:
```
NM_001267550.1	NM_001267550.1:38353insA	frameshift,indel	NP_001254479.1:12787del{6651},19439del{16},19456K>S,19457del{2037},21495delHP,21500del{9995},31496del{1124},32621del{3371}	indel		test_2	sample:1
NM_001267550.2	NM_001267550.2:38353insA	frameshift,indel	NP_001254479.2:12787del{6651},19439del{16},19456K>S,19457del{2037},21495delHP,21500del{9995},31496del{1124},32621del{3371}	indel		test_2	sample:1
```

I did a little bit of digging and found out that the memory issue seems to comes from the BioPerl library.
Installing `bioperl-ext` is fixing the memory issue (The Haplosaurus run only used 350Mb of memory with this library).
Here is the documentation about how to install it: https://www.ensembl.org/info/docs/tools/vep/haplo/index.html#hp_bioperl_ext.

Furthermore we strongly recommend to use the same release version between API and databases/caches: you are using VEP `release/91` with the current Ensembl databases (`release/96`).

Best regards,
Laurent

**Comment by LukeGoodsell** [comment]
Thanks, @ens-lgil, that did the trick - it finished in 7 minutes using no more than 1.5GB of memory.

> Furthermore we strongly recommend to use the same release version between API and databases/caches: you are using VEP release/91 with the current Ensembl databases (release/96).

Thanks for looking out for me. I'm using a locally downloaded cache for e!91 - I used the servers in the commands I provided just so they would work for other people.

**Comment by tinyheero** [comment]
Thanks @ens-lgil. That's super useful. Would it be possible to make the suggestion of `bioperl-ext` more prominent on the Haplosaurus website for posterity?

**Comment by ens-lgil** [comment]
Dear @tinyheero,

Yes, this is what I realised when I was writing the reply to @LukeGoodsell! 
I will try to make the change for the incoming release 97 (should be out by the end of the month).

Best regards,
Laurent

**Comment by tinyheero** [comment]
Great. And thanks @ens-lgil for all your hard work!
