### ISSUE TITLE
HGVS: Protein prediction should be written as predicted

### ISSUE THREAD

**Issue by ifokkema** [Ensembl/ensembl-vep#498]
The HGVSp field shows the predicted protein change, like `NP_878258.1:p.Arg188Trp`. But the HGVS nomenclature states that predicted protein changes should be written between parenthesis, like `NP_878258.1:p.(Arg188Trp)` to indicate that they're predictions.

See:
http://varnomen.hgvs.org/recommendations/general/   (under "Characters used")
http://varnomen.hgvs.org/recommendations/protein/variant/substitution/   (under Note)
> predicted consequences, i.e. without experimental evidence (no RNA or protein sequence analysed), should be given in parentheses, e.g. p.(Arg727Ser).

**Comment by dglemos** [comment]
Hello @ifokkema,
Thank you for pointing that out! 
Currently, the only terminology using parentheses that we support is to represent a gene name/protein change: 
NM_017651.4(AHI1):c.3053A>C(p.Gln1018Pro) 
In the future, we plan to support other terminologies - that includes representing predicted protein changes with parentheses.

Best regards,
Diana

**Comment by ifokkema** [comment]
Hi @dglemos, thank you for your quick reply! I'll wait for it then :) Right now, I have configured my tool to place the parentheses there if it doesn't find them.

**Comment by matthdsm** [comment]
Seconded! IMO, vep should be able to output HGVS notations according to the most recent recommendations. 

Cheers
M

**Comment by lacek** [comment]
This is indeed a great suggestion.

The idea of using bracket to indicate predicted protein change isn't something new. According to HGVS website, it was there back in 2004:
* (2004) examples protein-level: https://web.archive.org/web/20041212151916/http://www.hgvs.org/mutnomen/examplesAA.html#general
  > when changes are reported for which experimental proof is not available one should consider to list them between brackets
* (2004) FAQ: https://web.archive.org/web/20041018100648/http://www.hgvs.org:80/mutnomen/FAQ.html
  > Note that descriptions on RNA and protein level should only be given when this was experimentally verified; if not, changes should be placed between brackets to indicate that it is a prediction only.
* (2102) Recommendations V2.0: https://web.archive.org/web/20120108022808/http://www.hgvs.org/mutnomen/recs-prot.html#prot
  > to indicate that the description at protein level is without any experimental proof it is recommended that, when RNA has not been analysed, the description is given between brackets (e.g. p.(Arg22Ser))

Consider that VEP is widely adopted these days, there could be VEP users having their own scripts/programs that parse the HGVSp field.
Therefore it might be a good idea to implement the suggestion as an optional feature that can be toggled on by command line flag.

**Comment by helensch** [comment]
Hi @lacek 

Thank you for your comments. I have noted your suggestion that using brackets to indicate predicted protein change be an optional feature for consideration on the task list for supporting other HGVS terminologies.

Regards
Helen

**Comment by nakib103** [comment]
Hello,

We have added feature to show HGVSp variant in predicted format. It will be available in the next release of Ensembl VEP (e111).

I am closing this issue. Feel free to create another ticket if you any further problems.
