### ISSUE TITLE
HGVS: Protein prediction empty for variants not in coding region

### ISSUE THREAD

**Issue by ifokkema** [Ensembl/ensembl-vep#499]
The HGVSp field is empty for variants in the intron or in the UTR. The correct HGVS description for not expecting a change on protein level would actually be `p.(=)`. In case the variant is inside a splice site region, you can use `p.?`.

https://varnomen.hgvs.org/recommendations/uncertain/
> p.?
used to indicate that an effect on the protein level is expected but that it is not possible to give a reliable prediction of the consequences

https://varnomen.hgvs.org/recommendations/RNA/variant/splicing/    (see: Q&A)
> How can I best describe the predicted consequences at the protein level of a variant that most probably affects splicing?
The best format seems to use "p.?", meaning "I do not know what to expect at the protein level".

**Comment by dglemos** [comment]
Hi @ifokkema,
Thank you so much for your input. 
At the moment HGVSp is not provided if it's not in the protein but it's something we plan to implement in a future release. 

Best regards,
Diana

**Comment by ifokkema** [comment]
Hi @dglemos, thank you for your quick reply!
In principle, the variant could still affect the protein in some cases, even though it's not in the CDS. Since the variant is located in the gene, providing a predicted effect on protein level is still recommended. The following are the rules as in place by [LOVD](http://www.LOVD.nl/), which are simply an implementation choice and just a suggestion, by far not perfect and not the only possible implementation.

- Variant position(s) are upstream of the transcript, we can assume that the product will not be affected.
`p.(=)`
- Variant position(s) are downstream of the transcript, we can assume that the product will not be affected.
`p.(=)`
- Variant has an upstream start position and a downstream end position, we can assume that the product will not be expressed.
`p.0?`
- Variant has one of two positions within the transcript, so we can not make any assumptions based on that.
`p.?`
- Variant position(s) <= 5 nucleotides into the intron, splicing possibly affected.
`p.?`
- Variant further into intron, splicing rarely affected (if information is known about the branch point, it should obviously be used).
`p.(=)`

**Comment by dglemos** [comment]
Thank you for the detailed examples, it's very helpful to us to know how HGVS is being implemented by different entities. We'll look into this and I'll let you know when a change is coming. 

Thanks
Diana

**Comment by nakib103** [comment]
Hello @ifokkema,

We are not prioritising to add any new features to the current implementation of HGVS. Instead, we are looking to improve these cases in our future implementation of VEP.

Best regards,
Nakib

**Comment by ifokkema** [comment]
Thank you for the update, @nakib103 ! Does that new implementation of VEP have a different repository where I can copy the feature request to, or do you plan to use pre-existing libraries such as [VariantValidator](https://github.com/openvar/variantValidator/)?
