### ISSUE TITLE
VCF header malformed - branch release87

### ISSUE THREAD

**Issue by henrikstranneheim** [Ensembl/ensembl-vep#5]
Hi,

The header does not seem to be dereferenced properly and the contigs entries are incorrect:

##fileformat=VCFv4.2
##ALT=ARRAY(0x4e366e8)
##ALT=ARRAY(0x4e366e8)
##ALT=ARRAY(0x4e366e8)
##ALT=ARRAY(0x4e366e8)
##ALT=ARRAY(0x4e366e8)
##FILTER=ARRAY(0x53baf98)
##FILTER=ARRAY(0x53baf98)
##FILTER=ARRAY(0x53baf98)
##FILTER=ARRAY(0x53baf98)
##FILTER=ARRAY(0x53baf98)
##FILTER=ARRAY(0x53baf98)
##FORMAT=ARRAY(0x334bbe8)
##FORMAT=ARRAY(0x334bbe8)
##FORMAT=ARRAY(0x334bbe8)
##FORMAT=ARRAY(0x334bbe8)
##FORMAT=ARRAY(0x334bbe8)
##FORMAT=ARRAY(0x334bbe8)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##INFO=ARRAY(0x334bbd0)
##bcftools_annotateCommand=annotate --header-lines references/vcfanno_headerLines.v1.0.txt /scratch/718358/118_sorted_md_brecal_comb_SV_vt_filt_genmod_filter_vcfanno.vcf
##bcftools_annotateVersion=1.3.1+htslib-1.3.1
##bcftools_concatCommand=concat -a /scratch/718358/118_pmanta.vcf.gz
##bcftools_concatVersion=1.3.1+htslib-1.3.1
##bcftools_viewCommand=view -f PASS /scratch/718358/118_sorted_md_brecal_comb_SV_vt.vcf
##bcftools_viewVersion=1.3.1+htslib-1.3.1
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=hs37d5,length=35477943>
##fileDate=20161211
##reference=file:references/Homo_sapiens.GRCh37.d5.fasta
##source=GenerateSVCandidates 1.0.0
##VEP="v87" time="2016-12-13 08:41:39" cache="ensembl-tools-release-87/cache/homo_sapiens/87_GRCh37" ensembl-variation=87.f4bd0ac ensembl-funcgen=87.1514451 ensembl=87.f547798 ensembl-io=87.9a66f34 COSMIC="71" ClinVar="201507" ESP="20141103" HGMD-PUBLIC="20152" assembly="GRCh37.p13" dbSNP="144" gencode="GENCODE 19" genebuild="2011-04" polyphen="2.2.2" regbuild="13" sift="sift5.2.2"
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|CANONICAL|TSL|APPRIS|CCDS|ENSP|SWISSPROT|TREMBL|UNIPARC|SIFT|PolyPhen|DOMAINS|HGVS_OFFSET|MOTIF_NAME|MOTIF_POS|HIGH_INF_POS|MOTIF_SCORE_CHANGE|LoFtool|LoF|LoF_filter|LoF_flags|LoF_info">
##LoFtool=LoFtool score for gene
##LoF=Loss-of-function annotation (HC = High Confidence; LC = Low Confidence)
##LoF_filter=Reason for LoF not being HC
##LoF_flags=Possible warning flags for LoF
##LoF_info=Info used for LoF annotation

**Comment by willmclaren** [comment]
Thanks, this is fixed by https://github.com/Ensembl/ensembl-vep/commit/2de6bc97a40bb16b11918156a8bc578a8f1c2d6b

You will need to re-run INSTALL.pl as there is a part of this fix in the ensembl-io module.
