### ISSUE TITLE
HGVS: Insertions in the 3' UTR sometimes needs positions switched

### ISSUE THREAD

**Issue by ifokkema** [Ensembl/ensembl-vep#500]
HGVSc descriptions of variants in the 3' UTR sometimes behave strangely; their positions are switched and dups are not recognized. I can't really figure out the logic.

GRCh37/hg19, same variant twice, described differently:

```
chr1  20978294  .  TTTTATTTATTTA  TTTTATTTATTTATTTA
chr1  20978294  .  TTTTA  TTTTATTTA

```

gives

```
NM_005216.4:c.*578_*577insTAAA
ENST00000602624.2:c.*578_*577insTAAA
```

for the first variant, but

```
NM_005216.4:c.*574_*577dup
ENST00000602624.2:c.*574_*577dup
```

For the latter. The latter is correct. The first is wrong; not only are the positions in the wrong order, also it doesn't recognize the ins as a dup.

**Comment by aparton** [comment]
Hi,

Thanks for bringing this to our attention. I've taken a look this afternoon, and it looks like this is a bug. We'll investigate further, and I'll let you know when a fix is in place.

As mentioned in issue #501, the `--minimal` flag will provide the normalised annotations and as such give the correct result. However as this is not our default behaviour, then I appreciate this is not ideal.

If you have any more feedback for us, please let us know.

Kind Regards,
Andrew

**Comment by ifokkema** [comment]
Hi Andrew, thank you! So I guess the normalisation of `ins` to `dup` is debatable, but the switching of positions (that only seems to happen when the ALT consists of repeats of the REF) can be fixed for sure. Great, thank you!

**Comment by nakib103** [comment]
Hello @ifokkema,

We have added fix for this issue to output correct position and type. The fix will be available in the next release of Ensembl VEP (e111).

I am closing this issue. Feel free to create another ticket if you any further problems.
