### ISSUE TITLE
HGVS: Substitutions given als indels are not recognized as substitutions

### ISSUE THREAD

**Issue by ifokkema** [Ensembl/ensembl-vep#501]
Sometimes, variant callers report substitutions as indels. VEP should normalise the variants and recognise this as such, and provide the proper HGVSc prediction regardless of how the variant caller decided to represent the variant in the VCF file.

GRCh37/hg19
```
chr1 63044645 . CA AA
```

gives

```
ENST00000251157.5:c.1872-8delinsT
NM_033407.3:c.1872-8delinsT
```

Obviously, that should be:

```
ENST00000251157.5:c.1872-8G>T
NM_033407.3:c.1872-8G>T
```

I hope you're not tired of me yet :)

**Comment by aparton** [comment]
Hi,

Thank you for your interest in VEP. We're not tired at all, feedback like yours is always valuable to us, and with the complexity of our HGVS code then I'm sure you can find all sorts of idiosyncrasies in there.

This is an issue that we've taken a look at in the past - we've had some users request normalisation of variants before annotation, and some requests for annotation in the original format. As such, we introduced the `--minimal` flag, which tells VEP to normalise variant input before consequence and HGVS calculations. You can read more about this here: https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html

Kind Regards,
Andrew

**Comment by ifokkema** [comment]
Hi Andrew,
Thank you for pointing me to this option, I wasn't aware of it! I actually thought VEP was already doing this... I understand making this flag the default could break existing implementations, but I do think it's very important to your users to at least then highly recommend this feature, and to make it available from the web interface. While working on collecting and combining all data from all diagnostic labs in the Netherlands (paper submitted), we have had lots of problems with non-normalised variants. Most of the centers were even completely unaware that variant descriptions for one variant could differ.

I argue that the `--minimal` flag is essential and should be considered to be made the default in a future VEP release (with clear documentation of this change, obviously) as the representation of the variant is, in by far the most cases, an arbitrary choice by the variant caller anyway, and I believe users are mostly unaware of differences in this. Furthermore, any prediction result should be the same for any representation of the same variant.

In fact, it seems like VEP already partially normalises its input anyway. Submitting the same variant in different representations (GRCh38):
```
chr15 40410700 . GAGCAG GAGGAG
chr15 40410701 . AGCAG AGGAG
chr15 40410702 . GCAG GGAG
chr15 40410703 . CAG GAG
chr15 40410703 . CA GA
chr15 40410703 . C G
```
Gives me a `c.362delinsG` for all but the last, which is returned as `c.362C>G`. So lines 1-5 are already normalised into the same variant without the `--minimal` flag. I haven't checked any annotation, but I surely hope this won't be different between any of these lines.

Thank you!
