### ISSUE TITLE
rsIDs for instant VEP results link to JSON data instead of human readable page

### ISSUE THREAD

**Issue by ifokkema** [Ensembl/ensembl-vep#502]
Running this on "instant VEP", returns rsIDs with links. Clicking these links gives JSON pages, instead of HTML pages.

GRCh38/hg38
```
chrX 659083  . A AT
```

Returns:
> Colocated variants:
[rs532613188](http://www.ensembl.org/Homo_sapiens/ZMenu/Variation?v=rs532613188) (MAF: 0.4121), [rs753323054](http://www.ensembl.org/Homo_sapiens/ZMenu/Variation?v=rs753323054) (MAF: 0.0244).

Clicking these links gives you JSON data.

**Comment by ens-lgil** [comment]
Dear @ifokkema,

These links open a popup within the page (which contains summary information about the selected variant).
I believe you tried to open the links on a new tab/window, using right click.

Best regards,
Laurent

**Comment by ens-lgil** [comment]
Hi @ifokkema,

You are not the only one opening new tabs for every link!
However this popup link is used in several places across the website, mainly on our interactive Genome browser, so it is likely to require a broader code update in the website to change its behaviour.

Best regards,
Laurent

**Comment by ifokkema** [comment]
Makes total sense! Thank you for clarifying!
Regards,
Ivo

**Comment by ens-lgil** [comment]
I am closing this issue, but if you have any more questions please feel free to reopen it.

Best regards,
Laurent
