### ISSUE TITLE
Instant VEP cannot deal with empty lines between input

### ISSUE THREAD

**Issue by ifokkema** [Ensembl/ensembl-vep#503]
Pasting the following variants in the input data:
(GRCh38/hg38)
```
chrX 659083 . A AT
chrX 659083 . A AT
chrX 659083 . A AT
chrX 659083 . A AT
```
Instant VEP works for any line.
Now, empty line two as such:

```
chrX 659083 . A AT

chrX 659083 . A AT
chrX 659083 . A AT
```
Instant VEP runs for line 1, but fails for lines 3 and 4. Error message is confusing:
```
Unable to generate preview:
Failed for unknown format
```

When running instant VEP, I think it's normal that users like to play around to get certain results, and they might leave a line empty somewhere while playing with the input. They won't understand this error message and waste time checking their input. (well, that's what happened to me anyway :wink: )

**Comment by ens-lgil** [comment]
Dear @ifokkema,

Thank you for reporting this issue.
This is certainly an tiny issue with the javascript parsing the input in the `Either paste data:`.
We will look at it.

Best regards,
Laurent

**Comment by ens-lgil** [comment]
Dear @ifokkema,

The issue has been fixed and the fix has been deployed with the new Ensembl release.

Best regards,
Laurent

**Comment by ifokkema** [comment]
Excellent, thank you!
