### ISSUE TITLE
Multiple versions of the same transcripts map to the same protein haplotype identifier version

### ISSUE THREAD

**Issue by tinyheero** [Ensembl/ensembl-vep#509]
I've observed that multiple versions of the same transcript identifier can map to the same protein identifier version. For instance:

```
sed 's/ \{2,\}/\t/g' > example.vcf <<'EOF'
##fileformat=VCFv4.2
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotypes">
#CHROM  POS       ID  REF  ALT  QUAL  FILTER  INFO  FORMAT  sample
chr2    96780715  .   CT   TG   40    PASS    .     GT      0|1
EOF

bioenv haplo \
    --input_file example.vcf \
    --output_file example.haplo.json \
    --dir_cache ucsc.hg19-GATKBundle.fa.gz \
    --cache \
    --json \
    --offline \
    --assembly "GRCh37" \
    --force_overwrite \
    --refseq \
    --transcript_filter "stable_id match NM_000682"
```

I'm using e!91 here.

Here we get results from multiple versions of the same transcript (NM_000682.5, NM_000682.6), but map to the same protein version NP_000673.2. The protein haplotypes effects are:

* NM_000682.5:
    + NP_000673.2:392A>T
    + NP_000673.2:REF
* NM_000682.6
    + NP_000673.2:395A>T
    + NP_000673.2:REF

Moreover, the "reference" protein haplotype (NP_000673.2:REF) sequence is actually different between the two transcripts. With the latter one being slightly longer.

```
>NM_000682.5|NP_000673.2:REF
MDHQDPYSVQATAAIAAAITFLILFTIFGNALVILAVLTSRSLRAPQNLFLVSLAAADILVATLIIPFSLANELLGYWYFRRTWCEVYLALDVLFCTSSIVHLCAISLDRYWAVSRALEYNSKRTPRRIKCIILTVWLIAAVISLPPLIYKGDQGPQPRGRPQCKLNQEAWYILASSIGSFFAPCLIMILVYLRIYLIAKRSNRRGPRAKGGPGQGESKQPRPDHGGALASAKLPALASVASAREVNGHSKSTGEKEEGETPEDTGTRALPPSWAALPNSGQGQKEGVCGASPEDEAEEEEEEEEECEPQAVPVSPASACSPPLQQPQGSRVLATLRGQVLLGRGVGAIGGQWWRRRAQLTREKRFTFVLAVVIGVFVLCWFPFFFSYSLGAICPKHCKVPHGLFQFFFWIGYCNSSLNPVIYTIFNQDFRRAFRRILCRPWTQTAW*"
>NM_000682.6|NP_000673.2:REF
MDHQDPYSVQATAAIAAAITFLILFTIFGNALVILAVLTSRSLRAPQNLFLVSLAAADILVATLIIPFSLANELLGYWYFRRTWCEVYLALDVLFCTSSIVHLCAISLDRYWAVSRALEYNSKRTPRRIKCIILTVWLIAAVISLPPLIYKGDQGPQPRGRPQCKLNQEAWYILASSIGSFFAPCLIMILVYLRIYLIAKRSNRRGPRAKGGPGQGESKQPRPDHGGALASAKLPALASVASAREVNGHSKSTGEKEEGETPEDTGTRALPPSWAALPNSGQGQKEGVCGASPEDEAEEEEEEEEEEEECEPQAVPVSPASACSPPLQQPQGSRVLATLRGQVLLGRGVGAIGGQWWRRRAQLTREKRFTFVLAVVIGVFVLCWFPFFFSYSLGAICPKHCKVPHGLFQFFFWIGYCNSSLNPVIYTIFNQDFRRAFRRILCRPWTQTAW*"
```

I was under the impression there would be a 1-1 mapping of NM_XXXXXX.X to NP_XXXXXX.X identifiers. But these results suggest otherwise? Is this expected? It seems odd that `NP_000673.2` has two different reference sequences.

I merge all the FASTA sequences produced into a single FASTA file and have been making the assumption that the protein haplotype identifier is unique (i.e. identifies an unique sequence). But this assumption appears to be invalid. If so, is it correct that the "unique key" of a protein haplotype is actual the combination of the transcript and protein haplotype identifier?

**Comment by aparton** [comment]
Hi,

Thanks for this report. I’ve taken a look into this today, and it looks like there’s some subtle behaviour going on underneath the hood to explain the difference in mappings. 

To provide RefSeq annotations within VEP and Haplosaurus, we use NCBI-provided GFF files (to provide the transcript set) and BAM files (to align these transcripts to the reference genome).  The BAM file does not contain a mapping for NM_000682.5, so we can’t map it to the reference genome. We do have an entry for NM_000682.6, which recognises that there is a CDS mismatch with an insertion of 9bp, leading to the difference of 3 AA between the two transcripts.

Filtering transcripts like this is a little tricky, as we assume that the transcript matches the reference genome when no entry is provided. We do have flags to describe the refseq transcript matching status within our GRCh38 dataset, however we do not have a recommended practise to identify these within GRCh37 I’m afraid. Additionally, we know that there are fewer transcripts that have this issue within our GRCh38 dataset, however that doesn’t help your current position. 

Sorry that I couldn’t give you a more helpful response. If you have any further questions, please don’t hesitate to ask.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any other questions or comments, please feel free to reopen it.

Kind Regards,
Andrew
