### ISSUE TITLE
vep does not read from config

### ISSUE THREAD

**Issue by lccc1230** [Ensembl/ensembl-vep#511]
Hi, 

Sorry if it's a stupid mistake, but I am quite frustrated. When I follow the instructions and put configuration through config, the vep continues but doesn't read anything from it

~/git/ensembl-vep/vep --config vep.ini -i some.vcf 

my vep.ini looks like:

dir /data/ensembl/vep/
assembly   GRCh37
fasta   /data/ensembl/Homo_sapiens.GRCh37.75.dna.toplevel.fa

I have tested it by putting all options outside, and only the vep.ini as:

output_file xx.output

The vep will run fine, but there is the output file name would not be as stated in the vep.ini through --config.

By the way I'm using release 96

Could anyone help please? 

Thank you

**Comment by at7** [comment]
Hi,
how do you know that vep is not reading the options from your vep.ini file? Do you get any error messages? You need to add to your vep.ini file if you want to use the database or cache files.
If you want to use the database you need to specifiy --database and --port 3337 (for GRCh37 database), if you want to use the cache files you need to specify --cache.
For your ini file you would add:
dir /data/ensembl/vep/
assembly GRCh37
fasta /data/ensembl/Homo_sapiens.GRCh37.75.dna.toplevel.fa
**database 1
port 3337**
`or`
**cache 1**
When I run vep with your options I get the `IMPORTANT INFORMATION` notification. Do you have your cache files stored under `/data/ensembl/vep/`? 
Thanks,
Anja

**Comment by at7** [comment]
Dear @lccc1230,
did my suggestions help to resolve the problem? I will close this issue now but feel free to reopen it if you still have the same error or if you have any related questions.

Best regards,
Anja
