### ISSUE TITLE
Failed custom annotation of GTF files

### ISSUE THREAD

**Issue by mattnev17** [Ensembl/ensembl-vep#520]
Hi,

I'm attempting to annotate variants in a custom set of proteins with the --gtf flag. When testing my script in VEP v96.3 in docker, using the GRCh37 gtf downloaded from Gencode, it works successfully:
**Script with gencode**
~~~
./vep -i ~/.vep/tester.vcf -o gencodeTest.vcf --port 3337 --gtf ~/.vep/Homo_sapiens.GRCh37.87.gtf.gz --force_overwrite --fasta /opt/vep/.vep/homo_sapiens/96_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz
~~~
**tester.vcf**
`21	48019237	rs116960944	C	G	6458160.75	PASS	AC=4873;AN=246164`

**Output for gencode**
~~~
rs116960944	21:48019237	G	ENSG00000160307	ENST00000291700	Transcript	3_prime_UTR_variant	515	-	-	-	-	-	IMPACT=MODIFIER;STRAND=-1;SOURCE=Homo_sapiens.GRCh37.87.gtf.gz
rs116960944	21:48019237	G	ENSG00000160307	ENST00000367071	Transcript	3_prime_UTR_variant	609	-	-	-	-	-	IMPACT=MODIFIER;STRAND=-1;SOURCE=Homo_sapiens.GRCh37.87.gtf.gz
rs116960944	21:48019237	G	ENSG00000160307	ENST00000397648	Transcript	3_prime_UTR_variant	796	-	-	-	-	-	IMPACT=MODIFIER;STRAND=-1;SOURCE=Homo_sapiens.GRCh37.87.gtf.gz
~~~

But when I tried to follow the specifications at https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff to build my own custom GTF file, it doesnt seem to recognize the transcripts and annotates all variants as 'intergenic_variant'. An example:
**Script with custom**
~~~
./vep -i ~/.vep/tester.vcf -o gtfCustom.vcf --port 3337 --gtf ~/.vep/gtfCustom.gtf.gz --force_overwrite --fasta /opt/vep/.vep/homo_sapiens/96_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz 
~~~
**tester.vcf**
`21	48019237	rs116960944	C	G	6458160.75	PASS	AC=4873;AN=246164`
**gtfCustom.gtf**
~~~ 
chr21`	noInFrame_19.gp	transcript	48019161	48019397	.	-	.	gene_id "juz3H1"; transcript_id "juz3H1"; transcript_biotype "protein_coding";
chr21	noInFrame_19.gp	exon	48019161	48019397	.	-	.	gene_id "juz3H1"; transcript_id "juz3H1"; exon_number "1"; exon_id "juz3H1.1";
chr21	noInFrame_19.gp	stop_codon	48019161	48019163	.	-	0	gene_id "juz3H1"; transcript_id "juz3H1"; exon_number "1"; exon_id "juz3H1.1";
chr21	noInFrame_19.gp	gene	48019161	48019397	.	-	.	gene_id "juz3H1";  gene_biotype "protein_coding";
chr21	noInFrame_19.gp	CDS	48019164	48019397	.	-	0	gene_id "juz3H1"; transcript_id "juz3H1"; exon_number "1"; exon_id "juz3H1.1";
chr21	noInFrame_19.gp	start_codon	48019395	48019397	.	-	0	gene_id "juz3H1"; transcript_id "juz3H1"; exon_number "1"; exon_id "juz3H1.1"; 
~~~
**Output for custom**
`rs116960944	21:48019237	G	-	-	-	intergenic_variant	-	-	-	-	-	-	IMPACT=MODIFIER`

Can you see where I've gone wrong?

Best,
Matt

**Comment by ens-lgil** [comment]
Dear @mattnev17,

It looks like the issue (in your example) comes from the fact that the `gene_id` is the same as the `transcript_id`.
I changed the `gene_id "juz3H1"` by `gene_id "A"` and I got this result:
```
rs116960944	21:48019237	G	A	juz3H1	Transcript	missense_variant	161	161	54	G/A	gGt/gCt	-	IMPACT=MODERATE;STRAND=-1;SOURCE=custom.gtf.gz
```
Let me know if it works for you when you change the gene IDs or the transcript IDs.

Best regards,
Laurent

**Comment by mattnev17** [comment]
Yes that has fixed the issue, thanks very much Laurent.

Best,
Matt
