### ISSUE TITLE
Error: installing cache files

### ISSUE THREAD

**Issue by milgri** [Ensembl/ensembl-vep#522]
Good afternoon,
I installed VEP and at the end of installment I tried to download some cache files from the list but I got an error:
(I tried to install cache files 
296 : homo_sapiens_merged_vep_96_GRCh38.tar.gz
298 : homo_sapiens_refseq_vep_96_GRCh38.tar.gz
300 : homo_sapiens_vep_96_GRCh38.tar.gz)

NB: Remember to use --merged when running the VEP with this cache!
 - downloading ftp://ftp.ensembl.org/pub/release-96/variation/VEP/homo_sapiens_merged_vep_96_GRCh38.tar.gz
Cannot open Local file /home/milda/.vep/tmp/homo_sapiens_merged_vep_96_GRCh38.tar.gz: Not a directory
 at INSTALL.pl line 1227.
curl failed (150), trying to fetch using LWP::Simple
Cannot open Local file /home/milda/.vep/tmp/CHECKSUMS: Not a directory
 at INSTALL.pl line 1231.
 - unpacking homo_sapiens_merged_vep_96_GRCh38.tar.gz
tar (child): /home/milda/.vep/tmp/homo_sapiens_merged_vep_96_GRCh38.tar.gz: Cannot open: Not a directory
tar (child): Error is not recoverable: exiting now

gzip: stdin: unexpected end of file
tar: Child returned status 2
tar: Error is not recoverable: exiting now
ERROR: Could not create directory /home/milda/.vep/homo_sapiens_merged

I get errors if I try to download and unpack it offline following instructions in https://gist.github.com/ckandoth/5390e3ae4ecf182fa92f6318cfa9fa97 :

perl INSTALL.pl --AUTO f --SPECIES homo_sapiens --ASSEMBLY GRCh38 --DESTDIR $VEP_PATH --CACHEDIR $VEP_DATA

produces an error:

ERROR:
Cannot open Local file /home/milda/.vep/homo_sapiens/95_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz: Not a directory

Thank you for your time and help.

**Comment by ens-lgil** [comment]
Dear @milgri,

It looks like the VEP installer didn't managed to create the `tmp` directory (`/home/milda/.vep/tmp/`).
Please, could you check if the directories `/home/milda/.vep/` and `/home/milda/.vep/tmp/` exist ?

For the second part, this is mainly because you need to download/install the cache before downloading/installing the fasta file. You might need to add the `c` value for the `AUTO` option ,e.g.:
```
export VEP_PATH=$HOME/vep
export VEP_DATA=$HOME/.vep
perl INSTALL.pl --AUTO cf --SPECIES homo_sapiens --ASSEMBLY GRCh38 --DESTDIR $VEP_PATH --CACHEDIR $VEP_DATA
```

Best regards,
Laurent

**Comment by milgri** [comment]
I have done that since I was following instructions on https://gist.github.com/ckandoth/5390e3ae4ecf182fa92f6318cfa9fa97 but the errors still appear.
Thank you for your time.

**Comment by ens-lgil** [comment]
This is strange ... we had some user issues regarding firewall settings but this doesn't exactly looks like it.

You can still install the cache and fasta file manually (it will take some time):
1. Cache
```
## Cache (15Gb)
cd $HOME/.vep
# If you have tabix installed:
curl -O ftp://ftp.ensembl.org/pub/release-96/variation/indexed_vep_cache/homo_sapiens_merged_vep_96_GRCh38.tar.gz
# Otherwise:
curl -O ftp://ftp.ensembl.org/pub/release-96/variation/vep/homo_sapiens_merged_vep_96_GRCh38.tar.gz

tar xzf homo_sapiens_merged_vep_96_GRCh38.tar.gz

# You can remove the archive if you want:
rm -f homo_sapiens_merged_vep_96_GRCh38.tar.gz
```

2. Fasta
```
## Fasta (860Mb)
cd $HOME/.vep/homo_sapiens_merged/96_GRCh38/
curl -O ftp://ftp.ensembl.org/pub/release-96/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
gzip -d Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
bgzip Homo_sapiens.GRCh38.dna.primary_assembly.fa
```

I hope this helps.

Best regards,
Laurent

**Comment by milgri** [comment]
For some reason, it shows that the directories /home/milda/.vep/ and /home/milda/.vep/tmp/ do not exist.

I have documented all the steps I have done and the errors I got:

https://gyazo.com/e794cb50c47e927777abc8b9e8c2a10f
https://gyazo.com/56af1896e86522e0acb66bb6fcc7b5bb
https://gyazo.com/00a2ec0d81d38d1bac2937ec2d740687
https://gyazo.com/5dc2a9d058fe5e068231111067471323

Thank you for your time and help.

**Comment by milgri** [comment]
Oh and I also installed cpan before running the line
perl INSTALL.pl --AUTO a --DESTDIR $VEP_PATH --CACHEDIR $VEP_DATA --NO_HTSLIB
with
perl -MCPAN -e 'install Bundle::DBI'

the terminal response:

Reading '/home/milda/.cpan/Metadata'
  Database was generated on Wed, 26 Jun 2019 07:56:20 GMT
Fetching with LWP:
http://www.cpan.org/authors/01mailrc.txt.gz
Reading '/home/milda/.cpan/sources/authors/01mailrc.txt.gz'
............................................................................DONE
Fetching with LWP:
http://www.cpan.org/modules/02packages.details.txt.gz
Reading '/home/milda/.cpan/sources/modules/02packages.details.txt.gz'
  Database was generated on Thu, 04 Jul 2019 07:17:02 GMT
.............
  New CPAN.pm version (v2.27) available.
  [Currently running version is v2.18]
  You might want to try
    install CPAN
    reload cpan
  to both upgrade CPAN.pm and run the new version without leaving
  the current session.




...............................................................DONE
Fetching with LWP:
http://www.cpan.org/modules/03modlist.data.gz
Reading '/home/milda/.cpan/sources/modules/03modlist.data.gz'
DONE
Writing /home/milda/.cpan/Metadata
DBI is up to date (1.642).
DBI::Shell is up to date (11.95).
Storable is up to date (3.15).
Net::Daemon is up to date (0.48).
Running install for module 'RPC::PlServer'
Checksum for /home/milda/.cpan/sources/authors/id/M/MN/MNOONING/PlRPC/PlRPC-0.2020.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring M/MN/MNOONING/PlRPC/PlRPC-0.2020.tar.gz with Makefile.PL
Checking for Sys::Syslog ... ok
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for RPC::PlServer
Writing MYMETA.yml and MYMETA.json
  MNOONING/PlRPC/PlRPC-0.2020.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for M/MN/MNOONING/PlRPC/PlRPC-0.2020.tar.gz
perldoc -t lib/RPC/PlServer.pm >README
You need to install the perl-doc package to use this program.
Makefile:901: recipe for target 'README' failed
make: *** [README] Error 1
  MNOONING/PlRPC/PlRPC-0.2020.tar.gz
  /usr/bin/make -- NOT OK
DBD::Multiplex is up to date (2.11).

**Comment by ens-lgil** [comment]
Dear @milgri,

Thank you very much for the installation steps. There might be an firewall issue (cf the  `curl` error in your last screenshot).
Did you try to create the directory `/home/milda/.vep/` before running `rsync` ?

It looks like the API has been successfully installed but you still have issue to download and intstall the cache and fasta files.
Did you try to run the commands I listed in my previous message ?

Best regards,
Laurent

**Comment by milgri** [comment]
I am trying to run them now, though it still shows that $HOME/.vep is not a directory. Trying to install the cache according to your instructions at the moment. I will let you know how that turns out.
Thank you very much for your help and time.

**Comment by milgri** [comment]
I followed your instructions but moving forward error ERROR: directory /home/milda/.vep not found
still occurs.

**Comment by ens-lgil** [comment]
Dear @milgri,

This is strange as it should have been created.
Is your `$HOME` defined and match `/home/milda/` ? e.g.: 
```
echo $HOME
/home/milda/
```
What do you get when you run the following command ?
```
ls -al /home/milda/ | grep "\.vep$"
```
Do you get something like this ?
```
drwxr-xr-x  3  milda  yourgroup  4096  Jul  05  09:40  .vep
```

Best regards,
Laurent

**Comment by milgri** [comment]
Good morning,
Running the command
echo $HOME
I get the result:
/home/milda/
so yes, $HOME is defined and matches /home/milda

And running the command
ls -al /home/milda | grep "\.vep$"
I get the result:
-rw-r--r--  1 milda milda 12733816981 Ιουλ  4 10:07 .vep

Thank you for your time and help.

**Comment by ens-lgil** [comment]
Dear @milgri,

Your `.vep` looks like a file and not a directory.
Could you remove it (`rm -rf /home/milda/.vep`) and then run the following commands:
```
mkdir /home/milda/.vep
cd  /home/milda/.vep
curl -O ftp://ftp.ensembl.org/pub/release-96/variation/indexed_vep_cache
tar xzf homo_sapiens_merged_vep_96_GRCh38.tar.gz
``` 
As we just release the version 97, you can use these commands instead if you want to use/install VEP 97:
```
mkdir /home/milda/.vep
cd /home/milda/.vep
curl -O ftp://ftp.ensembl.org/pub/release-97/variation/indexed_vep_cache
tar xzf homo_sapiens_merged_vep_97_GRCh38.tar.gz
```

Please, let me know if it works.

Best regards,
Laurent

**Comment by milgri** [comment]
Good afternoon,
after running the last line:
tar xzf homo_sapiens_merged_vep_97_GRCh38.tar.gz
(I also tried -xzf instead and adding sudo at the beginning of the line)
I get the error:
tar (child): homo_sapiens_merged_vep_97_GRCh38.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

Thank you for your time and help.

**Comment by ens-lgil** [comment]
Dear @milgri,

My bad, I forgot the file name int he `curl` command line!
Here is the edited command with the filename:
```
cd /home/milda/.vep
curl -O ftp://ftp.ensembl.org/pub/release-97/variation/indexed_vep_cache/homo_sapiens_merged_vep_97_GRCh38.tar.gz
tar xzf homo_sapiens_merged_vep_97_GRCh38.tar.gz
``` 

Best regards,
Laurent

**Comment by milgri** [comment]
Good morning,
everything works wonderfully, thank you very much for your help.
Best regards,
Milda
