### ISSUE TITLE
G2P error

### ISSUE THREAD

**Issue by shigej38** [Ensembl/ensembl-vep#527]
Use of uninitialized value in concatenation (.) or string at /home/ertan/.vep/Plugins/G2P.pm line 945.

ı have one warnings help me please

my command.
`./vep -i /home/ertan/Desktop/pipeline/playground/NECESSARY/DE-FMF1/DE-FMF1.vcf -o /home/ertan/Desktop/fmf.csv --offline --cache --merged --use_given_ref --force_overwrite --tab --plugin dbNSFP,/mnt/7C033C763BE8E7D8/ensembl-data/dbNSFP3.5/dbNSFP3.5.gz,ALL --coding_only --fasta /mnt/7C033C763BE8E7D8/ensembl-data/fasta/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa --show_ref_allele --numbers --assembly GRCh37 --biotype --canonical --domains --uniprot --ccds --symbol --protein --hgvs --no_escape --allele_number --individual all --humdiv --polyphen p --sift p --variant_class --plugin Condel,/home/ertan/.vep/Plugins/config/Condel/config/condel_SP.conf,p --plugin G2P,/mnt/7C033C763BE8E7D8/ensembl-data/G2P/DDG2P_10_7_2019.csv
`

**Comment by at7** [comment]
Dear @shigej38,
thank you for the bug report. I have written a [fix](https://github.com/Ensembl/VEP_plugins/pull/207) which will be merged later today. For now you can run the G2P plugin with --plugin G2P,**file=**/mnt/7C033C763BE8E7D8/ensembl-data/G2P/DDG2P_10_7_2019.csv which works.

Thank you,
Anja
