### ISSUE TITLE
VEP stdin 

### ISSUE THREAD

**Issue by madzayasodara** [Ensembl/ensembl-vep#528]
I have to parse some vcf.gz files before I can read them in vep (basically translate scaffold names to the chr names the cache has and the do some col and line cuting using cut and sed. 
I am trying doing this a for loop with:

```
for file in ./*.vcf.gz; do
gunzip -c ${file} | awk 'BEGIN{FS=OFS=\"\t\"} NR == FNR{key[\$1]=\$2; next} \$1 in key{\$1=key[\$1]} 1' ./map - | cut -f1-6 | sed '1,6d' | vep -i - - o ./"${file}"_dnds --species taeniopygia_guttata --force_overwrite --symbol --tab --cache --dir_cache ./
done
```

but vep does not treat - as the piped input 

`MSG: ERROR: File "-" does not exist`

My files are of course huge, and I would like to do this whithout creating temp files.

Does vep has something built in. What you suggest to do?

**Comment by willmclaren** [comment]
You can pipe output into VEP, just remove `-i -` from your command. You'll need to add `--format vcf` since VEP can't auto-detect input format from STDIN.

**Comment by madzayasodara** [comment]
Nice! It's working. Thank you
