### ISSUE TITLE
VEP97 Unsorted VCF error on sorted vcf.  

### ISSUE THREAD

**Issue by thomasperson** [Ensembl/ensembl-vep#530]
Howdy,

When running VEP97 with the command:
vep -i gnomad.exomes.r2.1.1.sites.21.sorted.vcf -o gnomad.exomes.r2.1.1.sites.21.VEP97.vcf --everything --cache --offline --vcf --dir_cache CACHEDIR/ --fasta human_g1k_v37_decoy.fasta.gz --merged --no_stats --force_overwrite --assembly GRCh37 -v --use_given_ref --format vcf

It is exiting with the error: 
Exiting the program. The input file appears to be unsorted. Please sort by chromosome and by location and re-submit.

I downloaded the sites only exome vcf from https://gnomad.broadinstitute.org/downloads.  I also uncompressed it and sorted with vcf-sort from vcftools to ensure it is sorted and used the b37 fasta is from the GATK 2.8 bundle.  gnomad.exomes.r2.1.1.sites.Y.vcf.bgz  works with no issue.  

Don't know if its relevent, but the downloaded cache files for homo_sapiens_merged_vep_97_GRCh37.tar.gz are 7GB smaller than they were for v96. I deleted them and redownloaded and still smaller and still same issues.

Thanks for your help,

Nate

**Comment by ens-lgil** [comment]
Dear @thomasperson,

I am investigating the gnomAD: file https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.21.vcf.bgz

We implemented the sorting check as unsorted VCF files slow down VEP and use more memory.
In the meantime, you can add the option [--no_check_variants_order](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_no_check_variants_order) to skip the sorting check.

About the VEP cache size differences, I can only see a big difference for the default VEP indexed cache file:
- 20Gb: ftp://ftp.ensembl.org/pub/release-96/variation/indexed_vep_cache/homo_sapiens_vep_96_GRCh37.tar.gz
- 13Gb: ftp://ftp.ensembl.org/pub/release-97/variation/indexed_vep_cache/homo_sapiens_vep_97_GRCh37.tar.gz

Is this actually that file you a refering ?
I downloaded the `96` and `97` `merged` files and they are all between 13Gb and 14Gb.
What it the size of your downloaded 97 cache file ?

Best regards,
Laurent

**Comment by seru71** [comment]
I am also facing the "input file appears to be unsorted" error. The input is bgzipped VCF, definitely sorted because it is tabix indexed.

The command is ```
vep --offline --cache --dir_cache /data/References/vep-cache --assembly GRCh38   -i /data/MNM00060.norm.vcf.gz -o /data/MNM00060.norm.vep.vcf.gz --vcf --no_stats --force_overwrite               --everything --custom /data/References/gnomad.genomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF,AC,AN --fork 8```

**Comment by thomasperson** [comment]
Howdy Laurent,

Thanks for the info, --no_check_variants_order seems to be working.

For the size questions, that was just something I noticed.  I often have issues of truncated downloads, so do extra checks on downloads and when I saw the size difference I didn't know if that was the cause or just my issue.  My server is reporting directory size of CACHEDIR/homo_sapiens_merged/96_GRCh37 to be 22GB, 97_GRCh37 to be 15GB.  

Cheers,

Nate

**Comment by carbocation** [comment]
I seem to be running into this issue on Web VEP for GRCh37 / VEP 97, annotating a VCF. I am wondering if, perhaps, something about the way that indels are coded in VCFs might explain it? Unfortunately since I'm using the web tool, I don't have much data to go off of. Just this:

```
Error:
Exiting the program. The input file appears to be unsorted. Please sort by chromosome and by location and re-submit.
```

**Comment by ens-lgil** [comment]
Dear @thomasperson, @seru71 and @carbocation,

We just pushed a fix regarding this issue and we are going to update the code of the Web VEP as well, on the Ensembl and the GRCh37 websites.

Best regards,
Laurent

**Comment by thomasperson** [comment]
Thanks @ens-lgil!

Pulled and rebuilt.  Works now!

Cheers,

Nate

**Comment by Hoeze** [comment]
Please re-open.
I got the same problem for VEP 98.3.
My input:
`vcf_df.select(["contigName", "start", "end", "referenceAllele", "alternateAlleles"]).filter("contigName == '22'").orderBy(["contigName", "start", "end"])`
It is definitively sorted.

**Comment by aparton** [comment]
Hi @Hoeze,

Are you also using the gnomad dataset as your input file, or are you using your own file? If you're using your own file, could you please send a copy to helpdesk@ensembl.org so that I can take a closer look?

Kind Regards,
Andrew

**Comment by Hoeze** [comment]
@aparton I debugged the problem a little bit:

- [test.vcf.gz](https://drive.google.com/open?id=1yMlqJgTzFid6SgHK4sFF5GVXYFMUfRJz)
  This file has multiple alleles per line
- [normalized_test.vcf.gz](https://drive.google.com/open?id=1PBSGvdITep5NREbi-7qll45EnNUTbuJb)
  This is the same dataset but with normalized variants and only one alternate allele per line

The normalized one works without problems, so I guess it has something to do with VEP normalizing start positions by itself.

**Comment by aparton** [comment]
Hi,

Thanks for these files. The file test.vcf.gz appears to be unsorted:

gunzip -c test.vcf.gz | head -n 10

##fileformat=VCFv4.2
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
22	16135229	.	G	A	.	.	.
22	16091037	.	A	G	.	.	.
22	16086704	.	G	C	.	.	.
22	16133562	.	A	G	.	.	.
22	16124028	.	C	T	.	.	.
22	16122309	.	G	A	.	.	.
22	16163196	.	A	T	.	.	.
22	16151958	.	C	A	.	.	.

Sorting this file by position should solve your issue - having multiple alleles per line shouldn’t affect the sorting check. Alternatively, the option —no_check_variants_order will prevent VEP from failing if it thinks your input file is unsorted, although your VEP analyses may be slightly slower.

Please let us know if that fixes your issue, and if there’s anything else we can do to help please don’t hesitate to get in touch.

Kind Regards,
Andrew

**Comment by dglemos** [comment]
I'm going to close this ticket. Please feel free to open a new one if you have more questions.

Best wishes,
Diana
