### ISSUE TITLE
VEP97 filter --tab vs --vcf count results different

### ISSUE THREAD

**Issue by cagaser** [Ensembl/ensembl-vep#531]
Hello VEP team, 

I am enjoying using VEP for annotation, including its custom annotations and plugins. Amazing tool. 

For testing purposes, I annotated ensembl-vep/examples/homo_sapiens_GRCh38.vcf with some custom annotations, in two format (--vcf and --tab): 

- gnomAD(gnomad.genomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz)
- kaviar(Kaviar-160204-Public-hg38-trim.vcf.gz)
- goNL (multisample.parents_only.info_only.vcf.gz)

I am trying to count the rare variants (AF < 0.01) using the filter_vep as follows:

```
filter_vep \
--force_overwrite \
--input_file inVCF \
--output_file outVCF \
--filter "gnomAD_AF <  0.01" \
--filter "kaviar_AF < 0.01" \
--filter "goNl_AF < 0.01"

```
However, I noticed that I get the two different count results from the two formats. 

The TAB format gives me:  AF < 0.01: 71 variants
The VCF format gives me: AF < 0.01: 7 variants 

What might be the reason for that?

Thank you in advance.

**Comment by helensch** [comment]
Hi

We are pleased to hear you are  enjoying using VEP for annotation. We appreciate feedback from users.

The number of lines in the VCF and tab output will not contain the same number of lines if a variant overlaps more than 1 transcript. filter_vep will then also report different number of lines matched.

Do the number of matched lines differ or the number of variants?

Information on VEP output formats is at:
https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#output

In the VCF output: Each prediction, for a given variant, is separated by the character "," in the CSQ INFO field (e.g. when a variant overlaps more than 1 transcript). The results are in a single line in the VCF output. 

In the tab output, each transcript is on a separate line. Filtering tab output could return more matched lines.

Helen

**Comment by cagaser** [comment]
Hello, 

Thank you very much for the quick reply. 
Indeed the number of (unique) variants in the TAB is the same as the the number of variants in the VCF format. 

Cedrick
