### ISSUE TITLE
Installation Failure: cram/cram_io.c:60:10: fatal error: lzma.h: No such file or directory

### ISSUE THREAD

**Issue by nroak** [Ensembl/ensembl-vep#54]
While installing vep release 88, I get this error.
```
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_encode.o cram/cram_encode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_external.o cram/cram_external.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_index.o cram/cram_index.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c:60:10: fatal error: lzma.h: No such file or directory
 #include <lzma.h>
          ^~~~~~~~
compilation terminated.
make: *** [cram/cram_io.o] Error 1
Compile didn't complete. No libhts.a library file found at INSTALL.pl line 749.
```

This error goes away with --NO_HTSLIB flag. Is there an alternate way to this?

**Comment by willmclaren** [comment]
This shouldn't occur if you have an up-to-date checkout of release/87 or release/88.

This error can arise during installation of newer versions of htslib, but VEP's installer has been updated to use a fixed version of htslib that does not depend on lzma.

**Comment by nroak** [comment]
So, I started ensembl-vep installation from scratch again. Now with the release/89 for the tool.
I'm still getting the exact same error. Is there any pre-requisite installation on my system?

**Comment by willmclaren** [comment]
Strange, I can't recreate this.

You may have luck if you install the lzma and bz2 packages - how you do this will depend on your system, Google is your friend here.

You may also like to try installing [htslib](https://github.com/samtools/htslib) and [Bio::DB::HTS](https://github.com/Ensembl/Bio-DB-HTS) manually, then run `INSTALL.pl` with `--NO_HTSLIB`.
