### ISSUE TITLE
v97 can't not output gnomad annotion?

### ISSUE THREAD

**Issue by flying-polarbear** [Ensembl/ensembl-vep#544]
api:v97.1
cache db:hg19-indexed

I have a snp: rs79605387, which I can get gnomAD freq information from other annotation tool.
But with vep, even when I config --failed from 0  to 1,
####code
vep --input_data rs79605387 --port 3337 (other parameters stored in vep.ini)

the result is still empty for gnomAD field. And I manually check the site in gnomad.exomes.r2.1.sites.INFO_ANNOTATIONS_FIXED.vcf.gz, which can see this rs79605387 site.
So. Why I have no gnomAD_AF information missing???

Yours Sincerely.
Gao

**Comment by aparton** [comment]
Hi,

I've just had a quick look at this, and I can obtain gnomAD frequencies for this variant. gnomAD frequencies can only be obtained while using a cache file, and with the additional flag `--af_gnomad` - https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_af_gnomad

If you were already doing both of these things, could you please send me your full parameter list?

Kind Regards,
Andrew

**Comment by flying-polarbear** [comment]
Hi Aparton,
The vep verision is 97.1, I redo this site:
---
vep --input_data rs79605387 --port 3337

But still no gnomAD field

Here is my vep.ini:
---
cache 1
cache_version 97
dir_cache /home/practice_med/database/vep_db
dir_plugins /home/practice_med/database/vep_db/VEP_plugins
fasta /home/practice_med/database/gatk_google_b37/human_g1k_v37_decoy.fasta
merged 1
plugin SingleLetterAA
plugin Carol
compress_output gzip
variant_class 1
sift b
polyphen b
gene_phenotype 1
regulatory 1
allele_number 1
show_ref_allele 1
numbers 1
hgvs 1
hgvsg 1
transcript_version 1
protein 1
symbol 1
ccds 1
uniprot 1
canonical 1
biotype 1
domains 1
xref_refseq 1
af 1
max_af
af_1kg 1
af_gnomad 1
failed 1
pubmed 1

**Comment by flying-polarbear** [comment]
> Hi,
> 
> I've just had a quick look at this, and I can obtain gnomAD frequencies for this variant. gnomAD frequencies can only be obtained while using a cache file, and with the additional flag `--af_gnomad` - https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_af_gnomad
> 
> If you were already doing both of these things, could you please send me your full parameter list?
> 
> Kind Regards,
> Andrew

[variant_effect_output.txt.gz](https://github.com/Ensembl/ensembl-vep/files/3436052/variant_effect_output.txt.gz)
here is my output, plz check it!

**Comment by aparton** [comment]
Hi,

Thanks for these, I’ve reran everything with your .ini file and I suspect it may be a tabix installation issue. 

Could you please run:

`tabix homo_sapiens_merged/97_GRCh37/7/all_vars.gz 7:151851544-151851544`

From inside your dir_cache folder, and let me know what output you get? If you get a tabix error, then you may need to (re) install it - http://www.htslib.org/doc/tabix.html <http://www.htslib.org/doc/tabix.html>

Kind Regards,
Andrew

**Comment by flying-polarbear** [comment]
Hi, 
`tabix homo_sapiens_merged/97_GRCh37/7/all_vars.gz 7:151851544-151851544` in my dir_cache folder goes that:

7	rs79605387	.	.	151851544	.	A/C	.	C	0.0076	...	.	C:0	C:0	C:0.0357	C:0	C:0.002	C:0.001362	C:0	C:0.002116C:0.0006206	C:2.898e-05	C:0	C:0.02602	C:0	C:0	C:0.001643	C:0.0008178
it seems no error

Best,

**Comment by aparton** [comment]
Hi,

Ok, looks like tabix is installed correctly. For the next test, could you please try running the queries:

1) vep --id rs79605387 --port 3337 —cache —dir /home/practice_med/database/vep_db —af  

2) vep --id rs79605387 —assembly GRCh37 —offline —cache —dir /home/practice_med/database/vep_db —af —fasta /home/practice_med/database/gatk_google_b37/human_g1k_v37_decoy.fasta

3) vep --id rs79605387 —assembly GRCh37 —offline —cache —dir /home/practice_med/database/vep_db —af_gnomad —fasta /home/practice_med/database/gatk_google_b37/human_g1k_v37_decoy.fasta

And could you please let me know if any of those queries give you frequency data as part of your output?

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi @flying-polarbear,

This may be caused by the same issue as #591. If you would like us to take another look, please feel free to reopen the ticket.

Kind Regards,
Andrew
