### ISSUE TITLE
[SOLVED] variant list

### ISSUE THREAD

**Issue by shigej38** [Ensembl/ensembl-vep#545]
ensembl-vep lists my variants and creates separate rows for the same variants. do I combine variants that appear in the same position in a single row?

my ensembl-vep output:
```

#Uploaded_variation
--
chr16_3293888_C/T
chr16_3293888_C/T
chr16_3293888_C/T
chr16_3293888_C/T
chr16_3293888_C/T
chr16_3293888_C/T
chr16_3293922_A/T
chr16_3293922_A/T
chr16_3304573_G/T
chr16_3304573_G/T
chr16_3304573_G/T
chr16_3304573_G/T
chr16_3304573_G/T
chr16_3304573_G/T
chr16_3304573_G/T
chr16_3304654_T/C
chr16_3304654_T/C
chr16_3304654_T/C
chr16_3304654_T/C
chr16_3304654_T/C
chr16_3304654_T/C
chr16_3304654_T/C
chr16_3304762_A/G
chr16_3304762_A/G
chr16_3304762_A/G
chr16_3304762_A/G
chr16_3304762_A/G
chr16_3304762_A/G
chr16_3304762_A/G

```

ı am using ensembl-vep release 97.2

**Comment by flying-polarbear** [comment]
you use merged cache? it may have altrrnater transcript for this site

**Comment by shigej38** [comment]
no I am using the --refseq parameter. already tagging variants that it finds with the --merged parameter as ensembl entrez or refseq.

**Comment by aparton** [comment]
Hi,

VEP will print an output line every time that it finds a transcript that overlaps with an input variant. For the example variant chr16_3293888_C/T, there are 8 overlapping transcripts that VEP finds within the RefSeq cache, and it will provide information for each of them. 

If you want to reduce each variant to a single row, then there are a few ways that this can be done, although almost all of them involve losing some information. We published a blog post on this earlier this year that goes into this in detail, you can find that here: http://www.ensembl.info/2019/03/22/cool-stuff-the-ensembl-vep-can-do-take-your-pick/ <http://www.ensembl.info/2019/03/22/cool-stuff-the-ensembl-vep-can-do-take-your-pick/>

Some options include:

1) Using the —most_severe flag, which will only provide one line of output for each variant, for the transcript with the most severe consequence - https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_most_severe <https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_most_severe>

2) Using the —vcf flag. This will retain all information, provide your output file in VCF format and provide multiple consequences for multiple transcripts as part of the INFO field - https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_vcf <https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_vcf>

3) Using the —pick flag, which will allow you to rank transcripts - https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_pick <https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_pick>

4) You can run VEP as normal, and then use the filter_vep script to reduce the number of lines returned after VEP has completed - https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html <https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html>. If, while running VEP, you use flags like —ccds, —appris or —mane, then you can use the filter_vep script to isolate these transcripts after annotation is complete. 

For more information on these flags, see here: https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html <https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html>. There are more options described in the blog post I mentioned, and there are many creative options you could come up with with the filter_vep script if you so choose.

If you have any more questions, please don’t hesitate to ask.

Kind Regards,
Andrew

**Comment by shigej38** [comment]
Thank you @aparton
