### ISSUE TITLE
Some HGVSc positions are off by 1

### ISSUE THREAD

**Issue by anergictcell** [Ensembl/ensembl-vep#547]
For some transcripts, the HGVSc position is off by 1 (can go both directions)

Using hg19 / GRCh37
VEP Version 95 - 97

**Two examples:**

**PAH:   NM_000277.1    chr12 - 103310908 - T - C**
http://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Results?tl=P4kXWUtQAiwCLnzG-5515536

Excpected annotation:
NM_000277.1:c.**1**A>G

Observed:
NM_000277.1:c.**2**A>G
![image](https://user-images.githubusercontent.com/875703/61955742-f83cf380-afbb-11e9-9505-a5785d9ec03a.png)

**GBE1:   NM_000158.3      chr3 - 81810578 - G - A**
http://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Results?tl=f6ml4C9olW6cF4Ni-5476997

Excpected annotation:
NM_000158.3:c.**91**C>T

Observed:
NM_000158.3:c.**90**C>T
![image](https://user-images.githubusercontent.com/875703/61955715-e5c2ba00-afbb-11e9-8932-be4e14504e6b.png)

In both cases, you can see that the HGVSc position is off by one compared to the CDS position

This is true for most (if not all) of those transcripts

**Comment by aparton** [comment]
Hi Jonas,

Thanks for this report, it is an issue we are aware of. As you probably know, not all RefSeq transcripts completely match the reference genome. In cases where they don't, we are now using alignment files provided by NCBI to create a new reference, matching the transcript, and use this for consequence calling.

Our HGVS calculation does not currently use this reference modification, but it is something we are working on and aim to include in a future release. VEP can report reference mismatches for GRCh38, but these data are not available for GRCh37.
More details on the differences to the reference genome and correcting transcript models using BAM can be found here:  https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#refseq <https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#refseq>

Kind Regards,
Andrew
