### ISSUE TITLE
vep install failed on macosx 10.12.6,  Bio::DB:HTS not found

### ISSUE THREAD

**Issue by zillurbmb51** [Ensembl/ensembl-vep#548]
Hello, I was trying to install ensembl-vep using perl INSTALL.pl script. I am getting the following error:
`ERROR: Shared Bio::DB:HTS library not found`
I have tried to install this module using:
`cpanm -S --force Bio::DB::HTS` but failed. The log file is: 
[cpanm.build.log](https://github.com/Ensembl/ensembl-vep/files/3436949/cpanm.build.log)

Any help? Best, Zillur

**Comment by at7** [comment]
Hi @zillurbmb51,
did you first try running the INSTALL.pl script? The ensembl-vep/INSTALL.pl script will install Bio::DB::HTS for you. If you are installing Bio::DB::HTS with cpanm we recommend using version 2.11.

Best regards,
Anja

**Comment by zillurbmb51** [comment]
Thank you Anja. Yes, first I tried INSTALL.pl script but failed several times.

**Comment by at7** [comment]
Could you please let me know which error you get when you run the INSTALL.pl script?

**Comment by zillurbmb51** [comment]
Here are the last few lines:
`gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-vcf-sweep.o test/test-vcf-sweep.c
gcc -pthread  -o test/test-vcf-sweep test/test-vcf-sweep.o libhts.a -lz 
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.9 - moving files to ./biodbhts
 - making Bio::DB:HTS
ld: warning: object file (compilet-mU272.o) was built for newer OSX version (10.12) than being linked (10.4)
--htslib '/Volumes/Macintosh' command line parameter does not contain expected files

This module requires htslib (http://htslib/org)
Install it if you have not done so already.

This script will attempt to locate htslib by looking for hts.h and libhts.a in:

  1. --htslib command line argument
  2. HTSLIB_DIR environment variable
  3. --prefix command line argument (which also sets installation location)
  4. Alien::HTSlib dependency resolver
  5. pkg-config (extra directories can be set in PKG_CONFIG_PATH environment variable)
  6. common library locations: /usr /usr/local, /usr/share, /opt/local

ERROR: Shared Bio::DB:HTS library not found
(base) rcmi-29:ensembl-vep mzillur$ 
`

**Comment by at7** [comment]
Bio::DB::HTS requires htslib and it looks like the installation fails because it cannot locate htslib. Did you set the DYLD_LIBRARY_PATH to PATH_TO/ensembl-vep/htslib? Or have you already installed htslib somewhere else?

**Comment by zillurbmb51** [comment]
Thank you. I think I have done this.
`export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/Volumes/Macintosh\ HD2/data/UPR_CANCER_2/ensembl-vep/htslib` 
How can I find if I have installed it in any other place?

**Comment by at7** [comment]
Don't worry. I you haven't installed htslib yourself before then there won't be more than one installation on your system. Reading the error message `--htslib '/Volumes/Macintosh' command line parameter does not contain expected files` again makes me wonder if the space in your path name is causing the problem. I will need to test it myself and get back to you when I know more. You can run the VEP installation script with --NO_HTSLIB.

**Comment by zillurbmb51** [comment]
Thank you. Yes. You are right. That space was causing the problem. So, I tried to install this in another directory. Cache file downloading taking too much time. which one I should download from these:

> 301 : homo_sapiens_merged_vep_97_GRCh37.tar.gz
> 302 : homo_sapiens_merged_vep_97_GRCh38.tar.gz
> 303 : homo_sapiens_refseq_vep_97_GRCh37.tar.gz
> 304 : homo_sapiens_refseq_vep_97_GRCh38.tar.gz
> 305 : homo_sapiens_vep_97_GRCh37.tar.gz
> 306 : homo_sapiens_vep_97_GRCh38.tar.gz
>

**Comment by at7** [comment]
I'm glad we solved the installation problem. With regard to the cache files, it really depends on your input data, is it on GRCh37 or GRCh38?, and it depends on which transcript annotations you are interested in: Ensembl transcripts (homo_sapiens_vep_97), RefSeq transcripts (homo_sapiens_refseq_vep_97) or both (homo_sapiens_merged_vep_97).

**Comment by zillurbmb51** [comment]
Ok. Thank you very much. It helps a lot. Best, Zillur
