### ISSUE TITLE
[SOLVED] How to add data?

### ISSUE THREAD

**Issue by shigej38** [Ensembl/ensembl-vep#549]
I have data on diseases caused by variants in genes. How do I add this data to my annotations?

**Comment by at7** [comment]
Hi @shigej38,
in which file format is your data stored? You could use our [custom annotations](http://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html) option.

Best regards,
Anja

**Comment by shigej38** [comment]
my file  format is.xlsx
file column is:

Orphanet Number | Disease | Inheritance | Inheritance | Orphanet Number | Disease | Gene Symbol | OMIM Gene Number | Gene


`

**Comment by at7** [comment]
We don't support annotations from Excel. I can only recommend that you reformat your data into a format which is supported by our custom annotations option. In you case the easiest would probably be  to reformat into bed or bed-like files. Please read [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html#custom_formats) more about supported data formats.

**Comment by shigej38** [comment]
I need to follow the process after converting the data to bed file. to add to the anotation

**Comment by at7** [comment]
Yes, first you need to prepare your bed file and then you can use it with the vep command and --custom [arguments] option.

**Comment by shigej38** [comment]
am I going to encode the arguments you mentioned in the bed file?

**Comment by at7** [comment]
You can store all your genes from your XLSX file in a custom BED file using the gene's genomic location (chr start end). Using VEP's custom annotation you can then check if your variants overlap any regions from your custom BED file.

**Comment by shigej38** [comment]
thank you @at7
