### ISSUE TITLE
No Option to Specify Plugins Directory

### ISSUE THREAD

**Issue by DarioS** [Ensembl/ensembl-vep#552]
It's possible to specify a custom cache directory using `-c` but plugins seem to be installed into `~/.vep/Plugins/` with no option to change it. Could an option be added for specifying a plugin directory to make it consistent with the cache?

**Comment by at7** [comment]
We will add such an option for our next release 98. Thank you for the feedback.

**Comment by DarioS** [comment]
I can see that this option is available with release 98.
