### ISSUE TITLE
Missing RS identifiers

### ISSUE THREAD

**Issue by mikyatope** [Ensembl/ensembl-vep#553]
I'd like to report some variants incorrectly lack dbSNP RS identifier:

rs12532895 (chr7:6043386)
rs11528010 (chr10:88635779)
rs63750668 (chr7:6026708)

(GRCh37 coordinates)

This has been observed in version 94, and also after an update to version 97. 

RS correctly appear using the latest dbSNP database as custom annotation. However, these are not new RS's, they are correctly registered in Ensembl database.

I'm sorry the samples are from clinical patients, I cannot provide the raw files to replicate the behaviour, but wanted to report it somehow.

**Comment by ens-lgil** [comment]
Dear @mikyatope,

These 3 variants have been flagged as suspect by dbSNP in the release 151 (Validation status):
- dbSNP [rs12532895](https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?do_not_redirect&rs=rs12532895)
- dbSNP [rs11528010](https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?do_not_redirect&rs=rs11528010)
- dbSNP [rs63750668](https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?do_not_redirect&rs=rs63750668)

Therefore we `flagged` these variants as well in Ensembl:
- Ensembl [rs12532895](https://grch37.ensembl.org/Homo_sapiens/Variation/Explore?v=rs12532895)
- Ensembl [rs11528010](https://grch37.ensembl.org/Homo_sapiens/Variation/Explore?v=rs11528010)
- Ensembl [rs63750668](https://grch37.ensembl.org/Homo_sapiens/Variation/Explore?v=rs63750668)

By default the `flagged` variants are excluded in the VEP results.
However you can include them, with the option `--failed 1` ([see further documentation](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_failed)).

Best regards,
Laurent

**Comment by mikyatope** [comment]
Thank you very much for the clarification. We missed that flag since it's not displayed in dbSNPs new interface.

Kind regards,
