### ISSUE TITLE
MSG: Missing reference or alternate sequence(VEP 97.0)

### ISSUE THREAD

**Issue by ZhangXiujuan** [Ensembl/ensembl-vep#554]
Hi,

I'm useing VEP 97.0 to annotate `clinvar_20190708.vcf.gz`. 

The following error was reported for the first time: `Exiting the program. The input file appears to be unsorted. Please sort by chromosome and by location and re-submit.`. Even though I've sorted it. 

So I add `--no_check_variants_order` to run again, and it runs  slowly. Unfortunately, I got an error message again: `-------------------- EXCEPTION --------------------
MSG: Missing reference or alternate sequence
STACK Bio::EnsEMBL::Variation::Utils::Sequence::trim_sequences /home/usr/miniconda3/share/ensembl-vep-97.0-0/Bio/EnsEMBL/Variation/Utils/Sequence.pm:952
STACK Bio::EnsEMBL::Variation::Utils::Sequence::get_matched_variant_alleles /home/usr/miniconda3/share/ensembl-vep-97.0-0/Bio/EnsEMBL/Variation/Utils/Sequence.pm:1134
STACK Bio::EnsEMBL::VEP::AnnotationType::Variation::compare_existing /home/usr/miniconda3/share/ensembl-vep-97.0-0/modules/Bio/EnsEMBL/VEP/AnnotationType/Variation.pm:176
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::VariationTabix::_annotate_pm /home/usr/miniconda3/share/ensembl-vep-97.0-0/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/VariationTabix.pm:239
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::VariationTabix::annotate_InputBuffer /home/usr/miniconda3/share/ensembl-vep-97.0-0/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/VariationTabix.pm:120
STACK Bio::EnsEMBL::VEP::Runner::_buffer_to_output /home/usr/miniconda3/share/ensembl-vep-97.0-0/modules/Bio/EnsEMBL/VEP/Runner.pm:402
STACK (eval) /home/usr/miniconda3/share/ensembl-vep-97.0-0/modules/Bio/EnsEMBL/VEP/Runner.pm:665
STACK Bio::EnsEMBL::VEP::Runner::_forked_process /home/usr/miniconda3/share/ensembl-vep-97.0-0/modules/Bio/EnsEMBL/VEP/Runner.pm:659
STACK Bio::EnsEMBL::VEP::Runner::_forked_buffer_to_output /home/usr/miniconda3/share/ensembl-vep-97.0-0/modules/Bio/EnsEMBL/VEP/Runner.pm:490
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /home/usr/miniconda3/share/ensembl-vep-97.0-0/modules/Bio/EnsEMBL/VEP/Runner.pm:361
STACK Bio::EnsEMBL::VEP::Runner::run /home/usr/miniconda3/share/ensembl-vep-97.0-0/modules/Bio/EnsEMBL/VEP/Runner.pm:202
STACK toplevel /home/usr/miniconda3/bin/vep:223
Date (localtime)    = Mon Aug  5 16:22:49 2019
Ensembl API version = 97
Died in forked process 34655`

However, I can successfully run my own test data without `--no_check_variants_order`.

There is my command line: `vep -i clinvar_20190708.vcf.gz -o clinvar_20190708.ann.vcf --force --no_stats --cache --dir dir/vep_cache -offline --fasta dir/Homo_sapiens_assembly38.fasta --refseq --use_given_ref --exclude_predicted --vcf  --assembly GRCh38 --variant_class --sift b --polyphen b --regulatory --allele_number --total_length --numbers --no_esc
ape --hgvs --protein --symbol --canonical --biotype --check_existing --af --max_af --af_1kg --af_esp --af_gnomad --pubmed --failed 1 --flag_pick_allele --no_check_variants_order --custom clinvar_20190708.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNSIGCONF,MC --custom gnomad.exomes.r2.1.sites.grch38.noVEP.vcf.gz,gnomAD,vcf,exact,0,AF,AC --plugin dbscSNV,dbscSNV1.1_GRCh38.txt.gz --plugin dbNSFP,dbNSFP4.0a.gz,SIFT_score,SIFT_pred --plugin ExAC,ExAC.0.3.GRCh38.vcf.gz,AC,AN --plugin ExACpLI,ExACpLI_values.txt --plugin LoFtool,LoFtool_scores.txt --fork 4`

Thanks for your help,
Zhang

**Comment by ima23** [comment]
Hi @ZhangXiujuan,

thank you for your detailed report. 
We have pushed a fix on a VEP 97 dependency (ensembl-variation). Please could you reinstall VEP and the dependent API by selecting `(y)` to the question below:

`Do you want to continue installing the API (y/n)? `

Kind regards,
Irina

**Comment by ZhangXiujuan** [comment]
Hi,

I have reinstalled vep and it works.

Thanks.

**Comment by ima23** [comment]
Glad to hear it is working and thanks for letting us know. 
I will close this issue, but please feel free to reopen it or submit a new issue if you have any other questions.

Kind regards,
Irina
