### ISSUE TITLE
ERROR Failed to fork

### ISSUE THREAD

**Issue by lindsay-liang** [Ensembl/ensembl-vep#556]
I'm running a very large WGS VCF (321G) through VEP v95 on a machine with 32cpus and 256G of RAM.  The command is:

```
vep --fork 16 --assembly GRCh38  --verbose --offline  --vcf --force_overwrite  --buffer_size 800000000  -i /input/cos-wgs.gt.snp.indel.recal.vcf -o  /input/cos-wgs.gt.snp.indel.recal.anno.vcf --no_stats  --polyphen p  --ccds  --numbers  --canonical  --protein  --biotype  --uniprot  --tsl  --appris  --per_gene  --pick  --pick_order canonical,appris,tsl,biotype,ccds,rank,length  --distance 2000  --nearest symbol  --symbol  --af_1kg --af_gnomad --max_af --cache  --dir /root/.vep --plugin ExACpLI --plugin LoF,gerp_file:/root/.vep/Plugins/GERP_scores.final.sorted.txt.gz,loftee_path:/root/.vep/Plugins/
```

Returning:

```
-------------------- EXCEPTION --------------------
MSG: ERROR: Failed to fork

STACK Bio::EnsEMBL::VEP::Runner::_forked_buffer_to_output /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:488
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:361
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:202
STACK toplevel /opt/vep/src/ensembl-vep/vep:225
Date (localtime)    = Tue Aug  6 17:31:03 2019
Ensembl API version = 95
---------------------------------------------------
```

How can I fix this?

**Comment by aparton** [comment]
Hi Lindsay,

Reducing the buffer_size should allow VEP to fork correctly. The default buffer_size value of 5000 would be an appropriate value to use here - while the power of your system would likely support an increased buffer size, this is likely to only provide a very minor speedup in your annotations.

As an aside, there are a number of steps that you can take to ensure that your VEP installation is running as quickly as possible, which may be useful to you as you’re processing such a large VCF file. You can find more information about these steps here: http://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#faster <http://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#faster>

Let me know if that solves your problem, and if you have any other questions please don’t hesitate to ask.

Kind Regards,
Andrew

**Comment by lindsay-liang** [comment]
Ah ok, that's tremendously helpful!  

Are there any further speed ups? Our group frequently uses VEP on large cohorts and at the moment it's the bottleneck in our processing pipeline.  Since we're on the cloud, spinning up machines with high mem/CPU isn't an issue.

So I guess my question is closer to - what's the resource that I can gratuitously throw at VEP to get it run as fast as possible? E.g having 72 CPUs and having buffer set to 5000?  

(Re: I've got the container + all of the plugins/reference files + their indexes tar'd on the cloud so installation for me isn't an issue).

Thanks in advance Andrew!

**Comment by aparton** [comment]
Hi Lindsay,

Unfortunately there’s no single resource to feed VEP to significantly improve runtimes, however if we assume that significant cloud resources are available then there are some optimisations that you can make.

1) Ensure that you’re only asking VEP for the annotations that you’re looking for. When only predicting consequences, VEP can annotate an exome in less than 4 minutes. With the —everything flag added, then this can take up to 20x longer. While most of the flags you use are not computationally intensive, some of them (e.g. the plugins) can add significant amounts to runtime. If it’s relevant in your case, it may be worth running your initial VEP analyses, filtering based on your results and then rerunning VEP on the filtered dataset to only provide detailed analyses on the variants you are particularly interested in.

2) As linked in my previous mail, there are a collection of installation related optimisations that you can make to speed up VEP. The biggest improvements you can make here would be to install ensembl-xs and Set::IntervalTree, although the others will also provide speedups if they’re relevant to you.

3) Multithreading in VEP utilises the Perl forking system, which has a few limitations. We have found in the past that the optimal number of forks is 4 (although some people have had success with 8), and as such it’s faster and more reliable to split a large input file into chunks and run multiple VEP instances with fewer forks. Splitting will provide quicker results than simply running VEP with `—fork 64` for example, and if you already have a VEP container setup then this should be relatively easy to do.

4) Regarding the buffer_size, you can get away with increasing it if you have sufficient memory, however the previous tips will provide you with a more significant speed-up. 

If there’s anything else we can do to help, let me know.

Kind Regards,
Andrew

**Comment by lindsay-liang** [comment]
Ah that's all great information. Thanks!

**Comment by yangyxt** [comment]
Hi I just found my VEP command using tons of memory... with fork at 4. 
It's just insane that annotating a 1.5 Mb VCF file with around 30k variants would cause up to 200 GB peak memory....
I make sure my input vcf file is sorted bgzipped and tabix indexed.

And also I found that sometimes the top record more than **4 processes (like 6)** derived by the vep and here is the screenshot:
![image](https://user-images.githubusercontent.com/40780228/149606866-8ec78be3-7f24-4397-9988-553259539b21.png)

For your reference, the original commands are shown below:
`
vep 
-i input.vcf.gz 
--format vcf 
--use_given_ref 
--assembly GRCh37 
--cache 
--fork 4 
--buffer_size 3000 
--fasta /paedyl01/disk1/yangyxt/indexed_genome/ucsc.hg19.fasta ${mode} 
--dir_cache /paedyl01/disk1/yangyxt/public_data/ensembl-vep/caches 
--tab 
--verbose 
--dir_plugins /paedyl01/disk1/yangyxt/ngs_scripts/UTRannotator,/paedyl01/disk1/yangyxt/ngs_scripts/loftee,/paedyl01/disk1/yangyxt/ngs_scripts/VEP_plugins 
-plugin LoF,loftee_path:/paedyl01/disk1/yangyxt/ngs_scripts/loftee,fast_length_calculation:slow,human_ancestor_fa:${human_ancestor_file},conservation_file:${conservation_file} 
-plugin UTRannotator,/paedyl01/disk1/yangyxt/ngs_scripts/UTRannotator/uORF_5UTR_GRCh37_PUBLIC.txt 
--custom ${vep_gerp_score},GERP,bigwig 
--force_overwrite 
--no_check_variants_order 
-o vepoutput
`

**Comment by dbolser** [comment]
I had a quick look at the code, and I don't see forking happening in the main vep script...

Here is a hacky bash approach for processing chr1 across 32 cores:

```bash
chr=chr1

# Get the length of the chromosome
e=$(grep -w $chr ENCFF792NJK.tsv | cut -f 2)

# Chop it up...
x=$(perl -e "print int($e/32)+1")
echo $chr $e $x

# Bash magic
sequence=($(seq -w 0 $x $e) $e)
echo ${sequence[0]} ${sequence[1]} ${sequence[31] ${sequence[32]}

# I think bash coders are self loathing...
for (( i=0; i<${#sequence[@]} - 1; i++ )); do
    echo $chr:${sequence[i]}-${sequence[i+1]}
    time vep --config config.ini \
        -i <(tabix Input/$chr.tab.gz $chr:${sequence[i]}-${sequence[i+1]})
        -o Test/chr1/$chr:${sequence[i]}-${sequence[i+1]}.vep.gz \
        &> Test/chr1/$chr:${sequence[i]}-${sequence[i+1]}.out &
done
```
