### ISSUE TITLE
genotype information of multiple samples in VEP output

### ISSUE THREAD

**Issue by QANGFQ** [Ensembl/ensembl-vep#557]
Hi,

I use VEP command line version 97.
How to write genotypes of multiple samples per each variant like vcf format into VEP output
(tab, vcf format)?
The genotype information is present in VEP input(vcf file) but it isn't in VEP output...
Could you let me know a solution for this?

Thank you

**Comment by ens-lgil** [comment]
Dear @QANGFQ,

VEP will only keep your input genotypes with the VCF output format.
Here is an example:

- Input VCF file (with 2 genotypes)
```
##fileformat=VCFv4.2
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO FORMAT SAMPLE1 SAMPLE2
1	230710048	rs699	A	G	.	.	.	GT	1|1	1|0
``` 

- VEP command line (using the option `--vcf` to have the VEP output in VCF format):
```
./vep -i input.vcf -o output.vcf --cache --offline --assembly GRCh38 --fasta Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz --vcf
```

- Output VCF file (with genotypes `GT	1|1	1|0`):
```
##fileformat=VCFv4.2
##VEP="v97" ...
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|...">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO FORMAT SAMPLE1 SAMPLE2
1	230710048	rs699	A	G	.	.	CSQ=G|missense_variant|MODERATE|AGT|ENSG00000135744|Transcript|ENST00000366667|protein_coding|2/5||||843|803|268|M/T|aTg/aCg|||-1||HGNC|HGNC:333,G|downstream_gene_variant|MODIFIER|AL512328.1|ENSG00000244137|Transcript|ENST00000412344|lncRNA|||||||||||650|-1||Clone_based_ensembl_gene|	GT	1|1	1|0
```

Best regards,
Laurent

**Comment by QANGFQ** [comment]
Dear Laurent,

Thank you for detailed explanation!

I have an additional question about this issue.
Is there any command line or module to extract specific information on CSQ field so that the VEP output in VCF format could be transformed to the output like tab format having multiple genotypes ?

Thank you

**Comment by ens-lgil** [comment]
We don't have such feaure at the moment, mainly because the genotypes data are not processed by VEP itself.

There is an option to select the CSQ field(s) you want in your VEP VCF output: [--fields](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_fields).

There is also a tool available to convert VEP VCF output into TAB format, but I haven't tested it and I don't know if this will include the genotypes data: [https://vatools.readthedocs.io/en/latest/vep_annotation_reporter.html](https://vatools.readthedocs.io/en/latest/vep_annotation_reporter.html).

Best regards,
Laurent

**Comment by willmclaren** [comment]
You can achieve this with a combination of this bcftools plugin and bcftools query

http://samtools.github.io/bcftools/howtos/plugin.split-vep.html

**Comment by QANGFQ** [comment]
Dear Laurent and William, 

Thank you for your helpful comments.
I'll try tools or a command line option that you told me.

Thank you

**Comment by ens-lgil** [comment]
I am closing this issue, but if you have any more questions please feel free to reopen it.

Best regards,
Laurent
