### ISSUE TITLE
Allow for reciprocal overlap on custom tracks (gnomAD-SV)

### ISSUE THREAD

**Issue by fgvieira** [Ensembl/ensembl-vep#563]
I called SV on some samples, and I'd like to add gnomAD-SV frequencies to my calls but, as it is right now, the two SVs must either be an `exact` match or `overlap` (by at least 1 bp). For SVs, none of the options is ideal since it is highly unlikely that the two SVs will have the exact same coordinates, but also because two different SVs might overlap.

I was thinking if it would b possible to define a reciprocal overlap threshold (e.g. 80%):
```
custom          gnomad_v2_sv.sites.vcf.gz,gnomAD-SV,vcf,overlap_80,0,AFR_AF,AMR_AF,EAS_AF,EUR_AF,OTH_AF,POPMAX_AF
```

**Comment by sarahhunt** [comment]
Hi @fgvieira,
We have a new StructuralVariantOverlap plugin in our current release which allows more refined annotation of overlaps for SV data. It defaults to 80%, but is configurable. There's more information here-

http://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html

**Comment by fgvieira** [comment]
Hi @sarahhunt,

thanks for your quick reply. I gave it a try and, even though I found some issues (will report it on the VEP-plugins issue), I think I can use it.
