### ISSUE TITLE
how to remove "##" encoding header line dosen't remove "#" encoding line

### ISSUE THREAD

**Issue by shigej38** [Ensembl/ensembl-vep#568]
Hello,
I'm using the 97 version of ensembl-vep. When I give the "--no_header" parameter, it removes the header information of the columns separated by the character "#" and the part of the information separated by the character "##", but this does not work for me.
I want to delete the header part that starts with the "#" character and the headers encoded with "##" character. how can I solve this problem.

thank you.

**Comment by at7** [comment]
Hi @shigej38,
if you use --no_header vep won't write any header lines into your output file. The header lines in your input file won't change.
Best,
Anja

**Comment by shigej38** [comment]
Hi @at7 
my problem is that this "--no_header" parameter deletes all headers but I want to keep the header line encoded with the character "#" containing the column names.

**Comment by at7** [comment]
I see your point now. However in our documentation of the --no_headers flag we say that using the flag doesn't write header lines to the output file and according to the VCF file specifications the column names are also considered as a header line. Could you filter your output file as a post-processing step for the header lines you want to keep instead?

**Comment by shigej38** [comment]
can you explain how the filtering you mentioned?

**Comment by at7** [comment]
Here are a few suggestion for how you can filter your output file: https://www.biostars.org/p/49660/ Just make sure that you only remove lines which start with ##.

**Comment by shigej38** [comment]
Thank you your answer my problem it's solved
