### ISSUE TITLE
dbNSFP plugin replacement characters - vep 97

### ISSUE THREAD

**Issue by ZhangXiujuan** [Ensembl/ensembl-vep#569]
Hi,

There's a question about dbNSFP plugin. 
The default replacements: `; to ,` and `| to &`.
However, all characters (`, ; |`) of Interpro_domain are replaced by `&`. 
It makes the results messy.

How can I solve this problem？

Thank you

**Comment by at7** [comment]
Hi,
we do provide support for customising the replacement logic which is described in more detail [here](https://github.com/Ensembl/VEP_plugins/blob/release/97/dbNSFP.pm#L85-L93). Please try  running the dbNSFP plugin with the replacement logic file as described and let me know if you are still having the same problem.
Best wishes,
Anja

**Comment by ZhangXiujuan** [comment]
Thanks reply.
What is the format of the file dbNSFP_replacement_logic? I did not find it.

**Comment by at7** [comment]
You can use the file provided in the VEP_plugins directory: https://github.com/Ensembl/VEP_plugins/blob/release/97/dbNSFP_replacement_logic And the format is: colname from to. Colname=column name from dbNSFP file. from=character which needs to be replaced. to=character used for replacement.

**Comment by ZhangXiujuan** [comment]
Thank you very much.
I will try it.

**Comment by ZhangXiujuan** [comment]
dbNSFP_replacement_logic working.
The `,` is still replaced with `&`, however I want to keep it.
Is there any other way?

Thanks

**Comment by at7** [comment]
Dear @ZhangXiujuan,
could you please send me an example where _,_ is replaced by _&_? The default is to replace _|_ by _&_. It would be best if you could send me also the full command which you use for adding the dbNSFP plugin including the dbNSFP file version.
Thank you,
Anja

**Comment by ZhangXiujuan** [comment]
Oh, Sorry, I ignored this.

my command line:
```
--plugin dbNSFP,/vep_cache/dbNSFP4.0a.gz,/Plugins/dbNSFP_replacement_logic,REVEL_score,VEST4_score,Interpro_domain
```

dbNSFP_replacement_logic: 
```
colname from to
default ; ,
default | &
Interpro_domain ; ##
Interpro_domain | &
```

Since the downloaded `dbNSFP.pm` does not support `4.0a`, I added the code `elsif ($file =~ /4\.0a/){$version = '4.0';}` . I don't think this affects.

e.g. (just a part): 
dbNSFP  file
```
1  1045996  C  T  .;Factor I / membrane attack complex|EGF-like domain|Follistatin-like, N-terminal
```
annotate result
```
1  1045996  C  T  .##Factor_I_/_membrane_attack_complex&EGF-like_domain&Follistatin-like&_N-terminal
```

**Comment by at7** [comment]
Thank you for the example. The replacement from ',' to '&' is part of the VCF output writer. In order to conform with the VCF file specification we need to replace commas because according to the VCF file specification commas are only permitted as delimiters for lists of values. In our VCF output writer we use the following replacements: 
* , to &
* ; to %3B  
* a space character to _
* | to &

If you want to keep the VCF output format the comma character can only be used as a delimiter for lists of values and will otherwise be replaced by &.

The dbNSFP plugin has been updated for release 98 which is planned for September to work with the newest dbNSFP file.

Best regards,
Anja

**Comment by ZhangXiujuan** [comment]
Thanks for the detailed explanation !

**Comment by at7** [comment]
I will close this issue now. But please reopen this issue for related questions or please create a new issue for any new questions. Thank you.
