### ISSUE TITLE
 hg19 and --hgvsg

### ISSUE THREAD

**Issue by christianbioinf** [Ensembl/ensembl-vep#57]
I am observing an issue using vep 89.3 together with the flag `--hgvsg` and hg19 (from http://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/) as reference genome. With the downloadable GRCh37.75, it works fine but for some reason I get the following error when using hg19 (chromosomes are named with the prefix "chr" and the mitogenome is different).

```
$ perl /u/scratch/tools/vep/89.3/binary/linux/vep --offline --cache --dir /u/scratch/genomes/H_sapiens/UCSC/hg19/Annotation/variation/vep --fasta hg19/hg19.fa -i test.vcf.gz --vcf -o out.vcf.gz --refseq --species homo_sapiens --format vcf --hgvsg --force_overwrite
substr outside of string at /u/scratch/tools/vep/89.3/binary/linux/Bio/EnsEMBL/Variation/Utils/Sequence.pm line 517, <$fh> line 117.
Use of uninitialized value $ref_allele in string eq at /u/scratch/tools/vep/89.3/binary/linux/Bio/EnsEMBL/Variation/Utils/Sequence.pm line 520, <$fh> line 117.
Use of uninitialized value in concatenation (.) or string at /u/scratch/tools/vep/89.3/binary/linux/Bio/EnsEMBL/Variation/Utils/Sequence.pm line 648, <$fh> line 117.
Specifically, the error occurs when vep parses a variant entry of chrY and tries to do a substring of an empty string. However, also ref_slices ($ref_seq in function hgvs_variant_notation) of other chromosomes seem to be off (many Ns) and different to the ones I see with the GRCh37.75 genome.
```
It seems odd that up to now I did not have any troubles with hg19 (e.g. with `--hgvs`).

I have attached the test file containing only one variant on chrY ([test.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/1076820/test.vcf.gz)). To generate the hg19 reference, just execute the following commands.
```
mkdir hg19 && cd hg19 && wget -O - http://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/chromFa.tar.gz | tar -xzvf - && cat chr* > hg19.fa && rm chr* && cd ..
```

**Comment by willmclaren** [comment]
It's possible that you are experiencing the same bug discussed [here](https://github.com/chapmanb/bcbio-nextgen/issues/1948).

Basically, the fix required a patch to the ensembl-variation module (as opposed to this ensembl-vep repo). If you re-run INSTALL.pl to pick up the patched ensembl-variation then hopefully this should fix your issue.

**Comment by christianbioinf** [comment]
Thanks for the suggestions. I checked out the code again, re-run the INSTALL.pl but the issue remains. I checked the `Bio/EnsEMBL/Variation/Utils/FastaSequence.pm` file) and the fix is included. It appears however that even though the error only occurs with `--hgvsg`, the HGVSc output is also incorrect.

When executing the following call, I get `NR_001543.2:n.425-5051N>T` with hg19 and `NR_001543.2:n.425-5051G>T` with VEP's GRCh37.75.
```
perl /u/scratch/tools/vep/ensembl-vep/vep --offline --cache --dir /u/scratch/genomes/H_sapiens/UCSC/hg19/Annotation/variation/vep --fasta hg19/hg19.fa -i test.vcf.gz -o stdout --hgvs --tab --fields HGVSc --refseq --species homo_sapiens --format vcf --force_overwrite
```

**Comment by willmclaren** [comment]
Another possible issue is FASTA index corruption. Try removing the indexes and re-running (VEP will re-generate the index).

```rm hg19/hg19.fa```

Also, if you have Bio::DB::HTS installed, you might like to try compressing the FASTA with bgzip before indexing, this gives faster performance:

You can check with:

```perl -MBio::DB::HTS -e 'print "OK\n"'```

To compress and run VEP with compressed file:

```bgzip hg19/hg19.fa
perl /u/scratch/tools/vep/ensembl-vep/vep --offline --cache --dir /u/scratch/genomes/H_sapiens/UCSC/hg19/Annotation/variation/vep --fasta hg19/hg19.fa.gz -i test.vcf.gz -o stdout --hgvs --tab --fields HGVSc --refseq --species homo_sapiens --format vcf --force_overwrite```

**Comment by christianbioinf** [comment]
I already tried removing the fasta index and let it generate by VEP (both index files were the same) but the issue remained. Now, I have also tried it on the bgzip-compressed fasta file but the issue remained as well.

**Comment by willmclaren** [comment]
What cache version are you using? If you are not using a later version, the cache may not contain a [synonyms file](http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_synonyms) that allows for different chromosome namings.

**Comment by christianbioinf** [comment]
I am using the cache `89_GRCh37` which I got by executing the following command.
```
wget -O - ftp://ftp.ensembl.org/pub/release-89/variation/VEP/homo_sapiens_refseq_vep_89_GRCh37.tar.gz | tar -xzvf -
```
Therein, a `chr_synonyms.txt` file is present but since it does not contain a `chrY <=> Y` entry, I also tried my own file (which consists only of one line `Y<tab>chrY`) and provided it with the parameter `--synonyms`. Still no luck.

**Comment by willmclaren** [comment]
OK, there's a precedence issue with the synonyms loading which is causing a problem. If you concatenate the synonym file you created onto the end of the existing one 
(homo_sapiens_refseq/89_GRCh37/chr_synonyms.txt) it should work.

I'll look into a proper fix for this, though. Thanks for helping get to the bottom of it.

**Comment by willmclaren** [comment]
Should now be fixed by another [patch to ensembl-variation](https://github.com/Ensembl/ensembl-variation/commit/1cb69328ff9e28043624f99661220f63407470f7). If you re-run INSTALL.pl to pick up the patched ensembl-variation then hopefully this should fix your issue.

**Comment by christianbioinf** [comment]
Thanks a lot, it works very nicely.
