### ISSUE TITLE
sift and polyphen

### ISSUE THREAD

**Issue by shigej38** [Ensembl/ensembl-vep#572]
sift and polyphen not available 
I get an error this way :(
How can I fix.

No problem when I remove the "sift" and "polyphen" parameters

**Comment by at7** [comment]
I take a look. Could you please tell me with which parameters you are running vep? Are you using any cache files and if yes which ones? What does the error message say?

Thank you,
Anja

**Comment by shigej38** [comment]
my using command:
`$VEP/vep --fork 1 --force_overwrite --coding_only -i $IN/$BASE.vcf -o $OUT/$BASE/$BASE.csv --cache --offline --assembly GRCh37 --tab --check_existing --biotype --canonical --domains --uniprot --ccds --symbol --protein --hgvs --no_escape --numbers --show_ref_allele --allele_number --individual all --regulatory --humdiv --polyphen p --sift p --variant_class --plugin dbNSFP,$VEPDATA/dbNSFP3.5/dbNSFP3.5.gz,ALL --plugin Condel,$CACHE/Plugins/config/Condel/config/condel_SP.conf,p --fasta $VEPDATA/fasta/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa  --fields $SIRA --plugin Mastermind,$VEPDATA/mastermind/mastermind_cited_variants_reference-2019.06.14-grch37.vcf.gz --plugin G2P,file='$VEPDATA/G2P/DDG2P_10_7_2019.csv'`

my error text:
`WARNING: Failed to instantiate plugin G2P: ERROR: No file specified or could not read from file $VEPDATA/G2P/DDG2P_10_7_2019.csv


-------------------- EXCEPTION --------------------
MSG: ERROR: SIFT not available

STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::check_sift_polyphen /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:168
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::new /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:121
STACK Bio::EnsEMBL::VEP::CacheDir::get_all_AnnotationSources /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:150
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:121
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/vep:223
Date (localtime)    = Wed Aug 21 15:26:30 2019
Ensembl API version = 97
---------------------------------------------------
WARNING: Failed to instantiate plugin G2P: ERROR: No file specified or could not read from file $VEPDATA/G2P/DDG2P_10_7_2019.csv


-------------------- EXCEPTION --------------------
MSG: ERROR: SIFT not available

STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::check_sift_polyphen /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:168
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::new /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:121
STACK Bio::EnsEMBL::VEP::CacheDir::get_all_AnnotationSources /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:150
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:121
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/vep:223
Date (localtime)    = Wed Aug 21 15:26:31 2019
Ensembl API version = 97
---------------------------------------------------
WARNING: Failed to instantiate plugin G2P: ERROR: No file specified or could not read from file $VEPDATA/G2P/DDG2P_10_7_2019.csv


-------------------- EXCEPTION --------------------
MSG: ERROR: SIFT not available

STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::check_sift_polyphen /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:168
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::new /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:121
STACK Bio::EnsEMBL::VEP::CacheDir::get_all_AnnotationSources /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:150
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:121
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/vep:223
Date (localtime)    = Wed Aug 21 15:26:31 2019
Ensembl API version = 97
---------------------------------------------------
WARNING: Failed to instantiate plugin G2P: ERROR: No file specified or could not read from file $VEPDATA/G2P/DDG2P_10_7_2019.csv


-------------------- EXCEPTION --------------------
MSG: ERROR: SIFT not available

STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::check_sift_polyphen /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:168
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::new /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:121
STACK Bio::EnsEMBL::VEP::CacheDir::get_all_AnnotationSources /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:150
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:121
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/vep:223
Date (localtime)    = Wed Aug 21 15:26:31 2019
Ensembl API version = 97
---------------------------------------------------
WARNING: Failed to instantiate plugin G2P: ERROR: No file specified or could not read from file $VEPDATA/G2P/DDG2P_10_7_2019.csv


-------------------- EXCEPTION --------------------
MSG: ERROR: SIFT not available

STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::check_sift_polyphen /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:168
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::new /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:121
STACK Bio::EnsEMBL::VEP::CacheDir::get_all_AnnotationSources /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:150
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:121
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/vep:223
Date (localtime)    = Wed Aug 21 15:26:31 2019
Ensembl API version = 97
---------------------------------------------------
WARNING: Failed to instantiate plugin G2P: ERROR: No file specified or could not read from file $VEPDATA/G2P/DDG2P_10_7_2019.csv


-------------------- EXCEPTION --------------------
MSG: ERROR: SIFT not available

STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::check_sift_polyphen /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:168
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::new /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:121
STACK Bio::EnsEMBL::VEP::CacheDir::get_all_AnnotationSources /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:150
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:121
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /home/tarik/Desktop/programlar/ensembl-vep/ensembl-vep97/ensembl-vep/vep:223
Date (localtime)    = Wed Aug 21 15:26:32 2019
Ensembl API version = 97
------------------------------`

**Comment by at7** [comment]
To get rid of the warning _Failed to instantiate plugin G2P_ you need to replace the single quotes with double quotes: --plugin G2P,file="$VEPDATA/G2P/DDG2P_10_7_2019.csv" Otherwise perl treats $VEPDATA as a string and not a variable. 

For the more concerning error message _MSG: ERROR: SIFT not available_ can you please check the info.txt file in your cache directory: $ENV{HOME}/.vep/homo_sapiens/97_GRCh37/info.txt. Is $ENV{HOME}/.vep/ your cache directory? VEP reads the content of that file in order to know which annotations can be added and the file should contain a line: _sift  b_

Thank you,
Anja

**Comment by shigej38** [comment]
this problem has improved, but now I have a bigger problem "G2P" creates log files next to my input files. How do I cancel making these log files?

**Comment by at7** [comment]
For now there is no option to delete the log directory after a VEP run. But it is a good point and I will update the G2P plugin for the next release accordingly. In the meantime you need to delete the directory yourself. Thank you.

**Comment by shigej38** [comment]
Thank you for your interest. good work
