### ISSUE TITLE
--overlaps: additional explanation needed

### ISSUE THREAD

**Issue by thedam** [Ensembl/ensembl-vep#575]
hey,
what exactly does the option:
`--overlaps   `
`Report the proportion and length of a transcript overlapped by a structural variant in VCF format.`
? 
What "structural variant" it refers to? To some SV in my input VCF file? Or it is some information from internal VEP cache data?

The option `--overlaps` gives different output than the plugin output?:
`./vep -i structvariants.vcf --plugin StructuralVariantOverlap,file=gnomad_v2_sv.sites.vcf.gz`)

**Comment by sarahhunt** [comment]
Hi @thedam, 

--overlaps is an option used when your input is a SV. For longer variants, it's often interesting to know what proportion of a transcript or regulatory feature is covered in addition to the consequence.

The StructuralVariantOverlap plugin is different - this allows you to refine how your input SVs are compared to reference SVs (such as the gnomAD SV population frequency data) by specifying % overlap required etc . Eventually, we will roll this functionality into the VEP custom data file handling, but while it's new and potentially changing it is a separate plugin.

**Comment by thedam** [comment]
mhm, so for --overlaps I should not use the VCF from "normal SNV and small indels" pipeline. Ok, now it's more clear:)
