### ISSUE TITLE
gnomAD_AF value (vep 97)

### ISSUE THREAD

**Issue by ZhangXiujuan** [Ensembl/ensembl-vep#576]
Hi,
my command line is:
```
vep -i file.vcf -o file.ann.vcf --force --no_stats --cache --dir vep_cache --offline --fasta Homo_sapiens_assembly38.fasta --refseq --use_given_ref --vcf --assembly GRCh38 --allele_number --numbers --no_escape --af --max_af --af_1kg --af_gnomad --failed 1 
```
In the annotate result, the gnomAD_AF has two values `(e.g. 8.07859e-01&0.8079)` . 
Does it correspond to the number of alt Allele? But the variant only one allele `(chr1  827209 
 rs71507461  G  C)`.

Looking forward to your reply,
Thank you.

**Comment by at7** [comment]
Dear @ZhangXiujuan,
I'm not able to reproduce the error. When I run your command line with VEP release/97 for the variant which you have specified I only get 0.8079 for gnomAD_AF. Are you using the release/97 code? Could you please only run your command for chr1 827209 rs71507461 G C and send me the full output line and header of your output vcf file?
Thank you,
Anja

**Comment by ZhangXiujuan** [comment]
Dear @at7 ,

Thanks for your suggestion. 
Maybe I found the reason.
When I remove `--custom $gnomAD2.1.1` , it will be normal. 
But I don't know why, and I need to add this command.


There is another question :
 I installed `kent source tree` and `Bio::DB::BigFile` for `LoF.pm` ,but when I run vep command I got the following error:
```
Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 845.
Smartmatch is experimental at vep_cache/Plugins/de_novo_donor.pl line 214.
Smartmatch is experimental at vep_cache/Plugins/splice_site_scan.pl line 191.
Smartmatch is experimental at Plugins/splice_site_scan.pl line 194.
Smartmatch is experimental at Plugins/splice_site_scan.pl line 238.
Smartmatch is experimental at vep_cache/Plugins/splice_site_scan.pl line 241.
```
LoF command:
```
--plugin LoF,loftee_path:vep_cache/Plugins/,gerp_bigwig:vep_cache/loftee_file/gerp_conservation_scores.homo_sapiens.GRCh38.bw,conservation_file:vep_cache/loftee_file/loftee.sql,human_ancestor_fa:vep_cache/loftee_file/human_ancestor.fa.gz
```
I have moved all loftee files into `Plugins/`.

Can you help me solve these problems？
Thank you.

**Comment by at7** [comment]
Dear @ZhangXiujuan,
could you please send me your full command line for using VEP with the custom annotation option? We are not looking after the LoF plugin and I recommend that you ask any questions related to the LoF plugin here https://github.com/konradjk/loftee/issues.
Thank you,
Anja

**Comment by ZhangXiujuan** [comment]
here is my command line:
```
~/miniconda3/bin/vep -i toTESTgnomad.vcf -o toTESTgnomad.ann.refseq.vcf --force --no_stats \
--cache --dir vep_cache --offline --fasta Homo_sapiens_assembly38.fasta \
--refseq --use_given_ref --exclude_predicted --vcf --assembly GRCh38 \
--variant_class --sift b --polyphen b --allele_number --total_length --numbers --no_escape \
--hgvs --protein --symbol --canonical --biotype \
--check_existing --af --max_af --af_1kg --af_esp --af_gnomad --pubmed --failed 1 \
--flag_pick_allele \
--custom clinvar_20190708_add.vcf.gz,ClinVar,vcf,exact,0,CLNSIG, \
--custom gnomad.exomes.r2.1.1.sites.liftover_grch38.vcf.gz,gnomAD,vcf,exact,0,AF,AF_eas,AF_oth,AF_popmax,popmax \
--plugin dbscSNV,dbscSNV1.1_GRCh38.txt.gz \
--plugin CADD,whole_genome_SNVs.tsv.gz,InDels.tsv.gz \
--plugin dbNSFP,dbNSFP4.0a.gz,dbNSFP_replacement_logic,VEST4_score,Interpro_domain \
--plugin ExAC,ExAC.0.3.GRCh38.vcf.gz,AC \
--plugin ExACpLI,ExACpLI_values.txt \
--plugin LoFtool,LoFtool_scores.txt \
--fork 16
```

**Comment by at7** [comment]
The second option in your list of parameters for the custom annotation flag is the name of the custom annotation origin which will appear as the key in the key=value pairs in the results file. This way you create the same name _gnomAD_AF_ twice: once from the VEP cache annotation with --af_gnomad and once from the gnomad custom annotation. VEP then combines both values separated by & in the output. I suggest that you make the name for the custom annotation unique. You could for example use: --custom gnomad.exomes.r2.1.1.sites.liftover_grch38.vcf.gz,**gnomAD_custom**,vcf,exact,0,AF,AF_eas,AF_oth,AF_popmax,popmax \

**Comment by ZhangXiujuan** [comment]
thank you very much.

**Comment by at7** [comment]
No problem. Please reopen this issue if you have any more related questions.
Best regards,
Anja
