### ISSUE TITLE
Ensembl Vep release 97 install  test error

### ISSUE THREAD

**Issue by shigej38** [Ensembl/ensembl-vep#578]
Hello
ensembl vep version 97 I try to install `perl INSTALL.pl` If I use the command I get an error like this.
ERROR is:
`Testing VEP installation
./t/AnnotationSource_File_BED.t ...................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSource_File_BED.t ...................... ok    
./t/BaseVEP.t ........................................ Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/BaseVEP.t ........................................ ok    
./t/Parser_VCF.t ..................................... "my" variable $cnv_vf masks earlier declaration in same scope at ./t/Parser_VCF.t line 570.
Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/Parser_VCF.t ..................................... 1/? WARNING: variant sv_dup on line 1 is too long to annotate: (10000)
WARNING: variant sv_dup on line 1 is too long to annotate: (10000)
./t/Parser_VCF.t ..................................... ok    
./t/Parser_ID.t ...................................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/Parser_ID.t ...................................... ok   
./t/OutputFactory_Tab.t .............................. Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/OutputFactory_Tab.t .............................. ok    
./t/AnnotationSourceAdaptor.t ........................ Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSourceAdaptor.t ........................ ok    
./t/Runner.t ......................................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/Runner.t ......................................... All 73 subtests passed 
./t/AnnotationSource_File_VCF.t ...................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSource_File_VCF.t ...................... ok    
./t/AnnotationSource_Cache_RegFeat.t ................. Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSource_Cache_RegFeat.t ................. ok    
./t/Parser_Region.t .................................. Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/Parser_Region.t .................................. ok    
./t/AnnotationSource_File_GFF.t ...................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSource_File_GFF.t ...................... ok    
./t/Parser_VEP_input.t ............................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/Parser_VEP_input.t ............................... ok    
./t/AnnotationSource_Database_Variation.t ............ Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSource_Database_Variation.t ............ ok    
./t/bam_edit.t ....................................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/bam_edit.t ....................................... All 14 subtests passed 
./t/Parser_SPDI.t .................................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/Parser_SPDI.t .................................... ok   
./t/AnnotationSource_Cache_Transcript.t .............. Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSource_Cache_Transcript.t .............. ok    
./t/Parser.t ......................................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/Parser.t ......................................... ok     
./t/InputBuffer.t .................................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/InputBuffer.t .................................... ok    
./t/TranscriptTree.t ................................. Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/TranscriptTree.t ................................. ok    
./t/AnnotationSource_Cache_VariationTabix.t .......... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSource_Cache_VariationTabix.t .......... ok    
./t/Config.t ......................................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/Config.t ......................................... ok    
./t/VariantRecoder.t ................................. Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/VariantRecoder.t ................................. ok    
./t/AnnotationSource_File_GTF.t ...................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSource_File_GTF.t ...................... ok    
./t/Utils.t .......................................... ok    
./t/AnnotationSource.t ............................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSource.t ............................... ok    
./t/FilterSet.t ...................................... ok     
./t/AnnotationSource_Database_Transcript.t ........... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSource_Database_Transcript.t ........... ok    
./t/AnnotationSource_Cache_Variation.t ............... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSource_Cache_Variation.t ............... ok    
./t/Parser_HGVS.t .................................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/Parser_HGVS.t .................................... ok    
./t/CacheDir.t ....................................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/CacheDir.t ....................................... ok    
./t/version.t ........................................ ok   
./t/OutputFactory_JSON.t ............................. Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/OutputFactory_JSON.t ............................. ok    
./t/OutputFactory.t .................................. Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/OutputFactory.t .................................. ok     
./t/Stats.t .......................................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/Stats.t .......................................... ok    
./t/OutputFactory_VEP_output.t ....................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/OutputFactory_VEP_output.t ....................... ok    
./t/AnnotationSource_Database_RegFeat.t .............. Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSource_Database_RegFeat.t .............. ok    
./t/AnnotationSource_File.t .......................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSource_File.t .......................... ok    
./t/AnnotationSource_Cache.t ......................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSource_Cache.t ......................... ok   
./t/OutputFactory_VCF.t .............................. Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/OutputFactory_VCF.t .............................. ok    
./t/AnnotationSource_File_BigWig.t ................... Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSource_File_BigWig.t ................... ok    
./t/AnnotationSource_Database_StructuralVariation.t .. Possible precedence issue with control flow operator at /home/tarik/perl5/lib/perl5/Bio/DB/IndexedBase.pm line 845.
./t/AnnotationSource_Database_StructuralVariation.t .. ok    

Test Summary Report
-------------------
./t/Runner.t                                       (Wstat: 139 Tests: 73 Failed: 0)
  Non-zero wait status: 139
  Parse errors: No plan found in TAP output
./t/bam_edit.t                                     (Wstat: 139 Tests: 14 Failed: 0)
  Non-zero wait status: 139
  Parse errors: No plan found in TAP output
Files=41, Tests=1667, 88 wallclock secs ( 0.16 usr  0.09 sys + 84.76 cusr  2.02 csys = 87.03 CPU)
Result: FAIL
Failed 2/41 test programs. 0/1667 subtests failed.
`

however, if I use the `perl INSTALL.pl --NO_TEST` command, the program is installed.

what is the reason for this test error? what's wrong?

**Comment by thedam** [comment]
better use docker. Really ;)

**Comment by dglemos** [comment]
Hi @shigej38,

That seems to be a warning message related to BioPerl and not an error. You should check how many versions of BioPerl you have installed and make sure to have only one. 

Best regards,
Diana

**Comment by shigej38** [comment]
How do I check the bioperl versions installed on my system?

**Comment by dglemos** [comment]
You can check the version installed: 
`perl -MBio::Root::Version -e 'print $Bio::Root::Version::VERSION'`

Also, check `echo $PERL5LIB`

**Comment by dglemos** [comment]
I'm closing this issue but you can reopen it if you have more questions.

Best regards,
Diana
