### ISSUE TITLE
splicesite annotations

### ISSUE THREAD

**Issue by matthdsm** [Ensembl/ensembl-vep#58]
Hi Will,

As you know, there's been quite some work done to integrate full VEP functionality into bcbio. Lately, I've been running into quite some issue with splicesite annotations. I believe the greatest offenders are Genesplicer and MaxEntScan. Both these plugins rely on fairly ancient binaries, which are hugely inefficient.
With both plugins active, I keep getting forks killed off or going out of memory. Runtime for an exome goes from +- 6min to 2h+.

I believe the main cause of these issues (apart from runtime) is MaxEntScan. 
This plugin requires the `--fasta` flag to be set explicitly. When using a plain fasta file, it seems to work ok most of the time, but when using a compressed fasta, the memory requirements go through the roof, hence the process failure.

Do you have any idea what could be done to fix this? We're looking to use VEP results in diagnostics, and good splicesite annotations are essential. Do you know of any (more modern) alternatives?

Thanks for the help
Matthias

ping @chapmanb, so you know what's going on

**Comment by willmclaren** [comment]
In terms of runtime, there may not be any easy wins. As you say, both are old (GeneSplicer is a compiled binary, MaxEntScan a set of perl routines), and VEP does what it can in terms of caching to prevent the same sequence being analysed more than once. I can take a look at profiling them in more detail when I get some time.

Regarding memory, I can't seem to recreate this - can you provide an input file and command that I can use to test? I'm using a variety of input file types, and the memory usage is roughly stable, with and without forks, using a compressed FASTA file.

**Comment by willmclaren** [comment]
Having said there may be no easy wins, I've found an easy win to speed up MaxEntScan :-)

I've pushed a [commit](https://github.com/Ensembl/VEP_plugins/commit/3d17e9712c73f9c1215333285364ba03982ee340) to the release/89 branch.

**Comment by matthdsm** [comment]
Hi Will, 

Thanks for the fix! I'll run some tests as soon as we've got some leftover space on our cluster.
I'll keep you posted!

Cheers
M

**Comment by matthdsm** [comment]
Hi Will,

quick update, the edit's to the MaxEntScan plugin seem to have done wonders for the performance. Our only issue left now is GeneSplicer, but I fear that's going to be a lost cause.
Thanks for all the help!
M

**Comment by willmclaren** [comment]
GeneSplicer gets run on *every* variant, regardless of whether the variant falls in/near an existing splice site. The idea is that it can pick up splice signal gain. Obviously this is most of the reason why it is running slowly, and profiling it indeed shows this to be the case.

It might be an idea to at least have an option to disable this and only run it when the variant falls in the canonical splice region sites.

**Comment by matthdsm** [comment]
Hi Will, 

Thanks for the extra explanation. For me, runtime is no issue actually. It's perfectly this takes a while. The main issue for me is that when we use GeneSplicer, memory usage flies through the roof and I keep getting the message that several forks died. Is there some kind of timeout param for the forks that could be raised?

M

**Comment by willmclaren** [comment]
OK, thanks, I will take a look.

What kind of input data are you using - exome/genome/variant ID?

**Comment by matthdsm** [comment]
We're using VEP on WES data, vcf files as produced by bcbio.
If you're interested, here you have a sample vcf for GiaB.
I'll have to note, sometimes everything works just fine, so it's a bit hit and miss :-(

[GiaB.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/1108129/GiaB.vcf.gz)
