### ISSUE TITLE
Gene Symbols Missing in Results

### ISSUE THREAD

**Issue by DarioS** [Ensembl/ensembl-vep#582]
I am using the online interface for GRCh37 and I selected the most severe variant in the filtering section. The result table I get has impact of missense_variant but symbol is a dash. Why is symbol missing? My input in the text box was

```
NM_001285439.1(RICTOR):c.5156C>T
NM_002944.2(ROS1):c.500G>A
NM_020975.4(RET):c.2944C>T
```

"Show one selected consequence per variant" restores the gene symbols.

Also, it would be nice if the TXT download only saved the columns which are visible after changing Show/hide columns.

**Comment by dglemos** [comment]
Hi @DarioS,

About the most severe variant option, we are aware that the current output doesn't provide much data. At the moment, running vep with that option only outputs the consequence, the other fields are empty. It's something we plan to look at in the future. 
Using "Show one selected consequence per variant" outputs more data but in this case the criteria to chose the transcript is different than what you want. 

An alternative would be to use bcftools plugin [split-vep](https://samtools.github.io/bcftools/howtos/plugin.split-vep.html). There's an option to filter a vep annotated file by most severe consequence. VEP option `most severe consequence` and bcftools split-vep `worst` have a high concordance in the results. 

Also, thank you for the suggestion about the output columns. 

Best regards,
Diana

**Comment by dglemos** [comment]
I'm closing this issue, feel free to reopen if you have more questions.

Best regards,
Diana

**Comment by dglemos** [comment]
I'm closing this issue, feel free to reopen if you have more questions.

Best regards,
Diana
