### ISSUE TITLE
dyld error

### ISSUE THREAD

**Issue by jonathonthill** [Ensembl/ensembl-vep#586]
I have installed vep and am trying to run it from the ensembl-vep bioconductor package. When loading the library, I am getting the following warning:

> Warning message:
> In system2("perl", .getVepPath(), stdout = TRUE, stderr = TRUE) :
>   running command ''perl' /usr/local/bin/vep 2>&1' had status 134
> 

When I run the system command directly on the console, I get:

> \> system("perl /usr/local/bin/vep 2>&1")
> dyld: lazy symbol binding failed: Symbol not found: _Perl_xs_handshake
>   Referenced from: /Users/jthill/Code/ensembl-vep/Faidx.bundle
>   Expected in: flat namespace
> 
> dyld: Symbol not found: _Perl_xs_handshake
>   Referenced from: /Users/jthill/Code/ensembl-vep/Faidx.bundle
>   Expected in: flat namespace
> 
> sh: line 1:  8906 Abort trap: 6           perl /usr/local/bin/vep 2>&1
> 

On the other hand, when I run the same command on the command line it works fine. It appears that some environment variable is not being accessed by R, so it cannot find key components.

**Comment by aparton** [comment]
Hi Jonathon,

I’m not an R expert I’m afraid, but hopefully I can point you in the right direction here. 

I assume you’re running VEP on MacOS - have you followed all of the MacOS installation instructions found here? https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#macos <https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#macos>

Additionally, the installer requires /Users/jthill/Code/ensembl-vep/htslib to be added to your DYLD_LIBRARY_PATH environment variable - it may be possible that R is unaware of this.

If you have any more questions, or if your installation is more complex than I’ve assumed, please let us know and we can take another look.

Kind Regards,
Andrew
