### ISSUE TITLE
--merged option is missing intergenic_variants from ensembl

### ISSUE THREAD

**Issue by wxnc-jerome** [Ensembl/ensembl-vep#589]
Hi,

I expected running vep with the --merged option to give me the same result as combining the results an ensembl-only run and a refseq-only run (--refseq). But for positions where ensembl returns an intergenic_variant and refseq something else, the ensembl annotation does not appear in the "--merged" run

e.g. with input
```
# input.vcf
chr1    84006   chr1:84006:G:A  G       A
```

an ensembl-only run returns
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr1	84006	chr1:84006:G:A	G	A	.	.	CSQ=A|intergenic_variant|MODIFIER||||||||||||||||1||||1||
```
i.e. consequence='intergenic_variant'

a refseq-only run returns
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr1	84006	chr1:84006:G:A	G	A	.	.	CSQ=A|downstream_gene_variant|MODIFIER|LOC100996442|100996442|Transcript|XR_001737578.2|misc_RNA|||||||||||1|5000|-1||1|EntrezGene||,A|downstream_gene_variant|MODIFIER|LOC100996442|100996442|Transcript|XR_001737580.2|misc_RNA|||||||||||1|5000|-1||1|EntrezGene||,A|downstream_gene_variant|MODIFIER|LOC100996442|100996442|Transcript|XR_001737581.2|misc_RNA|||||||||||1|5000|-1||1|EntrezGene||,A|downstream_gene_variant|MODIFIER|LOC100996442|100996442|Transcript|XR_001737582.2|misc_RNA|||||||||||1|5000|-1||1|EntrezGene||,A|downstream_gene_variant|MODIFIER|LOC100996442|100996442|Transcript|XR_001737583.2|misc_RNA|||||||||||1|5000|-1||1|EntrezGene||,A|downstream_gene_variant|MODIFIER|LOC100996442|100996442|Transcript|XR_001737584.2|misc_RNA|||||||||||1|5000|-1||1|EntrezGene||
```
i.e. consequence='downstream_gene_variant' for 6 different transcripts

a --merged run returns
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr1	84006	chr1:84006:G:A	G	A	.	.	CSQ=A|downstream_gene_variant|MODIFIER|LOC100996442|100996442|Transcript|XR_001737578.2|misc_RNA|||||||||||1|5000|-1||1|EntrezGene|||RefSeq|G|G|,A|downstream_gene_variant|MODIFIER|LOC100996442|100996442|Transcript|XR_001737580.2|misc_RNA|||||||||||1|5000|-1||1|EntrezGene|||RefSeq|G|G|,A|downstream_gene_variant|MODIFIER|LOC100996442|100996442|Transcript|XR_001737581.2|misc_RNA|||||||||||1|5000|-1||1|EntrezGene|||RefSeq|G|G|,A|downstream_gene_variant|MODIFIER|LOC100996442|100996442|Transcript|XR_001737582.2|misc_RNA|||||||||||1|5000|-1||1|EntrezGene|||RefSeq|G|G|,A|downstream_gene_variant|MODIFIER|LOC100996442|100996442|Transcript|XR_001737583.2|misc_RNA|||||||||||1|5000|-1||1|EntrezGene|||RefSeq|G|G|,A|downstream_gene_variant|MODIFIER|LOC100996442|100996442|Transcript|XR_001737584.2|misc_RNA|||||||||||1|5000|-1||1|EntrezGene|||RefSeq|G|G|
```
i.e. same result as refseq alone (+ source column) and no mention of the intergenic_variant from ensembl.

Is that behavior documented somewhere, or is this a bug?

Options used: "--species homo_sapiens --assembly GRCh38 --vcf --minimal --force_overwrite --no_stats --database --input_file X --output_file Y"

Tested with vep95 and vep97, in offline and in database mode

**Comment by aparton** [comment]
Hi, 

Thank you for your query. VEP uses intergenic_variant as the default consequence term when no overlapping features of interest are found. The merged cache annotates variants across all overlapping regions of interest (whether RefSeq or Ensembl), and as none were found in the ensembl dataset then it only looks at the refseq ones.

If you have any more questions, please don’t hesitate to ask.

Kind Regards,
Andrew
