### ISSUE TITLE
--clin_sig_allele output

### ISSUE THREAD

**Issue by thedam** [Ensembl/ensembl-vep#593]
hey, VEP97, I've used option: `--clin_sig_allele` and I've got, among others, the outputs:
```
variant xx: benign,likely_benign
variant yy: uncertain_significance,benign
```
shouldn't this option return only one clinical significance per variant?
Based on the option description, I've expected something like this:
```
variant xx: benign
variant yy: uncertain_significance
```

**Comment by aparton** [comment]
Hi,

—clin_sig_allele will provide clinical significance annotations that are allele specific, not just locus specific. If we have multiple sources giving multiple clinical significance values, VEP will return them all.

However, if you still feel as if these values are incorrect, if you send me a particular variant then I can take a closer look.

Kind Regards,
Andrew

**Comment by thedam** [comment]
mhm, so I didn't understand how it works (an maybe still I don't).
locus: 7_150655537
allel: 7_150655537_G_A

command:
```
docker run --rm -t -i \
-v /mnt/ssd_01/VEP/vepCache:/opt/vep/.vep \
-v $PWD:$PWD \
-v /mnt/ssd_01/refs:/home/vep/refs \
ensemblorg/ensembl-vep:97 vep \
--format "vcf" \
-i $inFileFull \
-o $outVepFile \
--no_stats \
--cache \
--fasta /home/vep/refs/hs37d5_noHap.fa --port 3337 --ASSEMBLY GRCh37 \
--merged --tab \
--use_transcript_ref \
--pubmed --force_overwrite \
--exclude_predicted \
--clin_sig_allele \
--verbose
```

no matter if I put `clin_sig_allele` or not, I get exactly the same output under `CLIN_SIG` column.
I thought, that with` --clin_sig_allele` I'll get only one significance, not a comma separated list (risk_factor,likely_benign,uncertain_significance).

I thought that with --clin_sig_allel I'll get for example only one description:
`risk_factor`
and without --clin_sig_allel I'll get all of them:
`risk_factor,likely_benign,uncertain_significance`


ps. if I remove `--pubmed`, I don't get any `CLIN_SIG` annotations...

**Comment by aparton** [comment]
Hi,

—clin_sig_allele will filter out clinical significance values that have difference associated alleles to the input allele. This is just one of those situations where we have 3 different clinical significance values for one associated allele, see: 

http://grch37.ensembl.org/Homo_sapiens/Variation/Phenotype?db=core;r=7:150655037-150656037;v=rs36210422;vdb=variation;vf=38953497 <http://grch37.ensembl.org/Homo_sapiens/Variation/Phenotype?db=core;r=7:150655037-150656037;v=rs36210422;vdb=variation;vf=38953497> 

So in your case, none are filtered as all 3 clin_sig annotations are associated with the input allele. For an example of where clin_sig_allele will reduce the number of clinical significance values returned, see rs2228671 - http://grch37.ensembl.org/Homo_sapiens/Variation/Phenotype?v=rs2228671 <http://grch37.ensembl.org/Homo_sapiens/Variation/Phenotype?v=rs2228671>

Additionally, you can switch CLIN_SIG annotations on with —check_existing. —pubmed switches on —check_existing by default, which subsequently leads to clinical significance values being shown.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now, if you have any more questions, please feel free to reopen it.

Kind Regards,
Andrew
