### ISSUE TITLE
how to using ensembl-vep for bacteria

### ISSUE THREAD

**Issue by shigej38** [Ensembl/ensembl-vep#594]
Can I use ensembl-vep for Klebsiella Pneumoniae?

**Comment by aparton** [comment]
Hi,

Yes, you can! The most important thing if for you to identify which strain and genome you’re working with, as this must match with VEP, as we have approximately 90,000 non-vertebrate genomes that you can access here:  ftp://ftp.ensemblgenomes.org/pub/current/bacteria/vep

If you know the GCA for your genome, you can find it by searching on https://bacteria.ensembl.org

To access annotations via our databases, you need to add the —genomes flag and the —is_multispecies 1 flag.

You can find relevant cache files here: ftp://ftp.ensemblgenomes.org/pub/current/bacteria/vep

Documentation on how to do this can be found here: https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#basic <https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#basic>

Kind Regards,
Andrew

**Comment by shigej38** [comment]
how can I decide which reference genome to use. "https://bacteria.ensembl.org/index.html" is looking for hundreds of results here.

**Comment by aparton** [comment]
Hi,

That depends on the input data you’re using, and the strain used in your underlying experiment. You can find more information on the specific assemblies used and their taxonomy IDs here: http://ensemblgenomes.org/info/genomes?name=Klebsiella+Pneumoniae&division=All&pan_compara=All&variation=All&field_peptide_alignments_value=All&field_genome_alignments_value=All&field_other_alignments_value=All <http://ensemblgenomes.org/info/genomes?name=Klebsiella+Pneumoniae&division=All&pan_compara=All&variation=All&field_peptide_alignments_value=All&field_genome_alignments_value=All&field_other_alignments_value=All>

Kind Regards,
Andrew

**Comment by shigej38** [comment]
thanks, I can disturb you again after getting the necessary information.
