### ISSUE TITLE
how to using OMIM datasheet with ensembl-vep annotation

### ISSUE THREAD

**Issue by shigej38** [Ensembl/ensembl-vep#598]
Hi, I have a number of genetic data created by "omım". this data is stored in "txt" format.
The column headings of the data are as follows:
`
Chromosome "\t" Genomic Position Start "\t" Genomic Position End "\t" Cyto Location "\t" Computed Cyto Location "\t" Mim Number "\t" Gene Symbols "\t" Gene Name "\t" Approved Symbol "\t" Entrez Gene ID "\t" Ensembl Gene ID "\t" Comments "\t" Phenotypes "\t" Mouse Gene Symbol / ID
`

how can I use this data when annotation with ensembl-vep.

**Comment by ima23** [comment]
Hi @shigej38 ,

external data can be added using the `custom` flag. First you would need to make sure your file has been tabix indexed on the `Chromosome`, `Genomic Postion Start` and `Genomic Position End` columns.  Detailed information how to use custom annotation can be found here   https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html

Kind regards,
Irina

**Comment by shigej38** [comment]
Hello @ima23 
Does ensembl-vep custom flag accept txt format?

**Comment by ima23** [comment]
Hi @shigej38,

yes, the custom flag can work with tab delimited text files, please see BED example on the custom flag documentation [page](https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html) and the previous thread reply to your ticket **How to add data**  https://github.com/Ensembl/ensembl-vep/issues/549.

Kind regards,
Irina

**Comment by shigej38** [comment]
do I need to use --custom path / to / data.bed to convert the data source to bed format?
Or --custom /path/to/data.bed,fields,name

**Comment by ima23** [comment]
Hi @shigej38,

no, the `custom` flag will not convert your data into bed format.

Kind regrads,
Irina

**Comment by shigej38** [comment]
no I don't want to get a bed file using the custom flag.
the question I ask is how do I use the vep command line after I get the bed file.
for example:
"--custom /path/to/custom_files/clinvar_20190319.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNREVSTAT,CLNDN"

do I need to use the "Clinvar", "vcf", "exact", "0", "CLNSIG", "CLNREVSTAT", "CLNDN" parameters given in this command, or directly --custom /path/to/my-bed.bed Is it enough to use?

**Comment by ima23** [comment]
Hi @shigej38 ,

you do not need to use "Clinvar" ... and the other ClinVar specific parameters.

Yes, for your custom BED file you can run directly `--custom /path/to/my-bed.bed` in which case all the other options will be set to the default values (see documentation [options](https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html#custom_optionsl) section). 

Kind regards,
Irina

**Comment by shigej38** [comment]
How do I convert txt data to bed format? I couldn't understand anything from the documentation. can you help me with this ?.

first 25 lines of my file:

[head.txt](https://github.com/Ensembl/ensembl-vep/files/3604042/head.txt)

**Comment by shigej38** [comment]
thank you @ima23
