### ISSUE TITLE
Change option `--max_sv_size` behaviour

### ISSUE THREAD

**Issue by fgvieira** [Ensembl/ensembl-vep#600]
Dear all,

as it is now, option `--max_sv_size` excludes SVs greater than the value specified. I understand the idea behind it, but would it be possible for VEP to just skip the annotation of these SVs but still output them? I feel removing SVs is a filtering step and the user can easily remove them with `filter_vep` if needed.

thanks,

**Comment by leowill01** [comment]
Has there been any update to this? Is the current workaround to retain all possible SVs to just set the max size to a very large number (e.g. the size of the genome)?

**Comment by diegomscoelho** [comment]
Hi @leowill01,

Sorry for this late response. If you want to maintain all variants you can increase max_sv_size number, but you might fall into a memory issue problem as described here (https://github.com/Ensembl/ensembl-vep/pull/463).

 We are currently implementing some new SV features in VEP, if I have any news about this `enhancement`, I will post it here.

Regards, @diegomscoelho

**Comment by diegomscoelho** [comment]
Hi @fgvieira,

Your feature request was implemented to `max_sv_size` option. Lines will no longer be removed, just not annotated. This alteration will be available on release 109. I will close this issue now, any question related to this issue, feel free to comment here.

Regards, @diegomscoelho
