### ISSUE TITLE
different  SIFT and CADD_PHRED values for the same variant depending on several factors

### ISSUE THREAD

**Issue by QANGFQ** [Ensembl/ensembl-vep#602]
Hi, 

I found that SIFT values ​​are different for the same variant depending on output format(tab or vcf), --fields option and whether web version or command line version. 
The same is true for CADD_PHRED.

The command part of fields option was _--fields "SIFT, CADD_PHRED"_ and genome assembly version is GRCh37 and VEP command line version is 97.3.

Using rs199789235 as an example, the results are as follows.

 **tab & web version :** SIFT=-, CADD_PHRED=24.1
 **tab & command line version :** SIFT=0, CADD_PHRED=-
 **tab & command line version & fields option :** SIFT=0, CADD_PHRED=-
 **vcf & command line version & fields option :** SIFT=NULL, CADD_PHRED=NULL

I think that 'SIFT=0, CADD_PHRED=24.1' notation is correct. 
Is this right?
Why are the values different, despite the same variant?

Best regards,
QANGFQ

**Comment by helensch** [comment]
Hi

SIFT predicts whether an amino acid substitution is likely to affect protein function.
https://www.ensembl.org/info/genome/variation/prediction/protein_function.html#sift

VEP reports SIFT by transcript and for missense variants.

The variant rs199789235 falls in more than one transcript.                      

For example 
- for transcript ENST00000327044, the consequence is downstream_gene_variant, there is no SIFT prediction and the value reported is "-'
- for transcript ENST00000341065, the consequence is missense_variant and the SIFT prediction is deleterious(0)

For command line VEP, to get CADD_PHRED, the CADD VEP plugin is needed:
https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html
https://github.com/Ensembl/VEP_plugins/blob/release/97/CADD.pm

Helen

**Comment by QANGFQ** [comment]
Hi, 
Thanks to your explanation, the issue related with CADD has been solved!
However, SIFT issue is not yet solved.. 

Transcript for the variant which is rs199789235 : chr1_874697_C>G I mentioned earlier is ENST00000342066.
That is, SIFT scores of ENST00000342066 are "-"(tab & web version), NULL(vcf & command line) and 0(tab & command line).

Why are the values differently marked, despite the same transcript?

Best regards,
QANGFQ

**Comment by helensch** [comment]
Hi

Thank you for reporting this issue.

The SIFT score for rs199789235 on ENST00000342066 is 0.

This should be reported in the VCF output file and the VEP web inteface. 

The sift option can take three values:
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_sift
--sift b  (prediction term and score)
--sift s  (score)
--sift p  (prediction term)

The SIFT score of 0 is reported in the VCF when command line VEP is run with the 
--sift b  (both prediction  term and score).

Please could you let me know if you are using the --sift s (score) or the --sift b (prediction term and score) option?

We are looking into the issue, in the meantime as a workaround  can you  use --sift b  option with the VCF output? 

Helen

**Comment by QANGFQ** [comment]
Hi, Helen

I used --sift s (score only) in command line VEP and the output format is VCF.
Is this a bug, right?

Is there no solution yet under conditions of using the VCF as output format and --sift s option?

Best regards,
QANGFQ

**Comment by helensch** [comment]
Hi

Yes there is a bug using --sift s (score only) in command line VEP and the output format in VCF.

We are working on a fix, in the meantime as a workaround can you use --sift b option with the VCF output. I will let you know when a fix has been done.

Helen

**Comment by QANGFQ** [comment]
Hi, Helen

Thank you for your explanation.
I'll wait for your reply about this. 

Best regards,
QANGFQ

**Comment by helensch** [comment]
Hi

This issue has now been fixed and pushed to the branch release/97.

Please, could you update your VEP installation to get the fixed code?

Thank you for reporting the issue.

Helen

**Comment by QANGFQ** [comment]
Hi, Helen.

Thank you for fixing the bug.

I have a question for updating VEP.
Because I installed VEP v.97.3 via Conda, using Conda is more convenient for me. 
Will the changes be reflected now even if I update VEP v.97 via Conda?

Best regards,
QANGFQ

**Comment by ens-lgil** [comment]
Dear @QANGFQ,

Unfortunately we don't support the Bioconda package of ensembl-vep (it wasn't created by us in Ensembl).
However, a new package for VEP 97.4 has been created: https://anaconda.org/bioconda/ensembl-vep/files, so the changes should be in this new package.

Best regards,
Laurent

**Comment by QANGFQ** [comment]
Hi, Laurent.

Thank you for your advice to update VEP 97.4 via Conda, the changes could be reflected in VEP I use.
Thank you so much Helen and Laurent.

Best regards,
QANGFQ
