### ISSUE TITLE
VEP doesn't recognize HGVS inversions without nucleotides

### ISSUE THREAD

**Issue by stephan-hutter** [Ensembl/ensembl-vep#607]
Tested with scripts v94 and v97, also fails in the web interface.

VEP does not accept HGVS inversions unless you provide the inverted nucleotides. Quick example outputting HGVSc and HGVSg on GRCh37:

NM_001123385.1(BCOR):c.1260_1261inv
`Use of uninitialized value $ref_allele in concatenation (.) or string at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm line 2076, <__ANONIO__> line 2.
WARNING: Invalid allele string / on line 2 or possible parsing error`

NM_001123385.1(BCOR):c.1260_1261invTG
`ENST00000378444.4:c.1260_1261inv        X:g.39933338_39933339inv`

This is doubly curious as 1) VEP outputs HGVS nomenclature without nucleotides, and 2) the [official HGVS recommendations for inversions](https://varnomen.hgvs.org/recommendations/DNA/variant/inversion/) do not even mention the version with nucleotides, unlike for duplications where both versions are allowed.

It would be nice if VEP could support the non-nucleotide version.

**Comment by aparton** [comment]
Hi,

Thank you for your report. This is something that we’re looking to do in a future release, however this would be a significant amount of work for us so unfortunately it’s not something that will happen quickly.

However, we can improve how we communicate this and tidy up this error message, although that doesn’t help you very much.

Sorry that I couldn’t give you a more helpful response.

Kind Regards,
Andrew

**Comment by dglemos** [comment]
Hi @stephan-hutter, 

VEP version 98 supports inversions without nucleotides. If you run your example with v98 you'll get the expected output. 

Best regards,
Diana

**Comment by stephan-hutter** [comment]
Hi Diana,

that's great news! Thanks a bunch!

Cheers,
Stephan

**Comment by aparton** [comment]
Hi @stephan-hutter,

I'm going to close this issue now. If you have any more questions, please feel free to reopen it.

Kind Regards,
Andrew
