### ISSUE TITLE
Version file inconsistent with branch release/98

### ISSUE THREAD

**Issue by KallyopeBio** [Ensembl/ensembl-vep#608]
I just cloned the VEP repository to my local machine, using
`git clone https://github.com/Ensembl/ensembl-vep.git`

When I cd into the resulting ensembl-vep directory and run
`git status`
git reports:
On branch release/98
Your branch is up-to-date with 'origin/release/98'

However, when I run the install script, with
`perl INSTALL.pl`
I get the warning "Version check reports a newer release of 'ensembl-vep' is available (installed: 97, available: 98)"

Of course, if I follow the instructions to
`git pull`
`git checkout release/98`
nothing happens, because I'm already on the correct branch.

Digging deeper, I found the hidden .version folder in the repo. If I look at the contents of the ensembl file in this folder, which is what the INSTALL.pl script appears to read to identify the version of the source code, I see the following
`release 97`
`sub 378db18977278a066bd54b41e7afcf1db05d7db3`

I'd like to install the latest version of VEP. Am I doing something wrong, or is the source code in the hidden .version folder out of sync with the branch?

Thanks,
Justin

**Comment by at7** [comment]
Dear Justin,
thank you for reporting this installation problem. The reason was that we haven't updated the version for the new release which we have now corrected. Could you please checkout the vep repo again and start the installation process afresh?
Thank you,
Anja

**Comment by KallyopeBio** [comment]
Thanks for the speedy reply! Let me give it a shot and I'll report the results when I'm done.

**Comment by KallyopeBio** [comment]
After doing a git pull and re-running the INSTALL script, the script indicates that the current version is 98 (which is now correct) and offers to update the older version I was forced to install earlier (97). So it looks good now!
