### ISSUE TITLE
Cache convertion for 98 release

### ISSUE THREAD

**Issue by Stikus** [Ensembl/ensembl-vep#610]
Hello.
If I understand correctly release notes of 97 VEP release - now cache files in tabix indexed already and cache convertion step not needed anymore.
[Release notes VEP 97](https://github.com/Ensembl/ensembl-vep/releases/tag/release%2F97.0)
> tabix-indexed variant cache files are now installed by default.

Related [issue](https://github.com/Ensembl/ensembl-vep/issues/542)

But when I updated out VEP installation to 98 version (this problem was at 97 version too btw) conversion still started and too several ours both for 37 and 38 genome.

Context:
Our VEP installation command:
`perl INSTALL.pl --NO_TEST --NO_UPDATE --NO_HTSLIB --NO_BIOPERL -a ap --PLUGINSDIR "$SOFT/ensembl-vep-${VEP_VERSION}/Plugins" --PLUGINS ProteinSeqs,Downstream,Conservation,GO,G2P`

Our VEP cache install command:
`$VEPINSTALL --NO_TEST --NO_UPDATE --NO_HTSLIB --NO_BIOPERL -a cf -s homo_sapiens -y $vepCacheAssembly --CONVERT -c $VEPCACHEDIR`

If I understand perl script correctly - this [line](https://github.com/Ensembl/ensembl-vep/blob/release/98/INSTALL.pl#L1303) starts [convert_cache.pl](https://github.com/Ensembl/ensembl-vep/blob/release/98/convert_cache.pl) and this [line](https://github.com/Ensembl/ensembl-vep/blob/release/98/convert_cache.pl#L204) is check for need of convertion.
So if info.txt contains key: `var_type	tabix` - variant is skipped.

But this is our 98_GRCh37 info's before and after convertion:
Before:
```
species	homo_sapiens
assembly	GRCh37
sift	b
polyphen	b
source_polyphen	2.2.2
source_sift	sift5.2.2
source_genebuild	2011-04
source_gencode	GENCODE 19
source_assembly	GRCh37.p13
variation_cols	variation_name,failed,somatic,start,end,allele_string,strand,minor_allele,minor_allele_freq,clin_sig,phenotype_or_disease,clin_sig_allele,pubmed,AFR,AMR,EAS,EUR,SAS,AA,EA,gnomAD,gnomAD_AFR,gnomAD_AMR,gnomAD_ASJ,gnomAD_EAS,gnomAD_FIN,gnomAD_NFE,gnomAD_OTH,gnomAD_SAS
source_COSMIC	86
source_HGMD-PUBLIC	20174
source_ESP	20141103
source_ClinVar	201810
source_dbSNP	151
source_1000genomes	phase3
source_gnomAD	r2.1
regulatory	1
cell_types	A549,A549_ENCSR797CXN,A673,Aorta,B_cell_ENCSR682AXR,B_cells_(PB)_Roadmap,CD14+CD16-_monocyte_(CB),CD14+CD16-_monocyte_(VB),CD14_positive_monocyte,CD38-_naive_B_cell_(VB),CD4+_ab_T_cell_(CB),CD4+_ab_T_cell_(VB),CD4_positive_CD25_positive_alpha_beta_regulatory_T_cell,CD4_positive_alpha_beta_T_cell,CD4_positive_alpha_beta_T_cell_ENCSR948ZKZ,CD4_positive_alpha_beta_memory_T_cell,CD8+_ab_T_cell_(CB),CM_CD4+_ab_T_cell_(VB),DND-41,EM_CD8+_ab_T_cell_(VB),EPC_(VB),Fetal_Adrenal_Gland,Fetal_Intestine_Large,Fetal_Intestine_Small,Fetal_Muscle_Leg,Fetal_Muscle_Trunk,Fetal_Stomach,Fetal_Thymus,GM12878,GM12878_ENCSR447YYN,Gastric,H1-mesenchymal,H1-neuronal_progenitor,H1-trophoblast,H1ESC,H1_hESC,H1_hESC_ENCSR820QMS,H9,H9_ENCSR323FKB,HCT116,HMEC,HSMM,HSMMtube,HUES48,HUES6,HUES64,HUVEC,HUVEC_prol_(CB),HepG2,IMR90,IMR_90,K562,Karpas_422,Left_Ventricle,Lung,M0_macrophage_(CB),M0_macrophage_(VB),M1_macrophage_(CB),M1_macrophage_(VB),M2_macrophage_(CB),M2_macrophage_(VB),MCF_7,MM_1S,MSC_(VB),Monocytes-CD14+,Monocytes-CD14+_(PB)_Roadmap,NH-A,NHDF-AD,NHEK,NHLF,Natural_Killer_cells_(PB),Osteobl,Ovary,PC_3,PC_9,Pancreas,Placenta,Psoas_Muscle,Right_Atrium,SK_N_SH,Small_Intestine,Spleen,T_cells_(PB)_Roadmap,T_helper_17_cell,Thymus,astrocyte,bipolar_neuron,brain,cardiac_muscle_cell,common_myeloid_progenitor_CD34_positive,common_myeloid_progenitor_CD34_positive_ENCSR337XXD_1,common_myeloid_progenitor_CD34_positive_ENCSR722JRY,effector_memory_CD4_positive_alpha_beta_T_cell,endodermal_cell,endothelial_cell_of_umbilical_vein,eosinophil_(VB),erythroblast_(CB),esophagus,fibroblast_of_dermis,fibroblast_of_lung,heart,heart_right_ventricle,hepatocyte,iPS_15b,iPS_DF_19.11,iPS_DF_6.9,keratinocyte,kidney,lung_ENCSR465WKM,mammary_epithelial_cell,myotube,naive_B_cell_(To),naive_B_cell_(VB),naive_thymus_derived_CD4_positive_alpha_beta_T_cell,neural_progenitor_cell,neural_stem_progenitor_cell,neuron,neutrophil,neutrophil_(CB),neutrophil_(VB),neutrophil_myelocyte_(BM),sigmoid_colon,skeletal_muscle_myoblast
source_regbuild	1.0
```

After:
```
# CACHE UPDATED 2019-09-30 14:07:50
species	homo_sapiens
assembly	GRCh37
sift	b
polyphen	b
source_polyphen	2.2.2
source_sift	sift5.2.2
source_genebuild	2011-04
source_gencode	GENCODE 19
source_assembly	GRCh37.p13
variation_cols	chr,variation_name,failed,somatic,start,end,allele_string,strand,minor_allele,minor_allele_freq,clin_sig,phenotype_or_disease,clin_sig_allele,pubmed,AFR,AMR,EAS,EUR,SAS,AA,EA,gnomAD,gnomAD_AFR,gnomAD_AMR,gnomAD_ASJ,gnomAD_EAS,gnomAD_FIN,gnomAD_NFE,gnomAD_OTH,gnomAD_SAS
source_COSMIC	86
source_HGMD-PUBLIC	20174
source_ESP	20141103
source_ClinVar	201810
source_dbSNP	151
source_1000genomes	phase3
source_gnomAD	r2.1
regulatory	1
cell_types	A549,A549_ENCSR797CXN,A673,Aorta,B_cell_ENCSR682AXR,B_cells_(PB)_Roadmap,CD14+CD16-_monocyte_(CB),CD14+CD16-_monocyte_(VB),CD14_positive_monocyte,CD38-_naive_B_cell_(VB),CD4+_ab_T_cell_(CB),CD4+_ab_T_cell_(VB),CD4_positive_CD25_positive_alpha_beta_regulatory_T_cell,CD4_positive_alpha_beta_T_cell,CD4_positive_alpha_beta_T_cell_ENCSR948ZKZ,CD4_positive_alpha_beta_memory_T_cell,CD8+_ab_T_cell_(CB),CM_CD4+_ab_T_cell_(VB),DND-41,EM_CD8+_ab_T_cell_(VB),EPC_(VB),Fetal_Adrenal_Gland,Fetal_Intestine_Large,Fetal_Intestine_Small,Fetal_Muscle_Leg,Fetal_Muscle_Trunk,Fetal_Stomach,Fetal_Thymus,GM12878,GM12878_ENCSR447YYN,Gastric,H1-mesenchymal,H1-neuronal_progenitor,H1-trophoblast,H1ESC,H1_hESC,H1_hESC_ENCSR820QMS,H9,H9_ENCSR323FKB,HCT116,HMEC,HSMM,HSMMtube,HUES48,HUES6,HUES64,HUVEC,HUVEC_prol_(CB),HepG2,IMR90,IMR_90,K562,Karpas_422,Left_Ventricle,Lung,M0_macrophage_(CB),M0_macrophage_(VB),M1_macrophage_(CB),M1_macrophage_(VB),M2_macrophage_(CB),M2_macrophage_(VB),MCF_7,MM_1S,MSC_(VB),Monocytes-CD14+,Monocytes-CD14+_(PB)_Roadmap,NH-A,NHDF-AD,NHEK,NHLF,Natural_Killer_cells_(PB),Osteobl,Ovary,PC_3,PC_9,Pancreas,Placenta,Psoas_Muscle,Right_Atrium,SK_N_SH,Small_Intestine,Spleen,T_cells_(PB)_Roadmap,T_helper_17_cell,Thymus,astrocyte,bipolar_neuron,brain,cardiac_muscle_cell,common_myeloid_progenitor_CD34_positive,common_myeloid_progenitor_CD34_positive_ENCSR337XXD_1,common_myeloid_progenitor_CD34_positive_ENCSR722JRY,effector_memory_CD4_positive_alpha_beta_T_cell,endodermal_cell,endothelial_cell_of_umbilical_vein,eosinophil_(VB),erythroblast_(CB),esophagus,fibroblast_of_dermis,fibroblast_of_lung,heart,heart_right_ventricle,hepatocyte,iPS_15b,iPS_DF_19.11,iPS_DF_6.9,keratinocyte,kidney,lung_ENCSR465WKM,mammary_epithelial_cell,myotube,naive_B_cell_(To),naive_B_cell_(VB),naive_thymus_derived_CD4_positive_alpha_beta_T_cell,neural_progenitor_cell,neural_stem_progenitor_cell,neuron,neutrophil,neutrophil_(CB),neutrophil_(VB),neutrophil_myelocyte_(BM),sigmoid_colon,skeletal_muscle_myoblast
source_regbuild	1.0
var_type	tabix
```

Looks like info.txt doesn't contain info about that files are already tabix indexed. Do I missunderstood something on this is wrong?

**Comment by Stikus** [comment]
Looks like I found the reason of this issue.
According to VEP Cache [page](http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache) all indexed cache is here:
`ftp://ftp.ensembl.org/pub/release-98/variation/indexed_vep_cache/`
And all non-indexed is here:
`ftp://ftp.ensembl.org/pub/release-98/variation/vep/`

But default FTP Cache URL for VEP from [this](https://github.com/Ensembl/ensembl-vep/blob/release/98/INSTALL.pl#L212) line is:
`$CACHE_URL  ||= "ftp://ftp.ensembl.org/pub/release-$DATA_VERSION/variation/vep";`
And it is pointing on not indexed cache. Am I correct?

**Comment by aparton** [comment]
Hi,

Thank you for this report. You’re correct, the changes that we made to make the VEP installer default to using the indexed cache files are missing from release 98, and they shouldn’t be. I’ll let you know when a fix is in place.

And as you’ve also found, you can download the indexed cache file directly from ftp://ftp.ensembl.org/pub/release-98/variation/indexed_vep_cache/ <ftp://ftp.ensembl.org/pub/release-98/variation/indexed_vep_cache/> in the meantime.

Kind Regards,
Andrew

**Comment by Stikus** [comment]
Thank you for answer and fast update.
But what about `--CONVERT` option? It is still present in INSTALL.pl, but now it have no effect at all.
Should it be removed maybe?

**Comment by aparton** [comment]
Hi,

Thanks for reporting this issue to us, the installer has now been updated and will correctly install the indexed versions of the cache files. 

Regarding --CONVERT, while we've switched to installing tabix-indexed cache files by default, then the installer can still be used to install non-indexed cache files. We also want to provide users with a mechanism for converting old cache files if they choose, so we don't want to remove the flag entirely.

Kind Regards,
Andrew

**Comment by Stikus** [comment]
But you removed [this](https://github.com/Ensembl/ensembl-vep/blob/39ee5b95677c08c58992d1f8e76a42a7f9207eda/INSTALL.pl#L1298) code block and [this](https://github.com/Ensembl/ensembl-vep/blob/39ee5b95677c08c58992d1f8e76a42a7f9207eda/INSTALL.pl#L1303) line respectively:
`system("perl $dirname/convert_cache.pl --dir $CACHE_DIR --species $species --version $DATA_VERSION\_$assembly --bgzip $bgzip --tabix $tabix") == 0 or print STDERR "WARNING: Failed to run convert script\n";`

In currect (98.2) release there are only 2 occurencies of this option:
[line72](https://github.com/Ensembl/ensembl-vep/blob/release/98/INSTALL.pl#L72):
`$CONVERT,`
[line167](https://github.com/Ensembl/ensembl-vep/blob/release/98/INSTALL.pl#L167)
`'CONVERT|t'          => \$CONVERT,`
And in `usage`

So for now `--CONVERT` does nothing according to code if I'm not mistaken.

**Comment by aparton** [comment]
Hi,

Thanks for this report. You're correct, I've submitted a PR to adjust this.

Kind Regards,
Andrew

**Comment by Stikus** [comment]
Thanks for answers and for your work
