### ISSUE TITLE
homo_sapiens is not a valid species name

### ISSUE THREAD

**Issue by PlatonB** [Ensembl/ensembl-vep#616]
Elementary OS 5.0
VEP script 98

Small test data:
```
rs10134555
rs10138890
rs10141135
rs11624464
rs11627978
rs12896956
rs12897751
rs2145463
rs3020575
rs56089226
```
Commands from docs:
`sudo docker run -t -i -v $HOME/vep_data:/opt/vep/.vep ensemblorg/ensembl-vep`

`./vep --cache --merged --vcf --force_overwrite -e --dir_cache /opt/vep/.vep/ -i /opt/vep/.vep/input/test_input.txt -o /opt/vep/.vep/output/test_output.vcf`

Error:
```
-------------------- WARNING ----------------------
MSG: homo_sapiens is not a valid species name (check DB and API version)
FILE: Bio/EnsEMBL/Registry.pm LINE: 1334
CALLED BY: Bio/EnsEMBL/Registry.pm  LINE: 1109
Date (localtime)    = Tue Oct  1 12:38:55 2019
Ensembl API version = 98
---------------------------------------------------

-------------------- EXCEPTION --------------------
MSG: Can not find internal name for species 'homo_sapiens'
STACK Bio::EnsEMBL::Registry::get_adaptor /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Registry.pm:1111
STACK Bio::EnsEMBL::VEP::BaseVEP::get_adaptor /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:308
STACK Bio::EnsEMBL::VEP::BaseVEP::get_database_assembly /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:419
STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:118
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel ./vep:224
Date (localtime)    = Tue Oct  1 12:38:55 2019
Ensembl API version = 98
---------------------------------------------------
```

**Comment by helensch** [comment]
Hi

Thank you for reporting the error.  We had some issues accessing the 98 databases. This has now been fixed. Please could you try running your command again.  

Regards
Helen

**Comment by PlatonB** [comment]
Now it's another error.

```
2019-10-01 16:34:52 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this
2019-10-01 16:34:52 - INFO: Database will be accessed when using --hgvs
2019-10-01 16:34:52 - INFO: Database will be accessed when using --hgvsc
2019-10-01 16:34:52 - INFO: Database will be accessed when using --hgvsp
2019-10-01 16:34:52 - INFO: Database will be accessed when using --use_transcript_ref

-------------------- EXCEPTION --------------------
MSG: ERROR: Could not write to stats file /opt/vep/.vep/output/test_output.vcf_summary.html

STACK Bio::EnsEMBL::VEP::BaseRunner::get_stats_file_handle /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:280
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:142
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel ./vep:224
Date (localtime)    = Tue Oct  1 16:34:53 2019
Ensembl API version = 98
---------------------------------------------------
```

**Comment by aparton** [comment]
Hi,

VEP output needs to be written to a directory that already exists, VEP won’t create directories even when specifying the path for output files.

Running ‘mkdir /opt/vep/.vep/output’ before running VEP should fix this issue.

Kind Regards,
Andrew

**Comment by PlatonB** [comment]
I created only those folders that are shown in the image of the corresponding [documentation section](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker_setup). As far as I understand, command mentioned below the picture is designed for specified folder structure.

**Comment by aparton** [comment]
Hi,

You're right, it looks like the paths in our documentation need an update. I'll get this changed.

Thanks for passing this on.

Kind Regards,
Andrew

**Comment by nakib103** [comment]
Hello @PlatonB ,

I see that the image now contains the 'output' folder. It is recommended to create this folder along with the other folders mentioned in the image and mount them when creating the docker container.

The command below is designed to work with the recommended directory structure shown in the image. Please let me know if you find anything else needs to be changed in the doc.

Best regards,
Nakib

**Comment by PlatonB** [comment]
Hello, @nakib103 !
Over time I have written own annotators, and now, unfortunately, do not have the motivation and time to retest VEP.

**Comment by nakib103** [comment]
Thank you, I am closing this issue. Please re-open another one if you need to raise an issue in the future.

Best regards,
Nakib
