### ISSUE TITLE
Calculation of hg38 GnomAD Frequencies for Changed Reference

### ISSUE THREAD

**Issue by DarioS** [Ensembl/ensembl-vep#618]
The allele frequencies for hg38 are calculated using transformed coordinates. But, the reference allele between hg19 and hg38 changed in some places. How are such allele frequencies for variants that do not exist in hg19 because they were the reference sequence recorded?

**Comment by helensch** [comment]
Hi 

Thank you for your query. The frequency of a variant allele is reported if available.

From your query, I am currently looking into an issue with variants where the reference has changed.  Is there an example variant or region that you are querying?

Regards
Helen

**Comment by DarioS** [comment]
I have a real example. I type 

```
18 63712604 63712604 G T
```

into the text field of the hg38 version of the web application and process it. Unlike above, in hg19, the reference allele is T and the SNP is G.

In the VEP output for FIN AF (which is hg38 and G to T), I see 0.335. But on the [GnomAD website](https://gnomad.broadinstitute.org/variant/18-61379838-T-G), which is hg19 and has the reference and alternative alleles switched (T to G), I also see 0.335. This seems contradictory.

I suppose these kinds of problems will disappear in a few months' time when gnomAD releases its variant summaries based on reads mapped to hg38.

**Comment by at7** [comment]
If the reference allele has been swapped with one of the alternative alleles we didn't recalculate the frequencies correctly. At this point we will wait for the reprocessed gnomAD data for GRCh38 which is expected this fall. Depending on the actual release date we will hopefully be able to integrate the new data into Ensembl for release/100.

**Comment by DarioS** [comment]
[gnomAD 3](https://gnomad.broadinstitute.org/downloads#variants) using GRCh38 natively without lift-overs has been released. Perhaps it could even be in version 99!

**Comment by diegomscoelho** [comment]
Hi @DarioS,

Data from gnomAD 3 was added recently to VEP GRCh38 cache in release 107.
Closing this issue now, but feel free to reopen this or open a new one if you have any question.

Regards, @diegomscoelho
