### ISSUE TITLE
VEP Performance (after following optimization instructions) with dbSNP IDs

### ISSUE THREAD

**Issue by KallyopeBio** [Ensembl/ensembl-vep#619]
I've installed version 98 of the Variant Effect Predictor (VEP) onto a workstation running ubuntu 16.04 LTS. The machine has 8 cores and 64 GB of RAM. 

I've read all the documentation at:
https://useast.ensembl.org/info/docs/tools/vep/script/vep_download.html
https://useast.ensembl.org/info/docs/tools/vep/script/vep_other.html
https://useast.ensembl.org/info/docs/api/api_installation.html
https://useast.ensembl.org/info/docs/tools/vep/script/index.html

I followed all the instructions in the second link (above) to ensure the installation is configured for optimal performance. The documentation indicates that VEP can process 3 million variants in 30 minutes, but my installation has already taken several days to process just over 2 million variants, and the computation is still not complete. 

I'm running the following command (the filenames and directories have been anonymized):

`./vep --cache --input_file ./rsids.txt --format id --dir_cache ~/cache_dir --output_file  ./output_vep.tsv --no_stats --fork 12 --tab --distance 2000,500 --per_gene --verbose --buffer_size 1000000`

The output from the command, so far, is:

> Will only load v98 databases
Species 'homo_sapiens' loaded from database 'homo_sapiens_core_98_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_cdna_98_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_otherfeatures_98_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_rnaseq_98_38'
homo_sapiens_variation_98_38 loaded
homo_sapiens_funcgen_98_38 loaded
No ancestral database found
No ontology database found
ensembl_taxonomy API not found - ignoring ncbi_taxonomy
Use of uninitialized value $ensembl_metadata_db in concatenation (.) or string at /home/justin/Bioinformatics/ensembl/ensembl-vep/Bio/EnsEMBL/Registry.pm line 2363.
ensembl_metadata API not found - ignoring 
No production database or adaptor found
WARNING: No mappings found for variant 'rs6846235'
WARNING: No mappings found for variant 'rs7673364'
WARNING: No mappings found for variant 'rs7660850'
WARNING: No mappings found for variant 'rs7683747'

I've specified the input variants by their dbSNP rsIDs. Is that the problem, because it incurs a very large number of dbSNP lookups? I didn't see any documentation about this format causing performance issues. I've made sure to sort the variants by their position on the chromosome, in ascending order. 

I've noticed that the CPU usage on the machine is very low. So the slowness is not driven by CPU constraints. The memory usage is also very low, and yet the program is still running, and new outputs are periodically written to the output file. (This makes me suspect slow access to some important DB, probably the dbSNP?)

Could someone please suggest what may be going wrong, or strategies for debugging the slowness? Or additional information I can provide to make this question more tractable?

**Comment by aparton** [comment]
Hi,

Unfortunately, dbSNP rsIDs require a database connection to obtain coordinates for finding overlapping features. Using VCF or standard VEP input should provide a significant speedup.

If you require to use rsIDs as input, then you can use our LocalID plugin that allows for the use of rsIDs without requiring a database connection: https://github.com/Ensembl/VEP_plugins/blob/release/98/LocalID.pm <https://github.com/Ensembl/VEP_plugins/blob/release/98/LocalID.pm> - however this will take a long time to construct the initial database and will still be slightly slower than using VCF or standard VEP input.

Additionally, there are a list of suggested changes you can make to speed VEP up here: https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#faster <https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#faster> - in particular downloading a FASTA file will give you a significant speedup.

Kind Regards,
Andrew

**Comment by KallyopeBio** [comment]
Thanks very much for this excellent answer, Andrew. I found that using the LocalID plugin solves the performance issue I encountered. I've opened a separate issue regarding the behavior of LocalID in the Plugins repo, but the speed issue is resolved by your answer.
