### ISSUE TITLE
Failed test 'get_stats_file_handle'

### ISSUE THREAD

**Issue by cookersjs** [Ensembl/ensembl-vep#62]
Installing VEP using automatic methods:

`perl INSTALL.pl -a acf -s homo_sapiens -y GRCh38 -c ${dir:-/root}/.vep `

This worked with VEP v87 but when I was using that version, I used '--NO_HTSLIB', and now I want HTSLIB. This doesn't seem to be related to that, but figured it was worth mentioning. 

The error:

./t/CacheDir.t ....................................... ok
Possible precedence issue with control flow operator at /usr/local/lib/perl5/site_perl/5.24.1/Bio/DB/IndexedBase.pm line 839.

#   Failed test 'get_stats_file_handle - extension handling 2'
#   at ./t/Runner.t line 371.

#   Failed test 'get_stats_file_handle - extension handling 3'
#   at ./t/Runner.t line 374.

-------------------- EXCEPTION --------------------
MSG: ERROR: Stats file /root/.vep/ensembl-vep/t/testdata/user_file589.txt.txt already exists. Specify a different output file with --stats_file or overwrite existing file with --force_overwrite

STACK Bio::EnsEMBL::VEP::BaseRunner::get_stats_file_handle /root/.vep/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:273
STACK Bio::EnsEMBL::VEP::BaseRunner::dump_stats /root/.vep/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:301
STACK Bio::EnsEMBL::VEP::Runner::finish /root/.vep/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:161
STACK Bio::EnsEMBL::VEP::Runner::run /root/.vep/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:193
STACK toplevel ./t/Runner.t:394
Date (localtime)    = Mon Jul 17 13:49:58 2017
Ensembl API version = 89
---------------------------------------------------
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 29 just after 37.
Failed 1/38 test programs. 2/1521 subtests failed.
./t/Runner.t ......................................... 
Dubious, test returned 29 (wstat 7424, 0x1d00)
Failed 2/37 subtests 

Test Summary Report
-------------------
./t/Runner.t                                       (Wstat: 7424 Tests: 37 Failed: 2)
  Failed tests:  35-36
  Non-zero exit status: 29
  Parse errors: No plan found in TAP output
Files=38, Tests=1521, 66 wallclock secs ( 0.23 usr  0.12 sys + 60.02 cusr  3.38 csys = 63.75 CPU)
Result: FAIL

**Comment by cookersjs** [comment]
I should have looked through previous issues before posting this, as it seems like the exact same issue seen [here](https://github.com/Ensembl/ensembl-vep/issues/4). For now, I am just running the install with --NO_TEST

**Comment by willmclaren** [comment]
Thanks, this has already been reported and will be fixed in the next release (https://github.com/Ensembl/ensembl-vep/commit/5315bf31b20fd6563bbd18a606ea4968ff5e4e88).

You can avoid the issue also by checking out ensembl-vep using git rather than downloading a zip of the repo.
