### ISSUE TITLE
lib/Bio/DB/HTS.xs:52:10: fatal error: 'htslib/kseq.h' file not found

### ISSUE THREAD

**Issue by WallaceSUI** [Ensembl/ensembl-vep#621]
Hi, I was trying to install vep in my macbookpro 2019. I install vep in my home folder: /Users/wallace/ensembl-vep
**When I run 'perl INSTALL.pl':**
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-bcf-sr.o test/test-bcf-sr.c
gcc  -o test/test-bcf-sr test/test-bcf-sr.o libhts.a -lz -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-bcf-translate.o test/test-bcf-translate.c
gcc  -o test/test-bcf-translate test/test-bcf-translate.o libhts.a -lz -lz -lm -lbz2 -llzma -lpthread
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.11 - moving files to ./biodbhts
 - making Bio::DB:HTS
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.11'
Building Bio-DB-HTS
cc -iwithsysroot /Users/wallace/ensembl-vep/htslib -iwithsysroot /System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -DVERSION="2.11" -DXS_VERSION="2.11" -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wno-unused-result -c -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -Os -o lib/Bio/DB/HTS.o lib/Bio/DB/HTS.c
lib/Bio/DB/HTS.xs:52:10: fatal error: 'htslib/kseq.h' file not found
#include "htslib/kseq.h"
         ^~~~~~~~~~~~~~~
1 error generated.
error building lib/Bio/DB/HTS.o from 'lib/Bio/DB/HTS.c' at /System/Library/Perl/5.18/ExtUtils/CBuilder/Base.pm line 182.
ERROR: Shared Bio::DB:HTS library not found

And my environment variables are:
$DYLD_LIBRARY_PATH = /Users/wallace/ensembl-vep/htslib:
$PERL5LIB = /Users/wallace/perl5:

I don't know how to deal with this problem. Thanks a lot.

**Comment by WallaceSUI** [comment]
Can you help to give me some steps about this installation in my macbookpro?
my system is macOS Catalina version 10.5.
1: What environments variables should I add before the installation?
2: What packages should I install before 'perl INSTALL.pl'?
3: I always meet the error that 'ERROR: Shared Bio::DB:HTS library not found'. How can I avoid this error?
4: Should I use 'cpanm' to install some packages? If I want to put ensembl-vep in /Users/wallace/ensembl-vep/, should I run 'cpanm....' in this folder? or just in /Users/wallace/ ?
5: How to solve the problem: 'fatal error: 'htslib/kseq.h' file not found'
6: I have deleted folder 'ensembl-vep' and redownload it from git for many times. I'm not sure whether I should delete something that has been installed by the previous installation.
7: If I use 'no-htslib', then the testing result will be 0/1666......

Thanks a lot.

**Comment by aparton** [comment]
Hi,

A detailed list of instructions for how to install VEP on MacOS can be found here: https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#macos - including information on environment variables, prerequisite packages and cpanm. Following these instructions should help you avoid the errors you are currently seeing.

Regarding deleting the ensembl-vep folder, everything installed by INSTALL.pl will be stored within this folder, so you don't need to delete anything else if you've deleted the folder.

Let us know how you get on with the attached installation instructions, if you have any more issues then we can help from there.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any more questions, please feel free to reopen it or open a new one.

Kind Regards,
Andrew
