### ISSUE TITLE
Is it possible to update refseq build using GRCh37

### ISSUE THREAD

**Issue by genomics-geek** [Ensembl/ensembl-vep#622]
I was wondering if it was possible to update the cache to use the latest refseq build one can download from UCSC?

**Comment by dglemos** [comment]
Hi @genomics-geek,
You can correct the transcript models with the bam files provided by NCBI as explained here https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#refseq 
Hope this answers your question.

**Comment by genomics-geek** [comment]
Hi @dglemos not sure if this is what I need.  In SnpEff, one could (commands below) to get the latest refseq build from UCSC.  Is there something similar for VEP?

```
        echo "
            SELECT
                rg.bin as '#bin',
                CONCAT(rg.name,'.',gi.version) as 'name',
                rg.chrom,
                rg.strand,
                rg.txStart,
                rg.txEnd,
                rg.cdsStart,
                rg.cdsEnd,
                rg.exonCount,
                rg.exonStarts,
                rg.exonEnds,
                rg.score,
                rg.name2,
                rg.cdsStartStat,
                rg.cdsEndStat,
                rg.exonFrames
            FROM hg19.refGene rg
            INNER JOIN hgFixed.gbCdnaInfo gi ON rg.name=gi.acc;
        " > refgene.sql;

        mysql --user=genome --host=genome-mysql.cse.ucsc.edu \
            -A ${reference_version} \
            < refgene.sql > ${data_directory}/genes.refseq;
```

```
        mkdir ${data_directory}/rna;

        wget -r -nH --cut-dirs=3 -np \
            "ftp://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/mRNA_Prot/" \
            -A "human*rna.fna.gz" \
            -P ${data_directory}/rna;

        cat ${data_directory}/rna/human*fna.gz > ${data_directory}/human.rna.fna.gz
```

followed by:

```
        java -jar ${output_directory}/snpEff/snpEff.jar \
            build -refseq -v ${reference_version} \
            -dataDir ${output_directory}/snpEff/data/
```

**Comment by dglemos** [comment]
Hi,
the most similar thing in VEP is to use the refseq cache with option `--refseq` (read [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#cacheopt)) to output the consequence relative to refseq transcripts in place of the default Ensembl transcripts.  
How to download [refseq cache](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache)

**Comment by genomics-geek** [comment]
I am using  the cache for RefSeq, I just noticed some newer transcript ids are in RefSeq and not in the cache.  I was just curious if there was a way to update it.

**Comment by dglemos** [comment]
I didn't notice you were already using vep cache. Sorry about the mistake. 
The cache is updated every release, it's not possible to update it in between. However, you can run vep with custom annotation using a file that contains the features you want - read more [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html).

**Comment by genomics-geek** [comment]
Thanks @dglemos. That makes sense now.  I didn't realize it was updated each release.

**Comment by sarahhunt** [comment]
@genomics-geek - just to clarify, the GRCh37 transcript set is not updated frequently. RefSeq transcripts are not built from the genome sequence and do not always match the genome sequence. This means mappings back to the genome can be ambiguous. For this reason, we only ever use NCBI's mappings. 

New transcript annotation from both Ensembl and RefSeq has been released solely on GRCh38 for some years now. In 2017, NCBI mapped the then-current RefSeq transcript set back to GRCh37 and we made these data available in VEP. This process has just been repeated - it is slightly too late for our next release, so the newer RefSeq set will be available in VEP in March. 

If you wish to use this newer transcript set, as Diana said, you can use VEP's custom annotation option. The GFF and BAM files are here:
https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/annotation_releases/105.20190906/GCF_000001405.25_GRCh37.p13/

Our docs on the alignment correction step are here:
https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#refseq

**Comment by genomics-geek** [comment]
@sarahhunt thanks for the info. So if I understand correctly in the March release VEP will update RefSeq?

I understand how to use the BAM in VEP, but I don’t see in the docs how to use the GFF file for RefSeq. Maybe I missed it in the docs?

**Comment by aparton** [comment]
Hi,

You can use GFF files with VEP with the --custom flag. You can read more information about it here: https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html

And yes, our March/April release will include the newer RefSeq set for GRCh37.

Kind Regards,
Andrew

**Comment by genomics-geek** [comment]
Thank you @aparton
