### ISSUE TITLE
grch37 Install Instructions

### ISSUE THREAD

**Issue by DarioS** [Ensembl/ensembl-vep#624]
The [webpage](http://grch37.ensembl.org/info/docs/webcode/mirror/tools/vep.html) advises users to download a file such as Homo_sapiens.GRCh38.dna.toplevel.fa.gz which doesn't seem relevant for GRCh37. The instructions also refer to ensembl-tools which is defunct and the README advises going to the ensembl-vep repository instead. I wonder if the instructions for installing GRCh37 could be updated and placed closer to those for GRCh38 and perhaps some instructions for maintaining both installs on the same server added. A real use case for that is TCGA exome sequencing and RNA sequencing data has been harmonised to hg38 but whole genome sequencing wasn't harmonised and is only available from Legacy Archive in reference to hg19.

**Comment by dglemos** [comment]
Hi @DarioS,
Thanks for the examples. This page is quite old, it needs to be updated. 

Best regards,
Diana

**Comment by dglemos** [comment]
Hi @DarioS,
We have updated the VEP setup instructions page for GRCh37. The GRCh38 and GRCh37 are kept separated, the same applies to the VEP setup instructions. 
Please let me know if we are missing anything. 

Best wishes,
Diana

**Comment by jon4thin** [comment]
Where can this be found?
thank you!
