### ISSUE TITLE
Hi, I have a question

### ISSUE THREAD

**Issue by stellaoh** [Ensembl/ensembl-vep#626]
Dear VEP team. 
Hi, I have a question. 

I had called variants using hg19 mapped bam. 
So, chromosome name in called variants file was annotated with "chr". 

But, In ensembl, I could downloaded only "cache, and reference files of GRCh37 version" (chromosome name is annotated without "chr" ex. 1,2, 3 .. M). 

In this case..
If I delete "annotated chr", may I use cache and reference of GRCh37 version (in ensembl db)?

Thanks.

**Comment by ima23** [comment]
Dear @stellaoh,

If you use VEP to annotate your variants, either notation with or without "chr" will work.
If you encounter any issues please let me know and I will look into it.

Kind regards,
Irina

**Comment by ima23** [comment]
I am closing this issue, but if you have any more questions please feel free to reopen it.

Best regards,
Irina
