### ISSUE TITLE
Transcript ablation

### ISSUE THREAD

**Issue by CWYuan08** [Ensembl/ensembl-vep#627]
Hi there,

I am wondering why some variants with OverlapPC=100 are not assigned as transcript ablation, but as "stop_lost,coding_sequence_variant,5_prime_UTR_variant,3_prime_UTR_variant,intron_variant"? 

Thank you 
Ulrika

**Comment by ima23** [comment]
Hi Ulrika,

I see your point. Can you give me a specific example to double check the case?

Thanks,
Irina

**Comment by CWYuan08** [comment]
Hi, I have found a structural variant (deletion) in two of our samples, it is the same one but one has been reported as transcript ablation the other one as above, both with same OverlapBP and OverlapPC=100, why this is? (I can send you the screenshoot by email) 

Thank you again

**Comment by ima23** [comment]
Hi @CWYuan08,

I would only need the structural variants in the format described [here](https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#sv) to check them. For example:
```
1    160283    471362    DUP
1    1385015   1387562   DEL
```
Is it possible to write the 2 structural variants in this format and share them here?

Thanks,
Irina

**Comment by CWYuan08** [comment]
Hi Irina
Sorry I have run VEP with the genome and annotation of our organism of interest which is not in the VEP database, can I send you the result? 

Best 
Ulrika

**Comment by ima23** [comment]
Hi Ulrika,

in principle VEP will annotate with transcript_ablation structural variants (SVs) that remove the region covering the specific transcript.

I can have a look tracing this. Can you please share:

-  the structural variation in the input format 
- the structural variation vep results in the 2 runs
- vep commands
- genome annotation of the ablated transcript for the 2 samples (Is this a gff?)

Thanks,
Irina

**Comment by CWYuan08** [comment]
Hi Irina,
the input is: chrIII 10192119 10201100 DEL
relevant part of the result for this problem is: 
Location Allele Consequence Strain OverlapBP OverlapPC
1 chrIII:10192119-10201100 deletion transcript_ablation LKC34 1460 100
2 chrIII:10192119-10201100 deletion transcript_ablation LKC34 1620 100
3 chrIII:10192119-10201100 deletion transcript_ablation LKC34 1627 100
4 chrIII:10192119-10201100 deletion transcript_ablation LKC34 1667 100
5 chrIII:10192119-10201100 deletion stop_lost,coding_sequence_variant,5_prime_UTR_variant,3_prime_UTR_variant,intron_variant,feature_truncation LKC34 1731 76.26
6 chrIII:10193562-10201986 deletion stop_lost,coding_sequence_variant,5_prime_UTR_variant,3_prime_UTR_variant,intron_variant ECA248 1460 100
7 chrIII:10193562-10201986 deletion stop_lost,coding_sequence_variant,5_prime_UTR_variant,3_prime_UTR_variant,intron_variant ECA248 1620 100
8 chrIII:10193562-10201986 deletion stop_lost,coding_sequence_variant,5_prime_UTR_variant,3_prime_UTR_variant,intron_variant ECA248 1627 100
9 chrIII:10193562-10201986 deletion stop_lost,coding_sequence_variant,5_prime_UTR_variant,3_prime_UTR_variant,intron_variant ECA248 1667 100
10 chrIII:10193562-10201986 deletion stop_lost,coding_sequence_variant,5_prime_UTR_variant,3_prime_UTR_variant,intron_variant ECA248 2270 100

VEP commands: docker run -t -i -v ~/Documents/input/:/opt/vep/.vep ensemblorg/ensembl-vep ./vep --biotype -i /opt/vep/.vep/{input.Vcf} -o /opt/vep/.vep/{output} --custom /opt/vep/.vep/{input.Annotation},VC2010,gtf -fasta /opt/vep/.vep/{input.Fasta} 

I had a look at the genome annotation, the region covering all the 5 transcripts is 10199370-10201639. 

Thank you
Ulrika

**Comment by ima23** [comment]
Hi @CWYuan08,

Thank you for your patience, the fix has been now applied. If you reinstall VEP 98 updating the API, the change will get applied to your local installation.
Please don't hesitate to contact us if you are experiencing issues.

Kind regards,
Irina

**Comment by CWYuan08** [comment]
Dear @ima23,

thank you for getting back. Has the one in docker container also got updated? I need to run it through docker. 

Best
Ulrika

**Comment by ima23** [comment]
Hi @CWYuan08,

The docker image will not automatically get this change in. To get the change in you will need to run `docker pull ensemblorg/ensembl-vep`.

Regrads,
Irina

**Comment by ima23** [comment]
Hi @CWYuan08,

The docker image for the latest Ensembl VEP release 99 contains these changes.
Please let us know if you are experiencing the issue using the latest docker image.

Kind regards,
Irina

**Comment by ima23** [comment]
I am closing this issue now. If you have any related questions please feel free to reopen it and we will look into it.

Kind regards,
Irina
