### ISSUE TITLE
Allow to override CACHE_URL_INDEXED in INSTALL.pl

### ISSUE THREAD

**Issue by lbeltrame** [Ensembl/ensembl-vep#628]
Currently the `-u` option only sets CACHE_DIR, not CACHE_DIR_INDEXED. The result is that even if you have the (heavy!) cache files downloaded, they will get downloaded again: with slow connections (like the one at my institution) this can be extremely painful. 

Looking at https://github.com/Ensembl/ensembl-vep/pull/613 and `INSTALL.pl` (but my Perl knowledge is very basic) it seems to me that there's no explicit switch for this.

**Comment by aparton** [comment]
Hi,

Thanks for this report, you're right, this functionality isn't working correctly for indexed cache files.

I'll prepare a fix and let you know when it's in place.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

This issue has now been resolved, as VEP is now configured to download the indexed cache by default.

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew
