### ISSUE TITLE
ERROR: SIFT not available--- during test

### ISSUE THREAD

**Issue by rajkump** [Ensembl/ensembl-vep#631]
Hi ,
  I am following the instructions given here _[https://gist.github.com/ckandoth/5390e3ae4ecf182fa92f6318cfa9fa97]_ to install **vep**. Everything seems to be fine. When I tested the installation I get this ERROR message,

`./vep --species homo_sapiens --assembly GRCh37 --offline --no_progress --no_stats --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --pubmed --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --vcf --minimal --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --dir $VEP_DATA --fasta $VEP_DATA/homo_sapiens/$VER\_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz --input_file examples/homo_sapiens_GRCh37.vcf --output_file examples/homo_sapiens_GRCh37.vep.vcf --polyphen b --af --af_1kg --af_esp --regulatory`

-------------------- EXCEPTION --------------------
MSG: ERROR: SIFT not available

```
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::check_sift_polyphen /Software/vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:168
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::new /Software/vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:121
STACK Bio::EnsEMBL::VEP::CacheDir::get_all_AnnotationSources /Software/vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:150
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /Software/vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:121
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /Software/vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /Software/vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /Software/vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /Software/vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel ./vep:225
Date (localtime)    = Wed Oct 23 14:43:18 2019
Ensembl API version = 95
```
---------------------------------------------------

**Comment by dglemos** [comment]
Hi, 
vep checks if sift is available by reading the info.txt file in your cache directory, probably under path_to_cache/homo_sapiens/95_GRCh37/info.txt. The file should contain a line: sift b

**Comment by rajkump** [comment]
Hi,
   Glad to report it is solved now. The problem is that 'info.txt' is not present in that dir. So I 'untar' the file '$VEP_DATA\homo_sapiens_vep_95_GRCh37.tar.gz' to get 'info.txt'. This solved the problem. A fix to 'perl INSTALL.pl --AUTO f --SPECIES homo_sapiens --ASSEMBLY GRCh37 --DESTDIR $VEP_PATH --CACHEDIR $VEP_DATA' is needed.
