### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kai-21** [Ensembl/ensembl-vep#633]
Dear sir, 

I couldn't find the right place to ask a question about VEP, so I write here.

These are my questions..

The result from VEP annotation sometime have more than one consequences like below. I think some consequence combinations does not make sense (missense variant could not be located in splice_region). How could this consequences have made?  
'missense_variant,splice_region_variant', 
'stop_gained,inframe_insertion'
'intron_variant,NMD_transcript_variant'

And I also want to know how VEP decide 'NMD_transcript_variant'. Is there any document about rules or something for decision of NMD_transcript_variant.

I really hope you answer my questions.
Thank you.

**Comment by dglemos** [comment]
Hi @kai-21,
The definition of a splice region variant is "A sequence variant in which a change has occurred within the region of the splice site, either within 1-3 bases of the exon or 3-8 bases of the intron". 
It can happen that there's a substitution of one base pair in one of these regions. One example is rs781551140, for transcript ENST00000354383 this variant has consequence "missense_variant,splice_region_variant". 
Sometimes some combination of consequences can be wrong or misleading. If you think you found variants like that, you can send us some specific examples that will help us to improve vep calculations. 

Regarding your last question, a variant is 'NMD_transcript_variant' when that variant is in a transcript that is the target of NMD (transcript with nonsense_mediated_decay biotype). 
You can read more about vep calculated consequences and their definitions here: https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html

**Comment by dglemos** [comment]
I am closing this issue, but if you have any more questions please feel free to reopen it.

Best regards,
Diana
