### ISSUE TITLE
Unnnecessary Plugins Prompt

### ISSUE THREAD

**Issue by DarioS** [Ensembl/ensembl-vep#634]
The installation command I ran was `perl INSTALL.pl -c cache/ --PLUGINS dbNSFP,CADD,G2P` but during the procedure I was asked to specify the plugins anyway

> The VEP can use plugins to add functionality and data.
Plugins will be installed in cache//Plugins
Do you want to install any plugins (y/n)? y

**Comment by dglemos** [comment]
Hi @DarioS,
To run your command you have to run it with flag `--AUTO` which runs the installer without prompts. You can read more about installation options [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#installer)

**Comment by DarioS** [comment]
I overlooked the need for `--AUTO`.
