### ISSUE TITLE
VEP Uninitialized value in VariationTabix.pm line 184

### ISSUE THREAD

**Issue by LemuelRacacho** [Ensembl/ensembl-vep#636]
## Describe the issue
Output file is generated but lacking annotations that should be added by using "--everything"

### System
- VEP version: 98
- VEP Cache version: 98
- Perl version: v5.18.2
- OS: Ubuntu 14.04.5 LTS, Trusty Tahr
- tabix installed: ensembl-vep/biodbhts/lib/Bio/DB/DB/HTS/Tabix.pm

### Full VEP command line
```
./vep -i examples/homo_sapiens_GRCh37.vcf --refseq --everything --fasta ~/.vep/Homo_sapiens.GRCh37.dna.toplevel.fa  --offline
```

### Full error message
> 2019-11-06 15:31:35 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this
Use of uninitialized value in subtraction (-) at /home/lracacho/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/VariationTabix.pm line 184, <VARS> line 1.
Use of uninitialized value in addition (+) at /home/lracacho/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/VariationTabix.pm line 184, <VARS> line 1.
Use of uninitialized value in subtraction (-) at /home/lracacho/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/VariationTabix.pm line 184, <VARS> line 1.
Use of uninitialized value in addition (+) at /home/lracacho/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/VariationTabix.pm line 184, <VARS> line 1.

**Comment by dglemos** [comment]
Hi @LemuelRacacho,
Could you provide an example of a variant from your output file?

**Comment by LemuelRacacho** [comment]
Thanks for looking into my issue. Here is a partial .txt output file generated by the command above:

#Uploaded_variation	Location	Allele	Gene	Feature	Feature_type	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	Extra
rs116645811	21:26960070	A	54148	NM_017446.3	Transcript	intron_variant	-	-	-	-	-	-	IMPACT=MODIFIER;STRAND=-1;VARIANT_CLASS=SNV;SYMBOL=MRPL39;SYMBOL_SOURCE=EntrezGene;BIOTYPE=protein_coding;ENSP=NP_059142.2;INTRON=9/9;HGVSc=NM_017446.3:c.969+1077C>T;BAM_EDIT=OK
rs116645811	21:26960070	A	54148	NM_080794.3	Transcript	missense_variant	1015	1001	334	T/M	aCg/aTg	-	IMPACT=MODERATE;STRAND=-1;VARIANT_CLASS=SNV;SYMBOL=MRPL39;SYMBOL_SOURCE=EntrezGene;BIOTYPE=protein_coding;CANONICAL=YES;ENSP=NP_542984.2;SIFT=tolerated_low_confidence(0.22);PolyPhen=benign(0.102);EXON=10/11;HGVSc=NM_080794.3:c.1001C>T;HGVSp=NP_542984.2:p.Thr334Met;BAM_EDIT=OK
rs116645811	21:26960070	A	282566	NR_024092.1	Transcript	upstream_gene_variant	-	-	-	-	-	-	IMPACT=MODIFIER;DISTANCE=4534;STRAND=-1;VARIANT_CLASS=SNV;SYMBOL=LINC00515;SYMBOL_SOURCE=EntrezGene;BIOTYPE=misc_RNA;CANONICAL=YES;BAM_EDIT=OK
rs1135638	21:26965148	A	54148	NM_017446.3	Transcript	synonymous_variant	911	897	299	G	ggC/ggT	-	IMPACT=LOW;STRAND=-1;VARIANT_CLASS=SNV;SYMBOL=MRPL39;SYMBOL_SOURCE=EntrezGene;BIOTYPE=protein_coding;ENSP=NP_059142.2;EXON=8/10;HGVSc=NM_017446.3:c.897C>T;HGVSp=NP_059142.2:p.Gly299%3D;BAM_EDIT=OK

**Comment by LemuelRacacho** [comment]
This format might be better...

#Uploaded_variation | Location | Allele | Gene | Feature | Feature_type | Consequence | cDNA_position | CDS_position | Protein_position | Amino_acids | Codons | Existing_variation | IMPACT | DISTANCE | STRAND | FLAGS | VARIANT_CLASS | SYMBOL | SYMBOL_SOURCE | HGNC_ID | BIOTYPE | CANONICAL | MANE | TSL | APPRIS | CCDS | ENSP | SWISSPROT | TREMBL | UNIPARC | REFSEQ_MATCH | GENE_PHENO | SIFT | PolyPhen | EXON | INTRON | DOMAINS | miRNA | HGVSc | HGVSp | HGVS_OFFSET | AF | AFR_AF | AMR_AF | EAS_AF | EUR_AF | SAS_AF | AA_AF | EA_AF | gnomAD_AF | gnomAD_AFR_AF | gnomAD_AMR_AF | gnomAD_ASJ_AF | gnomAD_EAS_AF | gnomAD_FIN_AF | gnomAD_NFE_AF | gnomAD_OTH_AF | gnomAD_SAS_AF | MAX_AF | MAX_AF_POPS | CLIN_SIG | SOMATIC | PHENO | PUBMED | MOTIF_NAME | MOTIF_POS | HIGH_INF_POS | MOTIF_SCORE_CHANGE
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
rs116645811 | 21:26960070 | A | 54148 | NM_017446.3 | Transcript | intron_variant | - | - | - | - | - | - | MODIFIER | - | -1 | - | SNV | MRPL39 | EntrezGene | - | protein_coding | - | - | - | - | - | NP_059142.2 | - | - | - | - | - | - | - | - | 9-Sep | - | - | NM_017446.3:c.969+1077C>T | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | -
rs116645811 | 21:26960070 | A | 54148 | NM_080794.3 | Transcript | missense_variant | 1015 | 1001 | 334 | T/M | aCg/aTg | - | MODERATE | - | -1 | - | SNV | MRPL39 | EntrezGene | - | protein_coding | YES | - | - | - | - | NP_542984.2 | - | - | - | - | - | tolerated_low_confidence(0.22) | benign(0.102) | 11-Oct | - | - | - | NM_080794.3:c.1001C>T | NP_542984.2:p.Thr334Met | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | -
rs116645811 | 21:26960070 | A | 282566 | NR_024092.1 | Transcript | upstream_gene_variant | - | - | - | - | - | - | MODIFIER | 4534 | -1 | - | SNV | LINC00515 | EntrezGene | - | misc_RNA | YES | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | -

**Comment by LemuelRacacho** [comment]
Hi Diana,
I posted a partial output at Github.
Thank you very much for looking into the issue!!
Cheers
Lem

**Comment by aparton** [comment]
Hi,

It looks like tabix isn't working correctly, however I'm not entirely sure why. Could you please run 

tabix ~/.vep/homo_sapiens_refseq/98_GRCh37/11/all_vars.gz 11:119854-119854

And let me know what the output is?

Kind Regards,
Andrew

**Comment by LemuelRacacho** [comment]
Thanks for helping out! Am I supposed to run tabix on the cache files? Here is the output:

[tabix] failed to load the index file.

**Comment by aparton** [comment]
Hi,

Yes, running tabix on the command line on an all_vars.gz file within the cache should test if colocated variants are being found correctly by VEP.

It looks as if something unusual has happened with your index files. Can you please run

_ls -l ~/.vep/homo_sapiens_refseq/98_GRCh37/22/all_vars*_

and let me know the output?

If these files look unusual, then redownloading the cache file from ftp://ftp.ensembl.org/pub/release-98/variation/indexed_vep_cache/ may resolve your issue.

Kind Regards,
Andrew

**Comment by LemuelRacacho** [comment]
Thank you. Here is the output from the run:

-rw-r--r-- 1 lracacho lracacho 111959524 Aug 27 13:31 /home/lracacho/.vep/homo_sapiens_refseq/98_GRCh37/22/all_vars.gz
-rw-r--r-- 1 lracacho lracacho     24633 Aug 27 13:31 /home/lracacho/.vep/homo_sapiens_refseq/98_GRCh37/22/all_vars.gz.csi

**Comment by aparton** [comment]
Hi,

Thanks for this. These files look normal, suggesting an issue with tabix itself.

Next step in diagnosing your issue, could you please run:

_tabix --version_

_which tabix_

And let me know the output of both lines?

Kind Regards,
Andrew

**Comment by LemuelRacacho** [comment]
OUTPUT 1: "tabix --version"
tabix: invalid option -- '-'
tabix: invalid option -- 'v'
Program: tabix (TAB-delimited file InderXer)
Version: 0.2.5 (r1005)
Usage:   tabix <in.tab.bgz> [region1 [region2 [...]]]
Options: -p STR     preset: gff, bed, sam, vcf, psltbl [gff]
         -s INT     sequence name column [1]
         -b INT     start column [4]
         -e INT     end column; can be identical to '-b' [5]
         -S INT     skip first INT lines [0]
         -c CHAR    symbol for comment/meta lines [#]
         -r FILE    replace the header with the content of FILE [null]
         -B         region1 is a BED file (entire file will be read)
         -0         zero-based coordinate
         -h         print also the header lines
         -H         print only the header lines
         -l         list chromosome names
         -f         force to overwrite the index

OUTPUT 2: "which tabix"
/usr/bin/tabix

**Comment by aparton** [comment]
Hi,

Thanks for this, that seems to be the problem. There’s an older version of tabix on your machine that doesn’t recognise the index files used within the cache file.

Updating this version of tabix should hopefully resolve your issue.

Kind Regards,
Andrew

**Comment by LemuelRacacho** [comment]
Hi Andrew, thank you! I noticed that tabix is also located at ~/ensembl-vep/htslib/ which was created during recent version 98 install.

**Comment by LemuelRacacho** [comment]
I found that downloading the indexed file independent of INSTALL.pl worked for me. Thank you.

**Comment by aparton** [comment]
Hi,

Excellent, I'm glad that you were able to resolve your issue.

Kind Regards,
Andrew
