### ISSUE TITLE
9th column of GTF file

### ISSUE THREAD

**Issue by hadjie01** [Ensembl/ensembl-vep#638]
Hello,

I am trying to run VEP with my custom GTF file. Currently, only gene_id and transcript_id are included in the 9th column of my GTF file. Do I need to include more features? are exon number, exon id and biotypes mandatory?

Thanks a lot,
Evi

**Comment by dglemos** [comment]
Hi @hadjie01,
If you don't include the biotype VEP will try to interpret the 2nd column as the biotype. 
[Here](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff) you can read about the format expectations.

**Comment by hadjie01** [comment]
Hi Diana,

Thanks a lot for the fast response!

Here is an example of my gtf file:
chr12   PacBio  transcript      14522   31411   .       -       .       gene_id "ENSG00000226210.3"; transcript_id "PB.8092.4";
chr12   PacBio  exon    14522   15153   .       -       .       gene_id "ENSG00000226210.3"; transcript_id "PB.8092.4";
chr12   PacBio  exon    15913   16065   .       -       .       gene_id "ENSG00000226210.3"; transcript_id "PB.8092.4";

and here are the warnings that I get:

WARNING: Parent entries with the following IDs were not found or skipped due to invalid types: ENSG00000236423.6, ENSG00000142611.17, ENSG00000233304.7, ENSG00000177133.11, ENSG00000227372.12, ENSG00000198912.11, ENSG00000130764.10, ENSG00000158109.15, ENSG00000116198.13, ENSG00000272235.1, ENSG00000116213.16
WARNING: Parent entries with the following IDs were not found or skipped due to invalid types: ENSG00000214114.9, ENSG00000174574.16, ENSG00000185668.7, novelGene_775, ENSG00000183520.12, ENSG00000228436.3, ENSG00000224592.5, ENSG00000116954.8, ENSG00000183386.10, ENSG00000158315.11, ENSG00000274944.4
WARNING: Parent entries with the following IDs were not found or skipped due to invalid types: ENSG00000198162.12, ENSG00000196505.11, ENSG00000271427.1, ENSG00000065183.16, ENSG00000116830.12, ENSG00000134253.10

Is it because I am missing the biotypes?
All of my variants are classified as intergenic:
chr1_237323773_C/A      chr1:237323773  A       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
chr1_244659908_G/C      chr1:244659908  C       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER
chr1_28510353_T/C       chr1:28510353   C       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER

Best,
Evi

**Comment by dglemos** [comment]
VEP is building the annotations from the GFT file using the different IDs (gene -> transcript -> exon/CDS -> ...). 
The warning means that those gene IDs are missing from your GTF file and you have annotations referring to these genes (gene_id attribute) in their 9th column. 

You should have something like this: 
`chr12 PacBio gene _start end_ . - . gene_id _"A"_; transcript_id _"B"_;`
`chr12 PacBio transcript _start end_ . - . gene_id _"A"_; transcript_id _"B"_;`
`chr12 PacBio exon _start end_ . - . gene_id _"A"_; transcript_id _"B"_;` exon_number _x_

**Comment by dglemos** [comment]
I am closing this issue, but if you have any more questions please feel free to reopen it.

Best regards,
Diana

**Comment by hadjie01** [comment]
Hello Diana,

I noticed that the ExAC plugin available for GRCh38? If not, could it be possible to make it available?
I appreciate your help!

Best Regards,
Evi

**Comment by dglemos** [comment]
Hello @hadjie01,
The ExAC plugin is only available for GRCh37, we don't have plans to support it for GRCh38. 
We recommend to users that they use gnomAD frequency data as built into our cache files, as an alternative to ExAC, or to retrieve the frequency data using custom annotation. You can read more here: https://www.ensembl.org/info/docs/tools/vep/script/vep_example.html#gnomad

Best regards,
Diana

**Comment by hadjie01** [comment]
Hello Diana,

I would like to use the gnomADc frequency data so I downloaded the gnomAD data using the commands provided in gnomADc.pm:

> release="3.0"
> genomes="https://storage.googleapis.com/gnomad-public/release/${release}/coverage/genomes"
> wget -x "${genomes}"/gnomad.genomes.r${release}.chr{{1..22},X}.coverage.txt.gz
> for i in "${genomes#*//}"/gnomad.genomes.r${release}.chr{{1..22},X}.coverage.txt.gz; do
>   tabix -s 1 -b 2 -e 2 "${i}"
> done

However, I am getting an error with this command and not sure how to proceed .. could you please assist me on this matter? I am pasting the issue below.

Downloaded: 23 files, 1.3M in 0.4s (3.02 MB/s)
[tabix] was bgzip used to compress this file? console.cloud.google.com/storage/browser/gnomad-public/release/3.0/coverage/genomes/gnomad.genomes.r3.0.chr1.coverage.txt.gz
[tabix] was bgzip used to compress this file? console.cloud.google.com/storage/browser/gnomad-public/release/3.0/coverage/genomes/gnomad.genomes.r3.0.chr2.coverage.txt.gz
[tabix] was bgzip used to compress this file? console.cloud.google.com/storage/browser/gnomad-public/release/3.0/coverage/genomes/gnomad.genomes.r3.0.chr3.coverage.txt.gz

Thanks a lot!!

Evi

**Comment by dglemos** [comment]
Hi,
The gnomADc plugin retrieves data from coverage files which is probably not what you want to use. The coverage files are TXT format, running tabix on these files generates the error you're seeing. 

To get frequency data from gnomAD you need to follow the instructions from [this page] https://www.ensembl.org/info/docs/tools/vep/script/vep_example.html#gnomad). On this page, you can find the link to download the gnomAD files: `ftp://ftp.ensembl.org/pub/data_files/homo_sapiens/GRCh38/variation_genotype/gnomad/r2.1/genomes/`

**Comment by hadjie01** [comment]
Hello Diana,

Thanks for the response!

According to the link below, I’ll need to use the following command to get gnomADc frequency data:
./vep -i examples/homo_sapiens_GRCh38.vcf --cache \
--custom gnomad.genomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF_AFR,AF_AMR,AF_ASJ,AF_EAS,AF_FIN,AF_NFE,AF_OTH

But I am already using a --custom gtf annotation. Can I still use the above command?

Best,
Evi

**Comment by dglemos** [comment]
You can use the two commands at the same time. You just add the `--custom gnomad.genomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF_AFR,AF_AMR,AF_ASJ,AF_EAS,AF_FIN,AF_NFE,AF_OTH` to your previous command.

**Comment by hadjie01** [comment]
Hello Diana,

Thank you!

I have a couple of more questions. Can I use gnomAD v3.0 instead of v2.1? In that case I would just need to download the ‘All Chromosomes VCF’ https://gnomad.broadinstitute.org/downloads, right?

In my output file I only get ‘gnomADg=rs904983435;gnomADg_FILTER=PASS’, not frequency values.

Best,
Evi

**Comment by dglemos** [comment]
You can use v3.0 downloaded from https://gnomad.broadinstitute.org/downloads for all chromosomes. 

> In my output file I only get ‘gnomADg=rs904983435;gnomADg_FILTER=PASS’, not frequency values.
When using the file you need to check if the header names match the names in your command, for instance, if in the file header it's `##INFO=<ID=**AC_afr**` your command has to be `gnomad.genomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz,gnomADg,vcf,exact,0,**AC_afr**` an so on for the other columns.

**Comment by hadjie01** [comment]
Hello Diana,

Thanks for your help!

I have one more question for you (hopefully this will be the last one) ..
I am using GTF annotation which means I have novel transcripts in my dataset so If I use ExAC pLI I will only get precalculated pLI scores per gene but I want to be able to take into account the effect of the novel transcripts, right?

If this is the case then I thought it might be better to use LOFTEE & LOEUF instead. Is this something that I can do with VEP/97?
If yes, LOFTEE&LOEUF will recalculate the scores based on my transcripts, right? If I understood correctly, these tools are not using precalculated scores.

Also, is this the case with Condel? I won’t get a score for my novel transcripts because the SHIFT and PolyPhen scores are precalculated?

Thanks again!!
Evi

**Comment by hadjie01** [comment]
Hello Diana,

I am just following up on my questions below.

Are LOFTEE & LOEUF available with VEP/97? If yes, which files I should be using?
And what would be the best way to predict pathogenicity for novel transcripts?

Thanks a lot,
Evi

From: Hadjimichael, Evi
Sent: Thursday, February 27, 2020 12:45 PM
To: 'Ensembl/ensembl-vep' <reply@reply.github.com>; Ensembl/ensembl-vep <ensembl-vep@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Ensembl/ensembl-vep] 9th column of GTF file (#638)

Hello Diana,

Thanks for your help!

I have one more question for you (hopefully this will be the last one) ..
I am using GTF annotation which means I have novel transcripts in my dataset so If I use ExAC pLI I will only get precalculated pLI scores per gene but I want to be able to take into account the effect of the novel transcripts, right?

If this is the case then I thought it might be better to use LOFTEE & LOEUF instead. Is this something that I can do with VEP/97?
If yes, LOFTEE&LOEUF will recalculate the scores based on my transcripts, right? If I understood correctly, these tools are not using precalculated scores.

Also, is this the case with Condel? I won’t get a score for my novel transcripts because the SHIFT and PolyPhen scores are precalculated?

Thanks again!!
Evi

**Comment by dglemos** [comment]
Hi, 
Sorry for taking so long to reply. 
If you're using GTF annotation with novel transcripts with plugins that use pre-calculated scores you will get scores for the transcripts used by the tool and not your transcripts. This will happen with Sift, PolyPhen and as you said Condel integrates the output of these tools and calculates the weighted average of these scores which means these scores will not consider your custom annotation. 
[Loftee](https://github.com/konradjk/loftee) looks at a given variant-transcript pair so you should get scores based on your novel transcripts. We are not looking after the Loftee plugin. If you have any questions related to the plugin you should ask here: https://github.com/konradjk/loftee/issues

**Comment by hadjie01** [comment]
Hello Diana,

Thanks a lot for the response!
Is there any other tool/plugin that I could use to calculate pathogenicity for my novel transcripts?

Thanks again,
Evi

**Comment by dglemos** [comment]
If you want to consider your novel transcripts you should avoid all the plugins that use pre-calculated scores from files. Most of our plugins use these pre-calculated files but you can check the tools used to generate these files and try to use them for your use case. One example is [SpliceAI](https://github.com/Ensembl/VEP_plugins/blob/release/99/SpliceAI.pm) plugin. The plugin uses a file that contains pre-calculated scores, but you could run the [SpliceAI tool](https://github.com/Illumina/SpliceAI) for your gene annotation file (with the novel transcripts) and attach those scores to your vep annotation.

**Comment by dglemos** [comment]
I'm going to close this issue. Feel free to open a new issue if you have more questions.
