### ISSUE TITLE
Codon does not fit cDNA sequence

### ISSUE THREAD

**Issue by gilhornung** [Ensembl/ensembl-vep#64]
Hi,
I am running VEP from ensembl-tools-release-85, with --offline (so the version stays at 85_GRCh38).
I have a mutation in 10:5454288-5454289 GA/AT.

Based on VEP the transcript ENST00000355029 is mutated at cDNA position 934-935.
VEP outputs a codon change agGAgt/agATgt but when I look at the sequence around this position I get AGAGGT.

The files I have used (vcf and vep outpout) can be found at:
http://incpm-2.weizmann.ac.il/bioinfo/gil/mupexi_bug/

All the best
Gil Hornung

**Comment by willmclaren** [comment]
Your input reference allele is used by VEP; it is up to you to ensure that it matches the reference genome.

VEP can check for you if you use `--check_ref`. In release/89 of VEP you may also use `--use_transcript_ref`; this will replace your input reference allele with the correct one looked up from the transcript sequence.
