### ISSUE TITLE
v98.3 missing polyphen2 --humdiv option

### ISSUE THREAD

**Issue by jmo616** [Ensembl/ensembl-vep#640]
Hello,

I am using ensembl-vep release 98.3, and it does not seem to export any polyphen predictions when using the --humdiv option (although polyphen predictions for the humvar models using --polyphen [p|s|b] do export properly). All other annotations from the cache seem to export properly, so it seems to be specific to the --humdiv option.

I am using the 'homo_sapiens_GRCh38.vcf' provided in the 'examples' subdirectory created with the INSTALL.pl script. Is there something that I need to change in my commands in order to access both humdiv and humvar polyphen predictions? Thank you!

### System
- VEP version: 98.3 
- VEP Cache version: 98
- Perl version: v5.28.1
- OS: Ubuntu
- tabix installed: yes

### Full VEP command line
```
./vep --cache --dir_cache .vep/ -i examples/homo_sapiens_GRCh38.vcf --humdiv -o output_humdiv.txt
./vep --cache --dir_cache .vep/ -i examples/homo_sapiens_GRCh38.vcf --polyphen b -o output_humvar.txt   # this command works
```

### Full error message
No warnings are returned

### Data files (attached)
They include:
- The input file (I renamed it to ".txt" in order to upload it here)
- The output file

[output_humdiv.txt](https://github.com/Ensembl/ensembl-vep/files/3855147/output_humdiv.txt)
[homo_sapiens_GRCh38.vcf.txt](https://github.com/Ensembl/ensembl-vep/files/3855148/homo_sapiens_GRCh38.vcf.txt)

**Comment by aparton** [comment]
Hi,

Thank you for your query. To obtain humdiv annotations, you also need the —polyphen flag to specify whether you want the prediction term and/or the score. So for example:

perl vep -i examples/homo_sapiens_GRCh38.vcf --database --polyphen s -o nohumdiv.txt 
perl vep -i examples/homo_sapiens_GRCh38.vcf --database --polyphen s --humdiv -o humdiv.txt 

should provide you different polyphen scores.

Kind Regards,
Andrew

**Comment by jmo616** [comment]
Hello,

Thanks for the reply--I tried out the suggested changes to the commands as shown below, and still only seem to get one polyphen score (regardless of whether I use the ensembl database or the cache files). My output files are attached, and please let me know if you have any questions.

Thanks!

./vep --cache --dir_cache .vep/ -i examples/homo_sapiens_GRCh38.vcf --polyphen s --humdiv -o output_humdiv_cache.txt
./vep -i examples/homo_sapiens_GRCh38.vcf --database --polyphen s --humdiv -o output_humdiv_db.txt

[output_humdiv_cache.txt](https://github.com/Ensembl/ensembl-vep/files/3859923/output_humdiv_cache.txt)
[output_humdiv_db.txt](https://github.com/Ensembl/ensembl-vep/files/3859924/output_humdiv_db.txt)

**Comment by aparton** [comment]
Hi,

That's correct - whether you use the cache or the database to obtain your humdiv predictions, VEP will use the PolyPhen output field to display these annotations. VEP wont provide both the humVar and the humDiv score at the same time.

Kind Regards,
Andrew

**Comment by jmo616** [comment]
Hi Andrew,

Thanks very much for clarifying--these changes worked as intended.
