### ISSUE TITLE
Hi, I can't understand this phenomenon.

### ISSUE THREAD

**Issue by stellaoh** [Ensembl/ensembl-vep#642]
Dear VEP team. 

Hi, I have a question. 

![image](https://user-images.githubusercontent.com/33537478/69106431-a6abfd80-0ab1-11ea-868b-781c8d8780e9.png)

In this figure, white highlighted "1.47&1.47" is FATHMM_score. 

I can't understand why the score was separated with "&".

The header of this vcf file is shown below. 

"##FATHMM_score=(from dbNSFP) FATHMM default score (weighted for human inherited-disease mutations with Disease Ontology) (FATHMMori). Scores range from -16.13 to 10.64. The smaller the score the more likely the SNP has damaging effect. Multiple scores separated by ";", corresponding to Ensembl_proteinid." 

dbNSFP reference was shown in below. 
![image](https://user-images.githubusercontent.com/33537478/69108696-d27eb180-0ab8-11ea-868d-b3ed19ccb0c3.png)

In this figure, white highlighted "1.47;1.47" is FATHMM_score corresponding with "ENSP00000357739;ENSP00000357740". 

In vep, I used only canonical transcript (ENSP00000357740).  

I want to emit only dbNSFP scores of canonical transcript (or corresponding transcript) in my vep vcf file.

**Comment by helensch** [comment]
Hi

The scores are separated by & in VCF format as
- the dbNSFP plugin replaces occurrences of ';' with ','
https://github.com/Ensembl/VEP_plugins/blob/release/98/dbNSFP.pm

- for VEP output commas in fields are replaced with ampersands (&) to preserve VCF format. 
https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#vcfout

The field description in VCF is taken from the dbNSFP file as indicated by the (from dbNSP) and gives ';' as the separator. 

If other output formats e.g. tab,  the files are separated by commas

The canonical option adds a flag indicating if the transcript is the canonical transcript for the gene, it does not filter
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_canonical

The VEP option --transcript_filter or vep_filter can be used to filter transcripts
https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html

Please et me know if you have any further questions and if so, please could you provide
- the full VEP command line used
- the version of VEP
- the release version of dbNSFP used and the assembly

Helen

**Comment by helensch** [comment]
Hi 

I am going to close this issue now. If you have any more questions, please feel free to reopen it or open a new issue.

Helen
