### ISSUE TITLE
RefSeq and ensemble Gencode_basic annotation

### ISSUE THREAD

**Issue by leonschuetz** [Ensembl/ensembl-vep#643]
## Describe the issue
I would like to annotate a VCF file with RefSeq transcripts and ensemble transcripts which belong to the gencode basic data set. Currently I use the merged data set but if I use the --gencode_basic I'm missing the RefSeq transcripts. Is there any way to achieve this with VEP? 
I also didn't find any optional field which indicates if a annotated transcript belongs to gencode basic which would allow me to filter the results afterwards.

Thank You,
Leon

**Comment by aparton** [comment]
Hi,

Thank you for this query. As you've noticed, the --gencode_basic flag works as a filter to remove all non-gencode-basic transcripts from VEP output, and as such it's also removing all RefSeq transcripts.

Unfortunately, there is no easy way to add this information on as an optional field within VEP output. Your easiest two options to get the annotations you're looking for quickly are:

1) Run VEP twice, once with the --gencode_basic flag and once with the --refseq flag, and merge your results together

2) You could write a plugin to add this status as an optional field. You can read more about our plugins, and how to write your own here: https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html

Kind Regards,
Andrew

**Comment by leonschuetz** [comment]
Ok, then I will have to run it twice. Thank you for your response.

Best Regards,
Leon

**Comment by sigven** [comment]
Hi,

I have a somewhat related question regarding the GENCODE basic set. I have assumed that transcripts used by VEP for annotation with the `--gencode_basic` option were restricted to GENCODE transcripts annotated with the `basic` tag.  Meaning for the grch37 version of VEP, which uses GENCODE v19, I thought that transcripts were limited to those listed with `tag "basic"` in the [corresponding GENCODE GTF file](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.annotation.gtf.gz). However, looking at the results from my variant annotations (grch37 / GENCODE v19 / VEP v104), I frequently see transcripts attributed with other GENCODE tags in the output, e.g. `non_canonical_conserved`, `non_canonical_U12`, `alternative_3_UTR` etc. 

From these observations, I am therefore curious as to what the [_GENCODE basic set_](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_gencode_basic) constitutes in the context of VEP annotation and/or what the `--gencode_basic` option is restricting the output towards? Having a better understanding of this would make it easier to decide whether the `--gencode_basic` option might be suitable for our purposes or not.

kind regards,
Sigve

**Comment by jamie-m-a** [comment]
Hi @sigven,

That's also my understanding of how that flag should function. Would you mind providing the command you ran along with the input data and output data, specifically those variants on transcripts that aren't tagged as basic.

Cheers,
Jamie.

The intended functionality is as you'd expect, would it be possible for you to pro

**Comment by sigven** [comment]
Thanks for the swift response, @jamie-m-a. I just realized my internal check was not fully accurate (I failed to recognize that there are frequently multiple GENCODE tags pr. transcript, so I missed a number of _basic_ tag annotations). 

In my [current test result (includes a minor VCF, and output VEP results)](https://www.dropbox.com/sh/atl9kpyz8qe8o1q/AACSIOC7VjajYRPUPB5F08faa?dl=0), which I ran [online](http://grch37.ensembl.org/Homo_sapiens/Tools/VEP) using the GENCODE basic option, I only see one output entry (a pseudogene) that I cannot attribute to the basic set considering annotations in the [GENCODE gtf file](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.annotation.gtf.gz); however I see that this transcript is listed as a GENCODE basic member according to its [entry on the Ensembl website](https://grch37.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000267736;r=19:1203208-1203820;t=ENST00000591146), meaning things should be working as it should on your side, but I fail to see why this is also included as a GENCODE basic member?

**Comment by jamie-m-a** [comment]
Hi @sigven 

Thanks for providing the data, I'm glad you managed to clear up part of the issue. With regard to the presence of a pseudogene in the gencode basic set, I believe this is as a result of the methodology used in generating the set, there's a [full description here](https://www.ensembl.org/info/genome/genebuild/transcript_quality_tags.html#basic).

The pertinent part being step 4:

`If, after step (3), we've got an empty basket and no transcripts in the gene are tagged as 'Basic', we look for pseudogene transcripts and tag all the pseudogene transcripts that we find.`

Cheers,
Jamie.

**Comment by sigven** [comment]
Ah, thanks for clearing that up! Then it all makes sense. I have not come across this documentation site before.

Thanks for very helpful feedback, and close the issue at your convenience.

regards,
Sigve

**Comment by jamie-m-a** [comment]
Glad I could help, I'll close this ticket down.

Cheers,
Jamie.
