### ISSUE TITLE
vep no errors displayed, blank -o file created

### ISSUE THREAD

**Issue by cccnrc** [Ensembl/ensembl-vep#647]
I am working with several plugin in VEP v98 and I noticed that if I use commands with a big number of plugins VEP does not output any ERROR/WARNING but a totally blank file is created.

Command:
`
time ./vep 
     -i /home/enrico/vep/ensembl-vep/examples/homo_sapiens_GRCh37.vcf 
     --cache --dir_cache /media/enrico/vep_disk/vep_files/caches --merged --use_given_ref 
     --fasta /media/enrico/vep_disk/vep_files/fasta/GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz 
     --dir_plugins /media/enrico/vep_disk/vep_files/vep_plugins 
     --assembly GRCh37 
     --offline 
     --hgvs 
     --no_stats 
     --symbol 
     --json 
     --pick 
     --no_intergenic 
     --gencode_basic 
     --sift b 
     --polyphen b 
     --plugin SingleLetterAA 
     --plugin REVEL,/media/enrico/vep_disk/vep_files/plugin_databases/revel/new_tabbed_revel.tsv.gz 
     --plugin GeneSplicer,/media/enrico/vep_disk/vep_files/plugin_databases/genesplicer/GeneSplicer/bin/linux/genesplicer,/media/enrico/vep_disk/vep_files/plugin_databases/genesplicer/GeneSplicer/human 
     --plugin ExAC,/media/enrico/vep_disk/vep_files/plugin_databases/exac/ExAC.r0.3.1.sites.vep.vcf.gz,AF 
     --plugin ExACpLI,/media/enrico/vep_disk/vep_files/plugin_databases/exac_pli/ExACpLI_values.txt 
     --plugin dbscSNV,/media/enrico/vep_disk/vep_files/plugin_databases/dbscSNV/dbscSNV1.1_GRCh37.txt.gz 
     --plugin gnomADc,/media/enrico/vep_disk/vep_files/plugin_databases/coverage/exomes 
     --plugin gnomADc,/media/enrico/vep_disk/vep_files/plugin_databases/coverage/genomes 
     --plugin Mastermind,/media/enrico/vep_disk/vep_files/plugin_databases/mastermind/mastermind_cited_variants_reference-2019.09.27-grch37.vcf.gz 
     --plugin CADD,/media/enrico/vep_disk/vep_files/plugin_databases/cadd/hg19/whole_genome_SNVs.tsv.gz,/media/enrico/vep_disk/vep_files/plugin_databases/cadd/hg19/InDels.tsv.gz 
     --plugin StructuralVariantOverlap,file=/media/enrico/vep_disk/vep_files/plugin_databases/gnomad/sv/gnomad_v2_sv.sites.vcf.gz 
     --plugin GO 
     --plugin satMutMPRA,file=/media/enrico/vep_disk/vep_files/plugin_databases/satMutMPRA/satMutMPRA_GRCh37_ALL.gz 
     --plugin Phenotypes,file=/media/enrico/vep_disk/vep_files/plugin_databases/vep_phenotypes/Phenotypes.pm_homo_sapiens_98_GRCh37.gvf.gz 
     --plugin G2P,file=/media/enrico/vep_disk/vep_files/plugin_databases/G2P/DDG2P_24_11_2019.csv 
     --plugin dbNSFP,/media/enrico/vep_disk/vep_files/plugin_databases/dbNSFP/dbNSFP4.0a.gz,LRT_score,LRT_pred,GERP++_RS 
     --custom /media/enrico/vep_disk/vep_files/manual_annotations/clinvar/clinvar_20191118.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNREVSTAT,CLNDN 
     --force_overwrite 
     -o prove/outputs/prova0.txt
`

I have searched around but found nothing...any clue?

Thank you very much in advance

**Comment by cccnrc** [comment]
sorry to bother, any news?

**Comment by ima23** [comment]
Hi @cccnrc,

I'm looking into the issue. Can you please share 1 or 2 variants as input example?

Thanks,
Irina

**Comment by ima23** [comment]
@cccnrc : just noticed you are using the example input file. At first glance I can't see why you would get an empty output. Do you have more information at what point/ after how many plugins it stops working? 
Thanks.

**Comment by cccnrc** [comment]
It seems quite casual, as example:

`
time ./vep -v 
     -i /home/enrico/vep/ensembl-vep/examples/homo_sapiens_GRCh37.vcf --format vcf 
     --cache --dir_cache /media/enrico/vep_disk/vep_files/caches --merged --use_given_ref 
     --fasta /media/enrico/vep_disk/vep_files/fasta/GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz 
     --dir_plugins /media/enrico/vep_disk/vep_files/vep_plugins 
     --assembly GRCh37 
     --offline 
     --hgvs 
     --no_stats 
     --symbol 
     --vcf 
     --minimal 
     --allele_number 
     --pick 
     --no_intergenic 
     --gencode_basic 
     --sift b 
     --polyphen b 
     --plugin SingleLetterAA 
     --plugin REVEL,/media/enrico/vep_disk/vep_files/plugin_databases/revel/new_tabbed_revel.tsv.gz 
     --plugin GeneSplicer,/media/enrico/vep_disk/vep_files/plugin_databases/genesplicer/GeneSplicer/bin/linux/genesplicer,/media/enrico/vep_disk/vep_files/plugin_databases/genesplicer/GeneSplicer/human 
     --plugin ExAC,/media/enrico/vep_disk/vep_files/plugin_databases/exac/ExAC.r0.3.1.sites.vep.vcf.gz,AF 
     --plugin ExACpLI,/media/enrico/vep_disk/vep_files/plugin_databases/exac_pli/ExACpLI_values.txt 
     --plugin dbscSNV,/media/enrico/vep_disk/vep_files/plugin_databases/dbscSNV/dbscSNV1.1_GRCh37.txt.gz 
     --plugin gnomADc,/media/enrico/vep_disk/vep_files/plugin_databases/coverage/exomes 
     --plugin gnomADc,/media/enrico/vep_disk/vep_files/plugin_databases/coverage/genomes 
     --plugin Mastermind,/media/enrico/vep_disk/vep_files/plugin_databases/mastermind/mastermind_cited_variants_reference-2019.09.27-grch37.vcf.gz 
     --plugin CADD,/media/enrico/vep_disk/vep_files/plugin_databases/cadd/hg19/whole_genome_SNVs.tsv.gz,/media/enrico/vep_disk/vep_files/plugin_databases/cadd/hg19/InDels.tsv.gz 
     --plugin StructuralVariantOverlap,file=/media/enrico/vep_disk/vep_files/plugin_databases/gnomad/sv/gnomad_v2_sv.sites.vcf.gz 
     --plugin GO 
     --plugin Phenotypes,file=/media/enrico/vep_disk/vep_files/plugin_databases/vep_phenotypes/Phenotypes.pm_homo_sapiens_98_GRCh37.gvf.gz 
     --plugin dbNSFP,/media/enrico/vep_disk/vep_files/plugin_databases/dbNSFP/dbNSFP4.0a.gz,LRT_score,LRT_pred,GERP++_RS 
     --plugin G2P,file=/media/enrico/vep_disk/vep_files/plugin_databases/G2P/DDG2P_24_11_2019.csv,log_dir=prove/outputs,txt_report=prove/outputs/g2p_report.txt,html_report=prove/outputs/g2p_report.html 
     --custom /media/enrico/vep_disk/vep_files/manual_annotations/clinvar/clinvar_20191118.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNREVSTAT,CLNDN 
     --force_overwrite 
     -o prove/outputs/prova0.txt
`

did not work. The `-v verbose` output just stop to:

`
Will only load v98 databases
Species 'homo_sapiens' loaded from database 'homo_sapiens_core_98_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_cdna_98_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_otherfeatures_98_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_rnaseq_98_38'
homo_sapiens_variation_98_38 loaded
homo_sapiens_funcgen_98_38 loaded
No ancestral database found
No ontology database found
No taxonomy database found
Use of uninitialized value $ensembl_metadata_db in concatenation (.) or string at /home/enrico/vep/ensembl-vep/Bio/EnsEMBL/Registry.pm line 2363.
ensembl_metadata API not found - ignoring 
No production database or adaptor found
`

and say nothing else. Just removing `Phenotypes`, `dbNSFP`, `G2P` works and `verbose` print out the same just with a lot of other lines saying:
`
Argument "" isn't numeric in numeric eq (==) at /home/enrico/vep/ensembl-vep/modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm line 373.
`

but other orders work with also one plugin less.

Any idea to what could it be?

**Comment by at7** [comment]
Thank you for the extra information. The G2P plugin requires genotype data as input which the example file doesn't have. The G2P plugin sets the --individual flag and filters out everything without genotype data in the output file. You therefore need to remove the G2P plugin from your options.  There could also be a problem in recognising the input format of the example file. Adding --format vcf should help with that.

**Comment by cccnrc** [comment]
Yes it seems to work with the other plugins but `G2P`. It would be nice to have an advise just in case to know the analysis failed. I'll try other combinations, thank you very much for the moment
