### ISSUE TITLE
Pfam release

### ISSUE THREAD

**Issue by leonschuetz** [Ensembl/ensembl-vep#648]
## Describe the issue
Hello,
I am using VEP with the --domains parameter and found out that some of the Pfam IDs are outdated. Is there any way to find out which Pfam release is used in VEP 96? I checked the website and did not find it. 

Best Regards,
Leon

### System
- VEP version: 96.3
- VEP Cache version: 96
- OS: ubuntu

**Comment by ima23** [comment]
Hi @leonschuetz,

VEP Cache 96 is based on Ensembl release 96 which had Pfam 31.0 imported.

We recommend using the most recent release if possible to ensure the latest data is used, for example the latest Pfam release 32.0 was available in Ensembl release 97 and is also available in the latest release 98.

Kind regards,
Irina

**Comment by leonschuetz** [comment]
Thank You
