### ISSUE TITLE
filter_vep return empty files if input VCF has only header

### ISSUE THREAD

**Issue by fgvieira** [Ensembl/ensembl-vep#649]
## Describe the issue
When VCF has no variants (only headers), `filter_vep` returns an empty file.
I think if there are no variants, `filter_vep` should just print out the header anyway...

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 98.3 
- VEP Cache version: 98.3
- Perl version: 5.24
- OS: CentOS
- tabix installed ? YES

### Full VEP command line
```
filter_vep --input_file INPUT.vcf --filter "AF < 0.5"
```

### Full error message
No error message, just outputs an empty file

**Comment by ima23** [comment]
Hi @fgvieira,

Indeed `filter_vep` will not return anything if the input file contains only the header.
The script will however return the header if the input file contains at least one empty line after the header. Is this of use in your case?

Kind regards,
Irina

**Comment by fgvieira** [comment]
Well, not really since I cannot control that.
The input to `filter_vep` comes from other programs and, sometimes, there are not variants.

Would it be possible to have `filter_vep` to always print out the header?

**Comment by ima23** [comment]
Hi @fgvieira, 

I see, that makes sense. We will look into updating `filter_vep` to print the header out and let you know when the change is in.

Thanks,
Irina

**Comment by ima23** [comment]
Hi @fgvieira,

Good news. We updated the `filter_vep` script to print the header in the mentioned empty case. The change is on `release/99` branch.

Kind regards,
Irina

**Comment by fgvieira** [comment]
Great!
thanks,
