### ISSUE TITLE
Bug with --flag_pick_allele_gene

### ISSUE THREAD

**Issue by christianbioinf** [Ensembl/ensembl-vep#65]
I have observed an unexpected behaviour with the option `--flag_pick_allele_gene`. Previously, I have only used the option `--flag_pick_allele` which works fine and reports a separate `PICK` entry which is only set once per allele. Now, I have changed to the `--flag_pick_allele_gene` option but the complete `PICK` entry is not present (not even in the header). I have tried to use `--pick_allele_gene` which works fine but I would like to the other entries also present in the file.

I have assembled a small test dataset ([test.vcf.zip](https://github.com/Ensembl/ensembl-vep/files/1179311/test.vcf.zip)), just with one SNP (w/ one alternative allele) which overlaps with two genes BRCA1 and NBR2, for each I would like to have one `PICK` entry set.
```
perl vep_89.3/vep -i test.vcf --offline --cache --dir hg19/vep --fasta hg19/hg19.fa --format vcf --tab --flag_pick_allele_gene -o test_out.vcf --species homo_sapiens --refseq --force_overwrite --symbol
```
This does not report a column named `PICK` whereas the analogous command with `--flag_pick_allele` does report it.

Thanks a lot for your effort in advance.

**Comment by willmclaren** [comment]
Already fixed by https://github.com/Ensembl/ensembl-vep/pull/63
