### ISSUE TITLE
Performance tweaking: cache vs db

### ISSUE THREAD

**Issue by matthdsm** [Ensembl/ensembl-vep#652]
Hi,

Quick question wrt to performance tweaking.
Which cache option should provide the most performance gains? 
1. Using a tabix index (converted) cache on a fast local disk
2. Use a local version of the db

Or am I getting something wrong and do both add different data?

Thanks
M

### System
- VEP version: 95, or whatever
- VEP Cache version: 95, or whatever
- Perl version: 5.26
- OS: Ubuntu
- tabix installed ? True

**Comment by aparton** [comment]
Hi Matthias,

Thanks for your query. We recommend using a cache file to optimise VEP performance.

A list of additional potential optimisations to maximise speed can be found here: https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#faster <https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#faster>

Kind Regards,
Andrew

**Comment by matthdsm** [comment]
Hi Andrew, 

Thanks for the info! So I assume the db provides no extra value when using a local cache?

Cheers
M

**Comment by aparton** [comment]
Hi,

Most of the time, that’s correct, however the cache file does have some limitations. The cache file is not suitable when using rsIDs or HGVS format as input, and overlapping structural variants are not included in the cache files. You can find more information on these limitations here: https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#limitations <https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#limitations>

Kind Regards,
Andrew
