### ISSUE TITLE
Add identifier to tabular input of structural variants

### ISSUE THREAD

**Issue by cruckert** [Ensembl/ensembl-vep#653]
As far as I know there is currently no possibility to add variant identifiers when inputting structural variants in tabular input format, as it is possible for small variants. When using vcf as input format the ID column is correctly taken over to the output (vcf as well as tabular).

This would be very helpful.

**Comment by at7** [comment]
Hello,
thank you for reporting this. This will be fixed for our next release which is planned for either later this year or very early next year.
Best wishes,
Anja

**Comment by at7** [comment]
Hi @cruckert,

could you please share some of your input please? I'm testing with the following input:
1 160283 471362 DUP 1 ID1
1 1385015 1387562 DEL 1 ID2

And the variant IDs are added to the output file. First row of my output:
#Uploaded_variation Location  Allele  Gene  Feature Feature_type  Consequence cDNA_position CDS_position  Protein_position  Amino_acids Codons  Existing_variation  Extra
**ID1** 1:160283-471362 duplication ENSG00000222623 ENST00000410691 Transcript  upstream_gene_variant - - - - - - IMPACT=MODIFIER;DISTANCE=2396;STRAND=-1

Thank you,
Anja

**Comment by cruckert** [comment]
This way it works for me too, I only tried the identifiers as fifth column.

Maybe you can improve the example at https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#sv by adding a variant with these two extra columns, just as in the "Default VEP input" section

**Comment by at7** [comment]
We will update the example for our next release.

Best wishes,
Anja
