### ISSUE TITLE
Question w/ HGVS Protein notation

### ISSUE THREAD

**Issue by benjraspl** [Ensembl/ensembl-vep#654]
Hi VEP Team,

I have a question regarding the HGVS protein annotation given by the vep. When detecting a frameshift variant, will the vep always give the newly generated terminal aminoacid AND the predicted distance until termination? Or is it possible for any of the information to be missing? So far I have only been seeing the complete notation w/ new terminal amino acid and distance until termination, but I have to know whether other notations are also possible.
Thanks a lot in advance!

**Comment by aparton** [comment]
Hi,

In general, that's correct, however there are a couple edge cases where the annotations can be slightly different.

1) If an insertion instantly creates a stop codon, then HGVS considers the variant to be a substitution instead:

i.e. _perl vep -id '3 10200392 . T TA' --database --hgvs_ provides **HGVSp=ENSP00000256458.4:p.Cys101Ter**

2) When VEP cannot find a new stop codon within the new reading frame then it will replace the distance with a ?

i.e. _perl vep -id '1 6448798 . GA G' --database --hgvs_  provides **ENSP00000466437.1:p.Glu6ArgfsTer?**

I've had a look through the code and I believe those are the only cases where we consider the HGVS type to be a frameshift that don't fit your categories. 

If you have any more questions, please don't hesitate to ask.

Kind Regards,
Andrew

**Comment by benjraspl** [comment]
Thanks a lot for answer, this is what I needed to know! I do have another question - but regarding another vep function! Do you want me to open a new issue for this?

**Comment by aparton** [comment]
Hi,

Up to you, we'll do our best to answer it either way! If it's related, then it may be suitable here, however if it's unrelated then it may be best to open a new issue.

Kind Regards,
Andrew

**Comment by benjraspl** [comment]
Hi, I just opened a new issue with my question!

Best, Benjamin

**Comment by aparton** [comment]
Hi,

Excellent, I'll take a look. I'll close this issue now.

Kind Regards,
Andrew
