### ISSUE TITLE
MSG: ERROR: Could not write to output file

### ISSUE THREAD

**Issue by PlatonB** [Ensembl/ensembl-vep#655]
Elementary OS 5.1
Docker version 18.09.7, build 2d0083d
ensembl-vep latest fcfda10

`sudo docker run -t -i -v $HOME/vep_data:/opt/vep/.vep:Z ensemblorg/ensembl-vep`
`./vep --cache -e --vcf --force_overwrite --no_stats --dir_cache /opt/vep/.vep/ -i /opt/vep/.vep/input/vep_test_input.txt -o /opt/vep/.vep/output/vep_test_output.vcf`

```
-------------------- EXCEPTION --------------------
MSG: ERROR: Could not write to output file /opt/vep/.vep/output/vep_test_output.vcf

STACK Bio::EnsEMBL::VEP::BaseRunner::get_output_file_handle /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:226
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:196
STACK toplevel ./vep:224
Date (localtime)    = Sun Dec  8 21:36:50 2019
Ensembl API version = 98
---------------------------------------------------
```

**Comment by aparton** [comment]
Hi,

Thank you for reporting this issue. This issue occurs when the VEP output is directed into a folder that doesn't exist. Making the directory '/opt/vep/.vep/output/' and rerunning your query should fix your issue. 

I've had a look at our Docker documentation, and it could be a little clearer regarding the directory structure included within the docker image. I'll take a look at making some improvements to this.

Kind Regards,
Andrew

**Comment by PlatonB** [comment]
There are _/home/platon/vep_data/input/_ and _/home/platon/vep_data/output/_ folders. As far as I understand, `$HOME/vep_data:/opt/vep/.vep:Z` should make _/home/platon/vep_data/output/_ equivalent to _/opt/vep/.vep/output/_.

**Comment by aparton** [comment]
Hi,

Thanks for this. If /opt/vep/.vep/output exists, then I suspect it's a permissions issue that's preventing docker from writing to $HOME/vep_data. Could you please run:

_chmod a+rwx $HOME/vep_data/output_

and try again?

Kind Regards,
Andrew

**Comment by PlatonB** [comment]
Now it works. Thanks!

This is not critical, but I would like to inform you that the output file has a "locked" icon.
![VCF_output_locked](https://user-images.githubusercontent.com/25541767/70611768-c8168a00-1c16-11ea-8bf2-9f8c50d48ed8.png)

**Comment by aparton** [comment]
Hi,

Excellent, I'm glad that it's now working. Thanks for reporting the locked icon, we'll look into it.

I'm going to close this issue now. If you have any more questions, please feel free to reopen it or open a new one.

Kind Regards,
Andrew

**Comment by lamnvcnsh** [comment]
> Hi,
> 
> Thank you for reporting this issue. This issue occurs when the VEP output is directed into a folder that doesn't exist. Making the directory '/opt/vep/.vep/output/' and rerunning your query should fix your issue.
> 
> I've had a look at our Docker documentation, and it could be a little clearer regarding the directory structure included within the docker image. I'll take a look at making some improvements to this.
> 
> Kind Regards, Andrew

Dear Andrew,

I faced the same issue with VEP docker latest version (109_03);

As you instruction, I not quite fully understand how to solve this issue. Could you please provide me more information about that.

Docker version 23.0.3, build 3e7cbfd
Ubuntu: 20.04
Command:
docker run --rm -v /$HOME/vep_data:/data ensemblorg/ensembl-vep vep -i /data/1_S13.vcf --cache --offline -o /data/1_S13_out

==> MSG: ERROR: Could not write to stats file /data/1_S13_out_summary.html

Thank you very much.

Best regards,

**Comment by lamnvcnsh** [comment]
I can fix this problem with your intruction here: 
https://asia.ensembl.org/info/docs/tools/vep/script/vep_download.html (Read/Write access from the container);

The first option is not working for me, but the second option by changing permisison of the mount folder is working.

**Comment by nuno-agostinho** [comment]
Hi @lamnvcnsh!

Glad that fix worked for you. Is everything working as expected after changing the permissions of the mount folder?

Thanks,
Nuno

**Comment by lamnvcnsh** [comment]
Hi @nuno-agostinho 

The annotation process is working well now. 
I am reviewing the annotation result. If having any other issues, I'll let you know.
Thank you very much.

Best wishes,
Lam Nguyen

**Comment by mikal16** [comment]
Hi there,

I'm a bit new to working with docker and I am having a similar issue setting up the docker command. 

I created a folder call vep_data in my home directory like it shows in this tutorial (https://useast.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker) and placed my vcf, gff and fasta files in there and followed the steps to process the gff and fasta files for this analysis. 

This is the command I end up with:
docker run -t -i -v $HOME/vep_data:/data:Z ensemblorg/ensembl-vep ./vep -i $HOME/vep_data/out_filtered.mod.vcf -o $HOME/vep_data/output.txt --gff $HOME/vep_data/Sars_cov_2.ASM985889v3.101.gtf.gz -fasta $HOME/vep_data/Sars_cov_2.ASM985889v3.dna.toplevel.fa.gz

However, I'm not really sure here what data is referring to in this command and I get this error when I run this: 
<img width="1380" alt="Screen Shot 2023-04-21 at 1 15 58 AM" src="https://user-images.githubusercontent.com/66184173/233546533-c9222f19-d7a9-468e-9e9c-7089cadd2dbc.png">

When I try running a similar command, but not using docker, I then get this error: 
<img width="1378" alt="Screen Shot 2023-04-21 at 1 17 10 AM" src="https://user-images.githubusercontent.com/66184173/233546675-a85f32f2-1ae1-4388-865f-71832d2b5d6f.png">

Any help with where I am going wrong here would be really appreciated. 

Thanks a bunch in advance,

Mikal

**Comment by nuno-agostinho** [comment]
Hey Mikal,

Hope you are doing well!

Heare are some issues with your commands:
- `./vep` is not available in the working folder of Docker. You simply should replace it with `vep`.
- The paths to input data are pointing to folders in your host machine that are not available in Docker. You don't need to give the full path when using VEP Docker.
- The options `-t -i` only make sense if you want to run `vep` in interactive mode. If you simply want vep to run as a command (as I think that is your intention), you should avoid to use these options.
- VEP requires your GTF to have a Tabix-indexed file, so you need to run `tabix Sars_cov_2.ASM985889v3.101.gtf.gz` before running VEP.

Can you try first running Tabix on the GTF and then running this command with the fixes mentioned above?

```
docker run -v $HOME/vep_data:/data:Z ensemblorg/ensembl-vep \
  vep -i out_filtered.mod.vcf \
      -o output.txt \
      --gff Sars_cov_2.ASM985889v3.101.gtf.gz \
      --fasta Sars_cov_2.ASM985889v3.dna.toplevel.fa.gz
```

Kind regards,
Nuno

**Comment by mikal16** [comment]
Hi Nuno, 

Thank you so much for the quick reply! So, I ran this modified code and the first time I ran it, it seems that the "Couldn't find index for file Sars_cov_2.ASM985889v3.101.gtf.gz at /usr/local/lib/x86_64-linux-gnu/perl/5.26.1/Bio/DB/HTS/Tabix.pm line 53." disappeared. I then had the following additional error messages; I'm thinking maybe these are things I need to be installing into docker, so I'm going to look into that.

<img width="1385" alt="Screen Shot 2023-04-22 at 6 29 04 PM" src="https://user-images.githubusercontent.com/66184173/233810407-926f03ab-a58c-4148-a6bd-5879bda92265.png">

Strangely, when I logged on again and ran this code, the "Couldn't find index for file Sars_cov_2.ASM985889v3.101.gtf.gz at /usr/local/lib/x86_64-linux-gnu/perl/5.26.1/Bio/DB/HTS/Tabix.pm line 53." error appeared again along with those are those other same error messages.

<img width="995" alt="Screen Shot 2023-04-22 at 8 20 25 PM" src="https://user-images.githubusercontent.com/66184173/233848498-81f9b9be-5638-45c8-954f-b832ee0672e8.png">

Not sure, why this error disappeared then re-appeared, so I'm trying to look into that as well. Any insight into this would be helpful, and thanks so much again for your help and breaking everything down so nicely!

Mikal

**Comment by mikal16** [comment]
Hi there, 

Sorry for the double message, but I troubleshooted some more and actually found that when I was running tabix, I was getting this error: “tabix [E::hts_idx_push] Unsorted positions on sequence #1: 21553 followed by 266”.

I looked into how to fix this issue and came across this fix in a GitHub post https://github.com/samtools/htslib/pull/1457 . So, I fixed the issue by running the following commands to sort and run tabix again.
<img width="1286" alt="Screen Shot 2023-04-23 at 2 53 58 PM" src="https://user-images.githubusercontent.com/66184173/233859229-458b397d-8231-4b20-9137-ad037fdd8a83.png">
<img width="1285" alt="Screen Shot 2023-04-23 at 2 54 58 PM" src="https://user-images.githubusercontent.com/66184173/233859270-90df6b00-e6ac-498f-93c1-5f093c668de1.png">

After this, I ran the vep line again in docker and that fixes the “Couldn't find index for file Sars_cov_2.ASM985889v3.101.gtf.gz at /usr/local/lib/x86_64-linux-gnu/perl/5.26.1/Bio/DB/HTS/Tabix.pm line 53.” error. However, I still get the other errors along with a warning about the start and stop codons being skipped.
<img width="1263" alt="Screen Shot 2023-04-23 at 2 56 05 PM" src="https://user-images.githubusercontent.com/66184173/233859310-9673abe6-d903-48d6-92dd-f8fceffa7718.png">

Thanks again and let me know if there’s anything else I could provide that would be of use.

Kindest regards,

Mikal

**Comment by mikal16** [comment]
Hi Nuno, 

Ahh okay that makes a lot of sense! And yes, the output works, thank you!! I'm sorry, but I have one very last question, but when I ran this analysis using the web interface my output file looked slightly different then what I'm getting now (shown below).
<img width="1430" alt="Screen Shot 2023-04-24 at 4 17 46 PM" src="https://user-images.githubusercontent.com/66184173/234107287-27c90dfb-7bab-4196-a0e0-0611be878a32.png">

I am pretty sure this is because of the annotation I'm using, and so I was wondering if it be possible with this command to modify it so that I use the same annotation file as the one used by the web interface. I'm pretty sure that perhaps the fasta file would have to remain the same, but I think this could solve my issue, because I really need the gene and amino acid column information.

Thanks very much again.

Kindest regards,

Mikal El-Hajjar

**Comment by mikal16** [comment]
I think I may have spotted my error by looking through this github issue (https://github.com/Ensembl/ensembl-vep/issues/399). It looks like my gtf file has the proper format, but for some reason when I run vep, it is still detecting species as human and so I'm thinking maybe this is the issue? 

<img width="1432" alt="Screen Shot 2023-04-24 at 8 47 00 PM" src="https://user-images.githubusercontent.com/66184173/234148100-443c2980-fee8-4766-8405-ec73262934f8.png">

**Comment by mikal16** [comment]
Actually, I think I got this to work, I simply replaced --gtf by --custom and that fixed this. Can't say thank you enough for all the help!

Have a nice day,

Mikal

**Comment by nuno-agostinho** [comment]
Hey @mikal16,

I am glad that you made it work and I hope that you enjoy using VEP. 😊

If you have any other questions, feel free to open a new issue. Have a great day!

Cheers,
Nuno

**Comment by aiqc** [comment]
There are assumptions that make basic use of `-i` and `-o` not intuitive.

VEP expects `/input` and `/output` directories in the same folder as the local cache that gets mounted. I believe it creates these folders automatically if they do not exist, but the user needs to create them beforehand because you have to give the output folder permissions.

So before you get started, make sure the following structure exists
```
/home/layne/Desktop/vep_data/homo_sapiens_vep_109_GRCh38
↳ /homo_sapiens
↳ /input
↳ /output
```

Enable permissions for reading and wring to `/output` folder 
```
chmod a+rw /home/layne/Desktop/vep_data/homo_sapiens_vep_109_GRCh38/ouput
```

If you attempt to specify absolute paths for `-i` and `-o`, VEP ignores them because it is looking in the `./input` and `./output` folders. However, the user still needs to specify those folders manually

```
vep -i input/my.vcf -o output/my.vcf
```

I've had to figure this out from scratch a few times and it is tedious

**Comment by nuno-agostinho** [comment]
Hello @aiqc,

I am sorry you are facing issues running VEP Docker. I'll try to go through the points you raised.

> Absolute paths would be much better.

Absolute paths are indeed supported. Are you facing any issues when using absolute paths? What command are you using?

> I'd rather mount my own input and output folders than reverse-engineer VEP's predefined locations.

By default and for simplicity, we suggest to put all VEP data in the same folder and mount that local folder in the default directory of the Docker image (`/data`). However, you can mount any directories you want and use absolute paths to specify the location of cache, input, output, etc. like you would for any other Docker image.

> So before you get started, make sure the following structure exists

You can structure your directory in any way you want. In your case, VEP expects `input` and `output` folder if you are using the command `vep -i input/my.vcf -o output/my.vcf`. If you want to use files in the top-level folder, you can simply use `vep -i my.vcf -o output.vcf`.

> Enable permissions for reading and writing to /output folder

If you are having permissions issues using Docker, you should try one of the following:
- Run Docker commands with `sudo`
- [Add your user to the `docker` group](https://docs.docker.com/engine/install/linux-postinstall/)

For more information on how to use VEP Docker image, please read our instructions in http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_download.html#docker

Please tell me if you need further clarifications.

Best regards,
Nuno
