### ISSUE TITLE
the numbers of partitions divided by '|' are not equal to number of given partitions from VCF header INFO CSQ

### ISSUE THREAD

**Issue by JingWBX** [Ensembl/ensembl-vep#66]
We should have 91 partitions according to the VCF header  ##INFO=<ID=CSQ,blablabla>
However, when checking the records, the numbers of partitions were 90, 91,103,107 and so on.
This problem happened after we added  **--custom** and **plugin**.
These partitions are divided by "|". And we are sure that there is no problem on partition statistics.
I wonder know how it happens. 

Here is the code.
```
cd ~/liuxuanzhu/Database/ensembl-vep
./vep -i ~/wangyumei/ml/all.vcf   --cache -o wym-all.vcf  --force_overwrite  --everything --vcf  --fork 8 --assembly GRCh37 --offline --custom /mnt/bioinfo/Anno_Database/gnomad.exomes.r2.0.1.sites.vcf.gz,gnomad,vcf,exact,0,AC_POPMAX,AN_POPMAX,AF_POPMAX,AC,AN,AF --custom /mnt/bioinfo/Anno_Database/clinvar_20170228.norm.vcf.gz,clinvar,vcf,exact,0,CLNDBN,CLNSIG,CLNREVSTAT  -plugin dbscSNV,/mnt/bioinfo/Anno_Database/dbscSNV.txt.gz -plugin MCAP,/home/rd/liuxuanzhu/Database/VEP_cache/mcap_v1_0.txt.gz -plugin dbNSFP,/mnt/bioinfo/Anno_Database/dbNSFP3.4a_hg19.gz,M-CAP_pred,MetaLR_score,MetaLR_pred,MetaSVM_score,MetaSVM_pred,REVEL_rankscore,MutPred_rankscore,MutPred_Top5features,Eigen-phred,GERP++_RS,MutationTaster_score,CADD_raw,CADD_phred --plugin SPIDEX,/mnt/bioinfo/Anno_Database/hg19_spidex.txt.gz
```

**Comment by willmclaren** [comment]
I'm not familiar with the MCAP plugin, but it could be that this is what is causing the issue - perhaps it isn't declaring its headers correctly on initialisation. This is how VEP knows what field names will be present in the output.

I'd suggest trying adding one plugin and/or custom annotation flag at a time to see when the problem arises, then report back.

**Comment by JingWBX** [comment]
@willmclaren  Hi, I have known what caused the problem. After using " --custom", there are '|' existing in some result fields, such as 
```
CLNDBN=not_specified|Zellweger_syndrome;CLNREVSTAT=single|single;
```
We will modify the vcf files. And thx !
