### ISSUE TITLE
Use database w/ vep for HGVSg annotation

### ISSUE THREAD

**Issue by benjraspl** [Ensembl/ensembl-vep#660]
Hi, 
I have the problem of having to convert a set of cDNA variants (e.g. ENST00000375550.4:c.1143G>A)  to corresponding HGVS genome variants. Since this requires to not use local cache (at least thats what I figured) I added the --database flag and removed all flags leading to offline usage of the tool but I still get the following error:
>MSG: Cannot connect to the Ensembl MySQL server at ensembldb.ensembl.org:3306; check your settings & DBI error message: Can't connect to MySQL server on 'ensembldb.ensembl.org' (110)
STACK Bio::EnsEMBL::Registry::load_registry_from_db /mnt/SRV018/users/ahbranl1/data_vep/ensembl-vep-release-98.3/Bio/EnsEMBL/Registry.pm:1770
STACK Bio::EnsEMBL::VEP::BaseVEP::registry /mnt/SRV018/users/ahbranl1/data_vep/ensembl-vep-release-98.3/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:252
STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /mnt/SRV018/users/ahbranl1/data_vep/ensembl-vep-release-98.3/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:120
STACK Bio::EnsEMBL::VEP::Runner::init /mnt/SRV018/users/ahbranl1/data_vep/ensembl-vep-release-98.3/modules/Bio/EnsEMBL/VEP/Runner.pm:118
STACK Bio::EnsEMBL::VEP::Runner::run /mnt/SRV018/users/ahbranl1/data_vep/ensembl-vep-release-98.3/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /mnt/users/ahbranl1/data_vep/ensembl-vep-release-98.3/vep:224
Ensembl API version = 98

My arguments currently look like this:
*--format hgvs -i input -o output --vcf --species homo_sapiens --assembly GRCh37 --fork 1 --database --force_overwrite --hgvs --hgvsg --fields HGVSg*

So what do I do wrong? And is it even possible to do an annotation like this? I was wondering since the online tool is only able to give genomic location rather then the variant in HGVSg format.

Again, thanks a lot in advance!
Best regards,
Benjamin

**Comment by aparton** [comment]
Hi,

It’s definitely possible to generate annotations as you describe with VEP, and as you’ve ascertained, you cannot use a cache file with HGVS as input. So you’ll need to use the database, which will be slower, but will work. I believe your connection issues are firewall related however. 

If you want to connect to our GRCh37 database, then you need to add the parameter ‘—port 3337’ to your VEP command. If that doesn’t work, and you are unable to access the database directly with 'mysql --host=ensembldb.ensembl.org --port=3337 --user=anonymous’, then you may have to contact a systems administrator at your end to take a look.

Kind Regards,
Andrew

**Comment by benjraspl** [comment]
Hi,
so adding the --port=3337 flag did not help me, and I neither could access your database using the mysql command you provided. I will talk to an administator to figure things out on my side - thanks yet again for your help! 
I will reply as soon as I know more about this!

Best,
Benjamin

**Comment by benjraspl** [comment]
So I just had talk with an administrator! The problem is that we have an authenticating proxy server running on our side. Does VEP support requests through those kind of proxies? 

And another question: Since I have to annotate a rather large amount of variants I wondered if the file size restrictions for online requests through the command line tool are the same as when using the web interface based implementation?

Best,
Benjamin

**Comment by aparton** [comment]
Hi,

Unfortunately we do not support database connections of this type. 

To allow you to use VEP to convert your HGVSc to HGVSg, I believe your options are:

1) Convince your systems administrator to make an exception for VEP - which may or may not be possible.

2) You could use web VEP to convert your HGVSc input into VCF format. You could then use this VCF with command-line VEP using the —cache, —fasta, —hgvsg and —offline flags to generate the relevant HGVSg from HGVSc

Regarding file size restrictions, web VEP will accept an input file of up to 50MB. There are no file size restrictions for command line VEP, whether you use the database or the cache.

If there’s anything else we can do to help, or if you have any more questions, please don’t hesitate to ask.

Kind Regards,
Andrew

**Comment by benjraspl** [comment]
Thanks, unfortunitely making an exception for vep is not an option - i will go for the second option you suggested! Thanks for your help on this!

**Comment by aparton** [comment]
Hi,

I'm glad we were able to come up with a workaround. I'm going to close this issue now. If you have any other questions, please feel free to reopen it or create a new one.

Kind Regards,
Andrew
