### ISSUE TITLE
Problems updating to VEP 98 cache 

### ISSUE THREAD

**Issue by PedroBarbosa** [Ensembl/ensembl-vep#661]
Hi,

I'm having problems with the update, both for the GRCh37 and GRCh38 versions
My command is pretty simple:

```srun shifter -V=/mnt/nfs/lobo/IMM-NFS/ensembl_vep/cache:/media --image=ensemblorg/ensembl-vep:latest INSTALL.pl -c /media -a cfp -s homo_sapiens -y GRCh38 -g all```

```
WARNING: Unable to carry out version check for 'ensembl-vep'
 - getting list of available cache files
 - downloading ftp://ftp.ensembl.org/pub/release-98/variation/indexed_vep_cache/homo_sapiens_vep_98_GRCh38.tar.gz
Timeout at /usr/share/perl/5.26/Net/FTP.pm line 583.
srun: error: compute-21: task 0: Exited with exit code 255
```
On another trial:
```WARNING: Unable to carry out version check for 'ensembl-vep'
 - getting list of available cache files
 - downloading ftp://ftp.ensembl.org/pub/release-98/variation/indexed_vep_cache/homo_sapiens_vep_98_GRCh38.tar.gz
Unable to close datastream at /opt/vep/src/ensembl-vep/INSTALL.pl line 1259.
```
Actually this last one is still running but it's taking way longer than what usually takes.

Best,
Pedro

**Comment by aparton** [comment]
Hi Pedro,

It looks like Net::FTP is having trouble connecting to our FTP site to download the cache files. Could you please try to access the cache file directly with:

curl -O ftp://ftp.ensembl.org/pub/release-98/variation/indexed_vep_cache/homo_sapiens_vep_98_GRCh38.tar.gz

Additionally, are you able to access the cache file directly outside of the shifter image?

Kind Regards,
Andrew

**Comment by PedroBarbosa** [comment]
Hi,
> Additionally, are you able to access the cache file directly outside of the shifter image?

Yes, usually when the update runs fine i can always access the cache on the server filesystem. 

```
>  - getting list of available cache files
>  - downloading ftp://ftp.ensembl.org/pub/release-98/variation/indexed_vep_cache/homo_sapiens_vep_98_GRCh38.tar.gz
> Unable to close datastream at /opt/vep/src/ensembl-vep/INSTALL.pl line 1259.
```
This one above didn't finish as well. now I checked the log:
```curl failed (150), trying to fetch using LWP::Simple
LWP::Simple failed (500), trying to fetch using HTTP::Tiny
Use of uninitialized value in numeric eq (==) at /usr/share/perl/5.26/HTTP/Tiny.pm line 606.
Use of uninitialized value in numeric eq (==) at /usr/share/perl/5.26/HTTP/Tiny.pm line 606.
ERROR: Failed last resort of using HTTP::Tiny to download ftp://ftp.ensembl.org:21/pub/release-98/variation/indexed_vep_cache/homo_sapiens_vep_98_GRCh38.tar.gz
srun: error: compute-1: task 0: Exited with exit code 56
srun: Terminating job step 861637.0
```

Meanwhile, i'm downloading cache files directly as you suggested.
Best,
Pedro

**Comment by PedroBarbosa** [comment]
Hi,

The manual download also failed :/ there may be some problems with the FTP server..

`curl: (18) transfer closed with 4658457590 bytes remaining to read`

**Comment by aparton** [comment]
Hi Pedro,

We've had reports of issues with our FTP server last week that now appear to be resolved. Could you please try manually downloading the cache files again?

Kind Regards,
Andrew

**Comment by PedroBarbosa** [comment]
Hi @aparton ,

Yes, it's now solved, thank you.
Best,
Pedro
