### ISSUE TITLE
VEP JSON output format for v98.3?

### ISSUE THREAD

**Issue by Hoeze** [Ensembl/ensembl-vep#663]
Hi, I just tried to annotate variants with af_gnomad and return it as JSON.
However, I found that the actual output format differs from the [documentation](https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#json):

```json
{
   "transcript_consequences":[ ... ],
   "assembly_name":"GRCh37",
   "input":"1\\t55505092\\t.\\tG\\tA\\t.\\t.\\t.",
   "allele_string":"G/A",
   "colocated_variants":[
      {
         "minor_allele_freq":0.0054,
         "start":55505092,
         "minor_allele":"A",
         "id":"rs28362200",
         "seq_region_name":"1",
         "strand":1,
         "allele_string":"G/A",
         "frequencies":{
            "A":{
               "eur":0,
               "amr":0.0043,
               "afr":0.0182,
               "sas":0,
               "eas":0
            }
         },
         "end":55505092
      }
   ],
   "strand":1,
   "seq_region_name":"1",
   "id":".",
   "end":55505092,
   "start":55505092,
   "most_severe_consequence":"upstream_gene_variant"
}
```

How do I interpret this? The gnomAD AF is missing as far as I can see.
Is gnomAD-AF just missing and  "--JSON" drops missing values from the output?

### System
- VEP version: 98.3
- VEP Cache version: 98
- Perl version: 5.26.2
- OS: CentOS / Anaconda

### Full VEP command line
```
vep --dir_cache ensembl-vep/98/cachedir --dir_plugin ensembl-vep/98/cachedir/Plugins --plugin CADD,CADD/v1.3/whole_genome_SNVs.tsv.gz,CADD/v1.3/InDels.tsv.gz --format vcf --output_file STDOUT --allele_number --assembly GRCh37 --port 3337 --sift b --polyphen s --total_length --numbers --symbol --ccds --xref_refseq --uniprot --af --af_gnomad --max_af --pubmed --canonical --biotype --no_stats --cache --offline --json --merged
```

**Comment by aparton** [comment]
Hi,

We use gnomAD exomes v2.1 within our grch37 cache files. VEP cannot find a variant at that location in our gnomad files, and as such doesn’t return any data.

gnomAD genomes v2.1 does contain this variant however. If you would like to add gnomad genomes to your VEP output, you can see how to do that here: https://www.ensembl.org/info/docs/tools/vep/script/vep_example.html#gnomad <https://www.ensembl.org/info/docs/tools/vep/script/vep_example.html#gnomad>

If you have any more questions, please don’t hesitate to ask.

Kind Regards,
Andrew

**Comment by Hoeze** [comment]
Ah, I see. Thank you for explaining :+1:
