### ISSUE TITLE
only vep_45 on ensembl for bacteria, not 98

### ISSUE THREAD

**Issue by 4ureliek** [Ensembl/ensembl-vep#664]
I am trying to run VEP on the species `haemophilus_influenzae_10810`. 
I ended up making it work with `--fasta` and `--gff`, but I was more generally wondering if there was a way to use the cache?

I found these files for the cache:
ftp://ftp.ensemblgenomes.org/pub/bacteria/current/variation/vep/bacteria_20_collection/haemophilus_influenzae_10810_vep_45_ASM21087v1.tar.gz

### Docker:
`docker run -t -i -v /data1/vep_data:/opt/vep/.vep ensemblorg/ensembl-vep`

#### Check files are accessible in the docker:
```
ll /opt/vep/.vep/cache/
drwxr-xr-x+ 3 634 634      34 Aug 23 17:49 haemophilus_influenzae_10810/
-rw-rw-r--  1 634 634 1620406 Dec 12 22:06 haemophilus_influenzae_10810_vep_45_ASM21087v1.tar.gz
```

```
ll /opt/vep/.vep/cache/haemophilus_influenzae_10810/45_ASM21087v1/
-rw-r--r--  1 634 634 733673 Mar 22  2017 chr_synonyms.txt
drwxr-xr-x+ 2 634 634     62 Mar 26  2017 FQ312006/
-rw-r--r--  1 634 634    129 Mar 26  2017 info.txt
```

### Full VEP command line
`vep -i /opt/vep/.vep/input.vcf.sort.gz -o /opt/vep/.vep/output.vep --stats_file /opt/vep/.vep/output.vep.stats --format vcf --vcf --species haemophilus_influenzae_10810 --dir_cache /opt/vep/.vep/cache --offline --force_overwrite`

### Error message:
```
-------------------- EXCEPTION --------------------
MSG: ERROR: No cache found for haemophilus_influenzae_10810, version 98

STACK Bio::EnsEMBL::VEP::CacheDir::dir /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:328
STACK Bio::EnsEMBL::VEP::CacheDir::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:227
STACK Bio::EnsEMBL::VEP::CacheDir::new /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:115
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /opt/vep/src/ensembl-vep/vep:224
Date (localtime)    = Fri Dec 13 00:58:13 2019
Ensembl API version = 98
---------------------------------------------------
```

Which makes sense - there is indeed no cache available for the right version.
Thank you!

### System
- VEP version: `Ensembl API version = 98`
- VEP Cache version: `see above, that's the issue - looks like 45 only is available`
- Perl version: `v5.26.1`
- OS: `CentOS`
- tabix installed: `tabix (htslib) 1.9`

**Comment by ima23** [comment]
Hi @4ureliek,

Indeed the latest bacteria cache release is 45. Running your command with `-cache_version 45` should do the trick.
More info on how to run VEP with non-vertebrate species can be found here: https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#basic

Kind regards,
Irina
