### ISSUE TITLE
Installation failure.

### ISSUE THREAD

**Issue by KoenDebackere** [Ensembl/ensembl-vep#665]
## Describe the issue
I try to install ensembl-vep according to the [instructions provided for macOS](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html). All the prerequisites are installed according to the instructions. When running INSTALL.pl, all tests failed initially, but this could be overcome by installing Try::Tiny.
Now I get more or less the same errors as mentioned in the closed report #381. I double checked the path to the manual installation of BioPerl in my .bash_profile as suggested, and this is OK. I removed the vep-ensembl directory and did a reinstall, but I get exactly the same error.

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 98 
- VEP Cache version: 98
- Perl version: 5.26.2
- OS: macOS Mojave (14.6)
- tabix installed ? yes (as part of htslib 1.10 with home-brew)

### Full VEP command line
```
perl INSTALL.pl 
```

### Full error message
Installation on OSX requires that you set up some paths before running this installer.
Have you 
1. added /Users/u0062120/ensembl-vep/htslib to your DYLD_LIBRARY_PATH environment variable?
(y/n): y

Hello! This installer is configured to install v98 of the Ensembl API for use by the VEP.
It will not affect any existing installations of the Ensembl API that you may have.

It will also download and install cache files from Ensembl's FTP server.

Checking for installed versions of the Ensembl API...done

Setting up directories
 - fetching BioPerl
 - unpacking ./Bio/tmp/release-1-6-924.zip
 - moving files
Attempting to install Bio::DB::HTS and htslib.

>>> If this fails, try re-running with --NO_HTSLIB

 - checking out HTSLib
Cloning into 'htslib'...
remote: Enumerating objects: 68, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 12742 (delta 34), reused 49 (delta 24), pack-reused 12674
Receiving objects: 100% (12742/12742), 9.39 MiB | 8.63 MiB/s, done.
Resolving deltas: 100% (9117/9117), done.
Note: checking out '1832d3a1b75133e55fb6abffc3f50f8a6ed5ceae'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

 - building HTSLIB in ./htslib
In /Users/u0062120/ensembl-vep/htslib
echo '/* Default config.h generated by Makefile */' > config.h
echo '#define HAVE_LIBBZ2 1' >> config.h
echo '#define HAVE_LIBLZMA 1' >> config.h
echo '#define HAVE_LZMA_H 1' >> config.h
echo '#define HAVE_FSEEKO 1' >> config.h
echo '#define HAVE_DRAND48 1' >> config.h
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o kfunc.o kfunc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o knetfile.o knetfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o kstring.o kstring.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o bcf_sr_sort.o bcf_sr_sort.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o bgzf.o bgzf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o errmod.o errmod.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o faidx.o faidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hfile.o hfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.9-dirty"' > version.h
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hts.o hts.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hts_os.o hts_os.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o md5.o md5.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o multipart.o multipart.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o probaln.o probaln.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o realn.o realn.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o regidx.o regidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o sam.o sam.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o synced_bcf_reader.o synced_bcf_reader.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcf_sweep.o vcf_sweep.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o tbx.o tbx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o textutils.o textutils.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o thread_pool.o thread_pool.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcf.o vcf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcfutils.o vcfutils.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_decode.o cram/cram_decode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_encode.o cram/cram_encode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_external.o cram/cram_external.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_index.o cram/cram_index.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_io.o cram/cram_io.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_samtools.o cram/cram_samtools.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_stats.o cram/cram_stats.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/files.o cram/files.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/mFILE.o cram/mFILE.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/open_trace_file.o cram/open_trace_file.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/pooled_alloc.o cram/pooled_alloc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/rANS_static.o cram/rANS_static.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/sam_header.o cram/sam_header.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/string_alloc.o cram/string_alloc.c
ar -rc libhts.a kfunc.o knetfile.o kstring.o bcf_sr_sort.o bgzf.o errmod.o faidx.o hfile.o hfile_net.o hts.o hts_os.o md5.o multipart.o probaln.o realn.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o textutils.o thread_pool.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o
ranlib libhts.a
gcc -dynamiclib -install_name /usr/local/lib/libhts.2.dylib -current_version 1.9.255 -compatibility_version 2  -o libhts.dylib kfunc.o knetfile.o kstring.o bcf_sr_sort.o bgzf.o errmod.o faidx.o hfile.o hfile_net.o hts.o hts_os.o md5.o multipart.o probaln.o realn.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o textutils.o thread_pool.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o -lz -lm -lbz2 -llzma
ln -sf libhts.dylib libhts.2.dylib
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o bgzip.o bgzip.c
gcc  -o bgzip bgzip.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o htsfile.o htsfile.c
gcc  -o htsfile htsfile.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o tabix.o tabix.c
gcc  -o tabix tabix.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/hts_endian.o test/hts_endian.c
gcc  -o test/hts_endian test/hts_endian.o -lz -lm -lbz2 -llzma
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/fieldarith.o test/fieldarith.c
gcc  -o test/fieldarith test/fieldarith.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/hfile.o test/hfile.c
gcc  -o test/hfile test/hfile.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/sam.o test/sam.c
gcc  -o test/sam test/sam.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test_bgzf.o test/test_bgzf.c
gcc  -o test/test_bgzf test/test_bgzf.o libhts.a -lz -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test_realn.o test/test_realn.c
gcc  -o test/test_realn test/test_realn.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-regidx.o test/test-regidx.c
gcc  -o test/test-regidx test/test-regidx.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test_view.o test/test_view.c
gcc  -o test/test_view test/test_view.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-vcf-api.o test/test-vcf-api.c
gcc  -o test/test-vcf-api test/test-vcf-api.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-vcf-sweep.o test/test-vcf-sweep.c
gcc  -o test/test-vcf-sweep test/test-vcf-sweep.o libhts.a -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-bcf-sr.o test/test-bcf-sr.c
gcc  -o test/test-bcf-sr test/test-bcf-sr.o libhts.a -lz -lz -lm -lbz2 -llzma -lpthread
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-bcf-translate.o test/test-bcf-translate.c
gcc  -o test/test-bcf-translate test/test-bcf-translate.o libhts.a -lz -lz -lm -lbz2 -llzma -lpthread
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.11 - moving files to ./biodbhts
 - making Bio::DB:HTS
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.11'
Building Bio-DB-HTS
cc -I/Users/u0062120/ensembl-vep/htslib -I/Users/u0062120/perl5/perlbrew/perls/5.26.2/lib/5.26.2/darwin-thread-multi-2level/CORE -DVERSION="2.11" -DXS_VERSION="2.11" -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wno-unused-result -c -fno-common -DPERL_DARWIN -mmacosx-version-min=10.14 -arch x86_64 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV -O3 -o lib/Bio/DB/HTS.o lib/Bio/DB/HTS.c
lib/Bio/DB/HTS.xs:1770:22: warning: 'bcf_hdr_fmt_text' is deprecated: use bcf_hdr_format() instead [-Wdeprecated-declarations]
    RETVAL = newSVpv(bcf_hdr_fmt_text(header, is_bcf, &len), 0);
                     ^
/Users/u0062120/ensembl-vep/htslib/htslib/vcf.h:440:9: note: 'bcf_hdr_fmt_text' has been explicitly marked deprecated here
        HTS_DEPRECATED("use bcf_hdr_format() instead");
        ^
/Users/u0062120/ensembl-vep/htslib/htslib/hts_defs.h:65:49: note: expanded from macro 'HTS_DEPRECATED'
#define HTS_DEPRECATED(message) __attribute__ ((__deprecated__ (message)))
                                                ^
1 warning generated.
ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Bio/DB/HTS/HTS.bs')
env LD_RUN_PATH=/Users/u0062120/perl5/perlbrew/perls/5.26.2/lib/5.26.2/darwin-thread-multi-2level/CORE cc -arch x86_64 -mmacosx-version-min=10.14 -bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector-strong -o blib/arch/auto/Bio/DB/HTS/HTS.bundle lib/Bio/DB/HTS.o -L/Users/u0062120/ensembl-vep/htslib -Wl,-rpath,/Users/u0062120/ensembl-vep/htslib -lhts -lpthread -lz
cc -I/Users/u0062120/ensembl-vep/htslib -I/Users/u0062120/perl5/perlbrew/perls/5.26.2/lib/5.26.2/darwin-thread-multi-2level/CORE -DVERSION="2.11" -DXS_VERSION="2.11" -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wno-unused-result -c -fno-common -DPERL_DARWIN -mmacosx-version-min=10.14 -arch x86_64 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV -O3 -o lib/Bio/DB/HTS/Faidx.o lib/Bio/DB/HTS/Faidx.c
ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Bio/DB/HTS/Faidx/Faidx.bs')
env LD_RUN_PATH=/Users/u0062120/perl5/perlbrew/perls/5.26.2/lib/5.26.2/darwin-thread-multi-2level/CORE cc -arch x86_64 -mmacosx-version-min=10.14 -bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector-strong -o blib/arch/auto/Bio/DB/HTS/Faidx/Faidx.bundle lib/Bio/DB/HTS/Faidx.o -L/Users/u0062120/ensembl-vep/htslib -Wl,-rpath,/Users/u0062120/ensembl-vep/htslib -lhts -lpthread -lz

Downloading required Ensembl API files
 - fetching ensembl
 - unpacking ./Bio/tmp/ensembl.zip
 - moving files
 - getting version information
 - fetching ensembl-variation
 - unpacking ./Bio/tmp/ensembl-variation.zip
 - moving files
 - getting version information
 - fetching ensembl-funcgen
 - unpacking ./Bio/tmp/ensembl-funcgen.zip
 - moving files
 - getting version information
 - fetching ensembl-io
 - unpacking ./Bio/tmp/ensembl-io.zip
 - moving files
 - getting version information

Testing VEP installation
./t/Utils.t .......................................... ok    
./t/Parser_Region.t .................................. Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Parser_Region.t .................................. ok    
./t/FilterSet.t ...................................... ok     
./t/AnnotationSource_Cache.t ......................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache.t ......................... ok   
./t/AnnotationSource_Database_Variation.t ............ Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_Variation.t ............ ok    
./t/AnnotationSource_Database_RegFeat.t .............. Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_RegFeat.t .............. ok    
./t/OutputFactory_Tab.t .............................. Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_Tab.t .............................. ok    
./t/version.t ........................................ ok   
./t/AnnotationSource_File_BigWig.t ................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_BigWig.t ................... ok    
./t/AnnotationSource_Cache_VariationTabix.t .......... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_VariationTabix.t .......... ok    
./t/OutputFactory_VEP_output.t ....................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_VEP_output.t ....................... ok    
./t/Config.t ......................................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Config.t ......................................... ok    
./t/TranscriptTree.t ................................. Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/TranscriptTree.t ................................. ok    
./t/InputBuffer.t .................................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/InputBuffer.t .................................... ok    
./t/OutputFactory_JSON.t ............................. Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_JSON.t ............................. ok    
./t/Parser.t ......................................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Parser.t ......................................... ok     
./t/VariantRecoder.t ................................. Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/VariantRecoder.t ................................. ok    
./t/AnnotationSource_File.t .......................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File.t .......................... 1/? Can't locate object method "new" via package "Bio::EnsEMBL::VEP::AnnotationSource::File::GFF" at /Users/u0062120/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 167.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 17.
./t/AnnotationSource_File.t .......................... Dubious, test returned 2 (wstat 512, 0x200)
All 17 subtests passed 
./t/Parser_ID.t ...................................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Parser_ID.t ...................................... ok   
./t/OutputFactory.t .................................. Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory.t .................................. ok     
./t/Parser_VEP_input.t ............................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Parser_VEP_input.t ............................... ok    
./t/Parser_SPDI.t .................................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Parser_SPDI.t .................................... ok   
./t/CacheDir.t ....................................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/CacheDir.t ....................................... ok    
./t/AnnotationSource_Database_Transcript.t ........... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_Transcript.t ........... ok    
./t/Runner.t ......................................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Runner.t ......................................... 50/? Can't locate object method "new" via package "Bio::EnsEMBL::VEP::AnnotationSource::File::GFF" at /Users/u0062120/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 167.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 73.
./t/Runner.t ......................................... Dubious, test returned 255 (wstat 65280, 0xff00)
All 73 subtests passed 
./t/AnnotationSource_Database_StructuralVariation.t .. Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_StructuralVariation.t .. ok    
./t/AnnotationSource_Cache_RegFeat.t ................. Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_RegFeat.t ................. ok    
./t/AnnotationSource_File_GFF.t ...................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_GFF.t ...................... 1/? 
#   Failed test 'use Bio::EnsEMBL::VEP::AnnotationSource::File::GFF;'
#   at ./t/AnnotationSource_File_GFF.t line 41.
#     Tried to use 'Bio::EnsEMBL::VEP::AnnotationSource::File::GFF'.
#     Error:  Attempt to reload Bio/EnsEMBL/VEP/AnnotationSource/File/GFF.pm aborted.
# Compilation failed in require at ./t/AnnotationSource_File_GFF.t line 41.
# BEGIN failed--compilation aborted at ./t/AnnotationSource_File_GFF.t line 41.
Can't locate object method "new" via package "Bio::EnsEMBL::VEP::AnnotationSource::File::GFF" at ./t/AnnotationSource_File_GFF.t line 51, <__ANONIO__> line 9.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 25 just after 4.
./t/AnnotationSource_File_GFF.t ...................... Dubious, test returned 25 (wstat 6400, 0x1900)
Failed 1/4 subtests 
./t/Parser_HGVS.t .................................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Parser_HGVS.t .................................... ok    
./t/AnnotationSource_File_VCF.t ...................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_VCF.t ...................... ok    
./t/bam_edit.t ....................................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/bam_edit.t ....................................... ok    
./t/OutputFactory_VCF.t .............................. Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_VCF.t .............................. ok    
./t/AnnotationSourceAdaptor.t ........................ Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSourceAdaptor.t ........................ ok    
./t/Stats.t .......................................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Stats.t .......................................... ok    
./t/AnnotationSource_Cache_Transcript.t .............. Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_Transcript.t .............. ok    
./t/AnnotationSource_File_BED.t ...................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_BED.t ...................... ok    
./t/AnnotationSource.t ............................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource.t ............................... ok    
./t/AnnotationSource_Cache_Variation.t ............... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_Variation.t ............... ok    
./t/Parser_VCF.t ..................................... "my" variable $cnv_vf masks earlier declaration in same scope at ./t/Parser_VCF.t line 570.
Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/Parser_VCF.t ..................................... 1/? WARNING: variant sv_dup on line 1 is too long to annotate: (10000)
WARNING: variant sv_dup on line 1 is too long to annotate: (10000)
./t/Parser_VCF.t ..................................... ok    
./t/BaseVEP.t ........................................ Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/BaseVEP.t ........................................ ok    
./t/AnnotationSource_File_GTF.t ...................... Possible precedence issue with control flow operator at /Users/u0062120/perl5/BioPerl-1.6.924/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_GTF.t ...................... 1/? 
#   Failed test 'use Bio::EnsEMBL::VEP::AnnotationSource::File::GTF;'
#   at ./t/AnnotationSource_File_GTF.t line 41.
#     Tried to use 'Bio::EnsEMBL::VEP::AnnotationSource::File::GTF'.
#     Error:  Attempt to reload Bio/EnsEMBL/IO/Parser/GXF.pm aborted.
# Compilation failed in require at /Users/u0062120/perl5/perlbrew/perls/5.26.2/lib/5.26.2/parent.pm line 16.
# BEGIN failed--compilation aborted at Bio/EnsEMBL/IO/Parser/GTF.pm line 30.
# Compilation failed in require at Bio/EnsEMBL/IO/Parser/GTFTabix.pm line 41.
# BEGIN failed--compilation aborted at Bio/EnsEMBL/IO/Parser/GTFTabix.pm line 41.
# Compilation failed in require at /Users/u0062120/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/GTF.pm line 67.
# BEGIN failed--compilation aborted at /Users/u0062120/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/GTF.pm line 67.
# Compilation failed in require at ./t/AnnotationSource_File_GTF.t line 41.
# BEGIN failed--compilation aborted at ./t/AnnotationSource_File_GTF.t line 41.
Can't locate object method "new" via package "Bio::EnsEMBL::VEP::AnnotationSource::File::GTF" at ./t/AnnotationSource_File_GTF.t line 51, <__ANONIO__> line 9.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 25 just after 4.
./t/AnnotationSource_File_GTF.t ...................... Dubious, test returned 25 (wstat 6400, 0x1900)
Failed 1/4 subtests 

Test Summary Report
-------------------
./t/AnnotationSource_File.t                        (Wstat: 512 Tests: 17 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
./t/Runner.t                                       (Wstat: 65280 Tests: 73 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
./t/AnnotationSource_File_GFF.t                    (Wstat: 6400 Tests: 4 Failed: 1)
  Failed test:  2
  Non-zero exit status: 25
  Parse errors: No plan found in TAP output
./t/AnnotationSource_File_GTF.t                    (Wstat: 6400 Tests: 4 Failed: 1)
  Failed test:  2
  Non-zero exit status: 25
  Parse errors: No plan found in TAP output
Files=41, Tests=1613, 103 wallclock secs ( 0.24 usr  0.13 sys + 97.39 cusr  4.17 csys = 101.93 CPU)
Result: FAIL
Failed 4/41 test programs. 2/1613 subtests failed.

**Comment by at7** [comment]
Dear @KoenDebackere,
thank you for your detailed error report. Is it possible that you have already installed BioPerl? The errors look like there is a conflict with an existing BioPerl installation on your computer.
If that is the case we have previously suggested to:
1) Delete the ensembl-vep directory
2) Reclone VEP with ‘git clone https://github.com/ensembl/ensembl-vep
3) Ensure that the path to your manually installed BioPerl is stored within your PERL5LIB variable
4) Rerun the installer

Kind regards,
Anja

**Comment by KoenDebackere** [comment]
Dear @at7  Anja,

Thanks for your reply.  I already did that. I have a manual installation of BioPerl 1.6.924 and the path is correctly stored within my PERL5LIB variable:

`~$ echo $PERL5LIB                                       
/Users/u0062120/perl5/BioPerl-1.6.924`

When I try another reinstall, I get the same error.

Moreover, since the installer installs BioPerl 1.6.924 as well, I ran the INSTALL.pl script in an new session without the path to my manual install of BioPerl in the PERL5LIB variable, but I get exactly the same errors.

For both ./t/AnnotationSource_File.t and ./t/Runner.t I get this error: Can't locate object method "new" via package "Bio::EnsEMBL::VEP::AnnotationSource::File::GFF" at /Users/u0062120/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 167.

The next to errors involve ./t/AnnotationSource_File_GFF.t and ./t/AnnotationSource_File_GTF.t. First they throw "Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791." Then both scripts are ran again and throw a very similar error:
- Failed test 'use Bio::EnsEMBL::VEP::AnnotationSource::File::GFF;'  at ./t/AnnotationSource_File_GFF.t line 41
- Failed test 'use Bio::EnsEMBL::VEP::AnnotationSource::File::GTF;' at ./t/AnnotationSource_File_GTF.t line 41

Can these errors be related/a consequence of to the first two errors?

**Comment by at7** [comment]
The "Possible precedence issue with control flow operator" message can be ignored. I'm concerned about the second error related to the AnnotationSource::File::GFF and AnnotationSource::File::GTF tests. However, if you are not planning to use the custom annotation option I would suggest that you try running VEP regardless of those messages and we will look into it and get back to you with a solution. But this will not be before the new year.

**Comment by at7** [comment]
Hi @KoenDebackere,
how have you been getting on? Considering that you have already installed htslib through homebrew could you please try running the VEP installation with perl INSTALL.pl --NO_HTSLIB?
Thank you,
Anja

**Comment by KoenDebackere** [comment]
Hi Anja,
I have been using VEP despite the errors and so far everything seems OK. I use VEP in combination with an adapted version of vcf2maf.pl to annotate vcf4.1 files from VarScan2 and convert them tw .maf files for visualisation with the Maftools package.
I will try to reinstall with --NO_HTSLIB out of curiosity.

Best regards,

Koen
