### ISSUE TITLE
Bio-HTS --> Bio-DB-HTS

### ISSUE THREAD

**Issue by serge2016** [Ensembl/ensembl-vep#668]
Hi.
Here https://github.com/Ensembl/ensembl-vep/blob/release/98/INSTALL.pl#L898 there is an old link to the repo: https://github.com/Ensembl/Bio-HTS. Now it is https://github.com/Ensembl/Bio-DB-HTS.

Moreover, I think the code in https://github.com/Ensembl/ensembl-vep/blob/release/98/INSTALL.pl#L921 is unnecessary for current version (3.01) of `Bio-DB-HTS`.

And in the line https://github.com/Ensembl/ensembl-vep/blob/release/98/INSTALL.pl#L940 it would be great to check if ENV variable `HTSLIB_DIR` exists and points to the correct location. If so, `--htslib` is not necessary.

**Comment by ima23** [comment]
Hi @serge2016 ,

Thanks for the pointers, we will have a look and revise the script.

Thanks,
Irina

**Comment by aparton** [comment]
Hi @serge2016,

Thanks for the suggestions. Regarding the old repository and the Build.PL patching, both of these changes would be improvements to our installation scripts and pull requests have been submitted to add these.

Regarding adding a HTSLIB_DIR check, if a user has a previously installed HTSLIB on their machine then we don't want to use it by default as we've had compatibility issues in the past. Users can use the --NO_HTSLIB flag with the installer if they don't VEP to use a new locally installed HTSLIB.

If you have any more suggestions, please let us know.

Kind Regards,
Andrew

**Comment by ima23** [comment]
The code updates have been applied and will be available in release 101. I am going to close this issue for now. I will close this ticket. If you encounter other issues, please feel free to open a new ticket.
Kind regards,
Irina
