### ISSUE TITLE
check_api() should be executed before api()

### ISSUE THREAD

**Issue by serge2016** [Ensembl/ensembl-vep#669]
Hello!
For now, in AUTO mode API is installed without any checks for already installed components. Maybe it would be better at least run `check_api()` before?

**Comment by ima23** [comment]
Hi @serge2016,

Thanks for the message. AUTO runs is meant to run without any additional prompts. 
If you want to only run specify parts of the install, you can use the AUTO options, for example **c** for cache:

`perl INSTALL.pl --AUTO c`

The other AUTO options are listed [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#installer).

Thanks,
Irina

**Comment by serge2016** [comment]
@ima23, I do know the options pretty well)
I suggest adding autodetection of already installed modules in the AUTO mode. At least a part of such functionality is already implemented in `check_api()`, why not to reuse it?

**Comment by ima23** [comment]
@serge2016  Can you give please give an use case example that is not already covered by the current parameter options?  Only `--AUTO a` will install the API, the rest of `AUTO` options will not do that.

Thanks,
Irina

**Comment by ima23** [comment]
I am closing this ticket,  if you have any more questions please feel free to reopen it.

Best regards,
Irina
