### ISSUE TITLE
Error while installing ensembl-vep via INSTALL.pl

### ISSUE THREAD

**Issue by gk-bioin4m8x** [Ensembl/ensembl-vep#67]
Hi @willmclaren, 
I followed the instructions to install ensembl-vep and got the error:

```
git clone https://github.com/Ensembl/ensembl-vep.git
cd ensembl-vep
perl INSTALL.pl
ERROR: Failed last resort of using HTTP::Tiny to download https://api.github.com/repos/Ensembl/ensembl-vep
```
I am using Perlv5.22.1

Kindly guide.
Thanks!

**Comment by willmclaren** [comment]
The INSTALL.pl requires one of the following to download files:

- the curl command line utility
- the HTTP::Tiny Perl module
- the LWP::Simple Perl module

I'd suggest installing curl on your system; it is a standard utility on most UNIX and Mac OSX systems, but there's a chance your setup is non-standard. How you do this depends on your operating system - do a google search for "install curl on [MyOS]".

**Comment by gk-bioin4m8x** [comment]
Thanks @willmclaren. Its installing 89 version. My data was aligned with 79 version and hence the vcf files, how can I use 79 version?

**Comment by willmclaren** [comment]
If the assembly your data were called against was either GRCh37 or GRCh38 then you can use version 89 of the software fine.

However, if you specifically require Ensembl version 79 transcript data, you may download this cache with the following example command:

```perl INSTALL.pl -a cf -s homo_sapiens -v 79 -y GRCh38```

You should run this after you have successfully installed the v89 API.

Replace GRCh38 with GRCh37 if your data are on GRCh37/hg19.

The `--VERSION|-v` parameter described [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#installer) applies to both software and data.
