### ISSUE TITLE
Annotation is different with more variants in VCF

### ISSUE THREAD

**Issue by genomics-geek** [Ensembl/ensembl-vep#674]
## Describe the issue

When a VCF has additional variants, it seems to annotate differently.  For example, the variant (2:166170271 G/A) does not have gene_symbol annotation when the VCF has more variants.

### System
- VEP version: 97.3
- VEP Cache version: 97
- Perl version: 5.26
- OS: RHEL7
- tabix installed: yes

### Full VEP command line for scenario one (properly annotated)

```
./vep \
  --verbose \
  --no_stats \
  --offline \
  --cache \
  -dir ensembl-vep/cache/ \
  --force_overwrite \
  --fork 24 \
  --buffer_size 2000 \
  --compress_output bgzip \
  --json \
  --refseq \
  --fasta Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz \
  --input_file input.2.vcf \
  --output_file vep.2.json.gz \
  --everything \
  --exclude_predicted \
  --hgvsg \
  --flag_pick \
  --pick_order rank,canonical,ccds \
  --total_length \
  --distance 0 \
  --clin_sig_allele \
  --no_escape \
  --assembly GRCh37
```

### Data files (if applicable)
They include:

- The input file:
[input.2.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/4059831/input.2.vcf.gz)
 
- The output file: 
[vep.2.json.gz](https://github.com/Ensembl/ensembl-vep/files/4059832/vep.2.json.gz)

### Full VEP command line for scenario two (NOT properly annotated)

```
./vep \
  --verbose \
  --no_stats \
  --offline \
  --cache \
  -dir ensembl-vep/cache/ \
  --force_overwrite \
  --fork 24 \
  --buffer_size 2000 \
  --compress_output bgzip \
  --json \
  --refseq \
  --fasta Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz \
  --input_file input.2.vcf \
  --output_file vep.2.json.gz \
  --everything \
  --exclude_predicted \
  --hgvsg \
  --flag_pick \
  --pick_order rank,canonical,ccds \
  --total_length \
  --distance 0 \
  --clin_sig_allele \
  --no_escape \
  --assembly GRCh37
```

### Data files (if applicable)
They include:

- The input file: 
[input.3.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/4059834/input.3.vcf.gz)

- The output file: 
[vep.3.json.gz](https://github.com/Ensembl/ensembl-vep/files/4059836/vep.3.json.gz)

**Comment by at7** [comment]
Dear Michael,

thank you for your detailed error report which helped to quickly reproduce the problem. We are aware of the underlying cause which has been explained in more detail [here](https://github.com/Ensembl/ensembl-vep/issues/667#issuecomment-572529539). We will be fixing the cache files for release 100 expected for the beginning of April. I will create a ticket and send you a message when the updated cache files are available.

Best wishes,
Anja

**Comment by genomics-geek** [comment]
Hi @at7,  Just curious if there will be an update for this?  I know it was expected for early April.  Is there an update for this?

**Comment by at7** [comment]
Hi,
we are scheduled to have the new Ensembl release 100 by the end of April.

Best wishes,
Anja

**Comment by genomics-geek** [comment]
Awesome! thank you so much.

**Comment by at7** [comment]
Hi Michael,

Just to let you know, Ensembl 100 has just been released, including the updated GRCh37 RefSeq transcript set.

Best wishes,
Anja

**Comment by genomics-geek** [comment]
Great! Thank you :)

**Comment by genomics-geek** [comment]
hi @at7 - I am trying to install using `-s homo_sapiens_refseq` like I used to, but now get this error: 
```
ERROR: No matching species found at INSTALL.pl line 1191.
ERROR: No species specified (--species). Use "--species all" or select one of the following:
```

**Comment by at7** [comment]
Hi,
I just tested it by running perl INSTALL.pl  -a c -s homo_sapiens_refseq -assembly GRCh38 and it is working. Could you please try running again or send me your full command?

Thank you,
Anja

**Comment by genomics-geek** [comment]
Hi @at7 sorry, I should have been more clear...

Here is my full command:

```perl INSTALL.pl \
  -t \
  -c ./cache/ \
  -a acp \
  --species homo_sapiens_refseq \
  -y GRCh37
```

**Comment by at7** [comment]
Hi,
thank you for your full command. I'm able to install the homo sapiens RefSeq cache file with your command. Have you tried running it again? Are you using a fresh checkout of the ensembl-vep release/100 repo? Another option would be to install the new cache file manually by following the instructions from here: https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache

Best regards,
Anja

**Comment by genomics-geek** [comment]
so I think we were having a FTP access issue (it was timing out..).  Seems that our admins want us to use http:// instead. SO, I tried this:

```
perl INSTALL.pl \
  -t \
  -c ./cache/ \
  -a acp \
  --species homo_sapiens_refseq \
  -y GRCh37 \
  --CACHEURL http://ftp.ensembl.org/pub/release-100/variation/indexed_vep_cache  \
  -g Blosum62,CADD,Carol,Condel,Conservation,CSN,dbNSFP,dbscSNV,Downstream,FATHMM_MKL,G2P,HGVSIntronOffset,LoFtool,Mastermind,MPC,MTR,NearestExonJB,ReferenceQuality,REVEL,SameCodon,SingleLetterAA,StructuralVariantOverlap,SubsetVCF,TSSDistance;
```

This is the error I get:

```
 - getting list of available cache files
Could not get current species list - using predefined list instead
For more species, see http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#pre
ERROR: No matching species found at INSTALL.pl line 1191.
```

I wonder if it is because I have been forced to use the http:// url instead?

**Comment by at7** [comment]
Hi,
the installer doesn't support cache urls starting with http://. We will look into it and improve it very likely for our 101 release. In the meantime could you please try and installing the new cache files manually?
Thank you,
Anja

**Comment by at7** [comment]
Hi,
contrary to my last message we haven't been able to implement the request for downloading cache files from http with the VEP installer. However, we have added your request to our feature request list. I cannot give you an estimate for when the functionality will be added. But we will be highlighting any new developments when we tag a new release [here](https://github.com/Ensembl/ensembl-vep/tags). I'm going to close this issue now.
Best wishes,
Anja
