### ISSUE TITLE
Install default options error

### ISSUE THREAD

**Issue by nroak** [Ensembl/ensembl-vep#675]
## Describe the issue
I'm trying to install VEP per the instructions and getting an error below:

```
[noak@nodecn204 ensembl-vep]$ perl INSTALL.pl            
WARNING: Unable to carry out version check for 'ensembl-vep'

Hello! This installer is configured to install v98 of the Ensembl API for use by the VEP.
It will not affect any existing installations of the Ensembl API that you may have.

It will also download and install cache files from Ensembl's FTP server.

Checking for installed versions of the Ensembl API...No such file or directory at INSTALL.pl line 734.
```

I've followed the instructions [here](http://useast.ensembl.org/info/docs/tools/vep/script/vep_download.html) and I had to set up my local Perl libraries per the solution [here](https://github.com/Ensembl/ensembl-vep/issues/149).

### System
- VEP version: 98
- Perl version:  5.20
- OS: Linux 3.10.0-514.el7.x86_64
- tabix installed yes

**Comment by aparton** [comment]
Hi,

The two most common reasons for the VEP version check to fail are:

1) Internet connectivity issues when running the installer
2) Lack of write permissions to the ensembl-vep folder

Could you please check that your internet connection is working properly and that the VEP installer has permission to write in the ensembl-vep directory, and try again?

Failing that, could you please run:

curl https://api.github.com/repos/Ensembl/ensembl-vep | grep default_branch

And send me the output?

Kind Regards,
Andrew

**Comment by nroak** [comment]
This is the output I'm getting for this.
```
[noak@nodecn204 ensembl-vep]$ curl https://api.github.com/repos/Ensembl/ensembl-vep | grep default_branch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6634  100  6634    0     0  16668      0 --:--:-- --:--:-- --:--:-- 16626
  "default_branch": "release/99",
```

**Comment by nroak** [comment]
I'm getting a new error as below:

```
Downloading required Ensembl API files
 - fetching ensembl
 - unpacking ./Bio/tmp/ensembl.zip
 - moving files
 - getting version information
No such file or directory at INSTALL.pl line 734.
```

**Comment by aparton** [comment]
Hi,

Apologies for the slow response. I've looked into this issue this afternoon, and it looks like the VEP installer is successfully downloading necessary files, but failing to write them to disk.

Could you please check:

1) Do you have sufficient space on the disk you are attempting to install VEP on?
2) Are there any *.sub files left in your ensembl-vep folder after the installation fails?

Additionally, could you please send me the output of: _lsb_release -a_ - and I can have a look and see if there's any OS specific issue.

Kind Regards,
Andrew

**Comment by nroak** [comment]
I just confirmed that there is no issue with space and permissions. I will check again if VEP has internet access. That could be a bottleneck. I hope to get answer from our IS team soon.
Here is the output from the command:

```
[noak@nodecn201 ensembl-vep]$ lsb_release -a -
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.3 (Maipo)
Release:	7.3
Codename:	Maipo

```

**Comment by rtyb91** [comment]
Dear Andrew, 

I am having the same issue as nroak does, and I will paste my output from the command you have prompted below:

My problem was:
```
 Downloading required Ensembl API files
 - fetching ensembl
 - unpacking ./Bio/tmp/ensembl.zip
 - moving files
 - getting version information
No such file or directory at d:/huvim/wgs/vep100/install.pl line 734.
```

For the run of curl https://api.github.com/repos/Ensembl/ensembl-vep | grep default_branch, I got

```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6635  100  6635    0     0   6635      0  0:00:01 --:--:--  0:00:01 19287
  "default_branch": "release/100",

```

Lastly I tried running  lsb_release -a  but it wouldn't work on cygwin, hence I have no idea how to proceed from there after.

I am currently trying to run VEP100 from cygwin via a Windows10 terminal for variant filtering for canine genome. 

For the computer space I have 300GB left in the working directory, so I am hoping that it wouldn't be a problem. 

As for.sub file,

**Comment by aparton** [comment]
Hi @nroak, @rtyb91,

Are you still having issues with VEP installation? If so, please let us know and we can take another look.

Kind Regards,
Andrew

**Comment by dglemos** [comment]
I'm going to close this ticket. Please feel free to open a new one if you have more questions.

Best wishes,
Diana
