### ISSUE TITLE
VEP VS Haplosaurus results discrepancy

### ISSUE THREAD

**Issue by iranmdl** [Ensembl/ensembl-vep#676]
## Summary
I have run VEP using a custom database providing a GTF file using --gtf argument. VEP annotates the unique provided input variant as frameshift. However, when I try to run haplosaurus in the same way however, I got the following message:

```
-------------------- WARNING ----------------------
MSG: Haplosaurus can't find transcripts overlapping your variant(s). The output is empty.
FILE: VEP/Haplo/Runner.pm LINE: 213
CALLED BY: ensembl-vep/haplo  LINE: 100
Date (localtime)    = Wed Jan 15 16:34:16 2020
Ensembl API version = 98
```
See the provided input and output files for more debugging.

### Full VEP and haplosaurus command line
```
vep -i variant.vcf --gtf annotation.gtf.gz --fasta genome.fa --force_overwrite

haplo -i variant.vcf -o haplo_output.json --force_overwrite --fasta genome.fa --json --gtf annotation.gtf.gz

```

### Full error message
```
-------------------- WARNING ----------------------
MSG: Haplosaurus can't find transcripts overlapping your variant(s). The output is empty.
FILE: VEP/Haplo/Runner.pm LINE: 213
CALLED BY: ensembl-vep/haplo  LINE: 100
Date (localtime)    = Wed Jan 15 16:34:16 2020
Ensembl API version = 98
```

### Data files

[annotation.gtf.gz](https://github.com/Ensembl/ensembl-vep/files/4065720/annotation.gtf.gz)
[variant_effect_output.txt](https://github.com/Ensembl/ensembl-vep/files/4065721/variant_effect_output.txt)
[genome.fa.zip](https://github.com/Ensembl/ensembl-vep/files/4065728/genome.fa.zip)
[variant.vcf.zip](https://github.com/Ensembl/ensembl-vep/files/4065724/variant.vcf.zip)

**Comment by at7** [comment]
Dear @iranmdl,
thank you for your issue report. There are two reasons why you are not getting any results.
1)your input data needs to be [phased](https://www.ensembl.org/info/docs/tools/vep/haplo/index.html#hp_usage) 
2)the coordinates of your transcript in your input GTF file don't include all the exons and especially not the exon which overlaps the input variant. VEP and Haplosaurus parse GTF files slightly differently which is tailored to how both tools work. 

If you update the start coordinate for your transcript to 1 and change the genotype data to phased genotype data you should get the expected results.

Best wishes,
Anja

**Comment by iranmdl** [comment]
Thank for the quick answer!
I did not realize about the transcript coordinates! That fixed the issue!
Thank you again!
Best,

**Comment by at7** [comment]
Great! Thank you for letting us know.
