### ISSUE TITLE
VEP not annotating all input variants

### ISSUE THREAD

**Issue by benjraspl** [Ensembl/ensembl-vep#677]
I try to annotate a sorted vcf file using the vep and I require the output to have the same amount of variants as the input. However while my input has 80281 entries, my output only has 80069 and I am clueless as to why this is happening.

My vep version is 98.3 and I am using the following flags for running the job:

```*path2vep*/vep --format vcf -i trash_me.vcf -o annotated_trash_me.vcf --vcf --cache --dir_cache *path2cache* --species homo_sapiens --assembly GRCh37 --fork 5 --offline --fasta * path2GRCh37.fa* --force_overwrite --no_stats --af --af_gnomad --sift b --polyphen b --hgvs --hgvsg --custom  *path 2 gnomAD*/gnomAD_genome_r2.1.1.vcf.gz,gnomADg,vcf,exact,0,AF --plugin dbNSFP,*path2dbNFSP*/dbNSFP_hg19_3.5.gz,LRT_score,GERP++_RS,Polyphen2_HVAR_score,SIFT_score --fields Consequence,PolyPhen,SIFT,LRT_score,GERP++_RS,gnomAD_AF,AF,SYMBOL,HGVSp,HGVSg,Existing_variation```

As always any help is greatly appreciated!

**Comment by at7** [comment]
Dear @benjraspl,
have you checked the warnings file for any clues why some of your input variants have been excluded? It should be called annotated_trash_me.vcf_warnings.txt. Are you excluding the header lines in your counts? Could you please run the command again but this time without --plugin, --fields and --custom. This will help me to exclude a few reasons why the variants might be missing.

Thank you,
Anja

**Comment by benjraspl** [comment]
Dear Anja, 

thanks for your fast reply! The header lines are excluded in the counting of lines and sadly I did not recieve a warnings file for my job. I am currently running the job w/o the plugins, fields and custom flags and also removed to no_stats flag for good measure. I will get back to you as soon as my job is finished!

Best, Benjamin

**Comment by benjraspl** [comment]
So the jobs just finished and i checked the counts output files, the variants are exactly the same. I also checked the counts again - they did include  header lines (sorry for that) but still the number of variants differ between in and output! (As can be seen in the summary.html). Sadly there weren't any warnings file outputted for any of the jobs.

I uploaded the in- and output files can be found below:

[input.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/4071938/input.vcf.gz)
[normal_output.tsv.gz](https://github.com/Ensembl/ensembl-vep/files/4071973/normal_output.tsv.gz)    (regular flags w/o no_stats output)
[no_pluginsetc_output.tsv.gz](https://github.com/Ensembl/ensembl-vep/files/4071975/no_pluginsetc_output.tsv.gz)    (no plugins, custom or fields output)
[output_summary.html.gz](https://github.com/Ensembl/ensembl-vep/files/4071937/output_summary.html.gz) 
(I only uploaded of the summarys since they are both the same)

Any more ideas what could cause this?
Best,
Benjamin

**Comment by at7** [comment]
Thank you for the input file. That should help me to reproduce your results and hopefully also find the reason for the missing variants. I get back to you as soon as I know more.

**Comment by at7** [comment]
Your input file contains 221 variants without an alt allele. The alt is only given as '.' for example:
`17      37822311        177801  A       .       .       .       .`
VEP ignores those input lines and that explains the discrepancy in counts.

Best wishes,
Anja
