### ISSUE TITLE
WARNING: Plugin 'CADD' went wrong: ERROR: No start specified 

### ISSUE THREAD

**Issue by ZhangXiujuan** [Ensembl/ensembl-vep#678]
Hi，

I am using vep(v97.3) to annotate vcf, and I get the following error:
```
WARNING: 8414 : WARNING: Plugin 'CADD' went wrong: ERROR: No start specified
WARNING: Plugin 'CADD' went wrong: ERROR: No start specified
```

command line:
```
vep -i ${vcf} -o ${out} --force --no_stats --cache --offline --dir ${vep_cache} --fasta ${fa} --refseq --use_given_ref --exclude_predicted --vcf --assembly GRCh38 --plugin CADD,${cadd.snv},${cadd.indel} --fork 20
```

Any suggestions？
Thanks.

**Comment by at7** [comment]
Dear @ZhangXiujuan,

the error message suggests that at least on of your input variants has a start position which is smaller or equal to 2. The plugin uses those input coordinates to fetch data from the CADD file. However, for the start position it subtracts 2 to make sure that indels are included when fetching data from the CADD file. I updated the CADD plugin to check the start position before subtracting. Could you please update the [CADD plugin](https://github.com/Ensembl/VEP_plugins/blob/release/97/CADD.pm) and let me know if this resolves the problem?

Best wishes,
Anja

**Comment by ZhangXiujuan** [comment]
I updated the `CADD.pm`, but still reported that error.
And i found a special mutation starting with `1`.

**Comment by at7** [comment]
I tested the plugin with a single variant. Could you please use my input file
[pos_one_variant.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/4098061/pos_one_variant.vcf.gz) to see if it is throwing a warning? If it does throw the same warning could you please check that the correctly updated CADD.pm file is used? And if it doesn't throw a warning could you please share your variant starting at position 1? I will try and reproduce the error with your input data.
Thank you,
Anja
