### ISSUE TITLE
ERROR: Forked process(es) died

### ISSUE THREAD

**Issue by Sbeaum** [Ensembl/ensembl-vep#68]
Hi team VEP!

I have a new error when I'm running VEP today on  my dataset. Curiously it appear only when I have mutltiple sample in the VCF : 
```-------------------- EXCEPTION --------------------
MSG: 
ERROR: Forked process(es) died

STACK Bio::EnsEMBL::VEP::Runner::_forked_buffer_to_output /resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:515
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:331
STACK Bio::EnsEMBL::VEP::Runner::run /resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:193
STACK toplevel /resources/ensembl-vep/vep:211
Date (localtime)    = Wed Aug  2 11:13:51 2017
Ensembl API version = 89
---------------------------------------------------```

Any idea ?

Thank you in advance for you help !

**Comment by willmclaren** [comment]
Can you provide the command you are running, and preferably a sample of input that recreates the issue?

That error message is pretty generic.

**Comment by Sbeaum** [comment]
It seems to be a problem with the GeneSplicer plugins. 

`
vep  -i 1600_multi_sample.vcf --offline --cache --sift b --fork 4 --dir_cache /data/resources/human/GRCh37/index/vep --buffer_size 250 --vcf -o /tmp/1600_vep.vcf --fasta /data/resources/human/GRCh37/fasta/GRCh37.fa --refseq --cache_version 89 --no_stats --no_progress --force_overwrite --dir_plugins /data/resources/vep_plugins --plugin GeneSplicer,/data/resources/vep_plugins/GeneSplicer/bin/linux/genesplicer,/data/resources/vep_plugins/GeneSplicer/human,context=200,tmpdir=/tmp
`

When I run this command, RAM get filled and vep crash. I tried to update the plugin but the problem is still here. Here the corresponding chunck : 
[1600_multi_sample.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/1197369/1600_multi_sample.vcf.gz)

**Comment by willmclaren** [comment]
I can recreate the runaway memory issue. It seems to be a problem with the Bio::DB::Fasta module that is used when Bio::DB::HTS is not available.

Bio::DB::HTS is set up by INSTALL.pl - I assume you had problems setting it up or skipped that step? I'd recommend retrying (manually if need be, see https://github.com/Ensembl/Bio-DB-HTS) as there doesn't seem to be any memory issue with this.

**Comment by willmclaren** [comment]
I've tracked it down to an issue with the plugin actually, fixed on release/89 now (https://github.com/Ensembl/VEP_plugins/commit/1056a24b24a4b778195f155396694911fe0c9743)
