### ISSUE TITLE
Feature with dupl (e.g. NM_001122636.1_dupl17.1) in GRCh37 Refseq cache

### ISSUE THREAD

**Issue by cruckert** [Ensembl/ensembl-vep#688]
Using VEP version 99 with refseq cache some of my variants get annotated with strange transcripts:

13_114435807_A/G with NM_002929.2_dupl18.1

12_132853709_C/T with NM_001122636.1_dupl17.1
[](url)
There was a [Biostars posting](https://www.biostars.org/p/312593/) 2 years ago  saying it will be fixed and with advice to ignore these annotations, as they are duplicates of the same transcript with another version number. But for the two examples above there is no second version of the same transcript in the output, so ignoring them would lead to a complete miss of this transcript.

**Comment by aparton** [comment]
Hi,

Thanks for this report. I've been able to reproduce this at my end, I'll look into the source of these transcripts and get back to you when I know more.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi @cruckert,

Thanks for this report. The BioStars link is correct, these transcripts can be ignored. For both of the example transcripts provided, the associated 'non-dup' transcript is in fact in a different location, so missing the transcript is the correct way to interpret this result.

We are making significant updates to our GRCh37 annotations for Ensembl 100, currently scheduled for release in late March/early April, so these transcripts should be removed by then.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi @cruckert,

Just to let you know, Ensembl 100 has now been released, so this issue should now be resolved. If you still see any issues, please let us know and we'll see what we can do to help.

Kind Regards,
Andrew
