### ISSUE TITLE
Conflicting c.HGVS annotation

### ISSUE THREAD

**Issue by crispgc** [Ensembl/ensembl-vep#691]
Hi,
I'm annotating human variants with the VEP tool (version 99.1 for cache files and VEP software) and I might have detected an issue with a variant. Concretely, I'm talking about the variant 10:89720852-C-T, from which I've seen diferent cHGVS annotation in different platforms/websites:

- Ensembl-VEP:
  - NM_000314.4:c.1003C>T
  - **NM_000314.6:c.1004C>T**
- ClinVar:
  - NM_000314.7:c.1003C>T (https://www.ncbi.nlm.nih.gov/clinvar/variation/7833)
- dbSNP
  - NM_000314.4:c.1003C>T (https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?do_not_redirect&rs=rs121909231)
  - NM_000314.6:c.1003C>T (https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?do_not_redirect&rs=rs121909231)

The last version of the transcript being annotated is in conflict with the rest of them, and more importantly, with dbSNP and ClinVar.
I know that different versions of transcripts might give different HGVS notations, but the conflict with dbSNP and the consistent notation c.1003C>T worries me. Is there any explanation for this? Any thing that I might try to get the (I assume) correct annotation?

Thanks in advance,
Cristian.

**Comment by aparton** [comment]
Hi Jonas,

Thanks for this report, it is an issue we are aware of. As you probably know, not all RefSeq transcripts completely match the reference genome. In cases where they don't, we are now using alignment files provided by NCBI to create a new reference, matching the transcript, and use this for consequence calling.

Our HGVS calculation does not currently use this reference modification, but it is something we are working on and aim to include in release 100, currently scheduled for release at the end of March. VEP can report reference mismatches for GRCh38, but these data are not available for GRCh37.
More details on the differences to the reference genome and correcting transcript models using BAM can be found here:  https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#refseq

Kind Regards,
Andrew

**Comment by crispgc** [comment]
Hi @aparton,

As I understand from your answer, the feature would be available for GRCh37?

Best Regards and thanks for the quick answer.
Cristian

**Comment by aparton** [comment]
Hi,

Sorry for the delay in getting back to you. Yes, this feature will be available for GRCh37 in release 100, currently scheduled for release in April.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi @crispgc,

Just to let you know, Ensembl 100 has now been released, so this issue should now be resolved. If you still see any issues, please let us know and we'll see what we can do to help.

Kind Regards,
Andrew
