### ISSUE TITLE
Debug output issue

### ISSUE THREAD

**Issue by NLSVTN** [Ensembl/ensembl-vep#694]
I am having issues debugging **VEP** because it is hanging without giving me any output. I posted the issue on 2 different forums:

https://discuss.hail.is/t/no-vep-debug-output/1302
https://www.biostars.org/p/423083/

Basically what happens is that after certain point while fixing issues (for instance absent cache files) with VEP, it stopped producing any output instead just hanging. When I run it through **Hail** **luigi** pipeline, it fails, but when I submit it either to **spark-submit** or just run in terminal, nothing happens.

If I test **VEP** it seems to be working just fine:

`./vep -i examples/homo_sapiens_GRCh38.vcf --cache --dir_cache /vep/vep_cache`

Generating the output files that look right

**Comment by aparton** [comment]
Hi,

Unfortunately if VEP is working fine then we will be unable to help you debug this issue, as it looks as if it's related to your Hail Luigi pipeline. 

However, the VEP command you mentioned on BioStars asks VEP to provide a lot of annotations - with the --everything flag switched on and multiple plugins, then VEP can take a long time to produce a result. A list of possible optimisations can be found here, and this may be of benefit to you - https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#faster

Kind Regards,
Andrew

**Comment by NLSVTN** [comment]
Not really, regular VEP command that you can find in the attached links is not working. So, simple command for testing is working but the real world one is not.
