### ISSUE TITLE
DBD::SQLite::db prepare failed: no such table: phylocsf_summary

### ISSUE THREAD

**Issue by NLSVTN** [Ensembl/ensembl-vep#696]
I am trying to run **loftee** as a part of **VEP** with the following command:

`/vep/ensembl-tools-release-95/vep -i SF0637658_WES_CIDR.vcf --format vcf --json --everything --allele_number --no_stats --cache --offline --minimal --verbose --assembly GRCh38 --dir_cache /vep/vep_cache --fasta /vep/homo_sapiens/95_GRCh38/hg38.fa --plugin LoF,loftee_path:/vep/loftee_grch38,gerp_bigwig:/vep/loftee_data_grch38/gerp_conservation_scores.homo_sapiens.GRCh38.bw,human_ancestor_fa:/vep/loftee_data_grch38/human_ancestor.fa.gz,filter_position:0.05,min_intron_size:15,conservation_file:/vep/loftee_data_grch38/phylocsf_gerp.sql,run_splice_predictions:0 --dir_plugins /vep/loftee_grch38 -o vep_output`

The error that I am getting seems to be all about **conservation_file**:

> DBD::SQLite::db prepare failed: no such table: phylocsf_summary at /var/lib/spark/vep/loftee_grch38/LoF.pm line 553, <__ANONIO__> line 15156.

I tried supplying as conservation file **phylocsf_gerp.sql.gz**, **phylocsf_gerp.sql**, **loftee.sql** but none really works.

How could it be fixed? 

I have also installed **PhyloCSF** and placed it on the **PATH**. Not sure whether it is needed.
The version of **VEP** that I am using is **99**. I checked out the correct **grch38** **loftee** branch, and **_not just master_**. My OS is the following:

```
(py37) -bash-4.2$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.7 (Maipo)
Release:	7.7
Codename:	Maipo
```

**Comment by at7** [comment]
Hello,
we are not looking after the LoF plugin. Could you please ask questions related to the plugin [here](https://github.com/konradjk/loftee)?
Best,
Anja

**Comment by NLSVTN** [comment]
Sounds good, already asked, just that provided files for **loftee** are actually different in **VEP** **README** and **loftee's**
