### ISSUE TITLE
.fa.index: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by NLSVTN** [Ensembl/ensembl-vep#699]
## Describe the issue
The bug is identical to the previously closed issue where it is not specified how to actually solve it:

https://github.com/Ensembl/ensembl-vep/issues/211

## Additional information
Please, see the comment by **_meyermj_** with the respective stack trace.

### System
- VEP version: 99
- VEP Cache version: 99
- Perl version: 5.16.3
- OS: Red Hat Enterprise Linux Server release 7.7 (Maipo)
- tabix installed 1.3.2

Could you please, look over the closed ticket's end? How to make the index working or allow for VEP to run without it?

**Comment by helensch** [comment]
Hi

Information on using FASTA file with VEP is  described at
https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#fasta

Please could you provide the full VEP command you are using.

Please could you let me know:
- if VEP was used to index the FASTA file
- if you have Bio::DB::HTS installed

Helen

**Comment by NLSVTN** [comment]
From my understanding the first time **VEP** is run, the index will be generated. I just downloaded the actual fasta file and did not really do anything else with it specifically by myself. I checked with `perldoc -l Bio::DB::HTS` and this package is not there.

**Comment by NLSVTN** [comment]
I installed also `Bio::DB::HTS` with `htslib` but it did not help.

**Comment by helensch** [comment]
Thanks for the information. 

After running the command, was a fasta index file  created in /vep/homo_sapiens/GRCh38/?

After installing Bio::DB::HTS and running the command, what error message did you get? 

Please could you try running the command with a small test input file and without using plugins.

**Comment by NLSVTN** [comment]
Ok, I was able to solve it by:

> 1. Delete previously generated from **fasta** file **.fa.index** file
> 2. git clone git://github.com/samtools/htslib.git
>     cd htslib
>     make
>     export HTSLIB_DIR=/vep/htslib
> 3. cpanm Bio::DB::HTS

Then, rerunning **VEP** in the absence of previously generated index works fine.
