### ISSUE TITLE
Can't call method "strand"

### ISSUE THREAD

**Issue by arthurmelobio** [Ensembl/ensembl-vep#70]
Hi @willmclaren ,

I have tried to functionally annotate SNPs between two close related wheat genomes. So, I'm using a own genome sequence fasta file as well the GTF file. I had processed the GTF file and then run vep with the follow command line.

`$ grep -v "#" genome.annot.gtf | sort -k1,1 -k4,4n -k5,5n | bgzip -c > genome.annot.gtf.gz`
`$ tabix -p off genome.annot.gtf/gz`
`$ /path/to/vep/vep -i input.vcf --format vcf -o VEPout.txt --force_overwrite --variant_class --regulatory --symbol --stats_text --fasta genome.seq.fa --gtf genome.annot.gtf.gz`

My VCF input is v.4.0 and looks like:
##fileformat=VCFv4.0
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=chr4B,length=673896466>
##bcftools_viewVersion=1.2+htslib-1.2.1
##bcftools_viewCommand=view -m2 -M2 svevo.CDS.4B.3.vcf
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr4B	88144	.	G	A	32.1796	.	.
chr4B	172580	.	C	T	32.1796	.	.
chr4B	172614	.	C	T	32.1796	.	.
chr4B	179481	.	G	T	32.1796	.	.

Seems the analysis starts normally ... then print 
`Can't call method "strand" on unblessed reference at /home/arthur/Bioinfo_Softwares/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm line 105, <__ANONIO__> line 5007.`

I cannot see any issue with line 5007 from the VCF input:
chr4B   436179505       .       G       C       32.1796 .       .

What this method "strand" means and why the script cannot call it?

Thank you very much for the advice.

**Comment by willmclaren** [comment]
It might be there's an issue with your GTF. Check that you have the strand column correctly set for each line in the GTF (col 7 should be `+` or `-`).

If the problem persists could you please share a snippet of your GTF, preferably a whole gene with component parts.

**Comment by arthurmelobio** [comment]
Dear @willmclaren,

Thank you for your replay. 

I have found some of the variants on GTF that has `.` instead `+` or `-` and after fix this, the analysis runs without any error or warning message. 

However, I still getting all variants annotated as "intergenic_variant". 90-95% of "intergenic_variant" seems fine, but 100% seems something is not working correctly. I have checked my ID's again and it matches among all files (VCF, GTF and FASTA ). Looking more detail in these files, I can see examples with weird results:

The VEP output reports:

`.	chr4B:88144	A	-	-	-	intergenic_variant	-	-	-	-	-	-	IMPACT=MODIFIER;VARIANT_CLASS=SNV`
`.	chr4B:460129	A	-	-	-	intergenic_variant	-	-	-	-	-	-	IMPACT=MODIFIER;VARIANT_CLASS=SNV`


For those variants, the GFT file has:

`chr4B	WEWseq_PGSB_v1	exon	88128	88255	.	+	.	NA	gene_id	TRIDC4BG000010	transcript_id	TRIDC4BG000010.1	confidence_class	HC_G	Fatty acyl-CoA reductase 1`
`chr4B	WEWseq_PGSB_v1	CDS	88128	88255	.	+	0	NA	gene_id	TRIDC4BG000010	transcript_id	TRIDC4BG000010.2	confidence_class	HC_G	Fatty acyl-CoA reductase 1` 

`chr4B	WEWseq_PGSB_v1	exon	460072	460337	.	+	.	NA	gene_id	TRIDC4BG000100	transcript_id	TRIDC4BG000100.1	confidence_class	HC_G	GDSL esterase/lipase`
`chr4B	WEWseq_PGSB_v1	CDS	460072	460352	.	+	2	NA	gene_id	TRIDC4BG000100	transcript_id	TRIDC4BG000100.2	confidence_class	HC_G	GDSL esterase/lipase`

So, I cannot understand why in situations like that, the variants are annotated as "intergenic_variant". I guess the GTF file I'm using has enough information for a more detailed annotation.

Thank you again for all these helps.

Best,
Arthur

**Comment by sarahhunt** [comment]
Hi @arthurmelobio,

The GFF needs to contain specific information to be parsed by VEP. I would guess your file is missing something. There is information of GFF requirements here:

http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff

**Comment by arthurmelobio** [comment]
Hi @sarahhunt ,

Thank you for the insight. It makes a lot of sense. After some works in my GTF file, the analysis finally runs successfully. 

Thank you.

**Comment by sarahhunt** [comment]
Hi @arthurmelobio ,

Thanks for letting us know it's working for you now.

All the best.

Sarah
