### ISSUE TITLE
Documentation of Nonsense Mediated Decay Inference Rule

### ISSUE THREAD

**Issue by DarioS** [Ensembl/ensembl-vep#701]
I notice that some variants are annotated as stop_gained but others are stop_gained,NMD_transcript_variant. Likewise, I also see some which are missense_variant and others which are missense_variant,NMD_transcript_variant. There's no explanation I can find in the user guide or the journal article about what logic is used to determine if a variant gets NMD status or not. I am hoping to use the NMD_transcript_variant status to help restrict which variants I should be observing in RNA-seq reads and those I would expect to be absent because the transcript is rapidly degraded. I would like this detail to be present in the user guide.

**Comment by dglemos** [comment]
Hello @DarioS,

VEP determines a variant is `NMD_transcript_variant` if that variant is in a transcript that is the target of NMD (transcript with nonsense_mediated_decay biotype) and that consequence is added to other consequences the variant may also have. 

The documentation about VEP calculated consequences can be found here: 
https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html

**Comment by DarioS** [comment]
> ... a transcript that is the target of NMD ...

But how is that determined? What decision rules or databases are used to make that statement? I can't find the source documented anywhere.

**Comment by DarioS** [comment]
I just figured it out. The `NMD_transcript_variant` value has nothing to do with the SNV the user provides for annotation. It it taken directly from the ENSEMBL transcript type database. For example, ENST00000557057.5 has Type "Nonsense mediated decay" which is converted to NMD_transcript_variant by Variant Effect Predictor. I don't think it's a good idea to have stop_gained,NMD_transcript_variant in the consequence column of the results. One value is related to the SNV of the patient analysed (stop_gained) but the second value is not directly related to the particular SNV; it will appear for any patient which has any SNV that overlaps the transcript with Type "Nonsense mediated decay".

How can end-users identify SNVs in their samples that cause a mutation which is likely to be degraded by nonsense-mediated decay rather than just merely reference transcripts in the ENSEMBL database which are already annotated with NMD?

**Comment by dglemos** [comment]
I wasn't very clear when I tried to explain, sorry about that. But that's right, VEP only uses the term `NMD_transcript_variant` to indicate an overlap with an NMD transcript. It doesn't call a variant NMD_transcript_variant because the variant is likely to be degraded by nonsense-mediated decay.
