### ISSUE TITLE
Weird behavior with --cache and --offline flag

### ISSUE THREAD

**Issue by NTNguyen13** [Ensembl/ensembl-vep#702]
## Describe the issue
I want to annotate my vcf, I have already downloaded the cache and fasta for both GRCh37 and GRCh38.
When I used :
```
vep --cache -a GRCh37 \
-i sample_hg19.vcf \
-o sample_hg19_vep_clin.txt \
--check_existing
```

I got this error:
```
MSG: ERROR: Assembly version specified by --assembly (GRCh37) and assembly version in coord_system table (GRCh38) do not match

If using human GRCh37 add "--port 3337" to use the GRCh37 database, or --offline to avoid database connection entirely

```

Then I used 
```
vep --offline -a GRCh37 \
-i sample_hg19.vcf \
-o sample_hg19_vep_clin.txt \
--check_existing
```

and also 

```
vep --cache --port 3337-a GRCh37 \
-i sample_hg19.vcf \
-o sample_hg19_vep_clin.txt \
--check_existing
```

I got this error:
`[E::fai_build3_core] Cannot index files compressed with gzip, please use bgzip
`

I have also check `perl INSTALL.pl` and all dependencies are installed

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 99.2
- VEP Cache version: GRCh37 and GRCh38
- Perl version: 5.26.1
- OS: Ubuntu
- tabix installed: yes

**Comment by dglemos** [comment]
Hello @NTNguyen13 ,
1) Does VEP work successfully when connected to the database with `--database`?
2) Did you download the cache files through the installer? 
3) What do you get when you run `perl -e 'use Bio::DB::HTS::Faidx'`?

**Comment by NTNguyen13** [comment]
Hi @dglemos 
1, When I change the `cache` with `database`, this error appear:
```
MSG: ERROR: Assembly version specified by --assembly (GRCh37) and assembly version in coord_system table (GRCh38) do not match

If using human GRCh37 add "--port 3337" to use the GRCh37 database, or --offline to avoid database connection entirely

STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /home/thanh/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:127
STACK Bio::EnsEMBL::VEP::Runner::init /home/thanh/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:118
STACK Bio::EnsEMBL::VEP::Runner::run /home/thanh/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /home/thanh/ensembl-vep/vep:224
Date (localtime)    = Wed Mar  4 15:14:03 2020
Ensembl API version = 99
```

2, Yes, I choose both GRCh37 and GRCh38 during installation.

3, This is what I got from running that command
```
Can't locate Bio/DB/HTS/Faidx.pm in @INC (you may need to install the Bio::DB::HTS::Faidx module) (@INC contains: /home/thanh/perl5/lib/perl5/5.26.1/x86_64-linux-gnu-thread-multi /home/thanh/perl5/lib/perl5/5.26.1 /home/thanh/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/thanh/perl5/lib/perl5 /home/thanh/perl5/lib/perl5/5.26.1/x86_64-linux-gnu-thread-multi /home/thanh/perl5/lib/perl5/5.26.1 /home/thanh/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/thanh/perl5/lib/perl5 /home/thanh/perl5/lib/perl5/5.26.1/x86_64-linux-gnu-thread-multi /home/thanh/perl5/lib/perl5/5.26.1 /home/thanh/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/thanh/perl5/lib/perl5 /home/thanh/perl5/lib/perl5/5.26.1/x86_64-linux-gnu-thread-multi /home/thanh/perl5/lib/perl5/5.26.1 /home/thanh/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/thanh/perl5/lib/perl5 /home/thanh/BioPerl-1.6.924/ /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /home/thanh/perl5/lib/perl5/5.26.0 /home/thanh/perl5/lib/perl5/5.26.0/x86_64-linux-gnu-thread-multi /home/thanh/perl5/lib/perl5/5.26.0 /home/thanh/perl5/lib/perl5/5.26.0/x86_64-linux-gnu-thread-multi /home/thanh/perl5/lib/perl5/5.26.0 /home/thanh/perl5/lib/perl5/5.26.0/x86_64-linux-gnu-thread-multi /home/thanh/perl5/lib/perl5/5.26.0 /home/thanh/perl5/lib/perl5/5.26.0/x86_64-linux-gnu-thread-multi /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.

```

**Comment by NTNguyen13** [comment]
I have tried vep on `-a GRCh38`, it still works fine

**Comment by dglemos** [comment]
When running VEP you can:
1. connect to the database using `--database` and if you want to use assembly GRCh37 `-a GRCh37` you need to point to the right port with `--port 3337`, that's probably why you get the error for GRCh37 and not for GRCh38. 
2. use cache with `--cache` and if you want to run completely offline you can add `--offline` flag.
[Annotation sources documentation here](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache)

When using --cache or --offline VEP retrieves reference sequence locally from a fasta file. Your error `[E::fai_build3_core] Cannot index files compressed with gzip, please use bgzip` seems to be related with this file. [Fasta files documentation here](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#fasta) and [download fasta GRCh37 here](ftp://ftp.ensembl.org/pub/grch37/release-99/fasta/homo_sapiens/dna/) 

Could you try running VEP pointing to a fasta file, something like:
```
vep --offline --cache -a GRCh37 --fasta /my_dir/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz \
-i sample_hg19.vcf \
-o sample_hg19_vep_clin.txt \
--check_existing
```

**Comment by NTNguyen13** [comment]
I have tried the above command, it has this error:

```
[E::fai_build3_core] Cannot index files compressed with gzip, please use bgzip
Segmentation fault (core dumped)
```

Maybe the fasta file has some error, am I right?

**Comment by NTNguyen13** [comment]
Hi, I have downloaded a new fasta from ensembl-VEP and the it's working fine now, thank you for pointing out the problem

**Comment by dglemos** [comment]
Good to know the problem has been solved. If you have any other questions feel free to ask.
