### ISSUE TITLE
Can't get GNOMAD Frequency to work Using VEP

### ISSUE THREAD

**Issue by marianakhoul** [Ensembl/ensembl-vep#708]
Hello,

I am trying to Run VEP to get the gnomad frequencies for some variants I have that are annotated.
My input file:
#CHROM	POS	ID	REF	ALT
1	1737915	745971	T	C
1	1737915	1346473	T	G
1	1737916	1026499	T	C
1	1737940	116121	T	C
1	1737942	905125	A	G

the IDs are generated at random. 
I am Using VEP version 99 and GRCh38.

to get the gnomad frequencies I am using the below command:
./ensembl-vep/vep -i ./data/new_VEP_input.txt -o ./RHP_variant.VEP.OUTPUT.TXT --cache --offline --af_gnomad --max_af --fasta /apps/Homo_sapiens_assembly19.fasta --dir_cache ./ensembl-vep/vep_data/

this is one of the outputs from the VEP that I am obtaining:
108121703	11:108121703	G	ENSG00000075239	ENST00000299355	Transcript	intron_variant	-	-	-	-	-	rs1294537526	IMPACT=MODIFIER;STRAND=1;gnomAD_AF=6.941e-06;gnomAD_AFR_AF=0;gnomAD_AMR_AF=0;gnomAD_ASJ_AF=0;gnomAD_EAS_AF=0;gnomAD_FIN_AF=0;gnomAD_NFE_AF=1.886e-05;gnomAD_OTH_AF=0;gnomAD_SAS_AF=0;MAX_AF=1.886e-05;MAX_AF_POPS=gnomAD_NFE

for 11-108121703 on the Gnomad Website (https://gnomad.broadinstitute.org/variant/11-108121703-A-G?dataset=gnomad_r2_1) the rsid of this variant is:rs56365018 while from VEP I am getting rs1294537526 and this gets me the gnomad frequencies for rs1294537526 instead of the variant I input.

How can I fix this issue?

I am relatively new to VEP so any help would be much appreciated!!

Thank you,
Maria Nakhoul

**Comment by aparton** [comment]
Hi,

Thanks for your query. Your reference genomes appear to be mixed up - you state that you’re using GRCh38, however the attached gnomad link you’ve sent is using GRCh37. Additionally, the overlapping transcript that VEP has found is in that location on GRCh38 (so I assume your cache file is for GRCh38), however your fasta file is tagged assembly19.fasta, so I assume that’s using GRCh37.

Ensuring that all of your inputs are using the same assembly should resolve your issue.

If you have any other questions, please don’t hesitate to ask.

Kind Regards,
Andrew

**Comment by marianakhoul** [comment]
Thank you for your reply!
The solution you proposed worked!

There are still cases that aren't being annotated but are present on the Gnomad Website (https://gnomad.broadinstitute.org/). Could this be an issue version? Since VEP uses gnomad v 2.1 and the website is v2.1.1?

**Comment by aparton** [comment]
Hi,

Thanks for this report. I've looked into this variant, and it does indeed look like a versioning issue. While this variant is included within gnomAD 2.1, the variant has been updated in dbSNP and our cache files are only including the updated variant. 

Kind Regards,
Andrew

**Comment by marianakhoul** [comment]
Hello,

That makes more sense now. Is there a gnomAD 2.1.1 in VEP? I am downloading the gnomad.exomes.r2.1.1.sites.vcf.bgz file and I saw that on the website it said I can use the following command:
./vep -i examples/homo_sapiens_GRCh38.vcf --cache \
--custom gnomad.genomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF_AFR,AF_AMR,AF_ASJ,AF_EAS,AF_FIN,AF_NFE,AF_OTH

so would:
./vep -i new_VEP_input.txt -cache \
 --custom gnomad.exomes.r2.1.1.sites.vcf.bgzvcf,exact,0,AF_AFR,AF_AMR,AF_ASJ,AF_EAS,AF_FIN,AF_NFE,AF_OTH

possibly get me what I need?

thank you,
Maria Nakhoul

**Comment by aparton** [comment]
Hi,

Yes, you can use our custom annotation functionality if you're looking to use a different version of ClinVar. You can find more information on our custom annotation functionality here: https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html

Kind Regards,
Andrew

**Comment by marianakhoul** [comment]
thank you!

**Comment by marianakhoul** [comment]
Are the custom file outputs supposed to look like this:
```
ENSG00000078369	ENST00000434686	Transcript	missense_variant	373	186	62	H/Q	caC/caG	-	IMPACT=MODERATE;STRAND=-1;FLAGS=cds_end_NF;gnomADg=rs747574579;gnomADg_FILTER=PASS
1346474	1:1747212	C	ENSG00000078369	ENST00000437146	Transcript	missense_variant	286	186	62	H/Q	caC/caG	-	IMPACT=MODERATE;STRAND=-1;FLAGS=cds_end_NF;gnomADg=rs747574579;gnomADg_FILTER=PASS
```

Or should I be getting a gnomad Frequency value?

thank you,
Maria Nakhoul
