### ISSUE TITLE
Double annotation with custom annotation (VCF)

### ISSUE THREAD

**Issue by stefandiederich** [Ensembl/ensembl-vep#71]
Hi, 
I use the a custom VCF file (allele frequencies from own database) to annotate my variants. If I have multiple alleles at the same postion in my custom VCF file VEP does not pick the correct one for annotating my variant VCF file. 

Small example:
Custom VCF file:
`17	17697101	het:1/137--hom:0/137	AGCAG	A`
`17	17697101	het:1/137--hom:0/137	AGCAG	ACAG`
`17	17697101	het:56/137--hom:16/137	AG	A`

Variant VCF file line:
`chr17	17697101	.	AG	A	468.73	.	AC=1;AF=0.500;AN=2;BaseQRankSum=-1.933;ClippingRankSum=0.000;DP=33;ExcessHet=3.0103;FS=3.419;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.000;QD=14.20;ReadPosRankSum=0.700;SOR=0.257	GT:AD:DP:GQ:PL	0/1:14,19:33:99:506,0,633`

Im my oppinion VEP should only report the third entry of my custom VCF file, but it reports all entries. Am I doing something wrong?

Thanks in advance.
Kind regards 
Stefan Diederich

**Comment by at7** [comment]
You are correct that only the third entry should be used for annotation because it matches the allele from the input VCF. Could you please share the options which you use for the custom annotation and the ensembl-vep release you are using? Thank you.

**Comment by stefandiederich** [comment]
Dear Anja,

thanks for your quick response!

Iam using ensemble-vep version 89.0

The option for the custom annotation is: -custom '/media/Berechnungen/AnnotationDBs/ihdb/current/ihdb_count.vcf.gz',IHDB_Count,vcf,exact,0

The whole command of vep I’m using is the following:

vep --offline --dir '/media/Berechnungen/AnnotationDBs/vep' --fasta /media/Berechnungen/Referenzgenom/HG19/HG19.karyo.fasta.VEP.fa --everything --assembly GRCh37 -i /media/Ergebnisse/0202-17_Exom\ \(Epilepsie\)_NB501654_0030/0202-17.vcf -o /media/Ergebnisse/0202-17_Exom\ \(Epilepsie\)_NB501654_0030/0202-17.annot.neu.vcf --plugin CADD,'/media/Berechnungen/AnnotationDBs/cadd/20160314/whole_genome_SNVs.tsv.gz','/media/Berechnungen/AnnotationDBs/cadd/20160314/cadd_InDels.tsv.gz' --plugin LoFtool -custom '/media/Berechnungen/AnnotationDBs/phylop/20160314/hg19.100way.phyloP100way.sorted.bedgraph.gz',PhyloP,bed,exact,0 -custom '/media/Berechnungen/AnnotationDBs/ihdb/current/ihdb_af.vcf.gz',IHDB_AF,vcf,exact,0 -custom '/media/Berechnungen/AnnotationDBs/ihdb/current/ihdb_count.vcf.gz',IHDB_Count,vcf,exact,0 -custom '/media/Berechnungen/AnnotationDBs/omim/20160315/omimInheritanceHG19.sorted.bed.gz',OMIM,bed,overlap,0 --buffer_size 10000 --vcf --pick --pick_order rank,canonical,appris,tsl,biotype,ccds,length --force_overwrite --fork 14


Thanks
Stefan Diederich
________________________________________
Stefan Diederich
M. Sc. Bioinformatik

Universitätsmedizin
der Johannes Gutenberg-Universität Mainz
Langenbeckstraße 1, 55131 Mainz
Tel.: 06131 17-5797

Von: Anja Thormann [mailto:notifications@github.com]
Gesendet: Dienstag, 29. August 2017 17:07
An: Ensembl/ensembl-vep
Cc: Diederich, Stefan; Author
Betreff: Re: [Ensembl/ensembl-vep] Double annotation with custom annotation (VCF) (#71)


You are correct that only the third entry should be used for annotation because it matches the allele from the input VCF. Could you please share the options which you use for the custom annotation and the ensembl-vep release you are using? Thank you.

**Comment by at7** [comment]
Dear Stefan,
this is something we have been working on and the updated code has now been [released](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#new). We explain [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#colocated) how we match alleles. For your example we match AGCAG ACAG and AG A. AGCAG ACAG can be reduced to AG A.

**Comment by stefandiederich** [comment]
Dear Anja,

I just installed version 90.1. As I understood you right, I have to prepare my VCF files in a different way and merge all these Variants to one entry of AG>A?

Kind regards
Stefan

________________________________________
Stefan Diederich
M. Sc. Bioinformatik

Universitätsmedizin
der Johannes Gutenberg-Universität Mainz
Langenbeckstraße 1, 55131 Mainz
Tel.: 06131 17-5797

Von: Anja Thormann [mailto:notifications@github.com]
Gesendet: Mittwoch, 30. August 2017 11:01
An: Ensembl/ensembl-vep
Cc: Diederich, Stefan; Author
Betreff: Re: [Ensembl/ensembl-vep] Double annotation with custom annotation (VCF) (#71)


Dear Stefan,
this is something we have been working on and the updated code has now been released<http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#new>. We explain here<http://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#colocated> how we match alleles. For your example we match AGCAG ACAG and AG A. AGCAG ACAG can be reduced to AG A.

**Comment by at7** [comment]
You don't need to merge the alleles. The VEP will compare alleles from the custom annotation VCF file to the alleles from your input VCF file. The underlying VEP code will apply a comparison which will match AGCAG ACAG  from the custom annotation file to AG A in your input VCF file. After updating to version 90.1 just run your command as before and you should see that only 2 of the entries from your custom annotation file will be used for annotating your example variant.

**Comment by stefandiederich** [comment]
Oh yes I see, but it is not possible to get only one entry?
So I have to handle this in my application which is reading the vcf file. But that should not be a problem…

One other question, maybe an new topic:
In version 90.1 I get gnomAD annotations, what I do not understand is, why I get MAX_AF and MAX_AF_POPS but no gonmAD_AF annotation. When I then look for this variant in gnomAD browser there are a lot of AF information for every population. Am I doing something wrong?

________________________________________
Stefan Diederich
M. Sc. Bioinformatik

Universitätsmedizin
der Johannes Gutenberg-Universität Mainz
Langenbeckstraße 1, 55131 Mainz
Tel.: 06131 17-5797

Von: Anja Thormann [mailto:notifications@github.com]
Gesendet: Donnerstag, 31. August 2017 16:21
An: Ensembl/ensembl-vep
Cc: Diederich, Stefan; Author
Betreff: Re: [Ensembl/ensembl-vep] Double annotation with custom annotation (VCF) (#71)


You don't need to merge the alleles. The VEP will compare alleles from the custom annotation VCF file to the alleles from your input VCF file. The underlying VEP code will apply a comparison which will match AGCAG ACAG from the custom annotation file to AG A in your input VCF file. After updating to version 90.1 just run your command as before and you should see that only 2 of the entries from your custom annotation file will be used for annotating your example variant.

**Comment by at7** [comment]
For custom annotation: What type of custom annotation do you want to add to the result VCF file? I just noticed that you are using `-custom 'ihdb_count.vcf.gz',IHDB_Count,vcf,exact,0`. You can specify the VCF field you want to add to your result VCF file if the alleles match described [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html). For adding frequencies there is an example [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_example.html#gnomad).

For gnomAD data: Are you using --af_gnomad for including gnomAD frequencies?

**Comment by at7** [comment]
You also need to get the new cache files for release 90 which include the gnomAD frequencies.

**Comment by stefandiederich** [comment]
My custom annotation contains counts of heterozygote and homozygote allele counts like

1             137486  het:1/137--hom:0/137  A             G
1             137487  het:1/137--hom:0/137  A             C
1             137508  het:1/137--hom:0/137  C             A
1             137536  het:1/137--hom:0/137  G            C
1             137552  het:1/137--hom:0/137  T             C
1             137559  het:1/137--hom:0/137  GC          G
17           17697101 het:1/137--hom:0/137 AGCAG A
17           17697101 het:1/137--hom:0/137 AGCAG ACAG
17           17697101 het:56/137--hom:16/137 AG A

And because  “17            17697101 het:1/137--hom:0/137 AGCAG ACAG” is reduced to “17          17697101 het:1/137--hom:0/137 AG A” VEP will annotate my found Variant 17 17697101 AG A with both entries:
17           17697101 het:1/137--hom:0/137 AGCAG ACAG
17           17697101 het:56/137--hom:16/137 AG A
But that should not be a problem ☺

With the gnomad, I am using –af_gnomad and I have downloaded and tabixed the new cache file version 90.


________________________________________
Stefan Diederich
M. Sc. Bioinformatik

Universitätsmedizin
der Johannes Gutenberg-Universität Mainz
Langenbeckstraße 1, 55131 Mainz
Tel.: 06131 17-5797

Von: Anja Thormann [mailto:notifications@github.com]
Gesendet: Donnerstag, 31. August 2017 16:58
An: Ensembl/ensembl-vep
Cc: Diederich, Stefan; Author
Betreff: Re: [Ensembl/ensembl-vep] Double annotation with custom annotation (VCF) (#71)


For custom annotation: What type of custom annotation do you want to add to the result VCF file? I just noticed that you are using -custom 'ihdb_count.vcf.gz',IHDB_Count,vcf,exact,0. You can specify the VCF field you want to add to your result VCF file if the alleles match described here<http://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html>. For adding frequencies there is an example here<http://www.ensembl.org/info/docs/tools/vep/script/vep_example.html#gnomad>.

For gnomAD data: Are you using --af_gnomad for including gnomAD frequencies?

**Comment by at7** [comment]
Are you still missing the gnomad frequencies? I can annotate your example variant with gnomAD frequencies running `perl ./vep -i input_vcf.vcf --output_file output_vcf.vcf --force_overwrite --assembly GRCh37 --port 3337 --cache --af_gnomad`
or using your command:
`perl ./vep -i input_vcf.vcf --output_file output_vcf.vcf --force_overwrite --assembly GRCh37 --port 3337 --cache --everything --pick --pick_order rank,canonical,appris,tsl,biotype,ccds,length`

**Comment by stefandiederich** [comment]
Hi Anja,

sorry for let you wait so long, but I was out of office last week. 

I just had a deeper look into the data. First I was confused that the MAX_AF field was showing me a value for an allele frequency although gnomAD annotation was not there. I was allways thinking that MAX_AF is corresponding to the gnomAD data but it  describes the 1000 Genome Procet data as well. Rigth?

If my assumption is correct, we can close this topic. 
Thanks for your help!

Stefan

**Comment by willmclaren** [comment]
MAX_AF can be a value from any of the frequency data found for the variant.
