### ISSUE TITLE
DBD::mysql::db selectall_arrayref failed: Access denied

### ISSUE THREAD

**Issue by martbro** [Ensembl/ensembl-vep#711]
## Describe the issue
I am trying to use the phenotype plugin for VEP: [https://github.com/Ensembl/VEP_plugins/blob/release/99/Phenotypes.pm](url). 

From the documentation: "On the first run for each new version/species/assembly will download a GFF-format dump to ~/.vep/Plugins/" and so requires database connection but it gives me this error: DBD::mysql::db selectall_arrayref failed: Access denied; you need (at least one of) the SHOW DATABASES privilege(s) for this operation at /gpfs/commons/groups/lappalainen_lab/mbroly/sfw/ensembl-vep/Bio/EnsEMBL/Registry.pm line 1775.

### Full error message
DBD::mysql::db selectall_arrayref failed: Access denied; you need (at least one of) the SHOW DATABASES privilege(s) for this operation at /gpfs/commons/groups/lappalainen_lab/mbroly/sfw/ensembl-vep/Bio/EnsEMBL/Registry.pm line 1775.

-------------------- WARNING ----------------------
MSG: homo_sapiens is not a valid species name (check DB and API version)
FILE: Bio/EnsEMBL/Registry.pm LINE: 1334
CALLED BY: Bio/EnsEMBL/Registry.pm  LINE: 1109
Date (localtime)    = Thu Mar 12 20:43:38 2020
Ensembl API version = 99

-------------------- EXCEPTION --------------------
MSG: Can not find internal name for species 'homo_sapiens'
STACK Bio::EnsEMBL::Registry::get_adaptor /gpfs/commons/groups/lappalainen_lab/mbroly/sfw/ensembl-vep/Bio/EnsEMBL/Registry.pm:1111
STACK Bio::EnsEMBL::VEP::BaseVEP::get_adaptor /gpfs/commons/groups/lappalainen_lab/mbroly/sfw/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:308
STACK Bio::EnsEMBL::VEP::BaseVEP::get_database_assembly /gpfs/commons/groups/lappalainen_lab/mbroly/sfw/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:419
STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /gpfs/commons/groups/lappalainen_lab/mbroly/sfw/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::init /gpfs/commons/groups/lappalainen_lab/mbroly/sfw/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:118
STACK Bio::EnsEMBL::VEP::Runner::run /gpfs/commons/groups/lappalainen_lab/mbroly/sfw/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /gpfs/commons/groups/lappalainen_lab/mbroly//sfw/ensembl-vep/vep:224
Date (localtime)    = Thu Mar 12 20:43:38 2020
Ensembl API version = 99

Will only load v99 databases
No core-like databases found. Check your DB_VERSION (used '99')
No variation databases found
No funcgen databases found
No ancestral database found
No ontology database found
No taxonomy database found
No ensembl_metadata database found
No production database or adaptor found
Writing to /gpfs/commons/groups/lappalainen_lab/mbroly//tests//chrY_multivcf_fixed_sorted_ACANok_sorted_temp
log file: ql::db selectall_arrayref failed: Access denied

### Full VEP command line
```
vep \
--force_overwrite \
--fork 10 \
--buffer_size 10000 \
--format vcf \
--no_escape \
--database \
--db_version 99 \
--assembly GRCh38 \
--dir_cache ${dir_cache} \
--exclude_predicted \
--fasta ${ref_fasta} \
--symbol \
--hgvs \
--check_existing \
--vcf \
--pick_allele_gene \
--dir_plugins ${dir_plugins} \
--plugin Phenotypes,dir=${Phenotypes_dir},include_types=Gene \
--input_file ${input_dir}/${vcf} \
--output_file ${output_dir}/${vcf_id}_annotated.vcf.gz \
--compress_output bgzip \
--terms SO \
--verbose
```

### System
Versions:
  ensembl              : 99.d3e7d31
  ensembl-funcgen      : 99.0832337
  ensembl-io           : 99.441b05b
  ensembl-variation    : 99.566bbdc
  ensembl-vep          : 99.2
- VEP Cache version: .vep/homo_sapiens_merged/99_GRCh38/
- Perl version: 5.28.1
- OS: Operating System: CentOS Linux 7 (Core)
- tabix installed ? Yes

You can provide a sample of them

Thank you very much !

**Comment by aparton** [comment]
Hi,

Thank you for your query, Ensembl resources currently have reduced functionality (see http://www.ensembl.info/2020/02/18/reduced-functionality-16th-25th-march-2020/) and this may have affected your VEP command. Could you please try running your command again?

If it's still not working, could you please try running a simple vep query to connect to the database like:

perl vep -id rs699 --database -o test_output.txt

and check if that's working correctly?

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi @martbro,

Are you still seeing this issue? Ensembl services should now be fully up and running, so this issue should be resolved. If not, please let me know and I'll see what we can do to help.

Kind Regards,
Andrew

**Comment by martbro** [comment]
Hi Andrew, thank you very much for looking into this

This query perl vep -id rs699 --database -o test_output.txt 
as well as my query now works ! Thanks a lot
