### ISSUE TITLE
VEP produces wrong genomic coordinates for HGVS c. duplications

### ISSUE THREAD

**Issue by stephan-hutter** [Ensembl/ensembl-vep#712]
I have been using VEP to convert between VCF and HGVS representations of variants and ran into an issue when converting from HGVS c. to VCF (and in consequence HGVS g.), the genomic coordinates are wrong. It seems to happen for certain duplications.

This occurs on my local VEP (using Docker VEP 99.2 with the v99 cache and DB), as well as using the web interface. I have extensively tested it for GRCh37, but it does also seem to occur for GRCh38.

Here are some examples...

Starting from VCF variants, VEP correctly converts them into HGVS c. variants:

2 58386928 . G GTAAT -> ENST00000402135.3:c.1111_1114dup
5 176942945 . T TCATC -> ENST00000507955.1:c.415_418dup
10 64573470 . A AGGC -> ENST00000242480.3:c.925_927dup
12 49427265 . T TTGC -> ENST00000301067.7:c.11220_11222dup
12 49427314 . T TGCTGCA -> ENST00000301067.7:c.11168_11173dup
13 28608262 . T TTCATATTCTCTGAAATCAACG -> ENST00000241453.7:c.1773_1793dup
19 33792731 . G GGCGGGT -> ENST00000498907.2:c.584_589dup
19 33792754 . G GGGC -> ENST00000498907.2:c.564_566dup
19 33793106 . G GCGGC -> ENST00000498907.2:c.211_214dup
19 33793119 . T TGTAG -> ENST00000498907.2:c.198_201dup
21 36164461 . G GGC -> ENST00000300305.3:c.1412_1413dup
21 36164771 . C CATGCCG -> ENST00000300305.3:c.1098_1103dup

But going the other way, seems to shift the variants around:

ENST00000402135.3:c.1111_1114dup -> 2 58386931 . A ATAAT
ENST00000507955.1:c.415_418dup -> 5 176942948 . T TCATC
ENST00000242480.3:c.925_927dup -> 10 64573472 . G GGGC
ENST00000301067.7:c.11220_11222dup -> 12 49427267 . G GTGC
ENST00000301067.7:c.11168_11173dup -> 12 49427319 . C CGCTGCA
ENST00000241453.7:c.1773_1793dup -> 13 28608282 . C CTCATATTCTCTGAAATCAACG
ENST00000498907.2:c.584_589dup -> 19 33792736 . G GGCGGGT
ENST00000498907.2:c.564_566dup -> 19 33792756 . G GGGC
ENST00000498907.2:c.211_214dup ->19 33793109 . G GCGGC
ENST00000498907.2:c.198_201dup ->19 33793122 . A AGTAG
ENST00000300305.3:c.1412_1413dup -> 21 36164462 . G GGC
ENST00000300305.3:c.1098_1103dup -> 21 36164776 . C CATGCCG

Looking at the resulting sequence, this is not a problem of alternative (non-normalized) representations of the same allele, they are clearly different. For example, ENST00000300305.3:c.1412_1413dup:

`36164460 AGGCGCGCGGA 36164470 (reference)`
`36164460 AGGCGCGCGCGGA 36164470 (from VCF, correct)`
`36164460 AGGGCCGCGCGGA 36164470 (from HGVS, wrong)`

Funnily enough, this even breaks the HGVS c. to HGVS c. "conversion", as the new HGVS variants seem to be based on the wrong "VCF variants" from above. I looks like the resulting insertion is shifted by 1bp compared to the correct duplication:

ENST00000402135.3:c.1111_1114dup -> ENST00000402135.3:c.1111_1112insATTA
ENST00000507955.1:c.415_418dup -> ENST00000507955.1:c.415_416insGATG
ENST00000242480.3:c.925_927dup -> ENST00000242480.3:c.925_926insGCC
ENST00000301067.7:c.11220_11222dup -> ENST00000301067.7:c.11220_11221insGCA
ENST00000301067.7:c.11168_11173dup -> ENST00000301067.7:c.11168_11169insTGCAGC
ENST00000241453.7:c.1773_1793dup -> ENST00000241453.7:c.1773_1774insCGTTGATTTCAGAGAATATGA
ENST00000498907.2:c.584_589dup -> ENST00000498907.2:c.584_585insACCCGC
ENST00000498907.2:c.564_566dup -> ENST00000498907.2:c.564_565insGCC
ENST00000498907.2:c.211_214dup -> ENST00000498907.2:c.211_212insGCCG
ENST00000498907.2:c.198_201dup -> ENST00000498907.2:c.198_199insCTAC
ENST00000300305.3:c.1412_1413dup -> ENST00000300305.3:c.1412_1413insGC
ENST00000300305.3:c.1098_1103dup -> ENST00000300305.3:c.1098_1099insCGGCAT

I hope this issue can be resolved in a coming update.

Cheers,
Stephan

**Comment by aparton** [comment]
Hi Stephan,

Thanks for this report. I've had a look at this issue today, and you're right. VEP takes HGVS input, converts it into a 'variation feature' object similar to a VCF record, and uses this to generate all of its annotations. This object is using an incorrect reference sequence on creation with HGVSdup input, and it's causing the issue that you're seeing.

I've put a ticket in, and we'll try and get this issue fixed for Ensembl 101, currently scheduled for release in July. I'll keep you up to date with its progress.

Thanks again for the report, and if you see any other issues please let us know.

Kind Regards,
Andrew

**Comment by aeoeue** [comment]
Hi, I stumbled across the same problem.

Sorry if the following is already known:

Maybe it's just a coincidence, but for the variants I tested, the conversion was incorrect only for multi nucleotide duplications and only for genes on the minus strand.
That sounds like an incorrect conversion of start and end position from antisense to sense. Maybe the HGVS 3’ rule also plays a part ...

Maybe that helps narrow down the error.

Nevertheless, thanks a lot for the hard work.

**Comment by stephan-hutter** [comment]
Hi Andrew,

I just saw that Ensembl 101 was released, but it didn't seem to contain a fix resolving this issue.
Do you have an update on when this will be fixed?

Thanks!
Stephan

**Comment by aparton** [comment]
Hi @stephan-hutter,

Thanks for getting in touch. We discovered an unexpected side effect of our initial fix, and as such were unable to release a fix for release 101. We're still looking into it, and I'll let you know when we know more.

Kind Regards,
Andrew

**Comment by stephan-hutter** [comment]
I don't know exactly with which version this happened, but in version 110.1 this bug is fixed.

HGVS duplications now produce the expected VCF records an everything works fine from there.
All examples I gave above now generate the correct results.

This also seems to have fixed issue #1316 

Thanks,
Stephan
