### ISSUE TITLE
web and docker VEP give different annotations for mtDNA GRCh38 variant

### ISSUE THREAD

**Issue by jazberna1** [Ensembl/ensembl-vep#714]
Hello,
## Describe the issue
I am annotating one human mtDNA GRCh38 variant by running VEP from the docker container and from the web tool. Both are giving me different annotations.

The web tool reports:
MT	10471	.	T	C	.	.	DP=63;ECNT=6;MBQ=37,35;MFRL=0,0;MMQ=60,60;MPOS=5;OCM=0;POPAF=2.40;TLOD=0.675;CSQ=C|downstream_gene_variant|MODIFIER|MT-ND3|

The container reports:
MT	10471	.	T	C	.	.	DP=63;ECNT=6;MBQ=37,35;MFRL=0,0;MMQ=60,60;MPOS=5;OCM=0;POPAF=2.40;TLOD=0.675;CSQ=C|intergenic_variant|MODIFIER||

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 98
- VEP Cache version: 98
- Perl version: v5.26.1
- OS: Ubuntu 18.04.3 LTS
- tabix installed: yes

### Full VEP command line
The comand line I use to run VEP from the container is:
```
vep ./vep \
--show_ref_allele \
-i /opt/vep/src/ensembl-vep/jorge/GRD94mtDNA_mutect2.vcf \
-o /opt/vep/src/ensembl-vep/jorge/GRD94mtDNA_mutect2.vep.vcf \
--plugin Condel,/opt/vep/src/ensembl-vep/Condel,b,1 \
--plugin Phenotypes,file=/opt/vep/src/ensembl-vep/jorge/phenotypes.GRCh38.gff.gz,include_types=Gene \
--custom /opt/vep/src/ensembl-vep/clinvar.GRCh38.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNREVSTAT,CLNDN,CLNDISDB \
--plugin GeneSplicer,/opt/vep/src/ensembl-vep/GeneSplicer/sources/genesplicer,/opt/vep/src/ensembl-vep/GeneSplicer/human \
--plugin miRNA \
--refseq \
--custom /opt/vep/src/ensembl-vep/gerp_conservation_scores.homo_sapiens.GRCh38.bw,GERP,bigwig \
--custom /opt/vep/src/ensembl-vep/gnomADe/gnomad.exomes.r2.1.1.sites.liftover_grch38.vcf.bgz,gnomADe,vcf,exact,0,AF_AFR,AF_AMR,AF_ASJ,AF_EAS,AF_FIN,AF_NFE,AF_OTH \
--plugin ExAC,/opt/vep/src/ensembl-vep/ExAC.r1.sites.liftover.b38.vcf.gz,AC,AN \
--vcf \
--fork 4 \
--force_overwrite \
--cache \
--use_given_ref 
```

### Full error message
> Including the warnings, if available

### Data files (if applicable)
They include:
- The input file
[input.vcf.txt](https://github.com/Ensembl/ensembl-vep/files/4349863/input.vcf.txt)

- The output file from the docker container
[output.docker.vep.vcf.txt](https://github.com/Ensembl/ensembl-vep/files/4349871/output.docker.vep.vcf.txt)

- The output file from the web tool
[output.web.vep.vcf.txt](https://github.com/Ensembl/ensembl-vep/files/4349876/output.web.vep.vcf.txt)

Many thanks
Jorge

**Comment by at7** [comment]
Hello Jorge,
the VEP web tool uses a few more parameters when annotating variants:
This is the command line used by the web tool:

> ./vep --af --appris --biotype --buffer_size 500 --check_existing --distance 5000 --mane --polyphen b --pubmed --regulatory --sift b --species homo_sapiens --symbol --transcript_version --tsl --cache --input_file [input_data] --output_file [output_file]

Adding --distance 5000 and --symbol to your docker command will create the same annotation results.

Please let me know if that is not the case.

Best wishes,
Anja

**Comment by jazberna1** [comment]
Hello Anja,

I added --distance 5000  and  --symbol  but I still tget he variant as intergenic_variant instead of downstream_gene_variant. I don't get the gene symbol (MT-ND3) either. 

Could you think of anything else I am doing wrong?

This is now my current command line:
```
./vep \
--show_ref_allele \
-i /opt/vep/src/ensembl-vep/jorge/input.vcf \
-o /opt/vep/src/ensembl-vep/jorge/input.vep.vcf \
--plugin Condel,/opt/vep/src/ensembl-vep/Condel,b,1 \
--plugin Phenotypes,file=/opt/vep/src/ensembl-vep/jorge/phenotypes.GRCh38.gff.gz,include_types=Gene \
--custom /opt/vep/src/ensembl-vep/clinvar.GRCh38.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNREVSTAT,CLNDN,CLNDISDB \
--plugin GeneSplicer,/opt/vep/src/ensembl-vep/GeneSplicer/sources/genesplicer,/opt/vep/src/ensembl-vep/GeneSplicer/human \
--plugin miRNA \
--refseq \
--custom /opt/vep/src/ensembl-vep/gerp_conservation_scores.homo_sapiens.GRCh38.bw,GERP,bigwig \
--custom /opt/vep/src/ensembl-vep/gnomADe/gnomad.exomes.r2.1.1.sites.liftover_grch38.vcf.bgz,gnomADe,vcf,exact,0,AF_AFR,AF_AMR,AF_ASJ,AF_EAS,AF_FIN,AF_NFE,AF_OTH \
--plugin ExAC,/opt/vep/src/ensembl-vep/ExAC.r1.sites.liftover.b38.vcf.gz,AC,AN \
--vcf \
--fork 4 \
--force_overwrite \
--cache \
--use_given_ref \
--distance 5000 \
--symbol
```

Many thanks
Jorge

**Comment by at7** [comment]
Hi Jorge,

I was testing with the Ensembl gene set. When I use RefSeq only as you have specified in your docker command I also get only intergenic_variant. I checked and we don't import RefSeq transcripts for the mitochondrial DNA. For now I can only recommend that you use the merged cache file which gives you MT annotations from the Ensembl gene set.

Thanks,
Anja

**Comment by jazberna1** [comment]
Hello Anja,

Thanks so much. It's perfect now with the merged cache.

Regards
Jorge
