### ISSUE TITLE
MSG: ERROR: Cannot use format vcf without Bio::DB::HTS::Tabix module installed

### ISSUE THREAD

**Issue by marianakhoul** [Ensembl/ensembl-vep#718]
## Describe the issue

I am trying to run the following command:
./ensembl-vep/vep -i ./data/RHP_variant_vep.txt --cache --offline --dir ./vep_data/  --custom gnomad.vcf.gz,gnomADg,vcf,exact,0,AF_AFR,AF_AMR,AF_ASJ,AF_EAS,AF_FIN,AF_NFE,AF_OTH
But I am getting the above error message. I have installed Bio-DB-HTS from git and configured it.
I have installed the modules using cpan. I know that this module exists, but when I use:
```
locate Tabix.pm or locate Bio/DB/HTS/Tabix
```
It doesn't find it inside the Ensembl-vep directory inside Bio, but it does exist there.
The below is more information about what I have done.

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 99
- VEP Cache version: 99
- Perl version: 5.16
- OS: CentOS
- tabix installed yes
-Bio-DB-HTS downloaded from git

### Full VEP command line
```
./ensembl-vep/vep -i ./data/RHP_variant_vep.txt --cache --offline --dir ./vep_data/  --custom gnomad.vcf.gz,gnomADg,vcf,exact,0,AF_AFR,AF_AMR,AF_ASJ,AF_EAS,AF_FIN,AF_NFE,AF_OTH

```

### Full error message
```
-------------------- EXCEPTION --------------------
MSG: ERROR: Cannot use format vcf without Bio::DB::HTS::Tabix module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:162
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:228
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:93
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel ./ensembl-vep/vep:224
Date (localtime)    = Tue Mar 24 08:26:40 2020
Ensembl API version = 99
---------------------------------------------------
```
### Data files
- The input file: RHP_variant_vep.txt 
1 1737915 1737915 T/C . 745971
1 1737915 1737915 T/G . 1346473
1 1737916 1737916 T/C . 1026499
1 1737940 1737940 T/C . 116121
1 1737942 1737942 A/G . 905125
1 1737942 1737942 A/T . 1066191
1 1737948 1737948 T/G . 1550944
1 1737949 1737949 T/C . 1086580
1 1737954 1737954 T/C . 116122
1 1747212 1747212 G/C . 1346474

### Exports
export PATH=/usr/local/lib64/perl5:${PATH}
export PATH=/apps/ensembl-vep:${PATH}
export LD_LIBRARY_PATH=/usr/local/lib
export PERL5LIB=/usr/local/lib64/perl5
export PATH=/usr/local/lib64:${PATH}
export PATH=/apps/ensembl-vep/tabix:$PATH
export LD_LIBRARY_PATH=/usr/local/lib

perldoc -l  Bio::DB::HTS::Tabix: (output)
/usr/local/lib64/perl5/Bio/DB/HTS/Tabix.pm

perl -e "use Bio::DB::HTS::Tabix"
Gave no output, usually gives errors when I have the wrong paths
 
Any help would be helpful.

Thank you,
Maria Nakhoul

**Comment by aparton** [comment]
Hi,

Thanks for your query. Could you please:

- Check that the Bio::DB::HTS::Tabix module is located in the ensembl-vep directory at: /ensembl-vep/Bio/DB/HTS/Tabix.pm
- Check that your ensembl-vep folder is included within your PERL5LIB. If not, you can add it with:
export PERL5LIB=${PERL5LIB}:ENSEMBL-VEP_PATH
- Rerun your initial command, and send me the output if it's still not working correctly?

Kind Regards,
Andrew

**Comment by marianakhoul** [comment]
Hello,
```
ls ./ensembl-vep/Bio/DB/HTS/Tabix.pm
```
 gave the following output:
./ensembl-vep/Bio/DB/HTS/Tabix.pm
I know it is there in that directory but if I write:
```
locate ./ensembl-vep/Bio/DB/HTS/Tabix.pm
```
it gives no output.
```
export PERL5LIB=${PERL5LIB}:/apps/ensembl-vep
```
```
sudo ./ensembl-vep/vep -i ./data/RHP_variant_vep.txt --cache --offline --dir ./vep_data/  --custom gnomad.vcf.gz,gnomADg,vcf,exact,0,AF_AFR,AF_AMR,AF_ASJ,AF_EAS,AF_FIN,AF_NFE,AF_OTH
```
```
-------------------- EXCEPTION --------------------
MSG: ERROR: Cannot use format vcf without Bio::DB::HTS::Tabix module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:162
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:228
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:93
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /apps/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel ./ensembl-vep/vep:224
Date (localtime)    = Tue Mar 24 09:05:38 2020
Ensembl API version = 99
---------------------------------------------------
```

**Comment by marianakhoul** [comment]
starting everything without having prior environmental variables:

```
export PERL5LIB=/apps/ensembl-vep
perldoc -l  Bio::DB::HTS::Tabix
```
output:
/apps/ensembl-vep/Bio/DB/HTS/Tabix.pm

but then
```
perl -e "use Bio::DB::HTS::Tabix"
Bio::DB::HTS object version 3.01 does not match $Bio::DB::HTS::VERSION 2.11 at /usr/lib64/perl5/DynaLoader.pm line 213.
Compilation failed in require at /apps/ensembl-vep/Bio/DB/HTS/Tabix.pm line 22.
BEGIN failed--compilation aborted at /apps/ensembl-vep/Bio/DB/HTS/Tabix.pm line 22.
Compilation failed in require at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```
gave me this error.

**Comment by marianakhoul** [comment]
deleted and downloaded everything from scratch. solved the issue
