### ISSUE TITLE
Pick Most Frequent Consequence Type

### ISSUE THREAD

**Issue by DarioS** [Ensembl/ensembl-vep#719]
There is an option `--most_severe` but what if there are 10 transcripts for a gene and the most severe consequence applies to only one of them but a less severe consequence applies to the other nine isoforms. Chances are that the relevant consequence will be the one that applied to 9 out of isoforms. Could VEP get an option such as `--most_frequent`?

**Comment by aparton** [comment]
Hi @Dario,

Thank you for your suggestion. I've had a chat about this with the team today, and I don't think it would be prudent to include such a flag within VEP.

While we are aware that providing one transcript per gene can be of significant benefit when reducing the complexity of further analysis, we try to ensure that any potential loss of vital information is kept to a minimum at this point. With the --most_severe flag, we can be confident that information about severe consequences will not be lost, however, a --most_frequent flag would not provide us such an assurance. 

If you have any other issues or suggestions, please let us know.

Kind Regards,
Andrew
