### ISSUE TITLE
Predict NMD Status for Frameshift Indels

### ISSUE THREAD

**Issue by DarioS** [Ensembl/ensembl-vep#728]
Could Variant Effect Predictor output estimated consequences for frameshift indels regarding whether they would be degraded or not? Perhaps something like in [American Journal of Human Genetics](https://www.cell.com/ajhg/fulltext/S0002-9297(18)30203-9)

> We designed an efficient tool, NMDEscPredictor, to predict whether a given frameshifting indel will lead to NMD+ or to NMD− transcripts based on the relative location of the variant within the gene.

It would be convenient to see `frameshift_variant,stop_gained`

**Comment by dglemos** [comment]
Hello @DarioS,
Could you give an example? 
About NMD prediction VEP predicts a variant is 'NMD_transcript_variant' when it overlaps a transcript that is the target of NMD (transcript with nonsense_mediated_decay biotype).

**Comment by DarioS** [comment]
As an example, consider NM_000546 and the base position in hg38 chr17:7676268 is deleted. This single base deletion would introduce a stop codon 22 bases further along in the direction of transcription in the same exon (chr17:7676244-7676246 in reference genome coordinates before deletion). This is a long way away from the normal stop codon, therefore it could be annotated as also causing a new stop codon, perhaps by `stop_gained`, and be predicted to be degraded by nonsense-mediated decay, perhaps by `NMD_transcript_variant`.

**Comment by dglemos** [comment]
Thank you for the example. 
This is something we need to look into. It's not something we will do for the next releases but it could be an interesting feature for some time in the future.

**Comment by DarioS** [comment]
Great. Just for comparison, ANNOVAR already has [such functionality](http://annovar.openbioinformatics.org/en/latest/user-guide/gene/#output-file-2-refseq-gene-annotation) built in. It would be nice to see VEP catch up to this.

**Comment by davmlaw** [comment]
FYI - a NMD plugin was added on September 20th

https://m.ensembl.org/info/docs/tools/vep/script/vep_plugins.html#nmd

**Comment by davmlaw** [comment]
Hey @dglemos - given that there's a NMD plugin now I think you can close this one

https://m.ensembl.org/info/docs/tools/vep/script/vep_plugins.html#nmd

**Comment by dglemos** [comment]
Thanks, @davmlaw. That is correct we have a new plugin NMD that predicts if a stop_gained variant allows the transcript to escape nonsense-mediated mRNA decay.
I'm closing the issue but feel free to open a new issue if you have more questions.

Best wishes,
Diana
