### ISSUE TITLE
vep recorder use offline?

### ISSUE THREAD

**Issue by dj10086** [Ensembl/ensembl-vep#730]
Dear professor,
I want tot find  a easy way to convert a variant to hgvs annotation, and vep really can be helpful.
but If I used annovar first, I need to use vep again, so I want to find a concise programme to convert a variant to hgvs anotation(vep is too big to some degree, I am not pointing its shortcommings), so I find https://www.ensembl.org/info/docs/tools/vep/recoder/index.html  **Variant Recoder**, but it seems must used online? am I right, and is there a easy programme use offline?

thanks a lot.

**Comment by dglemos** [comment]
Hello @dj10086,
Unfortunately, there isn't any other offline tool to convert to hgvs. You can use **vep** in offline mode which should annotate your variants quickly or use **variant recoder** which is part of the vep package ([installation instructions](https://www.ensembl.org/info/docs/tools/vep/recoder/index.html#vr_dl_install)) but needs database connection to run.

**Comment by dj10086** [comment]
thanks a lot. I also want to ask a question. annovar always updates database, but it seems vep does not, is this because of some reason?

**Comment by dglemos** [comment]
We support database updates for GRCh38 in every Ensembl release which is every 3 months. 
If you're using GRCh37, the Ensembl geneset hadn't been updated since the release 76 but we update variant and regulation data once a year. The new update is going to be next release probably the end of April.

**Comment by dglemos** [comment]
The new update has been released. 
I'm going to close this ticket but feel free to open a new one if you have more questions.

**Comment by lacek** [comment]
Hi @dglemos, I found there to be options for specifying database connection details: https://github.com/Ensembl/ensembl-vep/blob/release/104/variant_recoder#L51-L57
Does it mean that variant_recorder can run without Internet if I hosts the database locally?
If so, may I know which tables are required?

I intend to convert a large among of variants in VCF format into HGVS in LRG sequence. The online query (either via vep, variant_recorder or REST API) is way too slow for me.

**Comment by dglemos** [comment]
Hi @lacek,
That is correct, you can run variant_recoder pointing to a local database, the option is listed [here](https://www.ensembl.org/info/docs/tools/vep/recoder/index.html#vr_dl_install). You have to be aware if you are querying a large amount of variants the query may still take some time because it needs to establish a connection to the database. We advise to run small sets of variants. 
You could also try running VEP locally in offline mode (--offline) and specify a fasta file (--fasta) to be able to fetch the HGVS notations (--hgvs).

**Comment by lacek** [comment]
Hi @dglemos, I wish to get LRG annotation but the `--lrg` option in VEP doesn't work with `--offline`. So I'll still need a local database. Thanks anyway.
