### ISSUE TITLE
VEP ignores programmed frameshift in gene annotation of Covid-19

### ISSUE THREAD

**Issue by etapanari** [Ensembl/ensembl-vep#734]
Hi there,

I am using a GFF for covid-19 that has a gene with 2 CDSs (frameshift) 
I ran VEP and in the variation result file I see that it ignores the second CDS while it spans the first CDS until the end of the gene.
The lines of the GFF regarding the gene in question are as follows:
 NC_045512v2	RefSeq	gene	13442	16236	.	+	.	ID=gene-nsp12;Name=nsp12;gene=nsp12;gbkey=Gene;gene_biotype=protein_coding;locus_tag=GU280_gp01
NC_045512v2	RefSeq	transcript	13442	16236	.	+	.	ID=mRNA-nsp12;Name=transcript_of_nsp12;Parent=gene-nsp12;transcript_type=protein_coding
NC_045512v2	RefSeq	exon	13442	16236	.	+	.	ID=exon-nsp12;Name=exon_of_nsp12;Parent=mRNA-nsp12
NC_045512v2	RefSeq	CDS	13442	13468	.	+	0	ID=cds_1-nsp12;Name=cds_1_of_nsp12;Parent=mRNA-nsp12
NC_045512v2	RefSeq	CDS	13467	16236	.	+	0	ID=cds_2-nsp12;Name=cds_2_of_nsp12;Parent=mRNA-nsp12

This is in accordance to the GFF specs (see here for programmed frameshift):
https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md

it says:
The representation of this is to make the CDS discontinuous:

chrX  . gene               XXXX   YYYY .  +  . ID=gene01;name=my_gene
chrX  . mRNA               XXXX   YYYY .  +  . ID=tran01;Parent=gene01;Ontology_term=SO:1000069
chrX  . exon               XXXX   YYYY .  +  . Parent=tran01
chrX  . CDS                XXXX   YYYY .  +  0 ID=cds01;Parent=tran01
chrX  . CDS                YYYY-1 ZZZZ .  +  0 ID=cds01;Parent=tran01

which is our implementation in the GFF.(well.. kind of.. I tried with end coords of gene, transcript, exon to be 13468 but VEP was ignoring the gene after coord 13468)
But when I query the VEP output I see:

>  grep NC_045512v2:13468 variant_effect_output.txt   | grep nsp12
NC_045512v2_13468_C/T	NC_045512v2:13468	T	gene-nsp12	mRNA-nsp12	Transcript	synonymous_variant	27	27	9	N	aaC/aaT	-	IMPACT=LOW;STRAND=1;SOURCE=covid_19.gff.gz
NC_045512v2_13468_C/G	NC_045512v2:13468	G	gene-nsp12	mRNA-nsp12	Transcript	missense_variant	27	27	9	N/K	aaC/aaG	-	IMPACT=MODERATE;STRAND=1;SOURCE=covid_19.gff.gz
NC_045512v2_13468_C/A	NC_045512v2:13468	A	gene-nsp12	mRNA-nsp12	Transcript	missense_variant	27	27	9	N/K	aaC/aaA	-	IMPACT=MODERATE;STRAND=1;SOURCE=covid_19.gff.gz

which is only the first CDS

Does VEP create variation annotations when there are frameshifts in the gene annotation?
I can provide the whole GFF file if needed.
Also, I was wondering if you get more tickets about VEP from scientists that use covid-19 since it is so much studied these days, I wonder how they do it..
 
Best,
Electra

**Comment by aparton** [comment]
Hi Electra,

I've investigated this issue this morning, and it's not something that our GFF parser currently supports. Within our current transcript model, this would usually be described as two separate transcripts. Some comments:

1) The easiest workaround for this would be to add the second CDS in as an additional transcript (and associated exon). VEP would then report overlaps and associated annotations for both CDS when appropriate.

2) As you've noted, this is within the GFF3 spec, and as such it's something that we would like to support in the future. However, I'm unable describe exactly how we will support this or put a timeframe on how long this will take at this point.

3) Additionally, COVID-19 transcript model resources are something that we are working on providing, however we don't have an expected release date yet.

If there's anything else we can do to help, please let us know.

Kind Regards,
Andrew

**Comment by etapanari** [comment]
Hi there,

Any luck with this yet?

Thanks so much,
Electra

**Comment by etapanari** [comment]
Hi Andrew,
Thanks a lot for your answer. I followed your advice and now I get variation results for both CDSs.
The only issue I have is that this gene codes for 1 protein while VEP considers that there are 2 proteins because of the 2 transcripts and 2 CDSs. So, in the "Protein_position" field the second transcript starts from 1 instead of 10 (the first transcript has 9 codons), so I had to manually edit the VEP result to add 9 for that column for the specific transcript. 

Also, another thing I would like to ask is if I want the gene symbol to be output in the VEP result how  do I do it?

Best,
Electra

**Comment by MattBashton** [comment]
@etapanari would you be able to share the working .gff file?  I also have the same issue, but if  you've already ironed out the kinks in your .gff this would save me and many other people the effort in getting some rudimentary nCov2 annotation out of VEP.

**Comment by aparton** [comment]
Hi,

@MattBashton Just incase it's useful to you, Ensembl will be releasing Sars-COV-2 data, including a GFF file that is fully supported by VEP, at the beginning of next week.

@etapanari Apologies for the delay in getting back to you. Gene symbol information can be added from your GFF file to your VEP output with the `--symbol` flag, and the data itself will be taken from the `Name` key from the attributes column of a gene entry within your GFF. You can see an example of this here: https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff

Kind Regards,
Andrew
