### ISSUE TITLE
How is the column "IMPACT" computed?

### ISSUE THREAD

**Issue by wenh06** [Ensembl/ensembl-vep#736]
The VEP outcome has a column "IMPACT", which is described as "Subjective impact classification of consequence type" on [this page](https://asia.ensembl.org/info/docs/tools/vep/vep_formats.html#defaultout), while in the paper "The Ensembl Variant Effect Predictor", it might be inferred that it is adopted and processed using data from GENCODE and RefSeq but without any further details.

I think this "Subjective" "classification" invovles some handicrafted rules. Can anyone provide more details on this? Thanks!

**Comment by aparton** [comment]
Hi,

Thanks for your query. As you've noted, the IMPACT column is a subjective classification of the severity of the variant consequence, based on agreement with SNPEff. You can find detailed information on all of our consequences and the associated impact values here: https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html

Kind Regards,
Andrew

**Comment by wenh06** [comment]
> Hi,
> 
> Thanks for your query. As you've noted, the IMPACT column is a subjective classification of the severity of the variant consequence, based on agreement with SNPEff. You can find detailed information on all of our consequences and the associated impact values here: https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html
> 
> Kind Regards,
> Andrew

OK, I see. Thanks~
