### ISSUE TITLE
constant gzip: stdout: Broken pipe

### ISSUE THREAD

**Issue by antonkulaga** [Ensembl/ensembl-vep#739]
I constantly get:
```
gzip: stdout: Broken pipe
```
However Vep manages to run annotations on that vcf.gz file and the files do not look corrupted :(

**Comment by aparton** [comment]
Hi,

Thank you for your query. Could you please send me on a copy of your VCF and I can attempt to reproduce the issue? You can either attach it to this ticket, or email it to helpdesk@ensembl.org

Alternatively, as a workaround, decompressing the input VCF file before running VEP should resolve this issue.

Kind Regards,
Andrew

**Comment by DarioS** [comment]
Probably a duplicate of #720

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew
