### ISSUE TITLE
Spaces in CSQ field breaks Vcf spec 

### ISSUE THREAD

**Issue by ffinfo** [Ensembl/ensembl-vep#74]
While Running VEP I did see it outputs a vcf file with spaces in the info field CSQ. Downstream tools breaks because they are very strict on the specs.

Vep information from header:
##VEP="v90" time="2017-08-30 13:00:50" cache="<cache directory>/danio_rerio/90_GRCz10" ensembl=90.4a44397 ensembl-variation=90.8684f2b ensembl-funcgen=90.e775c00 ensembl-io=90.9a148ea assembly="GRCz10" dbSNP="142" genebuild="2015-05" sift="sift"

Record with a space:
```
chr3    34793054        rs1582354       T       C       12.77   .       AC=2;AF=1.0;AN=2;DB;DP=1;Dels=0.0;FS=0.0;HaplotypeScore=0.0;MLEAC=2;MLEAF=1.0;MQ=60.0;MQ0=0;QD=12.77;SOR=1.609;VariantCaller=unifiedgenotyper;CSQ=C|intron_variant|MODIFIER|CA10 (1 of many)|ENSDARG00000009568|Transcript|ENSDART00000055264|protein_coding||1/8||||||||||1||SNV|HGNC|HGNC:1369|YES||P5||ENSDARP00000055263||E7EYF2|UPI0001E92014|1|||||||||||||||||||||||||||||       GT:AD:DP:GQ:PL  1/1:0,1:1:3:39,3,0
```

Note that it contains this: `CA10 (1 of many)`, this is not allowed in a vcf file.

**Comment by sarahhunt** [comment]
@ffinfo - thanks for the report. There are unexpected spaces in some gene symbols in the latest zebrafish gene set. There's now an update in release/90 branch to URL encode these for VCF output. As with the encoding of HGVS strings, it can be switched off with the --no_escape option.

**Comment by ffinfo** [comment]
@sarahhunt: I have updated my vep and it seems to be resolved now. All my tests are not complaining anymore.
Ty for your fast respond 👍
