### ISSUE TITLE
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm 

### ISSUE THREAD

**Issue by winni-liu** [Ensembl/ensembl-vep#741]
## Describe the issue
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm line 276, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm line 276, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm line 276, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm line 290, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm line 290, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm line 290, <__ANONIO__> line 8364

### System
- VEP version: [e.g. 95.0] 
- VEP Cache version: [e.g. 99]
- Perl version: [e.g. 5.26.2]
- OS: [CentOS]
- tabix installed ? yes

### Full VEP command line
```
vep --cache --dir_cache ../database/ --species canis_familiaris --force_overwrite --hgvs --refseq --cache_version 99 -i sample.vcf -o sample.vep
```

### Full error message
> Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/AnnotationTy
pe/Transcript.pm line 276, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/AnnotationTy
pe/Transcript.pm line 276, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/AnnotationTy
pe/Transcript.pm line 276, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/AnnotationTy
pe/Transcript.pm line 290, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/AnnotationTy
pe/Transcript.pm line 290, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/AnnotationTy
pe/Transcript.pm line 290, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/Stats.pm lin
e 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/Stats.pm lin
e 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/Stats.pm lin
e 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/Stats.pm lin
e 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/Stats.pm lin
e 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/Stats.pm lin
e 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/Stats.pm lin
e 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/Stats.pm lin
e 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/Stats.pm lin
e 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/Stats.pm lin
e 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/Stats.pm lin
e 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/Stats.pm lin
e 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/Stats.pm lin
e 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/Stats.pm lin
e 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep/share/ensembl-vep-95.0-1/modules/Bio/EnsEMBL/VEP/Stats.pm lin
e 365, <__ANONIO__> line 8364.
2020-04-23 09:10:41 - INFO: Database will be accessed when using --hgvs
2020-04-23 09:10:41 - INFO: Database will be accessed when using --hgvsc
2020-04-23 09:10:41 - INFO: Database will be accessed when using --hgvsp

**Comment by dglemos** [comment]
Hi,
You're using vep version 95 and cache 99, you should use the same version for both. 
Can you also send your input file to try to replicate the issue?

**Comment by winni-liu** [comment]
hi, 
I change the vep version to 99:
`  ensembl              : 99.d3e7d31
  ensembl-funcgen      : 99.0832337
  ensembl-io           : 99.441b05b
  ensembl-variation    : 99.642e1cd
  ensembl-vep          : 99.2`
and I use this command run it again,
`vep --cache --dir_cache ../database/ --species canis_familiaris --force_overwrite --hgvs --refseq --cache_version 99 -i sample.vcf -o sample.ncbi.vep &>log &`
and I get the new error message:
`Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm line 276, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm line 276, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm line 276, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm line 290, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm line 290, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm line 290, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
...
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
Use of uninitialized value in hash element at /psd/biosoft/anaconda/envs/ensembl-vep_99/share/ensembl-vep-99.2-0/modules/Bio/EnsEMBL/VEP/Stats.pm line 365, <__ANONIO__> line 8364.
2020-04-26 10:18:37 - INFO: Database will be accessed when using --hgvs
2020-04-26 10:18:37 - INFO: Database will be accessed when using --hgvsc
2020-04-26 10:18:37 - INFO: Database will be accessed when using --hgvsp

`
if I don't use the "--refseq", I will not get error message, so, error message just appear only I use the '--refseq'.
also, the cache is succeeded creat,
`2020-04-22 09:08:07 - Processing canis_familiaris
2020-04-22 09:08:07 - Processing version 95_CanFam3.1
2020-04-22 09:08:07 - No unprocessed types remaining, skipping
2020-04-22 09:08:07 - Processing felis_catus_refseq
2020-04-22 09:08:07 - Processing version 99_Felis_catus_9.0
2020-04-22 09:08:07 - Processing _var cache type
^M[>                                                          ]    [ 0% ]^M[>                                                          ]    [ 0% ]...
2020-04-22 09:12:14 - Processing felis_catus
2020-04-22 09:12:14 - Processing version 95_Felis_catus_9.0
2020-04-22 09:12:14 - No unprocessed types remaining, skipping
2020-04-22 09:12:14 - Processing tmp
2020-04-22 09:12:14 - Processing canis_familiaris_refseq
2020-04-22 09:12:14 - Processing version 99_CanFam3.1
2020-04-22 09:12:14 - Processing _var cache type
^M[>                                                          ]    [ 0% ]^M[>                                                          ]    [ 1% ]....
2020-04-22 09:18:16 - All done!
`
I have attached my input vcf(sample.txt), for attach the file, 'sample.vcf' in the command line was moved 'sample.txt'
[sample.txt](https://github.com/Ensembl/ensembl-vep/files/4534524/sample.txt)

**Comment by dglemos** [comment]
I can reproduce the issue. It looks like there's a problem with some of the RefSeq transcripts, some gene symbols are missing. That means that in your output, some variants are missing the gene, for example: 1 5070565 G/T
We are looking into the issue and we'll let you know of any updates.
