### ISSUE TITLE
Restrict VEP annotation to a subset of the variants

### ISSUE THREAD

**Issue by fgvieira** [Ensembl/ensembl-vep#743]
Is it possible to restrict VEP annotation to only the variants that match a certain criteria? For example, only annotate those where `FILTER == PASS`, or where `SV_length < 1000000`.

thanks,

**Comment by dglemos** [comment]
Hi,
It's not possible to annotate only the variants that match specific criteria. However, you can first filter the variants using filter_vep and then only annotate those with vep.

**Comment by fgvieira** [comment]
Hi,

but I'd like to still keep all the variants in the VCF and just restrict the annotations to a subset.

The way you suggest, I'd have to split the VCF in two files, annotate one, merge them, and sort them. I was just hoping for an easier way... :)

**Comment by dglemos** [comment]
Hi @fgvieira,
First, I apologize for the delay in getting back to you.
We had a discussion within the team regarding your suggestion to restrict VEP annotations based on specific criteria.
At this time, we have decided not to implement this feature immediately. However, we certainly see the value it could bring, and we’ll keep it in mind as we plan for the new VEP implementation.
In the meantime, the approach of splitting the VCF, annotating and merging it back is the only workaround.

Thank you for your understanding and for sharing your input on improving the tool.

Best wishes,
Diana
