### ISSUE TITLE
Empty "contributing variants" field.

### ISSUE THREAD

**Issue by iranmdl** [Ensembl/ensembl-vep#745]
I am running haplosaurus using a home made database with custom GTF and reference fasta file.
I have noticed that "contributing variants" field is empty when the input contains an indel that generates a frameshift + an early stop codon (see attached the output JSON that haplosaurus is reporting). Is this an expected behaviour?
- VEP/haplosaurus version: 95 

[missing_contributing_variants.json.gz](https://github.com/Ensembl/ensembl-vep/files/4550536/missing_contributing_variants.json.gz)

**Comment by at7** [comment]
Hello,
what you describe sounds like a [bug](https://github.com/Ensembl/ensembl-vep/issues/671) which we have fixed for release/99. Would it be possible for you to upgrade to release/99 and run haplosaurus again? You could also try and integrate the bugfix into your current checkout. It is only a small change: https://github.com/Ensembl/ensembl-variation/pull/519
I would also be happy to test it for you if you could also send me your input file and command line.

Best wishes,
Anja

**Comment by iranmdl** [comment]
Hey! Sorry for the delay! Your suggestion fixed the bug, thanks!
Unfortunately, I have just jumped into another error.
 I've as input a VCF with a set of variants, all of them phased as `0|1`. So, I expect to obtain two `protein_haplotypes` after running `haplosaurus`, one with the variants applied and with "`contributing_variants`" field filled with the variants applied, and another one with the `REF` sequence (since the other allele remains reference). This is how I've seen that `haplosaurus` behaves so far. However, for the current files I am uploading (see attachments), two `protein_haplotypes` haplotypes are generated, both of them different from `REF`, and only one of them with contributing_variants data (the other has this field empty, but still, it is generating a different protein sequence). Am I missing something? Any help is appreciated :)

Used command:
`haplo -i input.vcf       -o $clonename'_haplo_output.json'       --fasta ref.fasta       --json       --gtf annotation.gtf.gz`

[annotation.gtf.gz](https://github.com/Ensembl/ensembl-vep/files/4719925/annotation.gtf.gz)
[input.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/4719926/input.vcf.gz)
[ref.fa.gz](https://github.com/Ensembl/ensembl-vep/files/4719927/ref.fa.gz)

**Comment by at7** [comment]
Hi,
this might be related to your input annotation file. Could you please change the exon and CDS phase (8th field) from 2 to 0 and then run haplosaurus again? Thank you for providing the input data which made it very easy for me to replicate the problem.

Thank you,
Anja

**Comment by iranmdl** [comment]
Hello!
Thank you for quick answer! You are 100% right, the mistake was on my side, and not in haplosaurus, with a wrong annotation of the exon and CDS frame.
Thank you very much, you have been really helpful. 
Regards,

Irantzu

**Comment by at7** [comment]
I'm glad it fixed the problem. I will close the ticket now.
