### ISSUE TITLE
./INSTALL.pl for version 100 does not work

### ISSUE THREAD

**Issue by znikasz** [Ensembl/ensembl-vep#746]
Hi there, 

I'm not sure if it's a correct place for submitting the issue, as it may not concern VEP but rather fhe Ensembl FTP maintainers, but anyway:

Installing VEP cache with release 100 fails:

Command:
```
docker run -it --rm -v /mnt/disk1/pio/wum/tmp/vep-cache:/opt/vep/.vep/ ensemblorg/ensembl-vep ./INSTALL.pl --AUTO cf --SPECIES homo_sapiens_merged --ASSEMBLY GRCh38
```

Gives an error:
```
Using default tag: latest
latest: Pulling from ensemblorg/ensembl-vep
Digest: sha256:7810977378d6048aa89ef3b6e7337a9c52a5fb044f9a5d1b476eb2be83db83b0
Status: Image is up to date for ensemblorg/ensembl-vep:latest
docker.io/ensemblorg/ensembl-vep:latest
 - getting list of available cache files
NB: Remember to use --merged when running the VEP with this cache!
 - downloading ftp://ftp.ensembl.org/pub/release-100/variation/indexed_vep_cache/homo_sapiens_merged_vep_100_GRCh38.tar.gz
curl failed (550), trying to fetch using LWP::Simple
LWP::Simple failed (404), trying to fetch using HTTP::Tiny
Use of uninitialized value in numeric eq (==) at /usr/share/perl/5.26/HTTP/Tiny.pm line 606.
Use of uninitialized value in numeric eq (==) at /usr/share/perl/5.26/HTTP/Tiny.pm line 606.
ERROR: Failed last resort of using HTTP::Tiny to download ftp://ftp.ensembl.org:21/pub/release-100/variation/indexed_vep_cache/CHECKSUMS
```

Which is correct, as there is no file `ftp://ftp.ensembl.org:21/pub/release-100/variation/indexed_vep_cache/CHECKSUMS` on the server. Is it a VEP bug, and it should not look for the CHECKSUMS file or is it an FTP server bug?

Thanks,

**Comment by aparton** [comment]
Hi,

Thanks for this report. Indeed, VEP is looking for a file that is missing, we’ll get that fixed as soon as possible.

In the meantime, you can download the cache file manually from ftp://ftp.ensembl.org/pub/release-100/variation/indexed_vep_cache/homo_sapiens_merged_vep_100_GRCh38.tar.gz <ftp://ftp.ensembl.org/pub/release-100/variation/indexed_vep_cache/homo_sapiens_merged_vep_100_GRCh38.tar.gz>, and decompress it in your ~/.vep folder, which will install the cache file correctly without the need for the installer.

Thanks for bringing this issue to our attention.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi, 

Just to let you know, this issue has been resolved now and the installer should work as normal. If you see any other issues, please let us know.

Kind Regards,
Andrew
