### ISSUE TITLE
Building custom RefSeq cache files from GFF

### ISSUE THREAD

**Issue by MaximilianStammnitz** [Ensembl/ensembl-vep#748]
Hi,

We are currently working on variant annotation comparisons between an old and new assembly of the same species (Tasmanian devil).

One of these references has been completed very recently, and so far annotations are only available via RefSeq (ENSEMBL following later in the year). Tried to find this in the VEP description/tutorial pages, and hope I didn't simply miss this part: for command line runs, is there a quick way to build your own VEP cache files from RefSeq GFFs/GTFs?

These are the two annotations I'd be interested in:
(1) https://ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/9305/102/GCF_000189315.1_Devil_ref_v7.0/GCF_000189315.1_Devil_ref_v7.0_genomic.gff.gz
(2) https://ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/9305/103/GCF_902635505.1_mSarHar1.11/GCF_902635505.1_mSarHar1.11_genomic.gff.gz

Many thanks,
Max

**Comment by aparton** [comment]
Hi @MaximilianStammnitz,

You can integrate annotations from standard format files into your VEP results by using the --custom flag. You can read more about this functionality and it's limitations here: https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html
https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gfftypes

If you have any more questions, please don't hesitate to ask.

Kind Regards,
Andrew

**Comment by MaximilianStammnitz** [comment]
Hi @aparton,

Many thanks. I just realised that the external GFF usages works when _only_ relying on the basic flags, rather than additionally trying to specify a --cache file, i.e.:
./vep -i -o --custom --fasta

Since it is an NCBI based GFF, I have now also hit [issue 732](https://github.com/Ensembl/ensembl-vep/issues/732) regarding miRNA annotations with parent transcripts, please keep us posted when this is solved.

Best regards,
Max

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew
