### ISSUE TITLE
GENCODE version (32/33/34) inconsistencies

### ISSUE THREAD

**Issue by sigven** [Ensembl/ensembl-vep#749]
## Describe the issue
From what I can see, it seems there is some misleading information regarding GENCODE release in version 100 (grch38). In the VCF output file from version 100, VEP outputs `gencode="GENCODE 32"`, while in the website describing [contents of the pre-indexed cache](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#database), it states that GENCODE v33 is used for grch38. However, when interrogating the results from a testrun, I found a transcript in the output ([ENST00000674496](http://www.ensembl.org/homo_sapiens/Transcript/Summary?t=ENST00000674496&db=core)), which I am not able to find in the [GTF files of 32 or 33](https://www.gencodegenes.org/human/releases.html), but only in 34. From this I am thinking that VEP 100 is using GENCODE v34 for grch38, and that the documentation/code needs to be updated?

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 100
- VEP Cache version: 100
- Perl version: 5.26
- OS: Ubuntu
- tabix installed ? Yes

### Full VEP command line
Not relevant

### Full error message
Not relevant

### Data files (if applicable)
Not relevant

**Comment by ima23** [comment]
Hi @sigven,

Thanks for your message, indeed the correct version is Gencode 34, the corresponding meta data will be updated to reflect this. We'll let you know when the update is in.

Kind regards,
Irina

**Comment by ima23** [comment]
Hi @sigven, 

the info field in the cache has been updated and the live website is also now up to date. Thanks for letting us know about the discrepancy. I will close the ticket now.

Kind regards,
Irina
