### ISSUE TITLE
VEP R100 installation error with Bio::DB::HTS (libhts.so) and a solution

### ISSUE THREAD

**Issue by conanyangqun** [Ensembl/ensembl-vep#754]
A similar question to #733 ,but not the same.

Hi,
I am installing vep R100 from a fresh start, and follow all steps in documentation.
Briefly,
1. Installing 3 perl modules (Archive::Zip, DBI, DBD::mysql)
2. Installing VEP API using INSTALL.pl.

The installation ends with a warning for lib/Bio/DB/HTS.xs and an Error: **Cannot use format gff without Bio::DB::HTS::Tabix module installed**.

Because of the error above, I can not annotate a vcf file using vep. The same error.

I find vep folder contains `Bio/DB/HTS/Tabix.pm`, so I set PERL5LIB using `export PERL5LIB=VEP-folder` and run `perl -e "use Bio::DB::HTS::Tabix"`. And it says `libhts.so.3 cannot open shared object file: no such file...`.  So I check the htslib in vep folder, and find it has a `libhts.so.2`, not the `libhts.so.3`。

My solution is `ln -s libhts.so libhts.so.3`, and everything seems ok.
So, I think this is bug in the code.

**Comment by aparton** [comment]
Hi @conanyangqun,

Thank you for this report. Could you please tell me which operating system you're using?

Kind Regards,
Andrew

**Comment by conanyangqun** [comment]
> Hi @conanyangqun,
> 
> Thank you for this report. Could you please tell me which operating system you're using?
> 
> Kind Regards,
> Andrew

Hi, @aparton 
I am using Centos7.6.1810.

**Comment by likhitha-surapaneni** [comment]
Hi @conanyangqun, 

I am closing this issue for now. Please feel free to reopen the issue if the problem still persists.
