### ISSUE TITLE
ClinVar fields not consistent 

### ISSUE THREAD

**Issue by EugeneEA** [Ensembl/ensembl-vep#759]
## Describe the issue
I'm trying to annotate a toy example of two SNP and get CLIN_SIG and CLNREVSTAT fields. 
here is the input vcf wo header:
`#CHROM	POS	ID	REF	ALT	QUAL	FILTER
chr7	140749365 	.	A	T	50	PASS
chr7	140753339	.	G	C	50	PASS
`

both SNP are in BRAF protein, Pathogenic and have a clinVar records (I'm using latest version of clinvar as custom annotation, and check it there). 

But the problem here is - for some reason there are no CLIN_SIG and CLNREVSTAT fields for the first SNP. I've double check the raw clinVar file and it is there, so I'm quite confused...

###  Here is the Full VEP command line (run from the docker container)

`~/src/ensembl-vep$ time ./vep --cache --offline --format vcf --vcf --force_overwrite --dir_cache /opt/vep/.vep/ --input_file /opt/vep/.vep/input/test_chr_renamed.vcf --output_file /opt/vep/.vep/output/my_output.vcf --buffer_size 10000  --fork 30 --custom /opt/vep/.vep/custom/clinvar.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNREVSTAT,CLNDN`

and here is the VEP output (sorry for the mess):

`#CHROM	POS	ID	REF	ALT	QUAL	FILTER
7	140749365 	.	A	T	50	PASS	CSQ=T|missense_variant|MODERATE|BRAF|ENSG00000157764|Transcript|ENST00000288602|protein_coding|17/19||||2063|2034|678|D/E|gaT/gaA|||-1||HGNC|HGNC:1097|||||,T|missense_variant&NMD_transcript_variant|MODERATE|BRAF|ENSG00000157764|Transcript|ENST00000479537|nonsense_mediated_decay|6/9||||584|585|195|D/E|gaT/gaA|||-1|cds_start_NF|HGNC|HGNC:1097|||||,T|missense_variant|MODERATE|BRAF|ENSG00000157764|Transcript|ENST00000496384|protein_coding|16/19||||2021|1914|638|D/E|gaT/gaA|||-1||HGNC|HGNC:1097|||||,T|3_prime_UTR_variant&NMD_transcript_variant|MODIFIER|BRAF|ENSG00000157764|Transcript|ENST00000497784|nonsense_mediated_decay|17/19||||2000|||||||-1||HGNC|HGNC:1097|||||,T|3_prime_UTR_variant&NMD_transcript_variant|MODIFIER|BRAF|ENSG00000157764|Transcript|ENST00000642228|nonsense_mediated_decay|16/18||||1904|||||||-1||HGNC|HGNC:1097|||||,T|non_coding_transcript_exon_variant|MODIFIER|BRAF|ENSG00000157764|Transcript|ENST00000642875|retained_intron|12/15||||1312|||||||-1||HGNC|HGNC:1097|||||,T|non_coding_transcript_exon_variant|MODIFIER|BRAF|ENSG00000157764|Transcript|ENST00000644120|processed_transcript|15/17||||2304|||||||-1||HGNC|HGNC:1097|||||,T|missense_variant&NMD_transcript_variant|MODERATE|BRAF|ENSG00000157764|Transcript|ENST00000644650|nonsense_mediated_decay|10/14||||1010|1011|337|D/E|gaT/gaA|||-1|cds_start_NF|HGNC|HGNC:1097|||||,T|non_coding_transcript_exon_variant|MODIFIER|BRAF|ENSG00000157764|Transcript|ENST00000644905|retained_intron|16/18||||2796|||||||-1||HGNC|HGNC:1097|||||,T|missense_variant|MODERATE|BRAF|ENSG00000157764|Transcript|ENST00000644969|protein_coding|17/20||||2034|2034|678|D/E|gaT/gaA|||-1||HGNC|HGNC:1097|||||,T|3_prime_UTR_variant&NMD_transcript_variant|MODIFIER|BRAF|ENSG00000157764|Transcript|ENST00000646730|nonsense_mediated_decay|18/21||||2250|||||||-1||HGNC|HGNC:1097|||||,T|missense_variant|MODERATE|BRAF|ENSG00000157764|Transcript|ENST00000646891|protein_coding|16/18||||2139|1914|638|D/E|gaT/gaA|||-1||HGNC|HGNC:1097|||||,T|missense_variant&NMD_transcript_variant|MODERATE|BRAF|ENSG00000157764|Transcript|ENST00000647434|nonsense_mediated_decay|8/10||||791|791|264|M/K|aTg/aAg|||-1|cds_start_NF|HGNC|HGNC:1097|||||
7	140753339	.	G	C	50	PASS	CSQ=C|missense_variant|MODERATE|BRAF|ENSG00000157764|Transcript|ENST00000288602|protein_coding|16/19||||1945|1916|639|T/R|aCa/aGa|||-1||HGNC|HGNC:1097||280033|Pathogenic|criteria_provided&_multiple_submitters&_no_conflicts|Cardiofaciocutaneous_syndrome_1&not_provided,C|missense_variant&NMD_transcript_variant|MODERATE|BRAF|ENSG00000157764|Transcript|ENST00000479537|nonsense_mediated_decay|5/9||||466|467|156|T/R|aCa/aGa|||-1|cds_start_NF|HGNC|HGNC:1097||280033|Pathogenic|criteria_provided&_multiple_submitters&_no_conflicts|Cardiofaciocutaneous_syndrome_1&not_provided,C|missense_variant|MODERATE|BRAF|ENSG00000157764|Transcript|ENST00000496384|protein_coding|15/19||||1903|1796|599|T/R|aCa/aGa|||-1||HGNC|HGNC:1097||280033|Pathogenic|criteria_provided&_multiple_submitters&_no_conflicts|Cardiofaciocutaneous_syndrome_1&not_provided,C|3_prime_UTR_variant&NMD_transcript_variant|MODIFIER|BRAF|ENSG00000157764|Transcript|ENST00000497784|nonsense_mediated_decay|16/19||||1882|||||||-1||HGNC|HGNC:1097||280033|Pathogenic|criteria_provided&_multiple_submitters&_no_conflicts|Cardiofaciocutaneous_syndrome_1&not_provided,C|3_prime_UTR_variant&NMD_transcript_variant|MODIFIER|BRAF|ENSG00000157764|Transcript|ENST00000642228|nonsense_mediated_decay|15/18||||1786|||||||-1||HGNC|HGNC:1097||280033|Pathogenic|criteria_provided&_multiple_submitters&_no_conflicts|Cardiofaciocutaneous_syndrome_1&not_provided,C|intron_variant&non_coding_transcript_variant|MODIFIER|BRAF|ENSG00000157764|Transcript|ENST00000642875|retained_intron||11/14||||||||||-1||HGNC|HGNC:1097||280033|Pathogenic|criteria_provided&_multiple_submitters&_no_conflicts|Cardiofaciocutaneous_syndrome_1&not_provided,C|non_coding_transcript_exon_variant|MODIFIER|BRAF|ENSG00000157764|Transcript|ENST00000644120|processed_transcript|14/17||||2186|||||||-1||HGNC|HGNC:1097||280033|Pathogenic|criteria_provided&_multiple_submitters&_no_conflicts|Cardiofaciocutaneous_syndrome_1&not_provided,C|missense_variant&NMD_transcript_variant|MODERATE|BRAF|ENSG00000157764|Transcript|ENST00000644650|nonsense_mediated_decay|9/14||||892|893|298|T/R|aCa/aGa|||-1|cds_start_NF|HGNC|HGNC:1097||280033|Pathogenic|criteria_provided&_multiple_submitters&_no_conflicts|Cardiofaciocutaneous_syndrome_1&not_provided,C|non_coding_transcript_exon_variant|MODIFIER|BRAF|ENSG00000157764|Transcript|ENST00000644905|retained_intron|15/18||||2678|||||||-1||HGNC|HGNC:1097||280033|Pathogenic|criteria_provided&_multiple_submitters&_no_conflicts|Cardiofaciocutaneous_syndrome_1&not_provided,C|missense_variant|MODERATE|BRAF|ENSG00000157764|Transcript|ENST00000644969|protein_coding|16/20||||1916|1916|639|T/R|aCa/aGa|||-1||HGNC|HGNC:1097||280033|Pathogenic|criteria_provided&_multiple_submitters&_no_conflicts|Cardiofaciocutaneous_syndrome_1&not_provided,C|3_prime_UTR_variant&NMD_transcript_variant|MODIFIER|BRAF|ENSG00000157764|Transcript|ENST00000646730|nonsense_mediated_decay|17/21||||2132|||||||-1||HGNC|HGNC:1097||280033|Pathogenic|criteria_provided&_multiple_submitters&_no_conflicts|Cardiofaciocutaneous_syndrome_1&not_provided,C|missense_variant|MODERATE|BRAF|ENSG00000157764|Transcript|ENST00000646891|protein_coding|15/18||||2021|1796|599|T/R|aCa/aGa|||-1||HGNC|HGNC:1097||280033|Pathogenic|criteria_provided&_multiple_submitters&_no_conflicts|Cardiofaciocutaneous_syndrome_1&not_provided,C|intron_variant&NMD_transcript_variant|MODIFIER|BRAF|ENSG00000157764|Transcript|ENST00000647434|nonsense_mediated_decay||7/9||||||||||-1|cds_start_NF|HGNC|HGNC:1097||280033|Pathogenic|criteria_provided&_multiple_submitters&_no_conflicts|Cardiofaciocutaneous_syndrome_1&not_provided
`

### System
  ensembl              : 99.d3e7d31
  ensembl-funcgen      : 99.0832337
  ensembl-io           : 99.441b05b
  ensembl-variation    : 99.a7f8736
  ensembl-vep          : 99.2

 tabix installed  -Yes

### Data files (if applicable)
They include:
- The input file
[test_input.txt](https://github.com/Ensembl/ensembl-vep/files/4640892/test_input.txt)

- The output file
[my_output.txt](https://github.com/Ensembl/ensembl-vep/files/4640890/my_output.txt)

**Comment by aparton** [comment]
Hi,

Thank you for this report. This issue is caused by a whitespace character attached to the coordinate column of the first variant in your file. This has caused VEP to miss some colocated variants.

I'll let you know when there is a fix in place. In the meantime, removing the whitespace from your input file should resolve your issue.

If you have any more questions, please get in touch.

Kind Regards,
Andrew

**Comment by EugeneEA** [comment]
Thaks a lot and sorry for bothering you with such a newbie mistake (
