### ISSUE TITLE
perl INSTALL.pl failed due to connetion?

### ISSUE THREAD

**Issue by MatthewP-Newbee** [Ensembl/ensembl-vep#760]
I have internet access and already installed `curl`, `LWP::Simple` and `HTTP::Tiny` what may the problem?
```
$perl INSTALL.pl curl failed (000), trying to fetch using LWP::Simple
LWP::Simple failed (501), trying to fetch using HTTP::Tiny  
ERROR: Failed last resort of using HTTP::Tiny to download https://api.github.com/repos/Ensembl/ensembl-vep
```

**Comment by aparton** [comment]
Hiya,

To help us better diagnose your problem, could you please tell us:

1) What happens when you run `curl -0 https://api.github.com/repos/Ensembl/ensembl-vep`?

2) Which operating system and perl version are you using?

Kind Regards,
Andrew

**Comment by MatthewP-Newbee** [comment]
`curl -0 https://api.github.com/repos/Ensembl/ensembl-vep` prints very long json format output, I will just paste a few lines unless you want to see all of them.
```
$curl -0 https://api.github.com/repos/Ensembl/ensembl-vep
{
  "id": 55504797,
  "node_id": "MDEwOlJlcG9zaXRvcnk1NTUwNDc5Nw==",
  "name": "ensembl-vep",
  "full_name": "Ensembl/ensembl-vep",
  "private": false,
  "owner": {
    "login": "Ensembl",
    "id": 5832463,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjU4MzI0NjM=",
    "avatar_url": "https://avatars3.githubusercontent.com/u/5832463?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Ensembl",
    "html_url": "https://github.com/Ensembl",

```
My system is `centos7` and perl is `perl 5`
```
$cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

$perl --version

This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi

Copyright 1987-2018, Larry Wall
```
My perl is installed in conda environment.

**Comment by aparton** [comment]
Hi @MatthewP-Newbee,

If your host machine is able to successfully use curl, I suspect it is a permissions issue related to your conda environment installation of perl. Unfortunately, this is not something that we will be able to provide detailed support for.

If you continue to have issues, may I suggest taking a look at our docker image, which you can find here: https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker

If you have any other questions, please don't hesitate to ask.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi @MatthewP-Newbee,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new one.

Kind Regards,
Andrew

**Comment by biofilos** [comment]
In case anyone is still facing this issue and has no connection issues, make sure that `curl` is installed. I might have missed it from the docs, but this was the problem I had. Once I installed curl, the installed worked as expected
