### ISSUE TITLE
VEP doesn't catch gnomAD AF

### ISSUE THREAD

**Issue by cccnrc** [Ensembl/ensembl-vep#764]
I found some inconsistencies between VEP annotated VCF gnomAD fields and gnomAD actual DB.

I am using VEP v98 on a Debian 9 machine. dbNSFP v4.0a.

As example, variant 12-116398626-A-C ([here gnomAD page](https://gnomad.broadinstitute.org/variant/12-116398626-A-C)) is reported with a genome AF of 0.378 (37.8%).

If I isolate this variant only from VCF file (attached 
[161618.normalized.vcf.ch12_116398626.vcf.txt](https://github.com/Ensembl/ensembl-vep/files/4652641/161618.normalized.vcf.ch12_116398626.vcf.txt)
):
`chr12	116398626	.	A	C	584.19	PASS	AC=2;AF=0.333;AN=6;BaseQRankSum=-1.007;ClippingRankSum=0;DP=42;ExcessHet=3.9794;FS=0;MLEAC=2;MLEAF=0.333;MQ=60;MQ0=0;MQRankSum=0;QD=17.7;ReadPosRankSum=-0.279;SOR=1.022	GT:AD:DP:GQ:PL	0/1:7,8:15:99:230,0,232	0/1:7,11:18:99:386,0,236	0/0:9,0:9:24:0,24,360`
 
and pass it through VEP with `--af_gnomad` and `dbNSFP gnomad attributes` flags:

`
time /home/enrico/vep/ensembl-vep/vep -v \
                 -i "${sample_vcf_normalized}.ch12_116398626.vcf" --format vcf \
                 --cache --dir_cache /media/enrico/vep_disk/vep_files/ --merged --use_given_ref \
                 --fasta /media/enrico/vep_disk/vep_files/fasta/GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz \
                 --dir_plugins /media/enrico/vep_disk/vep_files/Plugins/ \
                 --assembly GRCh37 \
                 --offline \
                 --minimal \
                 --vcf \
                 --hgvs \
                 --no_stats \
                 --symbol \
                 --allele_number \
                 --pick \
                 --no_intergenic \
                 --gencode_basic \
                 --sift b \
                 --polyphen b \
                 --plugin SingleLetterAA \
                 --plugin dbNSFP,/media/enrico/vep_disk/vep_files/plugin_databases/dbNSFP/dbNSFP4.0a.gz,LRT_score,LRT_pred,GERP++_RS,MutationTaster_pred,MutationTaster_score,MutationAssessor_pred,MutationAssessor_score,FATHMM_score,FATHMM_pred,1000Gp3_AC,1000Gp3_AF,1000Gp3_AFR_AC,1000Gp3_AFR_AF,1000Gp3_EUR_AC,1000Gp3_EUR_AF,1000Gp3_AMR_AC,1000Gp3_AMR_AF,1000Gp3_EAS_AC,1000Gp3_EAS_AF,1000Gp3_SAS_AC,1000Gp3_SAS_AF,UK10K_AF,ESP6500_AA_AF,ESP6500_EA_AF,gnomAD_exomes_POPMAX_AF,gnomAD_exomes_POPMAX_nhomalt,gnomAD_genomes_POPMAX_AF,gnomAD_genomes_POPMAX_nhomalt,GTEx_V7_gene,GTEx_V7_tissue,Geuvadis_eQTL_target_gene,Polyphen2_HDIV_score,Polyphen2_HDIV_pred,Polyphen2_HVAR_score,Polyphen2_HVAR_pred,ExAC_AC,ExAC_AF,ExAC_Adj_AF,ExAC_AFR_AC,ExAC_AFR_AF,ExAC_AMR_AC,ExAC_AMR_AF,ExAC_EAS_AC,ExAC_EAS_AF,ExAC_FIN_AC,ExAC_FIN_AF,ExAC_NFE_AC,ExAC_NFE_AF,ExAC_SAS_AC,ExAC_SAS_AF,REVEL_score,REVEL_rankscore,clinvar_id,clinvar_clnsig,clinvar_trait,clinvar_review,clinvar_hgvs,clinvar_var_source,clinvar_MedGen_id,clinvar_OMIM_id,clinvar_Orphanet_id,CADD_phred,ExAC_Adj_AC,gnomAD_exomes_AN,gnomAD_exomes_AC,gnomAD_genomes_AN,gnomAD_genomes_AC,gnomAD_exomes_controls_AC,gnomAD_exomes_controls_AN,gnomAD_exomes_AFR_AF,gnomAD_exomes_AMR_AF,gnomAD_exomes_ASJ_AF,gnomAD_exomes_EAS_AF,gnomAD_exomes_FIN_AF,gnomAD_exomes_NFE_AF,gnomAD_exomes_SAS_AF,gnomAD_exomes_controls_AF,gnomAD_genomes_controls_AC,gnomAD_genomes_controls_AN,gnomAD_genomes_AFR_AF,gnomAD_genomes_AMR_AF,gnomAD_genomes_ASJ_AF,gnomAD_genomes_EAS_AF,gnomAD_genomes_FIN_AF,gnomAD_genomes_NFE_AF,gnomAD_genomes_controls_AF,genename \
                 --custom /media/enrico/vep_disk/vep_files/manual_annotations/clinvar/clinvar_20191118.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNREVSTAT,CLNDN,CLNDISDB \
                 --force_overwrite \
                 --af_gnomad \
                 -o "${sample_vcf_normalized}.ch12_116398626.vep.vcf"
`

I got an empty fields for both, as the variant wouldn't be in gnomAD! (attached the results file 
[161618.normalized.vcf.ch12_116398626.vep.vcf.txt](https://github.com/Ensembl/ensembl-vep/files/4652637/161618.normalized.vcf.ch12_116398626.vep.vcf.txt) )

Does anybody knows why?!

Thank you in advance for any help

**Comment by dglemos** [comment]
Hi, 
The variant you're looking at comes from gnomAD genomes and VEP caches only have gnomAD exome frequency data. 
To add gnomAD genomes data you can use custom annotation as explained here: https://www.ensembl.org/info/docs/tools/vep/script/vep_example.html#gnomad

**Comment by cccnrc** [comment]
Hi Diana @dglemos , thank you for the explanation, but this does not explain why it's not caught by `dbNSFP` that has gnomAD genomes fields and flagged in my command:
`
gnomAD_genomes_POPMAX_AF
gnomAD_genomes_POPMAX_nhomalt
gnomAD_genomes_AN
gnomAD_genomes_AC
gnomAD_genomes_controls_AC
gnomAD_genomes_controls_AN
gnomAD_genomes_AFR_AF
gnomAD_genomes_AMR_AF
gnomAD_genomes_ASJ_AF
gnomAD_genomes_EAS_AF
gnomAD_genomes_FIN_AF
gnomAD_genomes_NFE_AF
gnomAD_genomes_controls_AF
`

Why is the plugin not catching it??

**Comment by dglemos** [comment]
The variant 12-116398626-A-C is a 3_prime_UTR_variant (c.*445T>G) and dbNSFP only covers missense mutations. From the website: 'dbNSFP is a database developed for functional prediction and annotation of all potential non-synonymous single-nucleotide variants'.
