### ISSUE TITLE
VEP output prints duplicate of each variants twice

### ISSUE THREAD

**Issue by ranijames** [Ensembl/ensembl-vep#766]
## Describe the issue
I am running VEP tool for predicting the variant consequence. The input is a VCF file and my output is a txt file.
However, the tool generates a duplicated line for each variant. For example,
```
1:943961:G:A	1:943961	A	ENSG00000188976	ENST00000327044	Transcript	downstream_gene_variant	-	-	-	-	-	-	MODIFIER	242	-1	-	-	-
1:943961:G:A	1:943961	A	ENSG00000188976	ENST00000327044	Transcript	downstream_gene_variant	-	-	-	-	-	-	MODIFIER	242	-1	-	Homo_sapiens.GRCh38.97.gtf.gz	-
1:943961:G:A	1:943961	A	ENSG00000187634	ENST00000341065	Transcript	synonymous_variant	1577	1578	526	L	ctG/ctA	-	LOW	-	1	-	Homo_sapiens.GRCh38.97.gtf.gz	-
1:943961:G:A	1:943961	A	ENSG00000187634	ENST00000341065	Transcript	synonymous_variant	1577	1578	526	L	ctG/ctA	-	LOW	-	1	cds_start_NF	-	-
1:943961:G:A	1:943961	A	ENSG00000187634	ENST00000342066	Transcript	synonymous_variant	1944	1854	618	L	ctG/ctA	-	LOW	-	1	-	-	-
1:943961:G:A	1:943961	A	ENSG00000187634	ENST00000342066	Transcript	synonymous_variant	1944	1854	618	L	ctG/ctA	-	LOW	-	1	-	Homo_sapiens.GRCh38.97.gtf.gz	- 
```
Here for each variant it has a line with `Homo_sapiens.GRCh38.97.gtf.gz` and without `Homo_sapiens.GRCh38.97.gtf.gz`. All other column values are same.

### System
- VEP version: 99.0
- VEP Cache version: 99.0
- Perl version: 
- OS: Ubuntu 18 LTS
- tabix installed: yes

### Full VEP command line
```
    """
    vep \
    --offline \
    --dir "${ref_dir}" \
    --assembly "${assembly}" \
    --fasta "${refFasta}" \
    --gtf "${GTF}" \
    --force_overwrite \
    --species homo_sapiens \
    -i "${vcf}" \
    --stats_file "${output_html}" \
    --tab \
    -o "${output_file}"
    ""
```
The input for gtf `/Homo_sapiens.GRCh38.97.gtf.gz ` and `--fasta`  is `Homo_sapiens.GRCh38.dna.primary_assembly.fa`. The gtf is tabix index and fatsa file has also its indexed version within the reference diectory. I am runing everything via nextflow pipeline within the docker.

**Comment by dglemos** [comment]
Hi,
Thanks for the detailed explanation. 
You are using two annotation sources: the cache (--cache) and the gtf file (--gtf) and the output contains one line for each source. That's why the output has duplicated variants:
```
(cache) 1:943961:G:A	1:943961	A	ENSG00000188976	ENST00000327044	Transcript	downstream_gene_variant	-	-	-	-	-	-	MODIFIER	242	-1	-	-	-
(gtf) 1:943961:G:A	1:943961	A	ENSG00000188976	ENST00000327044	Transcript	downstream_gene_variant	-	-	-	-	-	-	MODIFIER	242	-1	-	Homo_sapiens.GRCh38.97.gtf.gz	-
```
Let me know if you have further questions.

**Comment by ranijames** [comment]
hi
Thanks for the reply.
I ran agagin without `--cache` parameter.
Still the output looks the same.
Here is what I tried ,
```
 """
    vep \
    --offline \
    --dir "${ref_dir}" \
    --assembly "${assembly}" \
    --fasta "${refFasta}" \
    --gtf "${GTF}" \
    --force_overwrite \
    --species homo_sapiens \
    -i "${vcf}" \
    --stats_file "${output_html}" \
    --tab \
    -o "${output_file}"

```

**Comment by dglemos** [comment]
Try to run again without using `--offline` option. 
`--offline` switches on `--cache` which is why you are still getting both annotations.

**Comment by ranijames** [comment]
Thanks it helped.!!

**Comment by dglemos** [comment]
Glad to know it worked. I'm closing this ticket but if you have more questions feel free to open a new one.
