### ISSUE TITLE
Issue with finding chromosome identifier in synonym file

### ISSUE THREAD

**Issue by robackem** [Ensembl/ensembl-vep#768]
### Description of the issue:
I am running multiple _Astyanax mexicanus_ VCF files through VEP using the ensembl cache for the species. My VCFs denote location using NW numbers while the GTF annotation uses chromosome number and APWO, so I have been using a synonym file. I have a VCF file for each chromosome, which have run through VEP no problem. But, I also have a few VCF files of unplaced scaffolds and when these are run I get an error that some of the chromosome identifiers could not be found in the synonyms file, like this... 

`WARNING: Chromosome NW_019170560.1 not found in annotation sources or synonyms on line 1
`

When I search in the synonym file for these NW numbers VEP says it could not find I see that they actually are listed with their corresponding APWO, so I am unsure why I am getting this error. According to the warning file there are 213 instances where the synonym couldn't be found, so it seems that VEP is finding some of the unplaced scaffold synonyms but not others. 

### System information:
- VEP version: 100
- VEP Cache version: 100
- Perl version: 5.26
- OS: Files are being run on an HP Linux distributed cluster, OS is CentOS
- tabix installed: no

### Full VEP command line:
```
./vep 
--species astyanax_mexicanus 
--cache 
--synonyms ~/.vep/astyanax_mexicanus/100_Astyanax_mexicanus-2.0/chr_synonyms.txt 
--offline 
-i ~/path/to/Chr_Un_1_Subset.vcf.gz --format vcf 
-o ~/path/to/Chr_Un_1_Subset_VEP.txt --tab --fields 
"Uploaded_variation,Location,Allele,Gene,Feature,Feature_type,Consequence,cDNA_position,
CDS_position,Protein_position,Amino_acids,Codons,Existing_variation,IMPACT,VARIANT_CLASS,
STRAND,FLAGS,FREQS,ALLELE_NUM" 
--variant_class 
--allele_number 
--stats_file ~/path/to/Chr_Un_1_Subset_VEP.html
```

### Data files:
Warning file -> [Chr_Un_1_Subset_VEP.txt_warnings.txt](https://github.com/Ensembl/ensembl-vep/files/4663006/Chr_Un_1_Subset_VEP.txt_warnings.txt)
Synonym file -> [chr_synonyms.txt](https://github.com/Ensembl/ensembl-vep/files/4663015/chr_synonyms.txt)

Thank you!

**Comment by at7** [comment]
Hi,
the reason you see the warning message is because we don't have any transcripts for the specified unplaced scaffold and therefore cannot calculate any overlaps with your input variants. We create a folder for each assembly component (e.g. chromosome, contigs or scaffolds) in the cache directory but only include components with annotated transcripts. I can see that the message  is misleading and we will improve the message in a future release.
Please let me know if you have any further questions.

Best wishes,
Anja

**Comment by robackem** [comment]
Ah, that totally makes sense. Thank you!
