### ISSUE TITLE
Docs: add corresponding ID tags to flags

### ISSUE THREAD

**Issue by matthdsm** [Ensembl/ensembl-vep#77]
Hi,

Would it be possible to add the CSQ tag names corresponding to the different flags to the docs.
We annotate our vcf's with pretty much everything VEP has to offer, so it gets a bit hard to differentiate which field corresponds to which field name. This is especially true for the population annotations (except gnomAD, since the name is included in the field).

Thanks a lot.
Cheers
M

**Comment by willmclaren** [comment]
We can do that, yes.

In the short term, if you can parse a bit of perl data structure you can see which flags populate which fields here: https://github.com/Ensembl/ensembl-vep/blob/release/90/modules/Bio/EnsEMBL/VEP/Constants.pm#L64-L122

**Comment by matthdsm** [comment]
Allright, thanks for the pointer!
M

**Comment by willmclaren** [comment]
Would this be most useful as a separate table, or would it be sufficient to add the field names to each options' documentation entry on http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html ?

**Comment by matthdsm** [comment]
We're not planning to parse this automatically, it's mostly for internal documentation and accreditation.
I think adding it to the options page would already be a great help. I'd say do what you feel is best/ least hassle. As long as it's possible to get the info we're very happy 😄 

Thanks for the quick reply!
M

**Comment by willmclaren** [comment]
Closed via https://github.com/Ensembl/public-plugins/commit/cf001e1af06eb8a0815a28d3a797d93e0a984fb3
