### ISSUE TITLE
MaxEntScan without cache

### ISSUE THREAD

**Issue by rollf** [Ensembl/ensembl-vep#773]
## Describe the issue
When providing a custom GFF file and no cache, there is no MaxEntScan result in the output. I am not sure whether this is expected behaviour.

### System
VEP docker image as of 29th May 2020. This should be VEP 100 I believe.

### Full VEP command line
```
$ time docker run -t -i -v $HOME/vep_data:/opt/vep/.vep -v $HOME/scratch:/scratch ensemblorg/ensembl-vep vep -i /scratch/input.vcf --gff /scratch/GCF_000001405.25_GRCh37.p13_genomic.no-miRNA.gff.bgz --fasta /scratch/GRCh37.fa.gz --plugin MaxEntScan,/scratch/fordownload --output_file /scratch/out.txt --force_overwrite

$ time docker run -t -i -v $HOME/vep_data:/opt/vep/.vep -v $HOME/scratch:/scratch ensemblorg/ensembl-vep vep -i /scratch/input.vcf --gff /scratch/GCF_000001405.25_GRCh37.p13_genomic.no-miRNA.gff.bgz --fasta /scratch/GRCh37.fa.gz --plugin MaxEntScan,/scratch/fordownload --output_file /scratch/out.txt --force_overwrite --cache  --merged --offline
```

### Output

```
# without cache
...
rs2232486	NC_000017.10:1968983	C	23293	NM_017575.5	Transcript	intron_variant	-	-	-	-	-	-	IMPACT=MODIFIER;STRAND=-1;SOURCE=GCF_000001405.25_GRCh37.p13_genomic.no-miRNA.gff.bgz

# with cache
...
rs2232486	NC_000017.10:1968983	C	23293	NM_017575.5	Transcript	intron_variant	-	-	-	-	-	-	IMPACT=MODIFIER;STRAND=-1;SOURCE=GCF_000001405.25_GRCh37.p13_genomic.no-miRNA.gff.bgz;GIVEN_REF=T;USED_REF=T;MaxEntScan_alt=5.749;MaxEntScan_diff=-0.599;MaxEntScan_ref=5.150
rs2232486	NC_000017.10:1968983	C	23293	NM_017575.4	Transcript	intron_variant	-	-	-	-	-	-	IMPACT=MODIFIER;STRAND=-1;SOURCE=RefSeq;GIVEN_REF=T;USED_REF=T;MaxEntScan_alt=5.749;MaxEntScan_diff=-0.599;MaxEntScan_ref=5.150
```

I'm happy to provide further details. 

Notes:
- I ran into #732 / #748 and simply created a new GTF without the offending lines
- The cache version does provide MaxEntScan scores for both sources (custom GFF as well as from RefSeq)
- I omitted the other transcripts for brevity.
- The MaxEntScan data folder is named "fordownload" (see plugin desc for details) and I put it into the scratch folder.

**Comment by at7** [comment]
Hi Rolf,

I will need to run this myself to be able to debug why you are missing the scores when you only run with the GFF option. Can I double check that it is fine to use https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.25_GRCh37.p13/GCF_000001405.25_GRCh37.p13_genomic.gff.gz ? Did you have to modify this GFF file?

Thank you,
Anja

**Comment by rollf** [comment]
Hi @at7,

sorry for the delay. Yes, is the GFF file I used. I modified it like so (see #732 / #748):

```
# Remove offending miRNA entries
grep -v miRNA GCF_000001405.25_GRCh37.p13_genomic.gff > GCF_000001405.25_GRCh37.p13_genomic.no-miRNA.gff
# Proceed as explained here https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff
grep -v "#" GCF_000001405.25_GRCh37.p13_genomic.no-miRNA.gff | sort -k1,1 -k4,4n -k5,5n -t$'\t' | bgzip -c > GCF_000001405.25_GRCh37.p13_genomic.no-miRNA.gff.bgz
tabix -p gff GCF_000001405.25_GRCh37.p13_genomic.no-miRNA.gff.bgz
```

Thanks in advance!

**Comment by at7** [comment]
Hi,
thank you for the details. I can reproduce the missing score when only using the gff option. The reason for this is a mismatch between the chromosome names that are used in the GFF and FASTA files. If your input looks like this NC_000017.10  1968983  rs2232486  T  C, you need to create a synonym file mapping NC_000017.10 to chr17. You need to specify the location with --synonyms [file]. The option is described [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#ident), last option in the Identifiers section.

Best wishes,
Anja

**Comment by rollf** [comment]
Ah, thank you very much Anja!

**Comment by rollf** [comment]
Just for reference, I used [GRCh37_NCBI2UCSC.txt](https://github.com/dpryan79/ChromosomeMappings/blob/master/GRCh37_NCBI2UCSC.txt) as input for ``--synonyms``. I also added the following lines to this file
```
NC_000001.10    1
NC_000002.11    2
NC_000003.11    3
NC_000004.11    4
NC_000005.9     5
NC_000006.11    6
NC_000007.13    7
NC_000008.10    8
NC_000009.11    9
NC_000010.10    10
NC_000011.9     11
NC_000012.11    12
NC_000013.10    13
NC_000014.8     14
NC_000015.9     15
NC_000016.9     16
NC_000017.10    17
NC_000018.9     18
NC_000019.9     19
NC_000020.10    20
NC_000021.8     21
NC_000022.10    22
NC_000023.10    X
NC_000024.9     Y
NC_012920.1     M
```

(I copied ``NC_000001.10    chr1`` and removed "chr". Same for all other chromosomes.)

**Comment by at7** [comment]
Thank you for sharing this. It is helpful to know.
