### ISSUE TITLE
GERP discrepancies between hg19 and hg38

### ISSUE THREAD

**Issue by jazberna1** [Ensembl/ensembl-vep#774]
## Describe the issue
Dear VEP team,

I have noticed the following discrepancies when calculating GERP values on two variants with hg19 and hg38.
In summary I have two variants for which GERP values vary significantly between the two builds.
I thought to send the ticket here too to as I used a VEP plugin to get the GERP values.

## Additional information
First these are the two variants in the hg38 assembly coordiante system:

##fileformat=VCFv4.0
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
20	57563613	.	G	A	.	.	.
20	57565383        .       G	A	.	.       .

Then I go and get their GERP (using VEP) with this .bw file from Compara.
ftp://ftp.ensembl.org/pub/release-100/compara/conservation_scores/103_mammals.gerp_conservation_score/gerp_conservation_scores.homo_sapiens.GRCh38.bw

This is my VEP command to get the GERP values:

```
./vep \
--species human --assembly GRCh38 \
--show_ref_allele \
-i /opt/vep/src/ensembl-vep/jorge/gerp_condel.vcf \
-o /opt/vep/src/ensembl-vep/jorge/gerp_condel.vep.vcf \
--custom /opt/vep/src/ensembl-vep/jorge/gerp_conservation_scores.homo_sapiens.GRCh38.bw,GERP_CONSERVATION_SCORE,bigwig \
--vcf \
--fork 4 \
--force_overwrite \
--pick \
--database
```

The only GERP I get is for 20:57563613 with a value of 2.96000003814697

I then repeat the same procedure lifting over the coordinates to hg19:
##fileformat=VCFv4.0
##liftOverProgram=CrossMap(https://sourceforge.net/projects/crossmap/)
##liftOverFile=/net/isilonP/public/ro/ensweb-data/latest/tools/www/e100/assembly_converter/homo_sapiens/GRCh38_to_GRCh37.chain.gz
##new_reference_genome=/net/isilonP/public/ro/ensweb-data/latest/tools/www/e100/assembly_converter/homo_sapiens/Homo_sapiens.GRCh37.dna.toplevel.fa
##liftOverTime=May30,2020
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
20	56138669	.	G	A	.	.	.
20	56140439	.	G	A	.	.	.

Then again I use VEP to get GERP values this time using this file from UCSC:
http://hgdownload.cse.ucsc.edu/gbdb/hg19/bbi/All_hg19_RS.bw

This is my VEP command to get the GERP values:

```
./vep \
--species human --assembly GRCh37 \
--show_ref_allele \
-i /opt/vep/src/ensembl-vep/jorge/gerp_condel.hg19.vcf \
-o /opt/vep/src/ensembl-vep/jorge/gerp_condel.hg19.vep.vcf \
--custom /opt/vep/src/ensembl-vep/All_hg19_RS.bw,GERP_CONSERVATION_SCORE,bigwig \
--vcf \
--fork 4 \
--force_overwrite \
--pick \
--database \
--port 3337
```

In this case I get GERP for the two variants with values 5.26999998092651 and 5.55000019073486 respectively.

Is there any reason you might think of that explains the differences between hg19 and hg38 based annotations?

### System
- VEP version: 98
- VEP Cache version: 98
- Perl version: v5.26.1
- OS: Ubuntu 18.04.3 LTS
- tabix installed: yes

### Full VEP command line
See above

### Full error message
There are no error messages

### Data files (if applicable)

Many thanks
Jorge

**Comment by ima23** [comment]
Hi Jorge,

The difference in GERP scores are most likely due to the different GERP analysis and alignments used for the two assemblies.
To find out how the GERP files are generated by Compara team you can send an email to helpdesk@ebi.ac.uk, where this will get picked up.
For the UCSC GERP files, UCSC might be able to give you more info on how the files were generated and why this position had the score it has.

Kind regards,
Irina

**Comment by jazberna1** [comment]
Hi,

Thanks for the information. 

Jorge
