### ISSUE TITLE
Plugin 'NearestGene' can not find internal name for species 'homo_sapiens'

### ISSUE THREAD

**Issue by petrsh** [Ensembl/ensembl-vep#776]
## Describe the issue
Hi, I can't figure out what's wrong here. The issue seems to be specific for this plugin as I tried to use NearestExonJB and it works properly.

## Additional information
I tried it for both "conda installation" and "classical installation" and got same error.

### System
- VEP version: 100
- VEP Cache version: 100
- Perl version: v5.26.2
- OS: Ubuntu
- tabix installed - yes

### Full VEP command line
```
vep --plugin NearestGene --offline --pick --assembly GRCh37 --symbol --nearest symbol --cell_type "B_(PB)" -i input.vcf -o output.vep --dir_cache ./ --fork 4
```

### Full error message
WARNING: Plugin 'NearestGene' went wrong:
-------------------- EXCEPTION --------------------
MSG: Can not find internal name for species 'homo_sapiens'
STACK Bio::EnsEMBL::Registry::get_adaptor /home/241914/miniconda3/share/ensembl-vep-100.1-0/Bio/EnsEMBL/Registry.pm:1111
STACK NearestGene::run /home/241914//.vep/Plugins/NearestGene.pm:104
STACK (eval) /home/241914/miniconda3/share/ensembl-vep-100.1-0/modules/Bio/EnsEMBL/VEP/OutputFactory.pm:2030
STACK Bio::EnsEMBL::VEP::OutputFactory::run_plugins /home/241914/miniconda3/share/ensembl-vep-100.1-0/modules/Bio/EnsEMBL/VEP/OutputFactory.pm:2029
STACK Bio::EnsEMBL::VEP::OutputFactory::get_all_VariationFeatureOverlapAllele_output_hashes /home/241914/miniconda3/share/ensembl-vep-100.1-0/modules/Bio/EnsEMBL/VEP/OutputFactory.pm:386
STACK Bio::EnsEMBL::VEP::OutputFactory::get_all_output_hashes_by_VariationFeature /home/241914/miniconda3/share/ensembl-vep-100.1-0/modules/Bio/EnsEMBL/VEP/OutputFactory.pm:336
STACK Bio::EnsEMBL::VEP::OutputFactory::get_all_output_hashes_by_InputBuffer /home/241914/miniconda3/share/ensembl-vep-100.1-0/modules/Bio/EnsEMBL/VEP/OutputFactory.pm:288
STACK Bio::EnsEMBL::VEP::OutputFactory::get_all_lines_by_InputBuffer /home/241914/miniconda3/share/ensembl-vep-100.1-0/modules/Bio/EnsEMBL/VEP/OutputFactory.pm:259
STACK Bio::EnsEMBL::VEP::Runner::_buffer_to_output /home/241914/miniconda3/share/ensembl-vep-100.1-0/modules/Bio/EnsEMBL/VEP/Runner.pm:416
STACK (eval) /home/241914/miniconda3/share/ensembl-vep-100.1-0/modules/Bio/EnsEMBL/VEP/Runner.pm:665
STACK Bio::EnsEMBL::VEP::Runner::_forked_process /home/241914/miniconda3/share/ensembl-vep-100.1-0/modules/Bio/EnsEMBL/VEP/Runner.pm:659
STACK Bio::EnsEMBL::VEP::Runner::_forked_buffer_to_output /home/241914/miniconda3/share/ensembl-vep-100.1-0/modules/Bio/EnsEMBL/VEP/Runner.pm:490
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /home/241914/miniconda3/share/ensembl-vep-100.1-0/modules/Bio/EnsEMBL/VEP/Runner.pm:361
STACK Bio::EnsEMBL::VEP::Runner::run /home/241914/miniconda3/share/ensembl-vep-100.1-0/modules/Bio/EnsEMBL/VEP/Runner.pm:202
STACK toplevel /home/241914/miniconda3/bin/vep:227
Date (localtime)    = Thu Jun  4 22:29:53 2020
Ensembl API version = 100

**Comment by helensch** [comment]
Hi

The NearestGene plugin does not work in --offline mode. 

I will update the documentation for the plugin for future releases.

Thank you for flagging this issue.

Helen

**Comment by petrsh** [comment]
Hi

Thank you, that was easy. 

I have two more questions:
1 - Is it possible to make the plugin return only the nearest protein-coding genes? And ideally as symbols?
2. How is the distance to the nearest gene calculated? Does it look for the nearest transcription start site or any part of the gene?

Petr

**Comment by helensch** [comment]
Hi

I will look into you questions regarding the plugin. 

The VEP --nearest option retrieves the transcript or gene with the nearest protein-coding transcription start site (TSS) to each input variant. Use "transcript" to retrieve the transcript stable ID, "gene" to retrieve the gene stable ID, or "symbol" to retrieve the gene symbol. 
 
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_nearest

Helen

**Comment by helensch** [comment]
Hi @petrsh 

Apologies for the delay in replying to you.

The NearestGene plugin searches for nearest gene that overlaps the variant. 
The plugin parameters that can be altered are described at
https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html#nearestgene

The NearestGene plugin uses a database connection.

The VEP --nearest option described at 
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_nearest
and provides the functionality in your queries.

We recommend using the --nearest option as it uses the cache (
https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache) 
and can be run offline. Using a cache is the fastest and most efficient way to run VEP.

Please let me know if you have any additional queries.

Regards
Helen
