### ISSUE TITLE
OutputFactory.pm throws multiple warnings

### ISSUE THREAD

**Issue by segoerge** [Ensembl/ensembl-vep#78]
Hi,

I'm running the VEP in Version 90, leading to a lot of these Perl warnings:

Use of uninitialized value in substitution (s///) at ....vep/modules/Bio/EnsEMBL/VEP/OutputFactory.pm line 1275, <__ANONIO__> line 5142.

The executed command was:

./vep -i input.vcf -o output.vcf --offline --vcf --merged --hgvs --fasta resources/vep/homo_sapiens/90_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz --force_overwrite --fork 1 --variant_class --vcf_info_field ANN --numbers --total_length --canonical --dir resources/vep

Maybe I'm wrong, but I took a look into the code and I think there is a bug not checking the undef or "-" case that can result from the line in front. 

Best regards,

Sebastian

**Comment by willmclaren** [comment]
Thanks, fixed by https://github.com/Ensembl/ensembl-vep/commit/b7b8ec4491746026aaa9792e226e9e1e15e1d12b on release/90.4
