### ISSUE TITLE
ERROR: Can't detect input format 

### ISSUE THREAD

**Issue by amizeranschi** [Ensembl/ensembl-vep#782]
Hi!

Could you please help me figure out why VEP won't parse the attached VCF file?

```
$ vep --fork 4 --vcf --input_file testingVC-struct-var.vcf --custom /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/genomes/Btaurus/bosTau6/rnaseq/ref-transcripts.gtf.gz,ref-transcripts,gtf,overlap,0 --fasta /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/genomes/Btaurus/bosTau6/seq/bosTau6.fa
Possible precedence issue with control flow operator at /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
ERROR: Can't detect input format
```

I can't find anything wrong with the VCF file that I'm using.

[testingVC-struct-var.zip](https://github.com/Ensembl/ensembl-vep/files/4775628/testingVC-struct-var.zip)

**Comment by amizeranschi** [comment]
The genome is Bos Taurus Ensembl v94, UMD3.1: 
ftp://ftp.ensembl.org/pub/release-94/fasta/bos_taurus/dna_index/Bos_taurus.UMD3.1.dna.toplevel.fa.gz

The GTF is: 
ftp://ftp.ensembl.org/pub/release-94/gtf/bos_taurus/Bos_taurus.UMD3.1.94.chr.gtf.gz

**Comment by aparton** [comment]
Hi @amizeranschi,

Unfortunately VEP currently does not support structural variants in breakend format. You can see the full list of SV types that VEP supports here: https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#sv

I'm sorry that I am unable to provide a more satisfactory conclusion to this issue. If you have any further questions, please don't hesitate to get in touch.

Kind Regards,
Andrew

**Comment by amizeranschi** [comment]
Thanks a lot for the reply. Removing variants with `SVTYPE=BND` got things working indeed. 

By any chance, is there a plan to include support for this type of variants as well?

**Comment by aparton** [comment]
Hi,

Yep, we are looking into ways of improving support for structural variations. We don't have a timescale for when we expect these improvements to be available, but it is something that we are looking at.

Kind Regards,
Andrew

**Comment by amizeranschi** [comment]
Alright, good luck with the updates and thanks for your assistance.

**Comment by FriederikeHanssen** [comment]
Hi! Has there been any progress on supporting `SVTYPE=BND` ? We are trying to annotate manta generated VCFs which keeps failing due to this

**Comment by amizeranschi** [comment]
@FriederikeHanssen I'm still in the same situation, see: https://github.com/Ensembl/ensembl-vep/issues/441#issuecomment-1120193686

In short: no, there's still no support for this, but they're considering it. In the mean time, if you simply remove the lines with `SVTYPE=BND` from Manta's VCF file, VEP should be able to parse it.

**Comment by stefandiederich** [comment]
Hi there, 
I know its a quite old post, but I also run into an "ERROR: Can't detect input format" error. I realised that there was a BND Type SV in the first line of my input VCF. If I copy that to the second line, VEP is working and annotating. 
Is this an intended behaviour or some kind of a bug?

Bests
Stefan

**Comment by nuno-agostinho** [comment]
Hey @stefandiederich,

As you mentioned, VEP fails when loading a VCF input file whose first line is BND-type SV. As VEP is not currently prepared to properly handle BND variants, it would be best to simply filter them out from your VCF file for now.

We are working on improving support for BND variants (hopefully to be released soon). Sorry for the inconvenience!

Thanks,
Nuno

**Comment by nuno-agostinho** [comment]
Hi @blex-max,

I hope you are having a nice day.

I opened PR #1399 to improve support for breakend variants in VEP, including a fix for the message `ERROR: Can't detect input format` associated with using a BND variant as the first line of a VCF input. As we want to make sure everything is working fine for breakend variants, these changes may only be available in release 111.

In the meantime, it would be best to filter out BND variants from your VCF file. Sorry for the inconvenience.

Please feel free to reply if you want to discuss this further.

Kind regards,
Nuno

**Comment by blex-max** [comment]
Thanks for the quick response! I see, I was hoping to use VEP on the output of GRIDSS/GRIPSS, I guess it won't be suitable until the future release then

**Comment by blex-max** [comment]
Hmm, perhaps we could use the [Ensembl:postreleasefix/110](https://github.com/Ensembl/ensembl-vep/tree/postreleasefix/110) branch once #1399 is merged, would you have any comments on that?

Have a good day & Thanks for your work!

**Comment by nuno-agostinho** [comment]
Hi @blex-max,

We do not recommend installing unreleased code from VEP because it may have issues that we may not notice at the time the PR is merged. We want to minimise misinterpretation of biological data related with technical bugs from our code, as that's why we ask to wait for the proper release.

That said, feel free to use the code in this repository in controlled settings for testing purposes. If you have any comments, please talk with me: all feedback is welcome and appreciated!

Cheers,
Nuno

**Comment by nuno-agostinho** [comment]
Hi @amizeranschi, @FriederikeHanssen, @stefandiederich and @blex-max,

We have updated the input format to detect more types of structural variants, including `<BND>`. This will be released in VEP 110 (coming soon).

Sorry for the inconvenience.

Kind regards,
Nuno

**Comment by FriederikeHanssen** [comment]
Amazing, thank you! 🙏

**Comment by blex-max** [comment]
Great news! Is it possible to estimate what "coming soon" might mean? Thank you.
