### ISSUE TITLE
probelm running VEP with gff caused by Bio::DB::HTS::Tabix

### ISSUE THREAD

**Issue by xbarvazx** [Ensembl/ensembl-vep#788]
Hi, 
I ran `perl -e "use Bio::DB::HTS::Tabix"` because I get an error `MSG: ERROR: Cannot use format gff without Bio::DB::HTS::Tabix module installed` when trying to run vep with gff annotation
and I get 
```
Bio::DB::HTS object version 3.01 does not match $Bio::DB::HTS::VERSION 2.11 at /usr/lib/x86_64-linux-gnu/perl/5.26/DynaLoader.pm line 204.
Compilation failed in require at /storage/raz/ensembl-vep-release-100/Bio/DB/HTS/Tabix.pm line 22.
BEGIN failed--compilation aborted at /storage/raz/ensembl-vep-release-100/Bio/DB/HTS/Tabix.pm line 22.
Compilation failed in require at -e line 1.
BEGIN failed--compilation aborted at -e line 1. 
```
Any help will be useful,
Thanks!

**Comment by aparton** [comment]
Hi @xbarvazx,

It looks as if you have multiple versions of Bio::DB::HTS on your machine. Updating your PERL5LIB to point to v2.11, the version installed by VEP, should hopefully resolve your issue.

Assuming that you don't have another version of Bio::DB::HTS included within your PERL5LIB, could you please run:

`export PERL5LIB=$PERL5LIB:/storage/raz/ensembl-vep-release-100/` 

If you're still having issues after running this, could you please send me the contents of your PERL5LIB, your perl version and your OS version?

Kind Regards,
Andrew

**Comment by xbarvazx** [comment]
Hi Andrew,

Nope this isn't working. This is the VEP installation output [vep_install_out.txt](https://github.com/Ensembl/ensembl-vep/files/4825512/vep_install_out.txt)
.
I use Ubuntu 18.04
perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi

I assume by PERL5LIB you mean '/storage/raz/ensembl-vep-release-100/'
the contents are:
```
Bio       convert_cache.pl  docker    Faidx.so    haplo   HTS.so      LICENSE  README.md  travisci   variant_effect_output.txt_warnings.txt  vep
biodbhts  cpanfile          examples  filter_vep  htslib  INSTALL.pl  modules  t          validator  variant_recoder
```

Best,
Raz

**Comment by aparton** [comment]
Hi @xbarvazx,

Thanks for sending on your installation output. Everything looks normal and successful there.

Apologies, buy your PERL5LIB I mean the environment variable. If you run:

`echo $PERL5LIB`

and send me the output then we should be able to see what's going on. 

Kind Regards,
Andrew

**Comment by xbarvazx** [comment]
Hi Andrew,

Here's the output of `echo $PERL5LIB`
`:/storage/raz/cpanm/lib/perl5:/storage/raz/ensembl-vep-release-100/`

Best,
Raz

**Comment by aparton** [comment]
Hi,

Multiple versions of Bio::DB::HTS on your machine seem to be giving VEP some issues. As far as I can tell, your options are:

1) Remove the `ensembl-vep/Bio/DB/HTS/` folder, leaving your currently installed version (3.01).
2) Remove your currently installed version (you should be able to find its location with `perldoc -l Bio::DB::HTS::Tabix`)

If you already have a full installation of Bio::DB::HTS on your machine, then I'd recommend option 1. Let me know how it goes.

Kind Regards,
Andrew

**Comment by xbarvazx** [comment]
Hi Andrew,

Actually did option 2 before you replayed and it works.
Thanks for all the help!

Raz

**Comment by aparton** [comment]
Hi,

Glad to hear that VEP is now working correctly. I'm going to close this issue now. If you have any further questions, please feel free to reopen this issue or create a new one.

Kind Regards,
Andrew

**Comment by Agridibuu** [comment]
-------------------- EXCEPTION --------------------

MSG: ERROR: Cannot use format gff without Bio::DB::HTS::Tabix module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /mnt/data/dayhoff/home/u7828736/.conda/envs/vep_env/share/ensembl-vep-91.3-0/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:162

STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /mnt/data/dayhoff/home/u7828736/.conda/envs/vep_env/share/ensembl-vep-91.3-0/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:228

STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /mnt/data/dayhoff/home/u7828736/.conda/envs/vep_env/share/ensembl-vep-91.3-0/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:93

STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /mnt/data/dayhoff/home/u7828736/.conda/envs/vep_env/share/ensembl-vep-91.3-0/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175

STACK Bio::EnsEMBL::VEP::Runner::init /mnt/data/dayhoff/home/u7828736/.conda/envs/vep_env/share/ensembl-vep-91.3-0/modules/Bio/EnsEMBL/VEP/Runner.pm:123

STACK Bio::EnsEMBL::VEP::Runner::run /mnt/data/dayhoff/home/u7828736/.conda/envs/vep_env/share/ensembl-vep-91.3-0/modules/Bio/EnsEMBL/VEP/Runner.pm:194

STACK toplevel /mnt/data/dayhoff/home/u7828736/.conda/envs/vep_env/bin/vep:222

Date (localtime)    = Wed Mar 26 13:19:34 2025

Ensembl API version = 91

--------------------------------------------------- 
 I got this error

**Comment by ainefairbrother** [comment]
Hi @Agridibuu, 

Thanks for your query. 

Have you tried any of the above solutions? Namely, ensuring that: 

- `Bio::DB::HTS::Tabix` is installed
- You don't have clashing installations
- Your environment variable `PERL5LIB` points to perl and VEP correctly

Once you have tried these things, let me know if you have any further issues. 

Best, 

@ainefairbrother

**Comment by Agridibuu** [comment]
Thank you for your reply.
I ran perl -e 'use Bio::DB::HTS::Tabix; print "Module loaded successfully!\n";'
it said loaded sucessfully_ but i got this error now "Unknown option: distance
ERROR: Failed to parse command-line flags"

**Comment by ainefairbrother** [comment]
Hi @Agridibuu, 

Could I see the full VEP command that you're running please?

Best, 

@ainefairbrother

**Comment by ainefairbrother** [comment]
Hi @Agridibuu, 

Please can you check that you've supplied data with a valid format to each flag as per the [VEP flag documentation](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#basic). For example, `--individual` expects actual sample names, not file names. 

It looks like you're trying to filter after running VEP, however, your original command looks like it outputs to STDOUT rather than to a file. Please specify an output file using `--output_file`. 

Please let me know if you continue to face issues. 

Regards, 

@ainefairbrother

**Comment by Agridibuu** [comment]
Hi thank you so much for your reply.
I changed it with this code 
# Use 'find' to get all sorted BAM files in the directory
BAM_FILES=($(find "$BAM_PATH" -type f -name "*.sorted.bam"))

# Join the BAM files into a single string (comma-separated)
BAM_FILES_STR=$(printf "%s," "${BAM_FILES[@]}")
BAM_FILES_STR=${BAM_FILES_STR%?}  # Remove the trailing comma

echo "Sorted BAM files: $BAM_FILES_STR"

# STEP 5: Run VEP with formatted genome and GFF file
vep -i allnumeric_no_leading_zeros.filtered.vcf \
    --gff data.gff.gz \
    --fasta genome_no_leading_zeros.fa.gz \
    --individual "$BAM_FILES_STR" \
    --force_overwrite \
    --output_file "variant_effect_output.txt" \
    --distance 500  # Keep the distance if your version supports it

# Check if VEP output exists before filtering
if [ -f "variant_effect_output.txt" ]; then
    filter_vep -i variant_effect_output.txt -o filtered_variant_effect.txt -filter "IMPACT is not MODIFIER" --force_overwrite
else
    echo "ERROR: VEP output file is empty or not found!"
    exit 1
fi. 
Still got the same error.
