### ISSUE TITLE
Vep dies when annotating variants in HLA-DRB1*01:01:01

### ISSUE THREAD

**Issue by jvolanen** [Ensembl/ensembl-vep#789]
Hi

We noticed that VEP cannot handle colons in chromosome names introduced in GRCh38. The problem reproduces when using both `--dont_skip` and `--custom` command line parameters as in the example below:

    $ cat /tmp/problem.vcf
    ##fileformat=VCFv4.2
    ##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structuralvariant">
    ##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">
    #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT
    HLA-DRB1*01:01:01       5902    .       AGT     A       .       PASS
    
    $ docker run --rm --log-driver=none -v /tmp:/tmp ensemblorg/ensembl-vep:release_100.2 vep \
    --input_file /tmp/problem.vcf \
    --assembly GRCh38 \
    --database \
    --format vcf \
    --pick \
    --tab \
    --output_file stdout \
    --no_stats \
    --dont_skip \
    --fork 2 \
    --custom http://storage.googleapis.com/gnomad-public/release/3.0/vcf/genomes/gnomad.genomes.r3.0.sites.vcf.bgz,gnomADv3,vcf,exact,,AF,AF_female,AF_male,AF_fin,nhomalt_female,nhomalt_male > /dev/null
    You must specify a region in the format chr, chr:start or chr:start-end at /usr/local/lib/x86_64-linux- gnu/perl/5.26.1/Bio/DB/HTS/Tabix.pm line 104, <__ANONIO__> line 5.
    Died in forked process 11

Apparently Tabix does not expect colons in chromosome names.

Best regards
Jussi

**Comment by aparton** [comment]
Hi Jussi,

Thanks for reporting this one to us, seems easy to reproduce. I'll have a chat with the team next week to see if there's any workaround we can put in place and get back to you.

Kind Regards,
Andrew

**Comment by chadisaad** [comment]
Hi, Any news for this ? I have the same issue

Best

**Comment by aparton** [comment]
Hi @chadisaad,

Unfortunately this is not an easy fix for us, VEP uses tabix to lookup overlapping variants, and tabix does not currently support chromosome names containing `:`.

We're currently investigating our options vis-a-vis a workaround. I'll let you know when we have a solution in place.

Kind Regards,
Andrew

**Comment by olaaustine** [comment]
Hi @chadisaad,
After careful consideration, this is not a feature we can support as the issue is based on Tabix parser which does not currently allow chromosome names containing` :`.
If anything changes in the future, we would update this. 
Meanwhile, we suggest that you change the VCF file to have Tabix supported chromosome names.
Please feel free to open another ticket if you have another question or issue.
Thank you,
Ola
