### ISSUE TITLE
Unable to run vep without hitting "Can't locate object method "new" via package" for GTF

### ISSUE THREAD

**Issue by Toseph** [Ensembl/ensembl-vep#793]
## Describe the issue
I have tried to install VEP using both "auto a" option and using specified directories on a machine I full access to. 
Each time the below test is run, the GTF annotation portion fails and cannot find "Bio::EnsEMBL::VEP::AnnotationSource::File::GTF". The file exists and the folder is in my PERL5LIB. 

/usr/local/software/ensembl-tools/ensembl-tools-100.2/Bio -> API Installed by INSTALL.pl 
/usr/local/software/ensembl-tools/ensembl-tools-100.2/cache -> Cache installed by INSTALL.pl for GRCh38 
/usr/local/software/ensembl-tools/ensembl-tools-100.2/modules/Bio/EnsEMBL -> From git clone 

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: [100.2] 
- VEP Cache version: [latest]
- Perl version: [e.g. 5.28.1]
- OS: [CentOS 7.7]
- tabix installed: Yes | /usr/local/software/ensembl-tools/ensembl-tools-100.2/htslib/tabix 

### Full VEP command line
```
vep --gtf all_no_SJ_promoters.isoforms.filter.gtf --format "vcf" --phased --vcf_info_field "ANN" --vcf --compress_output gzip --af --fasta /data/references/genome/Homo_sapiens_assembly38_noALT_noHLA_noDecoy.fasta --numbers --input_file GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased_biallelic.vcf.bgz
```

### Full error message
> Can't locate object method "new" via package "Bio::EnsEMBL::VEP::AnnotationSource::File::GTF" at /nfs/sw/ensembl-tools/ensembl-tools-100.2/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 167.

**Comment by ima23** [comment]
Hi @Toseph,

Just to double check, have all the tests part of the installation passed?
Could you please share a small snippet of your gtf that can reproduce the error?

Thanks,
Irina

**Comment by ima23** [comment]
Hi, I will close this issue but feel free to reopen it or create a new issue for any future problems.
