### ISSUE TITLE
Filtering with AND/OR

### ISSUE THREAD

**Issue by oalavijeh** [Ensembl/ensembl-vep#794]
## Describe the issue
When using filter_vep on an annotated vcf I would like to pull those annotations that are annotated to have a 'MAX_AF' <0.01 and an "IMPACT" that  is moderate or high. I am finding my syntax is not getting the correct result, I am getting Moderate only and high impact variants are being ignored. 

 filter_vep -i VCF - filter 'MAX_AF <0.01 or not MAX_AF' and 'IMPACT is MODERATE or IMPACT is HIGH' > output

Would it be better to pipe results:

 filter_vep -i VCF - filter 'MAX_AF <00.01 or not MAX_AF' |filter_vep  'IMPACT is MODERATE or IMPACT is HIGH' > output

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 98
- VEP Cache version: 98
- Perl version: [e.g. 5.26]
- OS: Ubunutu via HPC
- tabix installed yes 

### Full VEP command line
```
filter_vep -i VCF - filter 'MAX_AF <00.01 or not MAX_AF' and 'IMPACT is MODERATE or IMPACT is HIGH' > output

```

I'm afraid I work in an airlock HPC so cannot share scripts or outputs. 

Many thanks

**Comment by at7** [comment]
Hello,
adding parentheses around your filter constraints will allow the filter script to identify them and apply them in conjunction:
--filter "(MAX_AF < 0.01 or not MAX_AF) and (IMPACT is MODERATE or IMPACT is HIGH)"

You can also specify each filter separately:
--filter "MAX_AF < 0.01 or not MAX_AF" --filter "IMPACT is MODERATE or IMPACT is HIGH"

Please let me know if this is not giving you the expected results.

Best wishes,
Anja

**Comment by oalavijeh** [comment]
Brilliant thanks. I will run it and reopen if there is an issue. Many thanks
