### ISSUE TITLE
Can't locate Try/Tiny.pm in @INC

### ISSUE THREAD

**Issue by ayusyarif** [Ensembl/ensembl-vep#795]
## Describe the issue
I have run the API installation and all was good as this command said:

```
./ping_ensembl.pl
Installation is good. Connection to Ensembl works and you can query the human core database
```
also, I managed to install VEP and download the cache without getting any errors. 
However, when I tried to run vep with example provided, I got errors:

`./vep -i examples/homo_sapiens_GRCh38.vcf --cache`

it said:
```
Can't locate Try/Tiny.pm in @INC (@INC contains: /Users/ayuhutamisyarif/ensembl-vep/modules /Users/ayuhutamisyarif/ensembl-vep ##PATH_TO##/bioperl-1.6.924 /Users/ayuhutamisyarif/src/bioperl-1.6.924 /Users/ayuhutamisyarif/src/ensembl/modules /Users/ayuhutamisyarif/src/ensembl-compara/modules /Users/ayuhutamisyarif/src/ensembl-variation/modules /Users/ayuhutamisyarif/src/ensembl-funcgen/modules /Users/ayuhutamisyarif/src/bioperl-1.2.3 /Users/ayuhutamisyarif/src/ensembl-tools/modules /Users/ayuhutamisyarif/perl5/perlbrew/perls/5.14.4/lib/site_perl/5.14.4/darwin-thread-multi-2level /Users/ayuhutamisyarif/perl5/perlbrew/perls/5.14.4/lib/site_perl/5.14.4 /Users/ayuhutamisyarif/perl5/perlbrew/perls/5.14.4/lib/5.14.4/darwin-thread-multi-2level /Users/ayuhutamisyarif/perl5/perlbrew/perls/5.14.4/lib/5.14.4 .) at /Users/ayuhutamisyarif/ensembl-vep/Bio/EnsEMBL/IO/Parser.pm line 44.
BEGIN failed--compilation aborted at /Users/ayuhutamisyarif/ensembl-vep/Bio/EnsEMBL/IO/Parser.pm line 44.
Compilation failed in require at /Users/ayuhutamisyarif/perl5/perlbrew/perls/5.14.4/lib/5.14.4/parent.pm line 20.
BEGIN failed--compilation aborted at /Users/ayuhutamisyarif/ensembl-vep/Bio/EnsEMBL/IO/TextParser.pm line 45.
Compilation failed in require at /Users/ayuhutamisyarif/perl5/perlbrew/perls/5.14.4/lib/5.14.4/parent.pm line 20.
BEGIN failed--compilation aborted at /Users/ayuhutamisyarif/ensembl-vep/Bio/EnsEMBL/IO/ColumnBasedParser.pm line 36.
Compilation failed in require at /Users/ayuhutamisyarif/perl5/perlbrew/perls/5.14.4/lib/5.14.4/parent.pm line 20.
BEGIN failed--compilation aborted at /Users/ayuhutamisyarif/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 45.
Compilation failed in require at /Users/ayuhutamisyarif/perl5/perlbrew/perls/5.14.4/lib/5.14.4/parent.pm line 20.
BEGIN failed--compilation aborted at /Users/ayuhutamisyarif/ensembl-vep/Bio/EnsEMBL/IO/Parser/VCF4.pm line 41.
Compilation failed in require at /Users/ayuhutamisyarif/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 79.
BEGIN failed--compilation aborted at /Users/ayuhutamisyarif/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 79.
Compilation failed in require at /Users/ayuhutamisyarif/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 71.
BEGIN failed--compilation aborted at /Users/ayuhutamisyarif/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 71.
Compilation failed in require at /Users/ayuhutamisyarif/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 83.
BEGIN failed--compilation aborted at /Users/ayuhutamisyarif/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 83.
Compilation failed in require at ./vep line 20.
BEGIN failed--compilation aborted at ./vep line 20.
```

Could someone help me to explain these errors? 

### System
- VEP version: 100
- VEP Cache version: homo_sapiens_100_GrCh38
- Perl version: bioperl-1.2.3
- OS:MacOS mojave
- tabix installed ? = not sure. How do I check that?

**Comment by ertanyilmaz38** [comment]
check please https://metacpan.org/pod/Module::Build::Tiny

**Comment by at7** [comment]
Hi @ayusyarif,

you need to install Try::Tiny manually using `cpanm Try::Tiny`. We have documentation on how to run [VEP on Mac OS](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#macos) and will add the Try::Tiny dependency to it. Please let me know if installing the module is not fixing the issue.

Best regards,
Anja

**Comment by ertanyilmaz38** [comment]
@at7 Will my answer solve the problem?

**Comment by at7** [comment]
Dear Ertan,

I don't think that Try::Tiny is installed as part of the Module::Build::Tiny installation. But please correct me if that is not the case.

Best regards,
Anja

**Comment by ayusyarif** [comment]
Hi Anja, 

many thanks for the suggestion. I installed the Try::Tiny as you suggested. But, then I was wondering whether that fixed the issue or not. do you have any thoughts on how to check if it's working or not?

I run the command again:
`./vep -i examples/homo_sapiens_GRCh38.vcf --cache --force_overwrite`

this time, it didn't generate any statement. I checked the directory in which I run the command. 
```
(base) Ayus-Air:ensembl-vep ayuhutamisyarif$ ls
Bio					haplo
Faidx.bundle				homo_sapiens
HTS.bundle				htslib
INSTALL.pl				modules
LICENSE					t
README.md				travisci
biodbhts				validator
convert_cache.pl			variant_effect_output.txt
cpanfile				variant_effect_output.txt_summary.html
docker					variant_recoder
examples				vep
filter_vep
```

**Comment by at7** [comment]
It looks to me that you have solved the problem. The message "Can't locate Try/Tiny.pm in @INC..." which you have seen before is not returned anymore. You can now use VEP for your work. But please let me know if you get any error messages again.

**Comment by ayusyarif** [comment]
Hi anja,

yes, it worked! but, there's something that bothered me. I run VEP with 79444 snvs, but the result only generated 76111 snvs. I wonder what happen with the remaining snvs. I received a warning message, prior to the deep recursion:

```
WARNING: Chromosome NA not found in annotation sources or synonyms on line 5557
Deep recursion on subroutine "Bio::EnsEMBL::VEP::Parser::next" at /Users/ayuhutamisyarif/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 182, <$__ANONIO__> line 5656.
```
do you think this may cause a reduction in the results?

best,
 
ayu

**Comment by at7** [comment]
Hi Ayu,

is NA a valid chromosome? VEP uses the chromosome name or a chromosome synonym to look up transcripts in the cache file directory. However not providing a valid chromosome shouldn't cause the 'Deep recursion on subroutine' message you are also getting. I would be happy  to run your input file and try to see for myself where the problem lies if you can share your input and input command.

Thank you,
Anja

**Comment by ayusyarif** [comment]
Hi Anja,

Many thanks for your help.

Here's the input (as attached) and the command that I used yesterday.

[snvs.vep.input.txt](https://github.com/Ensembl/ensembl-vep/files/4891741/snvs.vep.input.txt)
`./vep -i WGS_smoking/snvs.vep.input.txt -o WGS/Smoking/snvs.vep.output.txt --cache --offline`

**Comment by at7** [comment]
Thank you for the input file. I can confirm that the problem is that NA is not a valid chromosome. You can add --dont_skip to your VEP command line which means that VEP doesn't skip input variants that fail validation and will in your case add variants with the NA chromosome to your output file. I also noticed that your file is not sorted which slows down the runtime a lot. I just sorted the file with `sort -k1,1 -k2,2n -k3,3n snvs.vep.input.txt > snvs.vep.input.sorted.txt` and then used snvs.vep.input.sorted.txt as the input file.

**Comment by ayusyarif** [comment]
Hi Anja,

Many thanks for your help.
It does the magic part of this task! 
is there any negative consequences of putting the --dont_skip into my future commands?

Best, 

Ayu

**Comment by at7** [comment]
Hi Ayu,

VEP has a validation step where it checks that:
-- start and end look like numbers
-- start/end are valid (start <= end + 1) and corresponds to ref allele
-- chr is in valid list

If one of those checks fail, like for your example where NA is not a valid chromosome, and --dont_skip is used VEP will attempt to calculate the variant consequence and write the result to the output. This might fail depending on how much any of the above cases affect the consequence calculation. The worst case is that you get wrong annotations. But you will always get a warning message about any of the above failures. If you use --dont_skip make sure you carefully read any warning messages.

Best wishes,
Anja

**Comment by ayusyarif** [comment]
Hi Anja,

Many thanks for the explanation. 

Best, 

Ayu
