### ISSUE TITLE
Connection to ENSEMBL MySQL Server Failing

### ISSUE THREAD

**Issue by DarioS** [Ensembl/ensembl-vep#797]
I am getting an error from Variant Effect Predictor

```
-------------------- EXCEPTION --------------------
MSG: Cannot connect to the Ensembl MySQL server at ensembldb.ensembl.org:3306; check your settings & DBI error message: Lost connection to MySQL server at 'handshake: reading inital communication packet', system error: 11
STACK Bio::EnsEMBL::Registry::load_registry_from_db /dskh/nobackup/biostat/software/ensembl-vep/Bio/EnsEMBL/Registry.pm:1770
STACK Bio::EnsEMBL::VEP::BaseVEP::registry /dskh/nobackup/biostat/software/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:252
STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /dskh/nobackup/biostat/software/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:120
STACK Bio::EnsEMBL::VEP::Runner::init /dskh/nobackup/biostat/software/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:118
STACK Bio::EnsEMBL::VEP::Runner::run /dskh/nobackup/biostat/software/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /verona/nobackup/biostat/software/ensembl-vep/vep:224
Date (localtime)    = Tue Jul  7 22:18:57 2020
Ensembl API version = 99
---------------------------------------------------
```

I tried a couple of the debugging suggestions on the website. `mysql --host=ensembldb.ensembl.org --port=3306 --user=anonymous` works and I get to the mySQL command prompt. However, the ping suggestion `ping -c 5 ensembldb.ensembl.org` fails.

```
PING ensembl-databases.ebi.ac.uk (193.62.194.233) 56(84) bytes of data.

--- ensembl-databases.ebi.ac.uk ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 183ms
```

Why do I need an internet connection in the first place? I specified `--cache --dir_cache /verona/nobackup/biostat/software/ensembl-vep/cache/`. I read that the cache does not store HGVS notations and structural variants, but I did not use `--format hgvs`, `--format id` or `--check_sv`, so I don't think a network connection would be needed at all. My analysis worked when I executed my script a few weeks ago, I'm just trying to run the same code on more patient samples. Interestingly, it works again if I specify `--offline`. The website says to check the ENSMBL blog for server status, but there's no recent blog about the server being down.

**Comment by at7** [comment]
Hello,
you need to specify --offline if you want to run without connecting to the ensembl database. Even if you specify using cache files VEP will still set up some database connections which can be used during the annotation step if offline is not set. I don't have any problems connecting to the ensembl database. Could you please share your full VEP command line? I will try and replicate the problem.

Thank you,
Anja

**Comment by DarioS** [comment]
The complete command is

```
vep --pick --vcf --symbol --cache --dir_cache /verona/biostat/software/ensembl-vep/cache/ -i cancer.vcf -o effects.vcf --sift b --polyphen b --plugin CADD,/verona/biostat/databases/CADD/hg38/whole_genome_SNVs.tsv.gz,/verona/biostat/databases/CADD/hg38/InDels.tsv.gz
```

**Comment by at7** [comment]
I just tested the database connection again and it seems to be working fine. We have an [FAQ](http://www.ensembl.org/Help/Faq?id=567) on database connection errors. Scroll to the bottom of the page for the error message you get. It could indicate that your local network prohibits the database connection. Could this be the case?
However, for your use case I would recommend that you just add the --offline flag.

**Comment by DarioS** [comment]
I got the server administrator to test it. Firstly, I can't use `ping` because he has set up a transparent proxy which doesn't work with ICMP, and only allows TCP and UDP. He explained that he tried the command `telnet ensembldb.ensembl.org 3306` and that showed him the server is actually unreachable.

```
  Error opening ensembl-databases.ebi.ac.uk:3306 :
    failed to open 193.62.194.233:3306 (connection timed out)
```

I have finished my analysis using `--offline`, but it would be good to sort this out for other people trying in future.

**Comment by at7** [comment]
Thank you for providing more details. I'm checking just now and there are no database connection problems for ensembldb.ensembl.org. I can connect with `mysql -h ensembldb.ensembl.org -uanonymous`. Are you still having connection problems today?

**Comment by DarioS** [comment]
The department's server doesn't have mySQL, so I tried the university's HPC and your command worked there. Also, the `telnet` command works. It must be something about the proxy or port settings on our department's server.
