### ISSUE TITLE
Duplicated variants in VCF output when run with --minimal flag

### ISSUE THREAD

**Issue by david-a-parry** [Ensembl/ensembl-vep#798]
## Describe the issue
The --minimal flag causes variants to be duplicated in VCF output for multiallelic sites with at least one insertion/deletion allele and an '*' allele.

In these cases, it appears that the variant line is written once for each ALT allele, with each VCF output line having CSQ annotations for one allele only, or in the case of '*' alleles, no CSQ field at all (error in rejoin_variants sub?). This breaks the VCF output for use in downstream applications.

### System
- VEP version: 100.2 
- VEP Cache version: 100
- Perl version: 5.30
- OS: Ubuntu 20.04
- tabix installed: yes

Issue also occurs when tested on VEP 99.2, Perl v5.26.1, Scientific Linux 7.5.

### Full VEP command line
```
./vep --offline -i problem_variants.vcf.gz  --vcf -o output.vep_min.vcf  --minimal

```

### Full error message
N/A

### Data files (if applicable)
- The input file
[problem_variants.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/4885853/problem_variants.vcf.gz)

- The output file
[output.vep_min.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/4885856/output.vep_min.vcf.gz)

**Comment by at7** [comment]
Dear David,
thank you for the report. You have uncovered a bug here. The variants should be joined together where possible. I haven't fully investigated how much work is involved in fixing the bug. But I will get back to you by next week and let you know by when we can provide the fix.

Thank you,
Anja

**Comment by at7** [comment]
I should mention that allele matching for assigning e.g. allele frequencies occurs independently of any allele transformations carried out by --minimal.

**Comment by david-a-parry** [comment]
Thanks Anja. My main motivation for using the --minimal flag was that the documentation for the [UTRannotator plugin](https://github.com/ImperialCardioGenetics/UTRannotator) claims it is necessary for it to function properly, otherwise I have always run VEP happily without this flag.

**Comment by at7** [comment]
Hi David,
this has been fixed for release/100. Could you please pull the latest changes from the release/100 branch?

Best wishes,
Anja

**Comment by david-a-parry** [comment]
Great, that seems to be working fine now. Thank you for the quick fix!
