### ISSUE TITLE
VEP error with large chromosome

### ISSUE THREAD

**Issue by eyeamnice** [Ensembl/ensembl-vep#800]
## Issue
I am running VEP version 100 in local mode and ran into an issue of Deep recursion on subroutine "Bio::EnsEMBL::VEP::Runner::_buffer_to_output" at ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 419, <$fh> line 495334. My chromosomes are large so I could only tabix index my files via csi rather than tbi. I am not sure if that counts. I also modified chromosome names according to https://github.com/Ensembl/ensembl-vep/issues/117, but that did not help as same error persisted. I let it run to the end but the output contained only comment and header lines.

### Full VEP command line
```
./vep -i S_data.vcf.gz --fasta S_ref.fasta --gff S_gene.gtf.gz --variant_class --coding_only 
--tab  --fork 8 --show_ref_allele --no_check_alleles --force_overwrite --total_length 
--flag_pick_allele_gene --pick_order canonical,rank,tsl,appris,ccds --domains --protein 
--output_file vep_result.txt
```

**Comment by helensch** [comment]
Hi

The vep command used has the option `-gff S_gene.gtf.gz`

The **-gff** option is used and the filename has **gtf** in name. If the file being used is a gtf file, can you try using the `-gtf` option.

Information on the VEP gtf and gff options is available at:
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#other

Information on the gtf and gff data formats is available at:
https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff

Helen

**Comment by helensch** [comment]
Hi 

I'm going to close this issue now. 

If you have any further questions, please feel free to reopen it or create a new issue.

Regards
Helen
