### ISSUE TITLE
How to see Read Depth(DP) and Allelic depths(AD) at output?

### ISSUE THREAD

**Issue by ngslabex** [Ensembl/ensembl-vep#801]
Is it possible to see Read Depth(DP) and Allelic depths(AD) at output as tabs?

**Comment by helensch** [comment]
Hi

When using VEP, if the input file is VCF and the output format is VCF (--vcf)  the file will remain unchanged save for the addition of the CSQ field (unless using any filtering). If Read Depth(DP) and Allelic Depth(AD) are in the input VCF, they will be in the output VCF.

If the output format is tab-delimited (--tab) the fields output are described at:
https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#tab and 
https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#defaultout

If the input VCF has, Read Depth(DP) and Allelic depth(AD) and the output is tab, the DP and AD fields are not output. We would recommend using --vcf for output to have the info in the output. 

VEP can integrate custom annotation from standard format files into your results (https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html).  However from above, I would recommend using VCF for input and output.

Helen
