### ISSUE TITLE
help to interpret the Allele Frequency reported by VEP

### ISSUE THREAD

**Issue by jazberna1** [Ensembl/ensembl-vep#805]
Hello,

## Describe the issue
This is not an issue. I am rather asking for help to interpret the --af (allele frequency) option in VEP.
The documentation says:
_For this and all --af\_* flags, the frequency reported is for the **input allele** only, not necessarily the non-reference or derived allele._

My understanding is that the allele frequency reported is for the ALT allele in the input VCF file. Am I right?

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 98
- VEP Cache version: 98
- Perl version: v5.26.1
- OS: Ubuntu 18.04.3 LTS
- tabix installed: yes

### Full VEP command line
The comand line I use to run VEP from the container is:
```
   vep ./vep --show_ref_allele \
    -i /opt/vep/src/ensembl-vep/panels/input.vcf \
    -o /opt/vep/src/ensembl-vep/panels/output.vcf  \
    --plugin CADD,/opt/vep/src/ANNOTATIONS/whole_genome_SNVs.tsv.gz,/opt/vep/src/ANNOTATIONS/InDels.tsv.gz \
    --custom /opt/vep/src/ANNOTATIONS/gerp_conservation_scores.homo_sapiens.bw,GERP,bigwig \
    --plugin Condel,/opt/vep/src/ensembl-vep/Condel,b,1 \
    --custom /opt/vep/src/ANNOTATIONS/gscores.sorted.bed.gz,GSCORE,bed,overlap \
    --custom /opt/vep/src/ANNOTATIONS/clinvar.vcf.gz,ClinVar,vcf,exact,0,CLNSIG \
    --plugin ExAC,/opt/vep/src/ensembl-vep/ExAC.r1.sites.vep.vcf.gz,ExAC_AF,ExAC_AF_NFE \
    --plugin Phenotypes,file=/opt/vep/src/ANNOTATIONS/phenotypes.gff.gz,include_types=Gene,exclude_sources='AMDGC&COSMIC&Cancer_Gene_Census&ClinVar&DDG2P&DGVa&GEFOS&GIANT&HGMD-PUBLIC&MAGIC&NHGRI-EBI_GWAS_catalog&Orphanet&Teslovich&dbGaP&dbVar' \
    --vcf --fork 4 --force_overwrite --merged --cache --use_given_ref --distance 0 --symbol --pick --assembly $ASSEMBLY --offline --show_ref_allele --af_gnomad --af --af_1kg"

```

### Full error message
not apply

### Data files (if applicable)
not apply

Many thanks
Jorge

**Comment by dglemos** [comment]
Hello Jorge, 
It's correct, the allele frequency reported is for the input allele which means it's the alternative allele from the input file. 
Best wishes, 
Diana

**Comment by jazberna1** [comment]
Hi Diana,
Thanks a lot!
Jorge
