### ISSUE TITLE
SIFT not available

### ISSUE THREAD

**Issue by mkinnaman** [Ensembl/ensembl-vep#808]
## Describe the issue
I am aware this issues has been reported in the past but I downloaded the following for my vep cache:
ftp://ftp.ensembl.org/pub/release-100/variation/indexed_vep_cache/homo_sapiens_merged_vep_100_GRCh37.tar.gz

and after extraction there was no info.txt in the folder to provide the SIFT

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: [e.g. 98 or 98.1] 
- VEP Cache version: [100.3]
- Perl version: [e.g. 5.26.2]
- OS: [MacOs]
- tabix installed yes?

### Full VEP command line
```
`./vep --species homo_sapiens --dir /Users/kinnamam/.vep --assembly GRCh37 --cache_version 100 --no_progress --offline --no_stats --sift b --symbol --numbers --domains --gene_phenotype --pubmed --protein --variant_class --shift_hgvs 1 --check_existing --no_escape --failed 1 --minimal --allele_number --pick_order canonical,tsl,biotype,rank,ccds,length --input_file /Users/kinnamam/Computational/LiFD/LiFD_TMP/GENERAL_vep_input.tsv --output_file /Users/kinnamam/Computational/LiFD/LiFD_TMP/GENERAL_vep_output.tsv --polyphen b --buffer_size 50 --force_overwrite --pick`
```

### Full error message
`MSG: ERROR: SIFT not available

STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::check_sift_polyphen /Users/kinnamam/Computational/LiFD/software/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:168
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::new /Users/kinnamam/Computational/LiFD/software/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:121
STACK Bio::EnsEMBL::VEP::CacheDir::get_all_AnnotationSources /Users/kinnamam/Computational/LiFD/software/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:150
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /Users/kinnamam/Computational/LiFD/software/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:121
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /Users/kinnamam/Computational/LiFD/software/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /Users/kinnamam/Computational/LiFD/software/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /Users/kinnamam/Computational/LiFD/software/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /Users/kinnamam/Computational/LiFD/software/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel ./vep:227
Date (localtime)    = Tue Jul 21 15:46:46 2020
Ensembl API version = 100`

THanks!

**Comment by dglemos** [comment]
Hello @mkinnaman,
I checked and the VEP cache that you downloaded contains `info.txt` with SIFT inside. Which command did you use to extract the cache?
I noticed that the cache you downloaded is the merged version but in your VEP command you don't use the option `--merged`, you need this option to use it.

**Comment by dglemos** [comment]
I'm going to close this ticket. If this issue is not fixed please feel free to reopen it. 
Best wishes,
Diana
