### ISSUE TITLE
Problems annotating chrM

### ISSUE THREAD

**Issue by stefandiederich** [Ensembl/ensembl-vep#81]
Hi, 
I have problems with the annotation on the mitochondrial chromosome. 
In my data I have variants:
chrM:16093T>C which is annotated with the gene MT-ND6
chrM:408T>A which is annotated with the gene MT-ND2

But the gene MT-ND6 is located at Chromosome MT: 14,149-14,673 reverse strand and the gene MT-ND2 is located at Chromosome MT: 4,470-5,511 forward strand. 
So the annotations above are wrong. 
Have you seen something like this before? 

Thanks in advance 
Stefan

**Comment by willmclaren** [comment]
The consequence type for both of these results is `upstream_gene_variant`, and the `DISTANCE` field in the output shows you how far upstream the variant is from the transcription start site (TSS):

```
./vep -id "chrM:g.408T>A" -database -symbol -pick -o stdout -no_header
chrM:g.408T>A   MT:408  A       ENSG00000198763 ENST00000361453 Transcript      upstream_gene_variant   -       -       -       -       -       -       IMPACT=MODIFIER;DISTANCE=4062;STRAND=1;SYMBOL=MT-ND2;SYMBOL_SOURCE=HGNC;HGNC_ID=HGNC:7456
```

If you do not wish to include up/downstream annotations, you may modify the distance used with `--distance`; the default is 5000 (bp).

**Comment by stefandiederich** [comment]
Okay I was not aware of that.
Thanks for pointing out.

Stefan

________________________________________
Stefan Diederich
M. Sc. Bioinformatik

Universitätsmedizin
der Johannes Gutenberg-Universität Mainz
Langenbeckstraße 1, 55131 Mainz
Tel.: 06131 17-5797

Von: William McLaren [mailto:notifications@github.com]
Gesendet: Dienstag, 26. September 2017 15:46
An: Ensembl/ensembl-vep
Cc: Diederich, Stefan; Author
Betreff: Re: [Ensembl/ensembl-vep] Problems annotating chrM (#81)


The consequence type for both of these results is upstream_gene_variant, and the DISTANCE field in the output shows you how far upstream the variant is from the transcription start site (TSS):

./vep -id "chrM:g.408T>A" -database -symbol -pick -o stdout -no_header

chrM:g.408T>A   MT:408  A       ENSG00000198763 ENST00000361453 Transcript      upstream_gene_variant   -       -       -       -       -       -       IMPACT=MODIFIER;DISTANCE=4062;STRAND=1;SYMBOL=MT-ND2;SYMBOL_SOURCE=HGNC;HGNC_ID=HGNC:7456

If you do not wish to include up/downstream annotations, you may modify the distance used with --distance; the default is 5000 (bp).
