### ISSUE TITLE
No CADD score if --hgvs is provided

### ISSUE THREAD

**Issue by leonschuetz** [Ensembl/ensembl-vep#812]
## Describe the issue
If the --hgvs parameter is provided, the CADD phred score is missing for some Indels.

## Additional information
It seems to be the case only for Indels which are inframe_insertions. On version 96 all Indels are annotated with a CADD score.

### System
- VEP version: 100.3
- VEP Cache version: 100
- Perl version: v5.26.1
- OS: Ubuntu 18.04.4 LTS
- tabix installed: yes

### Full VEP command line
```
./vep -i test.vcf --format vcf -o test_vep100_hgvs.vcf --vcf --no_stats --force_overwrite --species homo_sapiens --assembly GRCh37 --offline --cache --dir_cache cache/ --fasta GRCh37.fa --plugin CADD,CADD_SNVs_1.6.tsv.gz,CADD_InDels_1.6.tsv.gz --hgvs --fields Consequence,CADD_PHRED

./vep -i test.vcf --format vcf -o test_vep100_nohgvs.vcf --vcf --no_stats --force_overwrite --species homo_sapiens --assembly GRCh37 --offline --cache --dir_cache cache/ --fasta GRCh37.fa --plugin CADD,CADD_SNVs_1.6.tsv.gz,CADD_InDels_1.6.tsv.gz --fields Consequence,CADD_PHRED

```

### Data files (if applicable)
see test.vcf:
[test.zip](https://github.com/Ensembl/ensembl-vep/files/4988033/test.zip)

**Comment by aparton** [comment]
Hi @leonschuetz,

Thanks for reporting this one to us. I've been able to reproduce the issue, and we're in the process of putting a fix in place. 

I'll let you know when the fix is live.

Kind Regards,
Andrew

**Comment by leonschuetz** [comment]
Hi @aparton,

Thanks for the answer. I found another variant where the ``--hgvs`` parameter leads to different CADD scores: 

``chr13	32972743	.	G	GTGAATTATA``

Here the ``infame_insertion`` reports a CADD score of 24.4 instead of 8.612 which the other transcripts report.

If you take a look in the CADD file it reports for this position 3 variants/indels:

``13      32972743        G       GGAATTATAT      3.325613        24.4``
``13      32972743        G       GGAATTATATC     3.321598        24.4``
``13      32972743        G       GTGAATTATA      0.420173        8.612``

So it seems that for the inframe insertions the wrong variant score is used.

Kind Regards,
Leon

[test.zip](https://github.com/Ensembl/ensembl-vep/files/5072942/test.zip)

**Comment by diegomscoelho** [comment]
Hi @leonschuetz,

This bug was fixed in our last PR - https://github.com/Ensembl/ensembl-variation/pull/814. This will be released in release/108. Closing this issue, any other question about this feel free to reopen/comment this issue or open a new one.

Regards, @diegomscoelho
