### ISSUE TITLE
retrieve  NCBI NM_ accession numbers with VEP

### ISSUE THREAD

**Issue by jazberna1** [Ensembl/ensembl-vep#815]
Hello,

## Describe the issue
This is not an issue. I would like to know if there is an option in VEP to retrieve NCBI NM_ accession numbers (i.e. NM_001173454)

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 98
- VEP Cache version: 98
- Perl version: v5.26.1
- OS: Ubuntu 18.04.3 LTS
- tabix installed: yes

### Full VEP command line
not apply

### Full error message
not apply

### Data files (if applicable)
not apply

Many thanks
Jorge

**Comment by dglemos** [comment]
Hi Jorge,
It's possible to get NM_ accession numbers running VEP with a  cache file (--cache). 
You have to download the RefSeq cache file (e.g. homo_sapiens_refseq), or a merged file of RefSeq and Ensembl transcripts (e.g. homo_sapiens_merged). After you have the correct cache file, run VEP with --refseq (RefSeq cache) or --merged (merged cache).

**Comment by jazberna1** [comment]
Hello Diana,

I have installed the merged cache and enabled the --merged option (as shown on the Full VEP command line section below). I haved observed that some variants get annotated with NM_ accession numbers while others have ENST identifiers. I have attached a vcf file (with txt extention) that contains two variants, one showing NM_ and the other ENST ids.

I checked in biomart that the NM_ corresponding to the ENST id exists.
ENST00000439458.1	NM_032504

Is there a way to force VEP to report  NM_ instead of ENST ids ? 
   
## Describe the issue
see above

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 98
- VEP Cache version: 98
- Perl version: v5.26.1
- OS: Ubuntu 18.04.3 LTS
- tabix installed: yes

### Full VEP command line
vep ./vep \
-i /opt/vep/src/ensembl-vep/panels/input.vcf \
-o /opt/vep/src/ensembl-vep/panels/output.vcf \
--plugin CADD,/opt/vep/src/ANNOTATIONS/whole_genome_SNVs.tsv.gz,/opt/vep/src/ANNOTATIONS/InDels.tsv.gz \
--custom /opt/vep/src/ANNOTATIONS/gerp_conservation_scores.homo_sapiens.bw,GERP,bigwig \
--plugin Condel,/opt/vep/src/ensembl-vep/Condel,b,1 \
--custom /opt/vep/src/ANNOTATIONS/gscores.sorted.bed.gz,GSCORE,bed,overlap \
--custom /opt/vep/src/ANNOTATIONS/clinvar.vcf.gz,ClinVar,vcf,exact,0,CLNSIG \
--plugin ExAC,/opt/vep/src/ensembl-vep/ExAC.r1.sites.vep.vcf.gz,ExAC_AF,ExAC_AF_NFE \
--plugin Phenotypes,file=/opt/vep/src/ANNOTATIONS/phenotypes.gff.gz,include_types=Gene,exclude_sources='AMDGC&COSMIC&Cancer_Gene_Census&ClinVar&DDG2P&DGVa&GEFOS&GIANT&HGMD-PUBLIC&MAGIC&NHGRI-EBI_GWAS_catalog&Orphanet&Teslovich&dbGaP&dbVar' \
--vcf --fork 4 --force_overwrite --merged --cache --use_given_ref --distance 0 --symbol --check_existing --pick --assembly GRCh37 --offline --show_ref_allele --af_gnomad --af --af_1kg \
--hgvs --hgvsg \
--fasta /opt/vep/src/REFERENCE/reference.fa

### Full error message
not apply

### Data files (if applicable)
I have attached a vcf file (with txt extention) that contains two variants, one showing NM_ and the other ENST ids.
[example.txt](https://github.com/Ensembl/ensembl-vep/files/5005989/example.txt)


Many thanks
Jorge

**Comment by dglemos** [comment]
You're using the option --pick which picks once line of consequence data per variant according to the criteria described here: https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick 
In your example, for the variant `chrX 19373555 C/A ` the consequence picked is for transcript ENST00000379806. If you want to keep using `--pick` then you should run VEP with `--refseq` cache (only RefSeq IDs) instead of `--merged`.

**Comment by jazberna1** [comment]
Hello Diana,

I understand that --pick returns one transcript only. I was asking if there is the option to for instance have the NM_ accession number alongside with the ENST, in the same way that both ENSG and HGNG are annotated for the  same variant. In this case NM_032504 is the NCBI equivalent to EBI ENST00000439458.

https://www.ncbi.nlm.nih.gov/CCDS/CcdsBrowse.cgi?REQUEST=CCDS&DATA=CCDS46504

Thanks
Jorge

**Comment by dglemos** [comment]
Hello Jorge,
There's no option to return both Ensembl and RefSeq transcript IDs in the same annotation because not all RefSeq completely match Ensembl transcripts. 
If you want to know which transcripts have a complete match with RefSeq you can use the option --mane which will indicate if the transcript is the [MANE](https://www.ensembl.org/info/genome/genebuild/mane.html) Select transcript for the gene.

**Comment by jazberna1** [comment]
Hello Diana,

ok, that is clarifying .

Thanks so much
Jorge
