### ISSUE TITLE
Error while installing VEP on Windows

### ISSUE THREAD

**Issue by peranti** [Ensembl/ensembl-vep#816]
## Describe the issue
Installation error 

## Additional information
I have followed the instructions as mentioned on the below webpage: 
https://grch37.ensembl.org/info/docs/tools/vep/script/vep_download.html#windows

DWIM Perl link is not working and so I have installed another Perl distribution: http://strawberryperl.com/ Hope it is okay.

Then I downloaded and unpacked the zip of the **ensembl-vep package**, as suggested on the webpage.

Then, I ran the command "`perl INSTALL.pl --NO_HTSLIB --NO_TEST`" which resulted in the below error.

### Full error message

```
Downloading required Ensembl API files
 - fetching ensembl
 - unpacking ./Bio/tmp/ensembl.zip
 - moving files
 - getting version information
 - fetching ensembl-variation
 - unpacking ./Bio/tmp/ensembl-variation.zip
 - moving files
 - getting version information
 - fetching ensembl-funcgen
 - unpacking ./Bio/tmp/ensembl-funcgen.zip
 - moving files
 - getting version information
 - fetching ensembl-io
 - unpacking ./Bio/tmp/ensembl-io.zip
 - moving files
ERROR: Could not move the directory './Bio/tmp/ensembl-io-release-100/modules/Bio/EnsEMBL/IO'
No such file or directory at INSTALL.pl line 706.
```

Could you suggest me a solution to install VEP on Windows?

**Comment by helensch** [comment]
Hi

Thanks for letting us know about the broken link. We will update our documentation.

From your error message it looks like the installation successfully unpacked and moved some of the Ensembl API files but
failed on the ensemb-io. 

Please could you check if file exist in './Bio/tmp/ensembl-io-release-100/'

There may have been a download error. Do you get the same error on re-running the install?

An alternative to installing VEP under Windows is to use Docker
https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker

Regards
Helen

**Comment by peranti** [comment]
Hi,

Yes, the issue remains after reinstallation too!

Meanwhile, I will try the Docker option and update the thread!

**Comment by helensch** [comment]
Hi

I'm going to close this issue now. 

If you have any further questions, please feel free to reopen it or create a new issue.

Regards,
Helen
