### ISSUE TITLE
Location of the bam file required for correcting transcript models has been changed

### ISSUE THREAD

**Issue by hsiaoyi0504** [Ensembl/ensembl-vep#820]
## Describe the issue

The location of bam files listed on this page: http://apr2020.archive.ensembl.org/info/docs/tools/vep/script/vep_other.html seems to have been changed to https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/annotation_releases/109/GCF_000001405.38_GRCh38.p12/RefSeq_transcripts_alignments/

However, in the current web page: ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/ARCHIVE/ANNOTATION_RELEASE.109/GRCh38_interim_annotation/ is indicated.

**Comment by at7** [comment]
Hi @hsiaoyi0504,

thank you very much for pointing this out. We have updated the link as part of our new release 101 which will be out soon. I will let you know here when the new release 101 is out.

Best wishes,
Anja

**Comment by at7** [comment]
Hi @hsiaoyi0504,
the links has now been updated.

Best wishes,
Anja

**Comment by lefcode** [comment]
Hello,
I have a question. Do you know where the .bam file should be in order for VEP to work?
I receive the error:

No index file for /home/lefos/Desktop/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationType/GCF_000001405.39_GRCh38.p13_knownrefseq_alns.bam; try opening file with -autoindex at /home/lefos/Desktop/ensembl-vep/Bio/DB/HTS.pm line 2056.

**Comment by at7** [comment]
Hi @lefcode,
could you please share your full VEP command? But generally speaking, you need to specify the location of your bam file with --bam [filename] as described [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#other). Please also note that from release 90 onwards, bam alignments have been incorporated and used to correct the transcript models in the human RefSeq and merged cache files. Which means that you don't need to specify a bam file. You can read the details [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#refseq).
Best wishes,
Anja

**Comment by lefcode** [comment]
Hi @at7 ,
The full VEP command is the following

./vep --cache --refseq -i ~/Desktop/SNPs-Prediction/04_Features_computation/refseqs.txt --format id --symbol --canonical --protein -o non_pathogenic_vep_output.txt  --force --bam ~/Downloads/GCF_000001405.39_GRCh38.p13_knownrefseq_alns.bam

And I receive the error that I said in the previous message.

Maybe it would be better to describe you what I desire from VEP output.
I'd like to see in the Gene and Feature columns results of ensembl transcripts such as:
ENSG00000224969 (GENE)	and ENST00000458555 (FEATURE).

But without bam, instead of them I receive genes and features such as:
538(GENE) and NM_000052.7 (FEATURE)

Do you know if this is possible? I read in the links that you sent that bam files are basically alignments between ensembl transcripts and refseqs.
Thanks in advance, 
Lefos

**Comment by at7** [comment]
Hi Lefos,
if you only want to use Ensembl transcripts as annotation source then you don't use --refseq and --bam options. If you also want refseq annotation you can use the merged cache files with --merged. You don't need to specify a bam file. The corrections between RefSeq transcripts and the reference genome are already contained in the refseq and merged cache files. [Here](https://www.ensembl.info/2020/06/26/cool-stuff-the-ensembl-vep-can-do-analysis-with-refseq-transcripts/) is a blog post where we explain how we correct RefSeq transcripts.

Best wishes,
Anja

**Comment by lefcode** [comment]
Thank you for you reply,
In case I don't use --refseq then my results are full of blank (-) rows in almost all columns. That's the reason why I used --refseq since my input is a file with refseq ids.

So using --refseq is maybe necessary to use.

**Comment by at7** [comment]
It should work with refseq ids. I can run:
./vep --cache --offline --id "NC_000001.11 230710048 230710048 A/G 1"
Could you please share some of your input data?
Thank you

**Comment by lefcode** [comment]
Yes of course,
[refseqs_test.txt](https://github.com/Ensembl/ensembl-vep/files/5952159/refseqs_test.txt)

**Comment by at7** [comment]
The identifiers in your input file are variant identifiers. VEP needs to make connections to the Ensembl database to look up the location and allele information before annotating the variant with the overlapping transcripts from the cache file. It should work with the Ensembl transcript cache file. Can you please let me know what you get when you run:
`./vep --cache --format id --symbol --canonical --protein -o non_pathogenic_vep_output.txt --force --id "rs786201005"`

**Comment by lefcode** [comment]
#Uploaded_variation | Location | Allele | Gene | Feature | Feature_type | Consequence | cDNA_position | CDS_position | Protein_position | Amino_acids | Codons | Existing_variation | Extra
rs786201005 | 1:1014143 | T | - | - | - | intergenic_variant | - | - | - | - | - | - | IMPACT=MODIFIER

This is the output

**Comment by lefcode** [comment]
It looks like the only possible result is the one I described before.
For you convenience I attach two files.

- Vep output file is the one I receive from using VEP comand line tool [vep_output.txt](https://github.com/Ensembl/ensembl-vep/files/5952483/vep_output.txt)
 
- Test VEP file has the format that I want to create. Specifically, Gene and Feature columns are the ones that I need more.
[test_vep.txt](https://github.com/Ensembl/ensembl-vep/files/5952492/test_vep.txt)

Lefos

**Comment by at7** [comment]
Is it possible that you have only downloaded the refseq cache file? You probably also need to install the Ensembl transcript cache file ([cache file installation docs](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache)).

**Comment by lefcode** [comment]
If you mean this site: [vep files](ftp://ftp.ensembl.org/pub/release-102/variation/vep/) then I have both 
homo_sapiens_vep_102_GRCh38.tar.gz and
homo_sapiens_refseq_vep_102_GRCh38.tar.gz

**Comment by lefcode** [comment]
Btw it may help that in the examples of Web Tool [Web Interface](https://www.ensembl.org/Multi/Tools/VEP?db=core)

I get the desired output by using as **input** the _Variant Identifiers_ and as **Transcript database:** the _Ensembl/GENCODE and RefSeq transcripts_

**Comment by at7** [comment]
I can see from your vep_output.txt that your refseq cache is under  /home/lefos/.vep/homo_sapiens_refseq/102_GRCh38
Can you please check that you also have data under /home/lefos/.vep/homo_sapiens/102_GRCh38?
Thank you

**Comment by lefcode** [comment]
Yes I have. 
All the archive of homo_sapiens_refseq_vep_102_GRCh38.tar.gz is there.
I executed an ls command in order to show you the content.

 lefos@lefos:~/.vep/homo_sapiens/102_GRCh38$ ls
CHR_HG107_PATCH                             KI270709.1  LRG_216
CHR_HSCHR11_1_CTG5                          KI270731.1  LRG_238
CHR_HSCHR1_3_CTG31                          LRG_10      LRG_39
CHR_HSCHR4_11_CTG12                         LRG_1171    LRG_390
CHR_HSCHRX_3_CTG7                           LRG_1308    LRG_536
Homo_sapiens.GRCh38.dna.toplevel.fa.gz      LRG_1323    LRG_617
Homo_sapiens.GRCh38.dna.toplevel.fa.gz.fai  LRG_162     LRG_779
Homo_sapiens.GRCh38.dna.toplevel.fa.gz.gzi  LRG_195

Thank you

**Comment by at7** [comment]
That looks good for the refseq data. But could you also please check lefos@lefos:~/.vep/**homo_sapiens**/102_GRCh38$ ls

**Comment by lefcode** [comment]
lefos@lefos:~/.vep/homo_sapiens/102_GRCh38$ ls
CHR_HG107_PATCH                             KI270709.1  LRG_216
CHR_HSCHR11_1_CTG5                          KI270731.1  LRG_238
CHR_HSCHR1_3_CTG31                          LRG_10      LRG_39
CHR_HSCHR4_11_CTG12                         LRG_1171    LRG_390
CHR_HSCHRX_3_CTG7                           LRG_1308    LRG_536
Homo_sapiens.GRCh38.dna.toplevel.fa.gz      LRG_1323    LRG_617
Homo_sapiens.GRCh38.dna.toplevel.fa.gz.fai  LRG_162     LRG_779
Homo_sapiens.GRCh38.dna.toplevel.fa.gz.gzi  LRG_195

Here you are

**Comment by at7** [comment]
If that is the complete list of directories in lefos@lefos:~/.vep/homo_sapiens/102_GRCh38 then you are missing data and I would recommend that you delete everything under 102_GRCh38 and run the tar command again. Have you checked the size of homo_sapiens_vep_102_GRCh38.tar.gz?

If you need to download the file again I would recommend downloading the indexed cache files from ftp://ftp.ensembl.org/pub/release-102/variation/indexed_vep_cache/ instead. Using indexed cache files will make your VEP annotations run a lot faster.

**Comment by lefcode** [comment]
What data am I missing?  Please notice that each lines consists of 3 files and not 1.

Shall I try to download the merged file instead of the  homo_sapiens_vep_102_GRCh38.tar.gz ?

**Comment by at7** [comment]
homo_sapiens/102_GRCh38 and homo_sapiens_refseq/102_GRCh38 must have the same content/ number of sub-directories. Could you please check that this is the case?

**Comment by lefcode** [comment]
Actually I used the download options to install-download the homo_sapiens/102_GRCh38.gz file so maybe something different has happened through this procedure.
Also  homo_sapiens_refseq/102_GRCh38 has way more files than homo_sapiens/102_GRCh38. 

Alsp, why would that be such a problem?

**Comment by at7** [comment]
Something must have gone wrong in the cache file installation and I would recommend that you try installing them again. The sub-directories are named by genomic region and contain the transcripts for that region. You seem to be missing a lot of those directories. VEP then doesn't find the transcripts for a specific region and this is why you are missing the annotations.

**Comment by lefcode** [comment]
Thank you,
I will let you know as soon as I download the file

**Comment by lefcode** [comment]
Hi again @at7, 
Everything works now, it seems that I just needed to re-download the homo_sapiens/102_GRCh38.gz and put it into the correct folder: /home/user-name/.vep/

Thank you so much Anja
