### ISSUE TITLE
Error when using the VEP Docker image for cache installation

### ISSUE THREAD

**Issue by kaloyan-marinov** [Ensembl/ensembl-vep#821]
Hello,

I am unable to use the VEP Docker image for cache installation. My machine is running Ubuntu 18.04.4 LTS.

Following the example given under "Cache and Plugins installation" on http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker, I executed
```
docker run \
    -t \
    -i \
    -v $HOME/vep_data:/opt/vep/.vep \
    ensemblorg/ensembl-vep \
    perl INSTALL.pl \
    --AUTO cf \
    --SPECIES homo_sapiens_refseq \
    --ASSEMBLY GRCh37
```
which gave me the following error:
```
Unable to find image 'ensemblorg/ensembl-vep:latest' locally
latest: Pulling from ensemblorg/ensembl-vep
7595c8c21622: Already exists
d13af8ca898f: Already exists
70799171ddba: Already exists
b6c12202c5ef: Already exists
a017f08c83a9: Already exists
1fa37e4c5684: Already exists
6ca4beb714bf: Already exists
a1e445a0d32e: Already exists
fa532507e038: Already exists
f7e05568a689: Already exists
38467b1964c7: Already exists
Digest: sha256:d62f633b94003761e67d05358d6a16f0b8a4b55ee132ead32c98d2ed516bfd2f
Status: Downloaded newer image for ensemblorg/ensembl-vep:latest
- getting list of available cache files
NB: Remember to use --refseq when running the VEP with this cache!
- downloading ftp://ftp.ensembl.org/pub/release-100/variation/indexed_vep_cache/homo_sapiens_refseq_vep_100_GRCh37.tar.gz
Cannot open Local file /opt/vep/.vep/tmp/homo_sapiens_refseq_vep_100_GRCh37.tar.gz: No such file or directory
at INSTALL.pl line 1263.
curl failed (150), trying to fetch using LWP::Simple
LWP::Simple failed (404), trying to fetch using HTTP::Tiny
Use of uninitialized value in numeric eq (==) at /usr/share/perl/5.26/HTTP/Tiny.pm line 606.
Use of uninitialized value in numeric eq (==) at /usr/share/perl/5.26/HTTP/Tiny.pm line 606.
ERROR: Failed last resort of using HTTP::Tiny to download ftp://ftp.ensembl.org:21/pub/release-100/variation/indexed_vep_cache/homo_sapiens_refseq_vep_100_GRCh37.tar.gz
```

The only thing that came to my mind was to troubleshoot whether `curl` actually works on my machine; for example, running `curl https://www.cyberciti.biz/files/sticker/sticker_book.pdf --output downloaded_sticker_book.pdf` works.

Could you help me get this to work?

Thank you for your time and help.

**Comment by at7** [comment]
Hi @kaloyan-marinov,
Could you please let me know if you created the vep_data directory as per description in our documentation?:
--Create a directory on your machine:
mkdir $HOME/vep_data
--Make sure that the created directory on your machine has read and write access granted so the docker container can write in the directory (VEP output):
chmod a+rwx $HOME/vep_data

Thank you,
Anja

**Comment by kaloyan-marinov** [comment]
Hi Anja,

I checked what you suggested, and it turned out that I had done the former but not the latter.

After changing the permissions on the `$HOME/vep_data` folder, I was able to execute the command successfully.

Many thanks for your help!

**Comment by at7** [comment]
I'm glad to hear that it is working for you now. I will close this issue but feel free to reopen the issue or create a new issue for any future problems you might encounter.
