### ISSUE TITLE
Error while using NCBI bam file for refseq annotation

### ISSUE THREAD

**Issue by MaguelonneR** [Ensembl/ensembl-vep#824]
I would like to predict the effect of my WGS variants based on RefSeq transcripts. 

My understanding is that I should use NBCI bam file to properly annotate the variants. So I downloaded the .bam et .bam.bai files from this link (https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/annotation_releases/105.20190906/GCF_000001405.25_GRCh37.p13/RefSeq_transcripts_alignments/).

I'm running this commande line : 
./vep -i examples/homo_sapiens_GRCh37.vcf -o examples/homo_sapiens_GRCh37_TEST.txt --offline --cache --force --refseq --bam Resources/GCF_000001405.25_GRCh37.p13_knownrefseq_alns.bam --use_given_ref

And I'm getting this error: [W::bam_hdr_read] EOF marker is absent. The input is probably truncated

I downloaded the .bam file several times and I still have the same issue. 

How could I fix this error?

### System
- VEP version: 100.4
- VEP Cache version: 100
- Perl version: 5.26.2
- OS: MacOS

**Comment by ima23** [comment]
Hi @MaguelonneR,

Starting with version 90, the NCBI bam files for human are already accounted for within the VEP code and does not need the `-bam ` parameter. 
More information can be found here: http://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#refseq. 
Could you try without the `-bam` parameter and let me know i

**Comment by MaguelonneR** [comment]
It worked. Thank you for your help!
