### ISSUE TITLE
Attempt to reload Bio/EnsEMBL/IO/Parser.pm aborted

### ISSUE THREAD

**Issue by NextGenBioinformatics** [Ensembl/ensembl-vep#825]
Hi there,

I am attempting to install the latest version of VEP by executing the following command line:

`perl INSTALL.pl`

The error message:

Downloading required Ensembl API files
 - fetching ensembl
 - unpacking ./Bio/tmp/ensembl.zip
 - moving files
 - getting version information
 - fetching ensembl-variation
 - unpacking ./Bio/tmp/ensembl-variation.zip
 - moving files
 - getting version information
 - fetching ensembl-funcgen
 - unpacking ./Bio/tmp/ensembl-funcgen.zip
 - moving files
 - getting version information
 - fetching ensembl-io
 - unpacking ./Bio/tmp/ensembl-io.zip
 - moving files
 - getting version information

Testing VEP installation
ERROR: Testing VEP script failed with the following error
Attempt to reload Bio/EnsEMBL/IO/Parser.pm aborted.
Compilation failed in require at perl-5.32.0/perl-5.32.0/lib/5.32.0/parent.pm line 16.
BEGIN failed--compilation aborted at ensembl-vep/Bio/EnsEMBL/IO/TextParser.pm line 45.
Compilation failed in require at perl-5.32.0/perl-5.32.0/lib/5.32.0/parent.pm line 16.
BEGIN failed--compilation aborted at ensembl-vep/Bio/EnsEMBL/IO/ColumnBasedParser.pm line 36.
Compilation failed in require at perl-5.32.0/perl-5.32.0/lib/5.32.0/parent.pm line 16.
BEGIN failed--compilation aborted at ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 45.
Compilation failed in require at perl-5.32.0/perl-5.32.0/lib/5.32.0/parent.pm line 16.
BEGIN failed--compilation aborted at ensembl-vep/Bio/EnsEMBL/IO/Parser/VCF4.pm line 41.
Compilation failed in require at ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 79.
BEGIN failed--compilation aborted at ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 79.
Compilation failed in require at ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 71.
BEGIN failed--compilation aborted at ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 71.
Compilation failed in require at ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 83.
BEGIN failed--compilation aborted at ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 83.
Compilation failed in require at ./vep line 20.
BEGIN failed--compilation aborted at ./vep line 20.

I have tried the solution below, but it didn't work.

```
wget https://cpan.metacpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.6.924.tar.gz
tar zxvf BioPerl-1.6.924.tar.gz
PERL5LIB=${PERL5LIB}:BioPerl-1.6.924
```

Thank you for your help.

Tom

**Comment by ima23** [comment]
Hi Tom,

The issue seems related to `reload Bio/EnsEMBL/IO/Parser.pm`. Can you check for me please if you have the following 2 libs installed: `Carp`, `Try::Tiny`? 

Thanks,
Irina

**Comment by jo6fu3** [comment]
Hi,

I was encountered the same error message:

Testing VEP installation
ERROR: Testing VEP script failed with the following error
Attempt to reload Bio/EnsEMBL/IO/Parser.pm aborted.
Compilation failed in require at /usr/share/perl5/vendor_perl/parent.pm line 20.
BEGIN failed--compilation aborted at /pkg/bioinfo_pkg/ensembl-vep/Bio/EnsEMBL/IO/TextParser.pm line 45.
Compilation failed in require at /usr/share/perl5/vendor_perl/parent.pm line 20.
BEGIN failed--compilation aborted at /pkg/bioinfo_pkg/ensembl-vep/Bio/EnsEMBL/IO/ColumnBasedParser.pm line 36.
Compilation failed in require at /usr/share/perl5/vendor_perl/parent.pm line 20.
BEGIN failed--compilation aborted at /pkg/bioinfo_pkg/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 45.
Compilation failed in require at /usr/share/perl5/vendor_perl/parent.pm line 20.
BEGIN failed--compilation aborted at /pkg/bioinfo_pkg/ensembl-vep/Bio/EnsEMBL/IO/Parser/VCF4.pm line 41.
Compilation failed in require at /pkg/bioinfo_pkg/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 79.
BEGIN failed--compilation aborted at /pkg/bioinfo_pkg/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 79.
Compilation failed in require at /pkg/bioinfo_pkg/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 71.
BEGIN failed--compilation aborted at /pkg/bioinfo_pkg/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 71.
Compilation failed in require at /pkg/bioinfo_pkg/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 83.
BEGIN failed--compilation aborted at /pkg/bioinfo_pkg/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 83.
Compilation failed in require at ./vep line 20.
BEGIN failed--compilation aborted at ./vep line 20.

Then I checked the` Carp`and `Try::Tiny` lib, and found that I didn't have  `Try::Tiny`.
After install `Try::Tiny`, problem solved!

Thanks @ima23

**Comment by ima23** [comment]
Thanks for letting us know @jo6fu3 and glad it fixed the issue.
I will close this ticket now. If this issue is not fixed for you @NextGenBioinformatics, please feel free to reopen it.
Thanks,
Irina
