### ISSUE TITLE
Missing transcripts in VEP output

### ISSUE THREAD

**Issue by tuncayseker** [Ensembl/ensembl-vep#827]
Some transcripts are not seen in the VEP output (local run with the cache and custom GFF file) and also in the web interface.

Example:
variant :  4:187209227:G:A
genome_version : hg19

In the output, 
for  F11 gene  (NM_001354804)
for F11-AS1   (NR_033900, ENST00000510172, ENST00000508110, ENST00000508287) are not listed when I run VEP in my local or in web interface. 
These transcripts are present in ensembl and refseq gff file. And other F11-AS1 transcripts (ENST00000505103, NR_033900.1) which are  listed in the output are not specifed as canonical whereas canonical transcripts are specified for F11 gene. Is this a bug or VEP discards some transcripts based on a rule? 

-----
### System
- VEP version: 100.2 (docker image)
- VEP Cache version: 100
- OS: Ubuntu
- tabix installed: yes

Best

tuncay

**Comment by ima23** [comment]
Hi Tuncay,

can you let me know what VEP parameters have you used? Some of the options can pick only one to display, see `-pick`: 
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html

Thanks,
Irina

**Comment by tuncayseker** [comment]
Hi Irina,

Thanks for the quick response. I'm sharing the vep output (
http://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Results?tl=8jmiHzxuYTeHvkJb-6475901
)

Here is the summary for the comparison between the output and the
transcripts in the related gff files (transcript gff versions are same as
indicated in the website). I didn't use --pick or any other filter in the
command line.

*Gene-id*:ENSG00000251165
*Symbol*:F11-AS1
*Transcripts(gff file)*
:ENST00000505103,ENST00000508110,ENST00000510172,ENST00000508287
*Reported*:ENST00000505103 (not shown as canonical)
*Missing*:*ENST00000508110**,ENST00000510172,ENST00000508287

*Gene-id*:285441
*Symbol:*F11-AS1
*Transcripts(gff file)*:NR_033900,NR_033901
*Reported*:NR_033900 (not shown as canonical)
*Missing:NR_033901**

*ENST00000508110 and NR_033901 as longest transcripts should be reported as
canonical transcript according to canonical transcript selection rule.

*Gene-id*:ENSG00000088926
*Symbol:*F11
*Transcripts(gff file)*:
ENST00000403665,ENST00000264692,ENST00000492972,ENST00000514715,ENST00000452239,ENST00000264691,ENST00000503841
*Reported*:ENST00000264691,ENST00000264692,ENST00000403665(*canonical*
),ENST00000503841
*Missing*: ENST00000492972,ENST00000514715,ENST00000452239

*Gene-id*:2160
*Symbol*:F11
*Transcripts(gff file)*: NM_000128,NM_001354804
*Reported*: NM_000128 (*canonical*)
*Missing*: NM_001354804

Best
Tuncay


Irina Armean <notifications@github.com>, 13 Ağu 2020 Per, 16:05 tarihinde
şunu yazdı:

**Comment by ima23** [comment]
Hi Tuncay,

hank you for the link and examples.

The Ensembl VEP will output consequences for transcripts overlapping the variation. For variation: `4:187209227:G:A` that means location `4:187,209,227`.

For the first example, gene ENSG00000251165 (F11-AS1), only one of the 4 transcripts overlaps the variation, namely ENST00000505103.1. See below the gene/transcripts and their location:

> ENSG00000251165 (F11-AS1):            4: 187,207,248-187,422,151
> ENST00000505103.1 (F11-AS1-004): 4: 187,207,248-187,422,151 
> ENST00000508110.1 (F11-AS1-001):  4: 187,344,882-187,422,151
> ENST00000508287.1 (F11-AS1-003): 4: 187,348,128-187,422,151
> ENST00000510172.1 (F11-AS1-002):  4: 187,344,882-187,347,447

http://grch37.ensembl.org/Homo_sapiens/Location/View?db=core;g=ENSG00000251165;r=4:187207248-187422151

Similar for the RefSeq gene model 285441 (F11-AS1) where only one transcript overlaps the variation:

> NR_033900.1: 4: 187,207,252-187,422,212
> NR_033901.1:  4: 187,337,280-187,422,212

For F11 gene only 4 Ensembl transcripts overlap location 4:187,209,227.
http://grch37.ensembl.org/Homo_sapiens/Location/View?db=core;g=ENSG00000088926;r=4:187187099-187210835

Relating to the canonical transcript questions:
- for F11-AS1 (id:ENSG00000251165) , ENST00000508110.1 is canonical and is not reported as it does not cover the input variation
- F11 (ENSG00000088926),  ENST00000403665.2 is the canonical and is reported as it covers the variation and the canonical flag is correct in your output
- F11-AS1 (285441), NR_033901.1 is the canonical and is not reported as it does not cover the input variation

Hope this helps,
Irina

**Comment by ima23** [comment]
Hi, I will close this issue but feel free to reopen it or create a new issue for any future problems.
