### ISSUE TITLE
HGVS output for some but not all variants

### ISSUE THREAD

**Issue by mvheetve** [Ensembl/ensembl-vep#829]
Hi,

using vep to annotate variants from genetic screening. After converting vep output (vcf) to a more readable format I noticed a large number of variants do not include HGVS annotation. I get that for some variants c. or p. annotation is not possible or not yet implemented, but how come a large number of HGVSg annotations are also missing? It seems that all variants missing HGVSg strings are also missing rsID numbers. I've included an example file of the final format, looking at the variant in line 4 of the file there is no HGVS(g, c or p) or rsID returned by vep. However, it concerns a known variant, so I would expect vep to find these data from [Ensembl](https://www.ensembl.org/Homo_sapiens/Variation/Mappings?db=core;r=1:169921292-169922292;tl=1QhBCg5oqe3M7ojo-6482235;v=rs518928;vdb=variation;vf=253262) or [dbSNP](https://www.ncbi.nlm.nih.gov/snp/rs518928).

Any ideas as to why these data are missing and if possible solve this problem? 
Kind regards

Mattias

### System
- VEP version: 100 
- VEP Cache version: 100
- Perl version: 5.26.2
- OS: MacOS 10.15.6
- tabix installed yes

### Full VEP command line
```
vep --input_file $input --stats_file $stats --output_file $output --cache --dir_cache $cache_dir --fork $fork --format vcf --vcf --fasta $fasta  --hgvsg --hgvs --regulatory --numbers --af_gnomad
```

### Full error message
Possible precedence issue with control flow operator at /Users/mvheetve/miniconda/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.

### Data files (if applicable)
They include:
- The input file: multi-sample vcf file
- The output file: multi-sample vcf file
- The custom file: the aformentioned example file [example.txt](https://github.com/Ensembl/ensembl-vep/files/5074616/example.txt)

**Comment by dglemos** [comment]
Hi @mvheetve,
I tried to reproduce your issue but when I run VEP the output contains HGVSg for all of the variants. 
About the error message, it seems to be a BioPerl warning message. You should make sure you only have one version installed. 
I have a few questions/suggestions:
 - Which fasta file are you using? 
 - Run the same vep command but without the `--stats_file` option. 
 - If the suggestion above doesn't work, run vep offline with `--offline` and if possible share your output file.

**Comment by mvheetve** [comment]
Hi,

thank you for your quick reply. Tried `--offline`, without `--stats_file` but no luck. Fasta came with cache installation, currently it is `Homo_sapiens.GRCh38.dna.toplevel.fa.gz`. I think I know what's going on, you've probably used my example file to build an input file for VEP. I'm running a multi-sample vcf as input, but I've noticed there's a mixture of vcf and gvcf formatted samples (`<NON_REF>` alleles). The gvcf format input leads to output without rsID or HGVS annotation. 
Please keep this thread open, I'll try and convert to vcf using `bcftools convert` and see if that fixes it. 

Regards
Mattias

**Comment by mvheetve** [comment]
Hi, 

justed wanted to update in case anyone else comes across this issue. 

So it was the format that caused the issue. I've converted to biallelic variants instead of multi-allelic `bcftools norm -m-any`, next used removed all `<NON_REF>` alleles with `bcftools view -e ALT="<NON_REF>` and used the exact same command as before
`vep --input_file $input --stats_file $stats --output_file $output --cache --dir_cache $cache_dir --fork $fork --format vcf --vcf --fasta $fasta  --hgvsg --hgvs --regulatory --numbers --af_gnomad`

All variants got annotated :)
Sorry to trouble you

Regards
Mattias
