### ISSUE TITLE
Error linked to the Downstream plugin

### ISSUE THREAD

**Issue by aditisk** [Ensembl/ensembl-vep#835]
Hi,

I am running into an error linked to the Downstream plugin when I try to run the VEP command. I'm using VEP v101.0. My error message is pasted below:

`Possible precedence issue with control flow operator at /ihome/rferris/adk85/.conda/envs/pvactools/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
Use of uninitialized value in numeric lt (<) at /ihome/rferris/adk85/.conda/envs/pvactools/bin/VEP_plugins/Downstream.pm line 129, <__ANONIO__> line 12610.
Use of uninitialized value in numeric lt (<) at /ihome/rferris/adk85/.conda/envs/pvactools/bin/VEP_plugins/Downstream.pm line 129, <__ANONIO__> line 12610.
Use of uninitialized value in addition (+) at /ihome/rferris/adk85/.conda/envs/pvactools/bin/VEP_plugins/Downstream.pm line 129, <__ANONIO__> line 12610.
Use of uninitialized value in numeric lt (<) at /ihome/rferris/adk85/.conda/envs/pvactools/bin/VEP_plugins/Downstream.pm line 129, <__ANONIO__> line 18659.
Use of uninitialized value in numeric lt (<) at /ihome/rferris/adk85/.conda/envs/pvactools/bin/VEP_plugins/Downstream.pm line 129, <__ANONIO__> line 18659.
Use of uninitialized value in addition (+) at /ihome/rferris/adk85/.conda/envs/pvactools/bin/VEP_plugins/Downstream.pm line 129, <__ANONIO__> line 18659.
Use of uninitialized value in numeric lt (<) at /ihome/rferris/adk85/.conda/envs/pvactools/bin/VEP_plugins/Downstream.pm line 129, <__ANONIO__> line 20192.
Use of uninitialized value in numeric lt (<) at /ihome/rferris/adk85/.conda/envs/pvactools/bin/VEP_plugins/Downstream.pm line 129, <__ANONIO__> line 20192.
Use of uninitialized value in addition (+) at /ihome/rferris/adk85/.conda/envs/pvactools/bin/VEP_plugins/Downstream.pm line 129, <__ANONIO__> line 20192.
`
Could you please help me fix this issue ? Thank you.

**Comment by ima23** [comment]
Hi @aditisk,

Thanks for the error log. Can you please share your VEP command and an example that triggers this error for me to reproduce it?

Thanks,
Irina

**Comment by aditisk** [comment]
Hi @ima23,

Thank you for the prompt response. Here is my command:

`/ihome/rferris/adk85/.conda/envs/pvactools/bin/vep \
--input_file /zfs1/rferris/adk85/Zandberg_0001-WES/results/Mutect2/ZAN173A15_vs_ZAN173A16/filtered_somatic_ZAN173A15_vs_ZAN173A16.vcf \
--output_file ./VEP_Test/HN9080_vep.vcf \
--format vcf \
--vcf \
--symbol \
--terms SO \
--tsl \
--hgvs \
--fasta /zfs1/rferris/adk85/Zandberg_0001-WES/Homo_sapiens.GRCh38.dna.primary_assembly.fasta \
--offline \
--dir_cache /zfs1/rferris/adk85/Tools/ensembl-vep \
--plugin Downstream \
--plugin Wildtype \
--dir_plugins /ihome/rferris/adk85/.conda/envs/pvactools/bin/VEP_plugins \
--verbose

`
Despite of those errors/warning, I have an annotated VCF and HTML file being created. Does this indicate that I can ignore those error lines ?

If we still need the VCF file for debugging, I can get approval and send a subset of the file to you for testing.

Thanks.

**Comment by ima23** [comment]
Hi @aditisk,

Thank you for the VEP command. Given the error, it looks like one of the transcripts that overlaps one of the input variation is not leading to a translation, to be able to reproduce and check the case I would need to know what variation that is.

Potentially the VCF is annotated to completion with the lines related to the error containing empty annotations from Downstream plugin. 

If you could identify and share a small input example that reproduces this behaviour then I can look further into this.

Thanks,
Irina

**Comment by aditisk** [comment]
Hi @ima23, I can make a small input example and share it with you. Could you please give me your email ID ? I would prefer sending the file privately rather than uploading it here.

Thanks a lot.

**Comment by ima23** [comment]
Hi @aditisk,

Sounds good. Can you send it to  helpdesk@ensembl.org please. I will pick it up from there. 

Thanks,
Irina

**Comment by aditisk** [comment]
Hi @ima23, just sent the file over. I'm closing this issue, we can continue via email. Thanks.
