### ISSUE TITLE
ERROR: Out of memory error when using cache

### ISSUE THREAD

**Issue by pinmarch** [Ensembl/ensembl-vep#836]
Hi, I sometimes get the OOM error at the line below.
https://github.com/Ensembl/ensembl-vep/blob/bf8fce94cfe1889c92771695bb57931b43b72484/modules/Bio/EnsEMBL/VEP/AnnotationSource.pm#L134

I think "$self->clean_cache" is required not after that line but before.
https://github.com/Ensembl/ensembl-vep/blob/bf8fce94cfe1889c92771695bb57931b43b72484/modules/Bio/EnsEMBL/VEP/AnnotationSource.pm#L136

**Comment by aparton** [comment]
Hi,

Thanks for this report. Could you please send me your VEP command and input data used that produced this issue, so that I can take a closer look?

Kind Regards,
Andrew

**Comment by pinmarch** [comment]
Thanks for your reply.

Command:
`vep -i input.vcf --assembly GRCh38 --offline --merged --everything --cache_version=100`
(VEP API version = 101, and RAM is limited to 4g or 8g with the option of docker container)

chr1 is processed without problems, but chr2 causes the OOM error.
(so input.vcf contains chr1 to 3)

Sincerely yours,
[input.zip](https://github.com/Ensembl/ensembl-vep/files/5123037/input.zip)

**Comment by aparton** [comment]
Hi @pinmarch,

I suspect this is due to the regulatory data being switched on as part of --everything. If you try running VEP with the additional flag `--buffer_size 500`, then it should prevent your out of memory error from occurring.

Let me know if this solves your issue, if not then I can take a closer look.

Kind Regards,
Andrew

**Comment by pinmarch** [comment]
Thanks for your suggestion.

I did not checked `--buffer_size` option. I tried `--buffer_size=500` and `--buffer_size=300`, but I got same results.

https://github.com/Ensembl/ensembl-vep/blob/bf8fce94cfe1889c92771695bb57931b43b72484/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseSerialized.pm#L125
I confirmed the caching process; it appears to be loading a file for one entire chromosome.
After the process of chr1 gz files, OOM ocurrs by loading ones of chr2 while keeping the chr1 cache.

Sincerely yours,

**Comment by pinmarch** [comment]
Hi, Andrew,

I figured out it passed with `--buffer_size=30` after reconsidering. 
Thanks for your advice.

**Comment by aparton** [comment]
Hi @pinmarch,

I'm glad you've been able to resolve your issue - however `--buffer_size 30` is very small and would probably slow your analyses down a reasonable amount. 

I'd like to investigate a little further just to make sure that there isn't something more concerning going on - could you please tell me a little about the input data you're using that's causing this issue? Are they primarily structural variants or shorter ones? How are you allocating resources to your docker container?

Kind Regards,
Andrew

**Comment by pinmarch** [comment]
Hi, Andrew,

Thanks for your reply.
I used short variants, and mount with `-v vcffiles:/mnt/data -v /path/to/cache:/root/.vep` option.
Docker containers are running on the VirtualBox, Core i7 1 core.

Thank you.

**Comment by aparton** [comment]
Hi @pinmarch,

Thank you for providing that information. As everything is now working at your end, I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew
