### ISSUE TITLE
How to include ref allele and AD:DP (info fields) in --tab format

### ISSUE THREAD

**Issue by Dwooi7417** [Ensembl/ensembl-vep#838]
## Describe the issue
I used the command

vep -i Cap1_index14.g.vcf -o Cap1_index14_vep_tab.g.tsv --tab --format vcf --symbol --everything --terms SO --tsl --hgvs --fasta /home/danwoo/.vep/homo_sapiens/101_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --cache --plugin Downstream --force_overwrite --fields "Location,REF_ALLELE,Allele,SYMBOL,IMPACT,Consequence,gnomAD_AF"

However REF_ALLELE is empty so how do I add the field? Also how do I add the fields AD:DP from INFO? I know its from --custom but I am not sure how it works. Can someone provide another example. I want to calculate variant allele frequency

#Location	REF_ALLELE	Allele	SYMBOL	IMPACT	Consequence	gnomAD_AF
chr1:632317	-	A	MTCO1P12	MODIFIER	non_coding_transcript_exon_variant	0
chr1:632317	-	A	MTCO3P12	MODIFIER	upstream_gene_variant	0
chr1:632317	-	A	MTND1P23	MODIFIER	downstream_gene_variant	0
chr1:632317	-	A	AL669831.3	MODIFIER	intron_variant,non_coding_transcript_variant	0
chr1:632317	-	A	MTCO2P12	MODIFIER	upstream_gene_variant	0
chr1:632317	-	A	AL669831.3	MODIFIER	intron_variant,non_coding_transcript_variant	0
chr1:632317	-	A	AL669831.3	MODIFIER	intron_variant,non_coding_transcript_variant	0
chr1:632317	-	A	AL669831.3	MODIFIER	upstream_gene_variant	0
chr1:632317	-	A	MTND2P28	MODIFIER	downstream_gene_variant	0

### System
- VEP version: [e.g. 98 or 98.1] 
- VEP Cache version: [e.g. 98]
- Perl version: [e.g. 5.26]
- OS: [e.g. MacOS, Ubuntu, CentOS]
- tabix installed ?

### Full VEP command line
```
./vep -i input.txt -o output.txt ...
```

### Full error message
> Including the warnings, if available

### Data files (if applicable)
They include:
- The input file
- The output file
- The custom file(s)
You can provide a sample of them

**Comment by ima23** [comment]
Hi @Dwooi7417,

Thank you for the message. 
I can replicate your issue with the empty REF_ALLELE. It looks like a bug and will update you when a fix is ready.

Relating to your question on keeping `AD:DP` from INFO, if these are in your input vcf, then they would be left unchanged in output if the output format is `vcf`. 
There are a few examples of how to add data with custom flag [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html), please let me know if you have questions on them : 
`./vep [...] --custom Filename , Short_name , File_type , Annotation_type , Force_report_coordinates , VCF_fields`. 

If you are interested in calculating allele frequencies then I would recommend you process your data in output format `vcf` and use a tool such as bcftools to annotate the `INFO/AF` field, see bcftools fill-tags : https://samtools.github.io/bcftools/howtos/plugin.fill-tags.html.

Kind regards,
Irina

**Comment by ima23** [comment]
Hi @Dwooi7417,

Just to let you know there is a fix in place for the missing REF_ALLELE and it should be available with the next release. 
Will let you know when the next release is out.

Kind regards,
Irina

**Comment by ima23** [comment]
Hi @Dwooi7417,

After checking within the team our docs seem not to reflect the intended use of `--fields`, will update this for our future release.

To use `--fields` to show the Extra columns, the appropriate data needs to be made available first.
For your example you would need to add  `--show_ref_allele`, `--symbol`, `--af_gnomad` to the vep command : 

`vep -i Cap1_index14.g.vcf -o Cap1_index14_vep_tab.g.tsv --tab --format vcf --symbol --everything --terms SO --tsl --hgvs --fasta /home/danwoo/.vep/homo_sapiens/101_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --cache --plugin Downstream --force_overwrite --fields "Location,REF_ALLELE,Allele,SYMBOL,IMPACT,Consequence,gnomAD_AF" --show_ref_allele --symbol --af_gnomad ` .

Kind regards,
Irina

**Comment by ima23** [comment]
Hi @Dwooi7417,

our documentation of the [--fields](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_fields) option has been updated with the release of e102 last week.
I will close this ticket now. If you have any related questions feel free to reopen it.

Kind regards,
Irina
