### ISSUE TITLE
VEP output

### ISSUE THREAD

**Issue by stellaoh** [Ensembl/ensembl-vep#843]
Dear vep team, 

I used VEP version 101. 

Q1. Can I get multi allelic variant to splited variants using VEP? 

ex. original vcf
![image](https://user-images.githubusercontent.com/33537478/92065582-f22e5e80-edda-11ea-89dd-0cacaa218f71.png)

ex. like this 
chr1    54712 TTTTCTTTCTTTCTTTCTTTC TTTTCTTTCTTTCTTTC CSQ=xxx
chr1    54712 TTTTCTTTCTTTCTTTCTTTC TTTTCTTTC CSQ=xxx
chr1    54712 TTTTCTTTCTTTCTTTCTTTC TTTTCTTTCTTTC CSQ=xxx
chr1    54712 TTTTCTTTCTTTCTTTCTTTC TTTTCTTTCTTTCTTTCTTTCTTTC CSQ=xxx
etc. 

Q2. Can I retain "GT of original vcf" in CSQ of vep.vcf? 

ex. The genotype of original vcf is 0/1 as below.
 
![image](https://user-images.githubusercontent.com/33537478/92065803-48030680-eddb-11ea-974e-aa87780d4f1b.png)

ex. This is vep annotated vcf.

![image](https://user-images.githubusercontent.com/33537478/92065876-784aa500-eddb-11ea-8e6a-599fbaf0a6b8.png)

Then, I want to emit this result. 

CSQ=C|non_coding_transcript_exon_variant|MODIFIER|DDX11L1|ENSG00000223972|Transcript|ENST00000450305|transcribed_unprocessed_pseudogene|5/6||ENST00000450305.2:n.313G>C||313/632|||||rs531730856|1||1|||SNV|HGNC|HGNC:37102|||||||||||||||,C|non_coding_transcript_exon_variant|MODIFIER|DDX11L1|ENSG00000223972|Transcript|ENST00000456328|processed_transcript|3/3||ENST00000456328.2:n.521G>C||521/1657|||||rs531730856|1||1||1|SNV|HGNC|HGNC:37102|YES|1|||||||||||||,C|downstream_gene_variant|MODIFIER|WASH7P|ENSG00000227232|Transcript|ENST00000488147|unprocessed_pseudogene||||||||||rs531730856|1|1131|-1|||SNV|HGNC|HGNC:38034|YES||||||||||||||,C|downstream_gene_variant|MODIFIER|MIR6859-1|ENSG00000278267|Transcript|ENST00000619216|miRNA||||||||||rs531730856|1|4096|-1|||SNV|HGNC|HGNC:50039|YES|||||||||||||| **0/1**

Thanks.

**Comment by at7** [comment]
Hi,
it is not possible to present each allele of a mutliallelic variant separately in the output if the output format is --vcf. You could post process your output VCF file with bcftools and its [norm --multiallelics](http://samtools.github.io/bcftools/bcftools.html#norm) option.
It is unfortunately also not possible to include the GT value into the CSQ info field. However, if you run VEP with the --[individual](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_individual) option it will add the zygosity of the individual genotype into the CSQ field.

Best wishes,
Anja

**Comment by at7** [comment]
Hi,
I'm going to close the ticket now but please reopen it in case you have any more questions related to the issue.
Best wishes,
Anja
