### ISSUE TITLE
Vep hangs with no error

### ISSUE THREAD

**Issue by mikpom** [Ensembl/ensembl-vep#850]
## Describe the issue
Vep hangs with no error

## Additional information
I recently tried to update VEP version (up to 101) but it hangs with not response or output. All tests on installation passed. If I run my previously installed vep ver. 98 with its corresponding cache the command finishes successfully.

### System
- VEP version: 101
- VEP Cache version: 101
- Perl version: 5.26
- OS: Ubuntu
- tabix installed ? yes

### Full VEP command line
```
/home/mikpom/apps/ensembl-vep-release-101/vep --force_overwrite --format vcf --polyphen b --uniprot --json --symbol --offline --cache --canonical --mane --hgvs --numbers --variant_class --allele_number --fork 4 -i dup.vcf -o dup.annot.vepout --dir /home/mikpom/.vep101 --verbose
```

[input.zip](https://github.com/Ensembl/ensembl-vep/files/5222400/input.zip)

**Comment by dglemos** [comment]
Hi @mikpom,
Can you run the same command but connecting to the database?

**Comment by mikpom** [comment]
Hi @dglemos 
hope you asked the following. 
In this case it also hangs on the last line you can see below.

```
$ /home/mikpom/apps/ensembl-vep-release-101/vep --force_overwrite --format vcf --polyphen b --uniprot --json --symbol --canonical --mane --hgvs --numbers --variant_class --allele_number --fork 4 -i dup.vcf -o dup.annot.vepout --verbose --database
Will only load v101 databases
Species 'homo_sapiens' loaded from database 'homo_sapiens_core_101_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_cdna_101_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_otherfeatures_101_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_rnaseq_101_38'
homo_sapiens_variation_101_38 loaded
homo_sapiens_funcgen_101_38 loaded
No ancestral database found
No ontology database found
ensembl_taxonomy API not found - ignoring ncbi_taxonomy
Use of uninitialized value $ensembl_metadata_db in concatenation (.) or string at /home/mikpom/apps/ensembl-vep-release-101/Bio/EnsEMBL/Registry.pm line 2393.
ensembl_metadata API not found - ignoring 
No production database or adaptor found

```

**Comment by mikpom** [comment]
Hi @dglemos 
hope you meant the following. 
In this case it finishes succesesfully after some time.

```
$ /home/mikpom/apps/ensembl-vep-release-101/vep --force_overwrite --format vcf --polyphen b --uniprot --json --symbol --canonical --mane --hgvs --numbers
--variant_class --allele_number --fork 4 -i dup.vcf -o dup.annot.vepout --verbose --database
Will only load v101 databases
Species 'homo_sapiens' loaded from database 'homo_sapiens_core_101_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_cdna_101_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_otherfeatures_101_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_rnaseq_101_38'
homo_sapiens_variation_101_38 loaded
homo_sapiens_funcgen_101_38 loaded
No ancestral database found
No ontology database found
ensembl_taxonomy API not found - ignoring ncbi_taxonomy
Use of uninitialized value $ensembl_metadata_db in concatenation (.) or string at /home/mikpom/apps/ensembl-vep-release-101/Bio/EnsEMBL/Registry.pm line 2393.                                                      
ensembl_metadata API not found - ignoring
No production database or adaptor found

```

**Comment by dglemos** [comment]
Yes, that's what I meant. 
Can you please list what you have in the directory `/home/mikpom/.vep101`.

**Comment by mikpom** [comment]
Here is the output of `tree -L 3 /home/mikpom/.vep101`

```
/home/mikpom/.vep101                          
└── homo_sapiens                            
    └── 101_GRCh38                                                   
        ├── 1
        ├── 10
        ├── 11
        ├── 12
        ├── 13
        ├── 14
        ├── 15
        ├── 16
        ├── 17
        ├── 18
        ├── 19
        ├── 2
        ├── 20
        ├── 21
        ├── 22
        ├── 3
        ├── 4
        ├── 5
        ├── 6
        ├── 7
        ├── 8
        ├── 9
        ├── CHR_HG107_PATCH
        ├── CHR_HG109_PATCH
        ├── CHR_HG126_PATCH
        ├── CHR_HG1277_PATCH
        ├── CHR_HG1298_PATCH
        ├── CHR_HG1309_PATCH
        ├── CHR_HG1311_PATCH
        ├── CHR_HG1320_PATCH
        ├── CHR_HG1342_HG2282_PATCH
        ├── CHR_HG1362_PATCH
        ├── CHR_HG1384_PATCH
~~lines ommited~~
       ├── Homo_sapiens.GRCh38.dna.toplevel.fa.gz
       ├── Homo_sapiens.GRCh38.dna.toplevel.fa.gz.vep.lock
       ├── info.txt           
~~lines ommited~~

```

**Comment by dglemos** [comment]
The fasta file is inside your cache directory maybe you should remove `Homo_sapiens.GRCh38.dna.toplevel.fa.gz.vep.lock` and move `Homo_sapiens.GRCh38.dna.toplevel.fa.gz` somewhere else and if you want to use the fasta file run vep with the option `--fasta dir/Homo_sapiens.GRCh38.dna.toplevel.fa.gz`. After you move the files, run vep again with your first vep offline command.

**Comment by mikpom** [comment]
I moved the genome to ~/.vep101/FASTA and  tried to run 

`/home/mikpom/apps/ensembl-vep-release-101/vep --force_overwrite --format vcf --polyphen b --uniprot --json --symbol --offline --cache --canonical --mane --hgvs --numbers --variant_class --allele_number --fork 4 -i dup.vcf -o dup.annot.vepout --dir /home/mikpom/.vep101 --verbose --fasta /home/mikpom/.vep101/FASTA/Homo_sapiens.GRCh38.dna.toplevel.fa.gz`

VEP still hangs with no errors or even messages of some kind.

**Comment by dglemos** [comment]
Let's try to run vep with minimal options to be sure it's not one of the flags that is stalling vep: 
`/home/mikpom/apps/ensembl-vep-release-101/vep -i dup.vcf -o dup.annot.vepout --offline --cache --dir_cache /home/mikpom/.vep101 --fasta /home/mikpom/.vep101/FASTA/Homo_sapiens.GRCh38.dna.toplevel.fa.gz `

**Comment by mikpom** [comment]
Looks like it's not, no success with minimal options : - (

**Comment by dglemos** [comment]
Do you have Bio::DB::HTS installed?

**Comment by mikpom** [comment]
Looks like it was not installed system-wide (don't know why VEP v98 worked fine). So I did and now `perl -e use Bio::DB::HTS` gives no errors. Still not responsive. 

PS. Not sure if this is even relevant information but if I add `-fasta /home/mikpom/.vep101/FASTA/Homo_sapiens.GRCh38.dna.toplevel.fa.gz ` to VEP 98 command, it also hangs.

**Comment by dglemos** [comment]
If you run with an unzipped fasta (for both vep versions) does it still hangs with no output?

**Comment by mikpom** [comment]
Both work!

**Comment by dglemos** [comment]
That's good news! When you downloaded the fasta did you unzipped and then recompressed with bgzip? To use compressed files in vep first you need to do those steps, like this:
```
curl -O ftp://ftp.ensembl.org/pub/release-101/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
gzip -d Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
bgzip Homo_sapiens.GRCh38.dna.primary_assembly.fa
```
On this page you can read more about fasta files in vep: https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#fasta

**Comment by mikpom** [comment]
I answered "yes" to the installer when asked whether to download FASTA files so I believe the very first FASTA I used should be automatically downloaded. Don't know why it caused problems.
Uncompressing the file solves the problem though.
