### ISSUE TITLE
Wrong HGVSc position?

### ISSUE THREAD

**Issue by smw1414** [Ensembl/ensembl-vep#851]
## Describe the issue
Hi VEP team, 
I found a incorrect HGVSc nomenclature for SNV chr9:16437210A>T. VEP reported this variant as NM_017637.6:c.1006A>T, a stop_gained mutation. However, I counted the position of chr9:16437210T>A and realized that this mutation locate at 1006 of NM_017637.6. But, this transcript CDS start from 23, Therefore, the correct position should be 984 and the consequences should be synonymous. 
![圖片](https://user-images.githubusercontent.com/28624336/93561803-6b22de00-f9b7-11ea-9225-16f23a0f9e01.png)
![圖片](https://user-images.githubusercontent.com/28624336/93561869-842b8f00-f9b7-11ea-8db1-b919a8f4327c.png)
https://www.ncbi.nlm.nih.gov/nuccore/NM_017637    

### System
- VEP version: 101 
- VEP Cache version: 101 
- OS:  Ubuntu
- tabix installed no

### Full VEP command line
```
docker run --rm  -v $(pwd):/data -v ${HOME}/vep_data:/opt/vep/.vep ensemblorg/ensembl-vep vep --fork 4 -i /data/${input_vcf} --format vcf -v --force --stats_text --assembly GRCh38 --output_file /data/${output_vct} --vcf --allele_number --numbers --everything --minimal --cache --total_length --exclude_predicted --refseq --offline --pick  --pick_order rank,appris,tsl,biotype,ccds,canonical,length
```

**Comment by dglemos** [comment]
@smw1414, 
You are right, the HGVS should be `NM_017637.6:c.984A>T`. This issue has been fixed for later releases. 
In the meantime, if you run vep with Ensembl transcripts the HGVS has the correct CDS position.

**Comment by dglemos** [comment]
Hi @smw1414,
Could you try again running with the current VEP release 102? The CDS position should be 984.

**Comment by dglemos** [comment]
The issue has been fixed. In the current version, the HGVS is `NM_017637.6:c.984A>T`. 
I'm going to close the issue but feel free to open a new one if you have more questions.

Best wishes,
Diana
