### ISSUE TITLE
Installing VEP into a self-contained directory

### ISSUE THREAD

**Issue by anderspitman** [Ensembl/ensembl-vep#857]
For [iobio](https://iobio.io/), we've been running VEP as a singularity container, installed from your Dockerfile. This has worked quite well, but we're now looking into changing our architecture in such a way that it's no longer ideal to use containers at that level.

Has anyone successful installed VEP into a self-contained directory, ie with Perl and all the dependencies contained in a directory you can copy to different machines and run in place? Is there any reason this might not work?

**Comment by ima23** [comment]
Hi @anderspitman,

As long as the environment variables contain the correct paths, VEP will work from a self-contained directory where all the VEP code is based. There should not be any issues, but please do let us know if you encounter any.

Kind regrads,
Irina

**Comment by ima23** [comment]
I am closing this issue now. If you have any related questions please feel free to reopen it.

Kind regards,
Irina
