### ISSUE TITLE
hgvs compliance

### ISSUE THREAD

**Issue by parlar** [Ensembl/ensembl-vep#861]
## Describe the issue
VEP is reporting predicted protein variants in the form p.AaaNumAaa , for example p.Ile2106Thr . 

However,  the hgvs nomenclature prescribes that "predicted consequences, i.e. without experimental evidence (no RNA or protein sequence analysed), should be given in parentheses, e.g. p.(Arg727Ser)"

I guess that it is difficult for VEP to know whether DNA or RNA sequence data is annotated. As I understand, to allow VEP to report correct HGVS nomenclature would require supplying the source material (DNA/RNA) but perhaps the benefit of generating correct hgvs nomenclature does not outweigh the increased "cost" in complexity? 

### System
- VEP version: ensembl-vep-100.4-0
- VEP Cache version: 100

**Comment by helensch** [comment]
Hi

Thank you for for raising this issue. 

We are looking at representing predicted protein changes with parentheses in a future release.

Thanks
Helen
