### ISSUE TITLE
[WARNINGS] Length of reference allele does not match co-ordinates

### ISSUE THREAD

**Issue by KevinMer** [Ensembl/ensembl-vep#862]
## Describe the issue
Trying to convert my VCF to ensembl format, some position remain discarded when running VEP.

## Additional information
Hi everybody,

I'm not sure to understand how to convert some position and I would like more precision about complex VCF entries.

I have three examples to show you.

**First one :**

**VCF format :**
chr1	154869723	.	GGCT	GGCTGCTGCTGCTGCTGCTGCT,GGCTGCTGCTGCT,G,GGCTGCTGCT	2588.36	PASS	.	GT:AD:DP:GQ:PL	1/1:0,17,0,0,0:17:69:1054,69,0,1060,75,1067,1060,75,1067,1067,1060,75,1067,1067,1067	1/2:0,7,6,0,0:13:99:767,232,212,278,0,238,652,248,285,638,652,248,285,638,638	3/4:1,0,0,16,8:28:99:807,852,1273,852,1273,1273,222,642,642,584,612,644,644,0,625

What should the ensembl format looks like ?
Am I supposed to trim the first G, since it is common to all alleles ? 

So it should be this :
1	154869724	154869723	GCT/GCTGCTGCTGCTGCTGCTGCT/CTGCTGCTGCT/-/CTGCTGCT

But I get a warning : (GCT length 3) does not match co-ordinates 154869724-154869723

--------------------------------------------------------------------------------------------------------------------------------------------------
**Second one :**

**VCF format :**
chr1	115700223	.	AT	ATT,A	299.57	PASS	.	GT:AD:DP:GQ:PL	0/1:25,6,0:31:64:64,0,531,139,549,687	0/2:24,0,14:38:99:240,312,854,0,542,500	0/2:19,0,3:22:14:14,71,512,0,441,432

This one looks like the previous one and I have exactly the same questions because I get a warning using this conversion :
1	115700224	115700223	T/TT/-

Warning : (T length 1) does not match co-ordinates 115700224-115700223

--------------------------------------------------------------------------------------------------------------------------------------------------
**Third one :**

**VCF format :**
chr1	55056232	.	GA	*,G	105.09	PASS	.	GT:AD:DP:GQ:PL	1/2:0,2,2:4:56:154,64,56,65,0,124	1/2:0,3,1:4:37:159,37,121,102,0,92	1/1:0,8,0:8:25:336,25,0,336,25,336

Can ensembl format deal with "*" in VCF ? How should I convert this position ?

--------------------------------------------------------------------------------------------------------------------------------------------------
I don't clearly understand the conversion between VCF and ensembl format and hope you could help me.

Thank you in advance for your answer. 

Best regards,

Kevin
### System
- VEP version: [101] 
- VEP Cache version: [101]
- Perl version: [5.26]
- OS: [Ubuntu]
- tabix installed ? -> yes

**Comment by aparton** [comment]
Hi Kevin,

Thanks for your query. Can I ask, why are you looking to convert your VCF into VEP format? VEP will annotate your VCF files as they are, so you shouldn't need to convert your input data to successfully use VEP.

To answer your questions specifically, for cases 1 & 2 then your start/end coordinates need to match your reference sequence, so your VEP input would be:
-chr1 154869723 154869726 GGCT/GGCTGCTGCTGCTGCTGCTGCT/GGCTGCTGCTGCT/G/GGCTGCTGCT
-1 115700224 115700224 T/TT/-

respectively. For case 3, we don't currently support * within VCF input - due to the incomplete description of the overlapping variant then VEP will just skip input of this type.

If you have any other questions, please don't hesitate to ask.

Kind Regards,
Andrew

**Comment by KevinMer** [comment]
Hi Andrew,

thanks a lot for your answer. Thanks to you, I just realized that I misunderstood the documentation. 
I thought that using a VCF as input only led to VCF format as output. But it's not the case. I used my VCF to get a "tab" output and all worked perfectly. 

Thanks again and have a nice day.

Best regards,

Kevin

**Comment by aparton** [comment]
Hi Kevin,

No problem at all, glad that we were able to resolve your issue quickly. If you have any other issues, please feel free to open a new ticket.

Kind Regards,
Andrew
