### ISSUE TITLE
MSG: ERROR: Could not write to FASTA lock file /opt/vep/.vep/Sars_cov_2.ASM985889v3.dna_sm.toplevel.fa.gz.vep.lock

### ISSUE THREAD

**Issue by valemirici** [Ensembl/ensembl-vep#863]
I run the following command
`docker run -t -i -v /root/Documenti/Valeria/1_campioni_17092020/9_VEP/:/opt/vep/.vep ensemblorg/ensembl-vep ./vep -i /opt/vep/.vep/AV09_S31_filter.vcf.gz -o /opt/vep/.vep/s_output.txt --gff /opt/vep/.vep/Sars_cov_2.ASM985889v3.100.primary_assembly.MN908947.3.gff3.gz -fasta /opt/vep/.vep/Sars_cov_2.ASM985889v3.dna_sm.toplevel.fa.gz`

and this is the output

`-------------------- EXCEPTION --------------------
MSG: ERROR: Could not write to FASTA lock file /opt/vep/.vep/Sars_cov_2.ASM985889v3.dna_sm.toplevel.fa.gz.vep.lock

STACK Bio::EnsEMBL::Variation::Utils::FastaSequence::_get_fasta_db /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Variation/Utils/FastaSequence.pm:329
STACK Bio::EnsEMBL::Variation::Utils::FastaSequence::setup_fasta /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Variation/Utils/FastaSequence.pm:212
STACK Bio::EnsEMBL::VEP::BaseVEP::fasta_db /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:477
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:138
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:203
STACK toplevel ./vep:228
Date (localtime)    = Tue Oct  6 10:20:32 2020
Ensembl API version = 101
---------------------------------------------------
`
could someone help me?

**Comment by aparton** [comment]
Hi @valemirici,

Looks like a permissions issue within the bind mount. With the --fasta flag, VEP regenerates the associated index file to avoid partial index issues and VEP is unable to do so inside your docker container.

The good news is that the fix should be as simple as adding `:Z` onto the end of your `-v` command to force docker to set all of the appropriate flags, so your input becomes:

`docker run -t -i -v /root/Documenti/Valeria/1_campioni_17092020/9_VEP/:/opt/vep/.vep ensemblorg/ensembl-vep:Z ./vep -i /opt/vep/.vep/AV09_S31_filter.vcf.gz -o /opt/vep/.vep/s_output.txt --gff /opt/vep/.vep/Sars_cov_2.ASM985889v3.100.primary_assembly.MN908947.3.gff3.gz -fasta /opt/vep/.vep/Sars_cov_2.ASM985889v3.dna_sm.toplevel.fa.gz`

For more information on read/write access within the VEP docker image, see https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker

Please let me know if this fixes your issue, and if you're still having problems then we can take another look.

Kind Regards,
Andrew

**Comment by valemirici** [comment]
Hi Andrew,

Thanks for your reply.

I've added `:Z` in the end of  `-v` but I have still the same problem

`(base) [root@localhost 9_VEP]# docker run -t -i -v /root/Documenti/Valeria/1_campioni_17092020/9_VEP/:/opt/vep/.vep:Z ensemblorg/ensembl-vep ./vep -i /opt/vep/.vep/AV09_S31_filter.vcf.gz -o /opt/vep/.vep/s_output.txt --gff /opt/vep/.vep/Sars_cov_2.ASM985889v3.100.primary_assembly.MN908947.3.gff3.gz -fasta /opt/vep/.vep/Sars_cov_2.ASM985889v3.dna_sm.toplevel.fa.gz

-------------------- EXCEPTION --------------------
MSG: ERROR: Could not write to FASTA lock file /opt/vep/.vep/Sars_cov_2.ASM985889v3.dna_sm.toplevel.fa.gz.vep.lock

STACK Bio::EnsEMBL::Variation::Utils::FastaSequence::_get_fasta_db /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Variation/Utils/FastaSequence.pm:329
STACK Bio::EnsEMBL::Variation::Utils::FastaSequence::setup_fasta /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Variation/Utils/FastaSequence.pm:212
STACK Bio::EnsEMBL::VEP::BaseVEP::fasta_db /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:477
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:138
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:203
STACK toplevel ./vep:228
Date (localtime)    = Tue Oct  6 13:12:04 2020
Ensembl API version = 101
---------------------------------------------------
`

I cannot understand which is the problem.

**Comment by aparton** [comment]
Hi @valemirici,

Thanks for letting me know. Apologies, I should have specified that the original suggestion requires root permissions and Docker 1.7 or higher. 

Alternatively, you should also be able to fix the issue by running `chmod -R a+rwx /opt/vep/.vep/` inside the container. This requires neither the root permissions or Docker version.

Please let me know if this fixes your issue.

Kind Regards,
Andrew

**Comment by valemirici** [comment]
Hi @aparton,

I fixed the issue. 
it was permission problem.

Actually this operation `chmod -R a+rwx /opt/vep/.vep/` is not permitted in the docker.
I'm using Centos8 and Docker version 19.03.13 and I've root permission.

I solved the problems changing permission before running the docker or from the properties folder (not by command line).

Thanks for your support!

Kings Regards,
Valeria
