### ISSUE TITLE
Argument"." isn't numeric in numeric eq (==) at ........../vep_data/Plugins//dbNSFP.pm line 323, <__ANONIO__> line 14869295

### ISSUE THREAD

**Issue by marionamujal** [Ensembl/ensembl-vep#864]
Hi, 
kindly requesting for your help on this?
I am using docker to run VEP, when I don't use the dbNSFP plugin, it runs successfully, however, when I use it (dbSNFP plugin), it still runs though does not have any results for the dbNSFP plugin. Instead, I get the error;
Argument "." isn't numeric in numeric eq (==) at ........../vep_data/Plugins//dbNSFP.pm line 323, <__ANONIO__> line 148692

I am using 
- VEP version: 101
- VEP Cache version: 101
- Perl version: v5.26.1
- OS: Debian
- tabix installed ? Yes, tabix (htslib) 1.9

### Full VEP command line
```
./vep --cache --offline --format vcf --vcf --force_overwrite --dir_cache /opt/vep/.vep/ --dir_plugins /opt/vep/.vep/Plugins/ --input_file /opt/vep/.vep/input/..........vcf --output_file /opt/vep/.vep/output/............vcf --plugin dbNSFP,/opt/vep/.vep/Plugins/dbNSFP4.1a.gz,Polyphen2_HVAR_pred,CADD_phred,SIFT_pred,FATHMM_pred,MutationTaster_pred,MetaSVM_score,MetaSVM_pred,MetaLR_score,MetaLR_pred,Reliability_index --species homo_sapiens --assembly GRCh37 --use_given_ref --verbose --sift b --polyphen b --hgvs --fasta /opt/vep/.vep/homo_sapiens/101_GRCh37/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz --symbol --regulatory --canonical --protein --gene_phenotype --af_1kg --af_gnomad --pubmed --pick --per_gene
```
Command used for processing;
> wget ftp://dbnsfp:dbnsfp@dbnsfp.softgenetics.com/dbNSFP4.1a.zip
> unzip dbNSFP4.1a.zip
> zcat dbNSFP4.1a_variant.chr1.gz | head -n1 > h
> zgrep -h -v ^#chr dbNSFP4.1a_variant.chr* | sort -k1,1 -k2,2n - | cat h - | bgzip -c > dbNSFP4.1a.gz
> tabix -s 1 -b 2 -e 2 dbNSFP4.1a.gz
NB; I downloaded this plugin from the googledrive following this link https://sites.google.com/site/jpopgen/dbNSFP

### Full error message
```Argument "." isn't numeric in numeric eq (==) at .................../vep_data/Plugins//dbNSFP.pm line 323, <__ANONIO__> line 11153968.
Argument "." isn't numeric in numeric eq (==) at ............/vep_data/Plugins//dbNSFP.pm line 323, <__ANONIO__> line 11764047.
Argument "." isn't numeric in numeric eq (==) at ............../vep_data/Plugins//dbNSFP.pm line 323, <__ANONIO__> line 11764047.
Argument "." isn't numeric in numeric eq (==) at .................../vep_data/Plugins//dbNSFP.pm line 323, <__ANONIO__> line 11764047.```

Thank you!!

**Comment by helensch** [comment]
Hi

From the VEP command assembly GRCh37 is being used.

Release 4.1a of dbNSFP uses GRCh38/hg38 coordinates and GRCh37/hg19 coordinates. Different parameters for sorting and indexing need to be used depending on the assembly.

For GRCh37, columns 8 and 9 are used. In addition the "." in column 8 need to be removed.  To process the file:

```
zgrep -h -v ^#chr dbNSFP4.1a_variant.chr* | awk '$8 != "." ' | sort -k8,8 -k9,9n - | cat h - | bgzip -c >  bNSFP4.1a_grch37.gz

tabix -s 8 -b 9 -e 9 dbNSFP4.1a_grch37.gz
```

The plugin docs contain information on using Release 3.5a of dbNSFP with GRCh37/hg19. We will update the plugin docs to include information on using Release4.1a of dbNSFP with GRCh37/hg19.

Thank you for raising this issue. Please let me know if you have any further questions. 

Regards
Helen

**Comment by marionamujal** [comment]
Thank you Helen for the reply!
However, after successfully installing the dbNSFP plugins, I now get the error. 
WARNING: Failed to instantiate plugin dbNSFP: ERROR: Could not read headers from /opt/vep/.vep/Plugins/dbNSFP4.1a_grch37.gz.
Note: I also renamed the readme file to dbNSFP4.1a_grch37.readme.txt from dbNSFP4.1a.readme.txt

**Comment by helensch** [comment]
Hi

The error suggests that running tabix on your dbNSFP input file did not work. 

Please could you check if tabix is working for the file by running:
tabix -fh dbNSFP4.1a_grch37.gz 1:1-1

Regards
Helen

**Comment by marionamujal** [comment]
When i run tabix, this is the result
`ayesDel_noAF_rankscore  BayesDel_noAF_pred      ClinPred_score  ClinPred_rankscore      ClinPred_pred   LIST-S2_score   LIST-S2_rankscore       LIST-S2_predAloft_Fraction_transcripts_affected      Aloft_prob_Tolerant     Aloft_prob_Recessive    Aloft_prob_Dominant     Aloft_pred      Aloft_Confidence        CADD_raw     CADD_raw_rankscore      CADD_phred      CADD_raw_hg19   CADD_raw_rankscore_hg19 CADD_phred_hg19 DANN_score      DANN_rankscore  fathmm-MKL_coding_score      fathmm-MKL_coding_rankscore     fathmm-MKL_coding_pred  fathmm-MKL_coding_group fathmm-XF_coding_score  fathmm-XF_coding_rankscore      fathmm-XF_coding_pred        Eigen-raw_coding        Eigen-raw_coding_rankscore      Eigen-phred_coding      Eigen-PC-raw_coding     Eigen-PC-raw_coding_rankscore   Eigen-PC-phred_coding        GenoCanyon_score        GenoCanyon_rankscore    integrated_fitCons_score        integrated_fitCons_rankscore    integrated_confidence_value  GM12878_fitCons_score   GM12878_fitCons_rankscore       GM12878_confidence_value        H1-hESC_fitCons_score   H1-hESC_fitCons_rankscore       H1-hESC_confidence_value     HUVEC_fitCons_score     HUVEC_fitCons_rankscore HUVEC_confidence_value  LINSIGHT        LINSIGHT_rankscore      GERP++_NR       GERP++_RS    GERP++_RS_rankscore     phyloP100way_vertebrate phyloP100way_vertebrate_rankscore       phyloP30way_mammalian   phyloP30way_mammalian_rankscore phyloP17way_primate  phyloP17way_primate_rankscore   phastCons100way_vertebrate      phastCons100way_vertebrate_rankscore    phastCons30way_mammalian        phastCons30way_mammalian_rankscore   phastCons17way_primate  phastCons17way_primate_rankscore        SiPhy_29way_pi  SiPhy_29way_logOdds     SiPhy_29way_logOdds_rankscore        bStatistic      bStatistic_converted_rankscore  1000Gp3_AC      1000Gp3_AF      1000Gp3_AFR_AC  1000Gp3_AFR_AF  1000Gp3_EUR_AC  1000Gp3_EUR_AF       1000Gp3_AMR_AC  1000Gp3_AMR_AF  1000Gp3_EAS_AC  1000Gp3_EAS_AF  1000Gp3_SAS_AC  1000Gp3_SAS_AF  TWINSUK_AC      TWINSUK_AF      ALSPAC_AC       ALSPAC_AF    UK10K_AC        UK10K_AF        ESP6500_AA_AC   ESP6500_AA_AF   ESP6500_EA_AC   ESP6500_EA_AF   ExAC_AC ExAC_AF ExAC_Adj_AC     ExAC_Adj_AF     ExAC_AFR_AC  ExAC_AFR_AF     ExAC_AMR_AC     ExAC_AMR_AF     ExAC_EAS_AC     ExAC_EAS_AF     ExAC_FIN_AC     ExAC_FIN_AF     ExAC_NFE_AC     ExAC_NFE_AF     ExAC_SAS_AC  ExAC_SAS_AF     ExAC_nonTCGA_AC ExAC_nonTCGA_AF ExAC_nonTCGA_Adj_AC     ExAC_nonTCGA_Adj_AF     ExAC_nonTCGA_AFR_AC     ExAC_nonTCGA_AFR_AF     ExAC_nonTCGA_AMR_AC  ExAC_nonTCGA_AMR_AF     ExAC_nonTCGA_EAS_AC     ExAC_nonTCGA_EAS_AF     ExAC_nonTCGA_FIN_AC     ExAC_nonTCGA_FIN_AF     ExAC_nonTCGA_NFE_AC ExAC_nonTCGA_NFE_AF      ExAC_nonTCGA_SAS_AC     ExAC_nonTCGA_SAS_AF     ExAC_nonpsych_AC        ExAC_nonpsych_AF        ExAC_nonpsych_Adj_AC    ExAC_nonpsych_Adj_AF ExAC_nonpsych_AFR_AC    ExAC_nonpsych_AFR_AF    ExAC_nonpsych_AMR_AC    ExAC_nonpsych_AMR_AF    ExAC_nonpsych_EAS_AC    ExAC_nonpsych_EAS_AF    ExAC_`
Thank you!

**Comment by helensch** [comment]
Hi

Thank you for the headers. It looks like tabix is working for you. I assume that the headers you posted have just been truncated as I would expect them to start: #chr pos(1-based) ref

Was the tabix command run on docker where you run vep from? 

Have you tried re-running VEP command after running the tabix command?

Are there any other warning messages returned by VEP? 

Regards
Helen

**Comment by marionamujal** [comment]
Was the tabix command run on docker where you run vep from?
No, i didn't run it in docker

When i run tabix in docker this is the output
`tabix -fh dbNSFP4.1a_grch37.gz 1:1-1` 
[E::hts_open_format] Failed to open file dbNSFP4.1a_grch37.gz
Could not read dbNSFP4.1a_grch37.gz
Thank you

**Comment by helensch** [comment]
Hi

The error message from  tabix in docker ```tabix -fh dbNSFP4.1a_grch37.gz 1:1-1``` suggests it cannot find the file.

Please can you run the tabix command in docker giving the full path to the file e.g.
```tabix -fh /opt/vep/.vep/Plugins/dbNSFP4.1a_grch37.gz 1:1-1```

The error message from VEP suggests that the tabix command is not working when called in the dbNSFP plugin and so it cannot get the headers from using tabix -fh.

Please could you check that:

- you are able to access  /opt/vep/.vep/Plugins/dbNSFP4.1a_grch37.gz and /opt/vep/.vep/Plugins/dbNSFP4.1a_grch37.gz.tbi in docker

-  /opt/vep/.vep/Plugins/dbNSFP4.1a_grch37.gz.tbi has been updated following the creating the file sorted on columns 8,9

```tabix -s 8 -b 9 -e 9 dbNSFP4.1a_grch37.gz```

Regrards
Helen

**Comment by helensch** [comment]
Hi

I'm going to close this issue now. 

If you have any further questions, please feel free to reopen it or create a new issue.

Regards,
Helen
