### ISSUE TITLE
Updated zebra finch assembly 

### ISSUE THREAD

**Issue by madzayasodara** [Ensembl/ensembl-vep#866]
Hi I have generated vcfs using the most recent Zebra finch assembly bTaeGut2.pat.W.v2
available at https://www.ncbi.nlm.nih.gov/genome/?term=txid59729[orgn]
I would like to use vep to annotate synonymous and nonsynonymous substitutions using the corresponding annotation (GCF_008822105.2_bTaeGut2.pat.W.v2_genomic.gff)
However, Ensenbl has an older version of the assembly, bTaeGut1_v1.p, 
https://uswest.ensembl.org/Taeniopygia_guttata/Info/Annotation 
How do I go about using the newer version in my analysis?
Thank you!

**Comment by dglemos** [comment]
Hi @madzayasodara,

You can integrate annotations from standard format files into your VEP results by using the --custom flag. 
You can read more about this functionality here: https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html and
https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gfftypes 

Best wishes,
Diana

**Comment by dglemos** [comment]
Hi @madzayasodara,

You can integrate annotations from standard format files into your VEP results by using the --custom flag.
You can read more about this functionality here: https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html and
https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gfftypes

Best wishes,
Diana

**Comment by madzayasodara** [comment]
Hi Diana, 
thanks for the reply!
I'm just a little confused about which exact cmd to run. Right now, I'm running 
`vep  -i vcf.gz --gff tabixprep.gz --fasta genomic.fa -o vcf.vep.gz --symbol --tab --compress_output gzip --force_overwrite`

using the costumized fasta and gff

Is this what I should be doing? Or I have to also include the custom flag to the cmd above? As in:

```
vep  -i vcf.gz --gff tabixprep.gz --fasta genomic.fa -o vcf.vep.gz --symbol --tab --compress_output gzip --force_overwrite
--custom tabixprep.gz,gff ,exact,0
```

**Comment by madzayasodara** [comment]
I'm also running into the issue "Transcript has unexpected type of child record" [#732](https://github.com/Ensembl/ensembl-vep/issues/732) , see bellow.
Would excluding all miRNA from my gff be a workaround?

-------------------- EXCEPTION --------------------
MSG: ERROR: Transcript has unexpected type of child record: $VAR1 = {
  'strand' => '1',
  'start' => '4288835',
  'source' => 'BestRefSeq',
  '_id' => 'rna-MIR139',
  'phase' => undef,
  'md5' => '8ae57f03afe6a6d36c85316bcaf3122d',
  'end' => '4288857',
  'chr' => 'NC_044998.1',
  'type' => 'miRNA',
  '_children' => [
    {
      'chr' => 'NC_044998.1',
      '_parent_id' => [
        'rna-MIR139'
      ],
      'attributes' => {
        'gbkey' => 'ncRNA',
        'Dbxref' => 'GeneID:100886580,miRBase:MIMAT0014500,miRBase:MI0013689',
        'product' => 'tgu-miR-139-5p',
        'gene' => 'MIR139',
        'ID' => 'exon-MIR139-1',
        'Parent' => 'rna-MIR139'
      },
      'type' => 'exon',
      'start' => '4288835',
      'strand' => '1',
      'md5' => '2e4367502d88773c82ab198b2655221a',
      'end' => '4288857',
      '_id' => 'exon-MIR139-1',
      'source' => 'BestRefSeq',
      'phase' => undef
    }
  ],
  '_parent_id' => [
    'rna-NR_048998.1'
  ],
  'attributes' => {
    'gene' => 'MIR139',
    'ID' => 'rna-MIR139',
    'Parent' => 'rna-NR_048998.1',
    'Dbxref' => 'GeneID:100886580,miRBase:MIMAT0014500,miRBase:MI0013689',
    'product' => 'tgu-miR-139-5p',
    'gbkey' => 'ncRNA'
  }
};

**Comment by dglemos** [comment]
Hi @madzayasodara,
To answer your first question, the first command you're running is right. `vep -i vcf.gz --gff tabixprep.gz --fasta genomic.fa -o vcf.vep.gz` 
About the issue you're running into, currently our GFF file handling doesn't support entries of type 'miRNA'. We have plans to support this however, it will take some time to be implemented. In the meantime, as you suggested you could exclude those entries from the GFF.

**Comment by madzayasodara** [comment]
Got it. I filtered miRNAs from mi file and followed up the analysis with it. Thank you.
