### ISSUE TITLE
BaseCacheVariation.pm line 211: Argument "" isn't numeric in addition (+)

### ISSUE THREAD

**Issue by shintzen** [Ensembl/ensembl-vep#87]
I'm running VEP on a large file. 
`Running ../vep --refseq --dir_cache ../ensembl-vep2 --fasta ../Homo_sapiens_assembly19.fasta --cache --offline --force_overwrite --filter_common --everything --gene_phenotype --regulatory --hgvsg --protein -i ../ALLVEP.TXT -o .../ALLVEP.OUTPUT.TXT`

Subsets of data are working correctly however when I run the full file 
I am getting the error:

> Argument "" isn't numeric in addition (+) at /data/.sys_dir/usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseCacheVariation.pm line 211, <__ANONIO__> line 62385.
> Argument "" isn't numeric in addition (+) at /data/.sys_dir/usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseCacheVariation.pm line 211, <__ANONIO__> line 63202.

Repeatedly until the file ends or I kill the process. Line 211 is in the sub get_frequency_data (marked as,  **$total_freq += $f;**, below):

  ```
  sub get_frequency_data {
    my $self = shift;
    my $vf = shift;

    my $freq_pop_full = uc($self->{freq_pop});
    $freq_pop_full =~ s/EXAC/ExAC/;
    my ($freq_group, $freq_pop) = split('_', $freq_pop_full);

    my $vf_strand = $vf->{strand} || 1;

    my %freq_data;

    foreach my $ex(@{$vf->{existing}}) {
      my $ex_strand = $ex->{strand} || 1;

      my %ex_alleles;
      foreach my $a(split('/', $ex->{allele_string})) {
        reverse_comp(\$a) unless $vf_strand == $ex_strand;
        $ex_alleles{$a} = 1;
    }

    my $total_freq = 0;

    # special case 1KG_ALL
    if($freq_pop_full eq '1KG_ALL' && defined($ex->{minor_allele_freq}) && defined($ex->{minor_allele})) {
      my $a = $ex->{minor_allele};
      my $f = $ex->{minor_allele_freq};

      reverse_comp(\$a) unless $vf_strand == $ex_strand;
      $freq_data{$a} = $f;

      # track total and delete observed alleles
      **$total_freq += $f;**
      delete($ex_alleles{$a});
    }
    # otherwise check match on first full pop name (e.g. ExAC_AMR, then last part e.g. AMR)
    elsif(my $tmp = ($ex->{$freq_pop_full} || $ex->{$freq_pop || ''})) {
      foreach my $a_f(split(',', $tmp)) {
        my ($a, $f) = split(':', $a_f);

        reverse_comp(\$a) unless $vf_strand == $ex_strand;
        $freq_data{$a} = $f;

        # track total and delete observed alleles
        $total_freq += $f;
        delete($ex_alleles{$a});
      }
    }
```

I've searched my file for what could be causing this and haven't found anything there or on google for this error. I was hoping this bug is something you've seen before and can point me in the right direction as to a solution.

**Comment by willmclaren** [comment]
We had an issue with an early release of our release/90 cache files that contained missing MAF data, it is possible this is the cause. The faulty caches were on our FTP site for around 2 weeks from 22nd of August; if you downloaded your cache in those dates, I'd recommend re-downloading the cache.

If the issue still persists, you can find which variant(s) are causing the issue by modifying the code you highlighted as follows:

```
  # special case 1KG_ALL
  if($freq_pop_full eq '1KG_ALL' && defined($ex->{minor_allele_freq}) && defined($ex->{minor_allele})) {
    my $a = $ex->{minor_allele};
    my $f = $ex->{minor_allele_freq};

    if(!$f && $f eq "") {
      use Data::Dumper;
      $Data::Dumper::Maxdepth = 3;
      $Data::Dumper::Indent = 1;
      print STDERR Dumper $vf;
      die;
    }

    reverse_comp(\$a) unless $vf_strand == $ex_strand;
    $freq_data{$a} = $f;

    # track total and delete observed alleles
    **$total_freq += $f;**
    delete($ex_alleles{$a});
  }
```

If you then share with us the printout from that with causal variant we can investigate further.

**Comment by shintzen** [comment]
Great! I will try this and get back to you!

**Comment by shintzen** [comment]
I have tried updating my cache and reinstalling VEP. What I have noticed is that if I install using INSTALL.pl and then don't use --dir_cache that I have no issue running my file. However, I cannot install it that way long term so I am still attempting to get --dir_cache to work. I added those lines to BaseCacheVariation.pm as you said, to help debug and this is the print out.

> ./vep 
--refseq 
--dir_cache cache_this/ 
--fasta .../Homo_sapiens_assembly19.fasta 
--cache 
--offline 
--force_overwrite 
--filter_common 
--everything 
--gene_phenotype 
--regulatory 
--hgvsg 
--protein 
-i ALL.VEP.TXT 
-o ALL.VEP.OUTPUT.TXT


```
2017-10-25 14:17:04 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this
$VAR1 = bless( {
  'existing' => [
    {
      'somatic' => 0,
      'gnomAD_NFE' => 'T:6.293e-05',
      'EA' => '',
      'failed' => 0,
      'gnomAD_ASJ' => 'T:0',
      'gnomAD_AFR' => 'T:0',
      'gnomAD_FIN' => 'T:0',
      'EAS' => '',
      'pubmed' => '',
      'gnomAD_EAS' => 'T:0',
      'AFR' => '',
      'EUR' => '',
      'gnomAD_OTH' => 'T:0',
      'AA' => '',
      'AMR' => '',
      'minor_allele_freq' => '',
      'SAS' => '',
      'strand' => 1,
      'gnomAD_SAS' => 'T:6.497e-05',
      'variation_name' => 'rs750379907',
      'phenotype_or_disease' => 0,
      'start' => 33482844,
      'clin_sig' => '',
      'end' => 33482844,
      'gnomAD' => 'T:3.663e-05',
      'allele_string' => 'C/T',
      'minor_allele' => '',
      'gnomAD_AMR' => 'T:0'
    }
  ],
  '_line' => [
    '19',
    '33482844',
    '33482844',
    'C/T',
    '.',
    '1159'
  ],
  'start' => 33482844,
  'end' => 33482844,
  'allele_string' => 'C/T',
  'map_weight' => 1,
  'strand' => 1,
  'adaptor' => bless( {
    'species' => 'homo_sapiens'
  }, 'Bio::EnsEMBL::Variation::DBSQL::VariationFeatureAdaptor' ),
  'variation_name' => '1159',
  'chr' => '19'
}, 'Bio::EnsEMBL::Variation::VariationFeature' );
Died at .../BaseCacheVariation.pm line 213, <__ANONIO__> line 125174.
```

**Comment by willmclaren** [comment]
I've managed to recreate your issue; fortunately the warning you are seeing is just that, a warning, and will have no detrimental effect on your VEP run other than printing that warning message many times!

I have a fix for it, but since it is not broken per se it will not go into the current release as a post-release fix.

There is a workaround you can use now which will also benefit you long-term - if you [tabix-convert your cache](http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#convert), the issue should not occur and you will see much faster performance overall too.

Regarding your issue with `--dir_cache`, can you be more specific with the difference between the commands and the issue?

**Comment by shintzen** [comment]
It was just a comment that I thought might help track down the issue. If I run:
`./vep --refseq --fasta .../Homo_sapiens_assembly19.fasta --cache --offline --force_overwrite --filter_common --everything --gene_phenotype --regulatory --hgvsg --protein -i ALL.VEP.TXT -o ALL.VEP.OUTPUT.TXT`
I don't have an issue. 
but running:
`./vep --refseq --dir_cache cache_this/ --fasta .../Homo_sapiens_assembly19.fasta --cache --offline --force_overwrite --filter_common --everything --gene_phenotype --regulatory --hgvsg --protein -i ALL.VEP.TXT -o ALL.VEP.OUTPUT.TXT`
is where I get the problem we've addressed above. I thought it was curious, as it seemed like using the cache installed by INSTALL.pl fixed the issue but I was unsure of how those two factors are related. 

Thank you for the suggestion for tabix and your help!
