### ISSUE TITLE
vep with custom gff3 returns 'substr outside of string at'

### ISSUE THREAD

**Issue by DafniG** [Ensembl/ensembl-vep#874]
I have supplemented the gencode.v26 gff3 protein-coding genes with new transcripts that I have found. I make sure that each transcript has a CDS and exons. I increase some gene co-ordinates if the new transcripts have boundaries greater than the ones in the GFF3. When I attempt to vep my VCF using the new gff3 file I get this error:
substr outside of string at /nfs/sw/ensembl-tools/ensembl-tools-100.3/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 855, <$fh> line 40001.
The error appears at different points for each chromosome, this is from chr22.

I assume it is a problem with the GFF3 file. I made sure not to use transcript_type and instead use biotype as pointed by another user. I sort, bgzip and tabix the file as you suggest:
`sort -k1,1 -k4,4n -k5,5n -t$'\t' new.gff3 > new_sorted.gff3`
`bgzip -c new_sorted.gff3 > new_sorted.gff3.gz`
`tabix -p gff new_sorted.gff3.gz`

I can provide a sample of the files via e-mail.
 
### System
Versions:
  ensembl              : 100.171092c
  ensembl-funcgen      : 100.f0c3948
  ensembl-io           : 100.f87ae4f
  ensembl-variation    : 100.b220ff4
  ensembl-vep          : 100.2
- Perl version: perl 5, version 32, subversion 0 (v5.32.0)
- OS: CentOS 7.6.1810
- tabix version: 1.1

### Full VEP command line
```
vep --gff new_sorted.gff3.gz --format "vcf" --phased --tab --compress_output bgzip --af --fasta Homo_sapiens_assembly38_noALT_noHLA_noDecoy.fasta --most_severe --input_file myVCF.vcf.gz --force_overwrite
```

### Full error message
substr outside of string at /nfs/sw/ensembl-tools/ensembl-tools-100.3/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 855, <$fh> line 40001.

**Comment by at7** [comment]
Hi,
could you please send me a sample of the files which reproduce the error message to our [helpdesk](https://www.ensembl.org/Help/Contact)? Our helpdesk team will forward the files to me and I will get back to you as soon as I know more.

Thank you,
Anja

**Comment by DafniG** [comment]
Hi Anja,
I seem to only be able to upload a single file on the helpdesk link you provided to me. Is there a specific address that I could use instead?
Best,
Dafni

**Comment by at7** [comment]
Hi Dafni,
could you please send the files to this address helpdesk [at] ensembl.org? The outreach team will then forward the files to me.

Thank you,
Anja

**Comment by at7** [comment]
Hi Dafni,
I was able to reproduce the error. The error is caused when VEP calculates the coding sequence for a transcript using the CDS and exon information. VEP cannot deal with a CDS element which covers several coding exons of the same transcript. The transcript model needs to provide a separate CDS element foreach coding exon. The [GFF specification](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md) illustrates that well. I realise that the example which is provided on the [VEP documentation page](http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff) doesn't make the distinction and we are looking into improving the gff example.

Best wishes,
Anja

**Comment by at7** [comment]
Hi Dafni,
I will close the issue for now. But please reopen it, if you have any more questions.
Best wishes,
Anja
