### ISSUE TITLE
Variants on scaffolds without entry in gff3 are removed from output

### ISSUE THREAD

**Issue by jd3234** [Ensembl/ensembl-vep#875]
I am trying to annotate a BCF with a custom gff3 but I am getting the `... not found in annotation sources of synonyms` error.  Variants on these scaffolds are not written in the output of VEP. The "problem" with the gff3 is, that some scaffolds have no gene annotation and hence there is no entry for the scaffold in the gff3. 
A workaround I found is to add a chromosome annotation in the gff3. But this seems cumbersome... Is there a paramater I can switch on to include variants that can not be annotated? I tried to add `--dont_skip` but that did not do the trick. 
If there is no parameter would it be possible to add a feature like that for the future?

### System
- VEP version: 100.2 
- VEP Cache version: -
- Perl version: 5.26
- OS: Ubuntu, CentOS
- tabix installed ? yes

### Full VEP command line
```
bcftools view in.bcf | vep --gff customgff.gff3.gz --fasta custom.fasta --format vcf --dont_skip --vcf -o annotated.vcf
```

### Full error message
> WARNING: Chromosome SEQ_1 not found in annotation sources or synonyms on line 1

**Comment by at7** [comment]
Hi,

using --dont_skip will still write variants, that for example fall on unrecognised sequences, into the output file.

Best wishes,
Anja

**Comment by jd3234** [comment]
Dear Anja,

thanks for your reply. Unfortunately using --dont_skip does not help. I also tried using a gtf but no success either. I also updated to version 101 but didn't help either.

**Comment by at7** [comment]
You are correct that you still get the warning message but the variant should be written into your output file. You could try to use [cache files](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache) as an additional annotation source. Could you please send me some of the scaffold names and I can check if the cache files contain them?
Thank you,
Anja

**Comment by jd3234** [comment]
Hi Anja,
but unfortunately the variants are not in the output. I can not use cache files as I am working with unpublished data.
I can send a test example if you can share an email address.
Best,
Janina

**Comment by at7** [comment]
Hi Janina,
it would help me to debug the problem if you could send some example data. Could you please send the files to this address helpdesk [at] ensembl.org and refer to vep-issue 875? Our outreach team will forward the files to me.
Thank you,
Anja

**Comment by at7** [comment]
Hi Janina,
I received the files and will get back to you when I know more.
Best wishes,
Anja

**Comment by at7** [comment]
Dear Janina,
we investigated further but are still not certain how the different results can be explained depending on the perl version used. I get the full output when I run under 

> perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-thread-multi-ld

but not under

> perl 5, version 26, subversion 1 (v5.26.1) built for darwin-2level

We have a proposed fix https://github.com/Ensembl/ensembl-vep/pull/881 which we sill need to review and test further. it is likely that we will only be able to provide a fix by the beginning of next year. I will keep you updated about any progress here.

Best wishes,
Anja

**Comment by at7** [comment]
Dear Janina,
we merged a bug fix for the issue that you have described. It will be available in our new Ensembl release 103 which we plan to release in February.

Best wishes,
Anja

**Comment by at7** [comment]
Our latest release 103 is now out. Please check that the updated code fixes the bug and let us know if the annotations are still missing after the code update.

Best wishes,
Anja

**Comment by jd3234** [comment]
Thanks Anja,
Will test it tomorrow!

**Comment by jd3234** [comment]
Hi Anja,

it's working now! Thanks for the fix!

Best,
Janina
