### ISSUE TITLE
--shift_hgvs does not seem to work

### ISSUE THREAD

**Issue by janrehker** [Ensembl/ensembl-vep#878]
Hello,

Added on https://github.com/Ensembl/ensembl-vep/issues/236?_pjax=%23js-repo-pjax-container as my issue is basically the same as the one reported in the closed thread. Sorry for spamming but I was not sure if anyone reads and reopens the closed threads.
It seems that the issue of vep ignoring the --shift_hgvs option is still around in later vep versions.

### System
- VEP version: 101 
- VEP Cache version: 101(?)
- Perl version: v5.26.2
- OS: CentOS8
- tabix installed yes

### Full VEP command line
vep -id '10 89711987 . CTA C' --offline --tab --hgvs --force_overwrite --dir Data/miniconda3/envs/vep2/.vep/ --assembly GRCh37 --refseq --fasta /home/rehkerj/Data/miniconda3/envs/vep2/.vep/homo_sapiens/101_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz --shift_hgvs 0 --symbol

### Full error message
2020-11-03 18:16:45 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this
2020-11-03 18:16:45 - INFO: --shift_hgvs has been set to zero, setting shift_3prime to 0

Output looks like this:
#Uploaded_variation     Location        Allele  Gene    Feature Feature_type    Consequence     cDNA_position   CDS_position    Protein_position        Amino_acids     Codons  Existing_variation      IMPACT  DISTANCE        STRAND  FLAGSSYMBOL   SYMBOL_SOURCE   HGNC_ID REFSEQ_MATCH    REFSEQ_OFFSET   GIVEN_REF       USED_REF        BAM_EDIT        HGVSc   HGVSp   HGVS_OFFSET
10_89711988_TA/-        10:89711988-89711989    -       5728    NM_000314.8     Transcript      frameshift_variant      1451-1452       606-607 202-203 TI/TX   acTAtt/actt     -       HIGH    -       1       -       PTEN    EntrezGene   -rseq_mrna_match -       TA      AT      -       NM_000314.8:c.607_608del        NP_000305.3:p.Ile203SerfsTer39  1
10_89711988_TA/-        10:89711988-89711989    -       5728    NM_001304717.5  Transcript      frameshift_variant      1450-1451       1125-1126       375-376 TI/TX   acTAtt/actt     -       HIGH    -       1       -       PTEN    EntrezGene    -       rseq_mrna_nonmatch,rseq_cds_mismatch    -       TA      AT      FAILED  NM_001304717.5:c.1126_1127del   NP_001291646.4:p.Ile376SerfsTer39       1
10_89711988_TA/-        10:89711988-89711989    -       5728    NM_001304718.2  Transcript      frameshift_variant      1564-1565       15-16   5-6     TI/TX   acTAtt/actt     -       HIGH    -       1       -       PTEN    EntrezGene   -rseq_mrna_nonmatch,rseq_5p_mismatch     -1      TA      AT      OK      NM_001304718.2:c.16_17del       NP_001291647.1:p.Ile6SerfsTer39 1

So I still get the offset of one while it should be zero. Maybe I'm holding it wrong...

Best regards,
Jan

**Comment by aparton** [comment]
Hi Jan,

I've taken a look into this issue this morning, and it seems to be a bug that occurs when the `--offline` flag is used in conjunction with `--shift_hgvs 0`.

I'll take a look at getting a fix in place, and I'll let you know when we have a timescale in mind. Thank you for bringing this issue to our attention.

Kind Regards,
Andrew

**Comment by janrehker** [comment]
Thanks a bunch for digging into it.

Jan

**Comment by aparton** [comment]
Hi,

We've been able to identify the problem and a fix will be in place for Ensembl 103, currently scheduled for release at the end of January.

Kind Regards,
Andrew

**Comment by janrehker** [comment]
Hi Andrew,

That is nice to hear! Will check back then. 

Happy Holidays!
Jan

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew
