### ISSUE TITLE
All SNPs are annotated as intergenic_variant

### ISSUE THREAD

**Issue by onebeingmay** [Ensembl/ensembl-vep#879]
Hi VEP team,
I am trying to use VEP to annotate a custom VCF file with a custom GTF file using local human genome fasta file. In the VEP summary html all my vairants were annotated as intergenic_variant (there are SNPs I know for sure on CDS). I am wondering if my VCF and GTF file format are correct as they are created myself. Here are the first few lines of my GTF file:
```
chr1	master_genepred.txt	exon	564442	564813	.	+	.	gene_id "ENST00000416931.1_1:chr1:+|8|372:260:311|noncoding|ACG"; transcript_id "ENST00000416931.1_1:chr1:+|8|372:260:311|noncoding|ACG"; exon_number "1"; exon_id "ENST00000416931.1_1:chr1:+|8|372:260:311|noncoding|ACG.1";
chr1	master_genepred.txt	transcript	564442	564813	.	+	.	gene_id "ENST00000416931.1_1:chr1:+|8|372:260:311|noncoding|ACG"; transcript_id "ENST00000416931.1_1:chr1:+|8|372:260:311|noncoding|ACG"; 
chr1	master_genepred.txt	CDS	564701	564748	.	+	0	gene_id "ENST00000416931.1_1:chr1:+|8|372:260:311|noncoding|ACG"; transcript_id "ENST00000416931.1_1:chr1:+|8|372:260:311|noncoding|ACG"; exon_number "1"; exon_id "ENST00000416931.1_1:chr1:+|8|372:260:311|noncoding|ACG.1";
chr1	master_genepred.txt	start_codon	564701	564703	.	+	0	gene_id "ENST00000416931.1_1:chr1:+|8|372:260:311|noncoding|ACG"; transcript_id "ENST00000416931.1_1:chr1:+|8|372:260:311|noncoding|ACG"; exon_number "1"; exon_id "ENST00000416931.1_1:chr1:+|8|372:260:311|noncoding|ACG.1";
chr1	master_genepred.txt	stop_codon	564749	564751	.	+	0	gene_id "ENST00000416931.1_1:chr1:+|8|372:260:311|noncoding|ACG"; transcript_id "ENST00000416931.1_1:chr1:+|8|372:260:311|noncoding|ACG"; exon_number "1"; exon_id "ENST00000416931.1_1:chr1:+|8|372:260:311|noncoding|ACG.1";
chr1	master_genepred.txt	exon	565020	566063	.	+	.	gene_id "ENST00000457540.1_1:chr1:+|11|1044:370:400|noncoding|CTG"; transcript_id "ENST00000457540.1_1:chr1:+|11|1044:370:400|noncoding|CTG"; exon_number "1"; exon_id "ENST00000457540.1_1:chr1:+|11|1044:370:400|noncoding|CTG.1";
chr1	master_genepred.txt	exon	565020	566063	.	+	.	gene_id "ENST00000457540.1_1:chr1:+|22|1044:760:946|noncoding|CTG"; transcript_id "ENST00000457540.1_1:chr1:+|22|1044:760:946|noncoding|CTG"; exon_number "1"; exon_id "ENST00000457540.1_1:chr1:+|22|1044:760:946|noncoding|CTG.1";
chr1	master_genepred.txt	exon	565020	566063	.	+	.	gene_id "ENST00000457540.1_1:chr1:+|23|1044:781:946|noncoding|TTG"; transcript_id "ENST00000457540.1_1:chr1:+|23|1044:781:946|noncoding|TTG"; exon_number "1"; exon_id "ENST00000457540.1_1:chr1:+|23|1044:781:946|noncoding|TTG.1";
chr1	master_genepred.txt	exon	565020	566063	.	+	.	gene_id "ENST00000457540.1_1:chr1:+|25|1044:880:946|noncoding|CTG"; transcript_id "ENST00000457540.1_1:chr1:+|25|1044:880:946|noncoding|CTG"; exon_number "1"; exon_id "ENST00000457540.1_1:chr1:+|25|1044:880:946|noncoding|CTG.1";
chr1	master_genepred.txt	exon	565020	566063	.	+	.	gene_id "ENST00000457540.1_1:chr1:+|9|1044:298:343|noncoding|ATG"; transcript_id "ENST00000457540.1_1:chr1:+|9|1044:298:343|noncoding|ATG"; exon_number "1"; exon_id "ENST00000457540.1_1:chr1:+|9|1044:298:343|noncoding|ATG.1";
```

And VCF file:
```
##fileformat=VCFv4.2
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr1	11048	NA	C	T	NA	NA	NA
chr1	11059	NA	G	A	NA	NA	NA
chr1	11068	NA	C	G	NA	NA	NA
chr1	11069	NA	G	C	NA	NA	NA
chr1	11086	NA	G	A	NA	NA	NA
chr1	11109	NA	A	G	NA	NA	NA
chr1	11113	NA	T	C	NA	NA	NA
chr1	11122	NA	G	A	NA	NA	NA
```
Sorry for the long post. Any suggestion would be really helpful!

### System
- VEP version: 101.0
- VEP Cache version: I didn't install cache
- Perl version: v5.16.3
- OS: Red Hat Enterprise Linux Server
- tabix installed

### Full VEP command line
```
vep=software/ensembl-vep/vep
$vep --fasta reference/GRCh37.primary_assembly.genome.fa \
 --gtf master_genepred.gtf.gz -i outgroup_info_new.vcf -o outgroup_info_annotation.txt
```

### Full error message Warnings
> Use of uninitialized value $key in substitution (s///) at software/ensembl-vep/Bio/EnsEMBL/IO/Parser/GTF.pm line 122, <__ANONIO__> line 5003.
> Use of uninitialized value $key in substitution (s///) at software/ensembl-vep/Bio/EnsEMBL/IO/Parser/GTF.pm line 123, <__ANONIO__Use of uninitialized value $key in hash element at software/ensembl-vep/Bio/EnsEMBL/IO/Parser/GTF.pm line 124, <__ANONIO__> line 5003.
>Use of uninitialized value $key in substitution (s///) at software/ensembl-vep/Bio/EnsEMBL/IO/Parser/GTF.pm line 122, <__ANONIO__> line 5003.

and a lot of similar warnings

**Comment by at7** [comment]
Hi,
I noticed a few things when checking your input files:

-- The GTF file is missing the gene entity
-- The transcript_biotype is missing
-- The variant positions don't overlap any of the coordinates in the GTF file
Could you please try updating the GTF file? You can take a look at the [GTF format description](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff) which is supported by VEP.

Please let me know if none of the updates fix the VEP annotations.
Thank you,
Anja

**Comment by onebeingmay** [comment]
Hi @at7 ,
Thank you for the prompt response. I tried fixing my GTF file by adding gene entity and transcript_biotype. I reran the program and still all SNPs were annotated as intergenic_variant. I also noticed warnings like this:
`WARNING: Parent entries with the following IDs were not found or skipped due to invalid types: Hum_TCONS_00008259:chr1:-|53|9903:1197:1485|noncoding|ATG, ENST00000471223.1_2:chr1:-|570|6089:5672:5777|noncoding|CTG, Hum_TCONS_00008263:chr1:-|53|10186:1197:1485|noncoding|ATG, ENST00000378230.8_3:chr1:-|4|6431:20:221|uORF|ATG `etc etc
I think VEP still can't recognized my GTF file. My current GTF file of the transcript mentioned above looks like:```

chr1	master_genepred.txt	gene	2971930	2985862	.	-	.	gene_id	"Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG";	gene_name	"Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG";
chr1	master_genepred.txt	transcript	2971930	2985862	.	-	.	gene_id	"Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG";	transcript_id	"Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG";	transcript_biotype	"protein_coding";
chr1	master_genepred.txt	exon	2971930	2976847	.	-	.	gene_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG"; transcript_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG"; exon_number "1"; exon_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG.1";
chr1	master_genepred.txt	exon	2977065	2977168	.	-	.	gene_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG"; transcript_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG"; exon_number "2"; exon_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG.2";
chr1	master_genepred.txt	exon	2977671	2980866	.	-	.	gene_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG"; transcript_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG"; exon_number "3"; exon_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG.3";
chr1	master_genepred.txt	exon	2983901	2984612	.	-	.	gene_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG"; transcript_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG"; exon_number "4"; exon_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG.4";
chr1	master_genepred.txt	CDS	2984209	2984493	.	-	0	gene_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG"; transcript_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG"; exon_number "4"; exon_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG.4";
chr1	master_genepred.txt	exon	2984786	2985862	.	-	.	gene_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG"; transcript_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG"; exon_number "5"; exon_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG.5";
chr1	master_genepred.txt	start_codon	2984491	2984493	.	-	0	gene_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG"; transcript_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG"; exon_number "4"; exon_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG.4";
chr1	master_genepred.txt	stop_codon	2984206	2984208	.	-	0	gene_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG"; transcript_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG"; exon_number "4"; exon_id "Hum_TCONS_00008262:chr1:-|53|10007:1197:1485|noncoding|ATG.4";


```
Transcript Hum_TCONS_00008259:chr1:-|53|9903:1197:1485|noncoding|ATG should be linked to gene by transcript_id. Do you have an idea what's still missing in my annotation?

**Comment by at7** [comment]
Hi @onebeingmay,
I will take a look now and get back to you when I know more about why the variants are only annotated as intergenic_variant.

Best wishes,
Anja

**Comment by at7** [comment]
Hi @onebeingmay,
I think I spotted the problem with your GTF file: Your transcript_id needs to be different from the gene_id. We describe the GTF format which is supported by VEP in the [GFF/GTF file section](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff) of our documentation.
Secondly, the variant coordinates don't overlap the transcript coordinates. I added this variant to the input file: chr1  2984509 NA  G A NA  NA  NA. And after updating the GTF input with a different id for the transcript I get this as a result: chr1  2984509 NA  G A NA  NA  NA;CSQ=A|5_prime_UTR_variant|MODIFIER||||||-1||||annotation.gtf.gz|

Please let me know if you have any more questions.

Best wishes,
Anja

**Comment by onebeingmay** [comment]
Hi Anja @at7 ,
Thank you for the response. I renamed the gene_id and the sorted and bgzipped GTF looks like this:
```
chr1	master_genepred.txt	exon	762973	763155	.	+	.	gene_id	"Gene_Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	transcript_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	exon_number	"1";	exon_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG.1";
chr1	master_genepred.txt	gene	762973	794902	.	+	.	gene_id	"Gene_Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	gene_name	"Gene_name_Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";
chr1	master_genepred.txt	transcript	762973	794902	.	+	.	gene_id	"Gene_Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	transcript_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	transcript_biotype	"protein_coding";
chr1	master_genepred.txt	exon	764383	764484	.	+	.	gene_id	"Gene_Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	transcript_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	exon_number	"2";	exon_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG.2";
chr1	master_genepred.txt	exon	776580	776753	.	+	.	gene_id	"Gene_Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	transcript_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	exon_number	"3";	exon_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG.3";
chr1	master_genepred.txt	CDS	776730	776753	.	+	0	gene_id	"Gene_Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	transcript_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	exon_number	"3";	exon_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG.3";
chr1	master_genepred.txt	start_codon	776730	776732	.	+	0	gene_id	"Gene_Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	transcript_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	exon_number	"3";	exon_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG.3";
chr1	master_genepred.txt	CDS	783034	783240	.	+	0	gene_id	"Gene_Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	transcript_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	exon_number	"4";	exon_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG.4";
chr1	master_genepred.txt	exon	783034	785731	.	+	.	gene_id	"Gene_Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	transcript_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	exon_number	"4";	exon_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG.4";
chr1	master_genepred.txt	stop_codon	783241	783243	.	+	0	gene_id	"Gene_Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	transcript_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	exon_number	"4";	exon_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG.4";
chr1	master_genepred.txt	exon	787307	788146	.	+	.	gene_id	"Gene_Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	transcript_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	exon_number	"5";	exon_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG.5";
chr1	master_genepred.txt	exon	788771	794902	.	+	.	gene_id	"Gene_Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	transcript_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	exon_number	"6";	exon_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG.6";
```
I input `SNP chr1	783080	NA	A	C	NA	NA	NA`, which is on the CDS `chr1	master_genepred.txt	CDS	783034	783240	.	+	0	gene_id	"Gene_Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	transcript_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG";	exon_number	"4";	exon_id	"Hum_TCONS_00000031:chr1:+|41|10129:436:670|noncoding|ATG.4";`
But still it was annotated as an intergenic_variant.
Am I modifying my GFT right? Or could you please share the updated GTF that was successfully used in your former post? Thank you!

**Comment by at7** [comment]
Hi,
It should work if your gene_id is different from your transcript_id which it is in your updated GTF file. I attach the GTF file with my modifications for you to use. I wonder if the spacing could be the issue. A GTF file has 9 columns which are separated by tab and the attributes in the 9th column must be only separated by a space. This is what I did for my test GTF file.
Let me know if you get annotations with my version of your GTF file.
Best wishes,
Anja
[Archive.zip](https://github.com/Ensembl/ensembl-vep/files/5520047/Archive.zip)

**Comment by onebeingmay** [comment]
Thank you Anja. I make sure attributes in the 9th column must be only separated by a space. Now the program works perfectly!
