### ISSUE TITLE
Chromosomes not found in reference

### ISSUE THREAD

**Issue by mikpom** [Ensembl/ensembl-vep#883]
## Describe the issue
Variants on **chrUn_KI270467v1** and **chrUn_KI270746v1** are skipped by VEP though these contigs can be found in `chr_synonyms.txt`

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 101
- VEP Cache version: 101
- Perl version: 5.26.1
- OS: Ubuntu 18.04
- tabix installed ? yes

### Full VEP command line
```
vep --force_overwrite --format vcf --offline --cache -i missing.vcf -o missing.annot.vepout --dir /storage1/mikpom/data/.vep101/ --fasta /storage1/mikpom/data/.vep101/homo_sapiens/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
```

### Full error message

```
WARNING: Chromosome chrUn_KI270467v1 not found in annotation sources or synonyms on line 1
WARNING: Chromosome chrUn_KI270746v1 not found in annotation sources or synonyms on line 2
```

### Data files (if applicable)
- The input file [missing.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/5535021/missing.vcf.gz)

**Comment by dglemos** [comment]
Hi @mikpom,
Thank you for reporting the issue. Both contigs are in `chr_synonyms.txt` however, the contigs data is missing from the cache. We'll have a look to understand why the data is missing and I will get back to you as soon as I know more. 

Best wishes,
Diana

**Comment by dglemos** [comment]
Hi again,
I had a look at your query and it's not an issue of missing data. These two contigs are not in the cache because they don't overlap any features (variants, transcripts, or regulatory features). The warning in the output is just a message that indicates there is no data for chrUn_KI270467v1 and chrUn_KI270746v1. The variants can be interpreted as intergenic. 
We understand the message is not very clear, that's why we are planning into improving it sometime in the future. 

Best wishes,
Diana

**Comment by mikpom** [comment]
The situtation about the variants on those contigs is clear now. 
Thanks Diana.

**Comment by dglemos** [comment]
Good to know it helped. I'm going to close this issue but feel free to create a new issue if you have more questions.
Best wishes,
Diana

**Comment by mikpom** [comment]
Your reply did clarify the situation, however it is not obvious that the issue is closed. Would it be better to still put such variants in output without gene features making their intergenic state explicit?

**Comment by dglemos** [comment]
We will improve the output at some point in the future. Either VEP writes a warning saying these contigs don't have any data or the variants will have the intergenic consequence. I'll keep the ticket open until we know what's the plan. Sorry for closing it so soon. 
Best wishes,
Diana

**Comment by olaaustine** [comment]
Hi @mikpom,
We have updated VEP to have the warning saying the contigs do not have data.
This change would reflect in future releases. 
Thank you for bringing this to our notice.
I will close this issue now. Please feel free to reopen or create another issue if you have more questions. 
Thank you, 
Ola
