### ISSUE TITLE
Custom VEP annotation using not only coordinates but also alt ref?

### ISSUE THREAD

**Issue by seunghun23** [Ensembl/ensembl-vep#884]
Hi I am trying to custom-annotate M-CAP scores, and the data file I downloaded from M-CAP website
has following 6 columns- 
#grch37_chrom 	pos     ref   alt 	 mcapv1.4 	mcap_sensitivityv1.4

From https://asia.ensembl.org/info/docs/tools/vep/script/vep_custom.html, 
I learned that I need to change this file into a BED format where the first three columns are 
chromosome,pos1,and pos2, and I did that, but different mcap scores are given to variants with 
a same coordinates but different alt alleles, so annotating variants only based on exact match of
genomic coordinates would be wrong. Is there a way to custom-annotate variants using 
not only genomic coordinates but also ALT (and REF) allele? 

### System
- VEP version: 101
- VEP Cache version: 101
- Perl version: NA
- OS: [e.g. MacOS, Ubuntu, CentOS]
- tabix installed Yes

**Comment by dglemos** [comment]
Hi @seunghun23,
The easiest way to add variant data is to use custom annotation with a VCF file, details [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html). 
VEP will add the data from the INFO field of your custom VCF to the VEP output. 

Best wishes,
Diana

**Comment by seunghun23** [comment]
Hi Diana, 

Thank you for the answer, but even when I choose to use a VCF file to do custom annotation,
it still doesn't solve my issue I wrote above. The link you gave me says "VCF : a format used to describe genomic variants. VEP will use the **3rd column of the file as the identifier.** INFO fields from records may be added to the VEP output." 
But what is the format of this identifier in the 3rd column? As I wrote, I want VEP to assign annotation based on genomic location and ALT allele of a variant. Can I make an identifier using those information? 

For example, a VCF file I want to use have following columns

#CHROM    POS        ID       REF      ALT     QUAL      FILTER     INFO 
1                  69096     .         G          A,T,C   .               .               SAP=1;exonic:0.016......

And all variants have value "." in the third column, "ID". I guess in this case VEP doesn't use this column as an identifier,
and I wonder whether I can make an identifier and put it in the third column using the values in POS and ALT 

-Seunghun

**Comment by dglemos** [comment]
Hi,
The 3rd column is just an identifier of the variant, it's not a mandatory field and it's not used to map the variants. You can use the input file you have the way it is (without the ID). 
If you want to assign annotation based on genomic location and ALT allele then you need to create a VCF file from the M-CAP scores and use it as a custom file, like the example below. 

Example of a variant in the input file:
```
##INFO=SAP,Number=1,Description="SAP">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       69091   .       A       T,G     .       .       SAP=1;exonic:0.016
```

Example of a custom VCF created from the original M-CAP file:
```
##INFO=MCap,Number=1,Description="mcapv1.4">
##INFO=MCapSensitivity,Number=1,Description="mcap_sensitivityv1.4">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	69091	.	A	T	.	.	MCap=0.007082;MCapSensitivity=0.99308
```

Running VEP with the custom VCF option, following the instructions [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html#custom_options):
`perl vep -i input_example.vcf --database --GRCh37 --port 3337 --custom custom_mcap.vcf.gz,mcap,vcf,exact,0,MCap,MCapSensitivity --vcf`

The output will have the M-CAP scores (notice that the score is only annexed to allele T):
```
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|SOURCE|mcap|mcap_MCap|mcap_MCapSensitivity">
##INFO=<ID=mcap,Number=.,Type=String,Description="custom_mcap.vcf.gz (exact)">
##INFO=<ID=mcap_MCap,Number=.,Type=String,Description="MCap field from custom_mcap.vcf.gz">
##INFO=<ID=mcap_MCapSensitivity,Number=.,Type=String,Description="MCapSensitivity field from custom_mcap.vcf.gz">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       69091   .       A       T,G     .       .       SAP=1;exonic:0.016;CSQ=T|start_lost|HIGH|OR4F5|ENSG00000186092|Transcript|ENST00000335137|protein_coding|1/1||||1|1|1|M/L|Atg/Ttg|||1||HGNC|14825||1:69091-69091|0.007082|0.99308,G|start_lost|HIGH|OR4F5|ENSG00000186092|Transcript|ENST00000335137|protein_coding|1/1||||1|1|1|M/V|Atg/Gtg|||1||HGNC|14825||||
```
Let me know if you have more questions.

**Comment by seunghun23** [comment]
This really helps! Thank you so much

**Comment by dglemos** [comment]
I'm glad to know it helps! I'm going to close this ticket but feel free to open a new one if you have more questions.
Best wishes,
Diana
