### ISSUE TITLE
Use of uninitialized value in subtraction (-)

### ISSUE THREAD

**Issue by LenkaSeg** [Ensembl/ensembl-vep#886]
## Describe the issue
When running VEP this message appears:

`Use of uninitialized value in subtraction (-) at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/TranscriptMapper.pm line 384, <__ANONIO__> line 1.`

The output is fine.

## Additional information
Happens only for the hgvs form of input: example: AKT1:Asp46Glu

There was some remotely similar issue here #636 
I tried everything mentioned there, including the upgrading the tabix, but it didn't help.

### System
- VEP version: 101, 100.3, 100.1, 98.3 (tried all these versions with their caches)
- VEP Cache version: 101, 100, 98
- Perl version: v5.26.1
- OS: ubuntu 18:04
- tabix installed yes, version 1.9

### Full VEP command line
```
vep -i input.tsv --force_overwrite -o STDOUT --tab --fields "Uploaded_variation,Location,Gene,Consequence,SYMBOL,ENSP,CANONICAL,Amino_acids,Protein_position,Feature,EXON,INTRON,Codons" --symbol --protein --numbers --canonical --no_stats --cache --fasta [path/to/Homo_sapiens.GRCh38.dna.toplevel.fa.gz] --dir_cache [path/to/cache]
```

### Full error message
```
Use of uninitialized value in subtraction (-) at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/TranscriptMapper.pm line 384, <__ANONIO__> line 1.
Use of uninitialized value in subtraction (-) at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/TranscriptMapper.pm line 385, <__ANONIO__> line 1.
```

### Data files (if applicable)
They include:
- The input file:
`AKT1:Asp46Glu`

**Comment by aparton** [comment]
Hi @LenkaSeg,

Thank you for this report. Unfortunately, we do not support HGVS in this format as it is missing a variant descriptor (i.e. `:p.`, `:g.` or `:c.`). Additionally, we do not recommend using gene symbols as the reference sequence, as this gives ambiguity for which transcript or translation is intended.

If you use the associated Ensembl protein identifier instead, and add the variant descriptor (e.g. ENSP00000270202.4:p.Asp46His), then VEP should annotate your variants correctly. As an aside, VEP will only be able to provide annotations with HGVSp input if there is an unambiguous way to change from reference to alternate amino acid at the genomic level.

Kind Regards,
Andrew

**Comment by LenkaSeg** [comment]
Oh, sorry, I made a mistake, the variant descriptor was actually part of the input.
example: ```AKT1:p.Asp46Glu```
Ok, I will use the protein identifier.
Thank you very much for your reply and help!

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew
