### ISSUE TITLE
Variant Recoder fails on specific HGVSp

### ISSUE THREAD

**Issue by xiechao-lucence** [Ensembl/ensembl-vep#888]
## Describe the issue
Variant Recoder fails with certin HGVSp, for example: http://rest.ensembl.org/variant_recoder/human/ENSP00000380860.3:p.D1010H
It complains that that "Sequence translated from reference (G -> ) does not match input sequence (D)", even though D is the correct amino acid at position 1010. 
The (G -> ) seems to be due to truncation at exon-exon boundary, and Variant Recoder failed to grab the complete codon for translation.

## Additional information
It works for the position both before and after this position:
http://rest.ensembl.org/variant_recoder/human/ENSP00000380860.3:p.E1009A
http://rest.ensembl.org/variant_recoder/human/ENSP00000380860.3:p.Q1011H

### System
- Variant Recoder web API (19th Nov 2020)

### Full VEP command line
```
http://rest.ensembl.org/variant_recoder/human/ENSP00000380860.3:p.D1010H
```

### Full error message
> error: "Unable to parse HGVS notation 'ENSP00000380860.3:p.D1010H':  : Sequence translated from reference (G -> ) does not match input sequence (D): Could not get a Transcript object for 'ENSP00000380860'"

**Comment by dglemos** [comment]
Hi @xiechao-lucence,
Thank you for reporting the issue. Unfortunately, variant recoder doesn't handle HGVS protein within two different exons. We are trying to find a solution to this problem but it's not a trivial fix. I'll let you know more once we know more. 
Best wishes,
Diana

**Comment by dglemos** [comment]
We have added a fix for VEP to support variants in multi-exons.
I'm going to close this issue but if you have more questions please feel free to open a new one.

Best wishes,
Diana
