### ISSUE TITLE
Way to use older version of VEP

### ISSUE THREAD

**Issue by seunghun23** [Ensembl/ensembl-vep#890]
Hi, 

I am using "ensemblorg/ensembl-vep" docker to run VEP and recently updated my Terra method for VEP and Cache v101.
Then, to run some old VEP plug-in, I tried to run VEP with cache v85 (GRch37), but it seems that the VEP docker installs latest VEP and the older cache wasn't compatible. Is there an easy way to run older version of VEP using the same docker?
or should I build a new docker installing specific version of VEP?

-Seunghun

**Comment by at7** [comment]
Hi,
the current github VEP repository only goes back to release 87. If you would like to update the dockerfile to work with version 85 you need to use a different repository: https://github.com/Ensembl/ensembl-tools/tree/release/85/scripts/variant_effect_predictor
Best wishes,
Anja

**Comment by at7** [comment]
Hello,
I will close the issue now. But please reopen it if you have any related questions.
Best wishes,
Anja
