### ISSUE TITLE
Are vep variant categories redundant?

### ISSUE THREAD

**Issue by madzayasodara** [Ensembl/ensembl-vep#891]
I've annotated some vcfs and noticed some variants are annotated using overlapping/redundant categories, for example:
```
intron_variant
intron_variant,non_coding_transcript_variant
```
or
```
missense_variant
missense_variant,splice_region_variant
missense_variant,stop_retained_variant
```

Is the same variant annotated multiple times?
If I count how many variants annotated `intron_variant `for  given gene, am I counting the total of intronic variants, or I should sum up the occurrence of anything annotated `intron_variant + intron_variant,non_coding_transcript_variant`, and so on to have that total?

**Comment by at7** [comment]
Hi,
could you please send me your VEP command? It is possible to choose options which allow you to summarise consequence annotations across all transcripts that overlap your variant. Taking a look at the command should hopefully help me to explain your results better.

Best wishes,
Anja

**Comment by madzayasodara** [comment]
Hi this is the command I used

vep -i vcf --gff ZFgenomic_tabixprep_nomiRNA.gff.gz --fasta ZFgenomic.fa -o vep.gz --fork 4 --symbol --tab --compress_output gzip --force_overwrite 

But I would prefer not to have to annotate it again, as it consumes a lot of time.
I comfortable with text processing.
No problem if the only way it's annotating again though.
thank you!

**Comment by at7** [comment]
Thank you for providing the command. I just wanted to make sure that you are not using --summary which outputs only a comma-separated list of all observed consequences per variant.

It is possible that you get different consequence annotations for the same variant. The consequence is calculated per overlapping transcript and if a variant overlaps several transcripts you can end up with different consequence annotations for each variant transcript pair.

For your question: "If I count how many variants annotated intron_variant for given gene, am I counting the total of intronic variants, or I should sum up the occurrence of anything annotated intron_variant + intron_variant,non_coding_transcript_variant"

-- if you count by gene you need to take into account that you have several transcripts for a gene
-- if you want to count all intron variants you need to count all occurrences of intron_variant including the ones from e.g. intron_variant,non_coding_transcript_variant

Best wishes,
Anja

**Comment by madzayasodara** [comment]
Hello Anja, thanks for the reply!
I manually filtered my annotations to only contain the longest transcript. So, yes I'm analyzing one transcript per gene. 
In this case, would the same variant be annotated with different terms, for example intron_variant  and intron_variant,non_coding_transcript_variant? Or different intronic variants will have non-overlapping labels, specific to them?
Thanks again,
-mdz

**Comment by at7** [comment]
I hope I understand you correctly but if you only annotate the longest transcript you should only get one annotation for your variant. The reason why you see for example intron_variant and intron_variant,non_coding_transcript_variant is that: if you only get intron_variant it means the the variant overlaps the intron region of a protein coding transcript. If you see intron_variant,non_coding_transcript_variant it means that the intron variant is overlapping a non-coding transcript. A variant can have more than one consequence if the criteria for the consequence annotation are fulfilled. We do explain all the different consequences [here](https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html).

**Comment by at7** [comment]
Hello,
I will close the issue now. But please reopen it if you have any related questions.
Best wishes,
Anja
