### ISSUE TITLE
VEP 102 cache is older then 101

### ISSUE THREAD

**Issue by Stikus** [Ensembl/ensembl-vep#892]
Hello, VEP team.
As we can see on FTP:

ftp://ftp.ensembl.org/pub/release-101/variation/indexed_vep_cache/
homo_sapiens_vep_101_GRCh37.tar.gz | 13.1 GB | 09.09.2020, 13:56:00
-- | -- | --
homo_sapiens_vep_101_GRCh38.tar.gz | 14.3 GB | 09.09.2020, 13:55:00

ftp://ftp.ensembl.org/pub/release-102/variation/indexed_vep_cache/
homo_sapiens_vep_102_GRCh37.tar.gz | 13.1 GB | 03.09.2020, 22:53:00
-- | -- | --
homo_sapiens_vep_102_GRCh38.tar.gz | 14.3 GB | 02.09.2020, 20:28:00

Is this correct?

**Comment by aparton** [comment]
Hi @Stikus,

Thanks for getting in touch. Yes, this is correct - we had an issue with missing RefSeq transcripts in 101 that we had to fix after release, so the 101 date is later than expected. 

If you have any further questions, please don't hesitate to ask.

Kind Regards,
Andrew

**Comment by Stikus** [comment]
Thank you for info, no more questions. Closing.
