### ISSUE TITLE
Cache problem for annotations on insertions

### ISSUE THREAD

**Issue by fescudie** [Ensembl/ensembl-vep#893]
## Describe the issue
Hi,

I worked with VEP release 94 and Human GRCh38 RefSeq cache and recently installed the release 101. When I compare results, insertions have missing annotations values: `existing variant` for dbSNP and populations AF (`gnomAD_AF`, ...). The concerned variants are known in dbSNP and gnomAD and the results are correct in VEP 94 and with online VEP.

As example, with VEP 94 the variant *17:42323632 G/GA* on human genome (GRCh38) corresponds to rs3830585 and allele frequencies are known in gnomAD:

    Allele|Existing_variation|AF|AFR_AF|AMR_AF|EAS_AF|EUR_AF|SAS_AF|AA_AF|EA_AF|gnomAD_AF|gnomAD_AFR_AF|gnomAD_AMR_AF|gnomAD_ASJ_AF|gnomAD_EAS_AF|gnomAD_FIN_AF|gnomAD_NFE_AF|gnomAD_OTH_AF|gnomAD_SAS_AF
    A|NM_003150.3|rs3830585|0.4020|0.7526|0.147|0.37|0.2048|0.3446|0.6672|0.193|0.2446|0.6903|0.1209|0.2816|0.3449|0.1974|0.1929|0.2259|0.3152

With VEP 101, these information are missing:

    Allele|Feature|Existing_variation|AF|AFR_AF|AMR_AF|EAS_AF|EUR_AF|SAS_AF|AA_AF|EA_AF|gnomAD_AF|gnomAD_AFR_AF|gnomAD_AMR_AF|gnomAD_ASJ_AF|gnomAD_EAS_AF|gnomAD_FIN_AF|gnomAD_NFE_AF|gnomAD_OTH_AF|gnomAD_SAS_AF|CLIN_SIG|SOMATIC|PHENO">
    A|NM_003150.4|COSV99065474||||||||||||||||||||||||

However, these information seem to be present in both caches but stored in two very distinct formats for position and allele:

    $ zcat homo_sapiens_refseq/101_GRCh38/*/*_var.gz | grep "rs3830585" -
    rs3830585   42323633 42323635 AAA/AAAA    benign 1  25741868,24033266,28415725 ClinVar::RCV000402556,VCV000165294,RCV000151933 AAAA:0.7526 AAAA:0.147 AAAA:0.37 AAAA:0.2048 AAAA:0.3446 AAAA:0.6672 AAAA:0.193 AAAA:0.246 AAAA:0.6879 AAAA:0.1225 AAAA:0.2823 AAAA:0.3459 AAAA:0.1966 AAAA:0.1928 AAAA:0.2289 AAAA:0.3153

    $ zcat homo_sapiens_refseq/94_GRCh38/*/*_var.gz | grep "rs3830585" -
    rs3830585   42323633 42323632 -/A/C  A 0.4020 benign 1 25741868,24033266 A:0.7526 A:0.147 A:0.37 A:0.2048 A:0.3446 A:0.6672 A:0.193 A:0.2446,C:4.885e-05 A:0.6903,C:0 A:0.1209,C:0 A:0.2816,C:0 A:0.3449,C:0 A:0.1974,C:0 A:0.1929,C:6.284e-05 A:0.2259,C:0 A:0.3152,C:0.0001626

Thanks in advance for your help in the fix of this problem.

#### Input VCF file

```
##fileformat=VCFv4.1
##INFO=<ID=SRC,Number=.,Type=String,Description="Variant callers where the variant is identified.">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT
17      42323632        .       G       GA      16388.4 PASS    SRC=mutect2     . 
```

##### Command line

    vep \
    --cache --dir_cache <path>/vep --offline \
    --species "homo_sapiens" --assembly GRCh38 --fasta <path>/Homo_sapiens.GRCh38.ensembl_v101.dna.toplevel.fa \
    --symbol \
    --refseq \
    --af --af_1kg --af_esp --af_gnomad \
    --no_stats --vcf --vcf_info_field ANN \
    --input_file test.vcf --output_file test_vep101.vcf

##### Result

    ##VEP="v101" time="2020-12-02 17:38:40" cache="<path>/vep/homo_sapiens_refseq/101_GRCh38" ensembl-funcgen=101.b918a49 ensembl-variation=101.50e7372 ensembl=101.856c8e8 ensembl-io=101.943b6c2 1000genomes="phase3" COSMIC="90" ClinVar="202003" ESP="V2-SSA137" HGMD-PUBLIC="20194" assembly="GRCh38.p13" dbSNP="153" gencode="GENCODE 35" genebuild="2014-07" gnomAD="r2.1" polyphen="2.2.2" refseq="2019-12-11 22:24:10 - GCF_000001405.39_GRCh38.p13_genomic.gff" regbuild="1.0" sift="sift5.2.2"
    ##INFO=<ID=ANN,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|REFSEQ_MATCH|REFSEQ_OFFSET|GIVEN_REF|USED_REF|BAM_EDIT|AF|AFR_AF|AMR_AF|EAS_AF|EUR_AF|SAS_AF|AA_AF|EA_AF|gnomAD_AF|gnomAD_AFR_AF|gnomAD_AMR_AF|gnomAD_ASJ_AF|gnomAD_EAS_AF|gnomAD_FIN_AF|gnomAD_NFE_AF|gnomAD_OTH_AF|gnomAD_SAS_AF|CLIN_SIG|SOMATIC|PHENO">
    #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT
    17      42323632        .       G       GA      16388.4 PASS    SRC=mutect2;ANN=A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_001369512.1|protein_coding||17/23||||||||COSV99065474||-1||EntrezGene|||||||||||||||||||||||||1|1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_001369513.1|protein_coding||17/23||||||||COSV99065474||-1||EntrezGene|||||||||||||||||||||||||1|1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_001369514.1|protein_coding||17/23||||||||COSV99065474||-1||EntrezGene|||||||||||||||||||||||||1|1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_001369516.1|protein_coding||17/23||||||||COSV99065474||-1||EntrezGene|||||||||||||||||||||||||1|1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_001369517.1|protein_coding||17/23||||||||COSV99065474||-1||EntrezGene|||||||||||||||||||||||||1|1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_001369518.1|protein_coding||17/23||||||||COSV99065474||-1||EntrezGene|||||||||||||||||||||||||1|1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_001369519.1|protein_coding||17/23||||||||COSV99065474||-1||EntrezGene|||||||||||||||||||||||||1|1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_001369520.1|protein_coding||17/23||||||||COSV99065474||-1||EntrezGene|||||||||||||||||||||||||1|1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_003150.4|protein_coding||17/23||||||||COSV99065474||-1||EntrezGene|||||||||||||||||||||||||1|1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_139276.2|protein_coding||17/23||||||||COSV99065474||-1||EntrezGene||||||OK|||||||||||||||||||1|1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_213662.2|protein_coding||17/23||||||||COSV99065474||-1||EntrezGene|||||||||||||||||||||||||1|1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|XM_017024973.2|protein_coding||17/23||||||||COSV99065474||-1||EntrezGene|||||||||||||||||||||||||1|1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|XM_024450896.1|protein_coding||16/22||||||||COSV99065474||-1||EntrezGene|||||||||||||||||||||||||1|1  .

##### Command line

    vep \
    --cache --dir_cache <path>/vep/vep_94.5 --offline \
    --species "homo_sapiens" --assembly GRCh38 --fasta <path>/Homo_sapiens.GRCh38.94.dna.fa \
    --symbol --refseq \
    --af --af_1kg --af_esp --af_gnomad \
    --no_stats --vcf --vcf_info_field ANN \
    --input_file test.vcf --output_file test_vep94.vcf

##### Result

    ##VEP="v94" time="2020-12-02 17:38:55" cache="<path>/vep/vep_94.5/homo_sapiens_refseq/94_GRCh38" ensembl-variation=94.066b102 ensembl=94.5c08d90 ensembl-io=94.8d53275 ensembl-funcgen=94.08b0c13 1000genomes="phase3" COSMIC="86" ClinVar="201807" ESP="V2-SSA137" HGMD-PUBLIC="20174" assembly="GRCh38.p12" dbSNP="151" gencode="GENCODE 29" genebuild="2014-07" gnomAD="170228" polyphen="2.2.2" refseq="2018-07-10 14:50:52 - GCF_000001405.38_GRCh38.p12_genomic.gff" regbuild="16" sift="sift5.2.2"
    ##INFO=<ID=ANN,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|REFSEQ_MATCH|GIVEN_REF|USED_REF|BAM_EDIT|AF|AFR_AF|AMR_AF|EAS_AF|EUR_AF|SAS_AF|AA_AF|EA_AF|gnomAD_AF|gnomAD_AFR_AF|gnomAD_AMR_AF|gnomAD_ASJ_AF|gnomAD_EAS_AF|gnomAD_FIN_AF|gnomAD_NFE_AF|gnomAD_OTH_AF|gnomAD_SAS_AF|CLIN_SIG|SOMATIC|PHENO">
    #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT
    17      42323632        .       G       GA      16388.4 PASS    SRC=mutect2;ANN=A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_003150.3|protein_coding||17/23||||||||rs3830585||-1||EntrezGene|||||OK|0.4020|0.7526|0.147|0.37|0.2048|0.3446|0.6672|0.193|0.2446|0.6903|0.1209|0.2816|0.3449|0.1974|0.1929|0.2259|0.3152|benign||1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_139276.2|protein_coding||17/23||||||||rs3830585||-1||EntrezGene|||||OK|0.4020|0.7526|0.147|0.37|0.2048|0.3446|0.6672|0.193|0.2446|0.6903|0.1209|0.2816|0.3449|0.1974|0.1929|0.2259|0.3152|benign||1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_213662.1|protein_coding||17/23||||||||rs3830585||-1||EntrezGene|||||OK|0.4020|0.7526|0.147|0.37|0.2048|0.3446|0.6672|0.193|0.2446|0.6903|0.1209|0.2816|0.3449|0.1974|0.1929|0.2259|0.3152|benign||1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|XM_005257616.4|protein_coding||17/23||||||||rs3830585||-1||EntrezGene||||||0.4020|0.7526|0.147|0.37|0.2048|0.3446|0.6672|0.193|0.2446|0.6903|0.1209|0.2816|0.3449|0.1974|0.1929|0.2259|0.3152|benign||1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|XM_005257617.3|protein_coding||17/23||||||||rs3830585||-1||EntrezGene||||||0.4020|0.7526|0.147|0.37|0.2048|0.3446|0.6672|0.193|0.2446|0.6903|0.1209|0.2816|0.3449|0.1974|0.1929|0.2259|0.3152|benign||1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|XM_011525145.3|protein_coding||17/23||||||||rs3830585||-1||EntrezGene||||||0.4020|0.7526|0.147|0.37|0.2048|0.3446|0.6672|0.193|0.2446|0.6903|0.1209|0.2816|0.3449|0.1974|0.1929|0.2259|0.3152|benign||1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|XM_011525146.3|protein_coding||17/23||||||||rs3830585||-1||EntrezGene||||||0.4020|0.7526|0.147|0.37|0.2048|0.3446|0.6672|0.193|0.2446|0.6903|0.1209|0.2816|0.3449|0.1974|0.1929|0.2259|0.3152|benign||1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|XM_017024972.1|protein_coding||17/23||||||||rs3830585||-1||EntrezGene||||||0.4020|0.7526|0.147|0.37|0.2048|0.3446|0.6672|0.193|0.2446|0.6903|0.1209|0.2816|0.3449|0.1974|0.1929|0.2259|0.3152|benign||1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|XM_017024973.2|protein_coding||17/23||||||||rs3830585||-1||EntrezGene||||||0.4020|0.7526|0.147|0.37|0.2048|0.3446|0.6672|0.193|0.2446|0.6903|0.1209|0.2816|0.3449|0.1974|0.1929|0.2259|0.3152|benign||1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|XM_017024974.1|protein_coding||17/23||||||||rs3830585||-1||EntrezGene||||||0.4020|0.7526|0.147|0.37|0.2048|0.3446|0.6672|0.193|0.2446|0.6903|0.1209|0.2816|0.3449|0.1974|0.1929|0.2259|0.3152|benign||1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|XM_017024975.1|protein_coding||17/23||||||||rs3830585||-1||EntrezGene||||||0.4020|0.7526|0.147|0.37|0.2048|0.3446|0.6672|0.193|0.2446|0.6903|0.1209|0.2816|0.3449|0.1974|0.1929|0.2259|0.3152|benign||1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|XM_017024976.1|protein_coding||17/23||||||||rs3830585||-1||EntrezGene||||||0.4020|0.7526|0.147|0.37|0.2048|0.3446|0.6672|0.193|0.2446|0.6903|0.1209|0.2816|0.3449|0.1974|0.1929|0.2259|0.3152|benign||1,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|XM_024450896.1|protein_coding||16/22||||||||rs3830585||-1||EntrezGene||||||0.4020|0.7526|0.147|0.37|0.2048|0.3446|0.6672|0.193|0.2446|0.6903|0.1209|0.2816|0.3449|0.1974|0.1929|0.2259|0.3152|benign||1       .

##### Command line equivalent

    ./vep --af --af_esp --af_gnomad --appris --biotype --buffer_size 500 --check_existing --distance 5000 --hgvs --mane --plugin CADD,[path_to]/CADD_GRCh38_1.6_whole_genome_SNVs.tsv.gz,[path_to]/CADD_GRCh38_1.6_InDels.tsv.gz --polyphen b --pubmed --refseq --regulatory --sift b --species homo_sapiens --symbol --transcript_version --tsl --cache --input_file [input_data] --output_file [output_file]

##### Result

    #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
    17	42323632	.	G	GA	.	.	CSQ=A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_001369512.1|protein_coding||17/23|NM_001369512.1:c.1601-8dup|||||||rs3830585||-1||EntrezGene||||||||||||||0.6672|0.193|0.246|0.6879|0.1225|0.2823|0.3459|0.1966|0.1928|0.2289|0.3153|benign||1|25741868&24033266&28415725||||||6.331|0.483447,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_001369513.1|protein_coding||17/23|NM_001369513.1:c.1601-8dup|||||||rs3830585||-1||EntrezGene||||||||||||||0.6672|0.193|0.246|0.6879|0.1225|0.2823|0.3459|0.1966|0.1928|0.2289|0.3153|benign||1|25741868&24033266&28415725||||||6.331|0.483447,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_001369514.1|protein_coding||17/23|NM_001369514.1:c.1601-8dup|||||||rs3830585||-1||EntrezGene||||||||||||||0.6672|0.193|0.246|0.6879|0.1225|0.2823|0.3459|0.1966|0.1928|0.2289|0.3153|benign||1|25741868&24033266&28415725||||||6.331|0.483447,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_001369516.1|protein_coding||17/23|NM_001369516.1:c.1601-8dup|||||||rs3830585||-1||EntrezGene||||||||||||||0.6672|0.193|0.246|0.6879|0.1225|0.2823|0.3459|0.1966|0.1928|0.2289|0.3153|benign||1|25741868&24033266&28415725||||||6.331|0.483447,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_001369517.1|protein_coding||17/23|NM_001369517.1:c.1601-8dup|||||||rs3830585||-1||EntrezGene||||||||||||||0.6672|0.193|0.246|0.6879|0.1225|0.2823|0.3459|0.1966|0.1928|0.2289|0.3153|benign||1|25741868&24033266&28415725||||||6.331|0.483447,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_001369518.1|protein_coding||17/23|NM_001369518.1:c.1601-8dup|||||||rs3830585||-1||EntrezGene||||||||||||||0.6672|0.193|0.246|0.6879|0.1225|0.2823|0.3459|0.1966|0.1928|0.2289|0.3153|benign||1|25741868&24033266&28415725||||||6.331|0.483447,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_001369519.1|protein_coding||17/23|NM_001369519.1:c.1601-8dup|||||||rs3830585||-1||EntrezGene||||||||||||||0.6672|0.193|0.246|0.6879|0.1225|0.2823|0.3459|0.1966|0.1928|0.2289|0.3153|benign||1|25741868&24033266&28415725||||||6.331|0.483447,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_001369520.1|protein_coding||17/23|NM_001369520.1:c.1601-8dup|||||||rs3830585||-1||EntrezGene||||||||||||||0.6672|0.193|0.246|0.6879|0.1225|0.2823|0.3459|0.1966|0.1928|0.2289|0.3153|benign||1|25741868&24033266&28415725||||||6.331|0.483447,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_003150.4|protein_coding||17/23|NM_003150.4:c.1601-8dup|||||||rs3830585||-1||EntrezGene||||||||||||||0.6672|0.193|0.246|0.6879|0.1225|0.2823|0.3459|0.1966|0.1928|0.2289|0.3153|benign||1|25741868&24033266&28415725||||||6.331|0.483447,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_139276.3|protein_coding||17/23|NM_139276.3:c.1601-8dup|||||||rs3830585||-1||EntrezGene||||||||||||||0.6672|0.193|0.246|0.6879|0.1225|0.2823|0.3459|0.1966|0.1928|0.2289|0.3153|benign||1|25741868&24033266&28415725||||||6.331|0.483447,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|NM_213662.2|protein_coding||17/23|NM_213662.2:c.1601-8dup|||||||rs3830585||-1||EntrezGene||||||||||||||0.6672|0.193|0.246|0.6879|0.1225|0.2823|0.3459|0.1966|0.1928|0.2289|0.3153|benign||1|25741868&24033266&28415725||||||6.331|0.483447,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|XM_017024973.2|protein_coding||17/23|XM_017024973.2:c.1601-8dup|||||||rs3830585||-1||EntrezGene||||||||||||||0.6672|0.193|0.246|0.6879|0.1225|0.2823|0.3459|0.1966|0.1928|0.2289|0.3153|benign||1|25741868&24033266&28415725||||||6.331|0.483447,A|splice_region_variant&intron_variant|LOW|STAT3|6774|Transcript|XM_024450896.1|protein_coding||16/22|XM_024450896.1:c.1697-8dup|||||||rs3830585||-1||EntrezGene||||||||||||||0.6672|0.193|0.246|0.6879|0.1225|0.2823|0.3459|0.1966|0.1928|0.2289|0.3153|benign||1|25741868&24033266&28415725||||||6.331|0.483447

#### VEP release 101

        conda install -c bioconda ensembl-vep

#### Cache release 101 from Ensembl FTP

        wget ftp://ftp.ensembl.org/pub/release-101/variation/vep/homo_sapiens_refseq_vep_101_GRCh38.tar.gz
        tar -xvf homo_sapiens_refseq_vep_101_GRCh38.tar.gz

**Comment by helensch** [comment]
Hi

Thank you for providing example data and the commands used to describe the issue you are having.
This has helped looking into this issue.

For e101 I have run the example variant provided with the e101 VEP indexed cache downloaded
from 
`ftp://ftp.ensembl.org/pub/release-101/variation/indexed_vep_cache/homo_sapiens_refseq_vep_101_GRCh38.tar.gz`

I am able to extract frequency data for 1000 Genomes and gnomAD.

From your command:
```
wget ftp://ftp.ensembl.org/pub/release-101/variation/vep/homo_sapiens_refseq_vep_101_GRCh38.tar.gz
tar -xvf homo_sapiens_refseq_vep_101_GRCh38.tar.gz
```

The cache you have downloaded is a non-indexed cache.

We recommend using the indexed cached for homo_sapiens
http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html

Please could you try using the e101 indexed cache.

Regards
Helen

**Comment by fescudie** [comment]
Hi,

Indeed, the indexed cache does not have this bug.

Thank you for your help.
