### ISSUE TITLE
Is the indexed cache the same thing as running convert_cache.pl?

### ISSUE THREAD

**Issue by anderspitman** [Ensembl/ensembl-vep#895]
Basically what the title says. If I download `ftp://ftp.ensembl.org/pub/release-102/variation/indexed_vep_cache/`, would that be the same as downloading `ftp://ftp.ensembl.org/pub/release-102/variation/vep/` and running `convert_cache.pl` on it?

**Comment by dglemos** [comment]
Hello,
The pre-indexed caches should be the same as downloading the cache and running the script `convert_cache.pl`. 
Diana

**Comment by anderspitman** [comment]
Excellent, thanks!
