### ISSUE TITLE
dbNSFP, length of MutationTaster_pred collection

### ISSUE THREAD

**Issue by olszewskip** [Ensembl/ensembl-vep#902]
## Describe the issue
The lengths of collections that are annotated by dbNSFP plugin to a single "vep-feature" are not equal. Specifically the collection requested by "MutationTaster_pred " flag is of different length than the collection requested by "Ensembl_transcriptid" (there is no analogous problem for other "*_pred" flags, e.g. "SIFT_pred")

## Additional information
Vep outputs annotations per transcript (or, generally, something called a "Feature" with "Feature type" often being "Transcript" in WES data); that is for each variant (row of a vcf) there may be between zero and many lines in vep's output file. (If --vcf flag is used those many annotations of a single variant are collected, delimited with `,` and put back in the corresponding row in a vcf.) Yet the dbNSFP annotations are not transcript-specific: instead each dbNSFP's output for a given transcript is itself a collection (formatted as a string delimited with & in my case). I expected all those collections (for a single transcript) to be of the same length, such that their subsequent elements can be meaningfully zipped together. This is not the case when the "MutationTaster_pred" collection is requested which can be both longer or shorter than e.g. the "Ensembl_transcriptid" collection.

### System
I'm running vep from docker without full knowledge about the system there.
The image is `konradjk/vep95_loftee:0.2`. Running `vep` in this container gives me
```
Versions:
  ensembl              : 95.4f83453
  ensembl-funcgen      : 95.94439f4
  ensembl-io           : 95.bd1a78d
  ensembl-variation    : 95.858de3e
  ensembl-vep          : 95.1
```
and running `perl --version`, I get
`This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi`.
Name of the `dbNSFP` data that I have in `/my/other/path` is `dbNSFP4.0a.gz`

### Full VEP command line
```
docker run --rm \
   -v /my/path:/species
   -v /my/other/path:/bulky_db \
   -v $PWD:/io
   konradjk/vep95_loftee:0.2 vep \
   -i /io/my/vcf/blocked/gzipped \
   -o /io/out.vcf \
   --offline \
   --cache \
   --dir_cache /species \
   --cache_version 101 \
   --species homo_sapiens \
   --fork 12 \
   --vcf \
   --dir_plugins /opt/vep/Plugins \
   --plugin dbNSFP,/bulky_db/dbNSFP4.0a.gz,Ensembl_transcriptid,MutationTaster_pred
```

### Full error message
There are no error messages

### Data files (if applicable)
I don't think the issue is specific to my particular input.
An example of a variant where the problem occurs is:
* contig=chr1, position=69428, reference_genome=GRCh38, ref='T', alt='G', rsid=rs140739101

This gets two vep-annotations, one for each transcript: 'ENST00000335137', 'ENST00000641515' (both of gene 'ENSG00000186092'). Each of those two annotations has identical dbNSFP-originating fields:
`ensembl_transcriptid=['ENST00000641515', 'ENST00000335137'], vep_canonical=['.', 'YES'], sift_pred=['.', 'D'], polyphen_hdiv_pred=['.', 'D'], polyphen_hvar_pred=['.', 'D'], mutation_taster_pred=['N']`.
So, in this case the `mutation_taster_pred` collection is shorter than `ensembl_transcriptid`. While most often I see it being of the same length, in a substantial number of cases it is shorter or longer.

**Comment by dglemos** [comment]
Hi @olszewskip,
For specific questions about the output scores, I advise you to ask the authors of Mutation Taster. They will explain more accurately the meaning of each output value and why do some variants have more than one prediction/model. 
But looking at your example, MutationTaster seems to have a prediction value for each model. This particular variant only has one model `MutationTaster_model=simple_aae` (e.g. leads to the substitution of a single amino acid) and as a consequence only one prediction `MutationTaster_pred=N` (polymorphism).

**Comment by olszewskip** [comment]
Thanks so much for answering @dglemos!
I would hate to stretch Your patience, but I don't fully follow Your answer, I'm embarrassed to admit. Was my assumption - that predictions from MutationTaster should be in one-to-one correspondence with Ensembl-transcript-ids annotated by dbNSFP - wrong? Does it mean that even if the number of those predictions and of the transcripts do happen to much, I shouldn't assume that the subsequent values in `MutationTaster_pred` are specific to the corresponding transcripts in `Ensembl_transcriptid`? Does it then mean that I shouldn't assume the same about eg. `SIFT_pred`? To stick with my example, do I understand incorrectly that:
'ENST00000641515' was annotated by dbNSFP with: `vep_canonical='.'`, `sift_pred='.'`, `polyphen_hdiv_pred='.'`, `polyphen_hvar_pred='.'`, wheras 'ENST00000335137' was annotated with: `vep_canonical='YES'`, `sift_pred='D'`, `polyphen_hdiv_pred='D'`, `polyphen_hvar_pred='D'`? If the collection fom MutationTaster were, say, `['N', 'D']`, I would assume that it was 'ENST00000641515', that is annotated with `N`, and 'ENST00000335137' with `D`; would that be incorrect too?

**Comment by dglemos** [comment]
SIFT has multiple scores corresponding to the different Ensembl transcript ids and amino acid positions, so it makes more sense to assume there's a one-to-one correspondence with the transcript IDs. However, Mutation Taster is different and we can't make the same assumption. [Here](http://www.mutationtaster.org/info/documentation.html) is the Mutation Taster documentation where it's explained the classifier used for the prediction scores. 
Also, you should be aware that these scores are retrieved from a tabix-indexed dbNSFP file. The transcript sequences referred in dbNSFP may be out of sync with those in the latest release of Ensembl which could lead to some discrepancies.

**Comment by dglemos** [comment]
I'm closing this issue for now. If you have any more questions please feel free to open a new ticket.

Best wishes,
Diana
