### ISSUE TITLE
Problems with cache files

### ISSUE THREAD

**Issue by Martaprf** [Ensembl/ensembl-vep#903]
I am installing the vep and I can not install cache files, I get the followed message:
Do you want to install any cache files (y/n)? y
 - getting list of available cache files
ERROR: Could not connect to FTP host ftp.ensembl.org
Connection timed out

Someone can help solving this issue.

Tanks

**Comment by ertanyilmaz38** [comment]
I have the same problem

**Comment by ima23** [comment]
Hi @Martaprf , @ertanyilmaz38 ,

Yesterday there was an issue with ensembl.org which likely affected ftp.ensembl.org too. Could you try again please and let me know if it's still an error? ftp.ensembl.org should work now.

Thank you,
Irina

**Comment by ertanyilmaz38** [comment]
> Hi @Martaprf , @ertanyilmaz38 ,
> 
> Yesterday there was an issue with ensembl.org which likely affected ftp.ensembl.org too. Could you try again please and let me know if it's still an error? ftp.ensembl.org should work now.
> 
> Thank you,
> Irina

I am trying again but get same error

`The VEP can either connect to remote or local databases, or use local cache files.
Using local cache files is the fastest and most efficient way to run the VEP
Cache files will be stored in /home/detagen/.vep
Do you want to install any cache files (y/n)? y
 - getting list of available cache files
ERROR: Could not connect to FTP host ftp.ensembl.org
Connection timed out
`

**Comment by ima23** [comment]
Hi @ertanyilmaz38 ,

Are you looking for a specific cache? Can you please try the direct link to a cache and let me know what message you get?
http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache
For human e102 GRCh38 would be: `curl -O ftp://ftp.ensembl.org/pub/release-102/variation/indexed_vep_cache/homo_sapiens_vep_102_GRCh38.tar.gz`.

Thanks,
Irina

**Comment by ertanyilmaz38** [comment]
my using ensembl vep version is : 102
ı runned command: ./vep
ı getting output is:
#----------------------------------#
# ENSEMBL VARIANT EFFECT PREDICTOR #
#----------------------------------#

Versions:
  ensembl              : 102.347f9ed
  ensembl-funcgen      : 102.6bd93a0
  ensembl-io           : 102.ff1cf96
  ensembl-variation    : 102.2716d2e
  ensembl-vep          : 102.0

Help: dev@ensembl.org , helpdesk@ensembl.org
Twitter: @ensembl

http://www.ensembl.org/info/docs/tools/vep/script/index.html

Usage:
./vep [--cache|--offline|--database] [arguments]

Basic options
=============

--help                 Display this message and quit

-i | --input_file      Input file
-o | --output_file     Output file
--force_overwrite      Force overwriting of output file
--species [species]    Species to use [default: "human"]
                       
--everything           Shortcut switch to turn on commonly used options. See web
                       documentation for details [default: off]                       
--fork [num_forks]     Use forking to improve script runtime

For full option documentation see:
http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html

but i not get cache files

**Comment by Martaprf** [comment]
I try again install da catch file and I get the same error:
The VEP can either connect to remote or local databases, or use local cache files.
Using local cache files is the fastest and most efficient way to run the VEP
Cache files will be stored in /home/mferreira/.vep
Do you want to install any cache files (y/n)? y
 - getting list of available cache files
ERROR: Could not connect to FTP host ftp.ensembl.org
Connection timed out

And when I try with the other solution (curl -O ftp://ftp.ensembl.org/pub/release-102/variation/indexed_vep_cache/homo_sapiens_vep_102_GRCh38.tar.gz) I get this other error:
curl: (28) Failed to connect to ftp.ensembl.org port 21: Connection timed out

Thanks for helping me solve this problem

**Comment by ima23** [comment]
Thanks @ertanyilmaz38,  @Martaprf, for checking. What environment are you running this in? I wonder if this is a firewall issue setup that prevents the connection to be established.

**Comment by Martaprf** [comment]
I am using a ubuntu server of my institution, maybe they block this.

**Comment by ertanyilmaz38** [comment]
i am using a ubuntu (18.04.5 LTS) and my institution using a firewall but i am configured firewall not blocking this ftp link. i trying access link with google chrome web browser and this succesfull but not accesing with bash (perl INSTALL.pl).

**Comment by Martaprf** [comment]
Hi,
I spoke with the people that administrate the server and they tell that it is because our firewall doesn´t allow FTP servers only HTTP, there are some manner to access by HTTP?

Thanks

**Comment by ima23** [comment]
Thanks for checking @Martaprf, @ertanyilmaz38 , as it is an institution server I would suggest you contact the systems administrators as it looks like the connection is not allowed via scripts or curl. They will be able to confirm this and let you know if such connections will be allowed in the future.

It's good news that the cache is available via google chrome browser. Can you download it manually via the browser ?

**Comment by ertanyilmaz38** [comment]
I can download it with the browser, but why can't I access a link that I can access with the browser with the curl command, if the firewall is blocking it, it should block all of them.

**Comment by ima23** [comment]
@ertanyilmaz38 , different security permissions can be set for different tools/access points. It is a lot more dangerous to allow tools to fetch files without control than allowing users to access files via browser.

**Comment by ertanyilmaz38** [comment]
I am understand. thank you your solvation

**Comment by ima23** [comment]
I am closing this issue now. If you have any related questions please feel free to reopen it.

Kind regards,
Irina
