### ISSUE TITLE
REVEL plugin is not outputting numeric score

### ISSUE THREAD

**Issue by sagitaninta** [Ensembl/ensembl-vep#905]
I am trying to call REVEL score for "bos_taurus" with a bed input from coding sequence like this.

```
vep -i chr.10_T_cds.bed --offline --cache --dir_cache .. --plugin REVEL,new_tabbed_revel.tsv.gz --flag_pick --sift b --species "bos_taurus" --force_overwrite --tab -o chr.10_T_vepREVEL.txt --fields "Location,Allele,Consequence,REVEL,Amino_acids,PICK"
```

vep runs perfectly and the output got out nicely. What I don't understand is why the field for REVEL score is filled with capital letters instead of numeric scores? It is neither the ref or alt amino acid symbol:

```
#Location     Allele   Consequence          REVEL Amino_acids  PICK
10:1170268      T       missense_variant        N       L/I     -
10:1170268      T       missense_variant        N       L/I     -
10:1170268      T       missense_variant        N       L/I     -
10:1170268      T       missense_variant        N       L/I     -
10:1170268      T       missense_variant        N       L/I     -
10:1170268      T       missense_variant        N       L/I     1
10:6504268      T       missense_variant        F       F/Y     1
10:6504308      T       missense_variant        F       V/I     1
10:12056032     T       missense_variant        S       P/T     1
10:12056038     T       missense_variant        E       E/K     1

```

I have downloaded the REVEL score and treated it as mentioned [in the documentation](https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html#plugins_how). My input, `chr.10_T_cds.bed` file looks like this:
```
10      296293  296293  A/T
10      296294  296294  A/T
10      296295  296295  A/T
10      296296  296296  C/T
10      296297  296297  A/T
10      296298  296298  C/T
10      296299  296299  C/T
10      296300  296300  C/T
10      296301  296301  T/T
10      296302  296302  C/T
```
I have been using release 102.

Any help is appreciated!

**Comment by ima23** [comment]
Hi @sagitaninta,

REVEL data is provided only for homo sapiens GRCh38 or GRCh37 assemblies. I can only assume that in this context coordinates from `bos taurus` are matched by chance to human genomic coordinates and data retrieved. In any case this will not lead to meaningful data. We will improve our documentation in the plugin to highlight it is available only for homo sapiens.

Kind regards,
Irina

**Comment by sagitaninta** [comment]
Thanks for the clarification! So I suppose none of the plugins are available for non-human species?

**Comment by ima23** [comment]
There are plugins available for non-human species, this information is either in the plugin documentation or at the external source of the data that are being used. 

For example the REVEL plugin uses the scores provided by https://sites.google.com/site/revelgenomics/downloads and they only provide scores for GRCh38 and GRCh37 which are human assemblies.

One example of plugin that is available for non-human species would be the Conservation plugin. It's best to check that the species you are interested is supported by the plugin you are interested in.

**Comment by olaaustine** [comment]
Hi, 
I'm going to close this issue now.
If you have any further questions, please feel free to reopen it or create a new issue.
Thanks,
Ola
