### ISSUE TITLE
Vep returns a tsv file with just a header

### ISSUE THREAD

**Issue by iab-bioinformatics** [Ensembl/ensembl-vep#906]
## Describe the issue
Running the command given below I see a tsv file with just a header and html file with 0 variants processed (the output is attached).
## Additional information
* vcf contains 59 CNVs
* vcf file was generated by Illumina TSO500 app
* vcf is readable by bcftools
* vcf contains header with ##fileformat=VCFv4.1

### System
- VEP version: 100.4
- VEP Cache version: 100
- Perl version: 5.26
- OS: CentOS
- tabix installed yes

### Full VEP command line
```
#!/usr/bin/bash
reference=/staging/tso500/TSO500_RUO_LocalApp/resources/genomes/hg19_hardPAR/genome.fa
vep=/mnt/lun00/databases/vep/homo_sapiens_refseq_GRCh37

for i in $(ls *.vcf);
do

vep --offline -quiet --cache_version 100 --assembly GRCh37 --dir $vep --refseq --fasta $reference -i $i -e -pick --force_overwrite -o ${i%.vcf}.tsv --numbers --hgvs --mane --af_gnomad --clin_sig_allele 0 --tab --gene_phenotype --check_existing
done
```

### Full error message
I have a warning but it doesnt influence the output from other vcf I am annotating.
Possible precedence issue with control flow operator at /home/ondra/anaconda3/envs/vep_env/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.

### Data files (if applicable)
They include:
- The input vcf file - SAMPLE_DNA_CopyNumberVariants.vcf
- The output html file -  SAMPLE_DNA_CopyNumberVariants.tsv_summary.html
- The output TSV file -  SAMPLE_DNA_CopyNumberVariants.tsv

[SAMPLE_DNA_CopyNumberVariants.zip](https://github.com/Ensembl/ensembl-vep/files/5714946/SAMPLE_DNA_CopyNumberVariants.zip)

**Comment by ima23** [comment]
Hi @iab-bioinformatics, 

Thank you for the description and examples, we are looking into it and will get back to you as soon as possible.

Kind regards,
Irina

**Comment by aparton** [comment]
Hi @iab-bioinformatics,

Thank you for your query. VEP does not support deletions in VCF format with a `.` as the alternate allele. According to the VCFv4.1 specification, alternate alleles are required to be A,C,G,T or N - https://samtools.github.io/hts-specs/VCFv4.1.pdf

So for example, the first variant in your file: 
`'1    40356095        .       C       . `
will work if it is rewritten as:
`'1    40356094        .       TC       T`

Currently, VEP is recognising these variants as invalid and skipping them.

Kind Regards,
Andrew

**Comment by iab-bioinformatics** [comment]
Thanks! It worked.
