### ISSUE TITLE
Problems with VEP from scratch (solved)

### ISSUE THREAD

**Issue by evissima** [Ensembl/ensembl-vep#908]
I installed VEP from scratch. When I figured out the command I needed to run, a very ambiguous error message appeared. I thought it was something about my computer but thanks to a friend we figured out a way to solve it. I think it's an issue but it can be avoided in a very unpredictable way, at least for me. I post it here just in case someone finds themselves in the same situation, or for the developers to consider including it in the FAQ section.

- VEP version: 102
- VEP Cache version: 102
- Perl version: 5.30 for x86_64
- OS: Ubuntu 20.04.1 LTS
- Tabix installed.

```
./vep \
-i ./mock001.SNP_INDEL.recalibrated_decomposed.vcf \
--offline \
--cache \
--dir_cache ~/.vep \
--assembly GRCh37 \
--fasta ~/.vep/homo_sapiens/102_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz \
--force_overwrite \
-o ~/mock001_decomp_annotated_VEP.txt
```
> [E::fai_build3_core] Cannot index files compressed with gzip, please use bgzip
 Segmentation fault (core dumped)

Both error messages disappeared when I **decompressed the FASTA file (.../Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz)**.

Hope this helps someone.

**Comment by dglemos** [comment]
Hi @evissima,
VEP should be able to run with compressed FASTA files. Here you can find some documentation about how to use FASTA files: https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#fasta 
Can you download the file from [here](http://ftp.ensembl.org/pub/grch37/release-102/fasta/homo_sapiens/dna/) and run VEP again with `--fasta ~/.vep/homo_sapiens/102_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz`?

**Comment by dglemos** [comment]
I'm going to close the ticket. If you have more questions feel free to open a new one.
Best wishes,
Diana

**Comment by yangyxt** [comment]
I'm a bit confused about these two options --fasta and --assembly. Is only one of them necessary? 
If I provide --fasta , then --assembly is not used? If yes, will this help improve performance ?

**Comment by nuno-agostinho** [comment]
Hello @yangyxt,

* `--fasta` allows to specify a FASTA file or a directory containing FASTA files to use to look up a reference sequence.
    * It is required if fetching HGVS annotations (`--hgvs`) or checking reference sequences (`--check_ref`) in offline mode (`--offline`).
    * It is optional with some performance increase in cache mode (`--cache`).
    * [More information on FASTA files](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#fasta).
* `--assembly` allows to select the assembly version (e.g. GRCh38 or GRCh37 for human). If using `--cache`, you must have the appropriate assembly's cache file installed. If not specified and you have only 1 assembly version installed, this will be chosen by default.

Please use the right FASTA file for the selected assembly. For instance,  if you select the GRCh38 assembly, you should use a FASTA file for GRCh38.

For more information on VEP arguments, please read https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html

Kind regards,
Nuno

**Comment by yangyxt** [comment]
> Hello @yangyxt,
> 
> * `--fasta` allows to specify a FASTA file or a directory containing FASTA files to use to look up a reference sequence.
>   
>   * It is required if fetching HGVS annotations (`--hgvs`) or checking reference sequences (`--check_ref`) in offline mode (`--offline`).
>   * It is optional with some performance increase in cache mode (`--cache`).
>   * [More information on FASTA files](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#fasta).
> * `--assembly` allows to select the assembly version (e.g. GRCh38 or GRCh37 for human). If using `--cache`, you must have the appropriate assembly's cache file installed. If not specified and you have only 1 assembly version installed, this will be chosen by default.
> 
> Please use the right FASTA file for the selected assembly. For instance, if you select the GRCh38 assembly, you should use a FASTA file for GRCh38.
> 
> For more information on VEP arguments, please read https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html
> 
> Kind regards, Nuno

Thanks for the reply. So I can basically understand that two arguments are used in different ways and I should provide them both when available.
