### ISSUE TITLE
adding ways to explicetly configure tbi

### ISSUE THREAD

**Issue by antonkulaga** [Ensembl/ensembl-vep#909]
In many places VEP requires tbi files for vcf-s but does not provide ways to specify them explicitly. This creates a lot of problems when running vep docker container with bionformatic workflow engines (i.e. Cromwell) as they handle input files separately (so VEP-s assumption that index tbi file will be in the same folder is always wrong there). It took me some time to figure out the workaround with symbolic links, however to avoid all those clutter it would be nice just to have additional parameters for the indexes, so when those files are not in the same folder the user will specify it.

**Comment by aparton** [comment]
Hi @antonkulaga,

Thank you for your suggestion. VEP uses tabix to process bgzipped VCF files, and unfortunately tabix does not support specifying the location of your index file, so this is not functionality that we can support.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew
