### ISSUE TITLE
Error in stats.pm

### ISSUE THREAD

**Issue by aadamk** [Ensembl/ensembl-vep#91]
I generate an error when running the following command on my somatic variants generated from an consensus calling method using Mutect2+Vardict from bcbio: 

./vep --assembly GRCh37 --vcf mel_case10.vcf --format vcf --output_file mel-case10-vep2 --cache --offline --symbol --plugin Downstream --plugin Wildtype --terms SO

There is an error related to the variant stats generated in my log file: 
Use of uninitialized value $_ in concatenation (.) or string at /gpfs/fs02/home/aadam/pVAC-Seq/ensembl-vep/modules/Bio/EnsEMBL/VEP/Stats.pm line 843.
Use of uninitialized value $_ in concatenation (.) or string at /gpfs/fs02/home/aadam/pVAC-Seq/ensembl-vep/modules/Bio/EnsEMBL/VEP/Stats.pm line 843.

Do you know why there is an error in printing variant stats?

**Comment by willmclaren** [comment]
It is just a warning, and will do no harm. There's already a [commit to fix it ](https://github.com/Ensembl/ensembl-vep/commit/d6fe1cb040430da05127ac2c0cb1bf7553b9cc40), but since it is not critical will appear in the next release.

**Comment by aadamk** [comment]
Thanks for the reply.  However, the annotation fails to complete - this is the only error generated in my log file.  I wind up with a nearly empty vcf as output from a ~130Mb input vcf.

**Comment by willmclaren** [comment]
The two are unlikely to be linked.

Are you able to share a snippet of your input file that recreates the issue?

**Comment by aadamk** [comment]
Yes, here you are.  
[mel_case5_snippet.txt](https://github.com/Ensembl/ensembl-vep/files/1428224/mel_case5_snippet.txt)

**Comment by aadamk** [comment]
And an example of one that ran without errors. I have the summary and warnings files for these as well if needed.
[mel_case-snippet.txt](https://github.com/Ensembl/ensembl-vep/files/1428258/mel_case-snippet.txt)

**Comment by willmclaren** [comment]
There's an error in the command you pasted; it looks like you've used `--vcf` when you should have used `--input_file`. [`--vcf`](http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_vcf) (on its own with no argument) indicates that VEP should write VCF output.

I believe your command should be:

`./vep --assembly GRCh37 --vcf --input_file mel_case10.vcf --format vcf --output_file mel-case10-vep2 --cache --offline --symbol --plugin Downstream --plugin Wildtype --terms SO`

If I run that with your sample file it works fine with no warnings or errors.

**Comment by aadamk** [comment]
Got it - thanks!
