### ISSUE TITLE
misconfiguration in ensemblorg/ensembl-vep:release_102.0 docker container when running haplo

### ISSUE THREAD

**Issue by antonkulaga** [Ensembl/ensembl-vep#910]
docker container in haplozaurus is totally misconfigured in terms of access! Whenever I try to do anything with it I get:
```
MSG: ERROR: Could not write to transcript coords file: Permission denied
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::tree_file /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:288
STACK Bio::EnsEMBL::VEP::AnnotationType::Transcript::populate_tree /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm:663
STACK Bio::EnsEMBL::VEP::TranscriptTree::new /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/TranscriptTree.pm:106
STACK Bio::EnsEMBL::VEP::Haplo::Runner::get_TranscriptTree /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Haplo/Runner.pm:400
STACK Bio::EnsEMBL::VEP::Haplo::Runner::get_InputBuffer /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Haplo/Runner.pm:374
STACK Bio::EnsEMBL::VEP::Haplo::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Haplo/Runner.pm:154
STACK Bio::EnsEMBL::VEP::Haplo::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Haplo/Runner.pm:196
STACK toplevel /opt/vep/src/ensembl-vep/haplo:100
Date (localtime)    = Wed Dec 30 20:59:02 2020
Ensembl API version = 102
```
I belive it is because it tries to write something to some temporary folder for which it does not have access Why do you make the container that hits itself in the foot each time? If you have a folder inside container which is temporary it should allow everything to be written there.

**Comment by aparton** [comment]
Hi @antonkulaga,

This is an issue that can occur depending on how your Docker bind mount is set up, and the permissions on the host machine. In some distributions (e.g. CentOS, Fedora, Red Hat Enterprise Linux) Docker daemon requires root privileges, which may cause read/write issues to the mounted volume.

One solution is to use the option `:Z` when specifying your bind mount (e.g. `sudo docker run -t -i -v $HOME/vep_data:/opt/vep/.vep:Z ensemblorg/ensembl-vep`), or alternatively you can change the read/write access of the mounted volume.

You can read more about Read/Write access within the Docker container here: https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker

Kind Regards,
Andrew

**Comment by antonkulaga** [comment]
@aparton my workaround was just to use a container that inherits from vep but is run under root user. The way I (and many other people) run the code is withing WDL and CWL pipelines, there mounting the docker container is done not manually but by the engine and .vep is usually not overriden by external volume, maybe if .vep will be chmod 777 by default inside the container will work fine by default.

**Comment by aparton** [comment]
Hi @antonkulaga,

Thank you for the suggestion. We don't do this by default to prevent users from accidentally tampering with cache files, leading to more complex subtle issues. In this situation we recommend that users update their permissions themselves.

I'm going to close this issue now, if you have any further questions, please feel free to reopen it, or create a new one.

Kind Regards,
Andrew
