### ISSUE TITLE
Possible precedence issue with control flow operator

### ISSUE THREAD

**Issue by kmegq** [Ensembl/ensembl-vep#914]
Hello,

I am getting a warning message saying:
"Possible precedence issue with control flow operator at (path)/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805." after installing ensembl-vep versions 101 and 102 in Conda.

I saw an earlier post about a similar issue but wasn't sure if it was the same, as it was with a different version. Is this warning affecting the output of the tool in any way? Is there a way to fix it?

Commands used for install:
conda create --no-default-packages python=3.6 --prefix (path to env)
source activate (path to env)
conda install ensembl-vep=102.0

Thank you for your help!

Best regards,
Kate

**Comment by dglemos** [comment]
Hi @kmegq,

How many versions of BioPerl you have installed and how did you install it? 
That seems to be just a warning message related to BioPerl and not an error.

**Comment by kmegq** [comment]
Dear Diana,

Thank you so much for your comment. BioPerl was installed as part of the bioconda ensembl-vep installation (See [here](https://bioconda.github.io/recipes/ensembl-vep/README.html)). The version is: perl-bioperl 1.7.2. 
The command used was: conda install ensembl-vep=101.0

I do not see any other installations, and am running the tool from within the conda environment where ensembl-vep was installed. There are some miniconda3 paths in my $PATH, although I don't find bioperl checking "Which bioperl? or Which perl-bioperl?

The conda environment started with no default packages.

Indeed, the tool does run, but I didn't know if the output could be adversely affected in any way - I don't have anything to compare the output to.

Best,
Kate

**Comment by dglemos** [comment]
It shouldn't interfere with the output. 
Can you print what is in $PATH and $PERL5LIB?

**Comment by kmegq** [comment]
Thank you Diana, I'm sorry for the delay. 

$PATH=/install_path/vep_99/bin:/home/unix/username/miniconda3/condabin:/seq/server/name/FireCloud/google-cloud-sdk/bin:/home/unix/username/miniconda3/bin:/home/unix/username/.local/bin:/home/unix/username/bin:/company/software/free/Linux/redhat_7_x86_64/pkgs/anaconda3_2020.07/bin:/company/uge/8.5.5/bin/lx-amd64:/company/software/free/Linux/redhat_7_x86_64/pkgs/samtools/samtools_1.8/bin:/company/software/free/Linux/redhat_7_x86_64/pkgs/plink_1.90b/bin:/home/unix/username/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/home/unix/username/miniconda3/bin

$PERL5LIB= blank

I consulted with a colleague who programs in Perl, and editing IndexedBase.pm line 805 to use the "||" rather than the "or" operator seems to fix the warning. Is this a reasonable solution?

Best,
Kate

**Comment by dglemos** [comment]
The change seems alright, but you should raise the issue with the BioPerl team to fix it. 
Best wishes,
Diana

**Comment by alanhoyle** [comment]
This issue has been raised by someone on the BioPerl repo:  https://github.com/bioperl/bioperl-live/issues/355

**Comment by dglemos** [comment]
As this issue is not specific to VEP I'm going to close it for now.

Best wishes,
Diana

**Comment by shawnyeager** [comment]
I just ran into this same error on Fedora 41 Workstation after installing stow via `sudo dnf install stow`.
