### ISSUE TITLE
Problem in the output of the variant annotation in SARS-COV-2

### ISSUE THREAD

**Issue by valemirici** [Ensembl/ensembl-vep#916]
Hello, I would like to know the reason why the same variant has two or more different consequences. 
Also, in some cases the same variant has a "gene id" different.
Could yuo explain it? Many thanks.
I have run VEP both from command line and web interface [https://covid-19.ensembl.org/Tools/VEP](url)

Kind Regards,
Valeria

**Comment by at7** [comment]
Dear Valeria,
it is possible that several consequence annotations apply to the same variant. [Here](https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html) is a list of all the different consequence annotation which we can assign. Sars-cov-2 has some overlapping genes which is good to see [here](https://covid-19.ensembl.org/Sars_cov_2/Location/View?r=MN908947.3:1-29903). If that doesn't explain your results could you please send me the list of consequences which you get as annotations for the same variant and also all the genes that you see annotated for the same variant? I would be happy to see your variant input as well if that is possible.

Best wishes,
Anja

**Comment by at7** [comment]
Dear Valeria,
I will close this issue, but please reopen it if you have any further questions.

Best wishes,
Anja
