### ISSUE TITLE
VEP doesn't copy headers from custom annotation files

### ISSUE THREAD

**Issue by mkohailan** [Ensembl/ensembl-vep#918]
Hi,

I am using `--custom` annotations with VEP. The run goes well but the headers that define the annotations are written by VEP, which refers to the field of the annotation in the source file (i.e. it does NOT explain what that annotation is). Here is an example:

**Source annotation file header:**

##INFO=<ID=AF_AFR,Number=A,Type=Float,Description="Allele Frequency among African/African American genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=AF_AMR,Number=A,Type=Float,Description="Allele Frequency among Admixed American genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=AF_ASJ,Number=A,Type=Float,Description="Allele Frequency among Ashkenazi Jewish genotypes, for each ALT allele, in the same order as listed">

**VEP output file header:**

##INFO=<ID=gnomAD,Number=.,Type=String,Description="database/GnomAD/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz (overlap)">
##INFO=<ID=gnomAD_AF_AFR,Number=.,Type=String,Description="AF_AFR field from database/GnomAD/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz">
##INFO=<ID=gnomAD_AF_AMR,Number=.,Type=String,Description="AF_AMR field from database/GnomAD/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz">
##INFO=<ID=gnomAD_AF_ASJ,Number=.,Type=String,Description="AF_ASJ field from database/GnomAD/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz">

Any solution for this?

**Comment by helensch** [comment]
Hi

Thank you for your query and providing the headers from the source annotation file and VEP output file.

The custom annotation adds a description using information from the custom annotation options.

https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html#custom_options

For your output the description includes the VCF field and source annotation filename.

This is similar to the output in the example of custom annotation for ClinVar:

https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html#custom_example

I will update the documentation to clarify the field descriptions that are used in the output of
custom annotations. 

I will discuss with the team about the inclusion of descriptions from custom annotation source VCF and get back to you.

Regards
Helen

**Comment by mkohailan** [comment]
Great. Thanks!

**Comment by jamie-m-a** [comment]
Thanks both - we will consider this for a future release, but it's relatively low priority so may take a while to implement. I'll close off this ticket now

**Comment by ainefairbrother** [comment]
Hi @mkohailan, @jethror1, 

Just to let you know that we've now implemented this fix. Let us know if this works for you or if you're still experiencing any issues. 

Best, 

@ainefairbrother
