### ISSUE TITLE
Vep does not find cache file

### ISSUE THREAD

**Issue by Kaskere** [Ensembl/ensembl-vep#920]
I downloaded cache in my /.vep folder, just as was written from manual
with curl -O ftp://ftp.ensembl.org/pub/release-102/variation/vep/homo_sapiens_vep_102_GRCh38.tar.gz 
 I have file homo_sapiens_vep_102_GRCh38.tar.gz in my /.vep directory right now
I qam not able to lauch vep and got the following issue:

-------------------- EXCEPTION -------------------- MSG: ERROR: Cache directory /mnt/home/baiba01/vep/homo_sapiens not found

STACK Bio::EnsEMBL::VEP::CacheDir::dir /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:311 STACK Bio::EnsEMBL::VEP::CacheDir::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:227 STACK Bio::EnsEMBL::VEP::CacheDir::new /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111 STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:115 STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91 STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170 STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:132 STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:203 STACK toplevel /opt/vep/src/ensembl-vep/vep:228 Date (localtime) = Thu Jan 28 13:16:06 2021 Ensembl API version = 101

When unzipping donwloaded file,
tar xzf homo_sapiens_vep_102_GRCh38.tar.gz
I got this
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

Is this a bug?

**Comment by aparton** [comment]
Hi @Kaskere,

Thank you for your query. There are a couple of things to check here:

- Have you unzipped the cache file? Unzipping and running again my fix your issue.
- We recommend using the cache file that matches with your version of VEP. While using the updated cache should work, then there may be unexpected issues.
- You can install cache files using our installer (INSTALL.pl), which can be found in the ensembl-vep folder. This should automatically configure your chosen cache file to work with VEP.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew
