### ISSUE TITLE
install failure

### ISSUE THREAD

**Issue by Huangdaosheng** [Ensembl/ensembl-vep#921]
## Describe the issue
$ perl INSTALL.pl
I got error below:
curl failed (000), trying to fetch using LWP::Simple
LWP::Simple failed (501), trying to fetch using HTTP::Tiny
ERROR: Failed last resort of using HTTP::Tiny to download https://raw.githubusercontent.com/Ensembl/ensembl-vep/release/102/modules/Bio/EnsEMBL/VEP/Constants.pm

### System
- VEP version: e.g. 102
- VEP Cache version:
-  Perl version: 5.30
- OS:  CentOS
- tabix installed ?no

### Full VEP command line
perl INSTALL.pl

### Full error message
> Including the warnings, if available

curl failed (000), trying to fetch using LWP::Simple
LWP::Simple failed (501), trying to fetch using HTTP::Tiny
ERROR: Failed last resort of using HTTP::Tiny to download https://raw.githubusercontent.com/Ensembl/ensembl-vep/release/102/modules/Bio/EnsEMBL/VEP/Constants.pm

**Comment by aparton** [comment]
Hi @Huangdaosheng,

Generally this error implies either a connectivity issue or a permissions issue. To investigate further, could you please run:

`curl -0 https://api.github.com/repos/Ensembl/ensembl-vep`

and let me know the results?

Kind Regards,
Andrew

**Comment by zhangshuo19920407** [comment]
Hi @aparton 
I got the same errors with that friends:
![image](https://user-images.githubusercontent.com/42530149/117936359-57a5f800-b337-11eb-9dcc-9c993f5a9292.png)

I run curl -0 https://api.github.com/repos/Ensembl/ensembl-vep, and this is the result:
![image](https://user-images.githubusercontent.com/42530149/117936975-0fd3a080-b338-11eb-8494-3f85eab0ecb1.png)
![image](https://user-images.githubusercontent.com/42530149/117937011-1eba5300-b338-11eb-962f-53229e533aeb.png)
![image](https://user-images.githubusercontent.com/42530149/117937131-3d204e80-b338-11eb-9bb1-862d9a8de68e.png)
![image](https://user-images.githubusercontent.com/42530149/117937216-51fce200-b338-11eb-97f7-06b5e76fba41.png)
![image](https://user-images.githubusercontent.com/42530149/117937305-680aa280-b338-11eb-837b-2f9c0615fc33.png)

**Comment by aparton** [comment]
Hi @zhangshuo19920407,

If you are able to use curl successfully on the command line, but are unable to with perl then I suspect it's a permissions issue. We've seen this before with perl installed in a conda environment, is this the case with your installation?

Additionally, could you please tell me which operating system and perl version you are using?

Kind Regards,
Andrew

**Comment by zhangshuo19920407** [comment]
Hi @aparton ,

Thanks for your reply! 
Perl I use was not installed in a conda environment. The operating system is Red Hat 4.8.3-9 and perl version is v5.16.3. 
If I run perl INSTALL.pl, I will get above error. But I successfully installed it running perl INSTALL.pl --AUTO ac -c ./ -n -s homo_sapiens_refseq,homo_sapiens_merged,homo_sapiens -y GRCh37  without any errors.

Sincerely,
Shuo Zhang

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew
