### ISSUE TITLE
VEP is not picking AF field in vcf in custom annotation

### ISSUE THREAD

**Issue by AisaacO** [Ensembl/ensembl-vep#922]
## Issue
I ran VEp with custom command. I expected a column called freq with the custom vcf AF values. This column is not showing up in the VEP result. I have all other columns. what could be the problem? Here is the column header from the result:
#Uploaded_variation     Location        Allele  Gene    Feature Feature_type    Consequence     cDNA_position   CDS_position    Protein_position        Amino_acids     Codons  Existing_variation      REF_ALLELE      IMPACT  DISTANCE        STRAND  FLAGS   PICK    VARIANT_CLASS   ENSP    SOURCE  DOMAINS

### System
- VEP version: 100 
- VEP Cache version: Not used
- Perl version: v5.26.1
- OS: Ubuntu
- tabix installed ? Yes

### Full VEP command line
```
./vep -i input.vcf.gz --fasta ref.fasta --gff gene.gff.gz --fork 4 --custom input.vcf.gz,freq,vcf,exact,0,AF --variant_class --coding_only --tab --no_check_alleles --show_ref_allele --force_overwrite --total_length flag_pick_allele_gene --pick_order canonical,rank,tsl,appris,ccds --domains --protein --no_stats --buffer_size 500
```

### Full error message
> No errors but the output does not contain the allele frequency information from custom annotation using custom vcf

**Comment by ima23** [comment]
Hi @AisaacO, 

Can you please share an example of the input.vcf.gz to replicate your issue? Having an example will also help confirm the presence of `AF` in your input file.

Thanks,
Irina

**Comment by AisaacO** [comment]
Hi Irina,
I have AF in my vcf. Here is a line from the vcf:
chr3    219     .       G       C       .       .       NS=1051;AN=3200;AF=0.51256;AC=2250;AC_Het=2630;AC_Hom=10;GT:RC:AC:GP:DS  0/1:2:7:2e-7,0.344998,5.218e-05:1.05532
I am not sure if you want a full sample but this line confirms the presence of AF in the vcf

Thank you

**Comment by ima23** [comment]
Hi @AisaacO, 

thanks for confirming that AF is present in the file. For me to replicate I would need to have small example data that I can run through your command. We can do a few checks first though.
Can you please run `./vep -i input.vcf.gz --custom input.vcf.gz,freq,vcf,exact,0,AF` and let me know what the output header is and one output line?
Just to confirm does `tabix input.vcf.gz chr3:219-219` retrieve the expected line?
I had another look at your command above `flag_pick_allele_gene` should be `--flag_pick_allele_gene`, this might be just a typo.

Thanks,
Irina

**Comment by AisaacO** [comment]
Hi Irina,
Indeed that was a typo. I carefully evaluated the command and found its an issue with how I was running VEP. I wrote a little fix (nothing to do with VEP). The fix is working. Closing this issue.

Thank you

**Comment by AisaacO** [comment]
I found and fixed the issue. It has nothing to do with vep
