### ISSUE TITLE
SV gene annotation: does VEP include genes within a certain distance? 

### ISSUE THREAD

**Issue by cagaser** [Ensembl/ensembl-vep#923]
Hello, 

I have annotated SV events with VEP. 
However, there are inconsistencies when it's viewed in IGV. 
Makes me wonder if VEP also include genes that are in closest distance. 
Take for example the following:

chr1_39532580 was annotated with gene PPIEL and BMP8A, but in IGV only PPIEL overlaps.
![Screenshot 2021-02-01 at 21 35 33](https://user-images.githubusercontent.com/47602860/106755444-6ee59300-662e-11eb-85be-dab982329a8f.png)

Similary, chr11_65874640 was annotated with gene CTSW and EFEMP2, but there are no overlaps at all. 
![Screenshot 2021-02-01 at 21 47 29](https://user-images.githubusercontent.com/47602860/106755511-815fcc80-662e-11eb-9241-0765cfca0e2c.png)

**Comment by ima23** [comment]
Hi @cagaser, 

I can check this for you. Can you share one SV examples formatted as in your input, a VEP command that replicates the issue and the used VEP version? I presume the species is homo_sapiens, is this GRCh38 or GRCh37?

Thanks,
Irina

**Comment by cagaser** [comment]
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=chr1,length=248956422>
##contig=<ID=chr11,length=135086622>
##ALT=<ID=DEL,Description="Deletion">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
chr1    39532580        chr1_39532580   G       <DEL>   1324    PASS    .       GT      ./.
chr11   65874640        chr11_65874640  N       <DEL>   3988    PASS    .       GT      0/1

**Comment by cagaser** [comment]
Hello, Is there any update regarding this question?

**Comment by ima23** [comment]
Hi @cagaser ,

apologies for the delay and thank you for the input example.
The format is not the expected format for structural variants, INFO field should contain `SVTYPE=...` see the examples here in the data formats section for [ VCF - structural variants](https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#sv ) .

Without the expected SV format, the run will result in the variants being skipped and the following warning message being displayed  `WARNING: VCF line on line x looks incomplete, skipping: ..`  and no variant being annotated. I ran e102 VEP to confirm that these 2 variants in the format sent are skipped and not annotated. 

Can you double check please what format the annotated variants were in and share an example that got annotated by VEP?  Can you tell me also what VEP version you used?

Thanks,
Irina

**Comment by cagaser** [comment]
Hi ima23, 

Thank you for looking in to this. I will have a quick and will get back to you. 
However, I just wanted confirm if VEP indeed includes nearby genes (within certain distance) when annotating. Is this a default behavior of VEP?

**Comment by ima23** [comment]
Hi @cagaser,

Yes, by default VEP annotates the genes within a 5000bp upstream and downstream of the variant, this distance can be modified using `--distance` option see [VEP Output options](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#output) section.
Going back to your variant starting at 39532580 it is 2711bp away from BMP8A [ENSG00000183682] (http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000183682;r=1:39491636-39529869;t=ENST00000331593) and this is why it gets annotated.

Kind regards,
Irina

**Comment by ima23** [comment]
I am closing this issue now. If you have any related questions please feel free to reopen it.

Kind regards,
Irina
