### ISSUE TITLE
No documentation for custom VCF FILTER field

### ISSUE THREAD

**Issue by davmlaw** [Ensembl/ensembl-vep#927]
Hi, thanks for VEP, it's great!

There's currently an undocumented feature - with custom VCFs, you can pass "FILTER" to get the VCF FILTER column

The current documentation only mentions INFO fields

https://asia.ensembl.org/info/docs/tools/vep/script/vep_custom.html

**Comment by aparton** [comment]
Hi @davmlaw,

Thanks for letting us know. We'll get those updated.

Kind Regards,
Andrew

**Comment by nakib103** [comment]
Thank you for reporting this. This information will be available in Ensembl release e107 docs.
