### ISSUE TITLE
Problem with DBD::mysql installation

### ISSUE THREAD

**Issue by Joya97** [Ensembl/ensembl-vep#928]
I have tried many times to install mysql on my Mac using the, but every time it gives me an error and I do not know how to solve it.

joy@Air-di-Joy ensembl-vep % cpan DBD::mysql                                      
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/Users/joy/.cpan/Metadata'
  Database was generated on Sun, 14 Feb 2021 17:55:47 GMT
Running install for module 'DBD::mysql'
Checksum for /Users/joy/.cpan/sources/authors/id/D/DV/DVEEDEN/DBD-mysql-4.050.tar.gz ok
Configuring D/DV/DVEEDEN/DBD-mysql-4.050.tar.gz with Makefile.PL

PLEASE NOTE:

For 'make test' to run properly, you must ensure that the
database user 'root' can connect to your MySQL server
and has the proper privileges that these tests require such
as 'drop table', 'create table', 'drop procedure', 'create procedure'
as well as others.

mysql> grant all privileges on test.* to 'root'@'localhost' identified by 's3kr1t';

You can also optionally set the user to run 'make test' with:

perl Makefile.PL --testuser=username

I will use the following settings for compiling and testing:

  cflags        (mysql_config) = -I/usr/local/Cellar/mysql/8.0.23/include/mysql
  embedded      (guessed     ) = 
  ldflags       (guessed     ) = 
  libs          (mysql_config) = -L/usr/local/Cellar/mysql/8.0.23/lib -lmysqlclient
  mysql_config  (guessed     ) = mysql_config
  nocatchstderr (default     ) = 0
  nofoundrows   (default     ) = 0
  nossl         (default     ) = 0
  testdb        (default     ) = test
  testhost      (default     ) = 
  testpassword  (default     ) = 
  testport      (default     ) = 
  testsocket    (default     ) = 
  testuser      (guessed     ) = root

To change these settings, see 'perl Makefile.PL --help' and
'perldoc DBD::mysql::INSTALL'.

Checking if libs are available for compiling...
Looks good.

Checking if your kit is complete...
Looks good
Using DBI 1.643 (for perl 5.028002 on darwin-thread-multi-2level) installed in /System/Library/Perl/Extras/5.28/darwin-thread-multi-2level/auto/DBI/
Generating a Unix-style Makefile
Writing Makefile for DBD::mysql
Writing MYMETA.yml and MYMETA.json
  DVEEDEN/DBD-mysql-4.050.tar.gz
  /usr/bin/perl Makefile.PL -- OK
Running make for D/DV/DVEEDEN/DBD-mysql-4.050.tar.gz
cp lib/DBD/mysql/GetInfo.pm blib/lib/DBD/mysql/GetInfo.pm
cp lib/DBD/mysql/INSTALL.pod blib/lib/DBD/mysql/INSTALL.pod
cp lib/Bundle/DBD/mysql.pm blib/lib/Bundle/DBD/mysql.pm
cp lib/DBD/mysql.pm blib/lib/DBD/mysql.pm
Running Mkbootstrap for mysql ()
chmod 644 "mysql.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- mysql.bs blib/arch/auto/DBD/mysql/mysql.bs 644
cc -c  -I/System/Library/Perl/Extras/5.28/darwin-thread-multi-2level/auto/DBI -I/usr/local/Cellar/mysql/8.0.23/include/mysql -DDBD_MYSQL_WITH_SSL -g  -g -pipe -fno-strict-aliasing -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -Wno-error=implicit-function-declaration -Os   -DVERSION=\"4.050\" -DXS_VERSION=\"4.050\"  -iwithsysroot "/System/Library/Perl/5.28/darwin-thread-multi-2level/CORE"   dbdimp.c
In file included from dbdimp.c:15:
./dbdimp.h:20:10: fatal error: 'DBIXS.h' file not found
#include <DBIXS.h>  /* installed by the DBI module                        */
         ^~~~~~~~~
1 error generated.
make: *** [dbdimp.o] Error 1
  DVEEDEN/DBD-mysql-4.050.tar.gz
  /usr/bin/make -- NOT OK

**Comment by at7** [comment]
Hello,
we have documentation for installing VEP dependencies on Mac [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#macos). We also have a docker image and documentation on how to run VEP in docker [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker).

Best wishes,
Anja

**Comment by yangyxt** [comment]
> Hello, we have documentation for installing VEP dependencies on Mac [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#macos). We also have a docker image and documentation on how to run VEP in docker [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker).
> 
> Best wishes, Anja

Hi, Thank you for the info here. May I ask whether you would consider offering a VEP running in singularity ?

**Comment by nakib103** [comment]
Hello @yangyxt ,

You can already run VEP on singularity. Here is a blogpost on how to do that - 
https://www.ensembl.info/2021/05/24/cool-stuff-the-vep-can-do-singularity/ 

Best regards,
Nakib
