### ISSUE TITLE
Fails to build HTSLIB 

### ISSUE THREAD

**Issue by veioenza** [Ensembl/ensembl-vep#930]
## Describe the issue
Clean installation failure

### System
- VEP version: 103.0
Perl v5.26.1
RHELS 6.10

Build version as mentioned in Isssue 733.
perl -MModule::Build -le 'print $Module::Build::VERSION'
0.4224

### Installation method
cd /local/software/ensembl-vep/source/
curl -L -O https://github.com/Ensembl/ensembl-vep/archive/release/103.0.zip
mkdir ../103.0
cd ../103.0
unzip ../source/103.0.zip
mv ensembl-vep-release-103.0 vep
cd vep

wget http://www.cpan.org/authors/id/P/PH/PHRED/Archive-Zip-1.68.tar.gz
cpanm -l /local/software/ensembl-vep/103.0 Archive-Zip-1.68.tar.gz
cpanm -l /local/software/ensembl-vep/103.0 DBI
cpanm -l /local/software/ensembl-vep/103.0 DBD::mysql
cpanm -l /local/software/ensembl-vep/103.0 Try::Tiny
cpanm -l /local/software/ensembl-vep/103.0 Bio::DB:HTS library

cd htslib/
git submodule update --init --recursive
cd ..

export PERL5LIB=/local/software/ensembl-vep/103.0/lib/perl5
perl INSTALL.pl

cd htslib/
git submodule update --init --recursive
cd ..

perl INSTALL.pl

### Full error message
 - building HTSLIB in ./htslib
In /home/local/software/ensembl-vep/103.0/vep/htslib
make: Nothing to be done for `all'.
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.11 - moving files to ./biodbhts
 - making Bio::DB:HTS
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.11'
Building Bio-DB-HTS
cc -I/home/local/software/ensembl-vep/103.0/vep/htslib -I/local/software/perl/5.26.1/lib/5.26.1/x86_64-linux/CORE -DVERSION="2.11" -DXS_VERSION="2.11" -fPIC -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wno-unused-result -c -fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -o lib/Bio/DB/HTS.o lib/Bio/DB/HTS.c
lib/Bio/DB/HTS.xs:80: error: redefinition of typedef 'Bio__DB__HTS__VCFfile'
lib/Bio/DB/HTS.xs:72: note: previous declaration of 'Bio__DB__HTS__VCFfile' was here
lib/Bio/DB/HTS.xs: In function 'XS_Bio__DB__HTS__VCF__Header_fmt_text':
lib/Bio/DB/HTS.xs:1770: warning: 'bcf_hdr_fmt_text' is deprecated (declared at /home/local/software/ensembl-vep/103.0/vep/htslib/htslib/vcf.h:570)
At top level:
cc1: warning: unrecognized command line option "-Wno-unused-result"
error building lib/Bio/DB/HTS.o from 'lib/Bio/DB/HTS.c' at /local/software/perl/5.26.1/lib/5.26.1/ExtUtils/CBuilder/Base.pm line 174.
ERROR: Shared Bio::DB:HTS library not found

**Comment by at7** [comment]
Hello,
have you set the DYLD_LIBRARY_PATH variable? You should have been asked during the VEP installation instructions to set the DYLD_LIBRARY_PATH variable to the htslib folder, which I think in your case should be /home/local/software/ensembl-vep/103.0/vep/htslib.

Kind regards,
Anja

**Comment by veioenza** [comment]
This is on Linux not Mac. Switched to GCC 6.1 (default on RHELS 6.10 is 4.4.7) and pre-downloaded htslib v1.11. VEP then built with only one failed test. Seems fine to me.

```
#   Failed test 'get_slice - fasta_db'
#   at ./t/BaseVEP.t line 131.
#     Structures begin differing at:
#          $got->{coord_system}{alias_to} = Does not exist
#     $expected->{coord_system}{alias_to} = undef
```
The workaround build is,

```
cd /local/software/ensembl-vep/source/
curl -L -O https://github.com/Ensembl/ensembl-vep/archive/release/103.0.zip
mkdir ../103.0
cd ../103.0
unzip ../source/103.0.zip
mv ensembl-vep-release-103.0 vep
cd vep

Intergrate htslib v1.11 into vep, by default it will just pull from the github head which doesn't integrate well.
wget https://github.com/samtools/htslib/archive/1.11.tar.gz
tar -xf 1.11.tar.gz
mv htslib-1.11 htslib

wget http://www.cpan.org/authors/id/P/PH/PHRED/Archive-Zip-1.68.tar.gz
cpanm -l /local/software/ensembl-vep/103.0 Archive-Zip-1.68.tar.gz
cpanm -l /local/software/ensembl-vep/103.0 DBI
cpanm -l /local/software/ensembl-vep/103.0 DBD::mysql
cpanm -l /local/software/ensembl-vep/103.0 Try::Tiny

export PERL5LIB=/local/software/ensembl-vep/103.0/lib/perl5

perl INSTALL.pl
```

**Comment by at7** [comment]
I'm glad to hear that you were able to fix the installation. Thank you for sending us your instructions. We will reviewing switching to htslib-1.11 in our installation script.
It is safe to ignore the failed test. Unfortunately, we missed updating the test before creating the new VEP release. We will create a new subversion 103.1 with the updated test shortly.
Thank you for your feedback,
Anja
