### ISSUE TITLE
Gwava plugin again

### ISSUE THREAD

**Issue by ariza-droid** [Ensembl/ensembl-vep#931]
## Describe the issue
Similar to Gwava plugin #242 issue reported previously. plugin installation critical error.

### System
- VEP version: 103
- Perl version: 5.26.1
- OS: Ubuntu

### Full VEP command line
```
sudo perl INSTALL.pl

```
### Full error message
> - installing "Gwava"
LWP::Simple failed (404), trying to fetch using HTTP::Tiny
Use of uninitialized value in numeric eq (==) at /usr/local/share/perl/5.26.1/HTTP/Tiny.pm line 615.
Use of uninitialized value in numeric eq (==) at /usr/local/share/perl/5.26.1/HTTP/Tiny.pm line 615.
ERROR: Failed last resort of using HTTP::Tiny to download ftp://ftp.sanger.ac.uk:21/pub/resources/software/gwava/v1.0/VEP_plugin/Gwava.pm

Thank  you!

**Comment by at7** [comment]
Hello,
I just tried to install the plugin with the VEP installer and it works for me. I wonder if the FTP site could have been unavailable when you tried to download the plugin? Also, could there be any restrictions on your system that prevent downloading from an FTP site? If both doesn't explain why the installation failed, could you please try installing the Gwava plugin manually into the correct folder?

Kind regards,
Anja

**Comment by ariza-droid** [comment]
Dear Anja,

Thank you for your reply. I gave it up without knowing what actually causes this!

Bw,
Anca
