### ISSUE TITLE
Lack of CHECKSUMS file on FTP server

### ISSUE THREAD

**Issue by znikasz** [Ensembl/ensembl-vep#932]
## Describe the issue
It's not really VEP bug, but I have no idea where to submit it. There is no ftp://ftp.ensembl.org:21/pub/release-103/variation/indexed_vep_cache/CHECKSUMS file, so `INSTALL.pl ` fails:

### System
- VEP version: 103
- VEP Cache version: 103

### Full VEP command line
```
./INSTALL.pl --AUTO cf --SPECIES homo_sapiens_merged --ASSEMBLY GRCh38

```

### Full error message
```
 - getting list of available cache files
NB: Remember to use --merged when running the VEP with this cache!
 - downloading ftp://ftp.ensembl.org/pub/release-103/variation/indexed_vep_cache/homo_sapiens_merged_vep_103_GRCh38.tar.gz
curl failed (550), trying to fetch using LWP::Simple
LWP::Simple failed (404), trying to fetch using HTTP::Tiny
Use of uninitialized value in numeric eq (==) at /usr/share/perl/5.26/HTTP/Tiny.pm line 606.
Use of uninitialized value in numeric eq (==) at /usr/share/perl/5.26/HTTP/Tiny.pm line 606.
ERROR: Failed last resort of using HTTP::Tiny to download ftp://ftp.ensembl.org:21/pub/release-103/variation/indexed_vep_cache/CHECKSUMS

```

**Comment by aparton** [comment]
Hi @znikasz,

Thank you for bringing this to our attention. This issue should now be resolved.

Kind Regards,
Andrew

**Comment by amizeranschi** [comment]
Hello @aparton,

I'm getting a similar error when trying to install a Bos Taurus cache for UMD3.1 (Ensembl version 94):

```

 - getting list of available cache files
 - downloading ftp://ftp.ensembl.org/pub/release-94/variation/indexed_vep_cache/bos_taurus_vep_94_UMD3.1.tar.gz
curl failed (550), trying to fetch using LWP::Simple
Use of uninitialized value in numeric eq (==) at /home/ubuntu/tools-python3/anaconda/lib/perl5/core_perl/HTTP/Tiny.pm line 615.
Use of uninitialized value in numeric eq (==) at /home/ubuntu/tools-python3/anaconda/lib/perl5/core_perl/HTTP/Tiny.pm line 615.
ERROR: Failed last resort of using HTTP::Tiny to download ftp://ftp.ensembl.org:21/pub/release-94/variation/indexed_vep_cache/CHECKSUMS
```

**Comment by jamie-m-a** [comment]
Hi @amizeranschi 

Sorry to hear you're having a problem with that download, we'll take a look at that and get back to you. I'll reopen this issue in the meantime.

**Comment by amizeranschi** [comment]
@jamie-m-a 

Thanks for looking into this! My guess is that you guys just need to create the file ftp.ensembl.org/pub/release-94/variation/indexed_vep_cache/CHECKSUMS, for the Ensembl 94 version. 

I know that's a bit old, now, but it's the latest that'll get me my Bos Taurus UMD3.1 genome, so there's that...

**Comment by amizeranschi** [comment]
@jamie-m-a great, thanks for looking into this!

**Comment by jamie-m-a** [comment]
Hi @amizeranschi 

Yes, as you surmised, we just need to generate the missing CHECKSUMS. I've been in contact with the people responsible for this and I'll update on here once the CHEKSUMS have been created.

**Comment by jamie-m-a** [comment]
Hi @amizeranschi 

The CHECKSUMS for e94 have been generated. Can you try downloading the Bos taurus cache again and let me know how it goes?

**Comment by jamie-m-a** [comment]
Hi @amizeranschi 

That's great to hear, I'll close this ticket off now, but do feel free to reopen or raise a new ticket if you have any further issues.

**Comment by Firingam** [comment]
Hi,
I have a similar issue for homo sapiens
Below, full text error
`
NB: Remember to use --merged when running the VEP with this cache!
 - downloading https://ftp.ensembl.org/pub/release-108/variation/indexed_vep_cache/homo_sapiens_merged_vep_108_GRCh37.tar.gz
Unable to close datastream at INSTALL.pl line 1277. # Also this point is weird
 - unpacking homo_sapiens_merged_vep_108_GRCh37.tar.gz
 - converting cache, this may take some time but will allow VEP to look up variants and frequency data much faster
 - use CTRL-C to cancel if you do not wish to convert this cache now (you may run convert_cache.pl later)
2022-12-29 20:45:48 - Processing homo_sapiens_merged
2022-12-29 20:45:48 - Processing version 108_GRCh37
2022-12-29 20:45:48 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this
2022-12-29 20:45:48 - No unprocessed types remaining, skipping
2022-12-29 20:45:48 - All done!
NB: Remember to use --merged when running the VEP with this cache!
 - downloading https://ftp.ensembl.org/pub/release-108/variation/indexed_vep_cache/homo_sapiens_merged_vep_108_GRCh38.tar.gz
ERROR: checksum for /root/.vep/tmp/homo_sapiens_merged_vep_108_GRCh38.tar.gz doesn't match checksum in CHECKSUMS file on FTP site`

**Comment by amizeranschi** [comment]
Hey @Firingam, I'm not with the Ensembl team myself, but out of curiosity, were you trying to simultaneously install caches for both GRCh37 and GRCh38? 

What is your usage scenario? And which command are you using to set these up?

Regardless, it seems really odd that GRCh37 would work and GRCh38 would error out. Hope it's as easy a fix for you at it was for me a few months ago.
