### ISSUE TITLE
problems with Bio::DB::HTS::Tabix

### ISSUE THREAD

**Issue by Martaprf** [Ensembl/ensembl-vep#935]
## Describe the issue
I had an error when I try use dbSNP plugin:
MSG: ERROR: Cannot use format gff without Bio::DB::HTS::Tabix module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /home/mferreira/programs/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:162
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /home/mferreira/programs/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:228
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/mferreira/programs/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:93
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/mferreira/programs/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /home/mferreira/programs/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:132
STACK Bio::EnsEMBL::VEP::Runner::run /home/mferreira/programs/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:203
STACK toplevel /home/mferreira/programs/ensembl-vep/vep:229
Date (localtime)    = Wed Feb 17 16:47:30 2021
Ensembl API version = 102

I already try some suggestions in other issues, but I cannot solve this problem, can you help me?

thanks

**Comment by aparton** [comment]
Hi @Martaprf,

Happy to help. Could you please:
- Check that the Bio::DB::HTS::Tabix module is located in the ensembl-vep directory at: /ensembl-vep/Bio/DB/HTS/Tabix.pm
- Check that your ensembl-vep folder is included within your PERL5LIB. If not, you can add it with:
`export PERL5LIB=${PERL5LIB}:ENSEMBL-VEP_PATH`
- Rerun your initial command, and send me the output if it's still not working correctly? Additionally, could you please tell me which OS and Perl version you're using?

Kind Regards,
Andrew

**Comment by Martaprf** [comment]
Hi @aparton 

Thanks for your attention, but I continue with the same error!!!
I already add the path of ensembl to the perlib and nothing solve my issue:

> $ echo $PERL5LIB
> /home/mferreira/perl5/lib/perl5:/home/mferreira/programs/ensembl-vep/

My OS is Ubuntu 18.04.5 LTS and my perl version is perl 5, version 26, subversion 1 (v5.26.1),

I don´t know what I made wrong.

Thanks,
Marta

**Comment by aparton** [comment]
Hi Marta,

Could you please run the command `perl -e "use Bio::DB::HTS::Tabix"` and let me know the output?

Kind Regards,
Andrew

**Comment by Martaprf** [comment]
Hi,
I run the command: perl -e "use Bio::DB::HTS::Tabix"

> Can't locate Bio/DB/HTS/Tabix.pm in @INC (you may need to install the Bio::DB::HTS::Tabix module) (@INC contains: /home/mferreira/perl5/lib/perl5/5.26.1/x86_64-linux-gnu-thread-multi /home/mferreira/perl5/lib/perl5/5.26.1 /home/mferreira/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/mferreira/perl5/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /home/mferreira/perl5/lib/perl5/5.26.0 /home/mferreira/perl5/lib/perl5/5.26.0/x86_64-linux-gnu-thread-multi /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at -e line 1.
> BEGIN failed--compilation aborted at -e line 1.

**Comment by aparton** [comment]
Hi @Martaprf,

Sorry for the delay in getting back to you. The ensembl-vep directory is not included within @INC in the above error message, which I suspect is causing your issue. Could you please run:

`export PERL5LIB=${PERL5LIB}:/home/mferreira/programs/ensembl-vep/ && perl -e 'use Bio::DB::HTS::Tabix'`

and let me know the output?

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew

**Comment by aminhaghparast** [comment]
Hi. I tried with this command :
export PERL5LIB=${PERL5LIB}:/home/mferreira/programs/ensembl-vep/ && perl -e 'use Bio::DB::HTS::Tabix'
and received this one 
Can't locate Bio/DB/HTS/Tabix.pm in @INC (you may need to install the Bio::DB::HTS::Tabix module) (@INC contains: /home/main/perl5/lib/perl5/5.34.0/x86_64-linux-gnu-thread-multi /home/main/perl5/lib/perl5/5.34.0 /home/main/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/main/perl5/lib/perl5 /home/mferreira/programs/ensembl-vep/ /home/mferreira/programs/ensembl-vep/ /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at -e line 1.

could you plz explain why this happens?

**Comment by nuno-agostinho** [comment]
Hey @aminhaghparast,

Can you confirm in which folder you have VEP installed? Please export that folder with a command similar to `export PERL5LIB=${PERL5LIB}:/path/to/ensembl-vep/ && perl -e 'use Bio::DB::HTS::Tabix'`.

You can also try running our [VEP Docker image](https://hub.docker.com/r/ensemblorg/ensembl-vep) instead, if you prefer.

Best regards,
Nuno

**Comment by BenayounLaboratory** [comment]
I am having a similar issue - and I don't understand why it is refusing to run:
benayoun$ perl -e 'use Bio::DB::HTS::Tabix'

```
Bio::DB::HTS object version 3.01 does not match $Bio::DB::HTS::VERSION 2.11 at /System/Library/Perl/5.30/darwin-thread-multi-2level/DynaLoader.pm line 214.
Compilation failed in require at /Users/benayoun/Softwares/ensembl-vep/Bio/DB/HTS/Tabix.pm line 22.
BEGIN failed--compilation aborted at /Users/benayoun/Softwares/ensembl-vep/Bio/DB/HTS/Tabix.pm line 22.
Compilation failed in require at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```

Any idea why this is happening?

**Comment by nuno-agostinho** [comment]
Hi @BenayounLaboratory,

Can you check what version of $Bio::DB::HTS you are using? It seems there is an incompatibility between the installed versions (maybe you installed both 3.01 and 2.11?)

If you installed HTS with VEP, I suggest you to check if the `ensembl-vep` path is in your PERL5LIB by running `echo $PERL5LIB`. If it's not, please add it with `export PERL5LIB=${PERL5LIB}:/path/to/ensembl-vep/` and try to run `perl -e 'use Bio::DB::HTS::Tabix'` again.

Thank you.

Best,
Nuno
