### ISSUE TITLE
Unable to close datastream when downloading cache

### ISSUE THREAD

**Issue by Akazhiel** [Ensembl/ensembl-vep#936]
## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 99.2
- VEP Cache version: 99
- Perl version: 5.26.2
- OS: Ubuntu
- tabix installed Yes

### Full VEP command line
```
vep_install -a c -c .vep -s homo_sapiens -y GRCh37 --CACHE_VERSION 99 --CONVERT --NO_BIOPERL --NO_HTSLIB --NO_TEST --NO_UPDATE
```

### Full error message
> Unable to close datastream at /home/jonathan/anaconda3/envs/vep/bin/vep_install line 1263.

I've been getting this error all the times I've tried to install the cache files for version 99.

**Comment by at7** [comment]
Hello,
unfortunately, this looks like a problem in the bioconda code and I would recommend that you contact the developers about the error message. Alternatively, you can install cache files manually by following our instructions [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache).

Kind regards,
Anja

**Comment by Akazhiel** [comment]
It has the same behaviour even if I try running it using the installer from this repository. Exact same command, except replacing `vep_install` for `perl INSTALL.pl`. Only the line at which the error appears differs, but checking the code is the same step at which it fails. In the case of `perl INSTALL.pl` it was at line 1240.

**Comment by at7** [comment]
Thank you for pointing that out. I just ran the command myself and I'm not able to reproduce the error message. I tried to find out more about possible reasons for that message but cannot give you a conclusive answer as to why you see that error message.
Are you still able to install the cache files or does the installation stop at the error message? The installer should try other options for downloading files if the FTP module doesn't work.

**Comment by Akazhiel** [comment]
When the error message comes up, it just seems to retry the installation a couple more times and last time it ended up complaining about this `ERROR: Failed last resort of using HTTP::Tiny to download`. Could it be a firewall problem on my end? Is there any port that is being used specifically that could lead to problems? Because I'm trying to download the cache using a Docker image and it gave the same error, I am using the conda version inside the image but given both versions give the same error the problem has to be something else.

**Comment by at7** [comment]
It is worth checking if your firewall is blocking downloads from FTP sites. Are you able to run the download command manually?: 
curl -O ftp://ftp.ensembl.org/pub/release-99/variation/indexed_vep_cache/homo_sapiens_vep_99_GRCh38.tar.gz

**Comment by Akazhiel** [comment]
Got this error when attempting to manually download `curl: (18) transfer closed with 158992 bytes remaining to read`

**Comment by at7** [comment]
I cannot tell from the error message if the problem is on our side. Could you please let me know if you only have problems downloading from the ftp.ensembl.org site?

**Comment by Akazhiel** [comment]
Hello!
I tried downloading using `curl` but using `http` protocol instead and it also failed. This is the whole error message when the download using `INSTALL.pl` finishes.
```
Unable to close datastream at INSTALL.pl line 1240.
curl failed (000), trying to fetch using LWP::Simple
LWP::Simple failed (500), trying to fetch using HTTP::Tiny
Use of uninitialized value in numeric eq (==) at /home/jonathan/anaconda3/envs/vep/lib/5.26.2/HTTP/Tiny.pm line 606.
Use of uninitialized value in numeric eq (==) at /home/jonathan/anaconda3/envs/vep/lib/5.26.2/HTTP/Tiny.pm line 606.
ERROR: Failed last resort of using HTTP::Tiny to download ftp://ftp.ensembl.org:21/pub/release-103/variation/indexed_vep_cache/homo_sapiens_vep_103_GRCh37.tar.gz
```

I tried downloading a smaller file from the ftp.ensembl.org site as a test given the homo sapiens one takes almost 2 hours to download, and it downloaded without a problem using both my browser and `curl`. I also tried to download some files from another ftp site, in this case the UCSC one and it also downloaded without a problem.

**Comment by at7** [comment]
Thank you for all the additional information. It sounds to me as if the download is interrupted and not resumed again correctly. I searched for a solution and found this [thread](https://stackoverflow.com/questions/19728930/how-to-resume-interrupted-download-automatically-in-curl). It also suggests to use wget. Could you please check if anything from the thread fixes the download?
Thank you.

**Comment by Akazhiel** [comment]
Seems using both `wget` and `curl -L -O` downloads the files without errors. They can also be uncompressed without throwing any error.

**Comment by at7** [comment]
I'm glad the download worked with those options. We will look into incorporating both options into the installer script in the future.
Best wishes,
Anja

**Comment by leowill01** [comment]
I'm having this problem only when trying to download `GRCh38 v106`. It installed `GRCm39 v106` fine:

```bash
alias dvep='docker run -t -i -v $HOME/vep_data:/opt/vep/.vep ensemblorg/ensembl-vep'

dvep \
perl INSTALL.pl \
--AUTO cf \
--SPECIES "homo_sapiens" \
--ASSEMBLY "GRCh38" \
--CONVERT
```

```
 - getting list of available cache files
 - downloading ftp://ftp.ensembl.org/pub/release-106/variation/indexed_vep_cache/homo_sapiens_vep_106_GRCh38.tar.gz
Unable to close datastream at INSTALL.pl line 1240.

```

At this point I guess it restarts the install process because doing an `exa -l ~/vep_data/tmp` shows the download size for `homo_sapiens_vep_106_GRCh38.tar.gz` went from `19G` when I last checked it to `1.7G` now.

`GRCm39` downloaded and installed very quickly, but even just the downloading of `GRCh38` takes a long time, though this could be just because the genome archive `.tar` is much larger (although I'm not sure why it's so much larger than the mouse one)

**Comment by dglemos** [comment]
Hi @leowill01,
The human GRCh38 (homo_sapiens_vep_106_GRCh38.tar.gz) has a size of 14G while mouse GRCm39 (mus_musculus_vep_106_GRCm39.tar.gz) is 1.3G
If the human GRCh38 is taking a long time you could try to download it manually following these instructions: https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache

**Comment by dstephensSD** [comment]
I'm having the same problem as @leowill01.  The download gets to about 19GB and then fails.

**Comment by stevekm** [comment]
I left mine running overnight, it took three hours trying to download `homo_sapiens_merged_vep_109_GRCh37.tar.gz`. Did not realize that it was restarting the download, I thought the installer was simply broken. This is using  `ensembl-vep_release_109.3` in a container.
