### ISSUE TITLE
Valid populations for --freq_pop flag?

### ISSUE THREAD

**Issue by loreseeker** [Ensembl/ensembl-vep#94]
Hello, I have played around a little with frequency filtering flags (ensembl-vep ones, not filter-vep) and noticed a few peculiar things. I used ensembl-vep 90.5, and these are two example command lines:

/opt/ensembl-vep/vep -offline --dir ./87_38 --vcf --check_frequency --freq_freq 0.1 --freq_gt_lt gt --freq_filter exclude --force_overwrite --freq_pop ExAC_AMR --cache_version 87 -i toy.vcf

/opt/ensembl-vep/vep -offline --dir ./90_38 --vcf --check_frequency --freq_freq 0.1 --freq_gt_lt gt --freq_filter include --force_overwrite -no_stats --freq_pop gnomAD_SAS_AF  -i minitest.vcf

1. If setting a filter that no variant will pass, annotation fails unless --no_stats is set. This is the error message:
Use of uninitialized value $_ in concatenation (.) or string at /opt/ensembl-vep/modules/Bio/EnsEMBL/VEP/Stats.pm line 846, <__ANONIO__> line 320.

(This might be intended behaviour, not sure, but it's rather inconvenient if filtering outcome is not known before hand)

2. Strange behaviour regarding populations to filter on. I was just testing things, so I did not check the outcome validity, just whether annotation executes or not. Out of curiosity, I tried all keywords listed on the flag [documentation page](http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html) and played with some gnomAD fields.

When using cache 87, surprisingly, no error was reported for gnomAD_SAS_AF, gnomAD_EAS_AF, gnomAD_AFR_AF, and gnomAD_AMR_AF keywords to --freq_pop, even though gnomAD data is not part of this cache at all. ExAC_Adj keyword from the documentation page fails with:
MSG: ERROR: Invalid population ExAC_Adj specified.

When using cache 90, invalid population was reported for gnomAD_AF, gnomAD_ASJ_AF, gnomAD_FIN_AF, gnomAD_NFE_AF, and gnomAD_OTH_AF (SAS, EAS, AFR, AMR completed). As expected, ExAC, ExAC_Adj, ExAC_FIN, ExAC_NFE, and ExAC_OTH failed (invalid population error), but ExAC_AMR, ExAC_AFR, ExAC_SAS and ExAC_EAS are accepted, even though this cache should have gnomAD, not ExAC data.

Just thought someone might want to take a look at this.

**Comment by willmclaren** [comment]
1. has already been fixed by https://github.com/Ensembl/ensembl-vep/commit/d6fe1cb040430da05127ac2c0cb1bf7553b9cc40; the message is just a warning and won't affect VEP or the output

2. Don't add "_AF" to the population names. You should use "gnomAD" for the global gnomAD population, and e.g. gnomAD_NFE for the sub-pops.

There is a specific issue when selecting ExAC_Adj due to uppercase conversion; a fix for this will appear shortly in release/90.7

Finally, I'd recommend post-filtering your data with `[filter_vep](http://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html)` rather than using `--check_frequency`; it is much more flexible.

**Comment by loreseeker** [comment]
Thank you for your reply. Yes, I'm using filter_vep for this, was just playing with these options in VEP as I haven't noticed them before.

I was more concerned that some seem to silently pass (gnomAD_AMR_AF for example) without an error appearing on an older cache.

**Comment by willmclaren** [comment]
Ah, yes that does indeed fall through the cracks. It doesn't if you remove "_AF" though (i.e. you do get a warning), so I won't treat this as an urgent fix for now.

**Comment by willmclaren** [comment]
Oops, scratch that, it does still slip through. I'll put a proper fix in now.

**Comment by willmclaren** [comment]
Now fixed in release/90.7
