### ISSUE TITLE
ERROR: No valid sample IDs given at /usr/local/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 842

### ISSUE THREAD

**Issue by NessKerkeni** [Ensembl/ensembl-vep#941]
Hi,
I'm trying to run vep:

/usr/local/ensembl-vep/vep -i /home2/karkeni/nk/Echantillon1_AS_snp_indel-recalibrated.vcf --database --fasta /home2/karkeni/nk/hg38.fa --sift b --polyphen b --symbol --hgvs --individual Famille1 --variant_class --gene_phenotype --tab --af --fields Uploaded_variation,Location,Allele,Consequence,VARIANT_CLASS,ZYG,Gene,SYMBOL,GENE_PHENO,HGVSc,HGVSp,SIFT,PolyPhen,AF -o /home2/karkeni/nk/Echantillon1.txt

but i had an error message:

ERROR: No valid sample IDs given at /usr/local/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 842.
	Bio::EnsEMBL::IO::Parser::BaseVCF4::_get_sample_index_list(Bio::EnsEMBL::IO::Parser::VCF4=HASH(0x55e00f1e3a78), ARRAY(0x55e00bc54c20)) called at /usr/local/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 802
	Bio::EnsEMBL::IO::Parser::BaseVCF4::get_raw_samples_info(Bio::EnsEMBL::IO::Parser::VCF4=HASH(0x55e00f1e3a78), ARRAY(0x55e00bc54c20)) called at /usr/local/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 874
	Bio::EnsEMBL::IO::Parser::BaseVCF4::get_samples_info(Bio::EnsEMBL::IO::Parser::VCF4=HASH(0x55e00f1e3a78), ARRAY(0x55e00bc54c20), "GT") called at /usr/local/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 908
	Bio::EnsEMBL::IO::Parser::BaseVCF4::get_samples_genotypes(Bio::EnsEMBL::IO::Parser::VCF4=HASH(0x55e00f1e3a78), ARRAY(0x55e00bc54c20), 0) called at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 539
	Bio::EnsEMBL::VEP::Parser::VCF::create_individual_VariationFeatures(Bio::EnsEMBL::VEP::Parser::VCF=HASH(0x55e00f0066b0), Bio::EnsEMBL::Variation::VariationFeature=HASH(0x55e00f0cdb50), HASH(0x55e00ea4f6d0)) called at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 358
	Bio::EnsEMBL::VEP::Parser::VCF::create_VariationFeatures(Bio::EnsEMBL::VEP::Parser::VCF=HASH(0x55e00f0066b0)) called at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 191
	Bio::EnsEMBL::VEP::Parser::VCF::next(Bio::EnsEMBL::VEP::Parser::VCF=HASH(0x55e00f0066b0)) called at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/InputBuffer.pm line 210
	Bio::EnsEMBL::VEP::InputBuffer::next(Bio::EnsEMBL::VEP::InputBuffer=HASH(0x55e00f0cd760)) called at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 405
	Bio::EnsEMBL::VEP::Runner::_buffer_to_output(Bio::EnsEMBL::VEP::Runner=HASH(0x55e00bc54a70), Bio::EnsEMBL::VEP::InputBuffer=HASH(0x55e00f0cd760), undef) called at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 373
	Bio::EnsEMBL::VEP::Runner::next_output_line(Bio::EnsEMBL::VEP::Runner=HASH(0x55e00bc54a70)) called at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 211
	Bio::EnsEMBL::VEP::Runner::run(Bio::EnsEMBL::VEP::Runner=HASH(0x55e00bc54a70)) called at /usr/local/ensembl-vep/vep line 229

Thanks for your help

**Comment by helensch** [comment]
Hi

The error message "No valid sample IDs" suggests that it is unable to find the sample in the input VCF.

Please could you confirm that you have the sample "Famille1" in the input VCF?

Information on the individual option:
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_individual

Regards
Helen

**Comment by NessKerkeni** [comment]
thanks , 
it works
i wrote `all` in place of Famille1

**Comment by helensch** [comment]
Hi @NessKerkeni 

Thanks for letting me know that it worked.  I am going to close this issue but feel free to create a new issue if you have more questions. 

Regards
Helen
