### ISSUE TITLE
cksum output value different as stated in CHECKSUM

### ISSUE THREAD

**Issue by Jack-Ow** [Ensembl/ensembl-vep#942]
## Describe the issue

I have manually downloaded cache homo_sapiens_merged_vep_101_GRCh38.tar.gz and compare the the checksum value in [CHECKSUMS](http://ftp.ensembl.org/pub/release-101/variation/vep/CHECKSUMS) . The size of 2 files do tally but the 2 checksum values do not seems to tally (See the 2 screenshots). Can I still use this file?

http://ftp.ensembl.org/pub/release-101/variation/vep/homo_sapiens_merged_vep_101_GRCh38.tar.gz

http://ftp.ensembl.org/pub/release-101/variation/vep/CHECKSUM

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.
![image](https://user-images.githubusercontent.com/17189484/109112455-a7801480-7775-11eb-824a-f3a026430c73.png)
checksum stated 
![image](https://user-images.githubusercontent.com/17189484/109112495-bebf0200-7775-11eb-8966-69de37f7a4d5.png)

### System
- VEP version: 101
- VEP Cache version: release 101
- Perl version: v5.30.0
- OS: Ubuntu 20.04.1 LTS
- tabix installed ? Yes

### Full VEP command line
```
./vep -i input.txt -o output.txt ...
```

### Full error message
> Including the warnings, if available

### Data files (if applicable)
They include:
- The input file
- The output file
- The custom file(s)
You can provide a sample of them

**Comment by helensch** [comment]
Hi

The checksums are created using the `sum` utility
`sum homo_sapiens_merged_vep_101_GRCh38.tar.gz`

I have confirmed that this returns the checksum in CHECKSUMS file.

I noticed you are using the  non-indexed cache. For speed we recommend using the indexed cache
For info on caches see: https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html

Regards
Helen

**Comment by Jack-Ow** [comment]
Hi Helen,

The sum utility works. Thanks, I've also download the indexed cache.

Best,
Jack
