### ISSUE TITLE
Cache version flag defaulting to latest

### ISSUE THREAD

**Issue by Akazhiel** [Ensembl/ensembl-vep#943]
## Describe the issue
Cache version flag not having the expected behaviour.

## Additional information
When I'm running VEP version 103 and try to annotate a VCF using the version 102 that I have downloaded, the software still defaults to the version 103. Is this the expected behaviour?

### System
- VEP version: 103
- VEP Cache version: 102
- Perl version: 5.26.2
- OS: Ubuntu
- tabix installed yes

### Full VEP command line
```
./vep -i ~/test_jacquard/output/combined_calls.vcf -o ~/test_jacquard/b.vcf --cache --cache_version 102 --assembly GRCh38 --species homo_sapiens --verbose --format vcf --vcf
```

### Output
```
Possible precedence issue with control flow operator at /home/jonathan/anaconda3/envs/hla2/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
Will only load v103 databases
Species 'homo_sapiens' loaded from database 'homo_sapiens_core_103_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_cdna_103_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_otherfeatures_103_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_rnaseq_103_38'
homo_sapiens_variation_103_38 loaded
homo_sapiens_funcgen_103_38 loaded
No ancestral database found
No ontology database found
ensembl_taxonomy API not found - ignoring ncbi_taxonomy
Use of uninitialized value $ensembl_metadata_db in concatenation (.) or string at /home/jonathan/VEP/ensembl-vep/Bio/EnsEMBL/Registry.pm line 2393.
ensembl_metadata API not found - ignoring 
No production database or adaptor found
```

**Comment by dglemos** [comment]
Hi @Akazhiel,
We don't recommend to use different versions for the API and the cache. With your command, VEP uses the cache version 102 but it still establishes a database connection to fetch some data and by default it's version 103. 
If you want to only use data from the cache without connecting to any database you can run VEP in offline mode with the flag `--offline` (https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#offline).

**Comment by Akazhiel** [comment]
In that case, if I wanted to still annotate using the cache version 102 and without offline mode, should I use VEP version 102?

**Comment by dglemos** [comment]
Yes, we always recommend using the same API and cache(+database) version to avoid any discrepancies.
