### ISSUE TITLE
Do VEP take into account ORF change to predict variant consequences?

### ISSUE THREAD

**Issue by gwendolinelecuyer** [Ensembl/ensembl-vep#944]
Hello,
I'm working with VEP and I was wondering if VEP takes into account ORF change to predict variant consequences?
For exemple, I have 2 variants:
- the first one is an insertion and the consequence is a frameshift
- the second variant is after the frameshift variant, so do the prediction will take into account the frameshift (and so the ORF change) to predict the consequence of this second variant?

Thank you for your help !
Gwendoline L.

**Comment by helensch** [comment]
Hi

VEP treats each input variant independently. 

Haplosaurus (https://www.ensembl.org/info/docs/tools/vep/haplo/index.html)  takes phased genotypes from a VCF and
considers the combined change contributed by all the variant alleles across a transcript.

Regards
Helen

**Comment by gwendolinelecuyer** [comment]
Thank you for your help. I didn't know this tool, I will try it !

Regards
Gwendoline L.

**Comment by helensch** [comment]
Hi @gwendolinelecuyer 

I am going to close this issue now.

If you have any further questions, please feel free to reopen it or create a new issue.

Regards
Helen
