### ISSUE TITLE
Fasta flag not having expected behaviour

### ISSUE THREAD

**Issue by Akazhiel** [Ensembl/ensembl-vep#945]
Hello!

I'm attempting to use the `--fasta` flag to enable the HGVS annotation in offline mode, and I use that flag to point to a directory `--fasta $HOME/.vep/` but when I try running VEP it fails with the following error.

`[E::fai_build3_core] Failed to open the file /home/jonathan/.vep/`

I am running VEP version 102 with the respective cache version.

**Comment by aparton** [comment]
Hi @Akazhiel,

The `--fasta` flag requires to be pointed towards a specific file rather than a directory. If you point towards a `.fa` or `.fa.gz` file then this should resolve your issue.

Kind Regards,
Andrew

**Comment by Akazhiel** [comment]
Thought you could point to a directory like the documentation said, and I've tried some stuff and seems you require the use of a wildcard in the path for it to work. Just in case you want to update the documentation or something.

Now regarding the fasta file, this is more of a processing topic, but if I'm running a pipeline with X fasta file to which I align and call the variants and then want to annotate with VEP, I should use that same X fasta file or a fasta file from ensembl repository?

Best regards,
Jonatan

**Comment by aparton** [comment]
Hi Jonatan,

You can use any FASTA file with VEP, it is not required to only use files taken from Ensembl resources. In your situation, we would recommend using the same fasta file that you used to align and call your variants.

Thank you for letting us know about the necessary wildcard. I'll get the documentation updated.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew
