### ISSUE TITLE
Docker image: vcf file does not exist

### ISSUE THREAD

**Issue by bsmith030465** [Ensembl/ensembl-vep#948]
Hi,

I download the docker image and followed all the instructions on the [ensembl page](http://uswest.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker), including installing all the plugins. However, when I try to annotate a vcf file with vep, I get a 'file not found' error. I give the full path of the input vcf, but it still doesn't seem to find it. Do I specifically need to link the data directory? If so, how do I do this? Thanks!

===========================
| => docker run -t -i -v $HOME/vep_data:/opt/vep/.vep ensemblorg/ensembl-vep ./vep --input_file /Users/bs/Documents/tdata/bams/ensembl-vep/batch_all.v1.95_95.vcf --output_file /Users/bsDocuments/tdata/bams/ensembl-vep/batch_all.v1.95_95.vep.vcf --format vcf --vcf --symbol --terms SO --tsl --hgvs --offline --dir_cache /opt/vep/.vep/

-------------------- EXCEPTION --------------------
MSG: ERROR: File "/Users/bs/Documents/tdata/bams/ensembl-vep/batch_all.v1.95_95.vcf" does not exist

STACK Bio::EnsEMBL::VEP::Parser::file /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm:231
STACK Bio::EnsEMBL::VEP::Parser::new /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm:125
STACK Bio::EnsEMBL::VEP::Runner::get_Parser /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:805
STACK Bio::EnsEMBL::VEP::Runner::get_InputBuffer /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:832
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:140
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:203
STACK toplevel ./vep:232
Date (localtime)    = Fri Feb 26 20:31:54 2021
Ensembl API version = 103

**Comment by dglemos** [comment]
Hi @bsmith030465,
This is the recommended data structure with an example of VEP command: http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker
The input file should be in `$HOME/vep_data`. Could you try running with your input file as the example `--input_file /opt/vep/.vep/input/batch_all.v1.95_95.vep.vcf` and see if VEP can find it there.

**Comment by dglemos** [comment]
I'm going to close this issue. If you have more questions feel free to open a new issue.
Best wishes,
Diana
