### ISSUE TITLE
Force strandness in variants

### ISSUE THREAD

**Issue by Akazhiel** [Ensembl/ensembl-vep#949]
Hello!

I've seen VEP reports if the same variant is present in genes that are located in different strands, and would like to know if there's any way to force strandness of the variants reported? Meaning for each variant, it'll report only the gene affected in strand `+` or strand `-` but not on both.

Best regards,
Jonatan

**Comment by dglemos** [comment]
Hi Jonatan,

VEP reports the affected features on both strands regardless of what strand you've used for your alleles. The strand you input only affects how VEP reads your alleles. 
If you only want the genes affected in a specific strand you could try filtering the strand/gene of your interest after the annotation is done.

**Comment by dglemos** [comment]
I'm going to close this issue. If you have more questions feel free to open a new issue.
Best wishes,
Diana
