### ISSUE TITLE
VEP tool installation 

### ISSUE THREAD

**Issue by shwetanavle** [Ensembl/ensembl-vep#952]
I have installed VEP tool and its running fine but when i am trying to add additional feature i am getting this error 
not ok 1 - use Bio::EnsEMBL::VEP::AnnotationSource::File;
#   Failed test 'use Bio::EnsEMBL::VEP::AnnotationSource::File;'
#   at t/AnnotationSource_File_BigWig.t line 26.
#     Tried to use 'Bio::EnsEMBL::VEP::AnnotationSource::File'.
#     Error:  Can't locate Bio/EnsEMBL/Utils/Exception.pm in @INC (you may need to install the Bio::EnsEMBL::Utils::Exception module) (@INC contains: /home/dell/vep/ensembl-vep/t modules /home/dell/perl5/lib/perl5/5.30.3/x86_64-linux-gnu-thread-multi /home/dell/perl5/lib/perl5/5.30.3 /home/dell/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/dell/perl5/lib/perl5 /home/dell/cpanm/lib/perl5/5.30.3/x86_64-linux-gnu-thread-multi /home/dell/cpanm/lib/perl5/5.30.3 /home/dell/cpanm/lib/perl5/x86_64-linux-gnu-thread-multi /home/dell/cpanm/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.3 /usr/local/share/perl/5.30.3 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /home/dell/perl5/lib/perl5/5.30.2 /home/dell/perl5/lib/perl5/5.30.2/x86_64-linux-gnu-thread-multi /home/dell/perl5/lib/perl5/5.30.0 /home/dell/perl5/lib/perl5/5.30.0/x86_64-linux-gnu-thread-multi /home/dell/cpanm/lib/perl5/5.30.2 /home/dell/cpanm/lib/perl5/5.30.2/x86_64-linux-gnu-thread-multi /home/dell/cpanm/lib/perl5/5.30.0 /home/dell/cpanm/lib/perl5/5.30.0/x86_64-linux-gnu-thread-multi /usr/local/lib/site_perl) at modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 68.
# BEGIN failed--compilation aborted at modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 68.
# Compilation failed in require at t/AnnotationSource_File_BigWig.t line 26.
# BEGIN failed--compilation aborted at t/AnnotationSource_File_BigWig.t line 26.
ok 2 # skip Bio::DB::BigFile module not available
ok 3 # skip Bio::DB::BigFile module not available
ok 4 # skip Bio::DB::BigFile module not available
ok 5 # skip Bio::DB::BigFile module not available
ok 6 # skip Bio::DB::BigFile module not available
ok 7 # skip Bio::DB::BigFile module not available
ok 8 # skip Bio::DB::BigFile module not available
ok 9 # skip Bio::DB::BigFile module not available
ok 10 # skip Bio::DB::BigFile module not available
ok 11 # skip Bio::DB::BigFile module not available
ok 12 # skip Bio::DB::BigFile module not available
ok 13 # skip Bio::DB::BigFile module not available
ok 14 # skip Bio::DB::BigFile module not available
ok 15 # skip Bio::DB::BigFile module not available
1..15
So kindly help me with error

**Comment by dglemos** [comment]
Hi, 

- Can you give an example of a job that doesn't run?
- What OS are you trying to install VEP onto?
- Did you install Bio::DB::BigFile following [these instructions](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#bigfile)?

**Comment by shwetanavle** [comment]
I am using Ubuntu system 
I have downloaded the Bio::DB::BigFile following those instructions and i have checked it is present and I am trying to run this command-"perl -Imodules t/AnnotationSource_File_BigWig.t" to get the additional features. Actually VEP tool is running but when I am trying to download the additional features that time it is giving me this error.

**Comment by shwetanavle** [comment]
I am using Ubuntu system
I have downloaded the Bio::DB::BigFile following those instructions and i have checked it is present and I am trying to run this command-"perl -Imodules t/AnnotationSource_File_BigWig.t" to get the additional features. Actually VEP tool is running but when I am trying to download the additional features that time it is giving me this error.

**Comment by shwetanavle** [comment]
> Hi,
> 
> * Can you give an example of a job that doesn't run?
> * What OS are you trying to install VEP onto?
> * Did you install Bio::DB::BigFile following [these instructions](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#bigfile)?

I am using Ubuntu system
I have downloaded the Bio::DB::BigFile following those instructions and i have checked it is present and I am trying to run this command-"perl -Imodules t/AnnotationSource_File_BigWig.t" to get the additional features. Actually VEP tool is running but when I am trying to download the additional features that time it is giving me this error.

**Comment by dglemos** [comment]
Could you please add the ensembl-vep directory to your PERL5LIB environment variable, with something like:
```
echo 'export PERL5LIB=${PERL5LIB}:/home/dell/vep/ensembl-vep' >> ~/.bashrc
source ~/.bashrc
```
And try running the installer again with `perl INSTALL.pl`

Which version of perl do you have installed?

**Comment by shwetanavle** [comment]
> Could you please add the ensembl-vep directory to your PERL5LIB environment variable, with something like:
> 
> ```
> echo 'export PERL5LIB=${PERL5LIB}:/home/dell/vep/ensembl-vep' >> ~/.bashrc
> source ~/.bashrc
> ```
> 
> And try running the installer again with `perl INSTALL.pl`
> 
> Which version of perl do you have installed?

I have the updated version of perl i.e. 5.10

**Comment by dglemos** [comment]
The tests look alright. You can try running VEP with one of your input files.

**Comment by shwetanavle** [comment]
Thank you so much for your help
