### ISSUE TITLE
CNVs spanning multiple protein_coding genes annotated as intergenic_variant

### ISSUE THREAD

**Issue by seru71** [Ensembl/ensembl-vep#954]
## Describe the issue
After upgrade from VEP 97.4 to 102.0 we noticed that large structural variants spanning multiple protein-coding genes are no longer annotated as `coding_sequence_variant,intron_variant,...` but only `intergenic_variant`. Also information about affected EXONs and INTRONs is missing (when using `--numbers` arg)

## Additional information
Tested this on available docker images and caches and can confirm that we see the same behavior in versions 100.2 and 100.4 (cache 100). I am attaching a VCF with single input variant, and results for versions 102 (100.* was indetical) and 97.4 in gzipped tabular format.

### System
- VEP docker image: ensemblorg/ensembl-vep:release_102.0 vep (the same behavior in release 100.2 and 100.4)

### Full VEP command line
```
docker run --rm -v /tmp:/tmp -v /data:/data -v /mnt:/mnt -v /tmp/ascat_vep_problem:/ascat_vep_problem ensemblorg/ensembl-vep:release_102.0 vep --cache --dir_cache /data/References/vep-cache --cache_version 102 --assembly GRCh37 --offline --no_stats --force_overwrite --max_sv_size 1000000000 -i /ascat_vep_problem/test.vcf.gz -o /ascat_vep_problem/test.vcf.102.0.tsv --format vcf --per_gene --symbol --numbers --canonical --biotype --gene_phenotype
```
(the exact same command was used for testing other image versions)

### Full error message
No warnings

### Data files (if applicable)
They include:
- The input file 
[test.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/6122492/test.vcf.gz)
- The output files
[test.vcf.102.0.tsv.gz](https://github.com/Ensembl/ensembl-vep/files/6122501/test.vcf.102.0.tsv.gz)
[test.vcf.97.4.tsv.gz](https://github.com/Ensembl/ensembl-vep/files/6122500/test.vcf.97.4.tsv.gz)

##### Sample of problematic output

```
$ zgrep "MTOR;" test.vcf.*gz
test.vcf.100.4.tsv.gz:1_8956946_copy_number_variation	1:8956946-18419341	copy_number_variation	ENSG00000198793	ENST00000361445	Transcript	intergenic_variant	-	-	-	-	-	-	IMPACT=MODIFIER;STRAND=-1;SYMBOL=MTOR;SYMBOL_SOURCE=HGNC;HGNC_ID=3942;BIOTYPE=protein_coding;CANONICAL=YES;GENE_PHENO=1;OverlapBP=155973;OverlapPC=100.00
test.vcf.102.0.tsv.gz:1_8956946_copy_number_variation	1:8956946-18419341	copy_number_variation	ENSG00000198793	ENST00000361445	Transcript	intergenic_variant	-	-	-	-	-	-	IMPACT=MODIFIER;STRAND=-1;SYMBOL=MTOR;SYMBOL_SOURCE=HGNC;HGNC_ID=3942;BIOTYPE=protein_coding;CANONICAL=YES;GENE_PHENO=1;OverlapBP=155973;OverlapPC=100.00
test.vcf.97.4.tsv.gz:1_8956946_copy_number_variation	1:8956946-18419341	copy_number_variation	ENSG00000198793	ENST00000361445	Transcript	coding_sequence_variant,5_prime_UTR_variant,3_prime_UTR_variant,intron_variant	-	-	-	-	-	-	IMPACT=MODIFIER;STRAND=-1;SYMBOL=MTOR;SYMBOL_SOURCE=HGNC;HGNC_ID=3942;BIOTYPE=protein_coding;CANONICAL=YES;GENE_PHENO=1;EXON=1-58/58;INTRON=1-57/57;OverlapBP=155973;OverlapPC=100.00

```

**Comment by aparton** [comment]
Hi @seru71,

Thanks for reporting this issue to us. We'll take a closer look and get back to you.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi @seru71,

Thank you for bringing this issue to our attention. Having looked into it further, both the e97 and e102 descriptions of the CNV are incorrect. We're looking into improving the consequence prediction for variants of this type, and these improvements will be included in a future VEP release.

I'll let you know when we have a more concrete timeline of when you can expect these updates.

Kind Regards,
Andrew

**Comment by seru71** [comment]
Hi @aparton,

Thank you for checking this. Could you explain what is wrong with the e97 annotation?

**Comment by aparton** [comment]
Hi @seru71,

Sure. While the consequence list of `coding_sequence_variant,5_prime_UTR_variant,3_prime_UTR_variant,intron_variant` could be used to describe the CNV in your example, it doesn't follow the general rules we use to provide VEP consequences. VEP will provide multiple consequences for a single variant when required, however to avoid providing consequence descriptions that aren't particularly specific then VEP will only choose the variants with the highest impact.

For example, a variant described as a `stop_gained` could also be described as a `coding_sequence_variant`, but we'll only report the `stop_gained` as it is a more specific description.

In your situation, all 4 reported consequences are technically correct, but poor descriptors of the overall situation. A more impactful descriptor such as `transcript_amplification` would be more appropriate in this case.

If you're interested, you can find more information on the consequences we report and their impacts here: https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html

Kind Regards,
Andrew

**Comment by seru71** [comment]
Hi @aparton ,

Thank you for this explanation. It totally makes sense. 

The consequences provided by e97, in contrast to e102, indicated at least that the coding parts of the genes were affected. It also reported intron/exon numbers that were involved (`--numbers`), which was very useful to us. I hope this information could remain even if the consequence changes to `transcript_amplification`.

Looking forward to trying the fixed version.

Best regards,
Paweł

**Comment by aparton** [comment]
Hi @seru71,

Thank you, that's useful feedback. I'll make sure this is taken into account when we look at this issue.

Kind Regards,
Andrew

**Comment by seru71** [comment]
Hi @aparton,
has this issue been resolved?

**Comment by jamie-m-a** [comment]
Hi @seru71 

We have not yet updated VEP to more appropriately report on these multi gene spanning CNVs. This work is very much still on our radar, and I will update on this thread when we have implemented new consequence reporting - thanks for you patience.

**Comment by seru71** [comment]
Thanks for the update

**Comment by josephhalstead** [comment]
I was worried this bug would apply to my pipeline so took a look. Seems replacing the alt allele <CNV> with an explicit <DEL> or <DUP> solves the issue.

**Comment by olaaustine** [comment]
Hi @josephhalstead,
I have been able to recreate it and it solves the issue.
Thank you, 
Ola

**Comment by olaaustine** [comment]
Hi @seru71,
Changing the <CNV> to either <DUP> or <DEL> resolves the issue and it reports the right consequence (transcript_amplification)
I will be closing this ticket now, Please feel free to reopen or open another if you have any other query. 
Thank you, 
Ola.
