### ISSUE TITLE
MANE options do not work with RefSeq cache in VEP 103

### ISSUE THREAD

**Issue by davmlaw** [Ensembl/ensembl-vep#955]
VEP v103 recently added the --mane flags, which populate MANE_SELECT and MANE_PLUS_CLINICAL

These work for Ensembl annotation, but when run with RefSeq cache, they appear in the CSQ header but are always empty.

### System
- VEP version: 103
- VEP Cache version: 103
- Perl version: 5.30.2
- OS: Linux
- tabix installed Y

**Comment by aparton** [comment]
Hi @davmlaw,

Thank you for letting us know about this. I'll speak to the team and see how quickly we can get this functionality added.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi @davmlaw,

Thank you for bringing this issue to our attention. This should now be fixed in v104.

Kind Regards,
Andrew
