### ISSUE TITLE
VEP MASTERMIND AND LOF TOOL SCORE.TXT FILE PLUGIN ISSUE IN LINUX

### ISSUE THREAD

**Issue by shwetanavle** [Ensembl/ensembl-vep#956]
I have been trying to use plugins for my data so i downloaded MASTERMINDGRCh38 for 2021 release 
After downloading the data for mastermind plugin (mastermind_cited_variants_reference-2021.01.02-grch38-vcf.zip.gz) and running the commands mentioned on the website on the third command- ./vep -i variations.vcf --plugin Mastermind,/path/to/mastermind_cited_variants_reference-2021.01.02.GRCh38.vcf.gz

I am getting this error
WARNING: Failed to compile plugin mastermind_cited_variants_reference-2021.01.02-grch38.vcf.gz: Bareword "grch38" not allowed while "strict subs" in use at (eval 47) line 2.
Bareword "gz" not allowed while "strict subs" in use at (eval 47) line 2.
#####################################################################################################
Also for LoF tool the scores.txt file is required for running of the plugin where will i find that file and how to download it.

Please Help
Thank you in advance.

**Comment by aparton** [comment]
Hi @shwetanavle,

Regarding your Mastermind plugin issue, it looks as if there is an issue with your VEP input command - the error message suggests that VEP is trying to compile the data file as if it is the plugin. Perhaps there was some rogue whitespace in your command?

`perl vep -i variations.vcf --plugin Mastermind,mastermind_cited_variants_reference-2021.01.02.GRCh38.vcf.gz`

Regarding the LoFtool, you can find the scores file here: https://github.com/Ensembl/VEP_plugins/blob/release/103/LoFtool_scores.txt

Let me know if there's anything else I can do to help.

Kind Regards,
Andrew

**Comment by shwetanavle** [comment]
After running the command you suggested i am getting this error
WARNING: Failed to instantiate plugin Mastermind: ERROR: Mastermind input file not specified or found!

#####################################################################################################
Regrading the LoFtool scores file i already found that but how should i download it is my concern.. so if you could help me will be grateful..
Thank you in advance

**Comment by aparton** [comment]
Hi @shwetanavle,

You can download the LoFtool_scores file directly with `curl -O https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/103/LoFtool_scores.txt`

Regarding the Mastermind plugin, can you please try adding the absolute path instead of the relative path? That should fix your issue.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew
