### ISSUE TITLE
AF (1000G) is sometimes not populated

### ISSUE THREAD

**Issue by bjhall** [Ensembl/ensembl-vep#957]
## Describe the issue

It appears that the 1000G "AF" field is sometimes not populated even if the subpopulations (eg. AFR_AF, AMR_AF etc) are populated with high frequencies.

## Additional information

This appears to affect both the online and command line version, so it should not be a problem with our installation.

Reproduce by annotating this variant with --af either online or using the command line
`3	38548175	.	T	TCCCTCCTTTTTCCTACTCTCTTCTC	.`

That will give me

AF | AFR_AF | AMR_AF | EAS_AF | EUR_AF | SAS_AF
-- | -- | -- | -- | -- | --
. | 0.9977 | 0.9899 | 0.999 | 0.9791 | 0.998

It should have a value for AF as well!

### System
- VEP version: 103
- VEP Cache version: 103

**Comment by aparton** [comment]
Hi,

Thank you for reporting this issue. This is an issue that we've seen before and are currently investigating a solution. It occurs with multi-allelic variants when the alternate allele requested is not the minor allele.

The AF field in VEP reports the minor allele frequency, i.e. the frequency at which the second most common allele occurs. The colocated variant in your example (rs45592631) is a multi-allelic variant, and the alternate allele provided in the example is not the minor allele. As such, the AF field is empty. However, the 1000 genomes sub populations identify the allele specific population frequency, and they're successfully reported.

Unfortunately, this is an issue that does not have an easy fix for us, so unfortunately I'm unable to put a timeframe on when it is likely to be resolved.

Kind Regards,
Andrew

**Comment by bjhall** [comment]
Thanks for the feedback! It's not an important issues for us (we're not really using the 1000G frequencies anymore), it just caused a test to fail in a downstream software, and I thought I'd be a responsible person and report it. :)

Feel free to close the issue if you are already tracking it elsewhere!

**Comment by ibwoo** [comment]
Hi @aparton,
The behaviour I've encountered seems to be similar enough to append to this issue. I had been relying on the MAX_AF output value to determine allele frequency but the following mutation does not return a MAX_AF value, indeed it returns '-' by all AF metrics. The issue may be that the minor allele is the reference allele, and/or maybe that the frequency is close to 0%?

`chr3:195785236_T>A`

https://www.ncbi.nlm.nih.gov/snp/rs374495657#frequency_tab

In the browser version of VEP, the AF columns are all '-'. However, at least the 'Somatic status' column is 0,1. In my offline installation of VEP v101.0, in VEP output format nearly all of my variants have a somatic value but this mutation does not provide a SOMATIC output. See the following two example mutations from my output: 

`chr3_195785171_T>C	3:195785171	C	ENSG00000145113	ENST00000480843	Transcript	missense_variant,NMD_transcript_variant	6481	6409	2137	T/A	Aca/Gca	rs6805660,COSV62127750	IMPACT=MODERATE;STRAND=-1;SYMBOL=MUC4;SYMBOL_SOURCE=HGNC;HGNC_ID=HGNC:7514;BIOTYPE=nonsense_mediated_decay;MAX_AF=1;MAX_AF_POPS=gnomAD_AMR,gnomAD_ASJ,gnomAD_OTH;SOMATIC=0,1;PHENO=0,1`

`chr3_195785236_T>A	3:195785236	A	ENSG00000145113	ENST00000463781	Transcript	missense_variant	6456	6344	2115	D/V	gAc/gTc	rs374495657	IMPACT=MODERATE;STRAND=-1;SYMBOL=MUC4;SYMBOL_SOURCE=HGNC;HGNC_ID=HGNC:7514;BIOTYPE=protein_coding`

I hope this helps with your debugging of the issue.

**Comment by aparton** [comment]
Hi @ibwoo,

Thank you for this report. Regarding the differing somatic statuses between web VEP and your local version, this is due to a data difference between Ensembl versions 101 and 103. Updating to VEP 103 should align your web VEP and command line annotations.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew
