### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by yezheng1003** [Ensembl/ensembl-vep#96]
I tried to install the vep cloned here but there always is an install error like:unpacking a file in Bio/tmp named release-1-6-924.zip but the file is too short which is 0 byte.
Then I tried to clone the release-89 then install by 'perl INSTALL.pl' ,but the error still exist.
when I compare my install process with that in the website, I find I can install the API and BioPerl-1.6.1 ahead. Finally I successfully install the vep by this way.
could you fix the problem to install ensembl-vep without installing API and BioPerl-1.6.1 ahead? 
Thank you!

**Comment by willmclaren** [comment]
Can you provide details of the system on which you are attempting to install? We are unable to recreate this issue.

**Comment by yezheng1003** [comment]
Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic x86_64)，is it enough？

**Comment by willmclaren** [comment]
I just ran from a clean install of Ubuntu 14.04 (using a Docker container), and I don't experience the same problem.

I wonder if you have a network issue or firewall that is possibly affecting the download?

It may be that we can switch the installer to attempt using git as alternative to downloading with curl, but this is not something we can switch quickly.

**Comment by yezheng1003** [comment]
Actually,  I have problem linking to github and can not clone directly to the system. Maybe it is the issue and thank you to reply me.
