### ISSUE TITLE
Cannot use format vcf without Bio::DB::HTS::Tabix module installed

### ISSUE THREAD

**Issue by juliethampstead** [Ensembl/ensembl-vep#961]
## Describe the issue
I'm having trouble installing VEP on OS X 11.2.3 (Big Sur). When I run the perl INSTALL.pl from ensembl-vep, I get the following error:

```
./t/Runner.t ......................................... 50/? 
-------------------- EXCEPTION --------------------
MSG: ERROR: Cannot use format gff without Bio::DB::HTS::Tabix module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:162
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:228
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:93
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:132
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:365
STACK toplevel ./t/Runner.t:755
Date (localtime)    = Tue Mar 30 12:22:21 2021
Ensembl API version = 103
---------------------------------------------------
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 73.
```
All other tests pass. I need htslib and Bio::DB::HTS::Tabix to use ClinVar as a custom annotation, and I tried to run this command:

`./vep --cache -i /Users/jh/Dropbox/Penetrance/vcf/file1.vcf -o /Users/jh/Dropbox/Penetrance/vcf_annotated/file2.annotated.vcf --force_overwrite --dir_cache $HOME/.vep/ --assembly GRCh37 --show_ref_allele --symbol --canonical --af_gnomad --plugin LoF,loftee_path:/Users/jh/Resources/loftee,human_ancestor_fa:/Users/jh/Resources/loftee/human_ancestor/human_ancestor.fa.gz,conservation_file:/Users/jh/Resources/loftee/phylocsf/phylocsf_gerp.sql --custom /Users/jh/Resources/ClinVar/clinvar.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNREVSTAT,CLNDN`

unsuccessfully following installation with the following error:

```
-------------------- EXCEPTION --------------------
MSG: ERROR: Cannot use format vcf without Bio::DB::HTS::Tabix module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:162
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:228
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:93
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:132
STACK Bio::EnsEMBL::VEP::Runner::run /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:203
STACK toplevel ./vep:232
Date (localtime)    = Tue Mar 30 12:45:16 2021
Ensembl API version = 103
---------------------------------------------------
```

However, when I look at my /Users/jh/Resources/ensembl-vep/Bio/ folder, I have ~/DB/HTS/Tabix. perl -e Bio::DB::HTS::Tabix finds nothing, which I presume is the issue with VEP at runtime and during installation.

My echo $PERL5LIB is:

```
:/Users/jh/Resources/BioPerl-1.6.924:/Users/jh/Resources/ensembl-vep/Bio:/Users/jh/Resources/loftee/
```

### System
- VEP version: 103
- VEP Cache version: 103
- Perl version: 5.26.2
- OS: OS X 11.2.3
- tabix is installed and in $PATH

**Comment by helensch** [comment]
Hi @juliethampstead 

The VEP installation should install Bio::DB::HTS unless the option --NO_HTSLIB is specified.

Please can I check whether you installed Bio::DB::HTS as part of your VEP installation or whether it was already installed.

The Bio::DB::HTS needs to be in your PERL5LIB environment variable in the environment you are running VEP

If installed as part of VEP,  check that your ensembl-vep folder is included within your PERL5LIB e.g.
export PERL5LIB=${PERL5LIB}:/Users/jh/Resources/ensembl-vep

I noticed you had "Bio" included in your PERL5LIB path. /Users/jh/Resources/ensembl-vep/Bio

You mention, you have ~/DB/HTS/tabix. Can you confirm you have a directory
 /Users/jh/Resources/ensembl-vep/Bio/DB/HTS 
 or
 /Users/jh/DB/HTS/tabix

Please could you try running the following commands in the same environemnt  you are running VEP

```
perl -MBio::DB::HTS -e 'print "$Bio::DB::HTS::VERSION\n"'

perldoc -l Bio::DB::HTS
```

 Regards
 Helen

**Comment by juliethampstead** [comment]
Hey, thanks for getting back to me!

I forgot to mention, but I installed VEP as standard (perl INSTALL.pl), and did not use the --NO_HTSLIB or --NO_TEST flags. If I install VEP with --NO_HTSLIB, I get a working VEP install but without the ability to use custom ClinVar annotations from vcf (as this requires Bio::DB::HTS).

During the VEP install, I got no errors in terms of Bio::DB::HTS installing unsuccessfully, and the physical directory structure /Users/jh/Resources/ensembl-vep/Bio/DB/HTS and /Users/jh/Resources/ensembl-vep/Bio/DB/HTS/Tabix (capital T) both exist.

 However:

`perl -MBio::DB::HTS -e 'print "$Bio::DB::HTS::VERSION\n"'`

Returns:

```
Can't locate Bio/DB/HTS.pm in @INC (you may need to install the Bio::DB::HTS module) (@INC contains: /Users/jh/Resources/BioPerl-1.6.924 /Users/jh/Resources/ensembl-vep/Bio /Users/jh/Resources/loftee/ /Users/jh/perl5/perlbrew/perls/5.26.2/lib/site_perl/5.26.2/darwin-thread-multi-2level /Users/jh/perl5/perlbrew/perls/5.26.2/lib/site_perl/5.26.2 /Users/jh/perl5/perlbrew/perls/5.26.2/lib/5.26.2/darwin-thread-multi-2level /Users/jh/perl5/perlbrew/perls/5.26.2/lib/5.26.2).
BEGIN failed--compilation aborted.
```
On a positive note, the command:

`perldoc -l Bio::DB::HTS`

Returns:

`/Users/jh/Resources/ensembl-vep/Bio/DB/HTS.pm`

I have added `export PERL5LIB=${PERL5LIB}:/Users/jh/Resources/ensembl-vep` to my ~/.bash_profile and sourced it, and still get the same error I had before when I attempt to run ClinVar annotations from their vcf.

**Comment by juliethampstead** [comment]
Hi Helen,

I've tried this, my `echo $PERL5LIB` is now `:/Users/jh/Resources/BioPerl-1.6.924:/Users/jh/Resources/ensembl-vep:/Users/jh/Resources/loftee/`

I reran `perl -MBio::DB::HTS -e 'print "$Bio::DB::HTS::VERSION\n"'` and got the following:

```
Can't find 'boot_Bio__DB__HTS' symbol in /Users/jh/Resources/BioPerl-1.6.924/libHTS.dylib
 at -e line 0.
Compilation failed in require.
BEGIN failed--compilation aborted.
```

However, using `perldoc -l Bio::DB::HTS` I find only `/Users/jh/Resources/ensembl-vep/Bio/DB/HTS.pm`.

**Comment by juliethampstead** [comment]
As an update, if I change the order in which I export to PERL5LIB in my ~/.bash_profile, as below:

```
source $HOME/perl5/perlbrew/etc/bashrc
export PERL5LIB=${PERL5LIB}:/Users/jh/Resources/ensembl-vep
export PERL5LIB=${PERL5LIB}:/Users/jh/Resources/BioPerl-1.6.924
export PERL5LIB=${PERL5LIB}:/Users/jh/Resources/loftee/
```

(Previously, BioPerl-1.6.924 was exported first). When I run `perl -MBio::DB::HTS -e 'print "$Bio::DB::HTS::VERSION\n"'` I now get `2.11`, but I still get the same error when I attempt to run VEP:

```
./vep --cache -i /Users/jh/Dropbox/Penetrance/vcf/file1.vcf -o /Users/jh/Dropbox/Penetrance/vcf_annotated/file2.annotated.vcf --force_overwrite --dir_cache $HOME/.vep/ --assembly GRCh37 --show_ref_allele --symbol --canonical --af_gnomad --plugin LoF,loftee_path:/Users/jh/Resources/loftee,human_ancestor_fa:/Users/jh/Resources/loftee/human_ancestor/human_ancestor.fa.gz,conservation_file:/Users/jh/Resources/loftee/phylocsf/phylocsf_gerp.sql --custom /Users/jh/Resources/ClinVar/clinvar.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNREVSTAT,CLNDN
Smartmatch is experimental at /Users/jh/Resources/loftee/de_novo_donor.pl line 175.
Smartmatch is experimental at /Users/jh/Resources/loftee/de_novo_donor.pl line 214.
Smartmatch is experimental at /Users/jh/Resources/loftee/splice_site_scan.pl line 191.
Smartmatch is experimental at /Users/jh/Resources/loftee/splice_site_scan.pl line 194.
Smartmatch is experimental at /Users/jh/Resources/loftee/splice_site_scan.pl line 238.
Smartmatch is experimental at /Users/jh/Resources/loftee/splice_site_scan.pl line 241.

-------------------- EXCEPTION --------------------
MSG: ERROR: Cannot use format vcf without Bio::DB::HTS::Tabix module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:162
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:228
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:93
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:132
STACK Bio::EnsEMBL::VEP::Runner::run /Users/jh/Resources/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:203
STACK toplevel ./vep:232
Date (localtime)    = Tue Mar 30 18:03:10 2021
Ensembl API version = 103
---------------------------------------------------
```

**Comment by helensch** [comment]
Hi @juliethampstead 

Please could you let me know if you installed BioPerl manually before installing VEP?

If yes, did you  include the path to BioPerl in your PERL5LIB before installing VEP?

See: https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#macos
Installing BioPerl

Please could you also run
```perl -e 'use Bio::DB::HTS::Tabix; print "Tabix available\n"';```

Regards
Helen

**Comment by juliethampstead** [comment]
> Please could you let me know if you installed BioPerl manually before installing VEP?

Yes, I did!

> If yes, did you include the path to BioPerl in your PERL5LIB before installing VEP?

Yes, I did!

If I run `perl -e 'use Bio::DB::HTS::Tabix; print "Tabix available\n"';`, I get `Tabix available`.

**Comment by aparton** [comment]
Hi @juliethampstead,

We've been able to reproduce this issue when we have multiple version of Bio::DB::HTS installed on a Mac OS machine - one installed via cpan and one installed as part of the VEP installation process.

If you perform a clean install of VEP (by removing the ensembl-vep folder and re-cloning from github/other source) and run with the --NO_HTSLIB flag attached, do you still see this same issue? If you do, can you please send me the output of `perl -e 'use Bio::DB::HTS'` when HTSLib hasn't been installed as part of VEP?

Alternatively (and I understand that this is not ideal), we do have a Docker container that would solve this problem - https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker

Kind Regards,
Andrew

**Comment by kvn95ss** [comment]
Hello!

I was in a similar boat but in my case the issue was with the way perl was set up manually. Eventually settled on creating a conda environment with vep, and it is working quite well. Sure, it doesn't solve the perl related issues but at least the software gets up and running. 

Definitely worth a try.

**Comment by helensch** [comment]
Hi @juliethampstead 

I am going to close this issue now.

If you have any further questions, please feel free to reopen it or create a new issue.

Regards
Helen

**Comment by ncyue2** [comment]
Hi, I also facing the same issue; any possible way to solve this?
thanks

**Comment by nakib103** [comment]
Hi @ncyue2 ,

Thank you for your query.

Can you try installing VEP with the `--NO_HTSLIB` flag attached and see if this resolve this problem.

Best regards,
Nakib

**Comment by ncyue2** [comment]
hi, I did re-install with the --NO_HTSLIB flag, but the same error occur

**Comment by nakib103** [comment]
Can you check the following - 
- Check that the Bio::DB::HTS::Tabix module is located in the ensembl-vep directory at: /ensembl-vep/Bio/DB/HTS/[Tabix.pm](http://tabix.pm/)
- Check that your ensembl-vep folder is included within your PERL5LIB (`echo $PERL5LIB`). If not, you can add it with - 
`export PERL5LIB=${PERL5LIB}:<path of the ensembl-vep dir>`

Re-run the command and see if the error still persists.

**Comment by ncyue2** [comment]
yes! the Bio::DB::HTS::Tabix module is located in the ensembl-vep directory:
`./ensembl-vep/Bio/DB/HTS/Tabix.pm`

and here's a screen shot of `echo $PERL5LIB` which also shows my ensembl-vep folder is included within the PERL5LIB
<img width="573" alt="image" src="https://user-images.githubusercontent.com/123299170/220221857-b7c48199-b02c-4615-bc7e-040a1925162a.png">

but the error still occurs..

**Comment by nakib103** [comment]
Hi @ncyue2,

Thanks for verifying. One way this error could happen if you have multiple `Bio::DB::HTS` module installed in your machine. Have you tried a clean install of VEP by removing the ensembl-vep folder and re-cloning it and then install with --NO_HTSLIB and see if that solves the problem?

Or, you could look into using VEP using the docker containers which would resolve this issue - https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker

**Comment by ncyue2** [comment]
let me try with the docker container, thank you!
