### ISSUE TITLE
Error : No valid sample IDs given ...

### ISSUE THREAD

**Issue by NessKerkeni** [Ensembl/ensembl-vep#962]
i tried to use vep : 

`
/usr/local/ensembl-vep/vep` -i input_filtred.vcf --database  --fasta hg38.fa --variant_class --sift b --polyphen b --symbol --hgvs --gene_phenotype --regulatory --individual --show_ref_allele --hgvsg --ccds --uniprot --domains --xref_refseq --af --tab --fields Uploaded_variation,Location,REF_ALLELE,Allele,Consequence,VARIANT_CLASS,ZYG,Gene,SYMBOL,GENE_PHENO,EXON,INTRON,RefSeq,CCDS,HGVSg,HGVSc,HGVSp,DOMAINS,SWISSPROT,TREMBL,UNIPARC,MOTIF_NAME,MOTIF_POS,HIGH_INF_POS,MOTIF_SCORE_CHANGE,SIFT,PolyPhen,AF  -o output_vep_variant_effect.txt
`

but i got this error : 
ERROR: No valid sample IDs given at /usr/local/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 842.
	Bio::EnsEMBL::IO::Parser::BaseVCF4::_get_sample_index_list(Bio::EnsEMBL::IO::Parser::VCF4=HASH(0x55b5225ebb70), ARRAY(0x55b51ed6d1f8)) called at /usr/local/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 802
	Bio::EnsEMBL::IO::Parser::BaseVCF4::get_raw_samples_info(Bio::EnsEMBL::IO::Parser::VCF4=HASH(0x55b5225ebb70), ARRAY(0x55b51ed6d1f8)) called at /usr/local/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 874
	Bio::EnsEMBL::IO::Parser::BaseVCF4::get_samples_info(Bio::EnsEMBL::IO::Parser::VCF4=HASH(0x55b5225ebb70), ARRAY(0x55b51ed6d1f8), "GT") called at /usr/local/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 908
	Bio::EnsEMBL::IO::Parser::BaseVCF4::get_samples_genotypes(Bio::EnsEMBL::IO::Parser::VCF4=HASH(0x55b5225ebb70), ARRAY(0x55b51ed6d1f8), 0) called at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 539
	Bio::EnsEMBL::VEP::Parser::VCF::create_individual_VariationFeatures(Bio::EnsEMBL::VEP::Parser::VCF=HASH(0x55b5222b5718), Bio::EnsEMBL::Variation::VariationFeature=HASH(0x55b5224aab50), HASH(0x55b521e58440)) called at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 358
	Bio::EnsEMBL::VEP::Parser::VCF::create_VariationFeatures(Bio::EnsEMBL::VEP::Parser::VCF=HASH(0x55b5222b5718)) called at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 191
	Bio::EnsEMBL::VEP::Parser::VCF::next(Bio::EnsEMBL::VEP::Parser::VCF=HASH(0x55b5222b5718)) called at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/InputBuffer.pm line 210
	Bio::EnsEMBL::VEP::InputBuffer::next(Bio::EnsEMBL::VEP::InputBuffer=HASH(0x55b522570d58)) called at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 405
	Bio::EnsEMBL::VEP::Runner::_buffer_to_output(Bio::EnsEMBL::VEP::Runner=HASH(0x55b51f05c008), Bio::EnsEMBL::VEP::InputBuffer=HASH(0x55b522570d58), undef) called at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 373
	Bio::EnsEMBL::VEP::Runner::next_output_line(Bio::EnsEMBL::VEP::Runner=HASH(0x55b51f05c008)) called at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 211
	Bio::EnsEMBL::VEP::Runner::run(Bio::EnsEMBL::VEP::Runner=HASH(0x55b51f05c008)) called at /usr/local/ensembl-vep/vep line 229

**Comment by NessKerkeni** [comment]
i found the solution, 
we have to add `all` after `--individual`

`/usr/local/ensembl-vep/vep -i input_filtred.vcf --database --fasta hg38.fa --variant_class --sift b --polyphen b --symbol --hgvs --gene_phenotype --regulatory --individual --show_ref_allele --hgvsg --ccds --uniprot --domains --xref_refseq --af --tab --fields Uploaded_variation,Location,REF_ALLELE,Allele,Consequence,VARIANT_CLASS,ZYG,Gene,SYMBOL,GENE_PHENO,EXON,INTRON,RefSeq,CCDS,HGVSg,HGVSc,HGVSp,DOMAINS,SWISSPROT,TREMBL,UNIPARC,MOTIF_NAME,MOTIF_POS,HIGH_INF_POS,MOTIF_SCORE_CHANGE,SIFT,PolyPhen,AF -o output_vep_variant_effect.txt`

**Comment by helensch** [comment]
Hi @NessKerkeni 

Thank you for letting us know you were able to find a solution.

Information on the individual option:
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_individual

I assume this is linked to #941. I am going to close this issue but feel free to create a new issue if you have more questions.

Regards
Helen
