### ISSUE TITLE
GEMINI ISSUE  

### ISSUE THREAD

**Issue by shwetanavle** [Ensembl/ensembl-vep#967]

**Comment by aparton** [comment]
Hi @shwetanavle,

Unfortunately this looks like an issue with Gemini directly rather than with VEP, so we will be unable to provide support. If you contact Gemini directly then they may be in a better place to assist you.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew
