### ISSUE TITLE
`ERROR: Can't use --most_severe and --biotype together` when not using `--biotype`

### ISSUE THREAD

**Issue by dlaehnemann** [Ensembl/ensembl-vep#968]
I have run the following command with vep version 100 (never mind the piping in and out through bcf, I have just included the info for completeness of the command, most important is row 2):
```
bcftools view results/basic/calls/3_frozen.6-of-16.bcf | \
vep --most_severe --regulatory --vcf_info_field ANN --hgvsg --fork 4 --format vcf --vcf --cache --cache_version 100 --species homo_sapiens --assembly GRCh38 --dir_cache resources/vep/cache --dir_plugins resources/vep/plugins --offline  --output_file STDOUT --stats_file results/basic/calls/3_frozen.6-of-16.stats.html | \
bcftools view -Ob > results/basic/calls/3_frozen.6-of-16.annotated.bcf
```

This gives me the following error:
```
ERROR: Can't use --most_severe and --biotype together
```

However, I am not using the `--biotype` flag and from the [documentation of the vep options](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html) I don't see any option that would implicitly set `--biotype`. Also, `--biotype` is listed as off by default, so it really shouldn't be activated implicitly in any way.

Thus, I am assuming that there is some undocumented implicit activation? Because the respective test simply seems to check all the flags against each other:
https://github.com/Ensembl/ensembl-vep/blob/795f4258b370eb7917a9237a5eb5f8d5ae2b1202/modules/Bio/EnsEMBL/VEP/Config.pm#L658-L665

**Comment by aparton** [comment]
Hi @dlaehnemann,

Thank you for this report. You're correct, `--biotype` is being implicitly set by the `--vcf` flag. As noted, this isn't clear in our documentation, I'll get this updated.

Running without `--vcf` would allow you to use the `--most_severe` option, or if it fits with your analyses then `--pick` could be used to reduce your analyses to one relevant transcript while using `--vcf`.

Kind Regards,
Andrew

**Comment by dlaehnemann** [comment]
Thanks for the swift response! I didn't know about `--pick`, but it looks like a good "canonical" way of picking one annotation, so I'll try with that.

One only loosely related thing: I didn't come across any pointers on where to file bugs in the VEP documentation. Maybe I just didn't see it, but I guess it would be a good idea to have this info somewhere prominent. Three places I definitely went looking and didn't find anything would be:

1. The [VEP FAQ](https://www.ensembl.org/info/docs/tools/vep/vep_faq.html).
2. The [main page of the VEP command line tool docs](https://www.ensembl.org/info/docs/tools/vep/script/index.html). This only gives a mailing list and the Helpdesk, but I would think that a GitHub issue is probably the best way to document bugs, right?
3. As a menu entry under VEP or the VEP command line tool docs (the `in this section` on the top of the left-hand side frame).

**Comment by aparton** [comment]
Hi @dlaehnemann,

Thanks for the suggestion, I'll take a look at adding a link to this page in our FAQs to encourage users to report issues they find.

Kind Regards,
Andrew

**Comment by nakib103** [comment]
`--vcf` cannot be used with `--most_severe` and `--summary`; this changes in doc will appear at Ensembl release e107.

Thank you for reporting.

**Comment by nakib103** [comment]
Hello @Jeremy37,

Documentation have been updated to say - `--vcf cannot be used with --most_severe and --summary;` and can be found in the "**incompatible with**" table - https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_vcf

The standard format of VCF output has been long decided with SnpEff and Annovar and later VAI also adopted the format. This standard implies that default VCF output to include the biotype. See here in the doc to check the default fields for VCF format - 
https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#vcfout

You can actually achieve the output `--most_severe`  by using `--pick`. You can use `--pick_order rank` with `--pick` to get the most sever consequence. 

Let me know if you need any more help.

Best regards,
Nakib

**Comment by Jeremy37** [comment]
That's very helpful, thanks!

**Comment by Stikus** [comment]
@nakib103 Can you update this part of documentation too:

- https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_summary
- https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_most_severe

and add incompatibility with `--vcf`?

**Comment by nakib103** [comment]
Hello @Stikus,

Thanks for pointing out those missing options in the "Incompatible with" column. I can find some more options that are missing. We will add a fix for them.

Best regards,
Nakib
