### ISSUE TITLE
HGVS of 5_prime_UTR_variant are not properly annotated for RefSeq transcript

### ISSUE THREAD

**Issue by muwenbo** [Ensembl/ensembl-vep#969]
## Describe the issue
HGVS cannot be annotated to some 5'UTR variants in RefSeq transcripts, although the variants may exist in cache. 
For example,
NM_000518.4(HBB):c.-78A>G
NM_006493.4(CLN5):c.-21G>A
NM_006493.4(CLN5):c.-21delG

"11 5248329 5248329 T/C 1" can be annotated with "Clinical significance" "pathogenic/likely_pathogenic, pathogenic", but not HGVS NM_000518.4(HBB):c.-78A>G as expected. The issue exists in both web-based interface and command-line tool. The issue applies in both GRCh37 and GRCh38. For example, the GRCh38 coordinate "11 5227099 5227099 T/C 1" cannot be properly annotated either.  But it can be correctly annotated for ensemble transcript as ENST00000647020.1:c.-78A>G.

### System
- WEB interface
- VEP version: 103.1 
- VEP Cache version: 103
- GRCh37

### Full VEP command line
```
./vep --af --appris --biotype --buffer_size 500 --canonical --check_existing --distance 5000 --hgvs --mane --numbers --polyphen b --pubmed --refseq --regulatory --sift b --species homo_sapiens --symbol --transcript_version --tsl --cache --input_file [input_data] --output_file [output_file] --port 3337
```

### Data files (if applicable)
Query Variants:
13 77566213 77566213 G/- 1
13 77566213 77566213 G/A 1
11 5248329 5248329 T/C 1

WEB tool results:
http://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Results?tl=3byH1mkwV25ZbEmi-7229992

**Comment by dglemos** [comment]
Hi @muwenbo,
The three RefSeq HGVS variants `c.-78A>G`, `c.-21G>A` and c`.-21delG` seem to be laying in a gap of the sequences. I will have a better look at what is happening and will let you know more. In the meantime, they can be annotated if you provide the Ensembl sequence, e.g. ENST00000647020.1. 

`11 5227099 5227099 T/C 1` (GRCh38) is annotated with clinical significance "pathogenic/likely_pathogenic, pathogenic", [results here](https://www.ensembl.org/Homo_sapiens/Tools/VEP/Ticket?tl=n6AgsskSnbHwEUNu) 
`11 5248329 5248329 T/C 1` (GRCh37) is also "pathogenic/likely_pathogenic, pathogenic", [results here](https://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Ticket?tl=l7EOgLNWOehhkE4a)

**Comment by dglemos** [comment]
Hi @muwenbo,
I'm sorry for not replying earlier.
Running VEP with the latest release 110, returns annotation for your list of variants. 
VEP job: https://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Ticket?tl=QtBnBF1HA06C30DQ
This includes the transcript NM_000518.5 with associated clinical significance `pathogenic/likely_pathogenic, pathogenic`.

Best wishes,
Diana

**Comment by muwenbo** [comment]
Hi, @dglemos ,

Thank you very much for investigating. The problem seems still persist in new version. The behavior in release 110 remains consistent with release 103. While it successfully annotates the gene symbol and ClinVar significance, it does not provide the correct HGVSc and corresponding biotype. For instance, I am expecting HGVSc outputs like HBB c.-18-60A>G or HBB c.-78A>G for "11 5248329 5248329 T/C 1". HBB c.-78A>G is the HGVS nomenclature used by ClinVar. 

![Screen Shot 2023-11-13 at 11 16 51 AM](https://github.com/Ensembl/ensembl-vep/assets/4284092/e7c234df-5764-44d4-bf41-872363bc451e)

Best regards,
Wenbo
