### ISSUE TITLE
How to use latest gnomAD release (v3.1) via custom annotation

### ISSUE THREAD

**Issue by lourdesrosano** [Ensembl/ensembl-vep#971]
Hello,

First of all, thanks a lot for the great effort you are making to provide us which such a fantastic tool!

We are currently using VEP's custom annotation functionality to retrieve frequency data from the gnomAD genomes set. Up until release 3.0, they always provided a single VCF containing all sites across the genome (which we could then directly use in the --custom flag of the VEP command). However, for the latest gnomAD release which was recently made available (v3.1), a single VCF across all sites seems not to be provided anymore, and only per-chromosome VCFs are available.

We assume this decision was made in order to improve efficiency, so we suspect that merging all these (huge) VCFs into a single one again is probably not the best approach. Specially taking into account the extremely large size of this new dataset, we fear that using such a huge VCF for annotation with VEP will be very inefficient (or even crash the tool). On the other hand, having to run the VEP command several times, providing one chromosome file at a time, also seems like an overhead.

Do you have any recommendations or guidelines on how we should use this new release with your tool?
Thank you in advance!

Best,
Lourdes Rosano

**Comment by lourdesrosano** [comment]
Hi Anja,
Thank you for the super fast response. We will change the implementation to what your suggest, thanks a lot! 👍 
Best regards,
Lourdes

**Comment by lourdesrosano** [comment]
Hi again Anja,

Following your suggestion, we have tried out an example VEP call using a separate --custom argument for each per-chromosome VCF file that is provided in gnomAD v3.1. The annotation seems to work, however, the issue now is that we get multiple "duplicated" `gnomADg.v3` fields in the header, one corresponding to each chromosome call. This will make it extremely inconvenient to parse and extract the gnomAD annotations for the variants in the VCF: basically, depending on which chromosome the variant is located at, we would have to look at a different position of the CSQ string.

Is there a way of telling VEP to always use the same CSQ fields/positions for these annotations, regardless of the chromosome call used to annotate? So, having a single `gnomADg.v3` field in the header, instead of 24.

`
##INFO=<ID=gnomAD3g,Number=.,Type=String,Description="/path/to/gnomad.genomes.v3.1.sites.chr1.vcf.bgz (exact)">
##INFO=<ID=gnomAD3g,Number=.,Type=String,Description="/path/to/
gnomad_genomes_v3.1/gnomad.genomes.v3.1.sites.chr2.vcf.bgz (exact)">
...
##INFO=<ID=gnomAD3g,Number=.,Type=String,Description="/path/to/
gnomad_genomes_v3.1/gnomad.genomes.v3.1.sites.chrY.vcf.bgz (exact)">
`

**Comment by at7** [comment]
Hi Lourdes,
this behaviour is far from ideal. I only tested it for the default VEP output and forgot that for VCF output --custom adds a separate field for each data file. The only way to get around this , when using VCF output, is to create one gnomAD v3.1 VCF file for custom annotation.

Best wishes,
Anja

**Comment by alanhoyle** [comment]
We merged the gnomad 3.1 vcfs.  Recompressing on the fly using `bgzip -9 -@ 32` took 32 hours of wall clock, 28 days of CPU time total, and resulted in a 1.8 TiB VCF file.

**Comment by lourdesrosano** [comment]
Thanks a lot for your answers! We have also decided to merge all vcf files into a single one using `bcftools concat` (and this took ~25 hours). The resulting file seems to be working perfectly fine when annotating with VEP, and this step now took around 37 min as opposed to the previous 16 min (with gnomAD release 3.0), which is not bad at all.

Thank you again!
