### ISSUE TITLE
Could not write to the html stats file 

### ISSUE THREAD

**Issue by Liripo** [Ensembl/ensembl-vep#973]
![image](https://user-images.githubusercontent.com/54770415/115532412-551c2980-a2c8-11eb-8f14-d8a881f057b0.png)

I use  the docker version ensemblorg/ensembl-vep:release_103And I get ERROR: Could not write to stats file test_summary.html.

**Comment by at7** [comment]
Hello,
this might be related to a problem with read/write access from the docker container. Is your output file 'test' created correctly? Could you please check our documentation on that issue [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker), there is a section on _Read/Write access from the Docker container_ and see if any of the suggestions solves this problem? Please let me know how it goes.

Best wishes,
Anja

**Comment by Liripo** [comment]
Oh, it is indeed a problem of read and write permissions. I just add -u $UID when running docker.Thank you for your help.

>By the way, I want to ask that the cache list in perl INSTALL.pl seems to only have animals species . I want to comment on where to download the cache file for plants.

**Comment by Liripo** [comment]
Oh, it is indeed a problem of read and write permissions. When I add -u $UID when running docker it can work.Thank you for your help.

>By the way, I want to ask that the cache list in perl INSTALL.pl seems to only have animals species . I want to know on where to download the cache file for plants.

**Comment by at7** [comment]
I'm happy to hear that you were able to resolve the write error.

The VEP installer only points to the FTP site for vertebrate species. You need to download VEP cache files for any other species from the division specific FTP sites. You can find our VEP cache files for plant species here: ftp://ftp.ensemblgenomes.org/pub/plants/release-50/variation/vep/. And [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache) are instructions for setting up cache files manually.

Best wishes,
Anja

**Comment by Liripo** [comment]
Currently this path is [http://ftp.ensemblgenomes.org/vol1/pub/plants/current/variation/vep/](http://ftp.ensemblgenomes.org/vol1/pub/plants/current/variation/vep/)。

**Comment by at7** [comment]
Thank you for pointing this out. We will update our FTP URLs for the next release.
