### ISSUE TITLE
[Feature Request] Write to parquet

### ISSUE THREAD

**Issue by Hoeze** [Ensembl/ensembl-vep#978]
Hi, it would be very useful if VEP would support writing directly to parquet.
- stable output schema
- very efficient binary storage
- can be loaded from every language that supports Arrow

**Comment by at7** [comment]
Hello,
thank you for your feature request. We always welcome feedback and suggestions from our users and this looks indeed like a good solution for dealing with big data. We have documented the request, but we cannot commit to any development plans at this point. I will close this issue. However, if you have any related comments please feel free to reopen it.
Best wishes,
Anja
