### ISSUE TITLE
VEP in Docker, cannot find index for ClinVar database, "--custom" option.

### ISSUE THREAD

**Issue by rhinorus** [Ensembl/ensembl-vep#979]
### Problem description
I'm trying to use VEP docker image to annotate my .vcf file with "--custom" option. (ClinVar database).
Both clinvar.vcf.gz and clinvar.vcf.gz.tbi files downloaded from ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/, according to Ensembl VEP "Custom annotations" guide.

But VEP cannot process file because of Tabix.pm cannot find .tbi index file for clinvar.vcf.gz.

I've tried to build another index using tabix, but it still not work.

### System
- VEP version: 103
- VEP Cache version: 103
- Perl version: 5.26
- OS: Ubuntu 18.04 LTS
- tabix installed.

### Full VEP command line
```
sudo docker run \
    -t -i -v ~/.vep:/opt/vep/.vep \
    ensemblorg/ensembl-vep vep \
    -i test.vcf --o result.vcf --custom clinvar.vcf.gz,ClinVar,vcf,exact,0,CLNSIG
```

### Full error message
> [E::hts_open_format] Failed to open file clinvar.vcf.gz
Couldn't find index for file clinvar.vcf.gz at /usr/local/lib/x86_64-linux-gnu/perl/5.26.1/Bio/DB/HTS/Tabix.pm line 53.

**Comment by aparton** [comment]
Hi @rhinorus,

Thank you for this report. The error message returned here is a little unclear - while VEP is unable to find the index file, it is also unable to find the primary `clinvar.vcf.gz` file. 

Inside the docker container, VEP is contained within the `/opt/vep/src/ensembl-vep` directory, and it's looking for the `clinvar.vcf.gz` file within that directory. I recommend setting an absolute path in your VEP command, and an additional bind mount to the docker command to ensure that VEP knows where the clinvar file is located. Something along the lines of:

`sudo docker run     -t -i -v ~/.vep:/opt/vep/.vep **-v /route/to/clinvardata/:/opt/vep/.clinvar**     ensemblorg/ensembl-vep vep     -i examples/homo_sapiens_GRCh38.vcf --o result.vcf --custom **/opt/vep/.clinvar/**clinvar.vcf.gz,ClinVar,vcf,exact,0,CLNSIG`

I'll take a look at getting the error message updated to something a little clearer. Let me know if there's anything else we can do to help.

Kind Regards,
Andrew

**Comment by rhinorus** [comment]
@aparton, thanks for quick reply!
It works, the problem really was in the incorrectly specified path to the files directory.
