### ISSUE TITLE
VEP missing refseq Transcript for Gene: SON

### ISSUE THREAD

**Issue by namiller2015** [Ensembl/ensembl-vep#980]
## Describe the issue
Vep's refseq transcripts for the gene SON is missing transcript NM_032195. It outputs the following transcripts correctly
NM_001291412.3,NM_138927.4,NR_103797.2. 

As far as I can tell NM_032195 is still valid and should be included. 
https://www.ncbi.nlm.nih.gov/nuccore/NM_032195

Thanks for the help!

### System
- VEP version: latest docker version 
- VEP Cache version: 103

### Full VEP command line
```
./vep --cache --refseq --offline --fasta /opt/vep/.vep/homo_sapiens/103_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --hgvs --symbol -i /opt/vep/.vep/combo_final.vcf -o /opt/vep/.vep/vep_combo_output.vcf
```

### Full error message
> No error message 

### Data files 
Input vcf

##fileformat=VCFv4.0

##CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
21      33576390        .       GA      G       .       .       .

 

Output

21_33576391_A/- 21:33576391     -       6651    NM_001291412.3  Transcript      frameshift_variant      1387    1332    444     R/X     agA/ag  -       IMPACT=HIGH;STRAND=1;SYMBOL=SON;SYMBOL_SOURCE=EntrezGene;GIVEN_REF=A;USED_REF=A;HGVSc=NM_001291412.3:c.1332del;HGVSp=NP_001278341.1:p.Arg444SerfsTer8

21_33576391_A/- 21:33576391     -       29980   NM_017613.4     Transcript      downstream_gene_variant -       -       -       -       -       -       IMPACT=MODIFIER;DISTANCE=1160;STRAND=-1;SYMBOL=DONSON;SYMBOL_SOURCE=EntrezGene;GIVEN_REF=A;USED_REF=A

21_33576391_A/- 21:33576391     -       6651    NM_138927.4     Transcript      frameshift_variant      7303    7248    2416    R/X     agA/ag  -       IMPACT=HIGH;STRAND=1;SYMBOL=SON;SYMBOL_SOURCE=EntrezGene;GIVEN_REF=A;USED_REF=A;HGVSc=NM_138927.4:c.7248del;HGVSp=NP_620305.3:p.Arg2416SerfsTer8

21_33576391_A/- 21:33576391     -       6651    NR_103797.2     Transcript      intron_variant,non_coding_transcript_variant    -       -       -       -       -       -       IMPACT=MODIFIER;STRAND=1;SYMBOL=SON;SYMBOL_SOURCE=EntrezGene;GIVEN_REF=A;USED_REF=A;HGVSc=NR_103797.2:n.7357-27del

**Comment by helensch** [comment]
Hi @namiller2015 

The transcript NM_032195 is a transcript for the gene SON. The variant of interest (21 33576390 . GA G .) does not overlap this transcript so is not reported by VEP.

The sequence alignment between NM_032195.3 and transcript ENST00000300278.8 is given in the link below.

The location of ENST00000300278.8: Chromosome 21: 33,543,064-33,560,667

http://Feb2021.archive.ensembl.org/Homo_sapiens/Transcript/Similarity/Align?db=core;extdb=refseq_mrna;g=ENSG00000159140;r=21:33543064-33560667;sequence=NM_032195.3;t=ENST00000300278

Please let me know if you have any further queries.

Regards
Helen

**Comment by namiller2015** [comment]
Hi Helen,

That is a pretty good explanation! I feel dumb for not double checking that before posting but thanks for taking the time to respond. I'll select a variant for testing that is actually on the transcript this time.

Cheers
