### ISSUE TITLE
Suggestion: Removal of cpan cache in Dockerfile

### ISSUE THREAD

**Issue by sigven** [Ensembl/ensembl-vep#981]
Hi,

I noticed that the VEP Docker image contains a cache that, when deleted, will reduce the overall size of the image with some ~125-130Mb.  I simply added `rm -rf /root/.cpanm` at the end of [this RUN command](https://github.com/Ensembl/ensembl-vep/blob/release/103/docker/Dockerfile#L140).  My understanding is that this cache is not used during any analysis, so might want to include the statement that deletes it.

kind regards,
Sigve

**Comment by helensch** [comment]
Hi @sigven

Thank you for your suggestion to remove the cpan cache. We will review for inclusion in the next update.

Regards
Helen

**Comment by nuno-agostinho** [comment]
Hi @sigven, thanks for your suggestion!

We removed the CPAN cache from the Dockerfile and this should be reflected in our future Docker images.

Feel free to suggest other improvements you may think relevant.  Hope you have a nice day!

Cheers,
Nuno
