### ISSUE TITLE
Merge multiple custom columns with the same header into one column

### ISSUE THREAD

**Issue by alanhoyle** [Ensembl/ensembl-vep#984]
## Describe the issue

When multiple `--custom` annotations are specified that end up with the same names, they should be merged together into unified columns.  Currently, they end up in the CSQ field with repeated columns and repeated values.  

This comes up when a large annotation set is split (e.g. gnomAD 3.1 VCFs are split by chromosome), and we want to annotate across the entire genome.  See Issue #971 for an example.  For large split VCFs like this, a work-around is to merge them together, but takes significant pre-processing and creates an unwieldy multi-terabyte VCF file.  

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: any
- VEP Cache version: any
- Perl version: any
- OS: any
- tabix installed n/a

### Full VEP command line
```
./vep -i input.vcf -o output.vcf --vcf \
--custom /ref/gnomad/3.1/gnomad.genomes.v3.1.sites.chr22.vcf.bgz,gnomAD_3.1,vcf,exact,,AC,AN,AF,AF_popmax \
--custom /ref/gnomad/3.1/gnomad.genomes.v3.1.sites.chrM.vcf.bgz,gnomAD_3.1,vcf,exact,,AC,AN,AF,AF_popmax
```

### Full error message
No errors, but the output VCF's CSQ sections would contain multiple, repeated entries for the following, even though they wouldn't overlap.  

gnomAD_3.1_AC 
gnomAD_3.1_AN
gnomAD_3.1_AF
gnomAD_3.1_AF_popmax

Note the repeats in the `##INFO=<ID=CSQ...` line, the repeated later `##INFO=<ID=gnomAD_3.1*...` lines, and the repeated values in the INFO column in the data lines

like this:  

```
[...]
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|SOURCE|gnomAD_3.1|gnomAD_3.1_AC|gnomAD_3.1_AN|gnomAD_3.1_AF|gnomAD_3.1_AF_popmax|gnomAD_3.1|gnomAD_3.1_AC|gnomAD_3.1_AN|gnomAD_3.1_AF|gnomAD_3.1_AF_popmax">
##INFO=<ID=gnomAD_3.1,Number=.,Type=String,Description="/ref/gnomad/3.1/gnomad.genomes.v3.1.sites.chr22.vcf.bgz (exact)">
##INFO=<ID=gnomAD_3.1_AC,Number=.,Type=String,Description="AC field from /ref/gnomad/3.1/gnomad.genomes.v3.1.sites.chr22.vcf.bgz">
##INFO=<ID=gnomAD_3.1_AN,Number=.,Type=String,Description="AN field from /ref/gnomad/3.1/gnomad.genomes.v3.1.sites.chr22.vcf.bgz">
##INFO=<ID=gnomAD_3.1_AF,Number=.,Type=String,Description="AF field from /ref/gnomad/3.1/gnomad.genomes.v3.1.sites.chr22.vcf.bgz">
##INFO=<ID=gnomAD_3.1_AF_popmax,Number=.,Type=String,Description="AF_popmax field from /ref/gnomad/3.1/gnomad.genomes.v3.1.sites.chr22.vcf.bgz">
##INFO=<ID=gnomAD_3.1,Number=.,Type=String,Description="/ref/gnomad/3.1/gnomad.genomes.v3.1.sites.chrM.vcf.bgz (exact)">
##INFO=<ID=gnomAD_3.1_AC,Number=.,Type=String,Description="AC field from /ref/gnomad/3.1/gnomad.genomes.v3.1.sites.chrM.vcf.bgz">
##INFO=<ID=gnomAD_3.1_AN,Number=.,Type=String,Description="AN field from /ref/gnomad/3.1/gnomad.genomes.v3.1.sites.chrM.vcf.bgz">
##INFO=<ID=gnomAD_3.1_AF,Number=.,Type=String,Description="AF field from /ref/gnomad/3.1/gnomad.genomes.v3.1.sites.chrM.vcf.bgz">
##INFO=<ID=gnomAD_3.1_AF_popmax,Number=.,Type=String,Description="AF_popmax field from /ref/gnomad/3.1/gnomad.genomes.v3.1.sites.chrM.vcf.bgz">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NORMAL    TUMOR
chr22   12345678        .       G       T       100     .       STRELKA2_FILTER=LowEVS;STRELKA2_SomaticEVS=0.89;STRELKA2_QSS_NT=1;;CSQ=T|missense_variant&NMD_transcript_variant|MODERATE|COMT|ENSG00000093010|Transcript|ENST00000207636|nonsense_mediated_decay|3/6||||379|214|72|A/S|Gca/Tca|||1||HGNC|HGNC:2228||chr22:12345678-12345678|1319|152202|0.00866611|0.000482579|0.0224447|0.0491708||0.00000|0.00139624|0.00248139|0.00669216|0.0491708|chr22:19962740-19962740|1319|152202|0.00866611|0.000482579|0.0224447|0.0491708||0.00000|0.00139624|0.00248139|0.00669216|0.0491708

```

### Data files (if applicable)
They include:
- The input file
- The output file
- The custom file(s)
You can provide a sample of them

**Comment by aparton** [comment]
Hi @alanhoyle,

Thank you for bringing this to our attention. I'll have a chat with the team about it next week and I'll be in touch.

Kind Regards,
Andrew

**Comment by diegomscoelho** [comment]
Hi @alanhoyle,

We developed your enhancement. This will be available next release. Any question about this, feel free to comment or reopen this issue.

Regards, @diegomscoelho
