### ISSUE TITLE
DBI module error

### ISSUE THREAD

**Issue by shigej38** [Ensembl/ensembl-vep#985]
## Additional information
```
 cpanm DBI
DBI is up to date. (1.643)

cpanm DBI --reinstall
--> Working on DBI
Fetching http://www.cpan.org/authors/id/T/TI/TIMB/DBI-1.643.tar.gz ... OK
Configuring DBI-1.643 ... OK
Building and testing DBI-1.643 ... OK
Successfully reinstalled DBI-1.643
1 distribution installed

```

### System
- VEP version: 102
- VEP Cache version: 102
- Perl version: v5.26.2
- OS: [ubuntu 18.04 LTS]
- tabix installed Tabix version 1.5

### Full VEP command line
```
./ensembl-vep/vep --i WO449.vcf --o WO449.anno
```

### Full error message
> Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains:

**Comment by shigej38** [comment]
`which -a perl
/home/detagen/miniconda2/bin/perl
/usr/bin/perl`

`perl -e 'use DBI'
Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /home/detagen/perl5/lib/perl5 /home/detagen/miniconda2/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/detagen/miniconda2/lib/site_perl/5.26.2 /home/detagen/miniconda2/lib/5.26.2/x86_64-linux-thread-multi /home/detagen/miniconda2/lib/5.26.2 .) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.`

**Comment by nuno-agostinho** [comment]
Hey @gubrins,

We do not officially support miniconda VEP as it was not created by us.

We would rather point to using our Docker image instead ([instructions here](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker)) or to [manually install VEP](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#download).

Hope this helps.

Best regards,
Nuno
