### ISSUE TITLE
Not all the alts of the multiallelic site are annotated with RSID.

### ISSUE THREAD

**Issue by SWC12** [Ensembl/ensembl-vep#989]
## Describe the issue
Hi,
I will describe an example of the issue here.
From the GWAS catalog (gwas_dbSNPb154, grch38), there is a multiallelic site with rsid, rs3121567 shown below.

![Capture](https://user-images.githubusercontent.com/30064963/118357522-2df60680-b5ad-11eb-82d9-79ad89475fe2.PNG)
chr1    1008088 **rs3121567**       T       **A,C**     .       .       RS=3121567;dbSNPBuildID=103;SSR=0;VC=SNV;GNO;FREQ=1000Genomes:0.1062,.,0.8938|ALSPAC:0.03114,.,0.9689|Estonian:0.02924,.,0.9708|GENOME_DK:0.025,.,0.975|GnomAD:0.1104,.,0.8896|GoNL:0.02305,.,0.977|HapMap:0.2222,.,0.7778|KOREAN:0,0,1|Korea1K:0,.,1|MGP:0.06742,.,0.9326|NorthernSweden:0.02833,.,0.9717|Qatari:0.1713,.,0.8287|SGDP_PRJ:0.04927,.,0.9507|Siberian:0.03571,.,0.9643|TOPMED:0.1207,.,0.8793|TWINSUK:0.03695,.,0.9631|Vietnamese:0,.,1|dbGaP_PopFreq:0.07098,.,0.929;COMMON

**But in my sample VCF, VEP annotates the site with alt, C with rsid, rs3121567. The site with alt, A is not annotated with rsid.**
**This issue occurs for other (not all) multiallelic sites in the sample.**

![Capture](https://user-images.githubusercontent.com/30064963/118362517-65bb7900-b5c2-11eb-8191-34e7f36e4b8f.PNG)
![Capture](https://user-images.githubusercontent.com/30064963/118357817-87126a00-b5ae-11eb-9ebf-73d5c7e163e0.PNG)
chr1    1008088 .       T       A       272.04  PASS    AC=0;AF=0.00;AN=2;CSQ=A|non_coding_transcript_exon_variant|MODIFIER|AL645608.3|ENSG00000231702|Transcript|ENST00000423619|processed_pseudogene|1/1||ENST00000423619.2:n.142A>T||142/154||||||1||-1|||SNV|Clone_based_ensembl_gene||YES|||||||||||||||||||||||||||||||||||||,A|downstream_gene_variant|MODIFIER|AL645608.1|ENSG00000224969|Transcript|ENST00000458555|lncRNA|||||||||||1|3909|-1||1|SNV|Clone_based_ensembl_gene||YES|2||||||||||||||||||||||||||||||||||||,A|intron_variant|MODIFIER|ISG15|ENSG00000187608|Transcript|ENST00000624652|protein_coding||1/2|ENST00000624652.1:c.-107-106T>A||||||||1||1|cds_end_NF||SNV|HGNC|HGNC:4053||3||ENSP00000485313||A0A096LNZ9|||1|||||||||||||||||||||||||||||,A|intron_variant|MODIFIER|ISG15|ENSG00000187608|Transcript|ENST00000624697|protein_coding||1/2|ENST00000624697.4:c.-107-106T>A||||||||1||1|||SNV|HGNC|HGNC:4053||3||ENSP00000485643||A0A096LPJ4|||1|||||||||||||||||||||||||||||     GT:AD:DP:GQ:PL  0/0:0,0:8:0:0,0,0
chr1    1008088 .       T       C       272.04  PASS    AC=2;AF=1.00;AN=2;CSQ=C|non_coding_transcript_exon_variant|MODIFIER|AL645608.3|ENSG00000231702|Transcript|ENST00000423619|processed_pseudogene|1/1||ENST00000423619.2:n.142A>G||142/154|||||**rs3121567**|1||-1|||SNV|Clone_based_ensembl_gene||YES|||||||||||||0.8938|0.6815|0.9352|0.999|0.9602|0.9744||||||||||||||1|||||,C|downstream_gene_variant|MODIFIER|AL645608.1|ENSG00000224969|Transcript|ENST00000458555|lncRNA||||||||||rs3121567|1|3909|-1||1|SNV|Clone_based_ensembl_gene||YES|2||||||||||||0.8938|0.6815|0.9352|0.999|0.9602|0.9744||||||||||||||1|||||,C|intron_variant|MODIFIER|ISG15|ENSG00000187608|Transcript|ENST00000624652|protein_coding||1/2|ENST00000624652.1:c.-107-106T>C|||||||**rs3121567**|1||1|cds_end_NF||SNV|HGNC|HGNC:4053||3||ENSP00000485313||A0A096LNZ9|||1|||||0.8938|0.6815|0.9352|0.999|0.9602|0.9744||||||||||||||1|||||,C|intron_variant|MODIFIER|ISG15|ENSG00000187608|Transcript|ENST00000624697|protein_coding||1/2|ENST00000624697.4:c.-107-106T>C|||||||**rs3121567**|1||1|||SNV|HGNC|HGNC:4053||3||ENSP00000485643||A0A096LPJ4|||1|||||0.8938|0.6815|0.9352|0.999|0.9602|0.9744||||||||||||||1|||||        GT:AD:DP:GQ:PL  1/1:0,8:8:24:286,24,0

## Additional information
I put some examples of the issue here.
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-63296b10-7fff-4988-41bb-4b31a51f2b48"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">gwas_dbSNPb154 VCF entry</span></p><div dir="ltr" style="margin-left:0pt;" align="left">

rsid | chr | pos | ref | alt
-- | -- | -- | -- | --
rs3121567 | chr1 | 1008088 | T | A,C
rs75972122 | chr1 | 1216593 | G | A,C,T
rs1240697 | chr1 | 1441187 | A | C,G,T
rs3765908 | chr1 | 1641275 | A | C,G,T
rs11122155 | chr1 | 6803713 | T | A,C,G

</div></b>
</body>
</html>

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-41eb1b17-7fff-08ec-605f-deb0329af344"><div dir="ltr" style="margin-left:0pt;" align="left">

rsid | ref | alt | Is rsid assigned in annotated VCF by VEP?
-- | -- | -- | --
rs3121567 | T | A | No
rs3121567 | T | C | Yes
rs75972122 | G | A | Yes
rs75972122 | G | C | Yes
rs75972122 | G | T | No
rs1240697 | A | C | No
rs1240697 | A | G | Yes
rs1240697 | A | T | No
rs3765908 | A | C | Yes
rs3765908 | A | G | Yes
rs3765908 | A | T | No
rs11122155 | T | A | Yes
rs11122155 | T | C | Yes
rs11122155 | T | G | No

</div></b>
</body>
</html>

### System
- VEP version: 100.2
- VEP Cache version: 100
- Perl version: v5.26.2
- OS: debian
- tabix installed ? Yes

### Full VEP command line
```
vep --species homo_sapiens --assembly GRCh38 --no_progress --no_stats --buffer_size 5000 --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --vcf --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --dir vep_data_v100 --fasta grch38.fasta --format vcf --input_file sample.vcf --output_file annotated.vcf  --fork 3 --offline --pubmed  --polyphen b  --af  --af_1kg --af_esp --af_gnomad --regulatory
```

**Comment by at7** [comment]
Hi,
[--check_existing](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_check_existing) is allele specific for phenotype associations and for [rs3121567](http://www.ensembl.org/Homo_sapiens/Variation/Phenotype?db=core;r=1:1007588-1008588;v=rs3121567;vdb=variation;vf=2268913) only the C allele has been associated with a phenotype. You can use the [--no_check_alleles](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_no_check_alleles) option to only check for existing variants by coordinates.

Please let me know if you have any further questions.

Best wishes,
Anja

**Comment by SWC12** [comment]
I use the  --no_check_alleles option and all the alts of the multiallelic site are now annotated with RSID.

Thank you Anja.

**Comment by at7** [comment]
Thank you for letting me know.
