### ISSUE TITLE
vep 90 introduces double semi-colon issue

### ISSUE THREAD

**Issue by af8** [Ensembl/ensembl-vep#99]
I am using last version of VEP. Here follows the exact command line for completeness:

```
vep --fork 4 --buffer_size 100000 --offline --no_stats \
--species homo_sapiens --assembly GRCh37 --cache --refseq --exclude_predicted \
--dir ${VEP_CACHE} --fasta /data-ddn/software/ensembl-vep/cache/refs/human_g1k_v37.fasta \
--synonyms ${VEP_CACHE}/homo_sapiens_refseq/90_GRCh37/chr_synonyms.txt \
--use_given_ref \
--variant_class \
--canonical \
--polyphen b --sift b \
--total_length \
--numbers \
--domains \
--hgvs \
--protein \
--symbol \
--ccds \
--biotype \
--check_existing \
--af \
--af_1kg \
--af_gnomad \
--max_af \
--pick_order appris,tsl,ccds,biotype,length,rank \
--pick \
--format vcf \
--input_file ${IVCF} \
--vcf \
--output_file ${OVCF}

```
In my input VCF, I have for instance the following line (already annotated with an other VEP version):

> 6	143074537	.	G	A	0	PASS	CO=GCTxATC;SOMATIC;CSQ=A|stop_gained|HIGH|HIVEP2|3097|Transcript|NM_006734.3|protein_coding|10/10||NM_006734.3:c.7048C>T|NP_006725.3:p.Gln2350Ter|7791/9724|7048/7341|2350/2446|Q/*|Cag/Tag|COSM1723576||-1||1|SNV||||NP_006725.3||||||1|1,A|stop_gained|HIGH|HIVEP2|3097|Transcript|XM_005266956.1|protein_coding|10/10||XM_005266956.1:c.7048C>T|XP_005267013.1:p.Gln2350Ter|7824/9755|7048/7341|2350/2446|Q/*|Cag/Tag|COSM1723576||-1|||SNV||||XP_005267013.1||||||1|1,A|stop_gained|HIGH|HIVEP2|3097|Transcript|XM_005266957.1|protein_coding|10/10||XM_005266957.1:c.7048C>T|XP_005267014.1:p.Gln2350Ter|8103/10034|7048/7341|2350/2446|Q/*|Cag/Tag|COSM1723576||-1|||SNV|||YES|XP_005267014.1||||||1|1	GT:DP:AC	0/0:34:0	0/1:37:12

Now executing the code above, I get:

> 6	143074537	.	G	A	0	PASS	CO=GCTxATC;SOMATIC;;CSQ=A|stop_gained|HIGH|HIVEP2|3097|Transcript|NM_006734.3|protein_coding|10/10||NM_006734.3:c.7048C>T|NP_006725.3:p.Gln2350Ter|7791/9724|7048/7341|2350/2446|Q/*|Cag/Tag|COSM1723576||-1||SNV|EntrezGene||||NP_006725.3|rseq_mrna_match&rseq_ens_match_cds|||||||||||||||||||||||1|1	GT:DP:AC	0/0:34:0	0/1:37:12

It appears a double semi colon just before CSQ field `;;CSQ=`

If I call vep again this double semi colon will raise:

> Use of uninitialized value $key in hash element at /data-ddn/software/ensembl-vep/90.7/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 579, <$__ANONIO__> line 541.

on every line when parsing INFO with `get_info` routine.

Best,
Anthony

**Comment by willmclaren** [comment]
Thanks, fixed in release/90.8

**Comment by af8** [comment]
Just tested with `90.8`

It no more creates the double semi-colon

But it still complains if a double semi-colon exists:

`Use of uninitialized value $key in hash element at /data-ddn/software/ensembl-vep/90.8/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 579, <$__ANONIO__> line 107.`

**Comment by willmclaren** [comment]
That's because a double semi-colon is invalid in VCF (yes, I know VEP introduced it, but obviously that was a bug!)
