### ISSUE TITLE
No HGNC ID with --symbol

### ISSUE THREAD

**Issue by kmurphy902** [Ensembl/ensembl-vep#994]
When running vep locally, I am unable to get the HGNC IDs. I do get back a gene symbole and "EntrezGene" for SYMBOL_SOURCE, but when I look in HGNC, all of the genes that are annotated with EntrezGene also have a corresponding HGNC ID.

`~/Desktop/ensembl-vep/vep -i {input_vcf_path} -o {output_vcf} --cache --refseq --offline --use_given_ref --vcf --hgvs --fasta ~/Desktop/ensembl-vep/grch37_fasta_directory/ --numbers --symbol --fields 'Consequence,Feature,EXON,Gene,HGVSc,HGVSp,SYMBOL,HGNC_ID,SYMBOL_SOURCE' --force_overwrite
`

This is using VEP version 104, Cache version 104 (downloaded from here: http://ftp.ensembl.org/pub/release-104/variation/indexed_vep_cache/), Perl version 5.26.2, on MacOS with tabix installed.

There is no error message, per se; the HGNC_ID field is simply empty in the INFO field of the output vcf. The input is just a standard vcf v4.2 output from GATK/DRAGEN.

Thank you in advance!

**Comment by helensch** [comment]
Hi @kmsteinberg 

Thank you for your query re the HGNC_ID when using the RefSeq cache. This is similar issue to #898.

For RefSeq data we get the gene symbols from EntrezGene. Unfortunately, we do not store the corresponding HGNC IDs in the RefSeq geneset. You can get the HGNC IDs using the merged cache (--merged option)

https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_merged

Please let me know if you have any further queries re the HGNC_ID.

Regards
Helen

**Comment by kmsteinberg** [comment]
Hi Helen,

Thanks for your response. This is not clear at all in the documentation. Are there any future plans to store the corresponding HGNC data with RefSeq?

Thanks,
Karyn

**Comment by jamie-m-a** [comment]
Closing this issue now as no further action is required. Please feel free to reopen if you have any additional questions.
