### ISSUE TITLE
Picking Option Recommendation

### ISSUE THREAD

**Issue by DarioS** [Ensembl/ensembl-vep#996]
`--pick` is recommended as the most suitable option to reduce the number of variant annotations.

> This is the option we anticipate will be of use.

But, DNA is double-stranded and both strands are changed if a SNP occurs. Isn't `--pick_allele_gene` more biologically meaningful when two genes on two strands overlap? I think `--pick` isn't the best recommendation which could be made on the website.

**Comment by helensch** [comment]
Hi @DarioS 

The pick options and examples of output are described here:
https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick_options

The option used will depend on the user's use case. We will update the documentation to make this clearer.

Further examples are given in Ensembl blog post
https://www.ensembl.info/2019/03/22/cool-stuff-the-ensembl-vep-can-do-take-your-pick/

Thank you for your comments and use of VEP.

Regards
Helen

**Comment by helensch** [comment]
Hi @DarioS

I am going to close this issue now.

If you have any further questions, please feel free to reopen it or create a new issue.

Regards
Helen
