### ISSUE TITLE
SIFT does not display predictions

### ISSUE THREAD

**Issue by SergioRLL** [Ensembl/ensembl-vep#997]
Hello,

I'm trying to run VEP to annotate variants for metagenomic data using VCF and GFF files (mainly to see mutation consequences), I am executing it in the following way: 

`/vep -i ${vcf} -o ${output}/variant_effect_output_${bin}.txt --force_overwrite --sift b --variant_class --gff ${gff_files}/{bin}.gff.gz --fasta ${fasta_files}/${bin}.fa`

However, SIFT does not display predictions, and the "Extra" column in the output file only displays information like: `IMPACT=MODIFIER;VARIANT_CLASS=SNV`
How can I solve this?

Thank you,
Sergio

**Comment by dglemos** [comment]
Hi @SergioRLL,
SIFT predictions are fetched from the database or the cache files. You are only using a GFF file as the source which doesn't have the predictions. To display the SIFT scores, you can combine GFF with a cache (--cache) or database (--database) annotation.

**Comment by SergioRLL** [comment]
Hi,

Thanks for the reply. I'm now trying: `/home/srodriguez/srodriguez/ensembl-vep/vep -i ${vcf_files}/bin120.addRG.merged.vcf -o ${output}/variant_effect_output_bin120.txt --force_overwrite --sift b --variant_class --gff ${gff_files}/bin120.gff.gz --fasta ${fasta_files}/bin120.fa --species acidimicrobium_ferrooxidans_dsm_10331_gca_000023265 --cache --cache_version 51 --offline
`
But it displays de error message: `MSG: ERROR: SIFT not available`. I checked the info.txt file from the cache of my species and the line for SIFT is only present as `sift` with no letter after it. Does this mean that I cannot use SIFT with this species?

Thanks again

**Comment by dglemos** [comment]
By the message I suspect SIFT is not supported for your species. Unfortunately, we are not responsible for non-vertebrate species, we only support some of the more popular vertebrates species. 
For non-vertebrates you should check https://ensemblgenomes.org/

**Comment by SergioRLL** [comment]
I see, thanks for the reply.
